import { CountryCode, ExamFamily, TierCode } from "@prisma/client";
import type { ExamPathwayDefinition } from "./types";

/** Ordered chunk C of `EXAM_PATHWAYS` (US NP specialties). */
export const EXAM_PATHWAYS_SEGMENT_C: ExamPathwayDefinition[] = [
  // —— US — NP tracks (never collapse to one generic NP product) ——
  {
    id: "us-np-fnp",
    countrySlug: "us",
    countryCode: CountryCode.US,
    roleTrack: "np",
    examCode: "fnp",
    examFamily: ExamFamily.NP,
    examKey: "NP_FNP",
    displayName: "FNP certification prep",
    shortName: "FNP",
    stripeTier: TierCode.NP,
    contentExamKeys: ["NP", "FNP", "NP-FNP"],
    boardLabel: "ANCC / AANP — Family NP",
    seoTitle: "FNP Exam Prep | AANP Practice Exam & Readiness | NurseNest",
    seoDescription:
      "Family NP: AANP-style practice questions, FNP exam simulator, and readiness predictor framing—advanced practice items scoped to FNP (not interchangeable with other NP specialties).",
    status: "active",
    acquisitionMode: "subscribe",
  },
  {
    id: "us-np-agpcnp",
    countrySlug: "us",
    countryCode: CountryCode.US,
    roleTrack: "np",
    examCode: "agpcnp",
    examFamily: ExamFamily.NP,
    examKey: "NP_AGPCNP",
    displayName: "AGPCNP certification prep",
    shortName: "AGPCNP",
    stripeTier: TierCode.NP,
    contentExamKeys: ["NP", "AGPCNP", "AGNP"],
    boardLabel: "Adult-Gerontology Primary Care NP",
    seoTitle: "AGPCNP Exam Prep | NurseNest",
    seoDescription:
      "Adult-gerontology primary care NP preparation—content and copy are AGPCNP-specific; not shared with FNP or PMHNP hubs.",
    status: "active",
    acquisitionMode: "subscribe",
  },
  {
    id: "us-np-pmhnp",
    countrySlug: "us",
    countryCode: CountryCode.US,
    roleTrack: "np",
    examCode: "pmhnp",
    examFamily: ExamFamily.NP,
    examKey: "NP_PMHNP",
    displayName: "PMHNP certification prep",
    shortName: "PMHNP",
    stripeTier: TierCode.NP,
    contentExamKeys: ["NP", "PMHNP", "PSYCH-NP"],
    boardLabel: "Psychiatric-Mental Health NP",
    seoTitle: "PMHNP Exam Prep | NurseNest",
    seoDescription:
      "Psychiatric-mental health NP track: assessment, psychopharmacology, and therapeutic standards scoped to PMHNP preparation.",
    status: "active",
    acquisitionMode: "subscribe",
  },
  {
    id: "us-np-whnp",
    countrySlug: "us",
    countryCode: CountryCode.US,
    roleTrack: "np",
    examCode: "whnp",
    examFamily: ExamFamily.NP,
    examKey: "NP_WHNP",
    displayName: "WHNP certification prep",
    shortName: "WHNP",
    stripeTier: TierCode.NP,
    contentExamKeys: ["NP", "WHNP", "NP-WHNP", "Womens-Health-NP"],
    boardLabel: "Women’s Health Nurse Practitioner",
    seoTitle: "WHNP Exam Prep | Women’s Health NP | NurseNest",
    seoDescription:
      "Women’s Health NP preparation—reproductive health, pregnancy-related primary care, gynecology, and prevention—on a dedicated pathway with lessons and questions scoped to WHNP boards.",
    status: "active",
    acquisitionMode: "subscribe",
  },
  {
    id: "us-np-pnp-pc",
    countrySlug: "us",
    countryCode: CountryCode.US,
    roleTrack: "np",
    examCode: "pnp-pc",
    examFamily: ExamFamily.NP,
    examKey: "NP_PNP_PC",
    displayName: "PNP-PC certification prep",
    shortName: "PNP-PC",
    stripeTier: TierCode.NP,
    contentExamKeys: ["NP", "PNP-PC", "PNP_PC", "Pediatric-PC-NP"],
    boardLabel: "Pediatric Primary Care NP",
    seoTitle: "PNP-PC Exam Prep | Pediatric Primary Care NP | NurseNest",
    seoDescription:
      "Pediatric primary care NP track: growth, development, common conditions, immunizations, and family-centered management—scoped separately from adult-only AGPCNP preparation.",
    status: "active",
    acquisitionMode: "subscribe",
  },
  // —— Allied (parallel architecture, same route pattern) ——
];
