/**
 * Writes `reports/marketing-hub-review-required-lessons.md` at repo root:
 * catalog lessons where {@link classifyLessonForHub} returns REVIEW_REQUIRED (taxonomy gap / uncategorized hub bucket).
 *
 * Run from repo root: `cd nursenest-core && npx tsx scripts/report-marketing-hub-review-required-lessons.mts`
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { classifyLessonForHub } from "@/lib/lessons/pathway-lesson-body-system-groups";
import { displayCategoryForMarketingHubLesson, getMarketingLessonsHubCatalogLessons } from "@/lib/lessons/marketing-lessons-hub-category";
import { listCatalogPathwayIdsWithLessonsSync } from "@/lib/lessons/pathway-lesson-catalog-sync";
import { REVIEW_REQUIRED } from "@/lib/taxonomy/taxonomy";

const __dirname = dirname(fileURLToPath(import.meta.url));
const reportPath = join(__dirname, "../../reports/marketing-hub-review-required-lessons.md");

const pathwayIds = listCatalogPathwayIdsWithLessonsSync().sort();
const lines: string[] = [
  "# Marketing hub — Review required (taxonomy) lessons",
  "",
  "Generated by `nursenest-core/scripts/report-marketing-hub-review-required-lessons.mts`.",
  "These rows map to the hub **Review required** bucket (`REVIEW_REQUIRED`), not the learner-facing display category list.",
  "",
];

for (const pathwayId of pathwayIds) {
  const lessons = getMarketingLessonsHubCatalogLessons(pathwayId);
  const rr = lessons.filter((l) => classifyLessonForHub(l, pathwayId) === REVIEW_REQUIRED);
  if (rr.length === 0) continue;
  lines.push(`## ${pathwayId} (${rr.length})`, "");
  for (const l of rr) {
    const disp = displayCategoryForMarketingHubLesson(l);
    lines.push(`- \`${l.slug}\` — ${(l.title ?? "").slice(0, 120)} (display category: ${disp})`);
  }
  lines.push("");
}

writeFileSync(reportPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote ${reportPath}`);
