export type AlliedMasteryModuleLevel = "basics" | "basic" | "advanced";
export type AlliedMasteryModuleAccess = "free_preview" | "paid" | "admin_preview_only";

export type AlliedMasteryContentType =
  | "lessons"
  | "quizzes"
  | "case_scenarios"
  | "rapid_drills"
  | "worksheets"
  | "pattern_maps"
  | "clinical_action_layer";

export type AlliedMasteryVisualQuestionType =
  | "image_based"
  | "multi_image_comparison"
  | "scenario_based"
  | "rapid_drill";

export type AlliedMasteryVisualQuestionSupport = {
  questionTypes: AlliedMasteryVisualQuestionType[];
  mediaFields: {
    imageUrl: true;
    secondaryImageUrl: "optional";
    highlightOverlay: "optional";
  };
  requiredQuestionStructure: [
    "questionText",
    "answerOptions",
    "correctAnswer",
    "rationale",
    "whatToLookFor",
    "commonMistakes",
  ];
  rapidDrillMode: {
    fastImageRecognition: true;
    minimalText: true;
    delayedRationale: true;
  };
  worksheetSupport: {
    printableLabelingWorksheets: true;
    abnormalIdentificationSheets: true;
    comparisonWorksheets: true;
  };
  cardiacSupport?: {
    videoUrl: true;
    framePreviewImageUrl: true;
    functionalInterpretationPrompts: true;
  };
};

export type AlliedMasteryModule = {
  id: string;
  slug: string;
  title: string;
  description: string;
  professionKeys: string[];
  level: AlliedMasteryModuleLevel;
  access: AlliedMasteryModuleAccess;
  isPublic: false;
  adminPreviewOnly: true;
  entitlementKey: string;
  tags: string[];
  contentTypes: AlliedMasteryContentType[];
  route: string;
  sections: string[];
  actionLayer: string[];
  visualQuestionSupport?: AlliedMasteryVisualQuestionSupport;
};

export const ENABLE_ALLIED_MASTERY_MODULES_FLAG = "ENABLE_ALLIED_MASTERY_MODULES" as const;
export const ENABLE_ADMIN_MODULE_PREVIEW_FLAG = "ENABLE_ADMIN_MODULE_PREVIEW" as const;

export const ALLIED_MASTERY_ENTITLEMENTS = {
  ABG_MASTERY: "ALLIED_ABG_MASTERY_PAID",
  VENTILATOR_BASICS: "ALLIED_VENTILATOR_BASICS_PAID",
  VENTILATOR_MANAGEMENT: "ALLIED_VENTILATOR_MANAGEMENT_PAID",
  OXYGEN_DELIVERY: "ALLIED_OXYGEN_DELIVERY_PAID",
  RESPIRATORY_DISTRESS: "ALLIED_RESPIRATORY_DISTRESS_PAID",
  TRAUMA_TRIAGE: "ALLIED_TRAUMA_TRIAGE_PAID",
  IV_INFUSION_SAFETY: "ALLIED_IV_INFUSION_SAFETY_PAID",
  NEURO_STROKE_RECOGNITION: "ALLIED_NEURO_STROKE_RECOGNITION_PAID",
  ADVANCED_LAB_INTERPRETATION: "ALLIED_ADVANCED_LAB_INTERPRETATION_PAID",
  PHARMACOLOGY_PATTERNS: "ALLIED_PHARMACOLOGY_PATTERNS_PAID",
  DOSAGE_CALCULATIONS: "ALLIED_DOSAGE_CALCULATIONS_PAID",
  ADL_FUNCTIONAL_ASSESSMENT: "ALLIED_ADL_FUNCTIONAL_ASSESSMENT_PAID",
  MSK_REHAB_ASSESSMENT: "ALLIED_MSK_REHAB_ASSESSMENT_PAID",
  IMAGE_RECOGNITION: "ALLIED_IMAGE_RECOGNITION_PAID",
  CARDIAC_PATTERN_RECOGNITION: "ALLIED_CARDIAC_PATTERN_RECOGNITION_PAID",
  EMERGENCY_PATTERN_RECOGNITION: "ALLIED_EMERGENCY_PATTERN_RECOGNITION_PAID",
  MOVEMENT_INJURY_MECHANICS: "ALLIED_MOVEMENT_INJURY_MECHANICS_PAID",
  FUNCTIONAL_ASSESSMENT_ADL_SAFETY: "ALLIED_FUNCTIONAL_ASSESSMENT_ADL_SAFETY_PAID",
} as const;

export const ALLIED_MASTERY_PROFESSION_LABELS: Record<string, string> = {
  respiratory: "Respiratory Therapy",
  mlt: "Medical Laboratory Technology",
  "pharmacy-tech": "Pharmacy Technician",
  ota: "Occupational Therapy",
  pta: "Physiotherapy",
  imaging: "Diagnostic Imaging",
  sonography: "Cardiology Technology / Cardiac Sonography",
  paramedic: "Paramedic / EMS",
};

export const ALLIED_MASTERY_PROFESSION_ROUTE_SLUGS: Record<string, string> = {
  respiratory: "respiratory-therapy",
  mlt: "medical-lab-technology",
};

const allContentTypes: AlliedMasteryContentType[] = [
  "lessons",
  "quizzes",
  "case_scenarios",
  "rapid_drills",
  "worksheets",
  "pattern_maps",
  "clinical_action_layer",
];

const visualQuestionStructure: AlliedMasteryVisualQuestionSupport["requiredQuestionStructure"] = [
  "questionText",
  "answerOptions",
  "correctAnswer",
  "rationale",
  "whatToLookFor",
  "commonMistakes",
];

const visualQuestionSupport: AlliedMasteryVisualQuestionSupport = {
  questionTypes: ["image_based", "multi_image_comparison", "scenario_based", "rapid_drill"],
  mediaFields: {
    imageUrl: true,
    secondaryImageUrl: "optional",
    highlightOverlay: "optional",
  },
  requiredQuestionStructure: visualQuestionStructure,
  rapidDrillMode: {
    fastImageRecognition: true,
    minimalText: true,
    delayedRationale: true,
  },
  worksheetSupport: {
    printableLabelingWorksheets: true,
    abnormalIdentificationSheets: true,
    comparisonWorksheets: true,
  },
};

const cardiacVisualQuestionSupport: AlliedMasteryVisualQuestionSupport = {
  ...visualQuestionSupport,
  cardiacSupport: {
    videoUrl: true,
    framePreviewImageUrl: true,
    functionalInterpretationPrompts: true,
  },
};

function hiddenModule(input: Omit<AlliedMasteryModule, "access" | "isPublic" | "adminPreviewOnly" | "route">): AlliedMasteryModule {
  const professionKey = input.professionKeys[0];
  const routeProfessionSlug = ALLIED_MASTERY_PROFESSION_ROUTE_SLUGS[professionKey] ?? professionKey;
  return {
    ...input,
    access: "admin_preview_only",
    isPublic: false,
    adminPreviewOnly: true,
    route: `/allied/${routeProfessionSlug}/modules/${input.slug}`,
  };
}

function hiddenModuleForRoute(
  input: Omit<AlliedMasteryModule, "access" | "isPublic" | "adminPreviewOnly" | "route">,
  routeProfessionKey: string,
): AlliedMasteryModule {
  const routeProfessionSlug = ALLIED_MASTERY_PROFESSION_ROUTE_SLUGS[routeProfessionKey] ?? routeProfessionKey;
  return {
    ...input,
    access: "admin_preview_only",
    isPublic: false,
    adminPreviewOnly: true,
    route: `/allied/${routeProfessionSlug}/modules/${input.slug}`,
  };
}

export const ALLIED_MASTERY_MODULES: AlliedMasteryModule[] = [
  hiddenModule({
    id: "respiratory-abg-mastery",
    slug: "abg",
    title: "ABG Interpretation Mastery",
    description: "Respiratory therapy ABG interpretation from single-value meaning through compensation and priority action.",
    professionKeys: ["respiratory"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.ABG_MASTERY,
    tags: ["abg", "acid-base", "respiratory-therapy", "oxygenation", "ventilation"],
    contentTypes: allContentTypes,
    sections: [
      "Basics: What is an ABG?",
      "Basics: pH",
      "Basics: PaCO2",
      "Basics: HCO3",
      "Basics: PaO2",
      "Basics: SaO2",
      "Basic interpretation: acidosis vs alkalosis",
      "Basic interpretation: respiratory vs metabolic",
      "Basic interpretation: compensation basics",
      "Advanced interpretation: uncompensated",
      "Advanced interpretation: partially compensated",
      "Advanced interpretation: fully compensated",
      "Advanced interpretation: mixed disorders",
      "Cases: COPD exacerbation",
      "Cases: DKA",
      "Cases: sepsis/lactic acidosis",
      "Cases: opioid overdose",
      "Cases: pulmonary embolism",
      "Rapid drills: classify ABG pattern",
      "Rapid drills: identify priority action",
      "Worksheets: student version",
      "Worksheets: answer key version",
      "Pattern maps: pH + CO2 + HCO3 logic map",
      "Pattern maps: compensation map",
    ],
    actionLayer: [
      "What is happening?",
      "Why it matters",
      "Oxygenation or ventilation concern",
      "What to assess",
      "What to do first",
      "When to escalate",
    ],
  }),
  hiddenModule({
    id: "respiratory-ventilator-basics",
    slug: "ventilator-basics",
    title: "Ventilator Basics",
    description: "Core ventilator terms, settings, alarms, patient-ventilator safety, and escalation patterns for RT learners.",
    professionKeys: ["respiratory"],
    level: "basic",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.VENTILATOR_BASICS,
    tags: ["ventilator", "airway", "respiratory-therapy"],
    contentTypes: allContentTypes,
    sections: ["Modes and settings", "Alarm basics", "Oxygenation vs ventilation", "Patient assessment", "Escalation triggers"],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }),
  hiddenModule({
    id: "respiratory-ventilator-management",
    slug: "ventilator-management",
    title: "Ventilator Management",
    description: "Respiratory therapy ventilator settings, patient response, alarms, troubleshooting, and basic waveform pattern interpretation.",
    professionKeys: ["respiratory"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.VENTILATOR_MANAGEMENT,
    tags: ["ventilator", "mechanical-ventilation", "respiratory-therapy", "abg", "waveforms"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: What mechanical ventilation does",
      "Lessons: Ventilator modes AC/VC, AC/PC, SIMV, PSV, CPAP, and BiPAP/NIV",
      "Lessons: Core settings tidal volume, respiratory rate, FiO2, PEEP, pressure support, inspiratory pressure, and I:E ratio",
      "Lessons: Oxygenation vs ventilation",
      "Lessons: Peak pressure vs plateau pressure",
      "Lessons: Alarms and troubleshooting",
      "Lessons: Weaning basics",
      "Quizzes: mode recognition, setting purpose, oxygenation vs ventilation decisions, and alarm interpretation",
      "Cases: ARDS with low oxygenation",
      "Cases: COPD with rising CO2",
      "Cases: high peak pressure",
      "Cases: low exhaled tidal volume alarm",
      "Cases: accidental extubation/disconnection",
      "Cases: weaning readiness",
      "Rapid drills: PaCO2 rising — what setting is most related?",
      "Rapid drills: SpO2 low despite FiO2 — what setting may help oxygenation?",
      "Rapid drills: high peak pressure with normal plateau — what does this suggest?",
      "Rapid drills: low pressure alarm — what should you check first?",
      "Rapid drills: FiO2 increased but saturation remains low — what else supports oxygenation?",
      "Rapid drills: plateau pressure is high — what risk is increasing?",
      "Rapid drills: patient triggering rapid shallow breaths — what should you assess?",
      "Rapid drills: exhaled tidal volume suddenly low — what circuit issue is likely?",
      "Rapid drills: pressure support trial fatigue — what sign matters first?",
      "Rapid drills: waveform shows flow not returning to baseline — what does this suggest?",
      "Pattern maps: oxygenation problem map",
      "Pattern maps: ventilation problem map",
      "Pattern maps: peak vs plateau pressure map",
      "Pattern maps: alarm troubleshooting map",
    ],
    actionLayer: [
      "What is happening?",
      "Why it matters",
      "What to assess",
      "What action is priority",
      "When to escalate/call provider/team",
    ],
  }),
  hiddenModuleForRoute({
    id: "respiratory-paramedic-oxygen-delivery",
    slug: "oxygen-delivery",
    title: "Oxygen Delivery Systems",
    description: "Respiratory therapy oxygen device selection, FiO2 reasoning, escalation logic, and patient response interpretation.",
    professionKeys: ["respiratory"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.OXYGEN_DELIVERY,
    tags: ["oxygen-delivery", "respiratory-therapy", "paramedic", "spo2", "fio2", "escalation"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: Oxygenation basics SpO2 vs PaO2",
      "Lessons: Low-flow devices nasal cannula with flow rate, approximate FiO2, indications, limitations, and risks",
      "Lessons: Moderate/high oxygen simple mask and non-rebreather with flow rate, approximate FiO2, indications, limitations, and risks",
      "Lessons: Controlled oxygen Venturi mask with flow rate, approximate FiO2, indications, limitations, and risks",
      "Lessons: Advanced oxygen HFNC, CPAP, and BiPAP/NIV intro with indications, limitations, and risks",
      "Quizzes: device recognition, FiO2 estimation, escalation decisions, and matching patient condition to device",
      "Cases: COPD patient needing controlled oxygen",
      "Cases: acute hypoxia SpO2 below 85%",
      "Cases: trauma patient",
      "Cases: pediatric respiratory distress",
      "Cases: patient not improving on nasal cannula",
      "Cases: patient requiring escalation to NRB or HFNC",
      "Rapid drills: SpO2 82% → best device?",
      "Rapid drills: which delivers highest FiO2?",
      "Rapid drills: COPD patient → safest option?",
      "Rapid drills: patient worsening → next step?",
      "Rapid drills: nasal cannula flow limit?",
      "Rapid drills: Venturi mask purpose?",
      "Rapid drills: NRB reservoir collapsed — what check first?",
      "Rapid drills: HFNC escalation cue?",
      "Rapid drills: CPAP/BiPAP intro indication?",
      "Rapid drills: controlled vs uncontrolled oxygen?",
      "Pattern maps: oxygen escalation ladder nasal cannula → simple mask → NRB → HFNC → CPAP/BiPAP",
      "Pattern maps: FiO2 comparison map",
      "Pattern maps: controlled vs uncontrolled oxygen logic",
    ],
    actionLayer: [
      "What is happening?",
      "Why it matters",
      "What to assess",
      "Priority action",
      "Escalation criteria",
    ],
  }, "respiratory"),
  hiddenModuleForRoute({
    id: "paramedic-oxygen-delivery",
    slug: "oxygen-delivery",
    title: "Oxygen Delivery Systems",
    description: "Paramedic oxygen device selection, patient condition matching, FiO2 reasoning, and escalation cues for field care.",
    professionKeys: ["paramedic"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.OXYGEN_DELIVERY,
    tags: ["oxygen-delivery", "paramedic", "spo2", "fio2", "escalation"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: Oxygenation basics SpO2 vs PaO2",
      "Lessons: Low-flow devices nasal cannula with flow rate, approximate FiO2, indications, limitations, and risks",
      "Lessons: Moderate/high oxygen simple mask and non-rebreather with flow rate, approximate FiO2, indications, limitations, and risks",
      "Lessons: Controlled oxygen Venturi mask with flow rate, approximate FiO2, indications, limitations, and risks",
      "Lessons: Advanced oxygen HFNC, CPAP, and BiPAP/NIV intro with indications, limitations, and risks",
      "Quizzes: device recognition, FiO2 estimation, escalation decisions, and matching patient condition to device",
      "Cases: COPD patient needing controlled oxygen",
      "Cases: acute hypoxia SpO2 below 85%",
      "Cases: trauma patient",
      "Cases: pediatric respiratory distress",
      "Cases: patient not improving on nasal cannula",
      "Cases: patient requiring escalation to NRB or HFNC",
      "Rapid drills: SpO2 82% → best device?",
      "Rapid drills: which delivers highest FiO2?",
      "Rapid drills: COPD patient → safest option?",
      "Rapid drills: patient worsening → next step?",
      "Rapid drills: nasal cannula flow limit?",
      "Rapid drills: Venturi mask purpose?",
      "Rapid drills: NRB reservoir collapsed — what check first?",
      "Rapid drills: HFNC escalation cue?",
      "Rapid drills: CPAP/BiPAP intro indication?",
      "Rapid drills: controlled vs uncontrolled oxygen?",
      "Pattern maps: oxygen escalation ladder nasal cannula → simple mask → NRB → HFNC → CPAP/BiPAP",
      "Pattern maps: FiO2 comparison map",
      "Pattern maps: controlled vs uncontrolled oxygen logic",
    ],
    actionLayer: [
      "What is happening?",
      "Why it matters",
      "What to assess",
      "Priority action",
      "Escalation criteria",
    ],
  }, "paramedic"),
  hiddenModuleForRoute({
    id: "respiratory-paramedic-respiratory-distress",
    slug: "respiratory-distress",
    title: "Respiratory Distress Recognition",
    description: "Respiratory distress pattern recognition using symptoms, vitals, lung sounds, work of breathing, SpO2, ABGs, and oxygen escalation decisions.",
    professionKeys: ["respiratory"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.RESPIRATORY_DISTRESS,
    tags: ["respiratory-distress", "lung-sounds", "spo2", "abg", "oxygen-escalation", "respiratory-therapy"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: What respiratory distress looks like",
      "Lessons: Work of breathing signs accessory muscle use, retractions, nasal flaring, tripod positioning, and inability to speak full sentences",
      "Lessons: SpO2 interpretation and respiratory rate interpretation",
      "Lessons: Lung sounds wheezes, crackles, stridor, and diminished/absent sounds",
      "Lessons: Oxygenation vs ventilation",
      "Lessons: When respiratory distress becomes respiratory failure",
      "Lessons: RT vs Paramedic priorities",
      "Quizzes: identifying distress signs, matching lung sounds to likely cause, choosing oxygen escalation, and recognizing deterioration",
      "Cases: asthma exacerbation with wheezing",
      "Cases: CHF/pulmonary edema with crackles",
      "Cases: anaphylaxis/upper airway swelling with stridor",
      "Cases: COPD exacerbation with CO2 retention risk",
      "Cases: opioid overdose with hypoventilation",
      "Cases: trauma patient with absent breath sounds",
      "Cases: pediatric respiratory distress",
      "Rapid drills: SpO2 84%, RR 34, tripod, wheezing — likely issue?",
      "Rapid drills: crackles + edema + low SpO2 — likely pattern?",
      "Rapid drills: stridor after allergen exposure — priority?",
      "Rapid drills: absent breath sounds after trauma — suspect?",
      "Rapid drills: RR 8 after opioid use — oxygenation or ventilation issue?",
      "Rapid drills: accessory muscle use + cannot speak full sentences — severity?",
      "Rapid drills: wheezing not improving after oxygen escalation — next concern?",
      "Rapid drills: low SpO2 + normal PaCO2 — primary issue?",
      "Rapid drills: rising CO2 + drowsiness — deterioration sign?",
      "Rapid drills: pediatric nasal flaring + retractions — what pattern?",
      "Pattern maps: lung sound → likely cause map",
      "Pattern maps: oxygenation vs ventilation map",
      "Pattern maps: distress vs failure progression map",
      "Pattern maps: oxygen escalation decision map",
      "Pattern maps: RT/Paramedic priority action map",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }, "respiratory"),
  hiddenModuleForRoute({
    id: "paramedic-respiratory-distress",
    slug: "respiratory-distress",
    title: "Respiratory Distress Recognition",
    description: "Paramedic respiratory distress pattern recognition using symptoms, vitals, lung sounds, work of breathing, SpO2, and field oxygen escalation.",
    professionKeys: ["paramedic"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.RESPIRATORY_DISTRESS,
    tags: ["respiratory-distress", "lung-sounds", "spo2", "oxygen-escalation", "paramedic"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: What respiratory distress looks like",
      "Lessons: Work of breathing signs accessory muscle use, retractions, nasal flaring, tripod positioning, and inability to speak full sentences",
      "Lessons: SpO2 interpretation and respiratory rate interpretation",
      "Lessons: Lung sounds wheezes, crackles, stridor, and diminished/absent sounds",
      "Lessons: Oxygenation vs ventilation",
      "Lessons: When respiratory distress becomes respiratory failure",
      "Lessons: RT vs Paramedic priorities",
      "Quizzes: identifying distress signs, matching lung sounds to likely cause, choosing oxygen escalation, and recognizing deterioration",
      "Cases: asthma exacerbation with wheezing",
      "Cases: CHF/pulmonary edema with crackles",
      "Cases: anaphylaxis/upper airway swelling with stridor",
      "Cases: COPD exacerbation with CO2 retention risk",
      "Cases: opioid overdose with hypoventilation",
      "Cases: trauma patient with absent breath sounds",
      "Cases: pediatric respiratory distress",
      "Rapid drills: SpO2 84%, RR 34, tripod, wheezing — likely issue?",
      "Rapid drills: crackles + edema + low SpO2 — likely pattern?",
      "Rapid drills: stridor after allergen exposure — priority?",
      "Rapid drills: absent breath sounds after trauma — suspect?",
      "Rapid drills: RR 8 after opioid use — oxygenation or ventilation issue?",
      "Rapid drills: accessory muscle use + cannot speak full sentences — severity?",
      "Rapid drills: wheezing not improving after oxygen escalation — next concern?",
      "Rapid drills: low SpO2 + normal PaCO2 — primary issue?",
      "Rapid drills: rising CO2 + drowsiness — deterioration sign?",
      "Rapid drills: pediatric nasal flaring + retractions — what pattern?",
      "Pattern maps: lung sound → likely cause map",
      "Pattern maps: oxygenation vs ventilation map",
      "Pattern maps: distress vs failure progression map",
      "Pattern maps: oxygen escalation decision map",
      "Pattern maps: RT/Paramedic priority action map",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }, "paramedic"),
  hiddenModule({
    id: "paramedic-trauma-triage",
    slug: "trauma-triage",
    title: "Trauma & Triage",
    description: "Paramedic trauma scene size-up, triage priority, shock recognition, vitals-driven escalation, and safe transport decision patterns.",
    professionKeys: ["paramedic"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.TRAUMA_TRIAGE,
    tags: ["paramedic", "trauma", "triage", "shock", "vitals", "escalation"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: scene safety and mechanism of injury",
      "Lessons: primary assessment and life threats",
      "Lessons: triage categories and transport priority",
      "Lessons: shock patterns and vital sign interpretation",
      "Quizzes: triage priority, shock recognition, and transport decision-making",
      "Cases: multi-patient collision with abnormal vitals",
      "Cases: penetrating trauma with hypotension",
      "Cases: head injury with declining mental status",
      "Cases: pediatric trauma with subtle shock signs",
      "Rapid drills: identify immediate life threat",
      "Rapid drills: choose triage priority",
      "Rapid drills: interpret hypotension with tachycardia",
      "Rapid drills: decide when to escalate transport",
      "Pattern maps: trauma primary survey map",
      "Pattern maps: shock recognition map",
      "Pattern maps: triage escalation map",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "Priority action", "Escalation/transport criteria"],
  }),
  hiddenModuleForRoute({
    id: "pharmacy-tech-iv-infusion-safety",
    slug: "iv-infusion-safety",
    title: "IV Therapy + Infusion Safety",
    description: "Pharmacy technician IV fluid, compatibility, medication order, infusion reaction, and high-alert order safety mastery for exam prep.",
    professionKeys: ["pharmacy-tech"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.IV_INFUSION_SAFETY,
    tags: ["iv-therapy", "infusion-safety", "pharmacy-tech", "medication-orders", "compatibility"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: IV therapy basics",
      "Lessons: IV fluids overview isotonic, hypotonic, and hypertonic",
      "Lessons: common infusion risks",
      "Lessons: medication order safety",
      "Lessons: infusion rate basics",
      "Lessons: IV compatibility basics",
      "Lessons: infiltration vs extravasation",
      "Lessons: signs of infusion reaction",
      "Lessons: high-alert medication awareness",
      "Lessons: when to stop/escalate",
      "Quizzes: fluid type recognition, unsafe order recognition, infusion reaction recognition, compatibility concern recognition, rate interpretation, and priority action",
      "Cases: infusion reaction during medication administration",
      "Cases: infiltration/extravasation concern",
      "Cases: incompatible IV medication warning",
      "Cases: fluid overload risk",
      "Cases: high-alert medication order check",
      "Cases: paramedic fluid resuscitation scenario",
      "Rapid drills: IV site swollen and painful — concern?",
      "Rapid drills: new rash and wheezing during infusion — priority?",
      "Rapid drills: order appears incompatible — what next?",
      "Rapid drills: older adult with crackles after IV fluids — concern?",
      "Rapid drills: high-alert medication order — what must be verified?",
      "Rapid drills: isotonic vs hypotonic fluid — which category?",
      "Rapid drills: pump rate mismatch — what should be checked?",
      "Rapid drills: vesicant infiltration concern — escalation?",
      "Rapid drills: unclear medication order — safe next step?",
      "Rapid drills: compatibility alert appears — priority?",
      "Pattern maps: infiltration vs extravasation map",
      "Pattern maps: infusion reaction escalation map",
      "Pattern maps: fluid type comparison map",
      "Pattern maps: compatibility safety map",
      "Pattern maps: medication order safety check map",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }, "pharmacy-tech"),
  hiddenModuleForRoute({
    id: "paramedic-iv-infusion-safety",
    slug: "iv-infusion-safety",
    title: "IV Therapy + Infusion Safety",
    description: "Paramedic IV fluid safety, infusion risks, medication order checks, reaction recognition, and escalation triggers for exam prep.",
    professionKeys: ["paramedic"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.IV_INFUSION_SAFETY,
    tags: ["iv-therapy", "infusion-safety", "paramedic", "fluid-resuscitation", "vitals"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: IV therapy basics",
      "Lessons: IV fluids overview isotonic, hypotonic, and hypertonic",
      "Lessons: common infusion risks",
      "Lessons: medication order safety",
      "Lessons: infusion rate basics",
      "Lessons: IV compatibility basics",
      "Lessons: infiltration vs extravasation",
      "Lessons: signs of infusion reaction",
      "Lessons: high-alert medication awareness",
      "Lessons: when to stop/escalate",
      "Quizzes: fluid type recognition, unsafe order recognition, infusion reaction recognition, compatibility concern recognition, rate interpretation, and priority action",
      "Cases: infusion reaction during medication administration",
      "Cases: infiltration/extravasation concern",
      "Cases: incompatible IV medication warning",
      "Cases: fluid overload risk",
      "Cases: high-alert medication order check",
      "Cases: paramedic fluid resuscitation scenario",
      "Rapid drills: IV site swollen and painful — concern?",
      "Rapid drills: new rash and wheezing during infusion — priority?",
      "Rapid drills: order appears incompatible — what next?",
      "Rapid drills: older adult with crackles after IV fluids — concern?",
      "Rapid drills: high-alert medication order — what must be verified?",
      "Rapid drills: isotonic vs hypotonic fluid — which category?",
      "Rapid drills: pump rate mismatch — what should be checked?",
      "Rapid drills: vesicant infiltration concern — escalation?",
      "Rapid drills: unclear medication order — safe next step?",
      "Rapid drills: compatibility alert appears — priority?",
      "Pattern maps: infiltration vs extravasation map",
      "Pattern maps: infusion reaction escalation map",
      "Pattern maps: fluid type comparison map",
      "Pattern maps: compatibility safety map",
      "Pattern maps: medication order safety check map",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }, "paramedic"),
  hiddenModule({
    id: "mlt-advanced-lab-interpretation",
    slug: "advanced-lab-interpretation",
    title: "Advanced Lab Interpretation",
    description: "Medical laboratory pattern recognition across CBC, chemistry, renal, liver, coagulation, and critical value escalation.",
    professionKeys: ["mlt"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.ADVANCED_LAB_INTERPRETATION,
    tags: ["mlt", "lab-panels", "hematology", "chemistry", "critical-values"],
    contentTypes: allContentTypes,
    sections: [
      "Basics: CBC review, electrolytes, renal markers, liver markers, and coagulation basics",
      "Interpretation patterns: anemia patterns, infection/inflammation patterns, renal impairment patterns, electrolyte imbalance patterns, liver injury patterns, and coagulation abnormality patterns",
      "Advanced cases: iron deficiency anemia, sepsis pattern, acute kidney injury, DKA pattern, liver dysfunction, and bleeding/clotting risk",
      "Rapid drills: identify abnormal cluster, classify likely pattern, and identify critical value",
      "Worksheets: student version, answer key version, and full lab panel interpretation",
      "Pattern maps: CBC pattern map, renal/electrolyte pattern map, and coagulation pattern map",
    ],
    actionLayer: [
      "What pattern is present?",
      "Why it matters",
      "What values are critical",
      "What requires escalation",
      "What should be verified/rechecked",
    ],
  }),
  hiddenModule({
    id: "pharmacy-tech-pharmacology-patterns",
    slug: "pharmacology-patterns",
    title: "Pharmacology Pattern Recognition",
    description: "Drug class patterns, contraindications, adverse effects, and interaction recognition for pharmacy technician learners.",
    professionKeys: ["pharmacy-tech"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.PHARMACOLOGY_PATTERNS,
    tags: ["pharmacy-tech", "pharmacology", "drug-classes", "interactions"],
    contentTypes: allContentTypes,
    sections: ["Drug class lessons", "Contraindications", "Adverse effects", "Interactions", "Worksheet review"],
    actionLayer: ["What is happening?", "Why it matters", "What to verify", "What to do first", "When to escalate"],
  }),
  hiddenModule({
    id: "pharmacy-tech-dosage-calculations",
    slug: "dosage-calculations",
    title: "Dosage Calculations",
    description: "Calculation drills, unit conversion, medication safety checks, and pharmacy workflow accuracy.",
    professionKeys: ["pharmacy-tech"],
    level: "basic",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.DOSAGE_CALCULATIONS,
    tags: ["pharmacy-tech", "dosage-calculation", "medication-safety"],
    contentTypes: allContentTypes,
    sections: ["Unit conversion", "Dose calculations", "Safety checks", "Rapid calculation drills", "Answer key worksheets"],
    actionLayer: ["What is being calculated?", "Why it matters", "What to verify", "What to do first", "When to escalate"],
  }),
  hiddenModule({
    id: "ota-adl-functional-assessment",
    slug: "adl-functional-assessment",
    title: "ADL + Functional Assessment Mastery",
    description: "ADL assessment, adaptive strategies, care planning, goal writing, and occupation-focused case reasoning.",
    professionKeys: ["ota"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.ADL_FUNCTIONAL_ASSESSMENT,
    tags: ["occupational-therapy", "adl", "functional-assessment", "goal-writing"],
    contentTypes: allContentTypes,
    sections: ["ADL lessons", "Assessment cases", "Care planning", "Goal writing", "Worksheets"],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }),
  hiddenModule({
    id: "pta-msk-rehab-assessment",
    slug: "msk-rehab-assessment",
    title: "Musculoskeletal Rehab + Movement Assessment",
    description: "ROM, gait, injury patterns, rehab progression, and movement assessment cases for physiotherapy learners.",
    professionKeys: ["pta"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.MSK_REHAB_ASSESSMENT,
    tags: ["physiotherapy", "msk", "rehab", "gait", "rom"],
    contentTypes: allContentTypes,
    sections: ["ROM", "Gait", "Injury patterns", "Rehab progression", "Assessment cases", "Worksheets"],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }),
  hiddenModule({
    id: "imaging-image-recognition",
    slug: "image-recognition",
    title: "Image Recognition Basics",
    description: "Normal vs abnormal imaging, chest X-ray basics, CT/MRI safety concepts, and image case review.",
    professionKeys: ["imaging"],
    level: "basic",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.IMAGE_RECOGNITION,
    tags: ["diagnostic-imaging", "x-ray", "ct", "mri", "image-recognition"],
    contentTypes: allContentTypes,
    sections: [
      "Normal vs abnormal imaging",
      "Chest X-ray basics",
      "CT/MRI safety concepts",
      "Image-based questions",
      "Multi-image comparison questions",
      "Scenario-based image cases",
      "Rapid drill questions: fast image recognition",
      "Worksheets: printable labeling worksheets, abnormal identification sheets, comparison worksheets",
    ],
    actionLayer: ["What is visible?", "Why it matters", "What to verify", "What to do first", "When to escalate"],
    visualQuestionSupport,
  }),
  hiddenModule({
    id: "sonography-ecg-cardiac-patterns",
    slug: "ecg-cardiac-patterns",
    title: "ECG + Cardiac Pattern Recognition",
    description: "Rhythm strips, cardiac findings, echo and imaging basics where appropriate, and cardiac pattern cases.",
    professionKeys: ["sonography"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.CARDIAC_PATTERN_RECOGNITION,
    tags: ["cardiology-technology", "ecg", "cardiac-patterns"],
    contentTypes: allContentTypes,
    sections: [
      "Rhythm strips",
      "Cardiac findings",
      "Echo/imaging basics",
      "Image-based questions",
      "Multi-image comparison questions",
      "Scenario-based cardiac cases",
      "Rapid drill questions: fast image recognition",
      "Echo clip prompts: videoUrl, frame preview image, functional interpretation prompts",
      "Worksheets: printable labeling worksheets, abnormal identification sheets, comparison worksheets",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
    visualQuestionSupport: cardiacVisualQuestionSupport,
  }),
  hiddenModule({
    id: "paramedic-neuro-stroke-recognition",
    slug: "neuro-stroke-recognition",
    title: "Neurological Assessment + Stroke Recognition",
    description: "Paramedic neuro assessment, FAST/BE-FAST, GCS, stroke vs mimic differentiation, altered LOC patterns, and OT functional implications.",
    professionKeys: ["paramedic"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.NEURO_STROKE_RECOGNITION,
    tags: ["paramedic", "neuro", "stroke", "gcs", "altered-loc", "fast"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: Basic neuro assessment — LOC, orientation, pupil response, motor and sensory exam, speech",
      "Lessons: FAST/BE-FAST tool — facial droop, arm drift, speech, eyes, balance, time to call",
      "Lessons: GCS basics — eye, verbal, motor scoring and total score interpretation",
      "Lessons: Stroke recognition — FAST positive, sudden onset symptoms, cortical vs non-cortical signs",
      "Lessons: Stroke mimics — hypoglycemia, seizure post-ictal, Todd's paralysis, migraine, increased ICP signs",
      "Lessons: Altered LOC differential — AEIOU-TIPS, hypoglycemia, overdose, trauma, metabolic causes",
      "Lessons: OT functional implications — unilateral neglect, hemiplegia, aphasia, acute facial droop, ADL impact",
      "Lessons: Increased ICP recognition — Cushing's triad, decreasing GCS, severe headache, vomiting, unequal pupils",
      "Lessons: Altered LOC with low glucose — glucose check priority, dextrose administration, mimic recognition",
      "Lessons: When to escalate — stroke centre transport, altered LOC triggers, time-sensitive decisions, glucose requirement",
      "Quizzes: FAST/BE-FAST recognition, GCS scoring, stroke vs mimic identification, altered LOC priority, escalation timing",
      "Cases: acute facial droop and arm drift and slurred speech — FAST positive, glucose 5.2 mmol/L, onset 45 min ago",
      "Cases: altered LOC with low glucose — glucose 1.8 mmol/L, diaphoresis, confusion, priority intervention",
      "Cases: increased ICP pattern — Cushing's triad, HR 48, BP 178/102, RR 8, decreasing GCS",
      "Cases: stroke vs hypoglycemia mimic — glucose required to differentiate, unilateral weakness, altered LOC",
      "Cases: unilateral neglect post-stroke — OT functional deficit pattern, hemiplegia, left-sided neglect",
      "Cases: seizure with post-ictal altered LOC — Todd's paralysis, focal findings, differentiate from stroke",
      "Cases: pediatric first seizure with altered LOC — age-appropriate assessment, fever, meningismus",
      "Cases: hemorrhagic stroke cues — sudden severe headache, vomiting, rapid GCS decline, elevated BP 186/104",
      "Rapid drills: FAST positive plus onset 30 minutes ago — priority action?",
      "Rapid drills: GCS 10 + glucose 1.9 mmol/L + diaphoresis — first intervention?",
      "Rapid drills: Cushing's triad HR 48 BP 180/100 RR 6 — concern?",
      "Rapid drills: unilateral arm drift + facial droop + glucose normal — priority?",
      "Rapid drills: post-ictal patient + focal weakness — stroke or Todd's paralysis?",
      "Rapid drills: sudden worst headache of life + vomiting — suspect?",
      "Rapid drills: BEFAST positive + time unknown — transport decision?",
      "Rapid drills: altered LOC + glucose not checked — safe assumption to proceed?",
      "Rapid drills: unilateral neglect post-stroke — OT functional deficit pattern identified?",
      "Rapid drills: infant bulging fontanelle + altered LOC — concern?",
      "Rapid drills: GCS 14 drops to 10 in 10 minutes — urgency level?",
      "Rapid drills: pupils unequal + GCS 8 — immediate concern?",
      "Pattern maps: FAST/BE-FAST map — recognition to transport algorithm",
      "Pattern maps: GCS interpretation map — mild moderate severe TBI and altered LOC thresholds",
      "Pattern maps: stroke vs mimic map — hypoglycemia, post-ictal, migraine, and true stroke differentiators",
      "Pattern maps: OT functional deficit map — hemiplegia, unilateral neglect, speech, ADL impact pathway",
      "Pattern maps: altered LOC differential map — AEIOU-TIPS framework and glucose check priority",
      "Pattern maps: escalation and transport decision map — stroke centre triggers, glucose requirement, time factors",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate/transport"],
  }),
  hiddenModuleForRoute({
    id: "ota-neuro-stroke-recognition",
    slug: "neuro-stroke-recognition",
    title: "Neurological Assessment + Stroke Recognition",
    description: "OT-focused neuro assessment, FAST/BE-FAST recognition, stroke functional implications, altered LOC safety, and post-stroke ADL adaptation.",
    professionKeys: ["ota"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.NEURO_STROKE_RECOGNITION,
    tags: ["occupational-therapy", "neuro", "stroke", "adl", "functional-assessment", "fast"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: Basic neuro assessment for OT — LOC, cooperation, cognition, safety screening",
      "Lessons: FAST/BE-FAST tool — OT recognition and escalation relevance, facial droop, arm drift",
      "Lessons: GCS basics and functional correlation — GCS scores and occupational participation safety thresholds",
      "Lessons: Stroke recognition and OT context — FAST positive deficits affecting function and ADL",
      "Lessons: OT functional implications — hemiplegia, unilateral neglect, aphasia, dysphagia, visual field deficits",
      "Lessons: Altered LOC and OT session safety — when to defer, safety cues, escalation triggers",
      "Lessons: Acute facial droop — asymmetry, swallowing safety, OT mealtime assessment, FAST",
      "Lessons: Hypoglycemia and neuro mimics — confusion as a medical emergency, OT session safety",
      "Lessons: Increased ICP basics — safety contraindications for OT activity, escalation triggers",
      "Lessons: Post-stroke functional trajectory — acute phase, subacute rehab, ADL goal adaptation, unilateral neglect",
      "Quizzes: stroke vs mimic identification, GCS functional correlation, ADL safety decisions, neuro escalation recognition",
      "Cases: acute facial droop and swallowing concern — OT mealtime assessment, FAST recognition, escalation",
      "Cases: altered LOC with low glucose 1.8 mmol/L — OT defers assessment, glucose priority, escalation",
      "Cases: unilateral neglect post-stroke — ADL impact, goal adaptation, environmental modification",
      "Cases: hemiplegia affecting ADL — functional assessment, adaptive equipment, safe transfer techniques",
      "Cases: aphasia post-stroke — communication strategies, ADL compensation, goal writing with family",
      "Cases: increased ICP signs during OT session — Cushing's triad recognition, immediate escalation, session halt",
      "Cases: visual field deficit post-stroke — safe environment, scanning training, ADL modification",
      "Cases: post-ictal altered LOC — OT session deferred, neuro escalation, return-to-activity criteria",
      "Rapid drills: patient suddenly unable to lift one arm during OT session — priority action?",
      "Rapid drills: GCS drops from 14 to 10 during OT session — action?",
      "Rapid drills: patient confused with glucose 1.9 mmol/L — safe to continue ADL?",
      "Rapid drills: new facial asymmetry noted during mealtime — concern?",
      "Rapid drills: unilateral neglect pattern identified — OT assessment approach?",
      "Rapid drills: BP 178/102 + headache + vomiting during OT — escalation?",
      "Rapid drills: aphasia new onset in rehab setting — FAST positive response?",
      "Rapid drills: post-stroke patient new fall risk identified — priority ADL concern?",
      "Rapid drills: hemiplegia patient attempting unsupported transfer — OT safety action?",
      "Rapid drills: visual field deficit + patient driving goal — OT recommendation?",
      "Rapid drills: glucose 1.9 mmol/L + confusion + diaphoresis during OT session — response?",
      "Pattern maps: FAST/BE-FAST map — OT recognition and escalation pathway",
      "Pattern maps: GCS interpretation map — functional correlation and OT activity threshold",
      "Pattern maps: stroke vs mimic map — OT safety differentiation for session continuation",
      "Pattern maps: OT functional deficit map — hemiplegia, unilateral neglect, aphasia, dysphagia, visual deficits",
      "Pattern maps: altered LOC differential map — safety screening for OT session continuation",
      "Pattern maps: escalation and transport decision map — when OT defers, escalates, or continues session",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate"],
  }, "occupational-therapy"),
  hiddenModuleForRoute({
    id: "pta-movement-injury-mechanics",
    slug: "movement-injury-mechanics",
    title: "Movement + Injury Mechanics",
    description: "PT-focused movement dysfunction recognition, injury pattern identification, ROM/strength assessment, gait observation, and rehab progression logic for physiotherapy learners.",
    professionKeys: ["pta"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.MOVEMENT_INJURY_MECHANICS,
    tags: ["physiotherapy", "movement-assessment", "injury-patterns", "gait", "rom", "rehab-progression", "red-flags"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: Movement assessment basics — joint mobility, active vs passive ROM, strength grading, functional movement screening, pain and instability differentiation",
      "Lessons: Range of motion basics — joint-specific normal ROM values, goniometry, end-feel classification, hypomobility vs hypermobility, functional ROM thresholds",
      "Lessons: Strength grading basics — MRC grading scale 0–5, gravity-eliminated positions, functional strength indicators, grading reliability",
      "Lessons: Gait observation basics — gait cycle phases, normal vs abnormal patterns, antalgic gait, Trendelenburg sign, steppage/foot drop gait, scissor gait",
      "Lessons: Pain vs weakness vs instability — clinical differentiation, provocation testing, joint stability screening, functional task correlation",
      "Lessons: Ankle sprain — inversion mechanism of injury, Ottawa ankle rules, lateral ligament complex, grading I–III, acute management and rehab progression phases",
      "Lessons: ACL injury — mechanism of injury valgus pivot contact and non-contact, Lachman test and anterior drawer test, effusion, instability, conservative vs surgical pathway",
      "Lessons: Rotator cuff injury — impingement vs tear, painful arc, supraspinatus, Neer sign and Hawkins-Kennedy test, strength deficits, functional limitation",
      "Lessons: Low back strain — mechanism, red flag screening including cauda equina, SLR test, postural assessment, acute vs chronic LBP management basics",
      "Lessons: Hip fracture recovery basics — ORIF and hemiarthroplasty, post-op precautions, weight-bearing status, transfer safety, functional mobility milestones",
      "Lessons: Red flags in PT assessment — cauda equina syndrome, spinal cord compromise, fracture suspicion, malignancy, vascular claudication, saddle anesthesia, bilateral LE weakness",
      "Lessons: Rehab progression — acute phase protection and RICE, mobility phase ROM restoration, strengthening phase progressive resistance, return to function sport and task-specific goals",
      "Quizzes: injury pattern recognition from mechanism and physical findings, ROM limitation interpretation, gait abnormality recognition, safe rehab progression decisions, red flag identification and referral criteria",
      "Cases: ankle inversion injury — 22-year-old soccer player, immediate lateral ankle swelling, limited ROM, movementFindings Json: mechanism=inversion, swelling=lateral ankle, ROM=dorsiflexion 12°, strength=4/5 eversion, Ottawa rules applied, imageUrl for lateral ankle ROM assessment posture",
      "Cases: suspected ACL injury — 18-year-old basketball player, non-contact pivot mechanism, immediate instability, effusion, positive Lachman test, movementFindings Json: mechanism=valgus pivot non-contact, Lachman=positive, effusion=moderate, ROM=flexion 105° extension lag 5°, strength=3/5 quadriceps",
      "Cases: shoulder impingement and rotator cuff pattern — 45-year-old overhead worker, painful arc 70°–120°, Neer positive, Hawkins-Kennedy positive, movementFindings Json: painful arc=70-120°, Neer=positive, Hawkins-Kennedy=positive, ROM=abduction 140°, strength=4-/5 supraspinatus, imageUrl for posture and shoulder ROM assessment",
      "Cases: post-hip-fracture mobility limitation — 74-year-old post-ORIF left hip, non-weight-bearing, transfer requires maximum assist, movementFindings Json: weight-bearing=NWB left, transfer assist=maximum, gait=wheelchair-dependent, hip precautions=active post-op",
      "Cases: low back pain with red flag screening — 58-year-old, 6-week LBP, new bowel and bladder changes, bilateral LE weakness, saddle anesthesia, movementFindings Json: SLR=positive bilateral, LE strength=3/5 bilateral, saddle anesthesia=present, cauda equina red flag confirmed",
      "Cases: abnormal gait after stroke — 66-year-old post-CVA, right hemiplegia, steppage foot drop gait pattern, videoUrl for gait pattern recognition, movementFindings Json: gait=steppage right foot drop, Trendelenburg=absent, balance=moderate impairment, LE strength=3/5 right",
      "Rapid drills: Knee pop + swelling + instability — likely pattern?",
      "Rapid drills: Foot drop during swing phase — gait concern?",
      "Rapid drills: Painful arc with shoulder abduction 70°–120° — likely structure?",
      "Rapid drills: Hip fracture post-op + dizziness standing — priority?",
      "Rapid drills: Low back pain + new bowel and bladder changes — red flag?",
      "Rapid drills: Positive Lachman + effusion + non-contact mechanism — likely injury?",
      "Rapid drills: Antalgic gait with decreased stance phase — primary cause?",
      "Rapid drills: Saddle anesthesia + bilateral LE weakness — urgency level?",
      "Rapid drills: Supraspinatus weakness + painful arc 70°–120° — likely structure?",
      "Rapid drills: ROM limited passive dorsiflexion 12° + lateral ankle swelling — likely structure?",
      "Rapid drills: Post-ORIF hip patient attempts unsupported weight-bearing — priority?",
      "Rapid drills: MRC strength grade 2/5 quadriceps — functional meaning?",
      "Pattern maps: injury mechanism to likely structure map — inversion, valgus, overhead, axial loading, hyperextension",
      "Pattern maps: gait abnormality map — antalgic, Trendelenburg, steppage/foot drop, scissor, circumduction patterns",
      "Pattern maps: ROM limitation map — joint-specific, hypomobility vs hypermobility, end-feel classification, functional impact",
      "Pattern maps: red flag escalation map — cauda equina, spinal cord compromise, fracture suspicion, malignancy, vascular claudication",
      "Pattern maps: rehab progression map — acute phase to mobility to strengthening to return-to-function milestones and progression criteria",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate/refer"],
  }, "physiotherapy"),
  hiddenModuleForRoute({
    id: "ota-functional-assessment-adl-safety",
    slug: "functional-assessment-adl-safety",
    title: "Functional Assessment + ADL Safety",
    description: "OT-focused functional ability assessment, ADL/IADL safety, cognitive barriers, environmental risk, adaptive equipment, and care-planning priorities for occupational therapy learners.",
    professionKeys: ["ota"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.FUNCTIONAL_ASSESSMENT_ADL_SAFETY,
    tags: ["occupational-therapy", "adl", "iadl", "functional-assessment", "safety", "cognition", "adaptive-equipment", "discharge-planning"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: OT role in functional assessment — occupational profile, ICF model, top-down vs bottom-up approach, function-first screening",
      "Lessons: Activities of Daily Living — bathing, dressing, toileting, feeding, transfers, mobility basics — assessment, assistance grading, safety",
      "Lessons: Instrumental Activities of Daily Living — meal preparation, medication management, finances, transportation, home management — assessment and goal-setting",
      "Lessons: Cognition and safety — attention, memory, executive function, safety awareness, task sequencing, impulsivity, judgment during ADL",
      "Lessons: Visual neglect and perceptual deficits — unilateral spatial neglect, visual field loss, figure-ground, depth perception, mealtime and dressing implications",
      "Lessons: Falls risk and environmental assessment — intrinsic vs extrinsic risk factors, bathroom hazards, threshold risks, lighting, grab bars, fall prevention",
      "Lessons: Adaptive equipment basics — reachers, dressing aids, bath seats, raised toilet seats, one-handed techniques, equipment trial and training",
      "Lessons: Energy conservation basics — pacing, activity scheduling, work simplification, COPD and cardiac ADL implications, fatigue management",
      "Lessons: Goal-writing basics — SMART goals, client-centered approach, measurable ADL/IADL outcomes, long-term vs short-term goal structure",
      "Lessons: Discharge planning considerations — functional safety threshold, support system assessment, home modification vs higher-level care, interdisciplinary communication",
      "Quizzes: ADL vs IADL recognition, safety risk recognition, adaptive equipment matching, cognitive barrier identification, discharge planning decisions, functional deficit interpretation",
      "Cases: post-stroke dressing difficulty with neglect — 68-year-old post-CVA, left-sided neglect, unable to dress independently, functionalTaskData Json: task=dressing, deficit=left unilateral spatial neglect, assistance=moderate, safety risk=fall risk during standing dressing, cognitiveFindings Json: neglect=left unilateral spatial, safety awareness=impaired",
      "Cases: older adult fall risk at home — 79-year-old, recent bathroom fall, uses walker, cluttered environment, functionalTaskData Json: task=bathroom mobility, deficit=balance impairment, assistance=contact guard, safety risk=high fall risk, environmentFindings Json: bathroom=no grab bars, threshold=trip hazard, lighting=inadequate",
      "Cases: COPD patient needing energy conservation — 72-year-old COPD GOLD 3, dyspnea on bathing and dressing, functionalTaskData Json: task=bathing and dressing, deficit=exertional dyspnea, assistance=supervision, safety risk=moderate exertional risk",
      "Cases: cognitive impairment affecting medication management — 82-year-old early dementia, medication errors, functionalTaskData Json: task=medication management, deficit=memory and sequencing, assistance=moderate, safety risk=medication error high, cognitiveFindings Json: memory=impaired, executive function=impaired, safety awareness=limited",
      "Cases: hip fracture transfer safety — 76-year-old post-ORIF right hip, non-weight-bearing, unsafe transfer attempt without assistance, functionalTaskData Json: task=bed-to-chair transfer, deficit=weight-bearing restriction, assistance=maximum, safety risk=fall and surgical complication",
      "Cases: low vision affecting kitchen safety — 67-year-old macular degeneration, unsafe stovetop use, functionalTaskData Json: task=meal preparation, deficit=reduced central vision, assistance=supervision, safety risk=burn injury high, environmentFindings Json: stove=hazard without adaptation, lighting=inadequate, contrast=insufficient",
      "Cases: discharge planning after functional decline — 84-year-old post-hospital functional decline, global ADL impairment, videoUrl for task performance assessment, functionalTaskData Json: task=multiple ADLs, deficit=global decline bathing/dressing/transfers, assistance=substantial, safety risk=high, discharge planning=pending",
      "Rapid drills: Needs help bathing and dressing — ADL or IADL?",
      "Rapid drills: Forgets stove on — main concern?",
      "Rapid drills: Left-sided neglect during dressing — likely issue?",
      "Rapid drills: Short of breath while showering — best strategy category?",
      "Rapid drills: Unsafe transfer after hip fracture — priority?",
      "Rapid drills: Medication errors with complex pill schedule — main functional barrier?",
      "Rapid drills: No grab bars in bathtub and recent fall — priority environmental recommendation?",
      "Rapid drills: Global ADL decline after hospitalization — discharge destination priority?",
      "Rapid drills: Low vision affecting stove safety — OT priority intervention?",
      "Rapid drills: Client unable to manage finances independently — ADL or IADL concern?",
      "Rapid drills: OT observes unsafe stair transfer — priority action?",
      "Rapid drills: Caregiver asks when client can shower alone — OT priority?",
      "Pattern maps: ADL vs IADL map — categorization, independence continuum, safety thresholds, goal-setting framework",
      "Pattern maps: functional deficit to intervention map — adaptive equipment, environmental modification, technique training, goal adaptation pathway",
      "Pattern maps: cognition to safety risk map — attention, memory, executive function, neglect, safety awareness thresholds and OT response",
      "Pattern maps: home hazard assessment map — bathroom, kitchen, stair, floor, lighting, threshold risk categories and modification priorities",
      "Pattern maps: functional decline to discharge planning map — safety threshold, support availability, modification potential, care level recommendation",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate/refer"],
  }, "occupational-therapy"),
  hiddenModule({
    id: "paramedic-emergency-pattern-recognition",
    slug: "emergency-pattern-recognition",
    title: "Emergency Pattern Recognition",
    description: "Rapid prehospital pattern recognition from vitals, symptoms, lung sounds, ECG, and trauma context for EMS learners.",
    professionKeys: ["paramedic"],
    level: "advanced",
    entitlementKey: ALLIED_MASTERY_ENTITLEMENTS.EMERGENCY_PATTERN_RECOGNITION,
    tags: ["paramedic", "ems", "triage", "shock", "trauma", "ecg", "rapid-drills", "emergency"],
    contentTypes: allContentTypes,
    sections: [
      "Lessons: scene size-up basics — hazard identification, mechanism of injury, number of patients, resource needs",
      "Lessons: primary survey recap — ABCDE approach, life threat priority, immediate interventions",
      "Lessons: shock pattern recognition — distributive, hypovolemic, obstructive, cardiogenic, compensated vs decompensated",
      "Lessons: respiratory emergency recognition — upper airway obstruction, bronchospasm, tension pneumothorax, pulmonary edema",
      "Lessons: cardiac emergency recognition — STEMI patterns, life-threatening dysrhythmias, cardiac arrest cues",
      "Lessons: altered LOC patterns — GCS, AEIOU-TIPS differential, stroke vs hypoglycemia vs overdose",
      "Lessons: trauma red flags — mechanism severity, hemorrhage class, spinal risk, tension pneumo suspicion",
      "Lessons: sepsis recognition — prehospital sepsis criteria, vital sign clusters, fever, altered LOC, organ dysfunction cues",
      "Lessons: pediatric deterioration basics — age-appropriate vitals, work of breathing assessment, compensated vs decompensated shock",
      "Lessons: when to transport and escalate — priority transport triggers, load-and-go vs stay-and-play, ALS vs BLS decision",
      "Quizzes: pattern recognition from vitals, matching symptoms to likely emergency, identifying priority action, ECG/audio-based recognition, red flag recognition",
      "Cases: anaphylaxis with stridor and wheezing — HR 138, BP 74/40, RR 28, SpO2 88%, ClinicalMedia audio lung sounds",
      "Cases: septic shock pattern — HR 124, BP 82/50, RR 26, SpO2 94%, Temp 38.9°C, altered LOC, suspected source",
      "Cases: STEMI pattern — HR 88, BP 104/68, RR 18, SpO2 96%, ClinicalMedia ECG with ST elevation in leads II III aVF",
      "Cases: opioid overdose with hypoventilation — RR 5, HR 58, BP 100/64, SpO2 82%, pinpoint pupils, no response",
      "Cases: tension pneumothorax suspicion — absent unilateral breath sounds after chest trauma, HR 142, BP 72/44, tracheal deviation",
      "Cases: stroke recognition — unilateral weakness, facial droop, slurred speech, glucose 5.4 mmol/L, FAST positive",
      "Cases: major hemorrhage and hypovolemic shock — HR 146, BP 68/42, cool pale clammy skin, mechanism of injury",
      "Cases: pediatric respiratory distress — age-appropriate tachycardia and tachypnea, nasal flaring, retractions, SpO2 91%, ClinicalMedia audio",
      "Rapid drills: BP 78/44 + HR 142 + cool clammy skin — likely pattern?",
      "Rapid drills: stridor after allergen exposure — priority concern?",
      "Rapid drills: RR 8 + pinpoint pupils — likely emergency?",
      "Rapid drills: chest pain + ST elevation on ECG — concern?",
      "Rapid drills: unilateral weakness + slurred speech — priority action?",
      "Rapid drills: absent breath sounds after trauma — suspect?",
      "Rapid drills: fever + HR 118 + BP 88/54 + RR 24 — likely pattern?",
      "Rapid drills: SpO2 88% + wheezing + allergen exposure — first action?",
      "Rapid drills: altered LOC + glucose 1.8 mmol/L — priority?",
      "Rapid drills: infant HR 60 + poor skin perfusion — concern?",
      "Rapid drills: penetrating chest trauma + hypotension + JVD — suspect?",
      "Rapid drills: loss of radial pulse after trauma — hemodynamic significance?",
      "Rapid drills: STEMI pattern + BP 84/52 — transport priority?",
      "Rapid drills: SpO2 falling + bilateral crackles — likely pattern?",
      "Rapid drills: GCS 8 + unequal pupils — escalation priority?",
      "Rapid drills: pediatric nasal flaring + retractions + SpO2 91% — pattern and action?",
      "Pattern maps: shock pattern map — distributive vs hypovolemic vs obstructive vs cardiogenic signs",
      "Pattern maps: respiratory emergency map — upper vs lower airway, oxygenation vs ventilation failure escalation",
      "Pattern maps: cardiac emergency map — STEMI recognition, dysrhythmia priority, cardiac arrest pathway",
      "Pattern maps: altered LOC differential map — AEIOU-TIPS, stroke vs hypoglycemia vs overdose vs trauma",
      "Pattern maps: trauma red flag map — mechanism severity, hemorrhage class, tension pneumo, spinal risk, transport triggers",
      "Pattern maps: transport and escalation decision map — priority levels, destination decision, ALS vs BLS criteria",
    ],
    actionLayer: ["What is happening?", "Why it matters", "What to assess", "What to do first", "When to escalate/transport"],
  }),
];

export function isAlliedMasteryModulesPublicEnabled(env: Record<string, string | undefined> = process.env): boolean {
  const raw = env[ENABLE_ALLIED_MASTERY_MODULES_FLAG]?.trim().toLowerCase();
  return raw === "1" || raw === "true";
}

export function isAdminModulePreviewEnabled(env: Record<string, string | undefined> = process.env): boolean {
  const raw = env[ENABLE_ADMIN_MODULE_PREVIEW_FLAG]?.trim().toLowerCase();
  return raw == null || raw === "" || raw === "1" || raw === "true";
}

export function alliedMasteryModulesForProfession(professionKey: string): AlliedMasteryModule[] {
  return ALLIED_MASTERY_MODULES.filter((module) => module.professionKeys.includes(professionKey));
}

export function findAlliedMasteryModule(professionKey: string, moduleSlug: string): AlliedMasteryModule | null {
  return ALLIED_MASTERY_MODULES.find((module) => module.slug === moduleSlug && module.professionKeys.includes(professionKey)) ?? null;
}

export function groupedAlliedMasteryModules(): Array<{ professionKey: string; professionLabel: string; modules: AlliedMasteryModule[] }> {
  return Object.entries(ALLIED_MASTERY_PROFESSION_LABELS).map(([professionKey, professionLabel]) => ({
    professionKey,
    professionLabel,
    modules: alliedMasteryModulesForProfession(professionKey),
  }));
}
