/**
 * GCC — English SEO topics for UAE + Saudi Arabia.
 *
 * Content types:
 * - **A**: US NCLEX-RN seekers (practice hub: `/us/rn/nclex-rn/...`)
 * - **C**: Hybrid / migration + licensing literacy (UAE DOH/DHA/HAAD-style *titles* reflect
 *   common search language; articles must verify current regulator names/rules — NurseNest
 *   does not claim to be an official Gulf regulator prep product unless separately launched).
 */

import type { GlobalLocaleCode, GlobalRegionSlug } from "@/lib/i18n/global-regions";

export type GxGccContentType = "A" | "C";
export type GxGccSearchIntent = "transactional" | "informational" | "comparison";

export type GxGccEnTopic = {
  id: string;
  region: GlobalRegionSlug;
  locale: GlobalLocaleCode;
  contentType: GxGccContentType;
  examContext: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  slug: string;
  primaryKeyword: string;
  searchIntent: GxGccSearchIntent;
};

export const GEXP_HUB_US_NCLEX_RN = {
  lessons: "/us/rn/nclex-rn/lessons",
  questions: "/us/rn/nclex-rn/questions",
  cat: "/us/rn/nclex-rn/cat",
  pricing: "/us/rn/nclex-rn/pricing",
} as const;

export const GEXP_GCC_EN_TOPICS: GxGccEnTopic[] = [
  // ── UAE (20) ───────────────────────────────────────────────────────────────
  { id: "gx-ae-en-01", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "Dubai Nurse to US RN: When NCLEX-RN Becomes the Bottleneck (and When It Does Not)", metaTitle: "Dubai Nurse US RN NCLEX Bottleneck UAE | NurseNest", metaDescription: "If you work in the UAE and want US RN licensure, NCLEX-RN is the US exam step—not a UAE health authority exam. A realistic sequencing guide.", slug: "dubai-nurse-us-rn-nclex-bottleneck-uae", primaryKeyword: "Dubai nurse US RN NCLEX", searchIntent: "informational" },
  { id: "gx-ae-en-02", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "Pearson VUE NCLEX from the UAE: Travel vs Local Scheduling Tradeoffs", metaTitle: "Pearson VUE NCLEX UAE Travel vs Local | NurseNest", metaDescription: "UAE residents often choose between regional Pearson centers and travel options. A decision checklist—plus how to keep NCLEX training on the US hub.", slug: "pearson-vue-nclex-uae-travel-vs-local", primaryKeyword: "Pearson VUE NCLEX UAE scheduling", searchIntent: "comparison" },
  { id: "gx-ae-en-03", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Pharmacology for Filipino Nurses in the UAE: US Brand Names on Items", metaTitle: "NCLEX Pharmacology UAE Filipino US Brands | NurseNest", metaDescription: "Many UAE hospital nurses trained in the Philippines still need US brand recognition for NCLEX-RN. A high-yield drug class map and practice approach.", slug: "nclex-pharmacology-uae-filipino-us-brands", primaryKeyword: "NCLEX pharmacology UAE Filipino nurse", searchIntent: "transactional" },
  { id: "gx-ae-en-04", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Delegation Questions: US Scope vs Busy UAE Ward Realities", metaTitle: "NCLEX Delegation UAE vs US Scope | NurseNest", metaDescription: "Delegation on NCLEX follows US nurse practice act framing. Practice it as exam logic—not as a critique of any hospital’s staffing model.", slug: "nclex-delegation-uae-us-scope-ward", primaryKeyword: "NCLEX delegation UAE US scope", searchIntent: "informational" },
  { id: "gx-ae-en-05", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX SATA After 12-Hour Shifts in Abu Dhabi: Fatigue-Proof Drills", metaTitle: "NCLEX SATA UAE 12 Hour Shifts | NurseNest", metaDescription: "SATA needs calm completeness checks. A drill format for UAE shift workers preparing for US NCLEX-RN.", slug: "nclex-sata-uae-12-hour-shifts-fatigue", primaryKeyword: "NCLEX SATA UAE night shift", searchIntent: "transactional" },
  { id: "gx-ae-en-06", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "From UAE Hospital Nurse to US Med-Surg: What NCLEX Tests Before You Ever Chart in Epic", metaTitle: "UAE Nurse US Med-Surg NCLEX | NurseNest", metaDescription: "NCLEX-RN is not hospital software training—but it tests safety and prioritization you will need. A bridge plan for UAE-based candidates.", slug: "uae-hospital-nurse-us-med-surg-nclex-bridge", primaryKeyword: "UAE nurse US med surg NCLEX", searchIntent: "informational" },
  { id: "gx-ae-en-07", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Infection Control: Contact vs Droplet vs Airborne in US Item Logic", metaTitle: "NCLEX Infection Control UAE Airborne Droplet | NurseNest", metaDescription: "Isolation precautions are a major NCLEX theme. Train US logic with practice items and lessons on the US RN hub.", slug: "nclex-infection-control-uae-isolation-us-logic", primaryKeyword: "NCLEX infection control UAE", searchIntent: "informational" },
  { id: "gx-ae-en-08", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX OB Hemorrhage Chains: High-Yield Practice for Labor-Heavy UAE Nurses", metaTitle: "NCLEX OB Hemorrhage UAE Labor Nurse | NurseNest", metaDescription: "If your UAE practice is high-volume OB, leverage it—but still learn US exam phrasing and escalation wording for NCLEX-RN.", slug: "nclex-ob-hemorrhage-uae-labor-nurse", primaryKeyword: "NCLEX OB hemorrhage UAE", searchIntent: "transactional" },
  { id: "gx-ae-en-09", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Mental Health: Therapeutic Communication Boundaries US Items Love", metaTitle: "NCLEX Therapeutic Communication UAE | NurseNest", metaDescription: "Therapeutic communication is rule-based on NCLEX. Practice boundaries, autonomy, and safety-first responses.", slug: "nclex-therapeutic-communication-uae-boundaries", primaryKeyword: "NCLEX therapeutic communication UAE", searchIntent: "informational" },
  { id: "gx-ae-en-10", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Lab Value Items: BMP/CBC Patterns Without Memorizing Every Reference Range", metaTitle: "NCLEX Lab Values UAE BMP CBC | NurseNest", metaDescription: "Lab interpretation on NCLEX is pattern-based. Build a drill workflow for common abnormalities seen in US-style stems.", slug: "nclex-lab-values-uae-bmp-cbc-patterns", primaryKeyword: "NCLEX lab values UAE", searchIntent: "informational" },
  { id: "gx-ae-en-11", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Cardiac: ACS, Troponin Sequences, and Patient Education After PCI", metaTitle: "NCLEX Cardiac UAE ACS PCI | NurseNest", metaDescription: "Acute coronary syndrome management is a classic NCLEX cluster. Train sequences and teaching points.", slug: "nclex-cardiac-uae-acs-pci-education", primaryKeyword: "NCLEX cardiac UAE ACS", searchIntent: "informational" },
  { id: "gx-ae-en-12", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Renal: Dialysis Hypotension, Cramping, and Fluid/Sodium Teaching", metaTitle: "NCLEX Dialysis UAE Hypotension | NurseNest", metaDescription: "Dialysis complications are frequent exam topics. Practice interventions and patient teaching loops.", slug: "nclex-dialysis-uae-hypotension-teaching", primaryKeyword: "NCLEX dialysis UAE hypotension", searchIntent: "informational" },
  { id: "gx-ae-en-13", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Respiratory: COPD Exacerbation and Oxygen Safety Teaching", metaTitle: "NCLEX COPD UAE Oxygen Safety | NurseNest", metaDescription: "COPD management includes oxygen titration teaching. Drill US-style priorities.", slug: "nclex-copd-uae-oxygen-safety", primaryKeyword: "NCLEX COPD UAE oxygen", searchIntent: "informational" },
  { id: "gx-ae-en-14", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Pediatrics: Dehydration, Shock Signs, and Parent Teaching", metaTitle: "NCLEX Pediatric Dehydration UAE | NurseNest", metaDescription: "Pediatric shock and dehydration scenarios test escalation and teaching. Practice on the US RN hub.", slug: "nclex-pediatric-dehydration-uae-shock", primaryKeyword: "NCLEX pediatric dehydration UAE", searchIntent: "informational" },
  { id: "gx-ae-en-15", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Endocrine: DKA vs HHS Priorities and Insulin Safety", metaTitle: "NCLEX DKA HHS UAE Insulin | NurseNest", metaDescription: "Endocrine emergencies are classic judgment chains. Compare DKA and HHS management patterns.", slug: "nclex-dka-hhs-uae-insulin-safety", primaryKeyword: "NCLEX DKA HHS UAE", searchIntent: "informational" },
  { id: "gx-ae-en-16", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX GI: Bowel Obstruction, NG Tubes, and Complication Monitoring", metaTitle: "NCLEX Bowel Obstruction UAE NG Tube | NurseNest", metaDescription: "GI nursing scenarios combine assessment with interventions. Train monitoring priorities.", slug: "nclex-bowel-obstruction-uae-ng-tube", primaryKeyword: "NCLEX bowel obstruction UAE", searchIntent: "informational" },
  { id: "gx-ae-en-17", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Neurology: Stroke Care Timelines and Post-tPA Monitoring", metaTitle: "NCLEX Stroke UAE tPA Monitoring | NurseNest", metaDescription: "Stroke items emphasize time-sensitive actions and monitoring. Practice without overfitting to one hospital protocol name.", slug: "nclex-stroke-uae-tpa-monitoring", primaryKeyword: "NCLEX stroke UAE tPA", searchIntent: "informational" },
  { id: "gx-ae-en-18", region: "uae", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX CAT Practice: Interpreting Difficulty Shifts Without Panic", metaTitle: "NCLEX CAT UAE Difficulty Shifts | NurseNest", metaDescription: "Adaptive exams feel personal. Learn what difficulty changes do and do not mean while practicing on NurseNest CAT.", slug: "nclex-cat-uae-difficulty-shifts", primaryKeyword: "NCLEX CAT UAE adaptive", searchIntent: "transactional" },
  { id: "gx-ae-en-19", region: "uae", locale: "en", contentType: "C", examContext: "UAE licensing literacy + optional US NCLEX", title: "UAE Health Authority Exams vs US NCLEX-RN: Different Regulators, Different Blueprints", metaTitle: "UAE Health Authority Exam vs US NCLEX | NurseNest", metaDescription: "High-intent comparison: UAE licensing processes are not interchangeable with NCLEX-RN. If your goal is US RN licensure, train NCLEX on the US hub—verify Gulf requirements separately.", slug: "uae-health-authority-exam-vs-us-nclex-rn", primaryKeyword: "UAE health authority exam vs NCLEX", searchIntent: "comparison" },
  { id: "gx-ae-en-20", region: "uae", locale: "en", contentType: "C", examContext: "Migration literacy", title: "Dataflow + Credentialing for UAE Nurses: What “Primary Source Verification” Means for US Boards", metaTitle: "Dataflow Credentialing UAE Nurse US Board | NurseNest", metaDescription: "Credentialing vocabulary matters for timelines. This is not legal advice—verify with your board and evaluation service—but it helps you ask the right questions.", slug: "dataflow-credentialing-uae-nurse-us-board", primaryKeyword: "Dataflow UAE nurse US board", searchIntent: "informational" },

  // ── Saudi Arabia (20) ───────────────────────────────────────────────────────
  { id: "gx-sa-en-01", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "Saudi Arabia Hospital Nurse to US RN: NCLEX-RN Prep While Working KSA Shifts", metaTitle: "Saudi Hospital Nurse US RN NCLEX Prep | NurseNest", metaDescription: "KSA-based nurses preparing for US NCLEX-RN: shift-aware study blocks and practice on the US RN hub.", slug: "saudi-hospital-nurse-us-rn-nclex-shift-prep", primaryKeyword: "Saudi nurse US RN NCLEX prep", searchIntent: "transactional" },
  { id: "gx-sa-en-02", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Pharmacology in KSA: US Brand Names That Show Up on Exam Items", metaTitle: "NCLEX Pharmacology Saudi US Brands | NurseNest", metaDescription: "Pharmacology for NCLEX-RN is often US-labeled. Build recognition drills while working in Saudi Arabia.", slug: "nclex-pharmacology-saudi-arabia-us-brands", primaryKeyword: "NCLEX pharmacology Saudi Arabia US brands", searchIntent: "informational" },
  { id: "gx-sa-en-03", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Infection Control: MRSA, C.diff, and Contact Precautions in US Item Language", metaTitle: "NCLEX MRSA C.diff Saudi Contact Precautions | NurseNest", metaDescription: "Train transmission precautions the way NCLEX frames them—then apply your clinical experience from KSA hospitals as context, not as a distractor.", slug: "nclex-mrsa-cdiff-saudi-contact-precautions", primaryKeyword: "NCLEX MRSA C.diff Saudi Arabia", searchIntent: "informational" },
  { id: "gx-sa-en-04", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Delegation and Chain of Command: What US Items Want First", metaTitle: "NCLEX Chain of Command Saudi | NurseNest", metaDescription: "Chain-of-command scenarios test patient safety escalation. Practice US exam norms on NurseNest.", slug: "nclex-chain-of-command-saudi-arabia", primaryKeyword: "NCLEX chain of command Saudi Arabia", searchIntent: "informational" },
  { id: "gx-sa-en-05", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX SATA Weekly Plan for Nurses Working 6 Days per Week in Riyadh", metaTitle: "NCLEX SATA Weekly Plan Riyadh Nurse | NurseNest", metaDescription: "A sustainable weekly SATA plan: short daily completeness drills plus one longer block.", slug: "nclex-sata-weekly-plan-riyadh-nurse", primaryKeyword: "NCLEX SATA weekly plan Riyadh", searchIntent: "transactional" },
  { id: "gx-sa-en-06", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX OB: Preeclampsia, Magnesium Toxicity, and Fetal Assessment Priorities", metaTitle: "NCLEX Preeclampsia Saudi Magnesium | NurseNest", metaDescription: "OB emergencies are classic NCLEX chains. Train priorities and monitoring.", slug: "nclex-preeclampsia-saudi-magnesium", primaryKeyword: "NCLEX preeclampsia Saudi Arabia", searchIntent: "informational" },
  { id: "gx-sa-en-07", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Pediatrics: Febrile Seizures, Fever Teaching, and Red Flags", metaTitle: "NCLEX Febrile Seizures Saudi Pediatrics | NurseNest", metaDescription: "Pediatric fever scenarios test parent teaching and escalation. Practice US-style responses.", slug: "nclex-febrile-seizures-saudi-pediatrics", primaryKeyword: "NCLEX febrile seizures Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-08", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Respiratory: Pneumonia, Oxygen Delivery, and Aspiration Risk", metaTitle: "NCLEX Pneumonia Saudi Oxygen | NurseNest", metaDescription: "Respiratory management items combine assessment with oxygen safety. Drill device selection.", slug: "nclex-pneumonia-saudi-oxygen-aspiration", primaryKeyword: "NCLEX pneumonia Saudi oxygen", searchIntent: "informational" },
  { id: "gx-sa-en-09", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Cardiac: Heart Failure Exacerbation Teaching Loops", metaTitle: "NCLEX Heart Failure Saudi Teaching | NurseNest", metaDescription: "Heart failure teaching is a staple: daily weights, sodium, meds—practice explaining and monitoring.", slug: "nclex-heart-failure-saudi-teaching-loops", primaryKeyword: "NCLEX heart failure Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-10", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Renal: AKI vs CKD and Dialysis Teaching Priorities", metaTitle: "NCLEX AKI CKD Saudi Dialysis | NurseNest", metaDescription: "Renal items love acute vs chronic framing. Build compare/contrast notes.", slug: "nclex-aki-ckd-saudi-dialysis-teaching", primaryKeyword: "NCLEX AKI CKD Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-11", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Diabetes: Hypoglycemia Rescue, Insulin Safety, and Sick-Day Teaching", metaTitle: "NCLEX Hypoglycemia Saudi Insulin | NurseNest", metaDescription: "Diabetes management is high frequency. Drill safe sequences and patient teaching.", slug: "nclex-hypoglycemia-saudi-insulin-sick-day", primaryKeyword: "NCLEX hypoglycemia Saudi insulin", searchIntent: "informational" },
  { id: "gx-sa-en-12", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Fluids and Electrolytes: Potassium Replacement Monitoring", metaTitle: "NCLEX Potassium Saudi Replacement | NurseNest", metaDescription: "Electrolyte replacement items test safety monitoring and provider communication.", slug: "nclex-potassium-saudi-replacement-monitoring", primaryKeyword: "NCLEX potassium Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-13", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX GI: Upper GI Bleed Assessment and Resuscitation Thinking", metaTitle: "NCLEX GI Bleed Saudi Assessment | NurseNest", metaDescription: "GI bleed scenarios combine assessment with stabilization priorities.", slug: "nclex-gi-bleed-saudi-assessment-resuscitation", primaryKeyword: "NCLEX GI bleed Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-14", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Hematology: Transfusion Reactions and First Actions", metaTitle: "NCLEX Transfusion Reaction Saudi | NurseNest", metaDescription: "Transfusion safety is highly testable. Drill reaction types and immediate nursing actions.", slug: "nclex-transfusion-reaction-saudi-first-actions", primaryKeyword: "NCLEX transfusion reaction Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-15", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Oncology: Neutropenic Fever and Rapid Assessment", metaTitle: "NCLEX Neutropenic Fever Saudi | NurseNest", metaDescription: "Neutropenic fever is an emergency pattern on exams. Practice triage language.", slug: "nclex-neutropenic-fever-saudi-triage", primaryKeyword: "NCLEX neutropenic fever Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-16", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Ethics: Capacity, Consent, and Refusal Documentation Patterns", metaTitle: "NCLEX Consent Capacity Saudi | NurseNest", metaDescription: "Ethics items are structured. Practice consent elements and nurse responsibilities.", slug: "nclex-consent-capacity-saudi-refusal", primaryKeyword: "NCLEX consent capacity Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-17", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Geriatrics: Falls, Bone Health, and Vision Safety Teaching", metaTitle: "NCLEX Falls Saudi Geriatrics | NurseNest", metaDescription: "Geriatric safety topics appear as teaching + monitoring combinations.", slug: "nclex-falls-saudi-geriatrics-teaching", primaryKeyword: "NCLEX falls Saudi geriatrics", searchIntent: "informational" },
  { id: "gx-sa-en-18", region: "saudi-arabia", locale: "en", contentType: "A", examContext: "US NCLEX-RN", title: "NCLEX Leadership: Unsafe Orders, Clarification, and Escalation", metaTitle: "NCLEX Unsafe Orders Saudi Escalation | NurseNest", metaDescription: "Practice clarifying unsafe orders and escalating per US exam expectations.", slug: "nclex-unsafe-orders-saudi-escalation", primaryKeyword: "NCLEX unsafe orders Saudi", searchIntent: "informational" },
  { id: "gx-sa-en-19", region: "saudi-arabia", locale: "en", contentType: "C", examContext: "SCFHS / Prometric literacy (verify current rules)", title: "Saudi Prometric Nursing Exams vs US NCLEX-RN: Do Not Study the Wrong Blueprint", metaTitle: "Saudi Prometric Nursing Exam vs NCLEX | NurseNest", metaDescription: "High-intent clarification: Saudi regulatory exams and US NCLEX-RN answer different authorities. Verify SCFHS/MOH requirements officially; use NurseNest for US NCLEX-RN practice.", slug: "saudi-prometric-nursing-exam-vs-us-nclex-rn", primaryKeyword: "Saudi Prometric exam vs NCLEX", searchIntent: "comparison" },
  { id: "gx-sa-en-20", region: "saudi-arabia", locale: "en", contentType: "C", examContext: "Migration literacy", title: "English Tests, NCLEX, and US Employer Petitions: A GCC Nurse’s Document Stack Mental Model", metaTitle: "English NCLEX US Petition GCC Nurse | NurseNest", metaDescription: "Not legal advice: organize English tests, NCLEX results, and employer verification requests as separate streams to reduce timeline thrash.", slug: "english-nclex-us-petition-gcc-nurse-document-stack", primaryKeyword: "GCC nurse NCLEX US petition documents", searchIntent: "informational" },
];
