/**
 * Bounded high-yield nursing glossary (MVP). Expand via editorial review — not autogenerated spam.
 */

export type NursingGlossaryTerm = {
  slug: string;
  term: string;
  definition: string;
  /** Canonical topic slug for lesson/question cross-links */
  topicSlug: string;
  relatedTermSlugs?: readonly string[];
};

export const NURSING_GLOSSARY_TERMS: readonly NursingGlossaryTerm[] = [
  {
    slug: "preload",
    term: "Preload",
    definition:
      "Ventricular end-diastolic volume — the stretch on the ventricle before contraction. Preload guides fluid administration and diuretic decisions in heart failure and shock.",
    topicSlug: "heart-failure",
    relatedTermSlugs: ["afterload", "cardiac-output"],
  },
  {
    slug: "afterload",
    term: "Afterload",
    definition:
      "Resistance the ventricle must overcome to eject blood (often reflected by systemic vascular resistance). Afterload rises in hypertension and can worsen heart failure workload.",
    topicSlug: "heart-failure",
    relatedTermSlugs: ["preload", "cardiac-output"],
  },
  {
    slug: "cardiac-output",
    term: "Cardiac output",
    definition:
      "Volume of blood pumped per minute (stroke volume × heart rate). Perfusion goals in shock and heart failure depend on cardiac output and tissue oxygen delivery.",
    topicSlug: "heart-failure",
    relatedTermSlugs: ["preload", "afterload"],
  },
  {
    slug: "heart-failure",
    term: "Heart failure",
    definition:
      "Inability of the heart to pump sufficiently to meet metabolic needs (or only with elevated filling pressures). Nursing care focuses on volume status, perfusion, medications, and daily monitoring.",
    topicSlug: "heart-failure",
  },
  {
    slug: "hyperkalemia",
    term: "Hyperkalemia",
    definition:
      "Serum potassium above the reference range. High risk for cardiac conduction changes; nursing priorities include ECG monitoring, medication review, and urgent escalation when critical.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["hypokalemia"],
  },
  {
    slug: "hypokalemia",
    term: "Hypokalemia",
    definition:
      "Low serum potassium. Can cause muscle weakness, ileus, and cardiac irritability; replacement requires route/rate safety and magnesium assessment.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["hyperkalemia"],
  },
  {
    slug: "sepsis",
    term: "Sepsis",
    definition:
      "Life-threatening organ dysfunction caused by a dysregulated host response to infection. Early recognition, cultures, fluids, antibiotics, and reassessment are time-critical nursing actions.",
    topicSlug: "sepsis",
  },
  {
    slug: "sirs",
    term: "SIRS",
    definition:
      "Systemic inflammatory response syndrome — historical screening criteria (temperature, HR, RR, WBC). Modern sepsis frameworks emphasize organ dysfunction and infection suspicion.",
    topicSlug: "sepsis",
  },
  {
    slug: "dka",
    term: "Diabetic ketoacidosis (DKA)",
    definition:
      "Acute hyperglycemia with ketosis and metabolic acidosis. Nursing care addresses fluids, insulin protocol, potassium timing, and airway/breathing monitoring.",
    topicSlug: "diabetic-ketoacidosis",
  },
  {
    slug: "siadh",
    term: "SIADH",
    definition:
      "Syndrome of inappropriate antidiuretic hormone — dilutional hyponatremia with concentrated urine. Fluid restriction and sodium trends guide nursing surveillance.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["diabetes-insipidus"],
  },
  {
    slug: "diabetes-insipidus",
    term: "Diabetes insipidus",
    definition:
      "Deficient ADH effect or renal resistance causing dilute urine and hypernatremia risk. Contrasts with SIADH on sodium, urine output, and volume status.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["siadh"],
  },
  {
    slug: "copd",
    term: "COPD",
    definition:
      "Chronic obstructive pulmonary disease — progressive airflow limitation. Nursing priorities include exacerbation recognition, oxygen titration, bronchodilator therapy, and CO₂ retention awareness.",
    topicSlug: "copd",
  },
  {
    slug: "abg",
    term: "Arterial blood gas (ABG)",
    definition:
      "Blood sample analyzing pH, PaCO₂, PaO₂, HCO₃⁻, and oxygenation. Used to classify acid-base disorders and guide respiratory support decisions.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "metabolic-acidosis",
    term: "Metabolic acidosis",
    definition:
      "Primary decrease in bicarbonate or increase in non-volatile acids (low pH with low HCO₃⁻). Causes include DKA, renal failure, lactic acidosis, and toxin ingestion.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "respiratory-acidosis",
    term: "Respiratory acidosis",
    definition:
      "Primary CO₂ retention (high PaCO₂). Seen in hypoventilation, COPD exacerbation, and sedative toxicity — nursing focuses on airway and ventilation support.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "stroke",
    term: "Stroke (CVA)",
    definition:
      "Acute focal neurologic deficit from brain ischemia or hemorrhage. Time-critical assessment, neuro checks, and stroke-team activation define nursing priorities.",
    topicSlug: "stroke",
  },
  {
    slug: "delegation",
    term: "Delegation",
    definition:
      "Transferring responsibility for a task while retaining accountability. Requires appropriate scope, competency, supervision, and five rights of delegation.",
    topicSlug: "delegation",
  },
  {
    slug: "prioritization",
    term: "Prioritization",
    definition:
      "Ordering nursing actions by urgency and risk. ABC framework and unstable-before-stable rules underpin NCLEX-style judgment.",
    topicSlug: "prioritization",
  },
  {
    slug: "anticoagulation",
    term: "Anticoagulation",
    definition:
      "Therapy that inhibits clot formation (e.g., heparin, warfarin, DOACs). Nursing care emphasizes bleeding precautions, monitoring, and patient teaching.",
    topicSlug: "anticoagulation",
  },
  {
    slug: "troponin",
    term: "Troponin",
    definition:
      "Cardiac biomarker indicating myocardial injury. Trending troponin with symptoms and ECG guides ACS evaluation and monitoring intensity.",
    topicSlug: "myocardial-infarction",
  },
  {
    slug: "map",
    term: "Mean arterial pressure (MAP)",
    definition:
      "Average arterial pressure during a cardiac cycle. Perfusion targets (often MAP ≥ 65 mmHg in shock) guide vasopressor therapy in critical care.",
    topicSlug: "shock",
  },
] as const;

export function getNursingGlossaryTerm(slug: string): NursingGlossaryTerm | undefined {
  const key = slug.trim().toLowerCase();
  return NURSING_GLOSSARY_TERMS.find((t) => t.slug === key);
}

export function listNursingGlossaryTerms(): NursingGlossaryTerm[] {
  return [...NURSING_GLOSSARY_TERMS];
}
