/**
 * Bounded high-yield nursing glossary. Expand via editorial review — not autogenerated spam.
 */
import { NURSING_GLOSSARY_EXPANSION_TERMS } from "@/lib/seo/nursing-glossary-expansion";
import { buildCompetencyGlossaryTerms } from "@/lib/seo/nursing-glossary-competency-generated";

export type NursingGlossaryTerm = {
  slug: string;
  term: string;
  definition: string;
  /** Canonical topic slug for lesson/question cross-links */
  topicSlug: string;
  relatedTermSlugs?: readonly string[];
};

const NURSING_GLOSSARY_CORE: readonly NursingGlossaryTerm[] = [
  {
    slug: "preload",
    term: "Preload",
    definition:
      "Ventricular end-diastolic volume — the stretch on the ventricle before contraction. Preload guides fluid administration and diuretic decisions in heart failure and shock.",
    topicSlug: "heart-failure",
    relatedTermSlugs: ["afterload", "cardiac-output"],
  },
  {
    slug: "afterload",
    term: "Afterload",
    definition:
      "Resistance the ventricle must overcome to eject blood (often reflected by systemic vascular resistance). Afterload rises in hypertension and can worsen heart failure workload.",
    topicSlug: "heart-failure",
    relatedTermSlugs: ["preload", "cardiac-output"],
  },
  {
    slug: "cardiac-output",
    term: "Cardiac output",
    definition:
      "Volume of blood pumped per minute (stroke volume × heart rate). Perfusion goals in shock and heart failure depend on cardiac output and tissue oxygen delivery.",
    topicSlug: "heart-failure",
    relatedTermSlugs: ["preload", "afterload"],
  },
  {
    slug: "heart-failure",
    term: "Heart failure",
    definition:
      "Inability of the heart to pump sufficiently to meet metabolic needs (or only with elevated filling pressures). Nursing care focuses on volume status, perfusion, medications, and daily monitoring.",
    topicSlug: "heart-failure",
  },
  {
    slug: "hyperkalemia",
    term: "Hyperkalemia",
    definition:
      "Serum potassium above the reference range. High risk for cardiac conduction changes; nursing priorities include ECG monitoring, medication review, and urgent escalation when critical.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["hypokalemia"],
  },
  {
    slug: "hypokalemia",
    term: "Hypokalemia",
    definition:
      "Low serum potassium. Can cause muscle weakness, ileus, and cardiac irritability; replacement requires route/rate safety and magnesium assessment.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["hyperkalemia"],
  },
  {
    slug: "sepsis",
    term: "Sepsis",
    definition:
      "Life-threatening organ dysfunction caused by a dysregulated host response to infection. Early recognition, cultures, fluids, antibiotics, and reassessment are time-critical nursing actions.",
    topicSlug: "sepsis",
  },
  {
    slug: "sirs",
    term: "SIRS",
    definition:
      "Systemic inflammatory response syndrome — historical screening criteria (temperature, HR, RR, WBC). Modern sepsis frameworks emphasize organ dysfunction and infection suspicion.",
    topicSlug: "sepsis",
  },
  {
    slug: "dka",
    term: "Diabetic ketoacidosis (DKA)",
    definition:
      "Acute hyperglycemia with ketosis and metabolic acidosis. Nursing care addresses fluids, insulin protocol, potassium timing, and airway/breathing monitoring.",
    topicSlug: "diabetic-ketoacidosis",
  },
  {
    slug: "siadh",
    term: "SIADH",
    definition:
      "Syndrome of inappropriate antidiuretic hormone — dilutional hyponatremia with concentrated urine. Fluid restriction and sodium trends guide nursing surveillance.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["diabetes-insipidus"],
  },
  {
    slug: "diabetes-insipidus",
    term: "Diabetes insipidus",
    definition:
      "Deficient ADH effect or renal resistance causing dilute urine and hypernatremia risk. Contrasts with SIADH on sodium, urine output, and volume status.",
    topicSlug: "fluid-balance",
    relatedTermSlugs: ["siadh"],
  },
  {
    slug: "copd",
    term: "COPD",
    definition:
      "Chronic obstructive pulmonary disease — progressive airflow limitation. Nursing priorities include exacerbation recognition, oxygen titration, bronchodilator therapy, and CO₂ retention awareness.",
    topicSlug: "copd",
  },
  {
    slug: "abg",
    term: "Arterial blood gas (ABG)",
    definition:
      "Blood sample analyzing pH, PaCO₂, PaO₂, HCO₃⁻, and oxygenation. Used to classify acid-base disorders and guide respiratory support decisions.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "metabolic-acidosis",
    term: "Metabolic acidosis",
    definition:
      "Primary decrease in bicarbonate or increase in non-volatile acids (low pH with low HCO₃⁻). Causes include DKA, renal failure, lactic acidosis, and toxin ingestion.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "respiratory-acidosis",
    term: "Respiratory acidosis",
    definition:
      "Primary CO₂ retention (high PaCO₂). Seen in hypoventilation, COPD exacerbation, and sedative toxicity — nursing focuses on airway and ventilation support.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "stroke",
    term: "Stroke (CVA)",
    definition:
      "Acute focal neurologic deficit from brain ischemia or hemorrhage. Time-critical assessment, neuro checks, and stroke-team activation define nursing priorities.",
    topicSlug: "stroke",
  },
  {
    slug: "delegation",
    term: "Delegation",
    definition:
      "Transferring responsibility for a task while retaining accountability. Requires appropriate scope, competency, supervision, and five rights of delegation.",
    topicSlug: "delegation",
  },
  {
    slug: "prioritization",
    term: "Prioritization",
    definition:
      "Ordering nursing actions by urgency and risk. ABC framework and unstable-before-stable rules underpin NCLEX-style judgment.",
    topicSlug: "prioritization",
  },
  {
    slug: "anticoagulation",
    term: "Anticoagulation",
    definition:
      "Therapy that inhibits clot formation (e.g., heparin, warfarin, DOACs). Nursing care emphasizes bleeding precautions, monitoring, and patient teaching.",
    topicSlug: "anticoagulation",
  },
  {
    slug: "troponin",
    term: "Troponin",
    definition:
      "Cardiac biomarker indicating myocardial injury. Trending troponin with symptoms and ECG guides ACS evaluation and monitoring intensity.",
    topicSlug: "myocardial-infarction",
  },
  {
    slug: "map",
    term: "Mean arterial pressure (MAP)",
    definition:
      "Average arterial pressure during a cardiac cycle. Perfusion targets (often MAP ≥ 65 mmHg in shock) guide vasopressor therapy in critical care.",
    topicSlug: "shock",
  },
  {
    slug: "lactic-acid",
    term: "Lactic acid / lactate",
    definition:
      "Marker of tissue hypoperfusion and anaerobic metabolism. Rising lactate in sepsis or shock signals escalation and reassessment of fluids and perfusion.",
    topicSlug: "sepsis",
    relatedTermSlugs: ["sepsis"],
  },
  {
    slug: "anion-gap",
    term: "Anion gap",
    definition:
      "Helps classify metabolic acidosis (elevated gap suggests lactate, ketones, or toxins). Nursing priority is perfusion, airway, and cause-directed treatment.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "insulin",
    term: "Insulin",
    definition:
      "Lowers blood glucose and drives potassium intracellularly. In DKA, insulin timing must align with potassium monitoring to avoid dangerous hypokalemia.",
    topicSlug: "diabetic-ketoacidosis",
  },
  {
    slug: "vasopressor",
    term: "Vasopressor",
    definition:
      "Medications that increase vascular tone and MAP in distributive or cardiogenic shock. Nursing focuses on perfusion endpoints, extravasation risk, and reassessment.",
    topicSlug: "shock",
  },
  {
    slug: "peep",
    term: "PEEP",
    definition:
      "Positive end-expiratory pressure maintains alveolar recruitment in respiratory failure. Changes affect oxygenation and hemodynamics — monitor closely after adjustments.",
    topicSlug: "respiratory-failure",
  },
  {
    slug: "fio2",
    term: "FiO₂",
    definition:
      "Fraction of inspired oxygen. Titrate to target saturation while avoiding hyperoxia and CO₂ retention in COPD or chronic CO₂ retainers.",
    topicSlug: "copd",
  },
  {
    slug: "inr",
    term: "INR",
    definition:
      "Standardized measure of warfarin effect. Supratherapeutic INR increases bleeding risk; subtherapeutic INR fails anticoagulation goals.",
    topicSlug: "anticoagulation",
  },
  {
    slug: "creatinine",
    term: "Creatinine",
    definition:
      "Renal function marker trending with perfusion and nephrotoxin exposure. Acute rises prompt urine output, medication review, and fluid strategy reassessment.",
    topicSlug: "acute-kidney-injury",
  },
  {
    slug: "hemoglobin",
    term: "Hemoglobin",
    definition:
      "Oxygen-carrying capacity of blood. Low hemoglobin drives fatigue and instability; transfusion decisions weigh symptoms, rate of drop, and bleeding source.",
    topicSlug: "hematology",
  },
  {
    slug: "platelet",
    term: "Platelet count",
    definition:
      "Critical for hemostasis. Thrombocytopenia increases bleeding risk with procedures, anticoagulation, and severe infection or DIC contexts.",
    topicSlug: "hematology",
  },
  {
    slug: "pao2",
    term: "PaO₂",
    definition:
      "Partial pressure of oxygen in arterial blood. Interpret with FiO₂ and clinical context — hypoxemia drives oxygen therapy and escalation decisions.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "hco3",
    term: "Bicarbonate (HCO₃⁻)",
    definition:
      "Primary metabolic buffer on ABG. Low bicarbonate suggests metabolic acidosis; compensation patterns guide whether respiratory or metabolic processes dominate.",
    topicSlug: "abg-interpretation",
  },
  {
    slug: "osmolality",
    term: "Osmolality",
    definition:
      "Solute concentration affecting fluid shifts. High osmolality with hyperglycemia drives osmotic diuresis and dehydration in DKA or HHS.",
    topicSlug: "diabetic-ketoacidosis",
  },
  {
    slug: "raas",
    term: "RAAS",
    definition:
      "Renin-angiotensin-aldosterone system regulates blood pressure and sodium balance. Blockade reduces afterload but requires monitoring of K⁺ and renal function.",
    topicSlug: "heart-failure",
  },
  {
    slug: "scope-of-practice",
    term: "Scope of practice",
    definition:
      "Legal and organizational boundaries defining what the nurse may perform. Delegation must stay within scope, competency, and supervision requirements.",
    topicSlug: "delegation",
  },
] as const;

function mergeGlossaryTerms(): NursingGlossaryTerm[] {
  const bySlug = new Map<string, NursingGlossaryTerm>();
  for (const t of NURSING_GLOSSARY_CORE) bySlug.set(t.slug, t);
  for (const t of NURSING_GLOSSARY_EXPANSION_TERMS) {
    if (!bySlug.has(t.slug)) bySlug.set(t.slug, t);
  }
  for (const t of buildCompetencyGlossaryTerms()) {
    if (!bySlug.has(t.slug)) bySlug.set(t.slug, t);
  }
  return [...bySlug.values()];
}

export const NURSING_GLOSSARY_TERMS: readonly NursingGlossaryTerm[] = mergeGlossaryTerms();

export function getNursingGlossaryTerm(slug: string): NursingGlossaryTerm | undefined {
  const key = slug.trim().toLowerCase();
  return NURSING_GLOSSARY_TERMS.find((t) => t.slug === key);
}

export function listNursingGlossaryTerms(): NursingGlossaryTerm[] {
  return [...NURSING_GLOSSARY_TERMS];
}
