/**
 * Competency-linked glossary batch — graph-native entities (editorial definitions, not autogenerated spam).
 */
import type { NursingGlossaryTerm } from "@/lib/seo/nursing-glossary-registry";
import { RN_COMPETENCY_NODES } from "@/lib/educational-graph/rn-competency-ontology";

function humanizeSlug(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function definitionForTopic(slug: string, competencyLabel: string): string {
  const label = humanizeSlug(slug);
  return (
    `${label} is a high-yield NCLEX-RN topic within ${competencyLabel.toLowerCase()}. ` +
    `Nursing priorities include recognizing instability cues, linking mechanism to assessment, and sequencing safe interventions before reassessment.`
  );
}

/** Generated competency-linked terms — dedupe by slug at merge time. */
export function buildCompetencyGlossaryTerms(): NursingGlossaryTerm[] {
  const terms: NursingGlossaryTerm[] = [];
  const seen = new Set<string>();

  for (const node of RN_COMPETENCY_NODES) {
    for (const topicSlug of node.topicSlugs) {
      const key = topicSlug.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      terms.push({
        slug: key,
        term: humanizeSlug(key),
        definition: definitionForTopic(key, node.label),
        topicSlug: key,
      });
    }
    terms.push({
      slug: node.id,
      term: node.label,
      definition:
        node.description.length >= 72
          ? node.description
          : `${node.description} Use this competency band to organize lessons, drills, and reassessment before expanding to new domains.`,
      topicSlug: node.topicSlugs[0] ?? "prioritization",
      relatedTermSlugs: node.topicSlugs.slice(0, 3),
    });
  }

  const supplemental: Array<{ slug: string; term: string; topicSlug: string; def: string }> = [
    {
      slug: "abg-analysis",
      term: "ABG analysis",
      topicSlug: "abg-interpretation",
      def: "Systematic review of pH, PaCO₂, PaO₂, and bicarbonate to classify acid-base disorders and compensation. Guides oxygen therapy and escalation in respiratory failure.",
    },
    {
      slug: "anion-gap",
      term: "Anion gap",
      topicSlug: "metabolic-acidosis",
      def: "Calculated difference helping distinguish high anion-gap metabolic acidosis (e.g. DKA, lactate) from non-gap causes such as diarrhea or renal tubular acidosis.",
    },
    {
      slug: "insulin-drip",
      term: "Insulin drip",
      topicSlug: "diabetic-ketoacidosis",
      def: "Continuous IV regular insulin for DKA/HHS per protocol. Requires hourly glucose, potassium checks, and hypoglycemia treatment ready at bedside.",
    },
    {
      slug: "fluid-bolus",
      term: "Fluid bolus",
      topicSlug: "shock",
      def: "Rapid IV crystalloid infusion to restore intravascular volume in hypovolemic or distributive shock. Reassess lung sounds and perfusion after each bolus.",
    },
    {
      slug: "peak-inspiratory-pressure",
      term: "Peak inspiratory pressure",
      topicSlug: "respiratory-failure",
      def: "Maximum airway pressure during mechanical ventilation. Sudden rises suggest obstruction, bronchospasm, or patient-ventilator asynchrony requiring immediate assessment.",
    },
    {
      slug: "therapeutic-hypothermia",
      term: "Targeted temperature management",
      topicSlug: "stroke",
      def: "Controlled cooling after cardiac arrest or select neurologic injury to reduce metabolic demand. Nursing monitors shivering, electrolytes, and skin integrity.",
    },
    {
      slug: "therapeutic-communication",
      term: "Therapeutic communication",
      topicSlug: "mental-health",
      def: "Purposeful verbal and nonverbal techniques that establish trust, clarify concerns, and de-escalate distress without minimizing the patient's experience.",
    },
    {
      slug: "five-rights-delegation",
      term: "Five rights of delegation",
      topicSlug: "delegation",
      def: "Right task, circumstance, person, direction/communication, and supervision. Required before assigning work to assistive personnel in changing acuity.",
    },
    {
      slug: "contact-precautions",
      term: "Contact precautions",
      topicSlug: "infection",
      def: "Gown and gloves for direct contact with patients colonized or infected with multidrug-resistant organisms. Hand hygiene remains essential on exit.",
    },
    {
      slug: "droplet-precautions",
      term: "Droplet precautions",
      topicSlug: "infection",
      def: "Surgical mask within 3–6 feet for pathogens spread by large respiratory droplets (e.g. influenza, pertussis). Patient may cohort when appropriate.",
    },
    {
      slug: "warfarin-teaching",
      term: "Warfarin teaching",
      topicSlug: "anticoagulation",
      def: "Emphasize consistent vitamin K intake, bleeding precautions, and INR monitoring. Report nosebleeds, dark stools, or unusual bruising promptly.",
    },
    {
      slug: "heparin-drip",
      term: "Heparin infusion",
      topicSlug: "anticoagulation",
      def: "Weight-based IV anticoagulation with aPTT or anti-Xa monitoring. Assess for bleeding, HIT risk, and avoid IM injections while infusing.",
    },
    {
      slug: "chest-tube",
      term: "Chest tube",
      topicSlug: "pneumonia",
      def: "Closed drainage system for pneumothorax or hemothorax. Keep chamber below chest, monitor tidaling, air leak, and output; clamp only per protocol.",
    },
    {
      slug: "foley-catheter",
      term: "Indwelling urinary catheter",
      topicSlug: "fluid-balance",
      def: "Sterile bladder drainage that increases CAUTI risk. Use only when indicated; maintain closed system and remove as soon as clinically appropriate.",
    },
    {
      slug: "ng-tube",
      term: "Nasogastric tube",
      topicSlug: "gastrointestinal",
      def: "Decompression, feeding, or medication delivery via the nose into the stomach. Confirm placement before use and monitor for aspiration risk.",
    },
    {
      slug: "bowel-sounds",
      term: "Bowel sounds",
      topicSlug: "gastrointestinal",
      def: "Auscultated peristaltic activity — hyperactive, normoactive, or absent. Changes accompany ileus, obstruction, and postoperative recovery patterns.",
    },
    {
      slug: "cranial-nerves",
      term: "Cranial nerve assessment",
      topicSlug: "neurologic",
      def: "Focused screening of CN II–XII for stroke, increased ICP, or postoperative neurologic deficits. Compare sides and document acute changes immediately.",
    },
    {
      slug: "glasgow-coma-scale",
      term: "Glasgow Coma Scale",
      topicSlug: "neurologic",
      def: "Standardized consciousness score (eye, verbal, motor). Trending scores drive neuro check frequency and escalation for declining neurologic status.",
    },
    {
      slug: "fundal-height",
      term: "Fundal height",
      topicSlug: "maternity",
      def: "Centimeters from symphysis pubis to uterine fundus approximating gestational age. Sudden changes may suggest bleeding, rupture, or growth restriction.",
    },
    {
      slug: "apgar-score",
      term: "Apgar score",
      topicSlug: "newborn",
      def: "Rapid newborn assessment at 1 and 5 minutes (appearance, pulse, grimace, activity, respiration). Low scores prompt resuscitation and closer monitoring.",
    },
    {
      slug: "postpartum-hemorrhage",
      term: "Postpartum hemorrhage",
      topicSlug: "labor-delivery",
      def: "Excessive bleeding after delivery — assess fundal tone, lochia, and vital signs. Massive transfusion protocols and uterotonics may be required urgently.",
    },
    {
      slug: "triage",
      term: "Triage",
      topicSlug: "prioritization",
      def: "Sorting patients by acuity so the most unstable receive care first. Uses ABCs, vital sign trends, and resource availability — not arrival order alone.",
    },
    {
      slug: "sata-questions",
      term: "SATA questions",
      topicSlug: "nclex-strategy",
      def: "Select-all-that-apply items requiring independent judgment per option. Each choice is true/false; partial guessing reduces exam accuracy.",
    },
    {
      slug: "therapeutic-drug-monitoring",
      term: "Therapeutic drug monitoring",
      topicSlug: "pharmacology",
      def: "Serum levels for narrow-index drugs (e.g. digoxin, lithium, vancomycin). Draw at consistent times relative to doses and renal function.",
    },
    {
      slug: "digoxin-toxicity",
      term: "Digoxin toxicity",
      topicSlug: "pharmacology",
      def: "Nausea, vision changes, bradycardia, and arrhythmias — often with hypokalemia. Hold digoxin, check level, and monitor ECG closely.",
    },
    {
      slug: "lithium-toxicity",
      term: "Lithium toxicity",
      topicSlug: "mental-health",
      def: "Tremor, confusion, ataxia, and GI upset — worsened by dehydration or renal impairment. Maintain hydration and monitor serum lithium levels.",
    },
    {
      slug: "chemotherapy-precautions",
      term: "Chemotherapy precautions",
      topicSlug: "pharmacology",
      def: "Hazardous drug handling — PPE, spill kits, and safe disposal. Double-check doses and vesicant extravasation protocols at infusion sites.",
    },
    {
      slug: "tumor-lysis-syndrome",
      term: "Tumor lysis syndrome",
      topicSlug: "pharmacology",
      def: "Rapid cell breakdown releasing potassium, phosphate, and uric acid after chemotherapy. Prophylaxis and aggressive hydration reduce renal failure risk.",
    },
    {
      slug: "acute-pain-scale",
      term: "Pain assessment",
      topicSlug: "safety",
      def: "Regular rating using patient-appropriate scales (0–10, FLACC, PAINAD). Reassess after interventions; untreated pain limits mobility and recovery.",
    },
    {
      slug: "fall-risk",
      term: "Fall risk assessment",
      topicSlug: "safety",
      def: "Screening for history, gait, medications, and environment. Implement bed alarms, toileting schedules, and non-skid footwear per score.",
    },
    {
      slug: "restraints",
      term: "Restraint use",
      topicSlug: "safety",
      def: "Least-restrictive alternative first. Continuous monitoring, release for circulation and hygiene, and provider orders with time-limited renewal.",
    },
    {
      slug: "informed-consent",
      term: "Informed consent",
      topicSlug: "delegation",
      def: "Patient understands procedure, risks, benefits, and alternatives before agreeing. Nurse role is witness and advocate — not explaining surgical detail unless credentialed.",
    },
    {
      slug: "advance-directive",
      term: "Advance directive",
      topicSlug: "delegation",
      def: "Documented wishes for care if the patient cannot decide — living will, durable power of attorney. Verify on admission and before high-risk procedures.",
    },
    {
      slug: "rapid-response-team",
      term: "Rapid response team",
      topicSlug: "sepsis",
      def: "Interdisciplinary team for early deterioration outside ICU. Trigger when vital signs, mental status, or urine output cross unit-specific thresholds.",
    },
    {
      slug: "code-blue",
      term: "Code blue",
      topicSlug: "shock",
      def: "Cardiopulmonary arrest response — start compressions, attach monitor/defibrillator, secure airway, and assign roles clearly at the bedside.",
    },
    {
      slug: "rsi",
      term: "Rapid sequence intubation",
      topicSlug: "respiratory-failure",
      def: "Emergency airway with sedative and paralytic for imminent failure. Preoxygenate, prepare suction, and monitor for post-intubation hypotension.",
    },
    {
      slug: "peep",
      term: "PEEP",
      topicSlug: "respiratory-failure",
      def: "Positive end-expiratory pressure maintains alveolar recruitment in ARDS. Balance oxygenation against hemodynamic effects and barotrauma risk.",
    },
    {
      slug: "ards",
      term: "ARDS",
      topicSlug: "respiratory-failure",
      def: "Acute respiratory distress syndrome — refractory hypoxemia with bilateral infiltrates. Lung-protective ventilation and prone positioning when indicated.",
    },
    {
      slug: "pulmonary-embolism",
      term: "Pulmonary embolism",
      topicSlug: "cardiovascular",
      def: "Sudden dyspnea, chest pain, and hypoxia from venous thrombus embolization. Anticoagulation and hemodynamic support; massive PE may need thrombolysis.",
    },
    {
      slug: "deep-vein-thrombosis",
      term: "Deep vein thrombosis",
      topicSlug: "anticoagulation",
      def: "Unilateral leg swelling, warmth, and pain — confirm with ultrasound. Ambulation and anticoagulation per protocol; monitor for bleeding.",
    },
    {
      slug: "chf-exacerbation",
      term: "Heart failure exacerbation",
      topicSlug: "heart-failure",
      def: "Volume overload with crackles, edema, and weight gain. Diuretics, daily weights, sodium restriction, and daily I&O are core nursing actions.",
    },
    {
      slug: "jvd",
      term: "Jugular venous distension",
      topicSlug: "heart-failure",
      def: "Elevated jugular venous pressure suggesting right-sided failure or fluid overload. Measure at 30–45 degrees with patient relaxed.",
    },
    {
      slug: "peripheral-edema",
      term: "Peripheral edema",
      topicSlug: "heart-failure",
      def: "Pitting or non-pitting swelling in dependent areas. Grade depth and document skin integrity; correlate with intake, output, and diuretic response.",
    },
    {
      slug: "burn-percentage",
      term: "Rule of nines",
      topicSlug: "integumentary",
      def: "Estimates total body surface area burned for fluid resuscitation. Pediatric rules differ; transfer to burn center when thresholds are met.",
    },
    {
      slug: "pressure-injury",
      term: "Pressure injury",
      topicSlug: "integumentary",
      def: "Localized skin and tissue damage from sustained pressure and shear. Staging guides treatment; repositioning and support surfaces are prevention pillars.",
    },
    {
      slug: "wound-vac",
      term: "Negative pressure wound therapy",
      topicSlug: "integumentary",
      def: "Sealed suction device promoting granulation. Monitor seal, drainage character, and alarm settings; patient may need pain medication for dressing changes.",
    },
    {
      slug: "tracheostomy-care",
      term: "Tracheostomy care",
      topicSlug: "respiratory-failure",
      def: "Stoma cleaning, humidification, and suction as needed. Emergency airway supplies at bedside; prevent accidental decannulation.",
    },
    {
      slug: "enteral-feeding",
      term: "Enteral nutrition",
      topicSlug: "nutrition",
      def: "Tube-delivered formula when oral intake is unsafe or insufficient. Elevate head of bed, check residuals per policy, and flush tubes to maintain patency.",
    },
    {
      slug: "tpn",
      term: "Total parenteral nutrition",
      topicSlug: "nutrition",
      def: "Central-line hyperalimentation when gut cannot be used. Strict aseptic technique, dedicated line, and monitor glucose and electrolytes closely.",
    },
    {
      slug: "refeeding-syndrome",
      term: "Refeeding syndrome",
      topicSlug: "nutrition",
      def: "Electrolyte shifts (especially phosphate) when nutrition restarts after starvation. Thiamine and gradual calories reduce cardiac and neurologic complications.",
    },
    {
      slug: "diuretic-resistance",
      term: "Diuretic resistance",
      topicSlug: "fluid-balance",
      def: "Diminished urine output despite escalating diuretics in advanced heart or renal disease. May require combination therapy and nephrology input.",
    },
    {
      slug: "dialysis",
      term: "Hemodialysis",
      topicSlug: "acute-kidney-injury",
      def: "Extracorporeal blood filtration for renal failure. Monitor access thrill/bruit, fluid removal goals, and hypotension during treatment.",
    },
    {
      slug: "peritoneal-dialysis",
      term: "Peritoneal dialysis",
      topicSlug: "acute-kidney-injury",
      def: "Intraperitoneal dialysate exchange using a catheter. Assess for infection (cloudy fluid), catheter integrity, and sterile technique during exchanges.",
    },
    {
      slug: "contrast-nephropathy",
      term: "Contrast-induced nephropathy",
      topicSlug: "acute-kidney-injury",
      def: "Creatinine rise after iodinated contrast. Pre-hydration and minimizing volume reduce risk; hold nephrotoxic drugs when appropriate.",
    },
    {
      slug: "rhabdomyolysis",
      term: "Rhabdomyolysis",
      topicSlug: "acute-kidney-injury",
      def: "Muscle breakdown releasing myoglobin — dark urine, elevated CK. Aggressive IV fluids protect kidneys; monitor electrolytes and compartment syndrome.",
    },
    {
      slug: "hypoglycemia",
      term: "Hypoglycemia",
      topicSlug: "diabetes-mellitus",
      def: "Blood glucose below target with shakiness, confusion, or diaphoresis. Rule of 15 for oral carbs; glucagon or IV dextrose if unable to swallow.",
    },
    {
      slug: "diabetic-foot-ulcer",
      term: "Diabetic foot ulcer",
      topicSlug: "diabetes-mellitus",
      def: "Neuropathic and vascular wounds on feet — offloading, infection control, and glycemic management. Daily foot inspection is key prevention.",
    },
    {
      slug: "thyroid-storm-signs",
      term: "Thyroid storm signs",
      topicSlug: "thyroid",
      def: "Fever, tachycardia, agitation, and hypertension in severe thyrotoxicosis. Cooling, beta-blockade, and ICU-level monitoring are typical priorities.",
    },
    {
      slug: "addisonian-crisis",
      term: "Addisonian crisis",
      topicSlug: "endocrine",
      def: "Acute adrenal insufficiency with hypotension, hyperkalemia, and shock. Stress-dose steroids and volume resuscitation are life-saving interventions.",
    },
    {
      slug: "pheochromocytoma",
      term: "Pheochromocytoma",
      topicSlug: "endocrine",
      def: "Catecholamine-secreting tumor causing paroxysmal hypertension, headache, and diaphoresis. Avoid medications that trigger catecholamine release unprepared.",
    },
    {
      slug: "status-epilepticus",
      term: "Status epilepticus",
      topicSlug: "seizure",
      def: "Prolonged or recurrent seizures without recovery between. Treat as emergency with benzodiazepines per protocol and airway protection.",
    },
    {
      slug: "meningitis",
      term: "Meningitis precautions",
      topicSlug: "infection",
      def: "Bacterial meningitis requires droplet precautions until 24 hours of effective antibiotics. Assess nuchal rigidity, photophobia, and mental status changes.",
    },
    {
      slug: "clostridium-difficile",
      term: "Clostridioides difficile",
      topicSlug: "infection",
      def: "Antibiotic-associated colitis with watery diarrhea. Contact precautions, hand washing with soap and water, and contact precautions for spores.",
    },
    {
      slug: "mrsa",
      term: "MRSA",
      topicSlug: "infection",
      def: "Methicillin-resistant Staphylococcus aureus — contact precautions and targeted antibiotics. Screen colonization in high-risk admissions per policy.",
    },
    {
      slug: "c-diff-isolation",
      term: "C. diff isolation",
      topicSlug: "infection-control",
      def: "Dedicated equipment and contact precautions for toxin-positive diarrhea. Alcohol gel does not remove spores — use soap and water for hand hygiene.",
    },
    {
      slug: "sterile-technique",
      term: "Sterile technique",
      topicSlug: "infection-control",
      def: "Maintains asepsis during invasive procedures — sterile field, no breaks in technique, and immediate correction of contamination.",
    },
    {
      slug: "surgical-site-infection",
      term: "Surgical site infection",
      topicSlug: "infection-control",
      def: "Postoperative wound infection within 30–90 days depending on depth. Monitor erythema, drainage, fever, and opening orders for culture if indicated.",
    },
    {
      slug: "transfusion-reaction",
      term: "Transfusion reaction",
      topicSlug: "pharmacology",
      def: "Fever, chills, hypotension, or respiratory distress during blood products. Stop infusion, maintain line with saline, and follow institutional reaction protocol.",
    },
    {
      slug: "type-and-cross",
      term: "Type and crossmatch",
      topicSlug: "pharmacology",
      def: "Compatibility testing before transfusion. Two licensed staff verify patient ID, blood product, and consent at bedside.",
    },
    {
      slug: "ecg-stemi",
      term: "STEMI",
      topicSlug: "myocardial-infarction",
      def: "ST-elevation myocardial infarction — coronary occlusion requiring rapid reperfusion. Time-to-treatment drives outcomes; monitor for arrhythmias.",
    },
    {
      slug: "nitroglycerin",
      term: "Nitroglycerin",
      topicSlug: "myocardial-infarction",
      def: "Vasodilator for angina — check blood pressure before each dose. Store in original container; discard opened bottles per manufacturer timing.",
    },
    {
      slug: "beta-blocker-hold",
      term: "Beta-blocker considerations",
      topicSlug: "heart-failure",
      def: "Reduce heart rate and contractility — beneficial in chronic HF but may worsen acute decompensation or bradycardia. Hold when HR or BP too low per orders.",
    },
    {
      slug: "ace-inhibitor-cough",
      term: "ACE inhibitor",
      topicSlug: "heart-failure",
      def: "Afterload reduction and remodeling benefits in HFrEF. Monitor potassium, renal function, and persistent dry cough that may require class switch.",
    },
    {
      slug: "pulmonary-hypertension",
      term: "Pulmonary hypertension",
      topicSlug: "cardiovascular",
      def: "Elevated pulmonary artery pressures causing right ventricular strain. Syncope, exertional dyspnea, and careful fluid management are nursing focus areas.",
    },
    {
      slug: "pacemaker",
      term: "Pacemaker",
      topicSlug: "cardiovascular",
      def: "Device for bradycardia or conduction disease. Assess incision, magnet precautions, and interference with MRI per device type.",
    },
    {
      slug: "icd",
      term: "Implantable cardioverter-defibrillator",
      topicSlug: "cardiovascular",
      def: "Treats ventricular tachyarrhythmias with shock or antitachycardia pacing. Teach patients about driving restrictions and shock plans after delivery.",
    },
    {
      slug: "cardioversion",
      term: "Synchronized cardioversion",
      topicSlug: "cardiovascular",
      def: "Timed shock for unstable atrial arrhythmias with pulse. Sedation, airway readiness, and anticoagulation status are pre-procedure priorities.",
    },
    {
      slug: "defibrillation",
      term: "Defibrillation",
      topicSlug: "shock",
      def: "Unsynchronized shock for pulseless ventricular fibrillation or pulseless VT. Minimize pauses in compressions before and after shock.",
    },
    {
      slug: "rosc",
      term: "Return of spontaneous circulation",
      topicSlug: "shock",
      def: "Restoration of perfusing rhythm after arrest. Post-ROSC care targets oxygenation, blood pressure, and targeted temperature management when indicated.",
    },
    {
      slug: "anaphylaxis",
      term: "Anaphylaxis",
      topicSlug: "immunology",
      def: "Severe allergic reaction with airway compromise, hypotension, and urticaria. IM epinephrine is first-line; prepare for repeat doses and airway support.",
    },
    {
      slug: "epinephrine-auto-injector",
      term: "Epinephrine auto-injector",
      topicSlug: "immunology",
      def: "Patient-carried emergency treatment for anaphylaxis. Teach injection technique, when to call EMS, and need for observation after use.",
    },
    {
      slug: "latex-allergy",
      term: "Latex allergy",
      topicSlug: "safety",
      def: "Type I hypersensitivity to natural rubber latex. Use latex-free equipment and signage; avoid cross-reactive foods in severe allergy when relevant.",
    },
    {
      slug: "latex-sensitivity",
      term: "Latex sensitivity",
      topicSlug: "safety",
      def: "Contact irritation or allergy to latex products. Substitute nitrile or vinyl gloves and document allergy in the electronic record prominently.",
    },
  ];

  for (const row of supplemental) {
    const key = row.slug.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    terms.push({
      slug: key,
      term: row.term,
      definition: row.def,
      topicSlug: row.topicSlug,
    });
  }

  return terms;
}
