export function generateToxicologyBatch3() {
  const subtopicData: Record<string, { topics: {stem: string; options: string[]; correctAnswer: number; rationaleLong: string; learningObjective: string; examTrap: string; clinicalPearls: string[]; safetyNote: string; distractorRationales: string[]; lessonSlug: string; difficulty: number; cognitiveLevel: string; questionType: string}[] }> = {
    "Acetaminophen Overdose and NAC Protocol": { topics: [
      { stem: "A 28-year-old female presents 8 hours after ingesting 15g of acetaminophen. Her 4-hour level was not drawn. Current AST is 85 U/L and ALT is 92 U/L. The acetaminophen level is 45 mcg/mL. Should NAC be started?", options: ["Yes, initiate NAC immediately because elevated transaminases indicate hepatotoxicity regardless of current acetaminophen level", "No, the current level is below the treatment line", "Wait for a repeat level in 4 hours", "Administer activated charcoal instead"], correctAnswer: 0, rationaleLong: "When a patient presents more than 8 hours after acetaminophen ingestion with elevated liver enzymes (AST 85, ALT 92), NAC should be initiated immediately regardless of the current acetaminophen level. The Rumack-Matthew nomogram is only reliable for acute single ingestions with a known time of ingestion and a level drawn between 4-24 hours. At 8 hours post-ingestion, the acetaminophen level may be declining while toxic metabolite NAPQI is actively causing hepatocellular damage, as evidenced by the rising transaminases. NAC efficacy decreases significantly after 8 hours, making immediate initiation critical. The elevated AST and ALT confirm that hepatotoxicity is already occurring. Delaying NAC to wait for repeat levels or using activated charcoal (which has minimal benefit beyond 2 hours post-ingestion) would allow further hepatic damage. NAC should be continued until evidence of clinical improvement, declining transaminases, and normal coagulation studies.", learningObjective: "Recognize that elevated transaminases after acetaminophen ingestion require immediate NAC regardless of current drug level", examTrap: "The Rumack-Matthew nomogram is only valid for single acute ingestions with a level drawn at 4+ hours; elevated liver enzymes bypass the nomogram decision", clinicalPearls: ["NAC efficacy decreases significantly after 8 hours post-ingestion", "Elevated transaminases indicate NAPQI-mediated hepatotoxicity already occurring", "The nomogram is not reliable for staggered ingestions or unknown timing", "Continue NAC until transaminases trending down and INR normalizing"], safetyNote: "When in doubt about timing or dose of acetaminophen ingestion, start NAC and reassess rather than delay treatment", distractorRationales: ["Current level below the treatment line is irrelevant when transaminases are elevated indicating active hepatotoxicity", "Waiting for repeat levels wastes critical time when hepatotoxicity is confirmed by elevated enzymes", "Activated charcoal has no benefit at 8 hours post-ingestion"], lessonSlug: "acetaminophen-overdose", difficulty: 4, cognitiveLevel: "analysis", questionType: "MCQ_SINGLE" },
      { stem: "During NAC infusion for acetaminophen overdose, a patient develops facial flushing, urticaria, and bronchospasm 15 minutes into the loading dose. What is the appropriate nursing response?", options: ["Stop the infusion temporarily, administer diphenhydramine and an inhaled bronchodilator, then restart at a slower rate", "Discontinue NAC permanently and switch to oral NAC protocol", "Administer epinephrine 0.3 mg IM for anaphylaxis", "Continue the infusion at the same rate while treating symptoms"], correctAnswer: 0, rationaleLong: "Anaphylactoid reactions to IV NAC occur in approximately 10-20% of patients, most commonly during the loading dose infusion which delivers the highest concentration. These reactions are dose-rate dependent and mediated by histamine release, not IgE-mediated true anaphylaxis. Management includes temporarily stopping the infusion, administering antihistamines (diphenhydramine 25-50 mg IV), treating bronchospasm with inhaled bronchodilators (albuterol), and then restarting the infusion at a slower rate. Most patients can successfully complete the NAC protocol after treatment of the anaphylactoid reaction. True anaphylaxis with hemodynamic instability is rare and would require epinephrine. The key distinction is that anaphylactoid reactions to NAC are rate-dependent and can be managed by slowing the infusion, whereas true anaphylaxis would require permanent discontinuation. Continuing the infusion at the same rate would worsen the reaction. NAC should not be permanently discontinued as it may be life-saving for the acetaminophen toxicity.", learningObjective: "Manage anaphylactoid reactions to IV NAC by temporarily stopping infusion, treating symptoms, and restarting at a slower rate", examTrap: "NAC anaphylactoid reactions are rate-dependent histamine release, not true IgE-mediated anaphylaxis; most patients can complete the protocol after treatment", clinicalPearls: ["Anaphylactoid reactions occur in 10-20% of IV NAC recipients, mainly during loading dose", "Reactions are dose-rate dependent, not IgE-mediated", "Temporarily stop infusion, treat with antihistamines and bronchodilators, then restart slower", "Rarely requires permanent discontinuation"], safetyNote: "Always have resuscitation equipment available during IV NAC infusion; monitor closely during the loading dose when anaphylactoid reactions are most likely", distractorRationales: ["Permanent discontinuation is unnecessary as reactions are rate-dependent and manageable", "Epinephrine is reserved for true anaphylaxis with hemodynamic instability, not typical anaphylactoid reactions", "Continuing at the same rate would worsen the histamine-mediated reaction"], lessonSlug: "acetaminophen-overdose", difficulty: 3, cognitiveLevel: "application", questionType: "MCQ_SINGLE" },
      { stem: "A pregnant patient at 28 weeks gestation presents with acetaminophen ingestion and a 4-hour level above the treatment line. What modification to NAC therapy is required?", options: ["No modification; standard NAC protocol should be administered as NAC crosses the placenta and protects the fetal liver", "NAC is contraindicated in pregnancy; supportive care only", "Half-dose NAC to prevent fetal complications", "Delay NAC until after delivery to avoid teratogenicity"], correctAnswer: 0, rationaleLong: "NAC should be administered at standard doses without modification in pregnant patients with acetaminophen toxicity. NAC crosses the placenta and provides hepatoprotection to the fetal liver, which is also susceptible to NAPQI-mediated damage. Acetaminophen and its toxic metabolite NAPQI cross the placenta freely, and the fetal liver has limited capacity for detoxification due to immature enzyme systems. Untreated maternal acetaminophen toxicity carries significant risk of fetal hepatotoxicity, spontaneous abortion, and fetal death. There is no evidence that NAC causes teratogenic effects, and the benefit of preventing maternal and fetal hepatotoxicity far outweighs any theoretical risk. The standard 21-hour IV protocol (150 mg/kg over 60 minutes, then 50 mg/kg over 4 hours, then 100 mg/kg over 16 hours) should be used. Early treatment within 8 hours provides the best outcomes for both mother and fetus. Obstetric consultation should be obtained for fetal monitoring, but treatment should not be delayed.", learningObjective: "Administer standard-dose NAC in pregnant patients with acetaminophen toxicity for both maternal and fetal hepatoprotection", examTrap: "NAC is safe in pregnancy and crosses the placenta to protect the fetal liver; never withhold or reduce the dose", clinicalPearls: ["NAC crosses the placenta providing fetal hepatoprotection", "Fetal liver has limited detoxification capacity making it vulnerable to NAPQI", "Standard NAC dosing is used without modification in pregnancy", "Untreated APAP toxicity carries risk of fetal hepatotoxicity and fetal death"], safetyNote: "Acetaminophen toxicity in pregnancy is a dual emergency; treat aggressively with standard NAC for both maternal and fetal protection", distractorRationales: ["NAC is not contraindicated in pregnancy; it is essential for fetal protection", "Half-dose NAC would provide inadequate hepatoprotection for both mother and fetus", "Delaying NAC until delivery risks fatal maternal and fetal hepatotoxicity"], lessonSlug: "acetaminophen-overdose", difficulty: 3, cognitiveLevel: "application", questionType: "MCQ_SINGLE" },
    ]},
    "Opioid Overdose and Naloxone": { topics: [
      { stem: "A patient is receiving a naloxone infusion after reversal of a methadone overdose. Twelve hours into the infusion, the nurse notes the patient is becoming increasingly somnolent with declining respiratory rate. What should the nurse do?", options: ["Increase the naloxone infusion rate and administer an additional IV bolus while reassessing the patient", "Discontinue the infusion as it has been running long enough", "Switch to oral naltrexone for maintenance reversal", "Obtain a chest X-ray before any medication changes"], correctAnswer: 0, rationaleLong: "Methadone has an extremely long half-life (24-36 hours, sometimes up to 60 hours), far exceeding naloxone's duration of action. The declining mental status and respiratory rate during the naloxone infusion suggest the current infusion rate is insufficient to counteract the persistent methadone effect, or the methadone levels may be rising as absorption continues. The appropriate response is to administer an additional naloxone bolus to rapidly reverse the worsening symptoms while simultaneously increasing the infusion rate. The naloxone infusion rate should be titrated based on clinical response, targeting a respiratory rate above 12 breaths per minute while avoiding complete reversal that could precipitate severe withdrawal. Discontinuing the infusion would allow potentially fatal respiratory depression. Oral naltrexone is not appropriate for acute reversal in an obtunded patient. While a chest X-ray may be useful to evaluate for aspiration or pulmonary edema, it should not delay immediate treatment of respiratory depression.", learningObjective: "Titrate naloxone infusion rate for long-acting opioid overdose and recognize signs of inadequate reversal", examTrap: "Methadone half-life (24-60 hours) far exceeds naloxone duration; infusion rates may need upward titration over time", clinicalPearls: ["Methadone half-life is 24-60 hours requiring extended naloxone infusion", "Bolus and increase rate for breakthrough respiratory depression", "Titrate to RR >12, not complete arousal", "Monitor for at least 48-72 hours with methadone overdose"], safetyNote: "Methadone overdose requires the longest monitoring period of any opioid; premature discontinuation of naloxone infusion can be fatal", distractorRationales: ["Discontinuing the infusion with ongoing respiratory depression risks death", "Oral naltrexone cannot be given to an obtunded patient", "Chest X-ray should not delay treatment of worsening respiratory depression"], lessonSlug: "opioid-overdose", difficulty: 4, cognitiveLevel: "analysis", questionType: "MCQ_SINGLE" },
      { stem: "A 55-year-old chronic pain patient on buprenorphine (Suboxone) presents with respiratory depression, miosis, and obtundation after taking his medication with a large amount of alcohol. Naloxone 0.4 mg IV produces no response. What should the nurse anticipate?", options: ["Higher naloxone doses (up to 10-15 mg) may be needed because buprenorphine has extremely high mu-receptor binding affinity", "The respiratory depression is not opioid-related since naloxone failed", "Switch to flumazenil as the primary reversal agent", "Standard ACLS protocols for cardiac arrest"], correctAnswer: 0, rationaleLong: "Buprenorphine is a partial mu-opioid agonist with exceptionally high receptor binding affinity (Ki = 0.22 nM), much higher than naloxone. This means standard naloxone doses (0.4-2 mg) are often insufficient to displace buprenorphine from opioid receptors. In buprenorphine toxicity, naloxone doses of 10-15 mg or more may be required, and even then reversal may be partial. The high binding affinity also means that a continuous naloxone infusion at high doses may be needed for sustained reversal. The co-ingestion of alcohol likely contributed to the respiratory depression by compounding the CNS depressant effects. Failure to respond to initial naloxone does not rule out opioid involvement when buprenorphine is the causative agent. Flumazenil reverses benzodiazepines and would not help with opioid-related depression (though it could reverse alcohol's GABAergic effects to some degree, its use is not standard). The patient is not in cardiac arrest, so ACLS is not indicated. Aggressive airway management with BVM ventilation and preparation for intubation should proceed while escalating naloxone doses.", learningObjective: "Recognize that buprenorphine's high receptor affinity requires significantly higher naloxone doses for reversal", examTrap: "Buprenorphine has higher mu-receptor binding affinity than naloxone; standard 0.4-2 mg doses are often ineffective", clinicalPearls: ["Buprenorphine has Ki 0.22 nM, requiring 10-15+ mg naloxone for displacement", "Partial reversal may be the best achievable outcome", "Continuous high-dose naloxone infusion may be needed", "Co-ingestants (alcohol) compound respiratory depression"], safetyNote: "Always secure the airway with BVM ventilation while escalating naloxone doses for buprenorphine toxicity; do not rely solely on naloxone", distractorRationales: ["Failure of low-dose naloxone does not rule out opioid involvement with buprenorphine", "Flumazenil reverses benzodiazepines, not opioids or alcohol", "Patient has respiratory depression, not cardiac arrest"], lessonSlug: "opioid-overdose", difficulty: 5, cognitiveLevel: "analysis", questionType: "MCQ_SINGLE" },
    ]},
    "Cholinergic Toxidrome": { topics: [
      { stem: "A farmer presents after insecticide exposure with the SLUDGE symptoms. During atropine titration, the nurse notices resolution of salivation and bronchorrhea but persistent muscle fasciculations and weakness. Which additional medication is needed?", options: ["Pralidoxime (2-PAM) to address the nicotinic effects by reactivating acetylcholinesterase at the neuromuscular junction", "Additional atropine to address the remaining symptoms", "Neostigmine to reverse the neuromuscular blockade", "Succinylcholine for facilitated intubation"], correctAnswer: 0, rationaleLong: "Atropine only blocks muscarinic receptors, addressing the SLUDGE/BBB symptoms (salivation, lacrimation, urination, defecation, GI distress, emesis, bradycardia, bronchospasm, bronchorrhea). However, muscle fasciculations and weakness are nicotinic effects occurring at the neuromuscular junction, which atropine cannot reverse. Pralidoxime (2-PAM) works by reactivating acetylcholinesterase that has been inhibited by the organophosphate, thereby addressing both muscarinic and nicotinic effects. Pralidoxime must be given before the organophosphate-enzyme bond undergoes 'aging' (becomes irreversible), which occurs within 24-48 hours depending on the specific organophosphate. The dose is 1-2 grams IV over 15-30 minutes, which can be repeated if muscle weakness persists. Additional atropine would not address nicotinic symptoms since atropine only acts at muscarinic receptors. Neostigmine is an acetylcholinesterase inhibitor that would paradoxically worsen the toxicity. Succinylcholine should be avoided as it is metabolized by cholinesterases which are already inhibited.", learningObjective: "Differentiate muscarinic and nicotinic effects in organophosphate poisoning and understand the complementary roles of atropine and pralidoxime", examTrap: "Atropine addresses muscarinic effects only; persistent fasciculations and weakness require pralidoxime for nicotinic receptor effects", clinicalPearls: ["Atropine = muscarinic blockade; pralidoxime = cholinesterase reactivation (muscarinic + nicotinic)", "Pralidoxime must be given before aging occurs (24-48 hours)", "Fasciculations and weakness = nicotinic effects at NMJ", "Avoid succinylcholine as it is metabolized by inhibited cholinesterases"], safetyNote: "Pralidoxime is most effective when given early before enzyme-inhibitor aging; do not delay administration waiting for confirmation of specific agent", distractorRationales: ["Additional atropine cannot address nicotinic effects at the neuromuscular junction", "Neostigmine is a cholinesterase inhibitor that would worsen organophosphate toxicity", "Succinylcholine metabolism depends on cholinesterases which are already inhibited, causing prolonged paralysis"], lessonSlug: "cholinergic-toxidrome", difficulty: 3, cognitiveLevel: "application", questionType: "MCQ_SINGLE" },
    ]},
    "Activated Charcoal and Decontamination": { topics: [
      { stem: "A 20-year-old presents after ingesting a large quantity of theophylline extended-release tablets 1 hour ago. The emergency nurse administers a first dose of activated charcoal. Should additional doses be given?", options: ["Yes, multi-dose activated charcoal (MDAC) is indicated for theophylline because it undergoes enterohepatic circulation and gut dialysis enhances elimination", "No, a single dose of charcoal is always sufficient", "Only if the patient vomits the first dose", "MDAC is contraindicated with extended-release formulations"], correctAnswer: 0, rationaleLong: "Multi-dose activated charcoal (MDAC) is specifically indicated for certain drug ingestions where it provides enhanced elimination through a mechanism called 'gut dialysis.' Theophylline is one of the classic indications for MDAC because it undergoes enterohepatic circulation and has favorable pharmacokinetics for gut dialysis (moderate volume of distribution, significant GI secretion of drug). MDAC works by creating a concentration gradient across the intestinal wall, drawing drug from the blood into the GI lumen where it binds to charcoal. The recommended protocol is an initial dose of 1 g/kg followed by 0.5 g/kg every 2-4 hours. Other drugs that benefit from MDAC include carbamazepine, dapsone, phenobarbital, and quinine. Extended-release formulations are actually a stronger indication for MDAC because charcoal continues to adsorb drug as it is slowly released from the formulation matrix. The main risk of MDAC is aspiration, so airway protection must be ensured. A cathartic (sorbitol) should only be given with the first dose to avoid electrolyte disturbances.", learningObjective: "Identify indications for multi-dose activated charcoal and understand the gut dialysis mechanism of enhanced elimination", examTrap: "MDAC enhances elimination via gut dialysis for theophylline, carbamazepine, dapsone, phenobarbital, and quinine", clinicalPearls: ["MDAC works through gut dialysis creating a blood-to-gut concentration gradient", "Indications: theophylline, carbamazepine, dapsone, phenobarbital, quinine", "Dose: 1 g/kg initial, then 0.5 g/kg every 2-4 hours", "Only give cathartic (sorbitol) with first dose to prevent electrolyte disturbances"], safetyNote: "Ensure airway protection before MDAC; aspiration of charcoal is a serious complication requiring intubation in patients with decreased consciousness", distractorRationales: ["A single dose is insufficient for drugs amenable to gut dialysis enhanced elimination", "MDAC is re-dosed on a schedule, not only if vomited", "Extended-release formulations are actually a stronger indication for MDAC"], lessonSlug: "activated-charcoal-decontamination", difficulty: 3, cognitiveLevel: "application", questionType: "MCQ_SINGLE" },
      { stem: "An emergency nurse is considering whole bowel irrigation (WBI) for a patient. Which ingestion scenario is WBI most appropriate for?", options: ["A body packer with multiple drug-filled packets visible on abdominal imaging who is currently asymptomatic", "A patient who ingested 10 aspirin tablets 30 minutes ago", "A patient who drank bleach 1 hour ago", "A patient with mild acetaminophen ingestion presenting at 45 minutes"], correctAnswer: 0, rationaleLong: "Whole bowel irrigation (WBI) with polyethylene glycol electrolyte solution (GoLYTELY) is specifically indicated for scenarios where activated charcoal is ineffective or insufficient. The primary indications include: body packers/stuffers (drug-filled packets that could rupture and cause massive toxicity), sustained-release or enteric-coated medication ingestions, heavy metal ingestions (iron, lead, arsenic), and large ingestions of medications poorly adsorbed by charcoal. Body packers represent one of the strongest indications because: (1) the packets are not adsorbed by charcoal, (2) rupture of even one packet can cause fatal toxicity, (3) the packets need to pass through the GI tract intact, and (4) surgical intervention carries its own risks. The protocol involves administering PEG solution at 1-2 L/hour for adults (25 mL/kg/hour for children) via NGT until rectal effluent is clear. Contraindications include bowel obstruction, perforation, hemodynamic instability, intractable vomiting, and unprotected airway. Aspirin and acetaminophen are well-adsorbed by activated charcoal, making WBI unnecessary. Bleach is a corrosive where any GI decontamination is contraindicated.", learningObjective: "Identify appropriate indications for whole bowel irrigation, particularly body packing and substances not adsorbed by charcoal", examTrap: "WBI is indicated for body packers, sustained-release medications, and substances not adsorbed by charcoal (iron, lead, lithium)", clinicalPearls: ["WBI rate: 1-2 L/hour adults, 25 mL/kg/hour children via NGT", "Continue until rectal effluent is clear", "Best indication: body packers with intact packets", "Contraindicated with bowel obstruction, perforation, or hemodynamic instability"], safetyNote: "Body packer with any symptoms of packet rupture requires immediate surgical consultation regardless of WBI status", distractorRationales: ["Aspirin is well-adsorbed by activated charcoal; WBI is unnecessary", "Bleach is corrosive; any GI decontamination is contraindicated", "Mild acetaminophen ingestion at 45 minutes is best treated with activated charcoal"], lessonSlug: "activated-charcoal-decontamination", difficulty: 3, cognitiveLevel: "application", questionType: "MCQ_SINGLE" },
    ]},
  };

  const questions: any[] = [];
  let idCounter = 51;

  for (const [subtopic, data] of Object.entries(subtopicData)) {
    for (const q of data.topics) {
      questions.push({
        id: `en-tox-${String(idCounter).padStart(3, '0')}`,
        stem: q.stem,
        options: q.options,
        correctAnswer: q.correctAnswer,
        rationaleLong: q.rationaleLong,
        learningObjective: q.learningObjective,
        blueprintCategory: "Toxicology",
        subtopic,
        difficulty: q.difficulty,
        cognitiveLevel: q.cognitiveLevel,
        questionType: q.questionType,
        examTrap: q.examTrap,
        clinicalPearls: q.clinicalPearls,
        safetyNote: q.safetyNote,
        distractorRationales: q.distractorRationales,
        lessonLink: `/emergency/lessons/${q.lessonSlug}`
      });
      idCounter++;
    }
  }
  return questions;
}
