export function generateExpandedToxQuestions() {
  const q: any[] = [];
  let id = 80;
  const mk = (stem: string, options: string[], ca: number, rat: string, lo: string, cat: string, sub: string, diff: number, cog: string, et: string, pearls: string[], sn: string, dr: string[], slug: string) => {
    q.push({ id: `en-tox-${String(id++).padStart(3,'0')}`, stem, options, correctAnswer: ca, rationaleLong: rat, learningObjective: lo, blueprintCategory: cat, subtopic: sub, difficulty: diff, cognitiveLevel: cog, questionType: "MCQ_SINGLE", examTrap: et, clinicalPearls: pearls, safetyNote: sn, distractorRationales: dr, lessonLink: `/emergency/lessons/${slug}` });
  };

  mk("A 24-year-old male presents with tachycardia, hypertension, diaphoresis, and chest pain after using crack cocaine. Troponin is mildly elevated. Which first-line medication should the nurse administer for cocaine-induced acute coronary syndrome?",
    ["Benzodiazepine (diazepam or lorazepam IV) for sympatholysis and coronary vasodilation", "Metoprolol IV for rate control", "Aspirin only and monitor", "Immediate thrombolytic therapy"],
    0, "Benzodiazepines are first-line for cocaine-associated chest pain because they reduce sympathetic drive, lower heart rate and blood pressure through central anxiolysis, and indirectly promote coronary vasodilation. Cocaine blocks norepinephrine reuptake causing excessive adrenergic stimulation. Beta-blockers are contraindicated due to risk of unopposed alpha stimulation causing paradoxical worsening of coronary vasospasm and hypertension. Aspirin is important but does not address the catecholamine surge. Thrombolytics carry high bleeding risk in cocaine users and should be reserved for confirmed STEMI without PCI availability.", "Administer benzodiazepines as first-line treatment for cocaine-induced acute coronary syndrome", "Toxicology", "Sympathomimetic Toxidrome", 3, "application",
    "Beta-blockers are contraindicated in cocaine ACS; benzodiazepines are the correct first-line treatment for sympatholysis",
    ["Benzodiazepines reduce sympathetic drive and indirectly promote coronary vasodilation", "Beta-blockers cause unopposed alpha stimulation with cocaine use", "Nitroglycerin is safe adjunct for cocaine-related coronary vasospasm", "Consider phentolamine for refractory hypertension"],
    "Always screen for cocaine use before administering beta-blockers in young patients with chest pain",
    ["Metoprolol causes unopposed alpha stimulation worsening vasospasm", "Aspirin alone doesn't address the catecholamine surge", "Thrombolytics carry high bleeding risk in cocaine users"],
    "sympathomimetic-toxidrome");

  mk("A 55-year-old male is brought to the ED after a workplace exposure to hydrofluoric acid on his left hand. He reports severe pain out of proportion to the visible burn. What is the specific treatment?",
    ["Topical calcium gluconate gel 2.5% applied to the affected area, with possible subcutaneous or intra-arterial calcium gluconate injection", "Cold water irrigation only", "Silver sulfadiazine cream application", "Oral calcium supplements"],
    0, "Hydrofluoric acid (HF) burns are unique chemical injuries because the fluoride ion penetrates deeply into tissues, chelating calcium and magnesium, causing liquefactive necrosis and severe hypocalcemia at the tissue level. The hallmark is pain out of proportion to the visible injury. Topical calcium gluconate gel 2.5% is the first-line treatment, applied liberally and massaged into the affected area. The calcium binds the free fluoride ions, neutralizing the ongoing tissue destruction. For severe burns or if topical therapy fails, subcutaneous calcium gluconate injection around the burn or intra-arterial calcium gluconate infusion into the affected extremity may be necessary. Systemic hypocalcemia can develop with large burns, potentially causing fatal cardiac dysrhythmias. ECG monitoring and serial calcium levels are essential. Cold water irrigation is the initial decontamination step but does not address the ongoing fluoride penetration.", "Treat hydrofluoric acid burns with calcium gluconate to neutralize fluoride ions and prevent tissue destruction", "Toxicology", "Toxicology Screening and Antidote Protocols", 4, "application",
    "HF burns cause pain disproportionate to visible injury because fluoride ions penetrate deeply chelating tissue calcium",
    ["Fluoride ions penetrate deeply chelating calcium and magnesium", "Topical calcium gluconate 2.5% gel is first-line treatment", "Large HF burns can cause systemic hypocalcemia and cardiac arrest", "Subcutaneous or intra-arterial calcium gluconate for severe cases"],
    "HF burns involving more than 2% BSA or concentrated HF can cause fatal systemic hypocalcemia; monitor ECG and serum calcium",
    ["Cold water irrigation is initial decon only, not definitive treatment", "Silver sulfadiazine doesn't address fluoride ion toxicity", "Oral calcium is too slow and doesn't treat local tissue damage"],
    "toxicology-screening-antidotes");

  mk("An emergency nurse is caring for a patient with suspected gamma-hydroxybutyrate (GHB) overdose. The patient is alternating between deep sedation and sudden periods of combative agitation. What management approach is most appropriate?",
    ["Supportive care with airway management during sedation and benzodiazepines for agitation episodes; avoid intubation if possible as recovery is typically rapid", "Administer flumazenil for reversal", "Give naloxone for opioid-like sedation", "Restrain the patient and sedate with propofol"],
    0, "GHB toxicity produces a characteristic pattern of alternating deep sedation with sudden periods of extreme agitation, often triggered by stimulation such as vital sign checks or IV access attempts. This pattern distinguishes GHB from other sedative-hypnotic overdoses. GHB acts primarily on GABA-B receptors and GHB-specific receptors, producing dose-dependent CNS depression. There is no specific reversal agent. Management is supportive: protect the airway during periods of sedation (patients often maintain airway reflexes despite appearing deeply sedated), use benzodiazepines for agitation episodes, and avoid intubation if possible since GHB is rapidly metabolized with a half-life of 20-50 minutes, and most patients recover within 2-5 hours. Flumazenil (GABA-A antagonist) has minimal effect on GHB's GABA-B activity. Naloxone is ineffective as GHB is not an opioid. Propofol sedation risks over-sedation compounding the GHB effects.", "Manage GHB toxicity with supportive care recognizing the alternating sedation-agitation pattern and rapid spontaneous recovery", "Toxicology", "Toxicology Screening and Antidote Protocols", 3, "application",
    "GHB has rapid metabolism (half-life 20-50 min) with recovery in 2-5 hours; avoid unnecessary intubation in patients maintaining airway reflexes",
    ["GHB causes alternating deep sedation and sudden combative agitation", "Half-life 20-50 minutes; most patients recover in 2-5 hours", "No specific reversal agent; supportive care is mainstay", "Patients often maintain airway reflexes despite appearing deeply sedated"],
    "GHB withdrawal can be severe and life-threatening; patients with chronic GHB use who suddenly stop may develop seizures and autonomic instability",
    ["Flumazenil has minimal effect on GABA-B mediated GHB activity", "Naloxone is ineffective as GHB is not an opioid agonist", "Propofol compounds CNS depression and risks over-sedation"],
    "toxicology-screening-antidotes");

  mk("A patient presents with a severe local reaction after a brown recluse spider bite: central necrotic area with surrounding erythema and violaceous discoloration. What is the appropriate management?",
    ["Wound care, pain management, tetanus prophylaxis, and close follow-up for wound monitoring; dapsone may be considered for severe cases", "Immediate surgical excision of the necrotic area", "Apply ice and a tourniquet above the bite", "Administer CroFab antivenom"],
    0, "Brown recluse (Loxosceles reclusa) envenomation produces a dermonecrotic lesion from sphingomyelinase D in the venom, which causes complement-mediated destruction of cell membranes. The classic presentation is a 'red, white, and blue' sign: central pallor or necrosis (white/blue), surrounded by erythema (red). Management is primarily conservative: wound care with gentle cleaning, pain management, tetanus prophylaxis if not current, and close follow-up for wound monitoring every 48-72 hours. Dapsone (an anti-neutrophilic agent) may be considered for severe cases to reduce the neutrophil-mediated tissue destruction, though its efficacy is debated. Immediate surgical excision is contraindicated in the acute phase as it can extend the wound and worsen outcomes; excision may be considered after 6-8 weeks if necessary. There is no commercially available antivenom for brown recluse in the US (though one exists in research settings). CroFab is for pit viper envenomation only. Tourniquets and ice are not indicated.", "Manage brown recluse spider envenomation with conservative wound care and monitoring, avoiding early surgical excision", "Toxicology", "Toxicology Screening and Antidote Protocols", 3, "application",
    "Early surgical excision of brown recluse bites worsens outcomes; conservative management with delayed excision (6-8 weeks) if needed is preferred",
    ["Brown recluse venom contains sphingomyelinase D causing dermonecrosis", "Red, white, and blue sign: erythema, pallor/necrosis, violaceous border", "No commercially available antivenom in the US", "Dapsone may reduce neutrophil-mediated tissue destruction"],
    "Brown recluse bites rarely cause systemic loxoscelism (hemolytic anemia, DIC, renal failure); monitor for these complications in children",
    ["Early surgical excision extends the wound and worsens outcomes", "Ice and tourniquets are not indicated for spider bites", "CroFab is for pit viper envenomation only, not spider bites"],
    "toxicology-screening-antidotes");

  mk("A 68-year-old female on dabigatran (Pradaxa) presents with a massive GI bleed and hemodynamic instability. Which reversal agent should the nurse prepare?",
    ["Idarucizumab (Praxbind) 5g IV as specific reversal agent for dabigatran", "Vitamin K 10 mg IV", "4-factor PCC (Kcentra)", "Protamine sulfate"],
    0, "Idarucizumab (Praxbind) is the specific reversal agent for dabigatran, a direct thrombin inhibitor. Idarucizumab is a humanized monoclonal antibody fragment that binds dabigatran with 350-fold greater affinity than thrombin, effectively neutralizing its anticoagulant effect within minutes. The dose is 5g IV given as two 2.5g boluses no more than 15 minutes apart. It provides complete reversal within 10-30 minutes with sustained effect for at least 24 hours. Vitamin K reverses warfarin, not dabigatran. While 4-factor PCC has been used off-label for dabigatran reversal, idarucizumab is the specific approved agent. Protamine reverses heparin and has no effect on dabigatran. For factor Xa inhibitors (rivaroxaban, apixaban), andexanet alfa (Andexxa) is the specific reversal agent. Knowing which reversal agent matches which anticoagulant is essential: warfarin → vitamin K + PCC; dabigatran → idarucizumab; factor Xa inhibitors → andexanet alfa; heparin → protamine.", "Administer idarucizumab as the specific reversal agent for life-threatening bleeding on dabigatran", "Toxicology", "Toxicology Screening and Antidote Protocols", 3, "recall",
    "Match anticoagulant to reversal: warfarin→vitamin K/PCC, dabigatran→idarucizumab, Xa inhibitors→andexanet alfa, heparin→protamine",
    ["Idarucizumab binds dabigatran with 350x greater affinity than thrombin", "Dose: 5g IV as two 2.5g boluses, max 15 minutes apart", "Complete reversal within 10-30 minutes, lasting 24+ hours", "Andexanet alfa for factor Xa inhibitor reversal"],
    "Know which reversal agent matches which anticoagulant; administering the wrong reversal agent wastes critical time in hemorrhagic emergencies",
    ["Vitamin K reverses warfarin, not dabigatran", "PCC may be used off-label but idarucizumab is the specific approved agent", "Protamine reverses heparin only"],
    "toxicology-screening-antidotes");

  mk("A patient presents after ingesting windshield washer fluid. The nurse suspects methanol poisoning. Which bedside test can help differentiate methanol from ethanol intoxication?",
    ["An osmolar gap calculation: a significantly elevated osmolar gap (>10) with the patient appearing intoxicated suggests methanol or ethylene glycol rather than ethanol", "Blood alcohol level alone", "Urine color assessment", "Pupil size measurement"],
    0, "The osmolar gap is a valuable bedside tool for differentiating toxic alcohol (methanol, ethylene glycol) intoxication from ethanol intoxication. The osmolar gap is calculated as: measured serum osmolality minus calculated osmolality (2[Na] + glucose/18 + BUN/2.8 + ethanol/4.6). A gap greater than 10 mOsm/kg suggests the presence of unmeasured osmoles from toxic alcohols. In methanol or ethylene glycol poisoning, the parent alcohol contributes to the osmolar gap early in the course, while the toxic metabolites (formic acid from methanol, glycolic acid from ethylene glycol) contribute to an anion gap metabolic acidosis later. This creates the classic pattern: early elevated osmolar gap transitioning to elevated anion gap as metabolism proceeds. Ethanol also elevates the osmolar gap, but ethanol levels can be directly measured and accounted for in the calculation. A blood alcohol level alone cannot identify toxic alcohol co-ingestion. Urine color is not diagnostic (though calcium oxalate crystals in urine under UV light suggest ethylene glycol). Pupil size is not a reliable differentiator.", "Use the osmolar gap to screen for toxic alcohol ingestion and differentiate from ethanol intoxication", "Toxicology", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "The osmolar gap decreases as toxic alcohols are metabolized while the anion gap increases; both may normalize in late presentation",
    ["Osmolar gap >10 suggests unmeasured osmoles from toxic alcohols", "Early: high osmolar gap; Late: high anion gap as metabolism proceeds", "Account for measured ethanol when calculating osmolar gap", "Both gaps may normalize in late presentations creating a diagnostic challenge"],
    "A normal osmolar gap does not exclude toxic alcohol poisoning in late presentations when the parent alcohol has been fully metabolized to toxic acids",
    ["Blood alcohol level alone cannot detect methanol co-ingestion", "Urine color is not diagnostic for toxic alcohol poisoning", "Pupil size does not reliably differentiate alcohol types"],
    "toxicology-screening-antidotes");

  mk("A nurse notices that a pediatric patient admitted for accidental ingestion is playing with a used fentanyl patch found in the grandmother's waste basket. The child has not yet applied the patch. What immediate concern should the nurse address?",
    ["Even used fentanyl patches retain significant amounts of active drug; assess the child for any oral or dermal exposure and monitor closely for 24 hours", "No concern since the patch is used and depleted", "The patch only poses risk if swallowed whole", "Apply the patch to check if it still releases drug"],
    0, "Used transdermal fentanyl patches retain approximately 28-84% of the original drug content depending on the formulation and wearing duration. A used 100 mcg/hr patch can retain 5-8.4 mg of fentanyl, which is more than sufficient to cause fatal toxicity in a small child (lethal dose in opioid-naive child may be as low as 25 mcg/kg). Exposure routes include: oral (child chewing or sucking on the patch), dermal (handling the adhesive side), or transmucosal (contact with mucous membranes). Assessment should include: inspection of the child's oral cavity for gel residue, checking skin for adhesive marks, monitoring vital signs especially respiratory rate and oxygen saturation, and observation for at least 24 hours due to the depot effect of transdermal fentanyl. Used patches should be folded adhesive side together and disposed of in medication take-back programs or flushed per FDA guidance. This is a prevention education opportunity for the family.", "Recognize that used fentanyl patches retain lethal amounts of active drug posing extreme danger to children", "Toxicology", "Toxic Ingestion in Pediatrics", 2, "application",
    "Used fentanyl patches retain 28-84% of original drug content; even used patches can be lethal to children through oral or dermal exposure",
    ["Used fentanyl patches retain 28-84% of original drug content", "Lethal dose in opioid-naive child may be as low as 25 mcg/kg", "Exposure routes: oral, dermal, transmucosal contact", "Monitor for 24 hours due to depot effect of transdermal fentanyl"],
    "Educate families about proper disposal of used fentanyl patches by folding adhesive side together; used patches are a leading cause of pediatric opioid fatality",
    ["Used patches are NOT depleted and retain dangerous amounts of fentanyl", "Dermal and oral exposure both pose significant risks, not just swallowing", "Testing the patch on the child would cause potentially fatal exposure"],
    "toxic-ingestion-pediatrics");

  mk("A 32-year-old presents with elevated INR of 15.2, epistaxis, and gum bleeding. He admits to ingesting 'super-warfarin' rodenticide (brodifacoum) three days ago in a suicide attempt. How does management differ from warfarin overdose?",
    ["Super-warfarin rodenticides require prolonged vitamin K therapy for weeks to months due to extremely long half-lives (15-20+ days) compared to warfarin's 36-42 hour half-life", "Standard warfarin reversal with a single dose of vitamin K is sufficient", "Super-warfarin does not cause coagulopathy", "Activated charcoal will completely prevent absorption at 3 days"],
    0, "Super-warfarin rodenticides (brodifacoum, difethialone, bromadiolone) have extremely long half-lives of 15-20+ days (brodifacoum half-life is approximately 24 days), requiring prolonged oral vitamin K1 supplementation for weeks to months (typically 3-6 months) to prevent recurrent coagulopathy after initial reversal. This is fundamentally different from pharmaceutical warfarin (half-life 36-42 hours) which typically requires only a few days of vitamin K therapy. Acute management includes IV vitamin K for active bleeding, 4-factor PCC if hemorrhagically unstable, and transition to high-dose oral vitamin K1 (typically 50-100 mg daily, far exceeding the standard 10 mg warfarin reversal dose). Serial INR monitoring is essential, and vitamin K should not be discontinued until the INR remains normal for at least 72 hours after stopping supplementation. Patients require close outpatient follow-up with regular INR checks for months. Activated charcoal at 3 days post-ingestion has no benefit as the rodenticide has been fully absorbed.", "Manage super-warfarin rodenticide poisoning with prolonged vitamin K therapy for weeks to months based on the extremely long half-life", "Toxicology", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "Super-warfarin rodenticides require months of vitamin K therapy due to half-lives of 15-20+ days; a single dose is grossly insufficient",
    ["Brodifacoum half-life ~24 days vs warfarin ~36-42 hours", "Oral vitamin K1 50-100 mg daily for 3-6 months typically needed", "Do not stop vitamin K until INR normal for 72 hours after discontinuation", "4F-PCC for acute hemorrhagic instability"],
    "Premature discontinuation of vitamin K therapy after super-warfarin rodenticide causes recurrent life-threatening coagulopathy; ensure reliable outpatient follow-up",
    ["Single dose vitamin K is grossly insufficient for super-warfarin", "Super-warfarin rodenticides absolutely cause severe coagulopathy", "Activated charcoal at 3 days has no benefit"],
    "toxicology-screening-antidotes");

  mk("A patient who ingested sustained-release potassium chloride in a suicide attempt presents with nausea and vomiting. Current potassium is 5.8 mEq/L. The ECG shows peaked T waves. What decontamination method is most appropriate?",
    ["Whole bowel irrigation with polyethylene glycol solution to remove the sustained-release tablets from the GI tract while treating the hyperkalemia", "Activated charcoal administration", "Gastric lavage with large-bore orogastric tube", "No decontamination needed; treat hyperkalemia only"],
    0, "Sustained-release potassium chloride overdose is an unusual but potentially lethal ingestion. Activated charcoal does NOT adsorb potassium, making it ineffective for this ingestion. Whole bowel irrigation (WBI) with polyethylene glycol electrolyte solution is the most appropriate decontamination method because it can help move the sustained-release tablets through the GI tract before all of the potassium is absorbed. WBI is administered at 1-2 L/hour for adults via NGT until rectal effluent is clear. Simultaneously, the hyperkalemia must be treated aggressively with the standard protocol: IV calcium gluconate for cardiac membrane stabilization, insulin/glucose for potassium shifting, sodium bicarbonate, nebulized albuterol, and preparation for hemodialysis if needed. Gastric lavage is generally not effective for sustained-release tablets and carries aspiration risk. Simply treating the hyperkalemia without addressing the ongoing potassium absorption from the sustained-release tablets in the GI tract would be incomplete management.", "Use whole bowel irrigation for sustained-release potassium overdose since activated charcoal does not adsorb potassium", "Toxicology", "Activated Charcoal and Decontamination", 4, "application",
    "Activated charcoal does NOT adsorb potassium; WBI is the appropriate decontamination method for potassium tablet ingestion",
    ["Activated charcoal does not adsorb potassium, iron, or lithium", "WBI: 1-2 L/hour PEG solution via NGT until clear rectal effluent", "Simultaneously treat hyperkalemia with standard protocol", "Sustained-release tablets continue releasing drug in the GI tract"],
    "Potassium above 6.5 mEq/L with ECG changes is immediately life-threatening; treat hyperkalemia while performing decontamination simultaneously",
    ["Activated charcoal is ineffective as it does not adsorb potassium", "Gastric lavage is generally ineffective for sustained-release tablets", "Treating hyperkalemia alone leaves the ongoing GI source unaddressed"],
    "activated-charcoal-decontamination");

  mk("A patient on levetiracetam and valproic acid for epilepsy presents with bruising, petechiae, and bleeding gums. Labs show platelets 28,000/mm3 and ammonia 180 mcmol/L. Which medication is most likely causing these findings?",
    ["Valproic acid causing both thrombocytopenia and hyperammonemia", "Levetiracetam", "The combination of both medications equally", "Neither medication; this is an unrelated condition"],
    0, "Valproic acid (VPA) toxicity commonly causes thrombocytopenia and hyperammonemia, both of which are present in this patient. VPA-induced thrombocytopenia occurs through dose-dependent bone marrow suppression and direct toxic effects on megakaryocytes; it typically manifests when VPA levels exceed the therapeutic range or with chronic use. VPA-induced hyperammonemia occurs through inhibition of carbamoyl phosphate synthetase I in the urea cycle and can occur even with therapeutic VPA levels. The ammonia of 180 mcmol/L (normal <50) indicates significant urea cycle disruption. Treatment includes reducing or discontinuing VPA, administering L-carnitine (which is depleted by VPA and is necessary for normal mitochondrial function), and supportive care. L-carnitine dose is 100 mg/kg IV (max 6g) loading dose, then 50 mg/kg every 8 hours. Levetiracetam does not typically cause thrombocytopenia or hyperammonemia. This presentation demonstrates the importance of monitoring VPA levels, platelet counts, ammonia levels, and liver function in patients on chronic VPA therapy.", "Recognize valproic acid as a cause of thrombocytopenia and hyperammonemia requiring L-carnitine supplementation", "Toxicology", "Toxicology Screening and Antidote Protocols", 3, "analysis",
    "VPA causes hyperammonemia even at therapeutic levels through urea cycle enzyme inhibition; L-carnitine is the specific treatment",
    ["VPA inhibits carbamoyl phosphate synthetase I in urea cycle", "Hyperammonemia can occur even with therapeutic VPA levels", "L-carnitine: 100 mg/kg IV loading, then 50 mg/kg q8h", "Monitor VPA levels, platelets, ammonia, and liver function"],
    "VPA-induced hyperammonemic encephalopathy can mimic hepatic encephalopathy; check ammonia in any patient on VPA with altered mental status",
    ["Levetiracetam does not typically cause these effects", "The effects are specific to valproic acid, not the combination", "Both findings are well-established adverse effects of VPA"],
    "toxicology-screening-antidotes");

  mk("A 40-year-old male with schizophrenia presents confused and lethargic after starting clozapine 2 weeks ago. Labs show WBC 800/mm3 with ANC 200/mm3. Temperature is 38.9°C. What is the most critical concern?",
    ["Clozapine-induced agranulocytosis with severe neutropenia creating high risk for life-threatening infection requiring immediate discontinuation and reverse isolation", "Mild leukopenia that will resolve spontaneously", "Clozapine-induced sedation only", "Normal response to clozapine initiation"],
    0, "This patient has clozapine-induced agranulocytosis, a rare (approximately 1%) but potentially fatal adverse effect of clozapine therapy. Agranulocytosis is defined as ANC below 500/mm3; this patient's ANC of 200/mm3 represents severe agranulocytosis with extreme vulnerability to bacterial and fungal infections. The fever of 38.9°C in the setting of severe neutropenia constitutes a medical emergency (febrile neutropenia). Immediate actions include: (1) Permanent discontinuation of clozapine (the drug can never be restarted); (2) Reverse isolation to minimize infection exposure; (3) Blood cultures (at least 2 sets) before antibiotics; (4) Broad-spectrum empiric antibiotics immediately after cultures (do not wait for results); (5) G-CSF (filgrastim) to stimulate neutrophil production; (6) Infectious disease and hematology consultation. Clozapine requires mandatory ANC monitoring through the Clozapine REMS Program precisely because of this risk. This is not a self-limiting condition; untreated agranulocytosis with febrile neutropenia carries high mortality.", "Recognize clozapine-induced agranulocytosis as a medical emergency requiring immediate drug discontinuation, reverse isolation, and empiric antibiotics", "Toxicology", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "Clozapine-induced agranulocytosis requires permanent discontinuation; the drug can NEVER be restarted after agranulocytosis",
    ["Agranulocytosis: ANC <500; severe agranulocytosis: ANC <200", "Febrile neutropenia is a medical emergency requiring empiric antibiotics", "Clozapine requires mandatory ANC monitoring through REMS program", "G-CSF (filgrastim) stimulates neutrophil production"],
    "Febrile neutropenia carries high mortality; start broad-spectrum antibiotics immediately after cultures, do not wait for results",
    ["This is not mild or self-limiting; ANC 200 is a medical emergency", "Lethargy is concerning but agranulocytosis is the life-threatening issue", "This is NOT a normal response; it requires permanent drug discontinuation"],
    "toxicology-screening-antidotes");

  mk("A 5-year-old child presents to the ED after ingesting several of grandfather's metformin tablets. Current blood glucose is 82 mg/dL. The parent asks if the child can go home since the glucose is normal. What should the nurse explain?",
    ["Metformin does not typically cause hypoglycemia but can cause lactic acidosis which may develop on a delayed basis; the child needs observation and serial monitoring", "The child is safe since glucose is normal and can be discharged", "Metformin always causes immediate hypoglycemia in children", "Only adults are affected by metformin toxicity"],
    0, "Metformin toxicity presents differently from other diabetic medication overdoses because metformin does not directly cause hypoglycemia (it works by reducing hepatic glucose production and improving insulin sensitivity, not by stimulating insulin release). The primary concern in metformin ingestion is lactic acidosis, which can develop on a delayed basis as the drug accumulates and inhibits mitochondrial complex I. In pediatric ingestions, the risk depends on the dose ingested per kilogram. Even with a normal initial glucose, the child requires: (1) Observation for at least 12-24 hours; (2) Serial lactate levels every 2-4 hours; (3) Serial BMP including bicarbonate and anion gap; (4) Monitoring for clinical signs of lactic acidosis: nausea, vomiting, abdominal pain, tachypnea, altered mental status. (5) If lactic acidosis develops, treatment includes IV bicarbonate and hemodialysis. Renal function should also be monitored as impaired clearance increases metformin accumulation. Discharging based on normal glucose alone could result in the child developing fatal lactic acidosis at home.", "Monitor pediatric metformin ingestion for delayed lactic acidosis development regardless of normal glucose levels", "Toxicology", "Toxic Ingestion in Pediatrics", 3, "application",
    "Metformin does NOT cause hypoglycemia; the danger is delayed lactic acidosis from mitochondrial complex I inhibition",
    ["Metformin does not stimulate insulin release so does not cause hypoglycemia", "Primary toxicity is lactic acidosis from mitochondrial dysfunction", "Observe 12-24 hours with serial lactate and BMP monitoring", "Hemodialysis effectively removes metformin if lactic acidosis develops"],
    "Never discharge a pediatric metformin ingestion based solely on normal glucose; delayed lactic acidosis can develop hours later and be fatal",
    ["Normal glucose does not rule out significant metformin toxicity", "Metformin causes lactic acidosis, not hypoglycemia as its primary toxicity", "Children are also susceptible to metformin toxicity"],
    "toxic-ingestion-pediatrics");

  mk("A 72-year-old male presents obtunded after his wife accidentally gave him her insulin glargine (Lantus) injection instead of his B12 shot. Blood glucose is 28 mg/dL. After IV dextrose bolus restores glucose to 120 mg/dL, what should the nurse anticipate?",
    ["Prolonged monitoring with continuous dextrose infusion for 24+ hours due to insulin glargine's duration of action of up to 24 hours", "The patient can be discharged after glucose normalizes with one dextrose bolus", "Administer glucagon IM and observe for 4 hours", "Give oral glucose tablets and discharge"],
    0, "Insulin glargine (Lantus) is a long-acting basal insulin with a duration of action of up to 24 hours (with no discernible peak). Accidental administration requires prolonged monitoring and treatment because: (1) A single dextrose bolus will temporarily raise glucose but the ongoing insulin effect will cause recurrent hypoglycemia for up to 24 hours; (2) A continuous D10W infusion is typically required, titrated to maintain glucose above 100 mg/dL; (3) Frequent glucose monitoring every 1-2 hours is essential; (4) The patient should be admitted for observation for at least 24 hours after the last insulin glargine dose. Glucagon may provide temporary glucose elevation by mobilizing hepatic glycogen stores but has limited duration (60-90 minutes) and becomes ineffective once glycogen stores are depleted. Discharging after a single glucose correction would be dangerous as recurrent hypoglycemia would occur at home without monitoring. Oral glucose alone is insufficient for prolonged insulin effect and inappropriate in an obtunded patient.", "Manage long-acting insulin overdose with prolonged D10W infusion and monitoring matching the insulin's duration of action", "Toxicology", "Toxicology Screening and Antidote Protocols", 3, "application",
    "Long-acting insulin (glargine) requires 24+ hours of glucose monitoring and dextrose infusion; a single bolus correction is insufficient",
    ["Insulin glargine duration of action up to 24 hours", "Continuous D10W infusion needed, not just dextrose boluses", "Monitor glucose every 1-2 hours for at least 24 hours", "Glucagon becomes ineffective once glycogen stores are depleted"],
    "Accidental insulin administration in non-diabetic patients requires aggressive monitoring; recurrent hypoglycemia without monitoring can cause fatal brain injury",
    ["Single dextrose bolus provides only temporary correction", "Glucagon is insufficient for prolonged insulin effect", "Oral glucose is inappropriate for obtunded patients"],
    "toxicology-screening-antidotes");

  mk("A 30-year-old female presents with muscle cramps, perioral tingling, and QT prolongation after ingesting excessive amounts of an over-the-counter antacid containing magnesium citrate for a 'colon cleanse.' Serum magnesium is 6.8 mg/dL. What treatment should the nurse prepare?",
    ["IV calcium gluconate to antagonize the cardiac effects of hypermagnesemia, IV normal saline for volume expansion and renal magnesium excretion, and possible hemodialysis", "Oral magnesium citrate to continue the cleanse", "IV magnesium sulfate for the muscle cramps", "No treatment needed as the level will normalize on its own"],
    0, "Hypermagnesemia (normal 1.7-2.2 mg/dL; this patient has 6.8 mg/dL) is a potentially life-threatening electrolyte emergency. Magnesium excess causes progressive neuromuscular and cardiac depression: 4-7 mg/dL causes nausea, flushing, hypotension, bradycardia; 7-12 mg/dL causes areflexia, respiratory depression, QT prolongation; above 12 mg/dL causes complete heart block and cardiac arrest. Treatment includes: (1) IV calcium gluconate (10 mL of 10% solution over 2-3 minutes) which directly antagonizes magnesium's effects on cardiac and neuromuscular function; (2) IV normal saline to expand volume and promote renal magnesium excretion; (3) Loop diuretics (furosemide) to enhance renal magnesium clearance if renal function is adequate; (4) Hemodialysis for severe hypermagnesemia, renal impairment, or cardiovascular instability. IV magnesium sulfate would be contraindicated as it would worsen the hypermagnesemia. Additional magnesium intake should be immediately stopped.", "Treat severe hypermagnesemia with IV calcium gluconate for cardiac protection and saline diuresis for magnesium elimination", "Toxicology", "Toxicology Screening and Antidote Protocols", 3, "application",
    "QT prolongation from hypermagnesemia can progress to complete heart block and cardiac arrest; IV calcium gluconate provides immediate cardiac protection",
    ["Progressive toxicity: nausea/flushing -> areflexia/respiratory depression -> cardiac arrest", "IV calcium gluconate antagonizes magnesium's cardiac and neuromuscular effects", "Saline and loop diuretics promote renal magnesium excretion", "Hemodialysis for severe cases or renal impairment"],
    "Patients on chronic magnesium supplementation with renal impairment are at highest risk for iatrogenic hypermagnesemia",
    ["Continuing magnesium intake would worsen a life-threatening toxicity", "IV magnesium would be contraindicated in the setting of hypermagnesemia", "Untreated severe hypermagnesemia can progress to cardiac arrest"],
    "toxicology-screening-antidotes");

  // More expanded tox questions to reach target
  const additionalTox = [
    { s: "A patient presents after ingesting a 'death cap' mushroom. Initial GI symptoms have resolved and she feels well 24 hours later. Should she be discharged?", o: ["No, the apparent recovery phase (Phase II) of Amanita phalloides poisoning is deceptively benign; fulminant hepatic failure (Phase III) typically develops in 3-5 days", "Yes, symptom resolution indicates recovery", "Only if liver enzymes are normal", "Discharge with oral antibiotics"], ca: 0, r: "Amanita phalloides poisoning follows a triphasic course: Phase I (6-24h) GI symptoms, Phase II (24-48h) apparent recovery with deceptively normal labs, Phase III (3-5d) fulminant hepatic failure. The apparent improvement in Phase II leads to premature discharge, which can be fatal. Treatment includes NAC for hepatoprotection, silibinin or penicillin G, aggressive fluids, and hepatology consultation for possible transplant evaluation. Serial liver function tests every 6-12 hours are mandatory.", lo: "Recognize the deceptive Phase II of Amanita phalloides poisoning and prevent premature discharge", sub: "Toxicology Screening and Antidote Protocols", d: 4, c: "analysis", et: "Phase II apparent recovery in Amanita poisoning is the most dangerous period for premature discharge; never release these patients during this phase", p: ["Amanita poisoning: Phase I GI, Phase II apparent recovery, Phase III hepatic failure", "Serial liver function tests q6-12h mandatory", "NAC provides hepatoprotection even in mushroom poisoning", "Liver transplant evaluation should begin early"], sn: "Amanita phalloides has a 10-30% mortality rate; premature discharge during the apparent recovery phase is a known cause of preventable death", dr: ["Symptom resolution in Phase II does not indicate recovery", "Normal labs in Phase II can be falsely reassuring; hepatic failure develops in Phase III", "Outpatient management is inappropriate for death cap mushroom ingestion"], sl: "toxicology-screening-antidotes" },
    { s: "A 28-year-old male presents with severe anxiety, tremors, tachycardia, and hypertension 18 hours after his last dose of alprazolam, which he has been taking 6 mg daily for 3 years. What is the priority treatment?", o: ["Administer long-acting benzodiazepine (diazepam or chlordiazepoxide) in a cross-tolerant substitution protocol to prevent withdrawal seizures", "Tell the patient to continue alprazolam at his usual dose", "Administer phenytoin for seizure prophylaxis", "Provide supportive care only without pharmacotherapy"], ca: 0, r: "This patient is experiencing benzodiazepine withdrawal from abrupt cessation of high-dose alprazolam, a short-acting benzodiazepine. Benzodiazepine withdrawal can be life-threatening, causing seizures (potentially status epilepticus), psychosis, and autonomic instability. The standard treatment is cross-tolerant substitution with a long-acting benzodiazepine (diazepam or chlordiazepoxide), which provides smoother tapering due to the longer half-life (diazepam t½ 20-100 hours vs alprazolam t½ 6-12 hours). The conversion is approximately 0.5 mg alprazolam = 5 mg diazepam. This patient's 6 mg alprazolam ≈ 60 mg diazepam equivalent, indicating severe physical dependence. The long-acting benzodiazepine is then gradually tapered over weeks to months. Phenytoin is NOT effective for benzodiazepine withdrawal seizures (similar to alcohol withdrawal seizures). Supportive care alone risks fatal withdrawal seizures.", lo: "Manage benzodiazepine withdrawal with cross-tolerant substitution using long-acting benzodiazepines", sub: "Benzodiazepine Toxicity", d: 3, c: "application", et: "Phenytoin does NOT prevent benzodiazepine withdrawal seizures; only benzodiazepines are effective", p: ["Cross-tolerant substitution: short-acting to long-acting benzodiazepine", "Conversion: 0.5 mg alprazolam ≈ 5 mg diazepam", "BZD withdrawal can cause seizures, psychosis, and death", "Taper over weeks to months from the equivalent long-acting dose"], sn: "Abrupt discontinuation of high-dose benzodiazepines can cause fatal withdrawal seizures; never abruptly stop chronic benzodiazepine use", dr: ["Continuing current dose without tapering plan perpetuates dependence", "Phenytoin is ineffective for BZD withdrawal seizures", "Supportive care alone risks fatal withdrawal seizures"], sl: "benzodiazepine-toxicity" },
    { s: "A patient presents with hemolytic anemia, dark urine, and jaundice after eating fava beans. He is of Mediterranean descent. The nurse suspects glucose-6-phosphate dehydrogenase (G6PD) deficiency. Which medications should be AVOIDED in this patient?", o: ["Methylene blue, sulfonamides, primaquine, dapsone, and aspirin in high doses - all cause oxidative stress in G6PD-deficient patients", "Acetaminophen at standard doses", "IV normal saline", "Oral rehydration solutions"], ca: 0, r: "G6PD deficiency is the most common enzyme deficiency worldwide, particularly prevalent in people of Mediterranean, African, and Southeast Asian descent. G6PD is essential for maintaining glutathione in its reduced form, which protects red blood cells from oxidative stress. Without adequate G6PD activity, exposure to oxidant stressors triggers hemolytic crisis. Known triggers include: medications (sulfonamides, primaquine, dapsone, methylene blue, nitrofurantoin, high-dose aspirin), infections, and certain foods (fava beans - favism). The most critical medication to avoid in the ED setting is methylene blue, which is paradoxically used to treat methemoglobinemia but requires the NADPH-methemoglobin reductase pathway (dependent on G6PD) to function. In G6PD-deficient patients, methylene blue not only fails to treat methemoglobinemia but can worsen hemolysis. Alternative treatment for methemoglobinemia in G6PD deficiency includes ascorbic acid and exchange transfusion.", lo: "Identify medications contraindicated in G6PD deficiency that cause oxidative stress-induced hemolysis", sub: "Toxicology Screening and Antidote Protocols", d: 3, c: "recall", et: "Methylene blue is CONTRAINDICATED in G6PD deficiency because it requires the G6PD-dependent NADPH pathway to work and worsens hemolysis", p: ["G6PD deficiency: most common enzyme deficiency worldwide", "Triggers: sulfonamides, primaquine, dapsone, methylene blue, fava beans", "Methylene blue requires G6PD-dependent pathway; contraindicated in G6PD deficiency", "Alternative methemoglobinemia treatment: ascorbic acid, exchange transfusion"], sn: "Always screen for G6PD deficiency before administering methylene blue for methemoglobinemia; it can worsen hemolysis and is ineffective", dr: ["Acetaminophen at standard doses is safe in G6PD deficiency", "IV normal saline does not cause oxidative stress", "Oral rehydration is safe and supportive"], sl: "toxicology-screening-antidotes" },
    { s: "A patient with known beta-blocker overdose (propranolol) presents with profound bradycardia (HR 30), hypotension (BP 60/30), and hypoglycemia (glucose 42 mg/dL). Standard atropine and flumazenil have been given without response. What rescue therapy should be prepared?", o: ["IV glucagon 5-10 mg bolus followed by 2-5 mg/hour infusion as first-line specific antidote, plus high-dose insulin euglycemia therapy (HIET) as rescue", "Epinephrine drip only", "Transcutaneous pacing only", "IV calcium chloride only"], ca: 0, r: "Glucagon is the first-line specific antidote for severe beta-blocker toxicity because it activates adenylate cyclase through a mechanism independent of the beta-adrenergic receptor, increasing intracellular cAMP and improving cardiac contractility and heart rate even when beta-receptors are completely blocked. The dose for beta-blocker toxicity is 5-10 mg IV bolus (much higher than the 1 mg dose used for hypoglycemia), followed by an infusion of 2-5 mg/hour. Common side effects include nausea and vomiting. If glucagon is insufficient, HIET (insulin 1 unit/kg bolus then 1-10 units/kg/hour with dextrose) provides additional inotropic support through enhanced myocardial glucose utilization. The hypoglycemia (glucose 42) is characteristic of propranolol toxicity because beta-blockers impair glycogenolysis and gluconeogenesis and mask the sympathetic symptoms of hypoglycemia. Epinephrine may have reduced effectiveness when beta-receptors are blocked. Transcutaneous pacing may not capture in severe beta-blocker toxicity. Calcium has limited effect on beta-blocker-mediated cardiac depression.", lo: "Administer glucagon as first-line antidote for beta-blocker toxicity through the receptor-independent adenylate cyclase pathway", sub: "Toxicology Screening and Antidote Protocols", d: 4, c: "analysis", et: "Glucagon dose for beta-blocker toxicity (5-10 mg) is far higher than for hypoglycemia (1 mg); underdosing is a common error", p: ["Glucagon activates adenylate cyclase independent of beta-receptors", "Dose: 5-10 mg IV bolus, then 2-5 mg/hour infusion", "HIET as rescue for glucagon-resistant beta-blocker toxicity", "Beta-blockers mask hypoglycemia symptoms; always check glucose"], sn: "Beta-blocker toxicity can cause refractory bradycardia and hypotension; have glucagon, HIET supplies, and pacing equipment immediately available", dr: ["Epinephrine has reduced effectiveness when beta-receptors are blocked", "Pacing may not capture in severe beta-blocker toxicity", "Calcium has limited effect on beta-blocker cardiac depression"], sl: "toxicology-screening-antidotes" },
    { s: "A 14-year-old is brought to the ED after vaping a THC cartridge. He is anxious, tachycardic, and having his first-ever panic attack. Chest X-ray is clear. SpO2 is 99%. What is the most appropriate management?", o: ["Reassurance, supportive care, benzodiazepine if severe anxiety persists, and monitoring for EVALI symptoms with follow-up instructions", "Immediate intubation for airway protection", "Discharge without any evaluation", "Admission to psychiatric unit for substance abuse"], ca: 0, r: "Acute cannabis/THC intoxication from vaping can cause significant anxiety and panic attacks, especially in adolescents with low tolerance. The acute psychoactive effects of THC include anxiety, paranoia, tachycardia, and altered perception. While these symptoms are typically self-limiting (resolving in 2-6 hours), the nurse should: (1) Provide reassurance and a calm, quiet environment; (2) Administer a low-dose benzodiazepine (lorazepam 0.5-1 mg) if severe anxiety persists; (3) Monitor for E-cigarette or Vaping Product Use-Associated Lung Injury (EVALI), which presents with respiratory symptoms (cough, dyspnea, chest pain), GI symptoms (nausea, vomiting, diarrhea), and constitutional symptoms (fever, fatigue). While this patient's chest X-ray is clear and SpO2 normal, EVALI can develop subacutely; (4) Provide discharge instructions including return precautions for respiratory symptoms; (5) Discuss substance use counseling resources. Intubation is not indicated for anxiety with normal vitals. Discharge without evaluation misses potential complications. Psychiatric admission is excessive for an acute intoxication.", lo: "Manage acute THC vaping intoxication with supportive care and monitor for EVALI symptoms in adolescent patients", sub: "Toxicology Screening and Antidote Protocols", d: 2, c: "application", et: "EVALI can develop subacutely after THC vaping even with initially normal chest imaging; provide return precautions for respiratory symptoms", p: ["Acute THC effects: anxiety, paranoia, tachycardia, altered perception", "Effects typically resolve in 2-6 hours", "EVALI: respiratory, GI, constitutional symptoms from vaping", "Benzodiazepines for persistent severe anxiety"], sn: "Adolescent vaping with THC requires screening for EVALI and substance use counseling referral in addition to acute symptom management", dr: ["Intubation is not indicated for anxiety with normal oxygenation", "Discharge without evaluation misses potential EVALI and safety concerns", "Psychiatric admission is excessive for acute intoxication without suicidal ideation"], sl: "toxicology-screening-antidotes" },
  ];
  for (const a of additionalTox) {
    q.push({
      id: `en-tox-${String(id++).padStart(3,'0')}`, stem: a.s, options: a.o, correctAnswer: a.ca, rationaleLong: a.r, learningObjective: a.lo,
      blueprintCategory: "Toxicology", subtopic: a.sub, difficulty: a.d, cognitiveLevel: a.c, questionType: "MCQ_SINGLE",
      examTrap: a.et, clinicalPearls: a.p, safetyNote: a.sn, distractorRationales: a.dr, lessonLink: `/emergency/lessons/${a.sl}`
    });
  }

  return q;
}
