export function generateFinalToxQuestions() {
  const q: any[] = [];
  let id = 140;
  const mk = (s: string, o: string[], ca: number, r: string, lo: string, sub: string, d: number, c: string, et: string, p: string[], sn: string, dr: string[], sl: string) => {
    q.push({ id: `en-tox-${String(id++).padStart(3,'0')}`, stem: s, options: o, correctAnswer: ca, rationaleLong: r, learningObjective: lo, blueprintCategory: "Toxicology", subtopic: sub, difficulty: d, cognitiveLevel: c, questionType: "MCQ_SINGLE", examTrap: et, clinicalPearls: p, safetyNote: sn, distractorRationales: dr, lessonLink: `/emergency/lessons/${sl}` });
  };

  mk("A nurse is preparing to administer NAC for acetaminophen overdose. The physician orders the 21-hour IV protocol. What are the three phases of the standard NAC IV protocol?",
    ["Loading dose: 150 mg/kg over 60 minutes, second infusion: 50 mg/kg over 4 hours, third infusion: 100 mg/kg over 16 hours", "Single bolus of 300 mg/kg over 21 hours", "Three equal doses of 100 mg/kg every 7 hours", "150 mg/kg over 15 minutes followed by observation"],
    0, "The standard 21-hour IV NAC protocol consists of three phases with decreasing concentrations but increasing durations: (1) Loading dose: 150 mg/kg in 200 mL D5W over 60 minutes - this is the most concentrated phase and the one most likely to cause anaphylactoid reactions; (2) Second infusion: 50 mg/kg in 500 mL D5W over 4 hours; (3) Third infusion: 100 mg/kg in 1000 mL D5W over 16 hours. The total NAC dose delivered over 21 hours is 300 mg/kg. It is critical that the nurse calculate doses accurately based on actual body weight, mix each bag according to the protocol, and monitor closely during the loading dose (first hour) when anaphylactoid reactions are most common. For patients weighing more than 100 kg, dosing should be capped at 100 kg to prevent fluid overload. The loading dose infusion rate should be reduced if anaphylactoid symptoms develop. In obese patients, some institutions use lean body weight for dosing calculations.", "Describe the three phases of the 21-hour IV NAC protocol including dosing, infusion rates, and monitoring priorities", "Acetaminophen Overdose and NAC Protocol", 2, "recall",
    "The NAC IV protocol has three phases with specific concentrations and durations; anaphylactoid reactions are most common during the concentrated loading dose",
    ["Phase 1: 150 mg/kg in 200mL over 60 min (loading)", "Phase 2: 50 mg/kg in 500mL over 4 hours", "Phase 3: 100 mg/kg in 1000mL over 16 hours", "Cap weight at 100 kg to prevent fluid overload"],
    "Calculation errors are common with the three-phase NAC protocol; use standardized order sets or calculators to prevent dosing mistakes",
    ["Single bolus is not the standard protocol", "Equal doses is not the protocol; concentrations decrease as volume increases", "15-minute infusion is too rapid and would cause severe anaphylactoid reactions"],
    "acetaminophen-overdose");

  mk("A nurse receives a call from a frantic parent whose 18-month-old may have ingested one of grandmother's extended-release metoprolol tablets (25 mg). The child is currently asymptomatic. What should the nurse advise?",
    ["Bring the child to the ED immediately for observation; even a single beta-blocker tablet can cause life-threatening toxicity in a toddler due to weight-based dosing disproportionality", "One tablet is not enough to cause harm in anyone", "Monitor at home and bring to ED only if symptoms develop", "Give the child milk to bind the medication"],
    0, "Many common adult medications can be fatal to toddlers with a single tablet ingestion, often referred to as 'one pill can kill' medications. Extended-release beta-blockers are among these dangerous medications. In an 18-month-old weighing approximately 10-12 kg, a single 25 mg metoprolol ER tablet delivers approximately 2-2.5 mg/kg, which can cause significant bradycardia, hypotension, and hypoglycemia. The extended-release formulation adds additional risk because: (1) Symptom onset may be delayed as the drug slowly releases; (2) The extended-release matrix may release the entire dose if the coating is disrupted; (3) Duration of toxicity is prolonged. Other 'one pill can kill' medications for toddlers include: calcium channel blockers, sulfonylureas, opioids, TCAs, camphor, and antimalarials (chloroquine/hydroxychloroquine). The child should be evaluated in the ED with cardiac monitoring for at least 24 hours given the extended-release formulation.", "One Pill Can Kill in Pediatrics", "Toxic Ingestion in Pediatrics", 2, "application",
    "'One pill can kill' medications in toddlers include beta-blockers, CCBs, sulfonylureas, opioids, TCAs, and antimalarials; ED evaluation is mandatory",
    ["Single adult tablet can be lethal in toddlers due to weight-based dosing", "Extended-release formulations delay symptoms and prolong toxicity", "Other 'one pill can kill' meds: CCBs, sulfonylureas, opioids, TCAs", "Monitor at least 24 hours for extended-release formulations"],
    "Home monitoring for potential 'one pill can kill' ingestions in toddlers is dangerous; delayed presentation of symptoms can be fatal",
    ["Single adult medication tablets can absolutely harm a toddler", "Waiting for symptoms risks delayed presentation of life-threatening toxicity", "Milk does not effectively bind beta-blockers"],
    "toxic-ingestion-pediatrics");

  mk("A patient with chronic kidney disease stage 4 presents with acetaminophen overdose. How does renal impairment affect NAC dosing?",
    ["Standard NAC dosing is used; NAC is hepatically metabolized and renal impairment does not significantly affect its pharmacokinetics or efficacy", "Reduce NAC dose by 50% for CKD stage 4", "NAC is contraindicated in renal failure", "Double the NAC dose to compensate for altered metabolism"],
    0, "NAC (N-acetylcysteine) is primarily metabolized hepatically and its pharmacokinetics are not significantly affected by renal impairment. Standard dosing should be used for patients with chronic kidney disease at any stage. However, there are specific considerations for CKD patients with acetaminophen toxicity: (1) Volume of dilution should be adjusted for patients at risk of fluid overload; (2) CKD patients may have lower baseline glutathione levels, potentially making them more susceptible to acetaminophen hepatotoxicity; (3) Acetaminophen itself is not significantly renally cleared, so renal impairment does not increase drug accumulation but may affect metabolite clearance; (4) Patients on hemodialysis may have acetaminophen partially removed during dialysis, complicating level interpretation; (5) NAC has mild volume expansion effects that should be monitored in CKD patients. The key teaching point is that organ impairment affects different drugs differently, and knowing which organ metabolizes each drug is essential for dose adjustment decisions.", "Determine that NAC dosing does not require adjustment for renal impairment while monitoring fluid volume in CKD patients", "Acetaminophen Overdose and NAC Protocol", 3, "application",
    "NAC is hepatically metabolized; renal impairment does not require dose adjustment but fluid volumes should be monitored for overload risk",
    ["NAC hepatically metabolized; standard dosing in CKD", "Adjust dilution volumes for fluid overload risk in CKD", "CKD patients may have lower baseline glutathione levels", "Hemodialysis can partially remove acetaminophen, complicating level interpretation"],
    "NAC infusion volume (total ~1700 mL in standard protocol) may cause fluid overload in CKD/dialysis patients; use reduced-volume protocols if available",
    ["Dose reduction is not needed as NAC is hepatically metabolized", "NAC is not contraindicated in renal failure", "Doubling the dose has no pharmacological rationale"],
    "acetaminophen-overdose");

  mk("A patient with lithium toxicity presents with coarse tremor, confusion, and hyperreflexia. Lithium level is 3.2 mEq/L (therapeutic: 0.6-1.2). What is the primary treatment for severe lithium toxicity?",
    ["Aggressive IV normal saline for volume expansion and hemodialysis for levels >2.5 mEq/L with neurological symptoms", "Activated charcoal to prevent absorption", "Forced alkaline diuresis with sodium bicarbonate", "Chelation therapy with EDTA"],
    0, "Lithium toxicity treatment centers on two principles: (1) Aggressive IV normal saline hydration to restore renal perfusion and enhance lithium excretion. Lithium is a monovalent cation handled similarly to sodium by the kidneys; volume depletion and sodium depletion reduce renal lithium clearance, worsening toxicity. NS at 200-300 mL/hr restores volume and promotes lithium excretion. (2) Hemodialysis is indicated for: levels >2.5 mEq/L with neurological symptoms, levels >4 mEq/L regardless of symptoms, or failure to respond to IV fluids. Hemodialysis rapidly clears lithium from the blood but rebound levels occur 6-8 hours after dialysis as lithium redistributes from tissues, often requiring repeat dialysis sessions. Activated charcoal does NOT adsorb lithium (similar to iron and potassium - small monovalent/divalent ions are not effectively bound by charcoal). Forced alkaline diuresis does not enhance lithium excretion. EDTA chelation does not bind lithium. Whole bowel irrigation may be considered for sustained-release lithium preparations.", "Manage severe lithium toxicity with IV normal saline and hemodialysis recognizing that charcoal does not adsorb lithium", "Toxicology Screening and Antidote Protocols", 3, "application",
    "Activated charcoal does NOT adsorb lithium; treatment is IV NS + hemodialysis. Rebound lithium levels occur 6-8 hours post-dialysis requiring repeat sessions",
    ["Lithium handled like sodium by kidneys; volume depletion worsens toxicity", "Hemodialysis indicated: >2.5 with neuro symptoms, >4 regardless", "Rebound levels 6-8 hours post-dialysis from tissue redistribution", "Charcoal does not adsorb lithium, iron, or potassium"],
    "Post-dialysis lithium rebound is common; continue monitoring levels every 2-4 hours after dialysis and repeat if levels rise above therapeutic range",
    ["Activated charcoal does not adsorb lithium", "Alkaline diuresis does not enhance lithium excretion", "EDTA chelation does not bind lithium"],
    "toxicology-screening-antidotes");

  mk("A patient presents with a unilateral fixed, dilated pupil after instilling eye drops. The nurse should differentiate between which two causes?",
    ["Topical mydriatic eye drops (pharmacological mydriasis) versus acute angle-closure glaucoma or intracranial pathology - the key differentiator is whether the pupil reacts to pilocarpine drops", "The cause is always intracranial herniation", "Unilateral mydriasis is always benign", "Only orbital trauma causes unilateral fixed pupil"],
    0, "Unilateral fixed, dilated pupil (mydriasis) has a critical differential diagnosis that includes: (1) Pharmacological mydriasis from topical eye drops (tropicamide, phenylephrine, atropine), scopolamine patches, or contact with mydriatic plants (jimsonweed/Datura). (2) Third cranial nerve compression from intracranial pathology (transtentorial herniation, posterior communicating artery aneurysm). (3) Acute angle-closure glaucoma. (4) Traumatic mydriasis from direct orbital injury. The key differentiator is the pilocarpine test: a pharmacologically dilated pupil will NOT constrict with 1% pilocarpine drops because the muscarinic receptors are already blocked by the anticholinergic agent. A neurologically dilated pupil (from CN III compression) WILL constrict with pilocarpine because the muscarinic receptors are intact. This distinction is critical because misdiagnosis can lead to unnecessary neurosurgical intervention or, conversely, delayed treatment of a true neurological emergency. Patient and family history about eye drop use and a careful temporal relationship assessment are essential.", "Differentiate pharmacological mydriasis from neurological mydriasis using the pilocarpine test to guide appropriate workup", "Anticholinergic Toxidrome", 3, "analysis",
    "Pilocarpine test differentiates pharmacological mydriasis (won't constrict) from neurological mydriasis (will constrict); prevents unnecessary neurosurgical intervention",
    ["Pharmacological: pupil does NOT respond to pilocarpine", "Neurological: pupil WILL respond to pilocarpine", "Common topical mydriatics: tropicamide, phenylephrine, atropine", "History of eye drop use is the most important initial assessment"],
    "Misdiagnosing pharmacological mydriasis as intracranial herniation leads to unnecessary CT scans, angiography, and neurosurgical consultation",
    ["Unilateral mydriasis has multiple causes, not always herniation", "Unilateral mydriasis is NOT always benign; it can indicate CNS emergency", "Multiple causes exist beyond orbital trauma"],
    "anticholinergic-toxidrome");

  mk("A nurse is caring for a patient who ingested cyanide. The patient's oxygen saturation is reading 100% on pulse oximetry despite being critically ill with metabolic acidosis. Why is the SpO2 misleading?",
    ["Cyanide poisoning causes cytotoxic hypoxia where cells cannot utilize oxygen; venous blood remains oxygenated because oxygen is not extracted, so pulse oximetry reads falsely normal", "The pulse oximeter is broken", "The patient is actually well-oxygenated and improving", "Cyanide improves oxygen delivery"],
    0, "Cyanide poisoning produces a unique form of hypoxia called cytotoxic (histotoxic) hypoxia, where the cells are unable to utilize oxygen for aerobic metabolism despite adequate oxygen delivery. Cyanide inhibits cytochrome c oxidase (Complex IV) in the mitochondrial electron transport chain, blocking the final step of oxidative phosphorylation. Because tissues cannot extract oxygen, venous blood returns to the heart with high oxygen saturation. Pulse oximetry measures arterial hemoglobin oxygen saturation, which is normal (or even supra-normal) because: (1) Oxygen is being delivered to tissues normally; (2) Tissues are not extracting oxygen (hence the acidosis from anaerobic metabolism); (3) Venous blood is highly oxygenated, reducing the arterial-venous oxygen difference. This is why the classic clinical finding of cyanide poisoning is described as 'cherry red' venous blood. The SpO2 is technically accurate in measuring arterial oxygen saturation, but it is clinically misleading because the problem is not oxygen delivery but oxygen utilization. ABG will show normal PaO2 with severe metabolic acidosis and elevated lactate.", "Recognize that pulse oximetry is falsely normal in cyanide poisoning due to cytotoxic hypoxia where oxygen delivery is normal but utilization is blocked", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "Cyanide causes cytotoxic hypoxia where SpO2 reads normal because cells cannot extract oxygen; the problem is utilization, not delivery",
    ["Cyanide inhibits cytochrome c oxidase in mitochondrial Complex IV", "Cells cannot extract O2 → venous blood remains oxygenated", "SpO2 is technically accurate but clinically misleading", "ABG shows normal PaO2 with severe metabolic acidosis and elevated lactate"],
    "Normal SpO2 in a critically ill patient with metabolic acidosis should raise suspicion for cyanide poisoning; do not be reassured by normal pulse oximetry",
    ["The pulse oximeter is functioning correctly; the physiology is deceptive", "Normal SpO2 does not mean the patient is improving in cyanide poisoning", "Cyanide blocks oxygen utilization, not delivery"],
    "toxicology-screening-antidotes");

  mk("A patient with known atrial fibrillation on rivaroxaban (Xarelto) presents with intracranial hemorrhage. Which reversal agent should the nurse prepare?",
    ["Andexanet alfa (Andexxa) as the specific factor Xa inhibitor reversal agent, or 4-factor PCC if andexanet is unavailable", "Vitamin K 10 mg IV", "Protamine sulfate", "Idarucizumab (Praxbind)"],
    0, "Rivaroxaban is a direct factor Xa inhibitor, and its specific reversal agent is andexanet alfa (Andexxa). Andexanet alfa is a modified recombinant factor Xa that acts as a decoy, binding and sequestering the factor Xa inhibitor, thereby restoring normal coagulation. The dosing depends on which factor Xa inhibitor was taken and when: low-dose regimen (400 mg IV bolus then 4 mg/min x 2 hours) for patients who took rivaroxaban >7 hours ago or low-dose apixaban; high-dose regimen (800 mg IV bolus then 8 mg/min x 2 hours) for recent high-dose rivaroxaban or edoxaban. If andexanet alfa is unavailable, 4-factor PCC (Kcentra) 50 units/kg is used off-label as an alternative. Vitamin K reverses warfarin, not factor Xa inhibitors. Protamine reverses heparin. Idarucizumab (Praxbind) specifically reverses dabigatran (a direct thrombin inhibitor), not factor Xa inhibitors. Matching the correct reversal agent to the specific anticoagulant is critical in hemorrhagic emergencies.", "Match the correct anticoagulant reversal agent to the specific drug: andexanet for Xa inhibitors, idarucizumab for dabigatran, vitamin K for warfarin", "Toxicology Screening and Antidote Protocols", 3, "recall",
    "Andexanet alfa reverses factor Xa inhibitors (rivaroxaban, apixaban, edoxaban); idarucizumab reverses dabigatran; vitamin K reverses warfarin; protamine reverses heparin",
    ["Andexanet alfa: specific Xa inhibitor reversal (rivaroxaban, apixaban)", "4-factor PCC as alternative if andexanet unavailable", "Two dosing regimens based on drug and timing", "Idarucizumab reverses dabigatran, not Xa inhibitors"],
    "In hemorrhagic emergencies, administering the wrong reversal agent wastes critical time; know the anticoagulant-reversal matching",
    ["Vitamin K reverses warfarin, not Xa inhibitors", "Protamine reverses heparin, not Xa inhibitors", "Idarucizumab reverses dabigatran, not rivaroxaban"],
    "toxicology-screening-antidotes");

  mk("A 45-year-old woman presents with numbness, weakness, and garlic-flavored burps after drinking well water. She has Mees' lines on her fingernails and diffuse alopecia. What chronic exposure does this suggest?",
    ["Chronic arsenic poisoning from contaminated well water, characterized by peripheral neuropathy, Mees' lines, and hair loss", "Iron deficiency anemia", "Hypothyroidism", "Vitamin B12 deficiency"],
    0, "This presentation is classic for chronic arsenic poisoning: (1) Mees' lines (transverse white lines on fingernails) are a hallmark of arsenic and thallium exposure; (2) Diffuse alopecia from disruption of hair follicle growth; (3) Peripheral neuropathy (numbness, weakness) from axonal degeneration; (4) Garlic-flavored eructations from arsenic metabolism. Arsenic contamination of well water is a significant global public health issue, particularly in regions with naturally occurring arsenic in geological formations. Additional chronic arsenic toxicity manifestations include: skin changes (hyperpigmentation, hyperkeratosis, 'raindrop' pattern depigmentation), GI symptoms, cardiovascular effects, increased cancer risk (skin, lung, bladder, liver), and hematological effects (pancytopenia). Diagnosis is confirmed by 24-hour urine arsenic level (elevated above 50 mcg/L). Treatment includes source removal (stop drinking the contaminated water), chelation with succimer (DMSA) or dimercaprol (BAL) for symptomatic patients, and monitoring for late-onset malignancy. Mees' lines also occur with thallium, chemotherapy, and severe systemic illness.", "Recognize chronic arsenic poisoning by the clinical triad of Mees lines, peripheral neuropathy, and garlic-flavored eructations from contaminated water", "Heavy Metal Poisoning", 3, "application",
    "Mees' lines + alopecia + peripheral neuropathy + garlic breath from well water = chronic arsenic poisoning; confirm with 24-hour urine arsenic",
    ["Mees' lines: transverse white nail lines (arsenic, thallium)", "Diffuse alopecia from disrupted hair follicle growth", "Garlic-flavored eructations from arsenic metabolism", "24-hour urine arsenic >50 mcg/L confirms diagnosis"],
    "Chronic arsenic exposure significantly increases cancer risk (skin, lung, bladder, liver); all confirmed arsenic exposure patients need long-term cancer screening",
    ["Iron deficiency causes koilonychia, not Mees' lines", "Hypothyroidism causes hair loss but not Mees' lines or garlic breath", "B12 deficiency causes peripheral neuropathy but not the other features"],
    "heavy-metal-poisoning");

  mk("A patient in the ED has been started on IV nitroprusside for hypertensive emergency. After 3 hours of infusion, the patient develops metabolic acidosis with elevated lactate. What toxicity should the nurse suspect?",
    ["Cyanide toxicity from nitroprusside metabolism; nitroprusside is metabolized to cyanide which requires thiosulfate for detoxification", "Normal response to blood pressure reduction", "Lactic acidosis from underlying sepsis", "Allergic reaction to nitroprusside"],
    0, "Sodium nitroprusside is metabolized to cyanide as part of its mechanism of action. Each molecule of nitroprusside releases 5 cyanide ions upon decomposition. At therapeutic infusion rates (typically <2 mcg/kg/min), the liver can detoxify cyanide using thiosulfate and the enzyme rhodanese, converting cyanide to the non-toxic thiocyanate which is renally excreted. However, at higher infusion rates or with prolonged infusions, cyanide accumulation exceeds the detoxification capacity, leading to cyanide toxicity. Signs of cyanide toxicity from nitroprusside include: metabolic acidosis, rising lactate (from inhibited aerobic metabolism), tachyphylaxis (loss of blood pressure response), altered mental status, and cardiac instability. Risk factors include: infusion rate >2 mcg/kg/min, duration >3 days, renal impairment (impaired thiocyanate excretion), and hepatic impairment (impaired detoxification). Prevention includes: co-infusion of sodium thiosulfate, monitoring lactate levels every 2 hours during infusion, and limiting both rate and duration. Treatment of toxicity includes stopping the infusion, administering hydroxocobalamin or sodium thiosulfate, and treating metabolic acidosis.", "Recognize nitroprusside-induced cyanide toxicity by metabolic acidosis and elevated lactate during infusion and implement preventive monitoring", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "Nitroprusside releases 5 cyanide ions per molecule; monitor lactate every 2 hours and consider thiosulfate co-infusion to prevent cyanide accumulation",
    ["Nitroprusside releases 5 cyanide ions per molecule", "Cyanide accumulation exceeds detoxification at high rates/prolonged infusion", "Monitor lactate q2h during nitroprusside infusion", "Thiosulfate co-infusion prevents cyanide accumulation"],
    "Nitroprusside-induced cyanide toxicity is iatrogenic and preventable; limit infusion rate to <2 mcg/kg/min and duration to <3 days when possible",
    ["Metabolic acidosis during nitroprusside is NOT a normal response", "While sepsis causes lactic acidosis, the temporal relationship to nitroprusside points to iatrogenic cyanide toxicity", "This is not an allergic reaction but a pharmacological toxicity"],
    "toxicology-screening-antidotes");

  mk("A patient bitten by a copperhead snake presents with local swelling and pain at the bite site. No coagulopathy or systemic symptoms are present. Is antivenom indicated?",
    ["Antivenom (CroFab) should be administered if there is progressive local swelling crossing a joint or involving a large area, as copperhead envenomation can cause significant tissue destruction even without systemic effects", "Copperhead bites never require antivenom", "Only if INR is elevated", "Only if anaphylaxis occurs"],
    0, "Copperhead (Agkistrodon contortrix) envenomation is the most common venomous snakebite in the United States. While copperhead envenomation is generally less severe than rattlesnake or cottonmouth bites, it can cause significant local tissue destruction, long-term pain, and functional impairment. Antivenom (CroFab - Crotalidae Polyvalent Immune Fab) is indicated for: (1) Progressive local swelling that crosses a joint or involves more than a minimal area; (2) Moderate to severe local tissue effects (ecchymosis, blistering); (3) Any evidence of coagulopathy; (4) Systemic symptoms (hypotension, vomiting, fasciculations). The decision to administer antivenom for copperhead bites is based on the degree of local tissue involvement, not just systemic effects. Studies have shown that antivenom for copperhead bites reduces pain, swelling duration, and long-term limb dysfunction compared to supportive care alone. The initial dose is typically 4-6 vials of CroFab infused over 60 minutes. Mark the leading edge of swelling every 15-30 minutes to document progression.", "Determine antivenom indications for copperhead envenomation based on progressive local tissue effects rather than systemic symptoms alone", "Toxicology Screening and Antidote Protocols", 3, "application",
    "Copperhead bites CAN require antivenom based on progressive local tissue effects, not just systemic symptoms or coagulopathy",
    ["CroFab indicated for progressive swelling crossing joints or large area", "Mark swelling edge every 15-30 minutes to document progression", "Antivenom reduces pain duration and long-term limb dysfunction", "Initial dose: 4-6 vials CroFab over 60 minutes"],
    "Do not apply tourniquets, ice, or attempt wound suction for any snake bite; these interventions cause tissue damage and delay definitive care",
    ["Copperhead bites can cause significant tissue destruction requiring antivenom", "Coagulopathy is one indication but not the only criterion", "Antivenom, not anaphylaxis treatment, is the primary intervention"],
    "toxicology-screening-antidotes");

  // === Expanded toxicology areas ===
  const extraTox = [
    { s: "A patient presents with a 'burned garlic' odor on breath, hypersalivation, and convulsions after exposure to a rodenticide. What exposure should the nurse suspect?", o: ["Zinc phosphide or aluminum phosphide rodenticide poisoning, which releases phosphine gas in the stomach causing systemic toxicity", "Warfarin rodenticide", "Bromethalin neurotoxin", "Cholecalciferol rodenticide"], ca: 0, r: "Phosphide-containing rodenticides (zinc phosphide, aluminum phosphide) react with gastric acid and moisture to release phosphine gas (PH3), which is absorbed systemically and inhibits cytochrome c oxidase, similar to cyanide. The 'burned garlic' or 'rotten fish' odor is characteristic. Phosphine causes multiorgan failure including myocardial depression, hepatotoxicity, and metabolic acidosis. There is no specific antidote; treatment is supportive with aggressive resuscitation. Activated charcoal may reduce absorption if given within 1 hour. Gastric lavage with potassium permanganate or sodium bicarbonate solution may help neutralize the phosphide. The condition carries extremely high mortality (40-80%), particularly with aluminum phosphide. Healthcare workers must avoid secondary exposure to phosphine gas released from the patient's vomitus.", lo: "Recognize phosphide rodenticide poisoning by characteristic garlic odor and systemic cytochrome c oxidase inhibition", sub: "Toxicology Screening and Antidote Protocols", d: 4, c: "application", et: "Phosphide rodenticides release phosphine gas in the stomach; no specific antidote exists and mortality is 40-80%", p: ["Burned garlic odor is characteristic of phosphine gas", "Phosphine inhibits cytochrome c oxidase similar to cyanide", "No specific antidote; treatment is aggressive supportive care", "Healthcare worker risk from phosphine gas in patient's vomitus"], sn: "Perform gastric lavage in a well-ventilated area; phosphine gas from vomitus can cause secondary exposure to healthcare workers", dr: ["Warfarin rodenticides cause coagulopathy, not acute multi-organ failure", "Bromethalin causes cerebral edema with different clinical features", "Cholecalciferol causes hypercalcemia, not acute garlic-odor toxicity"], sl: "toxicology-screening-antidotes" },
    { s: "An IV drug user presents with wound botulism: descending paralysis, diplopia, and dysphagia originating from an injection site abscess. What distinguishes wound botulism from foodborne botulism in management?", o: ["Wound botulism requires surgical debridement of the infected wound PLUS antitoxin administration, AND antibiotics (metronidazole) unlike foodborne where antibiotics may be harmful", "Management is identical for both forms", "Wound botulism does not require antitoxin", "Wound botulism resolves spontaneously"], ca: 0, r: "Wound botulism occurs when C. botulinum colonizes a wound (commonly injection drug use sites) and produces toxin in situ. Management differs from foodborne botulism in three critical ways: (1) Surgical debridement of the infected wound is essential to remove the source of ongoing toxin production; (2) Antibiotics (metronidazole preferred; penicillin is an alternative) are indicated to kill the bacteria, unlike foodborne botulism where the toxin is preformed and antibiotics are unnecessary; (3) Heptavalent antitoxin from the CDC SNS is still required to neutralize circulating toxin. In foodborne botulism, antibiotics may theoretically worsen outcomes if bacterial lysis releases additional toxin from the GI tract. Wound botulism has been increasing among injection drug users, particularly those using black tar heroin, and should be considered in any IVDU presenting with cranial nerve palsies or descending weakness.", lo: "Differentiate wound botulism management from foodborne by adding surgical debridement and antibiotics to antitoxin therapy", sub: "Toxicology Screening and Antidote Protocols", d: 4, c: "analysis", et: "Wound botulism requires THREE interventions: antitoxin + surgical debridement + antibiotics (metronidazole); foodborne only needs antitoxin", p: ["Wound botulism: antitoxin + debridement + antibiotics", "Foodborne: antitoxin only; antibiotics may be harmful", "Metronidazole preferred antibiotic for wound botulism", "Increasing in IVDU using black tar heroin"], sn: "All suspected botulism cases require immediate notification to public health and CDC for antitoxin access from the Strategic National Stockpile", dr: ["Foodborne and wound botulism have different management requirements", "Wound botulism absolutely requires antitoxin", "Wound botulism does not resolve spontaneously; it is life-threatening"], sl: "toxicology-screening-antidotes" },
    { s: "A nurse is caring for a patient who received tissue plasminogen activator (tPA) for ischemic stroke 2 hours ago. The patient now has an expanding hematoma at the IV site, bleeding gums, and hematemesis. What should the nurse prepare?", o: ["Cryoprecipitate 10 units IV and tranexamic acid 1g IV to replace fibrinogen and inhibit fibrinolysis for tPA-associated hemorrhage", "Vitamin K for coagulopathy", "Protamine sulfate for heparin reversal", "Fresh frozen plasma only"], ca: 0, r: "tPA (alteplase) induces systemic fibrinolysis, breaking down clots throughout the body. When hemorrhagic complications occur, the primary treatment targets are: (1) Cryoprecipitate provides fibrinogen (target >200 mg/dL) to replace the fibrinogen consumed by tPA-induced fibrinolysis. Standard dose is 10 units IV. (2) Tranexamic acid (TXA) 1g IV is an antifibrinolytic that inhibits plasminogen activation, directly counteracting tPA's mechanism of action. TXA can also be given as 1g over 10 minutes followed by 1g over 8 hours. (3) Additional products may include: platelets if <100,000, aminocaproic acid as an alternative antifibrinolytic, and possible surgical intervention for expanding hematomas. Vitamin K reverses warfarin, not tPA. Protamine reverses heparin, not tPA. FFP provides clotting factors but contains relatively little fibrinogen compared to cryoprecipitate.", lo: "Manage tPA-associated hemorrhage with cryoprecipitate for fibrinogen replacement and tranexamic acid as antifibrinolytic therapy", sub: "Toxicology Screening and Antidote Protocols", d: 4, c: "application", et: "tPA hemorrhage requires cryoprecipitate for fibrinogen AND tranexamic acid as antifibrinolytic; vitamin K and protamine are for different anticoagulants", p: ["Cryoprecipitate 10 units to replace fibrinogen (target >200 mg/dL)", "Tranexamic acid 1g IV inhibits plasminogen activation", "tPA causes systemic fibrinolysis consuming fibrinogen", "Additional: platelets if <100,000, aminocaproic acid alternative"], sn: "tPA hemorrhage can be rapidly fatal; have cryoprecipitate and tranexamic acid immediately available whenever tPA is administered", dr: ["Vitamin K reverses warfarin, not fibrinolytic therapy", "Protamine reverses heparin, not tPA", "FFP provides clotting factors but insufficient fibrinogen compared to cryo"], sl: "toxicology-screening-antidotes" },
    { s: "A meth lab explosion has occurred. Multiple patients present with chemical burns and respiratory symptoms. Beyond standard burn care, what additional concern should the nurse address?", o: ["Clandestine methamphetamine production involves multiple toxic chemicals (anhydrous ammonia, red phosphorus, hydrochloric acid, lithium) requiring hazmat assessment and potential multi-agent decontamination", "Standard burn treatment only is needed", "Only methamphetamine exposure is a concern", "The explosion injuries are the only medical concern"], ca: 0, r: "Clandestine methamphetamine laboratories contain multiple extremely hazardous chemicals beyond methamphetamine itself. Common toxic agents include: (1) Anhydrous ammonia - severe respiratory irritant and caustic burns; (2) Red phosphorus - combustion hazard and phosphine gas release; (3) Hydrochloric acid gas - respiratory and skin burns; (4) Hydriodic acid - severe burns; (5) Lithium metal - explosive with water, caustic burns; (6) Organic solvents (ether, acetone, toluene) - CNS depression, respiratory irritation, fire hazard; (7) Sodium hydroxide (lye) - caustic alkali burns. Patients from meth lab explosions may have exposure to multiple agents simultaneously, requiring: multi-agent decontamination, respiratory protection for healthcare workers, assessment for specific toxic exposures based on manufacturing method, and hazmat team involvement. The explosion itself may disperse toxic chemicals over a wide area, contaminating the scene and patients. Law enforcement should also be notified as meth production is illegal.", lo: "Recognize meth lab explosions as multi-agent chemical exposures requiring hazmat assessment beyond standard burn treatment", sub: "Toxicology Screening and Antidote Protocols", d: 3, c: "application", et: "Meth labs contain multiple toxic chemicals; patients may have combined exposures to ammonia, phosphorus, acids, lithium, and solvents simultaneously", p: ["Meth labs: anhydrous ammonia, red phosphorus, HCl, lithium, solvents", "Multi-agent decontamination required", "Respiratory protection for healthcare workers", "Law enforcement notification for illegal drug production"], sn: "Healthcare workers at meth lab scenes have become casualties from toxic chemical exposure; full PPE and hazmat assessment are mandatory", dr: ["Standard burn treatment alone misses the chemical exposure component", "Multiple toxic chemicals are present, not just methamphetamine", "Chemical exposures may be more dangerous than the explosion injuries"], sl: "toxicology-screening-antidotes" },
  ];
  for (const a of extraTox) {
    mk(a.s, a.o, a.ca, a.r, a.lo, a.sub, a.d, a.c, a.et, a.p, a.sn, a.dr, a.sl);
  }

  return q;
}
