export function generateBulkToxQuestions() {
  const q: any[] = [];
  let id = 100;
  const mk = (stem: string, options: string[], ca: number, rat: string, lo: string, sub: string, diff: number, cog: string, et: string, pearls: string[], sn: string, dr: string[], slug: string) => {
    q.push({ id: `en-tox-${String(id++).padStart(3,'0')}`, stem, options, correctAnswer: ca, rationaleLong: rat, learningObjective: lo, blueprintCategory: "Toxicology", subtopic: sub, difficulty: diff, cognitiveLevel: cog, questionType: "MCQ_SINGLE", examTrap: et, clinicalPearls: pearls, safetyNote: sn, distractorRationales: dr, lessonLink: `/emergency/lessons/${slug}` });
  };

  // === ACETAMINOPHEN (5 more) ===
  mk("A chronic alcoholic presents with acetaminophen toxicity after taking only 4g over 24 hours. Why is this patient at higher risk for hepatotoxicity at a lower dose?",
    ["Chronic alcohol use induces CYP2E1 enzyme activity, increasing NAPQI production, while simultaneously depleting hepatic glutathione stores", "Alcohol inhibits acetaminophen absorption", "Chronic alcoholics have higher pain thresholds requiring less APAP", "Alcohol neutralizes acetaminophen preventing metabolism"],
    0, "Chronic alcohol consumption creates a 'double-hit' mechanism for acetaminophen hepatotoxicity: (1) CYP2E1 enzyme induction: Chronic alcohol use upregulates CYP2E1, the primary enzyme responsible for converting acetaminophen to its toxic metabolite N-acetyl-p-benzoquinone imine (NAPQI). This increased CYP2E1 activity means that a greater proportion of acetaminophen is shunted through the toxic oxidative pathway rather than the normal glucuronidation and sulfation pathways. (2) Glutathione depletion: Chronic alcohol use, combined with malnutrition common in alcoholics, depletes hepatic glutathione stores. Glutathione is the primary detoxification mechanism for NAPQI; when depleted, more NAPQI binds to hepatocellular proteins causing necrosis. This means chronic alcoholics can develop hepatotoxicity at doses below the typical 150 mg/kg threshold for acute ingestion. The FDA recommends that heavy drinkers (3+ drinks/day) limit acetaminophen to 2g/day rather than the standard 4g/day maximum.", "Explain the pathophysiology of increased acetaminophen toxicity risk in chronic alcoholics through CYP2E1 induction and glutathione depletion", "Acetaminophen Overdose and NAC Protocol", 4, "analysis",
    "Chronic alcohol use causes a 'double-hit': more NAPQI production via CYP2E1 induction AND less detoxification via glutathione depletion",
    ["CYP2E1 induction increases NAPQI production from APAP", "Glutathione depletion reduces NAPQI detoxification capacity", "Chronic alcoholics can develop toxicity below 150 mg/kg threshold", "FDA: heavy drinkers should limit APAP to 2g/day"],
    "Healthcare providers often fail to counsel alcoholic patients about reduced acetaminophen safety margins; document alcohol use before APAP prescribing",
    ["Alcohol does not inhibit APAP absorption; it increases toxic metabolism", "Chronic alcoholics are at higher, not lower risk", "Alcohol does not neutralize APAP"],
    "acetaminophen-overdose");

  mk("During NAC infusion monitoring, a nurse notes the patient's INR has risen from 1.2 to 4.8 and AST increased from 200 to 8,500 U/L over 12 hours. What does this rapid progression indicate?",
    ["Fulminant hepatic failure with coagulopathy requiring hepatology consultation for possible liver transplant evaluation and King's College Criteria assessment", "Normal progression of acetaminophen toxicity", "NAC-induced liver injury requiring drug discontinuation", "Laboratory error requiring repeat testing"],
    0, "Rapidly rising AST (200 to 8,500) with worsening coagulopathy (INR 1.2 to 4.8) indicates fulminant hepatic failure from severe acetaminophen toxicity. The liver is failing to produce clotting factors (hence rising INR) and hepatocytes are being destroyed (rising AST). This trajectory requires immediate hepatology consultation for liver transplant evaluation. The King's College Criteria for acetaminophen-induced fulminant hepatic failure include: arterial pH <7.3 regardless of other factors, OR all three of: INR >6.5, creatinine >3.4 mg/dL, and grade 3-4 hepatic encephalopathy. Meeting these criteria predicts mortality without transplant exceeding 90%. NAC should be continued as it provides benefit even in established hepatic failure. Transfer to a liver transplant center should be arranged emergently. NAC does not cause liver injury.", "Recognize fulminant hepatic failure from acetaminophen toxicity and initiate transplant evaluation using King's College Criteria", "Acetaminophen Overdose and NAC Protocol", 5, "analysis",
    "King's College Criteria: pH <7.3 alone OR (INR >6.5 + Cr >3.4 + Grade 3-4 encephalopathy) predicts >90% mortality without transplant",
    ["AST >10,000 with rising INR = fulminant hepatic failure", "King's College Criteria guide transplant evaluation", "Continue NAC even in established hepatic failure", "Arrange emergent transfer to liver transplant center"],
    "Delay in transplant evaluation is a preventable cause of death in acetaminophen-induced fulminant hepatic failure",
    ["This is NOT normal progression; it indicates severe hepatic failure", "NAC does not cause liver injury; discontinuation would worsen outcomes", "This rapid progression is clinically significant, not laboratory error"],
    "acetaminophen-overdose");

  mk("A nurse receives a pediatric patient whose parent gave repeated doses of children's acetaminophen every 4 hours for 3 days because the child had a fever. The parent used the 'correct dose' each time. The child now has vomiting and RUQ pain. What type of toxicity is this?",
    ["Repeated supratherapeutic dosing ('chronic' or 'therapeutic misadventure') which can cause hepatotoxicity at lower total doses than acute ingestion", "Acute single ingestion toxicity", "Acetaminophen allergy", "Normal side effect of therapeutic dosing"],
    0, "Repeated supratherapeutic dosing (RSTD) represents a distinct and dangerous pattern of acetaminophen toxicity different from acute single ingestion. Parents may give 'the correct dose' but at too-frequent intervals, or may use adult formulation for children, or may dose by age rather than weight. Over multiple days, this pattern depletes glutathione without allowing recovery between doses, causing cumulative hepatotoxicity. RSTD toxicity differs from acute ingestion in several ways: (1) The Rumack-Matthew nomogram cannot be applied; (2) Patients often present with symptoms rather than being asymptomatic; (3) AST/ALT may be significantly elevated at presentation; (4) The total dose over time is often lower than the single acute toxic dose; (5) NAC treatment decision is based on clinical signs and laboratory evidence rather than drug levels and nomogram. Risk factors include age under 2 years, concurrent illness with vomiting/dehydration, and use of multiple acetaminophen-containing products. Treatment is NAC if hepatotoxicity is present.", "Identify repeated supratherapeutic acetaminophen dosing as a distinct toxicity pattern requiring clinical judgment rather than nomogram-based management", "Acetaminophen Overdose and NAC Protocol", 3, "application",
    "RSTD is different from acute ingestion; the nomogram cannot be used, and clinical evidence of hepatotoxicity guides NAC initiation",
    ["RSTD depletes glutathione without recovery between doses", "Nomogram is not applicable for chronic/RSTD toxicity", "Parents may dose correctly each time but too frequently", "Multiple APAP-containing products cause unintentional overdose"],
    "Educate parents about maximum daily doses AND minimum dosing intervals for children's acetaminophen; weight-based dosing is essential",
    ["This is not a single acute ingestion pattern", "This is toxicity, not an allergic reaction", "Hepatotoxicity from RSTD is not a normal therapeutic side effect"],
    "acetaminophen-overdose");

  mk("A patient arrives with an unknown overdose. The nurse draws blood and notices the serum appears 'milky' or lipemic. Which overdose should be strongly considered?",
    ["Propofol overdose or massive lipid-soluble drug ingestion; lipemia may also indicate severe hypertriglyceridemia from parenteral nutrition or propofol infusion syndrome", "Normal blood variation", "Acetaminophen overdose", "Alcohol intoxication"],
    0, "Lipemic (milky appearing) serum in the setting of suspected overdose should raise concern for propofol toxicity, particularly propofol infusion syndrome (PRIS), or massive ingestion of lipid-soluble drugs. Propofol is formulated in a lipid emulsion (soybean oil), and prolonged infusion or overdose causes severe hypertriglyceridemia, giving serum a milky appearance. PRIS is a rare but often fatal syndrome characterized by: metabolic acidosis, rhabdomyolysis, hyperkalemia, hepatomegaly, cardiac failure, and lipemic serum. Risk factors include high-dose propofol (>4mg/kg/h) for prolonged duration (>48h), critical illness, catecholamine infusion, and young age. Lipemic serum can also interfere with many laboratory assays, producing inaccurate results for electrolytes, liver enzymes, and drug levels. Other causes of lipemic serum include familial hyperlipidemias and diabetic ketoacidosis but these have different clinical contexts from overdose.", "Recognize lipemic serum as a potential indicator of propofol toxicity or massive lipid-soluble drug ingestion", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "Lipemic (milky) serum in an overdose setting suggests propofol toxicity or PRIS; lipemia also interferes with laboratory assay accuracy",
    ["Propofol formulated in lipid emulsion causes hypertriglyceridemia", "PRIS: metabolic acidosis, rhabdomyolysis, hyperkalemia, cardiac failure", "Risk factors: high dose >4mg/kg/h, >48h duration, critical illness", "Lipemic serum interferes with many lab assay results"],
    "Monitor triglycerides in patients on prolonged propofol infusion; levels >500 mg/dL indicate high PRIS risk",
    ["Normal blood does not appear milky or lipemic", "APAP does not cause lipemic serum", "Alcohol does not produce this serum appearance"],
    "toxicology-screening-antidotes");

  mk("A patient who overdosed on diphenhydramine has a QRS duration of 140 ms on ECG. What treatment should the nurse prepare?",
    ["IV sodium bicarbonate bolus to narrow the QRS complex by overcoming the sodium channel blockade", "Physostigmine for anticholinergic reversal", "IV calcium gluconate", "Synchronized cardioversion"],
    0, "Diphenhydramine at high doses produces sodium channel blockade similar to tricyclic antidepressants, causing QRS widening and risk for ventricular dysrhythmias. Normal QRS duration is <120 ms; QRS >100 ms suggests significant sodium channel blockade, and QRS >160 ms predicts seizures and ventricular dysrhythmias. IV sodium bicarbonate (1-2 mEq/kg bolus) is the treatment because: (1) Sodium loading overcomes the competitive sodium channel blockade by increasing the sodium gradient across the channel; (2) Alkalinization decreases the percentage of ionized drug available to bind sodium channels; (3) Goal is to narrow QRS to <120 ms. Physostigmine, while useful for anticholinergic symptoms (delirium, agitation), should NOT be given when QRS is widened as it can precipitate asystole in the setting of sodium channel blockade. Calcium gluconate is for calcium channel blocker toxicity, not sodium channel blockade. Cardioversion is for unstable tachyarrhythmias, not QRS widening from drug toxicity.", "Treat diphenhydramine-induced QRS widening with sodium bicarbonate to overcome sodium channel blockade", "Anticholinergic Toxidrome", 4, "application",
    "Physostigmine is CONTRAINDICATED when QRS is widened; it can precipitate asystole. Use sodium bicarbonate for sodium channel blockade",
    ["QRS >100 ms = significant sodium channel blockade", "QRS >160 ms predicts seizures and ventricular dysrhythmias", "NaHCO3 1-2 mEq/kg IV bolus; goal QRS <120 ms", "Physostigmine contraindicated with QRS widening"],
    "Monitor ECG continuously in diphenhydramine overdose; seizures and cardiac arrest can occur rapidly with QRS widening",
    ["Physostigmine with widened QRS can cause asystole", "Calcium gluconate treats calcium channel blocker toxicity", "Cardioversion is for tachyarrhythmias, not drug-induced QRS widening"],
    "anticholinergic-toxidrome");

  // === OPIOID (3 more) ===
  mk("A heroin-dependent patient is admitted for pain management after a motor vehicle collision. He is receiving IV morphine PCA but reports inadequate pain relief. The nurse notices his pupils are pinpoint and respiratory rate is 10. What is the most appropriate action?",
    ["Hold the PCA, reassess pain management approach with the physician, consider multimodal analgesia, and monitor respiratory status closely", "Increase the PCA dose since the patient reports pain", "Administer naloxone for the respiratory depression", "Discontinue all opioids and use acetaminophen only"],
    0, "This scenario presents the complex challenge of pain management in opioid-tolerant patients. The patient has signs of opioid excess (pinpoint pupils, RR 10) despite reporting inadequate pain relief, which is common in tolerant patients. The appropriate response is to: (1) Hold the PCA to prevent further respiratory depression; (2) Reassess the pain management approach - opioid-tolerant patients often require multimodal analgesia including regional anesthesia, ketamine, gabapentinoids, NSAIDs, and non-pharmacological approaches; (3) Monitor respiratory status as RR of 10 indicates relative overdosing for acute pain management; (4) Consider consulting an acute pain service or addiction medicine specialist. Increasing the PCA dose would worsen the respiratory depression. Naloxone is not indicated unless respiratory depression is severe (RR <8 or oxygen desaturation) because it would precipitate severe withdrawal in a dependent patient. Discontinuing all opioids would cause withdrawal and leave pain untreated.", "Manage opioid analgesia in tolerant patients by recognizing signs of excess, implementing multimodal analgesia, and monitoring respiratory status", "Opioid Overdose and Naloxone", 3, "analysis",
    "Pinpoint pupils with RR <12 indicates opioid excess even if the patient reports pain; multimodal analgesia is the solution, not dose escalation",
    ["Opioid-tolerant patients need multimodal pain management", "Signs of excess (miosis, low RR) override subjective pain reports for dose decisions", "Naloxone precipitates withdrawal in dependent patients; use only for severe depression", "Consult acute pain service or addiction medicine"],
    "Opioid-tolerant patients are at risk for unintentional overdose during acute pain management; close respiratory monitoring is essential",
    ["Increasing PCA dose worsens the respiratory depression", "Naloxone would precipitate severe withdrawal in this dependent patient", "Discontinuing all opioids leaves pain untreated and causes withdrawal"],
    "opioid-overdose");

  mk("A patient on a patient-controlled analgesia (PCA) pump is found unresponsive with a family member repeatedly pressing the PCA button. SpO2 is 82%, RR 4. What safety concern does this represent?",
    ["PCA by proxy - unauthorized activation of the PCA pump by someone other than the patient, which is a leading cause of opioid-related respiratory depression in hospitalized patients", "Normal PCA operation", "PCA pump malfunction", "Appropriate family assistance"],
    0, "PCA by proxy is defined as activation of the PCA pump by someone other than the patient, most commonly a well-meaning family member or visitor. This is a recognized patient safety hazard and a leading cause of opioid-related respiratory depression in hospitalized patients. The safety design of PCA relies on the concept that a sedated patient cannot press the button, thereby providing a natural ceiling to dosing. When a third party presses the button, this safety mechanism is bypassed, allowing drug delivery to continue while the patient is over-sedated. The Joint Commission has issued sentinel event alerts regarding PCA by proxy. Prevention strategies include: (1) Patient and family education that ONLY the patient should press the PCA button; (2) Clear signage on the PCA pump; (3) Nursing monitoring at regular intervals including sedation assessment; (4) Capnography monitoring for high-risk patients; (5) PCA pump documentation of activation patterns. Immediate actions for this patient include: stop PCA, administer naloxone, support airway and ventilation.", "Identify PCA by proxy as a patient safety hazard and implement prevention strategies", "Opioid Overdose and Naloxone", 2, "application",
    "PCA by proxy bypasses the built-in safety mechanism; only the patient should press the PCA button - family education is essential",
    ["PCA by proxy: unauthorized pump activation by non-patient", "Joint Commission sentinel event alert on PCA by proxy", "PCA safety relies on sedated patient being unable to press button", "Prevention: education, signage, monitoring, capnography"],
    "PCA by proxy has caused deaths in hospitalized patients; educate ALL family members and visitors that only the patient presses the button",
    ["This is NOT normal PCA operation; it is a safety violation", "The pump is functioning as designed; the human intervention is the problem", "Family members should NEVER press the PCA button for the patient"],
    "opioid-overdose");

  mk("An emergency nurse is preparing to manage a patient with suspected carfentanil exposure. What unique precautions are needed beyond standard opioid overdose management?",
    ["Enhanced PPE including N95 respirator and double nitrile gloves due to carfentanil's extreme potency (10,000x morphine) and potential for dermal absorption and inhalation exposure causing rescuer overdose", "No additional precautions beyond standard opioid overdose care", "Chemical decontamination suit only", "Standard surgical mask and gloves"],
    0, "Carfentanil is a synthetic opioid approximately 10,000 times more potent than morphine and 100 times more potent than fentanyl. It was originally developed as a large animal tranquilizer. Due to its extreme potency, quantities invisible to the naked eye can cause fatal respiratory depression through dermal absorption or inhalation. Healthcare worker safety concerns include: (1) Dermal absorption through skin contact with contaminated surfaces, powder, or patient's skin/clothing; (2) Inhalation of aerosolized particles during patient assessment or clothing removal; (3) Mucous membrane absorption. Required precautions include: N95 respirator (minimum) to prevent inhalation, double nitrile gloves to prevent dermal absorption, eye protection, and consideration of Tyvek suit for gross contamination. Naloxone doses required for carfentanil reversal are substantially higher than for other opioids, often requiring 10+ mg with repeated boluses and high-dose infusion. Standard surgical masks do not prevent inhalation of fine particles. The potential for healthcare worker exposure has prompted the development of specific guidance from NIOSH and DEA.", "Implement enhanced PPE for carfentanil exposure management due to extreme potency and risk of rescuer contamination", "Opioid Overdose and Naloxone", 4, "application",
    "Carfentanil is 10,000x morphine potency; invisible quantities can be fatal through skin absorption or inhalation, putting healthcare workers at risk",
    ["Carfentanil: 10,000x morphine, 100x fentanyl potency", "Dermal absorption and inhalation can cause rescuer overdose", "N95 minimum, double nitrile gloves, eye protection required", "Much higher naloxone doses needed (10+ mg)"],
    "Healthcare workers have experienced overdose symptoms from dermal and inhalation exposure to carfentanil; enhanced PPE is mandatory",
    ["Standard opioid overdose precautions are insufficient for carfentanil", "Chemical decon suit alone without respiratory protection is insufficient", "Standard surgical masks do not filter fine carfentanil particles"],
    "opioid-overdose");

  // === ALCOHOL/BENZOS (3 more) ===
  mk("A 45-year-old male with severe alcohol withdrawal is seizing despite receiving 120 mg of lorazepam over 4 hours. This represents benzodiazepine-resistant alcohol withdrawal. What alternative medication should the nurse prepare?",
    ["IV phenobarbital loading dose of 10-20 mg/kg as rescue therapy for benzodiazepine-resistant alcohol withdrawal seizures", "Additional lorazepam at higher doses", "IV phenytoin for seizure control", "Oral chlordiazepoxide"],
    0, "Benzodiazepine-resistant alcohol withdrawal occurs when escalating doses of benzodiazepines fail to control symptoms, typically defined as requiring >40 mg diazepam equivalents per hour or >200 mg in 24 hours without adequate symptom control. This represents a true pharmacological failure of the GABA-A benzodiazepine binding site. Phenobarbital is the preferred rescue agent because it acts at a different site on the GABA-A receptor (the barbiturate binding site), providing additive GABAergic effect independent of the benzodiazepine binding site. IV phenobarbital loading dose of 10-20 mg/kg provides rapid, sustained seizure and withdrawal control. Phenobarbital has a long half-life (53-118 hours) providing a smooth, self-tapering effect. However, phenobarbital carries significant respiratory depression risk, especially when combined with benzodiazepines, requiring close airway monitoring and availability of intubation equipment. If phenobarbital fails, propofol infusion in the ICU setting may be needed. Phenytoin is NOT effective for alcohol withdrawal seizures. Oral chlordiazepoxide cannot be given to a seizing patient.", "Administer phenobarbital as rescue therapy for benzodiazepine-resistant alcohol withdrawal seizures", "Alcohol Withdrawal and DTs", 4, "analysis",
    "Phenytoin does NOT work for alcohol withdrawal seizures; phenobarbital acts at a different GABA-A site than benzodiazepines providing additive effect",
    ["BZD-resistant: >40mg diazepam equiv/hour or >200mg/24h without control", "Phenobarbital acts at barbiturate site on GABA-A receptor", "Loading dose 10-20 mg/kg IV provides sustained control", "Long half-life (53-118h) provides self-tapering effect"],
    "Phenobarbital combined with benzodiazepines carries high respiratory depression risk; intubation equipment must be immediately available",
    ["More lorazepam when already BZD-resistant is futile", "Phenytoin is NOT effective for alcohol withdrawal seizures", "Oral medications cannot be given to a seizing patient"],
    "alcohol-withdrawal");

  mk("An emergency nurse notices that a patient being treated for alcohol withdrawal has developed a new fever, leukocytosis, and elevated lipase. The patient's CIWA-Ar score has been well-controlled at 8. What should the nurse consider?",
    ["Alternative diagnoses such as alcoholic pancreatitis or infection that may be masked by or coexist with alcohol withdrawal; do not attribute all findings to withdrawal alone", "Increase benzodiazepine dosing for worsening withdrawal", "The fever and labs are typical of alcohol withdrawal", "Discharge the patient since CIWA-Ar is controlled"],
    0, "This scenario highlights a critical clinical thinking error called 'premature diagnostic closure' - attributing all findings to alcohol withdrawal when other serious conditions may coexist. While fever can occur in severe alcohol withdrawal (DTs), the combination of NEW fever, leukocytosis, and elevated lipase in an alcoholic patient should prompt evaluation for: (1) Alcoholic pancreatitis (elevated lipase is the key clue); (2) Aspiration pneumonia (common in obtunded alcoholics); (3) Spontaneous bacterial peritonitis (if cirrhotic); (4) Meningitis or encephalitis; (5) Subdural hematoma (alcoholics are prone to falls and coagulopathy). The well-controlled CIWA-Ar score of 8 suggests the alcohol withdrawal itself is being managed, making an alternative diagnosis more likely for the new findings. Increasing benzodiazepines when CIWA-Ar is controlled would cause unnecessary sedation. These findings are NOT typical of well-controlled withdrawal. Discharging ignores the new concerning findings.", "Evaluate for alternative diagnoses when alcohol withdrawal patients develop new symptoms not explained by their CIWA-Ar trend", "Alcohol Withdrawal and DTs", 3, "analysis",
    "New fever and abnormal labs in a patient with controlled withdrawal (CIWA-Ar 8) should prompt evaluation for alternative diagnoses, not dose escalation",
    ["Fever + leukocytosis + elevated lipase → evaluate for pancreatitis", "Avoid premature diagnostic closure with alcohol withdrawal", "Common co-morbidities: pancreatitis, aspiration PNA, SBP, SDH", "Well-controlled CIWA-Ar suggests withdrawal is not causing new findings"],
    "Attributing all symptoms to alcohol withdrawal can delay diagnosis of life-threatening conditions; always consider alternative diagnoses",
    ["Increasing BZDs when CIWA-Ar is 8 is inappropriate and causes sedation", "These findings exceed typical well-controlled withdrawal", "Discharge with new concerning findings is unsafe"],
    "alcohol-withdrawal");

  mk("A patient presents to the ED with confusion, ataxia, and lateral gaze nystagmus. He smells of alcohol but his blood alcohol level returns at 0. The nurse suspects Wernicke encephalopathy. What is the appropriate dose of thiamine?",
    ["High-dose IV thiamine 500 mg three times daily for 2-3 days, then 250 mg daily for 5 days, followed by oral supplementation", "Oral thiamine 100 mg once daily", "No thiamine since the patient is not drinking", "IM thiamine 100 mg once"],
    0, "Wernicke encephalopathy (WE) requires HIGH-DOSE IV thiamine, not the commonly underdosed 100 mg oral or IM that is often given. The classic triad of confusion, ataxia, and ophthalmoplegia (lateral gaze nystagmus in this case) is present in only about 30% of WE cases, making the full triad presentation a strong indication for aggressive treatment. Current evidence-based guidelines recommend IV thiamine 500 mg TID for 2-3 days (the Royal College of Physicians recommendation) because: (1) Oral thiamine has poor and unreliable absorption in alcoholics due to impaired GI absorption; (2) IM thiamine has slow and variable absorption; (3) The brain requires high concentrations of thiamine to overcome the metabolic deficit; (4) Low doses of thiamine are insufficient to cross the blood-brain barrier in adequate amounts; (5) Thiamine has essentially no toxicity even at high doses. After 2-3 days of high-dose IV therapy, if improvement is seen, the dose can be reduced to 250 mg daily IV for 5 additional days, then transitioned to oral supplementation. Failure to treat adequately can result in permanent Korsakoff syndrome (irreversible anterograde amnesia).", "Administer high-dose IV thiamine for Wernicke encephalopathy, recognizing that standard 100 mg dosing is inadequate", "Alcohol Withdrawal and DTs", 4, "application",
    "Standard 100 mg thiamine is INADEQUATE for Wernicke encephalopathy; evidence-based treatment is 500 mg IV TID for 2-3 days",
    ["IV thiamine 500 mg TID for 2-3 days (Royal College guideline)", "Oral thiamine has poor absorption in alcoholics", "Classic triad present in only 30% of WE cases", "Untreated WE → Korsakoff syndrome (irreversible amnesia)"],
    "Undertreated Wernicke encephalopathy progresses to permanent Korsakoff syndrome; high-dose IV thiamine is safe and potentially brain-saving",
    ["Oral 100 mg has inadequate absorption in alcoholics", "A zero BAL does not exclude WE; it can occur in chronic nutritional deficiency", "IM thiamine has slow, variable absorption"],
    "alcohol-withdrawal");

  // === SEROTONIN SYNDROME vs NMS (3 more) ===
  mk("A patient's medication list includes sertraline (SSRI) and she just started linezolid (antibiotic with MAOI properties) for a wound infection. The nurse notices she is developing agitation, clonus, and diaphoresis. What is the priority intervention?",
    ["Discontinue linezolid immediately, notify the physician, and prepare cyproheptadine for probable serotonin syndrome caused by the SSRI-MAOI combination", "Continue both medications as prescribed", "Administer additional sertraline for the agitation", "Start dantrolene for suspected NMS"],
    0, "This is a classic serotonin syndrome presentation caused by the combination of an SSRI (sertraline) with a medication possessing MAOI properties (linezolid). Linezolid is an oxazolidinone antibiotic that has significant monoamine oxidase inhibition, creating dangerous serotonin excess when combined with serotonergic medications. The triad of agitation, clonus, and diaphoresis is characteristic of serotonin syndrome (Hunter Criteria). Other common precipitating combinations include: SSRI + tramadol, SSRI + meperidine, SSRI + MAOI, and SSRI + methylene blue. The priority intervention is discontinuing the offending serotonergic combination. Linezolid should be stopped and an alternative non-MAOI antibiotic substituted. Cyproheptadine (serotonin antagonist) should be administered for moderate-severe serotonin syndrome. Continuing both medications would worsen the syndrome. Additional sertraline would dramatically worsen serotonin excess. Dantrolene treats NMS (muscle rigidity from dopamine blockade), not serotonin syndrome (clonus from serotonin excess).", "Recognize linezolid as a commonly overlooked MAOI that can precipitate serotonin syndrome when combined with serotonergic medications", "Serotonin Syndrome", 3, "application",
    "Linezolid and methylene blue are commonly overlooked medications with MAOI properties that cause serotonin syndrome with SSRIs",
    ["Linezolid has significant MAO inhibition activity", "Common overlooked MAOIs: linezolid, methylene blue, meperidine", "Hunter Criteria: clonus, agitation, diaphoresis confirm serotonin syndrome", "Discontinue offending agents and give cyproheptadine"],
    "Always check for SSRI interactions before starting linezolid; consult pharmacy for safe alternatives if the patient is on serotonergic medications",
    ["Continuing both medications worsens the potentially fatal syndrome", "More sertraline dramatically increases serotonin excess", "Dantrolene treats NMS, not serotonin syndrome"],
    "serotonin-syndrome");

  mk("A 60-year-old male on haloperidol for psychosis develops fever (39.8°C), extreme muscle rigidity, autonomic instability (BP 180/110, HR 130), and CPK of 15,000 U/L over 48 hours. The nurse suspects NMS. What specific treatment should be initiated?",
    ["Discontinue haloperidol, administer dantrolene 2-2.5 mg/kg IV for muscle rigidity, and consider bromocriptine 2.5 mg TID orally for dopamine agonism", "Increase haloperidol to treat the psychotic agitation", "Administer cyproheptadine for suspected serotonin syndrome", "Apply cooling blankets only and observe"],
    0, "Neuroleptic Malignant Syndrome (NMS) is a life-threatening reaction to dopamine antagonists (antipsychotics) characterized by the tetrad of: hyperthermia, muscle rigidity ('lead-pipe'), autonomic dysregulation, and altered mental status. The elevated CPK (15,000) confirms significant muscle damage from the severe rigidity. Treatment includes: (1) Immediately discontinue the causative dopamine antagonist (haloperidol); (2) Dantrolene 2-2.5 mg/kg IV to reduce muscle rigidity by acting directly on skeletal muscle (blocks ryanodine receptor-mediated calcium release from sarcoplasmic reticulum); (3) Bromocriptine 2.5 mg TID (dopamine agonist) to restore dopaminergic activity that was blocked by the antipsychotic; (4) Aggressive supportive care: IV fluids, cooling, electrolyte correction, monitoring for rhabdomyolysis complications (AKI, hyperkalemia); (5) ICU admission for close monitoring. Increasing haloperidol would catastrophically worsen NMS. Cyproheptadine treats serotonin syndrome, not NMS - the key differentiator is lead-pipe rigidity (NMS) vs clonus (serotonin syndrome). Observation alone is insufficient for this life-threatening emergency.", "Treat NMS with dantrolene for rigidity and bromocriptine for dopamine restoration after discontinuing the causative antipsychotic", "Neuroleptic Malignant Syndrome", 4, "application",
    "NMS treatment: dantrolene for rigidity + bromocriptine for dopamine agonism; serotonin syndrome treatment: cyproheptadine - do NOT confuse these",
    ["NMS tetrad: hyperthermia, rigidity, autonomic instability, AMS", "Dantrolene: blocks calcium release from sarcoplasmic reticulum", "Bromocriptine: dopamine agonist to restore blocked dopaminergic activity", "CPK elevation confirms rhabdomyolysis from severe rigidity"],
    "NMS has 10-20% mortality even with treatment; ICU admission is required for close monitoring and aggressive supportive care",
    ["Increasing haloperidol would worsen NMS catastrophically", "Cyproheptadine treats serotonin syndrome, not NMS", "Observation alone is insufficient; NMS requires specific pharmacotherapy"],
    "neuroleptic-malignant-syndrome");

  mk("A nurse is administering methylene blue to treat methemoglobinemia in a patient who is also taking an SSRI. After administration, the patient develops agitation, hyperthermia, and clonus. What happened?",
    ["Methylene blue has MAOI properties that precipitated serotonin syndrome when combined with the SSRI", "The methylene blue was contaminated", "This is a normal side effect of methylene blue", "The methemoglobinemia worsened"],
    0, "Methylene blue has significant monoamine oxidase inhibitory (MAOI) properties that are often overlooked. When administered to a patient already taking serotonergic medications (SSRIs, SNRIs, TCAs, tramadol, meperidine), methylene blue can precipitate serotonin syndrome. The FDA has issued a specific warning about this interaction. This creates a clinical dilemma: the patient needs methylene blue for methemoglobinemia treatment, but the MAOI properties interact dangerously with their chronic SSRI. Management of this situation includes: (1) Stop the methylene blue infusion; (2) Administer cyproheptadine for serotonin syndrome; (3) For continued methemoglobinemia treatment, consider ascorbic acid (less effective but without MAOI risk) or exchange transfusion for severe cases; (4) Discontinue the SSRI if methylene blue must be used urgently; (5) Monitor in the ICU. This scenario has caused actual patient deaths and the FDA issued a Drug Safety Communication about it. Prior to administering methylene blue, always review the medication list for serotonergic drugs.", "Recognize methylene blue as an MAOI that can precipitate serotonin syndrome when combined with serotonergic medications", "Serotonin Syndrome", 4, "analysis",
    "Methylene blue has MAOI properties and precipitates serotonin syndrome with SSRIs; the FDA has issued a specific warning about this interaction",
    ["Methylene blue has significant MAOI activity", "FDA has issued a Drug Safety Communication about this interaction", "Alternative methemoglobinemia treatments: ascorbic acid, exchange transfusion", "Always review medication list for serotonergic drugs before methylene blue"],
    "This interaction has caused patient deaths; always screen for SSRIs/SNRIs before administering methylene blue",
    ["Methylene blue is not contaminated; the MAOI activity is inherent", "Serotonin syndrome is NOT a normal side effect of methylene blue", "These symptoms indicate serotonin syndrome, not worsening methemoglobinemia"],
    "serotonin-syndrome");

  // === CO POISONING (2 more) ===
  mk("A firefighter is brought to the ED after a structure fire. His COHb level is 25%. SpO2 on pulse oximetry reads 99%. Why is the pulse oximetry reading unreliable?",
    ["Standard pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin, reading falsely normal because both absorb light similarly at the wavelengths used", "The pulse oximeter is malfunctioning", "High COHb levels increase oxygen delivery", "Smoke exposure damages the pulse oximeter sensor"],
    0, "Standard pulse oximetry is dangerously unreliable in carbon monoxide poisoning because it uses two wavelengths of light (660nm red and 940nm infrared) to calculate oxygen saturation based on the ratio of oxyhemoglobin (HbO2) to deoxyhemoglobin (Hb). Carboxyhemoglobin (COHb) absorbs red light at 660nm almost identically to oxyhemoglobin, causing the pulse oximeter to 'read' COHb as HbO2 and display a falsely normal or high SpO2. In this firefighter with COHb of 25%, the pulse oximeter adds the COHb to the apparent HbO2, potentially reading 99% when the true functional oxygen saturation is only about 74%. CO-oximetry (found in arterial blood gas analyzers) uses multiple wavelengths (4-7) to separately identify HbO2, Hb, COHb, and MetHb, providing accurate readings. All patients with suspected CO exposure should have CO-oximetry via ABG rather than relying on pulse oximetry. Some newer pulse oximeters (Masimo Rad-57) use 8 wavelengths and can estimate COHb, but standard devices cannot.", "Recognize that standard pulse oximetry gives falsely normal readings in CO poisoning and CO-oximetry via ABG is required", "Carbon Monoxide Poisoning", 2, "recall",
    "Pulse oximetry reads COHb as oxyhemoglobin giving falsely normal SpO2; CO-oximetry (ABG) is required for accurate assessment in CO exposure",
    ["Standard pulse ox uses 2 wavelengths; cannot distinguish COHb from HbO2", "COHb absorbs red light identically to oxyhemoglobin at 660nm", "CO-oximetry uses 4-7 wavelengths to separately identify hemoglobin species", "All CO-exposed patients need CO-oximetry via ABG"],
    "A falsely reassuring SpO2 in CO poisoning can lead to inadequate treatment; never rely on pulse oximetry in smoke inhalation or CO exposure",
    ["The pulse oximeter is functioning normally but lacks wavelength specificity", "High COHb reduces oxygen delivery despite normal SpO2 reading", "Smoke does not damage the sensor; the technology has inherent limitations"],
    "carbon-monoxide-poisoning");

  mk("A pregnant woman presents after accidental CO exposure. Her COHb level is 15%. When should hyperbaric oxygen (HBO) therapy be considered?",
    ["HBO should be strongly considered for all pregnant CO-exposed patients even at lower COHb levels because fetal hemoglobin has a much higher affinity for CO, resulting in higher fetal COHb levels than maternal levels", "Only if maternal COHb exceeds 40%", "HBO is contraindicated in pregnancy", "Standard NRB oxygen is always sufficient for pregnant patients"],
    0, "Pregnant patients with CO exposure represent a special population requiring more aggressive treatment because: (1) Fetal hemoglobin (HbF) has 10-15% higher affinity for CO compared to adult hemoglobin, meaning the fetus accumulates CO more readily than the mother; (2) Fetal COHb levels may be 10-15% higher than maternal levels; (3) CO elimination from fetal blood is significantly slower than from maternal blood; (4) The developing fetal brain is extremely vulnerable to CO-induced hypoxia, with risks of cerebral palsy, cognitive impairment, and fetal death. The threshold for HBO therapy in pregnancy is lower than for non-pregnant adults. Many toxicology guidelines recommend HBO for all pregnant patients with: COHb >15-20%, any signs/symptoms (headache, dizziness), any period of loss of consciousness, fetal distress, or abnormal neurological findings. HBO at 2-3 atmospheres increases dissolved oxygen by 10-20 fold and reduces CO half-life from 4-6 hours on NRB to approximately 20-25 minutes. HBO is NOT contraindicated in pregnancy; the benefits far outweigh the theoretical risks.", "Consider lower threshold for HBO therapy in pregnant CO-exposed patients due to fetal hemoglobin's higher CO affinity", "Carbon Monoxide Poisoning", 4, "analysis",
    "Fetal hemoglobin has 10-15% higher CO affinity than adult Hb; fetal COHb levels exceed maternal levels, requiring more aggressive treatment",
    ["Fetal hemoglobin has 10-15% higher CO affinity than adult HbA", "Fetal COHb levels may be 10-15% higher than maternal levels", "CO elimination from fetal blood is significantly slower", "Lower HBO threshold for pregnant patients: COHb >15-20%"],
    "CO exposure in pregnancy can cause fetal death, cerebral palsy, and cognitive impairment even when the mother appears minimally affected",
    ["The 40% threshold is for non-pregnant adults; pregnancy requires lower thresholds", "HBO is NOT contraindicated in pregnancy", "NRB oxygen may be insufficient for fetal CO elimination"],
    "carbon-monoxide-poisoning");

  // === ORGANOPHOSPHATE (2 more) ===
  mk("During atropine administration for organophosphate poisoning, the nurse uses which clinical endpoint to determine adequate atropinization?",
    ["Drying of respiratory secretions and resolution of bronchospasm; NOT pupil dilation or heart rate normalization", "Pupil dilation to 4 mm or greater", "Heart rate above 100 bpm", "Resolution of all SLUDGE symptoms simultaneously"],
    0, "The clinical endpoint for atropine therapy in organophosphate poisoning is drying of respiratory secretions and resolution of bronchospasm. This is because the most immediately life-threatening aspect of organophosphate poisoning is respiratory compromise from bronchorrhea (excessive bronchial secretions) and bronchospasm. Using heart rate or pupil size as endpoints leads to either under-dosing (causing continued respiratory secretion) or over-dosing (anticholinergic toxicity). Pupil dilation is unreliable because it occurs at different atropine doses in different patients and can be affected by direct organophosphate exposure to the eye. Heart rate is unreliable because some organophosphate poisoning causes initial tachycardia rather than bradycardia. Atropine dosing for OP poisoning is dramatically higher than standard doses: initial 1-2 mg IV, then doubling the dose every 3-5 minutes until secretions clear (cumulative doses of 50-100+ mg may be needed). Once secretions are controlled, an atropine infusion (10-20% of the total loading dose per hour) maintains the effect.", "Titrate atropine to drying of respiratory secretions as the primary clinical endpoint in organophosphate poisoning", "Organophosphate Exposure", 3, "application",
    "Atropine endpoint is drying of bronchial secretions, NOT pupil dilation or heart rate; respiratory secretions are what kills the patient",
    ["Endpoint: dry respiratory secretions, resolved bronchospasm", "NOT pupil size or heart rate as endpoints", "Double dose every 3-5 minutes: 1mg, 2mg, 4mg, 8mg, etc.", "Cumulative doses of 50-100+ mg may be needed"],
    "Under-dosing atropine because of tachycardia or large pupils allows continued bronchorrhea and death from respiratory failure",
    ["Pupil dilation is unreliable and not the therapeutic endpoint", "Heart rate normalization is not the goal; respiratory secretions are", "All SLUDGE symptoms do not need to resolve simultaneously"],
    "organophosphate-exposure");

  mk("A patient presents 2 weeks after organophosphate exposure with weakness, particularly of proximal muscles, neck flexors, and cranial nerve-innervated muscles. EMG shows decremental response. What delayed complication has developed?",
    ["Intermediate syndrome - a delayed neuromuscular junction dysfunction occurring 24-96 hours (sometimes longer) after organophosphate exposure, after initial cholinergic crisis resolution", "Recurrence of the original cholinergic crisis", "Guillain-Barre syndrome", "Simple deconditioning from prolonged bed rest"],
    0, "Intermediate syndrome (IMS) is a well-recognized but often missed complication of organophosphate poisoning that occurs 24-96 hours (and sometimes up to 2-3 weeks) after the initial cholinergic crisis has resolved. It is characterized by: weakness of proximal limb muscles, neck flexors, respiratory muscles (potentially requiring ventilatory support), and cranial nerve-innervated muscles (particularly muscles of mastication and facial weakness). The pathophysiology involves persistent inhibition and down-regulation of nicotinic receptors at the neuromuscular junction after the muscarinic effects have been treated with atropine. EMG typically shows a decremental response to repetitive nerve stimulation. IMS does NOT respond to atropine or pralidoxime. Treatment is primarily supportive with ventilatory support as needed. Recovery typically occurs over 5-18 days as new acetylcholinesterase is synthesized. The nurse should monitor for respiratory muscle weakness, as diaphragmatic weakness can cause respiratory failure requiring intubation. This differs from OPIDP (organophosphate-induced delayed polyneuropathy), which occurs 2-3 weeks later with distal weakness and sensory changes.", "Recognize intermediate syndrome as a delayed complication of organophosphate poisoning requiring supportive care with potential ventilatory support", "Organophosphate Exposure", 4, "analysis",
    "Intermediate syndrome occurs after cholinergic crisis resolves; it does NOT respond to atropine or pralidoxime - supportive care with ventilation is the treatment",
    ["IMS: proximal weakness, neck flexors, respiratory muscles, cranial nerves", "Occurs 24-96 hours after initial crisis resolution", "Does not respond to atropine or pralidoxime", "Recovery in 5-18 days as new acetylcholinesterase is synthesized"],
    "Monitor respiratory muscle strength in all organophosphate poisoning patients for 2-3 weeks; intermediate syndrome respiratory failure can be insidious",
    ["This is not recurrent cholinergic crisis; it is a different mechanism", "GBS has ascending weakness, not the proximal pattern of IMS", "Deconditioning does not produce EMG decremental response"],
    "organophosphate-exposure");

  // === PEDIATRIC TOXICOLOGY (3 more) ===
  mk("A 3-year-old is brought to the ED after found playing with a button battery. The parent found one battery missing from the package but is unsure if the child swallowed it. What is the most critical initial action?",
    ["Obtain immediate anteroposterior and lateral chest/abdominal X-ray to locate the battery; esophageal button battery impaction is a surgical emergency requiring removal within 2 hours", "Wait to see if the child develops symptoms", "Administer activated charcoal", "Send the child home with follow-up in 48 hours"],
    0, "Button battery ingestion in children is a medical emergency due to the risk of esophageal impaction and rapid tissue destruction. A button battery lodged in the esophagus can cause full-thickness esophageal burn within 2 hours through three mechanisms: (1) Generation of hydroxide ions by electrolysis at the negative pole (alkaline burn), (2) Pressure necrosis from the battery pressing against the esophageal wall, and (3) Leakage of caustic battery contents. Complications include esophageal perforation, mediastinitis, tracheoesophageal fistula, aortoesophageal fistula (which can cause fatal hemorrhage), and vocal cord paralysis. If the X-ray shows the battery is in the esophagus, endoscopic removal must occur within 2 hours regardless of the time of ingestion. If the battery has passed to the stomach, management depends on size and patient symptoms. Batteries in the stomach that are >20 mm in diameter should be removed endoscopically if they do not pass within 48 hours. Activated charcoal is contraindicated as it does not adsorb batteries and delays endoscopic visualization.", "Obtain emergent imaging for suspected button battery ingestion and facilitate removal within 2 hours if esophageally impacted", "Toxic Ingestion in Pediatrics", 2, "application",
    "Esophageal button battery causes full-thickness burn within 2 hours; removal is an emergency regardless of symptoms",
    ["Esophageal battery causes alkaline burn via electrolysis within 2 hours", "AP and lateral X-ray to locate and confirm it is a button battery", "Complications: perforation, fistula, fatal hemorrhage", "Activated charcoal is contraindicated"],
    "Aortoesophageal fistula from button battery impaction can cause delayed fatal hemorrhage even after battery removal; long-term follow-up is essential",
    ["Waiting for symptoms allows potentially irreversible tissue damage", "Activated charcoal is contraindicated and delays endoscopic visualization", "Sending home without imaging risks catastrophic esophageal injury"],
    "toxic-ingestion-pediatrics");

  mk("A 15-month-old toddler is brought to the ED after ingesting an unknown number of iron tablets from a sibling's supplement bottle. The child is currently vomiting and has bloody diarrhea. A serum iron level is drawn. What is the most important prognostic indicator for iron poisoning severity?",
    ["Peak serum iron level >500 mcg/dL indicates severe toxicity requiring aggressive management with IV deferoxamine chelation therapy", "The child's weight only", "The number of tablets reportedly ingested", "The color of the stool"],
    0, "Peak serum iron level is the most important prognostic indicator for iron poisoning severity. Iron levels >500 mcg/dL indicate severe toxicity with risk of significant morbidity and mortality. The severity scale is: <350 mcg/dL: mild, minimal symptoms; 350-500 mcg/dL: moderate, GI symptoms and potential for systemic toxicity; >500 mcg/dL: severe, requiring deferoxamine chelation; >1000 mcg/dL: associated with significant morbidity and mortality. Iron toxicity progresses through 5 phases: Phase 1 (0.5-6h): GI mucosal injury with vomiting, bloody diarrhea, abdominal pain; Phase 2 (6-24h): apparent improvement (quiescent phase); Phase 3 (12-48h): systemic toxicity with metabolic acidosis, hepatic failure, coagulopathy, cardiovascular collapse; Phase 4 (2-4 days): hepatic failure; Phase 5 (2-8 weeks): GI scarring and obstruction. Deferoxamine 15 mg/kg/hour IV is the specific chelation agent, forming ferrioxamine which is renally excreted, producing characteristic 'vin rose' colored urine. Activated charcoal does NOT adsorb iron, making whole bowel irrigation the preferred decontamination method.", "Use peak serum iron levels to guide severity assessment and deferoxamine chelation decisions in iron poisoning", "Toxic Ingestion in Pediatrics", 3, "application",
    "Activated charcoal does NOT adsorb iron; WBI is the decontamination method, and deferoxamine is the chelation agent producing 'vin rose' urine",
    ["Iron level >500 mcg/dL = severe, requiring deferoxamine chelation", "5 phases: GI injury, quiescent, systemic toxicity, hepatic failure, GI scarring", "Deferoxamine 15 mg/kg/h IV; produces vin rose colored urine", "Activated charcoal does NOT adsorb iron"],
    "Iron poisoning has a deceptive Phase 2 (quiescent); children who appear to improve after initial GI symptoms may deteriorate into systemic toxicity",
    ["Weight helps calculate mg/kg dose but peak level predicts severity better", "Reported tablet count is often inaccurate in pediatric ingestions", "Stool color is not a reliable prognostic indicator"],
    "toxic-ingestion-pediatrics");

  mk("A 2-year-old presents after drinking a small amount of lamp oil. The child is coughing but otherwise asymptomatic. A chest X-ray is normal. Can the child be discharged?",
    ["The child should be observed for 6 hours with repeat chest X-ray because hydrocarbon aspiration pneumonitis can develop on a delayed basis even when the initial X-ray is normal", "Yes, normal X-ray means no aspiration occurred", "Induce vomiting to remove the lamp oil", "Administer activated charcoal"],
    0, "Hydrocarbon ingestion (lamp oil, kerosene, mineral spirits, furniture polish) poses a primary risk of aspiration pneumonitis rather than systemic toxicity for most household hydrocarbons. The critical concern is not the GI absorption but the aspiration of low-viscosity hydrocarbons into the lungs during swallowing or if vomiting occurs. Aspiration pneumonitis from hydrocarbons can develop on a delayed basis: (1) Initial X-ray may be normal even if aspiration has occurred; (2) Radiographic changes typically appear within 2-6 hours; (3) Clinical deterioration (cough, tachypnea, hypoxia, fever) may develop over 6-24 hours. Therefore, the child should be observed for at least 6 hours with a repeat chest X-ray before discharge. If the child remains asymptomatic with a normal repeat X-ray at 6 hours, discharge is generally safe. Inducing vomiting is STRICTLY CONTRAINDICATED as it dramatically increases aspiration risk. Activated charcoal does not adsorb hydrocarbons effectively and also increases aspiration risk. The coughing in this child is concerning for possible aspiration and warrants observation.", "Observe hydrocarbon ingestion patients for minimum 6 hours with repeat imaging to evaluate for delayed aspiration pneumonitis", "Toxic Ingestion in Pediatrics", 3, "application",
    "Normal initial X-ray does NOT rule out hydrocarbon aspiration; radiographic changes develop within 2-6 hours requiring observation period",
    ["Primary risk is aspiration pneumonitis, not systemic toxicity", "Radiographic changes appear 2-6 hours after aspiration", "Observe 6 hours with repeat chest X-ray before discharge", "Vomiting is STRICTLY CONTRAINDICATED (increases aspiration risk)"],
    "NEVER induce vomiting after hydrocarbon ingestion; aspiration of low-viscosity hydrocarbons into the lungs causes chemical pneumonitis that can be fatal",
    ["Normal initial X-ray does not exclude aspiration", "Inducing vomiting is contraindicated and increases aspiration risk", "Activated charcoal is ineffective and increases aspiration risk"],
    "toxic-ingestion-pediatrics");

  // === HEAVY METALS (3 more) ===
  mk("A child presents with abdominal pain, constipation, and a 'lead line' on his gums. His blood lead level is 72 mcg/dL. He also has iron-deficiency anemia. What chelation therapy should the nurse prepare?",
    ["Combination therapy with dimercaprol (BAL) IM followed by CaNa2EDTA (calcium disodium EDTA) IV for blood lead levels above 70 mcg/dL", "Oral succimer (DMSA) alone", "D-penicillamine only", "No chelation; just remove the lead source"],
    0, "Blood lead levels above 70 mcg/dL in children constitute a medical emergency requiring aggressive parenteral chelation therapy. The standard protocol for severe lead poisoning (BLL >70 mcg/dL or symptomatic encephalopathy at any level) is combination therapy: (1) Dimercaprol (BAL: British Anti-Lewisite) 4 mg/kg IM every 4 hours, started FIRST to protect the brain by chelating lead in soft tissues; (2) CaNa2EDTA (calcium disodium EDTA) 1500 mg/m2/day IV continuous infusion, started 4 hours AFTER the first BAL dose. The delay is critical because CaNa2EDTA alone can temporarily increase lead levels in the brain by mobilizing lead from bone before it is excreted renally. BAL must be given first to chelate soft-tissue lead and prevent this redistribution. The iron-deficiency anemia is relevant because: (1) Iron deficiency increases lead absorption from the GI tract through shared divalent metal transporters; (2) Iron supplementation should be started after chelation to correct anemia and reduce further lead absorption. Oral succimer (DMSA) is appropriate for moderate lead levels (45-69 mcg/dL) but insufficient for severe poisoning.", "Administer combination chelation with BAL before CaNa2EDTA for severe lead poisoning, understanding the rationale for the treatment sequence", "Heavy Metal Poisoning", 4, "application",
    "BAL must be given BEFORE CaNa2EDTA to prevent CNS lead redistribution; CaNa2EDTA alone can transiently increase brain lead levels",
    ["BLL >70 mcg/dL requires parenteral combination chelation", "BAL 4 mg/kg IM q4h started FIRST to protect the brain", "CaNa2EDTA started 4 hours after first BAL dose", "Iron deficiency increases lead absorption; treat after chelation"],
    "CaNa2EDTA given without prior BAL in severe lead poisoning can cause acute lead encephalopathy by redistributing lead into the brain",
    ["Oral DMSA is for moderate levels (45-69); insufficient for BLL >70", "D-penicillamine has more side effects and is not first-line", "Source removal alone is insufficient for BLL >70"],
    "heavy-metal-poisoning");

  mk("An emergency nurse notices that a patient admitted for an unknown ingestion has blue-gray skin discoloration (argyria). What toxic exposure caused this permanent discoloration?",
    ["Chronic silver exposure (colloidal silver ingestion) causing irreversible argyria - silver deposits in the skin, nails, and mucous membranes", "Carbon monoxide poisoning", "Lead poisoning", "Mercury exposure"],
    0, "Argyria is a permanent blue-gray discoloration of the skin caused by chronic exposure to silver or silver compounds. Silver particles deposit in the dermis and are reduced by sunlight exposure, creating the characteristic blue-gray pigmentation that is most prominent in sun-exposed areas. Sources of silver exposure include: (1) Colloidal silver supplements (sold as alternative medicine for various conditions); (2) Silver-containing wound dressings with excessive use; (3) Occupational exposure in photography, jewelry, or electronics manufacturing; (4) Silver-containing medications. The discoloration is cosmetically disfiguring but is not in itself medically dangerous. However, it is a marker of significant chronic silver exposure. Treatment of argyria is limited; the discoloration is generally permanent, though laser treatments have shown some improvement. The key nursing role is recognizing argyria as an exposure indicator, discontinuing the silver source, and assessing for internal organ effects (hepatotoxicity, nephrotoxicity with very high exposures). CO poisoning causes cherry-red discoloration. Lead causes a 'lead line' on gums. Mercury causes different neurological and skin manifestations.", "Recognize argyria as a clinical marker of chronic silver exposure and distinguish it from other metal-induced skin changes", "Heavy Metal Poisoning", 2, "recall",
    "Argyria (blue-gray skin) is permanently caused by silver deposits and is a marker of chronic silver exposure, often from colloidal silver supplements",
    ["Argyria: silver deposits in skin from chronic silver exposure", "Common source: colloidal silver supplements sold as alternative medicine", "Discoloration is permanent and most prominent in sun-exposed areas", "Not medically dangerous itself but indicates significant chronic exposure"],
    "Colloidal silver supplements are marketed with unproven health claims; argyria is a permanent cosmetic consequence that patients are rarely warned about",
    ["CO poisoning causes cherry-red discoloration, not blue-gray", "Lead poisoning causes a lead line on gums, not diffuse skin color change", "Mercury causes neurological and different dermatological effects"],
    "heavy-metal-poisoning");

  mk("A patient who works in a thermometer recycling facility presents with tremor, personality changes, and excessive salivation. The nurse suspects mercury poisoning. What is the appropriate chelation agent?",
    ["Succimer (DMSA) orally for chronic elemental mercury exposure, or dimercaprol (BAL) IM for severe acute inorganic mercury poisoning", "CaNa2EDTA", "Deferoxamine", "Prussian blue"],
    0, "Mercury poisoning management depends on the type of mercury compound: (1) Elemental mercury (from thermometers, dental amalgam): primarily causes pulmonary toxicity if inhaled as vapor. Chronic exposure causes erethism (personality changes, tremor, excessive salivation - the 'mad hatter' syndrome). Chelation with oral succimer (DMSA) or unithiol (DMPS) for symptomatic patients. (2) Inorganic mercury salts: primarily cause GI and renal toxicity. Chelation with dimercaprol (BAL) IM for severe cases. (3) Organic mercury (methylmercury from fish): primarily causes CNS toxicity. Chelation is controversial; succimer may be used. This patient's occupational exposure to thermometer recycling (elemental mercury), combined with the classic triad of tremor, personality changes, and salivation, indicates chronic elemental mercury poisoning. CaNa2EDTA is for lead poisoning. Deferoxamine is for iron poisoning. Prussian blue is for thallium and cesium-137 poisoning. The specific chelation agent must match the specific toxic metal exposure.", "Select the appropriate chelation agent for mercury poisoning based on the type of mercury compound and severity of exposure", "Heavy Metal Poisoning", 3, "recall",
    "Match chelation to metal: mercury→DMSA/BAL, lead→BAL+CaNa2EDTA/DMSA, iron→deferoxamine, thallium→Prussian blue",
    ["Elemental Hg: tremor, personality changes, salivation (erethism)", "Inorganic Hg salts: GI and renal toxicity", "Organic Hg (methylmercury): CNS toxicity from fish consumption", "DMSA for chronic elemental; BAL for severe acute inorganic"],
    "Mercury spills require specific cleanup protocols; elemental mercury vaporizes at room temperature creating inhalation hazards",
    ["CaNa2EDTA is for lead poisoning", "Deferoxamine is the iron chelation agent", "Prussian blue is for thallium and radioactive cesium"],
    "heavy-metal-poisoning");

  // === TRICYCLIC ANTIDEPRESSANTS (2 more) ===
  mk("A patient with a TCA overdose has a QRS duration of 130 ms. After sodium bicarbonate bolus, the QRS narrows to 95 ms. However, 2 hours later the QRS widens again to 145 ms. What does this indicate?",
    ["Ongoing TCA absorption or redistribution requiring additional sodium bicarbonate therapy and possible bicarbonate infusion", "The sodium bicarbonate caused the QRS widening", "The patient is improving", "Equipment malfunction"],
    0, "Recurrent QRS widening after initial response to sodium bicarbonate in TCA overdose indicates ongoing drug absorption (particularly from extended-release formulations or large bezoars of pills in the stomach), or redistribution of TCA from tissue compartments back into the bloodstream. TCAs are highly lipophilic with large volumes of distribution, and tissue-bound drug can re-enter circulation causing recurrent toxicity even after initial treatment. Management includes: (1) Additional sodium bicarbonate bolus (1-2 mEq/kg IV) to re-narrow the QRS; (2) Initiation of a sodium bicarbonate infusion (150 mEq in 1L D5W at 1.5-2x maintenance rate) to maintain serum pH between 7.45-7.55; (3) Consideration of whole bowel irrigation if a pill bezoar is suspected; (4) Continuous ECG monitoring for at least 24 hours after the last episode of QRS widening; (5) Serial ABGs to monitor pH. TCAs have long half-lives (24+ hours for some), and sodium channel blockade effects can persist and recur. The patient should not be considered stable until QRS has been normal for at least 24 hours.", "Manage recurrent QRS widening in TCA overdose with additional sodium bicarbonate and consider bicarbonate infusion for sustained effect", "Tricyclic Antidepressant Overdose", 4, "application",
    "QRS can re-widen hours after initial bicarbonate treatment due to ongoing TCA absorption or tissue redistribution; sustained infusion may be needed",
    ["Recurrent widening = ongoing absorption or tissue redistribution", "Additional NaHCO3 bolus plus infusion for sustained effect", "Target serum pH 7.45-7.55 with bicarbonate infusion", "Monitor for at least 24 hours after last QRS widening episode"],
    "TCA effects can recur hours after apparent stabilization; do not transfer from monitored bed until QRS has been normal for 24 hours",
    ["NaHCO3 narrows QRS; recurrence indicates ongoing TCA effect", "Recurrent widening indicates worsening, not improvement", "This pattern is a recognized phenomenon in TCA overdose"],
    "tricyclic-antidepressant-overdose");

  mk("A patient with TCA overdose develops seizures. The emergency nurse knows that the initial seizure treatment differs from the usual protocol. What medication should be used?",
    ["Benzodiazepines (lorazepam or diazepam IV) as first-line, with avoidance of phenytoin which can worsen cardiac conduction abnormalities in TCA poisoning", "Phenytoin IV as first-line anticonvulsant", "Carbamazepine loading dose", "Levetiracetam IV only"],
    0, "TCA-induced seizures should be treated with benzodiazepines as first-line therapy. The critical distinction from standard seizure protocols is that phenytoin is CONTRAINDICATED in TCA overdose because: (1) Phenytoin also blocks sodium channels, which would compound the sodium channel blockade already caused by the TCA, potentially worsening cardiac conduction abnormalities; (2) Phenytoin can precipitate refractory ventricular dysrhythmias in the setting of TCA-induced sodium channel blockade; (3) Phenytoin can cause hypotension, which would worsen the hemodynamic instability common in TCA overdose. Lorazepam 0.1 mg/kg IV (max 4 mg) or diazepam 0.2 mg/kg IV (max 10 mg) should be given for seizures. If seizures are refractory to benzodiazepines, phenobarbital or propofol may be considered. Sodium bicarbonate should also be administered concurrently as seizures from TCA overdose indicate severe toxicity and the acidosis from seizure activity worsens sodium channel blockade. Carbamazepine also has sodium channel blocking properties and is contraindicated.", "Treat TCA-induced seizures with benzodiazepines while avoiding phenytoin which worsens sodium channel blockade", "Tricyclic Antidepressant Overdose", 3, "application",
    "Phenytoin is CONTRAINDICATED in TCA overdose because it compounds sodium channel blockade and can precipitate fatal cardiac dysrhythmias",
    ["Benzodiazepines are first-line for TCA seizures", "Phenytoin compounds sodium channel blockade and worsens cardiac conduction", "Give NaHCO3 concurrently as seizures worsen acidosis which worsens toxicity", "If refractory: consider phenobarbital or propofol"],
    "TCA seizures indicate severe toxicity; concurrent sodium bicarbonate should be administered even if QRS appears normal as seizure-induced acidosis worsens cardiotoxicity",
    ["Phenytoin worsens sodium channel blockade in TCA overdose", "Carbamazepine also has sodium channel blocking properties", "Levetiracetam may be used but benzodiazepines are first-line"],
    "tricyclic-antidepressant-overdose");

  // === TOXIC ALCOHOLS (3 more) ===
  mk("A patient presents with visual complaints described as 'looking through a snowstorm' after drinking homemade moonshine. What toxic substance exposure and its antidote should the nurse immediately consider?",
    ["Methanol poisoning with formic acid-induced optic nerve toxicity; administer fomepizole (4-MP) or ethanol IV to block alcohol dehydrogenase", "Ethanol intoxication causing blurred vision", "Ethylene glycol poisoning", "Isopropyl alcohol toxicity"],
    0, "Visual disturbances described as 'snowstorm' vision or 'looking through a snowfield' are pathognomonic for methanol poisoning. Methanol itself has relatively low toxicity, but it is metabolized by alcohol dehydrogenase to formaldehyde and then to formic acid, which is the toxic metabolite. Formic acid has a specific affinity for the optic nerve and retinal ganglion cells, causing optic disc hyperemia, retinal edema, and ultimately irreversible blindness. Treatment must be initiated emergently: (1) Fomepizole (4-MP) 15 mg/kg IV loading dose, then 10 mg/kg q12h, is the preferred antidote because it inhibits alcohol dehydrogenase with higher affinity than ethanol, preventing further metabolism of methanol to formic acid. (2) If fomepizole is unavailable, IV ethanol can be used (loading dose 0.8 g/kg, then infusion to maintain blood alcohol level 100-150 mg/dL) as a competitive substrate for alcohol dehydrogenase. (3) IV sodium bicarbonate for metabolic acidosis. (4) Hemodialysis for severe cases (methanol >50 mg/dL, severe acidosis, visual symptoms, renal failure). (5) Folate (leucovorin) 50 mg IV q6h enhances formate metabolism. Ethylene glycol causes renal toxicity, not visual symptoms. Isopropyl alcohol causes ketosis without acidosis.", "Recognize visual disturbances as pathognomonic for methanol poisoning and initiate fomepizole to block further toxic metabolism", "Toxic Alcohol Poisoning", 3, "application",
    "Snowstorm vision is pathognomonic for methanol; formic acid specifically damages the optic nerve. Fomepizole blocks the metabolic pathway",
    ["Visual changes from formic acid damage to optic nerve are pathognomonic", "Fomepizole: 15 mg/kg IV loading, then 10 mg/kg q12h", "Alternative: IV ethanol to maintain BAL 100-150 mg/dL", "Folate enhances formate metabolism; give leucovorin 50 mg IV q6h"],
    "Visual damage from methanol can be irreversible; treatment delay of even hours worsens the prognosis for vision recovery",
    ["Ethanol intoxication causes blurred vision but not the characteristic snowstorm description", "Ethylene glycol causes renal toxicity, not visual symptoms", "Isopropyl alcohol causes ketosis without metabolic acidosis"],
    "toxic-alcohol-poisoning");

  mk("A patient presents after ingesting antifreeze. Labs show a pH of 7.08, anion gap of 30, and osmolar gap of 25. Urinalysis reveals calcium oxalate crystals under Wood's lamp fluorescence. What toxic alcohol is responsible?",
    ["Ethylene glycol, which is metabolized to glycolic acid (causing acidosis) and oxalic acid (causing calcium oxalate crystal deposition in kidneys)", "Methanol", "Isopropyl alcohol", "Acetone"],
    0, "Ethylene glycol (the main component of antifreeze) poisoning is confirmed by the combination of severe anion gap metabolic acidosis, elevated osmolar gap, and calcium oxalate crystals in the urine. Ethylene glycol is metabolized through alcohol dehydrogenase to glycoaldehyde, then glycolic acid (responsible for the metabolic acidosis and elevated anion gap), and finally to oxalic acid, which combines with calcium to form calcium oxalate crystals. These crystals deposit in the renal tubules causing acute kidney injury. Additional findings may include: (1) Fluorescence of urine under Wood's lamp from the fluorescein additive in many antifreeze products (though this is not reliable as an absence does not exclude EG poisoning); (2) Hypocalcemia from calcium binding to oxalate (can cause QT prolongation and tetany); (3) Cranial nerve palsies (particularly facial nerve) from CNS calcium oxalate deposition. Treatment is identical to methanol: fomepizole, sodium bicarbonate for acidosis, and hemodialysis for severe cases. Thiamine and pyridoxine are given as cofactors to shunt metabolism away from oxalic acid production.", "Diagnose ethylene glycol poisoning by the triad of anion gap metabolic acidosis, elevated osmolar gap, and calcium oxalate crystalluria", "Toxic Alcohol Poisoning", 4, "analysis",
    "Calcium oxalate crystals in urine are the hallmark of ethylene glycol poisoning; also look for hypocalcemia from calcium chelation by oxalic acid",
    ["EG metabolites: glycolic acid (acidosis) and oxalic acid (crystals)", "Calcium oxalate crystals deposit in renal tubules causing AKI", "Hypocalcemia from calcium binding to oxalate (check QT interval)", "Thiamine and pyridoxine shunt metabolism away from oxalate production"],
    "Hypocalcemia from ethylene glycol can cause fatal cardiac dysrhythmias; monitor calcium levels and ECG for QT prolongation",
    ["Methanol causes visual toxicity, not calcium oxalate crystals", "Isopropyl alcohol causes ketosis without anion gap acidosis", "Acetone does not produce calcium oxalate crystals or acidosis"],
    "toxic-alcohol-poisoning");

  mk("An alcoholic patient presents intoxicated with a serum isopropyl alcohol level of 200 mg/dL. Labs show elevated ketones but normal pH and bicarbonate. What is the most important nursing intervention?",
    ["Supportive care with monitoring, as isopropyl alcohol does not cause anion gap metabolic acidosis like methanol and ethylene glycol; hemodialysis only if hemodynamically unstable", "Administer fomepizole to block alcohol dehydrogenase", "Give sodium bicarbonate for acidosis", "Start IV ethanol as competitive substrate"],
    0, "Isopropyl alcohol (rubbing alcohol) poisoning differs fundamentally from methanol and ethylene glycol poisoning in that it does NOT produce a toxic metabolite that causes metabolic acidosis. Isopropyl alcohol is metabolized to acetone (which causes ketonemia and ketonuria but NOT acidosis). This is the key differentiating feature: isopropyl alcohol causes an osmolar gap and elevated ketones but a NORMAL anion gap (no acidosis). This is in contrast to methanol (formic acid → anion gap acidosis) and ethylene glycol (glycolic/oxalic acid → anion gap acidosis). Management is primarily supportive because: (1) Acetone is relatively non-toxic and is excreted renally and through the lungs; (2) Fomepizole or ethanol is NOT needed because the metabolite (acetone) is not the problem; (3) Hemodialysis is reserved for cases with hemodynamic instability, as it effectively removes both isopropyl alcohol and acetone; (4) Monitoring for respiratory depression, hypotension, and GI hemorrhage (isopropyl alcohol is more irritating to the GI mucosa). The elevated ketones without acidosis is the hallmark that distinguishes isopropyl alcohol from the other toxic alcohols.", "Differentiate isopropyl alcohol poisoning from methanol/EG by the presence of ketosis WITHOUT metabolic acidosis", "Toxic Alcohol Poisoning", 3, "analysis",
    "Isopropyl alcohol produces ketones without acidosis (acetone is the metabolite); fomepizole and ethanol are NOT needed as the metabolite is non-toxic",
    ["Isopropyl alcohol → acetone (non-toxic metabolite)", "Ketosis WITHOUT metabolic acidosis (normal pH and bicarb)", "No need for fomepizole or ethanol since metabolite is non-toxic", "Hemodialysis only for hemodynamic instability"],
    "Do not reflexively give fomepizole for all toxic alcohol ingestions; isopropyl alcohol does not require enzyme blockade as its metabolite is non-toxic",
    ["Fomepizole blocks formation of toxic metabolites; acetone is not toxic", "No acidosis exists requiring bicarbonate treatment", "IV ethanol is not needed as there is no toxic metabolite to prevent"],
    "toxic-alcohol-poisoning");

  // === DIGOXIN TOXICITY (2 more) ===
  mk("A 75-year-old patient on digoxin presents with nausea, visual disturbances (yellow-green halos), and a heart rate of 40 bpm. Digoxin level is 3.8 ng/mL (therapeutic: 0.5-2.0). Potassium is 5.9 mEq/L. What is the most critical intervention?",
    ["Administer digoxin-specific antibody fragments (Digibind/DigiFab) for symptomatic digoxin toxicity with hyperkalemia and hemodynamically significant bradycardia", "Administer calcium gluconate for the hyperkalemia", "Administer atropine only for the bradycardia", "Perform gastric lavage to remove the digoxin"],
    0, "This patient has classic symptomatic digoxin toxicity: GI symptoms (nausea), visual disturbances (yellow-green halos - xanthopsia), bradycardia, supratherapeutic level (3.8 ng/mL), and hyperkalemia (5.9 mEq/L). The hyperkalemia in digoxin toxicity results from inhibition of the Na+/K+-ATPase pump, which normally maintains intracellular potassium. Digoxin-specific antibody fragments (DigiFab) are indicated for: (1) Symptomatic bradycardia unresponsive to atropine; (2) Hyperkalemia above 5.5 mEq/L in the setting of digoxin toxicity; (3) Hemodynamically significant dysrhythmias; (4) Ingestion of >10 mg in adults; (5) Digoxin level >15 ng/mL at any time. CRITICAL: Calcium gluconate for hyperkalemia is RELATIVELY CONTRAINDICATED in digoxin toxicity because excess extracellular calcium can potentiate digoxin's effects on the myocardium, potentially causing 'stone heart' (cardiac arrest in systole). Atropine may temporarily improve bradycardia but does not address the underlying toxicity. DigiFab dose is calculated based on either the total body digoxin load or empirically 10-20 vials for acute ingestion.", "Administer digoxin-specific antibody fragments for symptomatic digoxin toxicity and recognize that calcium is relatively contraindicated for hyperkalemia in this setting", "Digoxin Toxicity", 4, "application",
    "Calcium is RELATIVELY CONTRAINDICATED for hyperkalemia in digoxin toxicity because it can potentiate cardiac toxicity and cause 'stone heart'",
    ["Classic triad: GI symptoms, visual changes (xanthopsia), cardiac dysrhythmias", "DigiFab indications: symptomatic bradycardia, K+ >5.5, significant dysrhythmia", "Calcium relatively contraindicated in digoxin toxicity hyperkalemia", "Hyperkalemia results from Na+/K+-ATPase inhibition"],
    "Never give calcium for hyperkalemia in digoxin toxicity without conferring with toxicology; it may precipitate fatal cardiac arrest",
    ["Calcium may worsen cardiac toxicity in digoxin poisoning", "Atropine is temporary and doesn't address underlying toxicity", "Gastric lavage is not useful for chronic digoxin toxicity"],
    "digoxin-toxicity");

  mk("After administering DigiFab for digoxin toxicity, the nurse draws a follow-up digoxin level which returns markedly elevated at 12 ng/mL despite clinical improvement. Should additional DigiFab be given?",
    ["No, the elevated level represents antibody-bound (inactive) digoxin; clinical response, not drug levels, should guide further dosing", "Yes, the level is still dangerously elevated", "Check free digoxin level instead", "Administer additional DigiFab immediately"],
    0, "After DigiFab administration, total serum digoxin levels become unreliable for clinical decision-making because standard digoxin assays measure both free (active) and antibody-bound (inactive) digoxin. DigiFab binds free digoxin in the serum, rendering it pharmacologically inactive, but the antibody-digoxin complex is measured by standard assays, causing falsely elevated total digoxin levels that can be 10-20 times the pre-treatment level. This phenomenon can persist for days to weeks as the antibody-digoxin complex is slowly cleared by the kidneys. Clinical assessment should guide further management: if the patient shows clinical improvement (resolution of dysrhythmias, normalization of heart rate, improving GI symptoms, and declining potassium), no additional DigiFab is needed regardless of the reported digoxin level. Some laboratories offer free digoxin assays that measure only unbound, pharmacologically active digoxin, which can be useful but are not universally available. The key teaching point is that DigiFab efficacy is assessed by clinical response, not by drug levels.", "Recognize that post-DigiFab digoxin levels are falsely elevated and clinical response guides management, not drug levels", "Digoxin Toxicity", 3, "application",
    "Standard digoxin assays measure antibody-bound (inactive) digoxin after DigiFab, producing falsely elevated levels; assess clinical response instead",
    ["Post-DigiFab levels falsely elevated: assay measures bound + free digoxin", "Clinical improvement (HR, rhythm, GI, K+) guides management", "Falsely elevated levels can persist for days to weeks", "Free digoxin assays are available but not universally"],
    "Do not administer additional DigiFab based on post-treatment digoxin levels alone; this wastes an expensive resource and is not clinically indicated",
    ["The elevated level is antibody-bound inactive digoxin, not active drug", "The falsely elevated level reflects successful DigiFab binding", "Additional DigiFab based on this level would be unnecessary"],
    "digoxin-toxicity");

  return q;
}
