export function generateUltraToxQuestions() {
  const q: any[] = [];
  let id = 180;
  const mk = (s: string, o: string[], ca: number, r: string, lo: string, sub: string, d: number, c: string, et: string, p: string[], sn: string, dr: string[], sl: string) => {
    q.push({ id: `en-tox-${String(id++).padStart(3,'0')}`, stem: s, options: o, correctAnswer: ca, rationaleLong: r, learningObjective: lo, blueprintCategory: "Toxicology", subtopic: sub, difficulty: d, cognitiveLevel: c, questionType: "MCQ_SINGLE", examTrap: et, clinicalPearls: p, safetyNote: sn, distractorRationales: dr, lessonLink: `/emergency/lessons/${sl}` });
  };

  mk("A patient presents with cherry-red skin color, headache, and confusion after being found in a running car in a closed garage. ABG shows carboxyhemoglobin of 35%. What is the treatment?",
    ["100% oxygen via non-rebreather mask and consideration of hyperbaric oxygen therapy for COHb >25% with neurological symptoms", "Room air observation", "Albuterol nebulizer for respiratory distress", "IV methylene blue"],
    0, "Carbon monoxide (CO) poisoning is treated by displacing CO from hemoglobin. CO has 240 times greater affinity for hemoglobin than oxygen. High-flow 100% O2 via NRB reduces COHb half-life from 5-6 hours on room air to 60-90 minutes. Hyperbaric oxygen (HBO) at 2.5-3 atm further reduces half-life to 20-30 minutes and is indicated for COHb >25%, neurological symptoms, cardiac ischemia, pregnancy, or loss of consciousness. Cherry-red skin is a classic but late finding. Pulse oximetry is unreliable as it cannot distinguish COHb from oxyhemoglobin. Co-oximetry on ABG is required for accurate assessment.", "Treat carbon monoxide poisoning with high-flow oxygen and evaluate for hyperbaric oxygen therapy based on COHb level and clinical symptoms", "Carbon Monoxide Poisoning", 3, "application",
    "Pulse oximetry is falsely normal in CO poisoning; co-oximetry is required. HBO criteria: COHb >25%, neuro symptoms, cardiac ischemia, pregnancy",
    ["100% O2 via NRB: COHb half-life 60-90 min vs 5-6 h on room air", "HBO reduces half-life to 20-30 min", "Pulse ox unreliable; use co-oximetry", "Cherry-red skin is classic but late finding"],
    "CO poisoning may have delayed neurological sequelae days to weeks after exposure; ensure neurological follow-up is arranged",
    ["Room air is insufficient for COHb 35%", "Albuterol does not treat CO poisoning", "Methylene blue treats methemoglobinemia, not CO poisoning"],
    "carbon-monoxide-poisoning");

  mk("A toddler presents after ingesting a button battery found on the floor. The battery was swallowed approximately 2 hours ago. X-ray confirms it is lodged in the esophagus. What is the priority intervention?",
    ["Emergent endoscopic removal within 2 hours; esophageal button batteries cause liquefactive necrosis and perforation as rapidly as 2 hours after impaction", "Observation for 24 hours to see if it passes naturally", "Administer ipecac to induce vomiting", "Give activated charcoal"],
    0, "Esophageal button battery impaction is a true emergency. The battery creates an electrical circuit with esophageal tissue, generating hydroxide ions that cause liquefactive necrosis. Tissue damage can occur within 15 minutes and perforation within 2 hours. Complications include esophageal perforation, tracheoesophageal fistula, aortoesophageal fistula (fatal), mediastinitis, and vocal cord paralysis. Management: emergent endoscopic removal (do not wait for NPO status); post-removal: evaluate for injury with contrast study if perforation suspected. If battery has passed to the stomach, management depends on size and patient age: batteries >20 mm in children <5 years may warrant endoscopic removal from stomach if not passed within 48 hours.", "Recognize esophageal button battery impaction as requiring emergent endoscopic removal due to rapid liquefactive necrosis and perforation risk", "Toxicology Screening and Antidote Protocols", 4, "application",
    "Button battery in esophagus = emergent removal; liquefactive necrosis begins within 15 minutes and perforation within 2 hours",
    ["Liquefactive necrosis starts within 15 minutes", "Perforation possible within 2 hours", "Aortoesophageal fistula is a fatal complication", "Do not wait for NPO status for removal"],
    "Button battery esophageal impaction has caused deaths from aortoesophageal fistula; treat as a life-threatening emergency requiring immediate endoscopy",
    ["24-hour observation allows fatal complications to develop", "Ipecac is contraindicated and may cause esophageal re-exposure", "Activated charcoal does not bind or neutralize batteries"],
    "toxicology-screening-antidotes");

  mk("A nurse is managing a patient with isoniazid (INH) overdose who develops status epilepticus. What is the specific antidote?",
    ["Pyridoxine (vitamin B6) given gram-for-gram matching the amount of INH ingested, or 5 grams IV empirically if the amount is unknown", "Standard phenytoin loading", "Diazepam alone without pyridoxine", "Activated charcoal during seizures"],
    0, "Isoniazid (INH) toxicity causes seizures refractory to standard anticonvulsants because INH depletes pyridoxine (vitamin B6), which is required for GABA synthesis. Without GABA (the brain's primary inhibitory neurotransmitter), excitatory activity goes unchecked, causing seizures that do not respond to benzodiazepines or phenytoin alone. Treatment: pyridoxine IV, gram-for-gram matching the INH ingested. If the amount is unknown, give 5 grams IV empirically. Benzodiazepines are used adjunctively but are insufficient without pyridoxine. The classic triad of INH toxicity: seizures, metabolic acidosis, and coma. Phenytoin is ineffective and can worsen toxicity.", "Administer pyridoxine gram-for-gram for INH-induced seizures that are refractory to standard anticonvulsants due to GABA depletion", "Toxicology Screening and Antidote Protocols", 3, "application",
    "INH seizures require pyridoxine (B6) because INH depletes B6 needed for GABA synthesis; standard anticonvulsants alone are insufficient",
    ["Pyridoxine gram-for-gram matching INH dose; 5g empirically", "INH triad: seizures, metabolic acidosis, coma", "Benzodiazepines adjunctive but insufficient alone", "Phenytoin is ineffective for INH seizures"],
    "INH-induced status epilepticus without pyridoxine can be fatal; emergency departments should stock adequate pyridoxine supplies",
    ["Phenytoin is ineffective and may worsen INH toxicity", "Diazepam alone does not address the B6 depletion mechanism", "Activated charcoal should never be given during active seizures"],
    "toxicology-screening-antidotes");

  mk("A farmer presents to the ED with miosis, bradycardia, excessive salivation, and muscle fasciculations after spraying crops. What is the dual antidote regimen?",
    ["Atropine for muscarinic effects (titrated to dry secretions) AND pralidoxime (2-PAM) to reactivate acetylcholinesterase before enzyme aging occurs", "Atropine alone is sufficient", "Naloxone for the miosis", "Physostigmine for the bradycardia"],
    0, "Organophosphate poisoning requires dual antidote therapy: (1) Atropine: competitive antagonist at muscarinic receptors; treats SLUDGE/DUMBELS symptoms (salivation, lacrimation, urination, defecation, GI cramping, emesis, miosis, bronchorrhea, bradycardia). Dosing: 2-4 mg IV initially, doubled every 5 minutes until secretions dry. Patients may require massive doses (100+ mg). Endpoint: drying of secretions, NOT pupil dilation or heart rate. (2) Pralidoxime (2-PAM): reactivates acetylcholinesterase by cleaving the organophosphate-enzyme bond. Must be given before 'aging' occurs (irreversible bond formation). Aging time varies by agent: sarin 5 hours, VX 48 hours, parathion 24 hours. Dosing: 1-2 g IV over 15-30 minutes. 2-PAM does NOT treat muscarinic symptoms; it treats nicotinic symptoms (fasciculations, weakness, paralysis). Both antidotes are needed because atropine alone does not reverse nicotinic effects.", "Administer dual antidote therapy for organophosphate poisoning with atropine for muscarinic effects and pralidoxime for nicotinic effects and enzyme reactivation", "Organophosphate Exposure", 3, "application",
    "Atropine endpoint is drying of secretions, NOT pupil dilation; 2-PAM must be given before enzyme aging for cholinesterase reactivation",
    ["Atropine titrated to dry secretions; may need 100+ mg", "2-PAM reactivates cholinesterase before aging", "Atropine = muscarinic; 2-PAM = nicotinic effects", "Aging time varies by agent (sarin 5h, VX 48h)"],
    "Massive atropine doses may be needed; inadequate atropinization is a common error in OP poisoning management",
    ["Atropine alone does not treat nicotinic effects (weakness, paralysis)", "Naloxone treats opioids, not organophosphates", "Physostigmine is a cholinesterase inhibitor that would worsen OP poisoning"],
    "organophosphate-exposure");

  mk("A patient with suspected methanol ingestion has an osmolar gap of 30 mOsm/kg. What does this indicate and what treatment is needed?",
    ["The elevated osmolar gap indicates significant methanol present in blood that has not yet been metabolized to toxic formic acid; administer fomepizole and prepare for possible hemodialysis", "An osmolar gap of 30 is normal", "Only IV fluids are needed", "Give methylene blue for the elevated gap"],
    0, "The osmolar gap is the difference between measured and calculated serum osmolality. An osmolar gap >10 mOsm/kg suggests the presence of unmeasured osmotically active substances. In the context of suspected toxic alcohol ingestion, elevated osmolar gap indicates the parent compound (methanol or ethylene glycol) is still present in the blood. As the parent compound is metabolized to toxic metabolites (formic acid from methanol, glycolic/oxalic acid from ethylene glycol), the osmolar gap decreases while the anion gap increases - this is the 'osmolar gap to anion gap transition.' Treatment: fomepizole 15 mg/kg IV loading dose to block alcohol dehydrogenase, preventing metabolism to toxic metabolites. Hemodialysis indications: methanol level >25 mg/dL, severe metabolic acidosis (pH <7.25), visual symptoms, renal failure, or clinical deterioration despite antidotal therapy.", "Interpret the elevated osmolar gap as unmeasured toxic alcohol presence and initiate fomepizole therapy to prevent toxic metabolite formation", "Toxic Alcohol Poisoning", 4, "analysis",
    "Elevated osmolar gap = parent compound present; as metabolism occurs, osmolar gap falls and anion gap rises (the gap-gap transition)",
    ["Osmolar gap >10 suggests unmeasured osmotically active substance", "Gap-gap transition: osmolar gap ↓ as anion gap ↑ during metabolism", "Fomepizole blocks metabolism to toxic metabolites", "HD indications: level >25, pH <7.25, visual symptoms, renal failure"],
    "Both elevated osmolar gap AND elevated anion gap can be present simultaneously during toxic alcohol poisoning; absence of one does not rule out poisoning",
    ["An osmolar gap of 30 is significantly elevated (normal <10)", "IV fluids alone do not prevent toxic metabolite formation", "Methylene blue treats methemoglobinemia, not toxic alcohol poisoning"],
    "toxic-alcohol-poisoning");

  mk("A nurse is caring for a patient with lithium toxicity. The patient's lithium level is 3.5 mEq/L with confusion, tremor, and renal insufficiency. What is the treatment?",
    ["Aggressive IV normal saline hydration for mild-moderate toxicity, but hemodialysis is indicated for levels >2.5 mEq/L with symptoms or renal impairment", "Activated charcoal to absorb the lithium", "Forced alkaline diuresis", "Kayexalate to bind lithium"],
    0, "Lithium is a unique toxicological challenge because it is not protein-bound, has a narrow therapeutic index (0.6-1.2 mEq/L), and is entirely renally eliminated. At level 3.5 mEq/L with neurological symptoms and renal insufficiency, hemodialysis is clearly indicated. HD criteria: level >2.5 mEq/L with symptoms, level >4.0 mEq/L regardless of symptoms, or renal insufficiency preventing adequate excretion. IV NS hydration helps by maintaining renal perfusion and lithium clearance, but is insufficient when kidneys are impaired. Activated charcoal does NOT adsorb lithium (it is a monovalent cation too small for charcoal binding). Kayexalate (sodium polystyrene sulfonate) has been studied but evidence is insufficient and it may cause GI complications. Whole bowel irrigation may help with sustained-release lithium formulations. Post-dialysis lithium rebound occurs as lithium redistributes from tissues to blood; repeat levels should be checked.", "Initiate hemodialysis for severe lithium toxicity with neurological symptoms and renal insufficiency when lithium level exceeds 2.5 mEq/L", "Toxicology Screening and Antidote Protocols", 3, "application",
    "Activated charcoal does NOT adsorb lithium; hemodialysis is the definitive treatment for severe toxicity with renal impairment",
    ["Lithium therapeutic index: 0.6-1.2 mEq/L", "HD criteria: >2.5 with symptoms, >4.0 regardless, or renal failure", "Activated charcoal does not bind lithium", "Post-dialysis rebound requires repeat level monitoring"],
    "Lithium toxicity with neurological symptoms can cause permanent cerebellar damage; early hemodialysis is neuroprotective",
    ["Activated charcoal does not bind lithium ions", "Forced alkaline diuresis is not effective for lithium clearance", "Kayexalate has insufficient evidence and risk of GI complications"],
    "toxicology-screening-antidotes");

  mk("A patient with a history of substance use disorder presents with an agitated delirium, temperature of 106°F, muscle rigidity, and rhabdomyolysis after using 'Molly' (MDMA/ecstasy). What is the most life-threatening complication the nurse should anticipate?",
    ["Severe hyponatremia from SIADH and excessive water intake, combined with hyperthermia-induced disseminated intravascular coagulation (DIC) and multiorgan failure", "Mild anxiety requiring observation only", "Standard hangover effects", "Constipation from MDMA"],
    0, "MDMA (ecstasy/Molly) toxicity can cause a life-threatening syndrome combining serotonergic excess with stimulant effects: (1) Hyperthermia: the most dangerous immediate effect, which triggers DIC, rhabdomyolysis, hepatic failure, and cardiovascular collapse. Aggressive cooling with ice water immersion, evaporative cooling, and cold IV fluids is essential. Antipyretics are INEFFECTIVE because hyperthermia is from muscle hyperactivity, not altered thermoregulatory set point; (2) Hyponatremia: MDMA stimulates ADH (SIADH) and users often drink excessive water, leading to dilutional hyponatremia that can cause cerebral edema and seizures, particularly in young women; (3) Serotonin syndrome: agitation, clonus, hyperreflexia, autonomic instability; treat with benzodiazepines and cyproheptadine; (4) Rhabdomyolysis from muscle rigidity and dancing; (5) DIC from hyperthermia above 104°F.", "Manage MDMA toxicity with aggressive cooling, hyponatremia assessment, and anticipation of DIC and rhabdomyolysis from hyperthermia", "Serotonin Syndrome", 4, "analysis",
    "MDMA hyperthermia is from muscle hyperactivity not altered set point - antipyretics are ineffective; aggressive physical cooling is required",
    ["Hyperthermia triggers DIC at >104°F", "SIADH + excessive water intake = hyponatremia", "Antipyretics ineffective; use physical cooling methods", "Young women at higher risk for severe hyponatremia"],
    "MDMA-induced hyperthermia above 106°F has near 100% mortality without aggressive cooling; begin cooling immediately without delay",
    ["MDMA toxicity is a potentially fatal syndrome, not mild anxiety", "Effects are far more serious than a hangover", "MDMA causes diarrhea, not constipation; but the life-threatening issues are the focus"],
    "serotonin-syndrome");

  mk("A patient presents to the ED after being bitten by a copperhead snake on their hand. The hand is swollen to the wrist. What determines whether antivenom is needed?",
    ["Progressive swelling beyond the bite site, coagulopathy (low fibrinogen, elevated PT/INR, thrombocytopenia), or systemic symptoms determine antivenom need; a single-site swelling without progression may be managed with observation and wound care", "All snake bites require antivenom", "No copperhead bites ever need antivenom", "Antivenom is only for rattlesnake bites"],
    0, "Copperhead (Agkistrodon contortrix) envenomation is usually less severe than rattlesnake or cottonmouth bites, but can still cause significant morbidity. CroFab (crotalid polyvalent immune Fab) or Anavip (crotalidae immune F(ab')2) antivenom is indicated when: (1) Progressive swelling: extending beyond the immediate bite area with continued progression; (2) Coagulopathy: decreased fibrinogen, elevated PT/INR, thrombocytopenia; (3) Systemic symptoms: hypotension, perioral tingling, metallic taste, nausea/vomiting; (4) Significant functional impairment of the affected extremity. Monitoring includes: mark the leading edge of swelling every 15-30 minutes to track progression; serial labs (CBC, PT/INR, fibrinogen, CMP) every 4-6 hours; 12-lead ECG; tetanus prophylaxis; wound care. Do NOT: apply ice, tourniquet, or suction; elevate above heart level initially (controversial); do NOT incise the wound.", "Determine antivenom need for copperhead envenomation based on swelling progression, coagulopathy, and systemic symptoms rather than bite occurrence alone", "Toxicology Screening and Antidote Protocols", 3, "analysis",
    "Mark swelling edge every 15-30 minutes to track progression; copperhead bites may not need antivenom if swelling is localized and labs are normal",
    ["Mark swelling edge every 15-30 min to track progression", "Labs: CBC, PT/INR, fibrinogen, CMP every 4-6 hours", "No ice, tourniquet, suction, or wound incision", "CroFab or Anavip for progressive swelling or coagulopathy"],
    "Some copperhead bites may develop delayed coagulopathy days later; ensure outpatient follow-up with repeat labs at 2-3 days and 5-7 days post-bite",
    ["Not all snake bites require antivenom; severity determines treatment", "Some copperhead bites are severe enough to warrant antivenom", "CroFab and Anavip are effective for all North American pit viper bites"],
    "toxicology-screening-antidotes");

  mk("A patient on metformin for type 2 diabetes presents with severe lactic acidosis (pH 6.9, lactate 18 mmol/L) and acute kidney injury. What is the specific treatment concern?",
    ["Metformin-associated lactic acidosis (MALA) requires hemodialysis for both metformin removal and correction of severe acidosis; sodium bicarbonate alone is insufficient for pH <7.1", "Standard insulin drip for the acidosis", "Oral antacids for the pH correction", "Stop metformin and observe without further intervention"],
    0, "Metformin-associated lactic acidosis (MALA) occurs when metformin accumulates due to decreased renal clearance (AKI, dehydration, contrast dye nephropathy). Metformin inhibits mitochondrial complex I, shifting metabolism toward anaerobic glycolysis and lactate production. At pH 6.9 with lactate 18 mmol/L, this is severe metabolic acidosis requiring: (1) Hemodialysis: definitive treatment that removes metformin (molecular weight 129 Da, not protein bound, excellent dialysis characteristics) and corrects acidosis with bicarbonate-based dialysate; (2) Sodium bicarbonate: temporizing measure for pH <7.1, but may cause paradoxical intracellular acidosis and volume overload if used alone; (3) Hemodynamic support: vasopressors as needed; severe acidosis causes vasodilation and cardiac depression; (4) Supportive care: IV fluids, glucose monitoring. Mortality of severe MALA approaches 50% without hemodialysis but is significantly lower (15-25%) with early dialysis.", "Initiate hemodialysis for severe metformin-associated lactic acidosis to remove metformin and correct acidosis when pH is below 7.1", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "MALA mortality approaches 50% without dialysis; metformin is easily dialyzable (MW 129, no protein binding); early HD dramatically improves survival",
    ["Metformin accumulates in renal failure", "Inhibits mitochondrial complex I causing lactate production", "HD removes metformin and corrects acidosis simultaneously", "Bicarb alone insufficient for pH <7.1; causes paradoxical intracellular acidosis"],
    "Severe MALA (pH <7.0) has very high mortality; immediate hemodialysis consultation is critical and should not be delayed",
    ["Insulin drip does not correct metformin-induced lactic acidosis", "Oral antacids are absurd for a pH of 6.9 in critical illness", "Stopping metformin alone is insufficient for severe MALA with AKI"],
    "toxicology-screening-antidotes");

  mk("An emergency nurse is assessing a patient who presents with bilateral facial droop, dysphagia, and descending paralysis 12 hours after eating home-canned green beans. What toxicological diagnosis should be considered?",
    ["Botulism (Clostridium botulinum toxin) from improperly canned food causing descending flaccid paralysis by blocking acetylcholine release at the neuromuscular junction", "Stroke causing unilateral facial droop", "Myasthenia gravis exacerbation", "Guillain-Barré syndrome"],
    0, "Foodborne botulism presents with descending symmetric flaccid paralysis, starting with cranial nerves (ptosis, diplopia, facial weakness, dysphagia, dysarthria) and progressing downward to limb and respiratory muscles. The toxin blocks presynaptic acetylcholine release at the neuromuscular junction by cleaving SNARE proteins. Key distinguishing features from similar presentations: (1) vs. stroke: botulism is bilateral and symmetric; stroke is typically unilateral; (2) vs. myasthenia gravis: botulism is acute onset with food exposure history; MG is chronic with fluctuating symptoms; (3) vs. Guillain-Barré: botulism is descending; GBS is ascending. Treatment: botulism antitoxin (heptavalent from CDC) should be administered as soon as clinical suspicion is present without waiting for confirmatory testing; supportive care with mechanical ventilation as needed. Contact public health immediately as other people may have eaten the same food.", "Recognize descending flaccid paralysis with cranial nerve involvement and food exposure history as botulism requiring immediate antitoxin and public health notification", "Toxicology Screening and Antidote Protocols", 3, "analysis",
    "Botulism = descending paralysis (vs GBS ascending); bilateral symmetric (vs stroke unilateral); antitoxin from CDC; notify public health immediately",
    ["Descending symmetric flaccid paralysis", "Blocks presynaptic ACh release (SNARE protein cleavage)", "Antitoxin from CDC; give before confirmatory testing", "Notify public health for source control"],
    "Respiratory failure from diaphragm paralysis can occur rapidly; have intubation equipment ready and monitor respiratory function closely",
    ["Botulism is bilateral symmetric, not unilateral like stroke", "Acute onset with food exposure differentiates from chronic MG", "Descending paralysis distinguishes from ascending GBS"],
    "toxicology-screening-antidotes");

  mk("A teenager is brought to the ED after huffing difluoroethane (computer duster spray). He collapsed while running after inhaling. What is the mechanism of sudden death?",
    ["Sensitization of the myocardium to catecholamines causing fatal cardiac dysrhythmia (sudden sniffing death syndrome), triggered by the catecholamine surge from physical exertion after inhalation", "Respiratory depression from the inhalant", "Allergic reaction to the propellant", "Carbon monoxide production from the spray"],
    0, "Sudden sniffing death syndrome (SSDS) accounts for the majority of inhalant abuse deaths and can occur with a single use. The mechanism: fluorinated hydrocarbons (difluoroethane, trifluoroethane, found in computer duster, refrigerants) sensitize the myocardium to catecholamines. When the user then engages in physical activity (running, being startled, being chased) or experiences emotional stress, the resulting catecholamine surge triggers fatal cardiac dysrhythmias (usually ventricular fibrillation). This can happen even in first-time users with no prior history. Management: ACLS protocols for cardiac arrest; avoid additional catecholamines (epinephrine) as they worsen the catecholamine-sensitized state. Consider beta-blockers for ventricular dysrhythmias. If the patient survives, monitor for: myocardial injury (troponin), hepatotoxicity, and renal injury. Prevention education is critical as many adolescents do not perceive inhalant abuse as dangerous.", "Recognize sudden sniffing death syndrome from inhalant-induced myocardial catecholamine sensitization and avoid epinephrine in resuscitation", "Toxicology Screening and Antidote Protocols", 3, "analysis",
    "Avoid epinephrine in inhalant-associated cardiac arrest; the myocardium is already catecholamine-sensitized. Consider beta-blockers for dysrhythmias",
    ["Fluorinated hydrocarbons sensitize myocardium to catecholamines", "Physical activity after huffing triggers catecholamine surge", "Can occur with single first-time use", "Avoid epinephrine in resuscitation; consider beta-blockers"],
    "Sudden sniffing death can occur with the very first use; there is no safe dose or number of times for inhalant abuse",
    ["Death is from cardiac dysrhythmia, not respiratory depression", "This is a pharmacological sensitization, not an allergic reaction", "Computer duster spray does not produce carbon monoxide"],
    "toxicology-screening-antidotes");

  mk("A patient with end-stage liver disease is being treated for hepatic encephalopathy. The nurse knows that ammonia levels correlate poorly with clinical severity. What clinical assessment tool is most useful?",
    ["The West Haven Criteria grades hepatic encephalopathy from 0 (minimal/subclinical) to 4 (coma) based on clinical findings including consciousness, intellect, behavior, and neuromuscular function", "Ammonia levels alone determine severity", "Standard Glasgow Coma Scale is sufficient", "The MELD score grades encephalopathy severity"],
    0, "The West Haven Criteria is the standard clinical grading system for hepatic encephalopathy (HE): Grade 0 (minimal/covert): no clinical findings but impaired psychometric testing; Grade 1: trivial lack of awareness, shortened attention span, impaired addition/subtraction, altered sleep rhythm; Grade 2: lethargy, disorientation to time, obvious personality change, inappropriate behavior, asterixis; Grade 3: somnolence to semi-stupor, responsiveness to stimuli, confusion, gross disorientation, bizarre behavior; Grade 4: coma, no response to verbal or noxious stimuli. Nursing implications: regular neurological assessments using West Haven Criteria; lactulose titration to 3-4 soft stools per day; rifaximin for secondary prophylaxis; monitor for triggers (GI bleeding, infection, constipation, hypokalemia, alkalosis, excessive protein, sedatives). Ammonia levels do not reliably correlate with clinical severity and should not be used to titrate treatment.", "Assess hepatic encephalopathy severity using the West Haven Criteria rather than ammonia levels, which correlate poorly with clinical severity", "Toxicology Screening and Antidote Protocols", 3, "recall",
    "West Haven grades HE 0-4 by clinical findings; ammonia levels are unreliable for severity assessment; lactulose titrated to 3-4 stools/day",
    ["West Haven: 0=minimal, 1=mild confusion, 2=asterixis/lethargy, 3=somnolent, 4=coma", "Ammonia levels do not reliably correlate with severity", "Lactulose: titrate to 3-4 soft stools/day", "Triggers: GI bleed, infection, constipation, hypokalemia, alkalosis"],
    "Grade 3-4 HE may require ICU-level care with airway protection; aspiration risk is high in patients who are somnolent or obtunded",
    ["Ammonia levels are unreliable as a sole measure of severity", "GCS assesses consciousness but lacks HE-specific features", "MELD predicts liver disease mortality but does not grade encephalopathy"],
    "toxicology-screening-antidotes");

  mk("A patient who works in a battery recycling plant presents with abdominal colic, constipation, a bluish 'lead line' on the gingiva, and wrist drop. What is the diagnosis and confirmatory test?",
    ["Chronic lead poisoning confirmed by venous blood lead level; additional studies include free erythrocyte protoporphyrin (FEP), zinc protoporphyrin (ZPP), and basophilic stippling on peripheral smear", "Acute food poisoning with stool culture", "Carpal tunnel syndrome with EMG", "Iron deficiency anemia with ferritin level"],
    0, "Chronic lead poisoning (plumbism) presents with the classic triad: abdominal colic (lead colic), peripheral neuropathy (wrist drop from radial nerve motor neuropathy), and a bluish-gray line on the gingival margin (Burton's line from lead sulfide deposits). Additional findings include: constipation, fatigue, cognitive impairment, anemia (basophilic stippling on smear), nephropathy, and in children, developmental delays. Diagnosis: venous blood lead level (BLL) is the gold standard. BLL >5 μg/dL is considered elevated in adults (CDC). Free erythrocyte protoporphyrin (FEP) and zinc protoporphyrin (ZPP) are elevated as lead inhibits heme synthesis enzymes (ALA dehydratase and ferrochelatase). Treatment depends on severity: BLL 50-69 μg/dL: oral chelation with succimer (DMSA); BLL >70 μg/dL or symptomatic: parenteral chelation with CaNa2EDTA ± BAL (dimercaprol). Remove from exposure source.", "Diagnose chronic lead poisoning by clinical presentation and venous blood lead level, and initiate chelation therapy based on level severity", "Toxicology Screening and Antidote Protocols", 3, "recall",
    "Lead poisoning triad: abdominal colic + wrist drop + gingival lead line; diagnose with venous BLL; basophilic stippling on smear",
    ["Classic triad: abdominal colic, wrist drop, Burton's line", "Venous blood lead level is gold standard diagnosis", "FEP and ZPP elevated from heme synthesis inhibition", "Chelation: succimer (oral) for BLL 50-69; CaNa2EDTA for BLL >70"],
    "Lead exposure is an occupational hazard in battery recycling, smelting, and construction; report to occupational health and ensure workplace evaluation",
    ["This is chronic lead poisoning, not acute food poisoning", "Wrist drop is from lead neuropathy, not carpal tunnel syndrome", "Lead causes anemia but is confirmed by BLL, not ferritin"],
    "toxicology-screening-antidotes");

  mk("A patient presents after ingesting a large amount of diphenhydramine (Benadryl). The patient has wide-complex tachycardia on the monitor. What treatment should the nurse prepare?",
    ["Sodium bicarbonate boluses for the wide-complex tachycardia caused by diphenhydramine's sodium channel blocking effects, similar to tricyclic antidepressant overdose management", "Adenosine for the tachycardia", "Physostigmine for the sodium channel blockade", "Calcium chloride for the wide QRS"],
    0, "Diphenhydramine in overdose has multiple toxic effects: anticholinergic syndrome (the most common), but at high doses it also causes sodium channel blockade similar to tricyclic antidepressants, leading to QRS prolongation and wide-complex tachycardia that can degenerate to ventricular tachycardia or fibrillation. Treatment: (1) Sodium bicarbonate: 1-2 mEq/kg IV boluses for QRS >100 ms, targeting QRS narrowing and serum pH 7.45-7.55. This overcomes sodium channel blockade by increasing extracellular sodium and alkalinizing the blood; (2) Physostigmine: treats the anticholinergic syndrome (agitation, delirium) but is CONTRAINDICATED if there are conduction abnormalities (wide QRS, heart block) because it can worsen cardiac toxicity; (3) Benzodiazepines for seizures; (4) Avoid class IA and IC antiarrhythmics. The nurse should recognize that diphenhydramine overdose can mimic TCA overdose hemodynamically.", "Treat diphenhydramine-induced wide-complex tachycardia with sodium bicarbonate recognizing the sodium channel blocking effect, and avoid physostigmine when conduction abnormalities are present", "Anticholinergic Toxidrome", 4, "analysis",
    "High-dose diphenhydramine blocks sodium channels like TCAs; treat wide QRS with sodium bicarbonate. Physostigmine is CONTRAINDICATED with QRS widening",
    ["Sodium bicarbonate 1-2 mEq/kg for QRS >100 ms", "Target serum pH 7.45-7.55 for sodium channel blockade", "Physostigmine CONTRAINDICATED with conduction abnormalities", "Avoid class IA and IC antiarrhythmics"],
    "Wide-complex tachycardia from diphenhydramine can rapidly degenerate to VT/VF; sodium bicarbonate must be given emergently",
    ["Adenosine is for narrow-complex SVT, not sodium channel blocking toxicity", "Physostigmine worsens cardiac toxicity when conduction is abnormal", "Calcium chloride is for hyperkalemia or CCB overdose, not sodium channel blockade"],
    "anticholinergic-toxidrome");

  mk("A nursing student asks about the difference between toxicology terms 'LD50' and 'therapeutic index.' The emergency nurse explains these concepts using what definitions?",
    ["LD50 is the dose lethal to 50% of a test population; therapeutic index is the ratio of TD50 (toxic dose for 50%) to ED50 (effective dose for 50%), indicating the safety margin of a drug", "LD50 measures how quickly a drug works", "Therapeutic index is the maximum dose a patient can take", "These terms are interchangeable and mean the same thing"],
    0, "Key toxicology concepts: (1) LD50 (Lethal Dose 50): the dose of a substance that kills 50% of a test population under standardized conditions. Lower LD50 = more toxic substance. Used primarily in preclinical/animal studies; (2) ED50 (Effective Dose 50): the dose that produces the desired therapeutic effect in 50% of the population; (3) TD50 (Toxic Dose 50): the dose that produces toxic effects in 50% of the population; (4) Therapeutic Index (TI): TI = TD50/ED50. A higher TI means a larger margin between the effective dose and the toxic dose, meaning the drug is safer. Drugs with narrow therapeutic indices require careful dosing and monitoring: digoxin (TI ~2-3), lithium, warfarin, theophylline, phenytoin, carbamazepine, aminoglycosides. These concepts help nurses understand why certain medications require therapeutic drug monitoring and why overdose of narrow TI drugs is particularly dangerous.", "Define LD50, ED50, TD50, and therapeutic index and explain their clinical relevance for medication safety and therapeutic drug monitoring", "Toxicology Screening and Antidote Protocols", 2, "recall",
    "Narrow therapeutic index drugs (digoxin, lithium, warfarin, phenytoin) require therapeutic drug monitoring because toxic and therapeutic doses are close",
    ["LD50: dose lethal to 50% of test population", "TI = TD50/ED50; higher = safer margin", "Narrow TI drugs: digoxin, lithium, warfarin, phenytoin, theophylline", "Narrow TI requires therapeutic drug monitoring"],
    "Narrow therapeutic index drugs are the most common cause of medication-related toxicity; maintain vigilance with dosing and monitoring",
    ["LD50 measures lethality, not speed of action", "Therapeutic index is a ratio, not a maximum dose", "These are distinct concepts with different meanings"],
    "toxicology-screening-antidotes");

  mk("A patient presents with 'serotonin syndrome triad' after combining tramadol with an SSRI. What are the three components of the triad and the specific antidote?",
    ["Neuromuscular excitability (clonus, hyperreflexia, rigidity), autonomic dysfunction (hyperthermia, diaphoresis, tachycardia), and altered mental status; cyproheptadine is the specific serotonin antagonist", "The triad is rash, fever, and joint pain treated with steroids", "The triad is nausea, vomiting, and diarrhea treated with ondansetron", "The triad is headache, photophobia, and neck stiffness treated with antibiotics"],
    0, "Serotonin syndrome results from excessive serotonergic activity at 5-HT1A and 5-HT2A receptors. The Hunter Criteria diagnostic triad: (1) Neuromuscular excitability: clonus (spontaneous, inducible, or ocular), hyperreflexia, tremor, rigidity (late finding indicating severity); (2) Autonomic dysfunction: hyperthermia (can exceed 41°C/106°F), diaphoresis, tachycardia, hypertension, mydriasis, diarrhea, increased bowel sounds; (3) Altered mental status: agitation, anxiety, confusion, delirium. Treatment: (1) Discontinue all serotonergic agents; (2) Cyproheptadine: 5-HT2A antagonist, 12 mg loading dose then 4 mg every 1-2 hours (max 32 mg/day); only available orally or via NG tube; (3) Benzodiazepines for agitation and autonomic instability; (4) Active cooling for hyperthermia; (5) Avoid dantrolene (not effective for serotonin syndrome); (6) Intubation and paralysis for severe cases with temperature >41°C. Common drug combinations causing SS: SSRI + tramadol, SSRI + MAOI, SSRI + linezolid, SSRI + dextromethorphan.", "Identify the serotonin syndrome triad and administer cyproheptadine as the specific serotonin antagonist while managing hyperthermia and autonomic dysfunction", "Serotonin Syndrome", 3, "application",
    "Hunter Criteria: clonus is the key distinguishing feature of serotonin syndrome; cyproheptadine is only available PO/NG, not IV",
    ["Triad: neuromuscular + autonomic + mental status changes", "Cyproheptadine: 12 mg load, then 4 mg q1-2h; PO/NG only", "Clonus is the key feature distinguishing SS from other syndromes", "Common combo: SSRI + tramadol, SSRI + MAOI, SSRI + linezolid"],
    "Severe serotonin syndrome with temp >41°C requires intubation and neuromuscular paralysis; paralytic agents stop muscle activity producing heat",
    ["SS triad is neuromuscular + autonomic + mental status, not rash/fever/joint pain", "SS causes diarrhea from serotonergic GI stimulation; this is part of autonomic dysfunction", "SS is not meningitis; the triad components are different"],
    "serotonin-syndrome");

  mk("An elderly patient on digoxin presents with visual disturbances described as 'yellow halos around lights', nausea, and a heart rate of 38 bpm. The nurse suspects digoxin toxicity. What findings on ECG are characteristic?",
    ["Bidirectional ventricular tachycardia, atrial tachycardia with AV block, frequent PVCs, and the 'regularization of atrial fibrillation' (regular ventricular rate in a patient with known chronic AFib suggesting complete heart block)", "Normal sinus rhythm only", "ST elevation suggesting MI", "Prolonged QT interval only"],
    0, "Digoxin toxicity has characteristic ECG findings that the nurse should recognize: (1) Bidirectional ventricular tachycardia: alternating QRS axis, highly specific for digoxin toxicity; (2) Atrial tachycardia with variable AV block: increased automaticity with impaired conduction is the hallmark of digitalis toxicity; (3) Frequent PVCs, often in bigeminal pattern; (4) Regularization of AFib: in patients with chronic AFib, a regular ventricular rate suggests complete heart block from digoxin toxicity (the irregular irregularity becomes regular); (5) Junctional rhythms; (6) Any bradyarrhythmia. Other clinical features: nausea/vomiting (early symptoms), visual disturbances (xanthopsia - yellow-green halos, altered color perception), confusion, fatigue. Risk factors for toxicity: hypokalemia (most important - enhances digoxin binding to Na/K ATPase), hypomagnesemia, hypercalcemia, hypothyroidism, renal insufficiency. Treatment: Digoxin-specific antibody fragments (Digibind/DigiFab) for hemodynamically unstable rhythms, hyperkalemia >5.5 mEq/L, or ingestion >10 mg in adults.", "Recognize characteristic ECG patterns of digoxin toxicity including bidirectional VT and regularization of atrial fibrillation, and identify risk factors for toxicity", "Toxicology Screening and Antidote Protocols", 3, "recall",
    "Bidirectional VT is highly specific for digoxin toxicity; 'regularized AFib' (regular rate in chronic AFib) suggests complete heart block from digoxin",
    ["Bidirectional VT: alternating QRS axis, highly specific", "Atrial tach with AV block: hallmark of digitalis toxicity", "Regularized AFib suggests complete heart block", "Hypokalemia is the most important risk factor for toxicity"],
    "Do NOT cardiovert digoxin-toxic rhythms; cardioversion in the setting of digoxin toxicity can cause refractory VF. Use Digibind/DigiFab instead",
    ["Multiple arrhythmias are characteristic, not just normal sinus", "Digoxin toxicity does not typically cause ST elevation", "QT prolongation is not the primary ECG finding of digoxin toxicity"],
    "toxicology-screening-antidotes");

  mk("A nurse in the ED receives a patient transferred from an outside hospital with a documented allergy to N-acetylcysteine (NAC). The patient has a significant acetaminophen overdose with rising liver function tests. What alternative management is appropriate?",
    ["NAC 'allergy' is almost always an anaphylactoid (non-IgE mediated) reaction that can be managed by slowing the infusion rate, pretreatment with antihistamines and steroids, and using a modified dosing protocol; true NAC allergy is extremely rare", "Withhold NAC and provide supportive care only", "Substitute with activated charcoal as the sole treatment", "Transfer to another hospital that has a different antidote"],
    0, "NAC anaphylactoid reactions are relatively common (10-20% of patients receiving IV NAC) and are dose-related, occurring most frequently during the initial loading dose when NAC concentration is highest. They are anaphylactoid (non-IgE mediated histamine release), not true allergic reactions, meaning: (1) They can be managed by slowing the infusion rate; (2) Pretreatment with diphenhydramine 50 mg IV, ranitidine 50 mg IV, and dexamethasone 10 mg IV; (3) Modified dosing protocols that deliver the same total dose over a longer period (e.g., the 'two-bag' modified Prescott protocol); (4) If a reaction occurs: stop the infusion, treat symptoms (epinephrine for severe reactions), then restart at a slower rate. True IgE-mediated NAC allergy is extremely rare. The benefits of NAC in significant acetaminophen overdose (preventing fulminant hepatic failure and death) far outweigh the risks of managed anaphylactoid reactions. Withholding NAC for a documented 'allergy' without attempting modified administration is not appropriate.", "Manage NAC anaphylactoid reactions with rate reduction, pretreatment, and modified protocols rather than withholding this life-saving antidote", "Acetaminophen Overdose and NAC Protocol", 4, "application",
    "NAC reactions are anaphylactoid (non-IgE), not true allergies; manage with rate reduction and pretreatment, do NOT withhold NAC",
    ["10-20% of IV NAC patients have anaphylactoid reactions", "Non-IgE mediated: manageable by slowing infusion rate", "Pretreat: diphenhydramine + ranitidine + dexamethasone", "Modified dosing protocols deliver same dose over longer period"],
    "Withholding NAC from a patient with significant acetaminophen overdose due to a manageable anaphylactoid reaction can result in fulminant hepatic failure and death",
    ["Withholding NAC allows progressive liver injury", "Activated charcoal is useful early but not a substitute for NAC", "No alternative antidote exists; NAC must be given with appropriate precautions"],
    "acetaminophen-overdose");

  mk("A patient presents after accidentally ingesting a pod of concentrated laundry detergent. The patient is coughing and drooling. What specific complication should the nurse anticipate?",
    ["Aspiration pneumonitis from the surfactant causing direct chemical injury to lung tissue, with potential for rapid respiratory deterioration; laundry pod ingestion also risks esophageal burns and corneal injury from splashing", "Only mild GI upset", "No clinical effects from detergent ingestion", "Allergic reaction requiring epinephrine"],
    0, "Concentrated laundry detergent pods are significantly more toxic than traditional liquid detergent due to: higher concentration of surfactants, alkaline pH, and the pod membrane design that can burst and release concentrated product into the oropharynx. Complications include: (1) Aspiration pneumonitis: surfactants cause direct chemical injury to pulmonary epithelium; coughing and drooling suggest oropharyngeal exposure with aspiration risk; (2) Esophageal burns: alkaline pH causes liquefactive necrosis; (3) Corneal injury: if product splashes into eyes during biting/squeezing; (4) CNS depression: particularly in young children, cause unknown but well-documented; (5) Metabolic acidosis in severe cases. Management: no ipecac or activated charcoal (caustic substance); dilution with small amounts of water or milk; airway assessment and monitoring; chest X-ray if coughing or respiratory symptoms; ophthalmology consultation if ocular exposure; GI consultation if esophageal burns suspected. Several pediatric deaths have been attributed to laundry pod ingestion.", "Anticipate aspiration pneumonitis and esophageal burns from concentrated laundry pod ingestion, with aggressive airway monitoring and avoidance of emesis induction", "Toxicology Screening and Antidote Protocols", 3, "application",
    "Laundry pods are more toxic than regular detergent; aspiration of surfactant causes chemical pneumonitis; do NOT induce vomiting (caustic substance)",
    ["Higher concentration surfactants + alkaline pH", "Aspiration pneumonitis from surfactant pulmonary injury", "CNS depression in children from pods", "No ipecac or activated charcoal for caustic substances"],
    "Pediatric laundry pod ingestion deaths have occurred; these products are significantly more dangerous than traditional detergents",
    ["Laundry pod ingestion can be life-threatening, not just mild GI upset", "Concentrated pods have documented serious and fatal complications", "This is chemical injury, not an allergic reaction"],
    "toxicology-screening-antidotes");

  mk("A patient with confirmed coral snake envenomation shows no local wound changes. The nurse knows that coral snake venom has delayed effects. What type of venom does the coral snake produce?",
    ["Potent neurotoxin that blocks postsynaptic nicotinic acetylcholine receptors, causing delayed-onset descending paralysis that may not manifest for 6-12 hours after the bite; local wound effects are minimal", "Hemotoxin causing massive local swelling immediately", "Cytotoxin causing tissue necrosis at the bite site", "No clinically significant venom"],
    0, "Coral snake (Micrurus) envenomation is fundamentally different from pit viper (rattlesnake, copperhead, cottonmouth) envenomation: (1) Neurotoxic venom: blocks postsynaptic nicotinic acetylcholine receptors at the neuromuscular junction, causing paralysis; (2) Minimal local effects: unlike pit vipers, coral snake bites have minimal swelling, pain, or tissue destruction at the bite site - the absence of local effects does NOT indicate a 'dry bite'; (3) Delayed onset: neurotoxic effects may not appear for 6-12+ hours after the bite; once symptoms begin, they can progress rapidly to respiratory failure; (4) Descending paralysis: ptosis, diplopia, bulbar palsy, then respiratory muscle paralysis. Treatment: Coral snake antivenom (North American Coral Snake Antivenin from Pfizer); this is a horse serum-derived product. The key management principle is that antivenom should be administered for any confirmed coral snake bite WITHOUT waiting for symptoms, because neurotoxicity is difficult to reverse once established. Monitor for at least 24 hours.", "Administer coral snake antivenom for confirmed envenomation without waiting for symptoms, as neurotoxicity has delayed onset but rapid progression once established", "Toxicology Screening and Antidote Protocols", 4, "analysis",
    "Coral snake: neurotoxic (not hemotoxic); delayed onset 6-12h; minimal local effects; give antivenom BEFORE symptoms develop as reversal is difficult",
    ["Neurotoxin blocking postsynaptic nicotinic ACh receptors", "Minimal local wound effects - absence does NOT mean dry bite", "Delayed onset 6-12 hours; rapid progression once started", "Antivenom given prophylactically; do not wait for symptoms"],
    "Coral snake neurotoxicity can cause respiratory paralysis with rapid onset once symptoms begin; have intubation equipment ready and monitor for 24 hours minimum",
    ["Coral snake venom is neurotoxic, not hemotoxic like pit vipers", "Minimal tissue necrosis differentiates from pit viper bites", "Coral snake venom is clinically significant despite minimal local effects"],
    "toxicology-screening-antidotes");

  return q;
}
