/**
 * RN NCLEX master lesson map — canonical titles, tiers, word targets, deduplication.
 * Generated by `scripts/generate-rn-nclex-master-map.mjs` into `rn-nclex-master-map.json`.
 * Completeness audit vs checklist: `nclex-rn-source-checklist.json` + `scripts/audit-rn-nclex-map.mjs`.
 *
 * **Content:** Bodies are authored against your uploaded NCLEX source document; use the
 * exam-complete premium spine (`exam-complete-lesson-template.ts`) and **RN tier depth rules**
 * (`rn-nclex-content-depth-rules.ts`). Do not bulk-append thin placeholders to `catalog.json` —
 * merge in batches with full prose meeting tier word targets.
 */
import raw from "@/content/pathway-lessons/rn-nclex-master-map.json";
import type { RnNclexTier } from "@/lib/content-blueprint/rn-nclex-content-depth-rules";

export type { RnNclexTier } from "@/lib/content-blueprint/rn-nclex-content-depth-rules";

export type RnNclexMasterLesson = {
  id: string;
  canonicalTitle: string;
  slug: string;
  tier: RnNclexTier;
  wordTargetMin: number;
  wordTargetMax: number;
  primaryCategoryId: string;
  secondaryCategoryIds: string[];
  mergeNote: string | null;
  topicSlug: string;
  bodySystem: string;
};

export type RnNclexMasterMap = typeof raw;

export const RN_NCLEX_MASTER_MAP: RnNclexMasterMap = raw;

export const RN_NCLEX_BUILD_ORDER = raw.buildOrder as readonly string[];

export function rnNclexLessonsForCategory(categoryId: string): RnNclexMasterLesson[] {
  return (raw.lessons as RnNclexMasterLesson[]).filter(
    (l) => l.primaryCategoryId === categoryId || l.secondaryCategoryIds.includes(categoryId),
  );
}

export function rnNclexLessonsPrimaryCategory(categoryId: string): RnNclexMasterLesson[] {
  return (raw.lessons as RnNclexMasterLesson[]).filter((l) => l.primaryCategoryId === categoryId);
}

/** Titles with explicit merge / ownership notes (cross-category dedup). */
export function rnNclexMergeDecisions(): Array<{ title: string; note: string; primaryCategoryId: string }> {
  return (raw.lessons as RnNclexMasterLesson[])
    .filter((l) => l.mergeNote)
    .map((l) => ({
      title: l.canonicalTitle,
      note: l.mergeNote as string,
      primaryCategoryId: l.primaryCategoryId,
    }));
}
