/**
 * RN NCLEX master lesson map — canonical titles, tiers, word targets, deduplication.
 * Generated by `scripts/generate-rn-nclex-master-map.mjs` into `rn-nclex-master-map.json`.
 * Completeness audit vs checklist: `nclex-rn-source-checklist.json` + `scripts/audit-rn-nclex-map.mjs`.
 *
 * **Content:** Bodies are authored against the repo’s NCLEX-aligned sources (see
 * `docs/rn-nclex-rn-lesson-library.md`); use the exam-complete premium spine
 * (`exam-complete-lesson-template.ts`) and **RN tier depth rules** (`rn-nclex-content-depth-rules.ts`).
 * Do not bulk-append thin placeholders to `catalog.json` — merge in batches with full prose meeting tier word targets.
 */
import raw from "@/content/pathway-lessons/rn-nclex-master-map.json";
import type { RnNclexTier } from "@/lib/content-blueprint/rn-nclex-content-depth-rules";

export type { RnNclexTier } from "@/lib/content-blueprint/rn-nclex-content-depth-rules";

/** Planning filter — derived from primary category (see `rn-nclex-master-map.json` `sourceMap.archetypeDefinitions`). */
export type RnNclexLessonArchetype =
  | "condition_disease"
  | "medication_monograph"
  | "emergency_critical_care"
  | "nursing_priorities_safety";

export type RnNclexMasterLesson = {
  id: string;
  canonicalTitle: string;
  slug: string;
  tier: RnNclexTier;
  wordTargetMin: number;
  wordTargetMax: number;
  primaryCategoryId: string;
  secondaryCategoryIds: string[];
  mergeNote: string | null;
  archetype: RnNclexLessonArchetype;
  topicSlug: string;
  bodySystem: string;
};

export type RnNclexMasterMap = typeof raw;

export const RN_NCLEX_MASTER_MAP: RnNclexMasterMap = raw;

export const RN_NCLEX_BUILD_ORDER = raw.buildOrder as readonly string[];

export type RnNclexStagedBuildPhase = {
  phase: number;
  label: string;
  description: string;
  categoryIds: readonly string[];
};

export const RN_NCLEX_STAGED_BUILD_PHASES = raw.stagedBuildPhases as readonly RnNclexStagedBuildPhase[];

export function rnNclexLessonsForCategory(categoryId: string): RnNclexMasterLesson[] {
  return (raw.lessons as RnNclexMasterLesson[]).filter(
    (l) => l.primaryCategoryId === categoryId || l.secondaryCategoryIds.includes(categoryId),
  );
}

export function rnNclexLessonsPrimaryCategory(categoryId: string): RnNclexMasterLesson[] {
  return (raw.lessons as RnNclexMasterLesson[]).filter((l) => l.primaryCategoryId === categoryId);
}

/** Titles with explicit merge / ownership notes (cross-category dedup). */
export function rnNclexMergeDecisions(): Array<{ title: string; note: string; primaryCategoryId: string }> {
  return (raw.lessons as RnNclexMasterLesson[])
    .filter((l) => l.mergeNote)
    .map((l) => ({
      title: l.canonicalTitle,
      note: l.mergeNote as string,
      primaryCategoryId: l.primaryCategoryId,
    }));
}

export function rnNclexLessonsByArchetype(archetype: RnNclexLessonArchetype): RnNclexMasterLesson[] {
  return (raw.lessons as RnNclexMasterLesson[]).filter((l) => l.archetype === archetype);
}

/** Lessons that appear in more than one category bucket (secondary hub coverage; one canonical slug). */
export function rnNclexCrossListedLessons(): Array<{
  canonicalTitle: string;
  slug: string;
  primaryCategoryId: string;
  secondaryCategoryIds: string[];
  mergeNote: string | null;
}> {
  return (raw.lessons as RnNclexMasterLesson[])
    .filter((l) => l.secondaryCategoryIds.length > 0)
    .map((l) => ({
      canonicalTitle: l.canonicalTitle,
      slug: l.slug,
      primaryCategoryId: l.primaryCategoryId,
      secondaryCategoryIds: l.secondaryCategoryIds,
      mergeNote: l.mergeNote,
    }));
}
