/**
 * NCLEX-PN blueprint gap closure — question banks for 10 gap topics.
 * 25 questions per topic. Clinically accurate, exam-focused, monetization-ready.
 * Topics: Ethics, Client Education, DVT, Respiratory Failure, Oxygen Therapy,
 *         Diabetes, Hyperglycemia, Diuretics, Cardiac Medications, Medication Administration.
 */

export type PnGapQuestion = {
  id: string;
  topic: string;
  lessonSlug: string;
  exam: "NCLEX-PN";
  domain: string;
  blueprintCategory: string;
  difficulty: 1 | 2 | 3;
  questionType: "MCQ" | "SATA";
  stem: string;
  options: readonly string[];
  correct: readonly number[];
  rationale: string;
  whyCorrect: string;
  whyIncorrect: Record<string, string>;
  weakAreaTag: string;
  studyPlanMapping: string;
};

export const NCLEX_PN_GAP_QUESTIONS: readonly PnGapQuestion[] = [

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 1: ETHICS & PROFESSIONAL STANDARDS (25 questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-ethics-001",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 1,
  questionType: "MCQ",
  stem: "A patient with terminal cancer refuses further chemotherapy treatment. The patient's family insists that the PN encourage the patient to continue treatment. Which action by the PN is most appropriate?",
  options: [
    "Encourage the patient to consider the family's wishes since they know what is best",
    "Respect the patient's decision, document the refusal, and notify the provider",
    "Contact the ethics committee to override the patient's decision",
    "Tell the family the patient will continue treatment when they feel better",
  ],
  correct: [1],
  rationale: "A cognitively intact adult has the absolute right to refuse treatment under the ethical principle of autonomy. The PN's role is to support the patient's decision, not override it at family request. The refusal is documented, the provider notified, and the patient's wishes are upheld.",
  whyCorrect: "Option B correctly applies the principle of autonomy — a competent patient's informed refusal of treatment is legally and ethically binding.",
  whyIncorrect: {
    "A": "Encouraging a patient to override their own autonomous decision at family request violates the principle of autonomy and places the PN in a coercive role.",
    "C": "An ethics committee is consulted for complex ethical dilemmas — a competent patient's clear refusal is not a dilemma; it is their legal right.",
    "D": "Deceiving the family about the patient's intentions is dishonest and violates veracity. It also does not support the patient's autonomous decision.",
  },
  weakAreaTag: "patient-autonomy",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-002",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A PN discovers that a colleague administered a double dose of a scheduled medication to a patient in the morning. The patient's vital signs are currently stable. What is the PN's most appropriate first action?",
  options: [
    "Confront the colleague privately and advise them to document the correct dose",
    "Assess the patient and notify the charge nurse and provider",
    "Document your observation and report it at the end of the shift",
    "Wait and see if the patient develops symptoms before reporting",
  ],
  correct: [1],
  rationale: "Patient safety is the priority in medication errors. The PN first assesses the patient for adverse effects, then immediately notifies the charge nurse and provider regardless of apparent stability. Delayed reporting puts the patient at continued risk. The PN also completes an incident report.",
  whyCorrect: "Option B prioritizes patient assessment and escalation — both required immediately after discovering any medication error.",
  whyIncorrect: {
    "A": "Advising the colleague to document the incorrect dose is facilitating documentation fraud — a serious ethical and legal violation.",
    "C": "End-of-shift reporting of a known medication error delays necessary patient monitoring and is a breach of professional duty.",
    "D": "Waiting for symptoms before reporting a known double dose is negligent — the patient may have a narrow-window intervention period.",
  },
  weakAreaTag: "medication-error-response",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-003",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A PN is working in a long-term care facility and suspects that a resident is being financially exploited by a family member. The family member visits daily and the resident appears fearful when they are present. What is the PN's most appropriate action?",
  options: [
    "Confront the family member directly about the suspected exploitation",
    "Discuss the concern with other nursing staff to see if they have noticed the same thing",
    "Report the suspicion to the charge nurse and follow mandatory reporting protocols for elder abuse",
    "Wait until more definitive evidence is available before reporting",
  ],
  correct: [2],
  rationale: "PNs are mandated reporters. Any suspicion of elder abuse, neglect, or exploitation must be reported — the PN does not investigate, confront, or gather evidence independently. The report triggers a formal investigation by appropriate authorities. Waiting for definitive proof is not required and delays protection of a vulnerable adult.",
  whyCorrect: "Option C correctly follows mandatory reporting requirements — PNs report suspicion, not confirmed proof, to the charge nurse and to appropriate authorities.",
  whyIncorrect: {
    "A": "Directly confronting the suspected abuser can escalate danger for the resident and is outside the PN's role.",
    "B": "Informal staff discussion does not fulfill the mandatory reporting obligation and delays the formal process.",
    "D": "Mandatory reporting laws do not require certainty — suspicion is sufficient and legally obligatory to report.",
  },
  weakAreaTag: "mandatory-reporting",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-004",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 1,
  questionType: "MCQ",
  stem: "A patient's adult daughter calls the nursing unit and asks for an update on her mother's condition. The patient is alert, oriented, and has not authorized sharing information with family. What is the PN's best response?",
  options: [
    "Provide a brief summary since the caller is the patient's daughter",
    "Ask for the daughter's date of birth to verify her identity before sharing information",
    "Explain that patient information is confidential and cannot be shared without the patient's authorization",
    "Transfer the call to the charge nurse who has authority to share family information",
  ],
  correct: [2],
  rationale: "HIPAA protects patient health information regardless of family relationship. An alert, competent patient's information cannot be shared with family members without documented patient authorization. This applies even to spouses, adult children, and parents of adult patients.",
  whyCorrect: "Option C correctly applies HIPAA confidentiality principles — the PN declines to share information without verifiable patient authorization.",
  whyIncorrect: {
    "A": "Family relationship does not confer automatic right to patient information under HIPAA for a competent adult patient.",
    "B": "Verifying the caller's identity does not grant them access to information — they still need patient authorization.",
    "D": "The charge nurse has no more authority than the PN to share confidential information without patient authorization.",
  },
  weakAreaTag: "hipaa-confidentiality",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-005",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 3,
  questionType: "SATA",
  stem: "A PN witnesses a colleague nurse post a story on a personal social media account about a 'difficult patient' from work. Although no name is used, the post includes the patient's age, diagnosis, and unusual presentation. Which statements about this situation are correct? Select all that apply.",
  options: [
    "This is a HIPAA violation even without the patient's name because identifying details are present",
    "The PN should report this behavior to the charge nurse or facility compliance officer",
    "Since no name was used, no violation occurred and no action is needed",
    "The post could result in disciplinary action including loss of nursing license",
    "The PN should confront the colleague before deciding whether to report",
  ],
  correct: [0, 1, 3],
  rationale: "HIPAA violations can occur even without a patient's name when enough identifying details (age, diagnosis, unusual presentation, geographic details) allow the patient to be identified. The PN is professionally obligated to report HIPAA violations. Consequences include facility discipline, board of nursing action, and potential federal fines.",
  whyCorrect: "Options A, B, and D are all correct: the post violates HIPAA regardless of the name omission; the PN must report it; and consequences can include license action.",
  whyIncorrect: {
    "C": "Incorrect — HIPAA protects against sharing identifiable health information; sufficient identifying details without a name still constitute a violation.",
    "E": "The PN's obligation is to report to the appropriate authority, not to self-investigate by confronting the colleague first.",
  },
  weakAreaTag: "social-media-hipaa",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-006",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A provider gives a verbal order for 'morphine 4 mg IV now' over the phone. What is the PN's required action before administering?",
  options: [
    "Administer the morphine immediately since it is a verbal order from a physician",
    "Ask the provider to come to the unit and write the order before it is administered",
    "Repeat the order back completely to the provider and receive verbal confirmation before documenting and administering",
    "Have the charge nurse verify the order by listening on a second phone line",
  ],
  correct: [2],
  rationale: "Verbal medication orders require a full read-back verification — the PN repeats the complete order (drug, dose, route, frequency) back to the prescriber and receives confirmation before documenting and administering. This reduces transcription errors that are common with verbal orders.",
  whyCorrect: "Option C describes the required read-back process for verbal orders — essential patient safety practice.",
  whyIncorrect: {
    "A": "Administering without read-back verification risks errors from mishearing or misunderstanding the order.",
    "B": "Requiring written orders before emergency verbal orders delays time-sensitive care unnecessarily.",
    "D": "Charge nurse verification on a second line is not the standard verbal order process — the PN's own read-back is the required step.",
  },
  weakAreaTag: "verbal-orders-verification",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-007",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 2,
  questionType: "MCQ",
  stem: "Before a bronchoscopy procedure, the PN witnesses the patient sign the consent form. As the PN leaves the room, the patient says, 'I hope I made the right decision — the doctor talked so fast, I'm not sure I understood everything.' What is the PN's most appropriate action?",
  options: [
    "Reassure the patient that the procedure is routine and proceed as planned",
    "Stop and explain the bronchoscopy procedure to the patient since the PN is familiar with it",
    "Return to the patient, notify the provider of the patient's concern, and hold the procedure pending re-education",
    "Document that the patient signed the form and proceed with the pre-procedure preparation",
  ],
  correct: [2],
  rationale: "Informed consent requires that the patient understands what they consented to. A patient expressing uncertainty about whether they understood constitutes potentially uninformed consent. The PN's role is to hold the procedure and notify the provider to re-address the patient's concerns — obtaining informed consent is the provider's responsibility, not the PN's.",
  whyCorrect: "Option C correctly identifies that the PN must halt the procedure and escalate to the provider when a patient questions their understanding of the consent.",
  whyIncorrect: {
    "A": "Reassuring the patient without addressing their knowledge gap does not resolve the informed consent problem.",
    "B": "The PN cannot provide the educational content needed to ensure informed consent — this is the provider's scope.",
    "D": "Proceeding to pre-procedure prep with a patient who has expressed doubt about their understanding violates the informed consent principle.",
  },
  weakAreaTag: "informed-consent",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-008",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 3,
  questionType: "MCQ",
  stem: "A 16-year-old patient is admitted and is an emancipated minor. The patient's parents are present and request to be informed of all medical decisions. The patient does not want the parents involved. What does the PN understand about this situation?",
  options: [
    "The parents have legal rights over the child's care since the patient is under 18",
    "The emancipated minor has full adult legal rights regarding their healthcare decisions and confidentiality",
    "The PN should contact the ethics committee to determine who has authority",
    "Medical information can be shared with parents only for major procedures",
  ],
  correct: [1],
  rationale: "An emancipated minor has been legally recognized as having adult rights and responsibilities, including full autonomy over healthcare decisions. The PN must respect the emancipated minor's right to make their own medical decisions and maintain confidentiality from parents, just as with any adult patient.",
  whyCorrect: "Option B correctly identifies that emancipated minor status grants full healthcare autonomy equivalent to adult rights.",
  whyIncorrect: {
    "A": "Parental authority over healthcare ends when a minor is legally emancipated — age alone does not determine legal decision-making capacity.",
    "C": "This is not an ambiguous ethical dilemma requiring committee review — the legal status of emancipated minor is clear.",
    "D": "Sharing medical information without consent, regardless of procedure type, violates the emancipated minor's HIPAA rights.",
  },
  weakAreaTag: "minor-emancipated-rights",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-009",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 1,
  questionType: "MCQ",
  stem: "A PN makes a documentation error and writes the wrong blood pressure value in the patient's chart. What is the correct way to correct this error?",
  options: [
    "Use correction fluid (white-out) to cover the error and write the correct value",
    "Completely scribble out the error so it is illegible and write the correct value above it",
    "Draw a single line through the error, write 'error,' add initials and date, then write the correct value",
    "Delete the entry from the electronic medical record and re-enter the correct value",
  ],
  correct: [2],
  rationale: "Medical documentation error correction requires a single line through the error (keeping it legible), labeling it as 'error' with your initials and date, then writing the correct information. This maintains the legal integrity of the medical record. White-out and illegible corrections obscure the original entry, which is prohibited in medical records.",
  whyCorrect: "Option C describes the legally and professionally accepted method for correcting handwritten medical record errors.",
  whyIncorrect: {
    "A": "White-out is never acceptable in medical records — it destroys the original entry and suggests concealment.",
    "B": "Making the error illegible is equivalent to destruction of the original record — prohibited.",
    "D": "Electronic records have audit trails — deleting entries is fraudulent record alteration detectable in the system audit log.",
  },
  weakAreaTag: "documentation-standards",
  studyPlanMapping: "ethics-professional-standards",
},
{
  id: "pn-ethics-010",
  topic: "Ethics & Professional Standards",
  lessonSlug: "us-pn-ethics-professional-standards",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Coordinated Care",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A PN is asked by the supervising RN to perform an intravenous push chemotherapy administration. The PN has not received training for this procedure. What should the PN do?",
  options: [
    "Perform the task since a licensed nurse requested it",
    "Refuse the task and explain that IV push chemotherapy administration is outside the PN's current competency",
    "Ask another PN who seems more experienced to perform the task",
    "Perform the task with the RN supervising each step to ensure safety",
  ],
  correct: [1],
  rationale: "The PN must only perform tasks within their competency and training. Performing a task one is not trained or competent to perform, regardless of who requested it, violates the Nurse Practice Act and endangers the patient. Chemotherapy is a high-alert medication with significant toxicity risk. Refusal with a clear explanation is the appropriate professional response.",
  whyCorrect: "Option B correctly applies the principle of competence — refusing tasks beyond one's competency protects the patient and maintains professional integrity.",
  whyIncorrect: {
    "A": "A licensed nurse's request does not authorize the PN to perform procedures outside their training — scope of practice is determined by the NPA, not by delegation alone.",
    "C": "Asking another PN to perform a task neither is trained for does not resolve the competency issue.",
    "D": "Performing a task without training — even with RN oversight — still represents an unsafe act; the RN's presence does not substitute for the PN's own competency.",
  },
  weakAreaTag: "scope-of-practice",
  studyPlanMapping: "ethics-professional-standards",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 2: DVT (15 additional questions — 20 total with preTest)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-dvt-006",
  topic: "Deep Vein Thrombosis",
  lessonSlug: "us-pn-dvt-deep-vein-thrombosis",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient is prescribed sequential compression devices (SCDs) for DVT prophylaxis after abdominal surgery. When should the PN remove the SCDs?",
  options: [
    "When the patient needs to ambulate and during hygiene care only",
    "Whenever the patient is in pain to promote comfort",
    "Every 4 hours for 30-minute breaks to allow for skin inspection",
    "Only when the patient specifically asks for them to be removed",
  ],
  correct: [0],
  rationale: "SCDs should remain on the patient whenever they are in bed to maximize DVT prophylaxis effectiveness. They are removed only when the patient ambulates (the activity itself prevents DVT) and during hygiene care when necessary. Removing them for pain relief or scheduled breaks reduces their protective benefit.",
  whyCorrect: "Option A correctly identifies ambulation and hygiene as the appropriate times for SCD removal — otherwise they remain in place continuously.",
  whyIncorrect: {
    "B": "Pain is not an indication to remove SCDs; removing them reduces DVT prevention during a high-risk period.",
    "C": "Scheduled removal for breaks is not evidence-based; SCDs should be on continuously while the patient is in bed.",
    "D": "Patient preference alone does not override clinical indication for DVT prophylaxis — education is needed, not removal on request without discussion.",
  },
  weakAreaTag: "dvt-prophylaxis-scds",
  studyPlanMapping: "dvt-deep-vein-thrombosis",
},
{
  id: "pn-dvt-007",
  topic: "Deep Vein Thrombosis",
  lessonSlug: "us-pn-dvt-deep-vein-thrombosis",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 1,
  questionType: "MCQ",
  stem: "A patient with a confirmed DVT in the left leg is prescribed therapeutic anticoagulation. Which activity order does the PN anticipate?",
  options: [
    "Strict bedrest with the left leg immobilized to prevent PE",
    "Ambulation as tolerated with the anticoagulation in place",
    "Left leg elevation and no ambulation for 48 hours",
    "Bed rest until the anticoagulation reaches therapeutic levels",
  ],
  correct: [1],
  rationale: "Ambulation is NOT contraindicated in patients with DVT on therapeutic anticoagulation. Current evidence does not support mandatory bed rest for DVT — early ambulation with anticoagulation is safe and may help reduce post-thrombotic syndrome. Prolonged bed rest worsens venous stasis and increases DVT propagation risk.",
  whyCorrect: "Option B reflects current evidence-based practice: ambulation is encouraged with therapeutic anticoagulation for DVT.",
  whyIncorrect: {
    "A": "Strict bed rest is outdated practice for DVT management and increases venous stasis.",
    "C": "48-hour immobilization has no evidence basis and worsens the condition being treated.",
    "D": "Waiting for therapeutic anticoagulation levels before ambulating is not required — ambulation can begin immediately.",
  },
  weakAreaTag: "dvt-ambulation",
  studyPlanMapping: "dvt-deep-vein-thrombosis",
},
{
  id: "pn-dvt-008",
  topic: "Deep Vein Thrombosis",
  lessonSlug: "us-pn-dvt-deep-vein-thrombosis",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient on warfarin for DVT treatment has an INR of 1.4. The target range is 2.0–3.0. Which action is most appropriate?",
  options: [
    "Administer a higher dose of warfarin at the nurse's discretion",
    "Document the INR value and notify the provider for dose adjustment",
    "Hold the warfarin since the INR is below therapeutic range",
    "Continue the current dose and recheck the INR in one week",
  ],
  correct: [1],
  rationale: "An INR of 1.4 is below the therapeutic range of 2.0–3.0 for DVT treatment, meaning the patient is insufficiently anticoagulated and at risk for clot propagation. The PN documents the result and notifies the provider for a dose adjustment order. The PN does not independently adjust warfarin doses.",
  whyCorrect: "Option B is correct — the PN's role is to report sub-therapeutic INR values to the provider for dose adjustment.",
  whyIncorrect: {
    "A": "Independently adjusting warfarin dosing is outside PN scope — dose changes require a provider order.",
    "C": "Holding warfarin when the INR is sub-therapeutic removes the only protection the patient has against clot propagation.",
    "D": "Waiting one week with a sub-therapeutic INR leaves the patient at significant risk for DVT extension and PE.",
  },
  weakAreaTag: "warfarin-inr-monitoring",
  studyPlanMapping: "dvt-deep-vein-thrombosis",
},
{
  id: "pn-dvt-009",
  topic: "Deep Vein Thrombosis",
  lessonSlug: "us-pn-dvt-deep-vein-thrombosis",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 3,
  questionType: "SATA",
  stem: "A patient hospitalized with DVT develops sudden onset chest pain that worsens with inspiration, dyspnea, and an oxygen saturation of 88%. Which nursing actions are appropriate at this time? Select all that apply.",
  options: [
    "Stay with the patient and call for immediate assistance",
    "Apply supplemental oxygen via non-rebreather mask",
    "Place the patient in high Fowler's position",
    "Massage the affected leg to improve venous return",
    "Notify the provider and prepare for emergency assessment",
  ],
  correct: [0, 1, 2, 4],
  rationale: "The patient's presentation is consistent with pulmonary embolism — a life-threatening emergency requiring immediate response. The PN stays with the patient, applies O2, positions for comfort and maximal respiratory mechanics, and calls for help/notifies the provider. Leg massage is absolutely contraindicated — it can dislodge additional thrombus.",
  whyCorrect: "Options A, B, C, and E all address the emergency systematically: maintain patient safety, maximize oxygenation, and escalate.",
  whyIncorrect: {
    "D": "Massaging the leg with DVT is always contraindicated — it can cause dislodgment of thrombus and worsen or cause PE.",
  },
  weakAreaTag: "pulmonary-embolism-response",
  studyPlanMapping: "dvt-deep-vein-thrombosis",
},
{
  id: "pn-dvt-010",
  topic: "Deep Vein Thrombosis",
  lessonSlug: "us-pn-dvt-deep-vein-thrombosis",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient on heparin infusion for DVT has a platelet count that dropped from 280,000 to 90,000 over the past 7 days. The PN suspects heparin-induced thrombocytopenia (HIT). Which immediate action is priority?",
  options: [
    "Administer a platelet transfusion to bring the count above 150,000",
    "Reduce the heparin infusion rate by 50% and recheck platelets in 4 hours",
    "Hold all heparin products and notify the provider immediately",
    "Increase the heparin rate since low platelets indicate inadequate anticoagulation",
  ],
  correct: [2],
  rationale: "HIT is diagnosed when platelet count drops >50% between days 5–14 of heparin therapy. All heparin products (including flushes and heparin-coated catheters) must be discontinued immediately. HIT paradoxically increases thrombosis risk. The provider must be notified to transition to a non-heparin anticoagulant. Platelet transfusions are contraindicated in HIT as they can worsen clotting.",
  whyCorrect: "Option C correctly identifies stopping all heparin products immediately as the priority action in suspected HIT.",
  whyIncorrect: {
    "A": "Platelet transfusions are contraindicated in HIT — they worsen the thrombotic state.",
    "B": "Reducing (not stopping) heparin still exposes the patient to heparin and continues to drive the HIT immune response.",
    "D": "Increasing heparin in HIT is dangerous — HIT causes thrombocytopenia through an immune mechanism, not anticoagulation failure.",
  },
  weakAreaTag: "hit-heparin-induced-thrombocytopenia",
  studyPlanMapping: "dvt-deep-vein-thrombosis",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 3: DIURETICS (10 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-diuretics-006",
  topic: "Diuretics",
  lessonSlug: "us-pn-diuretics-pharmacology",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient taking hydrochlorothiazide (HCTZ) 25 mg daily for hypertension reports joint pain and swelling in the right big toe that began 2 days ago. The patient's serum uric acid is 9.2 mg/dL. What is the most likely explanation?",
  options: [
    "The HCTZ is causing hypokalemia, which has led to joint inflammation",
    "Thiazide diuretics decrease uric acid excretion, causing hyperuricemia and precipitating gout",
    "The patient is not taking the HCTZ correctly, causing fluid retention in the joint",
    "This is an allergic reaction to the sulfa component of HCTZ",
  ],
  correct: [1],
  rationale: "Thiazide diuretics reduce uric acid excretion in the renal tubules, causing hyperuricemia (elevated serum uric acid). In genetically predisposed individuals, this precipitates gout — urate crystal deposition in joints. The big toe (podagra) is the most common site. The elevated uric acid of 9.2 mg/dL (normal <6.0 for women, <7.0 for men) confirms hyperuricemia.",
  whyCorrect: "Option B correctly identifies hyperuricemia from impaired uric acid excretion as the thiazide mechanism leading to gout.",
  whyIncorrect: {
    "A": "Hypokalemia causes muscle weakness and cardiac effects, not joint inflammation.",
    "C": "Non-compliance causes recurrent hypertension, not joint swelling.",
    "D": "Sulfa allergy presents as rash or anaphylaxis, not isolated joint pain with elevated uric acid.",
  },
  weakAreaTag: "thiazide-hyperuricemia-gout",
  studyPlanMapping: "diuretics",
},
{
  id: "pn-diuretics-007",
  topic: "Diuretics",
  lessonSlug: "us-pn-diuretics-pharmacology",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 1,
  questionType: "MCQ",
  stem: "The PN is about to administer furosemide 40 mg PO to a patient with heart failure. The patient's morning weight shows a 1 kg increase from yesterday. Which finding is most important to assess before administering the furosemide?",
  options: [
    "The patient's current apical heart rate",
    "The patient's most recent serum potassium level",
    "The patient's respiratory rate and oxygen saturation",
    "Whether the patient has had breakfast yet",
  ],
  correct: [1],
  rationale: "Furosemide causes significant potassium loss. Before administering a loop diuretic, the PN must verify the current serum potassium. If K+ <3.0 mEq/L, the diuretic should be held and the provider notified for potassium replacement — further K+ loss increases the risk of dangerous cardiac arrhythmias, especially if the patient is on digoxin.",
  whyCorrect: "Option B identifies potassium monitoring as the critical pre-administration check for loop diuretics, given the significant K+ wasting effect.",
  whyIncorrect: {
    "A": "Heart rate is important for cardiac assessment but is not the specific pre-furosemide check — potassium is the priority.",
    "C": "Respiratory assessment is important for HF monitoring but is not the drug-specific safety check for furosemide.",
    "D": "Furosemide can be given regardless of meal timing — it is not dependent on food intake.",
  },
  weakAreaTag: "furosemide-potassium-monitoring",
  studyPlanMapping: "diuretics",
},
{
  id: "pn-diuretics-008",
  topic: "Diuretics",
  lessonSlug: "us-pn-diuretics-pharmacology",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 3,
  questionType: "SATA",
  stem: "A patient on furosemide 80 mg IV twice daily develops muscle weakness, constipation, and has an irregular heart rate on telemetry monitoring. Which electrolyte imbalances are consistent with this presentation? Select all that apply.",
  options: [
    "Hypokalemia",
    "Hypomagnesemia",
    "Hyperkalemia",
    "Hypocalcemia",
    "Hypernatremia",
  ],
  correct: [0, 1, 3],
  rationale: "Loop diuretics cause loss of sodium, potassium, magnesium, and calcium. Hypokalemia causes muscle weakness, constipation, and cardiac arrhythmias. Hypomagnesemia often accompanies hypokalemia and contributes to arrhythmias. Loop diuretics increase calcium excretion (unlike thiazides which retain calcium), potentially causing hypocalcemia.",
  whyCorrect: "Options A, B, and D represent the classic electrolyte losses associated with loop diuretics: K+, Mg2+, and Ca2+.",
  whyIncorrect: {
    "C": "Hyperkalemia is associated with potassium-sparing diuretics (spironolactone), not loop diuretics.",
    "E": "Hypernatremia is not a typical effect of loop diuretics — they cause natriuresis (sodium loss), which can lead to hyponatremia with volume depletion.",
  },
  weakAreaTag: "loop-diuretic-electrolytes",
  studyPlanMapping: "diuretics",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 4: CARDIAC MEDICATIONS (10 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-cardiac-med-006",
  topic: "Cardiac Medications",
  lessonSlug: "us-pn-cardiac-medications",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient taking digoxin 0.125 mg daily has a serum digoxin level of 2.6 ng/mL (therapeutic range: 0.5–2.0 ng/mL). The patient's serum potassium is 3.2 mEq/L. Which ECG finding would the PN most likely expect to see?",
  options: [
    "Peaked T waves and widened QRS complex",
    "ST elevation in multiple leads",
    "AV block with bradycardia and ventricular ectopy",
    "Shortened QT interval with tall, narrow T waves",
  ],
  correct: [2],
  rationale: "Digoxin toxicity (level >2.0 ng/mL) combined with hypokalemia (K+ 3.2 mEq/L) creates a high risk for cardiac conduction abnormalities. Classic ECG findings include AV block (prolonged PR interval, second or third degree block), bradycardia, and ventricular ectopy (PVCs, bigeminy, ventricular tachycardia). Hypokalemia sensitizes the myocardium to digoxin's toxic effects.",
  whyCorrect: "Option C describes the classic cardiac effects of digoxin toxicity: AV conduction disturbances, bradycardia, and ventricular dysrhythmias.",
  whyIncorrect: {
    "A": "Peaked T waves and widened QRS are classic findings in hyperkalemia, not digoxin toxicity.",
    "B": "ST elevation suggests myocardial ischemia or injury — not the primary ECG finding in digoxin toxicity.",
    "D": "Shortened QT and tall T waves are not characteristic of digoxin toxicity. Digoxin causes ST depression (scooped) as a therapeutic effect.",
  },
  weakAreaTag: "digoxin-toxicity-ecg",
  studyPlanMapping: "cardiac-medications",
},
{
  id: "pn-cardiac-med-007",
  topic: "Cardiac Medications",
  lessonSlug: "us-pn-cardiac-medications",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 3,
  questionType: "SATA",
  stem: "A patient with heart failure and atrial fibrillation is taking metoprolol 25 mg PO twice daily. Which assessments are priorities before administering this medication? Select all that apply.",
  options: [
    "Apical heart rate for 60 seconds",
    "Blood pressure",
    "Serum digoxin level",
    "Respiratory assessment for wheezing",
    "Blood glucose (for diabetic patients)",
  ],
  correct: [0, 1, 3, 4],
  rationale: "Before metoprolol administration: (1) Apical pulse — hold if <60; (2) Blood pressure — hold if SBP <90; (3) Respiratory assessment — metoprolol is cardioselective but can still cause bronchoconstriction in susceptible patients with asthma/COPD; (4) Blood glucose in diabetics — metoprolol masks tachycardia (a key hypoglycemia warning sign). Digoxin level is not a routine pre-metoprolol check.",
  whyCorrect: "Options A, B, D, and E are the correct pre-metoprolol assessments based on the drug's mechanism and adverse effect profile.",
  whyIncorrect: {
    "C": "Digoxin level is monitored for digoxin therapy, not as a routine pre-metoprolol assessment. These are separate drugs with separate monitoring.",
  },
  weakAreaTag: "beta-blocker-pre-administration",
  studyPlanMapping: "cardiac-medications",
},
{
  id: "pn-cardiac-med-008",
  topic: "Cardiac Medications",
  lessonSlug: "us-pn-cardiac-medications",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient on amlodipine 10 mg daily for hypertension develops 2+ pitting edema in bilateral ankles after 4 weeks of therapy. Blood pressure is 126/78 mmHg. The patient is concerned and asks if they should stop the medication. Which response is most appropriate?",
  options: [
    "Agree with the patient — ankle edema means the medication is not working and should be stopped",
    "Explain that ankle swelling is a known side effect of amlodipine caused by vasodilation, not fluid overload, and the provider should be notified for evaluation",
    "Administer the PRN furosemide to treat the edema and reassure the patient the medication is working",
    "Advise the patient to reduce fluid intake to manage the ankle swelling",
  ],
  correct: [1],
  rationale: "Peripheral edema is a known and expected side effect of dihydropyridine CCBs (amlodipine, nifedipine) resulting from arterial vasodilation causing fluid shift into interstitial tissue — not cardiac fluid overload. It does not indicate medication failure. However, the provider should be informed for evaluation and documentation. Furosemide has limited effectiveness for vasodilatory edema. Fluid restriction is unnecessary and inappropriate.",
  whyCorrect: "Option B correctly identifies the mechanism, distinguishes from HF edema, and appropriately escalates to the provider.",
  whyIncorrect: {
    "A": "Ankle edema from amlodipine is an adverse effect, not a sign of ineffectiveness — blood pressure is well-controlled.",
    "C": "Furosemide treats volume overload, not vasodilatory edema from CCBs — its benefit is limited here and requires a provider order.",
    "D": "Fluid restriction is inappropriate — this edema is not from excess fluid intake but from vasodilatation.",
  },
  weakAreaTag: "amlodipine-peripheral-edema",
  studyPlanMapping: "cardiac-medications",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 5: MEDICATION ADMINISTRATION (10 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-med-admin-006",
  topic: "Medication Administration",
  lessonSlug: "us-pn-medication-administration-six-rights",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Safety and Infection Control",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient asks the PN why they need to show an ID band every time they receive a medication. Which explanation is most accurate?",
  options: [
    "It is a hospital policy to keep track of which nurses are caring for which patients",
    "Using two patient identifiers before each medication prevents wrong-patient administration errors",
    "The ID band contains the medication order information that the PN must verify",
    "The ID band scan automatically administers the medication through the IV line",
  ],
  correct: [1],
  rationale: "Two-patient identifier verification (name + date of birth, or name + MRN) before every medication administration is a primary patient safety strategy to prevent wrong-patient errors. Wrong-patient medication errors are a significant source of preventable harm in healthcare settings.",
  whyCorrect: "Option B accurately explains the safety purpose of the two-identifier requirement.",
  whyIncorrect: {
    "A": "Staff tracking is not the purpose of patient identification — patient safety is.",
    "C": "The ID band contains patient identifiers, not medication order information.",
    "D": "ID band scanning is part of barcode medication administration (BCMA) but does not automatically administer medications.",
  },
  weakAreaTag: "two-patient-identifiers",
  studyPlanMapping: "medication-administration",
},
{
  id: "pn-med-admin-007",
  topic: "Medication Administration",
  lessonSlug: "us-pn-medication-administration-six-rights",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Safety and Infection Control",
  difficulty: 3,
  questionType: "SATA",
  stem: "A PN is preparing to give scheduled medications. Which situations require the PN to hold the medication and notify the provider before administering? Select all that apply.",
  options: [
    "The patient's apical pulse is 52 bpm before the scheduled metoprolol dose",
    "The patient's blood glucose is 68 mg/dL before the scheduled insulin lispro dose",
    "The patient's potassium is 2.9 mEq/L before the scheduled furosemide dose",
    "The patient's blood pressure is 132/84 before the scheduled lisinopril dose",
    "The patient states a new allergy to penicillin before the scheduled amoxicillin dose",
  ],
  correct: [0, 1, 2, 4],
  rationale: "Hold parameters and safety checks: (A) Metoprolol hold parameter is typically HR <60 — apical pulse 52 warrants holding; (B) Hypoglycemia (<70 mg/dL) requires treating the hypoglycemia before any insulin; (C) K+ 2.9 mEq/L before furosemide (which causes further K+ loss) requires holding and provider notification; (E) A stated allergy to amoxicillin (penicillin class) is a contraindication — hold and notify before administering. The blood pressure of 132/84 is within a range where lisinopril would not typically be held.",
  whyCorrect: "Options A, B, C, and E all represent situations where administering the scheduled medication without provider input would create patient harm.",
  whyIncorrect: {
    "D": "A blood pressure of 132/84 mmHg is not below the typical hold parameter for ACE inhibitors. Lisinopril would generally be held for SBP <90–100 mmHg; 132/84 is elevated, indicating the medication is needed.",
  },
  weakAreaTag: "medication-hold-parameters",
  studyPlanMapping: "medication-administration",
},
{
  id: "pn-med-admin-008",
  topic: "Medication Administration",
  lessonSlug: "us-pn-medication-administration-six-rights",
  exam: "NCLEX-PN",
  domain: "Safe and Effective Care Environment",
  blueprintCategory: "Safety and Infection Control",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient is prescribed nitroglycerin 0.4 mg sublingual PRN for angina. The patient asks why the nurse always checks for the pill burning under the tongue. What is the correct explanation?",
  options: [
    "Burning indicates the patient is having an allergic reaction and the drug should be removed",
    "Burning sensation under the tongue confirms that the nitroglycerin tablet is fresh and potent",
    "The burning means the medication is being absorbed directly into the bloodstream",
    "Burning means the tablet has dissolved and the patient can now swallow it"
  ],
  correct: [1],
  rationale: "Sublingual nitroglycerin causes a burning or tingling sensation under the tongue when it is potent and active. If there is no burning sensation, the tablet may have lost potency — often from improper storage (heat, light, or moisture degrade nitroglycerin). The absence of burning with a SL nitroglycerin tablet is a sign of degraded medication.",
  whyCorrect: "Option B correctly explains the clinical significance of the burning sensation as a marker of nitroglycerin potency.",
  whyIncorrect: {
    "A": "Burning is expected and desired — it is not an allergic response.",
    "C": "While sublingual absorption does enter the bloodstream, the burning sensation specifically indicates potency, not just absorption.",
    "D": "Sublingual tablets dissolve under the tongue — swallowing them reduces effectiveness through first-pass hepatic metabolism.",
  },
  weakAreaTag: "sublingual-nitroglycerin-administration",
  studyPlanMapping: "medication-administration",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 6: OXYGEN THERAPY (8 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-o2-006",
  topic: "Oxygen Therapy",
  lessonSlug: "us-pn-oxygen-therapy-fundamentals",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 1,
  questionType: "MCQ",
  stem: "A patient's family member lights a candle in the hospital room where the patient is receiving oxygen via nasal cannula at 2 L/min. What is the PN's immediate action?",
  options: [
    "Allow the candle since the oxygen flow rate is too low to present a fire risk",
    "Extinguish the candle immediately and educate the family about oxygen fire safety",
    "Lower the oxygen flow rate to 1 L/min before allowing the candle",
    "Ask the charge nurse for guidance before taking action",
  ],
  correct: [1],
  rationale: "Oxygen is flammable and supports combustion at any flow rate. Open flames — including candles — are absolutely prohibited in any environment where supplemental oxygen is in use, regardless of the flow rate. The PN must immediately extinguish the candle and educate the family. This is a direct patient safety emergency.",
  whyCorrect: "Option B is correct — immediate elimination of the fire hazard is the priority action; education follows.",
  whyIncorrect: {
    "A": "There is no 'safe' flow rate for an open flame near oxygen — even small amounts of oxygen accelerate combustion significantly.",
    "C": "Reducing flow rate does not make open flames safe around oxygen.",
    "D": "This is a direct patient safety emergency requiring immediate PN action — no need to consult the charge nurse before extinguishing a candle.",
  },
  weakAreaTag: "oxygen-fire-safety",
  studyPlanMapping: "oxygen-therapy",
},
{
  id: "pn-o2-007",
  topic: "Oxygen Therapy",
  lessonSlug: "us-pn-oxygen-therapy-fundamentals",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient who is normally alert and oriented is now mildly confused and restless. Oxygen saturation is 93% on room air. What is the PN's priority interpretation of this finding?",
  options: [
    "The patient is experiencing medication side effects — review the medication list",
    "Confusion and restlessness are consistent with hypoxia — apply supplemental oxygen and notify the provider",
    "These are signs of worsening dementia — document the change and continue monitoring",
    "The patient is likely anxious — offer reassurance and monitor for 30 minutes"
  ],
  correct: [1],
  rationale: "New onset confusion and restlessness in a patient who is normally alert, combined with an SpO2 of 93% (below the normal 95–100%), should be interpreted as hypoxia until proven otherwise. Hypoxia commonly presents with agitation and altered mental status before more classic respiratory signs appear. The PN applies supplemental oxygen and notifies the provider urgently.",
  whyCorrect: "Option B applies the clinical rule: agitation + hypoxia = hypoxemia problem, requiring immediate oxygen and provider notification.",
  whyIncorrect: {
    "A": "Medication review may be warranted eventually, but the 93% SpO2 combined with altered mental status requires immediate oxygen intervention first.",
    "C": "Attributing acute change to dementia without ruling out hypoxia misses a treatable cause — dementia does not typically cause acute-onset confusion in isolation.",
    "D": "SpO2 of 93% warrants action, not 30 minutes of monitoring. Delay could allow further deterioration.",
  },
  weakAreaTag: "hypoxia-mental-status-change",
  studyPlanMapping: "oxygen-therapy",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 7: RESPIRATORY FAILURE (7 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-resp-failure-006",
  topic: "Respiratory Failure",
  lessonSlug: "us-pn-respiratory-failure",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient with COPD on 2L nasal cannula oxygen has a blood gas result showing pH 7.29, PaCO2 68 mmHg, PaO2 56 mmHg, HCO3 30 mEq/L. How should the PN interpret this result?",
  options: [
    "Compensated metabolic alkalosis — the bicarbonate is elevated",
    "Acute respiratory acidosis without compensation — the pH is low due to elevated CO2",
    "Partially compensated respiratory acidosis — the pH is below normal with elevated CO2 and elevated bicarb showing renal compensation",
    "Normal arterial blood gas result for a COPD patient on supplemental oxygen",
  ],
  correct: [2],
  rationale: "pH 7.29 (acidosis), PaCO2 68 (elevated — respiratory cause of acidosis), HCO3 30 (elevated — renal compensation, kidneys retained bicarb to buffer the acidosis). The low pH (7.29 below normal 7.35–7.45) indicates incomplete compensation — partially compensated respiratory acidosis. PaO2 56 mmHg confirms hypoxemia meeting Type 2 respiratory failure criteria.",
  whyCorrect: "Option C correctly identifies partially compensated respiratory acidosis: pH low (still acidotic), CO2 high (driving the acidosis), HCO3 high (compensatory renal response).",
  whyIncorrect: {
    "A": "Metabolic alkalosis would show a high pH with high HCO3 — this patient has a low pH (acidosis), not alkalosis.",
    "B": "Fully uncompensated acute respiratory acidosis would show normal or low bicarb — the elevated HCO3 of 30 shows renal compensation has begun.",
    "D": "A pH of 7.29 and PaCO2 of 68 are not normal — even for COPD patients with chronic CO2 retention, a pH below 7.35 indicates acute decompensation.",
  },
  weakAreaTag: "abg-respiratory-acidosis-copd",
  studyPlanMapping: "respiratory-failure",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 8: DIABETES MANAGEMENT (7 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-diabetes-006",
  topic: "Diabetes Management",
  lessonSlug: "us-pn-diabetes-management",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient with Type 1 diabetes is scheduled to receive insulin lispro 6 units before breakfast. The patient says they are not hungry and does not want to eat. Which action is most appropriate?",
  options: [
    "Administer the full 6 units as ordered since the schedule must be maintained",
    "Skip the insulin dose since the patient is not eating",
    "Hold the lispro and notify the provider — rapid-acting insulin before a skipped meal risks hypoglycemia",
    "Administer half the dose since the patient may eat something small later",
  ],
  correct: [2],
  rationale: "Rapid-acting insulin (lispro) should not be administered when a patient refuses to eat. Rapid-acting insulins act within 5–15 minutes and peak within 30–90 minutes — administering without carbohydrate intake causes rapid hypoglycemia. The PN holds the dose and notifies the provider. The basal insulin (long-acting) may still be administered per order.",
  whyCorrect: "Option C correctly holds the rapid-acting insulin for a patient who will not eat and escalates to the provider for guidance.",
  whyIncorrect: {
    "A": "Administering rapid-acting insulin to a fasting patient causes preventable hypoglycemia — the schedule does not override clinical safety.",
    "B": "Simply skipping without provider notification does not address insulin management for the day.",
    "D": "Half-doses are not within the PN's scope to decide independently — this requires a provider order modification.",
  },
  weakAreaTag: "rapid-acting-insulin-meal-coordination",
  studyPlanMapping: "diabetes-management",
},
{
  id: "pn-diabetes-007",
  topic: "Diabetes Management",
  lessonSlug: "us-pn-diabetes-management",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Pharmacological and Parenteral Therapies",
  difficulty: 3,
  questionType: "SATA",
  stem: "A patient with Type 2 diabetes is being discharged on metformin 1000 mg twice daily. Which instructions should the PN include in the discharge teaching? Select all that apply.",
  options: [
    "Take metformin with meals to reduce GI side effects",
    "Metformin can cause low blood sugar (hypoglycemia) if meals are missed",
    "Call your provider if you are scheduled for any imaging procedure using contrast dye",
    "Do not take NSAIDs (ibuprofen, naproxen) while on metformin without checking with your provider",
    "Store metformin in the refrigerator to maintain potency",
  ],
  correct: [0, 2, 3],
  rationale: "Correct metformin teaching: (A) Taking with meals reduces GI side effects (nausea, diarrhea, stomach upset); (C) Metformin must be held before procedures with IV contrast in patients at renal risk to prevent lactic acidosis; (D) NSAIDs can reduce renal function, impair metformin clearance, and increase lactic acidosis risk. Metformin does not typically cause hypoglycemia (it does not stimulate insulin secretion). Metformin is stored at room temperature, not refrigerated.",
  whyCorrect: "Options A, C, and D are all accurate and important metformin safety teaching points.",
  whyIncorrect: {
    "B": "Metformin alone does not cause hypoglycemia — it reduces hepatic glucose production and improves insulin sensitivity without stimulating insulin release.",
    "E": "Metformin is stored at room temperature (59–86°F) — refrigeration is not required.",
  },
  weakAreaTag: "metformin-discharge-teaching",
  studyPlanMapping: "diabetes-management",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 9: HYPERGLYCEMIA (5 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-hyperglycemia-006",
  topic: "Hyperglycemia Management",
  lessonSlug: "us-pn-hyperglycemia-management",
  exam: "NCLEX-PN",
  domain: "Physiological Integrity",
  blueprintCategory: "Reduction of Risk Potential",
  difficulty: 3,
  questionType: "MCQ",
  stem: "A patient without prior diabetes history is started on prednisone 60 mg daily for an asthma exacerbation. On day 2, the blood glucose is 286 mg/dL at 3 PM. The fasting glucose this morning was 112 mg/dL. What is the PN's best action?",
  options: [
    "Reassure the patient — mild glucose elevation is expected with steroids and resolves when steroids are stopped",
    "Notify the provider of the afternoon glucose spike — steroid-induced hyperglycemia peaking in the afternoon is expected but requires insulin coverage orders",
    "Administer sliding scale insulin from the standing order without notifying the provider",
    "Hold the evening prednisone dose to prevent further glucose elevation",
  ],
  correct: [1],
  rationale: "Corticosteroids predictably cause blood glucose to peak 4–8 hours after the morning dose — in the afternoon. A glucose of 286 mg/dL represents significant steroid-induced hyperglycemia requiring provider evaluation for insulin coverage orders. The PN notifies the provider with the glucose pattern (fasting 112, afternoon 286) so appropriate insulin (often NPH to cover the afternoon peak) can be ordered. Withholding steroids is not within PN scope.",
  whyCorrect: "Option B correctly identifies the steroid-induced hyperglycemia mechanism and the need for provider notification for insulin coverage.",
  whyIncorrect: {
    "A": "A glucose of 286 mg/dL is significant enough to require treatment — reassuring without notification risks DKA if untreated.",
    "C": "The PN may apply standing sliding scale orders if they exist, but a glucose of 286 with an unusual pattern in a non-diabetic requires provider notification regardless.",
    "D": "Holding steroids requires a provider order — the PN cannot independently discontinue prescribed therapy.",
  },
  weakAreaTag: "steroid-induced-hyperglycemia",
  studyPlanMapping: "hyperglycemia-management",
},

// ═══════════════════════════════════════════════════════════════════════════
// TOPIC 10: CLIENT EDUCATION (5 additional questions)
// ═══════════════════════════════════════════════════════════════════════════

{
  id: "pn-edu-006",
  topic: "Client Education",
  lessonSlug: "us-pn-client-education-principles",
  exam: "NCLEX-PN",
  domain: "Health Promotion and Maintenance",
  blueprintCategory: "Health Promotion and Disease Prevention",
  difficulty: 2,
  questionType: "MCQ",
  stem: "A patient needs teaching about a new insulin injection technique. The patient speaks limited English and the PN does not speak the patient's language. Which action is most appropriate before beginning the teaching?",
  options: [
    "Use simple gestures and visual demonstrations to teach the injection technique without an interpreter",
    "Ask the patient's adult child who is present to translate during the teaching session",
    "Arrange for a certified medical interpreter before beginning any teaching",
    "Provide written instructions in the patient's language and ask them to read it at home",
  ],
  correct: [2],
  rationale: "For complex health teaching — especially high-risk skills like insulin injection — a certified medical interpreter is required. Family members are not appropriate interpreters for medical education: they may lack vocabulary, may filter information based on personal concerns, and are not trained to maintain objectivity. The teaching session should be delayed until a qualified interpreter is available.",
  whyCorrect: "Option C ensures the patient receives accurate, complete, and professionally interpreted education — essential for safety with insulin administration.",
  whyIncorrect: {
    "A": "Gestures alone are insufficient for the detailed technical content of injection technique and hypoglycemia recognition.",
    "B": "Family members are not appropriate for high-stakes medical interpretation — they lack training and may introduce inaccuracies or omissions.",
    "D": "Written materials in the patient's language are a supplement, not a substitute for demonstrated skill teaching — insulin injection requires return demonstration.",
  },
  weakAreaTag: "interpreter-services-teaching",
  studyPlanMapping: "client-education",
},
{
  id: "pn-edu-007",
  topic: "Client Education",
  lessonSlug: "us-pn-client-education-principles",
  exam: "NCLEX-PN",
  domain: "Health Promotion and Maintenance",
  blueprintCategory: "Health Promotion and Disease Prevention",
  difficulty: 1,
  questionType: "MCQ",
  stem: "Which method best allows the PN to evaluate whether a patient has learned how to perform blood glucose monitoring at home?",
  options: [
    "Ask the patient if they understood the demonstration",
    "Have the patient explain the steps verbally",
    "Have the patient perform a return demonstration using the glucometer",
    "Give the patient a written quiz about the procedure",
  ],
  correct: [2],
  rationale: "For psychomotor skills (blood glucose monitoring, insulin injection, wound care), return demonstration by the patient is the gold standard for evaluating learning. It confirms the patient can actually perform the skill correctly, not just describe it. Verbal explanation tests knowledge but not the physical skill. Written quizzes test recall but not procedural competence.",
  whyCorrect: "Option C is the gold standard for evaluating psychomotor skill learning — return demonstration provides direct evidence of ability.",
  whyIncorrect: {
    "A": "Patient self-report of understanding is the weakest form of learning evaluation — patients frequently overestimate their understanding.",
    "B": "Verbal explanation tests cognitive domain knowledge, not the psychomotor skill needed for glucometer use.",
    "D": "Written quizzes test recall and cognitive understanding, not the ability to physically perform the skill.",
  },
  weakAreaTag: "return-demonstration-evaluation",
  studyPlanMapping: "client-education",
},

];

export default NCLEX_PN_GAP_QUESTIONS;
