export const ACTIVE_BUILD_PRIORITY = "AI_TUTORING_ASSISTANT";

export const CONTENT_EXPANSION_ROADMAP = [
  {
    priority: 1,
    title: "Certification Exam Bank Expansion",
    status: "in-progress" as const,
    description: "Build comprehensive question banks (1,500+ per cert) for 11 nursing certifications with mock exams and practice modes.",
    seoImpact: "High" as const,
    conversionImpact: "High" as const,
    contentDepth: "High" as const,
    marketDemand: "High" as const,
    certifications: ["BLS", "ACLS", "PALS", "NRP", "TNCC", "ENPC", "CCRN", "CEN", "OCN", "CNOR", "CPN"],
  },
  {
    priority: 2,
    title: "Social Worker Tier Expansion",
    status: "complete",
    description: "Expanded ASWB question bank to 1,000+ questions across 20 content domains with category/domain pages, conversion hero, test bank, SEO structured data, and multilingual scaffolding (EN/FR/ES).",
    seoImpact: "High",
    conversionImpact: "High",
  },
  {
    priority: 3,
    title: "Addictions Counsellor Expansion",
    status: "planned" as const,
    description: "Add dedicated addictions counselling exam prep content and question banks.",
    seoImpact: "Medium" as const,
    conversionImpact: "Medium" as const,
    contentDepth: "Medium" as const,
    marketDemand: "High" as const,
  },
  {
    priority: 4,
    title: "Psychotherapist Expansion",
    status: "planned" as const,
    description: "Expand psychotherapist licensing exam preparation with province-specific content.",
    seoImpact: "Medium" as const,
    conversionImpact: "Medium" as const,
    contentDepth: "Medium" as const,
    marketDemand: "Medium" as const,
  },
  {
    priority: 5,
    title: "AI Adaptive Testing",
    status: "planned" as const,
    description: "Implement CAT-style adaptive testing for all certification exams.",
    seoImpact: "Low" as const,
    conversionImpact: "High" as const,
    contentDepth: "High" as const,
    marketDemand: "High" as const,
  },
  {
    priority: 6,
    title: "Personalized Study Plans",
    status: "planned" as const,
    description: "AI-generated personalized study plans based on diagnostic assessment results.",
    seoImpact: "Medium" as const,
    conversionImpact: "High" as const,
    contentDepth: "Medium" as const,
    marketDemand: "High" as const,
  },
];

export const TUTOR_EXPANSION_ROADMAP = [
  {
    rank: 1,
    title: "Competitive Study Leaderboards",
    description: "Gamified leaderboard system where students compete on accuracy, streaks, and study time across topics.",
    engagementImpact: 9,
    conversionPotential: 7,
    learningEffectiveness: 6,
    status: "planned" as const,
  },
  {
    rank: 2,
    title: "Group Study Rooms",
    description: "Virtual collaborative study spaces where students can quiz each other, share notes, and discuss topics in real time.",
    engagementImpact: 8,
    conversionPotential: 8,
    learningEffectiveness: 8,
    status: "planned" as const,
  },
  {
    rank: 3,
    title: "Daily Study Streaks",
    description: "Streak-based motivation system with daily study goals, badges, and rewards for consistency.",
    engagementImpact: 9,
    conversionPotential: 6,
    learningEffectiveness: 7,
    status: "planned" as const,
  },
  {
    rank: 4,
    title: "Exam Countdown Tracker",
    description: "Personalized countdown to exam day with adaptive study plan adjustments and readiness assessments.",
    engagementImpact: 7,
    conversionPotential: 8,
    learningEffectiveness: 9,
    status: "planned" as const,
  },
];

export const CERTIFICATION_BUILD_SUMMARY = {
  selectedPriority: "Certification Exam Bank Expansion",
  banksCreated: 11,
  certifications: ["BLS", "ACLS", "PALS", "NRP", "TNCC", "ENPC", "CCRN", "CEN", "OCN", "CNOR", "CPN"],
  mockExamsCreated: 33,
  totalQuestionsBuilt: 17210,
  filesModified: [
    "client/src/data/certification-exam-data.ts",
    "client/src/data/certification-prep-content.ts",
    "client/src/config/admin-constants.ts",
    "shared/tier-config.ts",
    "server/routes.ts",
  ],
  nextRecommendedExpansion: "Addictions Counsellor Expansion",
};
