/**
 * Simulation Catalog
 *
 * 42 complete simulation definitions covering RN, RPN, NP, RT, and New Graduate
 * pathways. Each simulation is a self-contained, authored scenario that drives
 * <MonitorWorkstation> and the full scoring/reporting pipeline.
 *
 * Simulations compose the existing deterioration-patterns + clinical-skills-adapter
 * + ngn-monitor-embed systems — they do not duplicate logic.
 *
 * Usage:
 *   const sim = getSimulation("rn-sepsis-early");
 *   // → pass sim.monitorConfig to MonitorWorkstation
 *   // → use sim.learningObjectives for the pre-brief
 *   // → use sim.ngnFormats to generate post-sim questions
 */

import type { MonitorMode } from "./physiology-state";

// ─── Profession ───────────────────────────────────────────────────────────────

export type SimulationProfession = "RN" | "RPN" | "NP" | "RT" | "NEW_GRAD";

// ─── Difficulty ───────────────────────────────────────────────────────────────

export type SimulationDifficulty = "foundational" | "developing" | "proficient" | "advanced";

// ─── NGN format ───────────────────────────────────────────────────────────────

export type NgnQuestionFormat = "bowtie" | "matrix" | "sata" | "prioritization" | "cloze";

// ─── Simulation definition ────────────────────────────────────────────────────

export interface SimulationDefinition {
  id: string;
  title: string;
  profession: SimulationProfession[];
  specialty: string[];
  conditionKey: string;
  pathwayId: string;
  difficulty: SimulationDifficulty;
  /** Estimated total session time in minutes. */
  estimatedMinutes: number;
  /** Monitor mode for this simulation. */
  monitorMode: MonitorMode;
  /** Stage the condition opens at (default "early"). */
  openingStage?: "early" | "developing" | "severe";
  /** Whether to show overlay by default. */
  defaultOverlay: boolean;
  /** Whether interventions are available (some assessment-only sims hide them). */
  showInterventions: boolean;
  patientBrief: string;
  sbar: { situation: string; background: string; assessment: string; recommendation: string };
  learningObjectives: string[];
  criticalActions: CriticalAction[];
  documentationPrompts: string[];
  ngnFormats: NgnQuestionFormat[];
  /** Primary NCJMM domains exercised by this simulation. */
  primaryNcjmmDomains: string[];
  /** Clinical tags for filtering and search. */
  tags: string[];
}

export interface CriticalAction {
  /** Ticks from session start within which this action must occur. */
  timeLimitTicks: number;
  description: string;
  /** Intervention key, or null if it is a recognition/escalation action. */
  interventionKey: string | null;
  /** Is failure a patient-safety event? */
  isHarmIfMissed: boolean;
}

// ─── Catalog ──────────────────────────────────────────────────────────────────

export const SIMULATION_CATALOG: SimulationDefinition[] = [

  // ══ RN SIMULATIONS ══════════════════════════════════════════════════════════

  {
    id: "rn-sepsis-early",
    title: "Sepsis: Early Recognition",
    profession: ["RN"],
    specialty: ["med-surg", "emergency", "icu"],
    conditionKey: "sepsis",
    pathwayId: "sepsis",
    difficulty: "developing",
    estimatedMinutes: 20,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mrs. Okafor, 64F, 2 days post-laparoscopic appendectomy. Called because she is 'not herself.' She is flushed, confused, and complaining of chills.",
    sbar: {
      situation: "Mrs. Okafor is febrile 39.1°C, HR 108, BP 96/58, RR 22, SpO₂ 95%. GCS has decreased from baseline.",
      background: "64F, post-op day 2 appendectomy. PMHx: T2DM, hypertension. Pre-op antibiotics given. Foley catheter in place — urine appears cloudy.",
      assessment: "Two SIRS criteria met, MAP 71, lactate not yet ordered. Wound appears clean. Suspect UTI or anastomotic leak.",
      recommendation: "Blood cultures × 2, lactate, CBC, BMP, CXR. Physician notification for sepsis order set.",
    },
    learningObjectives: [
      "Identify SIRS criteria and initiate sepsis screening",
      "Interpret rising lactate as a tissue perfusion marker",
      "Initiate the 1-hour sepsis bundle from Surviving Sepsis Campaign",
      "Escalate appropriately before hemodynamic compromise develops",
    ],
    criticalActions: [
      { timeLimitTicks: 3, description: "Recognise tachycardia and hypotension", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 5, description: "Apply supplemental oxygen", interventionKey: "supplemental_o2", isHarmIfMissed: false },
      { timeLimitTicks: 6, description: "Initiate IV fluid resuscitation", interventionKey: "fluid_bolus", isHarmIfMissed: true },
      { timeLimitTicks: 10, description: "Notify provider and activate sepsis protocol", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document SIRS criteria met with time of recognition",
      "Record lactate result and trend",
      "Document fluid administered: volume, type, time, response",
      "Document provider notification time and orders received",
      "Complete sepsis bundle checklist",
    ],
    ngnFormats: ["bowtie", "matrix", "sata"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses", "take_action"],
    tags: ["sepsis", "infection", "med-surg", "rn", "sirs", "lactate"],
  },

  {
    id: "rn-septic-shock",
    title: "Septic Shock: Vasopressor Management",
    profession: ["RN"],
    specialty: ["icu", "emergency"],
    conditionKey: "sepsis",
    pathwayId: "sepsis",
    difficulty: "advanced",
    estimatedMinutes: 30,
    monitorMode: "icu",
    openingStage: "severe",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Aldridge, 71M, ICU day 2 with gram-negative septic shock from pneumonia. Norepinephrine running at 0.08 mcg/kg/min. MAP has dropped to 58 in the last 30 minutes.",
    sbar: {
      situation: "MAP 58 mmHg despite current vasopressor. HR 128, Temp 39.8°C, Lactate 6.2 mmol/L. Urine output 10 mL/hr.",
      background: "71M, community-acquired pneumonia, ARDS, intubated day 1. PMHx: CKD, COPD, T2DM. ICU day 2 on norepinephrine, cefepime, and vancomycin.",
      assessment: "Refractory septic shock. Lactate not clearing. Consider adrenal insufficiency, occult source. Vasopressin add-on indicated.",
      recommendation: "Add vasopressin 0.04 units/min. Repeat 30 mL/kg fluid challenge. Cortisol stimulation test. Escalate to intensivist.",
    },
    learningObjectives: [
      "Recognise refractory septic shock from trend data",
      "Interpret rising lactate as inadequate perfusion despite vasopressors",
      "Titrate vasopressor therapy to MAP ≥ 65",
      "Identify when multi-drug vasopressor support is indicated",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise MAP < 65 on trend", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Escalate vasopressor (norepinephrine)", interventionKey: "norepinephrine", isHarmIfMissed: true },
      { timeLimitTicks: 6, description: "Notify intensivist of refractory shock", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 8, description: "Reassess perfusion markers (UO, lactate, capillary refill)", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document vasopressor doses, titration times, and MAP response",
      "Record hourly urine output trend",
      "Document lactate trend with times",
      "Note ventilator settings and tolerance",
      "Document intensivist communication and plan of care update",
    ],
    ngnFormats: ["bowtie", "matrix", "prioritization"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "evaluate_outcomes"],
    tags: ["sepsis", "septic-shock", "vasopressors", "icu", "rn", "lactate"],
  },

  {
    id: "rn-stemi",
    title: "STEMI: Recognition and Protocol Activation",
    profession: ["RN"],
    specialty: ["emergency", "telemetry", "cardiac"],
    conditionKey: "stemi",
    pathwayId: "stemi",
    difficulty: "proficient",
    estimatedMinutes: 20,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Kowalski, 57M, walked into the ED with crushing substernal chest pain rated 10/10, diaphoretic, radiating to his left jaw.",
    sbar: {
      situation: "HR 92, BP 138/84, SpO₂ 97%. Monitor shows ST elevation in leads II and aVF with reciprocal changes. Pain 10/10.",
      background: "57M, no prior cardiac history. Heavy smoker × 30 years. Hyperlipidemia. Father died of MI at 62.",
      assessment: "Inferior STEMI pattern on 12-lead. Hemodynamically stable. Time of symptom onset 45 minutes ago.",
      recommendation: "Cath lab activation. Aspirin 325 mg chewed. Heparin bolus. 12-lead every 10 min. IV access × 2.",
    },
    learningObjectives: [
      "Identify inferior STEMI on ECG (leads II, III, aVF) with reciprocal changes",
      "Initiate STEMI bundle within 10 minutes: ASA, heparin, cath lab activation",
      "Recognise hemodynamic deterioration indicating RV infarction",
      "Understand door-to-balloon time target (< 90 minutes)",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify STEMI pattern on monitor", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Apply supplemental oxygen if SpO₂ < 94%", interventionKey: "supplemental_o2", isHarmIfMissed: false },
      { timeLimitTicks: 5, description: "Cath lab activation / provider notification", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document time of first ECG and STEMI identification",
      "Record aspirin administration: dose, time, route",
      "Document cath lab activation time",
      "Note symptom onset time and total ischemic time calculation",
    ],
    ngnFormats: ["bowtie", "sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "take_action"],
    tags: ["stemi", "acs", "ecg", "cardiac", "cath-lab", "rn"],
  },

  {
    id: "rn-chf-exacerbation",
    title: "CHF Exacerbation: Pulmonary Congestion Management",
    profession: ["RN"],
    specialty: ["med-surg", "telemetry", "cardiac"],
    conditionKey: "heart_failure",
    pathwayId: "respiratory_failure",
    difficulty: "developing",
    estimatedMinutes: 25,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mrs. Bergmann, 78F, admitted via ED with 3-day worsening dyspnoea and bilateral ankle oedema. She sleeps on 4 pillows at home.",
    sbar: {
      situation: "SpO₂ 90% on 2L NC, RR 28, bilateral crackles to mid-zones. HR 112 AFib. BP 168/98.",
      background: "78F, EF 25%, known AFib on apixaban. Previous HF admission 3 months ago. Weight up 4 kg over 5 days.",
      assessment: "Acute decompensated heart failure. Possible AFib with RVR contributing. LVEF 25% — dilated CM.",
      recommendation: "Furosemide 80 mg IV. Upright positioning. BiPAP if SpO₂ fails to improve. Cardiology consult.",
    },
    learningObjectives: [
      "Recognise acute decompensated heart failure on the monitor",
      "Initiate diuresis and supplemental oxygen as first-line treatment",
      "Monitor response to furosemide (urine output trend)",
      "Identify when BiPAP is indicated vs supplemental oxygen alone",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise SpO₂ drop and tachypnea", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Upright positioning and supplemental O₂", interventionKey: "supplemental_o2", isHarmIfMissed: false },
      { timeLimitTicks: 4, description: "Furosemide administration", interventionKey: "furosemide", isHarmIfMissed: true },
      { timeLimitTicks: 8, description: "Reassess SpO₂ and urine output response", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document SpO₂ trend and oxygen delivery method",
      "Record diuretic dose, time, and urine output response (target 200–400 mL/hr)",
      "Document daily weight and fluid balance",
      "Note patient positioning and response",
    ],
    ngnFormats: ["matrix", "sata", "prioritization"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "evaluate_outcomes"],
    tags: ["chf", "heart-failure", "diuretics", "afib", "telemetry", "rn"],
  },

  {
    id: "rn-hyperkalemia",
    title: "Hyperkalemia: ECG Recognition and Emergency Treatment",
    profession: ["RN"],
    specialty: ["renal", "icu", "med-surg"],
    conditionKey: "hyperkalemia",
    pathwayId: "hyperkalemia",
    difficulty: "proficient",
    estimatedMinutes: 20,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Nwosu, 52M, CKD stage 4 patient on the renal unit. Labs returned: K⁺ 7.1 mEq/L. Monitor alarming. You are called to assess.",
    sbar: {
      situation: "K⁺ 7.1 mEq/L. ECG shows peaked T-waves with QRS widening. HR 54, BP 112/70. Patient complaining of leg weakness.",
      background: "52M, CKD4, hypertension, T2DM. Current meds include spironolactone and lisinopril. Last dialysis 4 days ago. Missed recent dialysis session.",
      assessment: "Severe symptomatic hyperkalemia with ECG changes. Risk of fatal arrhythmia without immediate treatment.",
      recommendation: "Calcium gluconate immediately. Insulin/dextrose. Sodium bicarbonate if acidaemic. Emergent dialysis consult.",
    },
    learningObjectives: [
      "Identify hyperkalemia ECG progression: peaked T → wide QRS → sine wave",
      "Apply the emergency hyperkalemia treatment sequence",
      "Understand the mechanism of each treatment modality",
      "Recognise when dialysis is the definitive treatment",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify peaked T-waves and QRS widening on ECG", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Calcium gluconate for membrane stabilisation", interventionKey: "calcium_gluconate", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Insulin + D50 to drive K into cells", interventionKey: "insulin_glucose", isHarmIfMissed: true },
      { timeLimitTicks: 6, description: "Notify nephrologist — dialysis consult", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document potassium value, ECG findings, and time of recognition",
      "Record calcium gluconate: dose, time, ECG response",
      "Document insulin/D50 administration and glucose monitoring schedule",
      "Note nephrology notification time and plan",
    ],
    ngnFormats: ["bowtie", "sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues", "take_action"],
    tags: ["hyperkalemia", "ecg", "renal", "electrolytes", "rn", "dialysis"],
  },

  {
    id: "rn-gi-bleed",
    title: "GI Bleed: Haemorrhagic Shock Resuscitation",
    profession: ["RN"],
    specialty: ["emergency", "med-surg"],
    conditionKey: "gi_bleed",
    pathwayId: "gi_bleed",
    difficulty: "proficient",
    estimatedMinutes: 25,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Harrington, 68M, vomited large amounts of coffee-ground material and has passed melaena stools × 3. He is pale and diaphoretic.",
    sbar: {
      situation: "HR 124, BP 88/52, SpO₂ 96%. Haematemesis, melaena. Abdomen soft, diffusely tender. Conscious but confused.",
      background: "68M, known NSAID user, cirrhosis Child-Pugh B. No current PPI use. Last EGD 2 years ago — gastric ulcers noted.",
      assessment: "Upper GI bleed with haemorrhagic shock. Likely peptic ulcer disease vs variceal source. Glasgow-Blatchford score high-risk.",
      recommendation: "IV access × 2 large bore. Type and cross × 4 units. Bolus NS. Activate massive transfusion protocol if needed. Endoscopy team notification.",
    },
    learningObjectives: [
      "Recognise haemorrhagic shock from vital sign trends",
      "Initiate haemorrhagic shock resuscitation: IV access, fluids, blood products",
      "Calculate and monitor blood loss indicators (HR trend, BP trend, mental status)",
      "Activate massive transfusion protocol criteria",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise shock from HR/BP trend", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "IV fluid resuscitation", interventionKey: "fluid_bolus", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Blood transfusion / activate MTP", interventionKey: "blood_transfusion", isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document GCS, haematemesis/melaena description and estimated blood loss",
      "Record fluid and blood product administration with times and response",
      "Document vital sign trend every 15 minutes",
      "Note endoscopy team notification and ETA",
    ],
    ngnFormats: ["prioritization", "matrix", "bowtie"],
    primaryNcjmmDomains: ["prioritize_hypotheses", "take_action"],
    tags: ["gi-bleed", "hemorrhage", "shock", "transfusion", "rn"],
  },

  {
    id: "rn-stroke",
    title: "Stroke: FAST Recognition and Acute Management",
    profession: ["RN"],
    specialty: ["med-surg", "emergency", "neurology"],
    conditionKey: "stroke",
    pathwayId: "stroke",
    difficulty: "developing",
    estimatedMinutes: 20,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Diallo, 73M, found unresponsive by his wife at 0630. He has left-sided facial droop, arm drift, and slurred speech. Last seen normal at 2200.",
    sbar: {
      situation: "GCS 11. Left facial droop, arm drift, slurred speech. BP 188/106, HR 82 sinus rhythm, SpO₂ 94%.",
      background: "73M, hypertension, T2DM, previously independent. Last seen well at 2200. Found at 0630. Wake-up stroke.",
      assessment: "Acute ischaemic stroke presentation. Last-known-well 8+ hours ago — thrombolysis window uncertain. MRI WAKE-UP protocol candidate.",
      recommendation: "Stat brain CT/CTA. Stroke team activation. Glucose check (88 mg/dL). Keep systolic < 185/110 pre-tPA. NPO.",
    },
    learningObjectives: [
      "Apply FAST criteria for stroke recognition",
      "Calculate stroke onset window for thrombolysis eligibility",
      "Maintain BP targets for acute ischaemic stroke (< 185/110 if tPA candidate)",
      "Understand NPO and aspiration precautions in acute stroke",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "FAST assessment and stroke recognition", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Activate stroke team / code stroke", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Glucose check and supplemental O₂ if SpO₂ < 94%", interventionKey: "supplemental_o2", isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document FAST findings: time of assessment, each criterion",
      "Record last-known-well time precisely",
      "Document BP readings every 15 minutes",
      "Note stroke team activation time",
      "Document glucose result",
    ],
    ngnFormats: ["bowtie", "sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses"],
    tags: ["stroke", "neuro", "fast", "thrombolysis", "rn"],
  },

  {
    id: "rn-respiratory-failure",
    title: "Respiratory Failure: Progressive Hypoxemia",
    profession: ["RN"],
    specialty: ["icu", "emergency", "med-surg"],
    conditionKey: "ards",
    pathwayId: "respiratory_failure",
    difficulty: "proficient",
    estimatedMinutes: 25,
    monitorMode: "icu",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Ms. Petrov, 44F, admitted 48h ago with COVID-19 pneumonia. SpO₂ was 94% on 6L NC this morning. Now SpO₂ 87% on 15L NRB. She is using accessory muscles.",
    sbar: {
      situation: "SpO₂ 87% on 15L NRB. RR 38. Accessory muscle use. Speaking in short sentences. BP 128/80, HR 118.",
      background: "44F, COVID-19 pneumonia, bilateral infiltrates CXR. PMHx: obesity BMI 38, no prior respiratory disease.",
      assessment: "Hypoxic respiratory failure, likely ARDS. BiPAP trial indicated. Intubation threshold approaching.",
      recommendation: "Initiate BiPAP 10/5 FiO₂ 0.6. Prone positioning if able. Dexamethasone and remdesivir. ICU attending at bedside.",
    },
    learningObjectives: [
      "Recognise the progression from hypoxaemia to respiratory failure on the monitor",
      "Initiate non-invasive ventilation (BiPAP) as bridge to intubation",
      "Identify intubation triggers: SpO₂ < 85% on NRB, RR > 35, altered consciousness",
      "Apply ARDS management principles: low TV, high PEEP, prone positioning",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise SpO₂ < 90% and respiratory distress", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Initiate BiPAP / HFNC", interventionKey: "bipap", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "ICU attending notification — intubation team on standby", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document SpO₂, RR, and work of breathing assessments every 30 minutes",
      "Record BiPAP settings, tolerance, and response",
      "Document respiratory failure threshold triggers met",
      "Note intubation team notification time if applicable",
    ],
    ngnFormats: ["bowtie", "matrix", "sata"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "take_action"],
    tags: ["ards", "respiratory-failure", "bipap", "hypoxemia", "icu", "rn"],
  },

  {
    id: "rn-rapid-response",
    title: "Rapid Response: Deteriorating Ward Patient",
    profession: ["RN"],
    specialty: ["med-surg", "telemetry"],
    conditionKey: "sepsis",
    pathwayId: "sepsis",
    difficulty: "developing",
    estimatedMinutes: 15,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: false,
    patientBrief: "You are reviewing your 0800 vital signs. Mr. Torres, room 412, has been deteriorating over the last 2 hours. Family called you saying he is 'not waking up properly.'",
    sbar: {
      situation: "SpO₂ 89% (was 97% at 0600), HR 118 (was 88), BP 88/50 (was 118/72), RR 26, GCS 12.",
      background: "62M, post-op day 3 colostomy. Baseline vitals were normal at 0600. No documented events overnight.",
      assessment: "Acute deterioration — signs consistent with sepsis vs surgical complication. MEWS score 7.",
      recommendation: "Immediate Rapid Response activation. Notify attending. Continue bedside assessment.",
    },
    learningObjectives: [
      "Identify trigger criteria for Rapid Response Team (RRT) activation",
      "Apply Modified Early Warning Score (MEWS) to triage urgency",
      "Communicate SBAR to the rapid response team",
      "Prepare the bedside environment for the arriving team",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Recognise acute deterioration across multiple vitals", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Activate Rapid Response Team", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Stay at bedside — continuous monitoring", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document all vital signs with exact times",
      "Record RRT activation time",
      "Document SBAR communicated to RRT",
      "Note family notification",
    ],
    ngnFormats: ["sata", "prioritization"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses"],
    tags: ["rapid-response", "deterioration", "mews", "escalation", "rn"],
  },

  {
    id: "rn-code-blue",
    title: "Code Blue: VF Arrest Management",
    profession: ["RN"],
    specialty: ["med-surg", "icu", "emergency"],
    conditionKey: "vt_to_vf",
    pathwayId: "cardiac_arrest",
    difficulty: "advanced",
    estimatedMinutes: 20,
    monitorMode: "general",
    openingStage: "severe",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Fontaine, 65M, telemetry patient post-NSTEMI. The monitor alarm sounds. You enter the room and find him unresponsive with no visible chest rise.",
    sbar: {
      situation: "Unresponsive. No palpable pulse. Monitor shows VF. Code Blue called.",
      background: "65M, admitted 36h ago for NSTEMI. PCI performed — 95% LAD stenosis stented. EF 35%.",
      assessment: "Ventricular fibrillation cardiac arrest. Shockable rhythm. ACLS protocol initiated.",
      recommendation: "Immediate defibrillation 200J, CPR 2 minutes, reassess. Epinephrine 1 mg IV every 3-5 min. Amiodarone if persistent VF.",
    },
    learningObjectives: [
      "Confirm VF on monitor and initiate ACLS protocol",
      "Deliver high-quality CPR: rate 100–120/min, depth 5–6 cm, full recoil",
      "Charge and defibrillate within 2 minutes of recognition",
      "Apply ACLS algorithm: shock → CPR 2 min → rhythm check → repeat",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Confirm VF — call code blue", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "Begin high-quality CPR", interventionKey: "cpr", isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Defibrillate 200J unsynchronised", interventionKey: "defibrillation", isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document exact time of arrest recognition and code blue activation",
      "Record each defibrillation: time, joules, rhythm before and after",
      "Document CPR start time and all interruptions",
      "Record each medication with dose and time",
      "Document ROSC time if achieved",
    ],
    ngnFormats: ["bowtie", "sata"],
    primaryNcjmmDomains: ["recognize_cues", "take_action"],
    tags: ["code-blue", "vf", "acls", "defibrillation", "cpr", "rn"],
  },

  {
    id: "rn-postop-deterioration",
    title: "Post-Op Deterioration: PACU to ICU Transfer",
    profession: ["RN"],
    specialty: ["surgical", "pacu", "icu"],
    conditionKey: "opioid_toxicity",
    pathwayId: "opioid_toxicity",
    difficulty: "developing",
    estimatedMinutes: 20,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mrs. Yamamoto, 58F, 2 hours post-laparotomy. In PACU on 4 mg/hr morphine PCA. Nurse notices she is very drowsy and her monitor is alarming.",
    sbar: {
      situation: "RR 6, SpO₂ 82%, very drowsy — rouses to voice but not sustained. HR 52, BP 98/60.",
      background: "58F, 2h post-laparotomy. Morphine PCA 4 mg/hr with 2 mg demand dose. Received fentanyl × 3 intra-op. PMHx: obstructive sleep apnoea.",
      assessment: "Opioid-induced respiratory depression. OSA risk factor. RR 6 is critical.",
      recommendation: "Naloxone 0.4 mg IV titrated. Stop PCA. Oxygen immediately. Anaesthesia notification. CPAP if OSA documented.",
    },
    learningObjectives: [
      "Recognise opioid toxicity triad: miosis, respiratory depression, sedation",
      "Administer naloxone correctly (titrated dosing to avoid acute withdrawal)",
      "Identify patients at high risk for opioid-induced respiratory depression",
      "Initiate safe post-operative pain management after reversal",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Recognise critical bradypnoea (RR < 8)", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Supplemental O₂ and airway positioning", interventionKey: "supplemental_o2", isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Stop PCA and notify anaesthesia", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document sedation score (CPOT/RASS) with time",
      "Record RR and SpO₂ at time of recognition",
      "Document naloxone dose, time, response",
      "Note PCA discontinued — time and order",
    ],
    ngnFormats: ["bowtie", "sata", "matrix"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues", "take_action"],
    tags: ["opioid-toxicity", "naloxone", "postop", "pacu", "respiratory-depression", "rn"],
  },

  {
    id: "rn-pe",
    title: "Pulmonary Embolism: Recognition and Stabilisation",
    profession: ["RN"],
    specialty: ["med-surg", "emergency", "icu"],
    conditionKey: "pulmonary_embolism",
    pathwayId: "pe",
    difficulty: "proficient",
    estimatedMinutes: 20,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Ms. Lindqvist, 38F, day 2 post-knee arthroplasty. She pressed her call bell complaining of sudden shortness of breath and pleuritic chest pain.",
    sbar: {
      situation: "Sudden dyspnoea, HR 122, SpO₂ 89%, RR 28. Pleuritic chest pain right side. BP 106/68. Legs asymmetric swelling right calf.",
      background: "38F, 2 days post right total knee arthroplasty. No anticoagulation yet — forgot morning enoxaparin. No prior PE/DVT. OCP user.",
      assessment: "High clinical probability PE. Wells score ≥ 5. SpO₂ falling. Haemodynamically borderline.",
      recommendation: "Supplemental O₂. Urgent CTPA. Heparin bolus if CT confirms. Escalate to medical team immediately.",
    },
    learningObjectives: [
      "Recognise acute PE from vital sign + symptom cluster",
      "Apply Wells criteria for PE probability estimation",
      "Differentiate haemodynamically stable vs unstable PE",
      "Initiate anticoagulation threshold criteria",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise PE symptom cluster and notify provider", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Supplemental O₂", interventionKey: "supplemental_o2", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "IV fluid bolus for haemodynamic support", interventionKey: "fluid_bolus", isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document Wells criteria assessed and score",
      "Record SpO₂, HR, BP trend at time of symptom onset",
      "Document O₂ delivery method and response",
      "Note medical team notification time and plan",
    ],
    ngnFormats: ["sata", "bowtie", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues"],
    tags: ["pe", "pulmonary-embolism", "dvt", "anticoagulation", "post-op", "rn"],
  },

  {
    id: "rn-dka",
    title: "DKA: Fluid and Insulin Management",
    profession: ["RN"],
    specialty: ["med-surg", "emergency", "icu"],
    conditionKey: "dka",
    pathwayId: "dka",
    difficulty: "proficient",
    estimatedMinutes: 25,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Santos, 24M, T1DM, brought in by EMS. Found at home with altered mental status, deep rapid breathing, and fruity odour on breath. Glucose 642 mg/dL on point-of-care.",
    sbar: {
      situation: "Glucose 642. RR 32 deep and regular (Kussmaul). HR 128, BP 94/60. GCS 12. Glucose strips positive for ketones.",
      background: "24M, T1DM × 12 years. Insulin omission × 3 days (poor compliance). No recent illness. K⁺ 5.8 mEq/L on point-of-care.",
      assessment: "Diabetic ketoacidosis. Moderate-severe. Hyperglycaemia, anion gap metabolic acidosis, ketonuria.",
      recommendation: "1 L NS bolus. Insulin 0.1 units/kg/hr infusion. K⁺ replacement as insulin drives K intracellularly. Hourly glucose monitoring.",
    },
    learningObjectives: [
      "Recognise DKA triad: hyperglycaemia, Kussmaul breathing, ketosis",
      "Initiate DKA protocol: fluids → insulin → K⁺ replacement",
      "Monitor glucose hourly and adjust insulin to avoid hypoglycaemia",
      "Understand why potassium must be replaced BEFORE or WITH insulin",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise Kussmaul breathing and DKA diagnosis", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Aggressive IV fluid resuscitation", interventionKey: "fluid_bolus", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Insulin infusion + K⁺ replacement", interventionKey: "insulin_glucose", isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document glucose, ketones, ABG results with time",
      "Record fluid administered: volume, type, rate, cumulative",
      "Document insulin infusion rate and hourly glucose response",
      "Note K⁺ replacement dose and frequency",
    ],
    ngnFormats: ["matrix", "cloze", "bowtie"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions"],
    tags: ["dka", "diabetes", "insulin", "fluid-resuscitation", "rn"],
  },

  {
    id: "rn-opioid-toxicity",
    title: "Opioid Toxicity: Naloxone Administration",
    profession: ["RN"],
    specialty: ["med-surg", "emergency", "community"],
    conditionKey: "opioid_toxicity",
    pathwayId: "opioid_toxicity",
    difficulty: "developing",
    estimatedMinutes: 15,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Patel, 32M, found unresponsive in the hospital hallway by a porter. Suspected PWUD — found with unknown substances nearby.",
    sbar: {
      situation: "Unresponsive. RR 4, SpO₂ 74%. Miosis. Cyanotic lips. No trauma visible. HR 44.",
      background: "Unknown history. Suspected PWUD. No ID on person. Bystander reports 'found like this.'",
      assessment: "Classic opioid toxicity triad. Life-threatening respiratory depression. Naloxone indicated.",
      recommendation: "Naloxone 0.4 mg IV/IM immediately. Airway support — jaw thrust. O₂ via BVM. Call code if no response in 2 minutes.",
    },
    learningObjectives: [
      "Recognise opioid toxicity triad: RR < 8, miosis, sedation",
      "Administer naloxone correctly — IM if no IV access",
      "Provide rescue breathing while naloxone takes effect",
      "Understand naloxone duration and re-dosing requirements",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Airway and stimulation assessment", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "Supplemental O₂ / BVM", interventionKey: "supplemental_o2", isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Naloxone administration", interventionKey: "epinephrine_im", isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document time of discovery and clinical presentation",
      "Record naloxone dose, route, time, and response",
      "Note SpO₂ and RR every 5 minutes post-naloxone",
      "Document if repeat dose required and why",
    ],
    ngnFormats: ["sata", "bowtie"],
    primaryNcjmmDomains: ["recognize_cues", "take_action"],
    tags: ["opioid-toxicity", "naloxone", "emergency", "airway", "rn"],
  },

  {
    id: "rn-anaphylaxis",
    title: "Anaphylaxis: Emergency Response",
    profession: ["RN"],
    specialty: ["med-surg", "emergency", "ambulatory"],
    conditionKey: "anaphylaxis",
    pathwayId: "anaphylaxis",
    difficulty: "proficient",
    estimatedMinutes: 15,
    monitorMode: "general",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mrs. Chen, 29F, 10 minutes after IV amoxicillin administration in an ambulatory infusion centre. Pressing call bell — states 'throat closing.'",
    sbar: {
      situation: "Urticaria spreading, throat tightness, stridor audible. HR 144, BP 72/38, SpO₂ 88%, RR 30.",
      background: "29F, admitted for IV antibiotics for cellulitis. Allergy documented as penicillin — rash. Not flagged as anaphylaxis risk.",
      assessment: "Anaphylaxis: angioedema, bronchospasm, distributive shock within 10 minutes of amoxicillin administration.",
      recommendation: "IM epinephrine 0.3 mg immediately. Stop amoxicillin. Lay supine. Call code. IV access. Diphenhydramine, methylprednisolone as adjuncts.",
    },
    learningObjectives: [
      "Distinguish anaphylaxis from an allergic reaction requiring epinephrine",
      "Administer IM epinephrine as FIRST-LINE — not antihistamines",
      "Monitor for biphasic reaction requiring second dose",
      "Understand post-anaphylaxis observation period (minimum 4–6 hours)",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Stop amoxicillin infusion immediately", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "IM epinephrine 0.3 mg right lateral thigh", interventionKey: "epinephrine_im", isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "IV fluid bolus for distributive shock", interventionKey: "fluid_bolus", isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document time of drug administration and time of symptom onset",
      "Record epinephrine: dose, route, time, clinical response",
      "Document vital signs every 5 minutes for 30 minutes post-epinephrine",
      "Record drug stopped and allergy documentation update",
    ],
    ngnFormats: ["bowtie", "sata"],
    primaryNcjmmDomains: ["recognize_cues", "take_action"],
    tags: ["anaphylaxis", "epinephrine", "allergy", "shock", "airway", "rn"],
  },

  {
    id: "rn-tamponade",
    title: "Cardiac Tamponade: Beck's Triad Recognition",
    profession: ["RN"],
    specialty: ["icu", "cardiac", "emergency"],
    conditionKey: "cardiac_tamponade",
    pathwayId: "cardiac_arrest",
    difficulty: "advanced",
    estimatedMinutes: 20,
    monitorMode: "icu",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Novak, 66M, 24h post-cardiac surgery. Chest tube output has suddenly decreased. He is now hypotensive and complaining of chest pressure.",
    sbar: {
      situation: "BP 82/70 (narrow pulse pressure). HR 128. JVD present. Chest tube output decreased to 5 mL/hr (was 80 mL/hr). Muffled heart sounds.",
      background: "66M, 24h post-CABG. Mediastinal chest tubes in place. No coagulopathy documented. Platelets 210.",
      assessment: "Beck's triad: hypotension + JVD + muffled heart sounds. High suspicion for cardiac tamponade. Chest tube may be clotted.",
      recommendation: "Urgent bedside echo. Notify cardiac surgery immediately. Prepare for pericardiocentesis or surgical re-exploration.",
    },
    learningObjectives: [
      "Recognise Beck's triad and Pulsus paradoxus as tamponade signs",
      "Differentiate tamponade from other post-operative hypotension causes",
      "Understand why fluids are a temporising measure",
      "Prepare for emergent pericardiocentesis",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Recognise Beck's triad on monitor + physical exam", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Notify cardiac surgery — emergent echo", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "IV fluid bolus (temporising measure)", interventionKey: "fluid_bolus", isHarmIfMissed: false },
      { timeLimitTicks: 6, description: "Pericardiocentesis preparation", interventionKey: "pericardiocentesis", isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document Beck's triad findings with time",
      "Record chest tube output trend hourly",
      "Document echo findings",
      "Note cardiac surgery notification time and response",
    ],
    ngnFormats: ["bowtie", "matrix", "sata"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues", "prioritize_hypotheses"],
    tags: ["tamponade", "post-op", "cardiac-surgery", "becks-triad", "rn"],
  },

  {
    id: "rn-tension-ptx",
    title: "Tension Pneumothorax: Emergency Decompression",
    profession: ["RN"],
    specialty: ["icu", "emergency", "trauma"],
    conditionKey: "tension_pneumothorax",
    pathwayId: "respiratory_failure",
    difficulty: "advanced",
    estimatedMinutes: 15,
    monitorMode: "icu",
    openingStage: "developing",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Burke, 42M, ICU day 1 post-blunt chest trauma, mechanically ventilated. Ventilator high-pressure alarm activating. SpO₂ dropping rapidly.",
    sbar: {
      situation: "SpO₂ 82% and falling. Vent PIP 56 cmH₂O (alarm limit 40). Absent breath sounds left side. Tracheal deviation right. HR 138, BP 72/44.",
      background: "42M, MVA blunt chest trauma. Intubated in ED 2h ago. Left-sided rib fractures on CXR. Now high-pressure vent alarm.",
      assessment: "Tension pneumothorax. Clinical diagnosis — do NOT wait for CXR. Tracheal deviation and absent breath sounds confirm.",
      recommendation: "Needle decompression immediately — 2nd ICS MCL left side. Followed by chest tube. Do NOT ventilate aggressively until decompressed.",
    },
    learningObjectives: [
      "Recognise tension pneumothorax as a clinical diagnosis",
      "Understand that treatment (needle decompression) PRECEDES imaging",
      "Identify the correct anatomical landmark for needle decompression",
      "Prepare for definitive tube thoracostomy after initial decompression",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Recognise high-pressure alarm + absent breath sounds = tension PTX", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "Needle thoracostomy — 2nd ICS MCL", interventionKey: "needle_decompression", isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Notify thoracic surgery for chest tube", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document SpO₂, vent pressures, and breath sound assessment time",
      "Record needle decompression: site, time, response (rush of air, SpO₂ improvement)",
      "Document thoracic surgery notification time",
      "Note chest tube insertion time and output",
    ],
    ngnFormats: ["bowtie", "prioritization"],
    primaryNcjmmDomains: ["recognize_cues", "take_action"],
    tags: ["tension-ptx", "pneumothorax", "trauma", "ventilator", "needle-decompression", "rn"],
  },

  // ══ RPN SIMULATIONS ══════════════════════════════════════════════════════════

  {
    id: "rpn-afib-monitoring",
    title: "AFib Monitoring: Rate Response and Escalation",
    profession: ["RPN"],
    specialty: ["telemetry", "med-surg"],
    conditionKey: "afib_rvr",
    pathwayId: "tachyarrhythmia",
    difficulty: "developing",
    estimatedMinutes: 20,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mrs. Park, 74F, admitted with palpitations and exertional dyspnoea. Monitor shows irregularly irregular rhythm. HR fluctuating 110–145.",
    sbar: {
      situation: "Irregularly irregular rhythm, HR 132 average, BP 104/68, SpO₂ 94%, RR 20.",
      background: "74F, new onset AFib vs known but undiagnosed. HTN, T2DM. No anticoagulation. Reports palpitations × 2 days.",
      assessment: "Atrial fibrillation with rapid ventricular response. Haemodynamically borderline. Rate control vs rhythm control decision needed.",
      recommendation: "Monitor closely. Notify RN charge and physician. Telemetry lead placement verification. 12-lead ECG.",
    },
    learningObjectives: [
      "Identify atrial fibrillation on the bedside monitor",
      "Distinguish rate from rhythm control indications",
      "Identify haemodynamic instability requiring escalation",
      "Apply safe monitoring parameters for AFib patients",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify AFib on monitor", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Escalate to RN/physician — HR > 120 + symptoms", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Document rhythm and vital signs", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document rhythm interpretation with time",
      "Record HR range over 30-minute observation",
      "Document RN/physician notification and instructions",
      "Note patient symptoms (palpitations, dyspnoea, chest pain)",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses"],
    tags: ["afib", "telemetry", "monitoring", "escalation", "rpn"],
  },

  {
    id: "rpn-chest-pain-escalation",
    title: "Chest Pain Escalation: STEMI Alert",
    profession: ["RPN"],
    specialty: ["telemetry", "med-surg"],
    conditionKey: "stemi",
    pathwayId: "stemi",
    difficulty: "developing",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mr. Eriksson, 59M, on your ward for 12-lead monitoring post-syncope. He presses his call bell — 'something feels wrong in my chest.'",
    sbar: {
      situation: "HR 96, new ST elevation on monitor, BP 128/82, SpO₂ 97%. Chest pain 8/10 substernal.",
      background: "59M, admitted for syncopal episode. HTN, hyperlipidaemia. Father had MI at 55.",
      assessment: "New ST elevation on telemetry — probable STEMI. Requires immediate RN and physician notification.",
      recommendation: "Notify RN immediately. Do not leave patient. Prepare to assist with 12-lead ECG. Keep patient calm and still.",
    },
    learningObjectives: [
      "Recognise ST elevation changes on a bedside telemetry monitor",
      "Know the limits of RPN scope — recognition and escalation, not treatment",
      "Apply safe patient management while waiting for the RN",
      "Communicate findings clearly using SBAR",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Identify ST changes + chest pain", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "Call RN immediately — do not leave patient", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Position patient, keep calm, document vital signs", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document exact time of ST change noted on monitor",
      "Record vital signs at time of escalation",
      "Document RN notification: time, person notified, instructions",
      "Note patient's reported symptoms",
    ],
    ngnFormats: ["sata", "prioritization"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses"],
    tags: ["stemi", "chest-pain", "escalation", "telemetry", "rpn"],
  },

  {
    id: "rpn-bradycardia-monitoring",
    title: "Bradycardia: Monitoring and Escalation",
    profession: ["RPN"],
    specialty: ["telemetry", "med-surg"],
    conditionKey: "increased_icp",
    pathwayId: "bradycardia",
    difficulty: "developing",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mr. Halvorsen, 81M, on your unit for telemetry monitoring post-CABG day 5. Monitor alarm sounds — HR 38.",
    sbar: {
      situation: "HR 38 sinus bradycardia. BP 92/58. Patient awake but dizzy and lightheaded.",
      background: "81M, post-CABG day 5. Previous bradycardia episodes documented. On metoprolol 50 mg BID. Started yesterday.",
      assessment: "Symptomatic bradycardia. Likely beta-blocker induced. HR 38 with symptoms — requires escalation.",
      recommendation: "Notify RN immediately. Do not administer next metoprolol dose. Monitor continuous. Patient on bed rest.",
    },
    learningObjectives: [
      "Identify symptomatic bradycardia on the monitor",
      "Distinguish sinus bradycardia from AV block patterns",
      "Apply RPN scope of practice: monitoring, reporting, holding meds within scope",
      "Recognise when bradycardia is a pharmacological adverse effect",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Identify HR 38 with symptoms — immediate escalation", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Hold next dose of beta-blocker (within RPN scope)", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 2, description: "Position patient supine, continuous monitoring", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document HR, rhythm, and time of bradycardia onset",
      "Record patient symptoms: dizziness, LOC, chest pain",
      "Document RN notification time",
      "Note metoprolol withheld if applicable",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses"],
    tags: ["bradycardia", "beta-blocker", "telemetry", "rpn", "escalation"],
  },

  {
    id: "rpn-code-assist",
    title: "Code Blue: RPN Assist Role",
    profession: ["RPN"],
    specialty: ["med-surg", "telemetry"],
    conditionKey: "vt_to_vf",
    pathwayId: "cardiac_arrest",
    difficulty: "developing",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    openingStage: "severe",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "You respond to a code blue in room 318. The RN team leader assigns you to chest compressions. The patient is unresponsive with VF on the monitor.",
    sbar: {
      situation: "VF on monitor. Patient unresponsive. CPR in progress. You are assigned to compressions.",
      background: "76F, cardiac history. Collapse witnessed. Code called 2 minutes ago.",
      assessment: "VF cardiac arrest. ACLS protocol running. Your role: high-quality CPR, rotation every 2 minutes.",
      recommendation: "Compressions 100–120/min, depth 5–6 cm, full recoil, minimal interruptions. Rotate on team leader signal.",
    },
    learningObjectives: [
      "Apply high-quality CPR technique within the RPN scope",
      "Understand team roles in a code blue",
      "Know when and how to rotate compressions",
      "Assist with AED/defibrillator preparation",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Begin high-quality compressions immediately", interventionKey: "cpr", isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Confirm role with team leader", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document your assigned role in the code",
      "Record compression start time",
      "Note rotation times (every 2 minutes per team lead)",
    ],
    ngnFormats: ["sata"],
    primaryNcjmmDomains: ["take_action"],
    tags: ["code-blue", "cpr", "rpn", "team-assist", "arrest"],
  },

  {
    id: "rpn-oxygen-escalation",
    title: "Oxygen Escalation: Worsening Hypoxia",
    profession: ["RPN"],
    specialty: ["med-surg", "telemetry"],
    conditionKey: "heart_failure",
    pathwayId: "respiratory_failure",
    difficulty: "foundational",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mrs. O'Brien, 77F, on 2L nasal cannula. SpO₂ was 96% at 0800. Now SpO₂ 89%, she is becoming more breathless.",
    sbar: {
      situation: "SpO₂ 89% (was 96%), RR 26, HR 108. Complaining of breathlessness. No new cough or fever.",
      background: "77F, CHF, known COPD. On 2L NC as baseline. Current meds: furosemide, lisinopril, metoprolol.",
      assessment: "Acute-on-chronic respiratory deterioration. CHF exacerbation vs COPD exacerbation vs new PE.",
      recommendation: "Increase O₂ to 4L NC per standing order. Notify RN. Document vital signs trend.",
    },
    learningObjectives: [
      "Identify worsening SpO₂ trend on the monitor",
      "Apply oxygen escalation within RPN scope (per standing order)",
      "Recognise when escalation beyond RPN scope is required",
      "Monitor SpO₂ continuously after oxygen adjustment",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Recognise SpO₂ < 92% and notify RN", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Increase oxygen per standing order", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Reassess SpO₂ every 5 minutes", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document SpO₂ trend with times",
      "Record O₂ delivery change: time, flow rate, method",
      "Document RN notification and response",
      "Note patient symptoms and positioning",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues"],
    tags: ["oxygen", "spo2", "copd", "chf", "escalation", "rpn"],
  },

  {
    id: "rpn-telemetry-response",
    title: "Telemetry Response: Alarm Interpretation",
    profession: ["RPN"],
    specialty: ["telemetry"],
    conditionKey: "afib_rvr",
    pathwayId: "tachyarrhythmia",
    difficulty: "foundational",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "You are monitoring 12 telemetry patients. Three alarms sound simultaneously. You must triage and respond appropriately.",
    sbar: {
      situation: "Alarm 1: HR 162 AFib — Room 204. Alarm 2: Low battery. Alarm 3: Lead disconnect — Room 208. Patient in Room 204 is symptomatic.",
      background: "Room 204: 68F, known AFib on diltiazem. Room 208: 72M, post-op monitoring.",
      assessment: "Alarm triage required. Room 204 is a priority (symptomatic tachycardia). Other alarms are technical.",
      recommendation: "Respond to Room 204 first. Notify RN about symptomatic AFib. Fix technical alarms second.",
    },
    learningObjectives: [
      "Apply clinical alarm triage: safety vs technical alarms",
      "Identify false alarms vs true clinical events",
      "Understand alarm fatigue and its clinical consequences",
      "Prioritise response based on patient risk",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Triage clinical vs technical alarms", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 2, description: "Respond to symptomatic AFib first — Room 204", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Notify RN of HR 162 with symptoms", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document alarm response sequence with times",
      "Record patient assessment in Room 204",
      "Note RN notification and instructions",
    ],
    ngnFormats: ["prioritization", "sata"],
    primaryNcjmmDomains: ["recognize_cues", "prioritize_hypotheses"],
    tags: ["telemetry", "alarm-management", "triage", "rpn"],
  },

  // ══ NP SIMULATIONS ═══════════════════════════════════════════════════════════

  {
    id: "np-acs-differential",
    title: "ACS Differential: STEMI vs NSTEMI vs UA",
    profession: ["NP"],
    specialty: ["emergency", "cardiac", "np-practice"],
    conditionKey: "stemi",
    pathwayId: "stemi",
    difficulty: "advanced",
    estimatedMinutes: 30,
    monitorMode: "np",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "You are the NP covering the chest pain unit. Mr. Abramowitz, 62M, presents with 2-hour substernal pressure. ECG and troponin results pending.",
    sbar: {
      situation: "HR 96, BP 148/88, SpO₂ 97%. Chest pressure 7/10. Monitor shows 1.5 mm ST elevation in V2–V4 with T-wave inversions in V5–V6.",
      background: "62M, HTN, T2DM, CKD stage 2. Prior PCI 3 years ago to LAD. On aspirin, atorvastatin. Troponin-I: 0.14 → 0.38 (rising).",
      assessment: "STEMI vs early NSTEMI. Pattern: anterior ST elevation with rising troponin. GRACE score high-risk.",
      recommendation: "Activate STEMI protocol if STe confirmed on repeat ECG or escalates to NP/cardiologist shared decision.",
    },
    learningObjectives: [
      "Differentiate STEMI, NSTEMI, and UA using ECG, troponin, and clinical picture",
      "Apply GRACE score for NSTEMI risk stratification",
      "Understand timing of revascularisation: immediate (STEMI) vs early invasive (NSTEMI)",
      "Lead the ACS bundle: ASA, anticoagulation, beta-blocker, cardiologist consult",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Interpret ECG findings and classify ACS type", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Initiate ACS bundle (ASA, anticoagulation)", interventionKey: "supplemental_o2", isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Cardiology/attending consultation", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document ECG interpretation with STEMI vs NSTEMI classification",
      "Record troponin trend with times",
      "Document GRACE score calculation",
      "Note cardiologist consultation time and management plan",
    ],
    ngnFormats: ["bowtie", "matrix", "cloze"],
    primaryNcjmmDomains: ["analyze_cues", "prioritize_hypotheses", "generate_solutions"],
    tags: ["acs", "stemi", "nstemi", "np", "cardiology", "differential"],
  },

  {
    id: "np-complex-shock",
    title: "Complex Shock: Mixed Aetiology Workup",
    profession: ["NP"],
    specialty: ["icu", "emergency", "np-practice"],
    conditionKey: "complex_shock",
    pathwayId: "shock",
    difficulty: "advanced",
    estimatedMinutes: 35,
    monitorMode: "np",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Rosenberg, 77M, 3-day ICU stay post-CABG. Now hypotensive despite fluids. CVP 18. Your task: determine shock aetiology and initiate appropriate treatment.",
    sbar: {
      situation: "MAP 52, HR 108, CVP 18, CO 2.8 L/min, ScvO₂ 54%. On norepinephrine. Fluid-unresponsive. WBC 18.",
      background: "77M, CABG × 3 post-op day 3. Prior EF 30%. Possible anastomotic infection — fever 38.8°C. Troponin mildly elevated.",
      assessment: "Mixed shock: cardiogenic (low CO, EF 30%) vs septic (fever, WBC 18, vasodilated). ScvO₂ 54% indicates mixed venous desaturation.",
      recommendation: "Echo to assess wall motion and volume status. Consider inotrope (dobutamine) if cardiogenic component dominant. Expand antibiotic coverage.",
    },
    learningObjectives: [
      "Classify shock by haemodynamic profile: CO/SVR/CVP/ScvO₂",
      "Distinguish and manage mixed-aetiology shock",
      "Interpret advanced haemodynamic monitoring (PA catheter or point-of-care echo)",
      "Titrate vasopressors and inotropes based on haemodynamic goals",
    ],
    criticalActions: [
      { timeLimitTicks: 3, description: "Classify shock from haemodynamic data", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Vasopressor titration", interventionKey: "norepinephrine", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Echo / haemodynamic reassessment plan", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document haemodynamic classification with reasoning",
      "Record vasopressor doses, titration, and MAP response",
      "Document echo findings and interpretation",
      "Note management plan with intensivist",
    ],
    ngnFormats: ["matrix", "bowtie", "cloze"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "evaluate_outcomes"],
    tags: ["complex-shock", "hemodynamics", "icu", "np", "mixed-shock", "cardiogenic"],
  },

  {
    id: "np-stable-vt",
    title: "Stable VT: Management Decision",
    profession: ["NP"],
    specialty: ["cardiac", "emergency", "np-practice"],
    conditionKey: "vt_to_vf",
    pathwayId: "tachyarrhythmia",
    difficulty: "advanced",
    estimatedMinutes: 25,
    monitorMode: "np",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Kato, 54M, in the cardiac step-down unit. Monitor alarming — wide-complex tachycardia, rate 158. He is awake, alert, and talking to you.",
    sbar: {
      situation: "Wide-complex tachycardia rate 158. BP 102/68. Alert and conversational. Mild palpitations, no chest pain or dyspnoea.",
      background: "54M, EF 35%, prior NSTEMI 6 months ago. On amiodarone 200 mg daily. History of non-sustained VT on Holter.",
      assessment: "Stable monomorphic VT. ACLS stable-VT algorithm: chemical cardioversion (amiodarone) vs electrical cardioversion.",
      recommendation: "Amiodarone 150 mg IV bolus over 10 minutes. Prepare for synchronized cardioversion if unstable. Cardiology at bedside.",
    },
    learningObjectives: [
      "Classify VT as stable vs unstable using haemodynamic criteria",
      "Apply ACLS stable-VT algorithm: antiarrhythmics before cardioversion",
      "Choose between amiodarone, procainamide, and sotalol based on cardiac history",
      "Identify when to escalate from chemical to electrical cardioversion",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Confirm stable haemodynamics — NOT immediate shock", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Amiodarone 150 mg IV bolus", interventionKey: "amiodarone", isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Cardiology bedside notification", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Reassess rhythm after amiodarone", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document VT rate, morphology, and haemodynamic stability at time of recognition",
      "Record amiodarone dose, time, administration rate, and rhythm response",
      "Document cardiology consultation time and plan",
      "Note patient symptoms throughout",
    ],
    ngnFormats: ["bowtie", "sata", "prioritization"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "take_action"],
    tags: ["vt", "stable-vt", "amiodarone", "acls", "np", "cardiac"],
  },

  {
    id: "np-afib-risk",
    title: "AFib Risk Stratification: CHA₂DS₂-VASc Decision",
    profession: ["NP"],
    specialty: ["cardiac", "ambulatory", "np-practice"],
    conditionKey: "afib_rvr",
    pathwayId: "tachyarrhythmia",
    difficulty: "proficient",
    estimatedMinutes: 20,
    monitorMode: "np",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mrs. Olsen, 71F, presents to your NP clinic with newly diagnosed paroxysmal AFib confirmed on 2-week Holter. She is haemodynamically stable.",
    sbar: {
      situation: "HR 88 at rest, BP 138/84. Monitor shows sinus rhythm with occasional PACs. Paroxysmal AFib confirmed on Holter (3 episodes).",
      background: "71F, HTN, T2DM, no prior stroke/TIA, non-smoker. CrCl 62 mL/min. No current anticoagulation.",
      assessment: "New paroxysmal AFib. CHA₂DS₂-VASc score calculation required for anticoagulation decision.",
      recommendation: "CHA₂DS₂-VASc score 3 (age ≥ 65, female, hypertension) → anticoagulation indicated. DOAC preferred over warfarin.",
    },
    learningObjectives: [
      "Calculate CHA₂DS₂-VASc score accurately",
      "Apply current guidelines for AFib anticoagulation decisions",
      "Choose appropriate anticoagulant based on renal function (CrCl 62)",
      "Discuss rate vs rhythm control strategy in the outpatient setting",
    ],
    criticalActions: [
      { timeLimitTicks: 3, description: "Calculate CHA₂DS₂-VASc score", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Initiate appropriate anticoagulation", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Rate control target: HR < 80 at rest", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document CHA₂DS₂-VASc score with components",
      "Record anticoagulation choice, dose, and rationale",
      "Document rate control target and medication plan",
      "Note patient education provided",
    ],
    ngnFormats: ["matrix", "cloze", "bowtie"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions"],
    tags: ["afib", "anticoagulation", "chadsvasc", "doac", "np", "risk-stratification"],
  },

  {
    id: "np-mobitz-pacing",
    title: "Mobitz II: Pacing Decision",
    profession: ["NP"],
    specialty: ["cardiac", "icu", "np-practice"],
    conditionKey: "increased_icp",
    pathwayId: "bradycardia",
    difficulty: "advanced",
    estimatedMinutes: 25,
    monitorMode: "np",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Mr. Yamamoto, 78M, telemetry day 2 post-inferior MI. New finding on strip: constant PR interval with intermittent dropped QRS complexes.",
    sbar: {
      situation: "HR dropping to 38 on intermittent dropped beats. Consistent PR interval. BP 96/58 when bradycardic. Mildly symptomatic.",
      background: "78M, inferior MI (RCA territory) post-PCI. On aspirin, ticagrelor, metoprolol. Inferior STEMI involves RCA → AV node supply.",
      assessment: "Mobitz Type II second-degree AV block. High risk of complete heart block. Pacing threshold likely to be met.",
      recommendation: "Transcutaneous pacing pads in place immediately. Atropine ineffective for Mobitz II. Cardiology for permanent pacemaker discussion.",
    },
    learningObjectives: [
      "Distinguish Mobitz Type I (Wenckebach) from Type II on ECG",
      "Understand why Mobitz II has higher risk than Type I",
      "Know that atropine is ineffective for Mobitz II (infranodal block)",
      "Apply transcutaneous pacing criteria for symptomatic Mobitz II",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify Mobitz II: fixed PR + dropped QRS", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Place transcutaneous pacing pads", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Cardiology for urgent pacemaker evaluation", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document ECG rhythm with Mobitz classification rationale",
      "Record HR and BP at time of symptomatic bradycardia",
      "Document pacing pad placement time and threshold",
      "Note cardiology consultation time",
    ],
    ngnFormats: ["bowtie", "sata", "cloze"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions"],
    tags: ["mobitz-ii", "av-block", "pacing", "ecg", "np", "conduction"],
  },

  {
    id: "np-multi-system-failure",
    title: "Multi-System Failure: ICU Management",
    profession: ["NP"],
    specialty: ["icu", "np-practice"],
    conditionKey: "multi_system_failure",
    pathwayId: "shock",
    difficulty: "advanced",
    estimatedMinutes: 40,
    monitorMode: "np",
    openingStage: "severe",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Ms. Beaumont, 58F, ICU day 7 with sepsis-induced multiorgan dysfunction. Sequential organ failure is worsening.",
    sbar: {
      situation: "MAP 56 (on norepi + vasopressin). ARDS: FiO₂ 0.85, PaO₂/FiO₂ 88. AKI: Cr 4.2, anuric. GCS 8. Lactate 7.1.",
      background: "58F, community-acquired pneumonia → SIRS → MODS. Day 7. Renal team recommending CRRT. ICU attending present.",
      assessment: "SOFA score 16. Multiorgan failure: respiratory, renal, cardiovascular, neurological. Prognosis guarded.",
      recommendation: "Goals-of-care discussion needed. CRRT initiation. Prone positioning ARDS. Family meeting today.",
    },
    learningObjectives: [
      "Calculate and interpret SOFA score for severity assessment",
      "Coordinate multidisciplinary ICU management of MODS",
      "Apply CRRT initiation criteria for AKI in sepsis",
      "Lead a goals-of-care family discussion in the ICU setting",
    ],
    criticalActions: [
      { timeLimitTicks: 3, description: "Calculate SOFA score and communicate prognosis", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 4, description: "Vasopressor optimisation", interventionKey: "norepinephrine", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "CRRT initiation referral", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document SOFA score with components",
      "Record organ support modalities and settings",
      "Document family meeting: participants, content, goals-of-care outcome",
      "Note palliative care involvement if applicable",
    ],
    ngnFormats: ["matrix", "bowtie", "prioritization"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "evaluate_outcomes"],
    tags: ["mods", "sofa", "icu", "np", "crrt", "ards", "multi-organ"],
  },

  // ══ RT SIMULATIONS ═══════════════════════════════════════════════════════════

  {
    id: "rt-ards",
    title: "ARDS: Lung-Protective Ventilation",
    profession: ["RT"],
    specialty: ["icu", "rt"],
    conditionKey: "ards",
    pathwayId: "respiratory_failure",
    difficulty: "advanced",
    estimatedMinutes: 30,
    monitorMode: "rt",
    defaultOverlay: true,
    showInterventions: true,
    patientBrief: "You are called to adjust ventilator settings for Mr. Nguyen, 52M, day 3 COVID-ARDS. Current settings inadequate — PaO₂/FiO₂ ratio 88.",
    sbar: {
      situation: "FiO₂ 1.0, PEEP 14, PIP 52, Plateau 46, TV 540 mL (patient weighs 80 kg, IBW 70 kg). SpO₂ 88%.",
      background: "52M, COVID-19 ARDS day 3. Previous TB. CXR: bilateral 'white out.' Compliance 16 mL/cmH₂O. Auto-PEEP suspected.",
      assessment: "Severe ARDS. Volutrauma and barotrauma risk. Plateau > 30. TV too high for IBW. Auto-PEEP contributing.",
      recommendation: "Reduce TV to 6 mL/kg IBW (420 mL). Increase PEEP to 18. Consider ECMO consult if no improvement within 2h.",
    },
    learningObjectives: [
      "Calculate ideal body weight and correct tidal volume for ARDSnet",
      "Titrate PEEP using the ARDSnet PEEP/FiO₂ table",
      "Measure static compliance and plateau pressure correctly",
      "Identify auto-PEEP using expiratory hold manoeuvre",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Calculate IBW and correct TV (6 mL/kg = 420 mL)", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Increase PEEP — reassess oxygenation", interventionKey: "increase_peep", isHarmIfMissed: true },
      { timeLimitTicks: 5, description: "Measure plateau pressure with inspiratory hold", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document IBW calculation and target TV derivation",
      "Record vent settings pre and post adjustment",
      "Document plateau pressure measurement results",
      "Note ECMO consult if initiated",
    ],
    ngnFormats: ["bowtie", "cloze", "matrix"],
    primaryNcjmmDomains: ["analyze_cues", "generate_solutions", "take_action"],
    tags: ["ards", "ventilator", "ardsnet", "peep", "rt", "lung-protective"],
  },

  {
    id: "rt-auto-peep",
    title: "Auto-PEEP: Identification and Management",
    profession: ["RT"],
    specialty: ["icu", "rt"],
    conditionKey: "rt_auto_peep",
    pathwayId: "respiratory_failure",
    difficulty: "advanced",
    estimatedMinutes: 20,
    monitorMode: "rt",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "You are called to bedside — patient with severe COPD exacerbation, intubated. The flow waveform shows expiratory flow not returning to zero.",
    sbar: {
      situation: "RR 24, I:E 1:1.5 (insufficient). Expiratory flow doesn't return to baseline. Expiratory hold measures total PEEP 20 vs set PEEP 8 — intrinsic PEEP 12.",
      background: "71M, COPD GOLD IV, intubated for exacerbation. Currently: AC/VC, TV 500, RR 24, PEEP 8.",
      assessment: "Auto-PEEP 12 cmH₂O from dynamic hyperinflation. I:E ratio insufficient for high-resistance COPD lungs.",
      recommendation: "Reduce RR to 12. Increase flow rate to shorten TI and allow longer TE. Consider sedation increase. Bronchodilators.",
    },
    learningObjectives: [
      "Identify auto-PEEP from the flow waveform (shark fin pattern)",
      "Measure intrinsic PEEP using the expiratory hold manoeuvre",
      "Adjust ventilator parameters to allow complete exhalation",
      "Understand the consequence of auto-PEEP: gas trapping, cardiovascular compromise",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify shark-fin pattern on flow waveform", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Perform expiratory hold — measure intrinsic PEEP", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Reduce RR and increase expiratory time", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document flow waveform interpretation",
      "Record intrinsic PEEP measurement",
      "Document ventilator adjustments made and I:E rationale",
      "Note bronchodilator administration",
    ],
    ngnFormats: ["cloze", "bowtie", "sata"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues"],
    tags: ["auto-peep", "copd", "ventilator", "rt", "waveform"],
  },

  {
    id: "rt-vent-asynchrony",
    title: "Ventilator Asynchrony: Recognition and Correction",
    profession: ["RT"],
    specialty: ["icu", "rt"],
    conditionKey: "rt_vent_asynchrony",
    pathwayId: "respiratory_failure",
    difficulty: "advanced",
    estimatedMinutes: 20,
    monitorMode: "rt",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mr. Osei, 48M, post-op abdominal surgery, ventilated. He appears uncomfortable, RN reports 'bucking the vent.' Waveforms show irregular double-triggering.",
    sbar: {
      situation: "Double-triggering visible on pressure and flow waveforms. Patient appears distressed. SpO₂ 93%, RR (patient effort) 28, vent RR 16.",
      background: "48M, laparotomy day 1. Light sedation (propofol 20 mcg/kg/min). Mode: AC/PC. Drive pressure triggering at -2 cmH₂O.",
      assessment: "Patient-ventilator asynchrony — double triggering. Patient's drive exceeding vent PC breath cycle. Sedation may be insufficient.",
      recommendation: "Increase trigger sensitivity. Consider PS mode. Review sedation adequacy. Assess pain.",
    },
    learningObjectives: [
      "Identify common asynchrony patterns on pressure/flow waveforms",
      "Distinguish double-triggering, missed triggers, and flow starvation",
      "Adjust vent parameters to reduce asynchrony",
      "Evaluate sedation and pain as contributing factors",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify asynchrony pattern on waveform", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Adjust trigger sensitivity / flow settings", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Assess and communicate sedation need to RN", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document asynchrony type and waveform findings",
      "Record vent settings pre and post adjustment",
      "Document sedation assessment (RASS/CPOT)",
      "Note pain assessment",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues"],
    tags: ["asynchrony", "ventilator", "waveform", "sedation", "rt"],
  },

  {
    id: "rt-accidental-extubation",
    title: "Accidental Extubation: Airway Emergency",
    profession: ["RT"],
    specialty: ["icu", "rt"],
    conditionKey: "rt_accidental_extubation",
    pathwayId: "respiratory_failure",
    difficulty: "advanced",
    estimatedMinutes: 15,
    monitorMode: "rt",
    openingStage: "developing",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "Code airway called in ICU room 14. You arrive to find a 72F patient who pulled out her ETT while confused. SpO₂ dropping. BVM in hand.",
    sbar: {
      situation: "SpO₂ 78%, RR 32 (laboured), BVM in progress. No ETT in place. Jaw clenching. Stridor audible. HR 142.",
      background: "72F, intubated post-cardiac arrest day 3. RASS -1 (light sedation). Attempted self-extubation.",
      assessment: "Accidental self-extubation. Difficult airway anticipated (Mallampati III on admission). Deteriorating rapidly.",
      recommendation: "BVM until RSI team ready. Suction airway. Call anaesthesiology. Prepare RSI medications and 7.0 ETT.",
    },
    learningObjectives: [
      "Perform effective BVM ventilation technique",
      "Assist with RSI preparation as airway team member",
      "Maintain oxygenation during the pre-intubation window",
      "Confirm ETT placement post-intubation using EtCO₂",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Effective BVM ventilation — 2-person technique if needed", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "Call anaesthesiology code airway", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "Confirm ETT placement with EtCO₂ after reintubation", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document extubation time and circumstances",
      "Record O₂ delivery during pre-intubation period",
      "Document intubation: time, ETT size, depth, confirmation method",
      "Note SpO₂ nadir and recovery trend",
    ],
    ngnFormats: ["bowtie", "sata"],
    primaryNcjmmDomains: ["take_action", "evaluate_outcomes"],
    tags: ["extubation", "airway-emergency", "bvm", "rsi", "rt"],
  },

  {
    id: "rt-acls-role",
    title: "Cardiac Arrest: RT ACLS Role",
    profession: ["RT"],
    specialty: ["icu", "rt", "emergency"],
    conditionKey: "vt_to_vf",
    pathwayId: "cardiac_arrest",
    difficulty: "advanced",
    estimatedMinutes: 20,
    monitorMode: "rt",
    openingStage: "severe",
    defaultOverlay: false,
    showInterventions: true,
    patientBrief: "You respond to a code blue. Patient is a 64M with VF arrest. CPR in progress. Team leader directs you to manage the airway.",
    sbar: {
      situation: "VF arrest. CPR × 3 minutes. BVM ventilation in progress. O₂ at 100%. SpO₂ not obtainable.",
      background: "64M, ARDS, intubated on day 4. Dislodged ETT 5 minutes ago immediately before arrest.",
      assessment: "VF arrest with lost airway. Dual priority: airway management + CPR support. Airway first.",
      recommendation: "Intubate ASAP with RSI. Do not interrupt CPR > 10 seconds. Confirm with EtCO₂ — rising EtCO₂ suggests ROSC.",
    },
    learningObjectives: [
      "Manage the airway during active CPR with minimal interruptions",
      "Use EtCO₂ to assess CPR quality and identify ROSC",
      "Understand the ventilation rate during cardiac arrest (10/min)",
      "Apply waveform capnography to confirm ETT placement in arrest",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Continue BVM with 100% FiO₂ during compressions", interventionKey: "supplemental_o2", isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Intubate with < 10 second CPR pause", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 4, description: "EtCO₂ monitoring — identify ROSC (EtCO₂ > 40)", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document airway management sequence and devices used",
      "Record intubation time and CPR interruption duration",
      "Document EtCO₂ values during CPR",
      "Note ROSC time if achieved",
    ],
    ngnFormats: ["bowtie", "sata"],
    primaryNcjmmDomains: ["take_action", "evaluate_outcomes"],
    tags: ["acls", "cardiac-arrest", "airway", "etco2", "rosc", "rt"],
  },

  {
    id: "rt-etco2-rosc",
    title: "EtCO₂ Monitoring: ROSC Recognition",
    profession: ["RT"],
    specialty: ["icu", "rt", "emergency"],
    conditionKey: "vt_to_vf",
    pathwayId: "cardiac_arrest",
    difficulty: "proficient",
    estimatedMinutes: 15,
    monitorMode: "rt",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "You are providing ventilation during CPR for a 55M in PEA arrest. EtCO₂ has been 12–14 mmHg for 8 minutes. It suddenly rises to 42.",
    sbar: {
      situation: "EtCO₂ jumps from 14 → 42 mmHg. CPR ongoing at 110/min. No rhythm check was initiated.",
      background: "55M, PEA arrest × 10 minutes. Epinephrine given × 2. Ventilated via ETT. Compressions in progress.",
      assessment: "Sudden EtCO₂ rise (> 40) during CPR strongly suggests return of spontaneous circulation (ROSC).",
      recommendation: "Halt CPR — call for pulse check. Confirm ROSC. Post-ROSC care: oxygenation target 94–98%, normothermia, 12-lead ECG.",
    },
    learningObjectives: [
      "Interpret EtCO₂ waveform during CPR as a surrogate for cardiac output",
      "Recognise sudden EtCO₂ rise ≥ 40 mmHg as probable ROSC indicator",
      "Apply post-ROSC ventilation targets (SpO₂ 94–98%)",
      "Understand why hyperoxia is harmful post-ROSC",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Identify EtCO₂ rise to 42 mmHg", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 1, description: "Alert team leader to halt CPR — pulse check", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 3, description: "Post-ROSC: SpO₂ 94–98%, normothermia ventilation targets", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document EtCO₂ values during CPR (q2 min)",
      "Record time of EtCO₂ rise and ROSC confirmation",
      "Document post-ROSC vent settings and SpO₂ target",
    ],
    ngnFormats: ["cloze", "bowtie"],
    primaryNcjmmDomains: ["recognize_cues", "evaluate_outcomes"],
    tags: ["etco2", "rosc", "cpr", "cardiac-arrest", "rt", "capnography"],
  },

  // ══ NEW GRADUATE SIMULATIONS ══════════════════════════════════════════════════

  {
    id: "ng-documentation",
    title: "Documentation 101: Vital Sign Charting",
    profession: ["NEW_GRAD"],
    specialty: ["foundational"],
    conditionKey: "sepsis",
    pathwayId: "sepsis",
    difficulty: "foundational",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Your first patient: Mr. Singh, 68M, post-op day 1 hernia repair. You are doing your 0800 assessment and vital signs.",
    sbar: {
      situation: "HR 88, BP 118/72, RR 14, SpO₂ 97%, Temp 37.2°C. Patient awake, alert, comfortable.",
      background: "68M, hernia repair yesterday under spinal. No past medical history. Currently on IV morphine PRN.",
      assessment: "Vitals within normal limits. Post-op recovery on track.",
      recommendation: "Document vitals, continue monitoring every 4 hours, report any deviations from normal.",
    },
    learningObjectives: [
      "Identify normal vital sign ranges for an adult patient",
      "Document vital signs accurately in the correct fields",
      "Understand the frequency of vital sign monitoring post-operatively",
      "Know which vital sign changes require immediate notification",
    ],
    criticalActions: [
      { timeLimitTicks: 5, description: "Complete and document all vital signs", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 6, description: "Identify any vital sign outside normal range", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Document all five vital signs with correct units",
      "Record time of assessment",
      "Note patient's general appearance and comfort level",
      "Document any patient concerns or complaints",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues"],
    tags: ["documentation", "new-grad", "foundational", "vital-signs"],
  },

  {
    id: "ng-stemi-recognition",
    title: "STEMI Recognition: New Grad Introduction",
    profession: ["NEW_GRAD"],
    specialty: ["telemetry", "med-surg"],
    conditionKey: "stemi",
    pathwayId: "stemi",
    difficulty: "foundational",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "You are caring for Mr. Lee, 60M. The telemetry monitor alarms. You see a change in the ECG pattern and the patient says 'I feel funny in my chest.'",
    sbar: {
      situation: "New ST elevation pattern on monitor. HR 98, BP 132/80, SpO₂ 97%. Patient alert but anxious, chest discomfort.",
      background: "60M, history of hypertension, admitted for monitoring after brief palpitations.",
      assessment: "Possible STEMI — ST changes on monitor with new symptoms. Requires immediate notification.",
      recommendation: "Call RN immediately. Do not leave patient. Press call bell for help. Keep patient calm.",
    },
    learningObjectives: [
      "Recognise that ST elevation on a monitor is a critical finding",
      "Know the first action: call for help — not independent management",
      "Stay calm and communicate clearly to the patient",
      "Understand the basics of what ST elevation means clinically",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Recognise ST change — call for help immediately", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Stay at bedside with patient", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document time of ST change noted",
      "Record patient symptoms and vital signs",
      "Document who you called and when",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["recognize_cues"],
    tags: ["stemi", "recognition", "escalation", "new-grad", "telemetry"],
  },

  {
    id: "ng-rapid-response",
    title: "Rapid Response: When and How to Call",
    profession: ["NEW_GRAD"],
    specialty: ["med-surg"],
    conditionKey: "sepsis",
    pathwayId: "sepsis",
    difficulty: "foundational",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mrs. Collins, 74F, 3 hours after your shift started, is 'not herself' per the family. You go to assess — she is drowsy and her vital signs have changed.",
    sbar: {
      situation: "SpO₂ 91% (was 97%), HR 112 (was 82), BP 88/52 (was 118/70), RR 24. Patient rouses to voice, confused.",
      background: "74F, post-op day 4 hip replacement. No prior respiratory history. Family at bedside noting decline over 2 hours.",
      assessment: "Acute change from baseline across multiple parameters. MEWS score 6 — meets rapid response criteria.",
      recommendation: "Call Rapid Response Team NOW. Do not attempt to manage independently. SBAR ready.",
    },
    learningObjectives: [
      "Identify when Rapid Response Team (RRT) criteria are met",
      "Overcome the hesitation to call for help as a new graduate",
      "Deliver a clear SBAR communication to the RRT",
      "Understand that calling RRT is never wrong — delayed calls cause harm",
    ],
    criticalActions: [
      { timeLimitTicks: 1, description: "Recognise multiple vital sign deviations", interventionKey: null, isHarmIfMissed: true },
      { timeLimitTicks: 2, description: "Activate Rapid Response Team", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document all vital signs with times",
      "Record RRT activation time",
      "Document SBAR communicated to RRT",
    ],
    ngnFormats: ["sata", "prioritization"],
    primaryNcjmmDomains: ["recognize_cues", "take_action"],
    tags: ["rapid-response", "new-grad", "escalation", "mews"],
  },

  {
    id: "ng-code-observer",
    title: "Code Blue Observer: Learning the Protocol",
    profession: ["NEW_GRAD"],
    specialty: ["foundational"],
    conditionKey: "vt_to_vf",
    pathwayId: "cardiac_arrest",
    difficulty: "foundational",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    openingStage: "severe",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "A code blue is called on your ward. As a new grad < 3 months, your role is observer and runner. You stand at the foot of the bed and learn the ACLS protocol in real time.",
    sbar: {
      situation: "VF arrest. Code team running ACLS. Defib in use. CPR ongoing. Team lead assigning roles.",
      background: "Patient details are secondary — your focus is the ACLS algorithm and team dynamics.",
      assessment: "Observer role: watch and learn rhythm identification, defibrillation, medication administration, team communication.",
      recommendation: "Stand at foot of bed. Watch for rhythm checks. Note each medication, timing, and team communication. Get help if asked.",
    },
    learningObjectives: [
      "Observe the ACLS algorithm in sequence",
      "Identify VF and the defibrillation response on the monitor",
      "Understand team roles in a cardiac arrest",
      "Recognise what ROSC looks like on the monitor",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Identify VF on monitor as observer", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Note defibrillation delivered and rhythm reassessment", interventionKey: null, isHarmIfMissed: false },
    ],
    documentationPrompts: [
      "Post-code reflection: describe the ACLS algorithm steps you observed",
      "Note which medications were given and when",
      "Describe the team communication you witnessed",
    ],
    ngnFormats: ["sata"],
    primaryNcjmmDomains: ["recognize_cues"],
    tags: ["code-blue", "observer", "acls", "new-grad", "learning"],
  },

  {
    id: "ng-deteriorating-patient",
    title: "Deteriorating Patient: Early Warning Signs",
    profession: ["NEW_GRAD"],
    specialty: ["med-surg", "telemetry"],
    conditionKey: "sepsis",
    pathwayId: "sepsis",
    difficulty: "developing",
    estimatedMinutes: 20,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mr. Johnson, 57M, post-op day 2 bowel resection. At 0900 he looked fine. At 1100 you are less certain — he seems 'off.'",
    sbar: {
      situation: "HR up from 82 → 104 over 2 hours. BP 118/72 → 102/64. RR 14 → 20. SpO₂ 97% → 94%. Temp 38.6°C.",
      background: "57M, post-op day 2. Wound intact. No active bleeding. On IV antibiotics for pre-op prophylaxis.",
      assessment: "Gradual vital sign deterioration — subtle but real. MEWS trending up. Escalation decision point.",
      recommendation: "Trust your instincts — call RN preceptor now. Describe the trend, not just current values.",
    },
    learningObjectives: [
      "Recognise subtle vital sign trends as early warning signs",
      "Understand why trends matter more than single readings",
      "Build confidence to escalate even with ambiguous findings",
      "Apply MEWS to support escalation decisions",
    ],
    criticalActions: [
      { timeLimitTicks: 3, description: "Identify vital sign trend — multiple parameters drifting", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 4, description: "Call RN preceptor — describe trend", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document each set of vitals with times — trend is visible",
      "Record your concern and what you noticed",
      "Document preceptor notification and advice",
    ],
    ngnFormats: ["sata", "cloze", "prioritization"],
    primaryNcjmmDomains: ["recognize_cues", "analyze_cues"],
    tags: ["deterioration", "trend", "new-grad", "mews", "escalation"],
  },

  {
    id: "ng-escalation-practice",
    title: "Escalation Practice: SBAR Communication",
    profession: ["NEW_GRAD"],
    specialty: ["foundational"],
    conditionKey: "heart_failure",
    pathwayId: "respiratory_failure",
    difficulty: "developing",
    estimatedMinutes: 15,
    monitorMode: "new_grad",
    defaultOverlay: true,
    showInterventions: false,
    patientBrief: "Mrs. Tan, 79F, on your unit with worsening dyspnoea. SpO₂ dropping. Your preceptor is with another patient. You must call the physician independently.",
    sbar: {
      situation: "SpO₂ 90% (was 96%), RR 28, HR 108. Increasing dyspnoea. Bilateral crackles. New peripheral oedema.",
      background: "79F, CHF EF 30%, admitted 2 days ago. Currently on 2L NC. Daily weight up 2.5 kg from yesterday.",
      assessment: "Acute CHF exacerbation — fluid overload with pulmonary congestion.",
      recommendation: "Your task: construct and deliver the SBAR to the physician independently.",
    },
    learningObjectives: [
      "Construct a complete SBAR communication independently",
      "Overcome hesitation when calling a physician as a new graduate",
      "Anticipate the physician's questions and have data ready",
      "Understand that clear communication saves lives",
    ],
    criticalActions: [
      { timeLimitTicks: 2, description: "Assemble all vital signs and relevant history before calling", interventionKey: null, isHarmIfMissed: false },
      { timeLimitTicks: 3, description: "Make the physician call — SBAR delivery", interventionKey: null, isHarmIfMissed: true },
    ],
    documentationPrompts: [
      "Document physician contacted: name, time, method",
      "Record SBAR communicated and orders received",
      "Document vital signs at time of call",
    ],
    ngnFormats: ["sata", "cloze"],
    primaryNcjmmDomains: ["prioritize_hypotheses", "take_action"],
    tags: ["sbar", "communication", "escalation", "new-grad", "physician-call"],
  },
];

// ─── Lookup helpers ───────────────────────────────────────────────────────────

export function getSimulation(id: string): SimulationDefinition | null {
  return SIMULATION_CATALOG.find((s) => s.id === id) ?? null;
}

export function getSimulationsByProfession(profession: SimulationProfession): SimulationDefinition[] {
  return SIMULATION_CATALOG.filter((s) => s.profession.includes(profession));
}

export function getSimulationsByDifficulty(difficulty: SimulationDifficulty): SimulationDefinition[] {
  return SIMULATION_CATALOG.filter((s) => s.difficulty === difficulty);
}

export function getSimulationsByCondition(conditionKey: string): SimulationDefinition[] {
  return SIMULATION_CATALOG.filter((s) => s.conditionKey === conditionKey);
}

export function getSimulationsByTag(tag: string): SimulationDefinition[] {
  return SIMULATION_CATALOG.filter((s) => s.tags.includes(tag));
}

export const SIMULATION_COUNT = SIMULATION_CATALOG.length;
