import type { PerioperativeLesson } from "./types";

export const managementPersonnel: PerioperativeLesson[] = [
  { title: "Perioperative Team Roles and Responsibilities", slug: "perioperative-team-roles", domain: "Management of Personnel, Services, and Resources", difficulty: "beginner",
    content: `## Overview\nThe perioperative team is a multidisciplinary group with defined roles and responsibilities. Understanding each team member's scope of practice ensures efficient collaboration and optimal patient outcomes.\n\n## Key Concepts\n- **Circulating nurse (RN)**: Manages the OR environment, documents care, performs counts, communicates with team, serves as patient advocate, monitors sterile technique, coordinates with other departments. Must be an RN — cannot be delegated to LPN/UAP.\n- **Scrub role (RN, ST, or LPN)**: Maintains sterile field, handles instruments, assists surgeon during procedure, performs counts with circulating nurse. Can be filled by an RN, surgical technologist, or LPN/LVN.\n- **Surgeon**: Leads the surgical team, performs the procedure, responsible for surgical decisions, obtains informed consent, marks the surgical site.\n- **Anesthesiologist/CRNA**: Administers anesthesia, monitors physiological status, manages airway, provides pain management, manages hemodynamics.\n- **First assistant**: Assists the surgeon with exposure, hemostasis, and tissue handling. Can be an RNFA, PA, or another physician.\n- **Perioperative manager/director**: Oversees staffing, budget, quality metrics, regulatory compliance, and departmental operations.\n\n## Clinical Pearls\n- The circulating nurse role MUST be filled by an RN. This is a non-negotiable standard in AORN guidelines and most state nurse practice acts.\n- The scrub role can be filled by a surgical technologist (CST), LPN, or RN. The choice depends on institutional policy and case complexity.\n- Effective team communication is the foundation of surgical safety. Team briefings, time-outs, and debriefings improve outcomes.\n- CRM (Crew Resource Management) principles adapted from aviation improve team communication and error prevention in the OR.`,
    checkpointQuestions: [
      { question: "Which team member role MUST be filled by a registered nurse (RN)?", options: ["Scrub role", "First assistant", "Circulating nurse", "Surgical technologist"], correctIndex: 2, rationale: "The circulating nurse must be an RN per AORN standards and most state regulations. This role requires nursing assessment, critical thinking, documentation, medication administration, and patient advocacy that are within the RN scope of practice." }
    ],
    commonMistakes: ["Delegating the circulating nurse role to non-RN personnel", "Not including all team members in time-outs and briefings", "Not understanding scope of practice differences"],
    examTrapWarning: "Circulating nurse = MUST be RN. Scrub role = can be RN, ST, or LPN. Surgeon marks the site. Anesthesiologist manages airway and hemodynamics.",
    clinicalReasoning: "When staffing shortages create pressure to assign an LPN to circulate, the perioperative manager must recognize that this violates AORN standards and potentially state nurse practice acts. Alternative solutions must be found to maintain patient safety.",
    relatedFlashcardTopics: ["OR Team Roles", "Circulating Nurse", "Scrub Role", "Surgical Team"] },
  { title: "Staffing Models and Resource Management", slug: "staffing-models-resource-management", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nEffective perioperative staffing ensures patient safety, staff well-being, and operational efficiency. Staffing models must balance patient acuity, case complexity, regulatory requirements, and available resources.\n\n## Key Concepts\n- **AORN staffing recommendations**: One circulating RN per OR room. One scrub person per OR room. Additional staff for complex cases (cardiac, trauma, transplant). Relief for breaks without compromising patient care.\n- **On-call staffing**: For after-hours, emergency, and weekend coverage. AORN recommends limits on call hours and mandatory rest periods after call shifts.\n- **Skill mix**: The combination of RNs, STs, LPNs, and UAPs that compose the perioperative team. Higher RN skill mix is associated with better patient outcomes.\n- **Turnover time management**: Time between one patient leaving the OR and the next patient entering. Target: 25-30 minutes for routine cases. Optimized through parallel processing, standardized workflows, and team communication.\n- **Budget management**: Capital equipment budget (equipment with lifespan > 1 year, high cost), operating budget (supplies, staffing, maintenance), variance analysis (tracking actual vs. budgeted spending).\n- **Case costing**: Understanding the cost of each surgical case (supplies, implants, disposables, personnel time) to support financial sustainability.\n\n## Clinical Pearls\n- Mandatory overtime and excessive on-call hours contribute to nurse fatigue, which increases error risk. AORN recommends limits on consecutive work hours.\n- First-case start-time delays are the most expensive inefficiency in the OR. They cascade through the entire day's schedule.\n- Preference cards (surgeon-specific supply lists) reduce setup time and supply waste when kept current.\n- Block scheduling (allocating specific OR time to surgeons/services) improves utilization when managed effectively.`,
    checkpointQuestions: [
      { question: "According to AORN recommendations, what is the minimum staffing for a standard operating room during a surgical procedure?", options: ["One circulating RN only", "One circulating RN and one scrub person", "Two circulating RNs", "One RN and two UAPs"], correctIndex: 1, rationale: "AORN recommends a minimum of one circulating RN and one scrub person (RN, ST, or LPN) for each operating room during a surgical procedure. Additional staff may be needed for complex cases." }
    ],
    commonMistakes: ["Staffing below AORN minimum recommendations", "Not updating preference cards regularly", "Excessive mandatory overtime contributing to fatigue"],
    examTrapWarning: "Minimum: 1 circulating RN + 1 scrub person per room. Higher RN mix = better outcomes. Fatigue from overtime increases errors. First-case delays cascade.",
    clinicalReasoning: "When a busy day requires opening a fifth OR room with limited staff, the perioperative manager must evaluate whether patient safety can be maintained with available personnel. Understaffing an OR room to open more rooms creates system-wide safety risks.",
    relatedFlashcardTopics: ["OR Staffing", "Resource Management", "Turnover Time", "Budget Management"] },
  { title: "Perioperative Education and Competency Validation", slug: "perioperative-education-competency", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nContinuing education and competency validation ensure that perioperative nurses maintain current knowledge and skills. Competency assessment is an ongoing process that includes initial orientation, annual skills validation, and targeted education for new technologies and procedures.\n\n## Key Concepts\n- **Orientation**: New perioperative nurse orientation typically includes classroom education, simulation, and precepted clinical experience. AORN's Periop 101 is a comprehensive orientation program.\n- **Competency validation methods**: Direct observation, skills checklists, return demonstration, written tests, simulation scenarios, peer review, case studies.\n- **Continuing education**: Required for license renewal (varies by state). Sources: AORN conferences, webinars, journal articles, in-service education, certification programs.\n- **New technology introduction**: New equipment and procedures require hands-on training, competency validation, and ongoing support before independent use.\n- **Simulation training**: High-fidelity simulation allows practice of rare but critical events (MH, cardiac arrest, fire) in a safe environment.\n\n## Clinical Pearls\n- Competency is not a one-time event — it is an ongoing process that must be reassessed regularly, especially when new technologies or procedures are introduced.\n- Simulation training for rare emergencies (MH, surgical fire, cardiac arrest) has been shown to improve response times and outcomes in real events.\n- Periop 101 (AORN's online perioperative education program) provides a structured pathway for nurses transitioning into perioperative nursing.\n- Peer mentoring and preceptorship programs accelerate competency development in new perioperative nurses.`,
    checkpointQuestions: [
      { question: "A new robotic surgical system is being introduced at the facility. What must happen before staff can independently use it?", options: ["Reading the manufacturer's manual is sufficient", "Hands-on training and competency validation must be completed", "Only the surgeon needs training", "One in-service presentation is adequate"], correctIndex: 1, rationale: "New technology introduction requires hands-on training, practice (ideally simulation), and formal competency validation before staff can independently use the equipment. Reading materials alone are insufficient for skills-based competencies." }
    ],
    commonMistakes: ["Treating competency as a one-time event", "Not providing hands-on training for new equipment", "Relying solely on written tests for competency validation"],
    examTrapWarning: "Competency is ONGOING, not one-time. New technology = hands-on training + competency validation. Simulation improves emergency response. Periop 101 = AORN orientation program.",
    clinicalReasoning: "When a perioperative nurse is asked to circulate for a type of procedure they have never experienced, they should request appropriate orientation and mentorship rather than assuming they can transfer general perioperative skills. Patient safety requires procedure-specific competency.",
    relatedFlashcardTopics: ["Competency Assessment", "Periop 101", "Simulation Training", "Continuing Education"] },
  { title: "Conflict Resolution and Team Communication", slug: "conflict-resolution-team-communication", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nEffective communication and conflict resolution are essential for perioperative team function and patient safety. Communication failures are the leading root cause of sentinel events in surgery. Structured communication tools and a culture of safety promote open dialogue and error prevention.\n\n## Key Concepts\n- **Communication failures**: Leading root cause of sentinel events (identified in >70% of sentinel event RCAs). Types: incomplete handoff, failure to escalate concerns, intimidation suppressing communication.\n- **Structured communication**: SBAR (Situation, Background, Assessment, Recommendation), CUS (Concerned, Uncomfortable, Safety issue), team briefings, time-outs, debriefings.\n- **CUS words**: Escalating language: "I am Concerned," "I am Uncomfortable," "This is a Safety issue/I need you to Stop." These trigger a mandatory pause and response.\n- **Just Culture**: A safety culture that distinguishes between human error (console), at-risk behavior (coach), and reckless behavior (punish). Encourages reporting without fear of retribution.\n- **Crew Resource Management (CRM)**: Adapted from aviation. Key principles: flat hierarchy for safety communication, mutual monitoring, situational awareness, speaking up regardless of rank.\n- **Disruptive behavior**: Intimidation, bullying, passive aggression, or hostile behavior that undermines team function and patient safety. Zero tolerance policies are mandated by The Joint Commission.\n\n## Clinical Pearls\n- Communication failures are the #1 root cause of sentinel events in the OR. Structured tools (SBAR, CUS) significantly reduce these failures.\n- The CUS framework gives any team member a scripted escalation pathway. When someone says "I have a safety concern," the team MUST stop and address it.\n- Just Culture recognizes that humans make errors in complex systems. The goal is to improve systems, not punish individuals for honest mistakes.\n- Debriefing after every case (even uneventful ones) has been shown to improve team performance, identify equipment issues, and enhance morale.`,
    checkpointQuestions: [
      { question: "What is the leading root cause of sentinel events in the operating room?", options: ["Equipment malfunction", "Medication errors", "Communication failures", "Insufficient staffing"], correctIndex: 2, rationale: "Communication failures are identified as the leading root cause in over 70% of sentinel event root cause analyses. This includes incomplete handoffs, failure to escalate concerns, and intimidation that suppresses open communication." }
    ],
    commonMistakes: ["Not using structured communication tools", "Allowing intimidation to suppress safety concerns", "Not conducting post-case debriefings"],
    examTrapWarning: "Communication failures = #1 root cause of sentinel events. CUS = Concerned, Uncomfortable, Safety issue. Just Culture: error = console, at-risk = coach, reckless = punish.",
    clinicalReasoning: "When a scrub tech notices the surgeon is about to incise on the wrong side but feels intimidated to speak up, the CUS framework provides a structured way to escalate: 'I have a safety concern — the incision site does not match the consent form.' This must trigger an immediate pause.",
    relatedFlashcardTopics: ["Team Communication", "SBAR", "CUS Framework", "Just Culture"] },
  { title: "Regulatory Compliance and Accreditation", slug: "regulatory-compliance-accreditation", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nPerioperative departments must comply with multiple regulatory agencies and accreditation standards. Understanding these requirements ensures legal compliance, patient safety, and continued accreditation.\n\n## Key Concepts\n- **The Joint Commission (TJC)**: Largest healthcare accreditation body. Conducts unannounced surveys. National Patient Safety Goals (NPSGs) are annual focus areas. Universal Protocol is a TJC requirement.\n- **CMS (Centers for Medicare & Medicaid Services)**: Conditions of Participation (CoPs) are mandatory for Medicare/Medicaid reimbursement. CMS can "deem" TJC-accredited hospitals as compliant.\n- **OSHA (Occupational Safety and Health Administration)**: Workplace safety requirements. Bloodborne Pathogen Standard, Hazard Communication Standard (chemical safety), PPE requirements, surgical smoke regulation.\n- **AAMI (Association for the Advancement of Medical Instrumentation)**: Standards for sterilization, instrument processing, water quality, and medical device reprocessing.\n- **State health departments**: License healthcare facilities. Conduct inspections. Enforce state regulations that may exceed federal requirements.\n- **FDA (Food and Drug Administration)**: Regulates medical devices, drugs, and biological products. MedWatch reporting for device failures/adverse events.\n\n## Clinical Pearls\n- The Joint Commission surveys are UNANNOUNCED. Facilities must maintain continuous readiness ("survey-ready every day").\n- National Patient Safety Goals change annually and are high-yield CNOR content. Current goals always include correct patient identification, medication safety, infection prevention, and fall prevention.\n- OSHA's Bloodborne Pathogen Standard mandates availability of HBV vaccination, engineering controls for sharps safety, and post-exposure protocols.\n- AAMI standards for sterilization are the reference for proper instrument reprocessing. They are often the basis for TJC survey questions about sterile processing.`,
    checkpointQuestions: [
      { question: "Which regulatory body mandates the Universal Protocol for surgical procedures?", options: ["OSHA", "FDA", "The Joint Commission", "CMS"], correctIndex: 2, rationale: "The Joint Commission mandates the Universal Protocol (preprocedure verification, site marking, time-out) as a National Patient Safety Goal. It applies to all accredited healthcare organizations performing surgical and invasive procedures." }
    ],
    commonMistakes: ["Not maintaining continuous survey readiness", "Not staying current with NPSGs", "Confusing regulatory bodies and their jurisdictions"],
    examTrapWarning: "TJC = Universal Protocol + NPSGs. OSHA = workplace safety + bloodborne pathogens. AAMI = sterilization standards. FDA = device regulation. TJC surveys are UNANNOUNCED.",
    clinicalReasoning: "When preparing for a potential Joint Commission survey, the perioperative nurse should verify that all current National Patient Safety Goals are being met in daily practice, not just during survey preparation. Continuous compliance is the expectation.",
    relatedFlashcardTopics: ["TJC Accreditation", "OSHA Standards", "NPSGs", "Regulatory Compliance"] },
  { title: "Quality Improvement in the Perioperative Setting", slug: "quality-improvement-perioperative", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nQuality improvement (QI) in perioperative nursing uses systematic, data-driven approaches to improve patient outcomes, reduce errors, and enhance efficiency. QI methodologies provide frameworks for identifying problems, implementing changes, and measuring results.\n\n## Key Concepts\n- **Plan-Do-Study-Act (PDSA)**: Iterative improvement cycle. Plan the change, implement on a small scale, study the results, act on findings (adopt, adapt, or abandon).\n- **Root Cause Analysis (RCA)**: Systematic investigation of adverse events or near-misses to identify underlying system failures rather than blaming individuals.\n- **Failure Mode and Effects Analysis (FMEA)**: Proactive risk assessment that identifies potential failure points in a process BEFORE an adverse event occurs.\n- **Key performance indicators (KPIs)**: Surgical site infection rates, wrong-site surgery incidence, first-case on-time starts, turnover time, patient satisfaction scores, staff injury rates.\n- **Benchmarking**: Comparing performance against national standards or peer institutions to identify improvement opportunities.\n- **Evidence-based practice (EBP)**: Integrating best research evidence with clinical expertise and patient preferences to guide care decisions.\n\n## Clinical Pearls\n- RCA looks backward (what happened?). FMEA looks forward (what could go wrong?). Both are essential for comprehensive quality management.\n- QI projects should focus on measurable outcomes, not just process changes. "We implemented a checklist" is process; "SSI rates decreased by 30%" is outcome.\n- The perioperative nurse contributes to QI by reporting near-misses, participating in RCAs, collecting data, and implementing evidence-based practices.\n- Small tests of change (PDSA cycles) allow rapid iteration without committing to large-scale changes that may not work.`,
    checkpointQuestions: [
      { question: "Which quality improvement method is used to proactively identify potential failure points BEFORE an adverse event occurs?", options: ["Root Cause Analysis (RCA)", "Failure Mode and Effects Analysis (FMEA)", "Sentinel Event Review", "Retrospective Chart Audit"], correctIndex: 1, rationale: "FMEA is a proactive risk assessment tool that identifies potential failure modes in a process before an adverse event occurs. RCA is reactive — it investigates events that have already happened." }
    ],
    commonMistakes: ["Focusing on blame rather than system improvements", "Implementing changes without measuring outcomes", "Not reporting near-misses"],
    examTrapWarning: "RCA = reactive (after event). FMEA = proactive (before event). PDSA = iterative improvement cycle. Focus on measurable outcomes, not just process changes.",
    clinicalReasoning: "After a retained surgical item event, an RCA reveals that the count policy was not followed due to time pressure from the surgeon. The system fix should address the culture of safety and communication, not just re-educate the nurse who miscounted.",
    relatedFlashcardTopics: ["Quality Improvement", "PDSA Cycle", "Root Cause Analysis", "FMEA"] },
  { title: "Supply Chain and Materials Management", slug: "supply-chain-materials-management", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nEfficient materials management ensures that the right supplies, instruments, and implants are available when needed while minimizing waste and controlling costs. The perioperative nurse plays a key role in supply chain management through accurate preference cards, par level maintenance, and product evaluation.\n\n## Key Concepts\n- **Preference cards**: Surgeon-specific supply and instrument lists for each procedure. Must be reviewed and updated regularly to reduce waste and ensure preparedness.\n- **Par levels**: Predetermined minimum and maximum quantities of supplies maintained in stock. Set based on usage data, lead times, and case volume.\n- **Just-in-time (JIT) inventory**: Supplies delivered as needed rather than stored in large quantities. Reduces storage costs but requires reliable supply chain.\n- **Product evaluation**: Standardized process for evaluating new products. Includes clinical trials, cost analysis, user feedback, and value analysis committee review.\n- **Value analysis**: Multidisciplinary committee that evaluates products based on clinical efficacy, safety, cost, and standardization opportunities.\n- **Consignment inventory**: Vendor-owned supplies (usually implants) stored at the facility but not purchased until used. Reduces inventory carrying costs.\n\n## Clinical Pearls\n- Outdated preference cards are a major source of waste and delay. A systematic review schedule (quarterly or semi-annually) keeps them current.\n- Product standardization reduces costs, simplifies training, and decreases errors. Too many similar products from different manufacturers creates confusion.\n- Expired supplies in the OR represent both a patient safety risk and financial waste. FIFO (First In, First Out) rotation prevents expiration.\n- Supply chain disruptions (as seen during COVID-19) require contingency planning and identification of alternative products.`,
    checkpointQuestions: [
      { question: "What is the primary purpose of regularly updating surgeon preference cards?", options: ["To increase supply orders", "To reduce waste and ensure case preparedness", "To satisfy regulatory requirements", "To give surgeons more choices"], correctIndex: 1, rationale: "Regularly updated preference cards ensure that the correct supplies are pulled for each case, reducing waste from unused items and preventing delays from missing supplies." }
    ],
    commonMistakes: ["Not regularly updating preference cards", "Not rotating stock using FIFO", "Failing to plan for supply chain disruptions"],
    examTrapWarning: "Preference cards = surgeon-specific supply lists, must be current. FIFO rotation prevents expiration. Value analysis = multidisciplinary product evaluation. JIT reduces storage costs.",
    clinicalReasoning: "When a surgeon requests a new type of surgical mesh, the perioperative nurse should initiate a value analysis review rather than simply ordering the product. This ensures proper clinical evaluation, cost analysis, and staff training before adoption.",
    relatedFlashcardTopics: ["Materials Management", "Preference Cards", "Value Analysis", "Supply Chain"] },
  { title: "Perioperative Information Systems and Technology", slug: "perioperative-information-systems", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nPerioperative information systems support documentation, scheduling, supply management, and quality reporting. Technology integration in the OR improves efficiency, accuracy, and patient safety when implemented with proper training and workflow design.\n\n## Key Concepts\n- **Electronic health record (EHR)**: Perioperative documentation including preoperative assessment, intraoperative record, counts, specimens, implants, and PACU documentation. Structured data enables quality reporting.\n- **OR scheduling systems**: Manage block time allocation, case scheduling, resource coordination, and utilization tracking. Optimize OR efficiency through data-driven scheduling.\n- **Barcode/RFID tracking**: Instrument set tracking, implant documentation, supply chain management, and specimen labeling. Reduces documentation errors and enables recall tracking.\n- **Clinical decision support**: Alerts for drug interactions, allergy warnings, antibiotic prophylaxis timing reminders, and count discrepancy alerts.\n- **Telehealth/telemedicine in surgery**: Remote proctoring, telementoring for complex procedures, intraoperative consultation with specialists not physically present.\n- **Robotic surgery systems**: Da Vinci, Mako, and other platforms require specialized training, room setup, and troubleshooting knowledge.\n\n## Clinical Pearls\n- Technology should support clinical workflow, not disrupt it. Poor EHR design can increase documentation time and distract from patient care.\n- Barcode scanning for implants eliminates transcription errors in lot/serial number documentation and streamlines recall management.\n- Downtime procedures must be established for when electronic systems fail. Paper-based backup documentation should be readily available.\n- Cybersecurity in the OR is increasingly important as more devices become networked. Connected surgical equipment can be vulnerable to cyber threats.`,
    checkpointQuestions: [
      { question: "Why is barcode scanning recommended for surgical implant documentation?", options: ["It is faster than typing", "It eliminates transcription errors in lot/serial numbers and enables recall tracking", "It is required by FDA", "It replaces the need for written documentation"], correctIndex: 1, rationale: "Barcode scanning eliminates human error in transcribing lot and serial numbers, ensures accurate documentation in the patient record, and enables rapid identification of patients who received recalled devices." }
    ],
    commonMistakes: ["Not having downtime procedures for electronic system failures", "Implementing technology without adequate staff training", "Relying solely on technology without clinical judgment"],
    examTrapWarning: "EHR supports but does not replace clinical judgment. Downtime procedures required. Barcode scanning reduces documentation errors. Cybersecurity is an emerging concern.",
    clinicalReasoning: "When the EHR system goes down during a surgical case, the circulating nurse must immediately switch to paper-based documentation and ensure all critical information (counts, specimens, implants) is accurately recorded for later entry into the electronic system.",
    relatedFlashcardTopics: ["Perioperative IT", "EHR Documentation", "Barcode Tracking", "OR Scheduling"] },
  { title: "Delegation and Supervision in Perioperative Nursing", slug: "delegation-supervision-perioperative", domain: "Management of Personnel, Services, and Resources", difficulty: "intermediate",
    content: `## Overview\nDelegation in perioperative nursing requires understanding scope of practice, competency assessment, and supervisory responsibilities. The RN retains accountability for delegated tasks and must ensure that delegation is appropriate, safe, and within regulatory boundaries.\n\n## Key Concepts\n- **Five Rights of Delegation**: Right task, right circumstance, right person, right direction/communication, right supervision/evaluation.\n- **Cannot be delegated by the circulating RN**: Nursing assessment, care planning, patient education, medication administration, evaluation of patient outcomes. These require RN judgment.\n- **Can be delegated**: Routine tasks such as obtaining supplies, positioning assistance, room setup, transport (under supervision), taking vital signs (to trained UAP with RN verification).\n- **Supervision levels**: Direct supervision (supervisor physically present), indirect supervision (supervisor available but not present), periodic inspection.\n- **State nurse practice acts**: Define the legal scope of delegation for each state. Requirements vary — the nurse must know their state's specific delegation rules.\n- **Accountability vs. responsibility**: The RN who delegates retains accountability for the outcome. The person who accepts the delegated task has responsibility for performing it correctly.\n\n## Clinical Pearls\n- The circulating RN can NEVER delegate nursing assessment, care planning, or medication administration. These are core RN functions.\n- Delegation decisions must consider the patient's condition, complexity of the task, competency of the person, and available supervision.\n- The surgical technologist can perform the scrub role under RN supervision but cannot independently make nursing judgments about patient care.\n- When a UAP is assisting in the OR, the RN must provide clear instructions, set expectations, and verify task completion.`,
    checkpointQuestions: [
      { question: "Which task can the circulating RN delegate to a UAP in the perioperative setting?", options: ["Patient assessment", "Medication administration", "Obtaining supplies from the supply room", "Evaluating patient response to anesthesia"], correctIndex: 2, rationale: "Obtaining supplies is a routine task that can be delegated to a UAP. Assessment, medication administration, and evaluation of patient responses require nursing judgment and cannot be delegated." }
    ],
    commonMistakes: ["Delegating nursing assessment to unlicensed personnel", "Not verifying competency before delegating", "Not providing adequate supervision after delegation"],
    examTrapWarning: "Five Rights of Delegation. RN retains accountability. Cannot delegate: assessment, care planning, meds, evaluation. Can delegate: supplies, transport, room setup.",
    clinicalReasoning: "When short-staffed, the charge nurse asks a UAP to assess the preoperative patient and report findings. The RN must decline this delegation — preoperative assessment requires nursing judgment and cannot be delegated to unlicensed personnel.",
    relatedFlashcardTopics: ["Delegation", "Scope of Practice", "Five Rights", "Supervision"] },
  { title: "Disaster Preparedness and Mass Casualty Planning", slug: "disaster-preparedness-mass-casualty", domain: "Management of Personnel, Services, and Resources", difficulty: "advanced",
    content: `## Overview\nPerioperative departments must be prepared for mass casualty incidents (MCIs), natural disasters, and facility emergencies. Planning includes surge capacity, triage protocols, resource allocation, and staff mobilization.\n\n## Key Concepts\n- **Emergency Operations Plan (EOP)**: Facility-wide plan that defines command structure, communication, resource allocation, and departmental responsibilities during emergencies.\n- **Incident Command System (ICS)**: Standardized management structure for emergency response. Key roles: Incident Commander, Operations, Planning, Logistics, Finance/Administration.\n- **Surge capacity**: Ability to expand OR capacity during MCIs. Strategies: cancel elective cases, open additional ORs, extend hours, call in off-duty staff, use procedure rooms for minor cases.\n- **Triage in MCI**: START triage (Simple Triage and Rapid Treatment). Categories: Immediate (red), Delayed (yellow), Minor (green), Expectant/Deceased (black).\n- **HICS (Hospital Incident Command System)**: Hospital-specific adaptation of ICS. Defines roles for all hospital departments including perioperative services.\n- **Communication**: Redundant communication systems (phones, radios, runners). Regular drills ensure staff know their roles and communication chains.\n\n## Clinical Pearls\n- The perioperative team's role in MCI is to maximize surgical throughput for life-threatening injuries. Elective cases are cancelled to free OR resources.\n- Damage control surgery (DCS) principles apply in MCI: abbreviated surgery to control hemorrhage and contamination, with definitive repair delayed.\n- Regular disaster drills (at least annually) are required for accreditation and ensure staff readiness.\n- Personal preparedness (knowing your role, having a personal emergency plan) is essential — staff who are worried about their own families cannot focus on patient care.`,
    checkpointQuestions: [
      { question: "During a mass casualty incident, what is the perioperative team's primary role?", options: ["Continue all scheduled elective cases", "Maximize surgical throughput for life-threatening injuries", "Evacuate the surgical suite", "Wait for specific instructions from administration"], correctIndex: 1, rationale: "During an MCI, the perioperative team's primary role is to maximize surgical capacity for life-threatening injuries. Elective cases are cancelled, additional ORs are opened, and damage control surgery principles are applied to treat the greatest number of patients." }
    ],
    commonMistakes: ["Not having a personal emergency plan", "Not participating in regular disaster drills", "Not understanding ICS roles"],
    examTrapWarning: "MCI = cancel electives, maximize OR throughput. ICS = standardized command structure. START triage: Immediate (red), Delayed (yellow), Minor (green), Expectant (black). Annual drills required.",
    clinicalReasoning: "When the hospital activates its MCI plan after a multi-vehicle accident with 20 casualties, the perioperative manager must immediately assess current OR status, cancel non-emergent cases, call in additional staff, and prepare multiple ORs for trauma surgery.",
    relatedFlashcardTopics: ["Disaster Preparedness", "Mass Casualty", "ICS", "START Triage"] }
];
