import type { PerioperativeLesson } from "./types";

export const postoperativeCare: PerioperativeLesson[] = [
  { title: "PACU Assessment and Admission Criteria", slug: "pacu-assessment-admission", domain: "Postoperative Patient Care", difficulty: "beginner",
    content: `## Overview\nThe Post-Anesthesia Care Unit (PACU) provides intensive monitoring during the immediate postoperative period. The Aldrete Scoring System (or Modified Aldrete Score) assesses discharge readiness based on activity, respiration, circulation, consciousness, and oxygen saturation.\n\n## Key Concepts\n- **Aldrete Score criteria**: Activity (0-2), Respiration (0-2), Circulation (0-2), Consciousness (0-2), SpO2 (0-2). Maximum score = 10. Discharge criterion: typically >= 9.\n- **Phase I PACU**: Immediate post-anesthesia recovery. One-to-one or one-to-two nurse-patient ratio. Continuous monitoring.\n- **Phase II PACU**: Step-down recovery. Less intensive monitoring. Preparation for discharge home.\n- **PACU admission assessment**: Airway patency, breathing pattern, vital signs, level of consciousness, surgical site (dressing, drains, bleeding), pain level, IV access, urinary output, temperature.\n- **Handoff**: SBAR from OR nurse/anesthesiologist to PACU nurse. Include procedure, anesthesia type, blood loss, fluids given, medications, complications, surgeon's orders.\n\n## Assessment Steps\n1. Assess airway and breathing first (ABCs).\n2. Obtain vital signs immediately upon arrival.\n3. Assess level of consciousness and orientation.\n4. Evaluate surgical site, dressings, and drains.\n5. Assess pain level using appropriate scale.\n6. Review the operative record and anesthesia record.\n7. Calculate initial Aldrete score.\n8. Continue vital signs every 5-15 minutes per protocol.\n\n## Complications\n- Airway obstruction (tongue falling back, laryngospasm, secretions).\n- Respiratory depression from residual anesthetic agents.\n- Hemorrhage (internal or external at surgical site).\n- Hypothermia causing shivering and increased oxygen demand.\n- PONV (postoperative nausea and vomiting).\n- Emergence delirium (especially in children and elderly).\n\n## Clinical Pearls\n- The most common cause of airway obstruction in the immediate postoperative period is the tongue falling back against the posterior pharynx. Treatment: jaw thrust or chin lift.\n- Vital signs should be taken every 5 minutes for the first 15 minutes, then every 15 minutes until discharge criteria are met.\n- Never discharge a patient from Phase I PACU with an Aldrete score < 9 (per most institutional policies).\n- Hypothermia in PACU is associated with increased bleeding, cardiac arrhythmias, and delayed drug metabolism.`,
    checkpointQuestions: [
      { question: "What is the most common cause of airway obstruction in the immediate postoperative period?", options: ["Bronchospasm", "Laryngospasm", "Tongue falling against the posterior pharynx", "Residual neuromuscular blockade"], correctIndex: 2, rationale: "The most common cause of airway obstruction in the immediate postoperative period is the tongue falling back against the posterior pharynx due to residual anesthetic effects on pharyngeal muscle tone." }
    ],
    commonMistakes: ["Not assessing airway first on PACU arrival", "Discharging with Aldrete score below criteria", "Incomplete handoff from OR to PACU"],
    examTrapWarning: "Most common PACU airway obstruction = tongue. Aldrete score >= 9 for discharge. ABCs first upon PACU arrival.",
    clinicalReasoning: "A patient arriving to PACU with snoring respirations likely has partial airway obstruction from the tongue. Simple interventions (jaw thrust, chin lift, lateral positioning) should be tried before considering advanced airway management.",
    relatedFlashcardTopics: ["PACU Assessment", "Aldrete Score", "Postoperative Airway Management", "Phase I/II Recovery"] },
  { title: "Postoperative Pain Management", slug: "postoperative-pain-management", domain: "Postoperative Patient Care", difficulty: "intermediate",
    content: `## Overview\nEffective postoperative pain management improves patient outcomes, promotes early mobilization, reduces complications, and enhances patient satisfaction. A multimodal approach combining pharmacologic and non-pharmacologic interventions is the current standard of care.\n\n## Key Concepts\n- **Multimodal analgesia**: Combines multiple drug classes (opioids, NSAIDs, acetaminophen, local anesthetics, gabapentinoids) to target different pain pathways. Reduces opioid requirements and side effects.\n- **Patient-Controlled Analgesia (PCA)**: Patient self-administers IV opioid doses within preset parameters. Lockout interval prevents overdose. ONLY the patient should press the PCA button.\n- **Regional analgesia**: Epidural analgesia, peripheral nerve block catheters. Provides excellent analgesia with reduced systemic opioid use.\n- **Pain assessment tools**: Numeric Rating Scale (NRS 0-10), Visual Analog Scale (VAS), Wong-Baker FACES scale (pediatric/nonverbal), FLACC scale (infants/nonverbal children), behavioral scales for cognitively impaired adults.\n- **ERAS (Enhanced Recovery After Surgery)**: Evidence-based perioperative protocols emphasizing multimodal analgesia, early nutrition, and early mobilization to reduce hospital stay.\n\n## Interventions / Management\n- Assess pain using an appropriate validated tool at regular intervals.\n- Administer analgesics on schedule (not PRN only) for the first 24-48 hours.\n- Implement multimodal approach: scheduled acetaminophen + NSAID + opioid for breakthrough.\n- Use non-pharmacologic adjuncts: positioning, ice, relaxation, guided imagery, TENS.\n- Monitor for opioid side effects: respiratory depression (most dangerous), sedation, nausea, constipation, pruritus.\n- Reassess pain within 30 minutes of IV analgesic and 60 minutes of oral analgesic.\n\n## Complications\n- **Opioid-induced respiratory depression**: Most dangerous complication. Risk factors: obesity, OSA, elderly, opioid-naive patients. Monitor sedation level and respiratory rate.\n- **Undertreated pain**: Leads to splinting, atelectasis, pneumonia, DVT, prolonged ileus, chronic pain.\n- **Opioid side effects**: PONV, constipation/ileus, urinary retention, pruritus, sedation.\n\n## Clinical Pearls\n- ONLY the patient should press the PCA button ("PCA by proxy" — family/nurse pressing — is a significant safety hazard that can cause respiratory arrest).\n- Sedation precedes respiratory depression. Increasing sedation is the earliest warning sign of impending respiratory compromise.\n- Acetaminophen 1g IV (Ofirmev) provides opioid-sparing analgesia equivalent to morphine 2-4 mg IV.\n- Ketorolac (Toradol) is an effective NSAID but limited to 5 days due to GI bleeding and renal risk.`,
    checkpointQuestions: [
      { question: "A patient's family member is pressing the PCA button while the patient is sleeping. What should the nurse do?", options: ["Allow it since the patient is in pain", "Educate the family that ONLY the patient should press the PCA button", "Reduce the PCA dose", "Discontinue the PCA"], correctIndex: 1, rationale: "PCA by proxy (anyone other than the patient pressing the button) is a significant safety hazard. The patient's ability to self-dose is a safety mechanism — if they are too sedated, they cannot press the button, preventing overdose. Family pressing the button bypasses this safety mechanism." }
    ],
    commonMistakes: ["Allowing PCA by proxy", "Using PRN-only dosing instead of scheduled multimodal approach", "Not reassessing pain after analgesic administration"],
    examTrapWarning: "ONLY the patient presses PCA. Sedation precedes respiratory depression. Multimodal analgesia is the standard of care. Reassess pain 30 min after IV, 60 min after PO.",
    clinicalReasoning: "When a postoperative patient becomes increasingly sedated despite not pressing their PCA button, the nurse should consider other contributing factors: residual anesthesia, epidural opioid, other sedating medications, or metabolic causes. The most important action is to assess respiratory rate and depth.",
    relatedFlashcardTopics: ["Multimodal Analgesia", "PCA Safety", "Pain Assessment Tools", "Opioid Side Effects"] },
  { title: "Postoperative Wound Care and Assessment", slug: "postoperative-wound-care-assessment", domain: "Postoperative Patient Care", difficulty: "beginner",
    content: `## Overview\nPostoperative wound assessment identifies complications early and promotes healing. The perioperative nurse evaluates the wound at the time of dressing application, during PACU care, and provides patient education for home wound management.\n\n## Key Concepts\n- **Wound classification (CDC)**: Class I Clean (elective, no inflammation, closed primarily), Class II Clean-Contaminated (respiratory, GI, GU tract entered under controlled conditions), Class III Contaminated (open fresh accidental wounds, major break in sterile technique, gross spillage from GI tract), Class IV Dirty/Infected (old traumatic wounds, existing infection, perforated viscera).\n- **Wound healing phases**: Hemostasis (immediate), Inflammatory (0-4 days), Proliferative (4-21 days), Maturation/Remodeling (21 days - 1 year).\n- **Wound closure types**: Primary intention (edges approximated with sutures/staples/adhesive), Secondary intention (wound left open to granulate), Tertiary (delayed primary) intention (wound initially left open, then closed after infection control).\n- **Wound assessment**: COCA — Color, Odor, Consistency, Amount of drainage. Note approximation of edges, signs of dehiscence, hematoma, or seroma.\n\n## Interventions / Management\n- Assess wound immediately upon PACU arrival and before patient discharge.\n- Note dressing integrity, drainage amount and character (serous, sanguineous, serosanguineous, purulent).\n- Reinforce (not change) initial surgical dressing unless ordered otherwise.\n- Maintain drain patency and accurate output measurement.\n- Educate patient on signs of infection: increasing redness, warmth, swelling, purulent drainage, fever, increasing pain.\n- Document wound appearance using standardized descriptors.\n\n## Complications\n- **Surgical site infection (SSI)**: Redness, warmth, swelling, purulent drainage, fever. Occurs within 30 days of surgery (or 1 year if implant placed).\n- **Dehiscence**: Separation of wound edges. Risk factors: obesity, malnutrition, infection, excessive strain, steroid use.\n- **Evisceration**: Protrusion of abdominal organs through a dehisced wound. EMERGENCY: cover with sterile saline-moistened dressings, place patient supine with knees flexed, notify surgeon immediately.\n- **Hematoma/Seroma**: Collection of blood or serous fluid under the wound.\n\n## Clinical Pearls\n- Evisceration is a surgical emergency. Cover exposed organs with sterile normal saline-moistened gauze, keep the patient NPO, supine with knees flexed, and notify the surgeon for emergent return to OR.\n- SSI can occur up to 30 days postoperatively (90 days if implant). Patients should be educated to monitor for signs beyond hospital discharge.\n- A wound with salmon-pink/red granulation tissue that is moist is healing normally. Pale, gray, or necrotic tissue indicates compromised healing.\n- First dressing changes are typically done by the surgeon at 24-48 hours unless the dressing is saturated.`,
    checkpointQuestions: [
      { question: "A patient's abdominal wound dehisces and bowel is visible. What is the FIRST nursing action?", options: ["Push the bowel back into the abdomen", "Apply dry sterile gauze and tape", "Cover with sterile saline-moistened dressings and notify the surgeon", "Place the patient in Trendelenburg position"], correctIndex: 2, rationale: "Evisceration is a surgical emergency. The nurse should cover exposed organs with sterile saline-moistened dressings to prevent desiccation and tissue damage, position the patient supine with knees flexed, and immediately notify the surgeon." },
      { question: "Which wound classification describes a cholecystectomy (gallbladder removal) without spillage?", options: ["Class I Clean", "Class II Clean-Contaminated", "Class III Contaminated", "Class IV Dirty"], correctIndex: 1, rationale: "Cholecystectomy enters the GI tract (bile duct system) under controlled conditions without unusual contamination, making it a Class II Clean-Contaminated wound." }
    ],
    commonMistakes: ["Attempting to replace eviscerated organs", "Not educating patients on SSI signs", "Changing the initial surgical dressing without orders"],
    examTrapWarning: "Evisceration: moist sterile saline dressings, supine, knees flexed, NEVER push organs back. CDC wound classes: I Clean, II Clean-Contaminated, III Contaminated, IV Dirty.",
    clinicalReasoning: "When assessing a postoperative wound that has increasing erythema extending beyond the incision margins, warmth, and serosanguineous drainage at 48 hours, the nurse should suspect early SSI and notify the surgeon. Early detection and treatment significantly improve outcomes.",
    relatedFlashcardTopics: ["Wound Classification", "Wound Healing Phases", "SSI Prevention", "Dehiscence and Evisceration"] },
  { title: "Postoperative Drain Management", slug: "postoperative-drain-management", domain: "Postoperative Patient Care", difficulty: "intermediate",
    content: `## Overview\nSurgical drains remove blood, serous fluid, pus, or air from surgical sites and body cavities. Proper drain management prevents complications such as hematoma, seroma, abscess, and tension pneumothorax. The perioperative nurse must understand different drain types, management protocols, and output monitoring.\n\n## Key Concepts\n- **Passive drains**: Rely on gravity and capillary action. Penrose drain (flat, rubber tube), gauze wick. No suction applied.\n- **Active drains**: Use negative pressure (suction). Jackson-Pratt (JP) drain (bulb suction), Hemovac drain (spring-loaded disc), Blake drain (channel drain with suction).\n- **Chest tubes**: Thoracic drainage system for pneumothorax, hemothorax, pleural effusion. Connected to a water-seal drainage system (Pleur-evac).\n- **Output monitoring**: Measure and document drainage output, color, and consistency every shift or more frequently as ordered. Report excessive output (> 200 mL/hr from chest tube, > 100 mL/hr from surgical drain).\n- **Drain security**: All drains must be secured to prevent accidental dislodgement. Mark drainage level on the collection device with time.\n\n## Interventions / Management\n- Maintain drain patency (avoid kinking, dependent loops).\n- Empty JP/Hemovac drains when half full to maintain adequate suction.\n- Maintain water-seal integrity for chest tubes (water level at 2 cm mark).\n- Monitor for air leaks in chest tube system (continuous bubbling in water-seal chamber).\n- Document output amount, color, and consistency with each emptying.\n- Secure drains to prevent traction on the insertion site.\n- Educate patients on drain care before discharge.\n\n## Complications\n- Accidental dislodgement (can require reoperation or cause tension pneumothorax with chest tubes).\n- Drain site infection.\n- Drain obstruction from clots or fibrin.\n- Tension pneumothorax from clamped/obstructed chest tube.\n\n## Clinical Pearls\n- A JP drain loses suction when the bulb re-expands. Always empty and recompress the bulb to maintain negative pressure.\n- Chest tubes should NEVER be clamped except for brief periods during system changes, as clamping can cause tension pneumothorax.\n- Continuous bubbling in the water-seal chamber indicates an air leak. Intermittent bubbling with expiration/coughing is normal after pneumothorax.\n- Normal surgical drain output transitions from sanguineous (bloody) to serosanguineous (pink) to serous (clear yellow) over 2-3 days.`,
    checkpointQuestions: [
      { question: "A patient's chest tube drainage system shows continuous bubbling in the water-seal chamber. What does this indicate?", options: ["Normal function", "Air leak in the system", "The system needs more water", "The patient is coughing"], correctIndex: 1, rationale: "Continuous bubbling in the water-seal chamber indicates an air leak, which could be from the patient's lung or from a connection point in the drainage system. Intermittent bubbling with expiration or coughing is normal, but continuous bubbling requires investigation." }
    ],
    commonMistakes: ["Clamping chest tubes for prolonged periods", "Not emptying JP drains when half full", "Not securing drains against accidental removal"],
    examTrapWarning: "NEVER clamp chest tubes (tension pneumothorax risk). JP bulb must be compressed to maintain suction. Continuous bubbling = air leak. Intermittent bubbling = normal.",
    clinicalReasoning: "When a patient with a chest tube suddenly develops dyspnea, tracheal deviation, and absent breath sounds on the affected side, tension pneumothorax should be suspected. Check that the chest tube is patent and not kinked or clamped.",
    relatedFlashcardTopics: ["Surgical Drains", "Chest Tube Management", "JP Drain", "Hemovac"] },
  { title: "DVT Prophylaxis and Early Mobilization", slug: "dvt-prophylaxis-early-mobilization", domain: "Postoperative Patient Care", difficulty: "beginner",
    content: `## Overview\nPostoperative DVT prophylaxis continues from the intraoperative period through discharge and beyond. Early ambulation is the single most effective non-pharmacologic intervention for preventing VTE, reducing pulmonary complications, and hastening recovery.\n\n## Key Concepts\n- **Risk factors for postoperative VTE**: Surgical immobility, venous stasis, hypercoagulable state from surgical stress, dehydration, previous VTE history, malignancy, obesity, oral contraceptive use, prolonged procedure.\n- **Mechanical prophylaxis**: SCDs (continue until ambulatory), graduated compression stockings (GCS/TEDs), early ambulation.\n- **Pharmacologic prophylaxis**: LMWH (enoxaparin 40 mg SC daily), unfractionated heparin (5000 units SC q8-12h), DOACs (rivaroxaban, apixaban). Started 6-12 hours postoperatively per surgeon orders.\n- **Duration of prophylaxis**: General surgery: until ambulatory. Major orthopedic: 10-35 days. Cancer surgery: 4 weeks.\n- **Early mobilization**: Begin day of surgery or POD 1. Progressive: sit on edge of bed, stand, walk in room, walk in hallway.\n\n## Interventions / Management\n- Ensure SCDs are functional and worn continuously when in bed.\n- Administer pharmacologic prophylaxis as ordered.\n- Assist with early ambulation beginning day of surgery when safe.\n- Teach ankle pump exercises for patients on bedrest.\n- Educate patients on VTE signs: unilateral leg swelling, calf pain, warmth, redness.\n- Monitor for bleeding complications of anticoagulant prophylaxis.\n\n## Clinical Pearls\n- Early ambulation within 24 hours of surgery reduces VTE risk by up to 70%.\n- SCDs work by simulating the muscle pump of walking, improving venous return.\n- Extended VTE prophylaxis (up to 35 days) is recommended after hip/knee replacement and cancer surgery.\n- Encourage patients to walk with purpose (to the bathroom, around the unit), not just sit in a chair.`,
    checkpointQuestions: [
      { question: "How long should VTE prophylaxis continue after total hip replacement?", options: ["Until hospital discharge only", "5-7 days", "10-35 days", "Lifelong"], correctIndex: 2, rationale: "Major orthopedic procedures (total hip/knee replacement, hip fracture surgery) require extended VTE prophylaxis for 10-35 days due to the persistently elevated risk of VTE even after hospital discharge." }
    ],
    commonMistakes: ["Discontinuing SCDs when patient sits in chair instead of walks", "Not providing extended prophylaxis after orthopedic surgery", "Not starting early mobilization day of surgery"],
    examTrapWarning: "Extended prophylaxis 10-35 days for major orthopedic surgery. Early ambulation = most effective non-pharmacologic DVT prevention. SCDs until ambulatory.",
    clinicalReasoning: "A patient 5 days post total knee replacement who develops sudden unilateral calf swelling and pain should be evaluated for DVT despite receiving pharmacologic prophylaxis. Breakthrough VTE can occur even with appropriate prophylaxis.",
    relatedFlashcardTopics: ["Postoperative DVT Prevention", "Early Mobilization", "Anticoagulant Prophylaxis"] },
  { title: "Postoperative Complications: Hemorrhage", slug: "postoperative-hemorrhage", domain: "Postoperative Patient Care", difficulty: "intermediate",
    content: `## Overview\nPostoperative hemorrhage can be immediate (within first 24 hours) or delayed (after 24 hours). Early recognition of hypovolemic shock signs is critical for timely intervention.\n\n## Key Concepts\n- **Primary hemorrhage**: During or immediately after surgery from inadequate hemostasis.\n- **Reactionary hemorrhage**: Within first 24 hours from dislodged clots, rising blood pressure, or resuming anticoagulants.\n- **Secondary hemorrhage**: After 24 hours, usually from infection or erosion of a blood vessel.\n- **Signs of hypovolemic shock**: Tachycardia (earliest sign), hypotension, tachypnea, decreased urine output, altered mental status, pallor, diaphoresis, cool/clammy extremities.\n- **External vs. internal hemorrhage**: External is visible (wound drainage, drain output). Internal is occult (increasing abdominal girth, rigid abdomen, dropping Hgb/Hct).\n\n## Interventions / Management\n- Monitor vital signs frequently. Tachycardia is often the FIRST sign of hemorrhage.\n- Assess surgical dressing and drain output for increasing sanguineous drainage.\n- For suspected internal hemorrhage: abdominal girth measurement, stat CBC, prepare for return to OR.\n- Initiate large-bore IV access (16-18 gauge) and begin fluid resuscitation.\n- Type and crossmatch blood, prepare for transfusion.\n- Notify surgeon immediately.\n- Position patient supine with legs elevated if hypotensive (modified Trendelenburg).\n\n## Clinical Pearls\n- Tachycardia is the EARLIEST sign of hemorrhage. Blood pressure drops are a LATE sign — the body compensates by increasing heart rate before pressure drops.\n- A young, healthy patient can lose up to 30% of blood volume before showing significant hypotension.\n- Serial Hgb/Hct measurements are more valuable than a single reading. A dropping trend is significant.\n- Increasing drain output (> 100 mL/hr from surgical drains) should trigger immediate surgeon notification.`,
    checkpointQuestions: [
      { question: "What is the earliest clinical sign of postoperative hemorrhage?", options: ["Hypotension", "Decreased urine output", "Tachycardia", "Altered mental status"], correctIndex: 2, rationale: "Tachycardia is the earliest compensatory response to hemorrhage. The body increases heart rate to maintain cardiac output as blood volume decreases. Hypotension is a LATE finding indicating decompensated shock." }
    ],
    commonMistakes: ["Waiting for hypotension before suspecting hemorrhage", "Not monitoring drain output closely", "Not obtaining serial Hgb/Hct levels"],
    examTrapWarning: "Tachycardia is the EARLIEST sign of hemorrhage, NOT hypotension. Hypotension is a LATE sign indicating decompensation. Young patients can compensate for significant blood loss.",
    clinicalReasoning: "A postoperative patient with an increasing heart rate (from 80 to 110 bpm) over 2 hours despite adequate pain control and no fever should be evaluated for occult hemorrhage. Serial vital signs trends are more informative than single measurements.",
    relatedFlashcardTopics: ["Postoperative Hemorrhage", "Hypovolemic Shock", "Hemorrhage Assessment", "Blood Transfusion"] },
  { title: "Postoperative Nausea and Vomiting (PONV)", slug: "postoperative-nausea-vomiting", domain: "Postoperative Patient Care", difficulty: "beginner",
    content: `## Overview\nPONV affects 30% of all surgical patients and up to 80% of high-risk patients. It decreases patient satisfaction, delays discharge, increases costs, and can cause aspiration, wound dehiscence, and electrolyte imbalances. Risk assessment and prophylaxis are essential.\n\n## Key Concepts\n- **Apfel Risk Score**: Four independent predictors: female sex, history of PONV/motion sickness, non-smoker, postoperative opioid use. Each factor = 1 point. 0 factors = 10% risk, 1 = 21%, 2 = 39%, 3 = 61%, 4 = 79%.\n- **Antiemetics**: Ondansetron (Zofran) — 5-HT3 antagonist, dexamethasone — steroid, scopolamine patch — anticholinergic, promethazine (Phenergan) — antihistamine, droperidol — dopamine antagonist.\n- **Multimodal antiemetic approach**: For patients with >= 2 risk factors, administer 2+ antiemetics from different classes.\n- **Non-pharmacologic**: Acupressure (P6 point/wristband), ginger, deep breathing, adequate hydration.\n\n## Interventions / Management\n- Assess Apfel risk score preoperatively.\n- Administer prophylactic antiemetics for patients with >= 2 risk factors.\n- Use TIVA (propofol-based anesthesia) instead of volatile agents for high-risk patients.\n- Minimize opioid use with multimodal analgesia.\n- Ensure adequate hydration.\n- Position the recovering patient on their side to prevent aspiration if actively vomiting.\n\n## Clinical Pearls\n- Propofol has intrinsic antiemetic properties. TIVA (Total IV Anesthesia with propofol) reduces PONV compared to inhalation anesthesia.\n- Ondansetron should be given at the END of surgery (not at induction) for maximum effectiveness.\n- Non-smokers are at HIGHER risk for PONV than smokers (counterintuitive but well-established).\n- Scopolamine patches should be placed behind the ear 4 hours before surgery for maximum effectiveness.`,
    checkpointQuestions: [
      { question: "According to the Apfel Score, which patient has the HIGHEST risk for PONV?", options: ["Male smoker with no PONV history", "Female non-smoker with PONV history receiving postoperative opioids", "Male non-smoker with no PONV history", "Female smoker with no PONV history"], correctIndex: 1, rationale: "A female, non-smoker, with history of PONV, receiving postoperative opioids has ALL 4 Apfel risk factors, giving an approximately 79% risk of PONV." }
    ],
    commonMistakes: ["Not assessing PONV risk preoperatively", "Using single-agent antiemetic therapy for high-risk patients", "Giving ondansetron at induction instead of end of surgery"],
    examTrapWarning: "Apfel Score: Female + non-smoker + PONV history + opioids = highest risk. Ondansetron given at END of surgery. Non-smokers have HIGHER PONV risk.",
    clinicalReasoning: "A female, non-smoking patient with history of severe PONV after a previous surgery who is scheduled for a laparoscopic procedure (another PONV risk factor) should receive multimodal prophylaxis: ondansetron at end of surgery + dexamethasone at induction + scopolamine patch preoperatively, with consideration of TIVA technique.",
    relatedFlashcardTopics: ["PONV", "Apfel Score", "Antiemetics", "PONV Prophylaxis"] },
  { title: "Postoperative Respiratory Complications", slug: "postoperative-respiratory-complications", domain: "Postoperative Patient Care", difficulty: "intermediate",
    content: `## Overview\nPostoperative pulmonary complications (PPCs) are among the most common and costly surgical complications. Atelectasis, pneumonia, respiratory failure, and aspiration can occur in any surgical patient but are more common after thoracic and upper abdominal surgery.\n\n## Key Concepts\n- **Atelectasis**: Most common PPC. Collapse of alveoli due to hypoventilation, mucus plugging, and absorption. Typically occurs within 24-48 hours. Presents with low-grade fever, decreased breath sounds, crackles, tachypnea.\n- **Pneumonia**: Infection of lung parenchyma. Risk increases with atelectasis, aspiration, mechanical ventilation, and immunosuppression.\n- **Aspiration**: Inhalation of gastric or oropharyngeal contents. Risk factors: impaired consciousness, impaired swallow reflex, NGT, GERD.\n- **Pulmonary embolism**: Blood clot travels to pulmonary vasculature. Sudden dyspnea, pleuritic chest pain, tachycardia, hypoxemia.\n- **Laryngospasm**: Reflex closure of vocal cords. Occurs during emergence or PACU. Stridor, inability to ventilate.\n\n## Interventions / Management\n- Encourage deep breathing and coughing exercises every 1-2 hours while awake.\n- Use incentive spirometry with specific volume goals (10 breaths every hour while awake).\n- Teach splinting technique for abdominal/thoracic incisions.\n- Promote early ambulation to improve lung expansion.\n- Elevate head of bed 30-45 degrees unless contraindicated.\n- Assess breath sounds systematically every shift.\n\n## Clinical Pearls\n- Atelectasis is the most common cause of fever in the first 24-48 hours postoperatively.\n- Incentive spirometry should focus on SLOW, DEEP breaths with a 3-5 second inspiratory hold, not rapid breathing.\n- Upper abdominal and thoracic incisions have the highest risk for PPCs due to diaphragmatic splinting.\n- Postoperative pneumonia typically develops on POD 3-5, while atelectasis develops within 24-48 hours.`,
    checkpointQuestions: [
      { question: "What is the most common cause of fever in the first 24-48 hours after surgery?", options: ["Surgical site infection", "Urinary tract infection", "Atelectasis", "Drug reaction"], correctIndex: 2, rationale: "Atelectasis (alveolar collapse) is the most common cause of early postoperative fever (within the first 24-48 hours). It results from hypoventilation, shallow breathing, and mucus retention." }
    ],
    commonMistakes: ["Attributing early postoperative fever to SSI instead of atelectasis", "Not emphasizing slow deep breaths with IS", "Not elevating head of bed to 30-45 degrees"],
    examTrapWarning: "Early fever (24-48 hrs) = atelectasis. Day 3-5 fever = pneumonia, UTI. Day 5-7 = SSI, DVT. Remember the 5 W's of postop fever: Wind, Water, Wound, Walk, Wonder drugs.",
    clinicalReasoning: "A postoperative patient with low-grade fever, decreased breath sounds at the bases, and crackles on auscultation within the first 24 hours most likely has atelectasis, not infection. Treatment focuses on aggressive incentive spirometry, coughing and deep breathing, and early ambulation.",
    relatedFlashcardTopics: ["Atelectasis", "Postoperative Pneumonia", "Incentive Spirometry", "Respiratory Assessment"] },
  { title: "Postoperative Ileus and GI Complications", slug: "postoperative-ileus-gi-complications", domain: "Postoperative Patient Care", difficulty: "intermediate",
    content: `## Overview\nPostoperative ileus (POI) is a temporary impairment of GI motility following surgery. It is most common after abdominal surgery and is exacerbated by opioid use, electrolyte imbalances, immobility, and surgical handling of the bowel.\n\n## Key Concepts\n- **Postoperative ileus**: Absent or reduced peristalsis. Normal recovery: small bowel (24 hours), stomach (24-48 hours), colon (3-5 days). Prolonged ileus > 5 days is pathologic.\n- **Symptoms**: Absent bowel sounds, abdominal distension, nausea, vomiting, inability to pass flatus or stool.\n- **Risk factors**: Abdominal surgery (especially open), opioid use, electrolyte abnormalities (hypokalemia most common), immobility, fluid overload.\n- **Bowel obstruction vs. ileus**: Obstruction has mechanical cause (adhesion, hernia, tumor) with intermittent cramping pain and high-pitched bowel sounds. Ileus has no mechanical cause with absent bowel sounds.\n\n## Interventions / Management\n- Encourage early ambulation (most effective prevention and treatment).\n- Minimize opioid use with multimodal analgesia.\n- Correct electrolyte imbalances (especially potassium).\n- Advance diet as tolerated using an evidence-based approach (clear liquids are NOT required before regular diet).\n- Consider gum chewing (sham feeding stimulates vagus nerve and peristalsis).\n- Monitor for return of bowel function: passing flatus is the key indicator of returning motility.\n\n## Clinical Pearls\n- Gum chewing after abdominal surgery has been shown to reduce ileus duration. It is a simple, cost-effective intervention.\n- Hypokalemia (K+ < 3.5) worsens ileus because potassium is essential for smooth muscle contractility.\n- Passing flatus is the most reliable indicator that bowel function is returning.\n- ERAS protocols recommend offering regular diet on POD 0 or 1 without waiting for bowel sounds or flatus (evidence shows this is safe and accelerates recovery).`,
    checkpointQuestions: [
      { question: "Which intervention has the strongest evidence for preventing postoperative ileus?", options: ["Nasogastric tube decompression", "Early ambulation", "Withholding oral intake until bowel sounds return", "IV prokinetic medications"], correctIndex: 1, rationale: "Early ambulation is the most effective intervention for preventing and treating postoperative ileus. It stimulates intestinal motility through increased parasympathetic activity and improved blood flow to the gut." }
    ],
    commonMistakes: ["Waiting for bowel sounds before advancing diet", "Not correcting hypokalemia", "Over-relying on opioids instead of multimodal analgesia"],
    examTrapWarning: "Early ambulation is the BEST prevention for ileus. Passing flatus = bowel function returning. Hypokalemia worsens ileus. Gum chewing stimulates peristalsis.",
    clinicalReasoning: "A postoperative patient with abdominal distension, absent bowel sounds, and nausea on POD 4 who has been receiving morphine PCA and has a potassium of 3.1 mEq/L likely has ileus exacerbated by opioids and hypokalemia. Interventions: correct potassium, switch to non-opioid analgesia, encourage ambulation, consider gum chewing.",
    relatedFlashcardTopics: ["Postoperative Ileus", "Bowel Assessment", "ERAS Protocols", "Electrolyte Correction"] },
  { title: "Postoperative Urinary Retention", slug: "postoperative-urinary-retention", domain: "Postoperative Patient Care", difficulty: "beginner",
    content: `## Overview\nPostoperative urinary retention (POUR) is the inability to void within 6-8 hours after surgery or the presence of a distended bladder with no output. It is common after spinal anesthesia, pelvic/rectal surgery, and procedures involving anticholinergic medications.\n\n## Key Concepts\n- **Risk factors**: Spinal/epidural anesthesia (parasympathetic block), pelvic surgery, rectal surgery, hernia repair, anticholinergic medications, opioids, age > 50, male sex, history of BPH.\n- **Assessment**: Bladder scan (ultrasound) for residual volume > 400-600 mL warrants catheterization. Palpation of suprapubic area for distension.\n- **Management**: Non-invasive first: privacy, running water, warm water over perineum, upright position. If unsuccessful: intermittent (straight) catheterization. Avoid indwelling catheter if possible (CAUTI risk).\n\n## Interventions / Management\n- Monitor voiding after surgery. Expected void within 6-8 hours of surgery or last catheter removal.\n- Perform bladder scan if patient has not voided and reports suprapubic fullness.\n- Try non-invasive measures first.\n- Perform straight catheterization for volumes > 400-600 mL.\n- Avoid routine indwelling catheter placement (increases CAUTI risk).\n- Document voiding pattern, volume, and any catheterization performed.\n\n## Clinical Pearls\n- Spinal anesthesia blocks the S2-S4 dermatomes that control the micturition reflex. Voiding function typically returns within 6-8 hours after spinal wears off.\n- Bladder overdistension (> 600 mL) can damage the detrusor muscle and worsen retention.\n- Intermittent (straight) catheterization has LOWER infection risk than indwelling catheterization.\n- Male patients over 50 with BPH are at highest risk for POUR.`,
    checkpointQuestions: [
      { question: "A patient has not voided 8 hours after spinal anesthesia. The bladder scan shows 550 mL. What is the appropriate intervention?", options: ["Wait another 2 hours", "Place an indwelling Foley catheter", "Perform intermittent (straight) catheterization", "Administer furosemide"], correctIndex: 2, rationale: "Intermittent (straight) catheterization is preferred over indwelling catheterization to reduce CAUTI risk. A volume > 400-600 mL after 8 hours warrants catheterization to prevent bladder overdistension." }
    ],
    commonMistakes: ["Placing an indwelling catheter instead of straight catheterization", "Not performing bladder scan before catheterization", "Ignoring suprapubic complaints"],
    examTrapWarning: "Straight catheterization preferred over indwelling (lower CAUTI risk). Spinal anesthesia blocks S2-S4 micturition reflex. Bladder overdistension > 600 mL can cause detrusor damage.",
    clinicalReasoning: "A patient after inguinal hernia repair under spinal anesthesia who has not voided in 7 hours and reports lower abdominal pressure should have a bladder scan performed. If the volume is > 400 mL, straight catheterization is indicated rather than continuing to wait.",
    relatedFlashcardTopics: ["Urinary Retention", "Bladder Scan", "CAUTI Prevention", "Spinal Anesthesia Complications"] },
  { title: "Discharge Planning and Postoperative Instructions", slug: "discharge-planning-postoperative", domain: "Postoperative Patient Care", difficulty: "beginner",
    content: `## Overview\nDischarge planning begins at preadmission and continues throughout the perioperative experience. Effective discharge education ensures patients can safely manage their recovery at home, recognize warning signs, and follow up appropriately.\n\n## Key Concepts\n- **Discharge criteria**: Stable vital signs, adequate pain control with oral medications, tolerance of oral intake, voiding spontaneously, ambulating safely, wound/drain management competence, understanding of discharge instructions.\n- **Outpatient surgery discharge**: Must have a responsible adult escort. Cannot drive, operate machinery, make legal decisions for 24 hours after sedation/anesthesia.\n- **Instruction content**: Wound care, activity restrictions, medication instructions (new and resumed), diet progression, follow-up appointment, when to call the surgeon (signs of infection, uncontrolled pain, fever, bleeding), when to call 911 (chest pain, severe dyspnea, signs of DVT/PE).\n- **Teach-back verification**: Patient/caregiver must demonstrate understanding of all instructions.\n\n## Interventions / Management\n- Provide written and verbal instructions in appropriate language and health literacy level.\n- Use teach-back to verify understanding of critical information.\n- Ensure prescriptions are filled or a plan for obtaining medications exists.\n- Schedule follow-up appointment before discharge when possible.\n- Provide 24-hour contact number for questions or concerns.\n- Document all education provided and patient's demonstrated understanding.\n\n## Clinical Pearls\n- Patients retain less than 50% of discharge instructions within 24 hours. Written reinforcement is essential.\n- Including the caregiver in discharge education significantly improves adherence.\n- Patients should be given specific parameters: "Call the surgeon if your temperature is above 101°F" rather than vague instructions.\n- Same-day surgery patients who had sedation must NOT drive, operate machinery, or sign legal documents for 24 hours.`,
    checkpointQuestions: [
      { question: "What is the MOST important nursing intervention to verify that a patient understands discharge instructions?", options: ["Have the patient sign the instruction sheet", "Ask 'Do you have any questions?'", "Use the teach-back method", "Provide written instructions in large font"], correctIndex: 2, rationale: "The teach-back method, where the patient explains the instructions in their own words, is the most effective way to verify understanding. A signed form or asking about questions does not confirm comprehension." }
    ],
    commonMistakes: ["Assuming signed form equals understanding", "Not including caregivers in education", "Providing vague instructions without specific parameters"],
    examTrapWarning: "Teach-back is the gold standard for verifying understanding. Patients cannot drive or make legal decisions for 24 hours after sedation/anesthesia.",
    clinicalReasoning: "When preparing a patient for discharge after outpatient surgery, the perioperative nurse must verify that a responsible adult is available to accompany the patient home and stay with them. Discharging a patient who received sedation to drive themselves home is a patient safety and legal issue.",
    relatedFlashcardTopics: ["Discharge Planning", "Patient Education", "Outpatient Surgery", "Teach-Back Method"] }
];
