import type { PerioperativeLesson } from "./types";

export const professionalAccountability: PerioperativeLesson[] = [
  { title: "AORN Standards and Recommended Practices", slug: "aorn-standards-recommended-practices", domain: "Professional Accountability", difficulty: "beginner",
    content: `## Overview\nThe Association of periOperative Registered Nurses (AORN) establishes standards of care and recommended practices that guide perioperative nursing practice. These evidence-based guidelines define the standard of care for perioperative nursing and are used as benchmarks for quality improvement, competency assessment, and legal standards.\n\n## Key Concepts\n- **AORN Perioperative Standards**: Define the responsibilities, behaviors, and quality of perioperative nursing care. Based on the nursing process (assessment, diagnosis, outcomes identification, planning, implementation, evaluation).\n- **AORN Guidelines for Perioperative Practice**: Evidence-based recommended practices covering all aspects of perioperative care (sterilization, positioning, counts, aseptic technique, environmental cleaning, etc.).\n- **Perioperative Nursing Data Set (PNDS)**: Standardized nursing language for perioperative documentation. Includes perioperative nursing diagnoses, interventions, and outcomes.\n- **Competency assessment**: Perioperative nurses must demonstrate and maintain competency through initial orientation, ongoing education, annual skills validation, and certification.\n\n## Clinical Pearls\n- AORN guidelines represent the evidence-based standard of care. Deviation from these guidelines must be documented with clinical rationale.\n- The PNDS provides standardized language that enables data collection, outcomes measurement, and research in perioperative nursing.\n- CNOR certification demonstrates advanced perioperative knowledge and is recognized as a mark of excellence.\n- AORN publishes position statements on critical issues: nurse-to-patient ratios, safe staffing, perioperative workplace safety, and more.`,
    checkpointQuestions: [
      { question: "What is the primary purpose of AORN Guidelines for Perioperative Practice?", options: ["To establish hospital policies", "To provide evidence-based recommended practices for perioperative nursing", "To replace institutional policies", "To create nursing diagnosis codes"], correctIndex: 1, rationale: "AORN Guidelines provide evidence-based recommended practices that guide perioperative nursing care. They represent the standard of care and serve as a foundation for institutional policies, but do not replace facility-specific policies." }
    ],
    commonMistakes: ["Not staying current with updated AORN guidelines", "Confusing AORN guidelines with mandatory regulatory requirements", "Not using PNDS standardized language in documentation"],
    examTrapWarning: "AORN guidelines = evidence-based standard of care. PNDS = standardized perioperative nursing language. CNOR = perioperative certification. Deviation from guidelines must be documented with rationale.",
    clinicalReasoning: "When a surgeon requests a practice that deviates from AORN recommended practices (e.g., skipping a count), the perioperative nurse should advocate for the patient by explaining the rationale for the guideline, offering alternatives, and documenting the deviation if it occurs.",
    relatedFlashcardTopics: ["AORN Standards", "PNDS", "Perioperative Competency", "Evidence-Based Practice"] },
  { title: "Legal and Ethical Issues in Perioperative Nursing", slug: "legal-ethical-perioperative-nursing", domain: "Professional Accountability", difficulty: "intermediate",
    content: `## Overview\nPerioperative nurses face unique legal and ethical challenges including informed consent, patient advocacy, scope of practice, delegation, documentation, and liability. Understanding the legal framework protects both the patient and the nurse.\n\n## Key Concepts\n- **Negligence and malpractice**: Requires four elements: duty (nurse-patient relationship existed), breach of duty (standard of care was violated), causation (the breach caused injury), damages (patient suffered harm). Perioperative nurses are held to the standard of a "reasonable, prudent perioperative nurse."\n- **Scope of practice**: Defined by the state nurse practice act, institutional policies, and professional standards. Perioperative nurses must practice within their scope and only perform tasks for which they are competent.\n- **Patient advocacy**: The perioperative nurse is the patient's primary advocate, especially when the patient is unable to speak for themselves (under anesthesia). This includes questioning unsafe practices, maintaining sterile technique, and ensuring informed consent.\n- **Delegation**: RNs may delegate tasks to LPNs/LVNs and UAPs within legal and institutional guidelines. The RN retains accountability for delegated tasks. Assessment, planning, evaluation, and patient education cannot be delegated.\n- **Advance directives**: Perioperative nurses must know the patient's code status and advance directive preferences. Some facilities suspend DNR during anesthesia (requires patient/family discussion); others honor them.\n- **Conscience clause**: Nurses may refuse to participate in procedures that violate their moral or religious beliefs (e.g., termination of pregnancy) if patient safety is not compromised and alternative staffing is available.\n\n## Clinical Pearls\n- A perioperative nurse who observes a break in sterile technique and fails to report it may be held liable for negligence if the patient develops an SSI.\n- Documentation is the nurse's strongest defense against malpractice claims. Thorough, accurate, timely documentation proves the standard of care was met.\n- The nurse must NEVER falsify or alter documentation. Late entries are acceptable when properly noted.\n- Patient advocacy may require speaking up against surgeons, anesthesiologists, or other team members who engage in unsafe practices. This is legally and ethically protected.`,
    checkpointQuestions: [
      { question: "Which assessment task can the perioperative RN delegate to a UAP (unlicensed assistive personnel)?", options: ["Preoperative nursing assessment", "Obtaining vital signs", "Patient education about surgery", "Evaluation of patient outcomes"], correctIndex: 1, rationale: "UAPs can obtain vital signs under RN supervision. Assessment (interpretation of vital signs), planning, education, and evaluation are nursing responsibilities that CANNOT be delegated to UAPs." }
    ],
    commonMistakes: ["Delegating nursing assessment to UAPs", "Not documenting breaks in sterile technique", "Altering or falsifying documentation"],
    examTrapWarning: "Four elements of negligence: duty, breach, causation, damages. RNs cannot delegate assessment, planning, evaluation, or education. Documentation is the best legal defense.",
    clinicalReasoning: "When a circulating nurse observes the surgeon begin to make an incision before the time-out is completed, the nurse has a legal and ethical obligation to stop the procedure and complete the safety verification. Failure to act could constitute negligence if a wrong-site error occurs.",
    relatedFlashcardTopics: ["Nursing Negligence", "Patient Advocacy", "Delegation", "Scope of Practice"] },
  { title: "Quality Improvement and Evidence-Based Practice", slug: "quality-improvement-evidence-based", domain: "Professional Accountability", difficulty: "intermediate",
    content: `## Overview\nQuality improvement (QI) in perioperative nursing uses systematic approaches to analyze and improve patient outcomes, safety, and efficiency. Evidence-based practice (EBP) integrates the best available research with clinical expertise and patient values to guide clinical decisions.\n\n## Key Concepts\n- **Quality improvement methodologies**: Plan-Do-Study-Act (PDSA cycle), Lean methodology, Six Sigma, Root Cause Analysis (RCA), Failure Mode and Effects Analysis (FMEA).\n- **Key quality metrics in perioperative care**: SSI rates, wrong-site surgery events, retained surgical items, patient falls, pressure injuries, hypothermia rates, antibiotic timing compliance, first-case start time, turnover time, patient satisfaction.\n- **Sentinel events**: Unexpected events resulting in death or serious injury. Require RCA and corrective action plan. Examples: wrong-site surgery, retained surgical item, patient death from medication error.\n- **Never events**: Serious reportable events that should never occur. Includes wrong-site/wrong-patient/wrong-procedure surgery, RSIs, and patient death from fall.\n- **EBP process**: Ask a clinical question (PICO format), search for best evidence, critically appraise the evidence, integrate evidence with clinical expertise and patient preferences, evaluate the outcome.\n\n## Clinical Pearls\n- The PDSA cycle (Plan-Do-Study-Act) is the most commonly used QI methodology in healthcare. It promotes small, iterative changes that can be measured and refined.\n- Root Cause Analysis (RCA) looks at system failures, not individual blame. It asks "why did this happen?" not "who did this?"\n- FMEA is a PROACTIVE approach to identifying potential failures before they occur, while RCA is REACTIVE (after an event).\n- The CNOR exam tests knowledge of QI concepts including the difference between QA (inspecting for compliance) and QI (continuous improvement focus).`,
    checkpointQuestions: [
      { question: "What is the key difference between Root Cause Analysis (RCA) and Failure Mode and Effects Analysis (FMEA)?", options: ["RCA is proactive, FMEA is reactive", "RCA is reactive (after an event), FMEA is proactive (before an event)", "They are the same process", "RCA focuses on individual blame, FMEA focuses on systems"], correctIndex: 1, rationale: "RCA is a reactive analysis conducted after a sentinel event to identify system failures that contributed to the event. FMEA is a proactive analysis that identifies potential failure modes in a process before an adverse event occurs." }
    ],
    commonMistakes: ["Confusing RCA (reactive) with FMEA (proactive)", "Focusing on individual blame instead of system improvement", "Not using EBP to guide clinical decisions"],
    examTrapWarning: "RCA = reactive (after event). FMEA = proactive (prevent events). PDSA = most common QI cycle. Never events should NEVER occur. Sentinel events require RCA.",
    clinicalReasoning: "After a retained sponge event, the RCA should examine system factors: Was the count protocol followed? Were there distractions? Was the team adequately staffed? Was there a change in procedure? The goal is to identify system improvements, not punish individuals.",
    relatedFlashcardTopics: ["Quality Improvement", "RCA", "FMEA", "Evidence-Based Practice"] },
  { title: "Perioperative Documentation Standards", slug: "perioperative-documentation-standards", domain: "Professional Accountability", difficulty: "beginner",
    content: `## Overview\nPerioperative documentation provides a legal record of care, supports communication between providers, and enables quality measurement. It must be accurate, complete, timely, and objective. The perioperative nursing record captures all aspects of care from admission through PACU discharge.\n\n## Key Concepts\n- **Documentation principles**: Accurate, objective, complete, timely, legible (or electronic), factual, without opinions or value judgments.\n- **Required documentation elements**: Patient identification, consent verification, time-out completion, positioning details and team members, skin assessment (before and after), count status, medications administered, specimens collected, implant information, equipment used and settings, estimated blood loss, wound classification, fluids/output, intraoperative events.\n- **Incident reporting**: Document the FACTS of what happened, not conclusions or blame. Incident reports are separate from the medical record. They are quality improvement tools, not part of the legal medical record.\n- **Late entries**: Acceptable when noted as "late entry" with the current date/time and reference to the original event date/time. Never backdate entries.\n- **Corrections**: Draw a single line through the error, write "error" or institution-approved abbreviation, date, time, and initial. NEVER use correction fluid, scribble out, or make entries illegible.\n\n## Clinical Pearls\n- "If it wasn't documented, it wasn't done" is the fundamental principle of healthcare documentation for legal purposes.\n- Incident reports should contain only objective facts, not opinions, blame, or conclusions about cause. Do NOT reference the incident report in the medical record.\n- Electronic health record (EHR) systems create an audit trail of all entries, modifications, and access. All entries are timestamped and attributed to the user.\n- Use standardized, approved abbreviations only. Avoid The Joint Commission's "Do Not Use" abbreviation list (U, IU, Q.D., Q.O.D., trailing zeros, leading zeros).`,
    checkpointQuestions: [
      { question: "How should a documentation error be corrected in the medical record?", options: ["Use correction fluid to cover the error", "Scribble out the incorrect entry completely", "Draw a single line through the error, write 'error,' date, time, and initial", "Delete the entry and rewrite it"], correctIndex: 2, rationale: "Proper correction of documentation errors requires drawing a single line through the error (leaving it legible), writing 'error' or the institution-approved notation, and adding the date, time, and initials. Never use correction fluid, scribble, or make entries illegible." }
    ],
    commonMistakes: ["Using correction fluid or scribbling out errors", "Including opinions in incident reports", "Referencing the incident report in the medical record"],
    examTrapWarning: "Single line through error + 'error' + date + time + initials. Incident reports are NOT part of the medical record. Never backdate entries. 'If not documented, not done.'",
    clinicalReasoning: "When a nurse realizes 2 hours after a case that they forgot to document the surgical site prep, they should make a late entry noting the current time, referencing the original procedure time, and documenting the prep details. This is legally acceptable and preferred over leaving the documentation incomplete.",
    relatedFlashcardTopics: ["Documentation Standards", "Incident Reporting", "Legal Documentation", "Correction of Errors"] },
  { title: "Patient Rights and Advocacy in Perioperative Care", slug: "patient-rights-advocacy-perioperative", domain: "Professional Accountability", difficulty: "beginner",
    content: `## Overview\nThe perioperative nurse serves as the patient's primary advocate, especially when the patient is vulnerable (anesthetized, sedated, or unable to communicate). Patient rights include informed consent, privacy, confidentiality, respectful care, and the right to refuse treatment.\n\n## Key Concepts\n- **Patient rights**: Informed consent, refusal of treatment at any time, privacy and confidentiality (HIPAA), respectful care regardless of race/religion/gender/socioeconomic status, access to medical records, participate in care decisions, advance directive recognition.\n- **HIPAA**: Protected health information (PHI) must be safeguarded. Conversations about patients should not occur in public areas. Computer screens should be positioned away from public view. Minimum necessary standard applies.\n- **Cultural competency**: Respect cultural and religious preferences regarding modesty, gender of caregivers, blood products, dietary restrictions, and end-of-life care.\n- **Jehovah's Witness patients**: May refuse blood products on religious grounds. This must be documented and respected. Bloodless surgery techniques and alternatives (cell saver with certain restrictions, erythropoietin preoperatively) should be discussed.\n- **Patient advocacy examples**: Stopping a procedure for consent discrepancy, reporting sterile technique breaks, advocating for appropriate pain management, protecting unconscious patient dignity.\n\n## Clinical Pearls\n- A patient can withdraw consent at ANY point, even when on the OR table. The nurse must advocate for this right.\n- Discussing patient information in the elevator, cafeteria, or hallway is a HIPAA violation, even if no one appears to be listening.\n- Cultural competency includes asking patients about their preferences rather than making assumptions based on cultural background.\n- The perioperative nurse must ensure that the patient's dignity is maintained during all phases: adequate covering during transport, limiting exposure during prep, and providing privacy during recovery.`,
    checkpointQuestions: [
      { question: "A Jehovah's Witness patient who has signed a refusal of blood products begins hemorrhaging intraoperatively. The surgeon wants to transfuse. What should the perioperative nurse do?", options: ["Prepare the blood products since the patient's life is at risk", "Respect the patient's documented refusal and support the use of alternative hemostatic measures", "Override the refusal since the patient is unconscious", "Ask the family to override the refusal"], correctIndex: 1, rationale: "A competent patient's documented refusal of blood products must be respected, even in a life-threatening situation. The perioperative nurse advocates for the patient's autonomy by supporting the refusal and assisting with bloodless surgery alternatives." }
    ],
    commonMistakes: ["Overriding patient refusal of treatment in emergencies", "Discussing patient information in public areas", "Making cultural assumptions without asking the patient"],
    examTrapWarning: "Patients can refuse treatment at any time. HIPAA applies to ALL conversations about patients. Jehovah's Witness blood refusal must be respected. Cultural competency = ASK, don't assume.",
    clinicalReasoning: "When an anesthetized patient's family member arrives and asks to override the patient's advance directive (DNR), the perioperative nurse must follow the patient's documented wishes, not the family's request, unless the family has legal authority to do so (healthcare power of attorney with different instructions).",
    relatedFlashcardTopics: ["Patient Rights", "HIPAA", "Cultural Competency", "Patient Advocacy"] },
  { title: "Perioperative Nursing Certification (CNOR)", slug: "perioperative-nursing-certification-cnor", domain: "Professional Accountability", difficulty: "beginner",
    content: `## Overview\nThe Certified Perioperative Nurse (CNOR) credential is awarded by the Competency & Credentialing Institute (CCI). It validates specialized knowledge in perioperative nursing and is recognized as the gold standard for perioperative nursing certification.\n\n## Key Concepts\n- **Eligibility**: Current RN license, minimum 2 years and 2400 hours of perioperative nursing experience within the last 5 years.\n- **Exam format**: 200 multiple-choice questions (185 scored, 15 pretest), computer-based, 4-hour time limit.\n- **Content domains**: (1) Preoperative Patient Assessment, (2) Intraoperative Care, (3) Postoperative Patient Care, (4) Equipment and Supplies, (5) Sterilization and Disinfection, (6) Emergency Situations, (7) Infection Prevention, (8) Patient Safety, (9) Professional Accountability, (10) Management of Personnel.\n- **Recertification**: Every 5 years through contact hours or re-examination.\n- **Benefits**: Demonstrates advanced knowledge, may qualify for salary differential, enhances professional credibility, improves patient outcomes (studies show CNOR-credentialed nurses are associated with lower SSI rates).\n\n## Clinical Pearls\n- Research shows that hospitals with higher percentages of CNOR-certified perioperative nurses have lower surgical complication rates.\n- The CNOR exam emphasizes clinical application and critical thinking, not rote memorization. Questions test the ability to apply knowledge to patient care scenarios.\n- Study strategies: Use AORN guidelines as the primary study resource, practice with scenario-based questions, focus on patient safety priorities.\n- CNOR certification requires ongoing professional development and reflects a commitment to lifelong learning in perioperative nursing.`,
    checkpointQuestions: [
      { question: "How often must CNOR certification be renewed?", options: ["Every 2 years", "Every 3 years", "Every 5 years", "Every 10 years"], correctIndex: 2, rationale: "CNOR certification must be renewed every 5 years through either accumulation of continuing education contact hours or by re-examination." }
    ],
    commonMistakes: ["Not meeting the minimum experience requirement before applying", "Focusing on memorization instead of clinical application", "Not using AORN guidelines as the primary study resource"],
    examTrapWarning: "CNOR covers 10 domains. Renewed every 5 years. 200 questions, 4-hour limit. Must have 2 years/2400 hours perioperative experience. Evidence links CNOR to better patient outcomes.",
    clinicalReasoning: "Pursuing CNOR certification is both a personal professional development goal and a patient safety initiative. Studies demonstrate that certified perioperative nurses are associated with improved patient outcomes, including lower SSI rates and fewer adverse events.",
    relatedFlashcardTopics: ["CNOR Certification", "CCI", "Perioperative Competency", "Professional Development"] }
];
