import pg from "pg";
import crypto from "crypto";
const Pool = pg.Pool;
const pool = new Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });
function hash(s: string): string { return crypto.createHash("md5").update(s.toLowerCase().trim()).digest("hex"); }
function rn(e:string,b:string,d:number,s:string,o:string[],c:number,r:string) {
  return {tier:"rn",exam:e,stem:s,options:o,correct:c,rationale:r,diff:d,bs:b};
}

const QS = [
  rn("NCLEX-RN","Cardiovascular",3,"A client receiving dobutamine should be monitored for which adverse effect?",["Hypothermia","Tachycardia and ventricular ectopy from increased myocardial contractility","Bradycardia","Bronchospasm"],1,"Dobutamine (beta-1 agonist) increases cardiac contractility and heart rate. Tachycardia increases myocardial oxygen demand and can trigger arrhythmias. Continuous ECG and hemodynamic monitoring are required. Titrate to achieve desired cardiac output."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with a recent ST-elevation MI should receive dual antiplatelet therapy consisting of:",["Aspirin alone","Aspirin plus a P2Y12 inhibitor (clopidogrel, ticagrelor, or prasugrel)","Warfarin plus aspirin","Two different NSAIDs"],1,"DAPT (aspirin + P2Y12 inhibitor) after STEMI reduces recurrent ischemic events by inhibiting platelet aggregation through two different pathways. Duration is typically 12 months post-ACS. Bleeding risk requires monitoring."),
  rn("RN-CAT","Cardiovascular",4,"A client with Brugada syndrome is at risk for:",["Coronary artery disease","Sudden cardiac death from ventricular fibrillation","Aortic dissection","Pulmonary embolism"],1,"Brugada syndrome is an inherited channelopathy causing characteristic ECG pattern (coved ST elevation in V1-V3) and risk of VF/sudden cardiac death. ICD implantation is indicated for high-risk patients. No antiarrhythmic drug prevents VF effectively."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with chronic stable angina has an abnormal stress test. The nurse should anticipate:",["Discharge with follow-up in 6 months","Coronary angiography to evaluate for revascularization","Immediate thrombolytic therapy","Bedrest for 2 weeks"],1,"Abnormal stress test with significant ischemia warrants coronary angiography to define coronary anatomy and guide treatment decisions (medical management, PCI, or CABG). Risk stratification helps determine urgency of intervention."),
  rn("NCLEX-RN","Respiratory",3,"A client with acute respiratory distress syndrome requires lung-protective ventilation. This includes:",["High tidal volumes to maximize oxygenation","Low tidal volumes (6 mL/kg ideal body weight) with plateau pressures below 30 cmH2O","Maximum PEEP without monitoring compliance","Rapid ventilator cycling"],1,"ARDSNet protocol: low tidal volumes (6 mL/kg IBW) reduce volutrauma, plateau pressure < 30 cmH2O reduces barotrauma. Higher PEEP maintains alveolar recruitment. This strategy reduces mortality. Permissive hypercapnia may be necessary."),
  rn("NCLEX-RN","Respiratory",3,"A client with pulmonary embolism has a Wells score of 8. The nurse should anticipate:",["CT pulmonary angiography for diagnosis confirmation","D-dimer testing only","Chest X-ray as sole diagnostic tool","Observation without testing"],0,"Wells score >= 7 indicates high probability PE. CTPA is the gold standard diagnostic test. D-dimer is useful only for low/intermediate probability (high sensitivity, low specificity). Immediate anticoagulation should be started while awaiting confirmation."),
  rn("RN-CAT","Respiratory",4,"A client on mechanical ventilation develops auto-PEEP. The nurse should:",["Increase the respiratory rate","Decrease the respiratory rate and increase expiratory time to allow complete exhalation","Increase tidal volume","Add more PEEP"],1,"Auto-PEEP (intrinsic PEEP) occurs when air is trapped due to incomplete exhalation, common in obstructive lung disease. Management: decrease rate, increase expiratory time (decrease I:E ratio), bronchodilators, and possible sedation to reduce breathing effort."),
  rn("NCLEX-RN","Neurological",3,"A client with myasthenia gravis develops a myasthenic crisis. The nurse should prepare for:",["Immediate thymectomy","Respiratory support with possible intubation, plasmapheresis, or IVIG","Increasing anticholinesterase dose without limit","Withholding all medications"],1,"Myasthenic crisis is life-threatening respiratory muscle weakness. Treatment: secure airway (intubation if FVC < 15-20 mL/kg), plasmapheresis or IVIG for rapid improvement, hold anticholinesterases initially (can cause cholinergic crisis), restart cautiously."),
  rn("NCLEX-RN","Neurological",3,"The nurse differentiates myasthenic crisis from cholinergic crisis by administering:",["Atropine","Edrophonium (Tensilon): improvement indicates myasthenic crisis; worsening indicates cholinergic crisis","Additional pyridostigmine","Epinephrine"],1,"Edrophonium test differentiates the two crises: positive response (strength improves) = myasthenic crisis (underdosed anticholinesterase). Worsening = cholinergic crisis (overdosed anticholinesterase). Have atropine ready to reverse cholinergic effects."),
  rn("NCLEX-RN","Neurological",3,"A client with a Glasgow Coma Scale of 6 and unequal pupils has signs of uncal herniation. The nurse should anticipate:",["Conservative management and observation","Emergency intervention including hyperventilation, osmotic therapy, and possible surgical decompression","Lumbar puncture","CT scan as the only intervention"],1,"Uncal herniation (ipsilateral pupil dilation, contralateral hemiparesis) requires emergent ICP management: elevation HOB 30 degrees, hyperventilation to PaCO2 30-35 (temporary), mannitol or hypertonic saline, and possible surgical decompression (craniectomy or hematoma evacuation)."),
  rn("NCLEX-RN","Endocrine",3,"A client with Graves disease is treated with radioactive iodine therapy. The nurse should teach that:",["Thyroid function will normalize without further treatment","Hypothyroidism will likely develop, requiring lifelong levothyroxine replacement","The treatment cures hyperthyroidism permanently without consequences","A second RAI treatment is never needed"],1,"RAI destroys thyroid tissue, eventually causing hypothyroidism in most patients (often within 6-12 months). Lifelong thyroid hormone replacement with levothyroxine is needed. Thyroid function tests are monitored regularly. Pregnancy should be avoided for 6-12 months after RAI."),
  rn("NCLEX-RN","Endocrine",3,"A client with pheochromocytoma during a hypertensive crisis should receive:",["Beta-blockers first","Phentolamine (alpha-adrenergic blocker) IV for immediate blood pressure reduction","ACE inhibitors","Calcium channel blockers only"],1,"Phentolamine (IV alpha-blocker) rapidly reverses catecholamine-mediated vasoconstriction in pheochromocytoma crisis. Beta-blockers should NOT be given first (unopposed alpha stimulation worsens hypertension). Nitroprusside is an alternative."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with acute cholecystitis has Murphy sign positive. This finding is:",["Rebound tenderness in the lower abdomen","Inspiratory arrest during deep palpation of the right upper quadrant","Periumbilical bruising","Severe epigastric pain radiating to the back"],1,"Murphy sign: the examiner palpates the RUQ while the patient inspires deeply. Positive when inspiration is arrested due to the inflamed gallbladder descending to meet the examiner's hand, causing sharp pain. This is classic for acute cholecystitis."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with upper GI bleeding and hemodynamic instability should receive:",["Oral fluids and observation","Aggressive IV fluid resuscitation, blood product transfusion, and emergent endoscopy","NG tube placement only","Proton pump inhibitor alone"],1,"Active upper GI bleeding with instability requires: large-bore IV access x2, aggressive crystalloid and blood product resuscitation, IV PPI, ICU admission, and emergent EGD (within 12-24 hours, or within 12 hours if high risk) for diagnosis and hemostasis."),
  rn("RN-CAT","Gastrointestinal",4,"A client with decompensated cirrhosis and ascites has a serum ascites albumin gradient (SAAG) of 1.5. The nurse interprets this as:",["Non-portal hypertensive ascites","Portal hypertension-related ascites (SAAG >= 1.1 indicates portal hypertension)","Normal finding","Indicative of malignant ascites"],1,"SAAG >= 1.1 g/dL indicates portal hypertension as the cause of ascites (cirrhosis, heart failure, Budd-Chiari). SAAG < 1.1 suggests non-portal hypertension causes (malignancy, TB peritonitis, nephrotic syndrome). This helps guide diagnosis and management."),
  rn("NCLEX-RN","Pharmacology",3,"A client on lithium therapy develops polyuria, polydipsia, and dilute urine. The nurse suspects:",["Diabetes mellitus","Nephrogenic diabetes insipidus from lithium toxicity","Normal side effects requiring no action","Renal failure"],1,"Chronic lithium use can cause nephrogenic DI by impairing aquaporin-2 expression in collecting ducts. The kidneys become resistant to ADH, causing dilute polyuria and compensatory polydipsia. Amiloride may help. Some cases are irreversible."),
  rn("NCLEX-RN","Pharmacology",3,"A client prescribed warfarin should know that the antidote for warfarin overdose with active bleeding is:",["Protamine sulfate","Vitamin K (phytonadione) IV plus prothrombin complex concentrate for life-threatening bleeding","Fresh frozen plasma as sole therapy","Activated charcoal"],1,"Warfarin reversal: vitamin K (phytonadione) reverses warfarin effect over 6-24 hours. For life-threatening bleeding, PCC (prothrombin complex concentrate) provides immediate factor replacement. FFP is an alternative but requires larger volumes and takes longer."),
  rn("NCLEX-RN","Pharmacology",3,"A client taking monoamine oxidase inhibitors (MAOIs) for depression should be warned about consuming tyramine-rich foods because it can cause:",["Hypoglycemia","Hypertensive crisis","Hypothermia","Hypotension"],1,"MAOIs prevent tyramine breakdown in the gut. Tyramine causes catecholamine release, and without MAO metabolism, this leads to massive sympathetic activation causing severe hypertensive crisis with headache, hypertension, tachycardia, and potential stroke."),
  rn("NCLEX-RN","Mental Health",3,"A client with generalized anxiety disorder should be offered which first-line pharmacological treatment?",["Benzodiazepines long-term","SSRIs or SNRIs as first-line pharmacotherapy","Barbiturates","Antipsychotics"],1,"SSRIs (escitalopram, sertraline) and SNRIs (duloxetine, venlafaxine) are first-line for GAD. Benzodiazepines are for short-term or PRN use due to dependence risk. CBT is the first-line psychotherapy. Buspirone is an alternative anxiolytic without abuse potential."),
  rn("NCLEX-RN","Mental Health",3,"A client with bulimia nervosa is at risk for which medical complication from purging?",["Weight gain","Metabolic alkalosis, hypokalemia, dental erosion, and esophageal tears","Hyperkalemia","Hypernatremia"],1,"Purging (self-induced vomiting) causes metabolic alkalosis from HCl loss, hypokalemia (cardiac arrhythmia risk), dental enamel erosion from gastric acid, parotid gland enlargement, esophageal tears (Mallory-Weiss), and electrolyte imbalances."),
  rn("NCLEX-RN","Pediatrics",3,"A newborn with transposition of the great arteries needs which emergency intervention?",["Immediate surgical correction","Prostaglandin E1 to maintain the ductus arteriosus open and balloon atrial septostomy","Digoxin therapy","Oxygen therapy alone"],1,"TGA creates two parallel circulations (oxygenated blood recirculates through lungs, deoxygenated through body). Survival depends on mixing: PGE1 keeps ductus arteriosus patent, balloon atrial septostomy (Rashkind) creates mixing at the atrial level. Definitive surgery is arterial switch operation."),
  rn("NCLEX-RN","Pediatrics",3,"A child with autism spectrum disorder should have which intervention implemented early?",["Medication as first-line treatment","Applied behavior analysis (ABA) and speech-language therapy","Restrictive diet only","Isolation to reduce sensory stimulation"],1,"Early intensive behavioral intervention (ABA, 25+ hours/week) combined with speech-language therapy and occupational therapy improves outcomes in ASD. Starting before age 3 maximizes neuroplasticity benefits. Medications target specific symptoms (irritability, anxiety) but not core deficits."),
  rn("NCLEX-RN","Maternal/Newborn",3,"A client with placental abruption presents with painful dark red vaginal bleeding and a rigid board-like abdomen. The nurse should:",["Position on left side and monitor","Prepare for emergency delivery and initiate large-bore IV access","Apply heat to the abdomen","Perform a cervical exam immediately"],1,"Placental abruption (premature placental separation) with board-like rigidity indicates concealed hemorrhage. Emergency delivery (usually cesarean) is indicated for fetal distress or maternal instability. Two large-bore IVs, fluid resuscitation, blood products, and continuous fetal monitoring."),
  rn("NCLEX-RN","Maternal/Newborn",3,"A client in the third trimester develops cholestasis of pregnancy. The primary fetal concern is:",["Macrosomia","Increased risk of stillbirth after 37 weeks","Premature rupture of membranes","Fetal anemia"],1,"Intrahepatic cholestasis of pregnancy (elevated bile acids, pruritus) increases stillbirth risk, particularly after 37 weeks. Early delivery (37 weeks) is recommended. Ursodeoxycholic acid (UDCA) reduces bile acid levels and pruritus."),
  rn("NCLEX-RN","Renal",3,"A client with rhabdomyolysis has a CK of 25,000 U/L. The nurse should anticipate:",["Oral hydration only","Aggressive IV normal saline infusion to prevent myoglobin-induced acute kidney injury","Fluid restriction","Dialysis as first-line treatment"],1,"Rhabdomyolysis releases myoglobin which is toxic to renal tubules. Aggressive IV NS (200-300 mL/hour) maintains high urine output (> 200 mL/hour), flushes myoglobin from tubules, and prevents precipitation. Bicarbonate may alkalinize urine. Monitor CK, electrolytes, and renal function."),
  rn("NCLEX-RN","Renal",3,"A client with IgA nephropathy presents with gross hematuria coinciding with an upper respiratory infection. The nurse should explain that:",["The blood in the urine is from the respiratory infection","IgA nephropathy causes hematuria triggered by mucosal infections (synpharyngitic hematuria)","The findings are unrelated","Antibiotics will cure the kidney disease"],1,"IgA nephropathy is the most common glomerulonephritis worldwide. Characteristic synpharyngitic hematuria (within 1-2 days of URI) distinguishes it from post-streptococcal GN (2-3 week delay). IgA deposits in the mesangium cause inflammation. ACEi/ARB slow progression."),
  rn("NCLEX-RN","Hematological",3,"A client with disseminated intravascular coagulation (DIC) has paradoxical bleeding AND clotting. The nurse should understand that treatment focuses on:",["Anticoagulation only","Treating the underlying cause and replacing consumed clotting factors and platelets","Antifibrinolytic therapy alone","Observation without intervention"],1,"DIC treatment priorities: treat the underlying trigger (sepsis, malignancy, trauma), replace consumed factors (FFP, cryoprecipitate for fibrinogen < 100, platelets if < 50,000 or actively bleeding), and supportive care. Heparin is considered for clot-predominant DIC."),
  rn("NCLEX-RN","Immunological",3,"A client receiving a TNF inhibitor develops reactivation tuberculosis. The nurse should understand this occurs because:",["The medication enhances immune function","TNF is essential for granuloma maintenance, and its inhibition allows dormant TB to reactivate","The medication directly infects the client","TB is unrelated to TNF therapy"],1,"TNF-alpha is critical for forming and maintaining granulomas that contain Mycobacterium tuberculosis. TNF inhibitors (infliximab, etanercept, adalimumab) disrupt granuloma integrity, allowing dormant TB to reactivate. This is why TB screening is mandatory before starting therapy."),
  rn("NCLEX-RN","Integumentary",3,"A client with necrotizing fasciitis presents with pain disproportionate to appearance, crepitus, and rapidly spreading erythema. The nurse should:",["Apply topical antibiotics and monitor","Prepare for emergent surgical debridement as this is a surgical emergency","Administer oral antibiotics and discharge","Apply warm compresses"],1,"Necrotizing fasciitis is a surgical emergency requiring emergent aggressive debridement of all necrotic tissue, broad-spectrum IV antibiotics (vancomycin + piperacillin-tazobactam + clindamycin), hemodynamic support, and possible repeat debridements. Mortality is 20-40% even with treatment."),
  rn("RN-CAT","Cardiovascular",3,"A client with cardiac tamponade has pulsus paradoxus. This is defined as:",["Irregular pulse rhythm","A decrease in systolic blood pressure > 10 mmHg during inspiration","Alternating strong and weak pulses","Absent peripheral pulses"],1,"Pulsus paradoxus: SBP drops > 10 mmHg during inspiration due to increased venous return compressing the left ventricle in the restricted pericardial space. Measured with sphygmomanometer during normal breathing. Classic in tamponade, severe asthma, and COPD."),
  rn("NCLEX-RN","Respiratory",3,"A client with sarcoidosis has bilateral hilar lymphadenopathy on chest X-ray. The nurse should teach the client that:",["Sarcoidosis is contagious","Sarcoidosis is a granulomatous inflammatory disease that often resolves spontaneously","Immediate chemotherapy is needed","The condition affects only the lungs"],1,"Sarcoidosis is a systemic granulomatous disease of unknown etiology. Bilateral hilar lymphadenopathy is the classic CXR finding. Many cases resolve spontaneously. Corticosteroids are indicated for significant organ involvement. It can affect skin, eyes, liver, heart, and nervous system."),
  rn("NCLEX-RN","Neurological",3,"A client with status epilepticus who does not respond to lorazepam should receive:",["Additional lorazepam at higher doses","IV fosphenytoin or phenytoin loading dose","Oral carbamazepine","Observation without further medication"],1,"Status epilepticus treatment algorithm: benzodiazepine (lorazepam IV) first-line. If seizures continue after 5-10 minutes, second-line is IV fosphenytoin, valproate, or levetiracetam. Refractory SE requires continuous infusion of midazolam, propofol, or pentobarbital with EEG monitoring."),
  rn("NCLEX-RN","Endocrine",3,"A client with a pituitary adenoma producing excess growth hormone in an adult has:",["Gigantism","Acromegaly (coarsened facial features, enlarged hands and feet, prognathism)","Cushing syndrome","Addison disease"],1,"Excess GH after epiphyseal closure causes acromegaly: enlarged hands, feet, jaw (prognathism), coarsened facial features, frontal bossing, and organomegaly. Before closure = gigantism. Diagnosis: elevated IGF-1, failure to suppress GH with oral glucose tolerance test."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with acute pancreatitis should be managed with:",["Immediate oral feeding to maintain nutrition","NPO status, aggressive IV hydration, pain management, and nutritional support when tolerated","Nasogastric decompression in all cases","Surgical intervention as first-line"],1,"Acute pancreatitis management: NPO (rest the pancreas), aggressive IV hydration (250-500 mL/hr isotonic crystalloid initially), pain management (hydromorphone, PCA), and nutritional support. Early enteral feeding (within 24-48 hours if tolerated) is preferred over TPN."),
  rn("NCLEX-RN","Pharmacology",3,"A client receiving IV magnesium sulfate for preeclampsia should be monitored for:",["Hyperreflexia","Loss of deep tendon reflexes (first sign of magnesium toxicity), respiratory depression","Tachycardia","Hyperglycemia"],1,"Magnesium toxicity progression: loss of DTRs (8-12 mEq/L), respiratory depression (12-15 mEq/L), cardiac arrest (> 20 mEq/L). Monitor DTRs, respiratory rate (>= 12), urine output (>= 30 mL/hr). Antidote: calcium gluconate 1g IV."),
  rn("NCLEX-RN","Mental Health",3,"Electroconvulsive therapy (ECT) is most effective for:",["Personality disorders","Severe treatment-resistant major depression with psychotic features","Mild anxiety","ADHD"],1,"ECT is most effective for severe, treatment-resistant depression, particularly with psychotic features (80-90% response rate). Also used for catatonia and bipolar disorder. Side effects include short-term memory loss and confusion. Maintenance ECT may prevent relapse."),
  rn("NCLEX-RN","Pediatrics",3,"A child with epiglottitis should NOT have which procedure performed?",["IV insertion","Throat examination or any procedure that might cause airway spasm","Blood pressure measurement","Temperature measurement"],1,"Epiglottitis (now rare due to Hib vaccine) causes rapid airway obstruction. Any distressing procedure (throat exam, blood draw, forced position change) can trigger complete airway obstruction from laryngospasm. Maintain calm environment, allow position of comfort, and prepare for emergent intubation."),
  rn("NCLEX-RN","Maternal/Newborn",3,"The nurse performing a non-stress test observes 2 accelerations of >= 15 bpm lasting >= 15 seconds in 20 minutes. This is classified as:",["Non-reactive requiring further evaluation","Reactive, indicating fetal well-being","Indeterminate","Positive for fetal distress"],1,"A reactive NST: >= 2 accelerations of >= 15 bpm above baseline lasting >= 15 seconds in a 20-minute window. This indicates adequate fetal oxygenation and autonomic nervous system function. Non-reactive NSTs require further evaluation (biophysical profile or CST)."),
  rn("NCLEX-RN","Renal",3,"A client with membranous nephropathy has nephrotic-range proteinuria. The nurse should monitor for increased risk of:",["Bleeding complications","Thromboembolic events (loss of antithrombin III in urine)","Hypotension","Hyperkalemia"],1,"Nephrotic syndrome causes urinary loss of antithrombin III and other anticoagulant proteins, creating a hypercoagulable state. DVT, PE, and renal vein thrombosis risk is significantly elevated. Membranous nephropathy has the highest thrombotic risk among nephrotic syndromes."),
  rn("NCLEX-RN","Hematological",3,"A client receiving packed red blood cells develops fever and chills within 30 minutes. The nurse should first:",["Continue the transfusion at a slower rate","Stop the transfusion and maintain IV access with normal saline","Administer acetaminophen and continue","Increase the rate to finish quickly"],1,"Any transfusion reaction requires immediate cessation. Fever and chills may indicate febrile non-hemolytic reaction (most common) OR acute hemolytic reaction (most dangerous). Stop transfusion, maintain IV with NS (new tubing), check vitals, notify provider, send labs and blood bag to lab."),
  rn("NCLEX-RN","Immunological",3,"A client with rheumatoid arthritis is started on methotrexate. The nurse should ensure the client also takes:",["Vitamin B12","Folic acid supplementation to reduce methotrexate side effects","Iron supplements","Calcium supplements"],1,"Folic acid (1-5 mg daily) reduces MTX side effects (stomatitis, GI upset, hepatotoxicity) without reducing efficacy. Monitor CBC (bone marrow suppression), liver function, and renal function. MTX is teratogenic - pregnancy must be avoided."),
  rn("RN-CAT","Critical Care",4,"A client on continuous renal replacement therapy (CRRT) develops hypothermia. The nurse should:",["Stop CRRT immediately","Warm the replacement fluid and use blood warmers as CRRT commonly causes heat loss","Apply external warming blankets only","Increase CRRT flow rate"],1,"CRRT removes body heat as blood circulates through the extracorporeal circuit. Warming replacement fluid and using in-line blood warmers prevent hypothermia. Temperature monitoring is essential. Hypothermia affects coagulation, drug metabolism, and cardiac function."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with stable heart failure should be prescribed which medications as the evidence-based foundation?",["Only diuretics","ACEi/ARB, beta-blocker, mineralocorticoid receptor antagonist, and diuretic for congestion","Digoxin as sole therapy","Calcium channel blockers"],1,"HFrEF quadruple therapy (GDMT): ACEi/ARB/ARNI (sacubitril-valsartan), beta-blocker (carvedilol, metoprolol succinate, bisoprolol), MRA (spironolactone/eplerenone), and SGLT2 inhibitor (dapagliflozin/empagliflozin). Diuretics for congestion but no mortality benefit."),
  rn("NCLEX-RN","Respiratory",3,"A client with allergic bronchopulmonary aspergillosis has worsening asthma and peripheral eosinophilia. Treatment includes:",["Antifungal therapy alone","Systemic corticosteroids and itraconazole","Additional bronchodilators only","Surgical lung resection"],1,"ABPA treatment: systemic corticosteroids (reduce immune response and airway inflammation) plus itraconazole (reduces fungal burden and allows steroid tapering). Monitor IgE levels for disease activity. Omalizumab may be used in refractory cases."),
  rn("NCLEX-RN","Neurological",3,"A client with multiple sclerosis is prescribed interferon beta. The nurse should teach that this medication:",["Cures MS","Reduces relapse frequency and slows disability progression but does not cure MS","Works immediately","Is taken orally"],1,"Interferon beta (Avonex, Betaseron, Rebif) is a disease-modifying therapy that reduces relapse frequency by approximately 30% and slows MRI lesion accumulation. Side effects include flu-like symptoms, injection site reactions, and hepatotoxicity. Regular blood monitoring is required."),
  rn("NCLEX-RN","Endocrine",3,"A client with primary hyperparathyroidism has elevated calcium and PTH. Definitive treatment is:",["Calcitonin therapy alone","Parathyroidectomy","Bisphosphonate therapy as sole treatment","Dietary calcium restriction only"],1,"Parathyroidectomy is the only curative treatment for primary hyperparathyroidism. Indications for surgery include: calcium > 1 mg/dL above normal, age < 50, osteoporosis, renal involvement, or any symptomatic hypercalcemia. Success rate is > 95% with experienced surgeon."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with Barrett esophagus should be monitored with:",["Annual chest X-ray","Periodic surveillance endoscopy with biopsies for dysplasia detection","No follow-up needed","CT scan every 2 years"],1,"Barrett esophagus (intestinal metaplasia of esophageal squamous epithelium) increases esophageal adenocarcinoma risk. Surveillance endoscopy with 4-quadrant biopsies at regular intervals (3-5 years for non-dysplastic, more frequently for dysplasia) enables early cancer detection."),
  rn("NCLEX-RN","Pharmacology",3,"A client taking clozapine for treatment-resistant schizophrenia requires regular monitoring of:",["Liver function tests only","Absolute neutrophil count (risk of agranulocytosis)","Thyroid function","Coagulation studies"],1,"Clozapine can cause life-threatening agranulocytosis (1-2%). Mandatory ANC monitoring: weekly for first 6 months, biweekly for months 7-12, monthly thereafter (REMS program). ANC < 1500 may require dose modification. < 500 requires discontinuation."),
  rn("NCLEX-RN","Mental Health",3,"A client with antisocial personality disorder in a forensic setting should be managed with:",["Individual psychotherapy as sole treatment","Clear behavioral expectations with consistent consequences and therapeutic community approaches","Unstructured environment to promote independence","Medication as primary treatment"],1,"ASPD management focuses on external structure: clear behavioral expectations, consistent limit-setting, therapeutic community models, and motivational interventions. Individual psychotherapy has limited evidence. No medication treats ASPD directly; medications target comorbid symptoms."),
  rn("NCLEX-RN","Pediatrics",3,"A child with Hirschsprung disease presents with:",["Immediate diarrhea after birth","Failure to pass meconium within 48 hours of birth, abdominal distension, and bilious vomiting","Normal bowel pattern","Rectal bleeding only"],1,"Hirschsprung disease (aganglionosis of distal colon) presents with failure to pass meconium within 24-48 hours, progressive abdominal distension, bilious vomiting, and enterocolitis risk. Diagnosis: rectal suction biopsy showing absent ganglion cells. Treatment: surgical pull-through procedure."),
  rn("NCLEX-RN","Maternal/Newborn",3,"During fetal heart rate monitoring, late decelerations indicate:",["Head compression during contractions","Uteroplacental insufficiency requiring immediate evaluation","Normal fetal response","Umbilical cord compression"],1,"Late decelerations (onset at contraction peak, nadir after contraction peak) indicate uteroplacental insufficiency. Interventions: left lateral positioning, IV fluids, oxygen, stop oxytocin, and notify provider. Persistent late decelerations may require emergency delivery."),
  rn("NCLEX-RN","Renal",3,"A client with lupus nephritis has active disease on biopsy. Treatment includes:",["NSAIDs for inflammation","Immunosuppressive therapy (mycophenolate mofetil or cyclophosphamide with corticosteroids)","Antibiotics","Dietary changes alone"],1,"Lupus nephritis (Class III/IV) requires aggressive immunosuppression: induction with mycophenolate mofetil or cyclophosphamide plus corticosteroids, followed by maintenance immunosuppression. ACEi/ARB for proteinuria reduction. Hydroxychloroquine is continued for SLE management."),
  rn("NCLEX-RN","Hematological",3,"A client with immune thrombocytopenic purpura (ITP) has a platelet count of 8,000. First-line treatment includes:",["Platelet transfusion alone","IV immunoglobulin (IVIG) and/or corticosteroids","Splenectomy immediately","Observation without treatment"],1,"ITP first-line: corticosteroids (prednisone) and/or IVIG (for rapid count elevation). IVIG works within 24-48 hours by blocking Fc receptors on reticuloendothelial cells. Platelet transfusion is reserved for life-threatening bleeding. TPO receptor agonists for refractory cases."),
  rn("NCLEX-RN","Immunological",3,"A client with Guillain-Barre syndrome should be monitored primarily for:",["Skin breakdown","Rapidly ascending paralysis affecting respiratory function","Seizures","Cognitive decline"],1,"GBS causes ascending demyelinating polyneuropathy. Respiratory failure (30% need ventilation) is the major risk as paralysis ascends. Serial FVC measurements (intubate if FVC < 20 mL/kg or declining rapidly). Treatment: IVIG or plasmapheresis. No role for steroids in GBS."),
  rn("RN-CAT","Cardiovascular",4,"A client with pulmonary hypertension is prescribed prostacyclin analogue therapy. The nurse should teach that:",["The medication is taken orally once daily","Continuous IV infusion through a central line requires meticulous line care to prevent infection and sudden interruption","The medication cures pulmonary hypertension","Side effects are minimal"],1,"Epoprostenol (prostacyclin) requires continuous IV infusion through a permanent central line. Sudden interruption can cause fatal rebound PH. Meticulous line care prevents life-threatening infections (tunneled catheter). Side effects include headache, jaw pain, flushing, and diarrhea."),
  rn("NCLEX-RN","Respiratory",3,"A client with a right-sided pleural effusion on chest X-ray shows meniscus sign at the costophrenic angle. This suggests:",["Pneumothorax","Free-flowing pleural fluid","Loculated effusion","Normal finding"],1,"The meniscus sign (concave upper border of fluid against the chest wall) indicates free-flowing pleural effusion. At least 200-300 mL of fluid must be present to be visible on upright PA CXR. Lateral decubitus film detects smaller effusions."),
  rn("NCLEX-RN","Neurological",3,"A client with a brain abscess presents with headache, focal neurological deficits, and fever. The nurse should anticipate:",["Lumbar puncture for diagnosis","CT or MRI with contrast for diagnosis, followed by IV antibiotics and possible surgical drainage","Oral antibiotics only","Observation without imaging"],1,"Brain abscess: CT/MRI with contrast shows ring-enhancing lesion with surrounding edema. LP is CONTRAINDICATED (risk of herniation). Treatment: high-dose IV antibiotics (4-6 weeks), possible stereotactic aspiration or excision for large abscesses (> 2.5 cm) or poor response."),
  rn("NCLEX-RN","Pharmacology",3,"A client on SGLT2 inhibitor therapy should be monitored for:",["Hypoglycemia as primary concern","Genital yeast infections, UTIs, and euglycemic DKA","Hepatotoxicity","Weight gain"],1,"SGLT2 inhibitors (empagliflozin, dapagliflozin) cause glucosuria, increasing genital yeast infection and UTI risk. Euglycemic DKA (normal glucose with acidosis) is rare but serious. Benefits include cardiovascular and renal protection, weight loss, and BP reduction."),
  rn("NCLEX-RN","Mental Health",3,"A nurse caring for a client who is actively hallucinating should:",["Agree with the hallucination to build trust","Acknowledge the experience without validating the hallucination content","Argue that the hallucination is not real","Ignore the client until the episode passes"],1,"Therapeutic response: 'I understand that you are hearing/seeing something, though I do not hear/see it.' Acknowledge the experience (validates the client's distress) without reinforcing the content. Assess for command hallucinations. Ensure safety and reduce stimulation."),
  rn("NCLEX-RN","Pediatrics",3,"A child with type 1 diabetes has a HbA1c goal of:",["Less than 5.0%","Less than 7.0% for most pediatric patients","Less than 10.0%","Greater than 8.0%"],1,"ADA recommends HbA1c < 7% for most children/adolescents with T1DM, balancing glycemic control with hypoglycemia risk. Less stringent goals may be appropriate for young children at higher hypoglycemia risk. Continuous glucose monitoring helps achieve targets."),
  rn("NCLEX-RN","Maternal/Newborn",3,"Rh-negative mother with an Rh-positive baby should receive RhoGAM:",["Only after delivery","At 28 weeks gestation AND within 72 hours after delivery of an Rh-positive infant","Only during the first pregnancy","Only if she has already formed antibodies"],1,"RhoGAM (anti-D immunoglobulin) prevents Rh sensitization. Given at 28 weeks (antepartum prophylaxis) AND within 72 hours postpartum if the infant is Rh-positive. Also given after any bleeding event, amniocentesis, miscarriage, or ectopic pregnancy."),
  rn("NCLEX-RN","Renal",3,"A client with stage 3b CKD has a GFR of 35 mL/min. The nurse should anticipate management including:",["No dietary modifications needed","Dietary phosphorus and potassium restriction, ACEi/ARB therapy, and anemia management with ESA","High-protein diet to prevent muscle wasting","Dialysis initiation"],1,"Stage 3b CKD (GFR 30-44): phosphorus and potassium restriction, ACEi/ARB for proteinuria and BP control, ESA for renal anemia (Hgb < 10), vitamin D supplementation, cardiovascular risk management, and dialysis access planning. Dialysis typically starts at GFR < 10-15."),
  rn("NCLEX-RN","Infection Control",3,"A client with suspected Ebola virus disease requires:",["Standard precautions only","Maximum isolation with full-body PPE including double gloves, fluid-resistant coveralls, and PAPR","Droplet precautions only","Contact precautions with standard gown"],1,"Ebola requires maximum barrier precautions: fluid-resistant coveralls, double gloves, shoe covers, PAPR or N95 with full face shield, supervised donning/doffing with trained observer. The virus is transmitted through direct contact with infected body fluids. Dedicated equipment and strict protocols are essential."),
  rn("RN-CAT","Critical Care",4,"Ventilator-associated event (VAE) prevention strategies include:",["Keeping the client sedated at all times","Daily sedation interruption and spontaneous breathing trials (SAT/SBT bundled approach)","Prophylactic antibiotics for all ventilated patients","Frequent ventilator circuit changes"],1,"VAE prevention bundle: daily sedation vacation (SAT), daily spontaneous breathing trial (SBT), HOB elevation 30-45 degrees, DVT prophylaxis, stress ulcer prophylaxis, oral care with chlorhexidine, early mobilization, and subglottic secretion drainage."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with aortic regurgitation has a widened pulse pressure. This occurs because:",["Both systolic and diastolic pressures are elevated","Systolic pressure is elevated from increased stroke volume while diastolic pressure drops from regurgitant flow","Both pressures are decreased","The pulse is irregular"],1,"Aortic regurgitation causes blood to leak back into the LV during diastole, reducing diastolic pressure. Compensatory increased stroke volume raises systolic pressure. The result is widened pulse pressure (bounding/water-hammer pulse). De Musset sign (head bobbing) may be present."),
  rn("NCLEX-RN","Respiratory",3,"A client with obesity hypoventilation syndrome should be evaluated for:",["Asthma only","Obstructive sleep apnea, as the two conditions frequently coexist","Pulmonary embolism","Cardiac tamponade"],1,"OHS (BMI >= 30 with chronic hypercapnia without other cause) coexists with OSA in 90% of cases. CPAP/BiPAP with weight loss are mainstays of treatment. Untreated OHS has high mortality. Bariatric surgery may be considered. Phlebotomy for polycythemia."),
  rn("NCLEX-RN","Neurological",3,"A client with normal pressure hydrocephalus classically presents with the triad of:",["Headache, nausea, and papilledema","Gait disturbance, urinary incontinence, and dementia (wet, wobbly, and wacky)","Seizures, visual changes, and tremor","Fever, neck stiffness, and photophobia"],1,"NPH triad: gait disturbance (magnetic gait - wide-based, shuffling), urinary incontinence, and cognitive decline/dementia. CSF drainage trial predicts shunt response. VP shunt placement is definitive treatment with gait improvement often seen first."),
  rn("NCLEX-RN","Endocrine",3,"A client with thyroid cancer undergoes total thyroidectomy. The nurse monitors for hypocalcemia because:",["Dietary calcium was restricted preoperatively","Parathyroid glands may be inadvertently damaged or removed during surgery","Calcium levels always drop after any surgery","Thyroid hormones regulate calcium"],1,"The four parathyroid glands sit behind the thyroid and may be damaged or removed during thyroidectomy. Loss of PTH causes hypocalcemia (Chvostek sign, Trousseau sign, tetany, seizures). Monitor calcium every 6-12 hours postoperatively. Treat with IV and oral calcium plus calcitriol."),
];

async function main() {
  let inserted = 0;
  const batchSize = 50;
  for (let i = 0; i < QS.length; i += batchSize) {
    const batch = QS.slice(i, i + batchSize);
    const values: string[] = [];
    const params: any[] = [];
    let idx = 1;
    for (const q of batch) {
      values.push(`($${idx},$${idx+1},$${idx+2},$${idx+3},$${idx+4},$${idx+5}::jsonb,$${idx+6}::jsonb,$${idx+7},$${idx+8}::integer,$${idx+9},$${idx+10},$${idx+11})`);
      params.push(q.tier,q.exam,"multiple_choice","published",q.stem,JSON.stringify(q.options),JSON.stringify([q.correct]),q.rationale,q.diff,q.bs,"BOTH",hash(q.stem));
      idx += 12;
    }
    const sql = `INSERT INTO exam_questions (tier, exam, question_type, status, stem, options, correct_answer, rationale, difficulty, body_system, region_scope, stem_hash)
                 SELECT v.* FROM (VALUES ${values.join(",")}) AS v(tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,body_system,region_scope,stem_hash)
                 WHERE NOT EXISTS (SELECT 1 FROM exam_questions e WHERE e.stem_hash = v.stem_hash)`;
    const result = await pool.query(sql, params);
    inserted += result.rowCount || 0;
  }
  console.log(`[RN-B3] Inserted ${inserted}/${QS.length}`);
  const counts = await pool.query(`SELECT tier, count(*) as cnt FROM exam_questions WHERE status='published' GROUP BY tier ORDER BY tier`);
  counts.rows.forEach((r: any) => console.log(`  ${r.tier}: ${r.cnt}`));
  await pool.end();
}
main().catch(e => { console.error(e); process.exit(1); });
