import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

interface Q {
  question: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctAnswer: string; rationale: string; category: string; topic: string;
  difficulty: number; country: string; bodyPart?: string; modality?: string; exam: string;
}

const QUESTIONS: Q[] = [
  { question: "The purpose of the rotating anode in an X-ray tube is to:", optionA: "Increase X-ray output", optionB: "Distribute heat over a larger area (focal track)", optionC: "Improve spatial resolution", optionD: "Reduce exposure time", correctAnswer: "B", rationale: "The rotating anode distributes heat over a large circular focal track, allowing higher tube loading without target damage.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The cathode of the X-ray tube consists of:", optionA: "Tungsten target and copper anode", optionB: "Filament and focusing cup", optionC: "Lead housing and glass envelope", optionD: "Collimator and filter", correctAnswer: "B", rationale: "The cathode has a tungsten filament (electron source) housed within a nickel focusing cup that directs the electron stream toward the anode.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The X-ray tube filament is made of:", optionA: "Copper", optionB: "Molybdenum", optionC: "Tungsten", optionD: "Lead", correctAnswer: "C", rationale: "The filament is made of thoriated tungsten because of its high melting point (3370°C) and efficient thermionic emission.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The anode target material in diagnostic X-ray tubes is primarily:", optionA: "Copper", optionB: "Molybdenum", optionC: "Tungsten (with rhenium alloy)", optionD: "Lead", correctAnswer: "C", rationale: "Tungsten (Z=74) is used as the target because of its high atomic number, high melting point, and good thermal conductivity. Rhenium alloy adds thermal resistance.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The purpose of the focusing cup is to:", optionA: "Filter the X-ray beam", optionB: "Focus the electron beam onto the focal spot", optionC: "Rotate the anode", optionD: "Measure exposure", correctAnswer: "B", rationale: "The negatively charged focusing cup electrostatically focuses the electron stream from the filament into a narrow beam directed at the focal spot on the anode.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Most X-ray tubes have dual filaments to provide:", optionA: "Backup in case one fails", optionB: "Two different focal spot sizes (small and large)", optionC: "Twice the electron output", optionD: "More heat dissipation", correctAnswer: "B", rationale: "Dual filaments provide two focal spot sizes: a small filament for high-resolution work and a large filament for high-output procedures.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Thermionic emission refers to:", optionA: "X-ray production at the anode", optionB: "The boiling off of electrons from the heated filament", optionC: "Heat dissipation from the anode", optionD: "Ionization of air", correctAnswer: "B", rationale: "Thermionic emission is the process by which electrons are 'boiled off' from the heated tungsten filament, forming the electron cloud (space charge).", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Space charge effect limits:", optionA: "The kVp", optionB: "The number of electrons emitted from the filament at low kVp", optionC: "The focal spot size", optionD: "The SID", correctAnswer: "B", rationale: "At low kVp, the electron cloud (space charge) around the filament repels additional electrons, limiting tube current below what the filament could provide.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 3, country: "usa", exam: "arrt" },
  { question: "The glass envelope of the X-ray tube:", optionA: "Provides structural support and maintains vacuum", optionB: "Filters the X-ray beam", optionC: "Produces X-rays", optionD: "Shields the operator", correctAnswer: "A", rationale: "The glass (or metal-ceramic) envelope provides structural support and maintains a vacuum (to prevent electron collision with gas molecules).", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The tube housing provides:", optionA: "Additional filtration only", optionB: "Radiation shielding (limits leakage to 100 mR/hr at 1 m), electrical insulation, and mechanical support", optionC: "Focal spot selection", optionD: "kVp regulation", correctAnswer: "B", rationale: "The tube housing provides radiation protection (leakage ≤100 mR/hr at 1 m), electrical insulation, mechanical support, and heat dissipation.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "In a high-frequency generator, the voltage waveform has approximately:", optionA: "100% ripple", optionB: "13-25% ripple", optionC: "Less than 1% ripple (nearly constant potential)", optionD: "50% ripple", correctAnswer: "C", rationale: "High-frequency generators produce nearly constant potential with less than 1% ripple, resulting in higher average beam energy and more consistent output.", category: "Equipment Operation & QC", topic: "Generators", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "A single-phase generator produces a voltage waveform with:", optionA: "No ripple", optionB: "100% ripple (pulsating DC)", optionC: "Less than 5% ripple", optionD: "50% ripple", correctAnswer: "B", rationale: "Single-phase full-wave rectified generators produce 100% voltage ripple, with the voltage dropping to zero between pulses.", category: "Equipment Operation & QC", topic: "Generators", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "A three-phase, 12-pulse generator has approximately:", optionA: "100% ripple", optionB: "25% ripple", optionC: "4% ripple", optionD: "Less than 1% ripple", correctAnswer: "C", rationale: "A three-phase 12-pulse generator has approximately 4% ripple, producing a more nearly constant potential than single-phase or 6-pulse systems.", category: "Equipment Operation & QC", topic: "Generators", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The autotransformer in the X-ray circuit:", optionA: "Produces the filament current", optionB: "Allows selection of kVp by varying the voltage to the step-up transformer", optionC: "Rectifies the current", optionD: "Rotates the anode", correctAnswer: "B", rationale: "The autotransformer operates on the principle of self-induction to select the voltage sent to the step-up (high-voltage) transformer, thereby controlling kVp.", category: "Equipment Operation & QC", topic: "X-ray Circuit", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The step-up (high-voltage) transformer:", optionA: "Decreases voltage for the filament", optionB: "Increases voltage to the kilovoltage range needed to accelerate electrons", optionC: "Controls mA", optionD: "Filters the beam", correctAnswer: "B", rationale: "The step-up transformer increases voltage from the autotransformer output to the kilovoltage range (40-150 kVp) needed to accelerate electrons across the tube.", category: "Equipment Operation & QC", topic: "X-ray Circuit", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The step-down (filament) transformer:", optionA: "Increases voltage to kVp levels", optionB: "Reduces voltage to heat the filament (about 10 volts)", optionC: "Controls kVp selection", optionD: "Rectifies the current", correctAnswer: "B", rationale: "The step-down transformer reduces incoming voltage to approximately 10 volts at high amperage (3-6 amps) to heat the filament.", category: "Equipment Operation & QC", topic: "X-ray Circuit", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Rectifiers in the X-ray circuit:", optionA: "Increase voltage", optionB: "Convert alternating current (AC) to direct current (DC)", optionC: "Control exposure time", optionD: "Measure dose", correctAnswer: "B", rationale: "Rectifiers (solid-state diodes) convert AC to DC, ensuring electrons flow only from cathode to anode in the X-ray tube.", category: "Equipment Operation & QC", topic: "X-ray Circuit", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The timer circuit controls:", optionA: "kVp", optionB: "The duration of the exposure", optionC: "The focal spot size", optionD: "The generator type", correctAnswer: "B", rationale: "The timer circuit controls the duration of the X-ray exposure. Modern electronic timers allow extremely short and precise exposure times.", category: "Equipment Operation & QC", topic: "X-ray Circuit", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Quality control testing of the X-ray generator should verify:", optionA: "Only kVp accuracy", optionB: "kVp accuracy (±5%), mA linearity, reproducibility, and timer accuracy", optionC: "Only mAs accuracy", optionD: "Only timer accuracy", correctAnswer: "B", rationale: "Generator QC includes kVp accuracy (±5%), mA linearity, exposure reproducibility (coefficient of variation <0.05), and timer accuracy (±5%).", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The kVp accuracy test requires that measured kVp be within:", optionA: "±1% of the set value", optionB: "±5% of the set value", optionC: "±10% of the set value", optionD: "±15% of the set value", correctAnswer: "B", rationale: "kVp accuracy must be within ±5% of the set value. kVp reproducibility requires a coefficient of variation of 0.02 or less.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Exposure reproducibility requires the coefficient of variation to be:", optionA: "Less than 0.10", optionB: "Less than 0.05", optionC: "Less than 0.02", optionD: "Less than 0.01", correctAnswer: "B", rationale: "Exposure reproducibility requires a coefficient of variation of 0.05 or less, meaning repeated exposures at the same settings produce consistent output.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "mA linearity testing verifies that:", optionA: "kVp is accurate", optionB: "Output is proportional to mA setting (mR/mAs is constant within ±10%)", optionC: "The timer is accurate", optionD: "The focal spot is correct size", correctAnswer: "B", rationale: "mA linearity ensures that radiation output per mAs (mR/mAs) remains constant (within ±10%) across different mA stations.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The focal spot size can be measured using:", optionA: "An ionization chamber", optionB: "A star test pattern or slit camera", optionC: "A densitometer", optionD: "A TLD", correctAnswer: "B", rationale: "Focal spot size is measured using a star (resolution) test pattern or slit camera. Pinhole camera can also be used for actual focal spot imaging.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The collimator light field alignment test requires agreement within:", optionA: "±1% of SID", optionB: "±2% of SID", optionC: "±5% of SID", optionD: "±10% of SID", correctAnswer: "B", rationale: "The light field must agree with the X-ray field within ±2% of SID. At 40 inches SID, this is ±0.8 inches.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The CR perpendicularity test verifies that the central ray is perpendicular to:", optionA: "The patient", optionB: "The image receptor within ±1 degree", optionC: "The collimator only", optionD: "The tube housing", correctAnswer: "B", rationale: "CR perpendicularity must be within ±1 degree. Misalignment can cause grid cutoff and image distortion.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "HVL testing verifies:", optionA: "Image quality", optionB: "Adequate beam filtration (beam quality)", optionC: "mA accuracy", optionD: "kVp accuracy", correctAnswer: "B", rationale: "HVL testing verifies that the beam has adequate filtration. At 80 kVp, the minimum HVL should be approximately 2.3 mm Al.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The fluoroscopy maximum tabletop exposure rate test is performed:", optionA: "Monthly", optionB: "Annually or after tube/generator replacement", optionC: "Only during installation", optionD: "Never", correctAnswer: "B", rationale: "Fluoroscopy maximum exposure rate testing is performed annually, after tube/generator changes, and as required by state regulations.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Lead apron QC testing should include:", optionA: "Only visual inspection", optionB: "Fluoroscopic or radiographic inspection for cracks, tears, and thinning annually", optionC: "Weight testing", optionD: "Color inspection", correctAnswer: "B", rationale: "Lead aprons must be fluoroscopically or radiographically inspected at least annually for cracks, tears, or thinning that reduce protective effectiveness.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The wire mesh test for cassettes evaluates:", optionA: "Radiation output", optionB: "Film-screen or phosphor plate contact", optionC: "kVp accuracy", optionD: "Grid alignment", correctAnswer: "B", rationale: "The wire mesh test identifies areas of poor contact between the screen/phosphor and the cassette, which appear as dark (blurred) areas.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The AEC (phototimer) consistency test verifies:", optionA: "Only kVp accuracy", optionB: "That optical density/exposure indicator remains consistent across different kVp settings and patient thicknesses", optionC: "Only timer accuracy", optionD: "Only mA accuracy", correctAnswer: "B", rationale: "AEC testing ensures consistent exposure (density/EI) across varying kVp settings and phantom thicknesses, with reproducibility within ±0.30 OD.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Monitor quality control for PACS viewing stations should test:", optionA: "Only brightness", optionB: "Luminance levels, uniformity, contrast, and resolution using SMPTE or TG18 patterns", optionC: "Only screen size", optionD: "Only color accuracy", correctAnswer: "B", rationale: "PACS monitor QC uses SMPTE or AAPM TG18 test patterns to evaluate luminance, contrast, uniformity, and resolution to ensure diagnostic quality display.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The SMPTE test pattern is used to evaluate:", optionA: "Generator output", optionB: "Display monitor quality (contrast, brightness, resolution)", optionC: "Tube heat capacity", optionD: "Grid alignment", correctAnswer: "B", rationale: "The SMPTE (Society of Motion Picture and Television Engineers) test pattern evaluates monitor performance including contrast, brightness, spatial resolution, and grayscale.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The relationship between kVp and mA in the X-ray tube is:", optionA: "kVp controls electron speed; mA controls the number of electrons", optionB: "kVp controls the number of electrons; mA controls their speed", optionC: "Both control the same thing", optionD: "Neither affects image quality", correctAnswer: "A", rationale: "kVp controls the potential difference (electron speed/energy), while mA controls the filament temperature and thus the number of electrons flowing to the anode.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Preventive maintenance for X-ray equipment typically includes:", optionA: "Only cleaning", optionB: "Checking electrical connections, lubrication, calibration verification, and tube warm-up protocols", optionC: "Only tube replacement", optionD: "Only visual inspection", correctAnswer: "B", rationale: "Preventive maintenance includes electrical safety checks, mechanical inspection, lubrication of moving parts, calibration verification, and tube warm-up procedures.", category: "Equipment Operation & QC", topic: "Equipment Maintenance", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Tube warm-up procedures before the first use of the day:", optionA: "Are unnecessary", optionB: "Gradually increase technique to prevent thermal shock to a cold anode", optionC: "Only apply to mobile units", optionD: "Require maximum technique immediately", correctAnswer: "B", rationale: "Tube warm-up gradually increases technique (low kVp/mAs first, progressing to higher) to prevent thermal shock to the cold anode, which could cause disc cracking.", category: "Equipment Operation & QC", topic: "Equipment Maintenance", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "An X-ray tube failure caused by a 'cracked anode' is typically due to:", optionA: "Excessive kVp", optionB: "Thermal stress from repeated high exposures or failure to warm up the tube", optionC: "Low mAs", optionD: "Excessive filtration", correctAnswer: "B", rationale: "Cracked anodes result from thermal stress — repeated high-heat-load exposures or exposing a cold anode to high technique without warm-up.", category: "Equipment Operation & QC", topic: "Equipment Maintenance", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "A bearing failure in the X-ray tube would present as:", optionA: "No output", optionB: "Grinding or whining noise during anode rotation", optionC: "Low kVp output", optionD: "Excessive density", correctAnswer: "B", rationale: "Bearing failure causes audible grinding, squealing, or rattling during anode rotation. The tube should be taken out of service and replaced.", category: "Equipment Operation & QC", topic: "Equipment Maintenance", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The stator in the X-ray tube:", optionA: "Produces X-rays", optionB: "Creates a rotating magnetic field to spin the anode through electromagnetic induction", optionC: "Heats the filament", optionD: "Controls kVp", correctAnswer: "B", rationale: "The stator is a series of electromagnets outside the glass envelope that creates a rotating magnetic field, causing the rotor (and attached anode disc) to spin.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The rotor in the X-ray tube:", optionA: "Heats the filament", optionB: "Is connected to the anode disc and spins within the stator's magnetic field", optionC: "Controls mA", optionD: "Filters the beam", correctAnswer: "B", rationale: "The copper rotor is connected to the anode target disc and spins within the stator's rotating magnetic field by electromagnetic induction, typically at 3,300-10,000 RPM.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Typical anode rotation speeds are:", optionA: "100-500 RPM", optionB: "3,300-3,600 RPM (standard) or 9,000-10,000 RPM (high-speed)", optionC: "50,000 RPM", optionD: "500-1,000 RPM", correctAnswer: "B", rationale: "Standard anode speed is 3,300-3,600 RPM. High-speed anodes rotate at 9,000-10,000 RPM for higher heat loading capacity.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Copper is used in the anode assembly to:", optionA: "Produce X-rays", optionB: "Conduct heat away from the tungsten target efficiently", optionC: "Increase X-ray output", optionD: "Reduce electrical resistance", correctAnswer: "B", rationale: "Copper is an excellent thermal conductor, efficiently conducting heat away from the tungsten target into the anode assembly for radiation/convection cooling.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The X-ray tube window is made of:", optionA: "Lead glass", optionB: "Beryllium or thin glass (lower atomic number for less absorption)", optionC: "Tungsten", optionD: "Aluminum", correctAnswer: "B", rationale: "The tube window (port) is made of thin glass or beryllium (Z=4) to allow maximum X-ray transmission with minimum inherent filtration.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Inherent filtration from the X-ray tube is typically:", optionA: "0 mm Al", optionB: "0.5-1.0 mm Al equivalent", optionC: "2.5 mm Al", optionD: "5 mm Al", correctAnswer: "B", rationale: "Inherent filtration (from the tube window, glass envelope, and cooling oil) is typically 0.5-1.0 mm Al equivalent.", category: "Equipment Operation & QC", topic: "X-ray Tube", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The purpose of the collimator light is to:", optionA: "Sterilize the field", optionB: "Indicate the size and position of the X-ray field before exposure", optionC: "Provide room lighting", optionD: "Heat the tube", correctAnswer: "B", rationale: "The collimator light simulates the X-ray field, showing its size and position to allow accurate centering and field limitation before exposure.", category: "Equipment Operation & QC", topic: "Collimator", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The mirror in the collimator is positioned at a 45-degree angle to:", optionA: "Filter the beam", optionB: "Redirect the light beam to simulate the X-ray field path", optionC: "Measure beam quality", optionD: "Control mA", correctAnswer: "B", rationale: "The 45-degree mirror reflects the light from the bulb to simulate the divergent path of the X-ray beam from the focal spot.", category: "Equipment Operation & QC", topic: "Collimator", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The fluoroscopy image intensifier converts X-rays to:", optionA: "Heat", optionB: "A brightened visible light image through input phosphor → photocathode → electron acceleration → output phosphor", optionC: "Sound", optionD: "Electrical current only", correctAnswer: "B", rationale: "The image intensifier chain: input phosphor (CsI) converts X-rays to light → photocathode converts light to electrons → electrons are accelerated and focused → output phosphor converts electrons to visible light.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The input phosphor of an image intensifier is typically made of:", optionA: "Zinc cadmium sulfide", optionB: "Cesium iodide (CsI)", optionC: "Calcium tungstate", optionD: "Gadolinium oxysulfide", correctAnswer: "B", rationale: "CsI is used for the input phosphor because of its high X-ray absorption efficiency and needle-like crystal structure that minimizes light spread.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Brightness gain in an image intensifier is the product of:", optionA: "kVp × mA", optionB: "Minification gain × flux gain", optionC: "SID × OID", optionD: "Grid ratio × Bucky factor", correctAnswer: "B", rationale: "Brightness gain = minification gain (ratio of input to output phosphor areas) × flux gain (electron acceleration), typically 5,000-20,000.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Flat panel fluoroscopy detectors have replaced image intensifiers in many systems because:", optionA: "They are cheaper", optionB: "They offer larger field of view, no distortion, higher DQE, and compact design", optionC: "They use more radiation", optionD: "They are easier to manufacture", correctAnswer: "B", rationale: "Flat panel detectors eliminate vignetting, pincushion distortion, and S-distortion of image intensifiers while providing superior image quality and compact design.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Vignetting in an image intensifier refers to:", optionA: "Improved center brightness", optionB: "Decreased brightness at the periphery compared to the center", optionC: "Pincushion distortion", optionD: "Increased noise", correctAnswer: "B", rationale: "Vignetting causes the periphery of the II image to appear darker than the center due to electron divergence and uneven photocathode sensitivity.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 3, country: "usa", exam: "arrt" },
  { question: "Pincushion distortion in an image intensifier causes:", optionA: "The image to appear barrel-shaped", optionB: "Straight lines near the periphery to appear curved outward", optionC: "The center to be distorted", optionD: "The image to be inverted", correctAnswer: "B", rationale: "Pincushion distortion causes straight lines near the periphery of the II image to appear bowed outward (convex) due to the curved input phosphor.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 3, country: "usa", exam: "arrt" },
  { question: "Automatic brightness control (ABC) in fluoroscopy:", optionA: "Controls room lighting", optionB: "Automatically adjusts kVp and/or mA to maintain consistent image brightness", optionC: "Controls collimation", optionD: "Is not used in modern systems", correctAnswer: "B", rationale: "ABC (automatic brightness/dose rate control) adjusts kVp and/or mA to maintain consistent image brightness regardless of patient thickness variations.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Magnification mode in fluoroscopy:", optionA: "Decreases patient dose", optionB: "Increases patient dose because the ABC increases technique to maintain brightness", optionC: "Has no effect on dose", optionD: "Improves contrast only", correctAnswer: "B", rationale: "Magnification mode uses a smaller portion of the input phosphor, reducing brightness. ABC compensates by increasing technique (kVp/mA), increasing patient dose.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Last-image hold in fluoroscopy:", optionA: "Stores the final image permanently", optionB: "Displays the last fluoroscopic image without additional radiation for review", optionC: "Increases image quality", optionD: "Replaces spot images", correctAnswer: "B", rationale: "Last-image hold retains the last fluoroscopic frame on the monitor for review without additional radiation exposure, reducing total fluoroscopy time.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Cine fluoroscopy is used primarily in:", optionA: "Chest radiography", optionB: "Cardiac catheterization to record rapid heart motion", optionC: "Extremity imaging", optionD: "Mammography", correctAnswer: "B", rationale: "Cine (cinematography) fluoroscopy records rapid sequential images (15-60 fps) during cardiac catheterization to evaluate heart motion and blood flow.", category: "Equipment Operation & QC", topic: "Fluoroscopy", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Digital subtraction angiography (DSA) uses:", optionA: "Film-screen imaging", optionB: "Pre-contrast mask subtraction from post-contrast images to isolate vessels", optionC: "MRI technology", optionD: "Ultrasound", correctAnswer: "B", rationale: "DSA subtracts a pre-contrast mask image from post-contrast images, removing bone and soft tissue to visualize contrast-filled vessels.", category: "Equipment Operation & QC", topic: "Special Equipment", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "An image artifact caused by a dead pixel on a flat panel detector appears as:", optionA: "A white line across the image", optionB: "A consistently black or white spot in the same location on every image", optionC: "Motion blur", optionD: "Grid lines", correctAnswer: "B", rationale: "Dead (non-functional) pixels appear as consistently black or white spots at the same location. Detector calibration maps correct for known dead pixels.", category: "Equipment Operation & QC", topic: "Digital Detector Artifacts", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The exposure switch for portable radiographic units must be:", optionA: "On the control panel", optionB: "On a cord at least 6 feet long, allowing the operator to maintain safe distance", optionC: "Wireless only", optionD: "Foot-operated only", correctAnswer: "B", rationale: "The exposure cord must be at least 6 feet (1.8 m) long to allow the operator to maintain adequate distance from the radiation source.", category: "Equipment Operation & QC", topic: "Mobile Equipment", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "The daily QC check for a CR reader should include:", optionA: "Full generator calibration", optionB: "Erasure cycle verification, system artifact check, and phantom image review", optionC: "Only cleaning the plates", optionD: "Only checking the laser", correctAnswer: "B", rationale: "Daily CR QC includes verifying proper erasure, checking for system artifacts, reviewing phantom images for consistency, and cleaning plates as needed.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Grid uniformity testing verifies:", optionA: "kVp accuracy", optionB: "Even grid strip spacing and alignment for uniform density", optionC: "Timer accuracy", optionD: "Focal spot size", correctAnswer: "B", rationale: "Grid uniformity testing ensures even spacing and alignment of grid strips, producing uniform image density without grid-related artifacts.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The recommended viewing conditions for diagnostic image interpretation include:", optionA: "Any lighting conditions", optionB: "Low ambient lighting with calibrated high-luminance monitors", optionC: "Bright room lighting", optionD: "No specific requirements", correctAnswer: "B", rationale: "Diagnostic workstations require low ambient lighting (<25 lux), calibrated monitors with appropriate luminance (250-400 cd/m² minimum), and daily QC.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "If the X-ray tube makes a clicking sound during the prep (rotor) phase, this may indicate:", optionA: "Normal operation", optionB: "Bearing wear or damage", optionC: "kVp overload", optionD: "Timer malfunction", correctAnswer: "B", rationale: "Clicking, grinding, or unusual sounds during rotor preparation may indicate bearing wear, requiring tube inspection and possible replacement.", category: "Equipment Operation & QC", topic: "Equipment Maintenance", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Repeat analysis as a QC tool serves to:", optionA: "Count total examinations", optionB: "Identify the causes and rates of repeated exposures to reduce waste and patient dose", optionC: "Measure generator output", optionD: "Calibrate detectors", correctAnswer: "B", rationale: "Repeat analysis identifies patterns (positioning errors, technique errors, equipment problems) causing repeat exposures, enabling corrective action to reduce patient dose.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "A falling load generator:", optionA: "Uses a constant mA throughout the exposure", optionB: "Starts at maximum mA and progressively reduces mA as the anode heats, providing shortest possible exposure time", optionC: "Increases mA during exposure", optionD: "Uses only low mA settings", correctAnswer: "B", rationale: "Falling load generators begin at the highest safe mA and progressively decrease as the anode heats, delivering the required mAs in the shortest possible time.", category: "Equipment Operation & QC", topic: "Generators", difficulty: 3, country: "usa", exam: "arrt" },
  { question: "The detent positions on a Bucky tray correspond to:", optionA: "Different kVp settings", optionB: "Standard IR sizes and centering positions", optionC: "Grid ratios", optionD: "Exposure times", correctAnswer: "B", rationale: "Detent positions are preset stops on the Bucky tray that correspond to standard IR sizes and centering points for different examinations.", category: "Equipment Operation & QC", topic: "Equipment Features", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "An AEC density selector adjustment of +1 increases or decreases the exposure by approximately:", optionA: "10%", optionB: "25-30%", optionC: "50%", optionD: "100%", correctAnswer: "B", rationale: "Each density step on an AEC typically changes exposure by approximately 25-30%. +1 increases density; -1 decreases density.", category: "Equipment Operation & QC", topic: "Automatic Exposure Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The backup time on an AEC should be set to:", optionA: "Twice the expected exposure", optionB: "150-200% of the expected exposure to prevent excessive dose from AEC malfunction", optionC: "The minimum possible", optionD: "Always at maximum", correctAnswer: "B", rationale: "Backup time should be set at 150-200% of the expected mAs (or time) to allow normal AEC operation while preventing excessive exposure from malfunction.", category: "Equipment Operation & QC", topic: "Automatic Exposure Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The CR plate reader laser scan pattern is:", optionA: "Random", optionB: "A raster pattern (line by line) across the PSP plate", optionC: "Circular", optionD: "Diagonal", correctAnswer: "B", rationale: "The CR reader scans the PSP plate in a raster pattern (line by line) using a focused laser beam, stimulating photostimulated luminescence for image capture.", category: "Equipment Operation & QC", topic: "CR System", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The light detected during CR plate readout is called:", optionA: "Fluorescence", optionB: "Photostimulated luminescence (PSL)", optionC: "Phosphorescence", optionD: "Thermoluminescence", correctAnswer: "B", rationale: "PSL (photostimulated luminescence) is the light emitted when the laser stimulates trapped electrons to return to their ground state in the PSP plate.", category: "Equipment Operation & QC", topic: "CR System", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "After readout, the CR plate is erased by:", optionA: "Chemical processing", optionB: "Exposure to bright white light", optionC: "Heating", optionD: "Magnetic degaussing", correctAnswer: "B", rationale: "The CR plate is erased by flooding it with high-intensity white light, which releases any remaining trapped electrons to prepare for reuse.", category: "Equipment Operation & QC", topic: "CR System", difficulty: 1, country: "usa", exam: "arrt" },
  { question: "Annual physicist QC testing of radiographic equipment should include:", optionA: "Only visual inspection", optionB: "Comprehensive generator testing, focal spot evaluation, HVL measurement, AEC testing, and collimator alignment", optionC: "Only kVp testing", optionD: "Only repeat analysis", correctAnswer: "B", rationale: "Annual physicist testing is comprehensive: kVp accuracy, timer accuracy, mA linearity, reproducibility, HVL, focal spot size, AEC performance, collimator alignment, and more.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "Spatial resolution in digital flat panel detectors is primarily determined by:", optionA: "kVp setting", optionB: "Pixel pitch (detector element size)", optionC: "mAs setting", optionD: "Grid ratio", correctAnswer: "B", rationale: "Spatial resolution is determined by pixel pitch — the distance between the centers of adjacent detector elements. Smaller pitch = higher resolution.", category: "Equipment Operation & QC", topic: "Digital Detectors", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The minimum HVL at 80 kVp for a diagnostic X-ray unit is approximately:", optionA: "1.0 mm Al", optionB: "2.3 mm Al", optionC: "3.5 mm Al", optionD: "5.0 mm Al", correctAnswer: "B", rationale: "At 80 kVp, the minimum HVL should be approximately 2.3 mm Al, ensuring adequate beam filtration for patient dose reduction.", category: "Equipment Operation & QC", topic: "Quality Control", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The digital DICOM modality worklist provides:", optionA: "Generator calibration data", optionB: "Patient scheduling information to the imaging equipment for automatic data entry", optionC: "Dose tracking only", optionD: "Equipment maintenance schedules", correctAnswer: "B", rationale: "DICOM Modality Worklist sends patient demographics and order information from the RIS/HIS to the imaging equipment, reducing manual data entry errors.", category: "Equipment Operation & QC", topic: "Digital Systems", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "The purpose of detector calibration (flat-field correction) is to:", optionA: "Improve spatial resolution", optionB: "Correct for individual pixel sensitivity variations and produce uniform image response", optionC: "Increase patient dose", optionD: "Adjust kVp", correctAnswer: "B", rationale: "Flat-field calibration compensates for inherent differences in sensitivity among detector elements, ensuring uniform image quality.", category: "Equipment Operation & QC", topic: "Digital Detectors", difficulty: 2, country: "usa", exam: "arrt" },
  { question: "If the AEC produces consistently overexposed images, the possible causes include:", optionA: "kVp too low", optionB: "Wrong chamber selected, density control set too high, or patient not covering the chamber", optionC: "SID too long", optionD: "Grid removed", correctAnswer: "B", rationale: "AEC overexposure can result from incorrect chamber selection, density control set too high (+), or anatomy not fully covering the selected chamber.", category: "Equipment Operation & QC", topic: "Automatic Exposure Control", difficulty: 2, country: "usa", exam: "arrt" },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2`, [q.question, q.country]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, body_part, modality, exam, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,'published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty, q.country, q.bodyPart||null, q.modality||null, q.exam]
      );
      inserted++;
    }
  }
  console.log(`[Equipment Operation & QC] Inserted ${inserted}/${QUESTIONS.length} USA ARRT questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
