import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

interface Q {
  question: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctAnswer: string; rationale: string; category: string; topic: string;
  difficulty: number; country: string; bodyPart?: string; modality?: string; exam: string;
  examDomain: string; masteryCategory?: string;
}

const QUESTIONS: Q[] = [
  { question: "For a PA oblique (RAO) projection of the sternum, the patient is rotated:", optionA: "45 degrees", optionB: "15-20 degrees from prone position", optionC: "30 degrees", optionD: "90 degrees (lateral)", correctAnswer: "B", rationale: "A 15-20 degree RAO oblique rotates the sternum just enough to clear the thoracic spine while keeping it superimposed over the cardiac shadow for uniform density.", category: "Procedures", topic: "Bony Thorax", difficulty: 2, country: "usa", bodyPart: "Sternum", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a lateral projection of the sternum, the patient's arms are positioned:", optionA: "At the sides", optionB: "Behind the back, with shoulders rolled posteriorly", optionC: "Above the head", optionD: "Crossed over the chest", correctAnswer: "B", rationale: "Arms behind the back with shoulders rolled posteriorly clears the humeral heads from superimposition on the sternum for a true lateral projection.", category: "Procedures", topic: "Bony Thorax", difficulty: 2, country: "usa", bodyPart: "Sternum", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For rib radiography above the diaphragm (upper ribs), which projection and breathing instruction are used?", optionA: "AP, expiration", optionB: "AP or PA, suspended deep inspiration", optionC: "PA, expiration", optionD: "Lateral, quiet breathing", correctAnswer: "B", rationale: "Upper ribs (above the diaphragm) are best demonstrated on AP or PA with deep inspiration to elevate the ribs and separate them from the diaphragm. Use lung technique (higher kVp).", category: "Procedures", topic: "Bony Thorax", difficulty: 2, country: "usa", bodyPart: "Ribs", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For rib radiography below the diaphragm (lower ribs), the breathing instruction is:", optionA: "Deep inspiration", optionB: "Suspended expiration", optionC: "Quiet breathing", optionD: "Valsalva maneuver", correctAnswer: "B", rationale: "Lower ribs (below the diaphragm) are best demonstrated on expiration, which pushes the diaphragm superiorly and the ribs inferiorly into the abdominal area. Use abdominal technique (lower kVp).", category: "Procedures", topic: "Bony Thorax", difficulty: 2, country: "usa", bodyPart: "Ribs", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The Towne projection demonstrates the dorsum sellae and posterior clinoid processes projected through which structure?", optionA: "The orbit", optionB: "The foramen magnum", optionC: "The frontal sinus", optionD: "The maxillary sinus", correctAnswer: "B", rationale: "With proper 30-degree caudal angulation to IOML, the Towne projection demonstrates the dorsum sellae and posterior clinoid processes projected within the foramen magnum.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 3, country: "usa", bodyPart: "Skull", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a modified Law projection of the mastoid, the head is rotated:", optionA: "45 degrees toward the side being examined", optionB: "15 degrees away from the side being examined", optionC: "True lateral", optionD: "30 degrees toward the side being examined", correctAnswer: "B", rationale: "The modified Law projection uses a 15-degree head rotation away from the side of interest with a 15-degree caudal CR angle to demonstrate the mastoid air cells and external auditory canal.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 3, country: "usa", bodyPart: "Temporal Bone", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a PA mandible projection, the CR is angled:", optionA: "Perpendicular", optionB: "20-25 degrees cephalad", optionC: "15 degrees caudad", optionD: "0 degrees (perpendicular) with OML perpendicular to IR", correctAnswer: "D", rationale: "For a PA mandible, the OML is perpendicular to the IR and the CR is directed perpendicular (0 degrees). This demonstrates the mandibular body and rami.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 2, country: "usa", bodyPart: "Mandible", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The panoramic radiograph (Panorex/OPG) demonstrates:", optionA: "Only the maxilla", optionB: "The entire mandible, maxilla, teeth, and temporomandibular joints in one image", optionC: "Only the TMJ", optionD: "Only individual teeth", correctAnswer: "B", rationale: "Panoramic radiography uses a rotating X-ray source and detector to produce a single image of the entire mandible, maxilla, all teeth, TMJs, and surrounding structures.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 1, country: "usa", bodyPart: "Mandible", exam: "arrt", examDomain: "Procedures", masteryCategory: "knowledge" },
  { question: "For the swimmer's lateral projection of the cervicothoracic region (C7-T1), which arm is elevated?", optionA: "The arm closest to the IR", optionB: "The arm farthest from the IR", optionC: "Both arms", optionD: "Neither arm", correctAnswer: "B", rationale: "The arm farthest from the IR is elevated overhead while the arm closest to the IR is depressed. This separates the shoulders to demonstrate the C7-T1 region.", category: "Procedures", topic: "Spine", difficulty: 2, country: "usa", bodyPart: "Cervical Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For AP axial sacrum, the CR is angled:", optionA: "10 degrees caudad", optionB: "15 degrees cephalad", optionC: "Perpendicular", optionD: "25 degrees caudad", correctAnswer: "B", rationale: "The CR for AP sacrum is angled 15 degrees cephalad, entering at the level of the pubic symphysis. This angle projects the sacrum without foreshortening above the pubic bones.", category: "Procedures", topic: "Spine", difficulty: 2, country: "usa", bodyPart: "Sacrum", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For AP axial coccyx, the CR is angled:", optionA: "15 degrees cephalad", optionB: "10 degrees caudad", optionC: "Perpendicular", optionD: "25 degrees cephalad", correctAnswer: "B", rationale: "The CR for AP coccyx is angled 10 degrees caudad to project the coccyx below the pubic symphysis. The centering point is approximately 2 inches above the symphysis.", category: "Procedures", topic: "Spine", difficulty: 2, country: "usa", bodyPart: "Coccyx", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "Flexion and extension lateral cervical spine projections are performed to evaluate:", optionA: "Fractures of C1-C2", optionB: "Ligamentous instability and abnormal vertebral motion", optionC: "Disc herniation", optionD: "Spinal cord compression", correctAnswer: "B", rationale: "Flexion-extension lateral views assess cervical spine stability by evaluating vertebral alignment during motion. Abnormal anterior listhesis or widening of interspinous distances suggests ligamentous injury.", category: "Procedures", topic: "Spine", difficulty: 3, country: "usa", bodyPart: "Cervical Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP oblique projection (RPO/LPO) of the lumbar spine, the patient is rotated:", optionA: "15 degrees", optionB: "45 degrees", optionC: "30 degrees", optionD: "60 degrees", correctAnswer: "B", rationale: "45-degree obliques of the lumbar spine demonstrate the zygapophyseal joints. RPO shows the left side joints; LPO shows the right side joints (joints closest to the IR in posterior obliques).", category: "Procedures", topic: "Spine", difficulty: 2, country: "usa", bodyPart: "Lumbar Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the AP axial (Towne) projection of the TMJ, the CR is angled:", optionA: "15 degrees cephalad", optionB: "35-40 degrees caudad", optionC: "Perpendicular", optionD: "25 degrees cephalad", correctAnswer: "B", rationale: "The AP axial TMJ projection uses a 35-40 degree caudal angle to project the TMJ condyles below the temporal bone, demonstrating the condylar heads.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 3, country: "usa", bodyPart: "TMJ", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a PA projection of the wrist, the hand is positioned:", optionA: "Supinated", optionB: "Pronated with fingers slightly flexed to bring the wrist in contact with the IR", optionC: "In lateral position", optionD: "In extension with fingers straight", correctAnswer: "B", rationale: "PA wrist requires the hand pronated with slight finger flexion to place the wrist flat against the IR. The CR is directed perpendicular to the midcarpal area.", category: "Procedures", topic: "Upper Extremity", difficulty: 1, country: "usa", bodyPart: "Wrist", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The Coyle method for the coronoid process requires the elbow flexed 80 degrees with the CR angled:", optionA: "45 degrees away from the shoulder", optionB: "45 degrees toward the shoulder", optionC: "Perpendicular", optionD: "15 degrees toward the wrist", correctAnswer: "B", rationale: "The Coyle method for coronoid process: elbow flexed 80 degrees, CR angled 45 degrees toward the shoulder (proximally). For radial head, elbow flexed 90 degrees with CR angled 45 degrees toward the wrist.", category: "Procedures", topic: "Upper Extremity", difficulty: 4, country: "usa", bodyPart: "Elbow", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the inferosuperior (axial/Lawrence) projection of the shoulder, the patient's arm is:", optionA: "Abducted 90 degrees overhead", optionB: "Externally rotated with the arm at the side and the CR directed through the axilla", optionC: "Adducted across the chest", optionD: "Internally rotated", correctAnswer: "B", rationale: "The Lawrence axillary view is performed with the arm externally rotated and slightly abducted, with the CR directed through the axilla to the IR placed on top of the shoulder, demonstrating the glenohumeral joint.", category: "Procedures", topic: "Upper Extremity", difficulty: 3, country: "usa", bodyPart: "Shoulder", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP projection of the clavicle, the CR is angled:", optionA: "30 degrees cephalad", optionB: "Perpendicular to the midshaft of the clavicle (0 degrees)", optionC: "15 degrees caudad", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "AP clavicle uses a perpendicular CR directed to the midshaft of the clavicle. This demonstrates the entire clavicle. An axial projection (AP with 15-30 degree cephalad angle) may be used for displaced fractures.", category: "Procedures", topic: "Upper Extremity", difficulty: 1, country: "usa", bodyPart: "Clavicle", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The AP weight-bearing bilateral knee projection is commonly performed to evaluate:", optionA: "ACL tears", optionB: "Joint space narrowing from degenerative arthritis", optionC: "Patellar fracture", optionD: "Meniscal tears", correctAnswer: "B", rationale: "Weight-bearing knee radiographs are the gold standard for evaluating joint space narrowing in osteoarthritis. Narrowing is often not apparent on non-weight-bearing views.", category: "Procedures", topic: "Lower Extremity", difficulty: 2, country: "usa", bodyPart: "Knee", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a stress inversion view of the ankle, the purpose is to evaluate:", optionA: "The tibiotalar joint articular surfaces", optionB: "Ligamentous integrity of the lateral ankle ligaments", optionC: "The calcaneus for fracture", optionD: "The talar dome for OCD lesion", correctAnswer: "B", rationale: "Stress inversion (and eversion) views apply controlled force to evaluate ligamentous integrity. Increased talar tilt angle on inversion stress suggests lateral ligament injury (ATFL, CFL).", category: "Procedures", topic: "Lower Extremity", difficulty: 3, country: "usa", bodyPart: "Ankle", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an axial sesamoid (tangential) projection of the foot, the patient's toes are:", optionA: "Extended flat on the IR", optionB: "Dorsiflexed so the ball of the foot is perpendicular to the IR", optionC: "Plantarflexed", optionD: "In neutral position", correctAnswer: "B", rationale: "The tangential sesamoid projection positions the toes dorsiflexed (MTP joints extended) so the CR passes tangentially through the plantar surface of the first MTP joint to demonstrate the sesamoid bones.", category: "Procedures", topic: "Lower Extremity", difficulty: 3, country: "usa", bodyPart: "Foot", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a lateral projection of the hip using the Danelius-Miller (cross-table) method, the unaffected leg is:", optionA: "Kept straight alongside the injured leg", optionB: "Flexed at the hip and knee and elevated out of the beam path", optionC: "Placed in a frog-leg position", optionD: "Abducted laterally", correctAnswer: "B", rationale: "The unaffected leg is flexed and elevated to clear the path for the horizontal (cross-table) beam, which passes through the affected hip to the IR positioned vertically against the patient's side.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 2, country: "usa", bodyPart: "Hip", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The AP axial inlet (Lilienfeld) projection of the pelvis demonstrates:", optionA: "The pelvic brim (superior aperture) and posterior displacement of fracture fragments", optionB: "The acetabular columns", optionC: "The sacroiliac joints", optionD: "The ischial tuberosities", correctAnswer: "A", rationale: "The inlet projection (40 degree caudal angle) shows the pelvic brim from above, demonstrating the true shape of the pelvic ring and any posterior displacement of fracture fragments.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 4, country: "usa", bodyPart: "Pelvis", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The AP axial outlet (Taylor) projection of the pelvis demonstrates:", optionA: "The pelvic inlet", optionB: "The inferior pubic rami, ischial rami, and anterior/inferior displacement of fracture fragments", optionC: "The femoral necks", optionD: "The sacroiliac joints", correctAnswer: "B", rationale: "The outlet projection (20-35 degree cephalad angle) opens the pubic and ischial rami and demonstrates superior/anterior displacement of pelvic fracture fragments.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 4, country: "usa", bodyPart: "Pelvis", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a lateral projection of the nasal bones, the SID should be reduced to:", optionA: "72 inches", optionB: "36-40 inches with detail (small focal spot) technique for optimal spatial resolution", optionC: "48 inches", optionD: "60 inches", correctAnswer: "B", rationale: "Nasal bone imaging uses a close SID (36-40\") with the small focal spot and fine-detail technique because the nasal bones are thin and require high spatial resolution for fracture detection.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 2, country: "usa", bodyPart: "Nasal Bones", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "An upper GI radiograph shows the 'retrogastric space' on the lateral projection. This space is between the:", optionA: "Stomach and liver", optionB: "Stomach and vertebral column", optionC: "Stomach and spleen", optionD: "Stomach and diaphragm", correctAnswer: "B", rationale: "The retrogastric space is the area between the posterior wall of the barium-filled stomach and the anterior surface of the vertebral bodies. Widening may suggest pancreatic pathology.", category: "Procedures", topic: "GI Studies", difficulty: 3, country: "usa", bodyPart: "Stomach", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a small bowel follow-through (SBFT), barium is given:", optionA: "Rectally", optionB: "Orally, with serial radiographs taken at timed intervals until barium reaches the cecum", optionC: "Intravenously", optionD: "Through a jejunostomy tube", correctAnswer: "B", rationale: "SBFT involves oral ingestion of barium with serial AP abdomen radiographs at intervals (usually every 15-30 minutes) tracking barium progression through the small bowel until it reaches the ileocecal valve/cecum.", category: "Procedures", topic: "GI Studies", difficulty: 2, country: "usa", bodyPart: "Small Bowel", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a T-tube cholangiogram, contrast is injected:", optionA: "Intravenously", optionB: "Through the indwelling T-tube drain in the common bile duct", optionC: "Orally", optionD: "Rectally", correctAnswer: "B", rationale: "A T-tube cholangiogram involves injecting contrast directly through the T-tube (surgically placed drain in the common bile duct) to evaluate for residual biliary stones or ductal obstruction post-cholecystectomy.", category: "Procedures", topic: "Biliary Studies", difficulty: 2, country: "usa", bodyPart: "Biliary System", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP projection of the sacroiliac joints, the CR is angled:", optionA: "Perpendicular", optionB: "30-35 degrees cephalad", optionC: "15 degrees caudad", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "The AP axial SI joints use a 30-35 degree cephalad angle to open the obliquely oriented SI joints. This projects them without superimposition of the sacrum.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 3, country: "usa", bodyPart: "Sacroiliac Joints", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "Oblique projections of the sacroiliac joints require the patient to be rotated:", optionA: "15 degrees", optionB: "25-30 degrees (RPO/LPO)", optionC: "45 degrees", optionD: "60 degrees", correctAnswer: "B", rationale: "SI joint obliques use 25-30 degree rotation. LPO demonstrates the right SI joint (joint closest to the IR); RPO demonstrates the left SI joint.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 3, country: "usa", bodyPart: "Sacroiliac Joints", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a transthoracic lateral (Lawrence) projection of the humerus, the exposure technique should use:", optionA: "Short exposure time to freeze motion", optionB: "Breathing technique (low mA, long exposure time) to blur overlying ribs and lung", optionC: "High kVp only", optionD: "Standard chest technique", correctAnswer: "B", rationale: "The transthoracic lateral uses breathing technique to blur the ribs and lung markings overlying the proximal humerus, improving visualization of the humeral shaft and surgical neck.", category: "Procedures", topic: "Upper Extremity", difficulty: 3, country: "usa", bodyPart: "Humerus", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a lateral projection of the scapula, the patient's arm is positioned:", optionA: "At the side", optionB: "Across the chest, reaching for the opposite shoulder, to move the scapula laterally", optionC: "Above the head", optionD: "Behind the back", correctAnswer: "B", rationale: "Reaching across the chest to the opposite shoulder protracts the scapula laterally away from the rib cage, providing a true lateral view. The humeral shaft should not be superimposed on the scapular body.", category: "Procedures", topic: "Upper Extremity", difficulty: 2, country: "usa", bodyPart: "Scapula", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the Stryker notch view of the shoulder, the arm is positioned:", optionA: "At the side in internal rotation", optionB: "With the hand on top of the head and the elbow pointing upward", optionC: "In external rotation at 90-degree abduction", optionD: "Behind the back", correctAnswer: "B", rationale: "The Stryker notch view positions the arm with the hand on top of the head, elbow pointing anteriorly. A 10-degree cephalad CR angle demonstrates the posterolateral humeral head (Hill-Sachs lesion).", category: "Procedures", topic: "Upper Extremity", difficulty: 4, country: "usa", bodyPart: "Shoulder", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the Robert's projection (AP true view) of the thumb, the hand is positioned:", optionA: "In PA position", optionB: "In extreme internal rotation so the thumb is in a true AP position on the IR", optionC: "In lateral position", optionD: "In oblique position", correctAnswer: "B", rationale: "The Robert's method places the thumb in a true AP position by internally rotating the hand until the posterior surface of the thumb is flat on the IR, providing a non-foreshortened AP view of the first digit.", category: "Procedures", topic: "Upper Extremity", difficulty: 3, country: "usa", bodyPart: "Thumb", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an intercondylar fossa (tunnel) view using the Camp-Coventry method, the patient is:", optionA: "Supine with knee flexed", optionB: "Prone with knee flexed 40-50 degrees and CR angled 40-50 degrees caudad perpendicular to the tibia", optionC: "Lateral with knee flexed 90 degrees", optionD: "Standing with knee extended", correctAnswer: "B", rationale: "Camp-Coventry: prone, knee flexed 40-50 degrees, CR angled caudad (same angle as knee flexion) perpendicular to the tibial plateau. This opens the intercondylar fossa for loose body or OCD evaluation.", category: "Procedures", topic: "Lower Extremity", difficulty: 3, country: "usa", bodyPart: "Knee", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP weight-bearing foot projection, the patient stands on the IR cassette with the CR angled:", optionA: "Perpendicular", optionB: "15 degrees posteriorly (toward the heel)", optionC: "10 degrees anteriorly", optionD: "30 degrees cephalad", correctAnswer: "B", rationale: "Weight-bearing AP foot uses a 15-degree posterior angle to compensate for the angle of the foot relative to the IR when standing. This demonstrates the longitudinal arch and joint spaces under physiologic load.", category: "Procedures", topic: "Lower Extremity", difficulty: 3, country: "usa", bodyPart: "Foot", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "A voiding cystourethrogram (VCUG) evaluates:", optionA: "Renal function", optionB: "Vesicoureteral reflux and urethral anatomy during voiding", optionC: "Gallbladder function", optionD: "Upper urinary tract obstruction", correctAnswer: "B", rationale: "VCUG evaluates vesicoureteral reflux (urine flowing back from bladder to ureters/kidneys during voiding), urethral anatomy, bladder wall integrity, and post-void residual.", category: "Procedures", topic: "Urinary Studies", difficulty: 2, country: "usa", bodyPart: "Urinary System", exam: "arrt", examDomain: "Procedures", masteryCategory: "knowledge" },
  { question: "For a hysterosalpingogram (HSG), contrast is injected through:", optionA: "An IV line", optionB: "A catheter placed through the cervix into the uterus", optionC: "The vagina without a catheter", optionD: "An NG tube", correctAnswer: "B", rationale: "HSG involves fluoroscopically guided injection of water-soluble contrast through a cervical catheter to outline the uterine cavity and demonstrate tubal patency for fertility evaluation.", category: "Procedures", topic: "Reproductive Studies", difficulty: 2, country: "usa", bodyPart: "Uterus", exam: "arrt", examDomain: "Procedures", masteryCategory: "knowledge" },
  { question: "For the AP Ferguson method of the lumbosacral junction, the CR is angled:", optionA: "Perpendicular", optionB: "30-35 degrees cephalad to open the L5-S1 disc space", optionC: "10 degrees caudad", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "The Ferguson method uses a 30-35 degree cephalad angle to open the L5-S1 intervertebral disc space on the AP projection, which is not visible with a perpendicular CR due to the lordotic curve.", category: "Procedures", topic: "Spine", difficulty: 3, country: "usa", bodyPart: "Lumbar Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a myelogram, contrast is injected into:", optionA: "The intervertebral disc space", optionB: "The subarachnoid (intrathecal) space via lumbar puncture", optionC: "The epidural space", optionD: "The vertebral artery", correctAnswer: "B", rationale: "Myelography involves intrathecal injection of water-soluble contrast into the subarachnoid space (usually at L2-L3 or L3-L4) to outline the spinal cord, nerve roots, and thecal sac under fluoroscopy.", category: "Procedures", topic: "Spine Studies", difficulty: 2, country: "usa", bodyPart: "Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "knowledge" },
  { question: "The Settegast (sunrise/skyline) projection of the patella is performed with the knee flexed:", optionA: "20-30 degrees", optionB: "40-45 degrees or more, with tangential CR through the patellofemoral joint", optionC: "Full extension", optionD: "90 degrees", correctAnswer: "B", rationale: "The Settegast method requires the patient prone with knee flexed approximately 45 degrees. The CR is directed tangentially through the patellofemoral joint. Less flexion (Merchant) is used for subluxation evaluation.", category: "Procedures", topic: "Lower Extremity", difficulty: 3, country: "usa", bodyPart: "Knee", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the Zanca projection of the AC joints, the CR is angled:", optionA: "Perpendicular", optionB: "10-15 degrees cephalad to project the AC joints above the acromion", optionC: "30 degrees caudad", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "The Zanca method uses a 10-15 degree cephalad angle with reduced kVp (1/3 to 1/2 less than standard shoulder) to demonstrate the AC joints free of superimposition with the acromion.", category: "Procedures", topic: "Upper Extremity", difficulty: 3, country: "usa", bodyPart: "Shoulder", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a portable AP chest on a patient who cannot sit upright, the minimum elevation angle for detecting air-fluid levels is:", optionA: "5 degrees", optionB: "10-15 degrees is acceptable, but 90 degrees is ideal", optionC: "0 degrees (supine is fine)", optionD: "45 degrees", correctAnswer: "B", rationale: "Air-fluid levels require an upright or semi-upright position. A minimum elevation of 10-15 degrees allows some detection, but full upright (90 degrees) is ideal. True supine positioning cannot demonstrate air-fluid levels.", category: "Procedures", topic: "Chest Radiography", difficulty: 2, country: "usa", bodyPart: "Chest", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The Clements-Nakayama modification for hip imaging is used when:", optionA: "The patient can be positioned normally", optionB: "The patient cannot abduct or rotate the injured leg (both legs extended), using a nearly vertical CR with the IR parallel to the femoral neck", optionC: "Both hips need to be imaged simultaneously", optionD: "A frog-leg view is adequate", correctAnswer: "B", rationale: "The Clements-Nakayama is used when neither leg can be moved (bilateral hip fractures or post-surgical). The IR is placed vertical against the lateral hip and the CR enters from the medial side.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 4, country: "usa", bodyPart: "Hip", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP scoliosis series, the entire spine is imaged from:", optionA: "C1 to the sacrum on a single long exposure", optionB: "T1 to the iliac crests using a 14×36 inch cassette or multiple images stitched together", optionC: "Only the thoracic spine", optionD: "Only the lumbar spine", correctAnswer: "B", rationale: "Scoliosis series images the entire spine from approximately C7/T1 to the iliac crests on one image (14×36 or 14×17 stitched) to measure Cobb angles. Both upright and supine or bending views may be obtained.", category: "Procedures", topic: "Spine", difficulty: 2, country: "usa", bodyPart: "Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP axial projection of the zygomatic arches (modified Towne), the CR is angled:", optionA: "15 degrees cephalad", optionB: "30 degrees caudad to the OML", optionC: "Perpendicular", optionD: "45 degrees caudad", correctAnswer: "B", rationale: "Modified Towne for zygomatic arches uses a 30-degree caudal angle to the OML, projecting the arches below the cranium for bilateral arch comparison.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 3, country: "usa", bodyPart: "Facial Bones", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an arthrogram of the knee, contrast is injected:", optionA: "Intravenously", optionB: "Directly into the joint space (intra-articular) under fluoroscopic guidance", optionC: "Into the muscle surrounding the knee", optionD: "Orally", correctAnswer: "B", rationale: "Arthrograms involve direct injection of contrast (iodinated, air, or both) into the joint space under fluoroscopic guidance. The patient then exercises the joint to distribute contrast before imaging.", category: "Procedures", topic: "Joint Studies", difficulty: 2, country: "usa", bodyPart: "Knee", exam: "arrt", examDomain: "Procedures", masteryCategory: "knowledge" },
  { question: "For the lateral projection of the calcaneus (os calcis), the CR is directed:", optionA: "40 degrees cephalad", optionB: "Perpendicular, 1 inch inferior to the medial malleolus", optionC: "10 degrees caudad", optionD: "25 degrees cephalad", correctAnswer: "B", rationale: "The lateral calcaneus uses a perpendicular CR directed to a point 1 inch inferior to the medial malleolus. This provides a true lateral view of the calcaneus, subtalar joint, and ankle joint.", category: "Procedures", topic: "Lower Extremity", difficulty: 2, country: "usa", bodyPart: "Calcaneus", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP projection of the toes (digits 2-5), the CR is angled:", optionA: "Perpendicular", optionB: "10-15 degrees toward the heel to open the interphalangeal joint spaces", optionC: "30 degrees cephalad", optionD: "45 degrees toward the toes", correctAnswer: "B", rationale: "A 10-15 degree posterior angle (toward the heel) opens the interphalangeal and MTP joint spaces of the toes, which would otherwise appear closed due to the natural curve of the toes.", category: "Procedures", topic: "Lower Extremity", difficulty: 2, country: "usa", bodyPart: "Foot", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The oblique lumbar spine projection demonstrates the 'scotty dog.' If the 'ear' of the scotty dog appears elongated, the patient was rotated:", optionA: "Not enough (less than 45 degrees)", optionB: "Too much (more than 45 degrees)", optionC: "Exactly 45 degrees", optionD: "In the wrong direction", correctAnswer: "B", rationale: "The 'ear' represents the superior articular process. If elongated, excessive rotation (>45°) has occurred, causing the zygapophyseal joints to be seen in foreshortened profile rather than optimally.", category: "Procedures", topic: "Spine", difficulty: 3, country: "usa", bodyPart: "Lumbar Spine", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an acute abdomen series (obstruction series), the standard views include:", optionA: "AP abdomen only", optionB: "AP supine abdomen, AP upright abdomen, and PA upright chest (or left lateral decubitus abdomen)", optionC: "Lateral abdomen only", optionD: "CT abdomen only", correctAnswer: "B", rationale: "An acute abdomen series typically includes: AP supine abdomen (bowel gas pattern), AP upright abdomen (air-fluid levels), and PA upright chest (free air under diaphragm). Left lateral decubitus substitutes if the patient cannot stand.", category: "Procedures", topic: "Abdomen", difficulty: 2, country: "usa", bodyPart: "Abdomen", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For a single-contrast barium enema, the primary purpose of the RAO position is to:", optionA: "Demonstrate the hepatic flexure", optionB: "Open the sigmoid colon and the rectosigmoid junction", optionC: "Demonstrate the splenic flexure", optionD: "Show the cecum", correctAnswer: "B", rationale: "The RAO position on barium enema straightens and opens the rectosigmoid junction, which is a common site for polyps and carcinoma.", category: "Procedures", topic: "GI Studies", difficulty: 3, country: "usa", bodyPart: "Large Bowel", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP projection of the scapula, the arm is positioned:", optionA: "At the side", optionB: "Abducted at 90 degrees to move the scapula laterally away from the rib cage", optionC: "Behind the back", optionD: "Across the chest", correctAnswer: "B", rationale: "Abducting the arm at 90 degrees (right angle) moves the scapula laterally, positioning the scapular body away from the rib cage for better visualization.", category: "Procedures", topic: "Upper Extremity", difficulty: 2, country: "usa", bodyPart: "Scapula", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For bilateral weight-bearing AP projections of the knees, the CR should be:", optionA: "Perpendicular to the femoral condyles", optionB: "Angled 5-7 degrees caudad to open the joint spaces", optionC: "Angled 15 degrees cephalad", optionD: "Perpendicular at the level of the patella", correctAnswer: "B", rationale: "Weight-bearing AP knees use a 5-7 degree caudad angle (or directed to the tibial plateaus) to open the knee joint spaces. The CR is directed at the level of the knee joints.", category: "Procedures", topic: "Lower Extremity", difficulty: 2, country: "usa", bodyPart: "Knee", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an intravenous urogram (IVU/IVP), the nephrographic phase radiograph is taken:", optionA: "Before contrast injection", optionB: "1 minute after injection to demonstrate the renal parenchyma opacified with contrast", optionC: "30 minutes after injection", optionD: "2 hours after injection", correctAnswer: "B", rationale: "The nephrographic phase (1 minute post-injection) shows contrast in the renal tubules, opacifying the entire renal parenchyma. This is ideal for demonstrating renal masses and parenchymal abnormalities.", category: "Procedures", topic: "Urinary Studies", difficulty: 3, country: "usa", bodyPart: "Kidneys", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an ERCP (endoscopic retrograde cholangiopancreatography), contrast is injected:", optionA: "Intravenously", optionB: "Directly into the bile and pancreatic ducts via an endoscope positioned in the duodenum", optionC: "Orally", optionD: "Through the skin into the liver", correctAnswer: "B", rationale: "ERCP uses a side-viewing duodenoscope to cannulate the ampulla of Vater. Contrast is injected directly into the common bile duct and/or pancreatic duct for diagnostic and therapeutic purposes.", category: "Procedures", topic: "Biliary Studies", difficulty: 3, country: "usa", bodyPart: "Biliary System", exam: "arrt", examDomain: "Procedures", masteryCategory: "knowledge" },
  { question: "For a portable AP pelvis on a trauma patient, the CR is directed:", optionA: "30 degrees cephalad", optionB: "Perpendicular to the midpoint between the iliac crests and pubic symphysis", optionC: "15 degrees caudad", optionD: "At an oblique angle", correctAnswer: "B", rationale: "The portable AP pelvis uses a perpendicular CR directed to the midpoint between the iliac crests and symphysis pubis. Internal leg rotation may not be possible in trauma.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 1, country: "usa", bodyPart: "Pelvis", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the Harris-Beath (ski-jump) calcaneal axial projection, the foot is dorsiflexed and the CR enters:", optionA: "Anteriorly at the toes", optionB: "Through the plantar surface of the heel, exiting at the ankle, angled to the long axis of the foot", optionC: "Laterally", optionD: "Through the dorsum of the foot", correctAnswer: "B", rationale: "The Harris-Beath method directs the CR through the plantar surface of the heel to demonstrate the sustentaculum tali and subtalar joint posterior facet.", category: "Procedures", topic: "Lower Extremity", difficulty: 4, country: "usa", bodyPart: "Calcaneus", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For an AP bilateral sacroiliac joint projection without CR angulation, the alternative positioning is to use:", optionA: "A 30-35 degree foam wedge under each side", optionB: "Bilateral 25-30 degree posterior obliques (RPO and LPO) one at a time", optionC: "A lateral position", optionD: "A Towne projection", correctAnswer: "B", rationale: "If an axial projection is not possible, bilateral posterior obliques (25-30 degrees RPO and LPO) demonstrate each SI joint individually. The joint closest to the IR is demonstrated.", category: "Procedures", topic: "Pelvis and Hip", difficulty: 3, country: "usa", bodyPart: "Sacroiliac Joints", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the PA axial (Caldwell) projection of the sinuses, the petrous ridges should be demonstrated:", optionA: "Filling the orbits", optionB: "In the lower third of the orbits", optionC: "Above the orbits", optionD: "Below the maxillary sinuses", correctAnswer: "B", rationale: "With the 15-degree caudal angle, the petrous ridges are projected into the lower third of the orbits. This clears the frontal sinuses and upper orbits from petrous ridge superimposition.", category: "Procedures", topic: "Sinuses", difficulty: 2, country: "usa", bodyPart: "Sinuses", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "For the parietoorbltal projection (Rhese method) of the optic foramen, the skull is rotated:", optionA: "15 degrees", optionB: "53 degrees from the PA position with AML perpendicular to the IR", optionC: "30 degrees", optionD: "90 degrees", correctAnswer: "B", rationale: "The Rhese method requires 53 degrees of rotation from PA with AML perpendicular to IR (three-point landing: nose, cheek, chin). The optic foramen is projected in the lower outer quadrant of the orbit.", category: "Procedures", topic: "Skull and Facial Bones", difficulty: 4, country: "usa", bodyPart: "Skull", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "The Waters method demonstrates the maxillary sinuses best because:", optionA: "It uses a caudal CR angle", optionB: "The chin elevation projects the petrous ridges below the maxillary sinus floors, providing an unobstructed view", optionC: "It uses the highest kVp", optionD: "It uses the smallest field size", correctAnswer: "B", rationale: "By elevating the chin so the OML forms a 37-degree angle with the IR, the dense petrous ridges are projected below the maxillary sinuses, allowing clear visualization of the sinuses for fluid levels.", category: "Procedures", topic: "Sinuses", difficulty: 2, country: "usa", bodyPart: "Sinuses", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
  { question: "A left lateral decubitus abdomen radiograph demonstrates free fluid in the peritoneum as:", optionA: "Air rising to the highest point", optionB: "Fluid layering along the dependent (left) side between the abdominal wall and bowel loops", optionC: "Fluid collecting under the diaphragm", optionD: "Fluid surrounding the liver only", correctAnswer: "B", rationale: "On a left lateral decubitus, free peritoneal fluid gravitates to the dependent (left) side, visible as a gray stripe between the abdominal wall and bowel loops. Free air rises to the non-dependent (right) side.", category: "Procedures", topic: "Abdomen", difficulty: 3, country: "usa", bodyPart: "Abdomen", exam: "arrt", examDomain: "Procedures", masteryCategory: "clinical" },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2 LIMIT 1`, [q.question, q.country]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, body_part, modality, exam, exam_domain, mastery_category, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,'published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty, q.country, q.bodyPart||null, q.modality||null, q.exam, q.examDomain, q.masteryCategory||null]
      );
      inserted++;
    }
  }
  console.log(`[Batch1 ARRT Procedures] Inserted ${inserted}/${QUESTIONS.length} questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
