import pg from "pg";
import crypto from "crypto";
const Pool = pg.Pool;
const pool = new Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });
function hash(s: string): string { return crypto.createHash("md5").update(s.toLowerCase().trim()).digest("hex"); }

interface Q {
  tier: string; exam: string; stem: string; options: string[];
  correct: number; rationale: string; diff: number; bs: string;
  topic: string; subtopic: string; tags: string[]; clinicalPearl: string;
}

function q(bs: string, d: number, s: string, o: string[], c: number, r: string, topic: string, subtopic: string, tags: string[], pearl: string): Q {
  return { tier: "rn", exam: "NCLEX-RN", stem: s, options: o, correct: c, rationale: r, diff: d, bs, topic, subtopic, tags, clinicalPearl: pearl };
}

const QS: Q[] = [
  // CARDIAC (15)
  q("Cardiovascular", 3, "A nurse identifies a client in asystole on the cardiac monitor. Per ACLS, the nurse should NOT:", ["Begin CPR immediately", "Administer epinephrine", "Defibrillate the client", "Check for reversible causes (H's and T's)"], 2, "Asystole is a NON-shockable rhythm. Defibrillation is only indicated for ventricular fibrillation and pulseless ventricular tachycardia (shockable rhythms). For asystole and PEA: high-quality CPR, epinephrine 1 mg IV every 3-5 minutes, identify and treat reversible causes (H's and T's), and consider advanced airway. Options A, B, and D are all appropriate.", "Cardiac Arrest", "Asystole Management", ["cardiac", "ACLS", "asystole", "non-shockable"], "Non-shockable rhythms: asystole and PEA. Treatment: CPR + epinephrine. Shockable rhythms: VFib and pulseless VTach. Treatment: CPR + defibrillation + medications. H's and T's: Hypovolemia, Hypoxia, Hydrogen ion, Hypo/Hyperkalemia, Hypothermia, Tension pneumothorax, Tamponade, Toxins, Thrombosis."),

  q("Cardiovascular", 3, "A client with heart failure has a measured ejection fraction of 30%. The nurse classifies this as:", ["Normal systolic function", "Heart failure with reduced ejection fraction (HFrEF)", "Heart failure with preserved ejection fraction (HFpEF)", "Mildly reduced EF"], 1, "Normal EF is 55-70%. HFrEF is defined as EF ≤40%. HFpEF has EF ≥50%. HFmrEF (mildly reduced) is EF 41-49%. An EF of 30% indicates significant systolic dysfunction (HFrEF). Treatment for HFrEF includes GDMT: ACE-I/ARB/ARNI, beta-blocker, mineralocorticoid antagonist, and SGLT2 inhibitor.", "Heart Failure", "EF Classification", ["cardiac", "heart-failure", "ejection-fraction", "classification"], "EF categories: HFrEF ≤40%, HFmrEF 41-49%, HFpEF ≥50%. GDMT for HFrEF: ACE-I/ARNI + beta-blocker + MRA + SGLT2i (four pillars). Target doses, not just starting doses."),

  q("Cardiovascular", 2, "A nurse is teaching a client about deep vein thrombosis prevention after surgery. The nurse should advise:", ["Remain on strict bed rest", "Early ambulation, sequential compression devices, prescribed anticoagulants, and adequate hydration", "Cross legs while sitting to improve circulation", "Massage the affected leg if DVT is suspected"], 1, "DVT prevention (Virchow's triad targets): early ambulation (reduce stasis), SCDs (promote venous return), pharmacologic prophylaxis (LMWH or fondaparinux), adequate hydration, and leg exercises. NEVER massage a suspected DVT (can dislodge clot causing PE). Option A promotes stasis. Option C impedes venous return. Option D can cause fatal PE.", "DVT Prevention", "Post-Surgical Prophylaxis", ["cardiac", "DVT", "post-operative", "prevention"], "DVT prevention: early ambulation, SCDs, anticoagulant prophylaxis. If DVT suspected: NEVER massage, Doppler ultrasound for diagnosis. Homan's sign is unreliable and no longer recommended for assessment."),

  q("Cardiovascular", 3, "A nurse is caring for a client with Wolff-Parkinson-White (WPW) syndrome. The nurse should avoid administering:", ["Normal saline", "Adenosine or AV nodal blocking agents (digoxin, verapamil, diltiazem) which can cause fatal ventricular fibrillation", "Oxygen via nasal cannula", "Acetaminophen for headache"], 1, "WPW syndrome involves an accessory pathway (Bundle of Kent) that bypasses the AV node. AV nodal blocking agents (digoxin, verapamil, diltiazem, adenosine) are CONTRAINDICATED because they slow conduction through the AV node while allowing rapid conduction through the accessory pathway, potentially causing ventricular fibrillation. Treatment for WPW with atrial fibrillation: procainamide or ibutilide. Definitive treatment: catheter ablation. Options A, C, and D are safe.", "Dysrhythmias", "WPW Syndrome", ["cardiac", "WPW", "accessory-pathway", "contraindications"], "WPW: delta wave on ECG (slurred upstroke of QRS). AVOID AV nodal blockers (digoxin, verapamil, diltiazem, adenosine). Treat AFib with WPW: procainamide or electrical cardioversion. Definitive: catheter ablation of accessory pathway."),

  q("Cardiovascular", 2, "A client with heart failure asks about daily sodium intake. The nurse should advise:", ["There are no sodium restrictions for heart failure", "Limit sodium to less than 2,000 mg (2 grams) per day; read food labels and avoid processed foods", "Only restrict sodium if taking diuretics", "Sodium restriction is only needed during hospitalization"], 1, "The AHA recommends sodium restriction to <2,000 mg/day for heart failure patients. Excess sodium causes fluid retention, increasing preload and worsening heart failure symptoms. Teaching: read food labels, avoid processed foods (80% of dietary sodium), cook at home, use herbs/spices instead of salt. Options A, C, and D underestimate the importance of sodium restriction.", "Heart Failure", "Sodium Restriction", ["cardiac", "heart-failure", "sodium", "nutrition"], "HF sodium: <2,000 mg/day. One teaspoon of table salt = 2,300 mg sodium. Teach to read labels: look for sodium content per serving. Highest sodium sources: processed foods, restaurant meals, canned soups, deli meats."),

  // RESPIRATORY (10)
  q("Respiratory", 3, "A nurse is caring for a client on BiPAP for acute COPD exacerbation. The nurse should monitor for:", ["Improved oxygen saturation and decreased work of breathing", "Gastric distension from air swallowing, skin breakdown from mask, and continued respiratory failure requiring intubation", "Hyperglycemia", "Bradycardia"], 1, "BiPAP (bilevel positive airway pressure) complications: aerophagia (gastric distension), skin breakdown at mask contact points (monitor and use properly fitting masks), aspiration risk (if patient vomits), and treatment failure requiring intubation. Reassess within 1-2 hours — if no improvement, escalate to intubation. Option A is the desired outcome, not a complication. Options C and D are not BiPAP-related.", "Non-Invasive Ventilation", "BiPAP Monitoring", ["respiratory", "BiPAP", "COPD", "complications"], "BiPAP: delivers different pressures for inspiration (IPAP) and expiration (EPAP). Reassess in 1-2 hours: if improving, continue. If not: intubate. Contraindications: facial trauma, decreased LOC, unable to protect airway, excessive secretions."),

  q("Respiratory", 2, "A client with a chest tube system accidentally disconnects the drainage tubing from the chest tube. The nurse should first:", ["Clamp the chest tube with a hemostat", "Submerge the end of the chest tube in a container of sterile water to create a temporary water seal", "Push the tubing back together without cleaning", "Remove the chest tube entirely"], 1, "If a chest tube disconnects from the drainage system, the immediate action is to submerge the open end of the chest tube in a container of sterile water or saline to prevent air entry (creating a temporary water seal). Clamping the chest tube (Option A) is generally contraindicated (can cause tension pneumothorax). Then set up a new drainage system. Options C and D are incorrect procedures.", "Chest Tube Management", "Emergency Disconnection", ["respiratory", "chest-tube", "emergency", "troubleshooting"], "Chest tube disconnection: submerge in sterile water immediately. Do NOT clamp (tension pneumothorax risk). Exception: clamping briefly to assess for air leak. If tube falls out completely: cover site with petroleum gauze (taped on 3 sides)."),

  q("Respiratory", 3, "A nurse is assessing breath sounds and hears fine inspiratory crackles at the lung bases bilaterally. This finding is most consistent with:", ["Normal breath sounds", "Fluid in the alveoli, as seen in early heart failure or pneumonia", "Airway obstruction from mucus", "Pleural friction rub"], 1, "Fine crackles (rales) are short, high-pitched, discontinuous sounds heard during inspiration. They indicate fluid in the alveoli or opening of collapsed alveoli. Common causes: pulmonary edema (heart failure), pneumonia, atelectasis, and pulmonary fibrosis. Coarse crackles indicate fluid in larger airways. Option A — fine crackles are abnormal. Option C produces rhonchi. Option D produces a grating sound with both inspiration and expiration.", "Lung Auscultation", "Crackles Assessment", ["respiratory", "auscultation", "crackles", "assessment"], "Breath sounds: Fine crackles = alveolar fluid/opening. Coarse crackles = large airway secretions. Wheezes = narrowed airways (asthma/COPD). Stridor = upper airway obstruction (emergency). Pleural rub = pleurisy. Absent = pneumothorax/effusion."),

  // GI (10)
  q("Gastrointestinal", 3, "A nurse is caring for a client with acute liver failure who has an elevated INR, elevated ammonia, and altered mental status. The nurse should:", ["Administer aspirin for headache", "Maintain airway, administer lactulose, monitor for cerebral edema, and prepare for possible liver transplant evaluation", "Encourage high-protein diet", "Discharge the client with oral medications"], 1, "Acute liver failure (ALF) is a medical emergency with rapid deterioration of hepatic function causing coagulopathy and encephalopathy. Management: ICU-level care, airway protection, lactulose for encephalopathy, fresh frozen plasma for bleeding, monitor for cerebral edema (ICP monitoring in severe cases), and emergent liver transplant evaluation. Option A increases bleeding risk. Option C worsens encephalopathy. Option D is inappropriate.", "Acute Liver Failure", "Emergency Management", ["GI", "liver-failure", "encephalopathy", "emergency"], "Acute liver failure: INR >1.5 + encephalopathy without pre-existing liver disease. Causes: acetaminophen toxicity (#1 in US), viral hepatitis, drug reactions. Cerebral edema is the #1 cause of death. Contact transplant center early."),

  q("Gastrointestinal", 2, "A nurse is teaching a client about preparation for a colonoscopy. The nurse should instruct:", ["Eat a regular diet the day before the procedure", "Follow a clear liquid diet the day before, complete the prescribed bowel preparation solution, and arrange for a driver due to sedation", "No preparation is needed for a colonoscopy", "Only take a single laxative tablet the morning of"], 1, "Colonoscopy preparation: clear liquid diet the day before, bowel preparation solution (polyethylene glycol or sodium phosphate) to cleanse the colon, NPO after midnight (or per protocol), arrange a responsible driver (sedation used), and review medication adjustments with the provider (hold anticoagulants, insulin adjustments, iron supplements). Options A, C, and D result in inadequate preparation and poor visualization.", "Colonoscopy", "Pre-Procedure Preparation", ["GI", "colonoscopy", "bowel-prep", "patient-education"], "Colonoscopy prep: clear liquids day before, complete bowel prep (both doses!), NPO after midnight, arrange driver. Inadequate prep = poor visualization = repeat procedure. Review medication changes: hold warfarin, adjust diabetes meds."),

  // RENAL (5)
  q("Renal/Urinary", 3, "A nurse is caring for a client with acute kidney injury in the oliguric phase. The nurse should expect which fluid management approach?", ["IV fluid boluses to force diuresis", "Restrict fluids to match output plus insensible losses (approximately 400-500 mL/day plus output)", "Encourage unlimited oral fluid intake", "Administer IV fluids at 250 mL/hr"], 1, "During the oliguric phase of AKI (urine output <400 mL/day), fluid restriction is essential to prevent fluid overload, pulmonary edema, and hypertension. Daily fluid allowance = urine output from the previous 24 hours + insensible losses (approximately 400-500 mL/day from respiration and perspiration). Monitor daily weights and I&O carefully. Options A, C, and D can cause dangerous fluid overload.", "Acute Kidney Injury", "Oliguric Phase Management", ["renal", "AKI", "fluid-restriction", "oliguric-phase"], "AKI phases: 1) Initiation (insult), 2) Oliguric (<400 mL/day — restrict fluids, manage K+), 3) Diuretic (massive UO — replace fluids and electrolytes), 4) Recovery. Monitor for fluid overload in oliguric phase and dehydration in diuretic phase."),

  q("Renal/Urinary", 2, "A client with a urinary catheter develops cloudy, foul-smelling urine with sediment. The nurse suspects:", ["Normal catheter drainage", "Catheter-associated urinary tract infection (CAUTI)", "Dehydration", "Normal concentrated urine"], 1, "Signs of CAUTI: cloudy urine, foul odor, sediment, fever, suprapubic tenderness, and sometimes hematuria. CAUTI prevention bundle: insert only when indicated, use aseptic technique, maintain closed drainage system, keep bag below bladder level, perform regular perineal hygiene, remove catheter as soon as possible. Options A and D normalize an abnormal finding. Option C may cause concentrated urine but not the described symptoms.", "Urinary Catheter", "CAUTI Recognition", ["renal", "CAUTI", "urinary-catheter", "infection"], "CAUTI prevention: insert only when necessary, remove ASAP, sterile insertion technique, closed drainage system, bag below bladder, daily assessment for continued need. #1 modifiable risk factor: unnecessary catheter days."),

  // NEURO (5)
  q("Neurological", 3, "A nurse is caring for a client with a traumatic brain injury who develops diabetes insipidus. The nurse should monitor for:", ["Fluid overload and hyponatremia", "Massive polyuria, hypernatremia, and dehydration", "Oliguria and hyperkalemia", "Weight gain and edema"], 1, "TBI can damage the posterior pituitary or hypothalamus, reducing ADH secretion and causing central diabetes insipidus. Signs: massive polyuria (4-20 L/day of dilute urine), hypernatremia (from water loss), dehydration, polydipsia, and low urine specific gravity (<1.005). Treatment: fluid replacement and DDAVP (desmopressin). Option A describes SIADH. Options C and D are not consistent with DI.", "Diabetes Insipidus", "Post-TBI DI", ["neuro", "diabetes-insipidus", "TBI", "hypernatremia"], "Post-TBI DI: monitor UO closely (sudden increase may signal DI). Urine SG <1.005, serum Na >145. Replace fluids mL-for-mL. Desmopressin (DDAVP) nasal spray or injection. May be temporary or permanent depending on injury severity."),

  q("Neurological", 3, "A client with Parkinson's disease exhibits 'on-off' phenomenon with their carbidopa-levodopa therapy. The nurse should explain:", ["This is unrelated to the medication", "Over time, the medication effect becomes unpredictable with sudden fluctuations between mobility ('on') and immobility ('off') periods", "The medication should be doubled", "This indicates the disease is cured"], 1, "The 'on-off' phenomenon is a motor fluctuation that develops after 5-10 years of levodopa therapy. During 'on' periods, the medication is working (improved mobility). During 'off' periods, the medication is ineffective (severe akinesia, rigidity). Management includes: more frequent smaller doses, extended-release formulations, adding COMT inhibitors (entacapone) or MAO-B inhibitors (rasagiline), or considering deep brain stimulation. Options A, C, and D are incorrect.", "Parkinson's Disease", "Motor Fluctuations", ["neuro", "parkinsons", "on-off-phenomenon", "levodopa"], "Parkinson's motor fluctuations: on-off phenomenon (unpredictable), wearing off (end-of-dose), dyskinesias (involuntary movements from peak dose). Management: dose adjustment, add entacapone/rasagiline, consider DBS surgery."),

  // ENDOCRINE (5)
  q("Endocrine", 3, "A client with type 1 diabetes is using an insulin-to-carbohydrate ratio of 1:15. The nurse should teach that this means:", ["Take 1 unit of insulin for every 15 minutes of exercise", "Take 1 unit of rapid-acting insulin for every 15 grams of carbohydrates consumed", "Take 15 units of insulin with every meal", "Skip insulin if eating fewer than 15 grams of carbohydrates"], 1, "Insulin-to-carbohydrate (I:C) ratio is a method for calculating mealtime insulin doses. A ratio of 1:15 means the client takes 1 unit of rapid-acting insulin for every 15 grams of carbohydrates eaten. If the client eats 60g of carbs, they would take 4 units (60/15 = 4). This ratio is individualized and adjusted based on blood glucose patterns. Options A, C, and D are incorrect interpretations.", "Diabetes Management", "Carbohydrate Counting", ["endocrine", "diabetes", "insulin-to-carb-ratio", "carb-counting"], "Insulin-to-carb ratio: calculate mealtime insulin based on carbs consumed. Common ratios: 1:10 to 1:15. Also use correction factor (sensitivity factor) for high blood glucose. Both are individualized."),

  q("Endocrine", 3, "A client is being discharged with a new prescription for prednisone 40 mg daily for an autoimmune condition. The nurse should teach:", ["Stop the medication immediately when symptoms resolve", "Take with food in the morning to mimic natural cortisol secretion, never stop abruptly, and carry a medical alert card", "Take on an empty stomach at bedtime", "No special instructions needed"], 1, "Prednisone teaching: take with food (reduces GI upset), take in the morning (mimics natural cortisol peak, reduces insomnia), never stop abruptly (adrenal crisis risk after prolonged use), carry a medical alert card/bracelet, report signs of infection (fever, sore throat), monitor blood glucose (steroid-induced hyperglycemia), and attend regular check-ups (bone density, eye exams). Option A risks adrenal crisis. Options C and D are incorrect.", "Corticosteroids", "Discharge Education", ["endocrine", "prednisone", "corticosteroid", "patient-education"], "Prednisone discharge teaching: morning dose, with food, never stop abruptly, carry steroid card, report infections, monitor weight/glucose. Taper schedule must be followed precisely. Stress dosing may be needed for illness/surgery."),

  // PHARMACOLOGY FINAL SET (90)
  q("Pharmacology", 3, "A client is prescribed rosuvastatin (Crestor). The nurse should advise that liver function tests should be monitored:", ["Never", "At baseline and periodically during therapy; report unexplained muscle pain", "Daily", "Only if the client drinks alcohol"], 1, "Statin monitoring: LFTs at baseline and as clinically indicated (no longer routinely recommended at set intervals per updated guidelines, but commonly done). Report unexplained muscle pain, tenderness, or weakness (myopathy/rhabdomyolysis). CK level if symptomatic. Rosuvastatin is the most potent statin. Fewer CYP3A4 interactions than atorvastatin/simvastatin. Options A, C, and D are incorrect.", "Antilipemics", "Statin Monitoring", ["pharmacology", "rosuvastatin", "statin", "LFT-monitoring"], "Rosuvastatin: most potent statin (least CYP3A4 metabolism). Can be taken any time of day. Fewer drug interactions than simvastatin. Monitor LFTs baseline + PRN. Report muscle pain immediately."),

  q("Pharmacology", 2, "A nurse is administering eye drops to a client. Proper technique includes:", ["Dropping the medication directly onto the cornea", "Pulling down the lower lid to create a pocket (conjunctival sac), instilling the drop, and having the client close the eye gently", "Having the client look down during instillation", "Pressing firmly on the eyeball after instillation"], 1, "Eye drop technique: wash hands, tilt head back, pull down lower lid creating a pouch (conjunctival sac), instill drop into the pouch (not directly on the cornea), close eye gently for 1-2 minutes, apply gentle pressure to the inner canthus (nasolacrimal duct occlusion) for 1-2 minutes to minimize systemic absorption. Wait 5 minutes between different eye drops. Option A causes blink reflex and corneal irritation. Options C and D are incorrect.", "Ophthalmic Medications", "Eye Drop Administration", ["pharmacology", "eye-drops", "ophthalmic", "administration-technique"], "Eye drop technique: conjunctival sac, close eye 1-2 min, nasolacrimal occlusion (prevents systemic absorption of timolol/beta-blocker eye drops — can cause bradycardia!). Wait 5 min between different drops. Ointment last."),

  q("Pharmacology", 3, "A client is prescribed doxycycline for an infection. The nurse should teach:", ["Take with a full glass of milk", "Take with a full glass of water, avoid lying down for 30 minutes after, and avoid dairy products and antacids", "Take on a completely empty stomach", "No sun precautions are needed"], 1, "Doxycycline teaching: take with full glass of water, remain upright for 30 minutes (prevents esophageal erosion), avoid dairy products, calcium, iron, and antacids (chelation reduces absorption), use sunscreen (photosensitivity), and complete the full course. Can be taken with food (unlike other tetracyclines). Option A reduces absorption. Option C — doxycycline can be taken with food. Option D — doxycycline causes significant photosensitivity.", "Antibiotics", "Doxycycline Education", ["pharmacology", "doxycycline", "tetracycline", "photosensitivity"], "Doxycycline: upright 30 min after (esophageal protection), avoid dairy/antacids/iron, sunscreen essential. Can take with food (unique among tetracyclines). Avoid in pregnancy and children <8 (teeth staining)."),

  q("Pharmacology", 3, "A client is receiving IV norepinephrine. The nurse notes the MAP has been consistently above target. The nurse should:", ["Increase the infusion rate", "Titrate the norepinephrine infusion DOWN gradually per protocol; abrupt discontinuation can cause rebound hypotension", "Stop the infusion abruptly", "Switch to oral vasopressors immediately"], 1, "Vasopressor weaning must be done gradually to allow the cardiovascular system to adapt. Abrupt discontinuation of norepinephrine can cause severe rebound hypotension, decreased organ perfusion, and cardiovascular collapse. Titrate down by small increments (typically 1-2 mcg/min) over hours while monitoring MAP, heart rate, and end-organ perfusion. Option A worsens the situation. Options C and D can cause hemodynamic instability.", "Vasopressors", "Norepinephrine Weaning", ["pharmacology", "norepinephrine", "vasopressor-weaning", "critical-care"], "Vasopressor weaning: titrate slowly, monitor MAP continuously. If hypotension recurs: increase rate back. Assess: adequate fluid resuscitation, resolved underlying cause, stable hemodynamics before weaning. Wean one vasopressor at a time if on multiple."),

  q("Pharmacology", 2, "A client is prescribed cetirizine (Zyrtec) for seasonal allergies. The nurse should explain:", ["This medication causes significant drowsiness like older antihistamines", "This is a second-generation antihistamine with less sedation than first-generation agents, but drowsiness can still occur", "This medication requires a prescription only", "It can be taken with alcohol safely"], 1, "Second-generation antihistamines (cetirizine, loratadine, fexofenadine) are less sedating than first-generation (diphenhydramine, chlorpheniramine) because they do not readily cross the blood-brain barrier. However, cetirizine can still cause mild drowsiness in some patients. Fexofenadine is the least sedating. Options A overstates sedation. Options C and D are incorrect.", "Antihistamines", "Second-Generation", ["pharmacology", "cetirizine", "antihistamine", "allergy"], "Second-generation antihistamines: cetirizine (mild sedation possible), loratadine (minimal sedation), fexofenadine (least sedating). No significant anticholinergic effects. Safe for long-term use."),

  q("Pharmacology", 3, "A client with type 2 diabetes is prescribed pioglitazone (Actos). The nurse should monitor for:", ["Hypoglycemia as a common effect", "Fluid retention, weight gain, and signs of heart failure (edema, dyspnea, weight gain)", "Hyperkalemia", "Lactic acidosis"], 1, "Thiazolidinediones (pioglitazone, rosiglitazone) improve insulin sensitivity but cause fluid retention, weight gain, and can precipitate or worsen heart failure. Contraindicated in NYHA Class III-IV heart failure. Other risks: bladder cancer (pioglitazone), fractures (especially in women), and hepatotoxicity (monitor LFTs). Options A — TZDs rarely cause hypoglycemia alone. Option C is not associated. Option D is metformin-related.", "Oral Hypoglycemics", "Thiazolidinedione Monitoring", ["pharmacology", "pioglitazone", "heart-failure", "diabetes"], "Thiazolidinediones: insulin sensitizers. Risk: fluid retention, edema, HF exacerbation. Contraindicated in NYHA III-IV. Monitor: weight, LFTs, bone density (fracture risk in women). Onset: 2-4 weeks for full effect."),

  q("Pharmacology", 3, "A nurse is administering blood products and the client develops urticaria (hives) without respiratory distress or hemodynamic instability. The nurse should:", ["Stop the transfusion permanently", "Slow or temporarily stop the transfusion, administer diphenhydramine as prescribed, and resume if symptoms resolve", "Continue the transfusion without intervention", "Administer epinephrine immediately"], 1, "Mild allergic transfusion reactions (urticaria, itching without systemic symptoms) can be managed by temporarily stopping the transfusion, administering antihistamines (diphenhydramine), and resuming if symptoms resolve within 30 minutes. If symptoms progress to anaphylaxis (respiratory distress, hypotension, angioedema), stop the transfusion permanently and administer epinephrine. Option A is too aggressive for mild reaction. Option C ignores the reaction. Option D is for anaphylaxis.", "Blood Transfusion", "Allergic Reaction Management", ["pharmacology", "transfusion", "allergic-reaction", "antihistamine"], "Transfusion reaction types: Mild allergic (urticaria): antihistamine, may resume. Febrile non-hemolytic (fever, chills): antipyretics, may resume if fever resolves. Hemolytic (back pain, dark urine): STOP permanently. Anaphylactic: STOP, epinephrine, emergency care."),

  q("Pharmacology", 3, "A client is prescribed oseltamivir (Tamiflu) for influenza. The nurse should explain:", ["This medication cures the flu instantly", "This medication reduces symptom duration by 1-2 days and is most effective when started within 48 hours of symptom onset", "It replaces the annual flu vaccine", "Take only when symptoms worsen"], 1, "Oseltamivir (neuraminidase inhibitor) reduces influenza symptom duration by 1-2 days and decreases complication risk. Most effective when started within 48 hours of symptom onset. Can be used for treatment (5 days) or prophylaxis (10 days). Does NOT replace vaccination. Side effects: nausea, vomiting (take with food). Options A overstates effectiveness. Options C and D are incorrect.", "Antivirals", "Oseltamivir Education", ["pharmacology", "oseltamivir", "influenza", "antiviral"], "Oseltamivir: start within 48 hrs of symptoms. Treatment: 75 mg BID x 5 days. Prophylaxis: 75 mg daily x 10 days. Baloxavir (Xofluza): single dose alternative. Neither replaces annual vaccination."),

  q("Pharmacology", 3, "A nurse is monitoring a client receiving IV sodium bicarbonate for metabolic acidosis. The nurse should watch for:", ["Hyperkalemia", "Metabolic alkalosis from overcorrection and hypokalemia from intracellular potassium shift", "Respiratory acidosis", "Hyperglycemia"], 1, "Sodium bicarbonate corrects metabolic acidosis by neutralizing hydrogen ions. Risks: overcorrection causing metabolic alkalosis, hypokalemia (as alkalosis shifts K+ intracellularly), hypernatremia (sodium load), fluid overload, and paradoxical intracellular acidosis (CO2 crosses cell membranes faster than bicarbonate). Monitor ABGs, electrolytes (especially K+), and serum osmolality. Option A is opposite — K+ decreases. Options C and D are not primary concerns.", "Alkalizing Agents", "Sodium Bicarbonate Monitoring", ["pharmacology", "sodium-bicarbonate", "metabolic-acidosis", "electrolytes"], "IV sodium bicarbonate: watch for overcorrection (metabolic alkalosis), hypokalemia, hypernatremia. Only indicated for severe metabolic acidosis (pH <7.1). Target pH 7.20-7.25, NOT normal pH. Let the body compensate for the rest."),

  q("Pharmacology", 2, "A client is prescribed calcium carbonate (Tums) as a calcium supplement. The nurse should advise:", ["Take on an empty stomach", "Take with food because stomach acid is needed for calcium carbonate absorption", "Take with iron supplements at the same time", "Calcium carbonate and calcium citrate work identically"], 1, "Calcium carbonate requires an acidic environment for absorption and should be taken with food (gastric acid production increases with eating). Calcium citrate does NOT require acid and can be taken without food (better for clients on PPIs or with achlorhydria). Take in divided doses (500 mg at a time for best absorption). Separate from iron (mutual absorption interference). Options A reduces absorption. Option C causes mutual interference. Option D — they differ in acid requirements.", "Calcium Supplements", "Calcium Carbonate vs Citrate", ["pharmacology", "calcium", "supplements", "absorption"], "Calcium supplements: carbonate = with food (needs acid). Citrate = anytime (acid-independent, better for PPI users). Max single dose: 500 mg. Take with vitamin D. Separate from iron, thyroid meds, and fluoroquinolones by 2+ hours."),

  q("Pharmacology", 3, "A client is prescribed sacubitril/valsartan (Entresto) for heart failure. The nurse should ensure:", ["The client is also taking an ACE inhibitor", "The client has been off ACE inhibitors for at least 36 hours before starting Entresto to prevent angioedema", "No special precautions are needed", "The medication can be started immediately regardless of previous medications"], 1, "Sacubitril/valsartan (ARNI — angiotensin receptor-neprilysin inhibitor) has demonstrated superior outcomes to ACE inhibitors in HFrEF (PARADIGM-HF trial). CRITICAL: must discontinue ACE inhibitors at least 36 hours before starting Entresto due to risk of severe angioedema (sacubitril increases bradykinin, combined with ACE inhibitor effect). Can be used as a replacement for ACE inhibitors in HFrEF. Options A, C, and D ignore the critical washout period.", "Heart Failure Medications", "Entresto Initiation", ["pharmacology", "entresto", "ARNI", "heart-failure"], "Entresto: 36-hour ACE inhibitor washout REQUIRED. PARADIGM-HF: 20% mortality reduction vs enalapril. Monitor: hypotension, hyperkalemia, renal function. Can be combined with beta-blockers and MRA. Contraindicated with ACE inhibitors or in pregnancy."),

  q("Pharmacology", 3, "A nurse is teaching a client about the medication apixaban (Eliquis). The client asks about dietary restrictions. The nurse should advise:", ["Avoid all vitamin K-containing foods", "No specific dietary restrictions are required with apixaban, unlike warfarin", "Follow a low-sodium diet specifically for the medication", "Avoid all grapefruit products"], 1, "Unlike warfarin (which requires consistent vitamin K intake), direct oral anticoagulants (DOACs) like apixaban do not interact with vitamin K or require dietary restrictions. This is a significant advantage and improves quality of life. However, clients should still avoid excessive alcohol and report any bleeding. Options A and D apply to warfarin, not DOACs. Option C is not medication-specific.", "Anticoagulant Therapy", "DOAC Dietary Freedom", ["pharmacology", "apixaban", "DOAC", "dietary-restrictions"], "DOAC advantages over warfarin: no dietary restrictions, no routine monitoring, predictable pharmacokinetics, fewer drug interactions, rapid onset/offset. Disadvantages: no routine monitoring (hard to assess compliance), cost, renal clearance considerations."),

  q("Pharmacology", 3, "A client with opioid use disorder is prescribed buprenorphine/naloxone (Suboxone). The nurse should explain:", ["This medication should be swallowed whole with water", "Place the sublingual film under the tongue and allow to dissolve completely; do not swallow, eat, or drink until fully dissolved", "This medication causes euphoria similar to other opioids", "Take this medication by injection only"], 1, "Buprenorphine/naloxone (Suboxone) is administered sublingually (film or tablet). Proper technique: place under the tongue, allow to dissolve completely (5-10 minutes), do not swallow (reduces bioavailability), and do not eat or drink during dissolution. Buprenorphine is a partial opioid agonist (ceiling effect — reduces overdose risk). Naloxone component deters IV misuse. Option A dramatically reduces effectiveness. Option C overstates effects (partial agonist). Option D is a different formulation.", "Opioid Use Disorder", "Buprenorphine Administration", ["pharmacology", "buprenorphine", "suboxone", "opioid-use-disorder"], "Suboxone: sublingual only (do not swallow). Partial agonist (ceiling effect = safety). Naloxone component blocks IV misuse. Must be in mild withdrawal before first dose (precipitated withdrawal risk). X-waiver no longer required (2023 DEA changes)."),

  q("Pharmacology", 3, "A nurse is caring for a client receiving packed red blood cells who develops dyspnea, crackles, distended neck veins, and elevated blood pressure during transfusion. The nurse suspects:", ["Hemolytic reaction", "Transfusion-associated circulatory overload (TACO)", "Anaphylactic reaction", "Febrile non-hemolytic reaction"], 1, "TACO occurs when the volume of transfused blood products exceeds the cardiac system's ability to manage. Signs: dyspnea, orthopnea, crackles, JVD, hypertension, and peripheral edema. More common in elderly and clients with heart failure. Prevention: slower transfusion rate, diuretic administration between units. Treatment: stop/slow transfusion, elevate HOB, administer diuretics. Option A causes hypotension and dark urine. Option C causes respiratory distress with hypotension. Option D causes fever/chills.", "Blood Transfusion", "TACO", ["pharmacology", "transfusion", "TACO", "fluid-overload"], "TACO vs TRALI: TACO = fluid overload (HTN, JVD, crackles). TRALI = non-cardiogenic pulmonary edema (hypotension, hypoxemia, bilateral infiltrates, no fluid overload). TACO: slow transfusion, diuretics. TRALI: supportive care, O2, possible intubation."),

  q("Pharmacology", 2, "A client is prescribed a nitroglycerin patch for chronic angina. The nurse should teach:", ["Apply the patch continuously 24 hours a day", "Apply the patch for 12-14 hours on and 10-12 hours off to prevent tolerance", "Apply the patch only during chest pain episodes", "Place the patch directly over the heart"], 1, "Nitrate tolerance develops with continuous exposure. To prevent this, a 10-12 hour nitrate-free interval is recommended (typically overnight — apply in the morning, remove at bedtime). Apply to a clean, dry, hairless area on the trunk or upper arm. Rotate sites. Do not cut patches. Wash hands after application. Option A promotes tolerance. Option C is not prophylactic use. Option D — can be placed on trunk or upper arm.", "Antianginal Agents", "Nitrate Tolerance Prevention", ["pharmacology", "nitroglycerin-patch", "tolerance", "angina"], "Nitrate patch: 12 hrs on, 12 hrs off (nitrate-free interval prevents tolerance). Apply to clean dry skin, rotate sites. Remove before MRI (metallic backing in some brands). Dispose safely (significant drug remains in used patches)."),

  q("Pharmacology", 3, "A client receiving IV amiodarone develops hypotension. The nurse should:", ["Continue the infusion and add a vasopressor", "Slow the infusion rate and notify the provider, as hypotension is a common side effect of IV amiodarone loading", "Increase the infusion rate", "Discontinue the medication permanently"], 1, "IV amiodarone commonly causes hypotension during the loading phase due to the solvent (polysorbate 80) causing vasodilation. Management: slow the infusion rate, position the client supine, administer IV fluids, and notify the provider. If the client is hemodynamically unstable, the infusion may need to be temporarily stopped. The new aqueous formulation (Nexterone) causes less hypotension. Option A skips the first step. Option C worsens hypotension. Option D may not be necessary.", "Antidysrhythmics", "IV Amiodarone Hypotension", ["pharmacology", "amiodarone", "hypotension", "IV-loading"], "IV amiodarone hypotension: slow rate first. Polysorbate 80 (old formulation) causes more hypotension than Nexterone (aqueous). Loading: 150 mg over 10 min, then 1 mg/min x 6 hrs, then 0.5 mg/min x 18 hrs. Monitor BP, HR, ECG continuously."),

  q("Pharmacology", 3, "A nurse is preparing to administer medications through a nasogastric tube. The nurse should:", ["Crush all medications together and mix with a carbonated beverage", "Verify tube placement, flush with 30 mL of water before and after medications, administer each crushed medication separately with flushes between", "Give all medications at once without flushing", "Mix crushed medications with enteral tube feeding formula"], 1, "NG tube medication administration: 1) Verify placement (pH ≤5.5 or X-ray), 2) Hold tube feeding 30 min before/after if medication requires empty stomach, 3) Flush with 30 mL water, 4) Crush each medication separately (avoid mixing — potential incompatibilities), 5) Flush with 5-10 mL between each medication, 6) Final flush with 30 mL water. NEVER crush: enteric-coated, extended-release, or sublingual tablets. Option A causes interactions and tube clogging. Options C and D compromise medication delivery.", "NG Tube Medications", "Administration Technique", ["pharmacology", "NG-tube", "medication-administration", "technique"], "NG medication rules: verify placement first, flush before/after, crush separately. NEVER crush: enteric-coated (EC), extended-release (ER/XR/SR/CR), sublingual, or cytotoxic drugs. Liquid forms preferred when available."),

  q("Pharmacology", 3, "A client with chronic kidney disease is prescribed sevelamer (Renagel) instead of calcium-based phosphate binders. The nurse should explain this choice:", ["Sevelamer is cheaper", "Sevelamer does not contain calcium, avoiding the risk of hypercalcemia and vascular calcification that calcium-based binders may cause", "Sevelamer works faster", "No difference exists between the two"], 1, "Sevelamer is a non-calcium, non-aluminum phosphate binder. Advantages over calcium-based binders (calcium acetate/carbonate): no risk of hypercalcemia, reduced vascular calcification (which accelerates cardiovascular disease in CKD patients), and may have additional benefits on lipid profiles. Must be taken WITH meals (binds dietary phosphorus). Option A — sevelamer is often more expensive. Options C and D are incorrect.", "CKD Medications", "Phosphate Binder Selection", ["pharmacology", "sevelamer", "CKD", "phosphate-binder"], "Phosphate binder options: calcium acetate (cheap but hypercalcemia risk), sevelamer (no calcium, reduces vascular calcification), lanthanum (chewable). All must be taken WITH meals. Choice depends on calcium levels, calcification risk, and cost."),

  q("Pharmacology", 2, "A client is prescribed metronidazole (Flagyl) for a C. difficile infection. The nurse must advise:", ["Alcohol is safe with this medication", "Avoid ALL alcohol during treatment and for 48-72 hours after completing the course due to disulfiram-like reaction", "Take on an empty stomach for better absorption", "This medication has no significant drug interactions"], 1, "Metronidazole causes a disulfiram-like reaction with alcohol: severe nausea, vomiting, abdominal cramps, flushing, headache, and tachycardia. Clients must avoid all forms of alcohol (including alcohol-containing medications, mouthwash, and cooking wine) during therapy and for 48-72 hours after completion. Other side effects: metallic taste, peripheral neuropathy with prolonged use. Option A is dangerous. Option C — can be taken with food. Option D ignores significant interactions.", "Antibiotics", "Metronidazole-Alcohol Interaction", ["pharmacology", "metronidazole", "alcohol-interaction", "C-diff"], "Metronidazole + alcohol = disulfiram-like reaction. Avoid ALL alcohol forms for 48-72 hrs after completing therapy. Other uses: H. pylori, bacterial vaginosis, anaerobic infections, C. diff. Metallic taste is common."),

  q("Pharmacology", 3, "A client is receiving IV propofol sedation in the ICU. The nurse notes the solution appears milky-white. The nurse should:", ["Discard the solution as it appears contaminated", "This is normal — propofol is a white lipid emulsion; monitor for hypertriglyceridemia and signs of infection", "Dilute the solution until it is clear", "Add normal saline to the bag"], 1, "Propofol (Diprivan) is formulated as a white lipid emulsion (soybean oil, glycerol, egg lecithin). The milky appearance is NORMAL. Because it is a lipid, it: provides 1.1 kcal/mL (count as caloric intake), supports bacterial growth (change tubing every 6-12 hours), and can cause hypertriglyceridemia (check levels every 24-48 hours). Options A, C, and D misinterpret the normal appearance.", "Sedation", "Propofol Characteristics", ["pharmacology", "propofol", "lipid-emulsion", "ICU"], "Propofol: white lipid emulsion (egg lecithin — caution with egg allergy). Change tubing q6-12h (bacterial growth medium). Count calories. Check triglycerides q24-48h. Green urine is a harmless side effect."),

  q("Pharmacology", 3, "A client is prescribed erythromycin ophthalmic ointment for a newborn. The nurse should explain:", ["This is optional and can be refused without consequences", "This is administered prophylactically to prevent ophthalmia neonatorum (gonorrheal or chlamydial eye infection acquired during passage through the birth canal)", "This treats existing eye infections in the newborn", "This is a vitamin supplement for the eyes"], 1, "Erythromycin 0.5% ophthalmic ointment is administered to all newborns within 1 hour of birth as prophylaxis against ophthalmia neonatorum — eye infection caused by Neisseria gonorrhoeae or Chlamydia trachomatis from the birth canal. Untreated, this can cause blindness. Apply a thin ribbon in each lower conjunctival sac. Do NOT irrigate eyes after application. While parents can refuse, they should be educated about the risks. Option C — it is prophylactic. Option D is incorrect.", "Neonatal Medications", "Ophthalmia Neonatorum Prophylaxis", ["pharmacology", "erythromycin", "neonatal", "prophylaxis"], "Newborn eye prophylaxis: erythromycin ointment within 1 hour of birth. Prevents gonococcal and chlamydial ophthalmia neonatorum. Apply to both eyes. Do not irrigate. Also give: vitamin K IM (prevents hemorrhagic disease) and hepatitis B vaccine."),

  q("Pharmacology", 3, "A client with COPD exacerbation is started on systemic corticosteroids (prednisone 40 mg/day). The nurse should explain:", ["This will be lifelong therapy", "Short courses (5-7 days) reduce airway inflammation and speed recovery; blood glucose may increase during treatment", "Stop the medication after 2 days if feeling better", "No monitoring is needed for a short course"], 1, "Systemic corticosteroids for COPD exacerbation: short courses (5-7 days) reduce inflammation, speed recovery, and improve outcomes. No taper needed for courses ≤7 days. Monitor blood glucose (steroid-induced hyperglycemia). Long-term systemic steroids are NOT recommended for COPD maintenance. Option A overstates duration. Option C risks incomplete treatment. Option D ignores glucose monitoring need.", "COPD Medications", "Short-Course Steroids", ["pharmacology", "prednisone", "COPD-exacerbation", "corticosteroid"], "COPD exacerbation steroids: prednisone 40 mg x 5-7 days (GOLD guidelines). No taper needed for ≤7 days. Monitor glucose. Reduces treatment failure and shortens recovery. Not for maintenance therapy (ICS + LABA/LAMA for maintenance)."),

  q("Pharmacology", 2, "A client is prescribed an iron infusion (IV iron sucrose). The nurse should:", ["Administer as a rapid IV push", "Administer slowly with a test dose first, monitor for anaphylaxis, and observe for 30 minutes after completion", "Mix with other medications in the same bag", "Give intramuscularly for convenience"], 1, "IV iron administration: administer test dose first (25 mg over 15 minutes), observe for 15-30 minutes for anaphylactic reactions, then administer the remainder slowly per protocol. Have emergency equipment available (epinephrine, airway equipment). Common reactions: hypotension, nausea, and injection site reactions. Monitor for anaphylaxis for 30 minutes after completion. Option A risks anaphylaxis. Options C and D are incorrect.", "Iron Replacement", "IV Iron Administration", ["pharmacology", "IV-iron", "anemia", "anaphylaxis"], "IV iron: test dose required, monitor 30 min post-infusion. Have epinephrine and resuscitation equipment at bedside. Common reactions: hypotension (slow rate), headache, muscle pain. Iron dextran has highest anaphylaxis risk. Iron sucrose/ferric carboxymaltose: lower risk."),

  q("Pharmacology", 3, "A client is prescribed linagliptin (Tradjenta) for type 2 diabetes. The nurse should explain this is a:", ["Sulfonylurea", "DPP-4 inhibitor (gliptin) that enhances incretin hormones to improve glucose-dependent insulin secretion", "Insulin sensitizer", "SGLT2 inhibitor"], 1, "DPP-4 inhibitors (sitagliptin, saxagliptin, linagliptin, alogliptin) prevent the breakdown of incretin hormones (GLP-1 and GIP), which stimulate insulin secretion and suppress glucagon in a glucose-dependent manner. Benefits: low hypoglycemia risk, weight-neutral, once-daily dosing. Linagliptin is unique — no renal dose adjustment needed. Side effects: nasopharyngitis, headache, rare pancreatitis. Options A, C, and D are different drug classes.", "Oral Hypoglycemics", "DPP-4 Inhibitors", ["pharmacology", "DPP-4-inhibitor", "linagliptin", "diabetes"], "DPP-4 inhibitors (gliptins): glucose-dependent insulin secretion (low hypo risk), weight neutral. Linagliptin: no renal adjustment. Monitor for pancreatitis (rare). Less potent glucose lowering than GLP-1 RAs but better tolerated."),

  q("Pharmacology", 3, "A client is receiving a continuous insulin infusion in the ICU. The nurse should use which type of insulin?", ["NPH insulin", "Regular insulin — the only insulin that can be administered intravenously", "Insulin glargine", "Insulin lispro"], 1, "Regular insulin is the ONLY insulin approved for IV administration. It has a rapid onset when given IV (5-15 minutes, peak 15-30 minutes) making it ideal for continuous infusions for DKA, HHS, and perioperative glucose management. NPH and glargine are suspensions/solutions that cannot be given IV. While rapid-acting insulins (lispro, aspart) have been used IV off-label, regular insulin remains the standard. Options A, C, and D are not standard IV insulins.", "Insulin", "IV Insulin Administration", ["pharmacology", "regular-insulin", "IV-insulin", "critical-care"], "IV insulin: regular insulin only. Onset IV: 5-15 min. Typical protocol: 0.1 units/kg/hr for DKA. Monitor BG hourly. When BG reaches 200-250: add dextrose to IVF and reduce insulin rate. Transition to SC insulin with overlap before stopping IV."),
];

async function main() {
  let inserted = 0;
  const batchSize = 50;
  for (let i = 0; i < QS.length; i += batchSize) {
    const batch = QS.slice(i, i + batchSize);
    const values: string[] = [];
    const params: any[] = [];
    let idx = 1;
    for (const item of batch) {
      values.push(`($${idx},$${idx+1},$${idx+2},$${idx+3},$${idx+4},$${idx+5}::jsonb,$${idx+6}::jsonb,$${idx+7},$${idx+8}::integer,$${idx+9},$${idx+10},$${idx+11},$${idx+12},$${idx+13},$${idx+14}::text[],$${idx+15})`);
      params.push(
        item.tier, item.exam, "multiple_choice", "published",
        item.stem, JSON.stringify(item.options), JSON.stringify([item.correct]),
        item.rationale, item.diff, item.bs, "BOTH", hash(item.stem),
        item.topic, item.subtopic, "{" + item.tags.join(",") + "}", item.clinicalPearl
      );
      idx += 16;
    }
    const sql = `INSERT INTO exam_questions (tier, exam, question_type, status, stem, options, correct_answer, rationale, difficulty, body_system, region_scope, stem_hash, topic, subtopic, tags, clinical_pearl)
                 SELECT v.* FROM (VALUES ${values.join(",")}) AS v(tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,body_system,region_scope,stem_hash,topic,subtopic,tags,clinical_pearl)
                 WHERE NOT EXISTS (SELECT 1 FROM exam_questions e WHERE e.stem_hash = v.stem_hash)`;
    const result = await pool.query(sql, params);
    inserted += result.rowCount || 0;
    console.log(`[RN-MedSurg-Pharm-B5] Batch ${Math.floor(i/batchSize)+1}: inserted ${result.rowCount || 0} questions`);
  }
  console.log(`\n[RN-MedSurg-Pharm-B5] Total inserted: ${inserted}/${QS.length}`);
  const counts = await pool.query(`SELECT tier, count(*) as cnt FROM exam_questions WHERE status='published' GROUP BY tier ORDER BY tier`);
  counts.rows.forEach((r: any) => console.log(`  ${r.tier}: ${r.cnt}`));

  const bodySys = await pool.query(`SELECT body_system, count(*) as cnt FROM exam_questions WHERE tier='rn' AND status='published' GROUP BY body_system ORDER BY cnt DESC LIMIT 30`);
  console.log(`\nRN Body System Distribution:`);
  bodySys.rows.forEach((r: any) => console.log(`  ${r.body_system || '(null)'}: ${r.cnt}`));

  await pool.end();
}

main().catch(e => { console.error(e); process.exit(1); });
