import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

interface SEO {
  pageType: string; exam: string; title: string; slug: string;
  metaTitle: string; metaDescription: string; contentHtml: string;
  faqJson: { q: string; a: string }[];
}

const SEO_PAGES: SEO[] = [
  { pageType: "exam-prep", exam: "arrt", title: "ARRT Radiography Exam Prep: Complete Study Guide 2025", slug: "arrt-radiography-exam-prep-study-guide", metaTitle: "ARRT Radiography Exam Prep | Free Practice Questions & Study Guide", metaDescription: "Prepare for the ARRT radiography certification exam with 1200+ practice questions, flashcards, positioning drills, and case studies. Pass on your first attempt.", contentHtml: "<h1>ARRT Radiography Exam Preparation</h1><p>The American Registry of Radiologic Technologists (ARRT) certification exam for radiography covers five content domains. Our comprehensive study platform includes practice questions, flashcards, positioning drills, and clinical case studies aligned with the current ARRT exam blueprint.</p>", faqJson: [{ q: "How many questions are on the ARRT radiography exam?", a: "The ARRT radiography exam contains 200 multiple-choice questions, with 175 scored and 25 pilot (unscored) questions." }, { q: "What is the passing score for the ARRT exam?", a: "The ARRT uses a scaled scoring system. A scaled score of 75 or higher is required to pass." }] },
  { pageType: "topic", exam: "arrt", title: "ARRT Patient Care Domain: Complete Review", slug: "arrt-patient-care-domain-review", metaTitle: "ARRT Patient Care & Education | Practice Questions & Study Notes", metaDescription: "Master the ARRT Patient Care domain with practice questions on vital signs, contrast media, infection control, patient assessment, and medical ethics.", contentHtml: "<h1>ARRT Patient Care & Education Domain</h1><p>The Patient Care domain covers approximately 18-22% of the ARRT exam. Topics include patient interactions, vital signs assessment, contrast media administration and reactions, infection control, and medical-legal considerations.</p>", faqJson: [{ q: "What percentage of the ARRT exam is Patient Care?", a: "Patient Care & Education comprises approximately 18-22% of the ARRT radiography exam." }, { q: "What vital signs should radiographers monitor?", a: "Radiographers should monitor heart rate (60-100 bpm), blood pressure (~120/80 mmHg), respiratory rate (12-20/min), temperature, and oxygen saturation (SpO2 95-100%)." }] },
  { pageType: "topic", exam: "arrt", title: "ARRT Radiation Safety Domain: Complete Review", slug: "arrt-radiation-safety-domain-review", metaTitle: "ARRT Radiation Safety | ALARA, Dose Limits & Protection Principles", metaDescription: "Study radiation safety for the ARRT exam: ALARA principle, NCRP dose limits, radiation biology, personnel dosimetry, and radiation protection methods.", contentHtml: "<h1>ARRT Radiation Safety Domain</h1><p>Radiation Safety covers approximately 21-27% of the ARRT exam. Master the three cardinal principles (time, distance, shielding), NCRP dose limits, radiation biology, and dose optimization techniques.</p>", faqJson: [{ q: "What is the annual occupational dose limit?", a: "The NCRP recommends an annual occupational whole-body dose limit of 50 mSv (5 rem)." }, { q: "What does ALARA stand for?", a: "ALARA stands for As Low As Reasonably Achievable — the guiding principle for radiation protection." }] },
  { pageType: "topic", exam: "arrt", title: "ARRT Image Production Domain: Complete Review", slug: "arrt-image-production-domain-review", metaTitle: "ARRT Image Production | Technical Factors, Digital Imaging & Image Quality", metaDescription: "Master image production for the ARRT exam: mAs, kVp, exposure indicators, digital imaging (CR/DR), grids, AEC, and image quality factors.", contentHtml: "<h1>ARRT Image Production Domain</h1><p>Image Production covers approximately 25-30% of the ARRT exam — the largest domain. Topics include technical factors (mAs, kVp), digital imaging systems (CR, DR), image quality parameters, grids, AEC operation, and digital image processing.</p>", faqJson: [{ q: "What is the primary controlling factor for density?", a: "mAs (milliampere-seconds) is the primary controlling factor for radiographic density/brightness." }, { q: "What is the primary controlling factor for contrast?", a: "kVp (kilovoltage peak) is the primary controlling factor for radiographic contrast." }] },
  { pageType: "topic", exam: "arrt", title: "ARRT Procedures Domain: Complete Review", slug: "arrt-procedures-domain-review", metaTitle: "ARRT Procedures | Positioning, Projections & Radiographic Anatomy", metaDescription: "Study radiographic procedures for the ARRT exam: positioning for all body parts, CR angles, evaluation criteria, and special projections.", contentHtml: "<h1>ARRT Procedures Domain</h1><p>The Procedures domain covers approximately 17-21% of the ARRT exam. It includes positioning for all body regions, central ray angulation, evaluation criteria, special projections, and contrast studies.</p>", faqJson: [{ q: "What is the standard SID for chest radiography?", a: "The standard SID for erect PA chest radiography is 72 inches (180 cm) to minimize cardiac magnification." }, { q: "How many posterior ribs indicate adequate chest inspiration?", a: "A minimum of 10 posterior ribs visible above the diaphragm indicates adequate inspiration." }] },
  { pageType: "topic", exam: "arrt", title: "ARRT Equipment Operation & QC Domain: Complete Review", slug: "arrt-equipment-operation-qc-domain-review", metaTitle: "ARRT Equipment Operation & QC | X-ray Tube, Generators & Quality Control", metaDescription: "Study equipment operation and quality control for the ARRT exam: X-ray tube components, generators, fluoroscopy, digital detectors, and QC testing.", contentHtml: "<h1>ARRT Equipment Operation & Quality Control Domain</h1><p>Equipment Operation & QC covers approximately 12-16% of the ARRT exam. Topics include X-ray tube construction and operation, generators, fluoroscopy systems, digital detectors, and quality control testing procedures.</p>", faqJson: [{ q: "What is the kVp accuracy tolerance?", a: "kVp accuracy must be within ±5% of the set value." }, { q: "What is the collimator alignment tolerance?", a: "The light field must agree with the X-ray field within ±2% of the SID." }] },
  { pageType: "positioning", exam: "arrt", title: "Radiographic Positioning Guide: PA Chest X-ray", slug: "positioning-guide-pa-chest-xray", metaTitle: "PA Chest X-ray Positioning | Step-by-Step Guide for Radiographers", metaDescription: "Learn proper PA chest radiograph positioning: patient setup, SID, kVp, CR direction, evaluation criteria, and common errors to avoid.", contentHtml: "<h1>PA Chest Radiograph Positioning Guide</h1><p>The PA chest is the most commonly performed radiographic examination. Proper technique ensures diagnostic quality while minimizing patient dose.</p>", faqJson: [{ q: "Why is PA preferred over AP for chest X-rays?", a: "PA reduces cardiac magnification because the heart is closer to the image receptor, and it reduces dose to anterior radiosensitive organs (breast, thyroid)." }] },
  { pageType: "positioning", exam: "arrt", title: "Radiographic Positioning Guide: Lateral Cervical Spine", slug: "positioning-guide-lateral-cervical-spine", metaTitle: "Lateral C-Spine Positioning | Trauma & Routine Cervical Spine X-ray", metaDescription: "Master lateral cervical spine positioning for trauma and routine exams. Learn proper SID, shoulder depression, and C7-T1 visualization techniques.", contentHtml: "<h1>Lateral Cervical Spine Positioning Guide</h1><p>The lateral cervical spine is critical in trauma and routine evaluation. All seven vertebrae plus the C7-T1 junction must be demonstrated.</p>", faqJson: [{ q: "Why is 72-inch SID used for lateral cervical spine?", a: "The increased SID compensates for the large OID (distance from spine to film) in lateral position, reducing magnification." }] },
  { pageType: "positioning", exam: "arrt", title: "AP Pelvis Positioning Guide with Hip Fracture Considerations", slug: "positioning-guide-ap-pelvis-hip-fracture", metaTitle: "AP Pelvis X-ray | Internal Rotation & Hip Fracture Protocol", metaDescription: "Learn AP pelvis positioning including 15-20° internal leg rotation, femoral neck visualization, and modifications for suspected hip fractures.", contentHtml: "<h1>AP Pelvis Positioning Guide</h1><p>The AP pelvis demonstrates both hip joints, femoral necks, and pelvic structures. Proper internal rotation is essential for femoral neck evaluation.</p>", faqJson: [{ q: "Why do we internally rotate the legs for AP pelvis?", a: "15-20° internal rotation places the femoral necks parallel to the image receptor, demonstrating them in full length without foreshortening." }] },
  { pageType: "study-guide", exam: "arrt", title: "Radiation Biology for Radiographers: ARRT Exam Review", slug: "radiation-biology-radiographers-arrt-review", metaTitle: "Radiation Biology Review | Cell Sensitivity, Effects & ARRT Exam Prep", metaDescription: "Comprehensive radiation biology review for the ARRT exam: Law of Bergonié and Tribondeau, stochastic vs deterministic effects, LET, OER, and cell radiosensitivity.", contentHtml: "<h1>Radiation Biology Review for the ARRT Exam</h1><p>Understanding radiation biology is essential for radiation safety practice and the ARRT exam. Key concepts include cell sensitivity, types of radiation effects, and the biological response to ionizing radiation.</p>", faqJson: [{ q: "What are the most radiosensitive cells?", a: "Lymphocytes are the most radiosensitive cells — an exception to the Law of Bergonié and Tribondeau, as they are mature but highly sensitive." }] },
  { pageType: "study-guide", exam: "arrt", title: "Digital Imaging for Radiographers: CR vs DR Systems", slug: "digital-imaging-cr-vs-dr-systems-arrt", metaTitle: "CR vs DR Imaging Systems | Digital Radiography Comparison for ARRT", metaDescription: "Compare computed radiography (CR) and digital radiography (DR) systems: PSP plates, flat panel detectors, DQE, exposure indicators, and image processing.", contentHtml: "<h1>Digital Imaging: CR vs DR Systems</h1><p>Understanding the differences between CR and DR systems is essential for modern radiographic practice and the ARRT exam.</p>", faqJson: [{ q: "What is the main difference between CR and DR?", a: "CR uses removable photostimulable phosphor (PSP) plates in cassettes, while DR uses integrated flat panel detectors that provide immediate image capture." }] },
  { pageType: "study-guide", exam: "arrt", title: "Grid Selection and Use in Radiography", slug: "grid-selection-use-radiography-arrt", metaTitle: "Radiographic Grids | Selection, Grid Ratio, Cutoff & ARRT Review", metaDescription: "Master grid selection and use: grid ratio, frequency, focused vs parallel, grid conversion factors, grid cutoff patterns, and common errors.", contentHtml: "<h1>Grid Selection and Use in Radiography</h1><p>Grids are essential for scatter cleanup in radiographic imaging. Understanding grid construction, selection criteria, and common errors is critical for the ARRT exam.</p>", faqJson: [{ q: "When should a grid be used?", a: "Grids are typically used when the body part exceeds 10 cm in thickness and/or kVp exceeds 60-70." }] },
  { pageType: "study-guide", exam: "arrt", title: "Contrast Media in Radiology: Types, Reactions, and Safety", slug: "contrast-media-radiology-types-reactions-safety", metaTitle: "Contrast Media Guide | Iodinated, Barium & Reaction Management for ARRT", metaDescription: "Comprehensive guide to contrast media: iodinated agents (HOCM, LOCM, IOCM), barium sulfate, contrast reactions classification, treatment protocols, and patient screening.", contentHtml: "<h1>Contrast Media in Radiology</h1><p>Understanding contrast media types, indications, contraindications, and reaction management is essential for patient safety and the ARRT exam.</p>", faqJson: [{ q: "When is barium sulfate contraindicated?", a: "Barium sulfate is contraindicated when bowel perforation is suspected because leakage into the peritoneal cavity causes severe chemical peritonitis." }] },
  { pageType: "study-guide", exam: "arrt", title: "Exposure Indicators in Digital Radiography", slug: "exposure-indicators-digital-radiography-arrt", metaTitle: "Exposure Indicators | EI, S-Number, Deviation Index for ARRT Exam", metaDescription: "Understand exposure indicator systems across vendors (Carestream, Fuji, Siemens), the standardized Deviation Index, dose creep prevention, and ALARA compliance.", contentHtml: "<h1>Exposure Indicators in Digital Radiography</h1><p>Exposure indicators provide feedback on the radiation reaching the digital detector. Understanding vendor-specific systems and the standardized Deviation Index is crucial for dose optimization.</p>", faqJson: [{ q: "What does a high Fuji S-number indicate?", a: "A high S-number on Fuji CR systems indicates underexposure (too few photons reached the plate). The S-number is inverse to exposure." }] },
  { pageType: "study-guide", exam: "arrt", title: "X-ray Tube Construction and Operation", slug: "xray-tube-construction-operation-arrt", metaTitle: "X-ray Tube Guide | Cathode, Anode, Heat Management for ARRT", metaDescription: "Study X-ray tube construction: cathode filament, focusing cup, rotating anode, line-focus principle, heat unit calculations, and tube failure prevention.", contentHtml: "<h1>X-ray Tube Construction and Operation</h1><p>The X-ray tube is the heart of the radiographic system. Understanding its components and operation is essential for equipment care and the ARRT exam.</p>", faqJson: [{ q: "Why does the anode rotate?", a: "The rotating anode distributes heat over a larger area (focal track), allowing higher tube loading without target damage." }] },
  { pageType: "positioning", exam: "arrt", title: "Skull Radiography: Caldwell, Towne, Waters, and SMV Projections", slug: "skull-radiography-caldwell-towne-waters-smv", metaTitle: "Skull X-ray Positioning | Caldwell, Towne, Waters & SMV for ARRT", metaDescription: "Master skull radiography projections: Caldwell (15° caudad), Towne (30° caudad), Waters (37° OML), and SMV positioning with evaluation criteria.", contentHtml: "<h1>Skull Radiography Projections</h1><p>Skull radiography requires precise positioning using specific positioning lines and central ray angles. Each projection demonstrates specific anatomy.</p>", faqJson: [{ q: "What is the CR angle for the Caldwell projection?", a: "The Caldwell projection uses a 15-degree caudad CR angle, projecting petrous ridges into the lower third of the orbits." }] },
  { pageType: "positioning", exam: "arrt", title: "Shoulder Positioning: AP, Y-View, Grashey, and Axillary Projections", slug: "shoulder-positioning-ap-yview-grashey-axillary", metaTitle: "Shoulder X-ray Positioning | AP, Scapular Y, Grashey for ARRT Exam", metaDescription: "Learn shoulder radiography: AP with internal/external rotation, scapular Y-view for dislocations, Grashey for glenohumeral joint, and axillary projections.", contentHtml: "<h1>Shoulder Radiography Positioning Guide</h1><p>Shoulder radiography includes multiple projections to evaluate the glenohumeral joint, rotator cuff, and surrounding structures.</p>", faqJson: [{ q: "Which view is best for shoulder dislocation?", a: "The scapular Y-view (lateral scapula) is the best view for determining anterior vs posterior shoulder dislocation." }] },
  { pageType: "positioning", exam: "arrt", title: "Lumbar Spine Positioning: AP, Lateral, Oblique, and L5-S1 Spot", slug: "lumbar-spine-positioning-ap-lateral-oblique-l5s1", metaTitle: "Lumbar Spine X-ray | AP, Lateral, Oblique Scotty Dog for ARRT", metaDescription: "Master lumbar spine positioning: AP with flexed knees, lateral with waist support, 45° oblique for scotty dog/zygapophyseal joints, and L5-S1 spot lateral.", contentHtml: "<h1>Lumbar Spine Positioning Guide</h1><p>The lumbar spine series typically includes AP, lateral, obliques, and an L5-S1 lateral spot. Proper positioning is essential for disc space and facet joint evaluation.</p>", faqJson: [{ q: "What does the scotty dog represent on oblique lumbar spine?", a: "The scotty dog is an anatomical landmark: eye=pedicle, nose=transverse process, ear=superior articular process, front leg=inferior articular process, neck=pars interarticularis." }] },
  { pageType: "study-guide", exam: "arrt", title: "AEC (Automatic Exposure Control) for Radiographers", slug: "automatic-exposure-control-aec-radiographers-arrt", metaTitle: "AEC Guide | Chamber Selection, Density Controls & Troubleshooting", metaDescription: "Master AEC operation for the ARRT exam: ionization chamber selection for chest, abdomen, and spine, density controls, backup timer, and common AEC errors.", contentHtml: "<h1>Automatic Exposure Control (AEC) for Radiographers</h1><p>AEC systems automatically terminate the X-ray exposure when a predetermined amount of radiation has been detected. Understanding proper chamber selection and troubleshooting is essential.</p>", faqJson: [{ q: "Which AEC chambers for PA chest?", a: "Both lateral (outside) chambers should be selected for PA chest to measure exposure through the lung fields." }] },
  { pageType: "topic", exam: "arrt", title: "Infection Control for Radiologic Technologists", slug: "infection-control-radiologic-technologists-arrt", metaTitle: "Infection Control in Radiology | Standard Precautions & PPE for ARRT", metaDescription: "Study infection control for the ARRT exam: chain of infection, Standard Precautions, transmission-based precautions, hand hygiene, and PPE donning/doffing.", contentHtml: "<h1>Infection Control for Radiologic Technologists</h1><p>Infection control is a critical component of patient care and the ARRT exam. Understanding precautions, proper hand hygiene, and PPE use protects both patients and healthcare workers.</p>", faqJson: [{ q: "What is the most effective method of preventing infection?", a: "Proper hand hygiene is the single most effective method for preventing the spread of infection in healthcare settings." }] },
  { pageType: "study-guide", exam: "arrt", title: "Fluoroscopy Radiation Safety and Dose Reduction", slug: "fluoroscopy-radiation-safety-dose-reduction-arrt", metaTitle: "Fluoroscopy Safety | Dose Limits, Pulsed Fluoro & Protection for ARRT", metaDescription: "Learn fluoroscopy radiation safety: maximum exposure rates, minimum SSD, 5-minute timer, pulsed fluoroscopy, magnification mode dose increases, and operator positioning.", contentHtml: "<h1>Fluoroscopy Radiation Safety</h1><p>Fluoroscopy provides the highest radiation exposure in diagnostic radiology. Understanding safety measures and dose reduction techniques is essential for patient and operator protection.</p>", faqJson: [{ q: "What is the maximum fluoroscopy tabletop exposure rate?", a: "Standard mode: 10 R/min. High-level control: 20 R/min. These limits are enforced by regulatory agencies." }] },
  { pageType: "positioning", exam: "arrt", title: "Abdomen Radiography: KUB, Erect, and Decubitus Positioning", slug: "abdomen-radiography-kub-erect-decubitus-positioning", metaTitle: "Abdomen X-ray Positioning | KUB, Erect & Decubitus for ARRT Exam", metaDescription: "Master abdomen radiography: supine KUB positioning, erect abdomen for free air and fluid levels, and left lateral decubitus technique for pneumoperitoneum.", contentHtml: "<h1>Abdomen Radiography Positioning Guide</h1><p>The acute abdomen series is a fundamental radiographic examination for evaluating bowel obstruction, perforation, and other acute abdominal conditions.</p>", faqJson: [{ q: "Why must the patient be erect for 5-10 minutes?", a: "This allows free intraperitoneal air to rise to the highest point under the diaphragm, making it visible on the erect image." }] },
  { pageType: "study-guide", exam: "arrt", title: "Pediatric Radiography: Technique Modifications and Considerations", slug: "pediatric-radiography-technique-modifications-arrt", metaTitle: "Pediatric Radiography Guide | Immobilization & Dose Reduction for ARRT", metaDescription: "Learn pediatric radiography modifications: immobilization techniques, dose reduction strategies, technique adjustments, and age-appropriate communication.", contentHtml: "<h1>Pediatric Radiography</h1><p>Pediatric patients require special considerations including immobilization, technique modification, dose reduction, and age-appropriate communication and patient care.</p>", faqJson: [{ q: "Why is dose reduction especially important in pediatrics?", a: "Children are more radiosensitive than adults, have more rapidly dividing cells, and have a longer lifespan for potential effects to manifest." }] },
  { pageType: "study-guide", exam: "arrt", title: "Image Quality Factors: Density, Contrast, Detail, and Distortion", slug: "image-quality-factors-density-contrast-detail-distortion", metaTitle: "Image Quality in Radiography | Density, Contrast & Resolution for ARRT", metaDescription: "Master the four image quality factors for the ARRT exam: density (mAs), contrast (kVp), recorded detail (focal spot, SID, OID), and distortion (magnification, shape).", contentHtml: "<h1>Image Quality Factors in Radiography</h1><p>Understanding the four fundamental image quality factors and their controlling variables is essential for producing diagnostic radiographs and passing the ARRT exam.</p>", faqJson: [{ q: "What are the four image quality factors?", a: "The four factors are: density/brightness (controlled by mAs), contrast (controlled by kVp), recorded detail/spatial resolution (focal spot, SID, OID), and distortion (magnification and shape)." }] },
  { pageType: "topic", exam: "arrt", title: "ARRT Exam Day Tips: What to Expect and How to Prepare", slug: "arrt-exam-day-tips-preparation-guide", metaTitle: "ARRT Exam Day Tips | Registration, Format & Test-Taking Strategies", metaDescription: "Prepare for ARRT exam day: what to bring, exam format (200 questions, 3.5 hours), test-taking strategies, time management, and common pitfalls to avoid.", contentHtml: "<h1>ARRT Exam Day: What to Expect</h1><p>The ARRT radiography certification exam is a computer-based test administered at Pearson VUE testing centers. Understanding the format and having a test-taking strategy can improve your performance.</p>", faqJson: [{ q: "How long is the ARRT radiography exam?", a: "You have 3.5 hours (210 minutes) to complete 200 multiple-choice questions." }, { q: "Can you go back and change answers?", a: "Yes, the computer-based ARRT exam allows you to review and change answers before submitting." }] },
];

interface IB {
  assetType: string; modality: string; bodyRegion: string; projection: string;
  seoTitle: string; seoDescription: string; seoKeywords: string[];
}

const IMAGE_BRIEFS: IB[] = [
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Chest", projection: "PA Chest", seoTitle: "PA Chest X-ray - Normal Radiograph", seoDescription: "Normal PA chest radiograph demonstrating proper positioning with 10+ posterior ribs, no rotation, and adequate penetration.", seoKeywords: ["PA chest X-ray", "normal chest radiograph", "chest positioning"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Chest", projection: "Left Lateral Chest", seoTitle: "Left Lateral Chest X-ray - Normal", seoDescription: "Normal left lateral chest radiograph with superimposed posterior ribs and clear retrocardiac and retrosternal spaces.", seoKeywords: ["lateral chest X-ray", "left lateral chest", "chest radiograph"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Chest", projection: "AP Portable Chest", seoTitle: "AP Portable Chest X-ray", seoDescription: "AP portable chest radiograph demonstrating cardiac magnification and proper line/tube positioning in ICU patient.", seoKeywords: ["AP portable chest", "ICU chest X-ray", "portable radiograph"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Chest", projection: "AP Lordotic Chest", seoTitle: "AP Lordotic Chest X-ray", seoDescription: "AP lordotic chest projection showing lung apices free of clavicular superimposition.", seoKeywords: ["lordotic chest", "lung apices", "AP lordotic projection"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Chest", projection: "PA Chest Setup", seoTitle: "PA Chest Positioning Diagram", seoDescription: "Positioning diagram showing proper PA chest setup: patient orientation, SID, CR direction, and scapulae rotation.", seoKeywords: ["chest positioning", "PA chest setup", "radiography positioning"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Hand", projection: "PA Hand", seoTitle: "PA Hand X-ray - Normal", seoDescription: "Normal PA hand radiograph showing all phalanges, metacarpals, and carpal bones with proper finger separation.", seoKeywords: ["PA hand X-ray", "hand radiograph", "finger X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Hand", projection: "Oblique Hand", seoTitle: "Oblique Hand X-ray", seoDescription: "PA oblique hand radiograph at 45 degrees showing separated metacarpals.", seoKeywords: ["oblique hand X-ray", "hand oblique", "metacarpal X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Wrist", projection: "PA Wrist", seoTitle: "PA Wrist X-ray - Normal", seoDescription: "Normal PA wrist radiograph demonstrating all eight carpal bones, distal radius, and ulna.", seoKeywords: ["PA wrist X-ray", "wrist radiograph", "carpal bones"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Wrist", projection: "Scaphoid View", seoTitle: "Scaphoid View X-ray - Ulnar Deviation", seoDescription: "Scaphoid (navicular) view with ulnar deviation showing elongated scaphoid without foreshortening.", seoKeywords: ["scaphoid view", "scaphoid fracture X-ray", "ulnar deviation wrist"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Wrist", projection: "Lateral Wrist", seoTitle: "Lateral Wrist X-ray", seoDescription: "Lateral wrist radiograph with superimposed radius and ulna, showing carpal alignment.", seoKeywords: ["lateral wrist X-ray", "wrist lateral", "carpal alignment"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Elbow", projection: "AP Elbow", seoTitle: "AP Elbow X-ray - Normal", seoDescription: "Normal AP elbow radiograph with full extension, hand supinated, showing open joint space.", seoKeywords: ["AP elbow X-ray", "elbow radiograph", "elbow joint"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Elbow", projection: "Lateral Elbow", seoTitle: "Lateral Elbow X-ray with Fat Pad Assessment", seoDescription: "Lateral elbow radiograph at 90° flexion showing normal fat pad positioning and open trochlear notch.", seoKeywords: ["lateral elbow X-ray", "fat pad sign", "sail sign elbow"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "AP External Rotation", seoTitle: "AP Shoulder External Rotation X-ray", seoDescription: "AP shoulder with external rotation showing greater tubercle in lateral profile.", seoKeywords: ["AP shoulder X-ray", "external rotation shoulder", "greater tubercle"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "AP Internal Rotation", seoTitle: "AP Shoulder Internal Rotation X-ray", seoDescription: "AP shoulder with internal rotation showing lesser tubercle in medial profile.", seoKeywords: ["AP shoulder internal rotation", "lesser tubercle", "shoulder X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "Scapular Y View", seoTitle: "Scapular Y-View Shoulder X-ray", seoDescription: "Scapular Y-view showing normal humeral head centered on glenoid Y formation.", seoKeywords: ["scapular Y view", "shoulder dislocation X-ray", "Y view shoulder"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "Grashey View", seoTitle: "Grashey Shoulder X-ray - Glenohumeral Joint", seoDescription: "AP oblique (Grashey) shoulder showing open glenohumeral joint space.", seoKeywords: ["Grashey shoulder", "glenohumeral joint X-ray", "AP oblique shoulder"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Forearm", projection: "AP Forearm", seoTitle: "AP Forearm X-ray - Normal", seoDescription: "Normal AP forearm showing separated radius and ulna with both wrist and elbow joints.", seoKeywords: ["AP forearm X-ray", "forearm radiograph", "radius ulna"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Humerus", projection: "AP Humerus", seoTitle: "AP Humerus X-ray", seoDescription: "AP humerus with external rotation showing both shoulder and elbow joints.", seoKeywords: ["AP humerus X-ray", "humerus radiograph", "upper arm X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Foot", projection: "AP Foot", seoTitle: "AP (Dorsoplantar) Foot X-ray", seoDescription: "AP foot radiograph with 10° posterior angle showing open tarsometatarsal joints.", seoKeywords: ["AP foot X-ray", "foot radiograph", "metatarsal X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Foot", projection: "Oblique Foot", seoTitle: "Medial Oblique Foot X-ray", seoDescription: "Medial oblique foot showing separated 3rd-5th metatarsals and sinus tarsi.", seoKeywords: ["oblique foot X-ray", "foot oblique", "5th metatarsal"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Ankle", projection: "AP Ankle", seoTitle: "AP Ankle X-ray - Normal", seoDescription: "Normal AP ankle radiograph with dorsiflexed foot showing tibial-fibular overlap.", seoKeywords: ["AP ankle X-ray", "ankle radiograph", "malleolus X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Ankle", projection: "Mortise View", seoTitle: "Ankle Mortise View X-ray", seoDescription: "Ankle mortise view with 15-20° internal rotation eliminating tibiofibular overlap.", seoKeywords: ["mortise view ankle", "ankle mortise X-ray", "tibiotalar joint"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Ankle", projection: "Lateral Ankle", seoTitle: "Lateral Ankle X-ray", seoDescription: "Lateral ankle showing tibiotalar joint and fibula superimposed on posterior tibia.", seoKeywords: ["lateral ankle X-ray", "ankle lateral", "talus X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Calcaneus", projection: "Axial Calcaneus", seoTitle: "Axial Calcaneus (Os Calcis) X-ray", seoDescription: "Axial calcaneus with 40° cephalad angle showing subtalar joint and calcaneal tuberosity.", seoKeywords: ["axial calcaneus X-ray", "os calcis", "calcaneus fracture X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Knee", projection: "AP Knee", seoTitle: "AP Knee X-ray - Normal", seoDescription: "Normal AP knee radiograph with 5-7° cephalad angle showing open joint space.", seoKeywords: ["AP knee X-ray", "knee radiograph", "knee joint X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Knee", projection: "Lateral Knee", seoTitle: "Lateral Knee X-ray - Normal", seoDescription: "Lateral knee at 20-30° flexion with superimposed femoral condyles and visible patella.", seoKeywords: ["lateral knee X-ray", "knee lateral", "patella X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Knee", projection: "Tunnel View", seoTitle: "Tunnel View (Intercondylar Fossa) Knee X-ray", seoDescription: "Tunnel view demonstrating open intercondylar fossa and intercondylar eminence.", seoKeywords: ["tunnel view knee", "intercondylar fossa X-ray", "Camp Coventry"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Knee", projection: "Merchant Patella", seoTitle: "Merchant (Sunrise) Patella View", seoDescription: "Tangential (Merchant) patella view showing bilateral patellofemoral alignment.", seoKeywords: ["Merchant view patella", "sunrise view knee", "patellar tracking X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Tibia/Fibula", projection: "AP Tib/Fib", seoTitle: "AP Tibia/Fibula X-ray", seoDescription: "AP tibia/fibula showing complete leg with both knee and ankle joints included.", seoKeywords: ["AP tibia fibula X-ray", "leg X-ray", "tibial fracture X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Pelvis", projection: "AP Pelvis", seoTitle: "AP Pelvis X-ray - Normal", seoDescription: "Normal AP pelvis with 15-20° internal rotation showing femoral necks without foreshortening.", seoKeywords: ["AP pelvis X-ray", "pelvis radiograph", "hip X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Hip", projection: "Frog-Leg Lateral", seoTitle: "Frog-Leg Lateral Hip X-ray", seoDescription: "Frog-leg (modified Cleaves) lateral hip showing femoral head and neck in lateral perspective.", seoKeywords: ["frog leg hip X-ray", "lateral hip", "hip radiograph"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Hip", projection: "Cross-Table Lateral", seoTitle: "Cross-Table Lateral Hip X-ray (Trauma)", seoDescription: "Cross-table lateral hip using horizontal beam for suspected hip fracture evaluation.", seoKeywords: ["cross-table lateral hip", "trauma hip X-ray", "hip fracture X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Cervical Spine", projection: "Lateral C-Spine", seoTitle: "Lateral Cervical Spine X-ray", seoDescription: "Lateral cervical spine at 72\" SID showing C1-C7 with C7-T1 junction.", seoKeywords: ["lateral cervical spine X-ray", "C-spine lateral", "neck X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Cervical Spine", projection: "Open Mouth C1-C2", seoTitle: "Open Mouth (Odontoid) View X-ray", seoDescription: "AP open mouth view demonstrating odontoid process (dens) and C1 lateral masses.", seoKeywords: ["open mouth view", "odontoid X-ray", "dens X-ray C1 C2"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Cervical Spine", projection: "AP Axial C-Spine", seoTitle: "AP Axial Cervical Spine X-ray", seoDescription: "AP axial cervical spine with 15-20° cephalad showing C3-C7 disc spaces.", seoKeywords: ["AP cervical spine", "cervical spine X-ray", "neck AP X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Cervical Spine", projection: "Oblique C-Spine", seoTitle: "Oblique Cervical Spine X-ray", seoDescription: "Oblique cervical spine showing intervertebral foramina.", seoKeywords: ["oblique cervical spine", "foramina X-ray", "cervical oblique"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Thoracic Spine", projection: "AP Thoracic", seoTitle: "AP Thoracic Spine X-ray", seoDescription: "AP thoracic spine showing T1-T12 vertebral bodies and costovertebral joints.", seoKeywords: ["AP thoracic spine", "T-spine X-ray", "thoracic vertebrae"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Thoracic Spine", projection: "Lateral Thoracic", seoTitle: "Lateral Thoracic Spine X-ray", seoDescription: "Lateral thoracic spine using breathing technique for vertebral body clarity.", seoKeywords: ["lateral thoracic spine", "T-spine lateral", "breathing technique"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "AP Lumbar", seoTitle: "AP Lumbar Spine X-ray", seoDescription: "AP lumbar spine with flexed knees showing L1-L5 disc spaces and pedicles.", seoKeywords: ["AP lumbar spine", "L-spine X-ray", "lumbar vertebrae"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "Lateral Lumbar", seoTitle: "Lateral Lumbar Spine X-ray", seoDescription: "Lateral lumbar spine with waist support showing vertebral bodies and disc spaces.", seoKeywords: ["lateral lumbar spine", "L-spine lateral", "lumbar disc space"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "Oblique Lumbar", seoTitle: "Oblique Lumbar Spine X-ray (Scotty Dog)", seoDescription: "45° oblique lumbar spine showing scotty dog appearance with visible pars interarticularis.", seoKeywords: ["oblique lumbar spine", "scotty dog X-ray", "spondylolysis X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "L5-S1 Spot", seoTitle: "L5-S1 Lateral Spot X-ray", seoDescription: "L5-S1 lateral spot with 5-8° caudad showing lumbosacral disc space.", seoKeywords: ["L5-S1 spot lateral", "lumbosacral junction", "L5 S1 X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Abdomen", projection: "KUB", seoTitle: "KUB (AP Supine Abdomen) X-ray", seoDescription: "KUB (kidneys, ureters, bladder) supine abdomen radiograph showing bowel gas pattern.", seoKeywords: ["KUB X-ray", "supine abdomen", "abdominal radiograph"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Abdomen", projection: "Erect Abdomen", seoTitle: "Erect Abdomen X-ray", seoDescription: "Erect abdomen showing air-fluid levels and diaphragm for free air detection.", seoKeywords: ["erect abdomen X-ray", "upright abdomen", "free air abdomen"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Abdomen", projection: "Left Lateral Decubitus", seoTitle: "Left Lateral Decubitus Abdomen X-ray", seoDescription: "Left lateral decubitus abdomen demonstrating free air on the right side.", seoKeywords: ["left lateral decubitus", "decubitus abdomen", "pneumoperitoneum X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Skull", projection: "Caldwell", seoTitle: "Caldwell (PA Axial) Skull X-ray", seoDescription: "Caldwell projection with 15° caudad showing frontal sinuses and petrous ridges in lower 1/3 of orbits.", seoKeywords: ["Caldwell skull X-ray", "PA axial skull", "frontal sinuses X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Skull", projection: "Towne", seoTitle: "Towne (AP Axial) Skull X-ray", seoDescription: "Towne projection with 30° caudad showing occipital bone and foramen magnum.", seoKeywords: ["Towne skull X-ray", "AP axial skull", "foramen magnum X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Facial Bones", projection: "Waters View", seoTitle: "Waters View (Parietoacanthial) X-ray", seoDescription: "Waters view showing maxillary sinuses with petrous ridges below the sinuses.", seoKeywords: ["Waters view X-ray", "maxillary sinuses", "parietoacanthial view"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Skull", projection: "SMV", seoTitle: "SMV (Submentovertex) Skull X-ray", seoDescription: "SMV projection showing base of skull, zygomatic arches, and sphenoid sinuses.", seoKeywords: ["SMV skull X-ray", "base of skull", "zygomatic arch X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Facial Bones", projection: "Lateral Facial Bones", seoTitle: "Lateral Facial Bones X-ray", seoDescription: "Lateral facial bones showing maxillary sinuses, sella turcica, and nasal bones.", seoKeywords: ["lateral facial bones", "facial bones X-ray", "nasal bones X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Ribs", projection: "AP Ribs Above Diaphragm", seoTitle: "AP Ribs Above Diaphragm X-ray", seoDescription: "AP ribs above diaphragm taken on inspiration showing upper rib cage.", seoKeywords: ["ribs X-ray", "rib fracture X-ray", "above diaphragm ribs"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Sternum", projection: "RAO Sternum", seoTitle: "RAO Sternum X-ray", seoDescription: "RAO sternum (15-20° rotation) projected over cardiac silhouette.", seoKeywords: ["sternum X-ray", "RAO sternum", "sternal fracture X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Sternum", projection: "Lateral Sternum", seoTitle: "Lateral Sternum X-ray", seoDescription: "Lateral sternum at 72\" SID showing manubrium, body, and xiphoid process.", seoKeywords: ["lateral sternum X-ray", "sternum lateral", "manubrium X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Sacrum", projection: "AP Axial Sacrum", seoTitle: "AP Axial Sacrum X-ray", seoDescription: "AP sacrum with 15° cephalad angle projecting sacrum above pubic symphysis.", seoKeywords: ["AP sacrum X-ray", "sacrum radiograph", "sacral fracture"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Coccyx", projection: "AP Axial Coccyx", seoTitle: "AP Axial Coccyx X-ray", seoDescription: "AP coccyx with 10° caudad angle projecting coccyx below pubic symphysis.", seoKeywords: ["coccyx X-ray", "AP coccyx", "tailbone X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Clavicle", projection: "AP Clavicle", seoTitle: "AP Clavicle X-ray", seoDescription: "AP clavicle showing entire clavicle from SC to AC joint.", seoKeywords: ["clavicle X-ray", "AP clavicle", "clavicle fracture X-ray"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "AC Joints", seoTitle: "AC Joint X-ray - With and Without Weights", seoDescription: "Bilateral AC joints with and without weights for separation evaluation.", seoKeywords: ["AC joint X-ray", "acromioclavicular joint", "AC separation X-ray"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Shoulder", projection: "Y-View Setup", seoTitle: "Scapular Y-View Positioning Diagram", seoDescription: "Positioning diagram for scapular Y-view showing body rotation and CR direction.", seoKeywords: ["Y-view positioning", "scapular lateral setup", "shoulder positioning diagram"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Knee", projection: "Tunnel View Setup", seoTitle: "Tunnel View Knee Positioning Diagram", seoDescription: "Positioning diagram for tunnel view (Camp-Coventry) showing knee flexion and CR angle.", seoKeywords: ["tunnel view positioning", "knee positioning", "intercondylar fossa setup"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Ankle", projection: "Mortise Setup", seoTitle: "Ankle Mortise View Positioning Diagram", seoDescription: "Positioning diagram showing 15-20° internal rotation for mortise view.", seoKeywords: ["mortise view positioning", "ankle positioning diagram", "internal rotation ankle"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Pelvis", projection: "AP Pelvis Setup", seoTitle: "AP Pelvis Positioning Diagram", seoDescription: "Positioning diagram showing 15-20° internal rotation of legs for femoral neck visualization.", seoKeywords: ["AP pelvis positioning", "pelvis setup diagram", "internal rotation legs"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Hip", projection: "Cross-Table Setup", seoTitle: "Cross-Table Lateral Hip Positioning Diagram", seoDescription: "Trauma hip positioning diagram showing horizontal beam technique with unaffected leg elevated.", seoKeywords: ["cross-table lateral hip positioning", "trauma hip setup", "horizontal beam hip"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Cervical Spine", projection: "Open Mouth Setup", seoTitle: "Open Mouth (Odontoid) Positioning Diagram", seoDescription: "Positioning diagram for open mouth view showing head position and CR direction.", seoKeywords: ["open mouth positioning", "odontoid view setup", "C1-C2 positioning"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "Oblique Setup", seoTitle: "Oblique Lumbar Spine Positioning Diagram", seoDescription: "Positioning diagram for 45° oblique lumbar spine showing scotty dog orientation.", seoKeywords: ["oblique lumbar positioning", "scotty dog setup", "L-spine oblique diagram"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Skull", projection: "Waters Setup", seoTitle: "Waters View Positioning Diagram", seoDescription: "Positioning diagram showing OML 37° angle to IR for Waters projection.", seoKeywords: ["Waters view positioning", "parietoacanthial setup", "sinus positioning diagram"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Skull", projection: "Towne Setup", seoTitle: "Towne Projection Positioning Diagram", seoDescription: "Positioning diagram showing 30° caudad CR angle for Towne AP axial skull.", seoKeywords: ["Towne positioning", "AP axial skull setup", "skull positioning diagram"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Abdomen", projection: "Left Lat Decub Setup", seoTitle: "Left Lateral Decubitus Abdomen Positioning Diagram", seoDescription: "Positioning diagram for left lateral decubitus showing horizontal beam and free air detection.", seoKeywords: ["left lateral decubitus positioning", "decubitus abdomen setup", "free air detection diagram"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "General", projection: "Motion Artifact", seoTitle: "Motion Artifact Example - Chest X-ray", seoDescription: "Example of motion artifact on chest radiograph showing generalized image blur.", seoKeywords: ["motion artifact", "blurred X-ray", "radiograph artifact"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "General", projection: "Grid Cutoff", seoTitle: "Grid Cutoff Artifact Examples", seoDescription: "Examples of grid cutoff patterns: off-center, off-level, off-focus, and upside-down grid.", seoKeywords: ["grid cutoff artifact", "upside down grid", "grid artifact X-ray"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "General", projection: "Quantum Mottle", seoTitle: "Quantum Mottle (Noise) Artifact Example", seoDescription: "Example of quantum mottle showing grainy, salt-and-pepper appearance from insufficient mAs.", seoKeywords: ["quantum mottle", "image noise", "underexposure artifact"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "General", projection: "Ghost Image", seoTitle: "Ghost Image Artifact on CR", seoDescription: "Ghost image artifact from incomplete erasure of CR imaging plate.", seoKeywords: ["ghost image artifact", "CR artifact", "incomplete erasure"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "General", projection: "Static Artifact", seoTitle: "Static Discharge Artifact on CR", seoDescription: "Static discharge (tree-like branching) artifact on CR imaging plate.", seoKeywords: ["static artifact", "CR static discharge", "branching artifact"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "Chest", projection: "Rotation Artifact", seoTitle: "Rotated PA Chest X-ray Example", seoDescription: "Example of patient rotation on PA chest showing unequal clavicle-spine distances.", seoKeywords: ["rotated chest X-ray", "chest rotation artifact", "positioning error"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "Chest", projection: "Inadequate Inspiration", seoTitle: "Inadequate Inspiration Chest X-ray", seoDescription: "Example showing only 6-7 posterior ribs indicating inadequate inspiration with apparent cardiomegaly.", seoKeywords: ["inadequate inspiration", "expiration chest X-ray", "short inspiration artifact"] },
  { assetType: "artifact_example", modality: "Radiography", bodyRegion: "General", projection: "Foreign Body Artifact", seoTitle: "Foreign Body Artifact on Radiograph", seoDescription: "Examples of external artifacts: jewelry, clothing snaps, and medical devices in X-ray field.", seoKeywords: ["foreign body artifact", "jewelry artifact", "external artifact X-ray"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "X-ray Tube Diagram", seoTitle: "X-ray Tube Components Diagram", seoDescription: "Labeled diagram of X-ray tube showing cathode, anode, filament, focusing cup, and tube housing.", seoKeywords: ["X-ray tube diagram", "tube components", "cathode anode diagram"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Anode Heel Effect", seoTitle: "Anode Heel Effect Diagram", seoDescription: "Diagram showing intensity variation across the X-ray beam due to anode heel effect.", seoKeywords: ["anode heel effect", "beam intensity diagram", "cathode anode intensity"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Grid Construction", seoTitle: "Grid Construction and Function Diagram", seoDescription: "Diagram showing grid construction with lead strips and interspaces, and scatter absorption.", seoKeywords: ["grid diagram", "grid construction", "scatter absorption grid"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Grid Cutoff Patterns", seoTitle: "Grid Cutoff Error Patterns Diagram", seoDescription: "Diagrams showing off-center, off-level, off-focus, and upside-down grid cutoff patterns.", seoKeywords: ["grid cutoff patterns", "grid errors diagram", "grid positioning errors"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Inverse Square Law", seoTitle: "Inverse Square Law Diagram", seoDescription: "Visual representation of the inverse square law showing intensity changes with distance.", seoKeywords: ["inverse square law diagram", "distance intensity", "radiation intensity"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Magnification SID OID", seoTitle: "Magnification, SID, and OID Relationship Diagram", seoDescription: "Diagram showing how SID and OID affect magnification and geometric unsharpness.", seoKeywords: ["magnification diagram", "SID OID", "geometric unsharpness"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Focal Spot Size Effect", seoTitle: "Focal Spot Size and Penumbra Diagram", seoDescription: "Diagram comparing small and large focal spots and their effect on penumbra/resolution.", seoKeywords: ["focal spot diagram", "penumbra effect", "geometric blur"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "CR vs DR Workflow", seoTitle: "CR vs DR Workflow Comparison Diagram", seoDescription: "Flowchart comparing computed radiography (CR) and digital radiography (DR) imaging chains.", seoKeywords: ["CR vs DR diagram", "digital imaging workflow", "PSP plate readout"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Window Width Level", seoTitle: "Window Width and Level Controls Diagram", seoDescription: "Diagram showing the effect of window width and level on digital image display.", seoKeywords: ["window width level", "digital image display", "contrast brightness controls"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "AEC Chambers", seoTitle: "AEC Ionization Chamber Positions Diagram", seoDescription: "Diagram showing three AEC chamber positions and selection for different examinations.", seoKeywords: ["AEC chambers diagram", "ionization chamber positions", "phototimer diagram"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Radiation Units", seoTitle: "Radiation Units Conversion Chart", seoDescription: "Chart showing SI and traditional radiation units: Gy/rad, Sv/rem, C/kg/R conversions.", seoKeywords: ["radiation units chart", "Gy to rad conversion", "Sv to rem conversion"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Dose Limits Chart", seoTitle: "NCRP Dose Limits Chart", seoDescription: "Chart summarizing NCRP recommended dose limits for occupational and public exposure.", seoKeywords: ["NCRP dose limits", "occupational dose limits", "radiation dose chart"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Cell Radiosensitivity", seoTitle: "Cell Radiosensitivity Ranking Diagram", seoDescription: "Diagram ranking cell types from most to least radiosensitive (lymphocytes to nerve cells).", seoKeywords: ["cell radiosensitivity", "Bergonie Tribondeau", "radiosensitive cells"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Chain of Infection", seoTitle: "Chain of Infection Diagram", seoDescription: "Circular diagram showing the six links in the chain of infection.", seoKeywords: ["chain of infection", "infection control diagram", "infection cycle"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "Scotty Dog Anatomy", seoTitle: "Scotty Dog Anatomy Diagram (Oblique Lumbar Spine)", seoDescription: "Labeled diagram showing scotty dog anatomy: eye=pedicle, nose=transverse process, ear=SAP, leg=IAP, neck=pars.", seoKeywords: ["scotty dog diagram", "pars interarticularis", "lumbar oblique anatomy"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "Elbow", projection: "Fat Pad Signs", seoTitle: "Elbow Fat Pad Signs Diagram", seoDescription: "Diagram showing normal vs elevated anterior and posterior fat pads (sail sign) indicating occult fracture.", seoKeywords: ["fat pad sign diagram", "sail sign elbow", "occult elbow fracture"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Generator Waveforms", seoTitle: "X-ray Generator Waveform Comparison", seoDescription: "Comparison of single-phase, three-phase (6-pulse, 12-pulse), and high-frequency generator waveforms.", seoKeywords: ["generator waveforms", "voltage ripple comparison", "single phase vs three phase"] },
  { assetType: "teaching_diagram", modality: "Radiography", bodyRegion: "General", projection: "Exposure Indicator Systems", seoTitle: "Exposure Indicator Vendor Comparison Chart", seoDescription: "Comparison chart of EI systems across vendors: Carestream, Fuji, Siemens, and standardized DI.", seoKeywords: ["exposure indicator chart", "EI systems comparison", "S-number vs EI"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Chest", projection: "Pneumothorax", seoTitle: "Pneumothorax on PA Chest X-ray", seoDescription: "PA chest radiograph demonstrating right pneumothorax with visible visceral pleural line.", seoKeywords: ["pneumothorax X-ray", "collapsed lung", "pleural line"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Chest", projection: "CHF", seoTitle: "Congestive Heart Failure on Chest X-ray", seoDescription: "Chest radiograph showing cardiomegaly, bilateral pleural effusions, and pulmonary edema.", seoKeywords: ["CHF chest X-ray", "cardiomegaly", "pulmonary edema X-ray"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Wrist", projection: "Colles Fracture", seoTitle: "Colles Fracture on Wrist X-ray", seoDescription: "Lateral wrist showing classic Colles fracture with dorsal displacement of distal radius fragment.", seoKeywords: ["Colles fracture X-ray", "distal radius fracture", "wrist fracture"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Shoulder", projection: "Anterior Dislocation", seoTitle: "Anterior Shoulder Dislocation on Y-View", seoDescription: "Scapular Y-view showing humeral head displaced anterior to the glenoid Y formation.", seoKeywords: ["shoulder dislocation X-ray", "anterior dislocation", "glenohumeral dislocation"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Hip", projection: "Femoral Neck Fracture", seoTitle: "Femoral Neck Fracture on AP Pelvis", seoDescription: "AP pelvis showing subcapital femoral neck fracture with external rotation of the affected leg.", seoKeywords: ["femoral neck fracture X-ray", "hip fracture", "subcapital fracture"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Abdomen", projection: "Bowel Obstruction", seoTitle: "Small Bowel Obstruction on Abdominal X-ray", seoDescription: "Erect abdomen showing dilated small bowel loops with air-fluid levels in step-ladder pattern.", seoKeywords: ["bowel obstruction X-ray", "air fluid levels", "SBO X-ray"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Abdomen", projection: "Pneumoperitoneum", seoTitle: "Pneumoperitoneum (Free Air) on Erect Abdomen", seoDescription: "Erect abdomen showing crescentic lucency (free air) under the right hemidiaphragm.", seoKeywords: ["pneumoperitoneum X-ray", "free air abdomen", "bowel perforation X-ray"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Knee", projection: "Lipohemarthrosis", seoTitle: "Lipohemarthrosis on Cross-Table Lateral Knee", seoDescription: "Cross-table lateral knee showing fat-fluid level (lipohemarthrosis) indicating intra-articular fracture.", seoKeywords: ["lipohemarthrosis X-ray", "fat fluid level knee", "tibial plateau fracture"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Lumbar Spine", projection: "Spondylolysis", seoTitle: "Spondylolysis on Oblique Lumbar Spine", seoDescription: "Oblique lumbar spine showing 'collar' on scotty dog indicating pars interarticularis defect.", seoKeywords: ["spondylolysis X-ray", "pars defect", "scotty dog collar"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Elbow", projection: "Occult Fracture Fat Pads", seoTitle: "Occult Elbow Fracture with Fat Pad Signs", seoDescription: "Lateral elbow showing elevated anterior fat pad (sail sign) and visible posterior fat pad.", seoKeywords: ["elbow fat pad sign", "sail sign X-ray", "occult elbow fracture"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Chest", projection: "Pneumonia", seoTitle: "Right Lower Lobe Pneumonia on PA Chest", seoDescription: "PA chest showing right lower lobe consolidation with air bronchograms.", seoKeywords: ["pneumonia X-ray", "RLL consolidation", "air bronchograms"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Clavicle", projection: "AP Axial Clavicle", seoTitle: "AP Axial Clavicle X-ray with Cephalad Angle", seoDescription: "AP axial clavicle radiograph with 15-30° cephalad angle projecting clavicle above the ribs.", seoKeywords: ["clavicle X-ray", "AP axial clavicle", "cephalad angle clavicle"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Clavicle", projection: "AP Clavicle Setup", seoTitle: "AP Clavicle Positioning Diagram", seoDescription: "Positioning diagram showing AP and AP axial clavicle setup with cephalad CR angulation.", seoKeywords: ["clavicle positioning", "AP clavicle setup", "cephalad angle"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "Grashey View", seoTitle: "Grashey (AP Oblique) Shoulder X-ray", seoDescription: "Grashey view showing open glenohumeral joint space with 35-45° body oblique.", seoKeywords: ["Grashey shoulder", "glenohumeral joint X-ray", "AP oblique shoulder"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Shoulder", projection: "Axillary View", seoTitle: "Inferosuperior Axillary Shoulder X-ray", seoDescription: "Axillary view of the shoulder showing humeral head and glenoid fossa in axial projection.", seoKeywords: ["axillary shoulder X-ray", "inferosuperior shoulder", "glenoid axial"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Shoulder", projection: "Axillary Setup", seoTitle: "Axillary Shoulder Positioning Diagram", seoDescription: "Positioning diagram showing inferosuperior axillary shoulder setup with arm abduction and CR direction.", seoKeywords: ["axillary shoulder positioning", "inferosuperior setup", "shoulder axial"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Humerus", projection: "AP Humerus", seoTitle: "AP Humerus X-ray - Normal", seoDescription: "Normal AP humerus radiograph showing external rotation with both shoulder and elbow joints included.", seoKeywords: ["AP humerus X-ray", "humerus radiograph", "external rotation humerus"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Humerus", projection: "Transthoracic Lateral", seoTitle: "Transthoracic Lateral Humerus X-ray", seoDescription: "Transthoracic lateral humerus showing proximal humerus through the thorax using breathing technique.", seoKeywords: ["transthoracic lateral humerus", "trauma humerus X-ray", "proximal humerus lateral"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Sacrum", projection: "AP Sacrum", seoTitle: "AP Axial Sacrum X-ray", seoDescription: "AP sacrum with 15° cephalad angle demonstrating sacral foramina without pubic overlap.", seoKeywords: ["AP sacrum X-ray", "sacral foramina", "cephalad angle sacrum"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Coccyx", projection: "AP Coccyx", seoTitle: "AP Axial Coccyx X-ray", seoDescription: "AP coccyx with 10° caudad angle demonstrating coccyx without pubic symphysis overlap.", seoKeywords: ["AP coccyx X-ray", "caudad angle coccyx", "coccyx radiograph"] },
  { assetType: "radiograph", modality: "Radiography", bodyRegion: "Pelvis", projection: "SI Joints Oblique", seoTitle: "Oblique SI Joint X-ray", seoDescription: "Oblique SI joint radiograph showing open sacroiliac joint space with 25-30° oblique positioning.", seoKeywords: ["SI joint X-ray", "sacroiliac oblique", "SI joint space"] },
  { assetType: "positioning_diagram", modality: "Radiography", bodyRegion: "Abdomen", projection: "Decubitus Setup", seoTitle: "Left Lateral Decubitus Abdomen Setup", seoDescription: "Positioning diagram showing left lateral decubitus technique for free air detection with horizontal beam.", seoKeywords: ["decubitus abdomen positioning", "free air detection", "horizontal beam abdomen"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Hand", projection: "Boxer Fracture", seoTitle: "Boxer Fracture - 5th Metacarpal Neck", seoDescription: "Oblique hand radiograph showing fracture of the 5th metacarpal neck with volar angulation.", seoKeywords: ["boxer fracture X-ray", "5th metacarpal fracture", "hand fracture"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Wrist", projection: "Colles Fracture", seoTitle: "Colles Fracture - Dorsal Displacement", seoDescription: "Lateral wrist radiograph showing distal radius fracture with dorsal displacement (silver fork deformity).", seoKeywords: ["Colles fracture X-ray", "distal radius fracture", "silver fork deformity"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Foot", projection: "Jones Fracture", seoTitle: "Jones Fracture - 5th Metatarsal Base", seoDescription: "Oblique foot radiograph demonstrating fracture at the base of the 5th metatarsal (metadiaphyseal junction).", seoKeywords: ["Jones fracture X-ray", "5th metatarsal fracture", "foot fracture"] },
  { assetType: "clinical_image", modality: "Radiography", bodyRegion: "Chest", projection: "Pleural Effusion", seoTitle: "Pleural Effusion on PA and Lateral Chest", seoDescription: "PA and lateral chest demonstrating blunting of costophrenic angles from pleural fluid collection.", seoKeywords: ["pleural effusion X-ray", "costophrenic angle blunting", "chest fluid"] },
];

async function seed() {
  let seoInserted = 0;
  for (const s of SEO_PAGES) {
    const exists = await pool.query(`SELECT id FROM seo_pages WHERE slug = $1`, [s.slug]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO seo_pages (id, page_type, exam, language_code, title, slug, meta_title, meta_description, content_html, faq_json, is_public, is_indexable, last_updated)
         VALUES (gen_random_uuid(), $1, $2, 'en', $3, $4, $5, $6, $7, $8::jsonb, true, true, NOW())`,
        [s.pageType, s.exam, s.title, s.slug, s.metaTitle, s.metaDescription, s.contentHtml, JSON.stringify(s.faqJson)]
      );
      seoInserted++;
    }
  }
  console.log(`[SEO Pages] Inserted ${seoInserted}/${SEO_PAGES.length} USA ARRT SEO blueprints`);

  let imgInserted = 0;
  for (const ib of IMAGE_BRIEFS) {
    const exists = await pool.query(`SELECT id FROM image_assets WHERE title = $1`, [ib.seoTitle]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO image_assets (id, title, description, image_url, modality, body_part, tags, source, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1, $2, '', $3, $4, $5, $6, 'draft', NOW(), NOW())`,
        [ib.seoTitle, ib.seoDescription, ib.modality, ib.bodyRegion, ib.seoKeywords, `usa-arrt-${ib.assetType}`]
      );
      imgInserted++;
    }
  }
  console.log(`[Image Briefs] Inserted ${imgInserted}/${IMAGE_BRIEFS.length} USA ARRT image briefs`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
