import pg from "pg";
import crypto from "crypto";
const Pool = pg.Pool;
const pool = new Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });
function hash(s: string): string { return crypto.createHash("md5").update(s.toLowerCase().trim()).digest("hex"); }
function rn(e:string,b:string,d:number,s:string,o:string[],c:number,r:string) {
  return {tier:"rn",exam:e,stem:s,options:o,correct:c,rationale:r,diff:d,bs:b};
}
function np(e:string,b:string,d:number,s:string,o:string[],c:number,r:string) {
  return {tier:"np",exam:e,stem:s,options:o,correct:c,rationale:r,diff:d,bs:b};
}
function rpn(e:string,b:string,d:number,s:string,o:string[],c:number,r:string) {
  return {tier:"rpn",exam:e,stem:s,options:o,correct:c,rationale:r,diff:d,bs:b};
}

const QS = [
  // === RN (100) ===
  rn("NCLEX-RN","Cardiovascular",3,"A client with third-degree burns over 40% BSA develops myocardial depression 24-48 hours post-burn. This is caused by:",["Pre-existing cardiac disease","Circulating myocardial depressant factors released from burned tissue","Dehydration only","Electrolyte imbalance alone"],1,"Myocardial depressant factors (TNF-alpha, IL-1, IL-6) released from burned tissue directly depress cardiac contractility 24-48 hours post-burn. Combined with massive fluid shifts and decreased preload, cardiac output drops significantly, requiring careful fluid management and inotropic support."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with stable angina has a positive calcium score on coronary CT. This indicates:",["No coronary disease","Coronary artery calcification suggesting atherosclerotic plaque burden","Normal aging findings","Valvular disease"],1,"Coronary artery calcium scoring quantifies calcified atherosclerotic plaque. Higher scores correlate with greater total plaque burden and cardiovascular event risk. Score of 0 = very low risk, > 400 = high risk. Used for risk stratification in intermediate-risk patients."),
  rn("RN-CAT","Cardiovascular",4,"A client with an LVAD develops a suction event. The nurse should:",["Increase the pump speed","Decrease the pump speed and assess volume status","Turn off the LVAD immediately","Administer a fluid bolus without speed adjustment"],1,"LVAD suction events occur when the left ventricle is relatively empty (hypovolemia, RV failure, arrhythmia) and the pump pulls on the ventricular wall. Management: decrease speed, volume resuscitation, and address the underlying cause. Turning off the LVAD could be fatal."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with chronic atrial fibrillation elects to undergo catheter ablation. The nurse should teach that:",["Success rate is 100% with no complications","Success rate is approximately 70-80% and may require repeat procedures","The procedure permanently cures all cases","No recovery time is needed"],1,"AF catheter ablation (pulmonary vein isolation) success rate is 70-80% for paroxysmal AF (lower for persistent). Complications include stroke, cardiac perforation, PV stenosis, and esophageal injury. Anticoagulation continues for at least 2-3 months post-procedure."),
  rn("NCLEX-RN","Respiratory",3,"A client with chronic respiratory failure adapts to elevated PaCO2. Their respiratory drive becomes dependent on:",["High CO2 levels stimulating the chemoreceptors","Hypoxic drive (low PaO2 stimulating peripheral chemoreceptors)","Cortical brain function","Vagal nerve stimulation"],1,"Chronic CO2 retainers (COPD) develop tolerance to elevated PaCO2. The medullary chemoreceptors become insensitive to CO2. Breathing is driven by hypoxic drive (peripheral chemoreceptors responding to low PaO2). Excessive O2 may suppress this drive, causing respiratory depression."),
  rn("NCLEX-RN","Respiratory",3,"A client receiving continuous pulse oximetry has a reading of 85% on room air. The nurse should first:",["Wait and recheck in 30 minutes","Verify the sensor placement and client perfusion status before intervening","Apply high-flow oxygen immediately","Call a rapid response team"],1,"Before treating an SpO2 reading, verify accuracy: check sensor placement, perfusion (cold fingers, nail polish, edema affect readings), and correlate with clinical assessment. If confirmed, apply supplemental oxygen and further evaluate. False readings are common."),
  rn("RN-CAT","Respiratory",3,"A client with pulmonary arterial hypertension should not receive:",["Endothelin receptor antagonists","Calcium channel blockers without prior vasoreactivity testing","Prostacyclin analogues","PDE-5 inhibitors"],1,"Only about 10% of PAH patients are vasoreactive (positive response to acute vasodilator testing with inhaled NO or IV prostacyclin). Non-reactive patients given high-dose CCBs (diltiazem, nifedipine) can develop severe hemodynamic collapse. Vasoreactivity testing is mandatory."),
  rn("NCLEX-RN","Neurological",3,"A client with frontotemporal dementia differs from Alzheimer disease in that FTD primarily causes:",["Memory loss as the first symptom","Personality changes, behavioral disinhibition, and language difficulties early in the disease","Visuospatial deficits","Motor symptoms"],1,"FTD involves frontal and temporal lobe degeneration causing early personality changes, behavioral disinhibition, apathy, loss of empathy, and language deterioration. Memory is relatively preserved early. Onset typically before age 65. No disease-modifying treatment exists."),
  rn("NCLEX-RN","Neurological",3,"A client with a posterior fossa tumor presents with increased intracranial pressure. The nurse should be especially vigilant for:",["Seizures","Tonsillar herniation compressing the brainstem (life-threatening respiratory arrest)","Visual field deficits only","Motor weakness"],1,"Posterior fossa tumors risk tonsillar (downward) herniation through the foramen magnum, compressing the brainstem. This causes respiratory arrest, cardiovascular collapse, and death. Lumbar puncture is contraindicated. Emergency surgical decompression may be needed."),
  rn("NCLEX-RN","Neurological",3,"A client with transient ischemic attack (TIA) should be treated as:",["A benign condition requiring no further evaluation","A medical emergency with stroke risk of 10-15% within 90 days requiring urgent workup","An episode that will not recur","A psychiatric condition"],1,"TIA = neurological emergency. 10-15% stroke risk within 90 days (highest in first 48 hours). ABCD2 score guides risk stratification. Urgent workup: brain imaging, carotid imaging, cardiac evaluation (ECG, echo), lipid panel, and glucose. Initiate antiplatelet therapy."),
  rn("NCLEX-RN","Endocrine",3,"A client with diabetic ketoacidosis should have potassium replaced when:",["Potassium is above 5.5 mEq/L","Potassium is below 5.3 mEq/L AND urine output is adequate","Only after glucose normalizes","Potassium replacement is never needed in DKA"],1,"Despite normal/high serum K+ at DKA presentation (acidosis shifts K+ extracellularly), total body K+ is severely depleted. As insulin drives K+ intracellularly and acidosis corrects, hypokalemia develops rapidly. Replace when K+ < 5.3 and urine output is established. Check K+ every 1-2 hours."),
  rn("NCLEX-RN","Endocrine",3,"A client with primary hyperthyroidism (Graves disease) should avoid:",["All dairy products","Excessive iodine intake (iodinated contrast, amiodarone, kelp supplements)","All protein sources","Moderate exercise"],1,"Excess iodine can worsen hyperthyroidism through the Jod-Basedow phenomenon in susceptible individuals. Sources: iodinated contrast dye, amiodarone (37% iodine by weight), kelp/seaweed supplements, and some medications. This can trigger thyroid storm in severe cases."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with spontaneous bacterial peritonitis is diagnosed when ascitic fluid analysis shows:",["WBC < 100 cells/mm3","Polymorphonuclear leukocyte count >= 250 cells/mm3 in ascitic fluid","Negative bacterial culture only","Normal protein levels"],1,"SBP diagnosis: ascitic fluid PMN count >= 250 cells/mm3. Culture may be negative in up to 40% (culture-negative neutrocytic ascites still treated as SBP). Treatment: ceftriaxone or cefotaxime + IV albumin (reduces hepatorenal syndrome risk). Secondary prophylaxis with norfloxacin."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with fecal microbiota transplantation (FMT) is being treated for:",["Ulcerative colitis as first-line","Recurrent Clostridium difficile infection unresponsive to standard therapy","All GI infections","Irritable bowel syndrome"],1,"FMT restores healthy gut microbiome diversity. Indicated for recurrent C. diff (>= 3 episodes despite appropriate antibiotics). Cure rate > 85%. Administered via colonoscopy, NG tube, or capsules. FDA regulates as investigational new drug. Screen donor stool extensively."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with cirrhosis and ascites should have which daily monitoring parameter?",["Calorie count only","Abdominal girth measurement at the same level each day","Serum albumin daily","Liver biopsy weekly"],1,"Daily abdominal girth measurement (at the umbilicus, same time, same position) tracks ascites progression or resolution. Combined with daily weights and I&O monitoring, these parameters guide diuretic therapy and evaluate treatment effectiveness."),
  rn("NCLEX-RN","Pharmacology",3,"A client prescribed IV potassium chloride replacement should have the infusion:",["Through a peripheral IV at any rate","Never exceed 10 mEq/hour through a peripheral IV and always use an infusion pump","Administered by IV push for rapid correction","Mixed with dextrose-containing solutions only"],1,"IV KCl safety: peripheral max rate 10 mEq/hour (40 mEq/hour central with cardiac monitoring), always use infusion pump, never push IV (can cause fatal cardiac arrest), dilute appropriately, and monitor ECG for hyperkalemia signs (peaked T waves, widened QRS)."),
  rn("NCLEX-RN","Pharmacology",3,"Sildenafil is contraindicated in clients taking:",["Beta-blockers","Nitrates (combination can cause severe, potentially fatal hypotension)","ACE inhibitors","Statins"],1,"PDE-5 inhibitors (sildenafil, tadalafil) potentiate the hypotensive effects of nitrates (both enhance nitric oxide/cGMP pathway). Combined use can cause severe, refractory hypotension. Wait 24 hours (48 for tadalafil) between these medications."),
  rn("NCLEX-RN","Pharmacology",3,"The nurse administering IV phenytoin should use:",["D5W solution for dilution","Normal saline for dilution (phenytoin precipitates in dextrose solutions)","Lactated Ringer's solution","Any available IV solution"],1,"Phenytoin is incompatible with dextrose solutions (precipitates). Use only NS for dilution and flushing. IV rate should not exceed 50 mg/min in adults (20 mg/min in elderly). Use an in-line filter (0.22 micron). Fosphenytoin can be given in any solution and faster."),
  rn("NCLEX-RN","Mental Health",3,"A client with factitious disorder (Munchausen syndrome) differs from malingering in that the motivation is:",["Financial gain","To assume the sick role (internal psychological motivation rather than external gain)","To avoid work","To obtain medications"],1,"Factitious disorder: internal motivation to assume the sick role (psychological need to be a patient). Malingering: external motivation (financial gain, avoiding responsibilities, obtaining drugs). Both involve deliberate symptom production, but motivation differs fundamentally."),
  rn("NCLEX-RN","Mental Health",3,"A client with narcissistic personality disorder may demonstrate:",["Avoidance of social situations","Grandiosity, need for admiration, and lack of empathy","Intense fear of abandonment","Odd beliefs and magical thinking"],1,"NPD characteristics: grandiose sense of self-importance, fantasies of unlimited success, belief of being special, need for excessive admiration, sense of entitlement, exploitative relationships, lack of empathy, envy, and arrogant behaviors. Treatment is challenging; psychotherapy is primary."),
  rn("NCLEX-RN","Pediatrics",3,"A child with Henoch-Schonlein purpura should be monitored long-term for:",["Cardiac complications","Renal involvement (nephritis can develop weeks to months after initial presentation)","Neurological deficits","Hepatic dysfunction"],1,"HSP nephritis (IgA nephropathy) can develop during or up to 6 months after HSP. Monitor urinalysis and blood pressure regularly for at least 6 months. 1-5% develop chronic kidney disease. Children with severe nephritis may need immunosuppressive therapy."),
  rn("NCLEX-RN","Pediatrics",3,"A child presenting with periorbital cellulitis versus orbital cellulitis is differentiated by:",["Both conditions are identical","Orbital cellulitis involves proptosis, painful eye movement, and decreased visual acuity","Only color of the swelling","Age of the child"],1,"Orbital cellulitis (behind the orbital septum) is more dangerous than periorbital (preseptal). Differentiating features: proptosis (forward eye displacement), restricted/painful eye movements, vision changes, and fever. CT scan confirms. Requires IV antibiotics and possible surgical drainage."),
  rn("NCLEX-RN","Pediatrics",3,"An infant with biliary atresia presents with:",["Normal stool color","Jaundice persisting beyond 2 weeks, acholic (pale/clay-colored) stools, and dark urine","Projectile vomiting","Green stools"],1,"Biliary atresia: obliteration of bile ducts causing persistent conjugated hyperbilirubinemia after 2 weeks, pale/white stools (no bile pigment reaching intestine), dark urine, and hepatomegaly. Kasai procedure (portoenterostomy) must be performed before 8 weeks for best outcomes."),
  rn("NCLEX-RN","Maternal/Newborn",3,"A client with uterine rupture during labor presents with:",["Progressive cervical dilation","Sudden tearing sensation, fetal bradycardia, loss of fetal station, and cessation of contractions","Normal labor pattern","Mild abdominal discomfort"],1,"Uterine rupture signs: sudden sharp pain, cessation of contractions, regression of fetal station, fetal heart rate deceleration, maternal tachycardia and hypotension, and possible palpation of fetal parts through the abdomen. Emergency cesarean delivery is required immediately."),
  rn("NCLEX-RN","Maternal/Newborn",3,"A client at 35 weeks gestation with twin pregnancy develops twin-to-twin transfusion syndrome. The donor twin is at risk for:",["Polycythemia and cardiomegaly","Anemia, growth restriction, and oligohydramnios","Hydrops fetalis only","No complications"],1,"TTTS: unbalanced vascular anastomoses in monochorionic twins cause blood shunting from donor to recipient. Donor: anemia, hypovolemia, IUGR, oligohydramnios (stuck twin). Recipient: polycythemia, volume overload, hydrops, polyhydramnios. Laser ablation of anastomoses is definitive treatment."),
  rn("NCLEX-RN","Renal",3,"A client with rapidly progressive glomerulonephritis (RPGN) has crescent formation on renal biopsy. This indicates:",["Chronic, slow-progressing disease","Aggressive inflammation with potential for rapid loss of kidney function within weeks to months","Benign finding","Infection only"],1,"RPGN (crescentic GN): crescents (proliferating parietal epithelial cells) in > 50% of glomeruli indicate severe, aggressive inflammation. Without treatment, ESRD develops in weeks to months. Causes: anti-GBM (type I), immune complex (type II), pauci-immune/ANCA (type III). Treatment: immunosuppression + plasmapheresis."),
  rn("NCLEX-RN","Renal",3,"A client with chronic kidney disease develops secondary hyperparathyroidism. This occurs because:",["The kidneys produce PTH","CKD impairs phosphorus excretion and vitamin D activation, causing hypocalcemia that stimulates PTH production","Parathyroid adenoma develops","Excess calcium intake"],1,"CKD mechanism: decreased phosphorus excretion (hyperphosphatemia) and impaired 1,25-dihydroxyvitamin D synthesis leads to hypocalcemia. Chronic hypocalcemia stimulates PTH secretion (secondary hyperparathyroidism), causing renal osteodystrophy. Treatment: phosphate binders, active vitamin D, calcimimetics."),
  rn("NCLEX-RN","Infection Control",3,"Clostridioides difficile infection control measures include:",["Alcohol-based hand sanitizer as preferred method","Soap and water hand hygiene, contact precautions, and bleach-based environmental cleaning","Standard precautions only","Droplet precautions"],1,"C. diff spores resist alcohol. Required: soap and water hand hygiene, contact precautions (gown and gloves), dedicated equipment, and sporicidal environmental cleaning (bleach-based products, hydrogen peroxide vapor). Antibiotic stewardship prevents new cases."),
  rn("NCLEX-RN","Hematological",3,"A client with multiple myeloma has bone pain, hypercalcemia, and Bence Jones proteinuria. The nurse should also monitor for:",["Hypernatremia","Renal insufficiency from light chain deposition (myeloma kidney)","Hypocalcemia","Hyperphosphatemia"],1,"Multiple myeloma complications (CRAB): Calcium elevation, Renal insufficiency, Anemia, Bone lesions. Renal failure occurs from light chain (Bence Jones protein) deposition in renal tubules, hypercalcemia, and NSAIDs. Maintain hydration and avoid nephrotoxins."),
  rn("NCLEX-RN","Immunological",3,"A client with systemic sclerosis (scleroderma) develops Raynaud phenomenon and esophageal dysmotility. The nurse should teach:",["Warm baths for Raynaud and spicy foods for esophageal motility","Cold avoidance, calcium channel blockers for Raynaud, and small frequent meals with HOB elevation for esophageal symptoms","Vigorous exercise in cold weather","Large meals before bedtime"],1,"Scleroderma management: Raynaud (keep hands warm, CCBs for vasodilation), esophageal dysmotility (small meals, upright positioning, PPI for reflux), skin thickening (moisturizers, physical therapy), and monitoring for renal crisis (ACEi first-line) and pulmonary involvement."),
  rn("NCLEX-RN","Integumentary",3,"A client with pemphigus vulgaris has flaccid bullae and a positive Nikolsky sign. The nurse should:",["Pop the blisters for comfort","Provide gentle skin care, avoid friction, and administer prescribed immunosuppressive therapy","Apply adhesive bandages directly","Use harsh soaps for cleaning"],1,"Pemphigus vulgaris (autoimmune intraepidermal blistering): positive Nikolsky sign (skin separates with lateral pressure). Fragile bullae rupture easily, creating painful erosions. Treatment: systemic corticosteroids and rituximab or other immunosuppressants. Gentle wound care, pain management, and nutrition support."),
  rn("RN-CAT","Critical Care",4,"A client with refractory cardiogenic shock is being evaluated for mechanical circulatory support. The nurse should anticipate:",["Medical management only","Percutaneous ventricular assist device (Impella) or ECMO placement","Immediate heart transplant listing","Discontinuation of all support"],1,"Refractory cardiogenic shock options: Impella (percutaneous LVAD providing up to 5.5 L/min flow), IABP (less potent), or VA-ECMO (provides both cardiac and respiratory support). These bridge to recovery, decision, or transplant/durable LVAD."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with cardiac tamponade should not receive:",["IV fluids","Positive pressure ventilation (further reduces venous return and cardiac output)","Vasopressors","Oxygen supplementation"],1,"PPV (including intubation) reduces venous return by increasing intrathoracic pressure, further compromising an already volume-dependent cardiac output in tamponade. If intubation is necessary, perform pericardiocentesis first when possible. Aggressive IV fluids augment preload temporarily."),
  rn("NCLEX-RN","Respiratory",3,"A client with suspected pulmonary embolism develops cardiovascular collapse. The nurse should prepare for:",["Outpatient anticoagulation","Systemic thrombolysis with alteplase for massive PE","CT scan first before any treatment","Oral anticoagulation only"],1,"Massive PE with hemodynamic instability (SBP < 90, shock): systemic thrombolysis (alteplase 100mg over 2 hours) is indicated despite bleeding risk because mortality without treatment exceeds 25-65%. If thrombolysis contraindicated, catheter-directed therapy or surgical embolectomy."),
  rn("NCLEX-RN","Neurological",3,"A client with peripheral neuropathy from diabetes should be screened using:",["Deep tendon reflex testing only","10-gram monofilament testing of the feet and 128-Hz tuning fork vibration assessment","Visual acuity testing","Cognitive screening tools"],1,"Diabetic neuropathy screening: 10g Semmes-Weinstein monofilament (detects loss of protective sensation at specific foot sites) and 128-Hz tuning fork (vibration sense). Ankle reflexes may also be reduced. Annual screening enables early intervention and foot care education to prevent ulceration and amputation."),
  rn("NCLEX-RN","Endocrine",3,"A client with multiple endocrine neoplasia type 2 (MEN2) should be screened for:",["Diabetes mellitus","Medullary thyroid carcinoma, pheochromocytoma, and primary hyperparathyroidism","Pancreatic tumors","Prolactinoma"],1,"MEN2A: medullary thyroid carcinoma (100%), pheochromocytoma (50%), hyperparathyroidism (20-30%). MEN2B: MTC, pheochromocytoma, mucosal neuromas, marfanoid habitus. RET proto-oncogene mutation. Prophylactic thyroidectomy recommended in RET mutation carriers."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with Zollinger-Ellison syndrome has recurrent peptic ulcers. The nurse should anticipate:",["Standard-dose PPI therapy","High-dose PPI therapy and workup for gastrinoma (fasting gastrin level, secretin stimulation test)","Antacid therapy only","H. pylori eradication as sole treatment"],1,"ZES: gastrin-secreting tumor (usually pancreatic or duodenal) causes massive acid hypersecretion and recurrent/refractory ulcers. Diagnosis: fasting gastrin > 1000 pg/mL or positive secretin stimulation test. Treatment: high-dose PPI, tumor localization (CT, octreotide scan), and surgical resection if possible."),
  rn("NCLEX-RN","Pharmacology",3,"A client receiving continuous heparin infusion should have the dose adjusted based on:",["Weight alone","Activated partial thromboplastin time (aPTT) measured every 6 hours initially","International normalized ratio (INR)","Platelet count only"],1,"UFH monitoring: aPTT every 6 hours initially, targeting 1.5-2.5x control (institution-specific protocol). Weight-based dosing: 80 units/kg bolus, then 18 units/kg/hour. Adjust per nomogram. Monitor platelet count every 2-3 days for HIT. Anti-Xa can be used alternatively."),
  rn("NCLEX-RN","Mental Health",3,"A client with agoraphobia avoids public places due to fear of having a panic attack. Treatment should include:",["Forced exposure without preparation","Graduated exposure therapy with cognitive restructuring and possible SSRI therapy","Permanent avoidance of triggers","Antipsychotic medication"],1,"Agoraphobia treatment: CBT with graduated exposure therapy (systematic desensitization to avoided situations) combined with cognitive restructuring (challenging catastrophic thinking). SSRIs reduce panic frequency and anxiety. Avoidance reinforces the phobia and should not be encouraged."),
  rn("NCLEX-RN","Mental Health",3,"A client with avoidant personality disorder desires social connections but avoids them due to:",["Lack of interest in relationships","Intense fear of rejection, criticism, and embarrassment","Suspicion of others' motives","Grandiose sense of self-importance"],1,"AVPD: pervasive social inhibition, feelings of inadequacy, hypersensitivity to criticism. Unlike schizoid PD (no desire for relationships) or social anxiety (may have adequate social skills), AVPD involves deep-seated inadequacy and fear of rejection. Treatment: CBT, social skills training, and possibly SSRIs."),
  rn("NCLEX-RN","Pediatrics",3,"A child with Kawasaki disease should receive treatment within the first 10 days to prevent:",["Skin complications","Coronary artery aneurysms","Renal failure","Hepatic damage"],1,"IV immunoglobulin (2g/kg single dose) plus high-dose aspirin within the first 10 days of illness reduces coronary artery aneurysm risk from 25% to < 5%. After fever resolves, transition to low-dose aspirin for antiplatelet effect. Echocardiographic monitoring is essential."),
  rn("NCLEX-RN","Pediatrics",3,"A newborn with congenital diaphragmatic hernia should NOT receive:",["Endotracheal intubation","Bag-mask ventilation (distends the herniated stomach/bowel, further compressing the lungs)","IV fluids","Sedation"],1,"CDH: abdominal organs herniate through the diaphragm into the chest. Bag-mask ventilation is contraindicated as it inflates the herniated bowel, worsening lung compression. Immediate intubation, NG tube (decompress stomach), and surgical repair after stabilization."),
  rn("NCLEX-RN","Maternal/Newborn",3,"A client with an incompetent cervix typically presents with:",["Painful contractions and bloody show","Painless cervical dilation in the second trimester","Premature rupture of membranes","Post-term pregnancy"],1,"Cervical insufficiency: painless cervical dilation, usually in the second trimester, leading to pregnancy loss. Treatment: cervical cerclage (McDonald or Shirodkar technique) placed at 12-14 weeks in future pregnancies. Progesterone supplementation may also be used."),
  rn("NCLEX-RN","Maternal/Newborn",3,"During electronic fetal monitoring, variable decelerations that are repetitive and deep with slow recovery indicate:",["Normal fetal heart rate pattern","Significant umbilical cord compression requiring intervention","Uteroplacental insufficiency","Fetal sleep state"],1,"Variable decelerations result from umbilical cord compression. Benign variables are brief and recover quickly. Concerning features: repetitive, deep (< 60 bpm), prolonged (> 60 seconds), slow recovery, loss of variability. Interventions: position changes, amnioinfusion, and possible delivery."),
  rn("NCLEX-RN","Renal",3,"A client with ANCA-associated vasculitis (granulomatosis with polyangiitis) develops rapidly progressive renal failure. Treatment includes:",["NSAIDs","Pulse IV cyclophosphamide or rituximab plus corticosteroids and possibly plasmapheresis","Antibiotics only","Dietary modifications alone"],1,"ANCA vasculitis (GPA/MPA) causing RPGN requires aggressive immunosuppression: induction with cyclophosphamide or rituximab plus high-dose corticosteroids. Plasmapheresis for severe renal involvement or pulmonary hemorrhage. Maintenance: rituximab or azathioprine to prevent relapse."),
  rn("NCLEX-RN","Hematological",3,"A client with paroxysmal nocturnal hemoglobinuria presents with dark urine upon waking. This is caused by:",["Dehydration overnight","Complement-mediated hemolysis of defective red blood cells, concentrated during sleep","Urinary tract infection","Liver disease"],1,"PNH: GPI-anchor deficiency makes RBCs vulnerable to complement-mediated lysis. Hemolysis concentrates during sleep (mild respiratory acidosis activates complement). Morning hemoglobinuria results. Treatment: eculizumab (complement C5 inhibitor). Bone marrow transplant is curative."),
  rn("NCLEX-RN","Immunological",3,"A client with anaphylaxis should receive epinephrine administered:",["Intravenously as first-line","Intramuscularly in the anterolateral thigh (fastest absorption site)","Subcutaneously in the upper arm","Intradermally"],1,"IM epinephrine in the anterolateral thigh provides the fastest absorption and peak blood levels. Auto-injector dose: 0.3mg adults, 0.15mg children < 30kg. Can repeat every 5-15 minutes. IV epinephrine is reserved for refractory anaphylaxis or cardiac arrest, requiring cardiac monitoring."),
  rn("NCLEX-RN","Integumentary",3,"A client with a suspected melanoma should have which characteristic assessed using the ABCDE criteria?",["Only color and size","Asymmetry, Border irregularity, Color variation, Diameter > 6mm, and Evolving features","Texture and temperature","Location and depth"],0,"ABCDE melanoma detection: Asymmetry (halves don't match), Border irregularity (ragged, notched edges), Color variation (multiple colors, especially blue/black), Diameter > 6mm (pencil eraser), Evolving (changing size, shape, color, or new symptoms). Any concern warrants referral for biopsy."),
  rn("RN-CAT","Critical Care",4,"A client with severe sepsis has a procalcitonin level of 8.5 ng/mL. The nurse should understand this indicates:",["Viral infection","High probability of bacterial infection requiring antibiotic therapy","Allergic reaction","Fungal infection"],1,"Procalcitonin > 2 ng/mL strongly suggests bacterial infection (not viral or inflammatory). PCT-guided antibiotic therapy reduces antibiotic duration without worsening outcomes. Serial levels help guide antibiotic de-escalation: decreasing PCT by 80% suggests adequate treatment response."),
  rn("RN-CAT","Critical Care",4,"A client on mechanical ventilation has a plateau pressure of 35 cmH2O. The nurse should:",["Accept this as normal","Notify the provider as plateau pressure should be < 30 cmH2O to prevent barotrauma","Increase the tidal volume","Remove PEEP entirely"],1,"Plateau pressure > 30 cmH2O increases barotrauma risk. Reduce tidal volume, check for compliance changes (effusion, pneumothorax, abdominal distension), or decrease PEEP if able. Driving pressure (plateau - PEEP) < 15 cmH2O is associated with better outcomes."),
  rn("NCLEX-RN","Cardiovascular",3,"A client receiving tissue valve prosthesis does not require lifelong anticoagulation because:",["Tissue valves never clot","Tissue valves have lower thrombogenicity than mechanical valves","Anticoagulation is always needed","Tissue valves are made from metal"],1,"Bioprosthetic (tissue) valves have lower thrombogenicity than mechanical valves. Anticoagulation (warfarin, INR 2.5-3.5) is needed for 3-6 months post-surgery, then aspirin only. However, tissue valves have limited durability (10-20 years) compared to mechanical valves (lifetime)."),
  rn("NCLEX-RN","Respiratory",3,"A client with pertussis (whooping cough) is most contagious during:",["The paroxysmal cough stage","The catarrhal stage (first 1-2 weeks with mild cold-like symptoms)","The convalescent stage","After antibiotic treatment"],1,"Pertussis is most contagious during the catarrhal stage before the characteristic whoop develops. Droplet isolation is required until 5 days of appropriate antibiotics (azithromycin) or 21 days from cough onset without treatment. Close contacts receive post-exposure prophylaxis."),
  rn("NCLEX-RN","Neurological",3,"A client with a basilar skull fracture has raccoon eyes and Battle sign. The nurse should NOT:",["Monitor neurological status","Insert a nasogastric tube (risk of intracranial insertion through the fractured cribriform plate)","Provide emotional support","Monitor CSF drainage"],1,"Basilar skull fracture: raccoon eyes (periorbital ecchymosis), Battle sign (mastoid ecchymosis), hemotympanum, CSF otorrhea/rhinorrhea. NG tube insertion risks brain penetration through cribriform plate fracture. Use orogastric tube instead. Do not pack nose/ears."),
  rn("NCLEX-RN","Endocrine",3,"A client with thyroid nodules and elevated calcitonin should be evaluated for:",["Hypothyroidism","Medullary thyroid carcinoma (calcitonin is a tumor marker for parafollicular C-cell cancer)","Papillary thyroid cancer","Benign goiter"],1,"Elevated calcitonin strongly suggests medullary thyroid carcinoma (C-cell origin). Calcitonin is both diagnostic and a monitoring marker. Screen for RET proto-oncogene mutation (MEN2 association). Treatment is total thyroidectomy with central lymph node dissection. MTC does not respond to RAI."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with Budd-Chiari syndrome has hepatic vein thrombosis causing:",["Small bowel obstruction","Ascites, hepatomegaly, and abdominal pain from hepatic venous outflow obstruction","Gallstones","Pancreatitis"],1,"Budd-Chiari: hepatic vein thrombosis causes sinusoidal congestion, hepatomegaly, ascites, and liver damage. Etiology: hypercoagulable states (myeloproliferative neoplasms most common), OCPs, pregnancy. Treatment: anticoagulation, TIPS, or liver transplant for severe cases."),
  rn("NCLEX-RN","Pharmacology",3,"A client prescribed tacrolimus post-transplant should have levels monitored because:",["Levels never change","Tacrolimus has a narrow therapeutic window; too low risks rejection, too high causes nephrotoxicity","Levels are always therapeutic at standard doses","No monitoring is needed after the first month"],1,"Tacrolimus trough levels guide dosing: target varies by organ, time post-transplant, and protocol (typically 5-15 ng/mL). Nephrotoxicity, neurotoxicity, hyperglycemia, and hypertension occur at supratherapeutic levels. Subtherapeutic levels risk acute rejection. Drug interactions are numerous (CYP3A4 substrate)."),
  rn("NCLEX-RN","Mental Health",3,"A client with somatic symptom disorder should be managed by:",["Ordering extensive diagnostic testing to reassure the client","Scheduling regular, brief appointments with one primary provider to reduce ER visits and unnecessary testing","Dismissing all physical complaints","Referring to psychiatry immediately without explanation"],1,"SSD management: establish one primary provider, schedule regular visits (not contingent on symptoms), acknowledge symptoms are real (not imaginary), limit unnecessary testing, gradually introduce psychosocial interventions, and treat comorbid depression/anxiety. CBT is effective."),
  rn("NCLEX-RN","Pediatrics",3,"A child with iron deficiency anemia should have iron supplementation given:",["With meals for better absorption","Between meals with citrus juice to enhance absorption","With dairy products","At bedtime without any food"],1,"Iron absorption is enhanced by vitamin C (citrus juice) and impaired by calcium (dairy), antacids, and tannins (tea). Give iron between meals for optimal absorption. GI side effects may necessitate taking with small amounts of food. Stool color will be dark/black (expected)."),
  rn("NCLEX-RN","Maternal/Newborn",3,"Delayed cord clamping (at least 30-60 seconds after birth) provides the newborn with:",["No additional benefit","Increased blood volume, iron stores, and reduced anemia risk","Risk of jaundice without any benefit","Increased infection risk"],1,"Delayed cord clamping (30-60 seconds for term; up to 30-60 seconds for preterm) increases blood volume (80 mL), iron stores (lasting several months), and reduces IVH risk in preterms. Slight increase in jaundice requiring phototherapy may occur but benefits outweigh risks."),
  rn("NCLEX-RN","Renal",3,"A client with focal segmental glomerulosclerosis is at risk for:",["Spontaneous resolution","Progressive renal failure requiring immunosuppressive therapy","Only mild proteinuria","No complications"],1,"FSGS causes podocyte injury with focal/segmental sclerosis. It is the most common cause of nephrotic syndrome in African Americans. Treatment: corticosteroids, calcineurin inhibitors, or rituximab. 50% progress to ESRD within 10 years. Recurrence in transplanted kidneys is common (30-40%)."),
  rn("NCLEX-RN","Hematological",3,"A client with glucose-6-phosphate dehydrogenase deficiency should avoid:",["All medications","Oxidative stress triggers including sulfonamides, aspirin, fava beans, and naphthalene","Dairy products","Citrus fruits"],1,"G6PD deficiency: oxidative stress causes acute hemolytic episodes. Avoid: sulfonamides, nitrofurantoin, primaquine, dapsone, aspirin (high dose), fava beans, and naphthalene (mothballs). G6PD assay should not be performed during acute hemolysis (false normal due to reticulocytosis)."),
  rn("NCLEX-RN","Immunological",3,"A client receiving CAR-T cell therapy should be monitored for:",["Only mild fatigue","Cytokine release syndrome (fever, hypotension, capillary leak) and neurotoxicity","No significant side effects","Allergic reaction only"],1,"CAR-T therapy adverse effects: cytokine release syndrome (CRS: fever, hypotension, hypoxia, organ dysfunction - treated with tocilizumab + corticosteroids), immune effector cell-associated neurotoxicity syndrome (ICANS: confusion, seizures, cerebral edema), and prolonged cytopenias."),
  rn("NCLEX-RN","Cardiovascular",3,"A client with diastolic heart failure (HFpEF) is managed differently from systolic HF because:",["Beta-blockers are contraindicated","The focus is on controlling blood pressure, heart rate, and volume status rather than increasing contractility","Diuretics are never used","ACE inhibitors are always beneficial"],1,"HFpEF: impaired relaxation with preserved EF (>= 50%). No mortality-reducing drugs proven (unlike HFrEF). Management focuses on symptom control: diuretics for congestion, BP control, rate control for AF, and treating comorbidities. SGLT2 inhibitors show emerging benefit."),
  rn("NCLEX-RN","Respiratory",3,"A client with a right mainstem intubation will have:",["Bilateral breath sounds","Absent or diminished breath sounds on the left with hyperinflation of the right lung","Normal chest X-ray","Bilateral hyperinflation"],1,"Right mainstem bronchus intubation (tube too deep): ventilates only the right lung, causing left lung atelectasis (absent/diminished left breath sounds) and right lung hyperinflation. Diagnosis: CXR shows tube tip below the carina. Withdraw tube 2-3 cm and verify position."),
  rn("NCLEX-RN","Neurological",3,"A client with pseudotumor cerebri (idiopathic intracranial hypertension) presents with:",["Focal neurological deficits","Headache, visual disturbances, papilledema, and elevated opening pressure on LP with normal imaging","Seizures","Motor weakness"],1,"IIH: elevated ICP without structural cause. Typical patient: obese woman of childbearing age. Opening pressure > 25 cmH2O on LP with normal MRI. Treatment: weight loss, acetazolamide (reduces CSF production), and serial visual field testing. Optic nerve sheath fenestration for visual threat."),
  rn("NCLEX-RN","Gastrointestinal",3,"A client with acute mesenteric ischemia presents with pain out of proportion to physical examination findings. The nurse should:",["Administer antacids","Recognize this as a surgical emergency requiring CT angiography and possible intervention","Encourage oral fluids","Monitor without intervention"],1,"Acute mesenteric ischemia: severe abdominal pain disproportionate to benign exam (pain-exam discordance). CT angiography diagnoses arterial or venous occlusion. Treatment: anticoagulation, revascularization (endovascular or surgical), and resection of necrotic bowel. Mortality is 60-80% if delayed."),
  rn("NCLEX-RN","Pharmacology",3,"A client on long-term prednisone therapy should be monitored for:",["Only weight changes","Osteoporosis, hyperglycemia, cataracts, adrenal suppression, and immunosuppression","No long-term effects","Only skin changes"],1,"Chronic corticosteroid complications: osteoporosis (bisphosphonates, calcium, vitamin D), hyperglycemia/diabetes, cataracts, glaucoma, adrenal suppression, immunosuppression, cushingoid appearance, myopathy, peptic ulcers, mood changes, and skin thinning. Use lowest effective dose."),
  rn("NCLEX-RN","Mental Health",3,"A client with dependent personality disorder should have the nursing care plan focus on:",["Making all decisions for the client","Promoting independent decision-making and self-reliance through gradual steps","Encouraging dependency on the treatment team","Discharge without follow-up"],1,"DPD treatment: gradually foster independence and self-efficacy through structured decision-making exercises, assertiveness training, and CBT targeting core beliefs of inadequacy. Avoid reinforcing dependency by making decisions for the client. Group therapy develops social skills."),
  rn("NCLEX-RN","Pediatrics",3,"A premature infant is at risk for retinopathy of prematurity. Screening should begin at:",["Birth","31-32 weeks postmenstrual age or 4 weeks chronological age (whichever is later)","6 months of age","1 year of age"],1,"ROP screening: begin at 31 weeks PMA or 4 weeks chronological age (whichever is later) for infants < 1500g or < 30 weeks. Examinations continue every 1-3 weeks until retinal vascularization reaches zone III. Treatment: laser photocoagulation or anti-VEGF injections for severe disease."),
  rn("NCLEX-RN","Maternal/Newborn",3,"A client receiving terbutaline for tocolysis should be monitored for:",["Bradycardia","Maternal tachycardia, hyperglycemia, and hypokalemia","Hypotension only","No significant side effects"],1,"Terbutaline (beta-2 agonist) side effects: maternal tachycardia (most common), hyperglycemia (glycogenolysis), hypokalemia (intracellular shift), tremors, and rarely pulmonary edema. FDA warns against long-term tocolysis use. Monitor maternal heart rate, glucose, and potassium."),
  rn("NCLEX-RN","Renal",3,"A client with acute interstitial nephritis should have the causative agent identified. The most common cause is:",["Infection","Medications (NSAIDs, antibiotics, PPIs, and sulfonamides)","Autoimmune disease","Obstruction"],1,"Drug-induced AIN accounts for 70-75% of cases. Common culprits: NSAIDs, beta-lactam antibiotics, PPIs, sulfonamides, allopurinol, and diuretics. Presentation: fever, rash, eosinophilia (classic triad), rising creatinine. Treatment: withdraw offending drug, consider corticosteroids."),

  // === NP (40) ===
  np("AANP","Cardiovascular",3,"A patient presenting with exertional chest tightness and ECG showing T-wave inversions in V1-V4 should be evaluated for:",["Benign early repolarization","Hypertrophic cardiomyopathy or acute coronary syndrome","Normal variant","Pericarditis"],1,"Deep T-wave inversions in precordial leads suggest HCM (especially with LVH criteria), apical HCM (Yamaguchi disease), or ACS (Wellens syndrome pattern - critical LAD stenosis). Echocardiography and possibly stress testing or coronary angiography are indicated."),
  np("AANP","Respiratory",3,"A patient with a solitary pulmonary nodule found incidentally on CT should be managed based on:",["Immediate surgical removal for all nodules","Fleischner Society guidelines considering size, morphology, and risk factors","No follow-up needed","Biopsy of all nodules regardless of size"],1,"Fleischner Society guidelines: management depends on nodule size (< 6mm, 6-8mm, > 8mm), morphology (solid vs. ground glass vs. part-solid), and risk factors (smoking history, prior malignancy). Small low-risk nodules may need no follow-up; larger or higher-risk nodules require serial CT or PET/biopsy."),
  np("NP-CAT","Neurological",4,"A patient with treatment-resistant migraine should be considered for:",["Only over-the-counter analgesics","CGRP monoclonal antibody therapy (erenumab, fremanezumab, galcanezumab)","Opioid therapy long-term","No preventive options exist"],1,"CGRP antagonists (monoclonal antibodies: erenumab, fremanezumab, galcanezumab - monthly/quarterly injections, or gepants: rimegepant, ubrogepant - oral) represent a breakthrough in migraine prevention. Indicated when traditional preventives fail or are contraindicated. Generally well-tolerated."),
  np("AANP","Endocrine",3,"A patient with a TSH of 8.5 and normal free T4 has:",["Overt hypothyroidism","Subclinical hypothyroidism","Hyperthyroidism","Normal thyroid function"],1,"Subclinical hypothyroidism: elevated TSH with normal free T4. Treatment is controversial for mild elevation (TSH 5-10). Consider treating if: TSH > 10, symptoms present, anti-TPO antibodies positive, pregnancy planned, or dyslipidemia. If not treating, monitor TSH every 6-12 months."),
  np("AANP","Gastrointestinal",3,"A patient with chronic hepatitis B and an elevated viral load should be started on:",["Interferon for all cases","Antiviral therapy with tenofovir or entecavir","No treatment until cirrhosis develops","Liver transplant evaluation immediately"],1,"Chronic HBV treatment indications: elevated ALT + HBV DNA > 2000 IU/mL (HBeAg-negative) or > 20,000 (HBeAg-positive), significant fibrosis, or family history of HCC. First-line: tenofovir (TDF or TAF) or entecavir - high barrier to resistance, long-term suppression."),
  np("NP-CAT","Pharmacology",3,"A patient on dual antiplatelet therapy (DAPT) after drug-eluting stent placement should continue therapy for:",["1 month","At least 12 months (6 months minimum in stable patients at low bleeding risk)","Lifelong","3 months"],1,"Post-DES DAPT: standard duration is 12 months (aspirin + P2Y12 inhibitor). Shorter duration (6 months) may be considered for high bleeding risk patients with low ischemic risk. Extended DAPT (> 12 months) may benefit high ischemic risk patients. Aspirin is continued indefinitely."),
  np("AANP","Mental Health",3,"A patient presenting with symptoms of both depression and anxiety should be treated with:",["Separate medications for each condition","An SSRI or SNRI as first-line, as both conditions respond to these medications","Benzodiazepines long-term","Antipsychotics"],1,"SSRIs and SNRIs effectively treat both depression and anxiety disorders. Sertraline, escitalopram (broad efficacy), venlafaxine, and duloxetine are commonly used. Starting doses should be low (anxiety patients are sensitive to activation) and titrated gradually. CBT addresses both conditions."),
  np("AANP","Dermatology",3,"A patient with herpes zoster (shingles) presenting within 72 hours should be treated with:",["Topical antiviral alone","Oral valacyclovir or famciclovir for 7 days","No treatment as it is self-limited","Antibiotics"],1,"Antiviral therapy within 72 hours of rash onset reduces acute pain duration, healing time, and postherpetic neuralgia risk. Valacyclovir (1g TID x 7 days) or famciclovir (500mg TID x 7 days) are preferred over acyclovir for better bioavailability and dosing convenience."),
  np("AANP","Musculoskeletal",3,"A patient with suspected carpal tunnel syndrome should have the diagnosis confirmed with:",["X-ray of the wrist","Nerve conduction studies and electromyography","MRI of the cervical spine","Blood tests only"],1,"NCS/EMG is the gold standard for CTS diagnosis: demonstrates median nerve conduction slowing across the carpal tunnel. Sensitivity > 85%. Also helps determine severity and rule out other conditions (cervical radiculopathy, polyneuropathy). Ultrasound is an emerging alternative."),
  np("NP-CAT","Infectious Disease",3,"A patient with recurrent urinary tract infections should be evaluated for:",["No further workup needed","Anatomical abnormalities, voiding dysfunction, and risk factors (sexual activity, diaphragm use, estrogen deficiency)","Only antibiotic resistance","Renal transplant"],1,"Recurrent UTI workup: urinalysis with culture, post-void residual volume, consideration of imaging (ultrasound for structural abnormalities), and identifying modifiable risk factors. Prevention: behavioral modifications, topical estrogen (postmenopausal), cranberry products, and possibly antibiotic prophylaxis."),
  np("AANP","Reproductive",3,"A patient seeking emergency contraception should be informed that:",["It is only available by prescription","Levonorgestrel (Plan B) is available OTC and most effective within 72 hours","It causes abortion","It is the same as mifepristone"],1,"Levonorgestrel (Plan B): OTC, most effective within 72 hours (95% within 24 hours, 85% within 72 hours). Ella (ulipristal) is prescription-only, effective up to 120 hours. Copper IUD is the most effective EC (> 99%) up to 5 days. None are abortifacients."),
  np("AANP","Geriatrics",3,"An elderly patient with a fall should be assessed for:",["Only the injury sustained","Fall risk factors including medications (benzodiazepines, anticholinergics), orthostatic hypotension, visual deficits, and home hazards","Mental health only","Dietary habits only"],1,"Comprehensive fall assessment: medication review (sedatives, antihypertensives, anticholinergics), orthostatic vital signs, visual acuity, gait/balance assessment (Timed Up and Go), lower extremity strength, cognitive screening, home safety evaluation, and footwear assessment."),
  np("NP-CAT","Hematological",4,"A patient with suspected hereditary hemochromatosis should have which initial diagnostic test?",["Liver biopsy","Transferrin saturation and ferritin level","Iron level alone","Complete blood count"],1,"Hereditary hemochromatosis screening: transferrin saturation > 45% is the earliest abnormality. Elevated ferritin confirms iron overload. HFE gene testing (C282Y mutation) confirms diagnosis. Liver biopsy is less commonly needed now with genetic testing available. Treatment: therapeutic phlebotomy."),
  np("AANP","Renal",3,"A patient with proteinuria and diabetes should have their ACEi/ARB dose titrated to:",["The lowest possible dose","Maximum tolerated dose for optimal renal protection","A standard fixed dose for all patients","No specific target"],1,"ACEi/ARB dose titration to maximum tolerated dose provides maximum renal protection by reducing intraglomerular pressure and proteinuria. Monitor potassium and creatinine after each dose increase. Up to 30% creatinine rise is acceptable after initiation (reflects hemodynamic effect)."),
  np("AANP","Women's Health",3,"A patient with BRCA1 mutation should be counseled about:",["No additional cancer screening needed","Enhanced breast and ovarian cancer screening and risk-reducing surgical options","Only routine mammography","Avoiding all surgery"],1,"BRCA1/2 carriers: enhanced screening (annual breast MRI starting at 25 + mammography starting at 30), risk-reducing bilateral mastectomy (reduces breast cancer risk by 90-95%), risk-reducing bilateral salpingo-oophorectomy (by age 35-40 for BRCA1, 40-45 for BRCA2), and chemoprevention options."),
  np("AANP","Preventive Medicine",2,"The HPV vaccine is recommended for:",["Only females aged 11-12","Males and females aged 9-26 (catch-up through age 45 with shared clinical decision-making)","Only sexually active individuals","Only after abnormal Pap smear"],1,"HPV vaccine (9-valent): routine at age 11-12, catch-up through 26 for both sexes. Ages 27-45: shared clinical decision-making. Prevents HPV-related cancers (cervical, anal, oropharyngeal, penile, vulvar, vaginal). Most effective before HPV exposure. Two-dose schedule if started before age 15."),
  np("NP-CAT","Cardiovascular",3,"A patient with chronic stable angina should have medical therapy optimized before revascularization. The ISCHEMIA trial showed:",["All patients benefit from early invasive strategy","Optimal medical therapy is as effective as invasive strategy for most patients with stable ischemia","Surgery is always superior","Medical therapy has no role"],1,"ISCHEMIA trial: in stable ischemic heart disease, initial invasive strategy did not reduce death/MI over optimal medical therapy (OMT). OMT includes antiplatelet, statin, beta-blocker/CCB, ACEi, and lifestyle modifications. Invasive approach reserved for refractory symptoms or ACS."),
  np("AANP","Endocrine",3,"A patient with polycystic ovary syndrome and insulin resistance should be treated with:",["Oral corticosteroids","Metformin combined with lifestyle modifications","Growth hormone therapy","No treatment for insulin resistance"],1,"PCOS with insulin resistance: metformin improves insulin sensitivity, reduces androgens, and may restore ovulation. Combined with lifestyle modifications (weight loss of 5-10% improves all PCOS parameters). For menstrual regulation, combined OCPs. For fertility, letrozole is first-line ovulation induction."),
  np("AANP","Gastrointestinal",3,"A patient with non-alcoholic fatty liver disease (NAFLD) should be counseled that first-line treatment is:",["Medication therapy","Lifestyle modification including weight loss of 7-10% and regular exercise","Liver transplant evaluation","Bariatric surgery for all patients"],1,"NAFLD/NASH: weight loss of 7-10% improves steatosis, inflammation, and fibrosis. Mediterranean diet and 150+ min/week of moderate exercise are recommended. No FDA-approved medication for NASH. Vitamin E (800 IU/day) may benefit non-diabetic NASH patients. GLP-1 RAs show promise."),
  np("AANP","Pharmacology",3,"When prescribing opioids for chronic non-cancer pain, the NP should follow which guideline?",["Prescribe without limits","CDC Opioid Prescribing Guidelines: lowest effective dose, avoid concurrent benzodiazepines, and reassess regularly","No guidelines exist","Always prescribe the maximum dose"],1,"CDC guidelines: start at lowest effective dose, avoid > 90 MME/day, co-prescribe naloxone if >= 50 MME or concurrent benzodiazepines, reassess within 1-4 weeks, check PDMP before prescribing, and use urine drug testing. Non-opioid and non-pharmacological treatments are preferred first-line."),
  np("NP-CAT","Mental Health",3,"A patient with treatment-resistant OCD should be considered for:",["No additional options beyond SSRIs","Augmentation with low-dose antipsychotic (aripiprazole), intensive ERP therapy, or deep brain stimulation in severe cases","Benzodiazepines long-term","Electroconvulsive therapy"],1,"Treatment-resistant OCD: first try adequate SSRI trial (max dose x 8-12 weeks), then switch SSRI or add clomipramine. Augmentation: low-dose atypical antipsychotic (aripiprazole, risperidone). Intensive ERP or residential treatment. DBS and ablative neurosurgery for the most refractory cases."),
  np("AANP","Dermatology",3,"A patient with rosacea should be treated with:",["Systemic antibiotics as first-line for all types","Topical metronidazole or azelaic acid for papulopustular rosacea","Topical retinoids for all types","Oral isotretinoin as first-line"],1,"Rosacea treatment by subtype: erythematotelangiectatic (brimonidine topical for flushing, laser for telangiectasia), papulopustular (topical metronidazole, azelaic acid; oral doxycycline for moderate-severe), phymatous (isotretinoin, surgical), ocular (lid hygiene, oral doxycycline)."),
  np("AANP","Musculoskeletal",3,"A patient with plantar fasciitis should be treated first-line with:",["Immediate surgery","Conservative management including stretching exercises, supportive footwear, and NSAIDs","Cortisone injections as first treatment","Casting the foot"],1,"Plantar fasciitis conservative management (90% resolution within 10 months): calf and plantar fascia stretching, supportive shoes with arch support, heel cups/orthotics, night splints, NSAIDs, and activity modification. Steroid injection for refractory cases. Surgery is last resort."),
  np("AANP","Infectious Disease",3,"A patient bitten by a tick in a Lyme-endemic area with an erythema migrans rash should receive:",["No treatment unless blood tests are positive","Doxycycline 100mg BID for 10-21 days (or amoxicillin if doxycycline is contraindicated)","IV antibiotics","Watchful waiting"],1,"Erythema migrans is diagnostic of early Lyme disease - serologic testing is not needed and may be negative early. Treat empirically: doxycycline 100mg BID x 10-21 days (preferred for age >= 8), amoxicillin for children < 8 and pregnant women. Do not delay treatment for test results."),
  np("AANP","Geriatrics",3,"Delirium in the hospitalized elderly should be prevented using:",["Prophylactic benzodiazepines","Non-pharmacological approaches: reorientation, sleep hygiene, early mobilization, and adequate hydration","Physical restraints","Continuous sedation"],1,"HELP (Hospital Elder Life Program) reduces delirium by 40%: orientation board, cognitive stimulation, early mobilization, sleep promotion (minimize nighttime disruptions), hydration, vision/hearing aids, and avoidance of deliriogenic medications. Restraints and benzodiazepines increase delirium risk."),
  np("NP-CAT","Reproductive",3,"A patient with endometrial hyperplasia without atypia should be treated with:",["Hysterectomy as first-line","Progestin therapy (oral medroxyprogesterone or levonorgestrel IUD)","Observation only","Combined estrogen-progesterone therapy"],1,"Endometrial hyperplasia without atypia: low progression to cancer (< 5%). First-line: progestin therapy (continuous oral or LNG-IUD, which has highest efficacy). Follow-up biopsy at 3-6 months. Hysterectomy for atypical hyperplasia or failed medical management. Address underlying cause (obesity, anovulation)."),
  np("AANP","Women's Health",3,"Cervical cancer screening guidelines recommend:",["Annual Pap smears for all women starting at age 18","Pap smear every 3 years starting at age 21, or co-testing (Pap + HPV) every 5 years starting at age 30","Monthly self-examinations","Annual HPV testing starting at puberty"],1,"USPSTF/ACS screening: age 21-29: cytology (Pap) every 3 years. Age 30-65: cytology every 3 years, HPV testing every 5 years, or co-testing every 5 years. > 65 with adequate prior screening: discontinue. Primary HPV testing every 5 years is emerging as preferred strategy."),
  np("NP-CAT","Hematological",3,"A patient with iron deficiency anemia who fails oral iron therapy should be considered for:",["Higher doses of oral iron","IV iron infusion (ferric carboxymaltose or iron sucrose)","Blood transfusion","No alternative exists"],1,"IV iron indications: oral iron intolerance/failure, malabsorption (celiac, gastric bypass), chronic inflammatory conditions (IBD), CKD on ESA, or need for rapid repletion. Ferric carboxymaltose allows single large-dose infusion (750-1000mg). Monitor for hypersensitivity reactions during infusion."),
  np("AANP","Renal",3,"A patient with CKD stage 3 should have which additional screening?",["No additional screening beyond creatinine","Proteinuria quantification, blood pressure monitoring, lipid panel, and cardiovascular risk assessment","Only renal ultrasound","Dialysis access evaluation"],1,"CKD stage 3 management: quantify proteinuria (UACR), optimize BP (< 130/80 with ACEi/ARB if proteinuric), assess cardiovascular risk (highest cause of death in CKD), manage dyslipidemia (statin therapy), monitor electrolytes, Hgb, PTH, and vitamin D. Nephrology referral for stage 4+."),
  np("AANP","Preventive Medicine",2,"The NP should recommend shingles vaccination with recombinant zoster vaccine (Shingrix) for adults aged:",["50 and older (2-dose series)","Only 65 and older","Only those with prior shingles","Under 50 with immunosuppression"],0,"Shingrix (recombinant, adjuvanted) is recommended for adults >= 50 years: 2-dose series (0 and 2-6 months). > 90% efficacy. Recommended even for those with prior shingles or prior Zostavax. Immunocompromised adults >= 19 may also be considered (shared clinical decision)."),

  // === RPN (40) ===
  rpn("REX-PN","Cardiovascular",2,"A client taking antihypertensive medications should be taught to:",["Stand up quickly from a sitting position","Rise slowly from lying to sitting to standing to prevent orthostatic hypotension","Take all medication doses at bedtime","Avoid all physical activity"],1,"Antihypertensives cause orthostatic hypotension. Rising slowly allows baroreceptors to compensate. Additional teaching: monitor BP at home, take medications as prescribed, report dizziness/lightheadedness, maintain adequate hydration, and avoid hot baths (vasodilation)."),
  rpn("REX-PN","Respiratory",2,"A client using a dry powder inhaler should be instructed to:",["Exhale into the device before inhaling","Inhale quickly and deeply through the device","Inhale slowly as with a metered-dose inhaler","Shake the device vigorously before each use"],1,"DPI technique differs from MDI: requires a quick, deep inhalation to generate turbulent airflow that disperses the powder into fine particles for lung deposition. Do not exhale into the device (moisture clumps the powder). No spacer is needed or used with DPIs."),
  rpn("RPN-CAT","Neurological",3,"A client with Parkinson disease should take levodopa/carbidopa:",["With high-protein meals for better absorption","On an empty stomach or with a low-protein snack for optimal absorption","At bedtime only","With antacids"],1,"Dietary protein competes with levodopa for absorption in the small intestine and transport across the blood-brain barrier (both use the same amino acid transport system). Taking levodopa 30-60 minutes before meals or with low-protein snacks optimizes absorption."),
  rpn("REX-PN","Endocrine",2,"A client receiving prednisone therapy should be monitored for:",["Hypoglycemia","Hyperglycemia (corticosteroids increase gluconeogenesis and insulin resistance)","Hypothyroidism","Anemia"],1,"Corticosteroids increase blood glucose through gluconeogenesis stimulation and insulin resistance. Monitor blood glucose regularly, especially in diabetic patients who may need insulin dose adjustments. Other monitoring: BP, weight, potassium, calcium, and mood changes."),
  rpn("REX-PN","Gastrointestinal",2,"A client with GERD should avoid which activity after eating?",["Walking slowly","Lying down within 2-3 hours of eating","Sitting in a recliner with head elevated","Light stretching"],1,"Lying flat after eating allows gastric acid to reflux through the LES. Wait 2-3 hours after meals before lying down. Elevate HOB 6-8 inches. Other measures: small meals, avoid trigger foods, weight loss, and avoid tight clothing around the abdomen."),
  rpn("REX-PN","Pharmacology",2,"A client receiving warfarin therapy should have:",["INR monitored regularly with a target typically between 2.0-3.0","No blood monitoring needed","PTT monitored weekly","Platelet count as the only monitoring parameter"],1,"Warfarin anticoagulation is monitored by INR. Target INR 2.0-3.0 for most indications (AF, DVT/PE). Mechanical heart valves may target 2.5-3.5. Initially check frequently (every 2-3 days), then extend to monthly when stable. Consistent vitamin K intake is essential."),
  rpn("REX-PN","Mental Health",2,"Therapeutic communication technique of 'reflection' involves:",["Giving the client advice about their problems","Repeating back the client's message to verify understanding and show active listening","Changing the subject to a less emotional topic","Sharing personal experiences"],1,"Reflection restates the client's message (content or feeling) in the nurse's own words. It validates the client's feelings, demonstrates active listening, encourages further exploration, and ensures accurate understanding. Example: Client: 'I'm so frustrated.' Nurse: 'You're feeling frustrated.'"),
  rpn("REX-PN","Pediatrics",2,"An infant should be positioned on their back for sleep to prevent:",["Plagiocephaly","Sudden infant death syndrome (SIDS)","Aspiration","Gastroesophageal reflux"],1,"The Back to Sleep campaign (now Safe to Sleep) reduced SIDS deaths by 50%. All infants should be placed supine for sleep on a firm, flat surface. Side-lying is not recommended. Tummy time while awake promotes development and prevents flat head."),
  rpn("REX-PN","Fundamentals",2,"When obtaining a blood pressure measurement, the cuff should cover:",["One-third of the upper arm length","Approximately 80% of the arm circumference (width covering 40% of arm circumference)","The entire arm from shoulder to elbow","Any size cuff can be used"],1,"Proper BP cuff sizing is essential: bladder width should be 40% of arm circumference, bladder length should encircle 80% of the arm. Too-small cuff falsely elevates readings, too-large falsely lowers. Document cuff size used."),
  rpn("REX-PN","Musculoskeletal",2,"A client with a new below-knee cast should be instructed to:",["Soak the cast in water when dirty","Keep the cast dry and report any numbness, tingling, increased pain, or color changes in toes","Scratch inside the cast with a coat hanger if itchy","Remove the cast if it feels tight"],1,"Cast care: keep dry (plastic covering for bathing), do not insert objects (skin breakdown, infection), report neurovascular changes (5 Ps), elevate extremity, and wiggle toes/fingers regularly. Itching: cool air from a hair dryer (low setting) may help."),
  rpn("REX-PN","Renal",2,"A client with a Foley catheter should have the drainage bag positioned:",["At the level of the bladder","Below the level of the bladder at all times to prevent retrograde flow","Above the bladder for better drainage","Anywhere convenient"],1,"Gravity drainage requires the collection bag below bladder level at all times. If the bag is elevated, urine flows back into the bladder, increasing infection risk. Secure tubing to prevent kinking, dependent loops, or pulling. Empty the bag when 2/3 full."),
  rpn("REX-PN","Maternal/Newborn",2,"A newborn's normal respiratory rate is:",["12-20 breaths per minute","30-60 breaths per minute","60-80 breaths per minute","20-30 breaths per minute"],1,"Normal newborn respiratory rate is 30-60/min. Breathing is primarily diaphragmatic and may be periodic (brief pauses < 20 seconds are normal). Count for a full minute. Report: rate > 60 (tachypnea), retractions, grunting, nasal flaring, or central cyanosis."),
  rpn("REX-PN","Infection Control",2,"When donning sterile gloves, the nurse should:",["Touch the outside of both gloves with bare hands","Pick up the first glove by the folded cuff using the dominant hand, then slide the gloved hand under the cuff of the second glove","Use non-sterile gloves and call them sterile","Apply hand sanitizer over non-sterile gloves"],1,"Sterile gloving technique: open package without touching inner surface, pick up first glove by the folded cuff (inner surface only), insert hand, use the sterile gloved hand to pick up the second glove by sliding fingers under the cuff (touching only the outer surface)."),
  rpn("REX-PN","Hematological",2,"A client with a low platelet count should be taught to:",["Use a straight razor for shaving","Use an electric razor and a soft toothbrush to minimize bleeding risk","Floss vigorously after every meal","Take aspirin for headaches"],1,"Thrombocytopenia bleeding precautions: electric razor, soft toothbrush, avoid flossing, avoid contact sports, avoid aspirin/NSAIDs, use stool softeners (prevent straining), report petechiae/bruising/bleeding gums, and avoid blowing nose forcefully."),
  rpn("REX-PN","Integumentary",2,"A client with contact dermatitis should be treated first by:",["Applying hot compresses to the affected area","Identifying and avoiding the causative agent","Taking systemic antibiotics","Covering the rash with adhesive bandages"],1,"Contact dermatitis management: identify and remove the trigger (occupational allergens, personal care products, jewelry). Treatment: topical corticosteroids, cool compresses, oral antihistamines for itching. Severe cases may need systemic corticosteroids. Patch testing identifies the specific allergen."),
  rpn("REX-PN","Emergency",2,"When performing the Heimlich maneuver on a conscious choking adult, the nurse should:",["Perform chest compressions","Position fists above the navel and below the xiphoid process, delivering upward abdominal thrusts","Slap the person on the back while they are standing","Give 5 back blows followed by 5 chest thrusts"],1,"Abdominal thrusts (Heimlich): stand behind the victim, wrap arms around the waist, place fist (thumb side) above navel and below xiphoid, grasp fist with other hand, and deliver quick upward thrusts until the object is expelled or the person becomes unconscious."),
  rpn("REX-PN","Oncology",2,"A client with cancer who develops anemia from chemotherapy should be assessed for:",["Only fatigue","Fatigue, dyspnea on exertion, tachycardia, and pallor","No symptoms as anemia from chemo is always asymptomatic","Only pallor"],0,"Chemotherapy-induced anemia causes decreased oxygen-carrying capacity. Symptoms include fatigue (most common), dyspnea on exertion, tachycardia, pallor, dizziness, and headache. Management: ESAs (erythropoietin), iron supplementation, RBC transfusion for severe anemia, and activity pacing."),
  rpn("REX-PN","Safety",2,"Fall prevention in hospitalized clients includes:",["Keeping bed in the highest position","Keeping the bed in the lowest position with side rails partially raised and call bell within reach","Restraining all clients at risk for falls","Keeping the room dark at all times"],1,"Fall prevention: bed in lowest position, partial (not full) side rails, call bell within reach, non-slip footwear, adequate lighting (especially at night), remove clutter, hourly rounding, toileting assistance, and fall risk identification with appropriate interventions."),
  rpn("REX-PN","Geriatrics",2,"An elderly client may experience decreased drug metabolism due to:",["Increased liver enzyme activity","Age-related decrease in liver blood flow and enzyme activity","Increased renal clearance","Enhanced protein binding"],1,"Aging reduces hepatic blood flow, liver mass, and phase I metabolism (CYP450 enzyme activity). This slows drug metabolism, increasing drug half-lives and risk of toxicity. Many medications require dose reduction in elderly patients. Phase II reactions are less affected by aging."),
  rpn("REX-PN","Community Health",2,"Primary healthcare is defined as:",["Emergency room services","First-contact, comprehensive, continuous, coordinated healthcare accessible to all","Specialized hospital care","Surgical services only"],0,"Primary healthcare encompasses: first-contact care (accessible entry point), comprehensive services (health promotion, disease prevention, treatment, rehabilitation), continuity over time, and coordination with other levels of care. Community health nursing is a key component."),
];

async function main() {
  let inserted = 0;
  const batchSize = 50;
  for (let i = 0; i < QS.length; i += batchSize) {
    const batch = QS.slice(i, i + batchSize);
    const values: string[] = [];
    const params: any[] = [];
    let idx = 1;
    for (const q of batch) {
      values.push(`($${idx},$${idx+1},$${idx+2},$${idx+3},$${idx+4},$${idx+5}::jsonb,$${idx+6}::jsonb,$${idx+7},$${idx+8}::integer,$${idx+9},$${idx+10},$${idx+11})`);
      params.push(q.tier,q.exam,"multiple_choice","published",q.stem,JSON.stringify(q.options),JSON.stringify([q.correct]),q.rationale,q.diff,q.bs,"BOTH",hash(q.stem));
      idx += 12;
    }
    const sql = `INSERT INTO exam_questions (tier, exam, question_type, status, stem, options, correct_answer, rationale, difficulty, body_system, region_scope, stem_hash)
                 SELECT v.* FROM (VALUES ${values.join(",")}) AS v(tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,body_system,region_scope,stem_hash)
                 WHERE NOT EXISTS (SELECT 1 FROM exam_questions e WHERE e.stem_hash = v.stem_hash)`;
    const result = await pool.query(sql, params);
    inserted += result.rowCount || 0;
  }
  console.log(`[Combined-B2] Inserted ${inserted}/${QS.length}`);
  const counts = await pool.query(`SELECT tier, count(*) as cnt FROM exam_questions WHERE status='published' GROUP BY tier ORDER BY tier`);
  counts.rows.forEach((r: any) => console.log(`  ${r.tier}: ${r.cnt}`));
  await pool.end();
}
main().catch(e => { console.error(e); process.exit(1); });
