import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

const QUESTIONS = [
  { question: "The traditional unit of absorbed dose is the:", optionA: "Roentgen", optionB: "Rad (radiation absorbed dose)", optionC: "Rem", optionD: "Curie", correctAnswer: "B", rationale: "Rad = traditional unit of absorbed dose. 1 rad = 0.01 Gy. SI equivalent = Gray (Gy).", category: "Safety", topic: "Radiation Units", difficulty: 1 },
  { question: "The traditional unit of dose equivalent is the:", optionA: "Rad", optionB: "Rem (roentgen equivalent man)", optionC: "Roentgen", optionD: "Gray", correctAnswer: "B", rationale: "Rem = traditional dose equivalent. 1 rem = 0.01 Sv. Rem = rad × quality factor.", category: "Safety", topic: "Radiation Units", difficulty: 1 },
  { question: "Attenuation of the X-ray beam refers to:", optionA: "Beam production", optionB: "The reduction in beam intensity as photons are absorbed or scattered while passing through matter", optionC: "Beam collimation", optionD: "Beam filtration only", correctAnswer: "B", rationale: "Attenuation = reduction in beam intensity through absorption (photoelectric) and scattering (Compton) as the beam passes through matter.", category: "Safety", topic: "Radiation Interactions", difficulty: 1 },
  { question: "Pair production occurs at photon energies above:", optionA: "50 keV", optionB: "1.02 MeV (not significant in diagnostic radiology)", optionC: "100 keV", optionD: "500 keV", correctAnswer: "B", rationale: "Pair production threshold: 1.02 MeV. The photon interacts with the nucleus, producing an electron-positron pair. Not relevant in diagnostic range.", category: "Safety", topic: "Radiation Interactions", difficulty: 3 },
  { question: "The main type of radiation interaction responsible for image contrast in diagnostic radiology is:", optionA: "Compton scattering", optionB: "Photoelectric absorption (differential absorption creates contrast between tissues)", optionC: "Coherent scattering", optionD: "Pair production", correctAnswer: "B", rationale: "Photoelectric absorption varies with Z³/E³, creating different absorption rates between bone (high Z) and soft tissue (low Z) = contrast.", category: "Safety", topic: "Radiation Interactions", difficulty: 2 },
  { question: "The photoelectric effect is proportional to the _____ power of the atomic number:", optionA: "First (Z¹)", optionB: "Third (Z³)", optionC: "Second (Z²)", optionD: "Fourth (Z⁴)", correctAnswer: "B", rationale: "Photoelectric absorption ∝ Z³/E³. Higher Z = dramatically more photoelectric absorption. This is why bone (Z~14) absorbs much more than soft tissue (Z~7.4).", category: "Safety", topic: "Radiation Interactions", difficulty: 2 },
  { question: "Compton scattering results in:", optionA: "Complete photon absorption", optionB: "A scattered photon of reduced energy and a recoil (Compton) electron", optionC: "No ionization", optionD: "Pair production", correctAnswer: "B", rationale: "Compton: photon interacts with outer shell electron, ejecting it (Compton electron) and producing a scattered photon of reduced energy and changed direction.", category: "Safety", topic: "Radiation Interactions", difficulty: 2 },
  { question: "The probability of Compton scattering is:", optionA: "Dependent on atomic number", optionB: "Independent of atomic number, dependent on electron density", optionC: "Dependent on temperature", optionD: "Absent in diagnostic radiology", correctAnswer: "B", rationale: "Compton is independent of Z, dependent on electron density. Since electron density is similar across soft tissues, Compton doesn't help differentiate tissues.", category: "Safety", topic: "Radiation Interactions", difficulty: 2 },
  { question: "According to the Bergonié-Tribondeau law, the MOST radiosensitive cells are:", optionA: "Neurons", optionB: "Young, immature, undifferentiated cells with high mitotic rates (stem cells, embryonic cells)", optionC: "Muscle cells", optionD: "Red blood cells", correctAnswer: "B", rationale: "Bergonié-Tribondeau: cells are more radiosensitive when they are young, undifferentiated, rapidly dividing, and have a long mitotic future.", category: "Safety", topic: "Radiation Biology", difficulty: 1 },
  { question: "Radiation-induced chromosome damage includes:", optionA: "Only point mutations", optionB: "Single-strand breaks, double-strand breaks, cross-links, point mutations, and chromosomal aberrations", optionC: "Only double-strand breaks", optionD: "No DNA damage", correctAnswer: "B", rationale: "Radiation causes multiple types of DNA damage: SSBs (most common, easily repaired), DSBs (more lethal, harder to repair), cross-links, and base mutations.", category: "Safety", topic: "Radiation Biology", difficulty: 2 },
  { question: "The latent period in radiation biology refers to:", optionA: "Time for DNA repair", optionB: "The time between radiation exposure and the clinical manifestation of biological effects", optionC: "The exposure time", optionD: "The time for electrons to travel", correctAnswer: "B", rationale: "Latent period: the interval between exposure and observable effects. Shorter for high doses (acute effects), longer for low doses (cancer may take 5-20+ years).", category: "Safety", topic: "Radiation Biology", difficulty: 2 },
  { question: "Dose fractionation reduces biological damage because:", optionA: "Each fraction has no effect", optionB: "Cells can repair sublethal damage between fractions, and repopulation occurs between treatments", optionC: "The total dose is reduced", optionD: "It changes the type of radiation", correctAnswer: "B", rationale: "Fractionation allows: repair of sublethal damage, redistribution of cells in the cell cycle, reoxygenation, and repopulation between fractions.", category: "Safety", topic: "Radiation Biology", difficulty: 2 },
  { question: "Which of the following organs is MOST radiosensitive?", optionA: "Muscle", optionB: "Lymphoid tissue and bone marrow", optionC: "Nerve tissue", optionD: "Cartilage", correctAnswer: "B", rationale: "Lymphoid tissue and bone marrow are highly radiosensitive (rapidly dividing, immature cells). Radiosensitivity ranking: lymphoid > bone marrow > GI > gonads > skin > bone > nerve > muscle.", category: "Safety", topic: "Radiation Biology", difficulty: 1 },
  { question: "Which of the following organs is MOST radioresistant?", optionA: "Bone marrow", optionB: "Nerve and muscle tissue (mature, non-dividing cells)", optionC: "Lymph nodes", optionD: "Intestinal epithelium", correctAnswer: "B", rationale: "Nerve cells and muscle cells are highly differentiated and non-dividing, making them the most radioresistant somatic cells.", category: "Safety", topic: "Radiation Biology", difficulty: 1 },
  { question: "Personal dosimeters should be worn:", optionA: "In the pocket", optionB: "At the collar level outside the lead apron (or at collar and waist if using two dosimeters)", optionC: "On the hand", optionD: "On the shoe", correctAnswer: "B", rationale: "Single dosimeter: collar level outside apron (worst-case head/neck exposure). Two dosimeters: collar outside + waist inside apron (for effective dose calculation).", category: "Safety", topic: "Personnel Monitoring", difficulty: 2 },
  { question: "A film badge dosimeter can detect doses as low as:", optionA: "0.01 mSv", optionB: "0.1 mSv (10 mrem)", optionC: "1 mSv", optionD: "5 mSv", correctAnswer: "B", rationale: "Film badge minimum detectable dose: ~0.1 mSv (10 mrem). OSL: ~0.01 mSv (1 mrem). TLD: ~0.05 mSv (5 mrem). OSL and TLD are more sensitive.", category: "Safety", topic: "Personnel Monitoring", difficulty: 3 },
  { question: "The purpose of the aluminum filter in a dosimeter badge is to:", optionA: "Protect the film", optionB: "Help distinguish between different types and energies of radiation by differential absorption", optionC: "Increase sensitivity", optionD: "Block all radiation", correctAnswer: "B", rationale: "Multiple filters (Al, Cu, Pb, open window) help identify radiation type and energy by comparing density under each filter.", category: "Safety", topic: "Personnel Monitoring", difficulty: 3 },
  { question: "The pocket ionization chamber dosimeter provides:", optionA: "Monthly dose readings", optionB: "Immediate, real-time dose readings but is easily discharged and not highly accurate", optionC: "Permanent dose records", optionD: "Energy discrimination", correctAnswer: "B", rationale: "Pocket dosimeters give immediate readings but are less accurate, can self-discharge (false high readings), and don't provide permanent records.", category: "Safety", topic: "Personnel Monitoring", difficulty: 2 },
  { question: "The NCRP cumulative lifetime dose limit formula is:", optionA: "Age × 10 mSv", optionB: "10 mSv × age in years", optionC: "50 mSv × age", optionD: "1 mSv × age", correctAnswer: "B", rationale: "NCRP cumulative limit: 10 mSv × age. For a 30-year-old: 10 × 30 = 300 mSv maximum cumulative lifetime dose.", category: "Safety", topic: "Dose Limits", difficulty: 2 },
  { question: "The concept of 'justification' in radiation protection means:", optionA: "All exams are automatically justified", optionB: "Every radiation exposure must have a net benefit that outweighs the risk — unnecessary exams should not be performed", optionC: "Only physicians can order X-rays", optionD: "Cost justification for equipment", correctAnswer: "B", rationale: "Justification: the first principle of ICRP — no exposure should be performed unless it produces a net benefit. The referring physician and radiologist share this responsibility.", category: "Safety", topic: "Radiation Protection", difficulty: 1 },
  { question: "EfD (effective dose) for a PA chest radiograph is approximately:", optionA: "0.001 mSv", optionB: "0.02 mSv (equivalent to about 2.4 days of natural background)", optionC: "1 mSv", optionD: "10 mSv", correctAnswer: "B", rationale: "PA chest effective dose: ~0.02 mSv. Lateral chest: ~0.04 mSv. CT chest: ~7 mSv. Useful for patient education using BERT.", category: "Safety", topic: "Dose Values", difficulty: 2 },
  { question: "The fluoroscopy maximum entrance exposure rate for standard operation is:", optionA: "5 R/min", optionB: "10 R/min (87 mGy/min)", optionC: "20 R/min", optionD: "2 R/min", correctAnswer: "B", rationale: "Standard fluoroscopy: maximum 10 R/min. High-level control (boost): 20 R/min. These limits are required by federal regulation.", category: "Safety", topic: "Fluoroscopy Safety", difficulty: 2 },
  { question: "The SSD for mobile C-arm fluoroscopy must be at least:", optionA: "15 inches", optionB: "12 inches (30 cm)", optionC: "18 inches", optionD: "6 inches", correctAnswer: "B", rationale: "Minimum SSD: 12 inches (30 cm) for mobile C-arms, 15 inches (38 cm) for fixed fluoroscopy. Greater distance reduces skin dose.", category: "Safety", topic: "Fluoroscopy Safety", difficulty: 2 },
  { question: "During pregnancy, ionizing radiation exposure during weeks 8-15 poses the greatest risk for:", optionA: "Limb defects", optionB: "Intellectual disability (mental retardation) at threshold doses >100 mGy", optionC: "Skin defects", optionD: "Heart defects", correctAnswer: "B", rationale: "Weeks 8-15 (CNS development period): greatest risk for intellectual disability/microcephaly. Threshold ~100-200 mGy. Below diagnostic levels.", category: "Safety", topic: "Embryo Protection", difficulty: 3 },
  { question: "Radiation hormesis is the theory that:", optionA: "All radiation is harmful", optionB: "Very small doses of radiation may stimulate protective biological mechanisms and be beneficial", optionC: "Radiation has no biological effect", optionD: "High doses are safe", correctAnswer: "B", rationale: "Hormesis: controversial theory that low-dose radiation stimulates DNA repair and immune function. NOT accepted as the basis for radiation protection (LNT model is used).", category: "Safety", topic: "Radiation Biology", difficulty: 3 },
  { question: "The use factor (U) for a secondary barrier is:", optionA: "0.25", optionB: "1 (always receiving scatter/leakage regardless of beam direction)", optionC: "0.5", optionD: "0", correctAnswer: "B", rationale: "Secondary barriers: U = 1 because they always receive scatter and leakage regardless of primary beam direction. Primary barriers: U varies (1 to 0.25).", category: "Safety", topic: "Structural Shielding", difficulty: 3 },
  { question: "Tissue weighting factor (WT) for the gonads is:", optionA: "0.01", optionB: "0.08 (ICRP 103)", optionC: "0.20", optionD: "0.12", correctAnswer: "B", rationale: "ICRP 103 WT values: gonads=0.08, bone marrow/colon/lung/stomach/breast=0.12 each. (Earlier ICRP 60 had gonads=0.20.)", category: "Safety", topic: "Dose Quantities", difficulty: 3 },
  { question: "A controlled area in a radiology department is defined as:", optionA: "An area open to the public", optionB: "An area where occupational exposure is possible and access is limited to authorized personnel", optionC: "A storage room", optionD: "A waiting room", correctAnswer: "B", rationale: "Controlled area: occupational exposure possible, access restricted, personnel monitored. Uncontrolled area: accessible to the public.", category: "Safety", topic: "Structural Shielding", difficulty: 1 },
  { question: "The ALARA program includes which key component?", optionA: "Eliminating all radiation use", optionB: "Management commitment, personnel monitoring, area monitoring, regular dose reviews, and corrective action for unusual exposures", optionC: "Maximum dose for all workers", optionD: "Only lead aprons", correctAnswer: "B", rationale: "ALARA program: management policy, personnel dosimetry, investigation levels (dose reviews), area surveys, equipment QC, education, and corrective actions.", category: "Safety", topic: "Radiation Protection", difficulty: 2 },
  { question: "Investigation level I (dose review trigger) is typically set at:", optionA: "5 mSv/month", optionB: "1 mSv/month (10% of annual limit on a monthly basis)", optionC: "50 mSv/month", optionD: "10 mSv/month", correctAnswer: "B", rationale: "Investigation Level I: approximately 1 mSv/month (triggers dose review and investigation). Level II: approximately 3-4 mSv/month (triggers corrective action).", category: "Safety", topic: "Personnel Monitoring", difficulty: 3 },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2`, [q.question, "usa"]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, exam, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'usa','arrt','published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty]
      );
      inserted++;
    }
  }
  console.log(`[Safety 4] Inserted ${inserted}/${QUESTIONS.length} USA ARRT questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
