import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

const QUESTIONS = [
  { question: "For a PA projection of the wrist, the fingers should be:", optionA: "Fully extended", optionB: "Slightly flexed (to bring the carpal bones closer to the IR and improve joint space visualization)", optionC: "In a tight fist", optionD: "Spread apart", correctAnswer: "B", rationale: "Slight finger flexion relaxes tendons and brings carpals closer to the IR. Full extension can open carpal joints unevenly.", category: "Procedures", topic: "Wrist", difficulty: 2 },
  { question: "The CR for a lateral wrist is directed to:", optionA: "The ulnar styloid", optionB: "The midcarpal area (scaphoid region)", optionC: "The radial styloid", optionD: "The DRUJ", correctAnswer: "B", rationale: "Lateral wrist: CR perpendicular to the midcarpal area. Demonstrates carpal alignment (lunate-capitate relationship).", category: "Procedures", topic: "Wrist", difficulty: 1 },
  { question: "The Merchant method of the patella uses a CR angle of:", optionA: "60 degrees", optionB: "30 degrees from the horizontal (both knees flexed 45° over the end of the table)", optionC: "0 degrees", optionD: "90 degrees", correctAnswer: "B", rationale: "Merchant: supine, knees over table edge flexed 45°, axial/tangential beam from above at 30° to the shin. Bilateral comparison of patellofemoral alignment.", category: "Procedures", topic: "Knee", difficulty: 3 },
  { question: "The Holmblad method for the intercondylar fossa has the patient:", optionA: "Supine", optionB: "Kneeling on the table with the femur angled 20-30° from vertical, CR horizontal to the knee joint", optionC: "Prone with legs extended", optionD: "Standing facing away", correctAnswer: "B", rationale: "Holmblad: patient kneels on table, leaning forward 20-30°, CR perpendicular to the IR (horizontal). Alternative to the Camp-Coventry tunnel view.", category: "Procedures", topic: "Knee", difficulty: 3 },
  { question: "For the AP oblique (external rotation) wrist, the wrist is rotated:", optionA: "Medially 45°", optionB: "Laterally (externally) 45° to demonstrate the trapezium and scaphoid without overlap", optionC: "90° lateral", optionD: "15° medially", correctAnswer: "B", rationale: "External oblique wrist: 45° lateral rotation. Demonstrates trapezium, scaphoid, and first metacarpal-trapezium joint.", category: "Procedures", topic: "Wrist", difficulty: 2 },
  { question: "The AP oblique (medial rotation) wrist demonstrates:", optionA: "Scaphoid and trapezium", optionB: "Triquetrum, pisiform, and hamate hook without overlap", optionC: "Lunate only", optionD: "Capitate", correctAnswer: "B", rationale: "Medial (internal) oblique wrist: 45° medial rotation. Demonstrates pisiform, triquetrum, and hook of hamate.", category: "Procedures", topic: "Wrist", difficulty: 2 },
  { question: "For the AP thumb (1st digit), the hand must be:", optionA: "Pronated palm down", optionB: "Rotated until the thumb lies flat on the IR in anatomical position (extreme internal rotation of the arm)", optionC: "In a lateral position", optionD: "In a fist", correctAnswer: "B", rationale: "True AP thumb: extreme internal arm rotation to place thumb flat on IR. Alternatively, place thumb on IR and angle tube. Both eliminate obliquity.", category: "Procedures", topic: "Thumb", difficulty: 2 },
  { question: "The tangential (inferosuperior) projection for the bicipital groove (Fisk method) demonstrates:", optionA: "The glenoid fossa", optionB: "The bicipital (intertubercular) groove between the greater and lesser tubercles of the humerus", optionC: "The acromion", optionD: "The rotator cuff", correctAnswer: "B", rationale: "Fisk method: arm supinated, IR on top of shoulder, CR angled inferosuperior through the bicipital groove. Shows groove depth and any osteophytes.", category: "Procedures", topic: "Shoulder", difficulty: 3 },
  { question: "A Ferguson view of the lumbar spine is an AP projection with:", optionA: "No angle", optionB: "30-35 degrees cephalad angle to demonstrate the L5-S1 junction and lumbosacral angle", optionC: "15 degrees caudad", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "Ferguson view: 30-35° cephalad from AP projects through the L5-S1 joint, opening it up. Used to evaluate spondylolisthesis and lumbosacral junction.", category: "Procedures", topic: "Lumbar Spine", difficulty: 3 },
  { question: "Inlet and outlet pelvic views are performed to evaluate:", optionA: "The hip joints only", optionB: "Pelvic ring fractures — inlet shows anterior/posterior displacement, outlet shows superior/inferior displacement", optionC: "The sacrum only", optionD: "The SI joints", correctAnswer: "B", rationale: "Inlet: 40° caudad — demonstrates pelvic brim, anterior/posterior displacement. Outlet: 40° cephalad — demonstrates ischiopubic rami, superior/inferior displacement.", category: "Procedures", topic: "Pelvis", difficulty: 3 },
  { question: "The proper respiration for above-diaphragm rib series is:", optionA: "Expiration", optionB: "Full inspiration (elevates diaphragm less, expanding the lungs to provide better contrast against upper ribs)", optionC: "Normal breathing", optionD: "Valsalva maneuver", correctAnswer: "B", rationale: "Above-diaphragm ribs: full inspiration expands lung air (providing contrast against bony ribs). Below-diaphragm ribs: expiration to push diaphragm up.", category: "Procedures", topic: "Ribs", difficulty: 1 },
  { question: "The Fuchs method demonstrates the dens using:", optionA: "Open mouth AP", optionB: "AP projection through the foramen magnum (patient's head extended until MML is perpendicular to IR)", optionC: "Lateral projection", optionD: "PA projection", correctAnswer: "B", rationale: "Fuchs: AP axial with maximum head extension so the dens projects within the foramen magnum. Alternative to the open-mouth view.", category: "Procedures", topic: "Cervical Spine", difficulty: 3 },
  { question: "The proper technique for cystography involves:", optionA: "IV contrast injection", optionB: "Retrograde filling of the bladder through a urinary catheter with dilute contrast under fluoroscopy", optionC: "Oral contrast", optionD: "Rectal contrast", correctAnswer: "B", rationale: "Cystography: contrast instilled into the bladder via Foley catheter. Evaluates bladder integrity, reflux, and capacity.", category: "Procedures", topic: "Special Procedures", difficulty: 2 },
  { question: "An ERCP (endoscopic retrograde cholangiopancreatography) involves:", optionA: "IV injection", optionB: "Endoscopic cannulation of the common bile duct and pancreatic duct with contrast injection under fluoroscopy", optionC: "Oral contrast", optionD: "Percutaneous injection", correctAnswer: "B", rationale: "ERCP: endoscope through the mouth to the ampulla of Vater, where a catheter is inserted into the bile/pancreatic ducts for contrast injection.", category: "Procedures", topic: "Special Procedures", difficulty: 2 },
  { question: "The oblique sternum (RAO) position requires rotation of approximately:", optionA: "45 degrees", optionB: "15-20 degrees (just enough to project the sternum over the heart shadow without excessive rotation)", optionC: "5 degrees", optionD: "30 degrees", correctAnswer: "B", rationale: "15-20° RAO places the sternum over the homogeneous cardiac silhouette. Too much rotation moves the sternum over the lung (poor contrast).", category: "Procedures", topic: "Sternum", difficulty: 2 },
  { question: "The SC (sternoclavicular) joints are best demonstrated on:", optionA: "AP projection", optionB: "PA oblique projections (RAO or LAO) with slight (10-15°) rotation to separate the joints from the spine", optionC: "Lateral projection only", optionD: "AP axial projection", correctAnswer: "B", rationale: "PA oblique (10-15° rotation): projects the SC joint away from the spine for clear visualization. Both sides should be examined for comparison.", category: "Procedures", topic: "Sternum", difficulty: 2 },
  { question: "The Waters view requires the patient to extend the chin until the:", optionA: "OML is perpendicular to IR", optionB: "MML (mentomeatal line) is perpendicular to the IR (OML forms 37° with IR)", optionC: "AML is perpendicular to IR", optionD: "IOML is parallel to IR", correctAnswer: "B", rationale: "Waters positioning line: MML perpendicular to IR. This tilts the OML 37° to the IR, projecting the petrous ridges below the maxillary sinuses.", category: "Procedures", topic: "Facial Bones", difficulty: 2 },
  { question: "The reverse Waters (AP parietoacanthial) is performed when the patient:", optionA: "Can sit upright", optionB: "Cannot be positioned prone/erect for standard PA Waters (trauma patient supine)", optionC: "Needs sinus evaluation", optionD: "Needs orbit views", correctAnswer: "B", rationale: "Reverse Waters: AP projection for trauma patients who cannot be positioned for the standard PA Waters. Same angle, reversed beam direction.", category: "Procedures", topic: "Facial Bones", difficulty: 2 },
  { question: "The modified Law projection demonstrates:", optionA: "The nasal bones", optionB: "The mastoid air cells and petrous portion of the temporal bone", optionC: "The sinuses", optionD: "The orbits", correctAnswer: "B", rationale: "Modified Law: 15° rotation with 15° caudad CR. Demonstrates mastoid air cells and petrous pyramid. Largely replaced by CT.", category: "Procedures", topic: "Temporal Bone", difficulty: 3 },
  { question: "The AP axial projection of the zygomatic arches requires a CR angle of:", optionA: "15 degrees caudad", optionB: "30 degrees caudad (modified Towne for arches)", optionC: "0 degrees", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "AP axial zygomatic arches: 30° caudad (similar to Towne but for arches). Alternatively, the SMV is the preferred view for bilateral arches.", category: "Procedures", topic: "Facial Bones", difficulty: 3 },
  { question: "The optic foramen is demonstrated using the:", optionA: "Caldwell projection", optionB: "Rhese method (PA oblique orbit) with the head positioned so the AML is perpendicular and the MSP forms a 53° angle with IR", optionC: "Towne projection", optionD: "Waters projection", correctAnswer: "B", rationale: "Rhese (parieto-orbital oblique): demonstrates the optic foramen in the lower outer quadrant of the orbit. Three-point positioning method. Largely replaced by CT.", category: "Procedures", topic: "Orbits", difficulty: 3 },
  { question: "For the AP projection of the toes, the CR enters:", optionA: "The ankle", optionB: "At the level of the MTP joints, directed posteriorly (toward the heel) at 10-15 degrees", optionC: "At the tips of the toes", optionD: "At the midfoot", correctAnswer: "B", rationale: "AP toes: CR to MTP joints with 10-15° posterior angle to open the joint spaces (similar to foot technique but focused on the toes).", category: "Procedures", topic: "Toes", difficulty: 1 },
  { question: "The Jones fracture occurs at the:", optionA: "1st metatarsal head", optionB: "Base of the 5th metatarsal (proximal diaphysis/metadiaphyseal junction)", optionC: "Calcaneus", optionD: "Navicular", correctAnswer: "B", rationale: "Jones fracture: base of 5th metatarsal at the metadiaphyseal junction (proximal shaft). Different from avulsion fracture (tuberosity). Best seen on oblique foot.", category: "Procedures", topic: "Foot", difficulty: 2 },
  { question: "Monteggia fracture-dislocation involves:", optionA: "Radial shaft fracture with distal radioulnar joint disruption", optionB: "Proximal ulna fracture with dislocation of the radial head", optionC: "Both bone forearm fracture", optionD: "Distal radius fracture", correctAnswer: "B", rationale: "Monteggia: proximal 1/3 ulna fracture + radial head dislocation. Galeazzi: distal 1/3 radius fracture + DRUJ dislocation. Must include both joints!", category: "Procedures", topic: "Forearm", difficulty: 2 },
  { question: "Galeazzi fracture-dislocation involves:", optionA: "Proximal ulna fracture with radial head dislocation", optionB: "Distal radius fracture with disruption of the distal radioulnar joint (DRUJ)", optionC: "Scaphoid fracture", optionD: "Olecranon fracture", correctAnswer: "B", rationale: "Galeazzi: distal 1/3 radius fracture + DRUJ disruption. Opposite of Monteggia. This is why both joints must be included on forearm radiographs.", category: "Procedures", topic: "Forearm", difficulty: 2 },
  { question: "A Colles fracture is a fracture of the:", optionA: "Radial head", optionB: "Distal radius with dorsal (posterior) displacement of the distal fragment", optionC: "Ulnar styloid", optionD: "Scaphoid", correctAnswer: "B", rationale: "Colles: distal radius fracture with posterior (dorsal) displacement — 'silver fork' deformity on lateral view. Smith fracture: anterior (volar) displacement.", category: "Procedures", topic: "Wrist", difficulty: 1 },
  { question: "A Smith fracture differs from a Colles fracture in that the distal fragment is displaced:", optionA: "Dorsally (posteriorly)", optionB: "Volarly (anteriorly) — 'reverse Colles' or 'garden spade' deformity", optionC: "Laterally", optionD: "Proximally", correctAnswer: "B", rationale: "Smith fracture: distal radius with volar (anterior) displacement. Colles: dorsal (posterior) displacement. Both are common distal radius fractures.", category: "Procedures", topic: "Wrist", difficulty: 2 },
  { question: "Boxer's fracture typically involves fracture of the:", optionA: "1st metacarpal base", optionB: "5th metacarpal neck with volar angulation of the distal fragment", optionC: "Scaphoid", optionD: "Distal radius", correctAnswer: "B", rationale: "Boxer's fracture: 5th metacarpal neck fracture with volar (anterior) angulation. Caused by punching with a closed fist.", category: "Procedures", topic: "Hand", difficulty: 1 },
  { question: "Bennett fracture involves:", optionA: "5th metacarpal neck", optionB: "Fracture-dislocation of the base of the 1st metacarpal at the CMC joint", optionC: "Phalangeal fracture", optionD: "Scaphoid fracture", correctAnswer: "B", rationale: "Bennett: intra-articular fracture-dislocation at the base of the 1st metacarpal (thumb CMC joint). Requires surgical fixation.", category: "Procedures", topic: "Thumb", difficulty: 2 },
  { question: "A Lisfranc injury involves disruption of the:", optionA: "Ankle joint", optionB: "Tarsometatarsal (TMT) joints — fracture and/or dislocation at the midfoot", optionC: "Subtalar joint", optionD: "IP joints", correctAnswer: "B", rationale: "Lisfranc: tarsometatarsal joint complex injury. Check for widening between 1st and 2nd metatarsal bases on AP foot. May require weight-bearing views.", category: "Procedures", topic: "Foot", difficulty: 2 },
  { question: "The lateral decubitus chest is taken with the patient lying on their side and the X-ray beam directed:", optionA: "Vertically (downward)", optionB: "Horizontally (cross-table) to demonstrate air-fluid levels", optionC: "At 45 degrees", optionD: "At 90 degrees cephalad", correctAnswer: "B", rationale: "Lateral decubitus uses a horizontal beam. Air rises to the non-dependent side (up), fluid layers on the dependent side (down).", category: "Procedures", topic: "Chest", difficulty: 1 },
  { question: "For the Caldwell projection, the petrous ridges should project:", optionA: "Below the maxillary sinuses", optionB: "Into the lower third of the orbits", optionC: "Above the orbits", optionD: "Into the upper third of the orbits", correctAnswer: "B", rationale: "Caldwell (15° caudad PA): petrous ridges in the lower 1/3 of the orbits. If ridges are at the infraorbital rim = 0° (straight PA). Below sinuses = Waters (37°).", category: "Procedures", topic: "Skull", difficulty: 2 },
  { question: "Lateral soft tissue neck radiographs evaluate:", optionA: "Cervical vertebrae alignment", optionB: "Prevertebral soft tissue width, epiglottis, retropharyngeal space, and adenoidal tissue in children", optionC: "The skull", optionD: "The mandible", correctAnswer: "B", rationale: "Soft tissue lateral neck: evaluate airway, prevertebral soft tissue (widening = hemorrhage/abscess), epiglottis (epiglottitis), and adenoids in children.", category: "Procedures", topic: "Soft Tissue", difficulty: 2 },
  { question: "A panoramic radiograph (Panorex/OPG) demonstrates:", optionA: "Individual teeth detail", optionB: "The entire mandible, maxilla, dentition, TMJs, and surrounding structures on a single curved image", optionC: "Only the sinuses", optionD: "Only the TMJ", correctAnswer: "B", rationale: "Panoramic radiography: the tube and detector rotate around the patient's head, producing a continuous image of the entire mandible and maxilla.", category: "Procedures", topic: "Mandible", difficulty: 1 },
  { question: "The proper patient preparation for an IVU (intravenous urography) typically includes:", optionA: "No preparation needed", optionB: "Light diet the day before, laxative the evening before (if ordered), NPO after midnight, and assessment of renal function", optionC: "Full meal before the exam", optionD: "Heavy fluid intake the morning of", correctAnswer: "B", rationale: "IVU prep: bowel cleansing (clearer images), NPO (reduce aspiration risk, dehydration concentrates contrast in kidneys), and verify BUN/creatinine.", category: "Procedures", topic: "Urography", difficulty: 2 },
  { question: "The ureteric compression device (paddle) used during IVU is placed:", optionA: "Over the kidneys", optionB: "Over both ureters at the level of the ASIS to temporarily distend the renal collecting systems for better opacification", optionC: "Over the bladder", optionD: "Under the patient", correctAnswer: "B", rationale: "Compression at the ASIS level temporarily obstructs the ureters, causing contrast to accumulate in the renal pelvis and calyces for better visualization.", category: "Procedures", topic: "Urography", difficulty: 2 },
  { question: "Compression is contraindicated during IVU when the patient has:", optionA: "Normal kidney function", optionB: "Ureteral calculi, abdominal aortic aneurysm, recent abdominal surgery, or abdominal mass", optionC: "No contraindications exist", optionD: "High blood pressure only", correctAnswer: "B", rationale: "Compression contraindicated: ureteral stones (could cause rupture), AAA, recent surgery, abdominal mass, transplanted kidney.", category: "Procedures", topic: "Urography", difficulty: 2 },
  { question: "The posteroanterior (PA) oblique projection of the lumbar spine using LAO position demonstrates:", optionA: "Left zygapophyseal joints", optionB: "Right zygapophyseal joints (upside/farthest from IR in anterior oblique)", optionC: "Both SI joints", optionD: "The sacrum", correctAnswer: "B", rationale: "Anterior obliques demonstrate joints FARTHEST from IR: LAO = right joints, RAO = left joints. Posterior obliques demonstrate joints CLOSEST to IR.", category: "Procedures", topic: "Lumbar Spine", difficulty: 2 },
  { question: "The RPO lumbar spine position demonstrates the:", optionA: "Left zygapophyseal joints", optionB: "Right zygapophyseal joints (downside/closest to IR in posterior oblique)", optionC: "Left SI joint", optionD: "Right pedicles", correctAnswer: "B", rationale: "Posterior obliques demonstrate joints CLOSEST to IR: RPO = right joints, LPO = left joints. 45° rotation for the scotty dog appearance.", category: "Procedures", topic: "Lumbar Spine", difficulty: 2 },
  { question: "The child abuse (skeletal survey) series typically includes radiographs of:", optionA: "Only the skull", optionB: "AP and lateral skull, AP chest, AP abdomen/pelvis, AP long bones of all extremities — comprehensive skeletal evaluation", optionC: "Only the limbs", optionD: "CT only", correctAnswer: "B", rationale: "Skeletal survey for suspected child abuse: entire skeleton including skull (multiple), chest, spine, pelvis, and all extremities. Follow ACR guidelines.", category: "Procedures", topic: "Pediatric", difficulty: 2 },
  { question: "The lateral projection of the nasal bones uses a:", optionA: "40-inch SID", optionB: "Reduced SID (36 inches) with fine detail technique for these small bones", optionC: "72-inch SID", optionD: "48-inch SID", correctAnswer: "B", rationale: "Lateral nasal bones: 36\" SID for slight magnification, fine detail (small focal spot), soft tissue technique (50-55 kVp). Both sides should be imaged.", category: "Procedures", topic: "Facial Bones", difficulty: 2 },
  { question: "An AP projection of the tibia/fibula must include:", optionA: "Only one joint", optionB: "Both ankle and knee joints (entire tibia and fibula with both articulations)", optionC: "Only the fracture site", optionD: "Only the knee", correctAnswer: "B", rationale: "Like the forearm, the tibia/fibula radiograph must include both joints to rule out associated proximal or distal injuries (e.g., Maisonneuve fracture).", category: "Procedures", topic: "Lower Leg", difficulty: 1 },
  { question: "The RAO position during an esophagram is used to demonstrate the esophagus:", optionA: "Superimposed on the spine", optionB: "Between the vertebral column and the heart shadow for clearest visualization", optionC: "Behind the sternum", optionD: "Lateral to the spine", correctAnswer: "B", rationale: "35-40° RAO: projects the esophagus between the spine and heart, providing optimal visualization without vertebral superimposition.", category: "Procedures", topic: "GI Studies", difficulty: 2 },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2`, [q.question, "usa"]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, exam, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'usa','arrt','published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty]
      );
      inserted++;
    }
  }
  console.log(`[Procedures 5] Inserted ${inserted}/${QUESTIONS.length} USA ARRT questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
