import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

const QUESTIONS = [
  { question: "The AP oblique (Grashey) projection of the shoulder requires the body to be rotated:", optionA: "15-20 degrees", optionB: "35-45 degrees toward the affected side", optionC: "90 degrees", optionD: "No rotation", correctAnswer: "B", rationale: "35-45° rotation places the glenoid fossa in profile, opening the glenohumeral joint space for clear visualization.", category: "Procedures", topic: "Shoulder", difficulty: 2 },
  { question: "The AP oblique (internal) elbow projection best demonstrates:", optionA: "The radial head", optionB: "The coronoid process in profile", optionC: "The olecranon", optionD: "The capitulum", correctAnswer: "B", rationale: "Internal (medial) rotation demonstrates the coronoid process. External (lateral) rotation demonstrates the radial head free of ulnar overlap.", category: "Procedures", topic: "Elbow", difficulty: 2 },
  { question: "For the lateral wrist, the hand is positioned with the:", optionA: "Palm down", optionB: "Ulnar side (little finger side) against the IR, thumb up", optionC: "Palm up", optionD: "Fingers spread", correctAnswer: "B", rationale: "Lateral wrist: ulnar side down, thumb up. This provides a true lateral with radius and ulna superimposed.", category: "Procedures", topic: "Wrist", difficulty: 1 },
  { question: "The carpal tunnel (Gaynor-Hart) projection demonstrates:", optionA: "Scaphoid", optionB: "Carpal canal contents (flexor tendons, median nerve space, hook of hamate, trapezium)", optionC: "Distal radius fracture", optionD: "Lunate dislocation", correctAnswer: "B", rationale: "Gaynor-Hart: tangential projection through the carpal canal. Demonstrates the carpal tunnel, hook of hamate, and trapezium.", category: "Procedures", topic: "Wrist", difficulty: 2 },
  { question: "When positioning for an AP forearm, the hand must be:", optionA: "Pronated (palm down)", optionB: "Supinated (palm up) to prevent radius/ulna crossover", optionC: "In a fist", optionD: "Flexed at the wrist", correctAnswer: "B", rationale: "Supination for AP forearm places radius and ulna parallel, preventing crossover. Pronation causes radius to cross over ulna (PA forearm).", category: "Procedures", topic: "Forearm", difficulty: 1 },
  { question: "The tangential (sunrise/skyline) projection of the patella is performed to evaluate:", optionA: "The tibial plateau", optionB: "Patellar tracking and alignment within the trochlear groove (patellofemoral joint)", optionC: "The intercondylar fossa", optionD: "The proximal fibula", correctAnswer: "B", rationale: "Tangential patella views assess patellar alignment, subluxation, fractures, and the patellofemoral joint space.", category: "Procedures", topic: "Knee", difficulty: 2 },
  { question: "The lateral decubitus position for evaluating pleural effusion requires the affected side to be:", optionA: "Up (elevated)", optionB: "Down (dependent) so fluid layers along the lateral chest wall", optionC: "Anterior", optionD: "Posterior", correctAnswer: "B", rationale: "Affected side DOWN for effusion: gravity causes fluid to layer along the dependent chest wall, making it visible as a meniscus.", category: "Procedures", topic: "Chest", difficulty: 2 },
  { question: "The PA oblique (RAO) esophagus position demonstrates the esophagus:", optionA: "Behind the sternum", optionB: "Between the spine and heart, free of vertebral superimposition", optionC: "Superimposed on the spine", optionD: "Behind the heart", correctAnswer: "B", rationale: "RAO: rotates the esophagus away from the spine into the space between the spine and heart for clear visualization with barium.", category: "Procedures", topic: "GI Studies", difficulty: 2 },
  { question: "Small bowel follow-through (SBFT) images are taken at intervals of:", optionA: "Every 5 minutes", optionB: "Every 15-30 minutes until barium reaches the ileocecal valve/cecum", optionC: "Every hour", optionD: "One image only", correctAnswer: "B", rationale: "SBFT: images taken every 15-30 minutes to track barium progress through the small bowel until it reaches the ileocecal valve/cecum (typically 1-2 hours).", category: "Procedures", topic: "GI Studies", difficulty: 2 },
  { question: "The double-contrast barium enema uses:", optionA: "Only barium", optionB: "Barium to coat the mucosa AND air to distend the colon for mucosal detail", optionC: "Only air", optionD: "Barium and water", correctAnswer: "B", rationale: "Double contrast: barium coats the mucosa surface, air distends the colon. This provides superior mucosal detail for polyps and early cancers.", category: "Procedures", topic: "GI Studies", difficulty: 1 },
  { question: "The proper method for inserting a barium enema tip is to:", optionA: "Insert rapidly", optionB: "With the patient in Sims position, gently insert the lubricated tip anteriorly toward the umbilicus following the rectum anatomy", optionC: "With the patient prone", optionD: "Without lubrication", correctAnswer: "B", rationale: "Sims position (left lateral, right knee flexed). Lubricated tip inserted gently toward the umbilicus. Never force the tip.", category: "Procedures", topic: "GI Studies", difficulty: 2 },
  { question: "The Trendelenburg position during a barium enema is used to:", optionA: "Empty the colon", optionB: "Fill the transverse colon and hepatic/splenic flexures with barium using gravity", optionC: "Demonstrate free air", optionD: "Reduce patient anxiety", correctAnswer: "B", rationale: "Trendelenburg (head down): gravity helps fill the transverse colon and flexures. This position is used during fluoroscopic filling of the colon.", category: "Procedures", topic: "GI Studies", difficulty: 2 },
  { question: "During an IVU, the nephrogram phase occurs at approximately:", optionA: "30 seconds", optionB: "1-3 minutes after injection", optionC: "10 minutes", optionD: "30 minutes", correctAnswer: "B", rationale: "Nephrogram phase (1-3 min): contrast fills the renal tubules, creating a homogeneous blush of the kidney parenchyma. Pyelogram phase: 5+ min.", category: "Procedures", topic: "Urography", difficulty: 2 },
  { question: "A post-void radiograph during an IVU is taken to:", optionA: "Demonstrate the nephrogram", optionB: "Evaluate bladder emptying and detect any retained contrast or pathology obscured by a full bladder", optionC: "Show the ureters", optionD: "Measure kidney size", correctAnswer: "B", rationale: "Post-void film: evaluates residual urine (incomplete emptying), demonstrates anatomy previously obscured by the full bladder, and shows the distal ureters.", category: "Procedures", topic: "Urography", difficulty: 2 },
  { question: "The myelogram procedure involves injection of contrast into the:", optionA: "Joint space", optionB: "Subarachnoid space (spinal canal) via lumbar puncture", optionC: "Disc space", optionD: "Epidural space", correctAnswer: "B", rationale: "Myelography: non-ionic contrast injected into the subarachnoid space to evaluate spinal cord, nerve roots, and spinal canal (now largely replaced by MRI).", category: "Procedures", topic: "Special Procedures", difficulty: 2 },
  { question: "An arthrogram involves injection of contrast into:", optionA: "A blood vessel", optionB: "A joint space (shoulder, knee, hip) to evaluate internal joint structures", optionC: "The spinal canal", optionD: "The GI tract", correctAnswer: "B", rationale: "Arthrography: contrast (and/or air) injected into a joint to evaluate cartilage, ligaments, tendons, and joint capsule integrity.", category: "Procedures", topic: "Special Procedures", difficulty: 1 },
  { question: "The Trendelenburg chest position (AP with caudad tilt) is sometimes confused with the:", optionA: "Lordotic view", optionB: "AP lordotic projection which projects the clavicles above the lung apices", optionC: "PA chest", optionD: "Lateral chest", correctAnswer: "B", rationale: "AP lordotic: patient leans back against upright Bucky. Projects clavicles above apices for improved visualization of the lung apices and middle lobe.", category: "Procedures", topic: "Chest", difficulty: 2 },
  { question: "The PA projection of the chest is preferred over AP because:", optionA: "It is easier to position", optionB: "The heart is closer to the IR (reducing cardiac magnification), and anterior structures (breast, thyroid) receive less entrance dose", optionC: "It produces higher contrast", optionD: "It requires less technique", correctAnswer: "B", rationale: "PA chest: heart closer to IR = less magnification. Anterior radiosensitive structures (breast/thyroid) are farther from the beam entrance.", category: "Procedures", topic: "Chest", difficulty: 1 },
  { question: "OSSIFICATION centers of the elbow appear in a specific order. The mnemonic CRITOE represents:", optionA: "Cervical rib indicators", optionB: "Capitellum(1yr), Radial head(3yr), Internal(medial) epicondyle(5yr), Trochlea(7yr), Olecranon(9yr), External(lateral) epicondyle(11yr)", optionC: "Carpal bone names", optionD: "Vertebral landmarks", correctAnswer: "B", rationale: "CRITOE: ossification order and approximate ages for pediatric elbow evaluation. Important for distinguishing fractures from normal ossification centers.", category: "Procedures", topic: "Pediatric", difficulty: 3 },
  { question: "The AP projection of the thoracic spine uses CR directed to:", optionA: "T1", optionB: "T7 (inferior angle of scapulae)", optionC: "T12", optionD: "T4", correctAnswer: "B", rationale: "AP thoracic spine: CR to T7, which corresponds to the inferior angle of the scapulae. This centers T1-T12 on the image.", category: "Procedures", topic: "Thoracic Spine", difficulty: 1 },
  { question: "The AP supine abdomen (KUB) must include from:", optionA: "Iliac crests to umbilicus", optionB: "Symphysis pubis to diaphragm (entire abdomen)", optionC: "ASIS to ASIS", optionD: "Only the kidney region", correctAnswer: "B", rationale: "KUB: from the symphysis pubis inferiorly to the diaphragm superiorly. Must include the entire abdomen for complete evaluation.", category: "Procedures", topic: "Abdomen", difficulty: 1 },
  { question: "Posterior oblique positions of the cervical spine demonstrate the intervertebral foramina:", optionA: "Farthest from the IR", optionB: "Closest to the IR (downside foramina)", optionC: "On both sides equally", optionD: "Not at all", correctAnswer: "B", rationale: "Posterior obliques (RPO/LPO) demonstrate foramina closest to IR. RPO = right foramina. LPO = left foramina. (Opposite for anterior obliques.)", category: "Procedures", topic: "Cervical Spine", difficulty: 2 },
  { question: "Anterior oblique positions of the cervical spine demonstrate the intervertebral foramina:", optionA: "Closest to the IR", optionB: "Farthest from the IR (upside foramina)", optionC: "On neither side", optionD: "Only posterior elements", correctAnswer: "B", rationale: "Anterior obliques (RAO/LAO) demonstrate foramina farthest from IR. RAO = left foramina. LAO = right foramina. (Opposite for posterior obliques.)", category: "Procedures", topic: "Cervical Spine", difficulty: 2 },
  { question: "For radiographic examination of the ribs below the diaphragm, the patient should:", optionA: "Inspire deeply", optionB: "Expire to lower the diaphragm, revealing the lower ribs", optionC: "Hold breath at mid-inspiration", optionD: "Breathe normally", correctAnswer: "B", rationale: "Expiration depresses the diaphragm, revealing lower ribs (8th-12th). Inspiration elevates the diaphragm for above-diaphragm rib visualization.", category: "Procedures", topic: "Ribs", difficulty: 1 },
  { question: "The Judd method demonstrates:", optionA: "The knee", optionB: "The dens (odontoid process) in the AP projection with the mouth closed", optionC: "The pelvis", optionD: "The sacrum", correctAnswer: "B", rationale: "Judd method: AP axial projection demonstrating the odontoid process with the mouth closed. Uses cephalad angle to project dens above the occiput.", category: "Procedures", topic: "Cervical Spine", difficulty: 3 },
  { question: "The modified Cleaves (bilateral frog-leg) method of the hip demonstrates:", optionA: "AP pelvis only", optionB: "Both femoral heads and necks in a lateral-like perspective simultaneously", optionC: "The sacrum", optionD: "The lumbar spine", correctAnswer: "B", rationale: "Bilateral modified Cleaves: both hips in frog-leg position simultaneously. Shows femoral heads/necks bilaterally for comparison. Contraindicated in fracture.", category: "Procedures", topic: "Hip", difficulty: 2 },
  { question: "A Pigg-O-Stat is a device used for:", optionA: "Adult chest radiography", optionB: "Immobilizing infants/toddlers in an upright position for chest and abdominal radiographs", optionC: "Measuring SID", optionD: "Grid alignment", correctAnswer: "B", rationale: "Pigg-O-Stat: infant immobilization device that holds the child upright for erect PA/AP chest radiographs. Allows consistent positioning with minimal restraint.", category: "Procedures", topic: "Pediatric", difficulty: 1 },
  { question: "For the AP projection of both SI (sacroiliac) joints, the CR is angled:", optionA: "Perpendicular", optionB: "30-35 degrees cephalad to enter at the ASIS level", optionC: "15 degrees caudad", optionD: "45 degrees cephalad", correctAnswer: "B", rationale: "AP axial SI joints: 30-35° cephalad projects the SI joints open. Obliques (25-30° rotation) demonstrate individual SI joints.", category: "Procedures", topic: "Pelvis", difficulty: 3 },
  { question: "The plantodorsal (axial) projection of the foot is also known as:", optionA: "AP foot", optionB: "Harris-Beath calcaneal view — demonstrating the subtalar joint and posterior facets", optionC: "Lateral foot", optionD: "Oblique foot", correctAnswer: "B", rationale: "Harris-Beath: weightbearing plantodorsal axial view of the calcaneus showing subtalar joint and posterior facet alignment.", category: "Procedures", topic: "Calcaneus", difficulty: 3 },
  { question: "For an AP projection of the toes, the CR is angled:", optionA: "Perpendicular", optionB: "10-15 degrees posteriorly (toward the heel) to open the MTP joint spaces", optionC: "20 degrees anteriorly", optionD: "30 degrees cephalad", correctAnswer: "B", rationale: "10-15° posterior angle for AP toes opens the MTP joint spaces, similar to the 10° posterior angle for AP foot.", category: "Procedures", topic: "Toes", difficulty: 2 },
  { question: "The Settegast method demonstrates the patella using:", optionA: "AP projection", optionB: "A tangential (axial) projection with the knee flexed 90° or more, CR directed cephalad through the patellofemoral joint", optionC: "Lateral projection", optionD: "Tunnel view", correctAnswer: "B", rationale: "Settegast: prone, knee flexed >90°, CR tangential through the patellofemoral joint. Demonstrates patella and femoral intercondylar sulcus.", category: "Procedures", topic: "Knee", difficulty: 3 },
  { question: "The Coyle method for the elbow is performed when the patient:", optionA: "Can fully extend the elbow", optionB: "Cannot extend the elbow fully — uses specific angles through the partially flexed elbow to demonstrate the radial head or coronoid", optionC: "Needs a lateral view only", optionD: "Has a shoulder injury", correctAnswer: "B", rationale: "Coyle method: for trauma patients who can't extend. 45° toward shoulder = radial head. 45° away from shoulder = coronoid process.", category: "Procedures", topic: "Elbow", difficulty: 3 },
  { question: "Nasal bone radiographs typically use a SID of:", optionA: "40 inches", optionB: "36 inches (shorter SID for slight magnification of the small nasal bones)", optionC: "72 inches", optionD: "48 inches", correctAnswer: "B", rationale: "Lateral nasal bones: 36\" SID provides slight magnification of the small nasal bones for better visualization. Bilateral laterals recommended.", category: "Procedures", topic: "Facial Bones", difficulty: 2 },
  { question: "For the AP axial (Towne) projection, if the IOML is used instead of the OML, the CR angle is adjusted to:", optionA: "30 degrees caudad", optionB: "37 degrees caudad (7 degrees more than OML reference)", optionC: "25 degrees caudad", optionD: "45 degrees caudad", correctAnswer: "B", rationale: "There is ~7° difference between OML and IOML. If IOML perpendicular: 37° caudad. If OML perpendicular: 30° caudad. Same result.", category: "Procedures", topic: "Skull", difficulty: 2 },
  { question: "The horizontal beam lateral abdomen is performed to demonstrate:", optionA: "Bowel gas pattern only", optionB: "Air-fluid levels and/or free air when the patient cannot be positioned erect", optionC: "Kidney stones", optionD: "Spine pathology", correctAnswer: "B", rationale: "Horizontal beam (decubitus or cross-table lateral) demonstrates air-fluid levels. Required for acute abdomen evaluation when patient cannot stand.", category: "Procedures", topic: "Abdomen", difficulty: 1 },
  { question: "Hysterosalpingography (HSG) is performed to evaluate:", optionA: "The bladder", optionB: "The uterine cavity and fallopian tube patency (tubal patency for infertility evaluation)", optionC: "The kidneys", optionD: "The prostate", correctAnswer: "B", rationale: "HSG: contrast injected through the cervix to evaluate uterine cavity shape and fallopian tube patency. Primary indication: infertility evaluation.", category: "Procedures", topic: "Special Procedures", difficulty: 2 },
  { question: "Voiding cystourethrography (VCUG) is performed to evaluate:", optionA: "Kidney function", optionB: "The bladder and urethra during voiding, particularly vesicoureteral reflux in pediatric patients", optionC: "The ureters only", optionD: "The GI tract", correctAnswer: "B", rationale: "VCUG: contrast-filled bladder is imaged during voiding. Primary pediatric indication: evaluate vesicoureteral reflux (VUR).", category: "Procedures", topic: "Special Procedures", difficulty: 2 },
  { question: "The most commonly fractured carpal bone is the:", optionA: "Lunate", optionB: "Scaphoid (navicular)", optionC: "Triquetrum", optionD: "Capitate", correctAnswer: "B", rationale: "Scaphoid is the most commonly fractured carpal bone, typically from FOOSH (fall on outstretched hand). Risk of AVN due to distal blood supply.", category: "Procedures", topic: "Wrist", difficulty: 1 },
  { question: "The most common type of shoulder dislocation is:", optionA: "Posterior", optionB: "Anterior (subcoracoid)", optionC: "Inferior (luxatio erecta)", optionD: "Superior", correctAnswer: "B", rationale: "Anterior dislocation accounts for ~95% of shoulder dislocations. The humeral head displaces anteriorly and inferiorly (subcoracoid position).", category: "Procedures", topic: "Shoulder", difficulty: 1 },
  { question: "The medial oblique foot projection best demonstrates:", optionA: "1st-2nd metatarsals", optionB: "3rd-5th metatarsals without overlap, cuboid, sinus tarsi, and 5th metatarsal base", optionC: "Calcaneus", optionD: "Talus", correctAnswer: "B", rationale: "Medial oblique (30-45° medial rotation): demonstrates 3rd-5th metatarsals separated, cuboid, sinus tarsi, and 5th metatarsal base (Jones fracture site).", category: "Procedures", topic: "Foot", difficulty: 2 },
  { question: "The AP projection of the ankle demonstrates:", optionA: "The ankle mortise without overlap", optionB: "The distal tibia and fibula with tibiofibular overlap, talus, and both malleoli", optionC: "The calcaneus in axial view", optionD: "The subtalar joint", correctAnswer: "B", rationale: "AP ankle shows tibiofibular overlap (normal). Mortise view (15-20° IR) eliminates overlap. Both views are part of the ankle series.", category: "Procedures", topic: "Ankle", difficulty: 1 },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2`, [q.question, "usa"]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, exam, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'usa','arrt','published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty]
      );
      inserted++;
    }
  }
  console.log(`[Procedures 3] Inserted ${inserted}/${QUESTIONS.length} USA ARRT questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
