import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

const QUESTIONS = [
  { question: "The medical term for difficulty swallowing is:", optionA: "Dyspnea", optionB: "Dysphagia", optionC: "Dysuria", optionD: "Dystopia", correctAnswer: "B", rationale: "Dysphagia = difficulty swallowing. Dyspnea = difficulty breathing. Dysuria = painful urination. Important for barium swallow studies.", category: "Patient Care & Education", topic: "Medical Terminology", difficulty: 1 },
  { question: "A patient receiving total parenteral nutrition (TPN) has a central line because:", optionA: "Peripheral veins are easier to access", optionB: "TPN is hyperosmolar and would damage peripheral veins; central venous access allows rapid dilution by high blood flow", optionC: "It is less expensive", optionD: "It delivers faster", correctAnswer: "B", rationale: "TPN's high osmolality causes phlebitis/thrombosis in small peripheral veins. Central lines (SVC) provide high flow for rapid dilution.", category: "Patient Care & Education", topic: "Medical Equipment", difficulty: 2 },
  { question: "The medical term for blood in the urine is:", optionA: "Hemoptysis", optionB: "Hematuria", optionC: "Hematemesis", optionD: "Hematoma", correctAnswer: "B", rationale: "Hematuria = blood in urine. Hemoptysis = coughing blood. Hematemesis = vomiting blood. Important for IVU/urography patients.", category: "Patient Care & Education", topic: "Medical Terminology", difficulty: 1 },
  { question: "When a patient experiences an anaphylactic reaction to contrast media, the FIRST drug typically administered is:", optionA: "Atropine", optionB: "Epinephrine (1:1000 for IM or 1:10,000 for IV)", optionC: "Diphenhydramine (Benadryl)", optionD: "Nitroglycerin", correctAnswer: "B", rationale: "Epinephrine is the first-line drug for anaphylaxis. It reverses bronchospasm, vasodilation, and hypotension. IM (anterolateral thigh) is preferred initially.", category: "Patient Care & Education", topic: "Contrast Reactions", difficulty: 2 },
  { question: "A mild contrast reaction includes:", optionA: "Laryngeal edema", optionB: "Urticaria (hives), mild nausea, limited skin redness, and mild itching", optionC: "Cardiovascular collapse", optionD: "Unresponsiveness", correctAnswer: "B", rationale: "Mild reactions: hives, itching, nausea, warmth, flushing. Moderate: tachycardia, hypotension, bronchospasm. Severe: laryngeal edema, seizures, cardiac arrest.", category: "Patient Care & Education", topic: "Contrast Reactions", difficulty: 1 },
  { question: "The proper method for removing contaminated gloves is to:", optionA: "Pull them off with bare hands", optionB: "Grasp the outside of one glove, peel off, hold removed glove in gloved hand, slide bare finger under the second glove cuff, peel off over the first", optionC: "Shake them off", optionD: "Pull from the fingertips", correctAnswer: "B", rationale: "The glove-in-glove technique prevents bare skin from contacting contaminated outer glove surfaces. Dispose in appropriate container.", category: "Patient Care & Education", topic: "Infection Control", difficulty: 1 },
  { question: "The Glasgow Coma Scale (GCS) assesses:", optionA: "Blood pressure only", optionB: "Level of consciousness based on eye opening, verbal response, and motor response", optionC: "Respiratory rate", optionD: "Pain level", correctAnswer: "B", rationale: "GCS: eye opening (1-4) + verbal response (1-5) + motor response (1-6) = total 3-15. Lower score = more severe impairment.", category: "Patient Care & Education", topic: "Patient Assessment", difficulty: 2 },
  { question: "A normal adult pulse rate is:", optionA: "40-60 BPM", optionB: "60-100 BPM", optionC: "100-120 BPM", optionD: "30-50 BPM", correctAnswer: "B", rationale: "Normal adult resting heart rate: 60-100 beats per minute. Tachycardia: >100. Bradycardia: <60.", category: "Patient Care & Education", topic: "Vital Signs", difficulty: 1 },
  { question: "A pulse oximeter measures:", optionA: "Heart rate only", optionB: "Oxygen saturation (SpO₂) of hemoglobin and pulse rate", optionC: "Blood pressure", optionD: "Temperature", correctAnswer: "B", rationale: "Pulse oximetry: non-invasive measurement of oxygen saturation. Normal SpO₂: 95-100%. Below 90% indicates significant hypoxemia.", category: "Patient Care & Education", topic: "Vital Signs", difficulty: 1 },
  { question: "Hand hygiene with alcohol-based hand sanitizer is appropriate for all situations EXCEPT:", optionA: "Between patients", optionB: "When hands are visibly soiled (must use soap and water instead)", optionC: "After removing gloves", optionD: "Before patient contact", correctAnswer: "B", rationale: "Alcohol-based sanitizer is effective for clean hands. Visibly soiled hands MUST use soap and water. Also ineffective against C. difficile spores.", category: "Patient Care & Education", topic: "Infection Control", difficulty: 1 },
  { question: "The proper hand washing duration recommended by WHO/CDC is:", optionA: "5 seconds", optionB: "At least 20 seconds with soap and water", optionC: "1 minute", optionD: "3 minutes", correctAnswer: "B", rationale: "CDC recommends at least 20 seconds of handwashing with soap and water (approximately singing Happy Birthday twice).", category: "Patient Care & Education", topic: "Infection Control", difficulty: 1 },
  { question: "Droplet precautions are required for patients with:", optionA: "MRSA", optionB: "Influenza, pertussis, meningococcal meningitis, and some types of pneumonia", optionC: "Tuberculosis", optionD: "Scabies", correctAnswer: "B", rationale: "Droplet precautions (surgical mask within 3-6 feet): influenza, pertussis, mumps, rubella, meningococcal disease. Different from airborne (TB, measles, varicella).", category: "Patient Care & Education", topic: "Infection Control", difficulty: 2 },
  { question: "Airborne precautions require:", optionA: "Surgical mask only", optionB: "N95 respirator (or PAPR), negative pressure room, and limited room entry", optionC: "Gown and gloves only", optionD: "Standard precautions only", correctAnswer: "B", rationale: "Airborne precautions: N95/PAPR respirator, negative pressure isolation room. For TB, measles, varicella, COVID-19 (aerosol-generating procedures).", category: "Patient Care & Education", topic: "Infection Control", difficulty: 1 },
  { question: "The acronym RACE in fire safety stands for:", optionA: "Remove, Alert, Cool, Exit", optionB: "Rescue (remove patients), Alarm (pull fire alarm), Contain (close doors), Extinguish/Evacuate", optionC: "Run, Alert, Call, Escape", optionD: "Rescue, Assess, Cover, Escape", correctAnswer: "B", rationale: "RACE: Rescue patients in immediate danger, Alarm (pull alarm/call), Contain fire (close doors), Extinguish small fires or Evacuate.", category: "Patient Care & Education", topic: "Safety", difficulty: 1 },
  { question: "The acronym PASS for fire extinguisher use stands for:", optionA: "Push, Aim, Spray, Squeeze", optionB: "Pull pin, Aim at base of fire, Squeeze handle, Sweep side to side", optionC: "Point, Aim, Shoot, Stop", optionD: "Pull, Apply, Spray, Stop", correctAnswer: "B", rationale: "PASS: Pull the pin, Aim the nozzle at the base of the fire, Squeeze the handle, Sweep from side to side.", category: "Patient Care & Education", topic: "Safety", difficulty: 1 },
  { question: "Barium sulfate contrast media is contraindicated when:", optionA: "The patient has renal insufficiency", optionB: "A bowel perforation is suspected (use water-soluble contrast instead)", optionC: "The patient is diabetic", optionD: "The patient is elderly", correctAnswer: "B", rationale: "Barium leaking through a perforation causes peritonitis (potentially fatal). Use water-soluble contrast (Gastrografin) when perforation is suspected.", category: "Patient Care & Education", topic: "Contrast Media", difficulty: 2 },
  { question: "The ethical principle of beneficence means:", optionA: "Do no harm", optionB: "Act in the patient's best interest to promote their well-being", optionC: "Tell the truth", optionD: "Treat patients fairly", correctAnswer: "B", rationale: "Beneficence = do good, act in the patient's best interest. Nonmaleficence = do no harm. Autonomy = patient's right to decide. Justice = fairness.", category: "Patient Care & Education", topic: "Ethics", difficulty: 1 },
  { question: "A tort in medical law refers to:", optionA: "A criminal offense", optionB: "A civil wrong (intentional or unintentional) that results in injury to another person", optionC: "A regulatory violation", optionD: "A billing error", correctAnswer: "B", rationale: "Torts are civil (not criminal) wrongs. Intentional: assault, battery, false imprisonment. Unintentional (negligence): failure to meet standard of care.", category: "Patient Care & Education", topic: "Legal", difficulty: 2 },
  { question: "Performing a radiographic examination on the wrong patient constitutes:", optionA: "Battery", optionB: "Negligence (failure to verify patient identity before the procedure)", optionC: "Assault", optionD: "Defamation", correctAnswer: "B", rationale: "Performing an exam on the wrong patient is negligence — failure to follow the standard of care (proper patient identification using two identifiers).", category: "Patient Care & Education", topic: "Legal", difficulty: 2 },
  { question: "False imprisonment in radiology might occur when:", optionA: "A patient refuses an exam", optionB: "A technologist unjustifiably restrains or prevents a competent patient from leaving when they wish to leave", optionC: "A patient misses their appointment", optionD: "An exam takes too long", correctAnswer: "B", rationale: "False imprisonment: unlawfully restraining or confining a patient. A competent adult has the right to refuse or leave at any time.", category: "Patient Care & Education", topic: "Legal", difficulty: 2 },
  { question: "A 72-year-old patient is confused and trying to get off the X-ray table. The MOST appropriate action is to:", optionA: "Restrain the patient immediately", optionB: "Speak calmly, reorient the patient, have someone stay with them, and use the least restrictive measures to ensure safety", optionC: "Complete the exam quickly", optionD: "Send the patient back to their room", correctAnswer: "B", rationale: "Use calm communication first. Least restrictive measures: verbal guidance, having someone stay, then physical assistance only if safety requires it.", category: "Patient Care & Education", topic: "Patient Management", difficulty: 2 },
  { question: "When a patient with a known iodine allergy requires a contrast-enhanced CT, the radiologist may order:", optionA: "No premedication needed", optionB: "Premedication with corticosteroids (prednisone) and antihistamines (diphenhydramine) 12-13 hours and 1 hour before the procedure", optionC: "Aspirin only", optionD: "Acetaminophen only", correctAnswer: "B", rationale: "Premedication protocol: prednisone 50mg at 13hr, 7hr, and 1hr before + diphenhydramine 50mg 1hr before. Reduces but doesn't eliminate reaction risk.", category: "Patient Care & Education", topic: "Contrast Media", difficulty: 3 },
  { question: "Orthostatic hypotension is defined as:", optionA: "High blood pressure while lying down", optionB: "A drop in systolic BP ≥20 mmHg or diastolic BP ≥10 mmHg when moving from supine to standing position", optionC: "High blood pressure while standing", optionD: "Normal blood pressure changes", correctAnswer: "B", rationale: "Orthostatic (postural) hypotension: BP drops ≥20 systolic or ≥10 diastolic upon standing. Can cause dizziness, syncope. Common in elderly patients.", category: "Patient Care & Education", topic: "Vital Signs", difficulty: 2 },
  { question: "The chain of infection includes all of the following EXCEPT:", optionA: "Infectious agent", optionB: "Radiation exposure", optionC: "Susceptible host", optionD: "Portal of entry", correctAnswer: "B", rationale: "Chain of infection: infectious agent → reservoir → portal of exit → mode of transmission → portal of entry → susceptible host. Breaking any link prevents infection.", category: "Patient Care & Education", topic: "Infection Control", difficulty: 1 },
  { question: "When a patient's IV line has a blood return (blood flows back into the tubing), the technologist should:", optionA: "Ignore it", optionB: "Elevate the IV bag above the IV site to restore flow and check the IV pump; notify the nurse if it persists", optionC: "Remove the IV", optionD: "Inject contrast immediately", correctAnswer: "B", rationale: "Blood return usually means the IV bag is too low or the pump stopped. Elevate the bag above the patient's heart level. Never disconnect or manipulate without training.", category: "Patient Care & Education", topic: "Medical Equipment", difficulty: 2 },
  { question: "The normal adult body temperature range (oral) is:", optionA: "95-96°F", optionB: "97.8-99.1°F (36.5-37.3°C)", optionC: "100-101°F", optionD: "95-97°F", correctAnswer: "B", rationale: "Normal oral temperature: ~98.6°F (37°C), range 97.8-99.1°F. Rectal is ~1°F higher, axillary ~1°F lower.", category: "Patient Care & Education", topic: "Vital Signs", difficulty: 1 },
  { question: "The correct sequence for donning PPE is:", optionA: "Gloves, gown, mask, goggles", optionB: "Gown first, mask/respirator, goggles/face shield, gloves last", optionC: "Mask, gloves, gown, goggles", optionD: "Goggles, mask, gown, gloves", correctAnswer: "B", rationale: "Donning order: gown → mask/respirator → goggles/face shield → gloves (last). Doffing (removal): gloves first → goggles → gown → mask (opposite order).", category: "Patient Care & Education", topic: "Infection Control", difficulty: 2 },
  { question: "The proper technique for using a gait belt during patient transfer is to:", optionA: "Place it loosely around the patient's chest", optionB: "Secure it snugly around the patient's waist, gripping the belt (not the patient's clothing) during transfer", optionC: "Place it around the patient's hips", optionD: "Place it under the patient's arms", correctAnswer: "B", rationale: "Gait belt: snug around waist, grip the belt for leverage and control during transfer. Provides a secure handhold to prevent falls.", category: "Patient Care & Education", topic: "Patient Transfer", difficulty: 1 },
  { question: "An unconscious patient who is NOT suspected of having a spinal injury and is vomiting should be placed in:", optionA: "Supine with head elevated", optionB: "Recovery position (lateral recumbent) to prevent aspiration", optionC: "Prone", optionD: "Sitting upright", correctAnswer: "B", rationale: "Recovery position (left lateral) allows vomit to drain from the mouth, preventing aspiration. Never place an unconscious vomiting patient supine.", category: "Patient Care & Education", topic: "Emergency Response", difficulty: 1 },
  { question: "Standard precautions apply to:", optionA: "Only patients with known infections", optionB: "ALL patients regardless of diagnosis or presumed infection status — treats all blood/body fluids as potentially infectious", optionC: "Only surgical patients", optionD: "Only immunocompromised patients", correctAnswer: "B", rationale: "Standard precautions: universal approach for ALL patients. Assumes all blood, body fluids, secretions, excretions (except sweat), mucous membranes, and non-intact skin are potentially infectious.", category: "Patient Care & Education", topic: "Infection Control", difficulty: 1 },
  { question: "HIPAA protects patient:", optionA: "Financial records only", optionB: "Protected Health Information (PHI) — any individually identifiable health information in any format", optionC: "Only electronic records", optionD: "Only verbal communications", correctAnswer: "B", rationale: "HIPAA protects PHI in all forms: electronic, paper, oral. Includes name, DOB, medical record number, diagnoses, images, and all identifiable health data.", category: "Patient Care & Education", topic: "Legal", difficulty: 1 },
  { question: "The proper body mechanics principle for lifting heavy objects is to:", optionA: "Bend at the waist and lift with the back", optionB: "Keep the back straight, bend at the knees, hold the load close to the body, and lift with the legs", optionC: "Twist while lifting", optionD: "Reach far from the body", correctAnswer: "B", rationale: "Proper lifting: wide base, bend knees (not waist), keep load close to body, use leg muscles, keep back straight, avoid twisting.", category: "Patient Care & Education", topic: "Body Mechanics", difficulty: 1 },
  { question: "A patient states they are allergic to shellfish. This is significant for contrast studies because:", optionA: "It's not relevant to radiology", optionB: "Shellfish allergy was historically associated with iodine allergy (though current evidence suggests no direct cross-reactivity); the technologist should note it and consult the radiologist", optionC: "The exam must be cancelled", optionD: "Barium must be used instead", correctAnswer: "B", rationale: "Current evidence shows shellfish allergy is NOT specifically linked to iodine contrast reactions. However, any allergy history increases risk, so document and consult radiologist.", category: "Patient Care & Education", topic: "Contrast Media", difficulty: 2 },
  { question: "Glucagon is administered during GI studies to:", optionA: "Increase gastric motility", optionB: "Relax smooth muscle of the GI tract (decrease peristalsis) for better mucosal coating", optionC: "Increase blood sugar", optionD: "Decrease stomach acid", correctAnswer: "B", rationale: "Glucagon: smooth muscle relaxant used in GI studies to decrease peristalsis. Allows better barium coating and visualization. Given IM or IV.", category: "Patient Care & Education", topic: "Pharmacology", difficulty: 2 },
  { question: "The purpose of an emesis basin at the patient's side during contrast procedures is:", optionA: "To hold supplies", optionB: "To collect vomit if the patient experiences nausea/vomiting as a contrast reaction", optionC: "To store the contrast", optionD: "For hand washing", correctAnswer: "B", rationale: "Nausea/vomiting is a common contrast reaction. Having an emesis basin ready prevents aspiration and allows immediate response.", category: "Patient Care & Education", topic: "Contrast Media", difficulty: 1 },
  { question: "When transferring a stroke patient, the technologist should:", optionA: "Transfer from the unaffected side", optionB: "Support the affected (weak) side and transfer toward the stronger side so the patient can assist with the stronger extremities", optionC: "Have the patient transfer independently", optionD: "Always use a mechanical lift", correctAnswer: "B", rationale: "Transfer toward the strong side. The patient pivots on the stronger leg while the technologist supports the affected side.", category: "Patient Care & Education", topic: "Patient Transfer", difficulty: 2 },
  { question: "The purpose of a PICC (peripherally inserted central catheter) line is to:", optionA: "Monitor blood pressure", optionB: "Provide long-term IV access for medications, TPN, chemotherapy via a peripheral insertion into the central veins (SVC)", optionC: "Measure cardiac output", optionD: "Drain fluid from the chest", correctAnswer: "B", rationale: "PICC: inserted peripherally (usually basilic/cephalic vein) and threaded to the SVC. Provides long-term central venous access without surgical placement.", category: "Patient Care & Education", topic: "Medical Equipment", difficulty: 2 },
  { question: "Negative contrast agents used in radiology include:", optionA: "Barium sulfate and iodine", optionB: "Air, carbon dioxide (CO₂), and other gases that appear radiolucent (dark) on images", optionC: "Water and saline", optionD: "Gadolinium", correctAnswer: "B", rationale: "Negative contrast agents are radiolucent (low atomic number gases): air, CO₂. They appear dark on radiographs. Used in double-contrast studies.", category: "Patient Care & Education", topic: "Contrast Media", difficulty: 1 },
  { question: "The most appropriate gauge needle for a subcutaneous injection is:", optionA: "18 gauge", optionB: "25-27 gauge (thin needle, 5/8 inch length)", optionC: "14 gauge", optionD: "20 gauge", correctAnswer: "B", rationale: "Subcutaneous injections: 25-27 gauge, 5/8 inch, at 45° angle. Small gauge = small needle. Larger gauges (18-20) for IV contrast.", category: "Patient Care & Education", topic: "Injections", difficulty: 2 },
  { question: "Intramuscular injections are given at what angle?", optionA: "15 degrees", optionB: "90 degrees (perpendicular to the skin)", optionC: "45 degrees", optionD: "10 degrees", correctAnswer: "B", rationale: "IM injection angles: 90° (perpendicular). Subcutaneous: 45°. IV: 15-30°. Intradermal: 10-15°.", category: "Patient Care & Education", topic: "Injections", difficulty: 1 },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2`, [q.question, "usa"]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, exam, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'usa','arrt','published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty]
      );
      inserted++;
    }
  }
  console.log(`[Patient Care 3] Inserted ${inserted}/${QUESTIONS.length} USA ARRT questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
