import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });

const QUESTIONS = [
  { question: "When using AEC for a lateral chest, the correct chamber selection is:", optionA: "Both outer (lateral) chambers", optionB: "Center chamber only (to measure through the denser mediastinum/spine)", optionC: "All three chambers", optionD: "Left chamber only", correctAnswer: "B", rationale: "Lateral chest: center chamber. It reads through the denser anatomy (mediastinum/spine). Outer chambers would read through less-dense lung and terminate too early.", category: "Image Production", topic: "AEC", difficulty: 2 },
  { question: "When using AEC for a PA chest, the correct chamber selection is:", optionA: "Center chamber", optionB: "Both outer (lateral) chambers to measure through the lung fields", optionC: "All three chambers", optionD: "Right chamber only", correctAnswer: "B", rationale: "PA chest: both outer chambers. They read through lung tissue. Center chamber would read through the dense mediastinum and overexpose the lungs.", category: "Image Production", topic: "AEC", difficulty: 1 },
  { question: "The density control (+1, +2, -1, -2) on the AEC adjusts the:", optionA: "kVp", optionB: "Amount of radiation needed to terminate the exposure — each step typically changes density by 25-30%", optionC: "SID", optionD: "Grid ratio", correctAnswer: "B", rationale: "AEC density controls adjust the target exposure level. Each step typically changes the mAs (and thus density) by approximately 25-30%.", category: "Image Production", topic: "AEC", difficulty: 2 },
  { question: "AEC will produce an overexposed image if:", optionA: "The correct chamber is selected", optionB: "The anatomy does not cover the selected chamber(s) completely", optionC: "The backup timer is set correctly", optionD: "The kVp is correct", correctAnswer: "B", rationale: "If the selected chamber is NOT covered by anatomy, radiation passes directly to the chamber, causing premature termination → actually this causes UNDER-exposure. If off-side anatomy covers, overexposure can result from excessive technique. Note: uncovered chamber = underexposure.", category: "Image Production", topic: "AEC", difficulty: 2 },
  { question: "In computed radiography, the term 'exposure class' or 'speed class' refers to:", optionA: "How fast the plate is read", optionB: "The system sensitivity setting that determines how amplified the signal is — analogous to film speed", optionC: "The laser scanning speed", optionD: "The erasure cycle speed", correctAnswer: "B", rationale: "Speed/sensitivity class in CR: determines signal amplification. Class 200 = less amplification (more technique needed). Class 400 = standard. Class 800 = more amplification.", category: "Image Production", topic: "CR Technology", difficulty: 2 },
  { question: "The look-up table (LUT) in digital radiography:", optionA: "Controls patient dose", optionB: "Maps raw pixel values to display values — determines how the final image appears on the monitor", optionC: "Determines the kVp", optionD: "Controls the AEC", correctAnswer: "B", rationale: "LUT: a mathematical function that converts raw detector data to display values. Different LUTs are applied for different body parts/exam types.", category: "Image Production", topic: "Digital Processing", difficulty: 2 },
  { question: "The term 'for processing' data in digital radiography refers to:", optionA: "The final displayed image", optionB: "Raw, unprocessed data from the detector before histogram analysis and LUT application", optionC: "Compressed image data", optionD: "DICOM header data only", correctAnswer: "B", rationale: "For processing (raw data): unmodified detector signal. For presentation: processed data after histogram analysis, LUT application, and post-processing.", category: "Image Production", topic: "Digital Processing", difficulty: 2 },
  { question: "Grid cutoff from using an SID outside the grid's focal range appears as:", optionA: "No effect", optionB: "Decreased density at the periphery (edges) of the image with relatively normal center density", optionC: "Uniform density decrease", optionD: "Increased density overall", correctAnswer: "B", rationale: "Off-focus distance: SID outside the grid's convergence range. The beam diverges differently than the grid's focused angle, causing peripheral cutoff.", category: "Image Production", topic: "Grid Errors", difficulty: 2 },
  { question: "Aliasing artifact in digital imaging occurs when:", optionA: "The image is too bright", optionB: "The spatial frequency of the object exceeds the Nyquist frequency of the detector, causing false patterns", optionC: "The kVp is too low", optionD: "The grid is used incorrectly", correctAnswer: "B", rationale: "Aliasing: when spatial frequency > Nyquist limit (1/2 pixel pitch). The detector cannot resolve the pattern and creates false (aliased) information.", category: "Image Production", topic: "Digital Artifacts", difficulty: 3 },
  { question: "The primary purpose of the photomultiplier tube (PMT) in a CR reader is to:", optionA: "Produce the laser beam", optionB: "Convert the photostimulated luminescence (light) from the CR plate into an electrical signal", optionC: "Erase the plate", optionD: "Store the image data", correctAnswer: "B", rationale: "PMT: detects the blue PSL light emitted from the CR plate during laser stimulation and converts it to an amplified electrical signal for digitization.", category: "Image Production", topic: "CR Technology", difficulty: 2 },
  { question: "The standardized Exposure Index (EI) proposed by AAPM/IEC is:", optionA: "Manufacturer-specific", optionB: "A universal system where EI is proportional to detector dose — EI_T is the target value and DI measures deviation", optionC: "Inversely proportional to dose", optionD: "Only for CT", correctAnswer: "B", rationale: "Standardized EI: proportional to detector dose. DI = 10 × log₁₀(EI/EI_T). DI=0 = ideal. Positive = overexposure. Negative = underexposure.", category: "Image Production", topic: "Exposure Indicators", difficulty: 2 },
  { question: "The primary advantage of CsI (cesium iodide) over GOS (gadolinium oxysulfide) as a scintillator is:", optionA: "Lower cost", optionB: "CsI's needle-like crystal structure channels light more efficiently, reducing lateral spread and improving spatial resolution and DQE", optionC: "Better availability", optionD: "Lower weight", correctAnswer: "B", rationale: "CsI needles act like light pipes (fiber optics), channeling light vertically to photodiodes with minimal lateral spread. GOS uses unstructured phosphor with more light scatter.", category: "Image Production", topic: "DR Technology", difficulty: 3 },
  { question: "The purpose of the anti-aliasing filter (Nyquist filter) in digital imaging is to:", optionA: "Increase spatial frequency", optionB: "Remove spatial frequencies above the Nyquist limit before sampling to prevent aliasing artifacts", optionC: "Increase patient dose", optionD: "Sharpen the image", correctAnswer: "B", rationale: "Anti-aliasing filter removes frequencies above the Nyquist limit before digitization. This prevents the detector from creating false patterns from unresolvable detail.", category: "Image Production", topic: "Digital Processing", difficulty: 3 },
  { question: "Image lag (ghosting) on a flat panel detector is caused by:", optionA: "Excessive mAs", optionB: "Residual charge trapped in the detector from a previous exposure that is released during the next exposure", optionC: "Incorrect kVp", optionD: "Grid misalignment", correctAnswer: "B", rationale: "Image lag: trapped charge from previous exposure bleeds into the current image. Addressed through calibration, dark frame subtraction, and detector reset.", category: "Image Production", topic: "DR Technology", difficulty: 2 },
  { question: "Tomosynthesis differs from conventional tomography in that it:", optionA: "Uses film-screen", optionB: "Acquires multiple low-dose projections over a limited arc and reconstructs them digitally into multiple thin tissue slices", optionC: "Uses only one exposure", optionD: "Is the same technique", correctAnswer: "B", rationale: "Digital tomosynthesis: tube moves through a limited arc taking multiple low-dose exposures. Software reconstructs any number of focal plane slices from the data.", category: "Image Production", topic: "Advanced Imaging", difficulty: 3 },
  { question: "The standardized Deviation Index (DI) target value is:", optionA: "1.0", optionB: "0 (zero — indicating ideal exposure matching the target EI)", optionC: "-1.0", optionD: "2.0", correctAnswer: "B", rationale: "DI = 0 means actual EI matches target EI (ideal). DI of +1 = 26% overexposure. DI of -1 = 20% underexposure. Acceptable range: ±1 to ±3.", category: "Image Production", topic: "Exposure Indicators", difficulty: 2 },
  { question: "The term 'wide latitude' in digital imaging means:", optionA: "The image has high contrast", optionB: "The detector can produce acceptable images over a wide range of exposures — from very low to very high", optionC: "The pixel size is large", optionD: "The matrix is small", correctAnswer: "B", rationale: "Wide latitude (dynamic range): digital detectors accept a much wider range of exposures (10,000:1) than film (100:1). This is why dose creep is a concern.", category: "Image Production", topic: "Digital Imaging", difficulty: 1 },
  { question: "The conversion efficiency of an X-ray tube (percentage of electron energy converted to X-rays) is approximately:", optionA: "50%", optionB: "Less than 1% (with the rest converted to heat)", optionC: "10%", optionD: "25%", correctAnswer: "B", rationale: "Less than 1% of the kinetic energy of electrons striking the target is converted to X-rays. Over 99% becomes heat.", category: "Image Production", topic: "X-ray Production", difficulty: 2 },
  { question: "The relationship between mAs and receptor exposure is:", optionA: "Inversely proportional", optionB: "Directly proportional (doubling mAs doubles the exposure)", optionC: "Exponential", optionD: "No relationship", correctAnswer: "B", rationale: "mAs and exposure have a linear, directly proportional relationship. Double the mAs = double the photons = double the exposure to the receptor.", category: "Image Production", topic: "Technique", difficulty: 1 },
  { question: "The purpose of image annotation in PACS is to:", optionA: "Delete the image", optionB: "Add text markers, measurements, and labels to the digital image for communication and documentation", optionC: "Change the exposure", optionD: "Compress the file", correctAnswer: "B", rationale: "Annotations (text, arrows, measurements) are added to images for communication. They are stored as overlay data, not modifying the original image data.", category: "Image Production", topic: "Digital Imaging", difficulty: 1 },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2`, [q.question, "usa"]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, exam, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'usa','arrt','published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty]
      );
      inserted++;
    }
  }
  console.log(`[Image Production 4] Inserted ${inserted}/${QUESTIONS.length} USA ARRT questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
