import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

interface Q {
  question: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctAnswer: string; rationale: string; category: string; topic: string;
  difficulty: number; country: string; bodyPart?: string; modality?: string; exam: string;
  examDomain: string; masteryCategory?: string;
}

const QUESTIONS: Q[] = [
  { question: "A 72-year-old patient arrives in the radiology department via stretcher for a portable chest radiograph. The patient is receiving 4 L/min oxygen via nasal cannula. During positioning, the oxygen tubing becomes disconnected. What should the technologist do FIRST?", optionA: "Complete the exposure quickly before reconnecting", optionB: "Immediately reconnect the oxygen and verify flow rate", optionC: "Call the nurse to reconnect the tubing", optionD: "Remove the nasal cannula and proceed without oxygen", correctAnswer: "B", rationale: "Oxygen therapy interruption can cause rapid desaturation in patients requiring supplemental oxygen. The technologist should immediately reconnect the tubing and verify the prescribed flow rate before continuing with the examination.", category: "Patient Care", topic: "Oxygen Administration", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "During a barium swallow examination, a patient suddenly develops severe stridor and facial swelling. Which medication should be administered FIRST?", optionA: "Diphenhydramine 50 mg IV", optionB: "Epinephrine 0.3 mg IM (1:1000)", optionC: "Albuterol nebulizer treatment", optionD: "Methylprednisolone 125 mg IV", correctAnswer: "B", rationale: "Severe stridor and facial swelling indicate anaphylaxis with airway compromise. Epinephrine IM is the first-line treatment for anaphylaxis as it addresses bronchospasm, hypotension, and angioedema simultaneously.", category: "Patient Care", topic: "Emergency Response", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A technologist is preparing to perform venipuncture for a CT contrast injection. The patient reports a history of a mastectomy with axillary lymph node dissection on the right side. Which is the MOST appropriate action?", optionA: "Proceed with venipuncture in the right antecubital fossa", optionB: "Use the left arm for venipuncture", optionC: "Use a foot vein instead", optionD: "Cancel the contrast injection entirely", correctAnswer: "B", rationale: "Venipuncture should be avoided on the side of mastectomy with lymph node dissection due to increased risk of lymphedema and infection. The contralateral arm should be used.", category: "Patient Care", topic: "Venipuncture", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient's lab values show a serum creatinine of 2.8 mg/dL and an eGFR of 22 mL/min. The referring physician has ordered a CT abdomen with IV contrast. What is the technologist's BEST course of action?", optionA: "Proceed with the contrast injection as ordered", optionB: "Notify the radiologist of the abnormal renal function before administering contrast", optionC: "Substitute barium sulfate for iodinated contrast", optionD: "Reduce the contrast volume by half and proceed", correctAnswer: "B", rationale: "An eGFR below 30 mL/min indicates severely reduced kidney function and significantly increased risk for contrast-induced nephropathy. The radiologist must be consulted before administering iodinated contrast.", category: "Patient Care", topic: "Contrast Media", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "When performing a mobile chest radiograph on a patient in the ICU, the technologist notices the patient has both a central venous catheter and a Swan-Ganz (pulmonary artery) catheter. What should be verified on the resulting image?", optionA: "Only the lung fields for pathology", optionB: "Position of the central line tip at the cavoatrial junction and PA catheter tip in the pulmonary artery", optionC: "Whether the catheters need to be removed", optionD: "Only the cardiac silhouette", correctAnswer: "B", rationale: "Portable chest radiographs in ICU patients serve to verify line and tube positions. The central venous catheter tip should be at the cavoatrial junction, and the PA catheter tip should be in a main pulmonary artery.", category: "Patient Care", topic: "Medical Equipment", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "Calculate the drip rate for a 500 mL bag of normal saline to infuse over 4 hours using standard tubing (15 gtt/mL).", optionA: "21 gtt/min", optionB: "31 gtt/min", optionC: "42 gtt/min", optionD: "63 gtt/min", correctAnswer: "B", rationale: "Drip rate = (Volume × Drop factor) / (Time in minutes) = (500 mL × 15 gtt/mL) / (240 min) = 7500/240 = 31.25 ≈ 31 gtt/min.", category: "Patient Care", topic: "IV Therapy", difficulty: 4, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "calculation" },
  { question: "A patient scheduled for an IVP states they had 'hives and itching' after receiving contrast during a previous CT scan. Which premedication protocol is MOST commonly used?", optionA: "Diphenhydramine 50 mg IV 1 hour before", optionB: "Prednisone 50 mg oral at 13, 7, and 1 hour before, plus diphenhydramine 50 mg 1 hour before", optionC: "Epinephrine 0.3 mg IM immediately before", optionD: "Famotidine 20 mg IV 1 hour before", correctAnswer: "B", rationale: "The ACR recommends oral corticosteroid premedication (prednisone 50 mg at 13, 7, and 1 hour before) plus diphenhydramine 50 mg 1 hour before contrast administration for patients with prior allergic-like reactions.", category: "Patient Care", topic: "Contrast Media", difficulty: 4, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient receiving IV contrast through a power injector suddenly complains of intense burning and swelling at the injection site. The technologist stops the injection. What additional step should be taken IMMEDIATELY?", optionA: "Apply a tourniquet above the site", optionB: "Elevate the extremity and apply cold compresses", optionC: "Resume injection at a slower rate", optionD: "Apply a warm compress and massage the area vigorously", correctAnswer: "B", rationale: "For contrast extravasation, immediate treatment includes stopping the injection, elevating the extremity, and applying cold compresses. The radiologist should be notified. Warm compresses may be used later if compartment syndrome is not suspected.", category: "Patient Care", topic: "Venipuncture", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "During a portable abdominal radiograph, a patient with a colostomy bag begins to have a large-volume output. The technologist should:", optionA: "Remove the colostomy bag for the exposure", optionB: "Empty the bag if needed, leave it in place, and proceed with the exam", optionC: "Wait until the output stops completely", optionD: "Replace the bag with a new one before imaging", correctAnswer: "B", rationale: "Colostomy bags should never be removed by a technologist. If the bag is very full, it may be emptied (if trained to do so). The bag stays in place during imaging and should not obscure the anatomy of interest.", category: "Patient Care", topic: "Patient Care Procedures", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A technologist discovers that a hand radiograph was performed on the wrong patient due to a name mix-up. Which of the following actions is required?", optionA: "Repeat the exam on the correct patient only", optionB: "File an incident report, notify the supervisor, and image the correct patient", optionC: "Label the images with the correct patient's name", optionD: "Delete the images and pretend it did not happen", correctAnswer: "B", rationale: "Wrong-patient errors are sentinel events requiring incident reporting, supervisor notification, and corrective action. Images must never be relabeled to a different patient. The correct patient must then be imaged.", category: "Patient Care", topic: "Legal & Ethics", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "An unconscious trauma patient arrives in the emergency department. No identification is available and no family members are present. Can the technologist perform the ordered radiographic examinations?", optionA: "No, written consent is always required before imaging", optionB: "Yes, under the doctrine of implied consent for emergency situations", optionC: "No, only a physician can authorize imaging of unidentified patients", optionD: "Yes, but only non-contrast radiographs", correctAnswer: "B", rationale: "The doctrine of implied consent applies to emergency situations where the patient is unable to give consent and a delay in treatment could result in harm. Life-saving diagnostic imaging can proceed.", category: "Patient Care", topic: "Legal & Ethics", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient with a known latex allergy is scheduled for a barium enema. Which precaution is MOST important?", optionA: "Use a non-latex enema tip and gloves", optionB: "Premedicate with epinephrine", optionC: "Substitute water-soluble contrast", optionD: "Cancel the procedure entirely", correctAnswer: "A", rationale: "Latex-free equipment (enema tip, gloves, tourniquets) must be used for patients with latex allergies to prevent potentially life-threatening allergic reactions. The procedure can proceed safely with non-latex alternatives.", category: "Patient Care", topic: "Patient Safety", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A radiograph of an infant's chest shows the endotracheal tube tip positioned at the level of the aortic arch. Is this placement acceptable?", optionA: "Yes, this is the ideal position", optionB: "No, the tip should be 1-2 cm above the carina, approximately at T2-T3 level", optionC: "No, the tip should be at the level of the carina", optionD: "Yes, as long as both lungs are ventilated", correctAnswer: "B", rationale: "The ideal ET tube position in neonates and infants is 1-2 cm above the carina, typically at the T2-T3 vertebral level. Placement at the aortic arch may be too high, risking inadvertent extubation.", category: "Patient Care", topic: "Medical Equipment", difficulty: 4, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "Which type of transmission-based precaution requires the patient to be in a negative-pressure airborne infection isolation room (AIIR)?", optionA: "Contact precautions", optionB: "Droplet precautions", optionC: "Airborne precautions", optionD: "Standard precautions", correctAnswer: "C", rationale: "Airborne precautions (for TB, measles, varicella, COVID-19) require a negative-pressure AIIR to prevent infectious particles from escaping. Healthcare workers must wear N95 respirators or PAPRs.", category: "Patient Care", topic: "Infection Control", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A contrast power injector is set to deliver 100 mL of iodinated contrast at 3 mL/sec. How long will the injection take?", optionA: "30 seconds", optionB: "33.3 seconds", optionC: "50 seconds", optionD: "100 seconds", correctAnswer: "B", rationale: "Injection time = Volume / Flow rate = 100 mL / 3 mL/sec = 33.3 seconds.", category: "Patient Care", topic: "Contrast Media", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "calculation" },
  { question: "A patient in the radiology department suddenly becomes unresponsive and is not breathing normally. After calling for help and activating the emergency response system, what is the technologist's NEXT action?", optionA: "Administer oxygen via nasal cannula", optionB: "Begin chest compressions at a rate of 100-120 per minute", optionC: "Obtain an AED", optionD: "Check for a pulse for 30 seconds", correctAnswer: "B", rationale: "Per AHA BLS guidelines, after activating emergency response, begin high-quality CPR with chest compressions at 100-120/min, depth of at least 2 inches. Check pulse for no more than 10 seconds.", category: "Patient Care", topic: "Emergency Care", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A diabetic patient taking metformin is scheduled for a contrast-enhanced CT. The patient's eGFR is 45 mL/min. Regarding metformin management:", optionA: "Metformin must be discontinued 48 hours before the exam", optionB: "Metformin should be held at the time of the procedure and for 48 hours after, with renal function reassessed before resuming", optionC: "Metformin poses no risk with contrast and can be continued", optionD: "Metformin must be permanently discontinued", correctAnswer: "B", rationale: "For patients with eGFR 30-60 taking metformin, the medication should be held at the time of contrast administration and for 48 hours afterward. Renal function should be reassessed before resuming to prevent lactic acidosis.", category: "Patient Care", topic: "Contrast Media", difficulty: 4, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "During a radiographic procedure, a patient's IV pump begins alarming. The technologist should:", optionA: "Silence the alarm and continue the exam", optionB: "Check for obvious causes (kinked tubing, empty bag) and call the nurse", optionC: "Disconnect the IV pump", optionD: "Ignore the alarm and complete the exposure", correctAnswer: "B", rationale: "The technologist should check for obvious causes of the alarm (kinked tubing, air in the line, empty bag) and notify the patient's nurse. The technologist should not adjust IV pump settings unless trained to do so.", category: "Patient Care", topic: "Medical Equipment", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient with suspected C-spine injury is brought to the radiology department on a backboard with a cervical collar in place. The technologist should:", optionA: "Remove the collar for lateral C-spine imaging", optionB: "Image through the collar without removing it, using a cross-table lateral as the initial view", optionC: "Have the patient sit up for an upright lateral", optionD: "Remove the backboard first and then image", correctAnswer: "B", rationale: "The cervical collar must remain in place until C-spine injury is ruled out. Initial imaging uses a cross-table lateral with the patient supine on the backboard. The collar is radiolucent enough for adequate visualization.", category: "Patient Care", topic: "Patient Safety", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "The proper body mechanics for a technologist lifting a heavy object from the floor include:", optionA: "Bending at the waist with straight legs", optionB: "Bending the knees, keeping the back straight, and holding the object close to the body", optionC: "Twisting the torso while lifting", optionD: "Extending the arms fully away from the body", correctAnswer: "B", rationale: "Proper lifting technique uses leg muscles: bend knees, keep back straight, hold object close to center of gravity, avoid twisting, and lift smoothly using leg power.", category: "Patient Care", topic: "Body Mechanics", difficulty: 1, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A 45-year-old female patient presents for an abdominal radiograph. She states her last menstrual period was 6 weeks ago and she has not had a pregnancy test. The technologist should:", optionA: "Proceed with the exam since the patient is over 40", optionB: "Obtain a pregnancy test or confirmation from the patient/physician before proceeding", optionC: "Use a lead apron over the abdomen and proceed", optionD: "Reduce the mAs by 50% and proceed", correctAnswer: "B", rationale: "A missed menstrual period suggests possible pregnancy. For women of childbearing age, pregnancy status must be confirmed before abdominal/pelvic radiation exposure. A pregnancy test or physician consultation is required.", category: "Patient Care", topic: "Radiation Protection", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "When communicating radiographic instructions to a patient who speaks limited English, the BEST approach is:", optionA: "Speak louder and slower", optionB: "Use a professional medical interpreter or hospital translation service", optionC: "Have a family member translate", optionD: "Use hand gestures only", correctAnswer: "B", rationale: "Professional medical interpreters ensure accurate communication of medical instructions and informed consent. Family members may not accurately translate medical terminology and may have conflicts of interest.", category: "Patient Care", topic: "Patient Communication", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient with a pheochromocytoma is scheduled for a CT with contrast. Why is this clinically significant?", optionA: "Contrast is absolutely contraindicated", optionB: "Ionic contrast media can precipitate a hypertensive crisis; nonionic contrast should be used with caution", optionC: "Extra filtration is needed", optionD: "The patient needs sedation", correctAnswer: "B", rationale: "Pheochromocytoma is an adrenal tumor that secretes catecholamines. Ionic contrast can trigger massive catecholamine release causing hypertensive crisis. Nonionic contrast is preferred, with alpha-blocker premedication.", category: "Patient Care", topic: "Contrast Media", difficulty: 5, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A 6-year-old child requires a wrist radiograph but is extremely anxious and uncooperative. The BEST approach is:", optionA: "Restrain the child immediately with immobilization devices", optionB: "Explain the procedure in age-appropriate terms, allow a parent in the room (with shielding), and use immobilization devices as needed", optionC: "Sedate the child", optionD: "Have two technologists hold the child", correctAnswer: "B", rationale: "Pediatric patients benefit from age-appropriate explanations, parental presence for comfort (with proper shielding), and gentle immobilization devices. Sedation is reserved for procedures where immobilization is critical and other methods fail.", category: "Patient Care", topic: "Special Populations", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "Which laboratory value is MOST important to check before administering iodinated contrast to a patient with a history of multiple myeloma?", optionA: "Hemoglobin", optionB: "BUN/Creatinine or eGFR", optionC: "Platelet count", optionD: "White blood cell count", correctAnswer: "B", rationale: "Multiple myeloma patients are at increased risk for contrast-induced nephropathy due to Bence Jones proteinuria and pre-existing renal compromise. Renal function (BUN/Creatinine, eGFR) must be evaluated before contrast administration.", category: "Patient Care", topic: "Contrast Media", difficulty: 4, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient develops urticaria (hives) limited to the injection site after receiving iodinated contrast. The technologist should:", optionA: "Administer epinephrine immediately", optionB: "Monitor the patient, notify the radiologist, and consider diphenhydramine for comfort", optionC: "Ignore it as it is a normal response", optionD: "Send the patient home immediately", correctAnswer: "B", rationale: "Limited urticaria at the injection site is a mild reaction. Monitor the patient for progression, notify the radiologist, and diphenhydramine may be given for comfort. Observation for 20-30 minutes is recommended.", category: "Patient Care", topic: "Contrast Media", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "When performing CPR on an adult, the correct compression-to-ventilation ratio for a single rescuer is:", optionA: "15:2", optionB: "30:2", optionC: "15:1", optionD: "5:1", correctAnswer: "B", rationale: "Per AHA BLS guidelines, the compression-to-ventilation ratio for single-rescuer adult CPR is 30:2 (30 compressions followed by 2 breaths).", category: "Patient Care", topic: "Emergency Care", difficulty: 1, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient with suspected pulmonary embolism is ordered for a CT pulmonary angiography (CTPA). The contrast injection protocol typically requires:", optionA: "Slow hand injection at 1 mL/sec", optionB: "Rapid bolus injection at 4-5 mL/sec with bolus tracking to the pulmonary arteries", optionC: "Oral contrast only", optionD: "Rectal contrast administration", correctAnswer: "B", rationale: "CTPA requires rapid IV contrast bolus (4-5 mL/sec) with bolus tracking or timing bolus to ensure optimal opacification of the pulmonary arteries during the arterial phase.", category: "Patient Care", topic: "Contrast Media", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A water-soluble iodinated contrast agent (such as Gastrografin) should be used instead of barium sulfate when:", optionA: "The patient has an iodine allergy", optionB: "Bowel perforation or anastomotic leak is suspected", optionC: "Superior mucosal detail is needed", optionD: "A double-contrast study is planned", correctAnswer: "B", rationale: "Water-soluble contrast is used when perforation is suspected because it is safely absorbed from the peritoneum. Barium leaking into the peritoneum causes life-threatening barium peritonitis.", category: "Patient Care", topic: "Contrast Media", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A geriatric patient with dementia becomes combative during a hip radiograph. The MOST appropriate response is:", optionA: "Physically restrain the patient without consent", optionB: "Speak calmly, reorient the patient, and request assistance; use the least restrictive immobilization necessary", optionC: "Administer sedation", optionD: "Abandon the examination entirely", correctAnswer: "B", rationale: "De-escalation techniques (calm voice, reorientation, simple instructions) should be attempted first. If immobilization is needed, use the least restrictive method. Physical restraints require a physician order and proper documentation.", category: "Patient Care", topic: "Special Populations", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "The medical term for difficulty swallowing is:", optionA: "Dyspnea", optionB: "Dysphagia", optionC: "Dysphasia", optionD: "Dysplasia", correctAnswer: "B", rationale: "Dysphagia refers to difficulty swallowing. It is significant in radiology as it is a common indication for barium swallow/modified barium swallow studies.", category: "Patient Care", topic: "Medical Terminology", difficulty: 1, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "knowledge" },
  { question: "A patient has a known sickle cell disease and is scheduled for a CT with contrast. The primary concern regarding contrast administration is:", optionA: "Allergic reaction risk", optionB: "Hyperosmolar contrast may trigger a sickle cell crisis in the renal vasculature", optionC: "The patient cannot receive any IV injections", optionD: "Contrast will interfere with hemoglobin measurement", correctAnswer: "B", rationale: "Hyperosmolar contrast agents can cause sickling of red blood cells in patients with sickle cell disease, potentially triggering a crisis. Low-osmolality or iso-osmolality nonionic contrast with adequate hydration is recommended.", category: "Patient Care", topic: "Contrast Media", difficulty: 5, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "When removing gloves after a procedure, the correct technique involves:", optionA: "Pulling both gloves off simultaneously by the fingertips", optionB: "Grasping the outside of one glove near the wrist and peeling it off, then sliding fingers under the second glove and peeling it inside out", optionC: "Tearing the gloves off quickly", optionD: "Washing the gloves before removal", correctAnswer: "B", rationale: "Proper glove removal technique prevents skin contact with contaminated outer surfaces. Pinch the outside of one glove near the wrist, peel off, hold in gloved hand, then slide ungloved fingers inside the second glove and peel off, turning inside out.", category: "Patient Care", topic: "Infection Control", difficulty: 1, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient presents to the radiology department with a PICC (peripherally inserted central catheter) line in the right arm. The technologist should:", optionA: "Use the PICC line for contrast injection", optionB: "Avoid blood pressure measurement and venipuncture in the arm with the PICC line", optionC: "Remove the PICC line before imaging", optionD: "Ignore the PICC line", correctAnswer: "B", rationale: "Blood pressure cuffs and venipuncture should be avoided in the arm with a PICC line to prevent occlusion or displacement. PICC lines should only be accessed by trained personnel per institutional policy.", category: "Patient Care", topic: "Medical Equipment", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "The proper sequence for donning personal protective equipment (PPE) for contact and droplet precautions is:", optionA: "Gloves, gown, mask, eye protection", optionB: "Gown, mask/respirator, eye protection, gloves", optionC: "Mask, gown, gloves, eye protection", optionD: "Eye protection, mask, gown, gloves", correctAnswer: "B", rationale: "CDC-recommended donning sequence: gown first, then mask or respirator, then eye protection (goggles/face shield), then gloves last (over gown cuffs). This order minimizes contamination risk.", category: "Patient Care", topic: "Infection Control", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A patient receiving anticoagulant therapy (warfarin) requires venipuncture for contrast injection. The technologist should be aware that:", optionA: "Venipuncture is absolutely contraindicated", optionB: "Extended pressure (5+ minutes) should be applied after venipuncture to prevent hematoma formation", optionC: "A larger gauge needle should be used", optionD: "No special precautions are needed", correctAnswer: "B", rationale: "Patients on anticoagulants are at increased risk for bleeding and hematoma formation after venipuncture. Extended direct pressure (5 or more minutes) should be applied after needle removal to ensure hemostasis.", category: "Patient Care", topic: "Venipuncture", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A radiograph of a post-operative patient reveals a sponge (retained surgical item) in the abdomen. The technologist's responsibility is to:", optionA: "Ignore it as it's not the technologist's role", optionB: "Immediately notify the radiologist or attending physician", optionC: "Remove the sponge", optionD: "Document it in the patient's chart directly", correctAnswer: "B", rationale: "Retained surgical items are serious findings requiring immediate notification of the radiologist and/or attending physician. The technologist should never diagnose but must communicate findings that may indicate an emergency.", category: "Patient Care", topic: "Legal & Ethics", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "An 84-year-old patient with osteoporosis needs to be moved from the stretcher to the X-ray table. The SAFEST transfer method is:", optionA: "Have the patient stand and pivot", optionB: "Use a slide board with two or more assistants and gentle lateral transfer", optionC: "Lift the patient in a bear hug", optionD: "Have the patient roll off the stretcher", correctAnswer: "B", rationale: "Patients with osteoporosis are at high risk for fractures. A slide board with multiple assistants provides the safest transfer, minimizing torque and impact forces that could cause pathologic fractures.", category: "Patient Care", topic: "Body Mechanics", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "The medical-legal term for performing a procedure on a patient without their consent is:", optionA: "Negligence", optionB: "Battery", optionC: "Malpractice", optionD: "Libel", correctAnswer: "B", rationale: "Battery is the unauthorized touching of another person. Performing any medical procedure, including radiographic examinations, without the patient's consent constitutes battery, which is both a tort and potentially a crime.", category: "Patient Care", topic: "Legal & Ethics", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "knowledge" },
  { question: "A patient with thyrotoxicosis (hyperthyroidism) is at increased risk when receiving which type of contrast?", optionA: "Barium sulfate", optionB: "Iodinated contrast media", optionC: "Gadolinium-based contrast", optionD: "Air contrast", correctAnswer: "B", rationale: "Iodinated contrast contains free iodine that can exacerbate thyrotoxicosis or trigger thyroid storm in patients with hyperthyroidism. Thyroid function should be evaluated and the radiologist consulted before administration.", category: "Patient Care", topic: "Contrast Media", difficulty: 4, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "When performing hand hygiene with alcohol-based hand rub, the minimum contact time required is:", optionA: "5 seconds", optionB: "20 seconds", optionC: "60 seconds", optionD: "2 minutes", correctAnswer: "B", rationale: "Alcohol-based hand sanitizer should be applied and rubbed over all surfaces of both hands for a minimum of 20 seconds until the hands are dry. If hands are visibly soiled, soap and water should be used instead.", category: "Patient Care", topic: "Infection Control", difficulty: 1, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "knowledge" },
  { question: "A patient's SpO2 reading on pulse oximetry is 88%. This indicates:", optionA: "Normal oxygenation", optionB: "Hypoxemia requiring supplemental oxygen and physician notification", optionC: "Equipment malfunction", optionD: "Normal for elderly patients", correctAnswer: "B", rationale: "Normal SpO2 is 95-100%. An SpO2 of 88% indicates significant hypoxemia. The technologist should administer supplemental oxygen (if authorized), position the patient upright if possible, and immediately notify the physician.", category: "Patient Care", topic: "Vital Signs", difficulty: 2, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "For sterile procedures in radiology (such as myelography), the technologist must maintain a sterile field. Which action would break sterile technique?", optionA: "Reaching above the sterile field to hand an instrument to the physician", optionB: "Opening sterile packages away from the body", optionC: "Keeping sterile items above waist level", optionD: "Facing the sterile field at all times", correctAnswer: "A", rationale: "Reaching over a sterile field potentially drops non-sterile particles onto the field, breaking sterile technique. Items should be passed around the field, not over it. The field is considered sterile only from waist to shoulder level.", category: "Patient Care", topic: "Infection Control", difficulty: 3, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
  { question: "A post-surgical patient has an indwelling urinary catheter (Foley). During the radiographic exam, the drainage bag should be:", optionA: "Placed on the X-ray table next to the patient", optionB: "Kept below the level of the patient's bladder at all times", optionC: "Clamped during the examination", optionD: "Hung on the IV pole above the patient", correctAnswer: "B", rationale: "The Foley drainage bag must always remain below the level of the bladder to prevent retrograde flow of urine, which can cause urinary tract infection. It should never be placed on the table or elevated.", category: "Patient Care", topic: "Medical Equipment", difficulty: 1, country: "usa", exam: "arrt", examDomain: "Patient Care", masteryCategory: "clinical" },
];

async function seed() {
  let inserted = 0;
  for (const q of QUESTIONS) {
    const exists = await pool.query(`SELECT id FROM imaging_questions WHERE question = $1 AND country = $2 LIMIT 1`, [q.question, q.country]);
    if (exists.rows.length === 0) {
      await pool.query(
        `INSERT INTO imaging_questions (id, question, option_a, option_b, option_c, option_d, correct_answer, rationale, category, topic, difficulty, country, body_part, modality, exam, exam_domain, mastery_category, status, created_at, updated_at)
         VALUES (gen_random_uuid(), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,'published',NOW(),NOW())`,
        [q.question, q.optionA, q.optionB, q.optionC, q.optionD, q.correctAnswer, q.rationale, q.category, q.topic, q.difficulty, q.country, q.bodyPart||null, q.modality||null, q.exam, q.examDomain, q.masteryCategory||null]
      );
      inserted++;
    }
  }
  console.log(`[Batch1 ARRT Patient Care] Inserted ${inserted}/${QUESTIONS.length} questions`);
}

seed().then(() => pool.end()).catch(e => { console.error(e); pool.end(); });
