import pg from "pg";
import crypto from "crypto";
const Pool = pg.Pool;
const pool = new Pool({ connectionString: process.env.PROD_DATABASE_URL || process.env.DATABASE_URL });
function hash(s: string): string { return crypto.createHash("md5").update(s.toLowerCase().trim()).digest("hex"); }

interface Q {
  tier: string; exam: string; stem: string; options: string[];
  correct: number; rationale: string; diff: number; bs: string;
  topic: string; subtopic: string; tags: string[]; clinicalPearl: string;
}

function q(bs: string, d: number, s: string, o: string[], c: number, r: string, topic: string, subtopic: string, tags: string[], pearl: string): Q {
  return { tier: "rn", exam: "NCLEX-RN", stem: s, options: o, correct: c, rationale: r, diff: d, bs, topic, subtopic, tags, clinicalPearl: pearl };
}

const QS: Q[] = [
  // ============================================================
  // CARDIAC ADDITIONAL SET 2 (15)
  // ============================================================
  q("Cardiovascular", 3, "A nurse assesses a client with peripheral edema, ascites, and hepatomegaly. These findings are most consistent with:", ["Left-sided heart failure", "Right-sided heart failure causing systemic venous congestion", "Pulmonary embolism", "Aortic stenosis"], 1, "Right-sided heart failure causes systemic venous congestion, resulting in peripheral edema, jugular venous distension, hepatomegaly (congested liver), ascites, and weight gain. Left-sided HF causes pulmonary congestion (dyspnea, crackles, orthopnea). In many cases, left-sided failure leads to right-sided failure over time. Option A causes pulmonary symptoms. Options C and D present differently.", "Heart Failure", "Right-Sided vs Left-Sided", ["cardiac", "heart-failure", "assessment", "edema"], "Right HF = systemic congestion (edema, JVD, hepatomegaly). Left HF = pulmonary congestion (dyspnea, crackles, orthopnea). Most common cause of right HF is left HF."),

  q("Cardiovascular", 2, "A client asks the nurse to explain the purpose of an echocardiogram. The nurse should explain:", ["It is an invasive procedure requiring sedation", "It uses ultrasound waves to create images of the heart, showing chamber size, valve function, and ejection fraction", "It measures electrical activity of the heart", "It is the same as a cardiac catheterization"], 1, "Echocardiography is a non-invasive ultrasound-based imaging study that evaluates cardiac structure and function. It assesses chamber size and wall thickness, valve function (stenosis, regurgitation), ejection fraction (normal 55-70%), wall motion abnormalities, pericardial effusion, and congenital defects. Option A — it is non-invasive. Option C describes an ECG. Option D is invasive.", "Cardiac Diagnostics", "Echocardiography", ["cardiac", "echocardiogram", "diagnostics", "patient-education"], "Echocardiogram: non-invasive, no radiation, shows EF (normal 55-70%). TEE (transesophageal echo) is semi-invasive and provides better views of posterior structures, valves, and atrial appendage."),

  q("Cardiovascular", 3, "A nurse is monitoring a client after thrombolytic therapy for STEMI. Which finding indicates successful reperfusion?", ["Continued ST elevation", "Resolution of chest pain, return of ST segments to baseline, and reperfusion dysrhythmias", "Increasing troponin levels over 72 hours", "Persistent T-wave inversions only"], 1, "Signs of successful reperfusion after thrombolytic therapy: relief of chest pain, resolution of ST elevation on ECG, reperfusion dysrhythmias (accelerated idioventricular rhythm, PVCs), early peaking and rapid fall of cardiac biomarkers (washout phenomenon). Option A suggests ongoing occlusion. Option C may be expected but is not specific to reperfusion. Option D alone is insufficient.", "Acute Coronary Syndrome", "Reperfusion Assessment", ["cardiac", "STEMI", "thrombolytics", "reperfusion"], "Reperfusion signs: pain relief, ST resolution, reperfusion arrhythmias (AIVR), early CK-MB peak (washout). AIVR is usually benign and self-limiting — do NOT treat with antiarrhythmics."),

  q("Cardiovascular", 4, "A client with severe aortic stenosis is being evaluated for transcatheter aortic valve replacement (TAVR). The nurse should teach that TAVR is preferred when:", ["The client is young and otherwise healthy", "The client is at high or prohibitive surgical risk for traditional open-heart valve replacement", "The client has mild aortic stenosis", "All clients with aortic stenosis should get TAVR"], 1, "TAVR is a minimally invasive alternative to surgical aortic valve replacement (SAVR) where a prosthetic valve is delivered via catheter (usually femoral artery). It is primarily indicated for patients at intermediate, high, or prohibitive surgical risk. Benefits include shorter recovery time, no sternotomy, and reduced perioperative morbidity. Option A — younger, low-risk patients may benefit more from SAVR. Option C — intervention only for severe AS. Option D is too broad.", "Valvular Heart Disease", "TAVR", ["cardiac", "TAVR", "aortic-stenosis", "minimally-invasive"], "TAVR: catheter-based valve replacement via femoral artery. Indicated for intermediate to prohibitive surgical risk. Complications: paravalvular leak, conduction abnormalities (may need pacemaker), vascular complications, stroke."),

  q("Cardiovascular", 2, "A nurse is caring for a client with heart failure who is weighed daily. A weight gain of 2 pounds overnight most likely indicates:", ["Increased caloric intake", "Fluid retention of approximately 1 liter", "Muscle gain", "Scale inaccuracy"], 1, "One liter of fluid weighs approximately 2.2 pounds (1 kg). An overnight weight gain of 2 pounds strongly suggests fluid retention rather than true weight gain from caloric intake (which requires approximately 3,500 excess calories per pound). Daily weights should be obtained at the same time, with similar clothing, on the same scale. Clients should report a gain of 2-3 pounds in 24 hours or 5 pounds in a week. Option A is unlikely overnight. Options C and D are improbable.", "Heart Failure", "Weight Monitoring", ["cardiac", "heart-failure", "daily-weights", "fluid-balance"], "Daily weight rule: 1 kg (2.2 lbs) = 1 liter of fluid. Weigh same time, same scale, similar clothing. Report: >2 lbs/day or >5 lbs/week to provider."),

  // ============================================================
  // RESPIRATORY ADDITIONAL SET 2 (15)
  // ============================================================
  q("Respiratory", 3, "A client with severe pneumonia develops sepsis and ARDS. The nurse should anticipate which ventilator setting to improve oxygenation?", ["Decreasing PEEP to 0 cmH2O", "Increasing PEEP to recruit collapsed alveoli and improve oxygenation", "Decreasing FiO2 to 21%", "Increasing tidal volume to 15 mL/kg"], 1, "PEEP (positive end-expiratory pressure) maintains alveolar recruitment at end-expiration, preventing atelectasis and improving oxygenation. In ARDS, higher PEEP levels (10-20 cmH2O) are often needed. The ARDSNet protocol uses PEEP/FiO2 tables to guide titration. Option A removes alveolar support. Option C may cause hypoxemia. Option D violates lung-protective ventilation.", "ARDS", "PEEP Titration", ["respiratory", "ARDS", "PEEP", "ventilation"], "PEEP in ARDS: maintains alveolar recruitment, improves V/Q matching. Monitor for hemodynamic effects (decreased venous return, decreased CO). Titrate using PEEP/FiO2 tables. Optimal PEEP balances oxygenation and hemodynamics."),

  q("Respiratory", 2, "A nurse is caring for a client who underwent a lobectomy. Which exercise should the nurse encourage in the early postoperative period?", ["Heavy lifting to strengthen the chest wall", "Deep breathing exercises, incentive spirometry, and early ambulation", "Holding the breath for extended periods", "Bed rest for the first 5 days"], 1, "Post-lobectomy pulmonary rehabilitation: deep breathing exercises (prevent atelectasis), incentive spirometry (10 times/hour while awake), coughing with splinting (pillow against chest), early ambulation (prevents DVT and pneumonia), and pain management to facilitate these activities. Option A is contraindicated in the early postoperative period. Option C does not promote gas exchange. Option D increases complications.", "Post-Thoracic Surgery", "Pulmonary Rehabilitation", ["respiratory", "lobectomy", "post-operative", "exercises"], "Post-lobectomy: IS 10x/hr, early ambulation, splinted coughing, turn q2h. Pain control is essential for compliance with pulmonary exercises. Monitor chest tube output and air leak."),

  q("Respiratory", 3, "A client develops a hemothorax after blunt chest trauma. The nurse expects the chest tube drainage to initially appear:", ["Clear and serous", "Bloody (sanguineous), with output monitored hourly for excessive bleeding", "Green-tinged", "Purulent"], 1, "Hemothorax (blood in the pleural space) results in bloody chest tube drainage. Monitor drainage output hourly — massive hemothorax (>1,500 mL initial or >200 mL/hr for 2-4 hours) may require thoracotomy. Auto-transfusion may be indicated for large hemothoraces. Option A is seen with pleural effusion. Option C suggests bile contamination. Option D suggests empyema.", "Chest Trauma", "Hemothorax", ["respiratory", "hemothorax", "trauma", "chest-tube"], "Hemothorax: bloody CT drainage. Massive hemothorax: >1500mL initial or >200mL/hr x 2-4 hrs = surgical intervention. Auto-transfusion may be performed. Type and crossmatch on admission."),

  q("Respiratory", 3, "A client with COPD is prescribed tiotropium (Spiriva) via a dry powder inhaler. The nurse should teach:", ["Shake the inhaler vigorously before use", "Do not shake; inhale quickly and deeply through the mouthpiece to draw the powder into the lungs", "Exhale into the device before inhaling", "Use a spacer with this device"], 1, "Dry powder inhalers (DPIs) like Spiriva HandiHaler require a QUICK, DEEP inhalation to disperse the powder and deliver it to the lungs. Unlike MDIs, DPIs do NOT require shaking, do NOT use spacers, and the patient should NOT exhale into the device (moisture clumps the powder). Option A — DPIs are not shaken. Option C — moisture damages the powder. Option D — spacers are for MDIs.", "COPD", "Inhaler Technique", ["respiratory", "COPD", "tiotropium", "DPI-technique"], "DPI technique: do NOT shake, do NOT exhale into device, inhale QUICKLY and DEEPLY. MDI technique: inhale SLOWLY. Key difference to teach patients: DPI = fast inhale, MDI = slow inhale."),

  q("Respiratory", 4, "A nurse is caring for a client on a high-flow nasal cannula (HFNC) at 60 L/min. The nurse understands that HFNC provides:", ["Only supplemental oxygen", "Humidified heated oxygen, low-level PEEP effect, washout of dead space CO2, and more precise FiO2 delivery", "The same effect as a simple nasal cannula", "Mechanical ventilation equivalent"], 1, "HFNC provides several physiologic benefits: precise FiO2 delivery (21-100%), heated humidification (improves mucociliary clearance), low-level PEEP effect (2-7 cmH2O depending on flow), nasopharyngeal dead space washout (improves CO2 clearance), and improved patient comfort versus NIPPV masks. It can delay or prevent intubation in some patients. Option A is incomplete. Option C vastly understates benefits. Option D overstates its capabilities.", "Oxygen Therapy", "High-Flow Nasal Cannula", ["respiratory", "HFNC", "oxygen-therapy", "critical-care"], "HFNC benefits: precise FiO2, heated humidity, mild PEEP, dead space washout. May avoid intubation in mild-moderate respiratory failure. Monitor: if no improvement in 1-2 hours, escalate to NIV or intubation."),

  // ============================================================
  // GI ADDITIONAL SET 2 (15)
  // ============================================================
  q("Gastrointestinal", 3, "A client with liver failure develops coagulopathy with an INR of 3.5. The nurse understands this occurs because:", ["The liver is producing too many clotting factors", "The damaged liver cannot synthesize adequate clotting factors, resulting in bleeding risk", "The client is receiving warfarin", "Vitamin K intake is excessive"], 1, "The liver is the primary site of synthesis for most clotting factors (I, II, V, VII, IX, X, XI, XII). When the liver is severely damaged, it cannot produce adequate clotting factors, leading to prolonged PT/INR and increased bleeding risk. Treatment: vitamin K (may be ineffective if liver is severely damaged), FFP (provides immediate clotting factors), and cryoprecipitate (provides fibrinogen). Option A is incorrect. Options C and D assume external causes.", "Liver Failure", "Coagulopathy", ["GI", "liver-failure", "coagulopathy", "lab-values"], "Liver failure coagulopathy: liver makes most clotting factors. Elevated PT/INR reflects synthetic function. Treatment: vitamin K (may not work), FFP, cryoprecipitate, platelet transfusion. Avoid IM injections and invasive procedures."),

  q("Gastrointestinal", 2, "A client with a new colostomy asks about foods that may cause odor. The nurse should advise that the following foods can increase odor:", ["Rice and bananas", "Eggs, onions, garlic, asparagus, and beans", "Applesauce and cheese", "Bread and potatoes"], 1, "Odor-producing foods: eggs, onions, garlic, asparagus, beans, cabbage, fish, and spicy foods. Odor-reducing foods: yogurt, buttermilk, parsley, and cranberry juice. Internal pouch deodorants are also available. Gas-producing foods: beans, broccoli, cabbage, carbonated beverages. Options A, C, and D generally do not increase odor significantly.", "Colostomy", "Dietary Education", ["GI", "colostomy", "ostomy-diet", "patient-education"], "Ostomy diet: Odor-causing: eggs, onions, garlic, asparagus, fish. Gas-causing: beans, broccoli, cabbage, soda. Thickening: rice, bananas, cheese, pasta. Loosening: prune juice, raw fruits/vegetables."),

  q("Gastrointestinal", 3, "A client with acute pancreatitis should be positioned:", ["Supine with legs straight", "Side-lying with knees flexed to the chest (fetal position) to reduce pain", "Prone", "Trendelenburg"], 1, "The fetal position (side-lying with knees flexed to the chest) reduces tension on the abdomen and decreases pain by reducing pressure on the inflamed pancreas. NPO status with NG tube suction may be needed. Pain management with IV opioids is essential (morphine was previously avoided due to concern about sphincter of Oddi spasm, but this is now considered safe). Option A increases abdominal tension. Options C and D do not help.", "Pancreatitis", "Pain Management", ["GI", "pancreatitis", "positioning", "pain"], "Pancreatitis position: fetal position (knees to chest). NPO initially, advance diet as tolerated. Monitor for complications: pseudocyst, abscess, hemorrhage, organ failure. Ranson criteria predict severity."),

  q("Gastrointestinal", 4, "A client with Crohn's disease develops a fistula between the ileum and bladder. The nurse should expect:", ["No symptoms", "Pneumaturia (air in urine), fecaluria (feces in urine), and recurrent UTIs", "Hematochezia only", "Constipation"], 1, "An enterovesical (bowel-to-bladder) fistula allows intestinal contents to pass into the bladder, causing pneumaturia (passage of gas during urination), fecaluria (fecal material in urine), and recurrent polymicrobial UTIs. This is a serious complication of Crohn's disease requiring surgical repair. Option A ignores significant symptoms. Options C and D are unrelated to fistula.", "Inflammatory Bowel Disease", "Fistula Complications", ["GI", "crohns", "fistula", "complications"], "Crohn's fistulas: enteroenteric (bowel-bowel), enterovesical (bowel-bladder), enterocutaneous (bowel-skin), rectovaginal. Management: antibiotics, immunosuppression, surgical repair. TNF inhibitors may help close fistulas."),

  q("Gastrointestinal", 2, "A nurse is teaching a client with irritable bowel syndrome (IBS) about dietary management. Which recommendation is appropriate?", ["Eliminate all fiber from the diet", "Gradually increase soluble fiber, identify trigger foods through a food diary, and consider a low-FODMAP diet", "Eat large, infrequent meals", "Increase caffeine intake for motility"], 1, "IBS dietary management: gradually increase soluble fiber (oats, psyllium — helps both constipation and diarrhea), keep a food diary to identify personal triggers, consider a low-FODMAP diet (reduces fermentable oligosaccharides, disaccharides, monosaccharides, and polyols), eat small frequent meals, and adequate hydration. Common triggers: caffeine, alcohol, fatty foods, dairy, and FODMAPs. Option A eliminates beneficial fiber. Option C worsens symptoms. Option D can worsen IBS.", "IBS", "Dietary Management", ["GI", "IBS", "nutrition", "FODMAP"], "IBS diet: low-FODMAP (avoid garlic, onion, wheat, lactose, certain fruits). Soluble fiber helps both IBS-C and IBS-D. Food diary essential for trigger identification. Peppermint oil may reduce cramping."),

  // ============================================================
  // RENAL ADDITIONAL SET 2 (15)
  // ============================================================
  q("Renal/Urinary", 3, "A client with chronic kidney disease asks why erythropoietin (EPO) injections are needed. The nurse explains:", ["EPO replaces iron in the blood", "Damaged kidneys cannot produce adequate erythropoietin, which is needed to stimulate red blood cell production in the bone marrow", "EPO is a diuretic", "EPO prevents kidney stones"], 1, "The kidneys are the primary source of erythropoietin, a hormone that stimulates the bone marrow to produce red blood cells. In CKD, damaged kidneys produce insufficient EPO, leading to normocytic, normochromic anemia. Synthetic EPO (epoetin alfa, darbepoetin alfa) replaces this hormone. Iron supplementation is often needed concurrently. Option A — EPO stimulates RBC production, not iron replacement. Options C and D are incorrect.", "Chronic Kidney Disease", "Anemia Management", ["renal", "CKD", "erythropoietin", "anemia"], "CKD anemia: kidneys make EPO. Damaged kidneys = less EPO = fewer RBCs. Treat: EPO injection + iron supplementation. Target Hgb 10-12 g/dL. Monitor iron stores (ferritin, TSAT) before starting."),

  q("Renal/Urinary", 3, "A nurse is caring for a client with a suprapubic catheter. Which assessment finding warrants immediate action?", ["Small amount of clear drainage around the catheter site", "Catheter dislodgement with no urine output and increasing abdominal distension", "Mild discomfort at the insertion site", "Slight skin redness at the insertion site"], 1, "Suprapubic catheter dislodgement is an emergency because the tract can close rapidly (within hours), potentially requiring surgical replacement. No urine output with abdominal distension suggests bladder distension without drainage. Immediate notification of the provider and possible reinsertion is needed. Option A may be normal. Options C and D require monitoring but are not emergencies.", "Urinary Catheterization", "Suprapubic Catheter", ["renal", "catheter", "suprapubic", "emergency"], "Suprapubic catheter: do NOT remove unless replacing — tract closes rapidly. If dislodged, cover site with sterile gauze and notify provider immediately. Advantages over urethral: lower UTI risk, easier hygiene, more comfortable."),

  q("Renal/Urinary", 2, "A client asks about the difference between hemodialysis and peritoneal dialysis. The nurse should explain that peritoneal dialysis:", ["Requires a vascular access and uses an artificial kidney", "Uses the peritoneal membrane as a natural filter, can be done at home, and allows more dietary freedom", "Is always performed in a hospital setting", "Cannot be done by the patient independently"], 1, "Peritoneal dialysis (PD) uses the peritoneal membrane as the dialysis membrane. Advantages: home-based, continuous (more physiologic), greater dietary freedom, no vascular access needed, better preservation of residual kidney function. Disadvantages: peritonitis risk, protein loss, body image concerns (catheter), and requires adequate peritoneal membrane function. Option A describes hemodialysis. Options C and D are incorrect.", "Dialysis", "PD vs HD Comparison", ["renal", "peritoneal-dialysis", "hemodialysis", "patient-education"], "PD advantages: home-based, continuous, dietary freedom, no needles, preserves residual function. HD advantages: efficient (3x/week, 3-4 hrs), done in clinic, no abdominal catheter. Choice depends on patient preference, lifestyle, and clinical factors."),

  q("Renal/Urinary", 3, "A client with acute kidney injury has a serum potassium of 6.8 mEq/L. Insulin and dextrose are administered IV. The nurse understands this works by:", ["Eliminating potassium from the body", "Driving potassium from the extracellular space into the cells, temporarily lowering serum potassium", "Increasing renal potassium excretion", "Converting potassium to a non-toxic form"], 1, "Insulin stimulates the sodium-potassium ATPase pump, driving potassium from the extracellular space into cells. Dextrose (D50) is given concurrently to prevent hypoglycemia. This is a TEMPORARY measure — it redistributes potassium but does not remove it from the body. Actual potassium removal requires kayexalate, loop diuretics, or dialysis. Effect begins within 15-30 minutes and lasts 4-6 hours. Option A is incorrect. Options C and D are wrong mechanisms.", "Acute Kidney Injury", "Potassium Management", ["renal", "hyperkalemia", "insulin-dextrose", "electrolytes"], "Hyperkalemia treatment steps: 1) Calcium gluconate (stabilize membrane), 2) Insulin + D50 (shift K+ into cells), 3) Sodium bicarb (shift K+), 4) Albuterol nebulizer (shift K+), 5) Kayexalate/patiromer (remove K+), 6) Dialysis (remove K+)."),

  q("Renal/Urinary", 3, "A nurse is caring for a client with polycystic kidney disease (PKD). The nurse should teach:", ["PKD only affects the kidneys", "PKD is hereditary and can also cause liver cysts, cerebral aneurysms, and cardiac valve abnormalities; monitor blood pressure closely", "PKD is caused by infection", "PKD resolves spontaneously in adulthood"], 1, "Autosomal dominant PKD (ADPKD) is a genetic disorder causing multiple fluid-filled cysts in the kidneys. Extra-renal manifestations include hepatic cysts (most common), cerebral aneurysms (berry aneurysms — risk of subarachnoid hemorrhage), cardiac valve abnormalities (mitral valve prolapse), and diverticular disease. Hypertension is common and must be controlled. Option A underestimates systemic nature. Options C and D are incorrect.", "Polycystic Kidney Disease", "Systemic Manifestations", ["renal", "PKD", "hereditary", "cerebral-aneurysm"], "PKD: autosomal dominant, progressive CKD. Monitor: BP (strict control), renal function, liver cysts, screen for cerebral aneurysms (family history of SAH). Tolvaptan may slow cyst growth. Avoid NSAIDs and nephrotoxins."),

  // ============================================================
  // NEURO ADDITIONAL SET 2 (15)
  // ============================================================
  q("Neurological", 3, "A nurse is caring for a client with Bell's palsy. The nurse should teach:", ["The condition is permanent", "Protect the affected eye from drying and corneal injury; most cases resolve within 3-6 months", "Vigorous facial exercises should begin immediately", "The client should avoid all social interactions"], 1, "Bell's palsy is sudden unilateral facial paralysis (CN VII). Most cases (85%) resolve spontaneously within 3-6 months. Eye care is critical: artificial tears during the day, lubricating ointment and eye patching at night, and sunglasses outdoors to prevent corneal drying and injury. Treatment: corticosteroids (prednisone) within 72 hours, antiviral if herpes suspected. Option A is usually incorrect. Option C may cause injury. Option D is unnecessary.", "Bell's Palsy", "Patient Teaching", ["neuro", "bells-palsy", "cranial-nerves", "eye-care"], "Bell's palsy: CN VII, unilateral. Eye care is priority (protect from corneal ulceration). Prednisone within 72 hrs improves outcomes. 85% recover fully. If no improvement in 3-6 months, consider further workup."),

  q("Neurological", 4, "A client with a ventriculoperitoneal (VP) shunt develops headache, vomiting, decreased LOC, and bulging fontanelle (if infant). The nurse suspects:", ["Normal post-operative finding", "VP shunt malfunction causing increased ICP", "Dehydration", "Migraine headache"], 1, "VP shunt malfunction (obstruction, disconnection, or infection) causes CSF accumulation and increased ICP. Signs: headache (worse in morning, with position change), nausea/vomiting, decreased LOC, visual changes, and bulging fontanelle in infants. This is a neurosurgical emergency. Shunt infection may present with fever, meningeal signs, and abdominal symptoms. Options A, C, and D do not explain the constellation of findings.", "Hydrocephalus", "Shunt Malfunction", ["neuro", "VP-shunt", "hydrocephalus", "ICP"], "VP shunt malfunction signs: headache, vomiting, decreased LOC, bulging fontanelle (infants), sunset eyes (infants). Emergency: notify neurosurgery. Shunt infection: fever + shunt malfunction signs. Do NOT pump the shunt reservoir without physician order."),

  q("Neurological", 3, "A client with amyotrophic lateral sclerosis (ALS) asks about disease progression. The nurse should explain:", ["ALS causes cognitive decline primarily", "ALS progressively destroys motor neurons, leading to muscle weakness, atrophy, and eventually respiratory failure, while cognition typically remains intact", "ALS is a relapsing-remitting disease", "ALS primarily affects sensory nerves"], 1, "ALS (Lou Gehrig's disease) selectively destroys upper and lower motor neurons. Cognition, sensation, vision, and bowel/bladder control are typically preserved. Progression: limb weakness → dysarthria → dysphagia → respiratory failure (usual cause of death, median survival 2-5 years). Riluzole (glutamate antagonist) may modestly extend survival. Option A is incorrect. Option C describes MS. Option D is wrong.", "ALS", "Disease Progression", ["neuro", "ALS", "motor-neuron-disease", "prognosis"], "ALS: motor neurons only — cognition INTACT. Upper motor neuron signs (spasticity, hyperreflexia) + lower motor neuron signs (weakness, atrophy, fasciculations). Riluzole extends survival modestly. Focus: respiratory support, nutrition, communication aids."),

  q("Neurological", 2, "A nurse is providing discharge teaching after a concussion. The client should be instructed to:", ["Resume all contact sports immediately", "Rest for 24-48 hours, gradually return to activities, and seek emergency care for worsening headache, vomiting, confusion, or unequal pupils", "Take aspirin for headache", "Sleep as much as possible without any monitoring"], 1, "Concussion discharge teaching: cognitive and physical rest for 24-48 hours, gradual return to activity following a stepwise protocol, acetaminophen for headache (NOT aspirin or NSAIDs — bleeding risk), and return to ED if: worsening or severe headache, repeated vomiting, seizures, confusion, unequal pupils, weakness/numbness, or inability to be awakened. Option A risks second impact syndrome. Option C increases bleeding risk. Option D — monitoring is essential.", "Traumatic Brain Injury", "Concussion Management", ["neuro", "concussion", "TBI", "patient-education"], "Concussion red flags: worsening headache, repeated vomiting, seizure, unequal pupils, confusion, slurred speech, weakness. Return to play protocol: stepwise progression over days-weeks. Second impact syndrome can be fatal."),

  q("Neurological", 3, "A client with a history of seizures is prescribed levetiracetam (Keppra). The nurse should monitor for:", ["Hepatotoxicity", "Behavioral changes including irritability, aggression, and mood disturbances", "Gingival hyperplasia", "Visual field defects"], 1, "Levetiracetam (Keppra) is generally well-tolerated with fewer drug interactions than older anticonvulsants. However, behavioral side effects are notable: irritability, aggression, mood changes, depression, and psychosis. These are more common in patients with pre-existing psychiatric conditions. Advantage: no routine drug level monitoring needed, renal excretion (no hepatic metabolism). Option A is rare with Keppra. Option C is phenytoin. Option D is vigabatrin.", "Seizure Disorders", "Levetiracetam Side Effects", ["neuro", "levetiracetam", "seizures", "behavioral-effects"], "Keppra: behavioral side effects (irritability, aggression, depression) in ~10% of patients. Advantages: no drug level monitoring, minimal drug interactions, renal elimination. Consider pyridoxine supplementation to reduce behavioral effects."),

  // ============================================================
  // ENDOCRINE ADDITIONAL SET 2 (15)
  // ============================================================
  q("Endocrine", 3, "A client with type 1 diabetes is wearing an insulin pump. The nurse should teach that if the pump malfunctions:", ["Wait until the next scheduled appointment", "Check blood glucose immediately and administer a correction dose of rapid-acting insulin by injection; do not wait", "Switch to oral hypoglycemics temporarily", "Reduce physical activity and wait"], 1, "Insulin pumps deliver continuous rapid-acting insulin (basal-bolus). If the pump malfunctions or disconnects, the client has NO insulin delivery and can develop DKA within hours. Emergency action: check blood glucose, administer rapid-acting insulin by injection using sick-day rules, check ketones, troubleshoot the pump, and contact the endocrinologist. Option A risks DKA. Option C is inappropriate for type 1. Option D does not address the insulin deficit.", "Diabetes Technology", "Insulin Pump Malfunction", ["endocrine", "diabetes", "insulin-pump", "emergency"], "Insulin pump malfunction: DKA can develop within 4-6 hours (no basal insulin). Always carry backup insulin pens and syringes. Check BG q2h, correct with injection, check ketones. Resume pump when issue resolved."),

  q("Endocrine", 2, "A client with hypothyroidism asks about expected symptoms before treatment. The nurse should explain:", ["Increased metabolism and weight loss", "Fatigue, weight gain, cold intolerance, constipation, dry skin, and bradycardia due to decreased metabolism", "Anxiety and tachycardia", "Increased appetite and diarrhea"], 1, "Hypothyroidism (decreased thyroid hormone) slows metabolism: fatigue, weight gain, cold intolerance, constipation, dry/coarse skin, brittle nails, hair loss, bradycardia, menstrual irregularities, depression, and myxedema (facial/periorbital edema). Severe untreated hypothyroidism can progress to myxedema coma (hypothermia, hypoventilation, hyponatremia, altered LOC). Options A, C, and D describe hyperthyroidism.", "Hypothyroidism", "Clinical Manifestations", ["endocrine", "hypothyroidism", "assessment", "metabolism"], "Hypo vs Hyper thyroid: Hypo = everything slows down (cold, constipated, bradycardia, weight gain). Hyper = everything speeds up (heat intolerant, diarrhea, tachycardia, weight loss). Treatment: hypo = levothyroxine, hyper = methimazole/PTU or RAI."),

  q("Endocrine", 3, "A client with type 2 diabetes is started on an SGLT2 inhibitor (empagliflozin/Jardiance). The nurse should teach about:", ["No specific precautions needed", "Risk of genital yeast infections, UTIs, and euglycemic DKA; maintain adequate hydration", "Taking the medication with insulin only", "Avoiding all carbohydrates"], 1, "SGLT2 inhibitors work by blocking glucose reabsorption in the kidneys, causing glycosuria. Side effects: genital mycotic infections (increased glucose in urine), UTIs, dehydration/hypotension, and euglycemic DKA (DKA with normal or mildly elevated glucose — particularly in type 1 diabetes, fasting, or illness). Benefits: weight loss, cardiovascular and renal protection. Option A ignores important precautions. Options C and D are incorrect.", "Diabetes Medications", "SGLT2 Inhibitors", ["endocrine", "diabetes", "SGLT2", "pharmacology"], "SGLT2 inhibitors: glycosuria = yeast infections. Watch for euglycemic DKA (DKA with normal glucose). Benefits: weight loss, CV protection, renal protection. Hold before surgery and during illness."),

  q("Endocrine", 4, "A nurse is caring for a client in myxedema coma. Priority interventions include:", ["Oral levothyroxine and warming with heating blankets", "IV levothyroxine or liothyronine, IV hydrocortisone, passive rewarming, supportive care, and possible intubation", "Oral iodine therapy", "IV insulin administration"], 1, "Myxedema coma is the most severe form of hypothyroidism with life-threatening features: hypothermia, hypoventilation, hypotension, hyponatremia, hypoglycemia, and altered mental status. Treatment: IV thyroid hormone (levothyroxine loading dose), IV hydrocortisone (prevent adrenal crisis — cortisol may be depleted), PASSIVE rewarming (active warming causes vasodilation and cardiovascular collapse), respiratory support, and correction of hyponatremia/hypoglycemia. Option A is too slow. Options C and D are incorrect.", "Myxedema Coma", "Emergency Management", ["endocrine", "myxedema-coma", "hypothyroidism", "critical-care"], "Myxedema coma: IV levothyroxine + IV hydrocortisone. PASSIVE rewarming only (heating blankets cause vasodilation/shock). Correct hyponatremia with fluid restriction, NOT hypertonic saline initially. ICU-level care required."),

  q("Endocrine", 3, "A client with type 2 diabetes has an HbA1C of 9.5%. The nurse understands this corresponds to an estimated average glucose of approximately:", ["150 mg/dL", "180 mg/dL", "226 mg/dL", "126 mg/dL"], 2, "The estimated average glucose (eAG) can be calculated from HbA1C using the formula: eAG = (28.7 × A1C) − 46.7. For A1C 9.5%: (28.7 × 9.5) − 46.7 = 272.65 − 46.7 = approximately 226 mg/dL. This indicates poor glycemic control requiring intensification of therapy. The ADA target A1C for most adults is <7% (eAG ~154 mg/dL). Options A, B, and D are incorrect calculations.", "Diabetes Management", "HbA1C Interpretation", ["endocrine", "diabetes", "HbA1C", "glycemic-control"], "HbA1C to eAG: 6% = 126 mg/dL, 7% = 154 mg/dL, 8% = 183 mg/dL, 9% = 212 mg/dL, 10% = 240 mg/dL. Formula: eAG = (28.7 × A1C) − 46.7. Each 1% A1C change ≈ 29 mg/dL eAG change."),

  // ============================================================
  // HEMATOLOGY/ONCOLOGY ADDITIONAL (15)
  // ============================================================
  q("Hematology", 3, "A nurse is caring for a client receiving a blood transfusion who develops back pain, fever, chills, and dark urine within the first 15 minutes. The nurse suspects:", ["Mild allergic reaction", "Acute hemolytic transfusion reaction requiring immediate intervention", "Febrile non-hemolytic reaction", "Circulatory overload"], 1, "Acute hemolytic transfusion reaction (ABO incompatibility) presents within minutes: back/flank pain (from hemolysis in kidneys), fever, chills, dark red/brown urine (hemoglobinuria), hypotension, tachycardia, and chest tightness. Immediate actions: STOP the transfusion, maintain IV access with NS, send blood bag and client blood samples to the lab, and monitor for DIC and acute kidney injury. Option A is too mild. Option C has fever but no hemolysis. Option D causes dyspnea.", "Blood Transfusion", "Hemolytic Reaction", ["hematology", "transfusion-reaction", "hemolysis", "emergency"], "Hemolytic transfusion reaction: STOP transfusion immediately, keep IV open with NS, send blood bag + patient samples to blood bank, monitor for DIC and renal failure. Most common cause: clerical error (wrong blood given to wrong patient)."),

  q("Hematology", 2, "A client receiving chemotherapy asks why regular oral care is important during treatment. The nurse explains:", ["Oral care is only cosmetic during chemotherapy", "Chemotherapy damages rapidly dividing cells including oral mucosa, causing stomatitis that can lead to infection, poor nutrition, and systemic sepsis", "Oral care prevents tooth discoloration only", "Oral care is only needed if pain develops"], 1, "Chemotherapy targets rapidly dividing cells, including the oral mucosa. Stomatitis/mucositis can be severe, causing painful ulcerations that impair eating and serve as portals for infection (especially dangerous in neutropenic patients). Oral care: soft toothbrush, mild toothpaste, salt/baking soda rinses, avoid alcohol-based mouthwashes, and cryotherapy during certain chemo infusions. Options A, C, and D minimize an important complication.", "Chemotherapy", "Oral Mucositis", ["hematology", "oncology", "stomatitis", "oral-care"], "Chemo oral care: soft brush, salt/baking soda rinse q4h, avoid alcohol mouthwash, lip moisturizer. Oral cryotherapy (ice chips during 5-FU infusion) reduces mucositis. Grade 3-4 mucositis may require TPN."),

  q("Hematology", 3, "A client with multiple myeloma should be monitored for which metabolic emergency?", ["Hypoglycemia", "Hypercalcemia from bone destruction", "Hypokalemia", "Metabolic alkalosis"], 1, "Multiple myeloma causes extensive bone destruction through osteoclast activation, releasing large amounts of calcium into the blood. Hypercalcemia manifestations: confusion, constipation, polyuria, weakness, nausea, cardiac dysrhythmias, and shortened QT interval. Treatment: aggressive IV hydration (NS), loop diuretics, bisphosphonates (zoledronic acid), calcitonin for rapid onset. Other myeloma complications: renal failure, anemia, infections, pathologic fractures.", "Multiple Myeloma", "Hypercalcemia", ["hematology", "oncology", "hypercalcemia", "multiple-myeloma"], "Multiple myeloma complications (CRAB): Calcium elevated, Renal insufficiency, Anemia, Bone lesions. Bence Jones protein in urine. Serum protein electrophoresis shows M-spike. Avoid dehydration and nephrotoxic drugs."),

  q("Hematology", 3, "A nurse is caring for a client with a port-a-cath (implanted venous access device). Before accessing, the nurse should:", ["Use a regular needle", "Use a non-coring (Huber) needle to access the port and clean the site with chlorhexidine", "Access the port through the skin without cleaning", "Ask the client to remove the port cover themselves"], 1, "Implanted ports require a non-coring (Huber) needle for access. A regular needle would damage the septum and compromise the port. Sterile technique is essential: clean the site with chlorhexidine, use sterile gloves, and verify blood return before infusion. Flush with NS before and after use, and heparin lock per protocol. The port can remain in place for years. Options A, C, and D are incorrect.", "Vascular Access", "Port Access", ["hematology", "port-a-cath", "vascular-access", "procedures"], "Port-a-cath: Huber needle only (non-coring), sterile technique, verify blood return, flush with NS then heparin lock. Change Huber needle every 7 days if continuous infusion. Accessed ports need transparent dressing."),

  q("Hematology", 4, "A client with acute promyelocytic leukemia (APL) begins treatment with all-trans retinoic acid (ATRA). The nurse should monitor for:", ["Hypoglycemia", "Differentiation syndrome (fever, dyspnea, weight gain, pleural effusions, pulmonary infiltrates)", "Hypothyroidism", "Hyperkalemia"], 1, "Differentiation syndrome (formerly retinoic acid syndrome) occurs in 25% of APL patients treated with ATRA. Maturing leukemic cells cause cytokine release leading to: fever, dyspnea, weight gain, pulmonary infiltrates, pleural/pericardial effusions, and sometimes renal failure. Treatment: dexamethasone. If severe, temporarily discontinue ATRA. Early recognition and treatment significantly reduce mortality. Options A, C, and D are not associated with ATRA.", "Leukemia", "Differentiation Syndrome", ["hematology", "oncology", "APL", "ATRA"], "APL + ATRA: monitor for differentiation syndrome (fever + dyspnea + weight gain = treat immediately with dexamethasone). APL also has high DIC risk. ATRA + arsenic trioxide = high cure rate."),

  // ============================================================
  // MUSCULOSKELETAL ADDITIONAL (15)
  // ============================================================
  q("Musculoskeletal", 3, "A client with a total knee replacement is prescribed continuous passive motion (CPM) machine therapy. The nurse should:", ["Set the CPM to full range immediately", "Start at a low degree of flexion and gradually increase as tolerated per provider orders", "Use the CPM for 24 hours continuously", "Apply ice over the CPM device"], 1, "CPM therapy after total knee replacement promotes early range of motion, reduces joint stiffness, prevents adhesion formation, and decreases swelling. Start at a low degree of flexion (typically 30-40 degrees) and gradually increase to 90+ degrees over days per provider orders. Use for prescribed intervals (typically 6-8 hours/day). Assess neurovascular status frequently. Option A may cause pain and damage. Option C is excessive. Option D impedes heat transmission from the machine.", "Total Knee Replacement", "CPM Therapy", ["musculoskeletal", "TKR", "CPM", "rehabilitation"], "CPM after TKR: start low, increase gradually. Goal: 90° flexion by discharge. Also: ice/elevation for swelling, incentive spirometry, DVT prophylaxis (LMWH + SCDs), early ambulation with walker."),

  q("Musculoskeletal", 2, "A nurse is teaching a client with osteoarthritis about joint protection. Which instruction is correct?", ["Push through pain during exercise", "Use the largest and strongest joints for tasks, maintain proper body mechanics, and rest when joints become painful", "Avoid all physical activity", "Use only hot compresses, never ice"], 1, "Joint protection principles for osteoarthritis: use large joints over small ones (carry bags on forearms, not fingers), maintain proper body mechanics, pace activities with rest breaks, use assistive devices (reachers, jar openers, raised toilet seats), avoid prolonged static positions, and exercise regularly (low-impact: swimming, cycling, walking). Option A worsens joint damage. Option C leads to deconditioning. Option D — both ice and heat are beneficial.", "Osteoarthritis", "Joint Protection", ["musculoskeletal", "osteoarthritis", "joint-protection", "patient-education"], "OA joint protection: big joints for heavy tasks, assistive devices, balance activity and rest. Exercise: low-impact 30 min/day. Weight loss reduces knee joint stress by 4 lbs for every 1 lb lost."),

  q("Musculoskeletal", 3, "A nurse is caring for a client with a fat embolism after a long bone fracture. The classic presentation includes:", ["Chest pain and hemoptysis only", "Petechial rash on the chest and axillae, respiratory distress, and altered mental status occurring 24-72 hours after fracture", "Immediate bleeding from the fracture site", "Jaundice and abdominal pain"], 1, "Fat embolism syndrome typically presents 24-72 hours after long bone fracture (especially femur) or orthopedic surgery. Classic triad: respiratory distress (most common), neurological changes (confusion, agitation, decreased LOC), and petechial rash (chest, axillae, conjunctivae — PATHOGNOMONIC but appears in only 50-60% of cases). Treatment: supportive (O2, mechanical ventilation if needed). Prevention: early stabilization of fractures. Options A, C, and D are incorrect presentations.", "Fracture Complications", "Fat Embolism", ["musculoskeletal", "fat-embolism", "fracture", "emergency"], "Fat embolism triad: respiratory distress + neurological changes + petechial rash. Occurs 24-72 hrs post long bone fracture. Prevention: early fracture fixation. Petechiae on chest/axillae are pathognomonic but late finding."),

  q("Musculoskeletal", 3, "A client with ankylosing spondylitis asks about exercise recommendations. The nurse should advise:", ["Avoid all exercise due to spine involvement", "Regular stretching, swimming, and posture exercises to maintain spinal flexibility and prevent fusion in a flexed position", "Only high-impact exercises", "Complete bed rest during flares"], 1, "Ankylosing spondylitis causes progressive spinal fusion. Exercise is essential to maintain flexibility, prevent fixed flexion deformity, and preserve function. Recommended: daily stretching, range of motion exercises, swimming (low-impact, full body), posture training (sleep on a firm mattress with a thin pillow to promote spinal extension). NSAIDs are first-line pharmacotherapy. Option A worsens stiffness. Option C may be too aggressive. Option D promotes deconditioning.", "Ankylosing Spondylitis", "Exercise Therapy", ["musculoskeletal", "ankylosing-spondylitis", "exercise", "posture"], "Ankylosing spondylitis: maintain erect posture, sleep on firm mattress with thin/no pillow, daily stretching/swimming. NSAIDs first-line. TNF inhibitors for refractory disease. Monitor for anterior uveitis."),

  q("Musculoskeletal", 2, "A client in a hip spica cast reports a burning sensation under the cast. The nurse should:", ["Ignore the complaint as casts normally feel warm", "Assess for pressure injury by checking the cast edges and notifying the provider; do NOT insert objects under the cast", "Pour water under the cast for relief", "Cut a window in the cast immediately"], 1, "Burning sensation under a cast may indicate a pressure injury developing over a bony prominence. NEVER insert objects (coat hangers, rulers) under the cast — they can injure the skin. NEVER pour substances under the cast (causes skin breakdown, mold). Assess cast edges for pressure points, check for hot spots (feel the cast surface), note any foul odor (may indicate skin breakdown or infection), and notify the provider for cast window or adjustment. Options A, C, and D are incorrect.", "Cast Care", "Pressure Injury Prevention", ["musculoskeletal", "cast-care", "skin-integrity", "patient-education"], "Cast complaints: burning/hot spots = potential pressure injury. NEVER put anything under the cast. Blow cool air (hair dryer on cool setting) for itching. Petaling cast edges prevents skin irritation. Assess neurovascular status: 5 P's."),

  // ============================================================
  // IMMUNOLOGY ADDITIONAL (10)
  // ============================================================
  q("Immunological", 3, "A nurse is caring for a client with a known allergy to eggs. The client asks about receiving the influenza vaccine. The nurse should explain:", ["All flu vaccines are contraindicated", "Most current flu vaccines contain minimal or no egg protein and can be safely administered; an egg-free vaccine (recombinant) is also available", "The client should receive the live attenuated vaccine instead", "No vaccines can ever be given to this client"], 1, "Updated CDC guidelines indicate that most flu vaccines contain very little egg protein and can be safely given to egg-allergic patients in any healthcare setting. Egg-free recombinant influenza vaccines (Flublok) are available for those with severe egg allergy (anaphylaxis). All patients should be observed for 15-30 minutes post-vaccination. Option A is outdated. Option C — live attenuated is also grown in eggs. Option D is incorrect.", "Immunizations", "Egg Allergy and Vaccines", ["immunology", "vaccination", "egg-allergy", "influenza"], "Egg allergy + flu vaccine: CDC says safe for all severity levels. Observe 15-30 min. Recombinant vaccine (Flublok) is egg-free alternative. Yellow fever vaccine is the only vaccine that requires caution with egg allergy."),

  q("Immunological", 3, "A client with rheumatoid arthritis is prescribed a biologic DMARD (adalimumab/Humira). Before starting therapy, the nurse should ensure:", ["No pre-treatment screening is needed", "TB screening, hepatitis B screening, and updated vaccinations are completed before starting", "The client has stopped all other RA medications", "Only a CBC is needed"], 1, "Before starting biologic DMARDs (anti-TNF agents like adalimumab), patients must be screened for: latent TB (PPD or IGRA — TNF-alpha is essential for TB granuloma maintenance), hepatitis B (risk of reactivation), and age-appropriate vaccinations should be updated (live vaccines are contraindicated during therapy). Also screen for active infections and malignancy history. Options A and D are insufficient. Option C is not always required.", "Rheumatoid Arthritis", "Biologic Pre-Treatment Screening", ["immunology", "biologics", "adalimumab", "pre-treatment"], "Biologic DMARD pre-treatment: TB screen (PPD/IGRA), HBV screen, update vaccines (no live vaccines during therapy), CBC, LFTs. Monitor for injection site reactions, serious infections, and malignancy."),

  q("Immunological", 2, "A client asks about the differences between contact precautions and droplet precautions. The nurse should explain:", ["They are the same", "Contact precautions require gloves and gown for direct contact; droplet precautions require a surgical mask within 3-6 feet of the patient", "Both require N95 respirators", "Neither requires hand hygiene"], 1, "Contact precautions: for diseases spread by direct/indirect contact (MRSA, VRE, C. diff, scabies). PPE: gloves and gown. Dedicated equipment. Droplet precautions: for diseases spread by large respiratory droplets (influenza, pertussis, meningococcal meningitis, strep pharyngitis). PPE: surgical mask within 3-6 feet. Option A is incorrect. Option C — N95 is for airborne precautions. Option D — hand hygiene is always required.", "Infection Control", "Transmission-Based Precautions", ["immunology", "infection-control", "isolation", "PPE"], "Isolation types: Contact = gloves + gown (MRSA, C. diff). Droplet = surgical mask within 6 feet (flu, pertussis). Airborne = N95 + negative pressure room (TB, measles, varicella). Hand hygiene ALWAYS required."),

  // ============================================================
  // PHARMACOLOGY ADDITIONAL SET 2 (80+ questions)
  // ============================================================
  q("Pharmacology", 3, "A client is prescribed enoxaparin for DVT prophylaxis after hip replacement. The nurse should administer:", ["Into the deltoid muscle using an 18-gauge needle", "Subcutaneously into the abdomen, alternating sides, without aspirating or massaging", "Intravenously over 30 minutes", "Into the vastus lateralis muscle"], 1, "Enoxaparin (Lovenox) is given SC into the abdominal wall (at least 2 inches from the umbilicus). Do NOT aspirate (increases bruising), do NOT massage (increases hematoma), and do NOT expel the air bubble (it clears the needle of medication). Rotate injection sites. Monitor platelet count for HIT. Options A, C, and D are incorrect administration routes for enoxaparin.", "Anticoagulant Therapy", "Enoxaparin Technique", ["pharmacology", "enoxaparin", "DVT-prophylaxis", "injection-technique"], "Enoxaparin injection: abdomen SC only, do NOT aspirate, do NOT massage, leave air bubble, rotate sites. Monitor platelets for HIT. Bridge to warfarin if long-term anticoagulation needed."),

  q("Pharmacology", 2, "A nurse is teaching a client about the antihypertensive losartan. The client should avoid:", ["Dairy products", "Potassium supplements and salt substitutes containing potassium chloride", "Leafy green vegetables", "All citrus fruits"], 1, "ARBs (losartan, valsartan, irbesartan) block angiotensin II receptors, leading to potassium retention similar to ACE inhibitors. Clients should avoid potassium supplements, potassium-containing salt substitutes (KCl), and excessive high-potassium foods when combined with other potassium-sparing drugs. Monitor serum potassium. Unlike ACE inhibitors, ARBs do NOT cause dry cough. Options A, C, and D are not significant interactions.", "ARBs", "Potassium Monitoring", ["pharmacology", "ARB", "losartan", "hyperkalemia"], "ARBs: no dry cough (unlike ACE inhibitors). Similar K+ retention risk. Contraindicated in pregnancy (like ACE-I). Monitor: K+, BUN, creatinine. Can cause first-dose hypotension."),

  q("Pharmacology", 3, "A client on long-term proton pump inhibitor therapy develops hypomagnesemia. The nurse should teach:", ["This is unrelated to the PPI", "PPIs can cause magnesium depletion with long-term use; report muscle cramps, tremors, or irregular heartbeat", "Increase dairy intake to prevent this", "No action needed if asymptomatic"], 1, "Long-term PPI use (>1 year) can impair intestinal magnesium absorption, leading to hypomagnesemia. Symptoms: muscle cramps, tremors, tetany, cardiac arrhythmias (QT prolongation), and seizures. The FDA issued a warning in 2011. Management: monitor magnesium levels periodically, supplement if needed, and consider step-down to H2 blockers when possible. Option A ignores the established association. Option C is insufficient. Option D ignores potential cardiac risks.", "Proton Pump Inhibitors", "Hypomagnesemia", ["pharmacology", "PPI", "magnesium", "long-term-effects"], "PPI-induced hypomagnesemia: usually after >1 year of use. May not respond to Mg supplementation until PPI is discontinued. Can cause secondary hypocalcemia and hypokalemia. FDA safety alert issued 2011."),

  q("Pharmacology", 3, "A client is prescribed tissue plasminogen activator (alteplase) for acute ischemic stroke. Which is an absolute contraindication?", ["Blood pressure 170/95 mmHg that is controlled to <185/110 with treatment", "Active internal bleeding or recent (within 3 months) hemorrhagic stroke", "Age greater than 65 years", "Diabetes mellitus"], 1, "Absolute contraindications for IV tPA in stroke include: active internal bleeding, recent hemorrhagic stroke (within 3 months), recent intracranial/spinal surgery (within 3 months), intracranial neoplasm, known AVM/aneurysm, and platelet count <100,000. BP must be controlled to <185/110 before administration (this is a relative issue, not an absolute contraindication if controlled). Options A (controllable), C (age), and D (diabetes) are not absolute contraindications.", "Thrombolytic Therapy", "Contraindications", ["pharmacology", "tPA", "stroke", "contraindications"], "tPA absolute contraindications: active bleeding, recent hemorrhagic stroke, intracranial surgery <3 months, AVM/aneurysm, platelets <100K, INR >1.7. BP must be <185/110 before administration."),

  q("Pharmacology", 2, "A client asks why fluconazole was prescribed along with antibiotics. The nurse explains:", ["Fluconazole is an antibiotic", "Antibiotics can disrupt normal flora, allowing fungal overgrowth; fluconazole prevents or treats fungal infections", "Fluconazole enhances antibiotic effectiveness", "It is given to all clients on antibiotics"], 1, "Broad-spectrum antibiotics kill normal bacterial flora that compete with fungi for resources. This disruption allows opportunistic fungal overgrowth (candidiasis — oral thrush, vaginal yeast infections, systemic candidiasis in immunocompromised). Fluconazole is an antifungal that prevents or treats these superinfections. Option A — it is an antifungal. Option C is incorrect. Option D — not all antibiotic patients need antifungals.", "Antifungals", "Superinfection Prevention", ["pharmacology", "fluconazole", "antifungal", "superinfection"], "Fluconazole: antifungal (azole class). Monitor LFTs (hepatotoxic). Drug interactions via CYP450 inhibition (increases warfarin, phenytoin, cyclosporine levels). Oral candidiasis prevention in immunosuppressed patients."),

  q("Pharmacology", 3, "A nurse is administering packed red blood cells (PRBCs). Which IV solution is compatible?", ["Dextrose 5% in water", "Normal saline (0.9% NaCl)", "Lactated Ringer's solution", "Dextrose 5% in 0.45% NaCl"], 1, "Only 0.9% normal saline is compatible with blood product transfusion. Dextrose solutions cause RBC hemolysis (osmotic swelling and lysis). Lactated Ringer's contains calcium, which can initiate clotting in the tubing (calcium activates the coagulation cascade). Use Y-tubing with a 170-260 micron blood filter. Option A causes hemolysis. Option C causes clotting. Option D contains dextrose.", "Blood Transfusion", "IV Solution Compatibility", ["pharmacology", "blood-transfusion", "IV-compatibility", "safety"], "Blood transfusion: NS only, no meds through blood tubing, 170-260 micron filter, complete within 4 hours, verify blood type with 2 nurses. VS: baseline, 15 min, 30 min, hourly, post-transfusion."),

  q("Pharmacology", 3, "A client is receiving norepinephrine (Levophed) for septic shock. The nurse should monitor for:", ["Hypotension as the primary concern", "Tissue ischemia from excessive vasoconstriction, extravasation injury, and cardiac dysrhythmias", "Bronchospasm", "Hypoglycemia"], 1, "Norepinephrine is a potent alpha-1 agonist (vasoconstriction) with some beta-1 activity (cardiac stimulation). It is the first-line vasopressor for septic shock. Risks: excessive vasoconstriction causing tissue ischemia (monitor extremity perfusion, urine output), extravasation causing tissue necrosis (use central line, have phentolamine available), and dysrhythmias. Option A is the indication, not the complication. Options C and D are not primary concerns.", "Vasopressors", "Norepinephrine Monitoring", ["pharmacology", "norepinephrine", "septic-shock", "vasoconstriction"], "Norepinephrine: first-line vasopressor for septic shock. Central line preferred (vesicant). Monitor: MAP target 65-70 mmHg, UO, peripheral perfusion, lactate. Extravasation: phentolamine rescue."),

  q("Pharmacology", 2, "A nurse is administering a first dose of an IV antibiotic. The nurse should observe the client for at least the first:", ["5 minutes", "15-30 minutes for signs of allergic or anaphylactic reaction", "2 hours", "No special observation is needed for IV antibiotics"], 1, "The first dose of any antibiotic (especially penicillins, cephalosporins, and vancomycin) carries the highest risk of allergic or anaphylactic reaction. The nurse should observe the client for at least 15-30 minutes after starting the infusion, with emergency equipment readily available (epinephrine, airway management equipment). Monitor for: urticaria, wheezing, hypotension, facial/tongue swelling. Option A is too short. Option C is excessive for standard monitoring. Option D ignores allergy risk.", "Antibiotics", "First Dose Monitoring", ["pharmacology", "antibiotics", "allergy", "anaphylaxis"], "First dose antibiotic: stay at bedside for 15-30 min, emergency equipment nearby. Cross-reactivity: penicillin-cephalosporin 1-2%. Always verify allergy history before administering."),

  q("Pharmacology", 3, "A client is prescribed gabapentin for neuropathic pain. The nurse should teach:", ["The medication works immediately", "The medication may take 1-2 weeks for full effect; do not stop abruptly as this may cause seizures", "Take the medication only during pain episodes", "No side effects are expected"], 1, "Gabapentin is used for neuropathic pain, post-herpetic neuralgia, and seizures. It requires gradual dose titration (start low, go slow) and reaches full therapeutic effect in 1-2 weeks. Abrupt discontinuation can cause seizures (even if not being used as an anticonvulsant). Common side effects: drowsiness, dizziness, peripheral edema, weight gain. Take consistently (not PRN). Option A is incorrect. Option C leads to inconsistent levels. Option D ignores significant side effects.", "Neuropathic Pain", "Gabapentin Education", ["pharmacology", "gabapentin", "neuropathic-pain", "patient-education"], "Gabapentin: titrate slowly up AND down. Side effects: drowsiness (take at bedtime initially), dizziness, edema, weight gain. Renal elimination — adjust dose for CKD. Abuse potential recognized (Schedule V in some states)."),

  q("Pharmacology", 3, "A nurse is teaching a client about the antiplatelet medication ticagrelor (Brilinta). The nurse should advise:", ["Take with a daily aspirin dose of 325 mg", "Take with low-dose aspirin (81 mg) only; aspirin doses above 100 mg reduce ticagrelor's effectiveness", "No aspirin is needed with ticagrelor", "Ticagrelor can be crushed and mixed with food"], 1, "Ticagrelor (Brilinta) must be taken with low-dose aspirin (75-100 mg). The FDA issued a boxed warning that aspirin doses above 100 mg daily reduce ticagrelor's effectiveness. Unlike clopidogrel, ticagrelor is a reversible P2Y12 inhibitor (effects wear off faster). Common side effects: dyspnea (usually mild and self-limiting) and bradycardia. Option A reduces effectiveness. Option C is incorrect. Option D — it can be crushed if needed but the key teaching is about aspirin dose.", "Antiplatelet Therapy", "Ticagrelor Education", ["pharmacology", "ticagrelor", "antiplatelet", "aspirin-interaction"], "Ticagrelor: aspirin must be ≤100 mg/day (boxed warning). Reversible P2Y12 inhibitor. Side effects: dyspnea (common, usually transient), bradycardia. Advantages over clopidogrel: no genetic variability in metabolism (CYP2C19 polymorphisms don't affect it)."),

  q("Pharmacology", 3, "A client is prescribed empagliflozin (Jardiance) for type 2 diabetes with heart failure. The nurse understands this medication has demonstrated:", ["Only blood glucose lowering", "Cardiovascular and renal protective effects independent of glucose lowering", "Increased cardiovascular risk", "No benefit beyond glucose control"], 1, "SGLT2 inhibitors (empagliflozin, dapagliflozin, canagliflozin) have demonstrated significant cardiovascular mortality reduction, heart failure hospitalization reduction, and renal protection in landmark trials (EMPA-REG, DAPA-HF, CREDENCE). These benefits occur independently of glucose lowering. They are now recommended for HFrEF regardless of diabetes status. Option A underestimates benefits. Option C is incorrect. Option D ignores trial evidence.", "SGLT2 Inhibitors", "Cardiovascular Benefits", ["pharmacology", "SGLT2", "heart-failure", "cardiorenal-protection"], "SGLT2 inhibitors: proven CV and renal protection. Now approved for HFrEF even WITHOUT diabetes. Benefits: reduce hospitalization for HF, slow CKD progression, reduce CV death. Monitor for genital infections and euglycemic DKA."),

  q("Pharmacology", 2, "A client is prescribed docusate sodium (Colace). The nurse should explain this medication:", ["Stimulates intestinal peristalsis", "Softens stool by allowing water and fat to penetrate, making passage easier; it may take 1-3 days to work", "Provides immediate relief from constipation", "Is used for diarrhea"], 1, "Docusate sodium is a stool softener (surfactant) that reduces surface tension, allowing water and fat to penetrate the stool mass. It is a PREVENTIVE measure, not for acute constipation relief. Onset: 1-3 days. Best used prophylactically (opioid use, post-surgery, hemorrhoids). For immediate relief, glycerin suppositories or bisacodyl are more appropriate. Option A describes stimulant laxatives. Option C overestimates speed. Option D is incorrect.", "Laxatives", "Stool Softener Education", ["pharmacology", "docusate", "constipation", "bowel-care"], "Stool softener (docusate): preventive, not for acute constipation. Takes 1-3 days. Pair with opioids prophylactically. Laxative types: bulk-forming (psyllium), osmotic (MiraLAX), stimulant (bisacodyl), stool softener (docusate)."),

  q("Pharmacology", 3, "A nurse is monitoring a client receiving cisplatin chemotherapy. The nurse should ensure:", ["Minimal fluid intake to reduce nausea", "Aggressive IV hydration before, during, and after infusion to prevent nephrotoxicity", "No electrolyte monitoring is needed", "The medication is given by IV push"], 1, "Cisplatin is highly nephrotoxic and emetogenic. Aggressive IV hydration (1-2 L NS before and after) maintains renal perfusion and promotes renal excretion of the drug, preventing tubular damage. Monitor: BUN, creatinine, urine output (maintain >100 mL/hr during infusion), and electrolytes (particularly magnesium — cisplatin causes severe hypomagnesemia). Antiemetic prophylaxis with 5-HT3 antagonist + dexamethasone + NK1 antagonist. Option A worsens nephrotoxicity. Options C and D are dangerous.", "Chemotherapy", "Cisplatin Administration", ["pharmacology", "cisplatin", "nephrotoxicity", "chemotherapy"], "Cisplatin: highly nephrotoxic and emetogenic. Aggressive hydration essential. Monitor: creatinine, Mg2+ (severe depletion), K+, hearing (ototoxic). Antiemetic prophylaxis: 5-HT3 + dexamethasone + aprepitant. Monitor UO (target >100 mL/hr)."),

  q("Pharmacology", 3, "A client is prescribed dexamethasone before chemotherapy. The nurse explains this is given to:", ["Treat infection", "Prevent nausea and vomiting as part of the antiemetic regimen, and reduce inflammation", "Increase white blood cell production", "Treat pain"], 1, "Dexamethasone is a key component of chemotherapy antiemetic protocols (combined with 5-HT3 antagonists like ondansetron and NK1 antagonists like aprepitant). It enhances the antiemetic effect of other agents, reduces inflammation, and helps prevent hypersensitivity reactions to certain chemotherapy agents (paclitaxel, docetaxel). Option A is not the purpose in this context. Option C — steroids actually suppress immunity. Option D is not the primary reason.", "Chemotherapy Support", "Dexamethasone as Antiemetic", ["pharmacology", "dexamethasone", "antiemetic", "chemotherapy"], "Dexamethasone in chemo: antiemetic potentiator, prevents hypersensitivity reactions (taxanes), reduces peritumoral edema (brain tumors). Short-term use minimizes steroid side effects."),

  q("Pharmacology", 4, "A client is receiving alteplase (tPA) for acute STEMI. The nurse should monitor for which most dangerous complication?", ["Hyperglycemia", "Hemorrhage, especially intracranial hemorrhage", "Hypertension", "Hyperkalemia"], 1, "The most dangerous complication of thrombolytic therapy is hemorrhage, particularly intracranial hemorrhage (ICH), which occurs in approximately 0.5-1% of STEMI patients receiving tPA. Monitor: neurological status (any change warrants stat CT), vital signs, bleeding from all sites (IV sites, gums, GI, GU), hemoglobin/hematocrit, and coagulation studies. Avoid invasive procedures during and after tPA administration. Options A, C, and D are not the primary complications.", "Thrombolytic Therapy", "Bleeding Complications", ["pharmacology", "tPA", "hemorrhage", "STEMI"], "Post-tPA monitoring: neuro checks q15min x 2hrs then q30min x 6hrs. Any headache or neuro change = stop tPA + stat CT. Avoid: IM injections, arterial puncture, invasive procedures for 24 hrs. Keep BP <180/105 post-tPA for stroke."),

  q("Pharmacology", 2, "A nurse is teaching a client about the cholesterol-absorption inhibitor ezetimibe (Zetia). The nurse should explain:", ["It works the same way as statins", "It blocks cholesterol absorption in the small intestine and can be taken at any time of day, with or without food", "It replaces the need for dietary changes", "It requires frequent liver function monitoring"], 1, "Ezetimibe selectively inhibits the NPC1L1 receptor at the brush border of the small intestine, reducing cholesterol absorption by approximately 50%. It can be taken at any time, with or without food, and has minimal side effects. It is often combined with statins for enhanced LDL reduction. Option A — different mechanism. Option C — dietary modifications are still important. Option D — minimal hepatotoxicity.", "Antilipemics", "Ezetimibe Education", ["pharmacology", "ezetimibe", "cholesterol", "patient-education"], "Ezetimibe: blocks intestinal cholesterol absorption. Take any time. Minimal side effects. Combined with statin: additional 15-20% LDL reduction. IMPROVE-IT trial showed CV benefit of ezetimibe + statin."),

  q("Pharmacology", 3, "A nurse is caring for a client prescribed cyclosporine after organ transplantation. The nurse should monitor for:", ["Hypoglycemia", "Nephrotoxicity, hypertension, and gingival hyperplasia", "Respiratory depression", "Bleeding"], 1, "Cyclosporine is a calcineurin inhibitor immunosuppressant with significant toxicity profile: nephrotoxicity (dose-limiting — monitor creatinine, BUN), hypertension, gingival hyperplasia, hirsutism, tremor, hepatotoxicity, and increased infection/malignancy risk. Drug levels must be monitored (narrow therapeutic index). Avoid grapefruit juice (increases levels). Options A, C, and D are not primary cyclosporine concerns.", "Immunosuppressants", "Cyclosporine Monitoring", ["pharmacology", "cyclosporine", "transplant", "nephrotoxicity"], "Cyclosporine monitoring: trough levels (narrow therapeutic index), creatinine, BUN, LFTs, BP, CBC. Grapefruit increases levels. Gingival hyperplasia + hirsutism = common. Nephrotoxic — distinguish from rejection."),

  q("Pharmacology", 3, "A client with chronic pain is started on duloxetine (Cymbalta) for diabetic neuropathy. The nurse should teach:", ["Immediate pain relief is expected", "Full pain relief may take 2-4 weeks; do not stop abruptly due to discontinuation syndrome", "Take only during pain episodes", "Alcohol use is unrestricted"], 1, "Duloxetine is an SNRI approved for diabetic peripheral neuropathy, fibromyalgia, chronic musculoskeletal pain, and major depression. It requires 2-4 weeks for full analgesic effect. Abrupt discontinuation causes SNRI discontinuation syndrome (dizziness, nausea, headache, paresthesias, brain zaps). Take daily, not PRN. Avoid alcohol (hepatotoxicity risk). Monitor liver function. Option A is incorrect. Option C is wrong. Option D is dangerous.", "SNRIs", "Duloxetine for Neuropathy", ["pharmacology", "duloxetine", "neuropathic-pain", "SNRI"], "Duloxetine: SNRI for neuropathic pain, fibromyalgia, depression. Takes 2-4 weeks. Taper gradually (never abrupt). Avoid alcohol. Monitor LFTs. Contraindicated in severe liver disease and with MAOIs."),

  q("Pharmacology", 2, "A client asks why a loading dose of digoxin is given before starting a maintenance dose. The nurse explains:", ["To test for allergic reactions", "A loading dose rapidly achieves therapeutic drug levels, which would otherwise take days to reach with maintenance dosing alone due to the drug's long half-life", "It is just tradition", "Loading doses are cheaper"], 1, "Digoxin has a long half-life (36-48 hours). Without a loading dose (digitalization), it would take approximately 5-7 half-lives (about 1 week) to reach steady-state therapeutic levels. The loading dose rapidly achieves therapeutic concentration. Digitalization: total loading dose 0.75-1.5 mg IV or PO given in divided doses over 24 hours. Then maintenance dose begins. Monitor: heart rate, rhythm, and serum levels. Option A is incorrect. Options C and D are wrong.", "Cardiac Glycosides", "Loading Dose Rationale", ["pharmacology", "digoxin", "loading-dose", "pharmacokinetics"], "Digoxin loading (digitalization): gives in divided doses (half, then quarter, then quarter) over 24 hrs. Monitor ECG for toxicity. Steady state without loading: ~7 days. Therapeutic level: 0.5-2.0 ng/mL."),

  q("Pharmacology", 3, "A client is prescribed trimethoprim-sulfamethoxazole (Bactrim). The nurse should advise:", ["Avoid sun exposure entirely", "Increase fluid intake to prevent crystalluria, use sunscreen for photosensitivity, and report rash immediately", "Take with antacids for stomach protection", "This medication is safe in pregnancy"], 1, "TMP-SMX can cause crystalluria (precipitation of drug in renal tubules) — prevented by adequate hydration (2-3 L/day). Photosensitivity reactions occur — use sunscreen and protective clothing. Rash may indicate Stevens-Johnson syndrome (discontinue immediately). Other side effects: hyperkalemia (TMP blocks K+ secretion), bone marrow suppression, hepatitis. Contraindicated in pregnancy (teratogenic). Options A (not entirely), C (not needed), and D are incorrect.", "Antibiotics", "TMP-SMX Patient Teaching", ["pharmacology", "bactrim", "crystalluria", "photosensitivity"], "TMP-SMX: adequate hydration (prevent crystalluria), sunscreen (photosensitivity), report any rash (SJS risk). Monitor: CBC, K+ (can cause hyperkalemia), creatinine. Contraindicated in pregnancy and sulfa allergy."),

  q("Pharmacology", 3, "A client with COPD is prescribed roflumilast (Daliresp). The nurse should teach:", ["This medication provides immediate bronchodilation", "This is a PDE4 inhibitor that reduces exacerbation frequency; it is NOT a rescue medication and may take weeks to show benefit", "Use this instead of an inhaler", "No side effects are expected"], 1, "Roflumilast is a phosphodiesterase-4 (PDE4) inhibitor that reduces inflammation in COPD. It is indicated for severe COPD with frequent exacerbations as ADD-ON therapy (not a replacement for bronchodilators). Not a bronchodilator — does not provide immediate symptom relief. Side effects: weight loss, nausea, diarrhea, headache, psychiatric effects (depression, suicidal ideation — monitor closely). Option A is incorrect. Option C is wrong. Option D ignores significant effects.", "COPD Medications", "PDE4 Inhibitor", ["pharmacology", "roflumilast", "COPD", "anti-inflammatory"], "Roflumilast: PDE4 inhibitor for COPD exacerbation prevention. NOT a bronchodilator or rescue med. Monitor: weight, psychiatric symptoms (depression, suicidal ideation), GI effects. Contraindicated in moderate-severe liver impairment."),

  q("Pharmacology", 3, "A nurse is caring for a client receiving IV vasopressin for septic shock. The nurse should monitor for:", ["Hypoglycemia", "Digital ischemia, mesenteric ischemia, and hyponatremia", "Hyperkalemia", "Tachycardia"], 1, "Vasopressin (ADH analog) causes vasoconstriction through V1 receptors and water retention through V2 receptors. In septic shock, it is used as a second-line vasopressor (added to norepinephrine). Complications: digital/extremity ischemia (intense vasoconstriction), mesenteric ischemia (splanchnic vasoconstriction), hyponatremia (water retention via V2 receptors), and cardiac ischemia. Fixed dose: 0.03-0.04 units/min (not titrated like norepinephrine). Options A, C, and D are not primary vasopressin concerns.", "Vasopressors", "Vasopressin Monitoring", ["pharmacology", "vasopressin", "septic-shock", "vasoconstriction"], "Vasopressin in septic shock: fixed dose 0.03-0.04 units/min, NOT titrated. Add to norepinephrine, not replace it. Monitor: peripheral perfusion, skin color, urine output, sodium levels. Watch for coronary ischemia."),

  q("Pharmacology", 2, "A client is prescribed montelukast (Singulair) for asthma. The nurse should teach:", ["Use as a rescue medication during acute attacks", "Take daily in the evening for asthma prevention; this is NOT a rescue inhaler", "Take only during asthma exacerbations", "It replaces all other asthma medications"], 1, "Montelukast is a leukotriene receptor antagonist taken daily for asthma prevention and allergic rhinitis. It blocks leukotriene-mediated bronchoconstriction and inflammation. Take in the evening (peak leukotriene production occurs at night). It is NOT a rescue medication and should NOT replace inhaled corticosteroids for moderate-severe asthma. FDA black box warning: neuropsychiatric events (mood changes, suicidal thoughts). Options A and C describe rescue medication. Option D overestimates its role.", "Asthma Medications", "Leukotriene Modifiers", ["pharmacology", "montelukast", "asthma", "leukotriene"], "Montelukast: take daily in evening (not PRN). Black box warning: mood changes, suicidal ideation — monitor closely. Not a first-line controller (ICS is first-line). Good for exercise-induced asthma and aspirin-sensitive asthma."),

  q("Pharmacology", 3, "A client on warfarin develops a major GI bleed with an INR of 8.5. The nurse should anticipate:", ["Oral vitamin K only", "IV vitamin K and 4-factor prothrombin complex concentrate (PCC) for rapid reversal", "Simply holding warfarin", "Fresh frozen plasma only"], 1, "Major bleeding with supratherapeutic INR requires rapid reversal: IV vitamin K (phytonadione) 10 mg slow IV + 4-factor PCC (contains factors II, VII, IX, X — faster and more effective than FFP). PCC provides immediate factor replacement. FFP is an alternative if PCC is unavailable but requires larger volume and longer administration time. Simply holding warfarin takes days for INR to normalize. Option A is too slow for major bleeding. Option C is insufficient. Option D alone is slower than PCC.", "Anticoagulant Therapy", "Major Bleeding Reversal", ["pharmacology", "warfarin", "bleeding", "reversal"], "Warfarin major bleeding reversal: IV vitamin K + 4-factor PCC (preferred) or FFP. PCC advantages: smaller volume, faster administration, more predictable response. IV vitamin K onset: 6-8 hours (need PCC for immediate reversal)."),
];

async function main() {
  let inserted = 0;
  const batchSize = 50;
  for (let i = 0; i < QS.length; i += batchSize) {
    const batch = QS.slice(i, i + batchSize);
    const values: string[] = [];
    const params: any[] = [];
    let idx = 1;
    for (const item of batch) {
      values.push(`($${idx},$${idx+1},$${idx+2},$${idx+3},$${idx+4},$${idx+5}::jsonb,$${idx+6}::jsonb,$${idx+7},$${idx+8}::integer,$${idx+9},$${idx+10},$${idx+11},$${idx+12},$${idx+13},$${idx+14}::text[],$${idx+15})`);
      params.push(
        item.tier, item.exam, "multiple_choice", "published",
        item.stem, JSON.stringify(item.options), JSON.stringify([item.correct]),
        item.rationale, item.diff, item.bs, "BOTH", hash(item.stem),
        item.topic, item.subtopic, "{" + item.tags.join(",") + "}", item.clinicalPearl
      );
      idx += 16;
    }
    const sql = `INSERT INTO exam_questions (tier, exam, question_type, status, stem, options, correct_answer, rationale, difficulty, body_system, region_scope, stem_hash, topic, subtopic, tags, clinical_pearl)
                 SELECT v.* FROM (VALUES ${values.join(",")}) AS v(tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,body_system,region_scope,stem_hash,topic,subtopic,tags,clinical_pearl)
                 WHERE NOT EXISTS (SELECT 1 FROM exam_questions e WHERE e.stem_hash = v.stem_hash)`;
    const result = await pool.query(sql, params);
    inserted += result.rowCount || 0;
    console.log(`[RN-MedSurg-Pharm-B3] Batch ${Math.floor(i/batchSize)+1}: inserted ${result.rowCount || 0} questions`);
  }
  console.log(`\n[RN-MedSurg-Pharm-B3] Total inserted: ${inserted}/${QS.length}`);
  const counts = await pool.query(`SELECT tier, count(*) as cnt FROM exam_questions WHERE status='published' GROUP BY tier ORDER BY tier`);
  counts.rows.forEach((r: any) => console.log(`  ${r.tier}: ${r.cnt}`));
  await pool.end();
}

main().catch(e => { console.error(e); process.exit(1); });
