import { pool } from "../server/storage";

interface EncEntry {
  slug: string; title: string; category: string;
  seoTitle: string; seoDescription: string; seoKeywords: string[];
  overview: string; mechanismPhysiology: string; clinicalRelevance: string;
  signsSymptoms: string; assessment: string; management: string; complications: string;
  clinicalPearls: string[]; examPitfalls: string[];
  faqJson: { question: string; answer: string }[];
}

const E = (e: EncEntry) => ({ profession: "mlt" as const, status: "published" as const, ...e });

async function insertEntry(e: ReturnType<typeof E>) {
  const topicResult = await pool.query(
    `INSERT INTO encyclopedia_topics (profession, slug, title, category, related_lesson_ids, related_question_ids, status)
     VALUES ($1, $2, $3, $4, $5, $6, $7)
     ON CONFLICT (profession, slug) DO UPDATE SET title = $3, category = $4, updated_at = NOW()
     RETURNING id`,
    [e.profession, e.slug, e.title, e.category, [], [e.category], e.status]
  );
  const topicId = topicResult.rows[0].id;
  await pool.query(
    `INSERT INTO encyclopedia_entries (topic_id, profession, slug, title, category,
      seo_title, seo_description, seo_keywords, overview, mechanism_physiology,
      clinical_relevance, signs_symptoms, assessment, management, complications,
      clinical_pearls, exam_pitfalls, faq_json, related_lesson_ids, related_question_ids,
      related_flashcard_ids, cross_profession_links, image_placeholders, status, published_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,NOW())
     ON CONFLICT (profession, slug) DO UPDATE SET
      title=EXCLUDED.title, category=EXCLUDED.category,
      seo_title=EXCLUDED.seo_title, seo_description=EXCLUDED.seo_description, seo_keywords=EXCLUDED.seo_keywords,
      overview=EXCLUDED.overview, mechanism_physiology=EXCLUDED.mechanism_physiology,
      clinical_relevance=EXCLUDED.clinical_relevance, signs_symptoms=EXCLUDED.signs_symptoms,
      assessment=EXCLUDED.assessment, management=EXCLUDED.management, complications=EXCLUDED.complications,
      clinical_pearls=EXCLUDED.clinical_pearls, exam_pitfalls=EXCLUDED.exam_pitfalls, faq_json=EXCLUDED.faq_json,
      status=EXCLUDED.status, updated_at=NOW()`,
    [topicId, e.profession, e.slug, e.title, e.category,
      e.seoTitle, e.seoDescription, e.seoKeywords,
      e.overview, e.mechanismPhysiology, e.clinicalRelevance,
      e.signsSymptoms, e.assessment, e.management, e.complications,
      JSON.stringify(e.clinicalPearls), JSON.stringify(e.examPitfalls), JSON.stringify(e.faqJson),
      [], [e.category], [], JSON.stringify([]), JSON.stringify([]), e.status]
  );
}

const ENTRIES = [
  // ======== HEMATOLOGY ========
  E({ slug: "hereditary-spherocytosis", title: "Hereditary Spherocytosis", category: "Hematology",
    seoTitle: "Hereditary Spherocytosis – MLT Encyclopedia", seoDescription: "Hereditary spherocytosis: osmotic fragility, spherocytes, spectrin deficiency for MLT exam.", seoKeywords: ["hereditary spherocytosis", "osmotic fragility", "spherocytes", "spectrin", "MLT exam"],
    overview: "Hereditary spherocytosis (HS) is the most common inherited hemolytic anemia in Northern Europeans. It results from defects in red cell membrane skeleton proteins (spectrin, ankyrin, band 3, protein 4.2) causing loss of membrane surface area and formation of spherocytes.",
    mechanismPhysiology: "Defects in vertical interactions between the lipid bilayer and underlying spectrin skeleton cause membrane loss as the RBC traverses the spleen. Progressive membrane loss converts the normal biconcave disc to a sphere (spherocyte). Spherocytes are rigid and cannot deform through splenic sinusoids, leading to splenic sequestration and extravascular hemolysis.",
    clinicalRelevance: "Autosomal dominant in 75% of cases. Severity ranges from asymptomatic carrier to severe transfusion-dependent anemia. Spherocytes have decreased surface-to-volume ratio, causing increased osmotic fragility (the hallmark diagnostic test).",
    signsSymptoms: "Anemia, jaundice, splenomegaly (triad). Aplastic crisis (parvovirus B19 infection), pigment gallstones (bilirubin), neonatal jaundice.",
    assessment: "CBC: normocytic normochromic anemia, elevated MCHC (>36 g/dL—characteristic), increased RDW. Peripheral smear: spherocytes (small, round, no central pallor). Osmotic fragility test: INCREASED (spherocytes lyse at higher NaCl concentrations than normal). Incubated osmotic fragility: more sensitive. DAT: NEGATIVE (differentiates from autoimmune hemolytic anemia). Eosin-5-maleimide (EMA) binding test: decreased fluorescence (flow cytometry—most sensitive screening test).",
    management: "Splenectomy: curative for symptomatic patients (eliminates the site of RBC destruction). Folic acid supplementation (chronic hemolysis). Vaccinations pre-splenectomy (pneumococcal, meningococcal, H. influenzae type b). Cholecystectomy if gallstones symptomatic.",
    complications: "Aplastic crisis (parvovirus B19), pigment gallstones, folate deficiency megaloblastic anemia, post-splenectomy sepsis.",
    clinicalPearls: ["MCHC >36 g/dL is characteristic of spherocytosis (one of the few conditions with elevated MCHC)", "Osmotic fragility is INCREASED in HS (spherocytes lyse sooner in hypotonic saline)", "DAT is NEGATIVE in HS but POSITIVE in autoimmune hemolytic anemia—critical differentiator"],
    examPitfalls: ["Spherocytes in HS vs AIHA: HS = DAT negative; AIHA = DAT positive", "Parvovirus B19 causes aplastic crisis (reticulocyte count drops to zero) not hemolytic crisis", "EMA binding test is replacing osmotic fragility as the screening test of choice"],
    faqJson: [{ question: "Why is MCHC elevated?", answer: "Spherocytes have lost membrane but retain hemoglobin, resulting in a higher hemoglobin concentration per unit volume (elevated MCHC >36 g/dL)." }, { question: "Why does splenectomy help?", answer: "The spleen is the site of spherocyte destruction. Removing it eliminates extravascular hemolysis. Spherocytes persist post-splenectomy but no longer hemolyzed." }]
  }),
  E({ slug: "hemoglobin-c-disease", title: "Hemoglobin C Disease", category: "Hematology",
    seoTitle: "Hemoglobin C Disease – MLT Encyclopedia", seoDescription: "Hemoglobin C: target cells, HbC crystals, electrophoresis for MLT exam.", seoKeywords: ["hemoglobin C", "HbC", "target cells", "HbC crystals", "MLT exam"],
    overview: "Hemoglobin C disease results from a point mutation in the beta-globin gene (glutamic acid → lysine at position 6). HbC homozygotes (CC) have mild hemolytic anemia with characteristic target cells and intracellular HbC crystals.",
    mechanismPhysiology: "HbC has decreased solubility compared to HbA, causing intracellular crystallization. HbC crystals make RBCs rigid and unable to deform, leading to splenic sequestration and mild extravascular hemolysis. HbC promotes potassium and water loss from RBCs, causing dehydration and target cell formation.",
    clinicalRelevance: "HbCC: mild hemolytic anemia. HbAC (trait): asymptomatic, no anemia. HbSC disease: compound heterozygote with clinically significant sickling disorder (milder than HbSS but more retinal and bone complications). HbC migrates with HbA2 and HbE on alkaline (cellulose acetate) electrophoresis at pH 8.6.",
    signsSymptoms: "HbCC: mild anemia, splenomegaly, target cells, may have joint pain. Often discovered incidentally.",
    assessment: "CBC: mild normocytic anemia. Peripheral smear: abundant target cells (most of any hemoglobinopathy), HbC crystals (rhomboid/hexagonal, dark-staining, intracellular). Hb electrophoresis: alkaline (pH 8.6): HbC migrates with HbA2 and HbE (position C). Citrate agar (acid, pH 6.2): separates HbC from HbA2 and HbE. Solubility test: NEGATIVE (HbC is soluble, unlike HbS).",
    management: "HbCC: usually no treatment needed. Folic acid supplementation. Genetic counseling for SC disease risk.",
    complications: "HbSC disease: vaso-occlusive crises, avascular necrosis, proliferative retinopathy, splenomegaly (spleen NOT autoinfarcts like in HbSS).",
    clinicalPearls: ["HbC produces the MOST target cells of any hemoglobinopathy", "HbC migrates with HbA2 and HbE at alkaline pH—citrate agar at acid pH separates them", "HbC crystals are intracellular rhomboid/hexagonal shapes seen on peripheral smear"],
    examPitfalls: ["HbC, HbA2, and HbE comigrate on alkaline electrophoresis—acid electrophoresis is needed to distinguish", "HbSC disease is clinically significant despite each mutation being mild alone", "HbC solubility test is NEGATIVE—only HbS is positive on solubility test"],
    faqJson: [{ question: "How is HbC separated from HbA2 and HbE?", answer: "Citrate agar (acid) electrophoresis at pH 6.2 separates them. At alkaline pH 8.6, all three migrate to the same position (C/A2/E)." }, { question: "What is HbSC disease?", answer: "Compound heterozygote with one HbS and one HbC gene. Milder than HbSS but with significant complications including proliferative retinopathy, avascular necrosis, and splenomegaly." }]
  }),
  E({ slug: "multiple-myeloma", title: "Multiple Myeloma", category: "Hematology",
    seoTitle: "Multiple Myeloma – MLT Encyclopedia", seoDescription: "Multiple myeloma: M-spike, Bence Jones protein, rouleaux, serum protein electrophoresis for MLT exam.", seoKeywords: ["multiple myeloma", "M-spike", "Bence Jones protein", "rouleaux", "SPEP", "MLT exam"],
    overview: "Multiple myeloma is a malignant neoplasm of plasma cells in the bone marrow producing a monoclonal immunoglobulin (M protein/paraprotein). It is the most common primary malignant bone tumor in adults.",
    mechanismPhysiology: "Clonal plasma cells accumulate in bone marrow, producing monoclonal immunoglobulin (usually IgG or IgA) with a single light chain type (kappa or lambda). Excess free light chains (Bence Jones protein) are filtered by kidneys. Osteoclast-activating factors from myeloma cells cause osteolytic bone lesions.",
    clinicalRelevance: "CRAB criteria: Calcium elevated, Renal insufficiency, Anemia, Bone lesions (lytic). Serum protein electrophoresis (SPEP): M-spike in gamma region. Urine protein electrophoresis (UPEP): Bence Jones proteinuria (free light chains). Serum free light chain ratio: abnormal kappa/lambda ratio.",
    signsSymptoms: "Bone pain (especially back), pathologic fractures, anemia (fatigue, pallor), recurrent infections (immunoparesis), renal failure, hypercalcemia (confusion, polyuria).",
    assessment: "CBC: normocytic anemia, rouleaux formation on peripheral smear (RBCs stacking like coins due to elevated immunoglobulin). ESR markedly elevated (often >100 mm/hr). SPEP: monoclonal M-spike (gamma region). Immunofixation electrophoresis (IFE): identifies immunoglobulin heavy and light chain type. Bone marrow: ≥10% clonal plasma cells. Serum free light chains: abnormal kappa/lambda ratio. Skeletal survey: lytic punched-out bone lesions (skull, spine, ribs). Urine: Bence Jones protein (free light chains).",
    management: "Induction: proteasome inhibitors (bortezomib), immunomodulatory drugs (lenalidomide), dexamethasone. Autologous stem cell transplant for eligible patients. Bisphosphonates for bone disease. Supportive: erythropoiesis-stimulating agents for anemia.",
    complications: "Renal failure (light chain cast nephropathy—myeloma kidney). Amyloidosis (AL type from light chains). Hyperviscosity syndrome (more common with IgM—Waldenström). Infections (immunoparesis—decreased normal immunoglobulins).",
    clinicalPearls: ["Rouleaux formation on peripheral smear is characteristic but NOT specific for myeloma", "SPEP shows M-spike; immunofixation identifies the specific immunoglobulin type (IgG-kappa most common)", "Bence Jones protein precipitates at 40-60°C and redissolves at 100°C—classic but outdated test"],
    examPitfalls: ["ESR is markedly elevated in myeloma (often >100)—may be the first laboratory clue", "Rouleaux resembles agglutination but disperses with saline dilution (agglutination does not)", "Normal serum free light chain ratio effectively excludes myeloma in the right clinical context"],
    faqJson: [{ question: "What is the M-spike?", answer: "A sharp, well-defined peak in the gamma region of serum protein electrophoresis caused by the monoclonal immunoglobulin produced by myeloma cells. It is the hallmark finding on SPEP." }, { question: "What is Bence Jones protein?", answer: "Free monoclonal light chains (kappa or lambda) in the urine. They are small enough to be filtered by the kidneys and cause cast nephropathy (myeloma kidney). Classic heat test: precipitate at 40-60°C, redissolve at 100°C." }]
  }),
  E({ slug: "hemolytic-disease-newborn", title: "Hemolytic Disease of the Fetus and Newborn (HDFN)", category: "Hematology",
    seoTitle: "HDFN – Hemolytic Disease of Newborn | MLT Encyclopedia", seoDescription: "HDFN: ABO vs Rh incompatibility, DAT, exchange transfusion for MLT exam.", seoKeywords: ["HDFN", "hemolytic disease newborn", "ABO incompatibility", "Rh incompatibility", "exchange transfusion", "MLT exam"],
    overview: "HDFN occurs when maternal IgG antibodies cross the placenta and destroy fetal/neonatal red blood cells. The two main causes are Rh (anti-D) incompatibility and ABO incompatibility. Rh HDFN is more severe but preventable with RhIg. ABO HDFN is milder but more common.",
    mechanismPhysiology: "Maternal IgG (not IgM) antibodies cross the placenta via Fc receptor-mediated transport. They bind fetal RBC antigens, causing extravascular hemolysis (splenic/hepatic macrophage destruction). Rh HDFN: requires prior sensitization (previous pregnancy/transfusion). ABO HDFN: can occur in first pregnancy (naturally occurring IgG anti-A/anti-B).",
    clinicalRelevance: "Rh HDFN: severe, progressive with each pregnancy. Hydrops fetalis in severe cases. ABO HDFN: usually mild, mostly Group O mothers with Group A (or B) infants. Anti-A,B IgG from Group O mothers crosses placenta and attacks fetal A/B antigens.",
    signsSymptoms: "Neonatal jaundice (within 24 hours = pathologic), anemia, hepatosplenomegaly, hydrops fetalis (severe: edema, ascites, pleural effusions). Kernicterus: bilirubin deposition in basal ganglia causing permanent neurologic damage.",
    assessment: "DAT on cord blood/neonatal sample: positive in HDFN (antibody on baby's RBCs). ABO HDFN: DAT may be weakly positive or negative (fewer A/B antigens on neonatal RBCs). Neonatal bilirubin: total and direct (unconjugated predominates). CBC: anemia, reticulocytosis, NRBCs. Peripheral smear: spherocytes (ABO HDFN), polychromasia. Maternal antibody screen: positive with antibody identification.",
    management: "Phototherapy: converts unconjugated bilirubin to water-soluble form for excretion. Exchange transfusion: removes antibody-coated RBCs and excess bilirubin (for severe cases). Intrauterine transfusion for severe fetal anemia. IVIG for moderate cases. Prevention: RhIg for Rh-negative mothers.",
    complications: "Kernicterus (bilirubin encephalopathy): hearing loss, choreoathetosis, intellectual disability. Hydrops fetalis: heart failure from severe anemia. Late anemia: hypoproliferative anemia persisting weeks after birth.",
    clinicalPearls: ["ABO HDFN is MORE COMMON but MILDER; Rh HDFN is LESS COMMON but MORE SEVERE", "ABO HDFN can occur in FIRST pregnancy (preformed IgG anti-A/B); Rh HDFN requires prior sensitization", "Jaundice within 24 hours of birth is ALWAYS pathologic and requires investigation"],
    examPitfalls: ["DAT in ABO HDFN may be weakly positive or negative—does NOT rule out ABO HDFN", "Exchange transfusion blood for Rh HDFN: Group O, Rh-NEGATIVE, crossmatch compatible with MOTHER's serum", "Spherocytes on neonatal smear suggest ABO HDFN (immune-mediated membrane loss)"],
    faqJson: [{ question: "Why can ABO HDFN occur in the first pregnancy?", answer: "Group O individuals naturally produce IgG anti-A and anti-B (in addition to IgM). IgG crosses the placenta and can attack fetal A or B RBCs without prior sensitization." }, { question: "What blood is used for exchange transfusion?", answer: "Group O (to avoid maternal ABO antibodies), Rh-negative (for Rh HDFN), irradiated (prevent TA-GVHD), crossmatch compatible with mother's serum (the antibody source)." }]
  }),

  // ======== CLINICAL CHEMISTRY continued ========
  E({ slug: "electrolyte-panel", title: "Electrolyte Panel (Na, K, Cl, CO2)", category: "Clinical Chemistry",
    seoTitle: "Electrolyte Panel – MLT Encyclopedia", seoDescription: "Sodium, potassium, chloride, CO2: ISE methodology, hemolysis interference for MLT exam.", seoKeywords: ["electrolytes", "sodium", "potassium", "chloride", "CO2", "ISE", "MLT exam"],
    overview: "The basic metabolic panel electrolytes (sodium, potassium, chloride, total CO2/bicarbonate) are measured by ion-selective electrodes (ISEs). They are among the most frequently ordered laboratory tests and are critical for assessing fluid/electrolyte balance, acid-base status, and renal function.",
    mechanismPhysiology: "ISE methodology: direct ISE measures ion activity in undiluted sample (blood gas analyzers, POC). Indirect ISE measures after sample dilution (most automated chemistry analyzers). Pseudohyponatremia: falsely low sodium on indirect ISE in patients with severe hyperlipidemia or hyperproteinemia (dilution artifact—the water fraction is reduced). Direct ISE gives accurate results.",
    clinicalRelevance: "Sodium (135-145 mEq/L): most abundant extracellular cation. Hyponatremia: SIADH, water intoxication, diuretics. Hypernatremia: dehydration, diabetes insipidus. Potassium (3.5-5.0 mEq/L): most abundant intracellular cation. Hyperkalemia: renal failure, acidosis, tissue destruction. Hypokalemia: diuretics, vomiting, diarrhea. Chloride (98-106 mEq/L): follows sodium. CO2 (22-28 mEq/L): reflects bicarbonate (metabolic component of acid-base).",
    signsSymptoms: "Hyperkalemia: peaked T waves → widened QRS → sine wave → cardiac arrest. Hypokalemia: U waves, muscle weakness, ileus. Hyponatremia: confusion, seizures, cerebral edema. Hypernatremia: lethargy, confusion, seizures.",
    assessment: "ISE types: glass electrode (sodium), valinomycin membrane (potassium), silver/silver chloride (chloride). CO2: enzymatic method (phosphoenolpyruvate carboxylase) or ISE. Specimen: serum or heparinized plasma. Critical values: K <2.5 or >6.5 mEq/L, Na <120 or >160 mEq/L. Hemolysis interference: FALSELY ELEVATES potassium (most clinically significant preanalytical error).",
    management: "Report critical values immediately. Hemolyzed specimens: request redraw for potassium (intracellular K released into serum). Lipemic specimens: may need ultracentrifugation or direct ISE measurement.",
    complications: "Hemolyzed specimen: most common preanalytical error for potassium. Pseudohyponatremia: indirect ISE artifact from lipemia/paraproteinemia. Potassium falsely elevated by: hemolysis, prolonged tourniquet, fist clenching, delayed separation, thrombocytosis, leukocytosis.",
    clinicalPearls: ["Hemolysis is the MOST COMMON preanalytical error—falsely elevates potassium", "Pseudohyponatremia occurs with INDIRECT ISE (dilution method) in severe lipemia/hyperproteinemia—direct ISE gives correct result", "Potassium is the most critical electrolyte—cardiac arrhythmias and arrest at extreme levels"],
    examPitfalls: ["Fist clenching and prolonged tourniquet falsely elevate potassium", "Thrombocytosis can cause pseudohyperkalemia (K released from platelets during clotting)—use plasma instead of serum", "Total CO2 on chemistry panel ≈ bicarbonate (HCO3-) on ABG—they measure the same thing differently"],
    faqJson: [{ question: "Direct vs indirect ISE?", answer: "Direct ISE measures ion activity in undiluted sample (accurate in all conditions). Indirect ISE dilutes sample first, which is affected by the volume displacement of lipids/proteins, causing pseudohyponatremia." }, { question: "Why does hemolysis affect potassium?", answer: "RBCs contain ~150 mEq/L potassium (vs 3.5-5.0 mEq/L in serum). Even mild hemolysis releases enough intracellular potassium to significantly elevate the measured value." }]
  }),
  E({ slug: "liver-function-tests", title: "Liver Function Tests (LFTs)", category: "Clinical Chemistry",
    seoTitle: "Liver Function Tests – MLT Encyclopedia", seoDescription: "ALT, AST, ALP, GGT, bilirubin: liver enzyme patterns and interpretation for MLT exam.", seoKeywords: ["liver function tests", "ALT", "AST", "ALP", "GGT", "bilirubin", "MLT exam"],
    overview: "Liver function tests encompass enzymes reflecting hepatocellular damage (ALT, AST), cholestasis/biliary obstruction (ALP, GGT), and synthetic function (albumin, PT/INR). Bilirubin metabolism assessment includes total, direct (conjugated), and indirect (unconjugated) fractions.",
    mechanismPhysiology: "ALT (alanine aminotransferase): most specific for liver (cytoplasmic). AST (aspartate aminotransferase): found in liver, heart, muscle, kidney (cytoplasmic and mitochondrial). AST/ALT ratio (De Ritis ratio): >2 suggests alcoholic liver disease (mitochondrial AST release + pyridoxal phosphate deficiency affecting ALT). ALP: canalicular enzyme, elevated in cholestasis and bone disease. GGT: biliary enzyme, most sensitive but least specific liver test; induced by alcohol and drugs. Bilirubin: heme catabolism product. Unconjugated (indirect): transported by albumin, elevated in hemolysis, Gilbert syndrome. Conjugated (direct): water-soluble, elevated in biliary obstruction, hepatocellular disease.",
    clinicalRelevance: "Hepatocellular pattern: ALT > AST (viral hepatitis). AST > ALT (alcoholic hepatitis, cirrhosis). Cholestatic pattern: ALP and GGT elevated out of proportion to transaminases (biliary obstruction, infiltrative disease). Confirm hepatic ALP origin: elevated GGT = liver source; normal GGT = bone source.",
    signsSymptoms: "Hepatocellular: jaundice, fatigue, nausea, elevated transaminases. Cholestatic: jaundice, pruritus, dark urine, pale stools, elevated ALP/GGT.",
    assessment: "ALT: pyridoxal phosphate-dependent, NADH-linked reaction (measured at 340 nm). AST: similar coupled reaction. ALP: measured at pH 10.3 using p-nitrophenylphosphate substrate. GGT: gamma-glutamyl-p-nitroanilide substrate. Total bilirubin: diazo reaction (Jendrassik-Grof method). Direct bilirubin: reacts without accelerator. Indirect = total - direct. Neonatal bilirubin: direct spectrophotometry at 454 nm.",
    management: "Interpret pattern (hepatocellular vs cholestatic) to guide further workup. Critical values: very high bilirubin in neonates (kernicterus risk). Monitor trends rather than single values.",
    complications: "Falsely elevated bilirubin: hemolysis, lipemia. Neonatal jaundice: physiologic (days 2-5) vs pathologic (<24 hours). Delta bilirubin: bilirubin covalently bound to albumin, prolonged half-life (17 days).",
    clinicalPearls: ["ALT is more SPECIFIC for liver than AST (AST also in heart/muscle)", "De Ritis ratio (AST/ALT >2) suggests ALCOHOLIC hepatitis; ALT > AST in viral hepatitis", "GGT confirms hepatic origin of elevated ALP—if GGT is normal, ALP elevation is from BONE"],
    examPitfalls: ["ALP is elevated in BOTH liver disease and bone disease—GGT distinguishes the source", "Delta bilirubin explains why jaundice persists after biliary obstruction resolves (half-life 17 days = albumin)", "Neonatal bilirubin <24 hours = ALWAYS pathologic (hemolytic disease, sepsis)"],
    faqJson: [{ question: "What is the De Ritis ratio?", answer: "AST/ALT ratio. >2 suggests alcoholic hepatitis (alcohol damages mitochondria releasing mitochondrial AST; alcohol also depletes pyridoxal phosphate needed for ALT synthesis). <1 suggests viral hepatitis." }, { question: "What is delta bilirubin?", answer: "Bilirubin covalently bound to albumin. It has the same half-life as albumin (~17 days) and is not excreted in urine. It explains persistent jaundice after resolution of obstruction." }]
  }),
  E({ slug: "renal-function-tests", title: "Renal Function Tests", category: "Clinical Chemistry",
    seoTitle: "Renal Function Tests – MLT Encyclopedia", seoDescription: "BUN, creatinine, eGFR, cystatin C: renal function assessment for MLT exam.", seoKeywords: ["renal function", "BUN", "creatinine", "eGFR", "cystatin C", "GFR", "MLT exam"],
    overview: "Renal function is assessed by measuring glomerular filtration rate (GFR) through surrogate markers: serum creatinine, cystatin C, and BUN. Estimated GFR (eGFR) calculated from serum creatinine using CKD-EPI equation is the standard measure of kidney function.",
    mechanismPhysiology: "Creatinine: produced by non-enzymatic conversion of creatine/creatine phosphate in skeletal muscle. Freely filtered by glomerulus with minimal tubular reabsorption and some tubular secretion. Level depends on muscle mass, diet, and GFR. BUN (blood urea nitrogen): urea is the end product of protein metabolism (urea cycle in liver). Freely filtered, 40-50% reabsorbed in proximal tubule (reabsorption increases with dehydration). BUN/creatinine ratio normally 10-20:1. Cystatin C: low molecular weight protein produced at a constant rate by all nucleated cells, freely filtered, completely reabsorbed and catabolized by tubules. Less affected by muscle mass, age, sex, and diet than creatinine.",
    clinicalRelevance: "Elevated creatinine: decreased GFR (kidney disease), rhabdomyolysis, high muscle mass. Elevated BUN: prerenal (dehydration, heart failure—BUN/Cr ratio >20:1), renal (intrinsic kidney disease—ratio 10-20:1), postrenal (obstruction). BUN/Cr ratio >20:1 suggests prerenal azotemia (dehydration). Jaffé reaction (picric acid): traditional creatinine method—positive interference from ketones, proteins, cephalosporins. Enzymatic method: more specific, preferred.",
    signsSymptoms: "Kidney disease: edema, hypertension, oliguria/anuria, uremia (nausea, confusion, pericarditis, asterixis).",
    assessment: "Creatinine: Jaffé (alkaline picrate, kinetic)—nonspecific, interferences. Enzymatic (creatininase)—specific, preferred. BUN: urease/glutamate dehydrogenase coupled reaction (NADH consumption at 340 nm). eGFR: CKD-EPI 2021 equation (creatinine-based, race-free). Cystatin C: immunoassay (particle-enhanced immunonephelometry or immunoturbidimetry). 24-hour urine creatinine clearance: measured GFR (collection errors limit accuracy).",
    management: "CKD staging by eGFR: G1 ≥90 (normal), G2 60-89 (mild), G3a 45-59, G3b 30-44, G4 15-29 (severe), G5 <15 (kidney failure/dialysis). Monitor creatinine trends. Use cystatin C when creatinine is unreliable (extremes of muscle mass, amputees, elderly).",
    complications: "Jaffé interference: ketones (DKA), proteins, bilirubin, cephalosporins → falsely elevated creatinine. Creatinine does not rise until GFR decreases ~50% (creatinine-blind range). Cystatin C may be affected by thyroid disease and corticosteroids.",
    clinicalPearls: ["Creatinine does NOT rise until GFR drops by ~50%—early kidney disease may be missed (creatinine-blind range)", "BUN/Cr ratio >20:1 suggests PRERENAL cause (dehydration, heart failure)", "Jaffé reaction is interfered by ketones (falsely elevated creatinine in DKA)—enzymatic method is more specific"],
    examPitfalls: ["Jaffé method: positive interference from ketones, proteins, cephalosporins, bilirubin", "Cystatin C is less affected by muscle mass than creatinine—better in elderly, amputees, bodybuilders", "24-hour creatinine clearance requires COMPLETE urine collection—incomplete collection is the most common error"],
    faqJson: [{ question: "Why is eGFR preferred over serum creatinine alone?", answer: "eGFR accounts for age, sex, and serum creatinine level using the CKD-EPI equation. Serum creatinine alone is affected by muscle mass, diet, and tubular secretion, making it less reliable for estimating kidney function." }, { question: "When is cystatin C preferred?", answer: "When creatinine is unreliable: extremes of muscle mass (bodybuilders, amputees, sarcopenia), elderly patients, vegetarian diet, and for confirming early CKD when creatinine-based eGFR is borderline." }]
  }),

  // ======== MICROBIOLOGY continued ========
  E({ slug: "mycobacterium-tuberculosis", title: "Mycobacterium tuberculosis", category: "Microbiology",
    seoTitle: "Mycobacterium tuberculosis – MLT Encyclopedia", seoDescription: "M. tuberculosis: acid-fast staining, culture, NAAT, and biosafety for MLT exam.", seoKeywords: ["Mycobacterium tuberculosis", "acid-fast bacilli", "AFB", "Ziehl-Neelsen", "NAAT", "MLT exam"],
    overview: "Mycobacterium tuberculosis is the causative agent of tuberculosis (TB), the leading infectious disease killer worldwide. It is an obligate aerobe with a thick, lipid-rich cell wall (mycolic acids) that makes it acid-fast. TB primarily affects the lungs but can disseminate to any organ.",
    mechanismPhysiology: "Mycolic acids in the cell wall: high lipid content makes the organism acid-fast (retains carbolfuchsin dye after acid-alcohol decolorization). Cell wall also provides resistance to drying, disinfectants, and many antibiotics. Slow growth rate: 2-6 weeks on solid media (doubling time 18-24 hours vs 20 minutes for E. coli). Facultative intracellular pathogen: survives within macrophages. Cord factor (trehalose dimycolate): virulence factor causing serpentine cording on culture.",
    clinicalRelevance: "TB is a BSL-3 pathogen. All specimen processing for AFB culture must be performed in a biological safety cabinet (BSC Class II or III). Specimens from non-sterile sites require digestion-decontamination (NALC-NaOH) before culture to reduce normal flora contamination.",
    signsSymptoms: "Pulmonary TB: chronic cough (>3 weeks), hemoptysis, night sweats, weight loss, fever, cavitary lesions on chest X-ray. Extrapulmonary: lymphadenitis, pleural effusion, meningitis, bone (Pott disease), genitourinary, miliary (disseminated).",
    assessment: "AFB smear: Ziehl-Neelsen (carbol fuchsin, hot) or Kinyoun (cold acid-fast). Fluorochrome: auramine-rhodamine (more sensitive screening method—positive screens confirmed by Ziehl-Neelsen). Culture: Löwenstein-Jensen (egg-based solid), Middlebrook 7H10/7H11 (agar-based solid), MGIT (mycobacteria growth indicator tube—liquid, most rapid culture system, ~1-2 weeks). NAAT: GeneXpert MTB/RIF (detects M. tuberculosis complex AND rifampin resistance in 2 hours—recommended as initial diagnostic test by WHO).",
    management: "Standard regimen: RIPE × 2 months (Rifampin, Isoniazid, Pyrazinamide, Ethambutol) then RI × 4 months. Drug susceptibility testing essential. Directly observed therapy (DOT). Latent TB: isoniazid × 9 months or rifampin × 4 months.",
    complications: "Drug-resistant TB: MDR-TB (resistant to isoniazid + rifampin), XDR-TB (MDR + fluoroquinolone + injectable agent resistance). Immune reconstitution inflammatory syndrome (IRIS) in HIV patients starting antiretrovirals.",
    clinicalPearls: ["AFB smear is only ~60% sensitive—negative smear does NOT rule out TB", "GeneXpert MTB/RIF: detects TB AND rifampin resistance in 2 hours—revolutionized TB diagnosis", "Cord factor (serpentine cording) on culture is characteristic of M. tuberculosis virulence"],
    examPitfalls: ["Acid-fast does NOT equal M. tuberculosis—Nocardia and other mycobacteria are also acid-fast", "NALC-NaOH decontamination is used ONLY for non-sterile sites (sputum, bronchial wash)—not CSF, blood, tissue", "TB is a BSL-3 organism—all AFB processing must be done in a biological safety cabinet"],
    faqJson: [{ question: "Ziehl-Neelsen vs Kinyoun vs fluorochrome?", answer: "Ziehl-Neelsen: hot carbolfuchsin (heat drives dye into cell wall). Kinyoun: cold method (higher concentration of carbolfuchsin). Fluorochrome (auramine-rhodamine): more sensitive screening (larger area scanned at lower magnification), positive screens confirmed by ZN or Kinyoun." }, { question: "What is GeneXpert MTB/RIF?", answer: "Automated NAAT that detects M. tuberculosis complex DNA and rifampin resistance mutations (rpoB gene) directly from sputum in about 2 hours. WHO-recommended as the initial diagnostic test for suspected TB." }]
  }),
  E({ slug: "non-fermenting-gram-negative-bacilli", title: "Non-Fermenting Gram-Negative Bacilli", category: "Microbiology",
    seoTitle: "Non-Fermenters – MLT Encyclopedia", seoDescription: "Pseudomonas, Acinetobacter, Stenotrophomonas, Burkholderia: oxidase, pigments for MLT exam.", seoKeywords: ["Pseudomonas aeruginosa", "Acinetobacter", "non-fermenting GNB", "oxidase positive", "MLT exam"],
    overview: "Non-fermenting gram-negative bacilli (NFGNB) are aerobic bacteria that cannot ferment glucose. They are ubiquitous environmental organisms that cause opportunistic infections in immunocompromised and hospitalized patients. Key species: Pseudomonas aeruginosa, Acinetobacter baumannii, Stenotrophomonas maltophilia, Burkholderia cepacia complex.",
    mechanismPhysiology: "Non-fermenters use oxidative metabolism (oxidase-positive for Pseudomonas, oxidase-negative for Acinetobacter). They grow aerobically only and often have intrinsic antibiotic resistance. P. aeruginosa: produces pigments (pyocyanin—blue-green, pyoverdin—yellow-green, pyorubin—red, pyomelanin—brown), grape-like odor (aminoacetophenone), biofilm formation on medical devices.",
    clinicalRelevance: "P. aeruginosa: nosocomial pneumonia (especially ventilator-associated), UTI, wound infections (burns), cystic fibrosis lung colonization, otitis externa (swimmer's ear), hot tub folliculitis, ecthyma gangrenosum (necrotizing skin lesion in neutropenic patients). Acinetobacter: MDR nosocomial infections, especially ICU pneumonia, wound infections in military personnel.",
    signsSymptoms: "Nosocomial pneumonia: fever, productive cough, new pulmonary infiltrate. Ecthyma gangrenosum: hemorrhagic, necrotic skin lesion (P. aeruginosa bacteremia). Burns: green-blue purulent drainage (P. aeruginosa pigment).",
    assessment: "P. aeruginosa: oxidase-POSITIVE, non-lactose fermenter on MacConkey (colorless), blue-green pigment on Mueller-Hinton/blood agar, grape-like odor, grows at 42°C. Acinetobacter: oxidase-NEGATIVE, coccobacillary (resembles Neisseria on Gram stain), non-motile, MDR. Stenotrophomonas: oxidase-NEGATIVE, lavender-green colonies, intrinsic carbapenem resistance (metallo-beta-lactamase). Burkholderia cepacia: oxidase-POSITIVE, intrinsic resistance to polymyxins.",
    management: "P. aeruginosa: anti-pseudomonal penicillins (piperacillin-tazobactam), cephalosporins (cefepime, ceftazidime), carbapenems (meropenem, doripenem—NOT ertapenem), fluoroquinolones, aminoglycosides. Combination therapy for serious infections. Acinetobacter MDR: carbapenems, ampicillin-sulbactam, polymyxins. Stenotrophomonas: TMP-SMX (drug of choice).",
    complications: "Multidrug resistance (MDR), extensively drug-resistant (XDR), pandrug-resistant (PDR) organisms. Biofilm formation on ventilators, catheters, implants. B. cepacia: fatal pulmonary disease in cystic fibrosis patients.",
    clinicalPearls: ["P. aeruginosa is OXIDASE-POSITIVE; Acinetobacter is OXIDASE-NEGATIVE—key differentiator among non-fermenters", "Grape-like odor and blue-green pigment = P. aeruginosa", "Stenotrophomonas is intrinsically resistant to CARBAPENEMS—TMP-SMX is the drug of choice"],
    examPitfalls: ["Ertapenem has NO activity against P. aeruginosa (unlike meropenem and doripenem)", "Acinetobacter is a coccobacillus that can be mistaken for Neisseria on Gram stain", "B. cepacia is intrinsically resistant to polymyxins—unlike P. aeruginosa and Acinetobacter"],
    faqJson: [{ question: "How to differentiate Pseudomonas from Enterobacteriaceae?", answer: "Pseudomonas is oxidase-POSITIVE and does NOT ferment glucose (non-fermenter). Enterobacteriaceae are oxidase-NEGATIVE and DO ferment glucose. This is the most fundamental distinction." }, { question: "Why is ertapenem excluded from anti-pseudomonal carbapenems?", answer: "Ertapenem has a narrower spectrum than meropenem and doripenem. It lacks activity against P. aeruginosa and Acinetobacter. For Pseudomonas, use meropenem, doripenem, or imipenem." }]
  }),
  E({ slug: "antimicrobial-susceptibility-testing", title: "Antimicrobial Susceptibility Testing", category: "Microbiology",
    seoTitle: "Antimicrobial Susceptibility Testing – MLT Encyclopedia", seoDescription: "Kirby-Bauer disk diffusion, MIC, broth microdilution, CLSI breakpoints for MLT exam.", seoKeywords: ["antimicrobial susceptibility", "Kirby-Bauer", "MIC", "disk diffusion", "CLSI", "breakpoints", "MLT exam"],
    overview: "Antimicrobial susceptibility testing (AST) determines the in vitro activity of antimicrobial agents against bacterial isolates. Results guide antibiotic selection and dosing. Methods include disk diffusion (Kirby-Bauer), broth microdilution (MIC), gradient diffusion (Etest), and automated systems (VITEK, MicroScan, Phoenix).",
    mechanismPhysiology: "Kirby-Bauer disk diffusion: standardized method using Mueller-Hinton agar, 0.5 McFarland inoculum, antibiotic-impregnated disks. Zone of inhibition diameter measured after 16-18 hours incubation at 35°C. CLSI (Clinical and Laboratory Standards Institute) publishes breakpoints: zone diameters and MIC values categorized as Susceptible (S), Intermediate (I), or Resistant (R). MIC (minimum inhibitory concentration): lowest concentration of antibiotic that inhibits visible bacterial growth. Gold standard: broth microdilution.",
    clinicalRelevance: "Key resistance mechanisms to detect: MRSA (cefoxitin disk), ESBL (cephalosporin resistance with clavulanate synergy), VRE (vancomycin MIC ≥32 = resistant), CRE (carbapenem resistance), high-level aminoglycoside resistance in Enterococcus. D-zone test: detects inducible clindamycin resistance in Staphylococcus (erythromycin-resistant, clindamycin-susceptible). Flattened zone of clindamycin adjacent to erythromycin disk = positive D-test = report clindamycin resistant.",
    signsSymptoms: "AST is a laboratory procedure guiding clinical antibiotic therapy.",
    assessment: "Kirby-Bauer requirements: Mueller-Hinton agar (standardized Ca²⁺/Mg²⁺ content), 0.5 McFarland standard (1-2 × 10⁸ CFU/mL), 150mm plates, no more than 12 disks per plate, read at 16-18 hours. MIC methods: broth microdilution (gold standard), gradient diffusion (Etest—plastic strip with antibiotic gradient, read where ellipse intersects strip), automated (VITEK, MicroScan). Quality control: ATCC reference strains (E. coli ATCC 25922, S. aureus ATCC 25923, P. aeruginosa ATCC 27853).",
    management: "Report results according to CLSI guidelines. Selective reporting: report narrow-spectrum agents first to promote antimicrobial stewardship. Cascade reporting: withhold broader-spectrum agents unless organism is resistant to first-line agents. Include interpretive comments for special resistance phenotypes.",
    complications: "Improper inoculum density: too heavy → falsely resistant; too light → falsely susceptible. Wrong medium (blood agar instead of MH): unreliable zones. Incorrect incubation: CO2 affects aminoglycoside and macrolide zones. Swarming Proteus on MH agar: ignore thin film of swarming growth.",
    clinicalPearls: ["0.5 McFarland standard is the REQUIRED inoculum density for disk diffusion—too heavy = falsely resistant, too light = falsely susceptible", "D-zone test detects INDUCIBLE clindamycin resistance—positive = report clindamycin as RESISTANT", "Mueller-Hinton agar is the standard medium—standardized cation content (Ca²⁺/Mg²⁺) is critical for aminoglycoside testing"],
    examPitfalls: ["Etest gives MIC (not zone diameter)—read where the ellipse intersects the strip", "Vancomycin disk diffusion should NOT be used for Enterococcus or S. aureus—use MIC method", "ATCC 25922 (E. coli) is the QC strain for gram-negative disk diffusion—know the reference strains"],
    faqJson: [{ question: "Why is Mueller-Hinton agar the standard?", answer: "MH agar has standardized pH, cation content (Ca²⁺/Mg²⁺ important for aminoglycoside accuracy), minimal sulfonamide/trimethoprim inhibitors, reproducible performance, and supports growth of most non-fastidious pathogens." }, { question: "What is the D-zone test?", answer: "Places erythromycin and clindamycin disks adjacent (15-26mm apart) on MH plate. If clindamycin zone is flattened (D-shaped) toward erythromycin, the organism has inducible erm gene-mediated clindamycin resistance and should be reported as resistant." }]
  }),
  E({ slug: "fungal-culture-identification", title: "Fungal Culture and Identification", category: "Microbiology",
    seoTitle: "Fungal Culture and Identification – MLT Encyclopedia", seoDescription: "Fungal culture media, dimorphic fungi, dermatophytes, identification methods for MLT exam.", seoKeywords: ["fungal culture", "dimorphic fungi", "dermatophytes", "SDA", "calcofluor white", "MLT exam"],
    overview: "Fungal culture remains the gold standard for diagnosing mycoses. Fungi are identified by colonial morphology, microscopic morphology (conidia, hyphae), growth rate, temperature requirements, and biochemical tests. Key groups: yeasts, dimorphic fungi, dermatophytes, and opportunistic molds.",
    mechanismPhysiology: "Dimorphic fungi: exist as mold at 25°C (environmental form) and yeast at 37°C (tissue form). 'Mold in the cold, yeast in the heat.' Key species: Histoplasma capsulatum, Blastomyces dermatitidis, Coccidioides immitis, Paracoccidioides brasiliensis, Sporothrix schenckii, Talaromyces (Penicillium) marneffei. Dermatophytes: keratinophilic fungi causing skin/hair/nail infections. Three genera: Trichophyton, Microsporum, Epidermophyton.",
    clinicalRelevance: "Histoplasma: Ohio/Mississippi River valley, intracellular yeast in macrophages (2-4 μm, small), bat/bird droppings. Blastomyces: Great Lakes region, broad-based budding yeast (8-15 μm). Coccidioides: Southwestern US, spherules with endospores in tissue (BSL-3!). Dermatophytes: tinea infections (tinea pedis, corporis, cruris, capitis, unguium).",
    signsSymptoms: "Histoplasmosis: asymptomatic or flu-like, progressive disseminated in immunocompromised. Blastomycosis: pulmonary and skin (verrucous/ulcerative). Coccidioidomycosis: valley fever, erythema nodosum, meningitis. Dermatophytosis: pruritic, scaly, erythematous annular lesions with central clearing.",
    assessment: "KOH prep: dissolves keratin, reveals hyphae/yeast. Calcofluor white: fluorescent stain (binds chitin/cellulose). Culture media: SDA (Sabouraud dextrose agar, pH 5.6, inhibits bacteria), BHI (brain heart infusion—better recovery of dimorphic fungi), Mycosel/mycobiotic (SDA + cycloheximide + chloramphenicol—selective for dermatophytes and dimorphic fungi, INHIBITS Aspergillus and Cryptococcus). Tease mount with LPCB (lactophenol cotton blue): microscopic identification. MALDI-TOF: rapid identification. Dermatophyte identification: hair perforation test, urease, growth on rice grains.",
    management: "Dermatophytes: topical antifungals (terbinafine, azoles), oral for extensive/nail disease. Histoplasmosis: itraconazole (mild-moderate), amphotericin B (severe). Coccidioidomycosis: fluconazole, amphotericin B for severe/meningeal.",
    complications: "Dimorphic fungi are BSL-3 in mold form (highly infectious arthroconidia/conidia). Coccidioides arthroconidia are particularly hazardous—work under BSC only. Progressive disseminated disease in immunocompromised.",
    clinicalPearls: ["Mold in the cold (25°C), yeast in the heat (37°C)—defines dimorphic fungi", "Cycloheximide in selective media INHIBITS Aspergillus and Cryptococcus—do not use these media when suspected", "Broad-based budding = Blastomyces; narrow-based budding = Cryptococcus; no budding (spherules) = Coccidioides"],
    examPitfalls: ["Coccidioides in mold form is EXTREMELY hazardous (BSL-3)—arthroconidia are highly infectious", "SDA with cycloheximide inhibits Aspergillus, Cryptococcus, and many opportunistic molds—use plain SDA in parallel", "Trichophyton rubrum is the most common dermatophyte worldwide"],
    faqJson: [{ question: "What is the role of cycloheximide?", answer: "Cycloheximide inhibits saprophytic fungi and fast-growing environmental molds, allowing slower-growing dermatophytes and dimorphic fungi to be recovered. However, it also inhibits important pathogens like Aspergillus and Cryptococcus, so selective and non-selective media should always be used in parallel." }, { question: "Why are dimorphic fungi BSL-3?", answer: "The mold form produces highly infectious conidia/arthroconidia that can cause laboratory-acquired infections through inhalation. Conversion to yeast form in tissues causes disease. Any manipulation of mold cultures must be performed in a biological safety cabinet." }]
  }),

  // ======== BLOOD BANKING continued ========
  E({ slug: "transfusion-reactions", title: "Transfusion Reactions", category: "Blood Banking/Transfusion Medicine",
    seoTitle: "Transfusion Reactions – MLT Encyclopedia", seoDescription: "Transfusion reactions: acute hemolytic, febrile, allergic, TRALI, TACO for MLT exam.", seoKeywords: ["transfusion reaction", "acute hemolytic", "TRALI", "TACO", "febrile", "allergic", "MLT exam"],
    overview: "Transfusion reactions are adverse events occurring during or after blood product transfusion. They range from mild (febrile, allergic) to life-threatening (acute hemolytic, TRALI, anaphylaxis, bacterial contamination). Immediate recognition and appropriate workup are critical for patient safety.",
    mechanismPhysiology: "Acute hemolytic transfusion reaction (AHTR): preformed ABO antibodies (IgM) cause intravascular hemolysis of donor RBCs. Most commonly due to ABO incompatibility from CLERICAL ERROR. Complement activation → hemoglobinemia → hemoglobinuria → DIC → renal failure. Febrile non-hemolytic (FNHTR): recipient antibodies against donor WBC antigens OR cytokines accumulated in stored blood products. Allergic: IgE-mediated reaction to donor plasma proteins (urticaria). Anaphylactic: anti-IgA in IgA-deficient recipients. TRALI: donor anti-HLA/anti-neutrophil antibodies activate recipient neutrophils in pulmonary vasculature → acute lung injury. TACO: circulatory overload from volume/rate of transfusion.",
    clinicalRelevance: "AHTR is the most common cause of transfusion-related DEATH and is almost always due to CLERICAL ERROR (wrong blood to wrong patient). TRALI is the leading cause of transfusion-related mortality reported to the FDA. Bacterial contamination: primarily platelets (stored at room temperature).",
    signsSymptoms: "AHTR: fever, chills, flank/back pain, hypotension, hemoglobinuria (dark/red urine), DIC, renal failure. FNHTR: fever (≥1°C rise), chills, rigors WITHOUT hemolysis. Allergic: urticaria, hives, pruritus. Anaphylactic: hypotension, bronchospasm, angioedema (within minutes). TRALI: acute respiratory distress, bilateral pulmonary infiltrates, hypoxemia within 6 hours (NO evidence of circulatory overload). TACO: dyspnea, hypertension, jugular venous distension, pulmonary edema.",
    assessment: "Transfusion reaction workup: (1) STOP transfusion immediately. (2) Maintain IV access. (3) Clerical check: verify patient ID and unit label. (4) Visual inspection of post-transfusion specimen: hemolysis (pink/red serum = hemoglobinemia). (5) DAT on post-transfusion sample: positive in AHTR. (6) Repeat ABO/Rh on pre- and post-transfusion samples and donor unit. (7) Urine: hemoglobinuria (free Hb in urine). (8) Haptoglobin: decreased. (9) Bilirubin: increased (unconjugated). (10) Coagulation studies: DIC screen.",
    management: "AHTR: stop transfusion, aggressive IV fluids (maintain renal perfusion), monitor for DIC, send reaction workup specimens. FNHTR: acetaminophen, antipyretics; prevent with leukoreduced products. Allergic: antihistamines (diphenhydramine); prevent with washed products if recurrent. Anaphylactic: epinephrine, IgA-deficient plasma products for future. TRALI: supportive care, oxygen, mechanical ventilation if needed. TACO: diuretics, slow transfusion rate.",
    complications: "AHTR: DIC, renal failure, death. TRALI: acute respiratory failure, death (mortality 5-10%). Bacterial contamination: septic shock, death. TA-GVHD (transfusion-associated graft-vs-host disease): fatal in >90%—prevented by irradiation.",
    clinicalPearls: ["ABO-incompatible transfusion (AHTR) is almost always due to CLERICAL ERROR—patient identification is the most critical safety step", "TRALI: bilateral infiltrates WITHOUT circulatory overload (vs TACO: bilateral infiltrates WITH circulatory overload)", "Bacterial contamination is most common in PLATELETS because they are stored at room temperature (20-24°C)"],
    examPitfalls: ["TRALI vs TACO: TRALI has normal BP or hypotension and no JVD; TACO has hypertension and elevated JVD", "The FIRST step in any transfusion reaction is STOP the transfusion and maintain IV access", "TA-GVHD is prevented by IRRADIATION of blood products (for immunocompromised recipients, HLA-matched products, and relative-directed donations)"],
    faqJson: [{ question: "How is TRALI differentiated from TACO?", answer: "TRALI: hypotension, normal BNP, bilateral infiltrates within 6 hours, no fluid overload, caused by donor antibodies. TACO: hypertension, elevated BNP, JVD, pulmonary edema, caused by volume overload, responds to diuretics." }, { question: "Why is bacterial contamination more common in platelets?", answer: "Platelets are stored at room temperature (20-24°C) with continuous agitation for up to 5-7 days. Room temperature promotes bacterial growth. RBCs are stored at 1-6°C, which inhibits most bacteria (exception: Yersinia enterocolitica thrives at cold temperatures)." }]
  }),
  E({ slug: "component-therapy", title: "Blood Component Therapy", category: "Blood Banking/Transfusion Medicine",
    seoTitle: "Blood Component Therapy – MLT Encyclopedia", seoDescription: "RBCs, platelets, FFP, cryoprecipitate: storage, indications, and modifications for MLT exam.", seoKeywords: ["blood components", "packed RBCs", "platelets", "FFP", "cryoprecipitate", "blood storage", "MLT exam"],
    overview: "Blood component therapy allows targeted treatment of specific deficiencies. Whole blood is separated by centrifugation into red blood cells (RBCs), platelets, plasma (FFP), and cryoprecipitate. Each component has specific storage conditions, shelf life, and clinical indications.",
    mechanismPhysiology: "RBCs: stored at 1-6°C in CPDA-1 (35 days) or additive solutions (AS-1, AS-3, AS-5: 42 days). During storage: 2,3-DPG decreases (left-shifted O2 dissociation curve), potassium increases (leaks from cells), pH decreases, lactate increases—collectively called 'storage lesion.' Platelets: stored at 20-24°C with continuous agitation for 5 days (7 days with pathogen reduction). FFP: frozen within 8 hours of collection, stored at ≤-18°C for 1 year. Contains ALL coagulation factors. Cryoprecipitate: cold-insoluble precipitate from FFP thawing at 1-6°C. Contains fibrinogen, Factor VIII, Factor XIII, vWF, and fibronectin.",
    clinicalRelevance: "RBC transfusion: Hb <7 g/dL (restrictive threshold for stable patients), <8 g/dL for cardiac disease. One unit raises Hb ~1 g/dL and Hct ~3%. Platelet transfusion: platelet count <10 ×10⁹/L (prophylactic), <50 ×10⁹/L (before procedures), <100 ×10⁹/L (neurosurgery). One apheresis unit raises count by 30,000-60,000/μL. FFP: coagulopathy with bleeding, warfarin reversal (if no PCC available), TTP (plasma exchange). Cryoprecipitate: fibrinogen <100-150 mg/dL (DIC, liver disease), Factor XIII deficiency.",
    signsSymptoms: "Component therapy is a therapeutic intervention. Transfusion need determined by clinical and laboratory assessment.",
    assessment: "Storage temperatures: RBCs 1-6°C, platelets 20-24°C (agitation), FFP/cryo ≤-18°C. Shelf life: RBCs 42 days (additive solutions), platelets 5 days, FFP 1 year frozen. Thawing: FFP thawed at 30-37°C in 20-30 minutes, used within 24 hours (or convert to thawed plasma, 5-day outdate). Cryoprecipitate: thawed at 30-37°C, pooled, used within 6 hours of pooling (4 hours if open system).",
    management: "Modified products: leukoreduced (prevent FNHTR, CMV-safe, prevent HLA alloimmunization), irradiated (prevent TA-GVHD), washed (remove plasma proteins for IgA-deficient/severe allergic), volume-reduced (neonates, fluid-restricted). CMV-safe: leukoreduced is equivalent to CMV-seronegative.",
    complications: "Storage lesion: decreased 2,3-DPG (restored within 24 hours post-transfusion), increased potassium (hyperkalemia risk with rapid/massive transfusion, especially neonates). Citrate toxicity: hypocalcemia from anticoagulant in massive transfusion. Hypothermia from cold blood products.",
    clinicalPearls: ["RBCs stored at 1-6°C for 42 days; platelets at 20-24°C for 5 days; FFP at ≤-18°C for 1 year", "Cryoprecipitate contains: fibrinogen, Factor VIII, Factor XIII, vWF, and fibronectin", "Leukoreduction prevents FNHTR, CMV transmission, and HLA alloimmunization"],
    examPitfalls: ["Platelets are stored at ROOM TEMPERATURE (20-24°C)—the only component NOT refrigerated", "Irradiation prevents TA-GVHD; leukoreduction does NOT prevent TA-GVHD (residual T lymphocytes can still engraft)", "2,3-DPG depletion during RBC storage causes LEFT shift of O2 dissociation curve (increased O2 affinity, decreased O2 delivery)"],
    faqJson: [{ question: "What is the storage lesion?", answer: "Progressive biochemical changes during RBC storage: decreased 2,3-DPG and ATP, increased potassium and lactate, decreased pH, membrane changes, and increased hemolysis. 2,3-DPG is restored within 24 hours of transfusion." }, { question: "What does cryoprecipitate contain?", answer: "Fibrinogen (150-250 mg per bag), Factor VIII (80-120 IU), Factor XIII, von Willebrand factor, and fibronectin. It is made by slowly thawing FFP at 1-6°C and collecting the cold-insoluble precipitate." }]
  }),

  // ======== COAGULATION continued ========
  E({ slug: "prothrombin-time-inr", title: "Prothrombin Time (PT) and INR", category: "Coagulation",
    seoTitle: "PT and INR – MLT Encyclopedia", seoDescription: "PT, INR: extrinsic pathway, warfarin monitoring, ISI, and preanalytical factors for MLT exam.", seoKeywords: ["prothrombin time", "PT", "INR", "warfarin", "extrinsic pathway", "tissue factor", "MLT exam"],
    overview: "The prothrombin time (PT) measures the extrinsic and common coagulation pathways (Factors VII, X, V, II, and fibrinogen). It is the primary test for monitoring warfarin (vitamin K antagonist) therapy and assessing liver synthetic function. The INR (International Normalized Ratio) standardizes PT results across laboratories for warfarin monitoring.",
    mechanismPhysiology: "PT reagent contains tissue factor (thromboplastin) and calcium. Tissue factor activates Factor VII → Factor VIIa activates Factor X → prothrombinase complex (Xa + Va) converts prothrombin to thrombin → thrombin converts fibrinogen to fibrin. INR = (Patient PT / Mean Normal PT)^ISI. ISI (International Sensitivity Index): assigned by the thromboplastin manufacturer; lower ISI = more sensitive reagent. ISI of 1.0 = ideal (reference thromboplastin).",
    clinicalRelevance: "Normal PT: 11-13.5 seconds. Normal INR: 0.8-1.2. Therapeutic INR for warfarin: 2.0-3.0 (most indications), 2.5-3.5 (mechanical heart valves). PT is prolonged by: warfarin, liver disease, vitamin K deficiency, DIC, factor deficiencies (VII, X, V, II, fibrinogen). Factor VII has the SHORTEST half-life (4-6 hours), so PT is the FIRST test to become prolonged in warfarin therapy and liver disease.",
    signsSymptoms: "PT/INR monitoring is a laboratory procedure. Supratherapeutic INR: increased bleeding risk. Subtherapeutic INR: thrombotic risk.",
    assessment: "Specimen: 3.2% sodium citrate (light blue top), 9:1 blood-to-citrate ratio. Centrifuge to obtain platelet-poor plasma (<10,000 platelets/μL). Testing: add tissue factor + calcium → measure time to clot formation (optical or mechanical endpoint). Critical specimen requirements: proper fill volume (underfilled = excess citrate = prolonged PT), no clots, processed within 24 hours (4 hours if on heparin).",
    management: "Warfarin monitoring: check INR 2-3 days after dose changes, weekly until stable, then monthly. Elevated INR without bleeding: hold warfarin, oral vitamin K. Elevated INR with bleeding: IV vitamin K + 4-factor PCC (prothrombin complex concentrate) or FFP.",
    complications: "Underfilled citrate tube: excess anticoagulant → falsely prolonged PT/INR. Heparin contamination: heparin primarily affects aPTT but high levels affect PT. Lipemia/icterus: may interfere with optical detection. Sample integrity issues: clotted, hemolyzed, or delayed specimens.",
    clinicalPearls: ["Factor VII has the SHORTEST half-life (4-6 hours)—PT is the FIRST test prolonged by warfarin and early liver disease", "INR standardizes PT across laboratories using the ISI of the thromboplastin reagent", "3.2% sodium citrate, 9:1 ratio—underfilled tubes are the most common preanalytical error"],
    examPitfalls: ["Underfilled citrate tube (excess citrate) causes FALSELY PROLONGED PT—always check fill volume", "INR is validated ONLY for warfarin monitoring—it should NOT be used to assess liver disease coagulopathy", "Heparin primarily prolongs aPTT but at high doses also prolongs PT"],
    faqJson: [{ question: "What is the ISI?", answer: "International Sensitivity Index assigned to each thromboplastin reagent by the manufacturer. It indicates the reagent's sensitivity to coagulation factor deficiencies. ISI of 1.0 = reference standard (most sensitive). Higher ISI = less sensitive reagent." }, { question: "Why is the 9:1 blood-to-citrate ratio important?", answer: "The citrate concentration is calibrated for a 9:1 ratio. Underfilling increases the citrate-to-blood ratio, causing excess calcium chelation and falsely prolonging clotting times. Overfilling results in insufficient anticoagulation and potential clot formation." }]
  }),
  E({ slug: "activated-partial-thromboplastin-time", title: "Activated Partial Thromboplastin Time (aPTT)", category: "Coagulation",
    seoTitle: "aPTT – MLT Encyclopedia", seoDescription: "aPTT: intrinsic pathway, heparin monitoring, factor deficiencies for MLT exam.", seoKeywords: ["aPTT", "activated partial thromboplastin time", "intrinsic pathway", "heparin monitoring", "MLT exam"],
    overview: "The activated partial thromboplastin time (aPTT) measures the intrinsic and common coagulation pathways (Factors XII, XI, IX, VIII, X, V, II, and fibrinogen). It is the primary test for monitoring unfractionated heparin therapy and screening for factor deficiencies and lupus anticoagulant.",
    mechanismPhysiology: "aPTT reagent contains a contact activator (kaolin, silica, or ellagic acid), phospholipid (partial thromboplastin—no tissue factor), and calcium. The activator initiates the intrinsic pathway: XII → XIIa → XI → XIa → IX → IXa + VIIIa → tenase complex → X → Xa + Va → prothrombinase → thrombin → fibrin. aPTT does NOT measure Factor VII (extrinsic pathway only) or Factor XIII (cross-linking factor).",
    clinicalRelevance: "Normal aPTT: 25-35 seconds (varies by reagent). Prolonged aPTT causes: heparin therapy, factor deficiencies (hemophilia A = VIII, hemophilia B = IX), lupus anticoagulant, specific factor inhibitors, vitamin K deficiency (if severe enough to affect Factors IX, X, II), liver disease, DIC. Heparin therapeutic range: aPTT 1.5-2.5× control (or anti-Xa 0.3-0.7 IU/mL).",
    signsSymptoms: "aPTT monitoring is a laboratory procedure. Factor deficiencies cause bleeding (hemarthrosis, deep tissue bleeding for Factors VIII/IX). Lupus anticoagulant paradoxically causes thrombosis.",
    assessment: "Specimen requirements: same as PT (3.2% citrate, 9:1, platelet-poor plasma). aPTT + PT combined interpretation: isolated prolonged aPTT (normal PT): Factor VIII, IX, XI, XII deficiency, or lupus anticoagulant, or heparin. Isolated prolonged PT (normal aPTT): Factor VII deficiency, early warfarin/vitamin K deficiency. Both prolonged: common pathway (X, V, II, fibrinogen) deficiency, liver disease, DIC, warfarin (advanced), heparin (high dose). Both normal: does NOT exclude bleeding disorders (Factor XIII deficiency, platelet disorders, vWD type 1).",
    management: "UFH monitoring: aPTT q6h after dose changes until therapeutic. Anti-Xa assay preferred when aPTT is unreliable (lupus anticoagulant, elevated factor VIII, elevated CRP). LMWH: monitored by anti-Xa level (aPTT is NOT reliable for LMWH monitoring).",
    complications: "Lupus anticoagulant prolongs aPTT but causes thrombosis (not bleeding). Elevated Factor VIII (acute phase reactant) shortens aPTT, masking heparin effect. Heparin contamination from IV lines is a common preanalytical error.",
    clinicalPearls: ["aPTT measures intrinsic (XII, XI, IX, VIII) and common (X, V, II, fibrinogen) pathways—NOT Factor VII", "Isolated prolonged aPTT with normal PT: think hemophilia A (VIII), hemophilia B (IX), or lupus anticoagulant", "Anti-Xa assay is preferred over aPTT for heparin monitoring when aPTT is unreliable"],
    examPitfalls: ["aPTT is NOT reliable for LMWH monitoring—use anti-Xa assay", "Factor XII deficiency prolongs aPTT but does NOT cause bleeding (no clinical significance)", "Normal PT AND normal aPTT does NOT rule out all bleeding disorders—Factor XIII deficiency and vWD can be missed"],
    faqJson: [{ question: "Why does lupus anticoagulant prolong aPTT?", answer: "Lupus anticoagulant is an antiphospholipid antibody that interferes with phospholipid-dependent coagulation tests in vitro (aPTT reagent contains phospholipid). In vivo, it paradoxically causes thrombosis through complex mechanisms." }, { question: "When is anti-Xa preferred over aPTT?", answer: "When aPTT is unreliable: lupus anticoagulant (falsely prolongs aPTT), elevated Factor VIII (acute phase reactant shortens aPTT), elevated CRP, for LMWH monitoring (aPTT not reliably affected), and in critically ill patients." }]
  }),

  // ======== URINALYSIS continued ========
  E({ slug: "urine-dipstick-testing", title: "Urine Dipstick Testing", category: "Urinalysis",
    seoTitle: "Urine Dipstick – MLT Encyclopedia", seoDescription: "Urine dipstick: reagent strip chemistry, false positives/negatives for MLT exam.", seoKeywords: ["urine dipstick", "reagent strip", "urinalysis", "false positive", "false negative", "MLT exam"],
    overview: "Urine reagent strip (dipstick) testing is a rapid, semi-quantitative screening method that measures multiple analytes simultaneously. Each reagent pad contains specific chemicals that produce a color change proportional to the analyte concentration. Results must be confirmed by microscopic examination and/or quantitative methods.",
    mechanismPhysiology: "Key reagent pad chemistries: pH: double indicator system (methyl red + bromothymol blue). Protein: protein error of indicators (tetrabromphenol blue changes color at constant pH when protein binds). Detects ALBUMIN primarily—misses Bence Jones protein and other globulins. Glucose: glucose oxidase/peroxidase double sequential enzyme reaction (specific for glucose). Blood: pseudoperoxidase activity of hemoglobin catalyzes oxidation of a chromogen. Detects free hemoglobin, myoglobin, AND intact RBCs (lysed on pad). Leukocyte esterase: detects esterase enzyme from granulocyte WBCs. Nitrite: Griess reaction—detects nitrite produced by bacterial reduction of nitrate (most Enterobacteriaceae).",
    clinicalRelevance: "Protein: albumin >30 mg/dL (positive). FALSE POSITIVE: highly alkaline urine (pH >8), quaternary ammonium compounds. FALSE NEGATIVE: Bence Jones protein, dilute urine. Glucose: FALSE NEGATIVE: ascorbic acid (vitamin C) interferes with glucose oxidase method. Blood: FALSE POSITIVE: myoglobin, oxidizing contaminants. FALSE NEGATIVE: high ascorbic acid, formalin. Nitrite: FALSE NEGATIVE: organisms that don't reduce nitrate (Enterococcus, Pseudomonas, yeast), insufficient bladder incubation time (<4 hours), ascorbic acid.",
    signsSymptoms: "Dipstick testing is a screening procedure. Results guide clinical decision-making.",
    assessment: "Reading: match pad color to chart at specified time interval (usually 60 seconds, leukocyte esterase 2 minutes). Automated readers improve consistency. Specific gravity: polyelectrolyte ionization method (detects ionic solutes only—not glucose, contrast dye, or protein). Refractometer measures ALL dissolved solutes (more accurate). Bilirubin: diazo reaction. Urobilinogen: Ehrlich reaction (positive with porphobilinogen and sulfonamides too). Ketones: nitroprusside reaction (detects acetoacetate and acetone, NOT beta-hydroxybutyrate—the predominant ketone in DKA).",
    management: "Positive protein: confirm with 24-hour urine protein or urine albumin-to-creatinine ratio (UACR). Positive blood: confirm with microscopic exam for RBCs. Positive nitrite/LE: correlate with culture. All abnormal dipstick results should be followed by microscopic examination.",
    complications: "Expired reagent strips give unreliable results. Improper technique: over-dipping, delayed reading, running colors between pads. Room temperature storage of strips is essential (refrigeration causes deterioration).",
    clinicalPearls: ["Dipstick PROTEIN detects primarily ALBUMIN—misses Bence Jones protein (use SSA acid precipitation test)", "Ascorbic acid (vitamin C) causes FALSE NEGATIVE glucose, blood, and nitrite results", "Dipstick KETONES detect acetoacetate/acetone but NOT beta-hydroxybutyrate—the most abundant ketone in DKA"],
    examPitfalls: ["Specific gravity by dipstick measures IONIC solutes only—not affected by glucose or contrast dye (unlike refractometer)", "Highly alkaline urine (pH >8) causes FALSE POSITIVE protein—the protein error of indicators method is pH-dependent", "Nitrite test requires bacteria that REDUCE nitrate AND adequate bladder incubation time (≥4 hours)—first morning specimen is best"],
    faqJson: [{ question: "Why does ascorbic acid cause false negatives?", answer: "Ascorbic acid (vitamin C) is a reducing agent that interferes with oxidase-based reactions (glucose oxidase, peroxidase for blood) and the Griess reaction (nitrite). It consumes the oxidizing intermediates before they can react with the chromogen." }, { question: "What confirms a positive protein dipstick?", answer: "24-hour urine protein collection (gold standard, normal <150 mg/day) or urine albumin-to-creatinine ratio (UACR, spot sample, normal <30 mg/g). Sulfosalicylic acid (SSA) test detects ALL proteins including Bence Jones (immunoglobulin light chains)." }]
  }),

  // ======== IMMUNOLOGY continued ========
  E({ slug: "hiv-testing-algorithm", title: "HIV Testing Algorithm", category: "Immunology/Serology",
    seoTitle: "HIV Testing Algorithm – MLT Encyclopedia", seoDescription: "HIV diagnosis: 4th gen Ag/Ab combo, differentiation assay, NAT, window period for MLT exam.", seoKeywords: ["HIV testing", "4th generation", "p24 antigen", "HIV-1/2 differentiation", "window period", "MLT exam"],
    overview: "HIV diagnosis follows the CDC/APHL recommended algorithm using a sequential three-step testing approach: (1) 4th generation HIV-1/2 Ag/Ab combination immunoassay, (2) HIV-1/HIV-2 antibody differentiation assay, and (3) HIV-1 NAT (nucleic acid test) if differentiation is indeterminate. This algorithm detects infection earlier than previous antibody-only approaches.",
    mechanismPhysiology: "4th generation (combo) assay: detects both HIV-1/HIV-2 antibodies (IgG and IgM) AND p24 antigen simultaneously. p24 antigen appears earlier than antibodies (detectable ~2 weeks post-infection vs ~3-4 weeks for antibodies). This narrows the window period to approximately 2 weeks. HIV-1/HIV-2 differentiation assay: identifies which virus type is present using separate antibody detection. HIV-1 NAT: detects HIV-1 RNA, confirming acute infection when antibodies are not yet detectable.",
    clinicalRelevance: "Window period: time between infection and detection by testing. 4th gen combo assay window: ~2 weeks (p24 antigen detection). Antibody-only assay window: ~3-4 weeks. Acute HIV infection: high viral load, p24 antigen positive, antibody negative or indeterminate—highly infectious period.",
    signsSymptoms: "Acute HIV: mononucleosis-like syndrome (fever, lymphadenopathy, pharyngitis, rash, myalgia) 2-4 weeks post-infection. Many patients are asymptomatic. Chronic HIV: progressive immunodeficiency, opportunistic infections when CD4 <200 cells/μL (AIDS-defining).",
    assessment: "Step 1: 4th gen Ag/Ab combo immunoassay. If REACTIVE → Step 2: HIV-1/HIV-2 antibody differentiation assay. If HIV-1 positive or HIV-2 positive → CONFIRMED. If HIV-1 indeterminate or negative → Step 3: HIV-1 NAT. NAT positive → acute HIV-1 infection (antibodies not yet developed). NAT negative → false positive on initial screen. Rapid/POC tests: mostly antibody-only (3rd generation)—may miss acute infection. CD4 count and HIV viral load: used for staging and monitoring, not diagnosis.",
    management: "ART (antiretroviral therapy) for all HIV-positive individuals regardless of CD4 count. U=U (Undetectable = Untransmittable): suppressed viral load prevents sexual transmission. PrEP (pre-exposure prophylaxis) for high-risk individuals.",
    complications: "False positive 4th gen screen: resolved by differentiation assay and NAT. False negative: testing during eclipse period (before p24 antigen detectable, ~10 days). Elite controllers: suppress virus without ART (rare). Drug resistance testing: genotypic resistance testing before starting ART.",
    clinicalPearls: ["4th gen combo assay detects p24 ANTIGEN + antibodies—narrows window period to ~2 weeks", "HIV-1/HIV-2 differentiation assay is Step 2—identifies virus type", "NAT (Step 3) detects acute HIV-1 infection when antibodies are not yet developed"],
    examPitfalls: ["Rapid/POC HIV tests are mostly antibody-only—may MISS acute infection (p24 antigen not detected)", "Western blot is NO LONGER recommended in the current CDC algorithm—replaced by differentiation assay", "p24 antigen may transiently become undetectable as antibodies appear (antigen-antibody complexes)—the 'second window'"],
    faqJson: [{ question: "Why was Western blot replaced?", answer: "The HIV-1/HIV-2 differentiation assay is faster, less expensive, and can distinguish HIV-1 from HIV-2. Western blot had high indeterminate rates, could not differentiate HIV types, and had longer turnaround time." }, { question: "What is the eclipse period?", answer: "The ~10 days after infection when neither p24 antigen nor antibodies are detectable by any serologic test. Only HIV-1 NAT (RNA detection) can identify infection during this earliest period." }]
  }),

  // ======== LAB SAFETY continued ========
  E({ slug: "specimen-collection-handling", title: "Specimen Collection and Handling", category: "Lab Safety & Quality Control",
    seoTitle: "Specimen Collection – MLT Encyclopedia", seoDescription: "Venipuncture, order of draw, specimen handling, preanalytical errors for MLT exam.", seoKeywords: ["specimen collection", "order of draw", "venipuncture", "preanalytical error", "hemolysis", "MLT exam"],
    overview: "Preanalytical errors account for 46-68% of all laboratory errors. Proper specimen collection, handling, and transport are critical for accurate test results. The phlebotomist/collector is the most important person in the laboratory testing process because specimen quality determines result quality.",
    mechanismPhysiology: "Order of draw (CLSI standard): Blood cultures (sterile) → Light blue (citrate—coagulation) → Red/gold (SST—serum) → Light green (PST—plasma) → Green (heparin) → Lavender (EDTA) → Gray (fluoride/oxalate). Rationale: prevents carryover of additives between tubes that would interfere with testing (e.g., EDTA contamination of citrate tube affects coagulation; tissue thromboplastin from venipuncture activates coagulation in the first tube).",
    clinicalRelevance: "Most common preanalytical errors: wrong patient identification (most dangerous), hemolysis (most common reason for specimen rejection), clotted specimens in anticoagulant tubes, improper fill volume (especially citrate tubes), delayed transport/processing. Hemolysis causes: falsely elevated potassium, LDH, AST, phosphorus, magnesium; falsely decreased haptoglobin; interferes with optical measurements.",
    signsSymptoms: "Preanalytical errors are laboratory process issues, not patient symptoms.",
    assessment: "Venipuncture site selection: antecubital fossa (median cubital vein preferred). Avoid: above IV site (dilution), mastectomy side (lymphedema risk), hematoma sites, edematous areas, AV fistula arm (dialysis patients). Tourniquet: apply ≤1 minute (prolonged application causes hemoconcentration of proteins, cells, and protein-bound analytes). Needle gauge: 21-22G for adults, 23G for difficult veins. Evacuated tube system (Vacutainer) is standard.",
    management: "Patient identification: two unique identifiers (name + DOB, or name + MRN). Label specimens at bedside. Reject and recollect: hemolyzed (for K, LDH), clotted (for CBC, coag), mislabeled, wrong tube, insufficient volume. Critical specimens: process stat, transport on ice (ABG, ammonia, lactic acid), protect from light (bilirubin, porphyrins).",
    complications: "Hemoconcentration from prolonged tourniquet: falsely elevated proteins, calcium, cholesterol, cells. Specimen collected above IV: falsely diluted or contaminated with IV fluid. Short draw citrate tube: excess citrate → prolonged PT/aPTT. EDTA contamination of chemistry specimens: falsely decreased calcium (chelated), falsely elevated potassium.",
    clinicalPearls: ["Blood cultures are ALWAYS drawn FIRST in the order of draw—to minimize contamination", "Light blue (citrate) tube MUST be properly filled (9:1 ratio)—short draws cause falsely prolonged PT/aPTT", "Hemolysis is the NUMBER ONE cause of specimen rejection—affects K+, LDH, AST most significantly"],
    examPitfalls: ["Tourniquet >1 minute causes hemoconcentration—elevates proteins, cholesterol, calcium", "Collecting blood ABOVE an IV infusion site gives falsely diluted/contaminated results", "EDTA contamination of a chemistry tube: falsely DECREASED calcium (EDTA chelates calcium) and falsely ELEVATED potassium"],
    faqJson: [{ question: "Why are blood cultures drawn first?", answer: "Blood cultures must be collected from a sterile site into sterile bottles to prevent contamination. Drawing them first minimizes the introduction of additives from other tubes and reduces contamination from the venipuncture site." }, { question: "Why does hemolysis affect potassium?", answer: "RBCs contain ~150 mEq/L potassium (30× the serum concentration). Even mild hemolysis releases significant intracellular potassium, causing falsely elevated results that may trigger unnecessary clinical interventions." }]
  }),

  // ======== MOLECULAR DIAGNOSTICS continued ========
  E({ slug: "southern-northern-western-blotting", title: "Blotting Techniques (Southern, Northern, Western)", category: "Molecular Diagnostics",
    seoTitle: "Blotting Techniques – MLT Encyclopedia", seoDescription: "Southern blot DNA, Northern blot RNA, Western blot protein: principles and applications for MLT exam.", seoKeywords: ["Southern blot", "Northern blot", "Western blot", "blotting techniques", "DNA analysis", "MLT exam"],
    overview: "Blotting techniques are molecular methods for detecting specific DNA (Southern), RNA (Northern), or protein (Western) molecules after gel electrophoresis. Named after Edwin Southern (DNA blot); Northern and Western are derivative names. While largely replaced by PCR and newer methods for routine diagnostics, understanding these techniques is important for MLT certification.",
    mechanismPhysiology: "General principle: (1) Separate molecules by gel electrophoresis (agarose for DNA/RNA, polyacrylamide/SDS-PAGE for proteins). (2) Transfer (blot) separated molecules to a membrane (nitrocellulose or PVDF). (3) Detect target using a labeled probe (DNA/RNA probes for Southern/Northern; labeled antibodies for Western). Southern blot: DNA digested with restriction enzymes → agarose gel electrophoresis → alkaline denaturation → transfer to membrane → hybridize with labeled DNA probe → detect. Northern blot: RNA separated on denaturing gel → transfer → hybridize with labeled probe → detect (RNA is labile, work in RNase-free conditions). Western blot: proteins separated by SDS-PAGE → transfer → block non-specific binding → primary antibody → labeled secondary antibody → detect.",
    clinicalRelevance: "Southern blot: historically used for gene rearrangement studies (BCR-ABL, immunoglobulin/T-cell receptor rearrangements for lymphoma), DNA fingerprinting (RFLP), and detecting specific gene mutations. Now largely replaced by PCR, FISH, and NGS. Western blot: was confirmatory test for HIV (replaced by HIV-1/HIV-2 differentiation assay in current algorithm), used for Lyme disease confirmatory testing (detects specific antibody bands).",
    signsSymptoms: "Blotting techniques are laboratory procedures with no patient symptoms.",
    assessment: "Key differences: Southern = DNA target + DNA probe. Northern = RNA target + DNA/RNA probe. Western = protein target + antibody probe. SDS-PAGE (Western): SDS denatures proteins and gives uniform negative charge, so separation is by molecular weight only. Transfer methods: capillary (Southern, overnight), electroblotting (Western, faster). Detection: radioactive (³²P), chemiluminescent, colorimetric, or fluorescent labels.",
    management: "Quality control: positive and negative controls, molecular weight markers/ladders. Troubleshooting: no signal (probe degradation, insufficient target, wash stringency too high), high background (insufficient blocking, wash stringency too low), non-specific bands (cross-reactive antibodies in Western).",
    complications: "Southern blot: time-consuming (2-3 days), requires relatively large DNA amounts. Northern blot: RNA degradation by ubiquitous RNases. Western blot: semi-quantitative, subjective band interpretation, replaced for HIV by more objective assays.",
    clinicalPearls: ["Southern = DNA, Northern = RNA, Western = PROTEIN—remember: SNoW DRoP (Southern-Northern-Western = DNA-RNA-Protein)", "Western blot is NO LONGER the HIV confirmatory test—replaced by HIV-1/HIV-2 differentiation assay", "SDS in Western blot denatures proteins and gives them uniform negative charge—separation is by SIZE only"],
    examPitfalls: ["Southern blot uses RESTRICTION ENZYMES to cut DNA; Northern blot does NOT cut RNA", "Western blot for Lyme disease is still used as a confirmatory test (unlike HIV where it was replaced)", "RNA is extremely labile—Northern blot requires RNase-free conditions (DEPC-treated water, gloves)"],
    faqJson: [{ question: "What is the SNoW DRoP mnemonic?", answer: "Southern-Northern-Western corresponds to DNA-RNA-Protein. Southern blot detects DNA with DNA probes. Northern blot detects RNA with complementary probes. Western blot detects proteins with antibodies." }, { question: "Why was Western blot replaced for HIV?", answer: "Western blot had high rates of indeterminate results, could not distinguish HIV-1 from HIV-2, was expensive, and had long turnaround time. The HIV-1/HIV-2 differentiation immunoassay is faster, more specific, and identifies virus type." }]
  }),

  // ======== PARASITOLOGY continued ========
  E({ slug: "intestinal-parasites-ova-examination", title: "Ova and Parasite Examination (O&P)", category: "Parasitology",
    seoTitle: "O&P Examination – MLT Encyclopedia", seoDescription: "O&P exam: concentration techniques, permanent stains, common intestinal parasites for MLT exam.", seoKeywords: ["ova and parasite", "O&P examination", "formalin-ethyl acetate", "trichrome stain", "intestinal parasites", "MLT exam"],
    overview: "The ova and parasite (O&P) examination is a comprehensive stool analysis for detecting intestinal parasites. A complete O&P includes three components: direct wet mount (motility), concentration (increases sensitivity), and permanent stained smear (morphologic detail). Three specimens collected on alternate days are recommended for maximum sensitivity.",
    mechanismPhysiology: "Concentration techniques increase parasite detection by removing fecal debris. Formalin-ethyl acetate (FEA) sedimentation: most widely used, recovers protozoan cysts, helminth eggs, and larvae in the sediment. Zinc sulfate flotation: floats protozoan cysts to the surface (may distort operculated eggs). Permanent stains: trichrome (Wheatley modification) or iron hematoxylin provide detailed morphology for protozoan identification (nuclear structure, cytoplasmic inclusions). PVA (polyvinyl alcohol) preservative: for permanent stains. Formalin (10% buffered): for concentration.",
    clinicalRelevance: "Common exam parasites: Entamoeba histolytica (pathogenic ameba, ingested RBCs in trophozoite), Giardia lamblia (teardrop trophozoite, falling-leaf motility, oval cyst with 4 nuclei), Cryptosporidium (modified acid-fast oocysts), Ascaris lumbricoides (largest intestinal roundworm, fertile vs infertile eggs), hookworm (Ancylostoma/Necator—eggs identical), Enterobius vermicularis (pinworm—NOT detected by O&P, use cellophane tape/paddle test), Trichuris trichiura (whipworm, barrel-shaped egg with bipolar plugs).",
    signsSymptoms: "Varies by parasite: diarrhea (watery, bloody, or fatty), abdominal pain, weight loss, malabsorption, perianal itching (pinworm), cough (larval migration—Ascaris, hookworm), iron-deficiency anemia (hookworm).",
    assessment: "Direct wet mount: saline preparation (motile trophozoites, larvae, eggs), iodine preparation (highlights cyst nuclei and glycogen). Concentration: FEA sediment examined with saline and iodine. Permanent stain: trichrome or iron hematoxylin on PVA-fixed smear. Special stains: modified acid-fast (Cryptosporidium, Cyclospora, Isospora—oocysts), modified trichrome/Weber (microsporidia). Timing: specimens should be examined within 30 minutes for trophozoite motility, or fixed immediately in PVA and formalin.",
    management: "Three specimens on alternate days (sensitivity: 1 specimen ~50%, 3 specimens >90%). Reject unpreserved stool specimens received >2 hours after collection (trophozoites degenerate). No barium, bismuth, or mineral oil 5-7 days before collection (interfere with examination).",
    complications: "False negatives: insufficient specimens, delay in processing, interfering substances (barium, antibiotics). False positives: misidentification of WBCs as amebae, yeast as cysts, pollen/plant cells as eggs. E. histolytica vs E. dispar: morphologically identical—antigen testing or PCR required to differentiate (only E. histolytica is pathogenic).",
    clinicalPearls: ["Three specimens on ALTERNATE days for maximum O&P sensitivity—single specimen misses ~50% of infections", "Enterobius (pinworm) is NOT detected by routine O&P—use cellophane tape/paddle test collected in the MORNING", "E. histolytica trophozoite with ingested RBCs is PATHOGNOMONIC—no other ameba ingests RBCs"],
    examPitfalls: ["E. histolytica and E. dispar are MORPHOLOGICALLY IDENTICAL—antigen or molecular testing differentiates them", "Modified acid-fast stain detects Cryptosporidium, Cyclospora, and Isospora—NOT routine trichrome", "Unpreserved stool specimens >2 hours old are UNACCEPTABLE for trophozoite detection"],
    faqJson: [{ question: "Why three specimens on alternate days?", answer: "Parasites are shed intermittently. A single specimen detects only ~50% of infections. Three specimens collected on alternate days over 7-10 days increases sensitivity to >90% by capturing different shedding cycles." }, { question: "Why is pinworm not detected by O&P?", answer: "Female Enterobius vermicularis migrates to the perianal area at night to deposit eggs. Eggs are not found in stool. The cellophane tape (Scotch tape) test or paddle device applied to perianal skin in the early morning is the diagnostic method." }]
  }),

  // ======== MYCOLOGY continued ========
  E({ slug: "aspergillus-species", title: "Aspergillus Species", category: "Mycology",
    seoTitle: "Aspergillus Species – MLT Encyclopedia", seoDescription: "Aspergillus fumigatus: galactomannan, septate hyphae, ABPA, invasive aspergillosis for MLT exam.", seoKeywords: ["Aspergillus fumigatus", "galactomannan", "septate hyphae", "invasive aspergillosis", "ABPA", "MLT exam"],
    overview: "Aspergillus is a ubiquitous saprophytic mold that causes a spectrum of diseases: allergic (ABPA), chronic (aspergilloma/fungal ball), and invasive aspergillosis (IA). A. fumigatus is the most common pathogenic species. Invasive aspergillosis is a life-threatening infection in severely immunocompromised patients (neutropenic, transplant recipients, high-dose corticosteroids).",
    mechanismPhysiology: "Aspergillus produces conidia (spores) that are inhaled and deposited in the airways. In immunocompetent hosts, neutrophils and macrophages clear conidia. In immunocompromised (neutropenic) patients, conidia germinate into hyphae that invade blood vessels (angioinvasive), causing thrombosis, infarction, and hemorrhage. Aspergillus has SEPTATE hyphae with DICHOTOMOUS (45°) branching—distinguishing it from Mucor (aseptate/pauciseptate with 90° branching).",
    clinicalRelevance: "Invasive aspergillosis: angioinvasive, pulmonary involvement (halo sign on CT—ground-glass opacity surrounding nodule), dissemination to brain, skin, other organs. Aspergilloma: fungal ball in pre-existing lung cavity (old TB cavity). ABPA: allergic bronchopulmonary aspergillosis in asthma/CF patients (elevated IgE, eosinophilia, positive Aspergillus precipitins).",
    signsSymptoms: "Invasive pulmonary: fever unresponsive to antibiotics in neutropenic patient, cough, hemoptysis, pleuritic chest pain. Aspergilloma: hemoptysis (can be massive), chronic cough. ABPA: wheezing, mucus plugging, fleeting pulmonary infiltrates, eosinophilia.",
    assessment: "Direct examination: KOH/calcofluor white showing septate hyphae with 45° dichotomous branching. Culture: SDA at 25-30°C (growth in 1-7 days). A. fumigatus: blue-green (smoky gray-green) colonies, thermotolerant (growth at 45°C), uniseriate conidial head (phialides on upper 2/3 of vesicle). A. flavus: yellow-green colonies. A. niger: black colonies (black pepper appearance). Galactomannan antigen (serum/BAL): cell wall polysaccharide marker for invasive aspergillosis. 1,3-beta-D-glucan (BDG): pan-fungal marker (positive in Aspergillus, Candida, Pneumocystis—NOT Mucor/Cryptococcus).",
    management: "Invasive aspergillosis: voriconazole (drug of choice), isavuconazole, amphotericin B. Aspergilloma: surgical resection if symptomatic. ABPA: corticosteroids ± itraconazole.",
    complications: "Invasive aspergillosis mortality: 30-60% despite treatment. Breakthrough infections on prophylactic azoles. Resistance to azoles emerging (TR34/L98H mutation).",
    clinicalPearls: ["Aspergillus has SEPTATE hyphae with 45° DICHOTOMOUS branching; Mucor has ASEPTATE (pauciseptate) hyphae with 90° branching", "Galactomannan is specific for ASPERGILLUS; BDG is pan-fungal (NOT positive for Mucor or Cryptococcus)", "Voriconazole is the drug of choice for invasive aspergillosis—NOT amphotericin B (first-line)"],
    examPitfalls: ["Aspergillus is INHIBITED by cycloheximide (Mycosel/mycobiotic agar)—use plain SDA for culture", "Galactomannan false positive: piperacillin-tazobactam (fermentation-derived), cross-reaction with other fungi", "1,3-beta-D-glucan is NOT positive for Mucor (Zygomycetes) or Cryptococcus—know the exceptions"],
    faqJson: [{ question: "How is Aspergillus differentiated from Mucor on tissue/smear?", answer: "Aspergillus: SEPTATE hyphae with DICHOTOMOUS 45° branching (uniform width). Mucor: ASEPTATE (pauciseptate, ribbon-like) hyphae with 90° WIDE-ANGLE branching (variable width). This distinction is critical for treatment (voriconazole for Aspergillus, amphotericin B for Mucor)." }, { question: "What is the halo sign?", answer: "A CT finding in invasive pulmonary aspergillosis: a ground-glass opacity (representing hemorrhage) surrounding a pulmonary nodule (representing infarction from angioinvasion). It is an early sign in neutropenic patients and should prompt empiric antifungal therapy." }]
  }),

  // ======== BODY FLUIDS continued ========
  E({ slug: "cerebrospinal-fluid-analysis", title: "Cerebrospinal Fluid (CSF) Analysis", category: "Body Fluids",
    seoTitle: "CSF Analysis – MLT Encyclopedia", seoDescription: "CSF: cell count, protein, glucose, bacterial vs viral meningitis differentiation for MLT exam.", seoKeywords: ["CSF analysis", "cerebrospinal fluid", "meningitis", "CSF protein", "CSF glucose", "MLT exam"],
    overview: "CSF analysis is critical for diagnosing meningitis, encephalitis, subarachnoid hemorrhage, and CNS malignancies. CSF is collected by lumbar puncture (LP) and is a STAT specimen that must be analyzed immediately. The classic tube distribution: Tube 1 (chemistry/serology), Tube 2 (microbiology), Tube 3 (cell count—least likely to contain blood from traumatic tap).",
    mechanismPhysiology: "Normal CSF: crystal clear, colorless, WBC 0-5/μL (all lymphocytes/monocytes), protein 15-45 mg/dL, glucose 60-70% of serum glucose (CSF/serum ratio >0.6). CSF is produced by choroid plexus (500 mL/day, total volume ~150 mL). The blood-brain barrier limits protein and cell entry. Increased WBCs, protein, and decreased glucose indicate meningeal inflammation/infection.",
    clinicalRelevance: "Bacterial meningitis: turbid CSF, markedly elevated WBC (>1,000/μL, predominantly PMNs/neutrophils), very elevated protein (>100 mg/dL), very decreased glucose (<40 mg/dL, CSF/serum ratio <0.4). Viral meningitis: clear CSF, mildly elevated WBC (10-500/μL, predominantly lymphocytes), mildly elevated protein, normal glucose. TB meningitis: clear to slightly turbid, WBC 25-500/μL (lymphocytes), elevated protein, very decreased glucose. Fungal meningitis (Cryptococcus): lymphocytic pleocytosis, decreased glucose, elevated protein, positive India ink (50% sensitivity), positive cryptococcal antigen (CrAg, >95% sensitivity).",
    signsSymptoms: "Meningitis: headache, neck stiffness (nuchal rigidity), fever, photophobia, altered mental status. Kernig sign (pain with knee extension), Brudzinski sign (neck flexion causes hip flexion). Neonatal meningitis: irritability, poor feeding, bulging fontanelle.",
    assessment: "Cell count: manual hemocytometer (Neubauer chamber). Tube 3 preferred for cell count (least traumatic blood contamination). Differential: cytocentrifuge preparation with Wright-Giemsa stain. Gram stain: S. pneumoniae (GPC in pairs), N. meningitidis (GN diplococci), H. influenzae (GN coccobacilli), Group B Strep (GPC in chains, neonates), Listeria (GP rods, neonates/elderly/immunocompromised). India ink: negative staining for Cryptococcus (encapsulated yeast with wide clear halo). Cryptococcal antigen (CrAg): latex agglutination or lateral flow assay (>95% sensitive). STAT processing: CSF is an irreplaceable specimen that degrades rapidly.",
    management: "CSF must be processed STAT—WBCs lyse within 1 hour, bacteria may die. Tube distribution: Tube 1 chemistry, Tube 2 micro, Tube 3 cell count (or lab-specific protocol). Never refrigerate CSF for microbiology (organisms may die). Gram stain positive in 60-90% of bacterial meningitis. Culture is gold standard.",
    complications: "Traumatic tap: blood contamination from the LP procedure. Correction formula: subtract 1 WBC for every 700 RBCs (rough estimate). Xanthochromia (yellow supernatant): indicates subarachnoid hemorrhage (hemoglobin breakdown to bilirubin) vs traumatic tap (clear supernatant after centrifugation). CSF WBCs lyse rapidly: count within 30 minutes to 1 hour of collection.",
    clinicalPearls: ["Tube 3 for cell count—least likely to be contaminated by traumatic tap blood", "CSF glucose must be compared to SERUM glucose (collected simultaneously)—normal CSF/serum ratio >0.6", "India ink is only 50% sensitive for Cryptococcus; CrAg (latex/LFA) is >95% sensitive—use CrAg"],
    examPitfalls: ["CSF must be analyzed STAT—WBCs lyse within 1 hour, delaying count gives falsely LOW results", "Traumatic tap vs SAH: traumatic tap clears in successive tubes and has clear supernatant; SAH has uniform blood and xanthochromic (yellow) supernatant", "Normal CSF WBC is 0-5/μL (lymphocytes/monocytes)—ANY neutrophils in CSF are abnormal"],
    faqJson: [{ question: "How to differentiate bacterial from viral meningitis?", answer: "Bacterial: turbid, WBC >1,000 (PMN predominant), very high protein, very low glucose. Viral: clear, WBC 10-500 (lymphocyte predominant), mildly elevated protein, normal glucose. TB/fungal: lymphocytic, elevated protein, low glucose (resembles bacterial for glucose)." }, { question: "What is xanthochromia?", answer: "Yellow discoloration of CSF supernatant from hemoglobin breakdown products (bilirubin). It indicates blood has been in the CSF space for at least 2-4 hours, distinguishing subarachnoid hemorrhage (xanthochromic) from traumatic tap (clear supernatant)." }]
  }),
  E({ slug: "pleural-fluid-analysis", title: "Pleural Fluid Analysis", category: "Body Fluids",
    seoTitle: "Pleural Fluid Analysis – MLT Encyclopedia", seoDescription: "Pleural fluid: Light criteria, transudate vs exudate differentiation for MLT exam.", seoKeywords: ["pleural fluid", "Light criteria", "transudate", "exudate", "pleural effusion", "MLT exam"],
    overview: "Pleural fluid analysis differentiates transudative from exudative effusions using Light's criteria. This distinction is critical because transudates are managed medically (treat underlying cause) while exudates require further investigation (infection, malignancy, inflammation).",
    mechanismPhysiology: "Transudates: caused by systemic factors altering hydrostatic or oncotic pressure. Fluid is an ultrafiltrate of plasma—low protein, low LDH, clear, straw-colored. Causes: CHF (most common), cirrhosis, nephrotic syndrome. Exudates: caused by local factors (inflammation, infection, malignancy) that increase capillary permeability or decrease lymphatic drainage. High protein, high LDH, may be turbid or bloody.",
    clinicalRelevance: "Light's criteria (ANY one = exudate): (1) Pleural fluid protein/serum protein ratio >0.5. (2) Pleural fluid LDH/serum LDH ratio >0.6. (3) Pleural fluid LDH >2/3 the upper limit of normal serum LDH. If NONE met → transudate. Light's criteria are 98% sensitive for exudates but may misclassify some transudates (CHF on diuretics) as exudates.",
    signsSymptoms: "Pleural effusion: dyspnea, pleuritic chest pain, decreased breath sounds, dullness to percussion on the affected side, decreased tactile fremitus.",
    assessment: "Gross appearance: clear/straw (transudate), turbid/cloudy (infection/inflammation), bloody (malignancy, trauma, PE), milky (chylothorax—triglycerides >110 mg/dL). Cell count and differential: neutrophil predominance (bacterial infection, early PE), lymphocyte predominance (TB, malignancy, viral), eosinophil predominance (parasitic, drug reaction, air/blood in pleural space). Chemistry: protein, LDH, glucose (decreased in empyema, TB, malignancy, RA), pH (<7.2 suggests empyema). Microbiology: Gram stain, culture (aerobic and anaerobic). Cytology: malignant cells (metastatic cancer, mesothelioma).",
    management: "Transudate: treat underlying cause (diuretics for CHF, paracentesis for cirrhosis). Exudate: thoracentesis (diagnostic and therapeutic), chest tube drainage for empyema, pleurodesis for malignant effusion.",
    complications: "Empyema: infected pleural space (pH <7.2, glucose <60 mg/dL, positive Gram stain/culture)—requires chest tube drainage. Chylothorax: lymphatic disruption (thoracic duct injury), milky fluid, triglycerides >110 mg/dL. Pseudochylous effusion: cholesterol crystals (chronic effusion, RA).",
    clinicalPearls: ["Light's criteria: ANY ONE criterion met = EXUDATE (98% sensitive)", "CHF is the most common cause of TRANSUDATIVE effusion; pneumonia is the most common cause of EXUDATIVE effusion", "pH <7.2 in pleural fluid suggests EMPYEMA—requires chest tube drainage"],
    examPitfalls: ["Light's criteria may misclassify CHF transudates as exudates in patients on diuretics—check serum-pleural albumin gradient", "Chylothorax (triglycerides >110) vs pseudochylous (cholesterol crystals)—different etiologies and management", "Lymphocyte-predominant exudate: think TB or malignancy—cytology and adenosine deaminase (ADA) help differentiate"],
    faqJson: [{ question: "What are Light's criteria?", answer: "Exudate if ANY one: (1) fluid protein/serum protein >0.5, (2) fluid LDH/serum LDH >0.6, (3) fluid LDH >2/3 upper limit of normal serum LDH. All three must be negative for transudate classification." }, { question: "What is a chylothorax?", answer: "Lymphatic fluid (chyle) in the pleural space from thoracic duct disruption (surgery, trauma, malignancy). Milky appearance with triglycerides >110 mg/dL. Contains chylomicrons. Treated by thoracic duct ligation or pleurodesis." }]
  }),
];

async function run() {
  let inserted = 0, errors = 0;
  console.log(`Starting MLT Encyclopedia Batch 4: ${ENTRIES.length} entries\n`);
  for (const e of ENTRIES) {
    try {
      await insertEntry(e);
      inserted++;
    } catch (err: any) {
      errors++;
      console.error(`Error inserting ${e.slug}: ${err.message}`);
    }
  }
  console.log(`\nBatch 4 complete: ${inserted} inserted, ${errors} errors out of ${ENTRIES.length} total entries`);
  const { rows } = await pool.query(`SELECT category, COUNT(*) as cnt FROM encyclopedia_entries WHERE profession='mlt' AND status='published' GROUP BY category ORDER BY category`);
  console.log("\nAll MLT entries by category:");
  for (const r of rows) console.log(`  ${r.category}: ${r.cnt}`);
  const { rows: [{ total }] } = await pool.query(`SELECT COUNT(*) as total FROM encyclopedia_entries WHERE profession='mlt' AND status='published'`);
  console.log(`\nTotal published MLT encyclopedia entries: ${total}`);
  console.log("Done!");
  await pool.end();
}
run();
