import { pool } from "../server/storage";

interface EncEntry {
  slug: string; title: string; category: string;
  seoTitle: string; seoDescription: string; seoKeywords: string[];
  overview: string; mechanismPhysiology: string; clinicalRelevance: string;
  signsSymptoms: string; assessment: string; management: string; complications: string;
  clinicalPearls: string[]; examPitfalls: string[];
  faqJson: { question: string; answer: string }[];
}

const E = (e: EncEntry) => ({ profession: "mlt" as const, status: "published" as const, ...e });

async function ins(e: ReturnType<typeof E>) {
  const t = await pool.query(
    `INSERT INTO encyclopedia_topics (profession,slug,title,category,related_lesson_ids,related_question_ids,status)
     VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (profession,slug) DO UPDATE SET title=$3,category=$4,updated_at=NOW() RETURNING id`,
    [e.profession,e.slug,e.title,e.category,[],[e.category],e.status]);
  await pool.query(
    `INSERT INTO encyclopedia_entries (topic_id,profession,slug,title,category,seo_title,seo_description,seo_keywords,overview,mechanism_physiology,clinical_relevance,signs_symptoms,assessment,management,complications,clinical_pearls,exam_pitfalls,faq_json,related_lesson_ids,related_question_ids,related_flashcard_ids,cross_profession_links,image_placeholders,status,published_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,NOW())
     ON CONFLICT (profession,slug) DO UPDATE SET title=EXCLUDED.title,category=EXCLUDED.category,seo_title=EXCLUDED.seo_title,seo_description=EXCLUDED.seo_description,seo_keywords=EXCLUDED.seo_keywords,overview=EXCLUDED.overview,mechanism_physiology=EXCLUDED.mechanism_physiology,clinical_relevance=EXCLUDED.clinical_relevance,signs_symptoms=EXCLUDED.signs_symptoms,assessment=EXCLUDED.assessment,management=EXCLUDED.management,complications=EXCLUDED.complications,clinical_pearls=EXCLUDED.clinical_pearls,exam_pitfalls=EXCLUDED.exam_pitfalls,faq_json=EXCLUDED.faq_json,status=EXCLUDED.status,updated_at=NOW()`,
    [t.rows[0].id,e.profession,e.slug,e.title,e.category,e.seoTitle,e.seoDescription,e.seoKeywords,e.overview,e.mechanismPhysiology,e.clinicalRelevance,e.signsSymptoms,e.assessment,e.management,e.complications,JSON.stringify(e.clinicalPearls),JSON.stringify(e.examPitfalls),JSON.stringify(e.faqJson),[],[e.category],[],JSON.stringify([]),JSON.stringify([]),e.status]);
}

const ENTRIES = [
  // ===== URINALYSIS =====
  E({ slug: "urine-sediment-examination", title: "Urine Sediment Examination (Microscopic)", category: "Urinalysis",
    seoTitle: "Urine Sediment Examination – MLT Encyclopedia", seoDescription: "Urine microscopy: RBCs, WBCs, bacteria, epithelial cells, formed elements for MLT exam.", seoKeywords: ["urine sediment", "urine microscopy", "RBCs", "WBCs", "epithelial cells", "MLT exam"],
    overview: "Microscopic examination of urine sediment identifies formed elements including red blood cells, white blood cells, epithelial cells, bacteria, yeast, casts, crystals, and other elements. It is performed on centrifuged urine using both low-power (10×) and high-power (40×) objectives with reduced light.",
    mechanismPhysiology: "Specimen preparation: centrifuge 10-12 mL of well-mixed urine at 400g (1,500 RPM) for 5 minutes. Decant supernatant, resuspend sediment in ~0.5 mL. Place one drop on slide with coverslip. Examine with reduced light (lowered condenser, partially closed iris diaphragm) to enhance contrast of transparent elements.",
    clinicalRelevance: "RBCs: hematuria (>3/HPF abnormal). Dysmorphic RBCs (acanthocytes) suggest glomerular origin. WBCs: pyuria (>5/HPF abnormal), usually neutrophils, indicate inflammation/infection. Bacteria: significant if accompanied by WBCs. Squamous epithelial cells: >5/LPF indicates contamination. Transitional epithelial cells: from renal pelvis/ureter/bladder. Renal tubular epithelial cells: from nephron tubules—clinically significant (ATN, transplant rejection, nephrotoxicity).",
    signsSymptoms: "Urine microscopy is a laboratory procedure that provides diagnostic information about renal and urinary tract pathology.",
    assessment: "Reporting: RBCs and WBCs per HPF (40×). Casts per LPF (10×). Bacteria, yeast, crystals: semiquantitative (rare, few, moderate, many). Key identifications: RBCs = small, round, biconcave, no nucleus (may be crenated in hypertonic or ghost in hypotonic urine). WBCs = larger than RBCs, granular cytoplasm, lobulated nucleus. Glitter cells = WBCs in hypotonic urine with Brownian movement of granules. Renal tubular epithelial cells (RTE): round/columnar, larger than WBCs, eccentric nucleus. Oval fat bodies: RTE filled with lipid droplets, Maltese cross pattern under polarized light (nephrotic syndrome).",
    management: "Correlate microscopic findings with dipstick results. Positive blood dipstick + no RBCs on micro = hemoglobinuria or myoglobinuria. Positive LE + no WBCs = lysed WBCs (alkaline or dilute urine). Standardized reporting using automated analyzers (UF-5000, iQ200) or manual methods.",
    complications: "Delayed analysis: cells lyse (especially in alkaline/dilute urine), casts dissolve, crystals may form artifactually from refrigeration. Over-centrifugation damages cells. Contamination: fecal material, vaginal secretions, talc/starch (Maltese cross—may mimic fat).",
    clinicalPearls: ["Dysmorphic RBCs (acanthocytes with membrane blebs) indicate GLOMERULAR hematuria", "Oval fat bodies with Maltese cross under polarized light = NEPHROTIC SYNDROME", "Squamous epithelial cells >5/LPF = contamination—specimen may need recollection"],
    examPitfalls: ["Reduce substage light to see transparent elements (hyaline casts, mucus)—bright light makes them invisible", "Crenated RBCs in concentrated urine may be confused with WBCs—RBCs are smaller and lack nuclei", "Talc/starch from gloves shows Maltese cross under polarized light—may be confused with lipid droplets"],
    faqJson: [{ question: "What are dysmorphic RBCs?", answer: "RBCs with irregular shapes, membrane blebs, and variable size (acanthocytes, Mickey Mouse shapes). They are damaged as they pass through the glomerular basement membrane, indicating glomerular disease rather than lower urinary tract bleeding." }, { question: "What are oval fat bodies?", answer: "Renal tubular epithelial cells that have absorbed lipid from the tubular filtrate. They contain cholesterol/lipid droplets that show a characteristic Maltese cross pattern under polarized light. They are pathognomonic for nephrotic syndrome." }]
  }),
  E({ slug: "urine-confirmatory-tests", title: "Urine Confirmatory Tests", category: "Urinalysis",
    seoTitle: "Urine Confirmatory Tests – MLT Encyclopedia", seoDescription: "SSA protein, Clinitest, Ictotest, urine confirmatory methods for MLT exam.", seoKeywords: ["SSA protein test", "Clinitest", "Ictotest", "urine confirmatory", "reducing substances", "MLT exam"],
    overview: "Urine confirmatory tests verify or supplement dipstick screening results. They are performed when dipstick results are unexpected, discordant with clinical findings, or when more specific analyte detection is needed. Key confirmatory tests include SSA for total protein, Clinitest for reducing substances, and Ictotest for bilirubin.",
    mechanismPhysiology: "Sulfosalicylic acid (SSA) precipitation: acid precipitates ALL proteins (albumin, globulins, Bence Jones protein, mucoproteins). Compare with dipstick protein (detects mainly albumin). SSA positive/dipstick negative = non-albumin proteinuria (Bence Jones/light chains). Clinitest (copper reduction): based on Benedict reaction—reduces copper sulfate to cuprous oxide by ANY reducing substance (glucose, galactose, fructose, lactose). NOT specific for glucose (unlike dipstick glucose oxidase). Used in neonatal screening for inborn errors of metabolism. Ictotest: more sensitive confirmatory test for bilirubin using diazo reaction on absorbent mat. 2,4-Dinitrophenylhydrazine (DNPH) test: screens for maple syrup urine disease (branched-chain keto acids).",
    clinicalRelevance: "SSA vs dipstick protein discrepancy: SSA positive, dipstick negative = Bence Jones protein (multiple myeloma, light chain disease). Both positive = albuminuria. False positive SSA: radiographic contrast dye, tolbutamide, high-dose penicillin. Clinitest 'pass-through': at very high glucose concentrations, the color passes through the endpoint and reads lower than actual (falsely low)—orange to green color progression that returns to lower reading.",
    signsSymptoms: "Confirmatory tests are laboratory procedures performed to verify or supplement screening results.",
    assessment: "SSA: add equal volume of 3% SSA to urine, grade turbidity (negative, trace, 1+ to 4+). Clinitest: 5 drops urine + 10 drops water + Clinitest tablet. Exothermic reaction produces color change proportional to reducing substances. Pass-through phenomenon: watch continuously during reaction. Ictotest: place drops of urine on absorbent mat, add Ictotest tablet—blue/purple color = positive bilirubin.",
    management: "Use confirmatory tests when: dipstick and microscopy are discordant, Bence Jones protein suspected, neonatal metabolic screening needed, bilirubin confirmation required.",
    complications: "Clinitest pass-through: must observe reaction continuously or will record falsely low result. SSA false positives from IV contrast dye (remains in urine 24-48 hours). Ictotest sensitivity: detects 0.05-0.1 mg/dL bilirubin (more sensitive than dipstick).",
    clinicalPearls: ["SSA detects ALL proteins; dipstick detects mainly ALBUMIN—discrepancy suggests Bence Jones protein (myeloma)", "Clinitest detects ALL REDUCING SUBSTANCES (glucose, galactose, lactose, fructose)—used for neonatal metabolic screening", "Clinitest PASS-THROUGH: orange color that fades back to green = very high concentration—must observe continuously"],
    examPitfalls: ["Dipstick glucose (glucose oxidase) is SPECIFIC for glucose; Clinitest detects ANY reducing substance—they have different purposes", "Radiographic contrast dye causes FALSE POSITIVE SSA protein—wait 24-48 hours after IV contrast", "Ictotest is MORE SENSITIVE for bilirubin than the dipstick pad"],
    faqJson: [{ question: "When is SSA testing clinically important?", answer: "When multiple myeloma is suspected. Bence Jones protein (free immunoglobulin light chains) is NOT detected by the dipstick protein pad (which detects albumin). SSA precipitates all proteins, so SSA positive with dipstick negative = non-albumin protein = suspect Bence Jones." }, { question: "What is the Clinitest pass-through phenomenon?", answer: "At very high glucose concentrations (>2 g/dL), the color reaction passes through the normal progression (blue→green→yellow→orange→brown) and returns to a lower color (green). If not observed continuously, the final reading appears falsely low. This is why the manufacturer instructions require continuous observation." }]
  }),

  // ===== IMMUNOLOGY =====
  E({ slug: "complement-system", title: "Complement System", category: "Immunology/Serology",
    seoTitle: "Complement System – MLT Encyclopedia", seoDescription: "Complement pathways: classical, alternative, lectin, CH50, C3, C4 for MLT exam.", seoKeywords: ["complement system", "classical pathway", "alternative pathway", "CH50", "C3", "C4", "MLT exam"],
    overview: "The complement system is a group of ~30 plasma proteins that function as an enzymatic cascade to enhance immune defense. Three activation pathways (classical, alternative, lectin) converge at C3 and lead to formation of the membrane attack complex (MAC, C5b-C9). Clinical laboratory tests include CH50, C3, and C4 levels.",
    mechanismPhysiology: "Classical pathway: activated by antigen-antibody complexes (IgG or IgM). C1q binds to Fc portion → activates C1r, C1s → C4 → C2 → C3 convertase (C4b2a). IgM is the most efficient complement activator (single molecule can activate). Alternative pathway: activated by microbial surfaces (LPS, zymosan), continuous low-level C3 hydrolysis (tick-over). C3 → Factor B → Factor D → C3 convertase (C3bBb). Lectin pathway: mannose-binding lectin (MBL) binds mannose on microbial surfaces → MASP-1, MASP-2 → C4 → C2 → same C3 convertase as classical. All pathways → C3 → C5 → MAC (C5b-9): pore formation in cell membrane → lysis.",
    clinicalRelevance: "CH50 (total hemolytic complement): measures CLASSICAL pathway—all components C1-C9 must be functional. AH50: measures ALTERNATIVE pathway. C3: shared by all pathways—decreased in active consumption. C4: CLASSICAL and LECTIN pathways only—decreased = classical pathway activation. Interpretation: low C3 + low C4 = classical pathway activation (SLE, immune complex disease). Low C3 + normal C4 = alternative pathway activation (membranoproliferative GN). Low CH50 (near zero) = complement deficiency.",
    signsSymptoms: "Complement deficiency: increased susceptibility to infections. C2 deficiency (most common): SLE-like syndrome. C3 deficiency: recurrent pyogenic infections. Terminal complement (C5-C9) deficiency: recurrent Neisseria infections. C1 esterase inhibitor deficiency: hereditary angioedema.",
    assessment: "CH50: patient serum + antibody-coated sheep RBCs → measure hemolysis (amount of complement needed to lyse 50% of sensitized RBCs). C3, C4: nephelometry or turbidimetry (quantitative). Specimen: serum, collected and stored properly (complement is heat-labile—inactivated at 56°C for 30 minutes). Transport at 4°C, test promptly.",
    management: "Monitor complement levels in SLE (C3, C4 decrease with disease activity). CH50 near zero: screen for complement component deficiency. Hereditary angioedema: C4 decreased (even between attacks), C1 esterase inhibitor decreased or dysfunctional.",
    complications: "Specimen handling critical: complement is heat-labile and degrades rapidly at room temperature → falsely decreased results. Hemolyzed specimens: C3 and C4 may be falsely elevated due to release from RBCs.",
    clinicalPearls: ["Low C3 + low C4 = CLASSICAL pathway activation (SLE, immune complex disease)", "Low C3 + normal C4 = ALTERNATIVE pathway activation", "Terminal complement (C5-C9) deficiency = recurrent NEISSERIA infections (meningococcal/gonococcal)"],
    examPitfalls: ["CH50 measures the CLASSICAL pathway (C1 through C9)—ALL components must be functional for a normal result", "Complement is HEAT-LABILE—improper specimen handling (room temperature) causes falsely decreased results", "C1 esterase inhibitor deficiency (hereditary angioedema): C4 is ALWAYS low, even between attacks—screening test"],
    faqJson: [{ question: "Why is IgM a better complement activator than IgG?", answer: "IgM is a pentamer—a single IgM molecule provides multiple Fc regions for C1q binding (C1q needs at least two Fc regions). IgG is a monomer—at least two IgG molecules must be close together for C1q binding, which is less efficient." }, { question: "What is the membrane attack complex?", answer: "MAC (C5b-C9) forms a transmembrane pore in the target cell membrane. C5b initiates assembly, C6-C8 insert into the membrane, and multiple C9 molecules polymerize to form the complete pore. This allows ions and water to enter, causing osmotic lysis." }]
  }),
  E({ slug: "immunoglobulin-classes", title: "Immunoglobulin Classes", category: "Immunology/Serology",
    seoTitle: "Immunoglobulin Classes – MLT Encyclopedia", seoDescription: "IgG, IgM, IgA, IgD, IgE: structure, function, and clinical significance for MLT exam.", seoKeywords: ["immunoglobulins", "IgG", "IgM", "IgA", "IgE", "antibody classes", "MLT exam"],
    overview: "Immunoglobulins (antibodies) are glycoproteins produced by plasma cells in response to antigenic stimulation. Five classes are defined by heavy chain type: IgG (gamma), IgM (mu), IgA (alpha), IgD (delta), and IgE (epsilon). Each has distinct structure, function, and clinical significance.",
    mechanismPhysiology: "Basic antibody structure: two heavy chains + two light chains (kappa or lambda) linked by disulfide bonds. Each chain has variable (V) and constant (C) regions. Fab region: antigen binding (variable). Fc region: effector function (complement activation, receptor binding, placental transfer). IgG: monomer, most abundant (75-80%), 4 subclasses (IgG1-4), crosses placenta (ONLY Ig that crosses placenta—provides passive immunity to newborn), fixes complement (IgG1, IgG3), long half-life (23 days). IgM: pentamer (largest Ig), first antibody produced in primary immune response, most efficient complement activator, does NOT cross placenta, has 10 antigen-binding sites. IgA: dimer in secretions (secretory IgA—sIgA), monomer in serum, most abundant Ig in secretions (tears, saliva, breast milk, GI/respiratory mucosa), does NOT fix complement. IgD: monomer, trace amounts in serum, surface receptor on mature B cells. IgE: monomer, lowest serum concentration, binds to mast cells and basophils via Fc receptor, mediates type I (immediate) hypersensitivity and allergic reactions, elevated in parasitic infections.",
    clinicalRelevance: "Primary immune response: IgM appears first (peaks at 1-2 weeks), then class switching to IgG (peaks at 4-6 weeks). IgM = acute/recent infection. IgG = past infection/immunity. Selective IgA deficiency: most common primary immunodeficiency (1:500). Patients may have anti-IgA antibodies → anaphylaxis with IgA-containing blood products. Hyper-IgE syndrome: extremely elevated IgE, recurrent staphylococcal abscesses. IgG subclass deficiency: recurrent sinopulmonary infections despite normal total IgG.",
    signsSymptoms: "Immunodeficiency: recurrent infections. Allergic disorders (IgE): allergic rhinitis, asthma, anaphylaxis. IgA deficiency: may be asymptomatic or have recurrent mucosal infections.",
    assessment: "Quantitative immunoglobulins: nephelometry (IgG, IgA, IgM). Serum protein electrophoresis: polyclonal vs monoclonal pattern. Immunofixation: identifies monoclonal Ig class. Total IgE: immunoassay (elevated in allergies, parasites). Specific IgE: ImmunoCAP (replaces RAST—quantifies allergen-specific IgE for allergy testing).",
    management: "IgG replacement therapy: for primary immunodeficiency (IVIG or subcutaneous Ig). IgA deficiency: use IgA-depleted or washed blood products. Allergic disease: allergen-specific IgE testing guides immunotherapy.",
    complications: "Anaphylaxis in IgA-deficient patients receiving IgA-containing products. Transient hypogammaglobulinemia of infancy: maternal IgG wanes before infant's IgG production matures (nadir at 3-6 months).",
    clinicalPearls: ["IgG is the ONLY immunoglobulin that crosses the placenta—provides passive immunity to newborns", "IgM is the LARGEST immunoglobulin (pentamer) and the FIRST produced in primary immune response", "IgA is the predominant immunoglobulin in SECRETIONS (tears, saliva, breast milk, mucosa)"],
    examPitfalls: ["IgA-deficient patients may have ANTI-IgA antibodies—can cause ANAPHYLAXIS with IgA-containing blood products", "IgE is the LEAST abundant immunoglobulin in serum but mediates TYPE I (immediate) hypersensitivity", "Transient hypogammaglobulinemia of infancy: physiologic nadir at 3-6 months as maternal IgG wanes"],
    faqJson: [{ question: "Why is IgM the best complement activator?", answer: "IgM is a pentamer with multiple Fc regions. C1q of the classical complement pathway requires binding to at least two Fc regions to be activated. A single IgM molecule provides these, whereas multiple IgG molecules (monomers) must be in close proximity." }, { question: "What is secretory IgA?", answer: "Secretory IgA (sIgA) is a dimer of two IgA molecules joined by J chain and wrapped with secretory component (produced by epithelial cells). The secretory component protects sIgA from proteolytic digestion in mucosal environments. It provides first-line immune defense at mucosal surfaces." }]
  }),
  E({ slug: "hypersensitivity-reactions", title: "Hypersensitivity Reactions", category: "Immunology/Serology",
    seoTitle: "Hypersensitivity Reactions – MLT Encyclopedia", seoDescription: "Type I-IV hypersensitivity: IgE-mediated, cytotoxic, immune complex, delayed for MLT exam.", seoKeywords: ["hypersensitivity", "type I", "type II", "type III", "type IV", "anaphylaxis", "MLT exam"],
    overview: "Hypersensitivity reactions are exaggerated or inappropriate immune responses that cause tissue damage. Gell and Coombs classified four types: Type I (immediate/anaphylactic), Type II (cytotoxic/antibody-mediated), Type III (immune complex), and Type IV (delayed-type/cell-mediated). Types I-III are antibody-mediated; Type IV is cell-mediated (T lymphocytes).",
    mechanismPhysiology: "Type I (Immediate): IgE binds to mast cell/basophil Fc receptors → re-exposure to allergen → cross-linking of IgE → degranulation → histamine, leukotrienes, prostaglandins release. Occurs within minutes. Type II (Cytotoxic): IgG or IgM antibodies bind to cell surface antigens → complement activation and/or ADCC → cell destruction. Type III (Immune Complex): antigen-antibody complexes deposit in tissues → complement activation → neutrophil recruitment → tissue damage. Type IV (Delayed): sensitized T cells (CD4+ Th1) release cytokines upon re-exposure → macrophage activation → granuloma formation. Occurs 48-72 hours after exposure.",
    clinicalRelevance: "Type I: anaphylaxis, allergic rhinitis, asthma, urticaria, food allergy, drug allergy. Type II: transfusion reactions (ABO incompatibility), HDFN (Rh incompatibility), autoimmune hemolytic anemia, Goodpasture syndrome, myasthenia gravis, Graves disease. Type III: SLE (DNA-anti-DNA complexes), serum sickness, post-streptococcal GN, Arthus reaction. Type IV: TB skin test (PPD/Mantoux), contact dermatitis (poison ivy), transplant rejection (acute cellular), granulomatous diseases (sarcoidosis, TB).",
    signsSymptoms: "Type I: urticaria, angioedema, bronchospasm, anaphylactic shock (minutes). Type II: hemolysis, cytopenias (hours). Type III: vasculitis, glomerulonephritis, arthritis (4-10 days for serum sickness). Type IV: induration at skin test site, contact dermatitis rash (48-72 hours).",
    assessment: "Type I: total IgE, specific IgE (ImmunoCAP), skin prick testing, tryptase (mast cell degranulation marker). Type II: DAT, IAT, antibody identification. Type III: C3, C4, CH50 (consumed), immune complex assays. Type IV: PPD/Mantoux skin test (read induration at 48-72 hours), interferon-gamma release assays (IGRA—QuantiFERON), patch testing for contact allergens.",
    management: "Type I: epinephrine (anaphylaxis), antihistamines, corticosteroids, allergen avoidance, immunotherapy. Type II: remove offending antigen/antibody (stop transfusion, discontinue drug). Type III: treat underlying cause, anti-inflammatory therapy. Type IV: remove allergen, corticosteroids.",
    complications: "Type I: anaphylactic shock (life-threatening, minutes). Type II: fatal hemolytic transfusion reaction. Type III: chronic immune complex deposition → organ damage. Type IV: granuloma formation, tissue fibrosis.",
    clinicalPearls: ["Types I-III are ANTIBODY-mediated; Type IV is CELL-mediated (T lymphocytes)—only type not involving antibodies", "Type I is the FASTEST (minutes); Type IV is the SLOWEST (48-72 hours)", "PPD/Mantoux test is the classic example of Type IV hypersensitivity—read at 48-72 hours, measure INDURATION not erythema"],
    examPitfalls: ["Transfusion reactions involve MULTIPLE types: acute hemolytic = Type II; allergic = Type I; febrile = cytokine-mediated (not classic hypersensitivity)", "PPD test: measure INDURATION (firm swelling), NOT erythema (redness)—erythema alone is not positive", "Goodpasture syndrome is Type II (anti-GBM antibodies) but SLE nephritis is Type III (immune complex deposition)"],
    faqJson: [{ question: "What is the key difference between types?", answer: "Type I: IgE + mast cells (minutes). Type II: IgG/IgM + cell surface antigens (hours). Type III: immune complexes + complement (days). Type IV: T cells + macrophages (48-72 hours). I-III = antibody; IV = cell-mediated." }, { question: "Why is tryptase measured in anaphylaxis?", answer: "Tryptase is a mast cell granule enzyme released during degranulation. Elevated serum tryptase (peaks 1-2 hours post-event) confirms mast cell activation and supports the diagnosis of anaphylaxis versus other causes of shock." }]
  }),

  // ===== LAB SAFETY =====
  E({ slug: "laboratory-accreditation-regulation", title: "Laboratory Accreditation and Regulation", category: "Lab Safety & Quality Control",
    seoTitle: "Lab Accreditation – MLT Encyclopedia", seoDescription: "CLIA, CAP, Joint Commission, proficiency testing, quality management for MLT exam.", seoKeywords: ["CLIA", "CAP", "accreditation", "proficiency testing", "quality management", "MLT exam"],
    overview: "Clinical laboratories in the United States must comply with CLIA (Clinical Laboratory Improvement Amendments of 1988) to perform patient testing. Accreditation by organizations such as CAP (College of American Pathologists), The Joint Commission, or state agencies provides deemed status for CLIA compliance. Quality management encompasses all aspects of laboratory operations.",
    mechanismPhysiology: "CLIA categorizes tests by complexity: waived (simple tests, minimal risk—glucose meters, rapid strep, urine dipstick), moderate complexity, and high complexity. Waived tests require a CLIA certificate of waiver. Moderate and high complexity require: qualified personnel, QC, QA, proficiency testing, and ongoing competency assessment. Personnel requirements: laboratory director (MD/DO with board certification or PhD), technical supervisor, general supervisor, testing personnel.",
    clinicalRelevance: "Proficiency testing (PT): external quality assessment. PT samples analyzed like patient specimens—results graded against peer group or target values. Unsatisfactory performance = 2 consecutive or 2 of 3 events for a single analyte. Unsuccessful PT can lead to sanctions, suspension, or revocation of CLIA certificate. PT samples must NEVER be referred to another laboratory (grounds for immediate revocation). CAP accreditation: voluntary but provides deemed status for CMS/CLIA compliance. Biennial inspection of laboratory operations.",
    signsSymptoms: "Accreditation and regulation are laboratory management processes with no patient symptoms.",
    assessment: "Quality management systems: document control, personnel qualifications, method validation (accuracy, precision, linearity, reportable range, reference range verification), QC (internal controls), QA (quality assessment—monitors, indicators, corrective actions), competency assessment (6 elements, annually). Six elements of competency assessment: direct observation, monitoring recording/reporting, review of QC/PT/QA, test of problem-solving, evaluation of specimen handling, written examination.",
    management: "CLIA inspection: every 2 years (or CAP inspection for deemed status). Proficiency testing: 3 events per year, 5 challenges per event for regulated analytes. Document retention: 2 years for most records, 10 years for immunohematology, 5 years for pathology slides. Corrective action required for any QC failure, PT failure, or quality indicator out of range.",
    complications: "PT referral to another lab: immediate CLIA certificate revocation. Unsatisfactory PT: remedial action, possible sanctions. Non-compliance with personnel standards: civil money penalties. Failure to perform QC: endangers patient safety and accreditation.",
    clinicalPearls: ["PT samples must NEVER be referred to another laboratory—grounds for IMMEDIATE CLIA certificate revocation", "CLIA waived tests are NOT exempt from manufacturer instructions—labs must follow package insert directions", "Competency assessment has 6 elements and must be performed 2× in the first year, then ANNUALLY"],
    examPitfalls: ["Waived tests still require a CLIA certificate of waiver—they are NOT unregulated", "Unsatisfactory PT = 2 consecutive failures OR 2 of 3 events—triggers remedial action", "CAP accreditation is VOLUNTARY but provides deemed status for CLIA—most hospitals are CAP-accredited"],
    faqJson: [{ question: "What is deemed status?", answer: "When a laboratory is accredited by a CMS-approved accreditation organization (CAP, Joint Commission, COLA), it is 'deemed' to meet CLIA requirements. This means the accrediting organization's inspection substitutes for a CMS/state inspection for CLIA compliance." }, { question: "Why is PT referral prohibited?", answer: "PT samples must be tested using the laboratory's routine methods and personnel. Referring PT samples to another lab defeats the purpose of proficiency testing (which is to assess YOUR laboratory's performance). CLIA specifically prohibits this practice with immediate certificate revocation as the penalty." }]
  }),
  E({ slug: "method-validation", title: "Method Validation and Verification", category: "Lab Safety & Quality Control",
    seoTitle: "Method Validation – MLT Encyclopedia", seoDescription: "Accuracy, precision, linearity, reference range verification for MLT exam.", seoKeywords: ["method validation", "accuracy", "precision", "linearity", "reference range", "MLT exam"],
    overview: "Method validation confirms that a test system performs as expected for its intended use. FDA-cleared (modified) methods require verification; laboratory-developed tests (LDTs) require full validation. Key parameters include accuracy, precision (within-run and between-run), linearity (analytical measurement range), detection limits, reference range verification, and interference studies.",
    mechanismPhysiology: "Accuracy: closeness of measured value to true value. Assessed by: comparison with reference method, certified reference materials, or PT/EQA programs. Precision: closeness of repeated measurements to each other (reproducibility). Within-run (repeatability): same sample, same run. Between-run (reproducibility): same sample, different runs/days. Expressed as coefficient of variation (CV% = SD/mean × 100). Linearity: ability to produce results proportional to analyte concentration across the reportable range. Verified by testing serial dilutions of high-concentration material. Analytical sensitivity (LOD): lowest concentration reliably detected (above background). Functional sensitivity (LOQ): lowest concentration meeting predefined precision criteria.",
    clinicalRelevance: "Verification (FDA-cleared method): confirm manufacturer's claims for accuracy, precision, and reportable range in YOUR laboratory with YOUR patient population. Validation (LDT or modified method): establish ALL performance characteristics de novo. Reference range verification: test 20 specimens from representative healthy population—if 18/20 (90%) fall within manufacturer's range, it is verified. If not, establish your own range (requires 120+ specimens).",
    signsSymptoms: "Method validation is a laboratory management process with no patient symptoms.",
    assessment: "Accuracy study: minimum 40 patient samples compared with reference/comparative method. Calculate correlation coefficient (r), slope, y-intercept (Deming or Passing-Bablok regression), and bias. Precision study: CLSI EP15—minimum 5 days, 5 replicates per day, 2 levels. Calculate within-run and between-run CV%. Linearity study: CLSI EP06—minimum 5 concentrations spanning reportable range, polynomial regression. Interference study: evaluate common interferents (hemolysis, icterus, lipemia, common drugs).",
    management: "Document everything. Director review and approval before patient testing. Ongoing quality monitoring: QC, PT, delta checks, correlation with clinical findings. Revalidation required for: method changes, reagent lot changes (abbreviated), instrument replacement.",
    complications: "Inadequate validation: erroneous patient results leading to misdiagnosis/mistreatment. Reference range transfer without verification: may not represent local patient population. Linearity failure at extremes: unreported results outside validated range.",
    clinicalPearls: ["VERIFICATION = confirm manufacturer's claims (FDA-cleared methods); VALIDATION = establish performance de novo (LDTs)", "Reference range verification: 20 specimens, 18/20 (90%) must fall within manufacturer's range", "CV% (coefficient of variation) = SD/mean × 100—the standard measure of analytical precision"],
    examPitfalls: ["Accuracy ≠ precision: a method can be precise (reproducible) but inaccurate (wrong answer consistently)", "Reference range verification requires only 20 specimens; ESTABLISHING a new range requires 120+ specimens", "Correlation coefficient (r) close to 1.0 indicates linear relationship but does NOT prove agreement—must also assess bias (slope and y-intercept)"],
    faqJson: [{ question: "Accuracy vs precision?", answer: "Accuracy = closeness to the true value (low bias). Precision = closeness of repeated measurements to each other (low random error/CV). A method can be precise but inaccurate (systematic bias), or accurate on average but imprecise (high scatter). The ideal method is both accurate and precise." }, { question: "What is the difference between verification and validation?", answer: "Verification confirms that an FDA-cleared method performs to the manufacturer's stated specifications in your laboratory. Validation establishes all performance characteristics (accuracy, precision, linearity, LOD, LOQ, interferences, reference range) from scratch—required for laboratory-developed tests and significantly modified methods." }]
  }),

  // ===== MOLECULAR DIAGNOSTICS =====
  E({ slug: "flow-cytometry-principles", title: "Flow Cytometry Principles", category: "Molecular Diagnostics",
    seoTitle: "Flow Cytometry – MLT Encyclopedia", seoDescription: "Flow cytometry: fluorescent markers, CD markers, scatter properties for MLT exam.", seoKeywords: ["flow cytometry", "CD markers", "fluorescence", "immunophenotyping", "forward scatter", "side scatter", "MLT exam"],
    overview: "Flow cytometry is an analytical technique that measures physical and chemical characteristics of cells or particles as they flow in a fluid stream past laser(s). It simultaneously measures forward scatter (size), side scatter (granularity/internal complexity), and multiple fluorescent markers (surface/intracellular antigens labeled with fluorochrome-conjugated antibodies). It is essential for immunophenotyping leukemias/lymphomas, HIV CD4 counting, DNA ploidy, and stem cell enumeration.",
    mechanismPhysiology: "Components: fluidics system (hydrodynamic focusing—cells pass single-file through laser), optics system (laser excitation, dichroic mirrors/filters separate emission wavelengths), electronics (photomultiplier tubes convert light to electrical signals, digitized for analysis). Forward scatter (FSC): proportional to cell SIZE (larger cells = more forward scatter). Side scatter (SSC): proportional to GRANULARITY/internal complexity (more granular = more side scatter). Fluorescence: fluorochrome-conjugated monoclonal antibodies bind specific CD (cluster of differentiation) antigens. Different fluorochromes emit at different wavelengths, allowing multicolor analysis.",
    clinicalRelevance: "Leukemia/lymphoma immunophenotyping: distinguishes AML from ALL, B-cell from T-cell, identifies specific subtypes. Myeloid markers: CD13, CD33, CD117, MPO. B-lymphoid: CD10, CD19, CD20, CD22. T-lymphoid: CD2, CD3, CD5, CD7. Monocytic: CD14, CD64. Stem cell: CD34. HIV monitoring: CD4 T-cell count (<200 cells/μL = AIDS-defining). DNA content analysis: ploidy and S-phase fraction in tumors. Paroxysmal nocturnal hemoglobinuria (PNH): absence of GPI-anchored proteins (CD55, CD59) on RBCs and WBCs. Stem cell enumeration: CD34+ cells for transplant.",
    signsSymptoms: "Flow cytometry is a laboratory analytical technique. Results guide diagnosis and treatment of hematologic malignancies and immune disorders.",
    assessment: "WBC populations by scatter: lymphocytes (low FSC, low SSC), monocytes (intermediate FSC, intermediate SSC), granulocytes (high FSC, high SSC). Gating: selecting cell populations for analysis based on scatter or marker expression. Compensation: correcting for spectral overlap between fluorochromes. Isotype controls: negative controls that match the fluorochrome and Ig class of test antibodies.",
    management: "Specimen: EDTA blood, bone marrow, CSF, body fluids. Specimens should be processed within 24-48 hours. Viability assessment: PI (propidium iodide) or 7-AAD staining excludes dead cells. Data analysis: dot plots, histograms, contour plots. Gating strategy defines populations of interest.",
    complications: "Non-specific binding: use isotype controls and Fc blocking. Dead cells bind antibodies non-specifically—exclude with viability dyes. Sample degradation with time: process promptly. Compensation errors: incorrect spectral overlap correction leads to false positive/negative markers.",
    clinicalPearls: ["Forward scatter = SIZE; Side scatter = GRANULARITY/internal complexity", "CD4 count <200 cells/μL = AIDS-defining immunosuppression", "PNH diagnosis: absence of GPI-anchored proteins (CD55, CD59) by flow cytometry—FLAER is the most sensitive"],
    examPitfalls: ["Flow cytometry immunophenotyping is the definitive method for classifying leukemia as myeloid or lymphoid", "Compensation corrects for SPECTRAL OVERLAP between fluorochromes—not for autofluorescence", "Dead cells stain non-specifically—always use viability dye to exclude them from analysis"],
    faqJson: [{ question: "How does forward vs side scatter work?", answer: "Forward scatter (FSC) measures light scattered in the forward direction, proportional to cell SIZE. Side scatter (SSC) measures light scattered at 90°, proportional to GRANULARITY and internal complexity. Together they create a scatter plot that separates lymphocytes (small, agranular), monocytes (medium, some granules), and granulocytes (large, very granular)." }, { question: "What is immunophenotyping?", answer: "Using fluorochrome-conjugated monoclonal antibodies against CD antigens to identify cell lineage, maturation stage, and aberrant antigen expression. Essential for classifying leukemias (AML vs ALL, B vs T), detecting minimal residual disease, and identifying PNH, among other applications." }]
  }),

  // ===== PARASITOLOGY =====
  E({ slug: "blood-parasites", title: "Blood Parasites", category: "Parasitology",
    seoTitle: "Blood Parasites – MLT Encyclopedia", seoDescription: "Babesia, Trypanosoma, Leishmania, microfilaria: blood smear identification for MLT exam.", seoKeywords: ["blood parasites", "Babesia", "Trypanosoma", "Leishmania", "microfilaria", "MLT exam"],
    overview: "Blood parasites include protozoa and helminths (microfilariae) that circulate in the bloodstream. Key species: Plasmodium (malaria), Babesia (babesiosis), Trypanosoma (sleeping sickness, Chagas disease), Leishmania (leishmaniasis), and filarial worms (Wuchereria, Brugia). Diagnosis relies on examination of thick and thin blood smears stained with Giemsa.",
    mechanismPhysiology: "Babesia: intraerythrocytic protozoan transmitted by Ixodes tick (same tick as Lyme disease). Resembles Plasmodium rings but forms distinctive Maltese cross (tetrad) pattern. No pigment (hemozoin)—unlike Plasmodium. Trypanosoma brucei: extracellular flagellated protozoan in blood (trypomastigote form), transmitted by tsetse fly (African sleeping sickness). T. cruzi: causes Chagas disease (American trypanosomiasis), transmitted by reduviid (kissing) bug, intracellular amastigotes in tissue. Leishmania: intracellular amastigotes in macrophages (no flagellum in tissue form—amastigote = Leishman-Donovan body), transmitted by sandfly. Microfilariae: larval stage of filarial worms in blood, sheathed (Wuchereria, Brugia) or unsheathed (Mansonella), collected with nocturnal periodicity (W. bancrofti, B. malayi).",
    clinicalRelevance: "Babesia: can be coinfected with Borrelia (Lyme) from same Ixodes tick. Asplenic patients at highest risk for severe disease. Babesia does NOT produce hemozoin pigment (differentiator from Plasmodium). T. cruzi (Chagas): screening required for blood donors in US. Chronic Chagas: cardiomyopathy, megaesophagus, megacolon. Microfilariae: nocturnal periodicity—blood collection must be timed (10 PM - 2 AM for W. bancrofti).",
    signsSymptoms: "Babesia: fever, hemolytic anemia, dark urine, hepatosplenomegaly (asplenic patients: severe). African trypanosomiasis: Winterbottom sign (posterior cervical lymphadenopathy), CNS invasion (sleeping sickness). Chagas: Romaña sign (unilateral periorbital edema), acute myocarditis. Filariasis: lymphedema, elephantiasis (chronic Wuchereria).",
    assessment: "Thick and thin Giemsa-stained blood smears (same as malaria). Babesia: intra-erythrocytic ring forms, Maltese cross (tetrad) pathognomonic, NO hemozoin pigment, extracellular merozoites may be seen. Multiple rings per RBC common (like P. falciparum). T. brucei: trypomastigotes in blood (C or S shaped, undulating membrane, posterior kinetoplast). T. cruzi: trypomastigotes in blood (C shaped), intracellular amastigotes in tissue (heart muscle). Leishmania: amastigotes (Leishman-Donovan bodies) in macrophages on bone marrow or splenic aspirate. Microfilariae: wet blood film or Giemsa-stained thick smear, membrane filtration technique (most sensitive).",
    management: "Babesia: atovaquone + azithromycin (mild), clindamycin + quinine (severe), exchange transfusion for high parasitemia (>10%) or severe disease. African trypanosomiasis: suramin or pentamidine (early stage), melarsoprol or eflornithine (CNS involvement). Chagas: benznidazole. Filariasis: diethylcarbamazine (DEC).",
    complications: "Babesia: severe hemolytic anemia, ARDS, renal failure, death (especially asplenic patients). Chagas: chronic cardiomyopathy (leading cause of infectious cardiomyopathy in Latin America). Filariasis: chronic lymphedema/elephantiasis.",
    clinicalPearls: ["Babesia Maltese cross (tetrad) is PATHOGNOMONIC—distinguishes from Plasmodium", "Babesia has NO hemozoin pigment (unlike Plasmodium)—key differentiator", "Microfilariae of W. bancrofti have NOCTURNAL periodicity—collect blood between 10 PM and 2 AM"],
    examPitfalls: ["Babesia resembles P. falciparum (multiple rings per RBC)—look for Maltese cross and ABSENCE of hemozoin", "Trypanosoma cruzi blood donors must be SCREENED in the US—Chagas is a transfusion-transmitted infection", "Leishmania amastigotes (Leishman-Donovan bodies) are intracellular in MACROPHAGES—not in RBCs"],
    faqJson: [{ question: "How is Babesia differentiated from Plasmodium on blood smear?", answer: "Babesia: Maltese cross (tetrad) pattern pathognomonic, NO hemozoin pigment, extracellular merozoites, no schizonts/gametocytes, ring forms may resemble P. falciparum. Plasmodium: hemozoin pigment present, species-specific morphology (schizonts, gametocytes), no Maltese cross." }, { question: "Why is nocturnal blood collection important for filariasis?", answer: "W. bancrofti and B. malayi microfilariae exhibit nocturnal periodicity—they are present in peripheral blood at highest numbers between 10 PM and 2 AM, retreating to deep capillaries during the day. Daytime collection may miss the diagnosis." }]
  }),

  // ===== MYCOLOGY =====
  E({ slug: "cryptococcus-neoformans", title: "Cryptococcus neoformans", category: "Mycology",
    seoTitle: "Cryptococcus neoformans – MLT Encyclopedia", seoDescription: "Cryptococcus: India ink, CrAg, encapsulated yeast, meningitis for MLT exam.", seoKeywords: ["Cryptococcus neoformans", "cryptococcal meningitis", "India ink", "CrAg", "encapsulated yeast", "MLT exam"],
    overview: "Cryptococcus neoformans is an encapsulated yeast that causes life-threatening meningitis in immunocompromised patients, particularly those with advanced HIV/AIDS (CD4 <100 cells/μL). It is found worldwide in pigeon droppings and soil. The polysaccharide capsule is the major virulence factor.",
    mechanismPhysiology: "Thick polysaccharide capsule: antiphagocytic (inhibits phagocytosis), inhibits complement activation, suppresses T cell immunity. Capsule visualized by India ink (negative staining—capsule appears as clear halo against dark background). Melanin production: phenoloxidase converts catecholamines to melanin (protects against oxidative killing). Urease positive. Narrow-based budding (unlike Blastomyces which has BROAD-based budding).",
    clinicalRelevance: "Cryptococcal meningitis: most common form of fungal meningitis, second most common opportunistic infection in AIDS globally. CSF findings: elevated opening pressure (hallmark), mild lymphocytic pleocytosis (may be minimal in AIDS), mildly elevated protein, decreased glucose. India ink: 50% sensitivity (many false negatives in early disease). Cryptococcal antigen (CrAg): >95% sensitivity and specificity (latex agglutination or lateral flow assay)—test of choice.",
    signsSymptoms: "Meningitis: headache, fever, neck stiffness, altered mental status, cranial nerve palsies. May present insidiously over weeks. Pulmonary: may be asymptomatic or pneumonia-like. Skin: papules, nodules, may resemble molluscum contagiosum in AIDS patients.",
    assessment: "CSF analysis: elevated opening pressure (frequently >25 cm H2O), mild lymphocytic pleocytosis (may be absent in AIDS), mildly elevated protein, decreased glucose. India ink: negative staining of CSF—encapsulated yeast with wide clear halo (50% sensitivity). CrAg (serum and CSF): >95% sensitive—recommended as initial test. Titer correlates with disease burden and monitors treatment. Culture: SDA (grows at 37°C, unlike most environmental yeasts), bird seed (niger seed/Staib) agar—brown colonies due to melanin production. Mucicicarmine stain: stains capsule red/magenta (tissue sections).",
    management: "Induction: amphotericin B + flucytosine (5-FC) × 2 weeks. Consolidation: fluconazole × 8 weeks. Maintenance: fluconazole (lifelong or until immune reconstitution). Serial lumbar punctures to manage elevated intracranial pressure. ART initiation delayed 4-6 weeks (to prevent IRIS).",
    complications: "Elevated intracranial pressure: most significant complication (repeated therapeutic LP or VP shunt). Immune reconstitution inflammatory syndrome (IRIS) with ART initiation. Relapse if maintenance therapy discontinued before immune recovery. Mortality remains 20-30% despite treatment in resource-limited settings.",
    clinicalPearls: ["India ink is only 50% sensitive; CrAg (latex/LFA) is >95% sensitive—CrAg is the preferred diagnostic test", "Cryptococcus produces NARROW-based budding; Blastomyces produces BROAD-based budding", "Bird seed (niger seed) agar: brown colonies due to MELANIN production—differentiates from other yeasts"],
    examPitfalls: ["Cryptococcus is INHIBITED by cycloheximide in selective media (Mycosel)—use plain SDA", "1,3-beta-D-glucan (BDG) is NOT elevated in Cryptococcus (capsule lacks beta-glucan)—CrAg is the marker", "Mucicarmine stains the CAPSULE red—used in tissue sections for histologic diagnosis"],
    faqJson: [{ question: "India ink vs CrAg for diagnosis?", answer: "India ink has only 50% sensitivity (negative stain—visualizes capsule but misses low-burden infections). CrAg (cryptococcal antigen by latex agglutination or lateral flow) has >95% sensitivity and specificity. CrAg is the recommended initial diagnostic test. India ink is supplementary." }, { question: "Why is elevated intracranial pressure so important?", answer: "Cryptococcal polysaccharide capsule and yeast cells obstruct CSF drainage through arachnoid granulations, causing elevated pressure. This is the major cause of morbidity and mortality. Serial therapeutic lumbar punctures (removing 20-30 mL CSF) are essential for pressure management." }]
  }),

  // ===== BODY FLUIDS =====
  E({ slug: "amniotic-fluid-analysis", title: "Amniotic Fluid Analysis", category: "Body Fluids",
    seoTitle: "Amniotic Fluid Analysis – MLT Encyclopedia", seoDescription: "Amniotic fluid: L/S ratio, lamellar body count, fetal lung maturity for MLT exam.", seoKeywords: ["amniotic fluid", "L/S ratio", "fetal lung maturity", "lamellar body count", "bilirubin", "MLT exam"],
    overview: "Amniotic fluid analysis evaluates fetal lung maturity (FLM), hemolytic disease severity, chromosomal abnormalities, and neural tube defects. Fetal lung maturity testing is performed before planned early delivery to assess the risk of respiratory distress syndrome (RDS).",
    mechanismPhysiology: "Fetal lung maturity: type II pneumocytes produce surfactant (phospholipids that reduce alveolar surface tension, preventing collapse). Lecithin (phosphatidylcholine) increases dramatically after 35 weeks gestation. Sphingomyelin remains relatively constant. L/S ratio ≥2.0 indicates mature lungs. Phosphatidylglycerol (PG): appears after 35 weeks—presence confirms maturity (PG is NOT affected by blood or meconium contamination). Lamellar body count: lamellar bodies are surfactant-containing organelles secreted by type II pneumocytes. Counted by automated hematology analyzer (platelet channel). Count ≥50,000/μL = mature lungs.",
    clinicalRelevance: "Fetal lung maturity tests: L/S ratio ≥2.0 (thin-layer chromatography—labor-intensive), PG presence (rapid, unaffected by blood/meconium), lamellar body count ≥50,000 (automated, rapid, widely available—most commonly used). Bilirubin in amniotic fluid (ΔOD 450): assesses severity of hemolytic disease of the fetus (HDFN/Rh incompatibility). Liley chart plots ΔOD 450 against gestational age into zones I (mild), II (moderate), III (severe—indicates need for intervention). AFP in amniotic fluid: elevated in neural tube defects (spina bifida, anencephaly). Acetylcholinesterase (AChE): confirms open neural tube defect.",
    signsSymptoms: "Amniotic fluid analysis is a prenatal diagnostic procedure. Fetal lung immaturity leads to neonatal RDS (respiratory distress syndrome).",
    assessment: "Collection: amniocentesis (ultrasound-guided). Specimen handling: protect from light for bilirubin analysis (bilirubin is photosensitive). L/S ratio: lipid extraction → TLC → densitometry. PG: TLC or rapid immunoassay (Amniostat-FLM). Lamellar body count: mix well (lamellar bodies settle), run on platelet channel of hematology analyzer. ΔOD 450: spectrophotometric scan 350-550nm, measure deviation from linearity at 450nm (bilirubin absorbance peak). Contamination: blood elevates L/S ratio (blood contains lecithin); meconium elevates ΔOD 450 and interferes with L/S ratio.",
    management: "FLM testing guides delivery timing: mature → safe to deliver; immature → delay delivery, administer antenatal corticosteroids (betamethasone) to accelerate surfactant production. ΔOD 450 in zone III: consider intrauterine transfusion or early delivery.",
    complications: "Amniocentesis risks: premature labor, infection, fetal injury (rare). Blood contamination: falsely increases L/S ratio. Meconium contamination: interferes with multiple tests. Photodegradation: bilirubin degrades in light → falsely low ΔOD 450.",
    clinicalPearls: ["L/S ratio ≥2.0 = mature lungs; PG PRESENCE confirms maturity and is NOT affected by blood or meconium", "Lamellar body count is the most commonly used FLM test today—rapid, automated, widely available", "ΔOD 450 measures BILIRUBIN to assess HDFN severity—protect specimen from LIGHT"],
    examPitfalls: ["Blood contamination FALSELY ELEVATES L/S ratio (blood contains lecithin)—PG is not affected", "Diabetic mothers: lung maturity may be DELAYED—L/S ratio ≥2.0 may NOT be reliable (PG presence required)", "Bilirubin at 450nm is PHOTOSENSITIVE—specimen must be protected from light during transport and analysis"],
    faqJson: [{ question: "What is the L/S ratio?", answer: "The ratio of lecithin to sphingomyelin in amniotic fluid. Lecithin (major surfactant component) increases sharply after 35 weeks while sphingomyelin remains constant. L/S ≥2.0 indicates mature fetal lungs with low risk of RDS. L/S <1.5 indicates immaturity." }, { question: "Why is PG useful?", answer: "Phosphatidylglycerol (PG) is the last phospholipid to appear in fetal surfactant (after 35 weeks). Its presence indicates full lung maturity. Critically, PG is NOT present in blood or meconium, so it is unaffected by specimen contamination—unlike the L/S ratio." }]
  }),
  E({ slug: "peritoneal-fluid-analysis", title: "Peritoneal (Ascitic) Fluid Analysis", category: "Body Fluids",
    seoTitle: "Peritoneal Fluid Analysis – MLT Encyclopedia", seoDescription: "Ascitic fluid: SAAG, spontaneous bacterial peritonitis, transudate vs exudate for MLT exam.", seoKeywords: ["peritoneal fluid", "ascitic fluid", "SAAG", "spontaneous bacterial peritonitis", "ascites", "MLT exam"],
    overview: "Peritoneal (ascitic) fluid analysis differentiates causes of ascites and diagnoses spontaneous bacterial peritonitis (SBP). The serum-ascites albumin gradient (SAAG) has replaced the transudate/exudate classification for peritoneal fluid. SAAG ≥1.1 g/dL indicates portal hypertension.",
    mechanismPhysiology: "SAAG = serum albumin - ascites albumin. SAAG ≥1.1 g/dL: portal hypertension (cirrhosis, heart failure, Budd-Chiari). SAAG <1.1 g/dL: non-portal hypertensive causes (peritoneal carcinomatosis, TB peritonitis, nephrotic syndrome, pancreatic ascites). SBP: infection of ascitic fluid without surgically treatable source. Most common in cirrhotic patients. Defined by ascitic fluid PMN count ≥250/μL with positive culture (usually single organism, E. coli most common).",
    clinicalRelevance: "Cell count: total and differential. PMN ≥250/μL = SBP (treat empirically before culture results). Gram stain sensitivity is only ~10% for SBP (low organism burden). Culture: inoculate blood culture bottles at bedside (increases sensitivity from 50% to 80%). Total protein: <2.5 g/dL in cirrhosis. Glucose: decreased in SBP, TB. LDH: elevated in secondary peritonitis.",
    signsSymptoms: "Ascites: abdominal distension, shifting dullness, fluid wave. SBP: fever, abdominal pain, altered mental status, worsening liver function (may be subtle).",
    assessment: "Paracentesis: diagnostic (cell count, albumin, culture) and therapeutic (large-volume for symptomatic relief). SAAG: measure simultaneously with serum albumin. Cell count: manual hemocytometer, WBC and differential. Culture: blood culture bottles inoculated at bedside (10 mL per bottle). Gram stain: low sensitivity (~10%) for SBP. Additional tests as indicated: cytology (malignancy), amylase (pancreatic), triglycerides (chylous), bilirubin (biliary), adenosine deaminase (TB).",
    management: "SBP: empiric IV ceftriaxone or cefotaxime, albumin infusion (reduces mortality). SBP prophylaxis: oral fluoroquinolone (norfloxacin) for high-risk cirrhotic patients. Large-volume paracentesis: albumin replacement (6-8 g/L removed) to prevent circulatory dysfunction.",
    complications: "SBP: 30-day mortality 20-30%. Secondary peritonitis (surgical cause): distinguished from SBP by: polymicrobial culture, ascitic glucose <50 mg/dL, LDH > ULN serum, total protein >1 g/dL. Paracentesis complications: bleeding, bowel perforation (rare).",
    clinicalPearls: ["SAAG ≥1.1 g/dL = portal hypertension (97% accuracy)—replaces transudate/exudate classification for ascites", "SBP diagnosis: PMN ≥250/μL—start empiric antibiotics immediately without waiting for culture", "Inoculate blood culture bottles at BEDSIDE to improve SBP culture sensitivity from 50% to 80%"],
    examPitfalls: ["SAAG is calculated from ALBUMIN (not total protein)—serum albumin minus ascites albumin", "Gram stain is only ~10% sensitive for SBP—do NOT rely on negative Gram stain to exclude SBP", "Secondary peritonitis has PMN ≥250 (like SBP) but is POLYMICROBIAL and requires SURGICAL intervention"],
    faqJson: [{ question: "SAAG vs transudate/exudate for ascites?", answer: "SAAG has replaced the transudate/exudate classification for ascitic fluid. SAAG ≥1.1 g/dL indicates portal hypertension with 97% accuracy. SAAG <1.1 g/dL indicates non-portal hypertensive causes. It is simpler, more accurate, and requires only albumin measurement." }, { question: "Why inoculate blood culture bottles at bedside?", answer: "Ascitic fluid in SBP has very low bacterial counts (often <1 organism/mL). Standard culture of a few drops of fluid on agar plates has only ~50% sensitivity. Inoculating 10 mL into blood culture bottles (enriched liquid medium) concentrates organisms and improves sensitivity to ~80%." }]
  }),

  // ===== CLINICAL CHEMISTRY =====
  E({ slug: "therapeutic-drug-monitoring", title: "Therapeutic Drug Monitoring (TDM)", category: "Clinical Chemistry",
    seoTitle: "Therapeutic Drug Monitoring – MLT Encyclopedia", seoDescription: "TDM: trough/peak levels, narrow therapeutic index drugs, aminoglycosides for MLT exam.", seoKeywords: ["therapeutic drug monitoring", "TDM", "trough level", "peak level", "narrow therapeutic index", "MLT exam"],
    overview: "Therapeutic drug monitoring (TDM) measures drug concentrations in blood to optimize efficacy and minimize toxicity. TDM is required for drugs with narrow therapeutic indices, significant pharmacokinetic variability, and concentration-dependent efficacy or toxicity. Key drugs monitored: aminoglycosides, vancomycin, digoxin, lithium, anticonvulsants (phenytoin, valproic acid, carbamazepine), immunosuppressants (cyclosporine, tacrolimus, sirolimus), theophylline.",
    mechanismPhysiology: "Narrow therapeutic index: small difference between therapeutic and toxic concentrations. Peak level: maximum drug concentration (measures efficacy). Trough level: minimum concentration before next dose (measures toxicity and ensures adequate steady-state levels). Steady state: achieved after 4-5 half-lives of drug administration. Timing: trough collected 30 minutes BEFORE next dose; peak collected 1-2 hours after IV infusion (drug-specific). Aminoglycosides: concentration-dependent killing—peak determines efficacy, trough determines toxicity (nephrotoxicity, ototoxicity).",
    clinicalRelevance: "Aminoglycosides (gentamicin, tobramycin, amikacin): peak for efficacy (concentration-dependent killing), trough for nephrotoxicity/ototoxicity. Vancomycin: trough-based monitoring (target trough 15-20 μg/mL for serious infections); AUC/MIC monitoring increasingly preferred. Digoxin: narrow therapeutic range (0.8-2.0 ng/mL), collect ≥6-8 hours after dose (distribution phase). Phenytoin: non-linear kinetics (zero-order at therapeutic concentrations—small dose changes cause disproportionate concentration changes); 90% protein-bound (measure free phenytoin in hypoalbuminemia). Lithium: collected 12 hours after last dose (therapeutic 0.6-1.2 mEq/L).",
    signsSymptoms: "TDM is a laboratory test. Drug toxicity symptoms vary by drug: aminoglycosides (tinnitus, nephrotoxicity), digoxin (visual disturbances, arrhythmias, nausea), phenytoin (nystagmus, ataxia, sedation), lithium (tremor, polyuria, seizures).",
    assessment: "Methods: immunoassay (most automated analyzers—EMIT, FPIA, CLIA, CMIA), HPLC/LC-MS/MS (immunosuppressants, some drugs). Specimen: serum or plasma (drug-specific). SST/gel separator tubes may absorb some drugs (phenytoin, phenobarbital)—use non-gel tubes. Hemolysis may affect immunoassay results. Timing is CRITICAL: incorrectly timed specimens yield misleading results.",
    management: "Collect at correct time relative to dosing. Report with timing information. Compare to therapeutic range. Dose adjustments based on pharmacokinetic calculations. Monitor renal function for renally cleared drugs (aminoglycosides, vancomycin, lithium, digoxin).",
    complications: "Incorrectly timed specimen: most common error (produces misleading results). Digoxin-like immunoreactive substances (DLIS): endogenous substances in neonates, renal failure, liver failure that cross-react with some digoxin immunoassays (falsely elevated). SST gel tubes absorb phenytoin, carbamazepine, phenobarbital, lidocaine.",
    clinicalPearls: ["TROUGH is collected 30 minutes BEFORE the next dose; timing is the MOST critical preanalytical factor", "Steady state is reached after 4-5 HALF-LIVES of continuous dosing—TDM is most meaningful at steady state", "Phenytoin has NON-LINEAR (zero-order) kinetics at therapeutic concentrations—small dose changes cause large concentration changes"],
    examPitfalls: ["Digoxin must be collected ≥6-8 HOURS after last dose (distribution phase)—early collection gives falsely elevated results", "In hypoalbuminemia: total phenytoin may be low/normal but FREE (active) phenytoin is elevated—measure free phenytoin", "SST (gel separator) tubes may ABSORB some drugs—use non-gel tubes for phenytoin, carbamazepine, phenobarbital"],
    faqJson: [{ question: "Why is specimen timing so critical?", answer: "Drug concentrations fluctuate between doses. Trough (pre-dose) reflects the lowest concentration and determines risk of toxicity/subtherapeutic levels. Peak reflects highest concentration and efficacy. Incorrectly timed specimens give misleading results and inappropriate dose adjustments." }, { question: "Why is free phenytoin important?", answer: "Phenytoin is ~90% protein-bound (primarily to albumin). In hypoalbuminemia (liver disease, nephrotic syndrome, malnutrition, elderly), more drug is free (unbound/active). Total phenytoin may be therapeutic/low, but free phenytoin is elevated and potentially toxic. Free phenytoin measurement is preferred in these patients." }]
  }),
  E({ slug: "iron-studies", title: "Iron Studies", category: "Clinical Chemistry",
    seoTitle: "Iron Studies – MLT Encyclopedia", seoDescription: "Serum iron, TIBC, ferritin, transferrin saturation: iron deficiency vs overload for MLT exam.", seoKeywords: ["iron studies", "ferritin", "TIBC", "transferrin saturation", "iron deficiency", "MLT exam"],
    overview: "Iron studies assess iron metabolism and differentiate causes of anemia and iron overload. The panel typically includes serum iron, total iron-binding capacity (TIBC), transferrin saturation, and ferritin. Ferritin is the most sensitive marker for iron deficiency but is also an acute phase reactant.",
    mechanismPhysiology: "Iron metabolism: dietary iron absorbed in duodenum, transported by transferrin, stored as ferritin (water-soluble) and hemosiderin (insoluble). Hepcidin (liver peptide) is the master regulator—increases in inflammation (blocks iron absorption and release), decreases in iron deficiency (allows absorption). Serum iron: measures iron bound to transferrin. TIBC: measures transferrin's total capacity to bind iron (inversely proportional to iron stores). Transferrin saturation = (serum iron / TIBC) × 100%. Ferritin: reflects iron STORES (1 ng/mL ≈ 8-10 mg stored iron).",
    clinicalRelevance: "Iron deficiency anemia: low serum iron, HIGH TIBC, LOW transferrin saturation (<20%), LOW ferritin (<12 ng/mL). Most common anemia worldwide. Anemia of chronic disease: low serum iron, LOW TIBC, LOW-NORMAL transferrin saturation, NORMAL-HIGH ferritin (acute phase reactant—elevated in inflammation). Iron overload (hemochromatosis): HIGH serum iron, LOW TIBC, HIGH transferrin saturation (>45%), HIGH ferritin (>300 ng/mL in men, >200 in women).",
    signsSymptoms: "Iron deficiency: fatigue, pallor, pica (craving non-food items), koilonychia (spoon nails), glossitis, angular cheilitis. Hemochromatosis: bronze skin, diabetes (bronze diabetes), liver cirrhosis, cardiomyopathy, arthropathy.",
    assessment: "Serum iron: colorimetric (ferrozine) method. Specimen should be collected fasting, in the morning (diurnal variation—highest in AM). TIBC: measured directly (adding excess iron, removing unbound, measuring total) or calculated from transferrin. Ferritin: immunoassay (chemiluminescent or turbidimetric). Soluble transferrin receptor (sTfR): elevated in iron deficiency, NOT affected by inflammation (differentiates IDA from ACD when ferritin is equivocal). Prussian blue stain (Perl stain): on bone marrow aspirate—gold standard for iron stores (absent iron stores = definitive iron deficiency).",
    management: "Iron deficiency: oral iron supplementation (ferrous sulfate). Monitor response: reticulocyte count rises in 3-5 days, Hb increases 1-2 g/dL per month. Hemochromatosis: therapeutic phlebotomy (target ferritin <50 ng/mL). HFE gene testing (C282Y/H63D mutations).",
    complications: "Ferritin as acute phase reactant: elevated in inflammation, infection, malignancy—may mask concurrent iron deficiency. Serum iron has marked diurnal variation and day-to-day variability—single measurement unreliable. Hemolyzed specimens falsely elevate serum iron.",
    clinicalPearls: ["Ferritin <12 ng/mL is DIAGNOSTIC for iron deficiency; ferritin 12-100 may be equivocal (use sTfR or bone marrow iron)", "Iron deficiency: LOW iron, HIGH TIBC, LOW ferritin. Chronic disease: LOW iron, LOW TIBC, NORMAL/HIGH ferritin", "Transferrin saturation >45% is the EARLIEST biochemical marker of hereditary hemochromatosis"],
    examPitfalls: ["Ferritin is an ACUTE PHASE REACTANT—it may be NORMAL or ELEVATED in iron-deficient patients with concurrent inflammation", "Serum iron has significant DIURNAL variation (highest in morning)—collect fasting AM specimen", "Hemolysis falsely ELEVATES serum iron (iron released from hemoglobin in RBCs)"],
    faqJson: [{ question: "How is iron deficiency differentiated from anemia of chronic disease?", answer: "IDA: low ferritin (<12), HIGH TIBC, elevated sTfR. ACD: normal/high ferritin, LOW TIBC, normal sTfR. When ferritin is equivocal (12-100 in presence of inflammation), sTfR or sTfR/log ferritin index helps differentiate—sTfR is elevated in IDA but normal in ACD." }, { question: "What is soluble transferrin receptor?", answer: "sTfR is a fragment of transferrin receptor shed from erythroid precursors. It increases when iron delivery to cells is insufficient (iron deficiency). Unlike ferritin, sTfR is NOT affected by inflammation—making it valuable for diagnosing iron deficiency in patients with concurrent inflammatory conditions." }]
  }),

  // ===== COAGULATION =====
  E({ slug: "platelet-function-testing", title: "Platelet Function Testing", category: "Coagulation",
    seoTitle: "Platelet Function Testing – MLT Encyclopedia", seoDescription: "Platelet aggregation, PFA-100, bleeding time, platelet disorders for MLT exam.", seoKeywords: ["platelet function", "platelet aggregation", "PFA-100", "bleeding time", "von Willebrand", "MLT exam"],
    overview: "Platelet function testing evaluates the ability of platelets to adhere, activate, and aggregate in primary hemostasis. Tests range from screening (PFA-100, bleeding time) to definitive (platelet aggregation studies, flow cytometry). Platelet function disorders present with mucocutaneous bleeding (petechiae, purpura, epistaxis, gingival bleeding).",
    mechanismPhysiology: "Primary hemostasis: vascular injury exposes subendothelial collagen → vWF mediates platelet adhesion (GPIb receptor) → platelet activation releases ADP, thromboxane A2 → platelet aggregation via fibrinogen bridging GPIIb/IIIa receptors. Platelet aggregation study (light transmission aggregometry—LTA): PRP in cuvette, add agonists, measure light transmission as platelets aggregate (platelet-rich plasma becomes clearer). Agonists: ADP, collagen, epinephrine, arachidonic acid, ristocetin. PFA-100: screens for platelet dysfunction and vWD. Blood flows through aperture coated with collagen/epinephrine or collagen/ADP. Measures closure time. Bleeding time: largely abandoned (poor reproducibility, invasive).",
    clinicalRelevance: "von Willebrand disease (vWD): most common inherited bleeding disorder. vWF mediates platelet adhesion (GPIb) and carries Factor VIII. Type 1 (80%): partial quantitative deficiency. Type 2: qualitative defects. Type 3: complete deficiency (rare, severe). Ristocetin-induced platelet aggregation (RIPA): decreased in vWD (ristocetin requires vWF to agglutinate platelets). Glanzmann thrombasthenia: absence of GPIIb/IIIa → no aggregation with ADP, collagen, epinephrine, or arachidonic acid but NORMAL response to ristocetin. Bernard-Soulier syndrome: absence of GPIb → decreased adhesion, GIANT platelets, thrombocytopenia, decreased ristocetin response.",
    signsSymptoms: "Mucocutaneous bleeding: petechiae, purpura, epistaxis, menorrhagia, GI bleeding, post-surgical bleeding. Differs from coagulation factor deficiency (deep tissue/joint bleeding, hemarthrosis).",
    assessment: "PFA-100: closure time >collagen/ADP or >collagen/epinephrine. Prolonged by: vWD, platelet function defects, aspirin (prolongs col/epi only), anemia, thrombocytopenia (<100,000). Platelet aggregation (LTA): test with multiple agonists—pattern of response identifies specific disorder. Aspirin effect: absent response to arachidonic acid (COX inhibition), reduced secondary wave ADP/epinephrine. vWD workup: vWF antigen, vWF activity (ristocetin cofactor), Factor VIII activity, multimer analysis.",
    management: "vWD: DDAVP (releases vWF from endothelial stores—effective in Type 1), vWF concentrate. Glanzmann: platelet transfusion, rFVIIa. Aspirin effect: discontinue 7-10 days before surgery. PFA-100 is a screening test—NOT a replacement for aggregation studies.",
    complications: "Aspirin irreversibly inhibits COX-1 for the LIFE of the platelet (~7-10 days). PFA-100 is insensitive to mild platelet dysfunction and some vWD types. Aggregation requires adequate platelet count (>100,000) and fresh specimen (within 4 hours).",
    clinicalPearls: ["Glanzmann thrombasthenia: ABSENT aggregation with ALL agonists EXCEPT ristocetin (which tests adhesion, not aggregation)", "Bernard-Soulier: GIANT platelets + decreased ristocetin response + thrombocytopenia", "Aspirin irreversibly inhibits COX—affects platelet function for 7-10 DAYS (platelet lifespan)"],
    examPitfalls: ["Ristocetin tests vWF-dependent platelet AGGLUTINATION (not true aggregation)—it is the only agonist that requires vWF", "PFA-100 is prolonged by aspirin (col/epi ONLY—col/ADP may be normal), anemia (Hct <30%), and low platelet count (<100,000)", "Aggregation studies require PRP prepared within 1-4 HOURS—specimens cannot be refrigerated or delayed"],
    faqJson: [{ question: "How does ristocetin work?", answer: "Ristocetin is an antibiotic that causes vWF to bind GPIb on platelet surfaces, inducing agglutination. It tests the vWF-GPIb adhesion pathway. Decreased ristocetin response = vWD or Bernard-Soulier. Normal ristocetin + absent other agonists = Glanzmann." }, { question: "Glanzmann vs Bernard-Soulier?", answer: "Glanzmann (GPIIb/IIIa deficiency): normal platelet count, normal size, absent aggregation with all agonists EXCEPT ristocetin. Bernard-Soulier (GPIb deficiency): thrombocytopenia, GIANT platelets, absent ristocetin response but normal response to other agonists." }]
  }),

  // ===== BLOOD BANKING =====
  E({ slug: "antibody-identification", title: "Antibody Identification", category: "Blood Banking/Transfusion Medicine",
    seoTitle: "Antibody Identification – MLT Encyclopedia", seoDescription: "Antibody panels, rule-out method, antigen typing, clinically significant antibodies for MLT exam.", seoKeywords: ["antibody identification", "antibody panel", "rule-out", "antigen typing", "clinically significant antibodies", "MLT exam"],
    overview: "Antibody identification determines the specificity of alloantibodies detected on antibody screening. It uses a panel of 10-16 group O reagent red blood cells with known antigen profiles. The rule-out (exclusion) method eliminates antibody specificities by identifying cells that are antigen-positive but non-reactive.",
    mechanismPhysiology: "When antibody screen is positive, patient serum is tested against a panel of group O reagent RBCs with known antigen profiles. An antigram (panel sheet) lists the antigen profile of each cell. Rule-out: if a cell is POSITIVE for an antigen but NEGATIVE in the test (no agglutination), that antibody specificity is excluded (ruled out). Only antigens that are positive on ALL reactive cells AND negative on ALL non-reactive cells match the antibody pattern. Autocontrol (patient serum + patient cells): positive autocontrol suggests autoantibody, alloantibody coating patient cells, or positive DAT.",
    clinicalRelevance: "Clinically significant antibodies: those causing hemolytic transfusion reactions or HDFN. Most are IgG, reactive at 37°C and AHG phase. Examples: anti-D, -K, -k, -Fya, -Fyb, -Jka, -Jkb, -S, -s. Clinically insignificant: typically IgM, reactive at room temperature or below (cold antibodies). Examples: anti-M (usually), -N, -P1, -Lewis (Lea, Leb). Anti-Jka: notorious for being difficult to detect (dosage effect, evanescent—drops below detectable levels between exposures), and causing DELAYED hemolytic transfusion reactions.",
    signsSymptoms: "Antibody identification is a laboratory procedure. Clinical significance relates to potential for transfusion reactions or HDFN.",
    assessment: "Panel interpretation steps: (1) Test at appropriate phases (IS, 37°C, AHG). (2) Determine reactivity pattern (which cells positive, which negative). (3) Apply rule-out method using non-reactive cells (homozygous antigen expression preferred for ruling out). (4) Identify matching pattern. (5) Confirm with antigen typing: patient cells should LACK the corresponding antigen. (6) Three-cell rule: statistical requirement—at least 3 antigen-positive reactive cells and 3 antigen-negative non-reactive cells (p <0.05). Additional techniques: enzyme treatment (ficin, papain) enhances Rh, Kidd, Lewis; destroys MNS, Duffy. LISS (low ionic strength saline): enhances IgG uptake. PEG (polyethylene glycol): enhances IgG detection.",
    management: "Once identified: select antigen-negative donor units (crossmatch with AHG). For multiple antibodies: all specificities must be antigen-negative. Rare phenotypes may require rare donor registries. Document antibodies permanently in patient's transfusion history.",
    complications: "Multiple antibodies: difficult to resolve. Antibodies to high-frequency antigens: most panel cells positive (very few antigen-negative donors). Dosage: some antibodies react more strongly with homozygous cells (Rh, Kidd, Duffy, MNS). Mixed-field agglutination: recent transfusion creates mixed cell population.",
    clinicalPearls: ["Three-cell rule: need ≥3 reactive antigen-positive cells AND ≥3 non-reactive antigen-negative cells for valid identification", "Anti-Jka is notorious: shows DOSAGE, is EVANESCENT (disappears between exposures), and causes DELAYED hemolytic reactions", "Enzyme treatment ENHANCES Rh, Kidd, Lewis BUT DESTROYS MNS and Duffy antigens"],
    examPitfalls: ["Patient must be ANTIGEN-NEGATIVE for the corresponding antibody—always confirm with antigen typing", "Rule-out requires HOMOZYGOUS antigen expression for antibodies showing dosage (Rh, Kidd, Duffy, MNS)", "Cold antibodies reactive ONLY at IS or RT are usually clinically INSIGNIFICANT—significant antibodies react at 37°C/AHG"],
    faqJson: [{ question: "What is the rule-out method?", answer: "If a panel cell is positive for an antigen but the test result is negative (no agglutination), that antibody can be excluded (ruled out). Only specificities whose antigen is present on ALL reactive cells and absent on ALL non-reactive cells match the antibody pattern." }, { question: "Why is anti-Jka clinically important?", answer: "Anti-Jka is dangerous because it: (1) shows dosage (reacts weakly with heterozygous cells), (2) is evanescent (titer drops below detection between exposures—may not be detected on current antibody screen), (3) causes severe delayed hemolytic transfusion reactions and HDFN. Always check transfusion history for previously identified antibodies." }]
  }),

  // ===== MICROBIOLOGY =====
  E({ slug: "neisseria-species", title: "Neisseria Species", category: "Microbiology",
    seoTitle: "Neisseria Species – MLT Encyclopedia", seoDescription: "N. meningitidis, N. gonorrhoeae: GN diplococci, oxidase, chocolate agar for MLT exam.", seoKeywords: ["Neisseria meningitidis", "Neisseria gonorrhoeae", "gram negative diplococci", "oxidase positive", "chocolate agar", "MLT exam"],
    overview: "Neisseria are gram-negative diplococci (kidney-bean shaped pairs), oxidase-positive, catalase-positive. Two pathogenic species: N. meningitidis (meningococcus—meningitis, septicemia) and N. gonorrhoeae (gonococcus—sexually transmitted). Both are fastidious, requiring enriched media (chocolate agar) and CO2 for growth.",
    mechanismPhysiology: "N. meningitidis: polysaccharide capsule (serogroups A, B, C, W, Y—vaccines available for A, C, W, Y; serogroup B vaccine uses protein antigens). IgA protease. LOS (lipooligosaccharide = endotoxin). Transmitted by respiratory droplets, colonizes nasopharynx. N. gonorrhoeae: NO capsule, antigenic variation of pili and Opa proteins (evades immunity—no vaccine), IgA protease. Transmitted sexually, infects mucosal surfaces (urethral, cervical, rectal, pharyngeal).",
    clinicalRelevance: "N. meningitidis: meningitis (second most common bacterial cause after S. pneumoniae), meningococcemia (fulminant sepsis with petechial/purpuric rash, DIC, Waterhouse-Friderichsen syndrome). N. gonorrhoeae: urethritis, cervicitis, PID, neonatal ophthalmia (ophthalmia neonatorum), disseminated gonococcal infection. Carbohydrate utilization: N. meningitidis: glucose + maltose. N. gonorrhoeae: glucose only. Both: NO lactose, NO sucrose.",
    signsSymptoms: "Meningitis: headache, fever, neck stiffness, petechial/purpuric rash (meningococcemia). Gonorrhea: males—urethral discharge, dysuria; females—often asymptomatic (cervicitis, PID); DGI—polyarthralgia, dermatitis, tenosynovitis.",
    assessment: "Gram stain: GN diplococci (intracellular in PMNs). Gram stain of male urethral discharge: 95% sensitive for gonorrhea (not recommended for female cervical specimens—sensitivity only 40-60%). Culture: chocolate agar (5-10% CO2, 35-37°C). Thayer-Martin (modified): selective medium for pathogenic Neisseria from non-sterile sites (vancomycin, colistin, nystatin, trimethoprim inhibit normal flora). NAAT: most sensitive method for GC/CT detection (urine or swab)—preferred for screening. Oxidase: POSITIVE (Kovac reagent → purple).",
    management: "N. meningitidis: ceftriaxone, chemoprophylaxis for close contacts (rifampin, ciprofloxacin, or ceftriaxone). N. gonorrhoeae: ceftriaxone IM 500 mg single dose (dual therapy with doxycycline for empiric chlamydia co-treatment). Report to public health.",
    complications: "Meningococcemia: DIC, purpura fulminans, Waterhouse-Friderichsen (adrenal hemorrhage). Gonococcal resistance: increasing ceftriaxone MICs, multidrug resistance globally. PID: tubal scarring, infertility, ectopic pregnancy.",
    clinicalPearls: ["N. meningitidis: glucose AND maltose positive. N. gonorrhoeae: glucose ONLY—the key differentiator", "NAAT is the MOST SENSITIVE test for N. gonorrhoeae—culture is required for antimicrobial susceptibility testing", "Thayer-Martin agar is selective for pathogenic Neisseria from NON-STERILE sites (e.g., genital, rectal, pharyngeal)"],
    examPitfalls: ["Oxidase test must be performed with steel or platinum loop—nickel-containing loops cause false positives", "N. gonorrhoeae is extremely FRAGILE—specimens must be plated immediately or transported in CO2-maintaining systems", "NAAT cannot test antimicrobial susceptibility—culture is still needed for resistance testing"],
    faqJson: [{ question: "Why is Thayer-Martin agar used?", answer: "Thayer-Martin is chocolate agar supplemented with antibiotics (vancomycin = GPC inhibitor, colistin = GNR inhibitor, nystatin = yeast inhibitor, TMP = Proteus swarming inhibitor). It suppresses normal flora allowing recovery of pathogenic Neisseria from contaminated sites like genital, rectal, and pharyngeal specimens." }, { question: "NAAT vs culture for gonorrhea?", answer: "NAAT is more sensitive (detects DNA even from non-viable organisms), faster, and can be performed on urine. Culture is less sensitive but is required for antimicrobial susceptibility testing (critical for detecting resistance) and is still required for medico-legal cases." }]
  }),
  E({ slug: "haemophilus-influenzae", title: "Haemophilus influenzae", category: "Microbiology",
    seoTitle: "Haemophilus influenzae – MLT Encyclopedia", seoDescription: "H. influenzae: X and V factor requirements, satellite test, chocolate agar for MLT exam.", seoKeywords: ["Haemophilus influenzae", "X factor", "V factor", "satellite test", "chocolate agar", "MLT exam"],
    overview: "Haemophilus influenzae is a small gram-negative coccobacillus that requires both X factor (hemin) and V factor (NAD) for growth. It is a common cause of respiratory infections (otitis media, sinusitis, pneumonia, epiglottitis) and meningitis in children. Type b (Hib) vaccine has dramatically reduced invasive disease.",
    mechanismPhysiology: "X factor (hemin/hematin): required for cytochrome enzyme synthesis. V factor (NAD/NADP): coenzyme for metabolic reactions. Both factors are present in blood agar but V factor is released only when RBCs are lysed (hence chocolate agar supports growth—RBCs are heat-lysed, releasing X and V factors). Blood agar: V factor is intracellular—Haemophilus cannot grow (unless adjacent to S. aureus which lyses RBCs, releasing V factor = satellite phenomenon). Six serotypes (a-f) based on capsular polysaccharide; type b is most invasive.",
    clinicalRelevance: "Invasive: meningitis (formerly #1 cause in children 6 months-5 years—now rare due to Hib vaccine), epiglottitis (medical emergency), bacteremia, septic arthritis. Non-invasive: otitis media, sinusitis, bronchitis, pneumonia (usually non-typeable strains). Hib vaccine: conjugate polysaccharide-protein vaccine (PRP-protein conjugate)—targeted type b capsule.",
    signsSymptoms: "Meningitis: fever, neck stiffness, altered mental status. Epiglottitis: drooling, dysphagia, stridor, tripod positioning (medical emergency—do NOT examine throat). Otitis media: ear pain, fever.",
    assessment: "Gram stain: small GN coccobacilli (pleomorphic—sometimes appearing as short rods or filaments). Culture: chocolate agar (35-37°C, 5-10% CO2)—does NOT grow on blood agar (unless satellite phenomenon). X and V factor requirement test: disks on Mueller-Hinton or nutrient agar. H. influenzae: requires BOTH X AND V. H. parainfluenzae: requires V ONLY. H. ducreyi: requires X ONLY. Satellite (satellitism) test: grow on blood agar adjacent to S. aureus streak—Haemophilus colonies appear as tiny satellites around S. aureus (which lyses RBCs, releasing V factor). Rapid antigen detection: CSF latex agglutination for type b capsule (largely replaced by culture and NAAT).",
    management: "Meningitis: ceftriaxone. Otitis/sinusitis: amoxicillin (check for beta-lactamase). Beta-lactamase positive: amoxicillin-clavulanate. Prophylaxis: rifampin for close contacts of invasive Hib disease.",
    complications: "Beta-lactamase production (~30% of strains): resistant to ampicillin/amoxicillin—test with nitrocefin (chromogenic cephalosporinase test). Epiglottitis: airway obstruction.",
    clinicalPearls: ["H. influenzae requires BOTH X (hemin) AND V (NAD) factors—does NOT grow on blood agar", "Satellite phenomenon: tiny colonies around S. aureus on blood agar—S. aureus lyses RBCs releasing V factor", "Chocolate agar supports growth because heating lyses RBCs, releasing both X and V factors"],
    examPitfalls: ["H. influenzae grows on chocolate agar but NOT blood agar (V factor is trapped inside intact RBCs on blood agar)", "H. parainfluenzae requires only V factor; H. ducreyi requires only X factor—know the factor requirements", "Nitrocefin (chromogenic cephalosporin) test detects beta-lactamase—positive = resistant to ampicillin"],
    faqJson: [{ question: "Why does H. influenzae grow on chocolate agar but not blood agar?", answer: "Both X and V factors are inside RBCs. On blood agar, RBCs are intact—V factor is unavailable (X factor can be obtained from free hemoglobin). On chocolate agar, RBCs are heat-lysed, releasing both X and V factors into the medium. The satellite phenomenon on blood agar works because S. aureus beta-hemolysin lyses nearby RBCs." }, { question: "What is the satellite test?", answer: "Haemophilus is streaked on blood agar with an S. aureus cross-streak. S. aureus produces hemolysins that lyse RBCs, releasing V factor. Haemophilus grows only near the S. aureus streak (satellite colonies). This demonstrates the V factor requirement in a simple, visual way." }]
  }),
];

async function run() {
  let inserted = 0, errors = 0;
  console.log(`Starting MLT Encyclopedia Batch 6: ${ENTRIES.length} entries\n`);
  for (const e of ENTRIES) {
    try { await ins(e); inserted++; } catch (err: any) { errors++; console.error(`Error ${e.slug}: ${err.message}`); }
  }
  console.log(`\nBatch 6 complete: ${inserted} inserted, ${errors} errors out of ${ENTRIES.length}`);
  const { rows } = await pool.query(`SELECT category, COUNT(*) as cnt FROM encyclopedia_entries WHERE profession='mlt' AND status='published' GROUP BY category ORDER BY category`);
  console.log("\nAll MLT entries by category:");
  for (const r of rows) console.log(`  ${r.category}: ${r.cnt}`);
  const { rows: [{ total }] } = await pool.query(`SELECT COUNT(*) as total FROM encyclopedia_entries WHERE profession='mlt' AND status='published'`);
  console.log(`\nTotal published MLT encyclopedia entries: ${total}`);
  console.log("Done!");
  await pool.end();
}
run();
