import pg from "pg";
const { Pool } = pg;

interface MltQuestion {
  stem: string;
  options: string[];
  correctAnswer: number;
  rationaleLong: string;
  blueprintCategory: string;
  subtopic: string;
  difficulty: number;
  cognitiveLevel: string;
  learningObjective: string;
}

const chemBatch3: MltQuestion[] = [
  { stem: "A patient's results show pH 7.32, pCO2 60 mmHg, HCO3- 30 mEq/L. What is the acid-base status?", options: ["Uncompensated respiratory acidosis", "Partially compensated respiratory acidosis", "Fully compensated metabolic alkalosis", "Mixed disorder"], correctAnswer: 1, rationaleLong: "pH 7.32 is acidotic. pCO2 60 (elevated) indicates respiratory acidosis. HCO3- 30 (elevated above normal 22-26) indicates renal compensation (kidneys retaining bicarbonate). Since pH has not returned to normal, this is partially compensated respiratory acidosis. Full compensation would normalize the pH.", blueprintCategory: "Clinical Chemistry", subtopic: "Electrolytes & Blood Gases", difficulty: 4, cognitiveLevel: "analysis", learningObjective: "Identify compensated acid-base disorders" },
  { stem: "A laboratory switches from an indirect ISE to a direct ISE method for sodium measurement. A patient with hyperlipidemia previously had sodium of 128 mEq/L. On the direct ISE, the sodium is most likely:", options: ["128 mEq/L (same)", "135 mEq/L (higher/normal)", "120 mEq/L (lower)", "145 mEq/L (much higher)"], correctAnswer: 1, rationaleLong: "The indirect ISE gave a falsely low sodium (pseudohyponatremia) due to the volume displacement effect of lipemia. Direct ISE measures ion activity in undiluted plasma, unaffected by lipemia, revealing the true sodium concentration which is likely normal (~135-145 mEq/L). This is a classic case of pseudohyponatremia.", blueprintCategory: "Clinical Chemistry", subtopic: "Instrumentation (Spectrophotometry, ISE, HPLC)", difficulty: 5, cognitiveLevel: "analysis", learningObjective: "Understand pseudohyponatremia and ISE methods" },
  { stem: "A serum specimen has a hemolysis index of 500. Which analytes should NOT be reported?", options: ["Sodium and chloride", "Potassium, LDH, and AST", "Glucose and BUN", "Total protein and albumin"], correctAnswer: 1, rationaleLong: "Potassium, LDH, and AST are the most significantly affected by hemolysis because these analytes are present in much higher concentrations within RBCs than in plasma. Hemolysis releases intracellular contents, causing falsely elevated results. Most analyzers flag results with high hemolysis indices and suppress affected analytes.", blueprintCategory: "Clinical Chemistry", subtopic: "Electrolytes & Blood Gases", difficulty: 3, cognitiveLevel: "application", learningObjective: "Know hemolysis-affected analytes" },
  { stem: "Which of the following assays uses the enzymatic rate method?", options: ["Total bilirubin (diazo method)", "BUN (urease/GLDH method)", "Total protein (biuret)", "Calcium (arsenazo III)"], correctAnswer: 1, rationaleLong: "The BUN urease/GLDH method is an enzymatic rate (kinetic) assay: urease converts urea to ammonia + CO2, then glutamate dehydrogenase (GLDH) couples ammonia with α-ketoglutarate, consuming NADH. The rate of NADH decrease (measured at 340 nm) is proportional to BUN concentration.", blueprintCategory: "Clinical Chemistry", subtopic: "Instrumentation (Spectrophotometry, ISE, HPLC)", difficulty: 4, cognitiveLevel: "recall", learningObjective: "Know enzymatic rate methods" },
  { stem: "Troponin I and troponin T are preferred over CK-MB for diagnosing MI because:", options: ["They rise faster", "They are more specific for cardiac tissue and remain elevated longer", "They are cheaper to measure", "They can be measured on any analyzer"], correctAnswer: 1, rationaleLong: "Cardiac troponins (cTnI, cTnT) are highly specific for myocardial injury because cardiac and skeletal muscle troponins have different amino acid sequences (allowing cardiac-specific antibodies). They also remain elevated for 7-14 days, providing a wider diagnostic window. CK-MB is found in small amounts in skeletal muscle and returns to normal in 2-3 days.", blueprintCategory: "Clinical Chemistry", subtopic: "Enzymes", difficulty: 3, cognitiveLevel: "application", learningObjective: "Compare cardiac biomarker specificity" },
  { stem: "A patient has the following thyroid results: TSH 0.1 mIU/L (low), free T4 3.8 ng/dL (high), free T3 elevated. This pattern indicates:", options: ["Primary hypothyroidism", "Hyperthyroidism (Graves disease)", "Euthyroid sick syndrome", "Subclinical hypothyroidism"], correctAnswer: 1, rationaleLong: "Low TSH with elevated free T4 and T3 is the classic pattern of hyperthyroidism. The excess thyroid hormones suppress TSH via negative feedback on the pituitary. Graves disease (autoimmune, TSH receptor stimulating antibodies) is the most common cause. Other causes include toxic multinodular goiter and toxic adenoma.", blueprintCategory: "Clinical Chemistry", subtopic: "Endocrine / Hormones", difficulty: 3, cognitiveLevel: "application", learningObjective: "Interpret hyperthyroid lab pattern" },
  { stem: "Which cardiac biomarker is the first to rise after acute MI?", options: ["Troponin I", "CK-MB", "Myoglobin", "BNP"], correctAnswer: 2, rationaleLong: "Myoglobin is the first cardiac biomarker to rise after acute MI (1-3 hours), due to its small molecular size (17 kDa). However, myoglobin is not cardiac-specific (also released from skeletal muscle). It peaks at 6-9 hours and returns to normal within 24 hours. High-sensitivity troponin assays have narrowed this time advantage.", blueprintCategory: "Clinical Chemistry", subtopic: "Enzymes", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know cardiac biomarker timeline" },
  { stem: "Immunofixation electrophoresis (IFE) is used to:", options: ["Quantify total protein", "Identify the type of monoclonal immunoglobulin", "Measure hemoglobin A1c", "Determine blood type"], correctAnswer: 1, rationaleLong: "IFE identifies the specific heavy chain class (IgG, IgA, IgM, IgD, IgE) and light chain type (kappa or lambda) of a monoclonal protein detected on serum protein electrophoresis. It is the gold standard for characterizing monoclonal gammopathies (multiple myeloma, Waldenström macroglobulinemia, MGUS).", blueprintCategory: "Clinical Chemistry", subtopic: "Proteins & Amino Acids", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know IFE purpose" },
  { stem: "Which of the following is an endogenous substance that can interfere with immunoassays by bridging capture and detection antibodies?", options: ["Hemoglobin", "HAMA (human anti-mouse antibodies)", "Bilirubin", "Ascorbic acid"], correctAnswer: 1, rationaleLong: "Human anti-mouse antibodies (HAMA) are endogenous antibodies that patients develop against mouse immunoglobulins (from exposure to mouse-based diagnostic or therapeutic products). HAMA can bridge capture and detection antibodies in sandwich immunoassays, causing false-positive results. Heterophilic antibody blocking agents are used to mitigate this.", blueprintCategory: "Clinical Chemistry", subtopic: "Instrumentation (Spectrophotometry, ISE, HPLC)", difficulty: 5, cognitiveLevel: "analysis", learningObjective: "Know immunoassay interferences" },
  { stem: "In the Jaffe creatinine method, which substance can cause positive interference?", options: ["Glucose at normal concentrations", "Acetoacetate (ketones)", "Sodium", "Chloride"], correctAnswer: 1, rationaleLong: "Acetoacetate and other ketone bodies are known positive interferents in the Jaffe (alkaline picrate) creatinine method, causing falsely elevated creatinine results in patients with DKA. Enzymatic creatinine methods are less susceptible to this interference. Other Jaffe interferents include proteins, cephalosporin antibiotics, and glucose at very high concentrations.", blueprintCategory: "Clinical Chemistry", subtopic: "Renal Function", difficulty: 4, cognitiveLevel: "application", learningObjective: "Know Jaffe method interferences" },
  { stem: "What is the prozone (hook) effect in immunoassay?", options: ["False negative due to very high analyte concentration overwhelming the antibody", "False positive due to cross-reactivity", "Nonspecific binding to the solid phase", "Matrix effect from patient specimen"], correctAnswer: 0, rationaleLong: "The prozone (hook) effect occurs in sandwich immunoassays when the analyte concentration is so high that it saturates both the capture and detection antibodies independently, preventing sandwich formation. This results in a falsely low or negative result. It can occur with very high concentrations of hCG, PSA, ferritin, and other analytes. Serial dilution resolves it.", blueprintCategory: "Clinical Chemistry", subtopic: "Instrumentation (Spectrophotometry, ISE, HPLC)", difficulty: 5, cognitiveLevel: "analysis", learningObjective: "Understand the hook effect" },
  { stem: "Gestational diabetes is screened using:", options: ["Fasting glucose only", "Random glucose", "Oral glucose tolerance test (OGTT) with 75g or 50g glucose challenge", "HbA1c only"], correctAnswer: 2, rationaleLong: "Gestational diabetes mellitus (GDM) is typically screened at 24-28 weeks gestation using either a one-step approach (75g OGTT, IADPSG criteria) or two-step approach (50g glucose challenge test followed by 100g OGTT if positive). The two-step approach is most common in the US. Fasting glucose and HbA1c alone are insufficient for GDM screening.", blueprintCategory: "Clinical Chemistry", subtopic: "Carbohydrates", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know gestational diabetes screening" },
  { stem: "High-sensitivity CRP (hs-CRP) is used primarily to assess:", options: ["Acute bacterial infection", "Cardiovascular risk", "Rheumatoid arthritis activity", "Complement deficiency"], correctAnswer: 1, rationaleLong: "High-sensitivity CRP (hs-CRP) measures very low concentrations of CRP for cardiovascular risk assessment. The AHA/ACC classifies risk as: <1.0 mg/L (low risk), 1.0-3.0 mg/L (average risk), >3.0 mg/L (high risk). hs-CRP reflects chronic low-grade inflammation associated with atherosclerosis, independent of traditional risk factors.", blueprintCategory: "Clinical Chemistry", subtopic: "Proteins & Amino Acids", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know hs-CRP clinical application" },
  { stem: "A random urine specimen shows a protein-to-creatinine ratio of 0.5 g/g. This is equivalent to approximately how many grams of protein per day?", options: ["0.15 g/day", "0.5 g/day", "1.0 g/day", "3.5 g/day"], correctAnswer: 1, rationaleLong: "The spot urine protein-to-creatinine ratio (g/g) approximates the 24-hour urine protein excretion in g/day. A ratio of 0.5 g/g corresponds to approximately 0.5 g/day of proteinuria. Normal is <0.2 g/day. Nephrotic range is >3.5 g/day. This ratio eliminates the need for cumbersome 24-hour urine collections.", blueprintCategory: "Clinical Chemistry", subtopic: "Renal Function", difficulty: 3, cognitiveLevel: "application", learningObjective: "Interpret protein-to-creatinine ratio" },
];

const hemBatch3: MltQuestion[] = [
  { stem: "A 65-year-old patient has pancytopenia with macrocytic RBCs, hypersegmented neutrophils, and oval macrocytes. Serum B12 is 95 pg/mL (low) and folate is normal. The most likely diagnosis is:", options: ["Iron deficiency anemia", "Pernicious anemia (B12 deficiency)", "Folate deficiency", "Myelodysplastic syndrome"], correctAnswer: 1, rationaleLong: "The combination of macrocytic anemia, oval macrocytes, hypersegmented neutrophils, and low serum B12 with normal folate is diagnostic of vitamin B12 deficiency. In an elderly patient, the most common cause is pernicious anemia (autoimmune destruction of gastric parietal cells, leading to decreased intrinsic factor and B12 malabsorption). Anti-intrinsic factor antibodies confirm the diagnosis.", blueprintCategory: "Hematology", subtopic: "Anemias (Iron-deficiency, Megaloblastic, Hemolytic)", difficulty: 4, cognitiveLevel: "analysis", learningObjective: "Diagnose pernicious anemia" },
  { stem: "A peripheral blood smear from a patient with fever shows banana-shaped (crescent) gametocytes. The most likely diagnosis is:", options: ["Plasmodium vivax malaria", "Plasmodium falciparum malaria", "Babesia microti infection", "Trypanosoma brucei infection"], correctAnswer: 1, rationaleLong: "Banana-shaped (crescent/sausage) gametocytes are pathognomonic for Plasmodium falciparum, the most dangerous malaria species. P. falciparum is unique in that it can infect RBCs of all ages (causing high parasitemia) and produces distinctively shaped gametocytes. Other Plasmodium species produce round gametocytes.", blueprintCategory: "Hematology", subtopic: "Erythrocytes (RBC Morphology & Disorders)", difficulty: 4, cognitiveLevel: "application", learningObjective: "Identify malaria parasites on blood smear" },
  { stem: "The LAP (leukocyte alkaline phosphatase) score is typically decreased in:", options: ["Bacterial infection", "Chronic myelogenous leukemia", "Polycythemia vera", "Pregnancy"], correctAnswer: 1, rationaleLong: "LAP score is characteristically low (decreased) in CML, helping distinguish it from other causes of leukocytosis (infection, other myeloproliferative neoplasms) where LAP is elevated. LAP is a cytochemical stain that measures alkaline phosphatase activity in neutrophils. In the era of molecular testing (BCR-ABL), LAP scoring is less commonly performed.", blueprintCategory: "Hematology", subtopic: "Leukemias & Lymphomas", difficulty: 3, cognitiveLevel: "application", learningObjective: "Know LAP score in CML" },
  { stem: "Which hemoglobin variant is associated with hemoglobin C disease?", options: ["Glutamic acid to valine substitution at position 6 of beta chain", "Glutamic acid to lysine substitution at position 6 of beta chain", "Deletion of alpha globin genes", "Point mutation in gamma globin gene"], correctAnswer: 1, rationaleLong: "Hemoglobin C results from a point mutation causing glutamic acid to lysine substitution at position 6 of the beta-globin chain (same position as HbS, which has glutamic acid to valine). HbCC disease causes a mild hemolytic anemia with target cells and HbC crystals (hexagonal). HbSC disease is a compound heterozygous condition.", blueprintCategory: "Hematology", subtopic: "Hemoglobin & Hemoglobinopathies", difficulty: 4, cognitiveLevel: "recall", learningObjective: "Know hemoglobin C mutation" },
  { stem: "In which disorder would you expect to see an elevated absolute monocyte count?", options: ["Allergic reaction", "Chronic myelomonocytic leukemia (CMML)", "Acute lymphoblastic leukemia", "Iron deficiency anemia"], correctAnswer: 1, rationaleLong: "CMML (chronic myelomonocytic leukemia) is a myelodysplastic/myeloproliferative neoplasm characterized by persistent monocytosis (>1,000/μL for >3 months) in the peripheral blood. Monocytes may appear dysplastic. CMML is most common in elderly patients. Other causes of monocytosis include chronic infections (TB), autoimmune diseases, and recovery from neutropenia.", blueprintCategory: "Hematology", subtopic: "Leukemias & Lymphomas", difficulty: 3, cognitiveLevel: "application", learningObjective: "Know causes of monocytosis" },
  { stem: "The hemoglobin solubility test (Sickledex) is used to:", options: ["Quantify HbS percentage", "Detect the presence of HbS", "Differentiate HbS from HbC", "Measure oxygen affinity"], correctAnswer: 1, rationaleLong: "The hemoglobin solubility test (Sickledex) is a screening test that detects the presence of HbS. When reduced (deoxygenated) by sodium dithionite, HbS is insoluble and produces turbidity. A positive test indicates HbS is present but cannot distinguish sickle cell trait (HbAS) from sickle cell disease (HbSS). Hemoglobin electrophoresis is needed for confirmation.", blueprintCategory: "Hematology", subtopic: "Hemoglobin & Hemoglobinopathies", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know Sickledex test purpose" },
  { stem: "An impedance-based hematology analyzer determines cell size by:", options: ["Measuring light scatter", "Measuring changes in electrical resistance as cells pass through an aperture", "Fluorescent staining intensity", "Centrifugal separation"], correctAnswer: 1, rationaleLong: "Impedance (Coulter) principle: cells suspended in an electrically conductive diluent pass through a small aperture. Each cell displaces its volume of diluent, causing a momentary increase in electrical resistance (impedance). The magnitude of the pulse is proportional to cell volume. The number of pulses gives the cell count.", blueprintCategory: "Hematology", subtopic: "Automated Hematology Analyzers", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know impedance counting principle" },
  { stem: "A patient with chronic liver disease has a prolonged PT and aPTT, low fibrinogen, elevated D-dimer, and thrombocytopenia. Is this DIC or liver disease?", options: ["Definitely DIC", "Definitely liver disease", "Both produce similar findings — Factor VIII level helps differentiate", "Neither — this is vitamin K deficiency"], correctAnswer: 2, rationaleLong: "DIC and severe liver disease can produce nearly identical coagulation profiles. The key differentiating test is Factor VIII level: in DIC, Factor VIII is consumed (decreased), while in liver disease, Factor VIII is normal or elevated (Factor VIII is produced by endothelial cells, not hepatocytes, and is an acute-phase reactant). Also, in liver disease, thrombin time may be prolonged due to dysfibrinogenemia.", blueprintCategory: "Hematology", subtopic: "Leukemias & Lymphomas", difficulty: 5, cognitiveLevel: "analysis", learningObjective: "Differentiate DIC from liver disease" },
];

const hemosBatch3: MltQuestion[] = [
  { stem: "Factor V Leiden is the most common inherited cause of:", options: ["Bleeding disorder", "Venous thromboembolism", "Platelet dysfunction", "Hemophilia"], correctAnswer: 1, rationaleLong: "Factor V Leiden is a point mutation (Arg506Gln) in Factor V that makes it resistant to inactivation by activated Protein C (APC resistance). It is the most common inherited thrombophilia, present in ~5% of Caucasians. Heterozygotes have a 5-10x increased risk of venous thrombosis; homozygotes have 50-100x increased risk.", blueprintCategory: "Hemostasis / Coagulation", subtopic: "Thrombophilia Screening", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know Factor V Leiden" },
  { stem: "Platelet aggregation studies show absent response to ristocetin but normal response to ADP, collagen, and epinephrine. The most likely diagnosis is:", options: ["Glanzmann thrombasthenia", "Von Willebrand disease or Bernard-Soulier syndrome", "Storage pool disease", "Aspirin effect"], correctAnswer: 1, rationaleLong: "Ristocetin induces platelet aggregation by activating VWF binding to platelet GPIb. Absent ristocetin-induced platelet aggregation (RIPA) with normal responses to other agonists indicates either VWD (missing VWF) or Bernard-Soulier syndrome (missing GPIb receptor). VWF antigen and activity levels differentiate between these two conditions.", blueprintCategory: "Hemostasis / Coagulation", subtopic: "Platelet Function Testing", difficulty: 4, cognitiveLevel: "analysis", learningObjective: "Interpret platelet aggregation patterns" },
  { stem: "Which direct oral anticoagulant (DOAC) directly inhibits Factor Xa?", options: ["Dabigatran", "Rivaroxaban", "Warfarin", "Heparin"], correctAnswer: 1, rationaleLong: "Rivaroxaban (Xarelto), apixaban (Eliquis), and edoxaban (Savaysa) are direct Factor Xa inhibitors. Dabigatran (Pradaxa) is a direct thrombin (Factor IIa) inhibitor. DOACs have predictable pharmacokinetics and generally do not require routine monitoring, unlike warfarin and heparin.", blueprintCategory: "Hemostasis / Coagulation", subtopic: "Anticoagulant Therapy Monitoring", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know DOAC mechanisms" },
  { stem: "Thrombotic thrombocytopenic purpura (TTP) is caused by deficiency of:", options: ["Factor VIII", "ADAMTS13 (VWF-cleaving protease)", "Protein C", "Antithrombin III"], correctAnswer: 1, rationaleLong: "TTP is caused by severe deficiency of ADAMTS13, the metalloprotease that cleaves ultra-large VWF multimers. Without ADAMTS13, ultra-large VWF multimers cause spontaneous platelet adhesion and aggregation in small vessels. The classic pentad is: thrombocytopenia, MAHA (schistocytes), neurological symptoms, renal dysfunction, and fever. Plasma exchange is the treatment.", blueprintCategory: "Hemostasis / Coagulation", subtopic: "DIC", difficulty: 4, cognitiveLevel: "recall", learningObjective: "Know TTP pathophysiology" },
  { stem: "Aspirin prevents platelet aggregation by irreversibly inhibiting:", options: ["Thromboxane A2 synthase", "Cyclooxygenase-1 (COX-1)", "Phospholipase A2", "ADP receptors"], correctAnswer: 1, rationaleLong: "Aspirin irreversibly acetylates COX-1 in platelets, preventing the conversion of arachidonic acid to thromboxane A2 (TXA2), a potent platelet activator and vasoconstrictor. Since platelets lack nuclei, they cannot synthesize new COX-1, so the effect lasts the lifetime of the platelet (7-10 days).", blueprintCategory: "Hemostasis / Coagulation", subtopic: "Platelet Function Testing", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know aspirin mechanism" },
];

const microBatch3: MltQuestion[] = [
  { stem: "A CSF culture grows small, gram-positive rods with tumbling motility that produce narrow zones of beta-hemolysis on blood agar. The organism is most likely:", options: ["Corynebacterium diphtheriae", "Listeria monocytogenes", "Bacillus cereus", "Lactobacillus species"], correctAnswer: 1, rationaleLong: "Listeria monocytogenes is a small gram-positive rod (may appear coccobacillary) with characteristic tumbling motility at 25°C and narrow zones of beta-hemolysis. It is a significant cause of meningitis in neonates, elderly, pregnant women, and immunocompromised patients. Listeria grows at 4°C (cold enrichment).", blueprintCategory: "Microbiology", subtopic: "Gram-Positive Cocci", difficulty: 3, cognitiveLevel: "application", learningObjective: "Identify Listeria from CSF culture" },
  { stem: "Specimen collection for anaerobic culture should avoid:", options: ["Using anaerobic transport media", "Collecting aspirates", "Exposing the specimen to air", "Using syringes without needles"], correctAnswer: 2, rationaleLong: "Anaerobic bacteria are killed by oxygen exposure. Specimens for anaerobic culture should be collected by aspiration (avoiding surface contamination with normal flora), transported in anaerobic transport media (pre-reduced), and processed promptly. Swabs are generally unacceptable for anaerobic culture because they expose organisms to oxygen.", blueprintCategory: "Microbiology", subtopic: "Anaerobes", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know anaerobic specimen collection" },
  { stem: "E. coli O157:H7 differs from typical E. coli in that it:", options: ["Is oxidase-positive", "Does not ferment sorbitol on SMAC agar", "Is gram-positive", "Produces hydrogen sulfide"], correctAnswer: 1, rationaleLong: "E. coli O157:H7 (enterohemorrhagic E. coli/EHEC) does not ferment sorbitol, so it produces colorless colonies on sorbitol-MacConkey (SMAC) agar, while typical E. coli ferments sorbitol (pink colonies). E. coli O157:H7 produces Shiga toxin and causes hemorrhagic colitis and hemolytic uremic syndrome (HUS).", blueprintCategory: "Microbiology", subtopic: "Gram-Negative Rods (Enterobacteriaceae)", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know E. coli O157:H7 characteristics" },
  { stem: "A sputum specimen is considered acceptable for culture if the Gram stain shows:", options: [">25 squamous epithelial cells per low-power field", "<10 squamous epithelial cells and >25 WBCs per low-power field", ">50 epithelial cells and <10 WBCs", "Any amount of organisms"], correctAnswer: 1, rationaleLong: "A quality sputum specimen should have <10 squamous epithelial cells (SECs) per low-power field (10x) and >25 WBCs/lpf. High SECs indicate oropharyngeal contamination (saliva, not sputum). Specimens with >25 SECs/lpf should be rejected and a new specimen requested (except for Legionella and mycobacterial cultures).", blueprintCategory: "Microbiology", subtopic: "Culture & Sensitivity (C&S)", difficulty: 2, cognitiveLevel: "application", learningObjective: "Assess sputum specimen quality" },
  { stem: "The MIC (minimum inhibitory concentration) is defined as:", options: ["The lowest concentration of antibiotic that kills 99.9% of organisms", "The lowest concentration of antibiotic that inhibits visible growth", "The highest concentration tolerated by the patient", "The concentration that achieves peak serum level"], correctAnswer: 1, rationaleLong: "MIC is the lowest concentration of an antimicrobial agent that inhibits visible growth of an organism after 16-20 hours of incubation. It is determined by broth dilution or agar dilution methods. The MBC (minimum bactericidal concentration) is the lowest concentration that kills 99.9% of organisms. MIC determines S/I/R interpretation.", blueprintCategory: "Microbiology", subtopic: "Antimicrobial Susceptibility Testing (AST)", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Define MIC" },
  { stem: "Carbapenem-resistant Enterobacteriaceae (CRE) represent a critical threat because:", options: ["They are easily treated with oral antibiotics", "Carbapenems are often the last-line therapy, and resistance leaves few treatment options", "They only cause skin infections", "They are not transmissible between patients"], correctAnswer: 1, rationaleLong: "CRE are a critical public health threat because carbapenems (imipenem, meropenem, ertapenem) are often the last effective antibiotics against multidrug-resistant gram-negative infections. CRE produce carbapenemases (KPC, NDM, OXA-48) that hydrolyze carbapenems. Treatment options are limited to colistin, tigecycline, and newer agents (ceftazidime-avibactam).", blueprintCategory: "Microbiology", subtopic: "Antimicrobial Susceptibility Testing (AST)", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know CRE significance" },
  { stem: "Which of the following is the best medium for recovery of fungi from clinical specimens?", options: ["Blood agar", "MacConkey agar", "Brain heart infusion (BHI) agar with chloramphenicol and gentamicin", "Mueller-Hinton agar"], correctAnswer: 2, rationaleLong: "BHI agar supplemented with antibiotics (chloramphenicol, gentamicin) and cycloheximide is commonly used for fungal recovery from clinical specimens. The antibiotics suppress bacterial contamination. Sabouraud dextrose agar (SDA) is also standard. Cultures should be incubated at both 25-30°C and 37°C for dimorphic fungi.", blueprintCategory: "Microbiology", subtopic: "Culture & Sensitivity (C&S)", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know fungal culture media" },
  { stem: "Chlamydia trachomatis cannot be cultured on routine agar because:", options: ["It requires anaerobic conditions", "It is an obligate intracellular pathogen requiring cell culture", "It only grows at 42°C", "It requires special blood supplements"], correctAnswer: 1, rationaleLong: "Chlamydia trachomatis is an obligate intracellular bacterium that requires host cells for replication. Traditional culture uses McCoy cell monolayers. However, nucleic acid amplification tests (NAATs) have largely replaced culture due to superior sensitivity and ease of use. NAATs can be performed on urine and swab specimens.", blueprintCategory: "Microbiology", subtopic: "Culture & Sensitivity (C&S)", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know Chlamydia culture requirements" },
  { stem: "The dimorphic fungi include:", options: ["Aspergillus and Candida", "Histoplasma, Blastomyces, and Coccidioides", "Cryptococcus and Mucor", "Trichophyton and Microsporum"], correctAnswer: 1, rationaleLong: "Dimorphic fungi exist as molds at environmental temperature (25°C) and as yeasts at body temperature (37°C) — 'mold in the cold, yeast in the heat.' The classic dimorphic fungi are Histoplasma capsulatum, Blastomyces dermatitidis, Coccidioides immitis, Paracoccidioides brasiliensis, Talaromyces (Penicillium) marneffei, and Sporothrix schenckii.", blueprintCategory: "Microbiology", subtopic: "Biochemical Identification", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know dimorphic fungi" },
  { stem: "Nocardia species differ from Actinomyces species in that Nocardia:", options: ["Is strictly anaerobic", "Is aerobic and partially acid-fast", "Is gram-negative", "Forms sulfur granules"], correctAnswer: 1, rationaleLong: "Nocardia is aerobic and partially acid-fast (modified acid-fast stain with weak decolorizer). Actinomyces is anaerobic and not acid-fast. Both are branching gram-positive rods. Actinomyces forms 'sulfur granules' (yellow masses of organisms). Nocardia causes pulmonary infections and brain abscesses in immunocompromised patients.", blueprintCategory: "Microbiology", subtopic: "Biochemical Identification", difficulty: 4, cognitiveLevel: "application", learningObjective: "Differentiate Nocardia from Actinomyces" },
];

const bbBatch3: MltQuestion[] = [
  { stem: "A patient's antibody panel shows reactivity consistent with anti-E. The technologist should select donor units that are:", options: ["E-positive", "E-negative and crossmatch compatible", "Any Rh type", "D-negative only"], correctAnswer: 1, rationaleLong: "When a clinically significant antibody is identified, antigen-negative donor units must be selected and crossmatch compatible at the AHG phase. For anti-E, E-negative (E-) units should be selected. The units should also be ABO/Rh compatible and crossmatch compatible to ensure there are no additional antibodies.", blueprintCategory: "Immunohematology / Blood Banking", subtopic: "Antibody Identification", difficulty: 2, cognitiveLevel: "application", learningObjective: "Select compatible units for antibody patients" },
  { stem: "Polyspecific AHG reagent contains antibodies to:", options: ["IgG only", "IgG and C3d (complement)", "IgM only", "IgA and IgE"], correctAnswer: 1, rationaleLong: "Polyspecific AHG (anti-human globulin) reagent contains both anti-IgG and anti-C3d (complement). It is used as the initial reagent in DAT and crossmatching. If the polyspecific AHG is positive, monospecific reagents (anti-IgG and anti-C3d separately) are used to determine which component is coating the RBCs.", blueprintCategory: "Immunohematology / Blood Banking", subtopic: "Direct & Indirect Antiglobulin Test (DAT/IAT)", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know AHG reagent composition" },
  { stem: "Coombs control cells (check cells) are added after a negative AHG test to:", options: ["Enhance weak reactions", "Verify that the AHG reagent was added and is functional", "Detect complement-only sensitization", "Perform forward typing"], correctAnswer: 1, rationaleLong: "Coombs control cells (IgG-coated RBCs) are added after a negative AHG test to verify that: AHG was added, AHG was functional, and adequate washing was performed (residual serum proteins would neutralize AHG). If Coombs control cells do not agglutinate, the negative test is invalid and must be repeated.", blueprintCategory: "Immunohematology / Blood Banking", subtopic: "Direct & Indirect Antiglobulin Test (DAT/IAT)", difficulty: 3, cognitiveLevel: "application", learningObjective: "Know Coombs control cells purpose" },
  { stem: "Which blood group system antibodies are characteristically associated with evanescence (decreasing below detectable levels)?", options: ["ABO antibodies", "Rh antibodies", "Kidd (Jk) antibodies", "Lewis antibodies"], correctAnswer: 2, rationaleLong: "Kidd system antibodies (anti-Jka, anti-Jkb) are notorious for evanescence — they can fall below detectable levels between exposures. This makes them dangerous because they may not be detected on pre-transfusion antibody screening. Upon re-exposure, an anamnestic response rapidly produces anti-Jk antibodies, causing delayed hemolytic transfusion reactions.", blueprintCategory: "Immunohematology / Blood Banking", subtopic: "Antibody Identification", difficulty: 4, cognitiveLevel: "recall", learningObjective: "Know evanescent antibodies" },
  { stem: "An Rh-negative patient has received 2 units of Rh-positive RBCs in an emergency. To prevent anti-D formation, the treatment of choice is:", options: ["No treatment available", "Administer RhIG (multiple vials based on volume of Rh-positive RBCs)", "Plasmapheresis", "Exchange transfusion"], correctAnswer: 1, rationaleLong: "RhIG can be administered to prevent anti-D formation after inadvertent Rh-positive transfusion to an Rh-negative recipient. Each vial of RhIG (300 μg) covers approximately 15 mL of Rh-positive RBCs (30 mL of whole blood). For 2 units of RBCs (~400 mL), multiple vials would be needed. The calculation uses the Kleihauer-Betke test or flow cytometry.", blueprintCategory: "Immunohematology / Blood Banking", subtopic: "Hemolytic Disease of the Fetus & Newborn (HDFN)", difficulty: 4, cognitiveLevel: "application", learningObjective: "Manage Rh-positive transfusion to Rh-negative patient" },
];

const uaBatch3: MltQuestion[] = [
  { stem: "Renal tubular epithelial (RTE) cells in urine sediment are clinically significant because they indicate:", options: ["Lower urinary tract contamination", "Renal tubular damage", "Squamous contamination", "Normal finding"], correctAnswer: 1, rationaleLong: "Renal tubular epithelial (RTE) cells originate from the nephron and their presence in increased numbers indicates renal tubular damage. They are seen in acute tubular necrosis (ATN), transplant rejection, drug toxicity (aminoglycosides, cisplatin), and pyelonephritis. RTE cells are round with a large, eccentric nucleus.", blueprintCategory: "Urinalysis & Body Fluids", subtopic: "Microscopic Sediment Analysis", difficulty: 3, cognitiveLevel: "application", learningObjective: "Know RTE cell significance" },
  { stem: "A transudative effusion is caused by:", options: ["Infection", "Systemic factors like CHF or cirrhosis (altered hydrostatic/oncotic pressure)", "Malignancy", "Pancreatitis"], correctAnswer: 1, rationaleLong: "Transudates are caused by systemic conditions that alter hydrostatic pressure (CHF — fluid pushed out) or oncotic pressure (cirrhosis, nephrotic syndrome — fluid not held in). They have low protein, low LDH, and few cells. Exudates are caused by local factors (infection, malignancy, inflammation) with high protein and LDH.", blueprintCategory: "Urinalysis & Body Fluids", subtopic: "Serous Fluids (Pleural, Peritoneal, Pericardial)", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know transudative effusion causes" },
  { stem: "Which urinalysis finding is most specific for diabetes mellitus?", options: ["Hematuria", "Glucosuria with ketonuria", "Proteinuria alone", "Bilirubinuria"], correctAnswer: 1, rationaleLong: "Glucosuria (glucose in urine) occurs when blood glucose exceeds the renal threshold (~180 mg/dL). Ketonuria in combination with glucosuria strongly suggests diabetic ketoacidosis or poorly controlled diabetes. The renal threshold can be lowered in pregnancy and renal disease, causing glucosuria at lower blood glucose levels.", blueprintCategory: "Urinalysis & Body Fluids", subtopic: "Chemical Examination (Dipstick)", difficulty: 2, cognitiveLevel: "application", learningObjective: "Correlate urinalysis with diabetes" },
  { stem: "A CSF specimen must be tested immediately for which analyte?", options: ["Protein", "Glucose", "Cell count and differential", "All CSF tests should be performed immediately"], correctAnswer: 2, rationaleLong: "CSF cell counts and differentials must be performed immediately because cells (especially neutrophils) begin to degenerate within 1 hour, and WBCs can decrease by 40% within 2 hours at room temperature. Glucose and protein are more stable but should also be analyzed promptly. For culture, CSF should be processed immediately.", blueprintCategory: "Urinalysis & Body Fluids", subtopic: "Cerebrospinal Fluid (CSF)", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know CSF testing priorities" },
  { stem: "Broad casts form in:", options: ["Normal-sized tubules", "Dilated or atrophied collecting ducts (indicating chronic renal disease)", "The bladder", "The ureter"], correctAnswer: 1, rationaleLong: "Broad casts (also called renal failure casts) are wider than other casts because they form in dilated or atrophied tubules and collecting ducts. Their presence indicates chronic renal disease with significant nephron loss. They may be hyaline, granular, or waxy in composition. Their large size indicates they come from large-diameter tubules.", blueprintCategory: "Urinalysis & Body Fluids", subtopic: "Microscopic Sediment Analysis", difficulty: 4, cognitiveLevel: "recall", learningObjective: "Know broad cast significance" },
];

const immBatch3: MltQuestion[] = [
  { stem: "Which of the following is a Type III (immune complex) hypersensitivity reaction?", options: ["Anaphylaxis", "Autoimmune hemolytic anemia", "Serum sickness", "Contact dermatitis"], correctAnswer: 2, rationaleLong: "Type III hypersensitivity is mediated by antigen-antibody immune complexes that deposit in tissues, activate complement, and cause inflammation. Serum sickness (after exposure to foreign protein/drugs), post-streptococcal glomerulonephritis, lupus nephritis, and Arthus reaction are examples. The deposited complexes cause tissue damage through complement activation and neutrophil recruitment.", blueprintCategory: "Immunology / Serology", subtopic: "Hypersensitivity Reactions", difficulty: 3, cognitiveLevel: "application", learningObjective: "Identify Type III hypersensitivity examples" },
  { stem: "The hepatitis B 'window period' is characterized by:", options: ["HBsAg positive, anti-HBs positive", "HBsAg negative, anti-HBs negative, anti-HBc IgM positive", "All markers negative", "HBeAg positive, HBsAg negative"], correctAnswer: 1, rationaleLong: "The window period occurs between the disappearance of HBsAg and the appearance of anti-HBs. During this time, anti-HBc (total or IgM) may be the only positive marker, making it the 'core window.' Anti-HBc IgM indicates recent infection. This window can last several weeks and represents a period when HBV infection could be missed without anti-HBc testing.", blueprintCategory: "Immunology / Serology", subtopic: "Hepatitis Serology (HBsAg, Anti-HBc, Anti-HCV)", difficulty: 4, cognitiveLevel: "analysis", learningObjective: "Understand HBV window period" },
  { stem: "Type IV (delayed-type) hypersensitivity is mediated by:", options: ["IgE antibodies", "IgG antibodies", "T lymphocytes (cell-mediated, no antibodies)", "Complement activation"], correctAnswer: 2, rationaleLong: "Type IV hypersensitivity is the only type mediated by T lymphocytes rather than antibodies. It takes 24-72 hours to develop (delayed). Examples include tuberculin skin test (PPD), contact dermatitis (poison ivy), transplant rejection, and granulomatous inflammation. Sensitized T cells release cytokines that recruit and activate macrophages.", blueprintCategory: "Immunology / Serology", subtopic: "Hypersensitivity Reactions", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know Type IV hypersensitivity mechanism" },
  { stem: "Which serological test result pattern indicates recovery from hepatitis B with immunity?", options: ["HBsAg+, anti-HBc+, anti-HBs-", "HBsAg-, anti-HBc+, anti-HBs+", "HBsAg-, anti-HBc-, anti-HBs+", "HBsAg+, anti-HBc-, anti-HBs+"], correctAnswer: 1, rationaleLong: "Recovery from hepatitis B shows: HBsAg negative (virus cleared), anti-HBc positive (indicates past infection), and anti-HBs positive (protective immunity developed). This distinguishes natural immunity (anti-HBc+, anti-HBs+) from vaccine immunity (anti-HBs+ only, anti-HBc negative because there was never actual infection).", blueprintCategory: "Immunology / Serology", subtopic: "Hepatitis Serology (HBsAg, Anti-HBc, Anti-HCV)", difficulty: 3, cognitiveLevel: "application", learningObjective: "Interpret HBV recovery serology" },
];

const labBatch3: MltQuestion[] = [
  { stem: "The 10x Westgard rule is violated when:", options: ["Any 10 consecutive QC results fall on the same side of the mean", "10 results exceed 3 SD", "10 different analytes fail QC", "QC is run 10 times consecutively"], correctAnswer: 0, rationaleLong: "The 10x rule is violated when 10 consecutive QC results fall on the same side of the mean (all above or all below). This indicates a systematic error (shift or bias) even though individual results may be within acceptable limits. It detects small but persistent shifts that might not trigger other Westgard rules.", blueprintCategory: "Laboratory Operations & Quality Management", subtopic: "Quality Control (Levey-Jennings, Westgard Rules)", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Know the 10x Westgard rule" },
  { stem: "Chain of custody documentation is required for:", options: ["All routine laboratory specimens", "Forensic and legal drug testing specimens", "Only blood bank specimens", "Quality control materials"], correctAnswer: 1, rationaleLong: "Chain of custody (COC) documentation is required for all forensic, workplace, and legal drug testing to ensure specimen integrity and prevent tampering. COC tracks the specimen from collection through analysis and reporting, documenting every person who handled the specimen. Proper COC is essential for results to be legally defensible.", blueprintCategory: "Laboratory Operations & Quality Management", subtopic: "Laboratory Safety (Chemical, Biological, Radiation)", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know chain of custody requirements" },
  { stem: "A laboratory notices a downward trend in QC results over 5 consecutive days. The most likely cause is:", options: ["Random error", "Deteriorating reagent or calibration drift", "Incorrect QC material", "Normal variation"], correctAnswer: 1, rationaleLong: "A progressive downward trend over multiple days suggests systematic deterioration, most commonly due to reagent degradation (loss of reactivity), calibration drift, or deterioration of the QC material itself. Trends are detected early by Levey-Jennings chart review. Corrective action may include reagent replacement, recalibration, or lamp/electrode replacement.", blueprintCategory: "Laboratory Operations & Quality Management", subtopic: "Quality Control (Levey-Jennings, Westgard Rules)", difficulty: 3, cognitiveLevel: "application", learningObjective: "Identify causes of QC trends" },
  { stem: "The term 'analytical sensitivity' of a test refers to:", options: ["The ability to detect true positives", "The lowest concentration that can be reliably detected (limit of detection)", "The ability to exclude true negatives", "The reproducibility of results"], correctAnswer: 1, rationaleLong: "Analytical sensitivity (limit of detection, LOD) is the lowest concentration of an analyte that can be reliably detected and distinguished from zero (blank) by the measurement procedure. It differs from clinical (diagnostic) sensitivity, which is the ability of a test to correctly identify patients who have the disease (true positive rate).", blueprintCategory: "Laboratory Operations & Quality Management", subtopic: "Quality Assurance Programs", difficulty: 3, cognitiveLevel: "recall", learningObjective: "Distinguish analytical from clinical sensitivity" },
  { stem: "A laboratory performs method validation. Which of the following is NOT a required component?", options: ["Accuracy (comparison with reference method)", "Precision (within-run and between-run)", "Patient satisfaction survey", "Reportable range (analytical measurement range)"], correctAnswer: 2, rationaleLong: "Method validation requires: accuracy (trueness, comparison study), precision (repeatability and reproducibility), reportable range (linearity), reference range verification, detection limit, analytical specificity (interferences), and carryover assessment. Patient satisfaction is important for the institution but is not part of method validation.", blueprintCategory: "Laboratory Operations & Quality Management", subtopic: "Quality Assurance Programs", difficulty: 2, cognitiveLevel: "recall", learningObjective: "Know method validation components" },
  { stem: "Which of the following is the correct response to a chemical spill in the laboratory?", options: ["Clean it up immediately without PPE", "Evacuate the building", "Consult the SDS, don PPE, contain the spill, and clean with appropriate materials", "Call the fire department"], correctAnswer: 2, rationaleLong: "For chemical spills: 1) Alert others in the area, 2) Consult the SDS for the specific chemical, 3) Don appropriate PPE, 4) Contain the spill (absorbent materials), 5) Clean with appropriate neutralizing agents or absorbents, 6) Dispose of waste properly, 7) Report and document the incident. For large or hazardous spills, evacuate and call emergency services.", blueprintCategory: "Laboratory Operations & Quality Management", subtopic: "Laboratory Safety (Chemical, Biological, Radiation)", difficulty: 2, cognitiveLevel: "application", learningObjective: "Know chemical spill response" },
];

const allBatch3: MltQuestion[] = [
  ...chemBatch3,
  ...hemBatch3,
  ...hemosBatch3,
  ...microBatch3,
  ...bbBatch3,
  ...uaBatch3,
  ...immBatch3,
  ...labBatch3,
];

async function seed() {
  const databaseUrl = process.env.PROD_DATABASE_URL || process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error("DATABASE_URL not set");
    process.exit(1);
  }

  const pool = new Pool({ connectionString: databaseUrl });

  console.log(`Batch 3 — Total questions to insert: ${allBatch3.length}`);

  const distribution: Record<string, number> = {};
  const diffDist: Record<number, number> = {};
  const cogDist: Record<string, number> = {};

  for (const q of allBatch3) {
    distribution[q.blueprintCategory] = (distribution[q.blueprintCategory] || 0) + 1;
    diffDist[q.difficulty] = (diffDist[q.difficulty] || 0) + 1;
    cogDist[q.cognitiveLevel] = (cogDist[q.cognitiveLevel] || 0) + 1;
  }

  console.log("Batch 3 distribution by discipline:", distribution);
  console.log("Batch 3 distribution by difficulty:", diffDist);
  console.log("Batch 3 distribution by cognitive level:", cogDist);

  let inserted = 0;
  let errors = 0;

  for (let i = 0; i < allBatch3.length; i++) {
    const q = allBatch3[i];
    try {
      await pool.query(
        `INSERT INTO allied_questions (
          id, career_type, stem, options, correct_answer, rationale_long,
          learning_objective, blueprint_category, subtopic, difficulty,
          cognitive_level, question_type, status, created_at
        ) VALUES (
          gen_random_uuid(), 'mlt', $1, $2, $3, $4,
          $5, $6, $7, $8,
          $9, 'mcq', 'active', NOW()
        )`,
        [
          q.stem,
          JSON.stringify(q.options),
          q.correctAnswer,
          q.rationaleLong,
          q.learningObjective,
          q.blueprintCategory,
          q.subtopic,
          q.difficulty,
          q.cognitiveLevel,
        ]
      );
      inserted++;
    } catch (e: any) {
      console.error(`Error inserting question ${i + 1}: ${e.message}`);
      errors++;
    }
  }

  console.log(`\nBatch 3 Inserted: ${inserted}, Errors: ${errors}`);

  const totalResult = await pool.query("SELECT COUNT(*) as cnt FROM allied_questions WHERE career_type ILIKE '%mlt%' AND status = 'active'");
  console.log(`Total active MLT questions in database: ${totalResult.rows[0].cnt}`);

  const byCat = await pool.query("SELECT blueprint_category, COUNT(*) as cnt FROM allied_questions WHERE career_type ILIKE '%mlt%' AND status = 'active' GROUP BY blueprint_category ORDER BY cnt DESC");
  console.log('\nFinal distribution by discipline:');
  byCat.rows.forEach((r: any) => console.log(`  ${r.blueprint_category}: ${r.cnt}`));

  const byDiff = await pool.query("SELECT difficulty, COUNT(*) as cnt FROM allied_questions WHERE career_type ILIKE '%mlt%' AND status = 'active' GROUP BY difficulty ORDER BY difficulty");
  console.log('\nFinal distribution by difficulty:');
  byDiff.rows.forEach((r: any) => console.log(`  Difficulty ${r.difficulty}: ${r.cnt}`));

  const byCog = await pool.query("SELECT cognitive_level, COUNT(*) as cnt FROM allied_questions WHERE career_type ILIKE '%mlt%' AND status = 'active' GROUP BY cognitive_level ORDER BY cnt DESC");
  console.log('\nFinal distribution by cognitive level:');
  byCog.rows.forEach((r: any) => console.log(`  ${r.cognitive_level}: ${r.cnt}`));

  await pool.end();
}

seed().catch(console.error);
