import crypto from "crypto";
import pg from "pg";
const pool = new pg.Pool({ host: process.env.PGHOST||"helium", user: process.env.PGUSER||"postgres", password: process.env.PGPASSWORD||"password", database: process.env.PGDATABASE||"heliumdb", ssl:false });
function sh(t:string):string{return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16);}
const O=(l:string,t:string)=>({label:l,text:t});
interface Q{tier:string;exam:string;stem:string;options:{label:string;text:string}[];ca:string[];rat:string;diff:number;tags:string[];topic:string;sub:string;rs:string;cp:string;bs:string;}

function build():Q[]{
  const qs:Q[]=[];
  const pn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // NCLEX-RN Batch 29
  rn("Pharmacology","Nitroprusside ICU","Physiological Integrity",4,
    "An RN in the ICU is administering nitroprusside (Nipride) for hypertensive emergency. Which precaution is UNIQUE to this medication?",
    [O("A","Nitroprusside has no unique precautions beyond standard IV medication safety"),O("B","Protect the infusion from LIGHT: nitroprusside is extremely light-sensitive and degrades when exposed to light; the IV bag and tubing must be wrapped in OPAQUE (foil or amber) covering; also monitor for CYANIDE TOXICITY with prolonged infusion (>48 hours or high doses): nitroprusside is metabolized to CYANIDE; signs include metabolic acidosis, tachycardia, altered mental status, seizures; treatment includes sodium THIOSULFATE and hydroxocobalamin; requires continuous ARTERIAL blood pressure monitoring (arterial line) due to potent rapid-onset hypotensive effect"),O("C","Nitroprusside can be mixed with any IV solution and exposed to light"),O("D","Nitroprusside has a slow onset and does not require close BP monitoring")],
    ["B"],"Nitroprusside (sodium nitroprusside/Nipride): MECHANISM: direct-acting vasodilator (both arterial AND venous); releases nitric oxide → potent vasodilation → rapid decrease in both preload and afterload → immediate BP reduction. USES: hypertensive EMERGENCY (requires ICU), controlled hypotension during surgery, acute heart failure with elevated SVR. ONSET: within SECONDS. LIGHT SENSITIVITY: nitroprusside DECOMPOSES when exposed to light → forms inactive and potentially toxic products; WRAP the IV bag and tubing in opaque (foil, amber, or light-protective) covering immediately after mixing; discard if the solution turns blue, green, or dark red (indicates degradation). CYANIDE TOXICITY: nitroprusside is metabolized to CYANIDE in the red blood cells; normally, cyanide is converted to thiocyanate by rhodanese (a hepatic enzyme using thiosulfate as a cofactor) → thiocyanate is renally excreted. Risk increases with: prolonged infusion (>48 hours), high doses (>2 mcg/kg/min), renal impairment (thiocyanate accumulation), hepatic impairment (decreased cyanide metabolism). CYANIDE TOXICITY signs: unexplained metabolic (lactic) acidosis, tachycardia, altered mental status, seizures, cherry-red skin (rarely seen), coma. TREATMENT: sodium THIOSULFATE (provides sulfur substrate for rhodanese to convert cyanide to thiocyanate), hydroxocobalamin (binds cyanide directly), amyl nitrite (creates methemoglobin which binds cyanide). MONITORING: continuous ARTERIAL LINE blood pressure monitoring (mandatory - the drug's potent and rapid effect requires beat-to-beat BP measurement), cyanide and thiocyanate levels (with prolonged use), ABGs (metabolic acidosis = early sign of cyanide toxicity).",
    "Nitroprusside: wrap in opaque covering (light-sensitive); cyanide toxicity risk >48hrs; arterial line required for continuous BP monitoring; thiosulfate = antidote for cyanide", ["nitroprusside","light-sensitive","cyanide-toxicity","hypertensive-emergency","ICU"]);

  rn("Renal","Dialysis Access Care","Physiological Integrity",2,
    "An RN is caring for a patient with a left arm arteriovenous fistula (AVF) for hemodialysis. Which assessment finding confirms the fistula is functioning properly?",
    [O("A","The fistula site should be silent on auscultation"),O("B","A palpable THRILL (vibration) and an audible BRUIT (buzzing/whooshing sound) over the fistula site: the thrill is a vibration felt when lightly palpating over the anastomosis (where the artery connects to the vein); the bruit is heard with a stethoscope; both indicate blood flow through the fistula; ABSENCE of thrill and bruit suggests THROMBOSIS (clotting) and is an EMERGENCY; the RN should NEVER take blood pressure, perform venipuncture, or start an IV in the AFFECTED arm; elevate the arm to reduce edema; assess circulation distal to the fistula (hand warmth, color, pulses)"),O("C","The fistula arm should feel cold and pulseless"),O("D","Blood pressure should be taken in the fistula arm to assess blood flow")],
    ["B"],"AVF (Arteriovenous Fistula) care: an AVF is surgically created by connecting an artery directly to a vein (usually radial artery to cephalic vein in the forearm) → the high-pressure arterial blood flows into the vein → the vein dilates and thickens (arterializes) over 2-6 months (maturation period) → creates a large, easily accessible vessel for hemodialysis access. AVF is the PREFERRED access for hemodialysis (lowest infection rate, longest patency compared to grafts or catheters). ASSESSMENT: THRILL: a palpable VIBRATION (buzzing sensation) felt when lightly placing fingers over the anastomosis site; caused by turbulent blood flow at the arteriovenous connection. BRUIT: an audible WHOOSHING/BUZZING sound heard with a stethoscope over the fistula; also caused by turbulent blood flow. Thrill + Bruit = PATENT (functioning) fistula. ABSENCE of thrill and bruit = possible THROMBOSIS → notify the physician immediately (may require thrombectomy or revision). NURSING CARE AND RESTRICTIONS: NEVER take BLOOD PRESSURE on the fistula arm (cuff compression → occlusion → thrombosis). NEVER perform VENIPUNCTURE or start an IV in the fistula arm. NEVER draw BLOOD from the fistula (except for dialysis-related labs). Do NOT apply tight clothing, jewelry, or restrictive dressings. Do NOT carry heavy objects with the fistula arm. Do NOT sleep on the fistula arm (prolonged compression). MONITORING: check thrill and bruit at least every shift (and more frequently in the immediate post-operative period). Assess the hand distal to the fistula: warmth, color, sensation, movement, capillary refill (if hand is cool, pale, numb, or painful → steal syndrome: the fistula is diverting too much blood from the hand). Monitor for signs of INFECTION: redness, warmth, swelling, drainage, fever.",
    "AVF: thrill (palpable vibration) + bruit (audible whoosh) = patent; no BP/IV/venipuncture on fistula arm; absence of thrill/bruit = thrombosis emergency", ["AVF","hemodialysis","thrill-bruit","access-care","thrombosis"]);

  rn("Pharmacology","Dopamine Infusion","Physiological Integrity",4,
    "An RN is titrating a dopamine infusion for a patient in septic shock. At which dose range does dopamine primarily stimulate alpha-1 receptors causing vasoconstriction?",
    [O("A","All dose ranges of dopamine produce the same cardiovascular effects"),O("B","HIGH doses (>10 mcg/kg/min) primarily stimulate ALPHA-1 receptors causing VASOCONSTRICTION (increased systemic vascular resistance → increased blood pressure); at LOW doses (1-3 mcg/kg/min), dopamine stimulates DOPAMINERGIC receptors (renal and mesenteric vasodilation → increased urine output, though the clinical significance is debated); at MODERATE doses (3-10 mcg/kg/min), dopamine stimulates BETA-1 receptors (increased heart rate and contractility → increased cardiac output); dose-dependent receptor activation is key to understanding dopamine's clinical effects"),O("C","Low doses cause the most vasoconstriction"),O("D","Dopamine does not have dose-dependent effects on different receptors")],
    ["B"],"Dopamine dose-dependent receptor activation: dopamine is a catecholamine that activates different receptors depending on the DOSE. LOW DOSE (1-3 mcg/kg/min) - 'RENAL DOSE': primarily DOPAMINERGIC receptor activation → renal and mesenteric vasodilation → theoretically increases renal blood flow and urine output; historically called 'renal dose dopamine'; current evidence does NOT support its use for renal protection (large RCTs showed no benefit in preventing acute kidney injury). MODERATE DOSE (3-10 mcg/kg/min) - 'CARDIAC DOSE': primarily BETA-1 receptor activation → increased heart rate (positive chronotropic), increased myocardial contractility (positive inotropic) → increased CARDIAC OUTPUT. Useful for: cardiogenic shock, heart failure with decreased cardiac output. SIDE EFFECTS at this dose: tachycardia, palpitations, increased myocardial oxygen demand. HIGH DOSE (>10 mcg/kg/min) - 'VASOPRESSOR DOSE': primarily ALPHA-1 receptor activation → peripheral VASOCONSTRICTION → increased systemic vascular resistance (SVR) → increased BLOOD PRESSURE. Useful for: severe hypotension, shock. SIDE EFFECTS at this dose: excessive vasoconstriction (tissue ischemia, digital gangrene), dysrhythmias, increased afterload (may worsen heart failure). NURSING: always use a continuous INFUSION PUMP (never gravity drip), preferably through a CENTRAL LINE (extravasation of dopamine → tissue NECROSIS; if peripheral IV must be used, choose a large vein and monitor closely). ANTIDOTE for extravasation: PHENTOLAMINE (alpha-blocker) injected locally into the affected tissue. Monitor: continuous ECG, arterial line BP monitoring, urine output, tissue perfusion (skin color, temperature, capillary refill).",
    "Dopamine: low (1-3) = dopaminergic/renal; moderate (3-10) = beta-1/cardiac; high (>10) = alpha-1/vasoconstriction; central line preferred; phentolamine for extravasation", ["dopamine","dose-dependent","vasoconstriction","septic-shock","titration"]);

  rn("Neurology","Increased ICP Signs","Physiological Integrity",3,
    "An RN is monitoring a patient with a traumatic brain injury. Which finding indicates the EARLIEST sign of increased intracranial pressure (ICP)?",
    [O("A","Cushing triad is the earliest sign of increased ICP"),O("B","CHANGE IN LEVEL OF CONSCIOUSNESS (LOC) is the EARLIEST and most sensitive indicator of increased ICP: restlessness, confusion, irritability, drowsiness, or decreased responsiveness; as ICP increases further, LATER signs include: CUSHING'S TRIAD (HTN with widened pulse pressure + bradycardia + irregular respirations - a LATE and ominous sign indicating brainstem herniation), unilateral PUPIL dilation (ipsilateral to the lesion - CN III compression), projectile vomiting, headache (worse in morning), papilledema, posturing (decerebrate worse than decorticate); use the Glasgow Coma Scale (GCS) for standardized neurological assessment"),O("C","Pupil dilation is always the first sign of increased ICP"),O("D","Headache is a more reliable early indicator than level of consciousness")],
    ["B"],"Increased ICP assessment: NORMAL ICP: 5-15 mmHg. ELEVATED: >20 mmHg. Critical: >40 mmHg. EARLIEST SIGN: CHANGE IN LEVEL OF CONSCIOUSNESS (LOC). LOC is the most sensitive and reliable indicator because the cerebral cortex is the first structure affected by increased pressure. Early changes: restlessness, agitation, confusion, irritability, lethargy, slowed responses, difficulty following commands. PROGRESSIVE SIGNS (as ICP continues to rise): HEADACHE: often worse in the morning (ICP naturally rises during sleep from recumbent position and CO2 retention). PUPILLARY changes: UNILATERAL PUPIL DILATION (mydriasis) - the pupil on the SAME SIDE (ipsilateral) as the lesion dilates and becomes fixed (non-reactive to light) due to compression of CRANIAL NERVE III (oculomotor nerve) against the tentorium cerebelli during transtentorial herniation. If BOTH pupils are fixed and dilated → bilateral herniation → very poor prognosis. VOMITING: projectile vomiting (without nausea - occurs when the vomiting center in the medulla is compressed). PAPILLEDEMA: swelling of the optic disc (seen on fundoscopic exam) from increased CSF pressure transmitted along the optic nerve sheath. POSTURING: DECORTICATE (flexion): arms flexed, legs extended → damage above the brainstem (cortex/internal capsule). DECEREBRATE (extension): arms AND legs extended with pronation → damage to the brainstem → WORSE prognosis. CUSHING'S TRIAD: HYPERTENSION with WIDENED pulse pressure (systolic rises, diastolic stays/drops) + BRADYCARDIA + IRREGULAR RESPIRATIONS (Cheyne-Stokes, ataxic, apneustic). This is a LATE sign indicating brainstem compression/herniation → IMMINENT death without intervention. GLASGOW COMA SCALE: Eye opening (1-4), Verbal response (1-5), Motor response (1-6). Total: 3-15. Severe: ≤8 (intubation required). Moderate: 9-12. Mild: 13-15.",
    "Increased ICP: earliest sign = change in LOC (restlessness, confusion); Cushing's triad (HTN/bradycardia/irregular resp) = LATE/ominous; ipsilateral pupil dilation; decerebrate worse than decorticate", ["increased-ICP","LOC","Cushings-triad","GCS","herniation"]);

  rn("Pharmacology","Antidote Summary","Physiological Integrity",3,
    "An RN needs to quickly recall the antidote for acetaminophen (Tylenol) overdose. A patient presents with nausea and elevated liver enzymes after ingesting a large quantity. What is the SPECIFIC antidote?",
    [O("A","There is no antidote for acetaminophen overdose"),O("B","N-ACETYLCYSTEINE (NAC, Mucomyst/Acetadote): must be administered within 8-10 HOURS of ingestion for maximum effectiveness (can still be beneficial up to 72 hours); NAC works by replenishing GLUTATHIONE stores in the liver (glutathione normally detoxifies the hepatotoxic metabolite NAPQI; in overdose, glutathione is depleted → NAPQI accumulates → hepatocellular NECROSIS); can be given orally (diluted, foul taste/smell) or IV; the Rumack-Matthew nomogram is used to determine the need for NAC based on the serum acetaminophen level at 4+ hours post-ingestion"),O("C","Flumazenil is the antidote for acetaminophen toxicity"),O("D","Naloxone reverses acetaminophen overdose")],
    ["B"],"Acetaminophen overdose and N-acetylcysteine: ACETAMINOPHEN METABOLISM: normally, most acetaminophen is metabolized by the liver through conjugation (glucuronidation and sulfation) → harmless metabolites excreted renally. A small percentage (~5%) is metabolized by cytochrome P450 (CYP2E1) → toxic metabolite NAPQI (N-acetyl-p-benzoquinone imine) → normally immediately detoxified by GLUTATHIONE → harmless mercapturic acid conjugate → excreted. IN OVERDOSE: the conjugation pathways become SATURATED → more acetaminophen is shunted through CYP2E1 → excessive NAPQI production → glutathione stores are DEPLETED → NAPQI accumulates → directly damages HEPATOCYTES → hepatic NECROSIS → LIVER FAILURE. TOXIC DOSE: >150 mg/kg or >7.5-10 g in adults. PHASES: Phase 1 (0-24 hrs): nonspecific: nausea, vomiting, malaise, diaphoresis (often mistaken for gastroenteritis; patients may feel 'fine'). Phase 2 (24-72 hrs): right upper quadrant pain, elevated liver enzymes (AST, ALT rising dramatically), elevated INR, possible oliguria. Phase 3 (72-96 hrs): PEAK HEPATOTOXICITY: jaundice, coagulopathy, encephalopathy, renal failure, possible DEATH from multi-organ failure. Phase 4 (4-14 days): recovery phase (for survivors; the liver regenerates). N-ACETYLCYSTEINE (NAC): MECHANISM: replenishes GLUTATHIONE (provides cysteine, a glutathione precursor), serves as a substitute for glutathione (directly conjugates NAPQI), and has anti-inflammatory/antioxidant effects. TIMING: most effective within 8-10 HOURS of ingestion; effectiveness decreases after 8 hours but is still beneficial up to 72 hours. ROUTES: oral (140 mg/kg loading, then 70 mg/kg q4h × 17 doses) or IV (150 mg/kg loading over 1 hour, then decreasing doses over 20 hours). RUMACK-MATTHEW NOMOGRAM: plot the serum acetaminophen level against the time since ingestion (minimum 4 hours post-ingestion); if the level falls above the treatment line → administer NAC.",
    "Acetaminophen antidote: NAC (N-acetylcysteine); replenishes glutathione; most effective within 8-10 hrs; Rumack-Matthew nomogram guides treatment; liver failure = primary risk", ["NAC","acetaminophen","overdose","glutathione","hepatotoxicity"]);

  // NCLEX-PN Batch 29 - 4 more PN questions (pushing hard to 250)
  pn("Physiological Integrity","Pulse Oximetry LPN","Physiological Integrity",1,
    "An LPN obtains a pulse oximetry reading of 88% on a patient who was previously 97% on room air. What should the LPN do?",
    [O("A","This is within normal range and requires no action"),O("B","Assess the patient IMMEDIATELY: an SpO2 of 88% indicates HYPOXEMIA (normal SpO2 is 95-100%); first troubleshoot the reading (check sensor placement, assess for nail polish which can interfere, check the waveform/signal quality, warm cold fingers, try a different digit); if the reading is accurate, position the patient in HIGH FOWLER'S position (sitting upright to maximize lung expansion), administer supplemental OXYGEN as prescribed or per standing orders, and notify the physician/RN immediately; assess respiratory status (rate, depth, effort, breath sounds, skin color, use of accessory muscles)"),O("C","Recheck in one hour to see if it improves on its own"),O("D","An SpO2 of 88% is normal for most patients")],
    ["B"],"Pulse oximetry interpretation and troubleshooting: NORMAL SpO2: 95-100%. MILD HYPOXEMIA: 90-94%. SIGNIFICANT HYPOXEMIA: <90% (clinical intervention required). CRITICAL: <85% (may indicate impending respiratory failure). FACTORS AFFECTING ACCURACY: POOR PERFUSION (hypotension, hypothermia, peripheral vascular disease → weak signal → inaccurate or no reading), NAIL POLISH (especially dark colors - blue, black, brown → absorb light → falsely LOW readings; clear/light colors have minimal effect), DARK SKIN PIGMENTATION (may overestimate SpO2 by 2-3% in dark-skinned individuals), MOTION ARTIFACT (patient movement → erratic readings), AMBIENT LIGHT (bright overhead lights, direct sunlight → interference), CARBON MONOXIDE POISONING (carboxyhemoglobin absorbs light similarly to oxyhemoglobin → FALSELY NORMAL SpO2 reading even when the patient is severely hypoxic; use co-oximetry for accurate assessment), ANEMIA (SpO2 may read normal despite inadequate oxygen delivery because it measures the percentage of hemoglobin saturated, not the total amount of oxygen carried), METHEMOGLOBINEMIA (falsely reads approximately 85%). NURSING RESPONSE to low SpO2: (1) ASSESS the patient first (does the clinical picture match the reading?). (2) TROUBLESHOOT: reposition the sensor, try a different digit (or earlobe, forehead), remove nail polish, warm cold extremities, check waveform quality. (3) If LOW SpO2 is confirmed: elevate the head of bed (HIGH FOWLER'S for respiratory patients), apply supplemental oxygen per protocol/orders, assess respiratory status comprehensively (RR, depth, effort, accessory muscles, lung sounds, skin color), notify the physician/RN.",
    "SpO2 <90% = significant hypoxemia; troubleshoot sensor first; if confirmed: high Fowler's, O2, notify MD; nail polish, poor perfusion, CO poisoning affect accuracy", ["pulse-oximetry","SpO2","hypoxemia","troubleshooting","respiratory"]);

  pn("Physiological Integrity","Seizure Precautions LPN","Physiological Integrity",2,
    "An LPN is caring for a patient who is actively having a tonic-clonic seizure. What is the PRIORITY nursing action?",
    [O("A","Place a tongue depressor or spoon between the patient's teeth"),O("B","Protect the patient from INJURY: do NOT restrain the patient or force anything into the mouth (this can cause broken teeth, aspiration of foreign objects, or jaw/hand injury); clear the area of hard/sharp objects; guide the patient to the FLOOR if they are standing or sitting; place padding (pillow, folded blanket) under the HEAD; turn the patient onto their SIDE (lateral/recovery position) after the active seizure to maintain an OPEN AIRWAY and allow secretions to drain; note the TIME of seizure onset and duration; stay with the patient; do NOT leave them alone; suction equipment should be available"),O("C","Hold the patient down firmly to prevent movement during the seizure"),O("D","Immediately administer oral medication during the active seizure")],
    ["B"],"Seizure management (tonic-clonic): DURING THE SEIZURE: (1) STAY with the patient (never leave a seizing patient alone). (2) NOTE the TIME: document the onset time and DURATION (status epilepticus = seizure lasting >5 minutes or repeated seizures without regaining consciousness → medical emergency requiring IV benzodiazepines). (3) PROTECT from injury: clear the immediate area of hard, sharp, or dangerous objects; if standing, guide them gently to the FLOOR; DO NOT restrain (restraining can cause injury to both the patient and the nurse). (4) PROTECT THE HEAD: place padding (pillow, folded blanket, jacket) under the head to prevent head injury from striking the floor. (5) AIRWAY: do NOT force anything into the mouth (tongue depressors, fingers, bite blocks → broken teeth, aspiration, jaw injury, bite injuries to the nurse's hand; the patient will NOT swallow their tongue, though they may bite it). Loosen tight clothing around the neck. (6) After the active seizure (tonic-clonic phase): turn to the LATERAL (side-lying/recovery) position → maintains an open airway and allows saliva, blood, or vomit to drain from the mouth (prevents aspiration). (7) Suction if needed (excessive secretions or vomitus). AFTER THE SEIZURE (POSTICTAL PHASE): the patient may be confused, drowsy, have a headache, or be amnestic about the seizure. Provide a safe, quiet environment. Reorient gently. Perform a neurological assessment. Check for injuries (tongue bite, head/body injuries). Document: seizure type, duration, body parts involved, aura (did the patient report a warning?), incontinence, postictal behavior. CALL FOR HELP if: first seizure, seizure lasts >5 minutes, the patient does not regain consciousness, or the patient is injured, pregnant, or diabetic.",
    "Seizure: protect from injury (floor, pad head); do NOT restrain or put anything in mouth; side-lying after seizure; time the duration; >5 min = status epilepticus = emergency", ["seizure","tonic-clonic","safety","side-lying","status-epilepticus"]);

  pn("Physiological Integrity","Wound Healing Stages LPN","Physiological Integrity",1,
    "An LPN is documenting a wound assessment and notes a wound bed filled with beefy red, bumpy tissue. What type of tissue is this and what does it indicate?",
    [O("A","This is necrotic tissue requiring immediate debridement"),O("B","GRANULATION tissue: healthy, beefy RED, moist, granular (bumpy/cobblestone) appearance; indicates POSITIVE wound healing and good blood supply; granulation tissue is composed of new capillaries (angiogenesis), fibroblasts (which produce collagen), and inflammatory cells; it fills the wound bed from the bottom up during the PROLIFERATIVE phase of wound healing; this tissue should be PROTECTED (use moist, non-adherent dressings; do not use wet-to-dry dressings which damage granulation tissue when removed); document as 'wound bed: 100% granulation tissue'"),O("C","Red tissue in a wound always indicates infection"),O("D","All wound tissue appears the same regardless of healing status")],
    ["B"],"Wound tissue types and healing assessment: GRANULATION TISSUE: HEALTHY. Appearance: beefy RED, MOIST, granular/bumpy/cobblestone texture. Composition: new blood vessels (capillaries formed by angiogenesis → explains the red color), fibroblasts (produce collagen to rebuild the extracellular matrix), inflammatory cells (macrophages, neutrophils). Significance: indicates GOOD HEALING and adequate blood supply; occurs during the PROLIFERATIVE PHASE (days 4-21); fills the wound from the bottom up. PROTECT this tissue: use moist, non-adherent dressings; avoid wet-to-dry gauze, cytotoxic agents, and unnecessary mechanical disruption. EPITHELIAL TISSUE: HEALTHY. Appearance: PINK/LIGHT PINK, thin, translucent, smooth; appears as new skin growing from the wound edges inward. Significance: final phase of healing; migrating epithelial cells cover the granulation tissue bed; very FRAGILE → protect from trauma. SLOUGH: UNHEALTHY (needs removal). Appearance: YELLOW, tan, or gray; soft, moist, stringy or firmly adherent tissue. Composition: dead cells, fibrin, debris, WBCs. Significance: delays healing by preventing granulation tissue formation; requires debridement (autolytic, enzymatic, sharp, or mechanical). ESCHAR: UNHEALTHY (needs removal in most cases). Appearance: BLACK or BROWN, hard, dry, leathery, firmly attached. Composition: thick layer of dead, dehydrated tissue. Significance: covers the wound and prevents assessment of wound depth and healing; in MOST cases requires debridement; EXCEPTION: stable, dry, intact eschar on the HEELS may be left in place (acts as a natural biological cover; adequate perfusion to the heel is limited). WOUND ASSESSMENT documentation: wound bed color and tissue type (% granulation, slough, eschar), wound dimensions (length × width × depth), wound edges, exudate (color, amount, odor), periwound skin condition, undermining/tunneling.",
    "Wound tissue: granulation = beefy red, moist, bumpy = HEALTHY; epithelial = pink, smooth = healing; slough = yellow = debride; eschar = black, hard = usually debride (except heels)", ["wound-assessment","granulation","tissue-types","proliferative","healing"]);

  pn("Physiological Integrity","Contact Precautions LPN","Safe & Effective Care Environment",1,
    "An LPN is assigned to care for a patient with Clostridioides difficile (C. diff) infection. Which precaution is ESSENTIAL and UNIQUE to C. diff?",
    [O("A","Standard precautions alone are sufficient for C. diff"),O("B","Use SOAP AND WATER for hand hygiene instead of alcohol-based hand sanitizer: C. diff forms SPORES that are NOT killed by alcohol-based hand sanitizers; spores can survive on surfaces for months; use CONTACT PRECAUTIONS (gown and gloves), perform THOROUGH handwashing with soap and water (friction mechanically removes spores), clean the room with BLEACH-BASED (sodium hypochlorite) disinfectant (regular hospital disinfectants do not kill C. diff spores), and use dedicated patient equipment (stethoscope, BP cuff, thermometer)"),O("C","Alcohol-based hand sanitizer is equally effective against C. diff spores"),O("D","Only gloves are needed; a gown is not required")],
    ["B"],"C. difficile infection control: C. difficile (CDI) is a spore-forming, anaerobic gram-positive bacterium that causes antibiotic-associated diarrhea and pseudomembranous colitis. SPORES: C. diff produces SPORES that are: resistant to ALCOHOL (alcohol-based hand sanitizers do NOT kill spores), resistant to most hospital disinfectants, resistant to heat and drying, and can survive on environmental surfaces for MONTHS → major source of transmission. TRANSMISSION: fecal-oral route (contact with contaminated surfaces, equipment, or the hands of healthcare workers). PRECAUTIONS: CONTACT PRECAUTIONS: gown and GLOVES for all contact with the patient and the patient's environment; put on before entering the room, remove before leaving. HAND HYGIENE: SOAP AND WATER (not alcohol-based sanitizer). The mechanical action of friction during handwashing physically REMOVES spores from the hands (alcohol cannot kill them). This is the single most important unique precaution. ENVIRONMENTAL CLEANING: use BLEACH-BASED (sodium hypochlorite) disinfectant or EPA-registered sporicidal agent → bleach kills C. diff spores. Regular quaternary ammonium-based hospital disinfectants are INEFFECTIVE against spores. DEDICATED EQUIPMENT: single-patient-use or dedicated equipment (stethoscope, BP cuff, thermometer) → prevents cross-contamination. PRIVATE ROOM: preferred; if unavailable, cohort C. diff patients together. ANTIBIOTIC STEWARDSHIP: the most important PREVENTION strategy; CDI is strongly associated with antibiotic use (especially fluoroquinolones, clindamycin, broad-spectrum cephalosporins, and carbapenems) that disrupt normal gut flora → C. diff overgrowth → toxin production → colitis. TREATMENT: oral VANCOMYCIN or FIDAXOMICIN (first-line); IV metronidazole for patients who cannot take oral medications; fecal microbiota transplant (FMT) for recurrent CDI.",
    "C. diff: SOAP AND WATER (not alcohol sanitizer); contact precautions; BLEACH for surfaces; spores survive months; antibiotic stewardship prevents CDI; oral vancomycin treats", ["C-diff","spores","soap-water","bleach","contact-precautions"]);

  // REx-PN Batch 29
  rpn("Ethics","RHPA Controlled Acts","Safe & Effective Care Environment",2,
    "An RPN receives a request to perform a procedure that is a controlled act under Ontario's Regulated Health Professions Act (RHPA). Under what circumstances can the RPN legally perform a controlled act?",
    [O("A","RPNs can perform any controlled act at any time without restriction"),O("B","RPNs can perform controlled acts ONLY when authorized through: (1) a DIRECT ORDER from an authorized prescriber (physician, NP) for a specific patient, (2) a MEDICAL DIRECTIVE (a written order for a procedure applied to a group of patients who meet specific criteria, without requiring an individual order each time), or (3) DELEGATION from another regulated health professional who is authorized to perform and delegate the act; the RPN must also meet the Three Factor Framework requirements (legislation authorizes it, individual competence exists, and the practice setting supports it)"),O("C","Controlled acts are only relevant to physicians, not nurses"),O("D","RPNs are authorized to perform all 14 controlled acts independently")],
    ["B"],"RHPA Controlled Acts in Ontario: the RHPA identifies 14 CONTROLLED ACTS that pose a risk of harm if performed by unqualified persons. Only AUTHORIZED practitioners can perform them. The 14 controlled acts include: (1) communicating a diagnosis, (2) performing a procedure below the dermis/mucous membrane, (3) moving joints beyond normal range, (4) putting an instrument/hand beyond specified body openings, (5) administering a substance by injection or inhalation, (6) putting an instrument beyond the ear canal, nasal passage, or artificial opening, (7) prescribing, dispensing, selling a drug, (8) prescribing/dispensing/selling a hearing aid, (9) prescribing/dispensing corrective lenses, (10) prescribing a form of energy (radiation, electromagnetic), (11) applying a form of energy, (12) ordering diagnostic tests, (13) managing labor/delivery, (14) allergy challenge testing. RPNs and CONTROLLED ACTS: RPNs are authorized under the Nursing Act (which operates under the RHPA) to perform THREE controlled acts: (1) performing a procedure below the dermis, (2) administering a substance by injection or inhalation, (3) putting an instrument beyond an artificial opening into the body. HOWEVER, authorization alone is not sufficient. RPNs must receive the controlled act through: INDIVIDUAL ORDER: a specific order from an authorized prescriber (physician, NP, dentist, midwife) for a specific patient. MEDICAL DIRECTIVE: a written order by an authorized prescriber that applies to a GROUP of patients who meet specified criteria (e.g., 'administer acetaminophen 650 mg PO for patients with temperature >38.5°C'); allows the nurse to initiate the act without contacting the prescriber each time. DELEGATION: when an authorized practitioner delegates the performance of a controlled act to the RPN (the delegator retains accountability). ALL THREE FACTORS of the CNO Three Factor Framework must also be met.",
    "RHPA: 14 controlled acts; RPNs authorized for 3 (below dermis, injection/inhalation, instrument beyond artificial opening); need order, medical directive, or delegation + Three Factor Framework", ["RHPA","controlled-acts","medical-directive","delegation","authorization"]);

  return qs;
}

async function main(){
  console.log("=== Massive Batch 29 ===\n");
  const before=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("BEFORE:");for(const r of before.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs=build();const bk:Record<string,number>={};for(const q of allQs)bk[q.exam]=(bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`,bk);
  let ins=0,dup=0,err=0;
  for(const q of allQs){const h=sh(q.stem);try{const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`,[h,q.tier,q.exam]);if(ex.rows.length>0){dup++;continue;}await pool.query(`INSERT INTO exam_questions(id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,[q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,"Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);ins++;}catch(e:any){err++;console.error(`ERR: ${e.message.substring(0,100)}`);}}
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("\nAFTER:");for(const r of after.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session=await pool.query(`SELECT exam,COUNT(*)::int as cnt FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at>NOW()-INTERVAL '24 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:");for(const r of session.rows)console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}
main().catch(e=>{console.error("Fatal:",e);process.exit(1);});
