import crypto from "crypto";
import pg from "pg";
const pool = new pg.Pool({ host: process.env.PGHOST||"helium", user: process.env.PGUSER||"postgres", password: process.env.PGPASSWORD||"password", database: process.env.PGDATABASE||"heliumdb", ssl:false });
function sh(t:string):string{return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16);}
const O=(l:string,t:string)=>({label:l,text:t});
interface Q{tier:string;exam:string;stem:string;options:{label:string;text:string}[];ca:string[];rat:string;diff:number;tags:string[];topic:string;sub:string;rs:string;cp:string;bs:string;}
function build():Q[]{
  const qs:Q[]=[];
  const rn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});

  rn("Pharmacology","Succinylcholine Hyperkalemia","Physiological Integrity",3,
    "An RN in the ICU is assisting with rapid sequence intubation. Succinylcholine is ordered. Which patient condition is an ABSOLUTE contraindication to succinylcholine?",
    [O("A","Succinylcholine has no contraindications"),O("B","HYPERKALEMIA or conditions predisposing to hyperkalemia: succinylcholine is a depolarizing neuromuscular blocker that causes transient potassium release from muscle cells (typically 0.5-1.0 mEq/L increase); in patients with burns >24 hours old, crush injuries, spinal cord injuries, stroke, prolonged immobilization, or pre-existing HYPERKALEMIA, the potassium release can be MASSIVE (upregulated acetylcholine receptors across the entire muscle membrane → exaggerated potassium efflux) → severe hyperkalemia → CARDIAC ARREST; also contraindicated in patients with a personal or family history of MALIGNANT HYPERTHERMIA and certain myopathies"),O("C","Succinylcholine can safely be given to all burn patients"),O("D","Hyperkalemia is not affected by neuromuscular blockers")],
    ["B"],"Succinylcholine contraindications: hyperkalemia risk patients (burns >24hr, crush injuries, spinal cord injuries, stroke, immobilization, myopathies, denervation injuries); malignant hyperthermia history. Use non-depolarizing agents (rocuronium) instead. Succinylcholine = only depolarizing NMB; rapid onset (~60 sec), short duration (~5-10 min).",
    "Succinylcholine: contraindicated in hyperkalemia risk (burns >24hr, crush, SCI, stroke, immobilization); malignant hyperthermia history; releases K+ from muscle cells; cardiac arrest risk", ["succinylcholine","hyperkalemia","contraindication","RSI","depolarizing"]);

  rn("Safety","Suicide Risk Assessment","Psychosocial Integrity",3,
    "An RN is caring for a patient who states, 'I have decided to end my life tonight. I have a gun at home.' What is the RN's PRIORITY action?",
    [O("A","Document the statement and continue with routine care"),O("B","Ensure IMMEDIATE SAFETY: the patient is expressing ACTIVE suicidal ideation with a SPECIFIC PLAN and access to LETHAL MEANS — this is the HIGHEST risk level; the RN must: (1) stay with the patient CONTINUOUSLY (do not leave them alone, even for a moment), (2) initiate 1:1 OBSERVATION, (3) remove all potentially harmful items from the environment (sharps, belts, cords, medications), (4) notify the physician STAT for psychiatric evaluation, (5) activate the facility's suicide protocol, (6) maintain a calm, non-judgmental, empathetic approach (asking about suicide does NOT increase risk), (7) assess protective factors (reasons for living, social support); the patient should not be discharged until thoroughly evaluated"),O("C","The patient is just seeking attention and no intervention is needed"),O("D","Suggest the patient call a helpline and leave the room")],
    ["B"],"Suicide risk: highest risk = specific plan + access to lethal means + intent + timeline. NEVER leave the patient alone. 1:1 observation, remove harmful items, notify physician STAT, psychiatric eval. Asking about suicide does NOT increase risk — it can be protective. Risk factors: previous attempt (#1), substance abuse, hopelessness, social isolation.",
    "Suicide: specific plan + lethal means = highest risk; NEVER leave alone; 1:1 observation; remove harmful items; STAT psychiatric eval; asking about suicide is PROTECTIVE, not harmful", ["suicide","safety","1-to-1","lethal-means","psychiatric-emergency"]);

  rn("Pharmacology","Gentamicin Nephrotoxicity","Physiological Integrity",3,
    "An RN is monitoring a patient receiving IV gentamicin for a serious gram-negative infection. Which assessments are ESSENTIAL to detect aminoglycoside toxicity?",
    [O("A","Aminoglycosides have no significant toxicities"),O("B","Monitor RENAL function (BUN, creatinine, urine output) and HEARING (audiometry, patient reports of tinnitus): aminoglycosides (gentamicin, tobramycin, amikacin) cause both NEPHROTOXICITY and OTOTOXICITY; NEPHROTOXICITY: occurs in 10-25% of patients; gentamicin accumulates in the proximal tubular cells → direct tubular damage → acute kidney injury; earliest sign: rising creatinine; monitor BUN/creatinine daily and urine output; maintain adequate HYDRATION; OTOTOXICITY: damage to the 8th cranial nerve (vestibulocochlear); can affect hearing (cochlear damage → high-frequency hearing loss, tinnitus) or balance (vestibular damage → vertigo, ataxia, nystagmus); may be IRREVERSIBLE; obtain baseline audiometry and assess before each dose; monitor peak and TROUGH levels (trough drawn 30 minutes before the dose; peak drawn 30 minutes after IV infusion)"),O("C","Only liver function tests are needed for gentamicin"),O("D","Hearing assessments are unnecessary during aminoglycoside therapy")],
    ["B"],"Aminoglycoside monitoring: nephrotoxicity (BUN/Cr daily, UO, hydration) + ototoxicity (hearing, vestibular, tinnitus). Peak and trough levels. Avoid concurrent nephrotoxins (vancomycin, NSAIDs, contrast). Extended-interval dosing (once-daily) may reduce toxicity. Ototoxicity may be irreversible.",
    "Aminoglycosides: nephrotoxicity + ototoxicity; monitor BUN/Cr + hearing; peak and trough levels; hydrate; avoid concurrent nephrotoxins; ototoxicity may be IRREVERSIBLE; assess hearing baseline", ["gentamicin","aminoglycoside","nephrotoxicity","ototoxicity","trough"]);

  rn("Safety","Compartment Syndrome","Physiological Integrity",3,
    "An RN is caring for a patient with a newly applied cast on the right lower leg after a tibial fracture. The patient reports severe pain that is NOT relieved by prescribed analgesics and INCREASES with passive stretching of the toes. What condition should the RN suspect?",
    [O("A","The pain is expected and requires no further evaluation"),O("B","COMPARTMENT SYNDROME: a surgical EMERGENCY where pressure within a closed fascial compartment exceeds perfusion pressure → compromised blood flow to muscles and nerves → tissue ISCHEMIA → if untreated within 6 HOURS, permanent muscle and nerve damage, contractures (Volkmann contracture in the forearm), and potentially AMPUTATION; the '6 P's of compartment syndrome: PAIN (out of proportion, unrelieved by analgesics, WORST with passive stretch of the affected muscles — the EARLIEST and most reliable sign), PRESSURE (tense, firm compartment on palpation), PARESTHESIA (numbness, tingling), PARALYSIS (late sign — indicates nerve damage), PALLOR, PULSELESSNESS (very late — pulses may be present until very late stages); immediate intervention: REMOVE the cast/bivalve, elevate to heart level, notify the surgeon STAT for possible FASCIOTOMY"),O("C","Analgesics should be increased until the pain is controlled"),O("D","Pain with passive stretching is normal after casting")],
    ["B"],"Compartment syndrome: surgical emergency; 6 Ps (pain out of proportion with passive stretch = earliest; paresthesia, pressure, paralysis, pallor, pulselessness = late). Remove/bivalve cast immediately. FASCIOTOMY within 6 hours to prevent permanent damage. Do NOT elevate above heart (decreases perfusion).",
    "Compartment syndrome: pain out of proportion + unrelieved by analgesics + worse with passive stretch = earliest sign; bivalve cast; FASCIOTOMY within 6 hrs; pulses may be present (late loss)", ["compartment-syndrome","6-Ps","fasciotomy","emergency","cast"]);

  rn("Pharmacology","Nitroprusside Cyanide","Physiological Integrity",4,
    "An RN in the ICU is administering sodium nitroprusside (Nipride) for a hypertensive emergency. After 48 hours of continuous infusion, the patient develops tachycardia, metabolic acidosis, and altered mental status. What complication should the RN suspect?",
    [O("A","These are expected effects of nitroprusside therapy"),O("B","CYANIDE TOXICITY: nitroprusside is metabolized to CYANIDE; prolonged infusion (>48-72 hours) or high doses can cause cyanide accumulation → cyanide inhibits cytochrome oxidase in the mitochondria → blocks aerobic metabolism → cells switch to anaerobic metabolism → LACTIC ACIDOSIS, tachycardia, altered mental status, bright red venous blood (cells cannot extract oxygen), seizures, coma, death; monitor: serum thiocyanate levels (>12 mg/dL indicates toxicity), blood cyanide levels, and lactate levels; antidote: THIOSULFATE (sodium thiosulfate) which converts cyanide to non-toxic thiocyanate; also hydroxocobalamin (vitamin B12a); WRAP the nitroprusside infusion in FOIL (light-sensitive — degrades to more cyanide with light exposure)"),O("C","Metabolic acidosis during nitroprusside infusion is benign"),O("D","Nitroprusside does not produce any toxic metabolites")],
    ["B"],"Nitroprusside cyanide toxicity: metabolized to cyanide; risk increases >48-72 hrs or high doses. Signs: lactic acidosis, tachycardia, altered LOC, bright red venous blood. Antidote: thiosulfate + hydroxocobalamin. Protect from light (foil wrap). Monitor thiocyanate and cyanide levels.",
    "Nitroprusside: cyanide toxicity risk (>48hr or high doses); lactic acidosis + tachycardia + bright red venous blood; antidote = thiosulfate; WRAP in foil (light-sensitive); monitor thiocyanate <12", ["nitroprusside","cyanide-toxicity","hypertensive-emergency","thiosulfate","light-sensitive"]);

  rn("Safety","Restraint Documentation","Safe & Effective Care Environment",2,
    "An RN applies wrist restraints to a patient who is pulling at their endotracheal tube despite alternative interventions. Which documentation and monitoring requirement is ESSENTIAL?",
    [O("A","Once restraints are applied, they can remain indefinitely without reassessment"),O("B","Assess the patient and restrained extremities every 1-2 HOURS (per facility policy): check circulation (pulses, color, capillary refill, temperature, sensation, movement distal to the restraints), release restraints every 2 hours for RANGE OF MOTION exercises, offer food/fluids/toileting/repositioning; restraints require a PHYSICIAN ORDER renewed every 24 hours (for medical-surgical patients) or every 1-4 hours (for behavioral health patients); the RN must document: the clinical JUSTIFICATION (alternatives attempted and failed), type of restraint, time applied, ongoing assessments, patient response, and continued need; least RESTRICTIVE device should always be used; restraints are a LAST resort after alternatives have failed"),O("C","Restraints require no physician order"),O("D","Circulation checks are not needed for soft wrist restraints")],
    ["B"],"Restraint standards: last resort after alternatives (redirection, sitter, mitt, etc.). Physician order q24hr (med-surg) or q1-4hr (behavioral). Assess CMS (circulation, movement, sensation) q1-2hr. Release q2hr for ROM, toileting, food, repositioning. Document justification, alternatives tried, ongoing assessment.",
    "Restraints: last resort; physician order renewal required; CMS checks q1-2hr; release q2hr for ROM/toileting/food; document alternatives tried; least restrictive device; ongoing need assessment", ["restraints","documentation","CMS-checks","least-restrictive","physician-order"]);

  rn("Pharmacology","Tamoxifen Teaching","Physiological Integrity",2,
    "An RN is educating a premenopausal patient about tamoxifen therapy following treatment for estrogen receptor-positive breast cancer. Which side effect is the MOST concerning?",
    [O("A","Tamoxifen has no serious side effects"),O("B","Increased risk of ENDOMETRIAL CANCER: tamoxifen is a selective estrogen receptor modulator (SERM) that acts as an estrogen ANTAGONIST in breast tissue (blocks estrogen → prevents estrogen-stimulated breast cancer growth) but acts as an estrogen AGONIST in the UTERUS (stimulates the endometrial lining → endometrial hyperplasia → increased risk of endometrial cancer, approximately 2-7× baseline risk); patients must report any abnormal vaginal BLEEDING immediately; also increases the risk of DEEP VEIN THROMBOSIS and PULMONARY EMBOLISM (prothrombotic effect); positive effects: acts as an agonist in bone → reduces osteoporosis risk"),O("C","Tamoxifen has no effect on the uterus"),O("D","Tamoxifen decreases the risk of blood clots")],
    ["B"],"Tamoxifen SERM effects: antagonist in BREAST (therapeutic), agonist in UTERUS (endometrial cancer risk → report abnormal vaginal bleeding) and BONE (reduces osteoporosis). Increases DVT/PE risk. Used for ER+ breast cancer. 5-10 year course. Report leg swelling, chest pain, vaginal bleeding.",
    "Tamoxifen: SERM → anti-estrogen in breast, pro-estrogen in uterus (endometrial cancer risk) and bone (protective); DVT/PE risk; report abnormal vaginal bleeding immediately", ["tamoxifen","SERM","endometrial-cancer","breast-cancer","thrombosis"]);

  rn("Pharmacology","Ondansetron QT Warning","Physiological Integrity",2,
    "An RN is administering ondansetron (Zofran) IV to a postoperative patient for nausea. The patient's ECG shows a prolonged QTc interval of 490 ms. What should the RN do?",
    [O("A","Ondansetron has no cardiac effects"),O("B","HOLD ondansetron and notify the physician: ondansetron (a 5-HT3 receptor antagonist antiemetic) carries an FDA warning for dose-dependent QT PROLONGATION; in a patient with an already prolonged QTc (490 ms), administering ondansetron could further prolong the QT interval → risk of TORSADES DE POINTES (life-threatening ventricular arrhythmia); the maximum recommended single IV dose has been reduced to 16 mg (previously 32 mg was used); discuss alternative antiemetics with the physician that have less QT effect (promethazine, prochlorperazine — though these also have risks); also check and correct ELECTROLYTES (K+, Mg2+) as hypokalemia and hypomagnesemia worsen QT prolongation"),O("C","Ondansetron is safe at any QTc level"),O("D","QT prolongation is only a concern with cardiac medications")],
    ["B"],"Ondansetron QT risk: dose-dependent QT prolongation. Avoid or use with caution in patients with baseline QTc prolongation (>450-470 ms), congenital long QT syndrome, or on other QT-prolonging drugs. Max single IV dose 16 mg. Correct K+ and Mg2+ first.",
    "Ondansetron: dose-dependent QT prolongation; hold if QTc already prolonged; max single IV dose 16 mg; correct electrolytes; alternative antiemetics may be needed", ["ondansetron","QT-prolongation","antiemetic","torsades-risk","dose-dependent"]);

  rn("Pharmacology","Alendronate Administration","Physiological Integrity",1,
    "An RN is teaching a patient about alendronate (Fosamax) for osteoporosis prevention. Which administration instruction is CRITICAL for safety?",
    [O("A","Take alendronate with food for better absorption"),O("B","Take alendronate FIRST THING in the morning on an EMPTY STOMACH with a FULL GLASS of PLAIN WATER (6-8 oz); remain UPRIGHT (sitting or standing) for at least 30 MINUTES after taking the medication and do NOT eat, drink, or take other medications during this time; this prevents ESOPHAGEAL IRRITATION, ULCERATION, and STRICTURE (alendronate is highly irritating to the esophageal mucosa; lying down or having food/other liquids in the esophagus allows prolonged contact with the drug → chemical erosion of the esophageal tissue); patients should report any difficulty swallowing, chest pain, or new/worsening heartburn immediately"),O("C","Take alendronate at bedtime and lie down immediately"),O("D","Alendronate can be taken with coffee or juice")],
    ["B"],"Alendronate (bisphosphonate): empty stomach, FIRST thing in AM, full glass plain water, stay UPRIGHT 30 min, nothing else by mouth for 30 min. Prevents esophageal erosion. Also: rare risk of osteonecrosis of the jaw (dental care before starting) and atypical femur fracture with long-term use.",
    "Alendronate: empty stomach + plain water + upright 30 min (esophageal protection); weekly dosing available; dental exam before starting (osteonecrosis of jaw risk); atypical femur fracture risk", ["alendronate","bisphosphonate","esophageal","osteoporosis","upright"]);

  rn("Pharmacology","Nifedipine Reflex Tachycardia","Physiological Integrity",2,
    "An RN notes that a patient started on nifedipine (Procardia) for hypertension has developed a heart rate of 110 bpm. What is the likely explanation?",
    [O("A","Nifedipine directly stimulates the heart to beat faster"),O("B","REFLEX TACHYCARDIA: nifedipine is a DIHYDROPYRIDINE (DHP) calcium channel blocker that primarily acts on VASCULAR smooth muscle → potent vasodilation → decreased blood pressure → the body's baroreceptors detect the drop in BP → REFLEX sympathetic activation → increased heart rate (tachycardia); this is in contrast to NON-dihydropyridine CCBs (diltiazem, verapamil) which act primarily on the HEART → decreased HR; this reflex tachycardia can increase myocardial oxygen demand → concerning in patients with angina; the physician may add a beta-blocker to control the reflex tachycardia; also monitor for headache, flushing, and peripheral EDEMA (common DHP side effects)"),O("C","Nifedipine always decreases heart rate"),O("D","A heart rate of 110 is unrelated to nifedipine")],
    ["B"],"Nifedipine reflex tachycardia: DHP CCB → vascular vasodilation → BP drop → baroreceptor reflex → sympathetic activation → tachycardia. DHP = vessels (nifedipine, amlodipine); non-DHP = heart (diltiazem, verapamil). DHP side effects: headache, flushing, peripheral edema, reflex tachycardia.",
    "DHP CCBs (nifedipine/amlodipine): vasodilation → reflex tachycardia + headache + flushing + edema; non-DHP (diltiazem/verapamil): heart effects → bradycardia; DHP = vessels, non-DHP = heart", ["nifedipine","reflex-tachycardia","DHP","CCB","vasodilation"]);

  return qs;
}

async function main(){
  console.log("=== Massive Batch 40 ===\n");
  const before=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("BEFORE:");for(const r of before.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs=build();const bk:Record<string,number>={};for(const q of allQs)bk[q.exam]=(bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`,bk);
  let ins=0,dup=0,err=0;
  for(const q of allQs){const h=sh(q.stem);try{const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`,[h,q.tier,q.exam]);if(ex.rows.length>0){dup++;continue;}await pool.query(`INSERT INTO exam_questions(id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,[q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,"Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);ins++;}catch(e:any){err++;console.error(`ERR: ${e.message.substring(0,100)}`);}}
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("\nAFTER:");for(const r of after.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session=await pool.query(`SELECT exam,COUNT(*)::int as cnt FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at>NOW()-INTERVAL '24 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:");for(const r of session.rows)console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}
main().catch(e=>{console.error("Fatal:",e);process.exit(1);});
