import crypto from "crypto";
import pg from "pg";
const pool = new pg.Pool({ host: process.env.PGHOST||"helium", user: process.env.PGUSER||"postgres", password: process.env.PGPASSWORD||"password", database: process.env.PGDATABASE||"heliumdb", ssl:false });
function sh(t:string):string{return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16);}
const O=(l:string,t:string)=>({label:l,text:t});
interface Q{tier:string;exam:string;stem:string;options:{label:string;text:string}[];ca:string[];rat:string;diff:number;tags:string[];topic:string;sub:string;rs:string;cp:string;bs:string;}

function build():Q[]{
  const qs:Q[]=[];
  const pn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // NCLEX-RN Batch 22
  rn("Pharmacology","Calcium Channel Blocker","Physiological Integrity",2,
    "An RN is administering diltiazem (Cardizem) IV to a patient with rapid atrial fibrillation. Which assessment is MOST important before administration?",
    [O("A","Check the patient's temperature"),O("B","Assess HEART RATE and BLOOD PRESSURE: diltiazem is a non-dihydropyridine calcium channel blocker that slows AV node conduction (negative chronotropic) and decreases myocardial contractility; it can cause significant BRADYCARDIA and HYPOTENSION; hold if HR <60 bpm or SBP <90 mmHg; also monitor for heart block; do NOT give with IV beta-blockers simultaneously (additive bradycardia and hypotension → cardiac arrest); diltiazem and verapamil are used for RATE CONTROL in atrial fibrillation/flutter and SVT"),O("C","Calcium channel blockers do not affect heart rate"),O("D","Only respiratory rate needs monitoring with diltiazem")],
    ["B"],"Calcium channel blocker classes: NON-DIHYDROPYRIDINES (diltiazem, verapamil): affect the HEART primarily. Decrease AV node conduction (negative dromotropic), decrease heart rate (negative chronotropic), decrease contractility (negative inotropic). Uses: rate control in AF/flutter, SVT, angina, hypertension. Cautions: BRADYCARDIA, HYPOTENSION, heart block, heart failure (decreased contractility). INTERACTION: IV diltiazem/verapamil + IV BETA-BLOCKER = ADDITIVE bradycardia and hypotension → potential cardiac arrest; NEVER give simultaneously IV. DIHYDROPYRIDINES (amlodipine, nifedipine, nicardipine): affect the VESSELS primarily. Potent vasodilators → decrease blood pressure. Minimal effect on heart rate and contractivity (amlodipine may cause reflex tachycardia). Uses: hypertension, angina (vasospastic/Prinzmetal angina). GRAPEFRUIT interaction: applies to some CCBs (nifedipine, felodipine) metabolized by CYP3A4. Constipation is a common side effect of ALL CCBs (especially verapamil). Peripheral edema (especially with dihydropyridines from vasodilation). Monitor: HR, BP, ECG rhythm, edema, constipation.",
    "CCBs: non-DHP (diltiazem/verapamil) = heart effects (rate control, bradycardia risk); DHP (amlodipine) = vessel effects (BP lowering); never IV CCB + IV beta-blocker together", ["calcium-channel-blocker","diltiazem","rate-control","bradycardia","atrial-fibrillation"]);

  rn("Obstetrics","Preeclampsia Management","Physiological Integrity",4,
    "An RN is caring for a patient at 34 weeks gestation with severe preeclampsia (BP 170/110, proteinuria, headache, visual changes). Which medication is the PRIORITY?",
    [O("A","Oxytocin to induce labor immediately"),O("B","IV MAGNESIUM SULFATE: the PRIORITY medication for severe preeclampsia/eclampsia to PREVENT SEIZURES (eclampsia); magnesium acts as a CNS depressant and blocks neuromuscular transmission; therapeutic level: 4-7 mEq/L; monitor for toxicity: loss of deep tendon reflexes (DTRs - earliest sign of toxicity, check patellar reflex), respiratory depression (<12 breaths/min), decreased urine output (<30 mL/hr), lethargy; antidote: CALCIUM GLUCONATE (at bedside); also administer antihypertensives (IV labetalol or hydralazine) for BP ≥160/110 to prevent stroke"),O("C","Diazepam as the first-line seizure prevention medication"),O("D","ACE inhibitors for blood pressure control in pregnancy")],
    ["B"],"Preeclampsia/eclampsia management: PREECLAMPSIA: a pregnancy-specific hypertensive disorder (BP ≥140/90 after 20 weeks gestation + proteinuria or end-organ damage). SEVERE PREECLAMPSIA: BP ≥160/110, proteinuria, thrombocytopenia, elevated liver enzymes, renal insufficiency, pulmonary edema, cerebral or visual disturbances (headache, scotomata, blurred vision). ECLAMPSIA: preeclampsia + SEIZURES. MAGNESIUM SULFATE: FIRST-LINE for seizure PREVENTION (not treatment of hypertension). MECHANISM: CNS depression, blocks neuromuscular transmission, cerebral vasodilation (reduces cerebral vasospasm). THERAPEUTIC LEVEL: 4-7 mEq/L. Loading dose: 4-6 g IV over 15-30 minutes. Maintenance: 1-2 g/hour continuous IV infusion. Continue 24-48 hours postpartum (eclampsia can occur up to 48 hours after delivery). TOXICITY (progressive with increasing levels): 7-10 mEq/L: loss of DEEP TENDON REFLEXES (earliest clinical sign - check PATELLAR reflex before each assessment). 10-12 mEq/L: RESPIRATORY DEPRESSION. 15-20 mEq/L: RESPIRATORY ARREST. >25 mEq/L: CARDIAC ARREST. MONITORING: DTRs (patellar reflex every 1-2 hours), respiratory rate (hold if <12), urine output (should be ≥30 mL/hour - magnesium is renally excreted; decreased output → accumulation), continuous fetal monitoring. ANTIDOTE: CALCIUM GLUCONATE 1 g IV push (at the BEDSIDE at all times). ANTIHYPERTENSIVES: IV LABETALOL or IV HYDRALAZINE for acute severe hypertension (BP ≥160/110) to prevent hemorrhagic stroke. ACE inhibitors and ARBs are CONTRAINDICATED in pregnancy (teratogenic).",
    "Preeclampsia: MgSO4 to prevent seizures (not for BP); therapeutic 4-7; monitor DTRs (earliest toxicity sign), RR, urine output; antidote = calcium gluconate; ACE/ARBs contraindicated", ["preeclampsia","magnesium-sulfate","seizure-prevention","calcium-gluconate","obstetric"]);

  rn("Pharmacology","Nitroglycerin Nursing","Physiological Integrity",2,
    "An RN is administering sublingual nitroglycerin to a patient experiencing acute chest pain. After giving one tablet, the patient's blood pressure drops to 85/50 mmHg. What should the RN do?",
    [O("A","Give two more tablets immediately to fully relieve the chest pain"),O("B","HOLD the next nitroglycerin dose and position the patient SUPINE with legs elevated: nitroglycerin is a potent VASODILATOR (primarily venous dilation → decreased PRELOAD → decreased myocardial oxygen demand); this reduces blood pressure; HYPOTENSION (SBP <90 mmHg) is a contraindication to additional doses; administer IV NORMAL SALINE if hypotension persists; also contraindicated if the patient has taken a PDE5 inhibitor (sildenafil/Viagra, tadalafil/Cialis) within the past 24-48 hours (severe refractory hypotension)"),O("C","Nitroglycerin cannot cause hypotension"),O("D","Continue giving nitroglycerin regardless of the blood pressure")],
    ["B"],"Nitroglycerin administration: MECHANISM: releases nitric oxide → activates guanylate cyclase → increases cGMP → vascular smooth muscle RELAXATION. At lower doses: primarily VENOUS dilation → decreased venous return (preload) → decreased ventricular volume → decreased myocardial wall tension → decreased myocardial oxygen demand. At higher doses: also arterial dilation (afterload reduction). SUBLINGUAL (SL) administration for acute chest pain: (1) Check BP first (SBP must be >90 mmHg). (2) Give 1 tablet (0.4 mg) SL or 1 metered spray. (3) Have the patient sit or lie down (prevent orthostatic hypotension). (4) If pain continues, may repeat every 5 MINUTES for a maximum of 3 doses. (5) If pain persists after 3 doses (or after 1 dose if instructed), call 911/activate EMS. MONITORING: BP (check before EACH dose; HOLD if SBP <90 mmHg), heart rate (reflex tachycardia may occur), headache (most common side effect from vasodilation of cerebral vessels). CONTRAINDICATIONS: hypotension (SBP <90), PDE5 INHIBITORS within 24 hours for sildenafil/vardenafil or 48 hours for tadalafil (PDE5 inhibitors prevent the breakdown of cGMP → with nitroglycerin, cGMP accumulates excessively → severe refractory hypotension that does not respond to fluids or vasopressors), right ventricular infarction (RV is preload-dependent), severe aortic stenosis, hypertrophic cardiomyopathy. STORAGE: SL tablets in the ORIGINAL dark glass container (light degrades nitroglycerin), replaced every 6 months (loses potency). The patient should feel a TINGLING sensation under the tongue (indicates potency).",
    "NTG: check BP before each dose (hold if SBP <90); max 3 SL doses q5min; contraindicated with PDE5 inhibitors (24-48 hrs); store in dark glass, replace q6 months", ["nitroglycerin","sublingual","hypotension","PDE5-inhibitor","chest-pain"]);

  rn("Neurology","Stroke Assessment FAST","Physiological Integrity",3,
    "An RN receives a call from a family member stating their elderly relative suddenly developed right-sided facial drooping, arm weakness, and slurred speech. What assessment tool should the RN recommend and what is the time-critical element?",
    [O("A","Advise the family to give aspirin and wait to see if symptoms resolve"),O("B","Use the FAST assessment (Face drooping, Arm weakness, Speech difficulty, Time to call 911) and emphasize that TIME IS BRAIN: acute ischemic stroke treatment with IV ALTEPLASE (tPA) has a strict window of 4.5 HOURS from symptom onset; every minute of untreated stroke results in approximately 1.9 million neurons dying; the family should call 911 IMMEDIATELY, note the TIME symptoms began (last known normal), and NOT give aspirin until a CT scan rules out hemorrhagic stroke"),O("C","Recommend the patient rest for a few hours to see if symptoms improve"),O("D","Stroke symptoms always resolve on their own and do not require emergency care")],
    ["B"],"Stroke assessment and time-critical management: FAST: F = FACE drooping (ask patient to smile; is one side drooping?). A = ARM weakness (ask patient to raise both arms; does one drift down?). S = SPEECH difficulty (ask patient to repeat a simple sentence; is speech slurred or garbled?). T = TIME to call 911 (note the exact TIME symptoms began - this determines treatment eligibility). TIME IS BRAIN: approximately 1.9 MILLION neurons die per MINUTE during an untreated ischemic stroke. tPA (ALTEPLASE) WINDOW: IV tPA must be administered within 4.5 HOURS of symptom onset (some patients may receive it within 3-4.5 hours with additional criteria). Mechanical thrombectomy: may be performed up to 24 hours in select patients with large vessel occlusion. CRITICAL STEPS: (1) Call 911 immediately (do NOT drive to the hospital - EMS can pre-notify the stroke team). (2) Note the TIME of symptom onset or last known normal (if the patient woke up with symptoms, the time is when they were last seen normal). (3) CT scan IMMEDIATELY on arrival (distinguish ischemic vs hemorrhagic stroke - tPA is given ONLY for ISCHEMIC stroke; giving tPA for hemorrhagic stroke = worsened bleeding = death). (4) Do NOT give aspirin BEFORE CT scan (aspirin is an antiplatelet; if it is a hemorrhagic stroke, aspirin worsens bleeding). POST-tPA: monitor neuro status q15 min ×2 hours, then q30 min ×6 hours, then q1h ×16 hours. Monitor BP strictly (target <180/105 after tPA). No anticoagulants or antiplatelets for 24 hours after tPA. Watch for signs of bleeding (most serious: intracranial hemorrhage).",
    "FAST stroke assessment; tPA within 4.5 hrs (ischemic only); CT first (rule out hemorrhagic before any treatment); 1.9M neurons/min lost; note symptom onset time", ["stroke","FAST","tPA","time-critical","neurology"]);

  rn("Infection Control","Neutropenic Precautions","Safe & Effective Care Environment",3,
    "An RN is caring for a patient with chemotherapy-induced neutropenia (ANC 350 cells/mm3). Which precaution is MOST critical?",
    [O("A","Neutropenic patients do not require any special precautions"),O("B","Implement NEUTROPENIC PRECAUTIONS: place the patient in a PRIVATE ROOM; STRICT hand hygiene for ALL visitors and staff (the most important measure); AVOID fresh flowers, live plants, standing water (sources of bacteria and mold); NO fresh fruits or vegetables unless thoroughly washed (consider a neutropenic/low-microbial diet); daily assessment for signs of INFECTION (neutropenic patients may NOT have typical signs like fever, redness, or pus because they lack the WBCs to mount an inflammatory response - fever may be the ONLY sign); avoid crowds; no rectal temperatures or suppositories (risk of perianal abscess)"),O("C","Only standard precautions are needed"),O("D","Administer prophylactic antibiotics to all visitors before they enter the room")],
    ["B"],"Neutropenic precautions: NEUTROPENIA: ANC (absolute neutrophil count) <1500 cells/mm3. Mild: 1000-1500. Moderate: 500-1000. Severe: <500 (highest infection risk). ANC <100: profound neutropenia. NEUTROPHILS are the body's primary defense against BACTERIAL and FUNGAL infections; without adequate neutrophils, patients are extremely vulnerable to infection and may not show typical signs of infection (because the inflammatory response requires WBCs). PRECAUTIONS: HAND HYGIENE: the single MOST EFFECTIVE measure for preventing infection in neutropenic patients. All visitors and staff must wash hands before entering the room. PRIVATE ROOM: preferably with POSITIVE PRESSURE airflow (air flows out of the room → prevents outside contaminants from entering; opposite of negative pressure used for TB). AVOID sources of microorganisms: no fresh FLOWERS or live PLANTS (harbor bacteria and fungal spores, especially Aspergillus), no STANDING WATER (breeding ground for bacteria), no construction areas (Aspergillus risk). DIET: neutropenic diet (low microbial): no raw/undercooked meat/fish, no raw eggs, no fresh fruits and vegetables unless thoroughly washed/peeled, no unpasteurized dairy, no well water. ASSESSMENT: monitor for FEVER (may be the ONLY sign of infection in neutropenic patients - the normal inflammatory response is impaired: no redness, no swelling, no pus formation). Neutropenic FEVER (>38.3°C once or >38°C sustained for 1 hour) is a MEDICAL EMERGENCY requiring immediate blood cultures and empiric broad-spectrum antibiotics within 1 HOUR. AVOID: rectal temperatures, suppositories, enemas (perianal area is a common site of abscess), IM injections (risk of abscess), indwelling catheters when possible, contact with people who are ill.",
    "Neutropenic precautions: hand hygiene #1; private room (positive pressure); no flowers/plants/standing water; fever may be ONLY sign of infection; neutropenic fever = emergency", ["neutropenia","chemotherapy","infection-prevention","neutropenic-fever","oncology"]);

  // NCLEX-PN Batch 22
  pn("Physiological Integrity","Oxygen Safety LPN","Physiological Integrity",1,
    "An LPN is providing oxygen therapy to a patient via nasal cannula at 3 L/min. Which safety precaution is MOST important to reinforce?",
    [O("A","Oxygen is not flammable so no special precautions are needed"),O("B","Oxygen SUPPORTS COMBUSTION (it is an oxidizer, not itself flammable, but it accelerates the burning of flammable materials): ensure NO open flames, NO smoking, NO electrical devices that produce sparks near the oxygen source; post 'Oxygen in Use' signs; keep petroleum-based products (Vaseline/petroleum jelly) away from the oxygen equipment (use water-based lubricants for lips and nasal passages); ensure electrical equipment is properly grounded; keep a fire extinguisher accessible"),O("C","Smoking is safe as long as the oxygen is turned off first"),O("D","Only alcohol-based hand sanitizer poses a fire risk with oxygen")],
    ["B"],"Oxygen safety: OXYGEN IS AN OXIDIZER: it does not burn itself but SUPPORTS and ACCELERATES combustion (makes fires burn faster, hotter, and more intensely). Materials that would not normally catch fire can become flammable in an oxygen-enriched environment. FIRE PREVENTION: NO SMOKING: the #1 cause of oxygen-related fires and burns. Post 'No Smoking - Oxygen in Use' signs on the door and at the bedside. This applies to the patient, visitors, and anyone in the area. No open FLAMES (candles, matches, lighters). No ELECTRICAL devices that produce sparks (razors, heating pads, ungrounded equipment). Do NOT use petroleum-based products (Vaseline/petroleum jelly, oil-based lotions, lip balm with petroleum) near oxygen equipment → use WATER-BASED lubricants for dry lips and nasal passages (water-soluble KY jelly, water-based moisturizers). Ensure all electrical equipment is properly GROUNDED. Keep a FIRE EXTINGUISHER accessible. COTTON clothing is preferred over synthetic materials (synthetics can generate static electricity and are more flammable). NASAL CANNULA CARE: assess the nares and behind the ears for skin breakdown from the tubing; use foam ear protectors; humidification is generally added for flow rates >4 L/min (prevents drying of mucous membranes); check flow rate matches the order. FLOW RATE and FiO2: nasal cannula delivers approximately 24-44% O2 at 1-6 L/min (each L/min adds approximately 4% to the 21% room air). Max flow rate for nasal cannula: 6 L/min.",
    "O2 supports combustion: no smoking/flames/sparks; no petroleum-based products near O2; post signs; water-based lubricants only; NC max 6 L/min (~24-44% FiO2)", ["oxygen-safety","combustion","no-smoking","nasal-cannula","fire-prevention"]);

  pn("Physiological Integrity","Post-Mortem Care LPN","Psychosocial Integrity",1,
    "An LPN is preparing to provide post-mortem care for a deceased patient. Which action demonstrates respectful and proper care?",
    [O("A","Remove all personal belongings immediately without documenting"),O("B","Handle the body with DIGNITY and RESPECT: position the body SUPINE with head slightly elevated (prevents discoloration of the face from blood pooling), close the EYES, close the MOUTH (dentures may be placed to maintain facial appearance), remove tubes and IV lines per facility policy (some facilities leave lines in for the medical examiner/coroner cases), bathe the body, place clean linens, allow family time for viewing and grieving, inventory and document ALL personal belongings, and follow cultural and religious preferences for post-mortem care"),O("C","Rush through the process to free up the bed as quickly as possible"),O("D","Do not allow the family to see the body")],
    ["B"],"Post-mortem care: PRINCIPLES: treat the deceased with the same DIGNITY and RESPECT afforded to a living patient; attend to the emotional needs of the family and other patients/staff. PROCEDURE: (1) VERIFICATION: confirm death (physician pronounces death; document the date, time, and who pronounced). (2) NOTIFICATION: notify the family (if not already present), physician, supervisor, organ donation organization (as required by law for all deaths), and coroner/medical examiner (if required - unnatural deaths, unexpected deaths, deaths within 24 hours of admission). (3) BODY POSITIONING: position SUPINE with the head slightly ELEVATED (15-30 degrees) to prevent blood pooling and discoloration of the face (livor mortis). Place the body in natural alignment. (4) FACIAL CARE: close the EYES gently (may use moist cotton balls to keep them closed initially); close the MOUTH (place a rolled towel under the chin; insert DENTURES if available to maintain the natural facial contour for family viewing). (5) LINES AND TUBES: remove per facility policy and physician orders. Exception: LEAVE ALL lines, tubes, and devices in place if the case is going to the CORONER/MEDICAL EXAMINER (they need to see the interventions that were performed). (6) HYGIENE: bathe the body, apply clean gown and linens, cover with a clean sheet. (7) BELONGINGS: carefully inventory and document ALL personal belongings; place in a labeled bag; have family sign for receipt. (8) IDENTIFICATION: apply identification tags (wrist, toe, and shroud/body bag). (9) CULTURAL CONSIDERATIONS: respect cultural, religious, and spiritual practices.",
    "Post-mortem: body supine, head elevated; close eyes/mouth; insert dentures; leave lines if coroner case; inventory belongings; allow family time; respect cultural practices", ["post-mortem-care","dignity","family-support","identification","end-of-life"]);

  pn("Physiological Integrity","Crutch Walking LPN","Physiological Integrity",1,
    "An LPN is teaching a patient how to use crutches with a non-weight-bearing restriction on the right leg. Which technique should the LPN teach for ascending stairs?",
    [O("A","Lead with the affected (non-weight-bearing) leg going up"),O("B","Use the mnemonic 'Up with the GOOD, down with the BAD': when going UP stairs, lead with the UNAFFECTED (strong/good) leg first, then bring the crutches and the affected leg up to the same step; when going DOWN stairs, lead with the CRUTCHES and the AFFECTED (bad) leg first, then bring the unaffected leg down; a HANDRAIL should be used when available (hold the handrail with one hand and both crutches in the other hand)"),O("C","Both legs should move simultaneously with the crutches"),O("D","Always lead with the crutches first regardless of direction")],
    ["B"],"Crutch walking on stairs: MNEMONIC: 'Up with the GOOD, down with the BAD' or 'The GOOD go to HEAVEN (up), the BAD go to HELL (down).' ASCENDING (going UP) stairs: (1) Stand close to the bottom step. (2) Transfer body weight to the CRUTCHES. (3) Step UP with the UNAFFECTED (good/strong) leg FIRST (this leg is strong enough to lift the body weight up). (4) Bring the CRUTCHES and the AFFECTED (bad/weak) leg up to the SAME step. (5) Repeat. DESCENDING (going DOWN) stairs: (1) Stand close to the edge of the step. (2) Transfer body weight to the UNAFFECTED leg. (3) Lower the CRUTCHES and the AFFECTED leg DOWN to the next step FIRST. (4) Transfer weight to the crutches. (5) Step DOWN with the UNAFFECTED leg to the SAME step. (6) Repeat. HANDRAIL: when available, the patient should hold the HANDRAIL with one hand and hold BOTH crutches in the OTHER hand (bundled together). CRUTCH FIT: when standing, crutch tips should be 4-6 inches to the front and side of the foot; 2-3 finger widths between the axillary pad and the axilla (NEVER rest body weight on the axillary pads → axillary nerve damage/crutch palsy → wrist drop and hand weakness); weight should be borne on the HANDS/hand grips, not the axillae. CRUTCH GAITS: 4-point (most stable), 3-point (non-weight-bearing), 2-point (partial weight-bearing), swing-to, swing-through (fastest).",
    "Stairs: up with good leg first, down with bad leg + crutches first; never rest on axillary pads (nerve damage); weight on hands; 2-3 finger widths at axilla", ["crutch-walking","stairs","good-up-bad-down","non-weight-bearing","mobility"]);

  // REx-PN Batch 22
  rpn("Clinical Skills","Nasopharyngeal Suctioning CA","Physiological Integrity",2,
    "An RPN is performing nasopharyngeal suctioning on a patient who cannot clear secretions effectively. Which complication should the RPN monitor for during the procedure?",
    [O("A","Nasopharyngeal suctioning has no complications"),O("B","Monitor for VAGAL STIMULATION causing BRADYCARDIA: stimulation of the vagus nerve during suctioning can trigger a vagal response leading to decreased heart rate; also monitor for HYPOXIA (suctioning removes air along with secretions; pre-oxygenate before and limit suction time to 10-15 seconds), MUCOSAL TRAUMA (use appropriate catheter size and gentle technique; do not force the catheter), INCREASED INTRACRANIAL PRESSURE (suctioning can increase ICP in patients with head injuries; pre-oxygenate and limit passes), and BRONCHOSPASM"),O("C","Only dehydration is a risk with suctioning"),O("D","Suctioning is a risk-free procedure that requires no monitoring")],
    ["B"],"Nasopharyngeal suctioning complications: (1) VAGAL STIMULATION → BRADYCARDIA: the vagus nerve (cranial nerve X) runs through the pharynx and trachea; mechanical stimulation from the suction catheter can activate the vagal reflex → decreased heart rate → potential cardiac arrest (especially in infants and patients on cardiac medications). Prevention: gentle technique, limit suction time, monitor heart rate. (2) HYPOXIA: suctioning removes oxygen along with secretions → desaturation. Prevention: PRE-OXYGENATE with 100% O2 for 30 seconds before and after suctioning; limit each pass to 10-15 seconds; allow recovery between passes. (3) MUCOSAL TRAUMA: the suction catheter can damage the delicate nasal, pharyngeal, or tracheal mucosa → bleeding, edema, inflammation. Prevention: use appropriate catheter size (≤½ the internal diameter of the naris or airway), apply suction only during WITHDRAWAL, use gentle rotating technique, lubricate the catheter with water-soluble lubricant for nasopharyngeal suctioning. (4) INCREASED ICP: suctioning can transiently increase intracranial pressure (coughing, gagging, and hypoxia all elevate ICP). Prevention: pre-oxygenate, limit passes, avoid in patients with acutely elevated ICP unless absolutely necessary. (5) BRONCHOSPASM: mechanical irritation can trigger airway constriction. Prevention: gentle technique, adequate humidification. (6) INFECTION: break in sterile technique can introduce organisms. Prevention: sterile technique for tracheal suctioning, clean technique for oropharyngeal.",
    "Suctioning complications: vagal bradycardia, hypoxia (pre-oxygenate), mucosal trauma (catheter ≤½ airway), increased ICP, bronchospasm; limit 10-15 sec per pass", ["suctioning","complications","vagal-bradycardia","hypoxia","nasopharyngeal"]);

  rpn("Ethics","Duty to Report Canada","Safe & Effective Care Environment",2,
    "An RPN witnesses a colleague diverting narcotics from the medication dispensing system for personal use. What is the RPN's professional and legal obligation?",
    [O("A","Ignore the situation to maintain a good working relationship"),O("B","REPORT the observation: RPNs have a DUTY TO REPORT under the Regulated Health Professions Act (RHPA) and CNO standards; the RPN must report to the charge nurse/supervisor, facility management, and may need to report to the College of Nurses of Ontario (CNO) if there is reasonable grounds to believe the colleague's practice poses a risk to patient safety; narcotic diversion is both a regulatory offense and a criminal offense; the RPN also has a DUTY to ensure patient safety by verifying that affected patients received their prescribed medications"),O("C","Confront the colleague privately and ask them to stop but not report it"),O("D","Only report if the colleague is caught by someone else first")],
    ["B"],"Duty to report in Ontario nursing: MANDATORY REPORTING under the RHPA (Regulated Health Professions Act) and CNO standards: nurses have a legal and ethical obligation to report concerns about the practice of colleagues. REPORTING OBLIGATIONS: (1) Report to the EMPLOYER (charge nurse, supervisor, manager) when a colleague's practice poses a risk to patient safety. (2) Report to the CNO (College of Nurses of Ontario) when there are reasonable grounds to believe a member is: incompetent, incapacitated (unable to practice safely due to physical or mental condition, substance use), sexually abusing a patient, or engaging in conduct that could harm patients. (3) NARCOTIC DIVERSION: a nurse diverting controlled substances is: committing a CRIMINAL offense (theft, fraud under the Criminal Code of Canada), violating the Controlled Drugs and Substances Act, breaching professional standards, and potentially endangering patients who may not receive their prescribed analgesics (patients may suffer uncontrolled pain). REPORTING PROCESS: document what was observed (factual, objective), report to the supervisor immediately, facility will investigate, CNO mandatory report filed if patient safety risk exists. PROTECTION: the RHPA provides WHISTLEBLOWER PROTECTION → employers cannot retaliate against employees who file mandatory reports in good faith. CONSEQUENCES for the diverting nurse: criminal charges, CNO discipline (suspension, revocation of registration), mandatory substance abuse treatment program, employment consequences.",
    "Duty to report: mandatory under RHPA and CNO; narcotic diversion = criminal + regulatory offense; report to employer and CNO; whistleblower protection; verify patient safety", ["duty-to-report","narcotic-diversion","RHPA","CNO","mandatory-reporting"]);

  rpn("Pharmacology","Beers Criteria Canada","Safe & Effective Care Environment",2,
    "An RPN reviews a 79-year-old long-term care resident's medication list and finds diphenhydramine (Benadryl) prescribed as a sleep aid. Why is this concerning according to the Beers Criteria?",
    [O("A","Diphenhydramine is the ideal sleep aid for elderly patients"),O("B","Diphenhydramine is on the BEERS CRITERIA list of potentially inappropriate medications for older adults (≥65 years): it has strong ANTICHOLINERGIC properties that are particularly dangerous in the elderly, causing confusion, delirium, cognitive impairment, dry mouth, constipation, urinary retention, blurred vision, tachycardia, orthostatic hypotension (fall risk), and sedation; elderly patients have decreased hepatic metabolism and renal clearance → prolonged drug effects; safer alternatives for insomnia in elderly include sleep hygiene education, melatonin, or low-dose trazodone"),O("C","The Beers Criteria does not apply to Canadian practice"),O("D","Diphenhydramine is only dangerous in children, not in the elderly")],
    ["B"],"Beers Criteria: developed by the American Geriatrics Society (AGS), widely used in Canada and internationally to identify POTENTIALLY INAPPROPRIATE MEDICATIONS (PIMs) for older adults (≥65 years). DIPHENHYDRAMINE (Benadryl): a first-generation antihistamine with strong ANTICHOLINERGIC effects. ANTICHOLINERGIC EFFECTS in elderly: CENTRAL: confusion, delirium, cognitive impairment (mimics or worsens dementia), hallucinations, agitation, sedation. PERIPHERAL: dry mouth (dental problems, swallowing difficulty), constipation, urinary retention (especially problematic in men with BPH), blurred vision, tachycardia, decreased sweating (heat intolerance). WHY ELDERLY ARE MORE VULNERABLE: decreased hepatic metabolism (CYP enzymes decline with age), decreased renal clearance, increased blood-brain barrier permeability (more drug crosses into the CNS), decreased cholinergic reserve (already low acetylcholine levels in aging brains), increased sensitivity to CNS depressants, polypharmacy (drug interactions). FALL RISK: anticholinergic-induced sedation, orthostatic hypotension, blurred vision, and cognitive impairment all increase fall risk → hip fractures → hospitalization → functional decline. ANTICHOLINERGIC BURDEN: the cumulative effect of all anticholinergic medications a patient is taking; higher burden = higher risk of adverse effects. OTHER common PIMs from Beers Criteria: benzodiazepines (fall risk, cognitive impairment), NSAIDs (GI bleeding, renal toxicity), muscle relaxants (sedation, anticholinergic effects), barbiturates, meperidine. SAFER ALTERNATIVES for insomnia: sleep hygiene education, melatonin, low-dose trazodone, cognitive behavioral therapy for insomnia (CBT-I).",
    "Beers Criteria: diphenhydramine inappropriate in elderly (anticholinergic → confusion, falls, urinary retention, delirium); safer alternatives: melatonin, trazodone, sleep hygiene", ["Beers-Criteria","anticholinergic","elderly","diphenhydramine","potentially-inappropriate"]);

  return qs;
}

async function main(){
  console.log("=== Massive Batch 22 ===\n");
  const before=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("BEFORE:");for(const r of before.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs=build();const bk:Record<string,number>={};for(const q of allQs)bk[q.exam]=(bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`,bk);
  let ins=0,dup=0,err=0;
  for(const q of allQs){const h=sh(q.stem);try{const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`,[h,q.tier,q.exam]);if(ex.rows.length>0){dup++;continue;}await pool.query(`INSERT INTO exam_questions(id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,[q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,"Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);ins++;}catch(e:any){err++;console.error(`ERR: ${e.message.substring(0,100)}`);}}
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("\nAFTER:");for(const r of after.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session=await pool.query(`SELECT exam,COUNT(*)::int as cnt FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at>NOW()-INTERVAL '23 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:");for(const r of session.rows)console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}
main().catch(e=>{console.error("Fatal:",e);process.exit(1);});
