import crypto from "crypto";
import pg from "pg";

const pool = new pg.Pool({ host: process.env.PGHOST || "helium", user: process.env.PGUSER || "postgres", password: process.env.PGPASSWORD || "password", database: process.env.PGDATABASE || "heliumdb", ssl: false });
function sh(t: string): string { return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16); }
const O = (l: string, t: string) => ({ label: l, text: t });

interface Q { tier:string; exam:string; stem:string; options:{label:string;text:string}[]; ca:string[]; rat:string; diff:number; tags:string[]; topic:string; sub:string; rs:string; cp:string; bs:string; }

function build(): Q[] {
  const qs: Q[] = [];
  const pn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // ===== NCLEX-PN MEGA BATCH =====

  pn("Physiological Integrity","Pneumonia Assessment","Physiological Integrity",2,
    "An LPN is caring for a 68-year-old patient admitted with community-acquired pneumonia. Which assessment finding is MOST characteristic?",
    [O("A","Clear lung sounds bilaterally with normal respiratory rate"), O("B","Productive cough with rust-colored or purulent sputum, crackles on auscultation, fever, pleuritic chest pain, tachypnea, and decreased oxygen saturation"), O("C","Dry cough without fever or sputum production"), O("D","Wheezing heard only during expiration without fever")],
    ["B"],"Community-acquired pneumonia (CAP) presents with: productive cough (rust-colored sputum is classic for Streptococcus pneumoniae, the most common bacterial cause), crackles/rales on auscultation (from consolidation and fluid in alveoli), fever with chills, pleuritic chest pain (sharp, worse with inspiration), tachypnea, dyspnea, and hypoxemia. Elderly patients may present atypically with confusion, falls, or hypothermia rather than classic symptoms. Nursing care includes: incentive spirometry (10 times/hour while awake), positioning (affected side DOWN for perfusion matching, or HOB elevated for comfort), hydration (2-3L/day unless contraindicated), oxygen to maintain SpO2 >92%, and monitoring sputum characteristics.",
    "Pneumonia: productive cough, crackles, fever, pleuritic pain; elderly may present atypically; S. pneumoniae = most common bacterial cause", ["pneumonia","CAP","crackles","sputum","respiratory"]);

  pn("Physiological Integrity","COPD Oxygen Therapy","Physiological Integrity",3,
    "An LPN is caring for a patient with severe COPD. The physician orders oxygen at 2 L/min via nasal cannula. Why is low-flow oxygen used for COPD patients?",
    [O("A","High-flow oxygen is too expensive for long-term use"), O("B","Patients with chronic CO2 retention (COPD) rely on HYPOXIC DRIVE for respiratory stimulation; high-flow oxygen can suppress this drive, leading to hypoventilation, CO2 narcosis, and respiratory failure; target SpO2 88-92% for these patients"), O("C","All patients should receive oxygen at exactly 2 L/min regardless of diagnosis"), O("D","Low-flow oxygen tastes better than high-flow oxygen")],
    ["B"],"In healthy individuals, the primary respiratory drive is rising CO2 levels (hypercapnic drive) detected by central chemoreceptors in the medulla. In patients with chronic COPD and chronic CO2 retention, the medullary chemoreceptors become desensitized to elevated CO2. These patients shift to a HYPOXIC DRIVE, where breathing is stimulated by LOW oxygen levels detected by peripheral chemoreceptors in the carotid and aortic bodies. If high-flow oxygen eliminates hypoxemia in these patients, the respiratory drive is removed, leading to hypoventilation, further CO2 accumulation (CO2 narcosis), respiratory acidosis, and potentially respiratory arrest. Therefore: maintain SpO2 88-92% (NOT 95-100%), use low-flow oxygen (1-2 L/min NC), and monitor for signs of CO2 retention (confusion, somnolence, headache).",
    "COPD + chronic CO2 retention = hypoxic drive; low-flow O2 (1-2 L/min); target SpO2 88-92%; high O2 can cause respiratory failure", ["COPD","oxygen-therapy","hypoxic-drive","CO2-retention","respiratory"]);

  pn("Physiological Integrity","Urinary Catheter Care","Physiological Integrity",2,
    "An LPN is providing care for a patient with an indwelling urinary catheter. Which nursing intervention helps PREVENT catheter-associated urinary tract infection (CAUTI)?",
    [O("A","Raise the drainage bag above the level of the bladder to promote gravity flow"), O("B","Maintain a closed drainage system, keep the drainage bag BELOW the level of the bladder at all times, perform perineal care with soap and water daily, secure the catheter to the thigh (female) or lower abdomen (male) to prevent traction, and advocate for early catheter removal"), O("C","Disconnect and reconnect the catheter tubing daily to flush the system"), O("D","Clean the catheter insertion site with alcohol three times daily")],
    ["B"],"CAUTI prevention follows evidence-based HOUDINI criteria for catheter removal (Hematuria, Obstruction, Urological procedure, Decubitus ulcer management, Input/output monitoring in critical illness, Nursing of end-of-life care, Immobility). Prevention measures: CLOSED SYSTEM (never disconnect the catheter from the drainage bag unless irrigating per order), GRAVITY drainage (bag ALWAYS below the bladder level but OFF the floor), PERINEAL CARE (soap and water, not antiseptics, daily and after each bowel movement), SECURE the catheter (prevents traction on the urethra and bladder neck; tape to THIGH in females, LOWER ABDOMEN in males to follow the natural curve), HAND HYGIENE before and after handling, ADEQUATE HYDRATION, and EARLY REMOVAL (the single most important intervention for CAUTI prevention).",
    "CAUTI prevention: closed system, bag below bladder, perineal care, secure catheter, early removal (most important intervention)", ["CAUTI","urinary-catheter","infection-prevention","indwelling-catheter","patient-safety"]);

  pn("Physiological Integrity","Chest Tube Management","Physiological Integrity",3,
    "An LPN is assisting with the care of a patient who has a chest tube connected to a water-seal drainage system. Which observation indicates the system is functioning properly?",
    [O("A","Continuous vigorous bubbling in the water-seal chamber during normal breathing"), O("B","Gentle tidaling (fluctuation of the water level in the water-seal chamber that rises with inspiration and falls with expiration in a spontaneously breathing patient), intermittent bubbling in the suction control chamber, and the drainage system positioned below the chest level"), O("C","No fluid movement in any chamber of the drainage system"), O("D","The drainage tubing is clamped to prevent air leaks")],
    ["B"],"Water-seal chest drainage systems have three chambers: (1) COLLECTION chamber (collects drainage; measure and document output), (2) WATER-SEAL chamber (acts as a one-way valve preventing air from entering the pleural space; look for TIDALING - gentle fluctuation of water level that corresponds with breathing, which confirms the system is patent and functioning. In spontaneously breathing patients: water rises with INSPIRATION (negative pleural pressure) and falls with expiration. In mechanically ventilated patients: opposite pattern), (3) SUCTION CONTROL chamber (controls the amount of suction; gentle continuous bubbling in this chamber is NORMAL when wall suction is applied). CONCERNING FINDINGS: continuous bubbling in the WATER-SEAL chamber (indicates an air leak - check all connections, tubing, and insertion site), sudden cessation of tidaling (could indicate tube obstruction, lung re-expansion, or tube dislodgement), or sudden large output of bright red blood.",
    "Chest tube: tidaling = good (system patent); continuous bubbling in water-seal = air leak; keep system below chest level; never clamp", ["chest-tube","water-seal","tidaling","drainage","pneumothorax"]);

  pn("Physiological Integrity","Tracheostomy Emergency","Physiological Integrity",3,
    "An LPN is caring for a patient with a tracheostomy when the inner cannula becomes occluded with thick secretions and the patient develops respiratory distress. What is the PRIORITY action?",
    [O("A","Wait for the respiratory therapist to arrive before taking any action"), O("B","Remove the inner cannula immediately (it is designed to be removable for cleaning), suction the outer cannula if needed, clean or replace the inner cannula, and prepare to provide manual ventilation via the tracheostomy if respiratory distress continues"), O("C","Remove the entire tracheostomy tube and reinsert a new one"), O("D","Administer oral medications to thin the secretions")],
    ["B"],"Tracheostomy tubes have two parts: the OUTER CANNULA (the main tube inserted into the trachea; secured with ties/Velcro around the neck) and the INNER CANNULA (a removable tube that fits inside the outer cannula; designed for easy removal and cleaning to maintain airway patency). In an emergency with a mucus-plugged inner cannula: (1) REMOVE the inner cannula immediately (twist and pull - this is a nursing action that does not require a physician order in an emergency), (2) This immediately opens the airway through the larger outer cannula, (3) SUCTION through the outer cannula if needed, (4) CLEAN the inner cannula with hydrogen peroxide solution then rinse with saline, or replace with a clean inner cannula, (5) If the patient remains in distress after inner cannula removal, provide manual ventilation via a bag-valve connected to the tracheostomy, (6) Have the emergency tracheostomy tray at the bedside (obturator, spare tracheostomy tube one size smaller, and scissors for cutting ties).",
    "Tracheostomy emergency: remove inner cannula first (designed to be removable); suction outer cannula; keep emergency tray at bedside", ["tracheostomy","inner-cannula","airway-obstruction","emergency","respiratory"]);

  pn("Health Promotion","Fall Prevention","Health Promotion",2,
    "An LPN is implementing fall prevention strategies for a 78-year-old patient identified as a fall risk. Which intervention is MOST important?",
    [O("A","Keep the patient in bed with all four side rails raised at all times"), O("B","Keep the bed in the LOWEST position with wheels locked, ensure the call light is within reach, provide non-skid footwear, keep the environment well-lit and free of clutter, toilet on a schedule, review medications that increase fall risk (sedatives, antihypertensives, diuretics), and use a fall risk identification system"), O("C","Apply physical restraints to keep the patient in the chair"), O("D","Remove the call light to encourage the patient to walk independently")],
    ["B"],"Evidence-based fall prevention uses a multimodal approach: ENVIRONMENTAL: bed in LOWEST position (reduces injury height), wheels LOCKED, call light within reach, adequate lighting (especially night lights), clear pathways free of clutter, non-skid footwear (no slippers), wet floor signs, assistive devices within reach. NOTE: raising ALL FOUR side rails constitutes a RESTRAINT and can actually INCREASE fall risk (patients climb over them and fall from a greater height). PHYSIOLOGICAL: toilet on a schedule (many falls occur going to the bathroom), review medications (polypharmacy, sedatives, antihypertensives, opioids increase risk), assess orthostatic hypotension, ensure adequate nutrition and hydration. PATIENT EDUCATION: use the call light before getting up, rise slowly, wear non-skid footwear. IDENTIFICATION: fall risk bracelet/wristband, door signage, bed alarm if appropriate.",
    "Fall prevention: bed lowest position, call light in reach, non-skid shoes, toileting schedule, review meds; all 4 rails up = restraint = INCREASES fall risk", ["fall-prevention","safety","elderly","bed-position","environment"]);

  pn("Physiological Integrity","Blood Transfusion Reaction","Physiological Integrity",3,
    "An LPN is monitoring a patient receiving a unit of packed red blood cells. Fifteen minutes after the transfusion begins, the patient develops fever, chills, flank pain, dark urine, and hypotension. What should the LPN do FIRST?",
    [O("A","Slow the transfusion rate and continue monitoring"), O("B","STOP the transfusion IMMEDIATELY, maintain IV access with normal saline using NEW tubing, take vital signs, notify the RN and physician, save the blood bag and tubing for the blood bank to analyze, collect blood and urine specimens as ordered"), O("C","Administer acetaminophen and continue the transfusion"), O("D","Increase the transfusion rate to complete it faster")],
    ["B"],"The symptoms described (fever, chills, flank/back pain, dark urine/hemoglobinuria, hypotension) indicate an ACUTE HEMOLYTIC TRANSFUSION REACTION, the most serious and potentially fatal type of transfusion reaction. It is usually caused by ABO blood type incompatibility where recipient antibodies attack donor RBCs, causing massive intravascular hemolysis. NURSING ACTIONS: (1) STOP the transfusion IMMEDIATELY (this is always the FIRST action for ANY transfusion reaction), (2) Maintain IV access with NORMAL SALINE via NEW tubing (do not flush old blood through the line), (3) Take vital signs, (4) Notify the RN and physician STAT, (5) Return the blood bag and tubing to the blood bank, (6) Collect blood samples (direct Coombs test, free hemoglobin, repeat crossmatch) and urine (hemoglobinuria), (7) Maintain strict I&O (monitor for acute kidney injury from hemoglobin precipitation in renal tubules), (8) Prepare for possible need for fluids, vasopressors, and dialysis.",
    "Transfusion reaction: STOP transfusion FIRST, NS with new tubing, save blood bag, notify physician; hemolytic reaction = flank pain + dark urine + fever", ["blood-transfusion","hemolytic-reaction","ABO-incompatibility","nursing-action","hematology"]);

  pn("Physiological Integrity","Wound Infection Signs","Physiological Integrity",2,
    "An LPN is assessing a surgical wound on post-operative day 4. Which finding indicates a wound INFECTION?",
    [O("A","Mild pinkness and warmth along the incision edges with no drainage"), O("B","Increasing erythema extending beyond the wound margins, warmth, edema, purulent (thick yellow-green) drainage, foul odor, fever, elevated WBC count, and increasing wound pain after initial improvement"), O("C","Scab formation over the incision line"), O("D","Slight serous drainage from the wound on post-op day 1")],
    ["B"],"Wound infection assessment uses the classic signs of inflammation/infection (REMEMBER: calor, dolor, rubor, tumor, functio laesa = heat, pain, redness, swelling, loss of function). Specific wound infection indicators: ERYTHEMA extending beyond wound edges (not just mild incision-line redness, which is normal healing), WARMTH, EDEMA, PURULENT DRAINAGE (thick, opaque, yellow/green/tan with possible foul odor), FEVER (especially >38.3°C or 101°F after post-op day 2), ELEVATED WBC (leukocytosis), INCREASING PAIN (pain should gradually decrease after surgery; increasing pain after initial improvement suggests infection or dehiscence), and WOUND DEHISCENCE (partial or complete opening of the wound layers). NORMAL healing findings: mild pinkness along incision (granulation tissue), serous/serosanguineous drainage in first 24-48 hours, scab/eschar formation. Wound infections typically manifest on post-op days 3-7.",
    "Wound infection: erythema beyond margins + warmth + purulent drainage + fever + increasing pain; typically POD 3-7; normal = mild pink, serous drainage", ["wound-infection","surgical-wound","assessment","post-operative","infection-signs"]);

  pn("Physiological Integrity","Colostomy Care Education","Physiological Integrity",2,
    "An LPN is teaching a patient about caring for their new colostomy. Which instruction is correct?",
    [O("A","The stoma should appear pale white or dusky blue"), O("B","The stoma should appear moist, beefy red (like the inside of the mouth), and slightly raised from the skin surface; change the pouching system when 1/3 full, cut the barrier opening 1/8 inch larger than the stoma, empty when 1/3 to 1/2 full, and notify the physician if the stoma becomes dusky, dark, or black (ischemia)"), O("C","Apply adhesive tape directly over the stoma to secure the pouch"), O("D","Irrigate the colostomy with hot water to stimulate bowel movements")],
    ["B"],"Colostomy care teaching points: STOMA ASSESSMENT: should be MOIST, BEEFY RED (well-perfused), and SLIGHTLY RAISED (1-2 cm above skin surface). Report: dusky/blue/black color (ischemia), prolapse (excessive protrusion), retraction (stoma below skin level), or excessive bleeding. POUCHING: cut the skin barrier opening 1/8 inch (3mm) LARGER than the stoma to prevent pressure on the stoma while protecting peristomal skin; change the entire system every 3-7 days or when the seal breaks; EMPTY the pouch when 1/3 to 1/2 full (not completely full - weight pulls the seal and causes leakage). SKIN CARE: clean peristomal skin with warm water (no soap with moisturizers, as they prevent barrier adhesion); apply skin barrier powder to irritated skin; ensure no skin is exposed between the stoma and barrier. DIET: avoid gas-producing foods (beans, cabbage, onions), chew food thoroughly, introduce new foods one at a time.",
    "Stoma: moist beefy red (healthy); dusky/black = ischemia (emergency); cut barrier 1/8 inch larger; empty pouch at 1/3-1/2 full", ["colostomy","stoma","ostomy-care","patient-education","GI"]);

  pn("Physiological Integrity","Glaucoma Types","Physiological Integrity",2,
    "An LPN is caring for a patient diagnosed with narrow-angle (angle-closure) glaucoma who presents with sudden severe eye pain, nausea, seeing halos around lights, and a fixed mid-dilated pupil. How does this differ from open-angle glaucoma?",
    [O("A","Both types present identically with the same symptoms and urgency"), O("B","Angle-closure glaucoma is a MEDICAL EMERGENCY with sudden onset (severe eye pain, headache, nausea/vomiting, halos around lights, blurred vision, fixed mid-dilated pupil, rock-hard eye); open-angle glaucoma is CHRONIC and GRADUAL with NO symptoms until peripheral vision loss occurs (the 'silent thief of sight')"), O("C","Open-angle glaucoma is the emergency form requiring immediate surgery"), O("D","Narrow-angle glaucoma only affects children while open-angle affects adults")],
    ["B"],"Glaucoma is a group of diseases characterized by increased intraocular pressure (IOP) that damages the optic nerve, leading to vision loss. Two main types: OPEN-ANGLE (chronic, accounts for 90% of cases): gradual, painless, bilateral. The trabecular meshwork becomes clogged over time, slowing aqueous humor drainage. Patients typically notice no symptoms until PERIPHERAL VISION LOSS occurs (tunnel vision), hence 'silent thief of sight.' Treatment: prostaglandin analogs (latanoprost), beta-blockers (timolol), alpha-agonists (brimonidine). ANGLE-CLOSURE (acute, 10% of cases): MEDICAL EMERGENCY. The iris physically blocks the trabecular meshwork, causing rapid IOP elevation (>40 mmHg). Symptoms: sudden severe eye pain, headache, N/V, halos, blurred vision, FIXED MID-DILATED PUPIL (diagnostic), red eye, rock-hard globe on palpation. Treatment: immediate laser iridotomy, miotics (pilocarpine to constrict pupil and open drainage angle), IV acetazolamide, osmotic agents (mannitol).",
    "Angle-closure glaucoma: EMERGENCY (sudden pain, fixed pupil, halos); Open-angle: chronic silent peripheral vision loss; avoid mydriatics in angle-closure", ["glaucoma","angle-closure","open-angle","IOP","ophthalmology"]);

  pn("Physiological Integrity","Spica Cast Care","Physiological Integrity",2,
    "An LPN is teaching parents about caring for their toddler who has a hip spica cast after a femur fracture repair. Which instruction is MOST important?",
    [O("A","Insert objects under the cast if the child complains of itching"), O("B","Check circulation distal to the cast frequently (assess the 5 Ps: Pain, Pallor, Pulselessness, Paresthesias, Paralysis), petal the rough edges of the cast with moleskin tape, keep the cast clean and dry, elevate to reduce swelling, and NEVER insert objects under the cast (risk of skin breakdown and infection)"), O("C","Get the cast wet during bath time to keep it clean"), O("D","The cast does not require any special monitoring since the child is young")],
    ["B"],"Hip spica cast covers the trunk and one or both legs for femur fractures or hip dysplasia in pediatric patients. CIRCULATION CHECK (5 Ps): PAIN (increasing, unrelieved by elevation or prescribed analgesics suggests compartment syndrome), PALLOR (compare color to unaffected extremity), PULSELESSNESS (check pedal pulses), PARESTHESIAS (numbness/tingling - may be difficult to assess in toddlers; observe for crying or irritability), PARALYSIS (inability to move toes - a late and ominous sign). CAST CARE: petal rough edges with moleskin or waterproof tape to prevent skin irritation; keep cast CLEAN and DRY (do not submerge in water; waterproof the perineal area with plastic wrap for toileting); do NOT insert objects under the cast (pencils, hangers, etc. can cause skin breakdown, burns, or infection); do NOT use powders or lotions under the cast. FEEDING: position child at 30-45 degree angle to prevent aspiration; small frequent meals. TURNING: turn every 2 hours to prevent skin breakdown.",
    "Spica cast: check 5 Ps (circulation), petal edges, keep dry, NEVER insert objects under cast; turn every 2 hours", ["spica-cast","pediatric","femur-fracture","circulation-check","cast-care"]);

  pn("Physiological Integrity","Addison Disease vs Cushing","Physiological Integrity",3,
    "An LPN is caring for a patient with Addison disease (primary adrenal insufficiency). Which cluster of symptoms should the LPN expect?",
    [O("A","Moon face, buffalo hump, weight gain, hyperglycemia, and hypertension"), O("B","Hyperpigmentation (bronzed skin), hypotension, hyponatremia, hyperkalemia, weight loss, fatigue, weakness, and salt craving; Addison disease is the OPPOSITE of Cushing syndrome"), O("C","Excess facial hair growth, acne, and central obesity"), O("D","Exophthalmos, tachycardia, and heat intolerance")],
    ["B"],"Addison disease (primary adrenal insufficiency) results from destruction of the adrenal cortex causing deficiency of CORTISOL (glucocorticoid) and ALDOSTERONE (mineralocorticoid). Clinical manifestations reflect the ABSENCE of these hormones: HYPERPIGMENTATION (bronzed/tanned skin, especially in skin creases, buccal mucosa, nipples - from elevated ACTH stimulating melanocyte-stimulating hormone), HYPOTENSION (from aldosterone deficiency causing sodium and water loss), HYPONATREMIA (sodium wasting), HYPERKALEMIA (potassium retention from aldosterone deficiency), WEIGHT LOSS, FATIGUE, WEAKNESS, ANOREXIA, NAUSEA, SALT CRAVING (from sodium depletion). This is the CLINICAL OPPOSITE of Cushing syndrome (cortisol excess): Cushing = hypertension, hypernatremia, hypokalemia, hyperglycemia, weight gain, moon face, buffalo hump, striae. ADDISONIAN CRISIS (acute adrenal insufficiency): life-threatening emergency with severe hypotension, shock, hyponatremia, hyperkalemia; triggered by stress, infection, or abrupt discontinuation of exogenous corticosteroids. Treatment: lifelong cortisol (hydrocortisone) and aldosterone (fludrocortisone) replacement.",
    "Addison = opposite of Cushing: hyperpigmentation, hypotension, hyponatremia, hyperkalemia, weight loss; crisis = vascular collapse = emergency", ["Addison","adrenal-insufficiency","cortisol","aldosterone","endocrine"]);

  // ===== NCLEX-RN MEGA BATCH =====

  rn("Cardiac","Cardiac Catheterization Post-Op","Physiological Integrity",3,
    "An RN is monitoring a patient after a cardiac catheterization performed via the right femoral artery approach. Which post-procedure assessment is MOST critical?",
    [O("A","Check the patient's appetite and encourage oral intake"), O("B","Assess the femoral puncture site for hematoma, bleeding, or bruit (indicates pseudoaneurysm); check distal pulses (dorsalis pedis and posterior tibial), skin color, temperature, sensation, and capillary refill of the affected extremity every 15 minutes for the first hour, then per protocol; keep the affected leg straight and the HOB ≤30 degrees for the prescribed period"), O("C","Encourage the patient to ambulate immediately after the procedure"), O("D","Post-procedure assessment focuses only on the cardiac rhythm")],
    ["B"],"Post-cardiac catheterization (femoral approach) nursing care: SITE ASSESSMENT: check puncture site for HEMATOMA (expanding firmness around site), BLEEDING (apply pressure if oozing), ECCHYMOSIS, and BRUIT (audible with stethoscope, suggests pseudoaneurysm formation). NEUROVASCULAR ASSESSMENT of the affected extremity (5 Ps): check PULSES (dorsalis pedis, posterior tibial - mark pulse locations pre-procedure for comparison), COLOR (compare bilaterally), TEMPERATURE (cool extremity suggests arterial occlusion), SENSATION, CAPILLARY REFILL (<3 seconds normal), and MOTOR FUNCTION. Frequency: every 15 min × 1 hour, every 30 min × 2 hours, then hourly × 4 hours (varies by facility). POSITIONING: keep the affected leg STRAIGHT (no bending at the hip), HOB ≤30 degrees, for 4-6 hours (varies based on closure device used). HYDRATION: encourage fluids (PO or IV) to flush contrast dye and prevent contrast-induced nephropathy. Monitor urine output (>30 mL/hr), BUN/creatinine. COMPLICATIONS to watch for: retroperitoneal hemorrhage (back/flank pain, tachycardia, hypotension), arterial thrombosis, pseudoaneurysm, AV fistula.",
    "Post-cardiac cath (femoral): check site for bleeding/hematoma, distal pulses q15min, leg straight, hydrate to flush contrast, monitor renal function", ["cardiac-catheterization","femoral-site","hematoma","pulse-check","post-procedure"]);

  rn("Pharmacology","Heparin vs Enoxaparin","Physiological Integrity",3,
    "An RN is comparing unfractionated heparin (UFH) and low-molecular-weight heparin (LMWH/enoxaparin). Which comparison is CORRECT?",
    [O("A","Both medications have identical administration routes, monitoring requirements, and antidotes"), O("B","UFH requires continuous IV infusion with aPTT monitoring (therapeutic range 1.5-2.5 times control) and is reversible with protamine sulfate; enoxaparin (LMWH) is given SubQ with predictable dosing requiring no routine coagulation monitoring (anti-Xa levels in renal impairment or obesity), and is partially reversible with protamine"), O("C","Enoxaparin requires more frequent lab monitoring than UFH"), O("D","UFH is given subcutaneously once weekly while enoxaparin requires continuous IV infusion")],
    ["B"],"Heparin comparison: UNFRACTIONATED HEPARIN (UFH): Route: IV (continuous infusion for therapeutic anticoagulation) or SubQ (prophylactic dosing). Monitoring: aPTT every 6 hours initially (therapeutic range 1.5-2.5 × control, typically 60-80 seconds). Onset: immediate IV, 1-2 hours SubQ. Half-life: 1-2 hours (short, advantage in high-bleeding-risk patients). Antidote: PROTAMINE SULFATE (1 mg neutralizes 100 units heparin; give slowly IV, max 50 mg; risk of hypotension, bradycardia, anaphylaxis). Side effect: heparin-induced thrombocytopenia (HIT) type II. LOW-MOLECULAR-WEIGHT HEPARIN (enoxaparin/Lovenox): Route: SubQ ONLY (NEVER IV except in specific acute coronary syndrome protocols). Monitoring: NO routine coagulation monitoring needed (predictable dose-response); anti-Xa levels only if: renal insufficiency, obesity, or pregnancy. Administration: inject into the ABDOMEN (alternate sides), do NOT aspirate or rub after injection, inject into the fatty tissue. Half-life: 4-6 hours (allows q12h or once-daily dosing). Antidote: protamine sulfate partially reverses enoxaparin (~60% neutralization).",
    "UFH: IV, aPTT monitoring, protamine reverses; LMWH (enoxaparin): SubQ abdomen, no routine monitoring, partially reversed by protamine", ["heparin","enoxaparin","anticoagulation","aPTT","comparison"]);

  rn("Respiratory","ARDS Management","Physiological Integrity",4,
    "An RN is caring for a patient with acute respiratory distress syndrome (ARDS). The patient is mechanically ventilated with FiO2 80% and PEEP of 10 cmH2O, but the PaO2 remains at 55 mmHg. Which intervention should the RN anticipate?",
    [O("A","Decrease the PEEP to reduce barotrauma risk"), O("B","Increase PEEP (to recruit collapsed alveoli and improve oxygenation) while using lung-protective ventilation strategy: low tidal volumes (4-8 mL/kg ideal body weight), plateau pressure <30 cmH2O; anticipate prone positioning if PaO2/FiO2 ratio remains <150"), O("C","Remove the patient from the ventilator and provide oxygen via nasal cannula"), O("D","Increase the tidal volume to 15 mL/kg to improve oxygenation")],
    ["B"],"ARDS is characterized by severe hypoxemia refractory to supplemental oxygen, bilateral lung infiltrates, and non-cardiogenic pulmonary edema. The hallmark is a PaO2/FiO2 ratio <300 (mild), <200 (moderate), <100 (severe). This patient: PaO2/FiO2 = 55/0.8 = 69, which is SEVERE ARDS. Management follows the ARDSNet lung-protective ventilation strategy: LOW TIDAL VOLUMES (4-8 mL/kg of IDEAL body weight, not actual weight; this prevents ventilator-induced lung injury/VILI from overdistension), PLATEAU PRESSURE <30 cmH2O (to prevent barotrauma), ADEQUATE PEEP (positive end-expiratory pressure recruits collapsed alveoli, improves V/Q matching, and increases the surface area available for gas exchange; higher PEEP tables guide adjustment based on FiO2 requirements), PERMISSIVE HYPERCAPNIA (accepting higher CO2 to maintain lung-protective tidal volumes). PRONE POSITIONING for ≥16 hours/day is recommended for moderate-severe ARDS (P/F <150) and has been shown to reduce mortality by improving ventilation-perfusion matching.",
    "ARDS: lung-protective ventilation (low TV 4-8 mL/kg IBW, plateau <30, adequate PEEP); prone positioning if P/F <150; permissive hypercapnia acceptable", ["ARDS","lung-protective","PEEP","prone-positioning","critical-care"]);

  rn("Endocrine","DKA vs HHS","Physiological Integrity",4,
    "An RN is differentiating between diabetic ketoacidosis (DKA) and hyperosmolar hyperglycemic state (HHS). Which comparison is CORRECT?",
    [O("A","DKA and HHS are the same condition with identical management"), O("B","DKA occurs primarily in type 1 DM with glucose typically 250-600 mg/dL, ketosis, metabolic acidosis (pH <7.3, bicarb <18), and Kussmaul breathing with fruity breath; HHS occurs primarily in type 2 DM with extreme hyperglycemia (>600 mg/dL, often >1000), hyperosmolality (>320 mOsm/kg), severe dehydration, but minimal or no ketosis and no acidosis"), O("C","HHS is less dangerous than DKA because there is no acidosis"), O("D","DKA requires only insulin while HHS requires only fluids")],
    ["B"],"DKA vs HHS: DKA: predominantly type 1 DM (can occur in type 2). Cause: absolute insulin deficiency → cells cannot use glucose → lipolysis produces ketone bodies → metabolic acidosis. Lab findings: glucose 250-600 mg/dL, pH <7.3, bicarb <18 mEq/L, positive serum/urine ketones, anion gap >12. Clinical: Kussmaul respirations (deep rapid breathing to blow off CO2), FRUITY breath (acetone), N/V, abdominal pain, dehydration. HHS: predominantly type 2 DM (often elderly, undiagnosed). Cause: enough insulin to prevent ketosis but insufficient to control glucose → extreme hyperglycemia → osmotic diuresis → severe dehydration. Lab findings: glucose >600 (often >1000), serum osmolality >320, pH >7.3, bicarb >18, minimal/no ketones. Clinical: altered mental status (from hyperosmolality), profound dehydration, seizures, focal neurological deficits. MORTALITY: HHS has HIGHER mortality (5-20%) vs DKA (1-5%) due to the extreme dehydration and the older, more comorbid patient population. TREATMENT (both): aggressive IV FLUID resuscitation first (normal saline), then IV regular insulin infusion, potassium replacement (insulin shifts K+ into cells), close monitoring.",
    "DKA: type 1, ketosis + acidosis, Kussmaul breathing, fruity breath; HHS: type 2, extreme hyperglycemia >600, no ketosis, higher mortality; both need fluids first then insulin", ["DKA","HHS","comparison","diabetic-emergency","endocrine"]);

  rn("Leadership","Delegation Scope","Safe & Effective Care Environment",3,
    "An RN is delegating tasks on a medical-surgical unit. Which task is MOST appropriate to delegate to an unlicensed assistive personnel (UAP)?",
    [O("A","Perform the initial assessment on a newly admitted patient"), O("B","Measure and record vital signs, intake and output, and daily weights on stable patients; assist with activities of daily living (bathing, feeding, ambulation); perform fingerstick blood glucose testing; and report any abnormal findings to the RN immediately"), O("C","Administer IV medications and titrate vasoactive drips"), O("D","Teach a newly diagnosed heart failure patient about fluid restriction and daily weights")],
    ["B"],"Delegation to UAP follows the Five Rights of Delegation: Right TASK (routine, standardized, does not require nursing judgment), Right CIRCUMSTANCE (stable, predictable patients), Right PERSON (UAP has been trained and is competent), Right DIRECTION (clear, specific instructions with expected parameters), Right SUPERVISION (RN follows up and evaluates outcomes). UAP CAN: vital signs on stable patients, I&O measurement, daily weights, ADL assistance (bathing, grooming, feeding, toileting, ambulation), fingerstick blood glucose (but RN interprets and acts on results), empty drainage devices (Foley, JP drain) and measure output, specimen collection, CPR, positioning and turning, transport. UAP CANNOT: ANY assessment (initial, ongoing, or discharge), administer medications (any route), insert or remove invasive devices (catheters, NG tubes, IV access), receive verbal or telephone orders, perform any teaching, triage, make clinical judgments, or develop/modify the care plan. The RN is ALWAYS accountable for the delegation decision and patient outcomes.",
    "UAP: vital signs, I&O, ADLs, fingerstick glucose, specimens; NEVER: assessment, medications, teaching, clinical judgment; RN always accountable", ["delegation","UAP","scope-of-practice","Five-Rights","leadership"]);

  rn("Maternal-Newborn","Preeclampsia Management","Physiological Integrity",4,
    "An RN is caring for a patient at 34 weeks gestation diagnosed with severe preeclampsia. BP is 168/110, proteinuria 3+, and the patient reports a severe headache and visual changes. Which medication is the PRIORITY?",
    [O("A","Oxytocin to induce labor immediately"), O("B","IV magnesium sulfate to prevent eclamptic seizures; the loading dose is 4-6g IV over 20-30 minutes, followed by a maintenance infusion of 1-2g/hour; monitor for magnesium toxicity (loss of deep tendon reflexes is the FIRST sign, followed by respiratory depression and cardiac arrest); keep calcium gluconate at the bedside as the antidote"), O("C","Ibuprofen for the headache"), O("D","Metformin to control blood pressure")],
    ["B"],"Severe preeclampsia with symptoms (severe headache, visual changes/scotomata, epigastric/RUQ pain, pulmonary edema) is an obstetric emergency. MAGNESIUM SULFATE is the drug of choice for SEIZURE PROPHYLAXIS (not primarily for BP control): Loading dose 4-6g IV over 20-30 min, then maintenance 1-2g/hr. MONITORING for magnesium toxicity (therapeutic level 4-7 mEq/L): check DTRs every 1-2 hours (loss of patellar reflexes at 7-10 mEq/L is the FIRST sign of toxicity), respiratory rate ≥12/min (respiratory depression at 10-15 mEq/L), urine output ≥30 mL/hr (magnesium is renally excreted; oliguria → accumulation → toxicity), LOC (lethargy/confusion at higher levels), cardiac arrest at >25 mEq/L. ANTIDOTE: CALCIUM GLUCONATE 1g IV push (must be at bedside at ALL times). BP CONTROL: IV labetalol or hydralazine (NOT ACE inhibitors or ARBs - teratogenic; NOT diuretics - patient is already intravascularly depleted). Definitive treatment: DELIVERY of the baby (the only cure for preeclampsia).",
    "Preeclampsia: MgSO4 for seizure prevention; monitor DTRs (first sign of toxicity), RR ≥12, UO ≥30; antidote = calcium gluconate; definitive treatment = delivery", ["preeclampsia","magnesium-sulfate","seizure-prevention","obstetrics","high-risk"]);

  rn("Oncology","Chemotherapy Safety","Physiological Integrity",3,
    "An RN is administering chemotherapy to an oncology patient. Which safety precautions are essential for handling chemotherapy agents?",
    [O("A","No special precautions are needed when handling chemotherapy medications"), O("B","Wear double gloves (chemotherapy-rated), non-permeable gown, face shield, and closed-system transfer devices; use a biological safety cabinet for preparation; manage spills with a chemotherapy spill kit; handle patient waste (urine, stool, vomit) for 48 hours post-administration with chemotherapy precautions; and chemotherapy waste goes in yellow hazardous waste containers"), O("C","Only wear gloves when cleaning up chemotherapy spills"), O("D","Chemotherapy agents are only hazardous if ingested, not through skin contact")],
    ["B"],"Chemotherapy agents are HAZARDOUS DRUGS that can cause mutagenic, teratogenic, and carcinogenic effects through occupational exposure. Safety precautions: PPE for handling: DOUBLE GLOVES (chemotherapy-tested, change every 30 min or when torn/contaminated), NON-PERMEABLE GOWN (disposable, closed-front), FACE SHIELD (if splash risk), goggles. PREPARATION: use a BIOLOGICAL SAFETY CABINET (BSC) or closed-system transfer device (CSTD); never eat, drink, or apply cosmetics in preparation areas. ADMINISTRATION: verify two patient identifiers and the 'rights' of medication administration; verify informed consent; use CSTD when possible; prime IV tubing with non-drug-containing fluid; monitor IV site for vesicant extravasation (stop infusion immediately if extravasation occurs; do NOT flush). EXPOSURE MANAGEMENT: spill kit (absorb, clean from outside in, double-bag waste); patient bodily fluids are considered contaminated for 48 HOURS after administration (urine, stool, blood, vomit, and sweat) - handle with chemotherapy gloves; male patients should use condoms for 48 hours. CONTRAINDICATIONS for nurses: pregnancy or attempting to conceive.",
    "Chemo safety: double gloves, gown, face shield; BSC for prep; patient waste hazardous for 48 hrs; spill kit; vesicant = stop infusion immediately", ["chemotherapy","safety","hazardous-drugs","PPE","oncology"]);

  // ===== MORE REx-PN =====

  rpn("Scope of Practice","RPN Scope Ontario","Safe & Effective Care Environment",2,
    "An RPN in Ontario is reviewing their scope of practice under the CNO standards. A physician asks the RPN to initiate blood product administration. What should the RPN do?",
    [O("A","Administer the blood product immediately as requested by the physician"), O("B","Respectfully decline as blood product initiation is outside the RPN's scope of practice in Ontario; the RPN should explain this to the physician, request that an RN initiate the transfusion, and offer to assist with monitoring vital signs and observing for transfusion reactions once the RN has initiated the infusion"), O("C","Administer the blood product but do not document it"), O("D","The RPN should administer the blood product since any licensed nurse can perform this task")],
    ["B"],"In Ontario, the College of Nurses of Ontario (CNO) defines the scope of practice for both RNs and RPNs. BLOOD PRODUCT ADMINISTRATION is a controlled act that falls within the RN scope of practice but is generally OUTSIDE the RPN scope. RPNs in Ontario: CAN perform medication administration (oral, SubQ, IM, some IV), wound care, data collection and focused assessments, implement established care plans, reinforce client teaching, perform vital signs and monitoring. CANNOT (without additional education and authorization): initiate blood products, perform initial comprehensive assessments, develop nursing care plans for complex/unstable patients, or manage patients whose conditions are unpredictable. The RPN should: (1) professionally decline using a respectful evidence-based approach referencing the CNO standards, (2) suggest an alternative (request an RN to perform the task), (3) offer what IS within scope (monitoring vital signs during transfusion, observing for reactions, documenting), (4) document the interaction. This reflects the principle of INTERPROFESSIONAL ACCOUNTABILITY.",
    "RPN Ontario: blood product initiation is OUTSIDE scope; decline respectfully, request RN, offer to monitor; CNO defines scope boundaries", ["RPN-scope","CNO","blood-products","Ontario","interprofessional"]);

  rpn("Cultural Safety","Indigenous Cultural Safety","Psychosocial Integrity",2,
    "An RPN is providing care to an Indigenous patient who requests a smudging ceremony (burning of sacred medicines like sage, sweetgrass, cedar, or tobacco) in the hospital. What is the culturally safe nursing response?",
    [O("A","Refuse the request immediately because burning anything in a hospital is a fire hazard and cannot be accommodated under any circumstances"), O("B","Facilitate the request by following the facility's Indigenous patient services protocol; contact the Indigenous health navigator or spiritual care services, arrange for a safe space (may include temporarily disabling room smoke detectors with security notification and fire watch), and support the patient's right to culturally safe care and traditional healing practices"), O("C","Tell the patient that Western medicine is the only appropriate treatment in a hospital"), O("D","Allow the patient to smudge anywhere in the hospital without any safety considerations")],
    ["B"],"Smudging is a sacred Indigenous ceremony involving the burning of sacred medicines (sage, sweetgrass, cedar, and/or tobacco) for purification, prayer, and healing. It is considered essential to the physical, emotional, mental, and spiritual well-being of many Indigenous peoples. Culturally safe nursing practice recognizes: the TRC Calls to Action specifically address the right of Indigenous patients to their traditional healing practices in healthcare settings; many Canadian hospitals now have SMUDGING PROTOCOLS that accommodate this practice safely (designated smudging rooms, temporary smoke detector management with security notification, fire safety precautions, ventilation considerations); the RPN should ADVOCATE for the patient's request through proper channels (Indigenous health services, patient advocate, spiritual care, nursing management); declining without exploring options violates principles of cultural safety and can contribute to healthcare avoidance by Indigenous patients. This is not simply about tolerance - it is about actively supporting the patient's right to culturally appropriate care.",
    "Smudging: facilitate through hospital protocol, contact Indigenous health services; culturally safe care is a TRC obligation, not optional", ["smudging","Indigenous","cultural-safety","TRC","traditional-healing"]);

  rpn("Pharmacology","Canadian Metric Units","Physiological Integrity",2,
    "An RPN in Canada is reviewing a patient's blood glucose results. The laboratory reports a fasting blood glucose of 12.4 mmol/L. How does the RPN interpret this value?",
    [O("A","This is a normal fasting blood glucose level requiring no intervention"), O("B","This is significantly elevated above the normal fasting range (4.0-7.0 mmol/L); a fasting glucose ≥7.0 mmol/L on two occasions is diagnostic of diabetes mellitus according to Diabetes Canada guidelines; 12.4 mmol/L indicates hyperglycemia requiring assessment, intervention, and notification of the physician"), O("C","Blood glucose is only measured in mg/dL, not mmol/L"), O("D","12.4 mmol/L is below normal and indicates hypoglycemia")],
    ["B"],"In Canada, blood glucose is measured in MMOL/L (not mg/dL as in the US). Conversion: mg/dL ÷ 18 = mmol/L (or mmol/L × 18 = mg/dL). So 12.4 mmol/L ≈ 223 mg/dL. Canadian blood glucose reference values (Diabetes Canada 2018 guidelines): NORMAL fasting: 4.0-7.0 mmol/L (72-126 mg/dL); TARGET for most diabetics: fasting 4.0-7.0, 2-hour postprandial 5.0-10.0 mmol/L; DIAGNOSIS of diabetes: fasting plasma glucose ≥7.0 mmol/L on two occasions, OR random glucose ≥11.1 mmol/L with symptoms, OR HbA1c ≥6.5%, OR 2-hour OGTT ≥11.1 mmol/L. HYPOGLYCEMIA: <4.0 mmol/L (the Rule of 15 in Canada: treat with 15g fast-acting carbohydrate, recheck in 15 minutes). RPNs must be familiar with BOTH unit systems as some references and patient transfers from the US may use mg/dL.",
    "Canada uses mmol/L for glucose; normal fasting 4.0-7.0 mmol/L; ≥7.0 = diabetes (×18 to convert to mg/dL); hypo = <4.0 mmol/L", ["blood-glucose","mmol-L","Canadian-units","diabetes","Diabetes-Canada"]);

  rpn("Community Health","Home Care Assessment","Health Promotion",2,
    "An RPN conducting a home care visit assesses the patient's living environment. Which finding poses the GREATEST safety risk for an elderly patient living alone?",
    [O("A","A well-organized kitchen with non-slip mats"), O("B","Loose scatter rugs on hardwood floors, poor lighting in hallways and stairways, no grab bars in the bathroom, medications stored in unlabeled containers, and expired food in the refrigerator"), O("C","A smoke detector installed on each floor"), O("D","A clearly labeled medication organizer on the kitchen counter")],
    ["B"],"Home safety assessment for elderly patients is a key component of community health nursing in Canada. Risk factors identified: SCATTER RUGS on smooth floors (tripping hazard - the #1 modifiable fall risk factor in the home; remove or secure with double-sided tape), POOR LIGHTING (inadequate lighting in hallways, stairways, and bathrooms contributes to falls; recommend nightlights, brighter bulbs, light switches accessible from bed), NO GRAB BARS (bathrooms are the highest-risk area for falls; recommend grab bars by toilet and in shower/tub, non-slip bath mats, raised toilet seat), UNLABELED MEDICATIONS (medication errors are a leading cause of preventable harm in elderly; recommend a weekly pill organizer, proper labeling, medication review with pharmacist), EXPIRED FOOD (indicates possible cognitive decline, nutritional risk, or limited access to fresh food - consider referral to Meals on Wheels or community food programs). The RPN should document findings, implement immediate safety measures, provide education, and make appropriate referrals (CCAC/LHIN for additional home support services).",
    "Home safety: remove scatter rugs, improve lighting, add grab bars, organize medications, check nutrition; refer to CCAC/LHIN for support", ["home-safety","elderly","fall-prevention","community-nursing","home-care"]);

  return qs;
}

async function main() {
  console.log("=== Massive Batch 2 ===\n");
  const before = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("BEFORE:"); for (const r of before.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs = build();
  const bk: Record<string,number> = {};
  for (const q of allQs) bk[q.exam] = (bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`, bk);
  let ins=0, dup=0, err=0;
  for (const q of allQs) {
    const h = sh(q.stem);
    try {
      const ex = await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`, [h, q.tier, q.exam]);
      if (ex.rows.length > 0) { dup++; continue; }
      await pool.query(
        `INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at)
         VALUES (gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,
        [q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,
         "Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);
      ins++;
    } catch (e: any) { err++; console.error(`ERR: ${e.message.substring(0,100)}`); }
  }
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("\nAFTER:"); for (const r of after.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session = await pool.query(`SELECT exam, COUNT(*)::int as cnt FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at > NOW() - INTERVAL '12 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:"); for (const r of session.rows) console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}

main().catch(e => { console.error("Fatal:", e); process.exit(1); });
