import crypto from "crypto";
import pg from "pg";
const pool = new pg.Pool({ host: process.env.PGHOST||"helium", user: process.env.PGUSER||"postgres", password: process.env.PGPASSWORD||"password", database: process.env.PGDATABASE||"heliumdb", ssl:false });
function sh(t:string):string{return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16);}
const O=(l:string,t:string)=>({label:l,text:t});
interface Q{tier:string;exam:string;stem:string;options:{label:string;text:string}[];ca:string[];rat:string;diff:number;tags:string[];topic:string;sub:string;rs:string;cp:string;bs:string;}

function build():Q[]{
  const qs:Q[]=[];
  const pn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // ===== NCLEX-PN Batch 4 =====
  pn("Physiological Integrity","NG Tube Care","Physiological Integrity",2,
    "An LPN is verifying nasogastric (NG) tube placement before administering a tube feeding. What is the MOST reliable method to confirm placement?",
    [O("A","Inject air into the tube and listen for a swooshing sound over the epigastrium with a stethoscope (auscultatory method)"),O("B","Obtain an abdominal X-ray (radiographic verification is the gold standard for confirming NG tube placement); additionally, check pH of aspirated contents (gastric pH should be ≤5.5, acidic; intestinal pH is >6; respiratory/pulmonary pH is >7) and verify external tube marking has not changed"),O("C","Check placement only at the initial insertion; no further verification is needed"),O("D","Ask the patient if they can feel the tube in their stomach")],
    ["B"],"NG tube placement verification: the GOLD STANDARD is RADIOGRAPHIC CONFIRMATION (X-ray) at initial insertion. For ongoing verification before each feeding/medication: (1) CHECK pH of aspirated contents: gastric aspirate is ACIDIC (pH ≤5.5, often 1-4); intestinal aspirate is ≥6; respiratory/pulmonary aspirate is >7. (2) CHECK external tube MARKING (the mark placed at the naris during insertion should remain at the same position). (3) ASSESS aspirate APPEARANCE: gastric = grassy green, clear/colorless, or tan; intestinal = bile-stained yellow/golden; pulmonary = off-white or tan with mucus. The AUSCULTATORY method (air bolus + stethoscope) is NO LONGER considered reliable because it cannot reliably differentiate between gastric and pulmonary placement. If placement cannot be confirmed, do NOT administer feeding or medications until verified by X-ray.",
    "NG placement: X-ray is gold standard; check pH (gastric ≤5.5); check external marking; auscultatory method is NO LONGER reliable", ["NG-tube","placement-verification","tube-feeding","pH-testing","GI"]);

  pn("Physiological Integrity","Sickle Cell Crisis","Physiological Integrity",3,
    "An LPN is caring for a patient admitted with a sickle cell vaso-occlusive crisis. Which nursing intervention is the PRIORITY?",
    [O("A","Apply cold packs to painful areas and restrict fluid intake"),O("B","Administer prescribed analgesics promptly (including opioids for severe pain), provide aggressive IV hydration (to reduce blood viscosity and prevent further sickling), apply WARM compresses (cold causes vasoconstriction worsening the crisis), administer oxygen if SpO2 <95%, and monitor for complications (acute chest syndrome, splenic sequestration, stroke)"),O("C","Encourage vigorous exercise to improve circulation"),O("D","Administer aspirin to thin the blood and reduce clotting")],
    ["B"],"Sickle cell vaso-occlusive crisis occurs when sickled RBCs occlude microcirculation causing tissue ischemia and SEVERE pain. Nursing priorities: PAIN MANAGEMENT is the #1 priority - administer prescribed opioids promptly (DO NOT undertreat pain; patients are often undertreated due to bias); use patient-controlled analgesia (PCA) if available; assess pain regularly. IV HYDRATION: 1.5-2× maintenance to reduce blood viscosity, prevent dehydration (dehydration increases sickling), and promote renal perfusion. WARM COMPRESSES: vasodilation improves blood flow to occluded areas; NEVER apply COLD (causes vasoconstriction and worsens sickling). OXYGEN: administer if SpO2 <95% (hypoxia promotes sickling). Monitor for COMPLICATIONS: Acute Chest Syndrome (fever, chest pain, pulmonary infiltrate - leading cause of death), splenic sequestration (sudden spleen enlargement, hypovolemic shock), stroke, priapism, and aplastic crisis.",
    "Sickle cell crisis: pain management first (opioids), aggressive IV hydration, WARM compresses (never cold), O2 if SpO2<95%; watch for acute chest syndrome", ["sickle-cell","vaso-occlusive","pain-management","hydration","hematology"]);

  pn("Physiological Integrity","Tuberculosis Precautions","Safe & Effective Care Environment",2,
    "An LPN is assigned to care for a patient with active pulmonary tuberculosis (TB). Which infection control precautions are required?",
    [O("A","Standard precautions and contact precautions with gown and gloves only"),O("B","AIRBORNE PRECAUTIONS: private negative-pressure room with the door CLOSED, N95 respirator (fit-tested) for all healthcare workers entering the room, surgical mask on the patient during transport, and minimize patient transport out of the room; the patient remains on airborne precautions until three consecutive sputum AFB smears are NEGATIVE"),O("C","Droplet precautions with a surgical mask within 6 feet of the patient"),O("D","No isolation is needed since TB is only transmitted through blood contact")],
    ["B"],"Active pulmonary TB is transmitted via AIRBORNE route (tiny droplet nuclei <5 micrometers that remain suspended in air for extended periods and travel on air currents). Required precautions: AIRBORNE ISOLATION: private room with NEGATIVE PRESSURE ventilation (air flows IN to the room and is exhausted directly outside or through HEPA filtration; minimum 6-12 air changes per hour); door must remain CLOSED. N95 RESPIRATOR: required for ALL personnel entering the room; must be PROPERLY FIT-TESTED (not a surgical mask, which only protects against droplets). PATIENT TRANSPORT: place a SURGICAL MASK on the patient when leaving the room (patient does NOT wear an N95). TB TREATMENT: multi-drug therapy (RIPE: Rifampin, Isoniazid, Pyrazinamide, Ethambutol) for minimum 6-9 months; directly observed therapy (DOT) to ensure compliance. DISCONTINUATION of airborne precautions: requires 3 consecutive negative sputum AFB smears collected 8-24 hours apart (usually at least one early morning specimen). Other airborne diseases: measles (rubeola), varicella (chickenpox), disseminated herpes zoster.",
    "TB: AIRBORNE precautions (negative pressure room, N95 for staff, surgical mask on patient during transport); 3 negative AFB smears to discontinue; RIPE therapy", ["tuberculosis","airborne-precautions","N95","negative-pressure","infection-control"]);

  pn("Physiological Integrity","TPN Administration","Physiological Integrity",3,
    "An LPN is monitoring a patient receiving total parenteral nutrition (TPN). Which monitoring parameter is MOST important?",
    [O("A","Monitor the patient's appetite and oral intake"),O("B","Monitor blood glucose levels every 4-6 hours (TPN contains high dextrose concentration causing hyperglycemia risk), check electrolytes daily, monitor I&O, check daily weight, assess the central line insertion site for signs of infection, and use an infusion pump for accurate delivery rate"),O("C","TPN requires no monitoring once the infusion rate is set"),O("D","Monitor the patient's ability to swallow")],
    ["B"],"TPN provides complete nutrition intravenously for patients who cannot use their GI tract. Critical monitoring: BLOOD GLUCOSE every 4-6 hours (TPN solutions contain 15-25% dextrose causing significant hyperglycemia risk; may require insulin supplementation or sliding scale coverage). ELECTROLYTES daily (Na, K, Mg, Ca, PO4 - all included in TPN and require careful balancing). DAILY WEIGHT (assessing fluid status and nutritional response). I&O (monitor fluid balance). CENTRAL LINE SITE (TPN's high osmolality requires central venous access - peripheral TPN/PPN is possible with lower dextrose concentrations; assess for infection signs: redness, swelling, drainage, fever). INFUSION PUMP mandatory (TPN must be infused at a constant rate; never speed up or slow down to catch up or compensate). LIVER FUNCTION TESTS weekly (long-term TPN can cause hepatic steatosis). NEVER abruptly STOP TPN (risk of rebound hypoglycemia from elevated endogenous insulin levels; taper the rate). TPN hangs for no longer than 24 hours. Lipid emulsions: use a filter, infuse over 8-12 hours, discard after 12 hours.",
    "TPN: check blood glucose q4-6h (hyperglycemia risk), electrolytes daily, central line site, infusion pump required, NEVER abruptly stop (rebound hypoglycemia)", ["TPN","parenteral-nutrition","blood-glucose","central-line","nutrition"]);

  pn("Physiological Integrity","Pacemaker Education","Physiological Integrity",2,
    "An LPN is providing discharge education to a patient with a newly implanted permanent pacemaker. Which instruction is MOST important?",
    [O("A","The patient can resume contact sports immediately after discharge"),O("B","Avoid lifting the arm on the pacemaker side above the shoulder for 4-6 weeks (to prevent lead displacement), carry a pacemaker identification card, avoid strong electromagnetic fields (MRI unless MRI-conditional, large magnets), report signs of infection at the incision site, learn to take and record pulse daily, and report dizziness, fainting, or return of pre-pacemaker symptoms"),O("C","Microwave ovens are dangerous and must be permanently avoided"),O("D","The pacemaker battery never needs replacement")],
    ["B"],"Pacemaker patient education: ARM RESTRICTION: avoid lifting the arm on the pacemaker side above shoulder height for 4-6 WEEKS (prevents displacement of newly placed leads before they become fibrosed into position). ELECTROMAGNETIC INTERFERENCE (EMI): avoid strong electromagnetic fields that can interfere with pacemaker function - MRI (unless device is MRI-CONDITIONAL and the scan is done at an approved facility), industrial generators, arc welding, high-voltage power lines (standing directly under them). Household appliances (microwaves, cell phones, computers) are generally SAFE at normal distance; hold cell phone to the OPPOSITE ear. IDENTIFICATION: carry a pacemaker ID card at ALL times; inform all healthcare providers; medical alert bracelet. MONITORING: check pulse DAILY (report rate below the set rate, as this may indicate malfunction); report dizziness, syncope, dyspnea, prolonged hiccups (may indicate lead displacement stimulating the diaphragm), chest pain, or return of pre-pacemaker symptoms. INCISION CARE: keep site clean and dry, report redness/swelling/drainage/fever. BATTERY LIFE: typically 5-15 years; regular follow-up (every 3-12 months, may include remote monitoring via telephone/wireless).",
    "Pacemaker: no arm elevation above shoulder × 4-6 weeks, carry ID card, avoid strong EMI, daily pulse check, report dizziness/syncope, regular follow-up", ["pacemaker","patient-education","lead-displacement","EMI","cardiac"]);

  // ===== NCLEX-RN Batch 4 =====
  rn("Critical Care","Sepsis Bundle","Physiological Integrity",4,
    "An RN identifies that a patient in the emergency department meets criteria for sepsis (suspected infection with qSOFA ≥2). What components of the Surviving Sepsis Campaign 1-hour bundle should be initiated?",
    [O("A","Administer acetaminophen and encourage oral fluids"),O("B","Within 1 HOUR: (1) measure serum lactate (if elevated >2 mmol/L, remeasure within 2-4 hours), (2) obtain blood cultures BEFORE starting antibiotics (at least 2 sets from different sites), (3) administer broad-spectrum IV antibiotics, (4) begin rapid IV crystalloid bolus of 30 mL/kg for hypotension or lactate ≥4 mmol/L, (5) apply vasopressors (norepinephrine first-line) if hypotension persists after fluid resuscitation to maintain MAP ≥65 mmHg"),O("C","Observe the patient for 6 hours before initiating treatment to confirm the diagnosis"),O("D","Administer oral antibiotics and discharge the patient home with follow-up instructions")],
    ["B"],"The Surviving Sepsis Campaign (SSC) 1-hour bundle reflects the urgency of sepsis management (sepsis kills approximately 11 million people worldwide annually). SEPSIS identification: qSOFA (quick Sequential Organ Failure Assessment): ≥2 of: altered mental status (GCS <15), systolic BP ≤100 mmHg, respiratory rate ≥22/min. The 1-HOUR BUNDLE components: (1) MEASURE LACTATE: lactate >2 mmol/L indicates tissue hypoperfusion; if initial lactate elevated, remeasure in 2-4 hours to guide resuscitation (lactate clearance). (2) BLOOD CULTURES: obtain at least 2 sets (aerobic and anaerobic) from different sites BEFORE starting antibiotics (but do NOT delay antibiotics if cultures cannot be obtained quickly). (3) BROAD-SPECTRUM IV ANTIBIOTICS: administer within 1 hour of sepsis recognition; each hour of delay increases mortality by 7.6%. (4) IV CRYSTALLOID 30 mL/kg for sepsis-induced hypotension (MAP <65 mmHg) or lactate ≥4 mmol/L. (5) VASOPRESSORS: norepinephrine is first-line if MAP remains <65 mmHg despite adequate fluid resuscitation.",
    "Sepsis 1-hour bundle: lactate, blood cultures, broad-spectrum antibiotics, 30 mL/kg crystalloid if hypotensive, vasopressors if MAP<65 after fluids; each hour delay = 7.6% increased mortality", ["sepsis","sepsis-bundle","lactate","vasopressors","critical-care"]);

  rn("Pharmacology","Warfarin Drug Interactions","Physiological Integrity",3,
    "An RN is reviewing a patient's medication list and identifies that the patient taking warfarin has also been prescribed ciprofloxacin for a urinary tract infection. What is the RN's concern?",
    [O("A","There is no interaction between warfarin and ciprofloxacin"),O("B","Ciprofloxacin (fluoroquinolone antibiotic) INHIBITS CYP1A2 and CYP3A4 enzymes that metabolize warfarin, causing INCREASED warfarin levels and INCREASED bleeding risk; the RN should notify the physician, anticipate more frequent INR monitoring, possible warfarin dose reduction, and educate the patient to report any signs of bleeding"),O("C","Ciprofloxacin decreases warfarin's effect, requiring a higher warfarin dose"),O("D","The interaction only occurs with IV ciprofloxacin, not oral")],
    ["B"],"Warfarin has EXTENSIVE drug and food interactions that make it one of the most commonly involved medications in adverse drug events. DRUGS THAT INCREASE WARFARIN EFFECT (increase bleeding risk): fluoroquinolones (ciprofloxacin, levofloxacin), azole antifungals (fluconazole), metronidazole, macrolide antibiotics (erythromycin), amiodarone, SSRIs, NSAIDs (also impair platelet function independently), acetaminophen (high doses >2g/day), sulfamethoxazole/TMP. These drugs inhibit cytochrome P450 enzymes (primarily CYP2C9) that metabolize warfarin, leading to elevated warfarin levels and supratherapeutic INR. DRUGS THAT DECREASE WARFARIN EFFECT: rifampin (most potent inducer), carbamazepine, phenytoin, barbiturates, St. John's Wort. FOOD INTERACTIONS: vitamin K-rich foods (dark green leafy vegetables: kale, spinach, broccoli) - maintain CONSISTENT dietary vitamin K intake rather than avoiding entirely. Nursing actions: monitor INR closely (target usually 2-3), educate about interactions, report signs of bleeding (unusual bruising, blood in urine/stool, bleeding gums, prolonged cuts, black tarry stools).",
    "Warfarin + ciprofloxacin: increased bleeding risk (enzyme inhibition); monitor INR closely; consistent vitamin K intake; INR target 2-3", ["warfarin","drug-interaction","ciprofloxacin","INR","anticoagulant"]);

  rn("Respiratory","Pneumothorax Assessment","Physiological Integrity",3,
    "An RN is assessing a patient who was involved in a motor vehicle accident. The patient has absent breath sounds on the left side, tracheal deviation to the RIGHT, hypotension, jugular vein distension, and severe dyspnea. What does the RN suspect?",
    [O("A","Left lower lobe pneumonia"),O("B","LEFT TENSION PNEUMOTHORAX: air entering the pleural space through a one-way valve mechanism with each breath cannot escape, causing progressive pressure buildup that collapses the affected lung, shifts the mediastinum (including the trachea) AWAY from the affected side (tracheal deviation to the RIGHT indicates LEFT-sided tension), compresses the contralateral lung and great vessels (causing hypotension from decreased venous return), and causes JVD from impaired venous return to the heart"),O("C","Right-sided pleural effusion"),O("D","Asthma exacerbation with bilateral wheezing")],
    ["B"],"TENSION PNEUMOTHORAX is a life-threatening emergency requiring IMMEDIATE intervention (needle decompression). Pathophysiology: a one-way valve mechanism allows air to enter the pleural space during inspiration but prevents escape during expiration → progressive air accumulation → complete lung collapse on the affected side → MEDIASTINAL SHIFT (mediastinum pushes AWAY from the affected side, compressing the contralateral lung and great vessels). Clinical findings: ABSENT BREATH SOUNDS on the affected side, TRACHEAL DEVIATION toward the OPPOSITE side (trachea shifts away from the tension), HYPOTENSION (compression of the vena cava and heart reduces venous return and cardiac output), JUGULAR VEIN DISTENSION (JVD from impaired venous return), severe DYSPNEA, cyanosis, tachycardia, subcutaneous emphysema (crepitus on palpation). TREATMENT: IMMEDIATE needle decompression (large-bore needle inserted at the 2nd intercostal space, midclavicular line on the affected side) followed by chest tube insertion. Do NOT delay treatment for X-ray confirmation - this is a clinical diagnosis treated emergently.",
    "Tension pneumothorax: absent breath sounds + tracheal deviation AWAY from affected side + hypotension + JVD = EMERGENCY; needle decompression at 2nd ICS midclavicular", ["tension-pneumothorax","tracheal-deviation","needle-decompression","emergency","trauma"]);

  rn("Renal","Acute Kidney Injury Phases","Physiological Integrity",3,
    "An RN is caring for a patient in the oliguric phase of acute kidney injury (AKI). Which lab abnormality is the MOST dangerous and requires immediate attention?",
    [O("A","Mildly elevated BUN"),O("B","HYPERKALEMIA: during the oliguric phase, the kidneys cannot excrete potassium adequately, leading to dangerous accumulation (K+ >5.5 mEq/L); hyperkalemia can cause fatal cardiac dysrhythmias (peaked T waves → widened QRS → sine wave → cardiac arrest); treatment includes IV calcium gluconate (cardiac membrane stabilization), insulin + dextrose and sodium bicarbonate (shift K+ intracellularly), and kayexalate or dialysis (remove K+)"),O("C","Slightly decreased calcium"),O("D","Increased urine output")],
    ["B"],"Acute kidney injury (AKI) progresses through phases: INITIATION: initial insult occurs (ischemia, nephrotoxins, obstruction). OLIGURIC PHASE (1-3 weeks): urine output <400 mL/day; the MOST DANGEROUS phase. Lab changes: HYPERKALEMIA (most immediately life-threatening - monitor ECG continuously), hyperphosphatemia, hypocalcemia (phosphorus and calcium have an inverse relationship), metabolic ACIDOSIS (kidneys can't excrete hydrogen ions), elevated BUN and creatinine (waste product accumulation), fluid OVERLOAD (decreased urine output with continued fluid intake → edema, hypertension, heart failure, pulmonary edema). DIURETIC PHASE (1-3 weeks): urine output increases dramatically (up to 3-5 L/day); risk of dehydration and electrolyte depletion (hypokalemia, hyponatremia). RECOVERY PHASE (up to 12 months): gradual return of renal function; some patients may have permanent residual impairment. Nursing priorities in oliguric phase: strict I&O, daily weights, cardiac monitoring for hyperkalemia, fluid restriction, dietary potassium restriction, phosphorus binders, possible emergent dialysis.",
    "AKI oliguric phase: hyperkalemia is most dangerous (cardiac arrest risk); monitor ECG, fluid restriction, anticipate dialysis; diuretic phase = dehydration risk", ["AKI","hyperkalemia","oliguric-phase","renal-failure","electrolyte"]);

  rn("Pharmacology","Beta-Blocker Overdose","Physiological Integrity",4,
    "An RN is caring for a patient who accidentally took an overdose of metoprolol. The patient presents with severe bradycardia (HR 34), hypotension (BP 70/40), and altered consciousness. What is the PRIORITY treatment?",
    [O("A","Administer more metoprolol to stabilize the heart rhythm"),O("B","Administer IV GLUCAGON (first-line antidote for beta-blocker overdose: works through a non-beta-receptor pathway to increase heart rate and cardiac contractility), atropine for symptomatic bradycardia, IV fluids for hypotension, and prepare for transcutaneous pacing if pharmacological measures fail; consider high-dose insulin euglycemic therapy for refractory cases"),O("C","Administer a calcium channel blocker to increase heart rate"),O("D","Apply external warming blankets as the primary intervention")],
    ["B"],"Beta-blocker overdose is a potentially fatal toxicological emergency. Toxicity presents with: BRADYCARDIA (beta-1 blockade reduces heart rate and AV conduction), HYPOTENSION (reduced cardiac output and contractility), altered mental status, hypoglycemia (from impaired glycogenolysis, especially in propranolol overdose), bronchospasm, and seizures (propranolol crosses the BBB). Treatment hierarchy: (1) IV GLUCAGON: the FIRST-LINE specific antidote for beta-blocker toxicity. Mechanism: activates adenylyl cyclase via a glucagon receptor (bypasses the blocked beta receptor) → increases cAMP → increases heart rate and contractility. Dose: 3-10 mg IV bolus, then infusion 3-5 mg/hr. (2) IV ATROPINE: for symptomatic bradycardia (blocks vagal tone; may be insufficient in severe overdose). (3) IV FLUIDS: for hypotension support. (4) VASOPRESSORS: norepinephrine or epinephrine if hypotension refractory. (5) TRANSCUTANEOUS PACING: if bradycardia refractory to pharmacological therapy. (6) HIGH-DOSE INSULIN EUGLYCEMIC THERAPY (HIET): regular insulin 1 unit/kg bolus then 0.5-1 unit/kg/hr with dextrose to maintain euglycemia; improves cardiac contractility through enhanced myocardial glucose utilization.",
    "Beta-blocker overdose: IV glucagon first-line (bypasses blocked beta receptor); atropine, IV fluids, vasopressors, pacing; consider high-dose insulin for refractory cases", ["beta-blocker","overdose","glucagon","antidote","toxicology"]);

  rn("Neurology","Meningitis Assessment","Physiological Integrity",3,
    "An RN is assessing a patient suspected of having bacterial meningitis. Which triad of classic findings supports the diagnosis?",
    [O("A","Bradycardia, hypertension, and irregular respirations"),O("B","The classic meningitis triad: FEVER, severe HEADACHE, and NUCHAL RIGIDITY (stiff neck/inability to flex the neck); additional signs include positive KERNIG sign (resistance/pain with knee extension when hip is flexed to 90°), positive BRUDZINSKI sign (involuntary flexion of hips and knees when the neck is passively flexed), photophobia, altered mental status, and petechial rash (especially with Neisseria meningitidis)"),O("C","Chest pain, dyspnea, and cough"),O("D","Polyuria, polydipsia, and polyphagia")],
    ["B"],"Bacterial meningitis is a medical emergency with mortality of 5-30% even with treatment. Classic triad: FEVER (usually high, >38.5°C), HEADACHE (severe, often described as 'the worst headache of my life'), NUCHAL RIGIDITY (stiffness of the neck from meningeal inflammation; the patient resists or is unable to flex the chin to the chest). MENINGEAL SIGNS: KERNIG SIGN (with the patient supine, flex the hip to 90°, then attempt to extend the knee; POSITIVE if there is resistance or pain with knee extension - stretching the inflamed meninges causes pain). BRUDZINSKI SIGN (with the patient supine, passively flex the neck; POSITIVE if there is involuntary flexion of the hips and knees - indicates meningeal irritation). Additional findings: photophobia, altered LOC, seizures, petechial/purpuric rash (classic for Neisseria meningitidis/meningococcal meningitis - indicates DIC). PRECAUTIONS: DROPLET precautions for meningococcal meningitis (N. meningitidis) until 24 hours of effective antibiotic therapy. Treatment: empiric IV antibiotics immediately (ceftriaxone + vancomycin); dexamethasone before or with first antibiotic dose; lumbar puncture for CSF analysis (elevated WBC, elevated protein, decreased glucose, positive Gram stain/culture).",
    "Meningitis triad: fever + headache + nuchal rigidity; Kernig/Brudzinski signs; petechial rash = meningococcal; DROPLET precautions; antibiotics STAT", ["meningitis","nuchal-rigidity","Kernig","Brudzinski","infection"]);

  rn("Psychiatric","Suicide Risk Assessment","Psychosocial Integrity",3,
    "An RN is assessing a patient who states, 'I've decided to end it all tonight. I have a loaded gun at home and I've written letters to my family.' What level of suicide risk does this represent?",
    [O("A","Low risk: vague thoughts without a plan"),O("B","HIGH/IMMINENT risk: the patient has a specific PLAN (tonight), access to LETHAL MEANS (loaded gun at home), and has engaged in PREPARATORY BEHAVIORS (written farewell letters); this requires immediate 1:1 continuous observation, removal of all potentially harmful objects from the environment, psychiatric evaluation, possible involuntary hospitalization if the patient refuses voluntary admission, and means restriction counseling"),O("C","Moderate risk: the patient is expressing frustration but has no real intent"),O("D","No risk: the patient is simply seeking attention and will not follow through")],
    ["B"],"Suicide risk assessment uses a structured approach to identify the level of risk and guide appropriate intervention. HIGH/IMMINENT RISK indicators (this patient has ALL THREE): (1) SPECIFIC PLAN: the patient states a clear method (gun), time (tonight), and location (home) - the more specific and lethal the plan, the higher the risk. (2) ACCESS TO MEANS: a loaded firearm is the most lethal method available; firearms account for over 50% of suicide deaths. (3) PREPARATORY BEHAVIORS: writing farewell letters, giving away possessions, making funeral arrangements, putting affairs in order, and saying goodbye indicate the patient has moved from ideation to planning to preparation. IMMEDIATE NURSING ACTIONS: (1) DO NOT leave the patient alone (continuous 1:1 observation), (2) maintain a CALM, THERAPEUTIC, NON-JUDGMENTAL approach, (3) directly ask about suicidal intent ('Are you thinking about killing yourself?') - asking does NOT increase risk, (4) remove all potentially harmful objects (sharps, cords, belts, medications), (5) ensure IMMEDIATE psychiatric evaluation, (6) if the patient refuses voluntary admission, initiate involuntary commitment procedures per state/provincial law. MEANS RESTRICTION (removing/securing access to firearms and other lethal means) is one of the most effective suicide prevention strategies.",
    "High suicide risk: specific plan + access to lethal means + preparatory behaviors; 1:1 observation, never leave alone, psychiatric eval, means restriction", ["suicide-assessment","risk-level","means-restriction","safety","psychiatric"]);

  rn("GI","Liver Failure Complications","Physiological Integrity",4,
    "An RN is caring for a patient with hepatic encephalopathy secondary to liver cirrhosis. The patient is confused, has asterixis (liver flap), and ammonia level is 148 mcg/dL (normal <35). Which medication should the RN anticipate?",
    [O("A","Administer protein supplements to improve the patient's nutrition"),O("B","Administer LACTULOSE (an osmotic laxative that reduces serum ammonia by: (1) drawing ammonia from the blood into the colon through osmosis, (2) acidifying the colonic environment which converts ammonia/NH3 to ammonium/NH4+ which cannot be reabsorbed, (3) promoting 2-3 soft stools per day for ammonia elimination); also anticipate rifaximin (non-absorbable antibiotic that reduces ammonia-producing gut bacteria)"),O("C","Administer high-protein diet to support liver regeneration"),O("D","Administer opioid analgesics for the patient's discomfort")],
    ["B"],"Hepatic encephalopathy (HE) results from the liver's inability to convert ammonia (a neurotoxic byproduct of protein metabolism) to urea for renal excretion. Stages: Grade I (mild confusion, irritability, sleep disturbance), Grade II (lethargy, moderate confusion, asterixis), Grade III (somnolence, marked confusion, incoherent speech), Grade IV (coma). ASTERIXIS (liver flap/flapping tremor): involuntary rapid flexion-extension movements of the wrists when arms are extended and wrists dorsiflexed - a hallmark sign of HE. Treatment: LACTULOSE: the first-line treatment. Mechanism: osmotic laxative that promotes ammonia excretion through 2-3 soft stools/day. Goal: 2-3 soft stools daily. Side effects: diarrhea (if excessive, can cause dehydration/hypokalemia). RIFAXIMIN (Xifaxan): non-absorbable antibiotic that reduces ammonia-producing gut flora; used adjunctively with lactulose. DIETARY PROTEIN: moderate restriction during acute episodes (1.0-1.5 g/kg/day, preferring vegetable protein over animal protein); excessive restriction is no longer recommended. AVOID: sedatives, opioids, hepatotoxic medications, and benzodiazepines (poorly metabolized by the failing liver, worsening encephalopathy).",
    "Hepatic encephalopathy: lactulose first-line (2-3 soft stools/day), rifaximin adjunct; asterixis = hallmark sign; moderate protein (not eliminated); avoid sedatives", ["hepatic-encephalopathy","lactulose","ammonia","asterixis","liver-cirrhosis"]);

  // ===== REx-PN Batch 4 =====
  rpn("Leadership","Conflict Resolution","Safe & Effective Care Environment",2,
    "An RPN observes a colleague consistently cutting corners on hand hygiene between patient contacts. What is the MOST appropriate initial action according to CNO professional standards?",
    [O("A","Ignore the behaviour to maintain the collegial relationship"),O("B","Address the behaviour directly with the colleague in a private, respectful manner using 'I' statements (e.g., 'I noticed hand hygiene was missed between those two patients, and I'm concerned about infection transmission'); if the behaviour continues despite direct communication, report to the charge nurse or manager; document the observations; the RPN has a professional obligation to address unsafe practice to protect patients"),O("C","Report the colleague to the College of Nurses immediately without speaking to them first"),O("D","Post about the colleague's behaviour on social media to raise awareness")],
    ["B"],"The CNO's Professional Standards and Code of Conduct requires nurses to address unsafe or incompetent practice to protect the public. The approach follows a graduated response: (1) DIRECT COMMUNICATION first: address the issue privately with the colleague in a non-threatening, respectful manner. Use 'I' statements rather than accusatory language. Focus on the BEHAVIOUR and its IMPACT, not the person. (2) If the behaviour CONTINUES: report to the charge nurse, supervisor, or manager through the chain of command. (3) DOCUMENT: record the specific observations (date, time, what was observed, context) and the actions taken. (4) If UNRESOLVED through internal channels or the behaviour represents an imminent threat to patient safety: report to the CNO as a mandatory report. Key principles: the nurse's PRIMARY obligation is to the PATIENT'S safety; maintaining collegial relationships is important but does NOT supersede the duty to protect patients; social media posting would violate patient privacy (PHIPA) and professional standards.",
    "Unsafe practice: address directly first (private, respectful, 'I' statements), escalate if continues, document; primary obligation = patient safety", ["conflict-resolution","professional-standards","hand-hygiene","CNO","accountability"]);

  rpn("Mental Health","Delirium vs Dementia","Psychosocial Integrity",2,
    "An RPN is assessing an elderly patient admitted to the hospital who has become acutely confused, agitated, and has fluctuating levels of consciousness. The family reports the patient was 'fine yesterday.' How should the RPN differentiate this from dementia?",
    [O("A","Acute confusion in elderly patients is always dementia and requires no further investigation"),O("B","This presentation suggests DELIRIUM (not dementia): delirium has ACUTE onset (hours to days), FLUCTUATING course, is REVERSIBLE when the underlying cause is treated, and has an identifiable TRIGGER (infection, medications, dehydration, pain, surgery, electrolyte imbalance); in contrast, dementia has GRADUAL onset (months to years), PROGRESSIVE irreversible course, and stable day-to-day level of consciousness; delirium is a MEDICAL EMERGENCY requiring immediate cause identification"),O("C","Delirium and dementia are the same condition with identical management"),O("D","Only patients with pre-existing dementia can develop acute confusion")],
    ["B"],"Delirium vs Dementia comparison is critical for appropriate management. DELIRIUM: onset = ACUTE (hours-days), course = FLUCTUATING (waxes and wanes throughout the day, often worse at night/'sundowning'), duration = TEMPORARY/REVERSIBLE (resolves when cause is treated), attention = IMPAIRED (key distinguishing feature - patient cannot focus or sustain attention), consciousness = ALTERED (ranges from hyperalert/agitated to lethargic/obtunded), perception = HALLUCINATIONS common (especially visual), cause = IDENTIFIABLE medical trigger. Common causes (mnemonic DELIRIUM): Drugs, Electrolyte imbalances, Lack of drugs (withdrawal), Infection (UTI #1 in elderly), Reduced sensory input, Intracranial pathology, Urinary retention/fecal impaction, Myocardial/pulmonary causes. DEMENTIA: onset = GRADUAL (months-years), course = PROGRESSIVE and IRREVERSIBLE, attention = RELATIVELY preserved until late stages, consciousness = CLEAR until late stages, hallucinations = LESS common until advanced stages. IMPORTANT: delirium can be SUPERIMPOSED on dementia (delirium-dementia overlap), and patients with dementia are at HIGHER risk of developing delirium. Delirium requires URGENT medical evaluation to identify and treat the underlying cause.",
    "Delirium: acute, fluctuating, reversible, has a treatable cause; Dementia: gradual, progressive, irreversible; delirium is a MEDICAL EMERGENCY", ["delirium","dementia","acute-confusion","elderly","differential-diagnosis"]);

  rpn("Pharmacology","Drug Calculation Canada","Physiological Integrity",2,
    "An RPN receives an order to administer heparin 800 units/hour IV. The pharmacy sends a bag labelled heparin 25,000 units in 250 mL D5W. At what rate in mL/hour should the RPN set the infusion pump?",
    [O("A","25 mL/hour"),O("B","8 mL/hour: calculation: concentration = 25,000 units ÷ 250 mL = 100 units/mL; desired rate = 800 units/hour ÷ 100 units/mL = 8 mL/hour; always use an infusion pump for heparin administration and verify the calculation with a second nurse (independent double check)"),O("C","80 mL/hour"),O("D","800 mL/hour")],
    ["B"],"Drug calculation for IV medications using the formula: desired dose ÷ concentration = volume per hour. Step 1: Calculate the CONCENTRATION: 25,000 units ÷ 250 mL = 100 units/mL. Step 2: Calculate the RATE: 800 units/hour ÷ 100 units/mL = 8 mL/hour. SAFETY MEASURES for heparin administration: (1) INFUSION PUMP mandatory (heparin is a HIGH-ALERT medication), (2) INDEPENDENT DOUBLE CHECK by a second nurse before starting and with any rate change (verify: right patient, right drug, right dose, right concentration, right rate), (3) monitor aPTT per protocol (typically every 6 hours until therapeutic, then every 24 hours; therapeutic range 1.5-2.5× control), (4) assess for signs of bleeding (bruising, hematuria, blood in stool, bleeding gums, petechiae), (5) have PROTAMINE SULFATE available (antidote), (6) monitor platelet count (HIT risk). In Canada, this calculation is tested on the REx-PN exam and RPNs must demonstrate competency in drug calculations as part of entry-to-practice requirements.",
    "Heparin calculation: dose ordered ÷ concentration = mL/hr; 800 units/hr ÷ 100 units/mL = 8 mL/hr; always double-check, use infusion pump", ["drug-calculation","heparin","IV-rate","infusion-pump","medication-safety"]);

  rpn("Maternity","Newborn Assessment","Physiological Integrity",2,
    "An RPN in a Canadian hospital is performing an initial assessment on a newborn using the Apgar scoring system at 1 and 5 minutes after birth. Which parameters does the Apgar score assess?",
    [O("A","Weight, length, head circumference, chest circumference, and temperature"),O("B","The Apgar score assesses five parameters each scored 0-2 (total 0-10): Appearance (skin color: blue/pale=0, acrocyanosis=1, completely pink=2), Pulse (heart rate: absent=0, <100=1, >100=2), Grimace (reflex irritability: no response=0, grimace=1, vigorous cry=2), Activity (muscle tone: limp=0, some flexion=1, active motion=2), and Respiration (respiratory effort: absent=0, weak cry=1, strong cry=2); a normal score is 7-10"),O("C","Only heart rate and respiratory rate are assessed"),O("D","Blood glucose, bilirubin, hemoglobin, hematocrit, and blood type")],
    ["B"],"The APGAR score is a standardized assessment tool used worldwide to evaluate the newborn's transition to extrauterine life at 1 minute (reflects need for immediate resuscitation) and 5 minutes (reflects effectiveness of resuscitation and overall adaptation). The mnemonic APGAR: A = APPEARANCE (skin color): 0 = blue/pale all over, 1 = acrocyanosis (body pink, extremities blue - NORMAL in first 24 hours due to peripheral circulation immaturity), 2 = completely pink. P = PULSE (heart rate): 0 = absent, 1 = <100 bpm (concerning), 2 = >100 bpm (normal). G = GRIMACE (reflex irritability/response to stimulation): 0 = no response, 1 = grimace/weak cry, 2 = vigorous cry/cough/sneeze. A = ACTIVITY (muscle tone): 0 = flaccid/limp, 1 = some flexion of extremities, 2 = active spontaneous movement/flexion. R = RESPIRATION (respiratory effort): 0 = absent, 1 = slow/irregular/weak cry, 2 = strong cry/regular respirations. Interpretation: 7-10 = NORMAL (vigorous newborn); 4-6 = MODERATE difficulty (may need stimulation and oxygen); 0-3 = SEVERE distress (requires immediate resuscitation). If 5-minute score <7, continue scoring every 5 minutes until 20 minutes.",
    "APGAR: Appearance, Pulse, Grimace, Activity, Respiration; scored 0-2 each at 1 and 5 minutes; 7-10 normal; <4 = immediate resuscitation", ["APGAR","newborn-assessment","neonatal","scoring","maternity"]);

  return qs;
}

async function main(){
  console.log("=== Massive Batch 4 ===\n");
  const before=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("BEFORE:");for(const r of before.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs=build();
  const bk:Record<string,number>={};
  for(const q of allQs)bk[q.exam]=(bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`,bk);
  let ins=0,dup=0,err=0;
  for(const q of allQs){
    const h=sh(q.stem);
    try{
      const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`,[h,q.tier,q.exam]);
      if(ex.rows.length>0){dup++;continue;}
      await pool.query(
        `INSERT INTO exam_questions(id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at)
         VALUES(gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,
        [q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,
         "Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);
      ins++;
    }catch(e:any){err++;console.error(`ERR: ${e.message.substring(0,100)}`);}
  }
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("\nAFTER:");for(const r of after.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session=await pool.query(`SELECT exam,COUNT(*)::int as cnt FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at>NOW()-INTERVAL '14 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:");for(const r of session.rows)console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}
main().catch(e=>{console.error("Fatal:",e);process.exit(1);});
