import crypto from "crypto";
import pg from "pg";

const pool = new pg.Pool({ host: process.env.PGHOST || "helium", user: process.env.PGUSER || "postgres", password: process.env.PGPASSWORD || "password", database: process.env.PGDATABASE || "heliumdb", ssl: false });

function sh(text: string): string { return crypto.createHash("sha256").update(text.trim().toLowerCase().replace(/[^a-z0-9\s]/g, "").replace(/\s+/g, " ")).digest("hex").substring(0, 16); }

const O = (l: string, t: string) => ({ label: l, text: t });

interface Q { tier: string; exam: string; qt: string; stem: string; options: {label:string;text:string}[]; ca: string[]; rat: string; diff: number; tags: string[]; topic: string; sub: string; rs: string; cp: string; es: string; ct: string; dr: Record<string,string>; bs: string; }

function buildAll(): Q[] {
  const qs: Q[] = [];

  const mk = (tier: string, exam: string, rs: string, topic: string, sub: string, bs: string, qt: string, diff: number, stem: string, opts: any[], ca: string[], rat: string, cp: string, tags: string[]): Q => ({
    tier, exam, qt, stem, options: opts, ca, rat, diff, tags, topic, sub, rs, cp,
    es: "Select the evidence-based, patient-safety-focused answer", ct: "Avoid answers using outdated practices or that could harm the patient",
    dr: { A: "Incorrect approach for this clinical scenario", C: "Does not align with evidence-based practice", D: "Inappropriate or potentially harmful" }, bs
  });

  const rpn = (t: string, s: string, bs: string, d: number, stem: string, opts: any[], ca: string[], rat: string, cp: string, tags: string[]) => mk("rpn","REx-PN","CA",t,s,bs,"MCQ",d,stem,opts,ca,rat,cp,tags);
  const pn = (t: string, s: string, bs: string, d: number, stem: string, opts: any[], ca: string[], rat: string, cp: string, tags: string[]) => mk("rpn","NCLEX-PN","US",t,s,bs,"MCQ",d,stem,opts,ca,rat,cp,tags);
  const rn = (t: string, s: string, bs: string, d: number, stem: string, opts: any[], ca: string[], rat: string, cp: string, tags: string[]) => mk("rn","NCLEX-RN","BOTH",t,s,bs,"MCQ",d,stem,opts,ca,rat,cp,tags);

  // ============= REx-PN Canadian Questions =============

  // Cardiac Care
  qs.push(rpn("Cardiac Care","Angina Assessment","Physiological Integrity",3,
    "An RPN is caring for a patient who reports substernal chest pain that occurs with exertion and is relieved by rest or nitroglycerin. This pattern is MOST consistent with which type of angina?",
    [O("A","Unstable angina requiring immediate cardiac catheterization"), O("B","Stable angina pectoris with a predictable pattern of onset and relief"), O("C","Prinzmetal (variant) angina caused by coronary artery spasm at rest"), O("D","Microvascular angina from small vessel disease")],
    ["B"],
    "Stable angina pectoris has a PREDICTABLE pattern: it occurs with consistent levels of exertion (physical activity, emotional stress, cold exposure) and is reliably relieved by rest and/or nitroglycerin within 3-5 minutes. The underlying cause is fixed atherosclerotic narrowing of a coronary artery that limits blood flow during increased myocardial oxygen demand. Unstable angina is NEW or CHANGING in pattern (occurring at rest, increasing frequency/severity, or occurring with less exertion than previously), indicating plaque instability and imminent MI risk. Prinzmetal angina occurs at REST, often at the same time of day (typically early morning), from coronary artery vasospasm rather than fixed atherosclerosis.",
    "Stable angina: predictable pattern, exertion-related, relieved by rest/NTG; Unstable: NEW or CHANGING pattern = emergency", ["cardiac","angina","stable-angina","chest-pain","assessment"]));

  qs.push(rpn("Cardiac Care","Heart Sound Assessment","Physiological Integrity",3,
    "An RPN auscultates a patient's heart sounds and hears an extra heart sound (S3 gallop) in a 68-year-old patient with a history of heart failure. What does an S3 heart sound indicate in this patient?",
    [O("A","Normal heart sound in all adult patients"), O("B","Volume overload and ventricular dysfunction; the S3 occurs during rapid ventricular filling and indicates decompensated heart failure"), O("C","Aortic valve stenosis requiring immediate valve replacement"), O("D","Pericardial friction rub from pericarditis")],
    ["B"],
    "S3 (ventricular gallop) is an extra heart sound heard early in diastole during the rapid ventricular filling phase. In adults over 30, an S3 is pathological and indicates increased ventricular volume or decreased ventricular compliance - hallmarks of congestive heart failure. The S3 is best heard at the apex (mitral area) with the bell of the stethoscope, with the patient in the left lateral decubitus position. The 'Ken-TUC-ky' mnemonic mimics the rhythm of S1-S2-S3. Note: S3 can be a normal finding in children, young adults, and during the third trimester of pregnancy. S4 (atrial gallop) = 'TEN-nes-see' = heard before S1, indicates stiff ventricle (ventricular hypertrophy, cardiomyopathy). A pericardial friction rub has a scratching/rubbing quality, not a gallop.",
    "S3 in adults = heart failure (volume overload); S4 = stiff ventricle (hypertrophy); both are pathological in older adults", ["cardiac","S3-gallop","heart-sounds","heart-failure","auscultation"]));

  // Respiratory scenarios
  qs.push(rpn("Respiratory","Asthma Action Plan","Physiological Integrity",2,
    "An RPN is teaching a patient with asthma about their asthma action plan. The patient's peak expiratory flow (PEF) reading is 55% of their personal best. According to the traffic light system, which zone does this indicate?",
    [O("A","Green zone (80-100% of personal best) - all clear, continue current medications"), O("B","Yellow zone (50-79% of personal best) - caution, use quick-relief medication and follow the action plan for adjusting controller medications"), O("C","Red zone (below 50% of personal best) - medical emergency, seek immediate help"), O("D","There is no standardized zone system for asthma management")],
    ["B"],
    "The Asthma Action Plan uses a traffic light system based on peak expiratory flow (PEF) readings as a percentage of personal best: GREEN ZONE (80-100%): asthma is well-controlled, continue regular medications, no symptoms. YELLOW ZONE (50-79%): asthma is getting worse, take quick-relief medication (salbutamol/ventolin), may need to increase controller medications (inhaled corticosteroids), contact healthcare provider if no improvement. RED ZONE (below 50%): medical emergency, take quick-relief medication immediately, seek emergency care. At 55%, this patient is in the yellow zone and should follow their action plan for medication adjustment.",
    "Asthma traffic light: Green (80-100%)=well controlled; Yellow (50-79%)=getting worse, adjust meds; Red (<50%)=emergency", ["respiratory","asthma","peak-flow","action-plan","self-management"]));

  qs.push(rpn("Respiratory","Pneumonia Assessment","Physiological Integrity",3,
    "An RPN is assessing a patient admitted with community-acquired pneumonia. Which cluster of assessment findings is MOST consistent with pneumonia?",
    [O("A","Bilateral wheezing with prolonged expiration and barrel chest"), O("B","Fever, productive cough with purulent sputum, crackles on auscultation over the affected lobe, and increased tactile fremitus"), O("C","Stridor, drooling, and tripod positioning"), O("D","Absent breath sounds bilaterally with hyperresonance to percussion")],
    ["B"],
    "Pneumonia assessment findings form a recognizable cluster: FEVER (from infectious/inflammatory response), PRODUCTIVE COUGH with PURULENT SPUTUM (green/yellow/rust-colored from WBC-laden secretions), CRACKLES (heard on auscultation over the consolidated area, caused by air passing through fluid-filled alveoli), and INCREASED TACTILE FREMITUS (vibrations are transmitted more effectively through consolidated/fluid-filled lung tissue than air-filled tissue). Additional findings include bronchial breath sounds over affected area, dullness to percussion, pleuritic chest pain (sharp, worsens with inspiration), tachypnea, and dyspnea. Bilateral wheezing with barrel chest (A) suggests COPD. Stridor with drooling (C) suggests upper airway obstruction. Absent breath sounds with hyperresonance (D) suggests pneumothorax.",
    "Pneumonia cluster: fever + productive cough + crackles + increased fremitus + dullness to percussion over affected area", ["respiratory","pneumonia","assessment","crackles","fremitus"]));

  // GI scenarios
  qs.push(rpn("Gastrointestinal","Peptic Ulcer Disease","Physiological Integrity",3,
    "An RPN is educating a patient newly diagnosed with a duodenal ulcer. Which statement by the patient indicates understanding of the condition?",
    [O("A","'My pain typically occurs immediately after eating and is relieved by antacids.'"), O("B","'My pain usually occurs 2-3 hours after eating when my stomach is empty, and eating food temporarily relieves it.'"), O("C","'I should avoid all food because eating makes the pain worse.'"), O("D","'This ulcer was caused by eating too much spicy food.'")],
    ["B"],
    "Duodenal ulcers characteristically cause pain that occurs 2-3 hours AFTER meals (when gastric acid is produced but the buffering effect of food has passed) or at night. Eating food temporarily RELIEVES the pain by buffering the acid. This is opposite to gastric ulcers, where pain occurs DURING or shortly AFTER eating (food stimulates acid production in an already-damaged stomach). Key differentiators: DUODENAL = pain 2-3 hrs after eating, relieved by food, nighttime pain, weight GAIN (eating relieves pain, so patient eats more). GASTRIC = pain during/after eating, worsened by food, weight LOSS (eating causes pain, so patient eats less). Most duodenal ulcers are caused by H. pylori infection (not spicy food, which can aggravate but not cause ulcers). Treatment includes PPI therapy, H. pylori triple therapy (PPI + clarithromycin + amoxicillin), and lifestyle modifications.",
    "Duodenal ulcer: pain 2-3hrs after eating, relieved by food, nighttime; Gastric ulcer: pain with eating, worsened by food", ["GI","peptic-ulcer","duodenal","H-pylori","pain-pattern"]));

  qs.push(rpn("Gastrointestinal","Liver Disease","Physiological Integrity",3,
    "An RPN is caring for a patient with liver cirrhosis who develops asterixis (liver flap), confusion, and fetor hepaticus. These findings indicate which complication?",
    [O("A","Portal hypertension with esophageal varices"), O("B","Hepatic encephalopathy from the liver's inability to metabolize ammonia to urea"), O("C","Hepatorenal syndrome affecting kidney function"), O("D","Spontaneous bacterial peritonitis")],
    ["B"],
    "Hepatic encephalopathy (HE) results from the liver's inability to convert ammonia (a toxic byproduct of protein metabolism) to urea for renal excretion. Elevated ammonia crosses the blood-brain barrier and causes neurological dysfunction. Hallmark signs include: ASTERIXIS (liver flap/flapping tremor - when arms are extended and wrists dorsiflexed, the hands display rapid flexion-extension movements), CONFUSION progressing through stages (Stage 1: personality changes, sleep disturbances; Stage 2: asterixis, lethargy; Stage 3: marked confusion, stupor; Stage 4: coma), and FETOR HEPATICUS (a distinctive musty, sweet odor on the breath from the accumulation of mercaptans). Treatment: lactulose (osmotic laxative that traps ammonia in the gut as ammonium and eliminates it in stool), rifaximin (non-absorbed antibiotic that reduces ammonia-producing gut bacteria), protein modification (moderate restriction, 1-1.5 g/kg/day), and avoidance of precipitating factors (GI bleeding, infection, constipation, medications metabolized by liver).",
    "Hepatic encephalopathy: asterixis + confusion + fetor hepaticus = elevated ammonia; treat with lactulose and rifaximin", ["GI","hepatic-encephalopathy","cirrhosis","ammonia","asterixis"]));

  // Renal
  qs.push(rpn("Renal","UTI Management","Physiological Integrity",2,
    "An RPN is providing discharge teaching to a female patient being treated for a urinary tract infection (UTI). Which prevention strategy should the RPN include?",
    [O("A","Decrease fluid intake to reduce the frequency of urination"), O("B","Wipe from front to back after toileting, increase fluid intake to at least 2-3 litres daily, void immediately after sexual intercourse, and avoid douching or irritating feminine products"), O("C","Hold urine for as long as possible to allow antibiotics to concentrate in the bladder"), O("D","Take bubble baths daily to keep the perineal area clean")],
    ["B"],
    "UTI prevention strategies for women focus on minimizing bacterial introduction and promoting bacterial clearance: WIPE FRONT TO BACK to prevent fecal bacteria (E. coli, the most common UTI pathogen) from reaching the urethral meatus; INCREASE FLUID INTAKE (2-3 L/day) to dilute urine and increase urination frequency, which flushes bacteria from the urinary tract; VOID AFTER INTERCOURSE to flush bacteria that may have been introduced into the urethra during sexual activity; AVOID IRRITANTS (douches, feminine sprays, bubble baths) that can alter the normal vaginal pH and flora, promoting bacterial overgrowth; wear cotton underwear and avoid tight-fitting clothing to reduce moisture and bacterial growth. Cranberry products may help prevent recurrent UTIs by preventing E. coli adherence to uroepithelial cells. Holding urine (C) allows bacterial multiplication. Bubble baths (D) are irritants that increase UTI risk.",
    "UTI prevention: front-to-back wiping, increase fluids, void after intercourse, avoid irritants; most UTIs are caused by E. coli", ["renal","UTI","prevention","patient-education","women-health"]));

  // Musculoskeletal
  qs.push(rpn("Musculoskeletal","Cast Care","Physiological Integrity",2,
    "An RPN is providing cast care education to a patient with a newly applied plaster cast on the left forearm. Which instruction is correct?",
    [O("A","Cover the cast with plastic wrap to keep it dry; dry it with a hair dryer on the hot setting if it gets wet"), O("B","Keep the casted extremity elevated above heart level to reduce swelling, perform neurovascular checks by wiggling fingers regularly, and do NOT insert objects inside the cast to scratch"), O("C","Apply ice directly on top of the plaster cast to reduce swelling"), O("D","Begin weight-bearing immediately on the casted arm to promote bone healing")],
    ["B"],
    "Cast care education includes: ELEVATION above heart level reduces dependent edema and promotes venous return; NEUROVASCULAR ASSESSMENT (the 5 Ps: Pain, Pallor, Pulselessness, Paresthesia, Paralysis) should be performed regularly; wiggling fingers/toes assesses motor function and helps maintain circulation; NEVER INSERT OBJECTS into the cast (pencils, coat hangers) to relieve itching - this can cause skin breakdown and infection; allow plaster casts to air dry (takes 24-72 hours), handle with palms (not fingertips) while damp to prevent indentations; do NOT use a hot hair dryer as heat can cause burns under the cast and uneven drying that weakens the plaster. If the cast gets wet, blot with a towel and allow to air dry. Report any drainage, foul odor, new pain, numbness, tingling, or color changes immediately.",
    "Cast care: elevate, neurovascular checks (5 Ps), no objects inside, handle damp cast with palms, air dry", ["musculoskeletal","cast-care","neurovascular","education","orthopedic"]));

  // Endocrine
  qs.push(rpn("Endocrine","Addison vs Cushing","Physiological Integrity",3,
    "An RPN is differentiating between Addison disease and Cushing syndrome. Which clinical finding is specific to Addison disease?",
    [O("A","Moon face, buffalo hump, and purple striae"), O("B","Hyperpigmentation of the skin (bronze skin colour), hypotension, hyponatremia, hyperkalemia, and severe fatigue"), O("C","Hyperglycemia, central obesity, and hirsutism"), O("D","Exophthalmos, pretibial myxedema, and thyroid bruit")],
    ["B"],
    "Addison disease (primary adrenal insufficiency) results from destruction of the adrenal cortex, causing deficiency of CORTISOL, ALDOSTERONE, and adrenal androgens. Key findings: HYPERPIGMENTATION (increased ACTH from the pituitary stimulates melanocyte-stimulating hormone, causing bronze skin, especially in creases, scars, and buccal mucosa), HYPOTENSION (loss of aldosterone causes sodium and water loss), HYPONATREMIA (sodium wasting), HYPERKALEMIA (potassium retention from aldosterone deficiency), HYPOGLYCEMIA (loss of cortisol's gluconeogenic effect), severe fatigue, weight loss, and GI symptoms. CUSHING syndrome (cortisol EXCESS) presents the OPPOSITE: moon face, buffalo hump, central obesity, purple striae, hypertension, hyperglycemia, hypokalemia (cortisol has mineralocorticoid effects at high levels), thin fragile skin, and immunosuppression. Exophthalmos and pretibial myxedema (D) are specific to Graves disease (hyperthyroidism).",
    "Addison = cortisol/aldosterone DEFICIENCY (bronze skin, low BP, low Na, high K); Cushing = cortisol EXCESS (moon face, high BP, high glucose, low K)", ["endocrine","Addison","Cushing","adrenal","comparison"]));

  // Hematology
  qs.push(rpn("Hematology","Sickle Cell Crisis","Physiological Integrity",3,
    "An RPN is caring for a patient with sickle cell disease who presents with severe bone pain, fever, and swollen joints. The patient is in vaso-occlusive crisis. What is the PRIORITY nursing intervention?",
    [O("A","Apply ice packs to the painful joints to reduce inflammation"), O("B","Administer prescribed opioid analgesics promptly for pain management, initiate aggressive IV fluid hydration, apply warm compresses, and administer oxygen if SpO2 is below 95%"), O("C","Restrict fluid intake to prevent edema and swelling"), O("D","Encourage vigorous physical exercise to improve circulation to the affected areas")],
    ["B"],
    "Vaso-occlusive crisis (pain crisis) is the most common type of sickle cell crisis, caused by sickled red blood cells obstructing blood flow in small vessels, leading to tissue ischemia, infarction, and severe pain. Priority interventions include: PAIN MANAGEMENT - opioid analgesics (morphine, hydromorphone) administered on schedule, NOT PRN, as severe pain requires consistent management; patient-controlled analgesia (PCA) is ideal; HYDRATION - aggressive IV fluid replacement (typically 1.5-2x maintenance) to reduce blood viscosity and promote RBC flow through microcirculation; WARM COMPRESSES (not cold) - warmth causes vasodilation, improving blood flow to ischemic tissue; cold causes vasoconstriction, which WORSENS sickling; OXYGEN - administer if SpO2 <95% to prevent further sickling (deoxygenated hemoglobin S polymerizes and causes sickling); MONITOR for complications (acute chest syndrome, stroke, organ damage). Fluid RESTRICTION (C) would worsen dehydration and sickling. Exercise (D) increases oxygen demand and can precipitate or worsen crisis.",
    "Sickle cell crisis: aggressive pain management (opioids on schedule), IV hydration, WARM compresses (never cold), oxygen if SpO2<95%", ["hematology","sickle-cell","vaso-occlusive","pain-management","hydration"]));

  // More Canadian-specific RPN questions
  const rpnTopics = [
    { t: "Professional Practice", s: "Informed Consent", stem: "An RPN is preparing a patient for a procedure. The patient states they do not understand the procedure and have not been told about the risks. What should the RPN do?",
      correct: "Hold the procedure, notify the physician that the patient lacks understanding, and advocate for the patient to receive a proper explanation before signing the consent form",
      w1: "Have the patient sign the consent form anyway since the procedure is already scheduled",
      w2: "Explain the surgical technique and risks in detail since any healthcare provider can obtain informed consent",
      w3: "Proceed with the procedure since the patient was told about it at a previous appointment",
      rat: "Informed consent requires that the patient has been adequately informed about the procedure, risks, benefits, alternatives, and consequences of refusal by the physician/surgeon performing the procedure. The RPN's role is to WITNESS the consent (verify the patient is signing voluntarily and appears to understand) and ADVOCATE for the patient if they express confusion or lack of understanding. The nurse does NOT obtain informed consent (that is the physician's responsibility) but is obligated to HALT the procedure and notify the physician if the patient does not understand. Proceeding without informed consent violates the patient's right to autonomy and can constitute assault/battery.",
      cp: "Informed consent is the physician's responsibility; the nurse advocates and witnesses", tags: ["informed-consent","patient-rights","advocacy","legal","ethics"] },
    { t: "Gerontology", s: "Elder Abuse Recognition", stem: "An RPN in a long-term care facility notices that a resident has unexplained bruises on the inner arms, appears fearful around a specific caregiver, and has become withdrawn over the past month. What should the RPN suspect and do?",
      correct: "Suspect elder abuse; document findings objectively, report to the charge nurse and facility management, and report to the appropriate provincial authority (e.g., Ministry of Long-Term Care in Ontario) as mandated by law",
      w1: "Assume the bruises are from normal aging and thin skin; no further action is needed",
      w2: "Confront the suspected abuser directly and demand an explanation before making any report",
      w3: "Wait for more evidence before reporting since the bruises could have an innocent explanation",
      rat: "The pattern described (unexplained bruises in protected areas, fear of a specific caregiver, personality changes) raises serious suspicion of elder abuse. In Canada, ALL healthcare providers are MANDATORY REPORTERS of suspected elder abuse. The duty to report requires REASONABLE SUSPICION, not certainty. The RPN must: (1) document findings objectively with descriptions, measurements, and photographs if facility policy permits; (2) report through the facility's chain of command AND to the external regulatory authority; (3) ensure the resident's immediate safety. Inner arm bruises are in a protected location not typically associated with accidental injury. Behavioral changes (fearfulness, withdrawal) are common indicators of abuse. Confronting the suspected abuser (B) could lead to retaliation against the resident and obstruction of investigation.",
      cp: "Elder abuse: mandatory reporting of reasonable suspicion; do not wait for proof or confront the suspected abuser", tags: ["elder-abuse","mandatory-reporting","long-term-care","safeguarding","documentation"] },
    { t: "Wound Care", s: "Pressure Injury Prevention", stem: "An RPN is implementing a pressure injury prevention plan for a patient at high risk (Braden Scale score of 12). Which intervention is MOST effective?",
      correct: "Reposition the patient every 2 hours using a standardized turning schedule, use a pressure redistribution mattress, keep skin clean and dry, optimize nutrition (protein and caloric intake), and perform regular skin assessments",
      w1: "Massage the reddened bony prominences to improve blood circulation",
      w2: "Keep the patient in one comfortable position to avoid disturbing them",
      w3: "Apply a donut-shaped cushion to the sacrum to relieve pressure",
      rat: "A Braden Scale score of 12 indicates HIGH risk for pressure injury (scale range: 6-23; lower scores = higher risk; subscales assess sensory perception, moisture, activity, mobility, nutrition, and friction/shear). Evidence-based prevention includes: REPOSITIONING every 2 hours (or more frequently) to relieve sustained pressure on bony prominences; PRESSURE REDISTRIBUTION surfaces (specialty mattresses, overlays) that distribute body weight over a larger area; SKIN CARE to maintain integrity (clean, dry, moisturized); NUTRITION optimization (adequate protein for tissue maintenance, vitamin C and zinc for wound healing); REGULAR SKIN ASSESSMENT focusing on bony prominences (sacrum, heels, ischial tuberosities, trochanters, occiput). MASSAGE of reddened areas is CONTRAINDICATED (A) as it causes further tissue damage to already compromised capillaries. Donut-shaped cushions (D) are CONTRAINDICATED as they concentrate pressure around the ring edge, increasing damage.",
      cp: "Braden Scale: lower score = higher risk; reposition q2h, specialty mattress, nutrition, skin assessment; never massage reddened areas", tags: ["pressure-injury","Braden-Scale","prevention","repositioning","nutrition"] },
    { t: "Mental Health", s: "Depression Assessment", stem: "An RPN is assessing a patient for depression using a validated screening tool. The patient reports persistent sadness for 3 weeks, loss of interest in activities they used to enjoy, difficulty sleeping, poor appetite with 4 kg weight loss, and difficulty concentrating. Based on DSM-5 criteria, how many criteria does this patient meet?",
      correct: "Five criteria (depressed mood, anhedonia, insomnia, appetite/weight change, difficulty concentrating), which meets the threshold for a major depressive episode (requires 5 or more symptoms for at least 2 weeks)",
      w1: "Only two criteria; this does not meet the threshold for depression diagnosis",
      w2: "The patient is simply going through a normal period of sadness that does not require assessment",
      w3: "Zero criteria; these symptoms do not match any known psychiatric condition",
      rat: "The DSM-5 diagnostic criteria for a major depressive episode require at least 5 of the following 9 symptoms present for at least 2 weeks, with at least one being either depressed mood OR anhedonia (loss of interest/pleasure): (1) Depressed mood most of the day, nearly every day ✓; (2) Markedly diminished interest or pleasure in activities (anhedonia) ✓; (3) Significant weight loss/gain or appetite change ✓; (4) Insomnia or hypersomnia ✓; (5) Psychomotor agitation or retardation; (6) Fatigue or loss of energy; (7) Feelings of worthlessness or excessive guilt; (8) Diminished ability to concentrate ✓; (9) Recurrent thoughts of death or suicidal ideation. This patient meets 5 criteria over 3 weeks, exceeding the minimum threshold. Screening tools include the PHQ-9 (Patient Health Questionnaire-9), which assesses all 9 DSM-5 criteria.",
      cp: "Major depression: ≥5 of 9 symptoms for ≥2 weeks, must include depressed mood OR anhedonia; use PHQ-9 for screening", tags: ["mental-health","depression","DSM-5","screening","PHQ-9"] },
    { t: "Diabetes Management", s: "Insulin Types", stem: "An RPN is caring for a patient with type 1 diabetes who takes insulin glargine (Lantus) at bedtime and insulin lispro (Humalog) before meals. Which statement demonstrates the RPN's understanding of these insulin types?",
      correct: "Glargine is a long-acting (basal) insulin with no peak that provides 24-hour background coverage, while lispro is a rapid-acting insulin given 15 minutes before meals to cover postprandial glucose spikes",
      w1: "Both insulins should be mixed in the same syringe for convenience",
      w2: "Glargine is the rapid-acting insulin used for meal coverage and lispro is the long-acting basal insulin",
      w3: "Both insulins have the same onset and duration and are interchangeable",
      rat: "Understanding insulin pharmacokinetics is essential for safe administration. RAPID-ACTING (lispro/Humalog, aspart/NovoRapid, glulisine/Apidra): onset 10-15 min, peak 1-2 hrs, duration 3-5 hrs. Given immediately before or with meals to control postprandial glucose. SHORT-ACTING (regular/Humulin R): onset 30-60 min, peak 2-4 hrs, duration 6-8 hrs. Given 30 min before meals. INTERMEDIATE-ACTING (NPH/Humulin N): onset 1-3 hrs, peak 4-12 hrs, duration 16-24 hrs. The cloudy insulin. LONG-ACTING (glargine/Lantus, detemir/Levemir): onset 1-2 hrs, NO PEAK (flat profile), duration 20-24+ hrs. Provides basal coverage. CRITICAL: glargine and detemir should NEVER be mixed with any other insulin in the same syringe (option A is incorrect). The clear insulin analogy: glargine is clear but long-acting (exception to the clear=fast rule). The basal-bolus regimen (long-acting + rapid-acting) mimics normal pancreatic insulin secretion.",
      cp: "Insulin types by onset: Rapid (15min) > Short (30-60min) > Intermediate (1-3hrs) > Long (1-2hrs, no peak); NEVER mix glargine", tags: ["diabetes","insulin-types","glargine","lispro","basal-bolus","pharmacology"] },
    { t: "Neurology", s: "Glasgow Coma Scale", stem: "An RPN is performing neurological assessments every 2 hours on a patient who sustained a head injury. The patient's GCS was 14 at the last assessment but is now 11. What does this decline indicate?",
      correct: "A deterioration of 3 or more points on the GCS indicates a significant neurological decline possibly suggesting increasing intracranial pressure, intracranial bleeding, or cerebral edema; the physician must be notified immediately",
      w1: "A GCS change from 14 to 11 is within normal variation and does not require any action",
      w2: "This improvement in the GCS score means the patient is getting better",
      w3: "The GCS is unreliable after head injury and should not be used for trending",
      rat: "The Glasgow Coma Scale (GCS) ranges from 3 (deep coma) to 15 (fully alert and oriented). A decrease in GCS indicates neurological deterioration. A drop of 2 or more points is clinically significant and warrants immediate physician notification. Going from 14 to 11 represents a 3-point decline, indicating significant deterioration that could signal: expanding intracranial hemorrhage (epidural or subdural hematoma), increasing cerebral edema, rising intracranial pressure, or herniation syndrome. The RPN must: (1) repeat the GCS assessment to confirm, (2) assess pupil size and reactivity (unilateral dilation = uncal herniation), (3) check vital signs for Cushing's triad (hypertension, bradycardia, irregular respirations), (4) notify the physician IMMEDIATELY, and (5) prepare for possible CT scan and neurosurgical intervention. Serial GCS monitoring is the MOST reliable trend indicator for neurological status in head-injured patients.",
      cp: "GCS drop of ≥2 points = significant deterioration requiring immediate notification; always trend GCS scores over time", tags: ["neurology","GCS","head-injury","neurological-deterioration","ICP"] },
    { t: "Maternal Health", s: "Gestational Diabetes", stem: "An RPN is caring for a pregnant patient diagnosed with gestational diabetes mellitus (GDM) at 26 weeks. Which teaching is MOST important for managing GDM?",
      correct: "Monitor blood glucose levels as directed (fasting and 1-2 hours postprandial), follow a balanced diet with controlled carbohydrate intake distributed across meals and snacks, engage in regular moderate exercise, and attend all prenatal appointments for fetal monitoring",
      w1: "Eliminate all carbohydrates from the diet to keep blood glucose levels as low as possible",
      w2: "Take oral hypoglycemic agents (metformin) without dietary modification since medication alone controls GDM",
      w3: "Skip meals to prevent blood glucose from rising after eating",
      rat: "Gestational diabetes mellitus (GDM) affects 3-9% of pregnancies in Canada and is caused by placental hormones (human placental lactogen, cortisol, progesterone) that create insulin resistance. Management priorities: BLOOD GLUCOSE MONITORING (targets: fasting <5.3 mmol/L, 1-hour postprandial <7.8 mmol/L, 2-hour postprandial <6.7 mmol/L per Diabetes Canada guidelines); MEDICAL NUTRITION THERAPY (the primary treatment - balanced diet with controlled carbohydrate intake distributed across 3 meals and 2-3 snacks to prevent glucose spikes; do NOT eliminate carbohydrates as they are essential for fetal brain development); EXERCISE (moderate activity for 30 min/day reduces insulin resistance); INSULIN THERAPY if targets are not met with diet/exercise alone (insulin does not cross the placenta). Risks of uncontrolled GDM: macrosomia, birth injuries, neonatal hypoglycemia, jaundice, and respiratory distress syndrome. Most GDM resolves after delivery, but affected women have a 50% risk of developing type 2 diabetes within 5-10 years.",
      cp: "GDM management: diet + exercise first; controlled carbohydrates (not elimination); insulin if needed; fasting glucose target <5.3 mmol/L", tags: ["gestational-diabetes","pregnancy","blood-glucose","nutrition","prenatal"] },
    { t: "Palliative Care", s: "Symptom Management", stem: "An RPN is caring for a patient receiving palliative care for end-stage pancreatic cancer. The patient has severe nausea despite antiemetic medication. Which complementary intervention can the RPN offer?",
      correct: "Offer ginger tea or ginger lozenges (evidence supports ginger's antiemetic properties), provide small frequent meals, ensure a well-ventilated room free of strong odours, and consider acupressure at the P6 (Neiguan) point on the wrist",
      w1: "Force the patient to eat large meals to maintain nutritional status despite nausea",
      w2: "Discontinue all antiemetic medications and rely solely on complementary therapies",
      w3: "Restrict all oral intake indefinitely to prevent vomiting",
      rat: "In palliative care, quality of life is the priority. Evidence-based complementary interventions for nausea include: GINGER (contains gingerols and shogaols that block serotonin receptors in the GI tract, similar to ondansetron; available as tea, lozenges, capsules); ACUPRESSURE at P6 (Neiguan) point (located 3 finger-widths above the wrist crease between the two tendons on the inner forearm; Sea-Bands apply continuous pressure to this point); DIETARY MODIFICATIONS (small frequent meals, bland foods, cold foods have less odour, avoid lying flat after eating); ENVIRONMENTAL measures (ventilation, removing strong odours, keeping the room cool); AROMATHERAPY with peppermint or lemon. These complement, not replace, pharmacological antiemetics. Forcing large meals (A) worsens nausea. Stopping antiemetics (B) removes the foundation of symptom management. Total oral restriction (D) is inappropriate unless there is bowel obstruction.",
      cp: "Palliative nausea: ginger (evidence-based), small meals, environment, P6 acupressure; complement medications, don't replace them", tags: ["palliative-care","nausea","complementary-therapy","ginger","symptom-management"] },
    { t: "Infection Control", s: "Tuberculosis Screening", stem: "An RPN performs a Mantoux tuberculin skin test (TST) on a patient. The RPN returns after 48 hours and measures 12 mm of induration. The patient is a healthcare worker with no known immunosuppression. How should this result be interpreted?",
      correct: "Positive result: for healthcare workers, ≥10 mm of induration is considered positive, indicating TB infection (latent or active); the patient needs a chest X-ray and further evaluation to differentiate latent TB infection from active TB disease",
      w1: "Negative result; only induration ≥25 mm is considered positive",
      w2: "The result is inconclusive and the test must be repeated in the other arm immediately",
      w3: "Positive only if erythema (redness) around the injection site exceeds 15 mm",
      rat: "The Mantoux tuberculin skin test (TST/PPD) is interpreted based on the size of INDURATION (raised, hardened area), NOT erythema (redness). Reading must occur 48-72 hours after injection. The interpretation threshold depends on the patient's risk category: ≥5 mm positive for: HIV-positive, recent TB contacts, immunosuppressed patients, organ transplant recipients, and persons with fibrotic changes on CXR. ≥10 mm positive for: healthcare workers, persons from high-prevalence countries, injection drug users, residents/employees of congregate settings (shelters, correctional facilities), and persons with clinical conditions increasing TB risk (diabetes, renal failure, malignancy). ≥15 mm positive for: persons with no known risk factors. As a healthcare worker, this patient's threshold is ≥10 mm, making 12 mm a POSITIVE result. A positive TST indicates the person has been INFECTED with TB bacteria but does not differentiate between latent TB infection (LTBI) and active TB disease. A chest X-ray is required to rule out active disease. The IGRA (interferon-gamma release assay) blood test is an alternative to TST.",
      cp: "TST interpretation by risk: ≥5mm (HIV/contacts), ≥10mm (healthcare workers), ≥15mm (no risk factors); measure INDURATION not redness", tags: ["TB","TST","Mantoux","screening","infection-control","healthcare-worker"] },
  ];

  for (const rr of rpnTopics) {
    qs.push(rpn(rr.t, rr.s, "Physiological Integrity", 3, rr.stem,
      [O("A", rr.w1), O("B", rr.correct), O("C", rr.w2), O("D", rr.w3)],
      ["B"], rr.rat, rr.cp, rr.tags));
  }

  // ============= NCLEX-PN US Questions =============

  const pnTopics = [
    { t: "Physiological Integrity", s: "Cardiac Assessment", stem: "An LPN is assessing a patient and notes bilateral ankle edema, ascites, and hepatomegaly. These findings are MOST consistent with which type of heart failure?", correct: "Right-sided heart failure: the right ventricle cannot effectively pump blood to the lungs, causing blood to back up into the systemic venous circulation, resulting in peripheral edema, ascites, hepatomegaly, and JVD", w1: "Left-sided heart failure causing pulmonary congestion", w2: "Aortic stenosis causing outflow obstruction", w3: "Pericardial effusion causing cardiac tamponade",
      rat: "Right-sided heart failure (RHF) causes systemic congestion because blood backs up into the venous system. Think 'right side = rest of the body.' Key findings: peripheral edema (bilateral, pitting, gravity-dependent - ankles when standing, sacrum when lying), ascites (fluid in peritoneal cavity from portal vein congestion), hepatomegaly (hepatic congestion from backed-up blood in the hepatic veins), jugular venous distension (JVD), weight gain from fluid retention. LEFT-sided heart failure causes PULMONARY congestion: dyspnea, orthopnea, paroxysmal nocturnal dyspnea, cough, crackles, pulmonary edema. Mnemonic: Left=Lungs, Right=Rest of body.", cp: "Right HF = systemic congestion (edema, ascites, JVD); Left HF = pulmonary congestion (dyspnea, crackles, pulmonary edema)", tags: ["cardiac","heart-failure","right-sided","edema","assessment"] },
    { t: "Pharmacological Therapies", s: "Antibiotic Teaching", stem: "An LPN is providing education to a patient who is prescribed a 10-day course of amoxicillin for a bacterial infection. The patient asks, 'Can I stop taking the antibiotic once I feel better?' What is the correct response?", correct: "'You must complete the entire 10-day course even if you feel better. Stopping early allows surviving bacteria to multiply and potentially develop antibiotic resistance, which could make the infection harder to treat.'", w1: "'Yes, once your symptoms are gone, you can save the remaining pills for the next time you get sick.'", w2: "'You only need to take it for 3 days; 10 days is excessive.'", w3: "'Share the remaining pills with a family member who has similar symptoms.'",
      rat: "Completing the full course of antibiotics is essential because: (1) Symptom improvement does NOT mean the infection is fully eradicated - bacteria may still be present in reduced numbers; (2) Stopping early allows the strongest, most resistant bacteria to survive and multiply (survival of the fittest/antibiotic selection pressure); (3) These resistant bacteria can cause a RELAPSE infection that is harder to treat; (4) Incomplete courses contribute to the global crisis of ANTIBIOTIC RESISTANCE; (5) Antibiotics should NEVER be saved for later or shared, as different infections require different antibiotics, doses, and durations. The prescriber determines the appropriate duration based on the type and severity of infection. The nurse should educate about: completing the full course, taking at consistent intervals, common side effects, drug/food interactions, and when to seek medical attention (allergic reactions, worsening symptoms).", cp: "Complete the FULL antibiotic course even when feeling better; stopping early promotes antibiotic resistance", tags: ["antibiotics","adherence","resistance","patient-education","amoxicillin"] },
    { t: "Safe & Effective Care Environment", s: "Falls Prevention", stem: "An LPN is implementing fall prevention strategies for a hospitalized 75-year-old patient on multiple medications including a sedative, diuretic, and antihypertensive. Which intervention is MOST important?", correct: "Implement a comprehensive fall prevention plan: bed alarm, non-slip footwear, bed in lowest position, call light within reach, toileting schedule (every 2 hours due to diuretic), adequate lighting, and medication review to minimize sedation", w1: "Apply bilateral wrist restraints to keep the patient in bed", w2: "Keep all four side rails up at all times as a fall prevention measure", w3: "Confine the patient to bed rest for the entire hospitalization to prevent falls",
      rat: "A comprehensive, individualized fall prevention plan addresses MULTIPLE risk factors simultaneously. This patient has 3 major medication-related fall risk factors: SEDATIVE (causes drowsiness, impaired judgment, slowed reflexes), DIURETIC (causes frequent urination with urgency, potential orthostatic hypotension from volume depletion), ANTIHYPERTENSIVE (causes orthostatic hypotension, dizziness). Evidence-based interventions include: bed alarm (alerts staff when patient attempts to get up unassisted), non-slip footwear (prevents slipping on hospital floors), lowest bed position (reduces injury height if fall occurs), call light within reach (enables patient to call for help), toileting schedule every 2 hours (anticipates diuretic-induced urgency, reducing independent bathroom trips), adequate lighting (prevents tripping in dim conditions), and medication review (physician may adjust sedative timing or dose). RESTRAINTS (A) increase fall risk and injury severity. All 4 side rails up (B) is considered a restraint and patients may climb over them. Bed rest (C) causes deconditioning, DVT, and pressure injuries.", cp: "Fall prevention is multimodal: address medications, environment, toileting, mobility; restraints INCREASE fall risk", tags: ["falls","prevention","geriatric","medication-risk","patient-safety"] },
    { t: "Physiological Integrity", s: "Gastrointestinal Assessment", stem: "An LPN is caring for a patient who underwent abdominal surgery 2 days ago. The patient has not passed flatus and has a distended abdomen with absent bowel sounds. What does this assessment indicate?", correct: "Paralytic ileus (postoperative ileus): temporary cessation of intestinal peristalsis common after abdominal surgery due to handling of the bowel, anesthesia effects, and opioid use", w1: "Normal postoperative recovery; begin a regular diet immediately", w2: "Bowel obstruction requiring emergency surgery within the hour", w3: "Appendicitis developing as a new complication of the surgery",
      rat: "Paralytic ileus (adynamic ileus) is a common postoperative complication characterized by temporary cessation of intestinal peristalsis without mechanical obstruction. It occurs in 10-30% of patients after abdominal surgery. Causes include: surgical manipulation of the bowel (handling triggers a sympathetic response that inhibits peristalsis), general anesthesia effects on GI motility, opioid analgesics (bind to mu receptors in the GI tract, slowing peristalsis), electrolyte imbalances (especially hypokalemia), and immobility. Assessment findings: abdominal distension, absent or hypoactive bowel sounds, no passage of flatus or stool, nausea/vomiting. Management: NPO or clear liquids until bowel function returns, NG tube insertion for decompression if vomiting occurs, early ambulation (most important intervention for promoting return of peristalsis), correction of electrolyte imbalances, minimize opioid use (use multimodal analgesia including ketorolac, acetaminophen), and chewing gum (stimulates the cephalic-vagal reflex promoting GI motility - evidence-based practice).", cp: "Post-op ileus: absent bowel sounds + distension + no flatus; treat with ambulation, NPO/NG, correct electrolytes, minimize opioids", tags: ["postoperative","ileus","GI","bowel-sounds","abdominal-surgery"] },
    { t: "Psychosocial Integrity", s: "Dementia Care", stem: "An LPN is caring for a patient with moderate Alzheimer disease who becomes agitated and combative during evening hours (sundowning). Which intervention is MOST therapeutic?", correct: "Maintain a consistent daily routine, reduce environmental stimulation in the evening (dim lights, reduce noise), redirect the patient's attention to a calming activity, use simple one-step instructions, and avoid arguing with or correcting the patient", w1: "Physically restrain the patient to prevent injury during agitated periods", w2: "Administer haloperidol (Haldol) as the first-line treatment for sundowning", w3: "Confine the patient to a dark room alone until the agitation passes",
      rat: "Sundowning (late-day confusion) is a common phenomenon in dementia where agitation, confusion, and behavioral disturbances worsen in the late afternoon and evening. Contributing factors include fatigue, sensory overload throughout the day, reduced lighting creating shadows and visual misperceptions, disrupted circadian rhythms, and unmet needs (pain, hunger, toileting). Non-pharmacological interventions are FIRST-LINE: maintain consistent daily routine (predictability reduces anxiety), reduce environmental stimulation in the evening (dim lights gradually to simulate natural sunset, reduce noise), redirect attention to calming familiar activities (music, folding towels, looking at photo albums), use simple language and one-step commands, NEVER argue with or correct the patient (enter their reality using validation therapy), address unmet needs, ensure adequate daytime light exposure, and minimize daytime napping. Restraints (A) increase agitation and are last resort. Antipsychotics (B) carry significant risks in elderly dementia patients (black box warning for increased mortality) and are not first-line. Isolation (C) increases fear and disorientation.", cp: "Sundowning: non-pharmacological interventions first (routine, reduce stimulation, redirect, validate); antipsychotics are last resort with significant risks in elderly", tags: ["dementia","sundowning","Alzheimer","behavioral-management","non-pharmacological"] },
    { t: "Pharmacological Therapies", s: "Opioid Safety", stem: "An LPN is monitoring a patient receiving a continuous morphine infusion via PCA pump. Which assessment finding indicates a need for IMMEDIATE intervention?", correct: "Respiratory rate of 8 breaths/min, pinpoint pupils, and the patient is difficult to arouse; these are signs of opioid overdose requiring immediate naloxone (Narcan) administration and supportive care", w1: "Mild nausea after the first dose, which is a common side effect", w2: "The patient reports pain relief with a pain score of 3/10 from a baseline of 8/10", w3: "Mild itching at the IV site without urticaria or rash",
      rat: "The triad of respiratory depression (RR <10-12), pinpoint pupils (miosis from parasympathetic stimulation of the oculomotor nerve), and altered level of consciousness (sedation preceding respiratory depression) are the classic signs of OPIOID OVERDOSE, a life-threatening emergency. Assessment using the Pasero Opioid-Induced Sedation Scale (POSS) helps identify escalating sedation before respiratory arrest: S = sleeping, easy to arouse (acceptable); 1 = awake and alert (acceptable); 2 = slightly drowsy, easy to arouse (acceptable); 3 = frequently drowsy, arousable, drifts off during conversation (UNACCEPTABLE - reduce dose); 4 = somnolent, minimal or no response to stimulation (UNACCEPTABLE - STOP opioid, consider naloxone). Immediate interventions for opioid overdose: (1) STOP the PCA infusion, (2) stimulate the patient (sternal rub, call name loudly), (3) call for help, (4) administer NALOXONE (Narcan) 0.04-0.4 mg IV, titrate in small increments to restore respirations without completely reversing analgesia, (5) provide bag-valve-mask ventilation if apneic, (6) monitor closely as naloxone has a shorter half-life than most opioids (redosing may be needed).", cp: "Opioid overdose triad: respiratory depression + pinpoint pupils + altered LOC = emergency; naloxone is the antidote", tags: ["opioid","overdose","naloxone","PCA","respiratory-depression","patient-safety"] },
    { t: "Coordinated Care", s: "Delegation to CNA", stem: "An LPN is working with a certified nursing assistant (CNA). Which task can the LPN appropriately delegate to the CNA?", correct: "Obtaining vital signs on a stable patient, recording intake and output, assisting with meals and ambulation, and performing perineal care; the LPN provides clear instructions, expected findings to report, and follows up on the results", w1: "Performing the initial admission assessment on a new patient", w2: "Administering oral medications to a stable patient", w3: "Educating a newly diagnosed diabetic patient about insulin injection technique",
      rat: "Delegation is the transfer of responsibility for performing a selected nursing task to a qualified individual, while retaining accountability for the outcomes. The Five Rights of Delegation guide the LPN: Right TASK (routine, standardized, low-risk tasks appropriate for the CNA's training), Right CIRCUMSTANCES (stable patient, predictable outcomes), Right PERSON (CNA is competent and trained for the specific task), Right DIRECTION/COMMUNICATION (clear instructions, expected outcomes, parameters for reporting), Right SUPERVISION/EVALUATION (LPN follows up, evaluates outcomes, provides feedback). CNAs can perform: vital signs on stable patients, I&O recording, assistance with ADLs (feeding, bathing, toileting, ambulation), specimen collection (urine, stool), simple wound dressing changes in some settings. CNAs CANNOT: perform assessments (A), administer medications (B), provide patient education (C), perform sterile procedures, or make clinical decisions. The LPN retains ACCOUNTABILITY for all delegated tasks.",
      cp: "Delegation: right task (routine, low-risk), right person (CNA competent), right communication (clear instructions), right supervision (follow up)", tags: ["delegation","CNA","scope-of-practice","five-rights","teamwork"] },
    { t: "Physiological Integrity", s: "Wound Care Basics", stem: "An LPN is caring for a patient with a stage 3 pressure injury on the sacrum. The wound bed shows 60% yellow slough and 40% red granulation tissue. Which wound care intervention is MOST appropriate?", correct: "Perform selective debridement of the yellow slough (enzymatic, autolytic, or sharp per provider order) while protecting the red granulation tissue; apply a moisture-retentive dressing, optimize nutrition, and continue pressure redistribution measures", w1: "Pack the wound tightly with dry gauze and change the dressing every 8 hours", w2: "Apply hydrogen peroxide directly to the wound bed to clean it before dressing", w3: "Leave the wound open to air to promote drying and scab formation",
      rat: "A stage 3 pressure injury involves full-thickness skin loss with subcutaneous tissue damage. The wound with 60% yellow slough requires debridement because slough impedes healing by providing a medium for bacterial growth and preventing granulation tissue formation. Types of debridement include: AUTOLYTIC (moisture-retentive dressings trap wound fluid containing enzymes that naturally dissolve slough - slowest but least painful), ENZYMATIC (collagenase/Santyl applied to the wound bed to dissolve necrotic tissue), SHARP/SURGICAL (fastest, performed by qualified practitioners using sterile instruments). The 40% red granulation tissue must be PROTECTED during debridement. Moisture-retentive dressings (hydrogels, foam, hydrocolloids) maintain the optimal moist wound healing environment. Dry gauze packing (A) desiccates the wound bed and damages granulation tissue when removed (wet-to-dry dressings are considered outdated practice). Hydrogen peroxide (B) is CYTOTOXIC to healthy cells and is no longer recommended for wound care. Allowing air drying (C) promotes desiccation, which impairs epithelial cell migration and delays healing.",
      cp: "Wound with slough: debride slough, protect granulation tissue, maintain moist environment; avoid H2O2 and dry gauze", tags: ["wound-care","pressure-injury","debridement","slough","granulation"] },
    { t: "Physiological Integrity", s: "Endocrine Assessment", stem: "An LPN is assessing a patient admitted with Graves disease. Which cluster of findings is MOST consistent with this condition?", correct: "Exophthalmos (protruding eyes), heat intolerance, unexplained weight loss despite increased appetite, tachycardia, tremors, diaphoresis, goiter, and emotional lability", w1: "Cold intolerance, weight gain, bradycardia, constipation, and fatigue", w2: "Moon face, central obesity, purple striae, and hirsutism", w3: "Bronze skin discoloration, hypotension, and salt cravings",
      rat: "Graves disease is the most common cause of hyperthyroidism, caused by thyroid-stimulating immunoglobulins (TSI) that bind to TSH receptors and stimulate excessive thyroid hormone production. Thyroid hormones regulate cellular metabolism, so EXCESS causes HYPERMETABOLIC symptoms: EXOPHTHALMOS (unique to Graves - antibodies cause inflammation and swelling of orbital tissues, pushing the eyes forward), HEAT INTOLERANCE (increased metabolic heat production), WEIGHT LOSS despite increased appetite (accelerated metabolism burns calories faster than consumed), TACHYCARDIA/palpitations (thyroid hormones increase cardiac sensitivity to catecholamines), TREMORS (increased nervous system stimulation), DIAPHORESIS (compensatory heat dissipation), GOITER (enlarged thyroid from TSI stimulation), EMOTIONAL LABILITY (anxiety, irritability, insomnia). Labs show: elevated free T4, elevated T3, suppressed TSH, positive TSI antibodies. Treatment: antithyroid medications (methimazole, PTU), radioactive iodine (RAI) ablation, or thyroidectomy. Option A describes HYPOTHYROIDISM, B describes CUSHING syndrome, C describes ADDISON disease.",
      cp: "Graves disease (hyperthyroidism): everything is UP (heart rate, metabolism, temperature, anxiety); opposite of hypothyroidism", tags: ["Graves","hyperthyroidism","exophthalmos","thyroid","endocrine"] },
    { t: "Physiological Integrity", s: "Respiratory Assessment", stem: "An LPN is caring for a patient with a chest tube. The water-seal chamber shows tidaling (fluctuation of the water level with respirations). What does this indicate?", correct: "Normal chest tube functioning: the water level rises on inspiration (spontaneously breathing patient) and falls on expiration, indicating the tube is patent and there is continued communication between the pleural space and the drainage system", w1: "The chest tube is blocked and needs to be replaced immediately", w2: "There is a massive air leak requiring emergency surgical intervention", w3: "The lung has fully re-expanded and the chest tube can be removed immediately",
      rat: "Tidaling (oscillation) in the water-seal chamber is a NORMAL finding indicating proper chest tube function. In a spontaneously breathing patient: the water level RISES during INSPIRATION (negative intrathoracic pressure pulls water up in the chamber) and FALLS during EXPIRATION (positive pressure pushes it down). In a mechanically ventilated patient, the pattern is REVERSED: water rises on expiration and falls on inspiration due to the positive pressure ventilation. ABSENCE of tidaling may indicate: (1) the lung has fully re-expanded (no more air/fluid communication between pleural space and tube), or (2) the tube is occluded by a clot, kink, or the patient lying on the tubing. The nurse should assess for tube patency before assuming lung re-expansion. CONTINUOUS BUBBLING in the water-seal chamber indicates an air leak (abnormal). GENTLE CONTINUOUS BUBBLING in the SUCTION CONTROL chamber is normal when suction is applied.", cp: "Tidaling = normal; absent tidaling = check for tube kink or occlusion OR lung re-expansion; continuous bubbling in water-seal = air leak", tags: ["chest-tube","water-seal","tidaling","respiratory","assessment"] },
  ];

  for (const pp of pnTopics) {
    qs.push(pn(pp.t, pp.s, "Physiological Integrity", 3, pp.stem,
      [O("A", pp.w1), O("B", pp.correct), O("C", pp.w2), O("D", pp.w3)],
      ["B"], pp.rat, pp.cp, pp.tags));
  }

  // ============= NCLEX-RN Questions =============

  const rnTopics = [
    { t: "Critical Care", s: "Shock Assessment", stem: "An RN is assessing a patient who presents with warm, flushed skin, bounding pulses, tachycardia (HR 110), hypotension (BP 84/50), and fever (39.8°C). Which type of shock should the RN suspect?",
      correct: "Distributive shock (septic): early/warm phase characterized by peripheral vasodilation causing warm flushed skin and bounding pulses, hypotension from decreased systemic vascular resistance, and compensatory tachycardia",
      w1: "Hypovolemic shock from hemorrhage causing cold, clammy skin",
      w2: "Cardiogenic shock from left ventricular failure causing pulmonary edema",
      w3: "Obstructive shock from cardiac tamponade causing muffled heart sounds",
      rat: "Shock types have distinct hemodynamic profiles: DISTRIBUTIVE (septic early/warm phase): massive peripheral VASODILATION reduces SVR, causing warm, flushed skin and bounding pulses (blood flows freely through dilated vessels). Cardiac output is initially HIGH (compensatory), but BP drops because SVR is so low. Fever indicates the infectious/inflammatory trigger. Late/cold phase: vasoconstriction, poor perfusion, cold mottled skin. HYPOVOLEMIC: decreased preload from blood/fluid loss; cold, clammy skin from vasoconstriction; tachycardia; narrow pulse pressure. CARDIOGENIC: pump failure; elevated filling pressures; pulmonary edema; cold clammy skin; JVD. OBSTRUCTIVE: physical obstruction to blood flow (PE, tamponade, tension pneumothorax); JVD; hypotension. Key differentiator: WARM skin + hypotension + fever = distributive (septic); COLD skin + hypotension = hypovolemic or cardiogenic.",
      cp: "Warm shock = early septic (vasodilation, warm skin, low SVR, high CO); Cold shock = late septic, hypovolemic, or cardiogenic (vasoconstriction, cold skin)", tags: ["shock","septic","distributive","hemodynamics","assessment"] },
    { t: "Pharmacology", s: "Antidote Knowledge", stem: "An RN is reviewing antidotes for common overdoses and poisonings. Which antidote-toxin pairing is CORRECT?",
      correct: "N-acetylcysteine (Mucomyst) is the antidote for acetaminophen (Tylenol) overdose; it replenishes glutathione stores in the liver, preventing hepatotoxic metabolite (NAPQI) accumulation that causes hepatic necrosis",
      w1: "Flumazenil is the antidote for opioid overdose",
      w2: "Naloxone (Narcan) is the antidote for benzodiazepine overdose",
      w3: "Protamine sulfate is the antidote for warfarin overdose",
      rat: "Knowing antidote-toxin pairings is critical for emergency nursing. Correct pairings: N-ACETYLCYSTEINE (NAC/Mucomyst) → ACETAMINOPHEN overdose (prevents hepatic necrosis by replenishing glutathione; most effective within 8 hours of ingestion but beneficial up to 72 hours). NALOXONE (Narcan) → OPIOID overdose (competitive antagonist at mu receptors; reverses respiratory depression). FLUMAZENIL (Romazicon) → BENZODIAZEPINE overdose (competitive antagonist at GABA-A receptors; use cautiously as it can precipitate seizures in chronic users). PROTAMINE SULFATE → HEPARIN overdose (binds to heparin, neutralizing its anticoagulant effect; 1 mg protamine neutralizes ~100 units of heparin). VITAMIN K (Phytonadione) → WARFARIN overdose (promotes synthesis of vitamin K-dependent clotting factors II, VII, IX, X). DIGOXIN IMMUNE FAB (Digibind) → DIGOXIN toxicity. ATROPINE → ORGANOPHOSPHATE/cholinergic poisoning. CALCIUM GLUCONATE → CALCIUM CHANNEL BLOCKER overdose and hypermagnesemia.",
      cp: "Key antidotes: NAC→acetaminophen, Naloxone→opioids, Flumazenil→benzos, Protamine→heparin, Vitamin K→warfarin", tags: ["pharmacology","antidotes","overdose","acetaminophen","emergency"] },
    { t: "Maternity", s: "Labor Stages", stem: "An RN is caring for a laboring patient. The patient's cervix is 8 cm dilated with contractions every 2-3 minutes lasting 60-90 seconds. The patient is restless, irritable, and says 'I can't do this anymore.' Which phase of labor is the patient in?",
      correct: "Transition phase (late first stage of labor): cervical dilation 8-10 cm, most intense contractions, emotional signs include restlessness, irritability, loss of control, and statements of inability to continue",
      w1: "Latent phase of the first stage with mild contractions and early dilation",
      w2: "Second stage of labor (pushing stage) from full dilation to delivery",
      w3: "Fourth stage of labor (recovery period) following placental delivery",
      rat: "Labor is divided into 4 stages, with the first stage having 3 phases: FIRST STAGE (cervical dilation): LATENT phase (0-6 cm): mild contractions every 5-30 min, 15-40 sec; patient is talkative, excited; may last 6-8+ hours. ACTIVE phase (6-8 cm): moderate contractions every 3-5 min, 40-60 sec; patient becomes more focused, uses breathing techniques. TRANSITION phase (8-10 cm): strong contractions every 2-3 min, 60-90 sec; most intense phase; patient shows: restlessness, irritability, loss of coping, nausea/vomiting, trembling, statements of being unable to continue, increased bloody show, rectal pressure. The nurse should: provide continuous support, offer reassurance that the feeling of being unable to continue is NORMAL for transition and often means delivery is near, maintain a calm environment, assist with breathing techniques, and prepare for the second stage (pushing). SECOND STAGE: full dilation (10 cm) to delivery of baby. THIRD STAGE: delivery of baby to delivery of placenta. FOURTH STAGE: first 1-2 hours after delivery (recovery/stabilization).",
      cp: "Transition phase: 8-10 cm, strongest contractions, emotional intensity ('I can't do this') = delivery is approaching", tags: ["maternity","labor","transition","first-stage","cervical-dilation"] },
    { t: "Pediatric", s: "Croup vs Epiglottitis", stem: "An RN is differentiating between croup and epiglottitis in a pediatric patient. Which finding is MOST characteristic of croup (laryngotracheobronchitis)?",
      correct: "Barking 'seal-like' cough, inspiratory stridor that worsens at night, low-grade fever, gradual onset over 1-2 days, and symptoms that improve with cool mist or steam",
      w1: "Sudden onset high fever (>39°C), drooling, tripod positioning, and muffled voice",
      w2: "Productive cough with green sputum, fever, and bilateral crackles",
      w3: "Wheezing with prolonged expiratory phase, barrel chest, and cyanosis",
      rat: "Croup (laryngotracheobronchitis) and epiglottitis are both upper airway conditions in children but have DISTINCTLY different presentations: CROUP: caused by parainfluenza virus (most common); GRADUAL onset (1-2 days of URI symptoms first); age typically 6 months to 3 years; BARKING 'seal-like' COUGH (the hallmark, caused by subglottic edema and narrowing); inspiratory STRIDOR (worsens at night due to cool air and position changes); LOW-GRADE FEVER; hoarseness; symptoms often IMPROVE with cool mist or brief exposure to cold night air; treatment: cool mist, racemic epinephrine nebulization for moderate-severe cases, oral dexamethasone. EPIGLOTTITIS: caused by H. influenzae type b (rare since Hib vaccine); SUDDEN onset (hours); age typically 3-7 years; HIGH FEVER (>39°C); DROOLING, DYSPHAGIA; TRIPOD position; MUFFLED voice; NO barking cough; NEVER examine the throat or use a tongue depressor (risk of complete obstruction). Option C describes pneumonia, Option D describes asthma/COPD.",
      cp: "Croup: gradual onset, barking cough, stridor, low fever, cool mist helps; Epiglottitis: sudden, high fever, drooling, DO NOT examine throat", tags: ["pediatric","croup","epiglottitis","comparison","airway","respiratory"] },
    { t: "Nutrition", s: "Parenteral Nutrition", stem: "An RN is caring for a patient receiving total parenteral nutrition (TPN) through a central line. The current bag of TPN runs out and the next bag is not yet available from pharmacy. What should the RN do?",
      correct: "Hang a bag of 10% dextrose in water (D10W) at the same rate as the TPN to prevent rebound hypoglycemia, and contact pharmacy urgently to expedite the next TPN bag",
      w1: "Simply stop the infusion and wait for the new bag; missing one bag will not affect the patient",
      w2: "Run normal saline (0.9% NaCl) at double the rate to compensate for the missed nutrition",
      w3: "Infuse the dextrose solution through a peripheral IV instead of the central line",
      rat: "TPN contains high concentrations of dextrose (typically 15-25%) that stimulate continuous insulin secretion from the pancreas. If TPN is abruptly discontinued, the elevated insulin levels persist for a period while the glucose source is suddenly removed, causing REBOUND HYPOGLYCEMIA, which can be severe and life-threatening (seizures, coma). To prevent this: hang D10W at the SAME RATE as the TPN to provide a glucose source that maintains blood glucose levels until the new TPN bag is available. The RN must: (1) never abruptly stop TPN, (2) taper TPN rate gradually when discontinuing (reduce by 50% for 1-2 hours before stopping), (3) monitor blood glucose frequently during transitions, (4) use D10W as a bridge solution. Normal saline (B) does not contain glucose and would not prevent hypoglycemia. Peripheral IV (C) may work but central line should be maintained for the TPN restart. Additional TPN nursing considerations: check blood glucose every 4-6 hours, do not exceed 1.2-1.5 g/kg/day of lipids, use 1.2 micron filter for solutions with lipids, change tubing every 24 hours, and never piggyback other medications into the TPN line.",
      cp: "TPN interrupted: hang D10W at same rate to prevent rebound hypoglycemia; never abruptly stop TPN", tags: ["nutrition","TPN","hypoglycemia","central-line","dextrose"] },
    { t: "Hematology", s: "Blood Typing", stem: "An RN is preparing to administer emergency O-negative packed red blood cells to a patient with massive hemorrhage. Why is O-negative blood used in emergency transfusion situations?",
      correct: "Type O blood lacks A and B antigens on the red blood cells, and Rh-negative blood lacks the D antigen, making it compatible with recipients of all blood types (universal donor) without risk of ABO or Rh hemolytic reactions",
      w1: "Type O-negative blood contains all antigens, making it compatible with any recipient",
      w2: "O-negative blood is the most common blood type, making it readily available in large quantities",
      w3: "All blood types are equally safe for emergency transfusion and O-negative is simply a preference",
      rat: "Blood typing and transfusion compatibility is based on the ABO and Rh antigen-antibody system. Type O blood has NO A or B antigens on the RBC surface, so there are no antigens to trigger an antibody-mediated hemolytic reaction in any recipient. Rh-negative means the D antigen is absent, preventing Rh-mediated reactions. This makes O-negative the 'universal DONOR' for RBCs. Conversely, Type AB-positive is the 'universal RECIPIENT' because these individuals have no antibodies against A, B, or Rh antigens. ABO compatibility is critical because ABO antibodies are naturally occurring IgM antibodies that cause rapid, severe intravascular hemolysis (complement activation leading to RBC lysis, DIC, renal failure, and death). Before any transfusion, the nurse must: (1) verify the blood type and crossmatch with two registered nurses, (2) check the patient's identification band against the blood product label, (3) verify blood type, Rh factor, unit number, and expiration date, (4) begin the transfusion slowly (first 15 minutes at 2 mL/min) while monitoring for reactions. O-negative blood is actually RARE (~7% of population), which is why it's reserved for emergencies.",
      cp: "O-negative = universal donor (no A, B, or Rh antigens); AB-positive = universal recipient (no ABO antibodies); verify 2-nurse check before every transfusion", tags: ["hematology","blood-typing","transfusion","O-negative","universal-donor"] },
    { t: "Legal & Ethics", s: "HIPAA Compliance", stem: "An RN is discussing a patient's care with an interdisciplinary team member in the elevator. Another hospital visitor overhears the conversation. Which violation has occurred?",
      correct: "A HIPAA (Health Insurance Portability and Accountability Act) violation: discussing protected health information (PHI) in a public area where unauthorized persons can overhear compromises patient confidentiality",
      w1: "No violation occurred because healthcare workers are allowed to discuss patient care anywhere in the hospital",
      w2: "The violation only occurs if the RN mentions the patient's full legal name and social security number",
      w3: "This is a HIPAA violation only if the visitor records the conversation on their phone",
      rat: "HIPAA's Privacy Rule protects all individually identifiable health information (protected health information/PHI), which includes: name, date of birth, medical record number, diagnosis, treatment plan, prognosis, and any other information that could reasonably identify a patient. Discussing PHI in PUBLIC AREAS (elevators, hallways, cafeterias, waiting rooms) where unauthorized persons can overhear constitutes a breach of confidentiality. Healthcare workers may discuss patient care with appropriate team members but must do so in PRIVATE settings where conversations cannot be overheard. The 'minimum necessary' standard requires limiting PHI disclosure to the minimum amount needed for the intended purpose. Violations can result in: civil penalties ($100-$50,000 per violation, up to $1.5 million per year), criminal penalties (fines up to $250,000 and imprisonment up to 10 years for intentional violations), professional discipline, and employment termination. The violation occurs at the point of unauthorized disclosure, regardless of whether the listener records it, knows the patient, or takes any further action.",
      cp: "HIPAA: never discuss PHI in public areas (elevators, hallways, cafeterias); use private spaces for patient-related conversations", tags: ["HIPAA","confidentiality","privacy","legal","patient-rights"] },
    { t: "Leadership", s: "Quality Metrics", stem: "An RN is leading a unit-based quality improvement project. The nurse-sensitive indicator being tracked shows that the unit's hospital-acquired pressure injury (HAPI) rate has increased from 2% to 5% over the past quarter. Which quality improvement action should the RN take FIRST?",
      correct: "Conduct a root cause analysis to identify contributing factors (staffing, turning compliance, skin assessment accuracy, nutrition screening, equipment availability), then develop and implement targeted interventions based on the findings",
      w1: "Blame individual nurses for the increase and issue written warnings to all staff",
      w2: "Accept the increase as inevitable and adjust the target metric upward",
      w3: "Implement all possible interventions simultaneously without analyzing the cause",
      rat: "Quality improvement (QI) follows a systematic, evidence-based approach. Nurse-sensitive indicators are patient outcomes directly affected by nursing care, including: fall rates, HAPI rates, CAUTI rates, CLABSI rates, and patient satisfaction. When a nurse-sensitive indicator worsens, the QI process includes: (1) DATA ANALYSIS: examine the trend, identify patterns (which shifts, which units, which patient populations), and quantify the problem; (2) ROOT CAUSE ANALYSIS (RCA): investigate contributing factors systematically using tools like fishbone (Ishikawa) diagrams, the '5 Whys' technique, or process mapping; potential factors include: inadequate staffing levels, non-compliance with turning schedules, inaccurate skin assessments, poor nutritional screening, unavailable pressure redistribution equipment, and insufficient patient education; (3) DEVELOP TARGETED INTERVENTIONS based on identified root causes; (4) IMPLEMENT using Plan-Do-Study-Act (PDSA) cycles; (5) MEASURE outcomes and sustain improvements. Blaming individuals (A) creates a punitive culture that discourages error reporting. Raising the target (B) accepts substandard care. Implementing everything at once (C) wastes resources and makes it impossible to determine which interventions are effective.",
      cp: "QI approach: analyze data → root cause analysis → targeted interventions → PDSA cycle → measure outcomes; never blame individuals", tags: ["quality-improvement","HAPI","nurse-sensitive-indicators","root-cause-analysis","PDSA"] },
    { t: "Psychiatric Nursing", s: "Bipolar Disorder", stem: "An RN is caring for a patient experiencing a manic episode of bipolar I disorder. The patient is talking rapidly, has not slept in 3 days, spent $15,000 on shopping sprees, and is displaying grandiosity. Which nursing intervention is the HIGHEST priority?",
      correct: "Ensure the patient's physical safety (adequate nutrition, hydration, rest), reduce environmental stimulation, set firm consistent limits on behavior, administer prescribed mood stabilizer (lithium) and antipsychotic medications, and monitor for escalation to violence",
      w1: "Encourage the patient to express their creative energy through group activities and socializing",
      w2: "Confront the patient about their excessive spending and demand they return all purchases",
      w3: "Place the patient in a stimulating environment with bright lights and television to channel their energy",
      rat: "A manic episode is characterized by an abnormally elevated, expansive, or irritable mood lasting at least 7 days with at least 3 additional symptoms (DIG FAST: Distractibility, Insomnia/decreased need for sleep, Grandiosity, Flight of ideas, Activity increase, Speech pressured, Thoughtlessness/risk-taking). PHYSICAL SAFETY is the highest priority because manic patients: don't eat/drink adequately (too distracted, too busy), don't sleep (3 days without sleep causes significant physiological and cognitive impairment), engage in risky behaviors (spending sprees, sexual indiscretions, dangerous activities), and may become agitated or violent when limits are set. Nursing interventions: REDUCE STIMULATION (quiet, low-stimulus environment; avoid group activities that increase excitement); SET FIRM LIMITS consistently (not punitively); OFFER high-calorie finger foods and fluids (patients cannot sit still for meals); ENSURE rest periods; ADMINISTER MEDICATIONS (lithium requires serum levels of 0.6-1.2 mEq/L for maintenance; therapeutic index is narrow; toxicity occurs >1.5 mEq/L; monitor sodium intake and hydration as dehydration increases lithium levels); MONITOR for escalation. Confrontation (B) and stimulating environments (C) increase agitation and potential violence.",
      cp: "Mania priorities: safety (nutrition, hydration, rest), reduce stimulation, set limits, lithium levels 0.6-1.2; avoid confrontation and stimulation", tags: ["psychiatric","bipolar","mania","lithium","safety","mood-stabilizer"] },
    { t: "Immunology", s: "Anaphylaxis Management", stem: "An RN is caring for a patient who develops anaphylaxis after receiving an IV antibiotic. The patient has facial swelling, wheezing, stridor, urticaria, and hypotension (BP 72/40). What is the FIRST medication the RN should administer?",
      correct: "Epinephrine 0.3-0.5 mg intramuscularly (IM) in the anterolateral thigh; epinephrine is the FIRST-LINE treatment for anaphylaxis as it reverses bronchospasm, reduces mucosal edema, supports blood pressure, and inhibits further mediator release from mast cells",
      w1: "Diphenhydramine (Benadryl) 50 mg IV as the primary treatment",
      w2: "Methylprednisolone (Solu-Medrol) 125 mg IV to reduce the allergic response",
      w3: "Albuterol nebulizer treatment to address the wheezing first",
      rat: "Anaphylaxis is a severe, life-threatening systemic allergic reaction requiring IMMEDIATE intervention. EPINEPHRINE is the FIRST and MOST IMPORTANT medication: it acts on multiple receptors: alpha-1 (vasoconstriction, increases BP, reduces mucosal edema), beta-1 (increases heart rate and contractility), and beta-2 (bronchodilation). It also stabilizes mast cell membranes, preventing further histamine and mediator release. DOSE: 0.3-0.5 mg IM (adults) in the ANTEROLATERAL THIGH (vastus lateralis) - IM absorption is faster and more reliable than subcutaneous. Can repeat every 5-15 minutes if no improvement. Delay in epinephrine administration is the most common factor contributing to anaphylaxis fatalities. ADJUNCT medications (given AFTER epinephrine): diphenhydramine (H1 blocker, helps with urticaria/itching), ranitidine (H2 blocker), methylprednisolone (prevents biphasic reaction, takes 4-6 hours for effect), albuterol (persistent bronchospasm), IV fluids (for hypotension). The RN must also: stop the offending agent, maintain airway, position patient supine with legs elevated, and prepare for possible intubation.",
      cp: "Anaphylaxis: EPINEPHRINE FIRST (IM, 0.3-0.5 mg, anterolateral thigh); then antihistamines, steroids, fluids; never delay epinephrine for other medications", tags: ["anaphylaxis","epinephrine","allergy","emergency","immunology"] },
  ];

  for (const rr of rnTopics) {
    qs.push(rn(rr.t, rr.s, "Physiological Integrity", 4, rr.stem,
      [O("A", rr.w1), O("B", rr.correct), O("C", rr.w2), O("D", rr.w3)],
      ["B"], rr.rat, rr.cp, rr.tags));
  }

  return qs;
}

async function main() {
  console.log("=== Final Question Bank Batch ===\n");
  const before = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("BEFORE:"); for (const r of before.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs = buildAll();
  const bk: Record<string,number> = {};
  for (const q of allQs) bk[q.exam] = (bk[q.exam] || 0) + 1;
  console.log(`\nGenerated ${allQs.length} total:`, bk);

  let ins = 0, dup = 0, err = 0;
  for (const q of allQs) {
    const h = sh(q.stem);
    try {
      const ex = await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`, [h, q.tier, q.exam]);
      if (ex.rows.length > 0) { dup++; continue; }
      await pool.query(
        `INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at)
         VALUES (gen_random_uuid(),$1,$2,$3,'published',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,'nursing',NOW(),NOW())`,
        [q.tier,q.exam,q.qt,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,q.es,q.ct,JSON.stringify(q.dr)]);
      ins++;
    } catch (e: any) { err++; console.error(`ERR: ${e.message.substring(0,100)}`); }
  }
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);

  const after = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("\nAFTER:"); for (const r of after.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  await pool.end();
  console.log("\n=== Done! ===");
}

main().catch(e => { console.error("Fatal:", e); process.exit(1); });
