import crypto from "crypto";
import pg from "pg";

const pool = new pg.Pool({ host: process.env.PGHOST || "helium", user: process.env.PGUSER || "postgres", password: process.env.PGPASSWORD || "password", database: process.env.PGDATABASE || "heliumdb", ssl: false });
function sh(t: string): string { return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16); }
const O = (l: string, t: string) => ({ label: l, text: t });

interface Q { tier:string; exam:string; stem:string; options:{label:string;text:string}[]; ca:string[]; rat:string; diff:number; tags:string[]; topic:string; sub:string; rs:string; cp:string; bs:string; }

function build(): Q[] {
  const qs: Q[] = [];
  const pn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // ========== NCLEX-PN - Large batch ==========

  pn("Physiological Integrity","Diabetes Type Comparison","Physiological Integrity",2,
    "An LPN is caring for a newly diagnosed diabetic patient. Which characteristic differentiates type 1 diabetes from type 2 diabetes?",
    [O("A","Type 1 diabetes is managed with diet and exercise alone"), O("B","Type 1 diabetes results from autoimmune destruction of pancreatic beta cells causing absolute insulin deficiency, requiring lifelong exogenous insulin; type 2 diabetes involves insulin resistance with relative insulin deficiency and may be managed initially with lifestyle changes and oral medications"), O("C","Type 2 diabetes only affects children and adolescents"), O("D","Type 1 and type 2 diabetes are the same disease with identical management")],
    ["B"],
    "Type 1 DM: autoimmune destruction of beta cells → absolute insulin deficiency → requires insulin from diagnosis. Typically young onset but can occur at any age. Presents acutely with polydipsia, polyuria, polyphagia, weight loss, and potentially DKA. Type 2 DM: progressive insulin resistance and relative insulin deficiency. Risk factors: obesity, sedentary lifestyle, family history, age >45, ethnic predisposition. Often asymptomatic initially. Managed with lifestyle, metformin first-line, then additional oral agents or injectable GLP-1 agonists, eventually insulin if needed.",
    "Type 1: autoimmune, absolute insulin deficiency, requires insulin always; Type 2: insulin resistance, lifestyle + oral agents first", ["diabetes","type-1","type-2","insulin","comparison"]);

  pn("Physiological Integrity","Post-Op Leg Assessment","Physiological Integrity",2,
    "An LPN is assessing the lower extremities of a postoperative patient for signs of deep vein thrombosis (DVT). Which assessment finding is MOST suggestive of DVT?",
    [O("A","Bilateral edema with no pain or color changes"), O("B","Unilateral calf swelling, warmth, redness, and pain with dorsiflexion of the foot (positive Homans' sign); the affected extremity may have a circumference >3 cm larger than the unaffected leg"), O("C","Cool, pale extremity with absent dorsalis pedis pulse"), O("D","Bilateral numbness and tingling in both feet")],
    ["B"],
    "DVT most commonly occurs in the deep veins of the lower extremities (iliac, femoral, popliteal veins). Classic findings include: UNILATERAL leg swelling (the most specific finding; measure calf circumference bilaterally - >3 cm difference is significant), WARMTH and REDNESS over the affected vein, PAIN or tenderness (especially in the calf), positive HOMANS' SIGN (pain with passive dorsiflexion - though this has low sensitivity and specificity). Diagnosis: D-dimer blood test (highly sensitive but not specific; negative D-dimer effectively rules out DVT), compression ultrasound (gold standard). Risk factors (Virchow's triad): venous STASIS (immobility, surgery, long flights), HYPERCOAGULABILITY (pregnancy, cancer, OCP use, genetic disorders), and ENDOTHELIAL INJURY (surgery, trauma). Prevention: early ambulation, sequential compression devices (SCDs), anticoagulant prophylaxis (enoxaparin, heparin).",
    "DVT: unilateral swelling >3cm difference, warmth, redness, calf pain; Virchow's triad: stasis + hypercoagulability + endothelial injury", ["DVT","deep-vein-thrombosis","post-operative","assessment","Virchow"]);

  pn("Physiological Integrity","Heart Sound Murmurs","Physiological Integrity",3,
    "An LPN auscultates a grade III/VI systolic murmur at the aortic area (right second intercostal space) in a 72-year-old patient. What condition should the LPN suspect?",
    [O("A","Normal heart sounds in an elderly patient requiring no further evaluation"), O("B","Aortic stenosis: the most common valvular heart disease in the elderly; the systolic murmur occurs when the left ventricle ejects blood through the narrowed, calcified aortic valve during systole"), O("C","Mitral regurgitation heard best at the apex"), O("D","Pericardial friction rub from pericarditis")],
    ["B"],
    "Aortic stenosis (AS) is the most common valvular heart disease in the elderly (calcific/degenerative AS), with a prevalence of 2-7% in adults >65 years. The SYSTOLIC MURMUR of AS is: heard BEST at the RIGHT SECOND INTERCOSTAL SPACE (aortic area), has a crescendo-decrescendo pattern, radiates to the carotid arteries, and results from turbulent blood flow through the stenotic (narrowed, calcified) valve during ventricular ejection. Grading: I/VI (barely audible) to VI/VI (heard without stethoscope). A grade III/VI is moderately loud. Symptoms (classic triad): Syncope (reduced cerebral perfusion), Angina (increased oxygen demand from ventricular hypertrophy), Dyspnea/heart failure (volume overload). Once symptoms develop, prognosis without treatment is poor. Treatment: surgical aortic valve replacement (SAVR) or transcatheter aortic valve replacement (TAVR) for high-risk surgical candidates.",
    "Aortic stenosis: systolic murmur at right 2nd ICS, radiates to carotids; most common valve disease in elderly; symptoms: syncope, angina, dyspnea", ["cardiac","aortic-stenosis","murmur","valvular","geriatric"]);

  pn("Physiological Integrity","Parkinson Disease","Physiological Integrity",2,
    "An LPN is caring for a patient with Parkinson disease. Which assessment finding is characteristic of this condition?",
    [O("A","Intentional tremor that occurs only during purposeful movement"), O("B","Resting tremor (pill-rolling tremor that is worse at rest and improves with voluntary movement), bradykinesia (slowness of movement), rigidity (cogwheel or lead-pipe), and postural instability (shuffling gait with forward-leaning posture)"), O("C","Sudden onset of weakness on one side of the body with slurred speech"), O("D","Ascending muscle weakness starting in the feet and progressing upward")],
    ["B"],
    "Parkinson disease (PD) is a progressive neurodegenerative disorder caused by loss of dopamine-producing neurons in the substantia nigra of the basal ganglia. The four CARDINAL motor symptoms are: (1) RESTING TREMOR (the hallmark - 'pill-rolling' tremor at 4-6 Hz, worst at rest, decreases with purposeful movement; this distinguishes it from cerebellar intention tremor which is WORSE during movement), (2) BRADYKINESIA (slowness and poverty of voluntary movement - difficulty initiating movement, reduced arm swing, masked face/hypomimia, micrographia/small handwriting), (3) RIGIDITY (increased muscle tone: cogwheel rigidity = ratchet-like resistance; lead-pipe rigidity = constant resistance throughout range of motion), (4) POSTURAL INSTABILITY (loss of postural reflexes, stooped posture, festinating gait - small shuffling steps that accelerate involuntarily, difficulty stopping once in motion). Treatment: carbidopa-levodopa (Sinemet) is the gold standard - levodopa is converted to dopamine in the brain; carbidopa prevents peripheral conversion.",
    "Parkinson's cardinal signs: TRAP = Tremor (resting), Rigidity, Akinesia/bradykinesia, Postural instability; treatment: carbidopa-levodopa", ["Parkinson","tremor","bradykinesia","rigidity","neurodegenerative"]);

  pn("Physiological Integrity","Thyroid Assessment","Physiological Integrity",2,
    "An LPN is assessing a patient who presents with fatigue, weight gain, cold intolerance, constipation, dry skin, and bradycardia. These findings are MOST consistent with which condition?",
    [O("A","Hyperthyroidism/Graves disease with hypermetabolic symptoms"), O("B","Hypothyroidism: deficiency of thyroid hormones causing a hypometabolic state; all body processes slow down, leading to the classic cluster of fatigue, weight gain, cold intolerance, constipation, dry skin, bradycardia, and mental sluggishness"), O("C","Addison disease causing adrenal insufficiency"), O("D","Type 1 diabetes mellitus")],
    ["B"],
    "Hypothyroidism results from insufficient thyroid hormone (T3 and T4) production, causing a HYPOMETABOLIC state where all body processes slow down. Assessment findings mirror the 'slowing' of each body system: METABOLISM (fatigue, weight gain, cold intolerance), CARDIAC (bradycardia, hypotension), GI (constipation, decreased appetite), INTEGUMENTARY (dry skin, brittle nails, hair loss, periorbital edema, myxedema), NEUROLOGICAL (mental sluggishness, depression, slow speech, delayed deep tendon reflexes), REPRODUCTIVE (menorrhagia, decreased libido), MUSCULOSKELETAL (muscle cramps, weakness). Labs show: elevated TSH (primary hypothyroidism - the pituitary produces more TSH trying to stimulate the failing thyroid), decreased free T4. Treatment: levothyroxine (Synthroid) taken on an empty stomach in the morning, at least 30-60 minutes before eating. This is the OPPOSITE clinical picture from HYPERthyroidism (Graves disease): tachycardia, weight LOSS, heat intolerance, diarrhea, warm moist skin, anxiety, tremor.",
    "Hypothyroidism: everything SLOWS (metabolism, heart rate, GI, cognition); high TSH, low T4; treatment: levothyroxine on empty stomach AM", ["hypothyroidism","thyroid","assessment","levothyroxine","hypometabolic"]);

  pn("Physiological Integrity","Liver Cirrhosis","Physiological Integrity",3,
    "An LPN is assessing a patient with liver cirrhosis who has distended superficial abdominal veins (caput medusae), splenomegaly, and esophageal varices. Which pathophysiological mechanism is responsible for these findings?",
    [O("A","Left-sided heart failure causing pulmonary congestion"), O("B","Portal hypertension: increased pressure in the portal venous system from cirrhotic liver scarring obstructing blood flow through the liver; blood is diverted through collateral circulation creating varices (esophageal, rectal hemorrhoids, caput medusae) and causing splenomegaly from splenic vein congestion"), O("C","Renal failure causing fluid overload and ascites"), O("D","Pulmonary embolism causing right heart strain")],
    ["B"],
    "Portal hypertension is a major complication of liver cirrhosis. The normal portal venous pressure is 5-10 mmHg; in portal hypertension it exceeds 10 mmHg. MECHANISM: scarred (fibrotic) liver tissue obstructs portal blood flow → increased pressure in the portal vein → blood seeks alternative (collateral) routes to return to the heart → PORTOSYSTEMIC ANASTOMOSES develop at several sites. CLINICAL MANIFESTATIONS: (1) ESOPHAGEAL VARICES (dilated submucosal veins in the esophagus - the most dangerous complication as rupture causes massive, life-threatening upper GI hemorrhage), (2) CAPUT MEDUSAE (dilated periumbilical veins visible on the abdominal wall), (3) HEMORRHOIDS (dilated rectal veins), (4) SPLENOMEGALY (splenic vein congestion causes enlarged spleen, which sequesters platelets causing thrombocytopenia), (5) ASCITES (increased portal pressure + decreased albumin production → fluid accumulation in peritoneal cavity). Treatment includes: beta-blockers (propranolol) to reduce portal pressure, endoscopic band ligation for varices, diuretics (spironolactone + furosemide) for ascites, paracentesis for tense ascites, and TIPS procedure (transjugular intrahepatic portosystemic shunt) for refractory cases.",
    "Portal hypertension: cirrhosis blocks portal flow → collateral circulation (esophageal varices, caput medusae, hemorrhoids) + splenomegaly + ascites", ["cirrhosis","portal-hypertension","varices","splenomegaly","liver"]);

  pn("Physiological Integrity","Fracture Types","Physiological Integrity",2,
    "An LPN is assessing a patient who fell and now has an open wound over the fracture site with bone visible through the skin. What type of fracture is this?",
    [O("A","Closed (simple) fracture with intact skin"), O("B","Open (compound) fracture: the bone has broken through the skin or a wound communicates with the fracture site, creating a HIGH risk of infection including osteomyelitis; this is an ORTHOPEDIC EMERGENCY requiring immediate irrigation, debridement, antibiotics, and surgical fixation"), O("C","Greenstick fracture common in children"), O("D","Stress fracture from repetitive activity")],
    ["B"],
    "An OPEN (compound) fracture is defined by communication between the fracture site and the external environment through a break in the skin. The bone may or may not be visible. Classification (Gustilo-Anderson): Type I (wound <1 cm, minimal soft tissue damage), Type II (wound 1-10 cm, moderate damage), Type III (wound >10 cm, severe damage, possible vascular injury). NURSING PRIORITIES: (1) Control bleeding with direct pressure and sterile dressing over the wound (do NOT attempt to push bone fragments back through the skin), (2) Immobilize the extremity in the position found, (3) Cover with sterile moist dressing, (4) Assess neurovascular status (5 Ps: Pain, Pallor, Pulselessness, Paresthesia, Paralysis), (5) Administer tetanus prophylaxis if indicated, (6) Administer prescribed IV antibiotics (cefazolin ± gentamicin) within 1 hour, (7) Prepare for surgical irrigation and debridement (I&D). The most serious risk is INFECTION (particularly osteomyelitis) because the broken skin allows direct bacterial contamination of the bone and surrounding tissues.",
    "Open fracture: bone breaks through skin = infection risk = emergency; sterile dressing, immobilize, antibiotics within 1hr, surgical I&D", ["fracture","open-compound","orthopedic","emergency","osteomyelitis"]);

  pn("Pharmacological Therapies","Digoxin Monitoring","Physiological Integrity",3,
    "An LPN is preparing to administer digoxin to a patient. The patient's apical pulse is 54 bpm and they report nausea and visual changes (seeing yellow-green halos around lights). What should the LPN do?",
    [O("A","Administer the digoxin since these are expected therapeutic effects"), O("B","HOLD the digoxin dose and notify the RN/physician immediately; the combination of bradycardia (<60 bpm), nausea, and visual disturbances (yellow-green halos) are classic signs of DIGOXIN TOXICITY; a stat serum digoxin level should be drawn (therapeutic range 0.5-2.0 ng/mL)"), O("C","Give a double dose to correct the bradycardia"), O("D","Administer the digoxin but skip the next dose")],
    ["B"],
    "Digoxin is a cardiac glycoside with a narrow therapeutic index (therapeutic level 0.5-2.0 ng/mL; toxicity often occurs >2.0 ng/mL, but can occur at lower levels especially in elderly and hypokalemic patients). BEFORE EACH DOSE: take the APICAL pulse for a FULL 60 SECONDS; HOLD if HR <60 bpm in adults (<70 in children, <90 in infants) and notify the physician. SIGNS OF DIGOXIN TOXICITY: CARDIAC (the most dangerous): bradycardia, any dysrhythmia (especially PVCs, bigeminy, heart block, atrial tachycardia with block), GI: nausea, vomiting, anorexia (often the FIRST signs), NEUROLOGICAL: visual changes (yellow-green halos around lights - the classic visual disturbance, also blurred vision, photophobia), fatigue, confusion. RISK FACTORS for toxicity: HYPOKALEMIA (the most important - low potassium increases digoxin binding to cardiac Na+/K+-ATPase pump), renal impairment (digoxin is renally excreted), drug interactions (amiodarone, verapamil, quinidine increase digoxin levels), hypothyroidism, and elderly age. TREATMENT of severe toxicity: digoxin immune Fab (Digibind).",
    "Digoxin: check apical pulse 60 seconds, hold if <60; toxicity signs: bradycardia + GI symptoms + yellow-green halos; monitor K+ (hypokalemia increases toxicity risk)", ["digoxin","toxicity","bradycardia","visual-changes","narrow-therapeutic-index"]);

  pn("Safe & Effective Care Environment","Restraint Alternatives","Safe & Effective Care Environment",2,
    "An LPN is caring for a confused elderly patient who keeps trying to remove their IV line. Before considering restraints, which LEAST RESTRICTIVE intervention should the LPN try FIRST?",
    [O("A","Apply bilateral wrist restraints immediately without trying alternatives"), O("B","Conceal the IV tubing under clothing or a sleeve, redirect the patient's attention, have a family member or sitter present, ensure adequate pain management, and address potential causes of confusion (delirium workup including infection, medications, metabolic causes)"), O("C","Sedate the patient heavily so they cannot move"), O("D","Remove the IV line entirely since the patient does not want it")],
    ["B"],
    "The principle of LEAST RESTRICTIVE intervention requires healthcare providers to exhaust ALL alternatives before applying physical or chemical restraints. Evidence shows restraints increase agitation, injury risk, and psychological trauma. Alternatives include: CONCEALING or CAMOUFLAGING tubes/lines (hiding IV tubing under clothing, using arm boards, moving IV to less accessible site), REDIRECTION (engaging the patient in a familiar activity, providing hand-held objects), PRESENCE (family member, volunteer, sitter at bedside), ENVIRONMENTAL MODIFICATION (reducing stimulation, providing familiar objects, orientation cues, adequate lighting), ADDRESSING UNDERLYING CAUSES (delirium evaluation - is confusion caused by infection, medication, pain, constipation, urinary retention, hypoxia, electrolyte imbalance?), PAIN MANAGEMENT (uncontrolled pain can cause agitation), and THERAPEUTIC COMMUNICATION. If restraints are truly necessary after all alternatives fail, they require a physician's order, least restrictive type for shortest duration, assessment every 1-2 hours, release every 2 hours, and ongoing reassessment of continued need.",
    "Least restrictive first: conceal tubes, redirect, sitter, address causes of confusion; restraints only as LAST resort after all alternatives exhausted", ["restraint-alternatives","least-restrictive","delirium","patient-safety","elderly"]);

  // ========== NCLEX-RN Large batch ==========

  rn("Critical Care","Hemodynamic Monitoring","Physiological Integrity",4,
    "An RN is interpreting pulmonary artery catheter (Swan-Ganz) readings. The patient has a pulmonary artery wedge pressure (PAWP) of 22 mmHg (normal 6-12 mmHg). What does this elevated PAWP indicate?",
    [O("A","Right ventricular failure with systemic congestion"), O("B","Left ventricular failure with elevated left atrial pressure causing pulmonary congestion; PAWP reflects left ventricular end-diastolic pressure and an elevated reading indicates the left ventricle is not effectively pumping, causing blood to back up into the pulmonary vasculature"), O("C","Pulmonary embolism obstructing pulmonary blood flow"), O("D","Normal hemodynamic values requiring no intervention")],
    ["B"],
    "The pulmonary artery wedge pressure (PAWP), also called pulmonary capillary wedge pressure (PCWP), is measured by inflating a balloon at the tip of the Swan-Ganz catheter in a pulmonary artery branch. This 'wedges' the catheter and measures the pressure transmitted backward from the LEFT ATRIUM and LEFT VENTRICLE through the pulmonary vasculature. PAWP serves as an indirect measurement of LEFT VENTRICULAR END-DIASTOLIC PRESSURE (preload). Normal PAWP: 6-12 mmHg. ELEVATED PAWP (>18-20 mmHg): indicates LEFT-sided heart failure, fluid overload, or mitral valve disease. The elevated pressure causes pulmonary congestion (crackles, dyspnea, pulmonary edema when PAWP >20-25 mmHg). Treatment: diuretics, vasodilators, inotropes. DECREASED PAWP (<4-6 mmHg): indicates hypovolemia or decreased preload. Treatment: IV fluid resuscitation. Other Swan-Ganz measurements: CVP/RAP (right preload, normal 2-6 mmHg), PA systolic/diastolic (25/10 mmHg), cardiac output (4-8 L/min), SVR (800-1200 dynes/sec/cm-5).",
    "PAWP reflects left heart preload: elevated = LV failure/fluid overload (pulmonary congestion); decreased = hypovolemia; normal 6-12 mmHg", ["hemodynamics","Swan-Ganz","PAWP","left-heart-failure","critical-care"]);

  rn("Emergency","Triage Categories","Safe & Effective Care Environment",3,
    "An RN working in the emergency department is using the Emergency Severity Index (ESI) triage system. Four patients arrive simultaneously. Which patient should be seen FIRST?",
    [O("A","A 45-year-old with a sprained ankle who is ambulatory and has stable vital signs"), O("B","A 62-year-old with sudden onset chest pain radiating to the left arm, diaphoresis, and nausea; SpO2 94%, HR 110, BP 90/60"), O("C","A 22-year-old with a sore throat and low-grade fever for 2 days"), O("D","A 35-year-old with a small laceration on the forearm that has stopped bleeding")],
    ["B"],
    "The Emergency Severity Index (ESI) is a 5-level triage system: ESI-1 (Immediate/life-threatening): requires immediate intervention to save life (cardiac arrest, active hemorrhage, respiratory failure). ESI-2 (Emergent): high risk of deterioration, acute onset, time-sensitive condition (chest pain with hemodynamic instability, stroke symptoms, severe sepsis). ESI-3 (Urgent): stable but needs multiple resources (moderate abdominal pain, fractures). ESI-4 (Less urgent): needs one resource (simple laceration, urinalysis). ESI-5 (Non-urgent): needs no resources (prescription refill, minor complaint). This patient with CHEST PAIN + radiation + diaphoresis + nausea + HYPOTENSION + TACHYCARDIA is ESI-2 and likely having an acute myocardial infarction (STEMI) with hemodynamic compromise. The mnemonic MONA (Morphine, Oxygen, Nitroglycerin, Aspirin) guides initial treatment, though aspirin 325 mg is the FIRST medication. CAUTION: with BP 90/60, nitroglycerin is CONTRAINDICATED (would worsen hypotension).",
    "Triage priority: chest pain + hemodynamic instability = ESI-2 (emergent); assess for STEMI; aspirin first but hold NTG if hypotensive", ["triage","ESI","chest-pain","STEMI","emergency"]);

  rn("Pharmacology","Anticoagulant Comparison","Physiological Integrity",3,
    "An RN is educating a patient about the differences between warfarin and direct oral anticoagulants (DOACs) such as apixaban (Eliquis). Which statement is CORRECT?",
    [O("A","Warfarin and DOACs have identical monitoring requirements and dietary restrictions"), O("B","DOACs (apixaban, rivarelbán, dabigatran) have predictable pharmacokinetics requiring no routine INR monitoring, fewer dietary restrictions (no vitamin K concerns), rapid onset of action (hours vs days for warfarin), and fixed dosing; however, they are more expensive and some have limited reversal agents"), O("C","Warfarin works within 30 minutes while DOACs take weeks to become effective"), O("D","DOACs are always safer than warfarin with zero bleeding risk")],
    ["B"],
    "Warfarin vs DOACs comparison: WARFARIN: mechanism = vitamin K antagonist (inhibits synthesis of factors II, VII, IX, X); onset = 3-5 days for full effect (requires bridging with heparin); monitoring = frequent INR checks (target 2-3); interactions = numerous food (vitamin K) and drug interactions; reversal = vitamin K + PCC/FFP; cost = inexpensive. DOACs: mechanism = direct factor Xa inhibitors (apixaban/Eliquis, rivarelbán/Xarelto, edoxaban/Savaysa) or direct thrombin inhibitor (dabigatran/Pradaxa); onset = 1-4 hours; monitoring = NO routine coagulation monitoring needed; interactions = fewer dietary/drug interactions; reversal = andexanet alfa for factor Xa inhibitors, idarucizumab for dabigatran; cost = significantly more expensive. DOACs are preferred for non-valvular atrial fibrillation, DVT/PE treatment and prevention. Warfarin is STILL preferred for mechanical heart valves, severe mitral stenosis, and antiphospholipid syndrome.",
    "DOACs: no INR monitoring, fewer interactions, rapid onset, fixed dosing; Warfarin: still preferred for mechanical valves; both carry bleeding risk", ["anticoagulant","warfarin","DOAC","apixaban","comparison"]);

  rn("Maternity","Postpartum Hemorrhage","Physiological Integrity",4,
    "An RN identifies that a postpartum patient is experiencing hemorrhage (estimated blood loss >500 mL for vaginal delivery). The uterus feels soft and boggy on palpation. What is the MOST likely cause and the FIRST intervention?",
    [O("A","Retained placental fragments requiring immediate hysterectomy"), O("B","Uterine atony (the most common cause of postpartum hemorrhage, responsible for 70-80% of cases): the FIRST intervention is bimanual uterine massage (fundal massage) to stimulate uterine contraction, while simultaneously administering prescribed uterotonic medications (oxytocin, methylergonovine, carboprost, misoprostol)"), O("C","Cervical laceration requiring suturing only"), O("D","Coagulopathy requiring only blood transfusion without addressing the uterine tone")],
    ["B"],
    "Postpartum hemorrhage (PPH) is defined as blood loss ≥500 mL after vaginal delivery or ≥1000 mL after cesarean section. The '4 Ts' of PPH etiology: TONE (uterine atony - 70-80% of cases, the most common cause), TRAUMA (lacerations, hematomas - 20%), TISSUE (retained placenta/membranes - 10%), THROMBIN (coagulopathy - 1%). For uterine atony: the FIRST intervention is bimanual FUNDAL MASSAGE (place one hand on the fundus abdominally and the other hand in the vagina cupped against the lower uterine segment, massage firmly to stimulate myometrial contraction). Simultaneously: UTEROTONIC MEDICATIONS: oxytocin (Pitocin) 10-40 units IV infusion, methylergonovine (Methergine) 0.2 mg IM (CONTRAINDICATED in hypertension), carboprost (Hemabate) 0.25 mg IM (CONTRAINDICATED in asthma), misoprostol (Cytotec) 800-1000 mcg rectally. Additional measures: IV fluid resuscitation, blood products, uterine tamponade (Bakri balloon), and surgical intervention if refractory.",
    "PPH most common cause: uterine atony; FIRST action: fundal massage + uterotonics; 4 Ts: Tone, Trauma, Tissue, Thrombin", ["postpartum-hemorrhage","uterine-atony","fundal-massage","uterotonics","obstetrics"]);

  rn("Pharmacology","Insulin Sick Day Rules","Physiological Integrity",3,
    "An RN is educating a patient with type 1 diabetes about sick day management. The patient asks, 'Should I stop taking my insulin when I'm sick and can't eat?' What is the correct response?",
    [O("A","Yes, stop all insulin when you cannot eat to prevent hypoglycemia"), O("B","NEVER stop basal insulin (glargine/detemir) even when sick and unable to eat; illness typically INCREASES blood glucose due to stress hormones (cortisol, glucagon, epinephrine); check blood glucose every 2-4 hours, check urine or blood ketones, stay hydrated, adjust rapid-acting insulin based on glucose readings, and contact the healthcare provider if glucose >300 mg/dL or ketones are present"), O("C","Take double the usual insulin dose whenever you are sick"), O("D","Only take insulin if your blood glucose is below 100 mg/dL during illness")],
    ["B"],
    "Sick day management for type 1 diabetes is critical to prevent diabetic ketoacidosis (DKA). During illness: (1) NEVER stop basal insulin (the most important rule) - counter-regulatory stress hormones (cortisol, glucagon, growth hormone, catecholamines) released during illness cause significant hyperglycemia and ketogenesis even without food intake; (2) CHECK blood glucose every 2-4 hours; (3) CHECK ketones (blood beta-hydroxybutyrate or urine ketones) every 4-6 hours; (4) STAY HYDRATED (sugar-free fluids if BG >250; glucose-containing fluids if BG <250 and unable to eat); (5) If unable to eat regular meals, consume easy-to-digest carbohydrates (crackers, soup, juice, popsicles) to prevent hypoglycemia; (6) ADJUST rapid-acting insulin based on glucose monitoring; (7) CONTACT healthcare provider if: BG consistently >300 mg/dL, moderate/large ketones, persistent vomiting, severe symptoms, or symptoms lasting >24 hours. DKA can develop within 12-24 hours in type 1 diabetes if insulin is withheld.",
    "Type 1 sick day rules: NEVER stop basal insulin; check BG every 2-4 hrs, check ketones, stay hydrated; illness raises BG even without eating", ["diabetes","sick-day","insulin","DKA-prevention","self-management"]);

  rn("Neurology","Spinal Cord Injury","Physiological Integrity",4,
    "An RN is caring for a patient with a T6 spinal cord injury who develops sudden severe hypertension (BP 220/120), pounding headache, flushing and diaphoresis above the level of injury, and bradycardia. What complication is occurring?",
    [O("A","Spinal shock causing hypotension and bradycardia"), O("B","Autonomic dysreflexia: a life-threatening emergency occurring in spinal cord injuries at T6 or above, triggered by a noxious stimulus below the level of injury (most commonly a distended bladder or impacted bowel) causing an uncontrolled sympathetic response"), O("C","Normal blood pressure fluctuation in spinal cord injured patients"), O("D","Orthostatic hypotension from position change")],
    ["B"],
    "Autonomic dysreflexia (AD) is a MEDICAL EMERGENCY in patients with spinal cord injuries at T6 or ABOVE. PATHOPHYSIOLOGY: a noxious stimulus below the level of injury (distended bladder is the #1 cause, followed by fecal impaction, pressure ulcers, tight clothing, UTI, kinked catheter) triggers a massive SYMPATHETIC response below the injury level that cannot be modulated by the brain (because the descending inhibitory pathways are interrupted by the spinal cord lesion). This causes severe VASOCONSTRICTION below the injury → extreme HYPERTENSION. The baroreceptors above the injury detect the hypertension and attempt to compensate via the VAGUS nerve → BRADYCARDIA, vasodilation above the injury (flushing, sweating, nasal congestion above injury level). If untreated: stroke, seizures, retinal hemorrhage, MI, death. IMMEDIATE TREATMENT: (1) Sit the patient UPRIGHT to lower BP using orthostatic effect, (2) IDENTIFY AND REMOVE the trigger (check bladder first - catheterize or check for kinked catheter; check for fecal impaction; loosen tight clothing), (3) MONITOR BP every 2-5 minutes, (4) Administer prescribed antihypertensives if BP does not respond (nifedipine, hydralazine, nitropaste).",
    "Autonomic dysreflexia: T6 or above, triggered by bladder distension/#1; severe HTN + headache + flushing above injury + bradycardia; sit upright, find/remove trigger", ["spinal-cord-injury","autonomic-dysreflexia","hypertension","emergency","neurology"]);

  rn("Hematology","DIC Assessment","Physiological Integrity",4,
    "An RN is caring for a patient with sepsis who develops oozing from venipuncture sites, petechiae, and prolonged clotting times (PT and aPTT elevated). Labs show: decreased platelets, decreased fibrinogen, and elevated D-dimer. What condition has developed?",
    [O("A","Immune thrombocytopenic purpura (ITP)"), O("B","Disseminated intravascular coagulation (DIC): a paradoxical condition where widespread microvascular thrombosis consumes clotting factors and platelets faster than the body can produce them, leading to simultaneous CLOTTING and BLEEDING"), O("C","Hemophilia A from factor VIII deficiency"), O("D","Vitamin K deficiency from malnutrition")],
    ["B"],
    "DIC is a life-threatening coagulopathy characterized by the paradox of simultaneous clotting AND bleeding. PATHOPHYSIOLOGY: a trigger (sepsis #1 cause, also trauma, obstetric complications, malignancy, transfusion reactions) activates the coagulation cascade systemically → widespread MICROTHROMBI form in small vessels (causing organ damage from ischemia) → this CONSUMES clotting factors (I/fibrinogen, V, VIII), platelets, and natural anticoagulants faster than they can be replaced → CONSUMPTION COAGULOPATHY → generalized BLEEDING (from depleted clotting factors and platelets). LAB FINDINGS: DECREASED platelets (consumed), DECREASED fibrinogen (consumed), PROLONGED PT and aPTT (clotting factors consumed), ELEVATED D-dimer and fibrin degradation products/FDPs (from the massive fibrinolysis breaking down the widespread microthrombi), ELEVATED INR, schistocytes on blood smear (from RBC mechanical shearing through thrombosed microvessels). TREATMENT: treat the UNDERLYING CAUSE (antibiotics for sepsis), replace consumed components (FFP for clotting factors, cryoprecipitate for fibrinogen <100, platelets if <50,000), heparin may be used cautiously in some cases to interrupt the coagulation cascade, and supportive care.",
    "DIC: simultaneous clotting + bleeding; low platelets + low fibrinogen + high PT/aPTT + high D-dimer; treat the underlying cause + replace consumed factors", ["DIC","coagulopathy","sepsis","bleeding","clotting-factors"]);

  // ========== MORE REx-PN ==========

  rpn("Wound Care","Wound Drainage Types","Physiological Integrity",2,
    "An RPN is documenting wound drainage. The drainage is thick, opaque, yellow-green with a foul odour. What type of drainage is this?",
    [O("A","Serous: clear, watery, normal healing"), O("B","Purulent: thick, opaque, yellow-green or tan with foul odour, indicating infection; the RPN should notify the physician, obtain a wound culture as ordered, and document the characteristics of the drainage"), O("C","Sanguineous: bright red, fresh blood"), O("D","Serosanguineous: pale pink, normal early healing")],
    ["B"],
    "Wound drainage types reflect different phases of healing or pathology: SEROUS (clear, watery, straw-colored) - normal in early wound healing; composed of plasma and serous fluid from damaged capillaries. SANGUINEOUS (bright red to dark red) - indicates active bleeding; normal immediately post-surgery but should decrease; persistent sanguineous drainage may indicate hemorrhage. SEROSANGUINEOUS (pale pink, thin) - mixture of serous and sanguineous drainage; normal in wound healing. PURULENT (thick, opaque, yellow/green/tan/brown, often malodorous) - indicates INFECTION; composed of dead WBCs (neutrophils), bacteria, and necrotic tissue (pus); requires wound culture, possible antibiotic therapy, and close monitoring. Documentation should include: TYPE (serous, sanguineous, serosanguineous, purulent), COLOR, CONSISTENCY, AMOUNT (scant, small, moderate, large or measured in mL), ODOUR (none, mild, foul), and any CHANGE from previous assessments.",
    "Drainage types: serous (clear), sanguineous (red/blood), serosanguineous (pink), purulent (thick yellow-green + odour = infection)", ["wound-drainage","purulent","infection","documentation","wound-care"]);

  rpn("Safety","Fire Safety RACE","Safe & Effective Care Environment",2,
    "An RPN smells smoke and discovers a small fire in a supply room. What is the FIRST action according to the RACE fire safety protocol?",
    [O("A","Attempt to extinguish the fire immediately with a fire extinguisher"), O("B","R = RESCUE: remove any patients or personnel from immediate danger in the fire area; then A = ALARM (pull the fire alarm and call 911), C = CONTAIN (close doors and windows to contain fire and smoke), E = EXTINGUISH/EVACUATE (attempt to extinguish with appropriate fire extinguisher or evacuate if unable)"), O("C","Continue working and assume someone else will handle the fire"), O("D","Open all doors and windows to ventilate the smoke")],
    ["B"],
    "The RACE protocol guides the nurse's response to fire emergencies: R = RESCUE: protect patients and remove anyone in IMMEDIATE danger from the fire area; this is always FIRST because human life takes priority over property. A = ALARM: activate the nearest fire alarm pull station AND call the facility emergency number (911 or internal code red number). C = CONTAIN: close all doors and windows to prevent fire and smoke spread (smoke inhalation is the leading cause of death in hospital fires). E = EXTINGUISH/EVACUATE: if the fire is small and you are trained, attempt to extinguish using the PASS technique with the appropriate fire extinguisher (P = Pull the pin, A = Aim at the base of the fire, S = Squeeze the handle, S = Sweep side to side). If the fire cannot be controlled, EVACUATE following the facility's evacuation plan (horizontal evacuation first to the next fire compartment, then vertical evacuation via stairs, NEVER elevators). Fire extinguisher types: Class A (ordinary combustibles), Class B (flammable liquids), Class C (electrical), Class ABC (multipurpose - most common in healthcare).",
    "Fire: RACE (Rescue, Alarm, Contain, Extinguish/Evacuate); PASS for extinguisher (Pull, Aim, Squeeze, Sweep); never use elevators during fire", ["fire-safety","RACE","PASS","emergency","hospital-safety"]);

  rpn("Pharmacology","Metformin Precautions","Physiological Integrity",2,
    "An RPN is caring for a patient with type 2 diabetes who takes metformin (Glucophage). The patient is scheduled for a CT scan with IV contrast dye tomorrow. What precaution is necessary?",
    [O("A","No precautions are needed; metformin is safe with all imaging procedures"), O("B","Metformin should be HELD for 48 hours before and after the contrast dye procedure; the combination of metformin and contrast dye can increase the risk of lactic acidosis, a rare but potentially fatal complication, particularly in patients with renal impairment"), O("C","Double the metformin dose on the day of the CT scan"), O("D","Switch to insulin permanently before the CT scan")],
    ["B"],
    "Metformin and IV contrast dye interaction: IV iodinated contrast agents can cause contrast-induced nephropathy (CIN), temporarily impairing kidney function. Metformin is renally excreted, and if kidney function is impaired by contrast, metformin can accumulate to toxic levels, increasing the risk of LACTIC ACIDOSIS (a serious metabolic emergency with mortality of 30-50%). Current guidelines vary, but common practice: HOLD metformin for 48 hours AFTER contrast administration (some guidelines also recommend holding 48 hours before); VERIFY serum creatinine/eGFR before restarting; ENSURE adequate hydration before and after the procedure to support renal function and contrast clearance; RESTART metformin only when renal function is confirmed stable (eGFR >30 mL/min). Patients at highest risk: elderly, pre-existing renal impairment, heart failure, dehydration, hepatic dysfunction. Other important metformin facts: does NOT cause hypoglycemia as monotherapy, must be held before general anesthesia, GI side effects (nausea, diarrhea) are common initially.",
    "Metformin + IV contrast: hold metformin 48 hrs after procedure; risk of lactic acidosis if renal function impaired; verify creatinine before restarting", ["metformin","contrast-dye","lactic-acidosis","renal-function","diabetes"]);

  rpn("Gerontology","Polypharmacy in Elderly","Safe & Effective Care Environment",2,
    "An RPN is reviewing medications for a 79-year-old patient and identifies that the patient is taking diphenhydramine (Benadryl) for sleep. According to the Beers Criteria, why is this medication potentially inappropriate for this elderly patient?",
    [O("A","Diphenhydramine is safe and appropriate for sleep in all age groups"), O("B","Diphenhydramine is a first-generation antihistamine with strong ANTICHOLINERGIC properties that are particularly dangerous in elderly patients: causes confusion, sedation, urinary retention, constipation, falls, dry mouth, and delirium; the Beers Criteria lists it as potentially inappropriate for adults ≥65 years"), O("C","Diphenhydramine is only dangerous if taken with food"), O("D","The Beers Criteria only applies to inpatient settings, not community-dwelling elderly")],
    ["B"],
    "The Beers Criteria (American Geriatrics Society) is an evidence-based list of potentially inappropriate medications (PIMs) for adults ≥65 years. DIPHENHYDRAMINE (Benadryl) is classified as HIGH RISK due to its strong ANTICHOLINERGIC effects. In elderly patients, anticholinergic medications cause: CONFUSION and COGNITIVE IMPAIRMENT (can precipitate or worsen delirium), excessive SEDATION (increased fall risk), URINARY RETENTION (especially in men with BPH), CONSTIPATION (already common in elderly), DRY MOUTH (impairs nutrition and increases dental caries), BLURRED VISION, TACHYCARDIA. Age-related changes that increase risk: decreased hepatic metabolism, decreased renal clearance, increased blood-brain barrier permeability, reduced cholinergic reserve in the brain, and altered body composition (increased fat-to-water ratio prolongs drug effects). Safer alternatives for insomnia in elderly: sleep hygiene education, cognitive behavioral therapy for insomnia (CBT-I), melatonin (low dose), and addressing underlying causes of insomnia.",
    "Beers Criteria: diphenhydramine inappropriate in elderly (anticholinergic: confusion, falls, urinary retention, constipation, delirium); safer alternatives exist", ["Beers-Criteria","diphenhydramine","anticholinergic","elderly","polypharmacy"]);

  return qs;
}

async function main() {
  console.log("=== Bulk Final Batch ===\n");
  const before = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("BEFORE:"); for (const r of before.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs = build();
  const bk: Record<string,number> = {};
  for (const q of allQs) bk[q.exam] = (bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`, bk);
  let ins=0, dup=0, err=0;
  for (const q of allQs) {
    const h = sh(q.stem);
    try {
      const ex = await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`, [h, q.tier, q.exam]);
      if (ex.rows.length > 0) { dup++; continue; }
      await pool.query(
        `INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at)
         VALUES (gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,
        [q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,
         "Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);
      ins++;
    } catch (e: any) { err++; console.error(`ERR: ${e.message.substring(0,100)}`); }
  }
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("\nAFTER:"); for (const r of after.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session = await pool.query(`SELECT exam, COUNT(*)::int as cnt FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at > NOW() - INTERVAL '10 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:"); for (const r of session.rows) console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}

main().catch(e => { console.error("Fatal:", e); process.exit(1); });
