import crypto from "crypto";
import pg from "pg";

const pool = new pg.Pool({ host: process.env.PGHOST || "helium", user: process.env.PGUSER || "postgres", password: process.env.PGPASSWORD || "password", database: process.env.PGDATABASE || "heliumdb", ssl: false });
function sh(t: string): string { return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16); }
const O = (l: string, t: string) => ({ label: l, text: t });

interface Q { tier:string; exam:string; stem:string; options:{label:string;text:string}[]; ca:string[]; rat:string; diff:number; tags:string[]; topic:string; sub:string; rs:string; cp:string; bs:string; }

function build(): Q[] {
  const qs: Q[] = [];
  const pn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn = (t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[]) => qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // ============ NCLEX-PN - Massive batch ============

  // Pediatric scenarios
  pn("Pediatric","Dehydration Assessment","Physiological Integrity",2,
    "An LPN is assessing a 10-month-old infant brought to the clinic by the parents who report 2 days of vomiting and diarrhea. Which finding indicates MODERATE dehydration?",
    [O("A","Active, playful infant with moist mucous membranes and elastic skin turgor"), O("B","Decreased urine output, sunken fontanelle, dry mucous membranes, decreased skin turgor (tenting), and increased heart rate with normal blood pressure"), O("C","Limp, unresponsive infant with absent tears, very sunken eyes, and no urine output for 8 hours"), O("D","Fever of 37.5°C with normal activity level and normal fontanelle")],
    ["B"],
    "Dehydration assessment in infants uses specific clinical markers: MILD (<5%): slightly decreased urine output, slightly dry mucous membranes, alert and active. MODERATE (5-10%): DECREASED URINE OUTPUT (fewer wet diapers), SUNKEN ANTERIOR FONTANELLE (open in infants <18 months; a reliable dehydration indicator), DRY MUCOUS MEMBRANES, DECREASED SKIN TURGOR (skin tents when pinched and slowly returns to normal), TACHYCARDIA (compensatory mechanism to maintain cardiac output with decreased intravascular volume), sunken eyes, decreased tears. SEVERE (>10%): minimal or absent urine output, markedly sunken fontanelle and eyes, absent tears, very poor skin turgor, lethargy/unconsciousness, hypotension (a LATE sign indicating decompensation), cold mottled extremities.",
    "Moderate dehydration in infants: sunken fontanelle, decreased urine, dry mucous membranes, decreased skin turgor, tachycardia", ["pediatric","dehydration","infant","fontanelle","assessment"]);

  pn("Pediatric","Otitis Media","Physiological Integrity",2,
    "An LPN is caring for a toddler diagnosed with acute otitis media (AOM). The child is pulling at the right ear and is irritable with a fever of 38.9°C. Which intervention is appropriate?",
    [O("A","Irrigate the ear canal with warm water to remove the infection"), O("B","Administer prescribed amoxicillin as ordered, provide age-appropriate antipyretics (acetaminophen or ibuprofen) for fever and pain, and position the child with the affected ear UP (unaffected ear down) to promote drainage"), O("C","Insert cotton balls soaked in alcohol into the ear canal"), O("D","No treatment is needed for otitis media in toddlers; it always resolves without intervention")],
    ["B"],
    "Acute otitis media (AOM) is one of the most common childhood infections. Management includes: ANTIBIOTICS (amoxicillin is first-line for AOM), PAIN MANAGEMENT (acetaminophen or ibuprofen appropriate for age; NEVER aspirin in children due to Reye syndrome risk), POSITIONING with the affected ear UP (this promotes gravity drainage of the middle ear through the eustachian tube and can relieve pressure). Ear irrigation (A) is contraindicated as it can rupture the tympanic membrane. Alcohol in the ear canal (C) is dangerous. While watchful waiting IS appropriate for some cases of AOM in children >6 months with mild symptoms and uncertain diagnosis, this child has clear symptoms warranting treatment.",
    "AOM treatment: amoxicillin first-line, age-appropriate analgesics, position affected ear UP for drainage; never aspirin in children", ["pediatric","otitis-media","ear-infection","amoxicillin","fever"]);

  pn("Pediatric","RSV Bronchiolitis","Physiological Integrity",2,
    "An LPN is caring for a 3-month-old infant admitted with respiratory syncytial virus (RSV) bronchiolitis. Which assessment finding requires IMMEDIATE notification of the RN?",
    [O("A","Mild nasal congestion with clear rhinorrhea"), O("B","Respiratory rate of 72 breaths/min with nasal flaring, intercostal retractions, grunting, and SpO2 of 88%"), O("C","Temperature of 37.8°C with mild cough"), O("D","The infant is feeding well with no signs of respiratory distress")],
    ["B"],
    "RSV bronchiolitis is the most common lower respiratory tract infection in infants <1 year. Signs of SEVERE respiratory distress requiring immediate intervention include: TACHYPNEA (RR >60 in infants), NASAL FLARING (nares widen to increase air entry), INTERCOSTAL/SUBCOSTAL/SUPRASTERNAL RETRACTIONS (accessory muscle use indicates increased work of breathing), GRUNTING (expiratory sound from partial glottis closure to maintain positive end-expiratory pressure/auto-PEEP), and HYPOXEMIA (SpO2 <90% is critical and requires supplemental oxygen). This combination indicates impending respiratory failure and requires immediate RN notification, physician evaluation, supplemental oxygen, and possibly respiratory support. Treatment is primarily supportive: supplemental oxygen, suctioning of nasal secretions, IV fluids if unable to feed, and monitoring. Palivizumab (Synagis) is used for PREVENTION in high-risk infants, not treatment.",
    "Infant respiratory distress: tachypnea + nasal flaring + retractions + grunting + low SpO2 = EMERGENCY; RSV treatment is supportive", ["pediatric","RSV","bronchiolitis","respiratory-distress","infant"]);

  // Mental health PN
  pn("Psychosocial Integrity","Therapeutic Communication","Psychosocial Integrity",2,
    "An LPN is talking with a patient who says, 'Nobody cares about me. I'm all alone.' Which response uses therapeutic communication?",
    [O("A","'That's not true! You have lots of people who care about you.'"), O("B","'You're feeling alone and as though no one cares. Tell me more about what you're experiencing.'"), O("C","'You shouldn't feel that way. Other patients have it much worse.'"), O("D","'Let me turn on the television to cheer you up and distract you from those thoughts.'")],
    ["B"],
    "Therapeutic communication techniques promote a healing nurse-patient relationship. Option B demonstrates: REFLECTION (restating the patient's feelings to show understanding: 'You're feeling alone...'), VALIDATION (acknowledging the patient's emotional experience without judgment), and OPEN-ENDED EXPLORATION ('Tell me more...' invites the patient to elaborate and feel heard). NON-THERAPEUTIC responses include: DISAGREEING/CHALLENGING (A: 'That's not true!' dismisses the patient's feelings), MINIMIZING/COMPARING (C: 'Other patients have it worse' invalidates the patient's experience and implies they shouldn't feel the way they do), and FALSE REASSURANCE/DISTRACTION (D: turning on the TV avoids addressing the patient's emotional needs). Key therapeutic techniques: active listening, silence, reflection, restating, clarifying, focusing, broad opening, and offering self. Key non-therapeutic responses: giving advice, changing the subject, false reassurance, minimizing, agreeing/disagreeing, using 'why' questions, and giving approval.",
    "Therapeutic communication: reflect feelings, validate, explore; avoid disagreeing, minimizing, false reassurance, or distraction", ["therapeutic-communication","psychosocial","nursing-relationship","reflection","validation"]);

  pn("Psychosocial Integrity","Substance Withdrawal","Psychosocial Integrity",3,
    "An LPN is monitoring a patient admitted for alcohol withdrawal. The patient begins experiencing tremors, diaphoresis, tachycardia, and visual hallucinations 48 hours after the last drink. Using the CIWA-Ar scale, which intervention is MOST appropriate?",
    [O("A","Encourage the patient to have 'just one drink' to ease the withdrawal symptoms"), O("B","Administer prescribed benzodiazepines (chlordiazepoxide or lorazepam) per CIWA-Ar protocol, maintain a quiet low-stimulation environment, ensure seizure precautions are in place, monitor vital signs frequently, and maintain IV access for hydration"), O("C","Restrain the patient and administer a stimulant to counteract the sedation of withdrawal"), O("D","Discharge the patient since these symptoms are normal and will resolve on their own at home")],
    ["B"],
    "Alcohol withdrawal syndrome (AWS) progresses through predictable stages: 6-12 hours: tremors, anxiety, tachycardia, diaphoresis, nausea/vomiting. 12-24 hours: withdrawal seizures (generalized tonic-clonic). 24-72 hours: alcoholic hallucinosis (visual, tactile, or auditory hallucinations while the patient is aware they are hallucinating). 48-96 hours: DELIRIUM TREMENS (DTs) - the most severe and life-threatening form: confusion, agitation, hallucinations, severe autonomic instability (tachycardia, hypertension, hyperthermia), seizures. Mortality of untreated DTs: 15-35%. The CIWA-Ar (Clinical Institute Withdrawal Assessment for Alcohol-Revised) is a 10-item scoring tool that guides symptom-triggered benzodiazepine administration. BENZODIAZEPINES are the treatment of choice for AWS: long-acting (chlordiazepoxide/Librium, diazepam/Valium) for stable patients, short-acting (lorazepam/Ativan) for patients with liver disease. Additional measures: quiet environment, seizure precautions, IV hydration, thiamine (to prevent Wernicke encephalopathy), electrolyte monitoring.",
    "Alcohol withdrawal: CIWA-Ar guided benzodiazepine therapy; seizure precautions; thiamine; quiet environment; DTs peak at 48-96 hrs with 15-35% mortality if untreated", ["alcohol-withdrawal","CIWA-Ar","benzodiazepines","delirium-tremens","substance-abuse"]);

  pn("Psychosocial Integrity","Anxiety Management","Psychosocial Integrity",2,
    "An LPN is caring for a patient experiencing a panic attack in the emergency department. The patient is hyperventilating, trembling, and states, 'I'm having a heart attack! I'm going to die!' What is the PRIORITY intervention?",
    [O("A","Tell the patient to stop overreacting since this is not a real emergency"), O("B","Stay with the patient, speak in a calm low voice, guide slow deep breathing exercises (inhale for 4 counts, hold for 4, exhale for 8), provide reassurance that the symptoms are temporary and not life-threatening, and reduce environmental stimulation"), O("C","Leave the patient alone to calm down in privacy"), O("D","Administer oxygen at 15 L/min via non-rebreather mask immediately")],
    ["B"],
    "A panic attack is an acute episode of intense fear/anxiety with physical symptoms that mimic cardiac or respiratory emergencies. Nursing interventions: REMAIN WITH THE PATIENT (never leave a patient experiencing a panic attack alone; your presence provides security), CALM COMMUNICATION (speak in a calm, low, reassuring voice; short, simple sentences), GUIDED BREATHING (the patient's hyperventilation causes respiratory alkalosis, leading to tingling, lightheadedness, chest tightness; slow deep breathing normalizes CO2 levels: inhale 4 counts, hold 4, exhale 8), REASSURANCE (acknowledge the patient's fear while reassuring that symptoms are temporary: 'I can see you're frightened. These feelings will pass. I'm going to stay right here with you.'), REDUCE STIMULATION (dim lights, reduce noise, limit the number of people in the room). Telling the patient to 'stop overreacting' (A) is dismissive and non-therapeutic. Leaving (C) increases anxiety. High-flow oxygen (D) is unnecessary for hyperventilation-induced symptoms.",
    "Panic attack: stay with patient, calm voice, guide slow breathing, reassure, reduce stimulation; acknowledge fear without dismissing", ["panic-attack","anxiety","therapeutic-intervention","breathing-exercises","psychosocial"]);

  // More clinical PN
  pn("Physiological Integrity","Appendicitis Assessment","Physiological Integrity",2,
    "An LPN is assessing a patient with suspected appendicitis. Which assessment finding is characteristic of acute appendicitis?",
    [O("A","Pain that improves with eating and radiates to the left shoulder"), O("B","Right lower quadrant pain at McBurney's point (one-third of the distance from the anterior superior iliac spine to the umbilicus), rebound tenderness, nausea/vomiting, low-grade fever, and elevated WBC count"), O("C","Left upper quadrant pain that worsens with deep breathing"), O("D","Diffuse abdominal pain that improves with bowel movements and is associated with diarrhea")],
    ["B"],
    "Appendicitis presents with a classic progression of symptoms: (1) PERIUMBILICAL PAIN (initial visceral pain from appendiceal distension, poorly localized), (2) MIGRATION to the RIGHT LOWER QUADRANT (RLQ) within 12-24 hours as the inflammation involves the parietal peritoneum, (3) localization at MCBURNEY'S POINT (the point one-third of the distance from the right anterior superior iliac spine to the umbilicus). Additional signs: REBOUND TENDERNESS (pain worsens when pressure is released, indicating peritoneal irritation), ROVSING'S SIGN (palpation of the left lower quadrant causes pain in the RLQ), PSOAS SIGN (pain with right hip extension - suggests retrocecal appendix), OBTURATOR SIGN (pain with internal rotation of the right hip - suggests pelvic appendix), low-grade fever, anorexia, nausea/vomiting, and leukocytosis (elevated WBC). CRITICAL: do NOT apply heat to the abdomen (risk of perforation), and avoid laxatives or enemas (can increase intraluminal pressure and cause rupture).",
    "Appendicitis: RLQ pain at McBurney's point, rebound tenderness, Rovsing's/psoas/obturator signs; NEVER apply heat or give laxatives", ["appendicitis","McBurney-point","rebound-tenderness","assessment","GI"]);

  pn("Physiological Integrity","Cataract Post-Op","Physiological Integrity",2,
    "An LPN is providing post-operative instructions to a patient after cataract surgery. Which instruction is MOST important for preventing complications?",
    [O("A","Bend at the waist frequently to pick up objects from the floor"), O("B","Avoid bending, straining, lifting heavy objects (>5 lbs), rubbing the eye, and lying on the operated side; wear the protective eye shield as instructed especially during sleep; report sudden pain, vision loss, or flashing lights immediately"), O("C","Vigorously rub the operated eye if it itches to promote healing"), O("D","Resume all normal activities including contact sports the day after surgery")],
    ["B"],
    "After cataract surgery, specific activity restrictions are essential to prevent increased intraocular pressure (IOP), lens displacement, retinal detachment, and infection: AVOID BENDING at the waist (increases IOP; bend at the knees instead), AVOID STRAINING (Valsalva maneuver increases IOP - use stool softeners), AVOID HEAVY LIFTING (>5-10 lbs for 1-4 weeks), DO NOT RUB the operated eye (can displace the lens implant or disrupt the incision), WEAR the protective eye shield during sleep and naps (prevents accidental rubbing/pressure), AVOID LYING on the operated side. Report danger signs IMMEDIATELY: sudden severe pain (may indicate endophthalmitis/infection or acute glaucoma), sudden vision loss, seeing flashing lights or new floaters (retinal detachment), increasing redness, purulent discharge. Eye drops are typically prescribed in a specific sequence: antibiotic (prevent infection), corticosteroid (reduce inflammation), and NSAID (reduce pain and inflammation).",
    "Post-cataract: avoid bending/straining/lifting/rubbing; eye shield during sleep; report sudden pain, vision loss, flashing lights immediately", ["cataract","post-operative","eye","intraocular-pressure","patient-education"]);

  pn("Physiological Integrity","Hip Replacement Post-Op","Physiological Integrity",2,
    "An LPN is caring for a patient after total hip arthroplasty (replacement) with a posterior approach. Which position MUST be avoided?",
    [O("A","Abduction (legs apart) with the operative leg in neutral alignment"), O("B","Flexion of the hip beyond 90 degrees, adduction (crossing legs), and internal rotation of the operative leg, as these positions risk posterior hip dislocation"), O("C","Elevating the head of bed to 45 degrees for meals"), O("D","Keeping an abduction pillow between the legs while in bed")],
    ["B"],
    "After total hip replacement with a POSTERIOR approach, hip precautions are essential to prevent DISLOCATION of the prosthesis. The three movements to AVOID are: (1) FLEXION beyond 90 degrees (do not bend the hip past a right angle - use a raised toilet seat, avoid low chairs, do not lean forward when sitting), (2) ADDUCTION past midline (do not cross the legs or bring the operative leg toward or past the midline - use an ABDUCTION PILLOW between the legs while sleeping and turning), (3) INTERNAL ROTATION of the operative leg (do not turn the foot and leg inward). These restrictions apply because the posterior capsule and short external rotator muscles were cut during the surgical approach, and these movements can force the femoral head posteriorly out of the acetabular component. Abduction with neutral alignment (A) is the DESIRED position, not avoided. HOB elevation to 45 degrees (C) is acceptable. An abduction pillow (D) is RECOMMENDED. For anterior approach hip replacement, the restrictions are different (avoid external rotation and hyperextension).",
    "Posterior hip replacement precautions: avoid hip flexion >90°, adduction past midline, internal rotation; use raised toilet seat and abduction pillow", ["hip-replacement","posterior-approach","dislocation-prevention","orthopedic","postoperative"]);

  pn("Physiological Integrity","Seizure Management","Physiological Integrity",2,
    "An LPN witnesses a patient having a generalized tonic-clonic seizure in bed. What is the PRIORITY nursing action DURING the seizure?",
    [O("A","Restrain the patient's extremities to prevent injury from the convulsions"), O("B","Protect the patient from injury by lowering the bed, padding side rails, turning the patient to their side when possible, clearing the area of hazardous objects, noting the time of onset, and NOT placing anything in the mouth"), O("C","Insert a padded tongue blade between the patient's teeth to prevent them from biting their tongue"), O("D","Attempt to hold the patient still and administer oral medication")],
    ["B"],
    "During a generalized tonic-clonic seizure, the PRIORITY is patient SAFETY. Correct interventions: LOWER the bed to the lowest position, PAD side rails, turn the patient to their SIDE (lateral position) when possible to prevent aspiration of secretions, CLEAR the area of sharp or hard objects, NOTE THE TIME of onset and duration, stay with the patient and call for help, provide PRIVACY, and observe and document the seizure characteristics (type of movement, progression, duration, body parts involved, post-ictal behavior). NEVER insert ANYTHING into the mouth (A tongue blade, fingers, or any object can break teeth, lacerate the gums, or be aspirated; it is a MYTH that people swallow their tongues during seizures). NEVER restrain the patient (can cause fractures, dislocations, or musculoskeletal injuries against the force of tonic-clonic contractions). NEVER administer ORAL medications during a seizure (aspiration risk; emergent anticonvulsants are given IV or rectal). After the seizure: maintain airway, assess neurological status, document duration and characteristics, administer prescribed medications.",
    "During seizure: protect from injury, side-lying position, time the event, do NOT restrain or put anything in the mouth", ["seizure","tonic-clonic","safety","nursing-intervention","neurology"]);

  pn("Physiological Integrity","Osteoporosis","Health Promotion",2,
    "An LPN is educating a postmenopausal female patient about osteoporosis prevention. Which recommendation is MOST effective?",
    [O("A","Avoid all physical activity to prevent fractures"), O("B","Perform regular weight-bearing exercise (walking, jogging, dancing), ensure adequate calcium intake (1200 mg/day) and vitamin D (800-1000 IU/day), avoid smoking and excessive alcohol, and discuss bone density screening (DEXA scan) with the healthcare provider"), O("C","Drink 6 cups of coffee daily to strengthen bones"), O("D","Take calcium supplements of 5000 mg per day to maximize bone density")],
    ["B"],
    "Osteoporosis prevention and management involves a multimodal approach: WEIGHT-BEARING EXERCISE (walking, jogging, dancing, stair climbing) stimulates bone formation by stressing bone through impact and gravity. Resistance training builds muscle strength that protects against falls. CALCIUM: 1200 mg/day for women >50 (from dietary sources preferably; supplements if dietary intake is insufficient; excessive calcium >2000 mg/day increases kidney stone risk and cardiovascular risk). VITAMIN D: 800-1000 IU/day (necessary for calcium absorption; deficiency is common in northern latitudes, elderly, dark-skinned individuals). LIFESTYLE: avoid smoking (smoking decreases estrogen levels and impairs osteoblast function), limit alcohol (>3 drinks/day decreases bone formation), limit caffeine (excessive caffeine increases calcium excretion). BONE DENSITY: DEXA scan recommended for all women ≥65 years and postmenopausal women <65 with risk factors. Medications: bisphosphonates (alendronate, risedronate) are first-line pharmacological therapy for diagnosed osteoporosis.",
    "Osteoporosis prevention: weight-bearing exercise, calcium 1200mg/day, vitamin D 800-1000 IU, no smoking, limit alcohol, DEXA screening", ["osteoporosis","prevention","calcium","vitamin-D","weight-bearing-exercise"]);

  pn("Safe & Effective Care Environment","Infection Control Principles","Safe & Effective Care Environment",2,
    "An LPN is donning personal protective equipment (PPE) to enter a patient's room that requires full contact precautions. What is the correct ORDER for putting on PPE?",
    [O("A","Gloves first, then gown, then mask, then eye protection"), O("B","Hand hygiene first, then gown, then mask/respirator, then eye protection/face shield, then gloves (gloves are always LAST because they touch the patient directly and must go over the gown cuffs)"), O("C","Eye protection first, then gloves, then gown, then mask"), O("D","The order doesn't matter as long as all PPE is worn")],
    ["B"],
    "The correct sequence for DONNING (putting on) PPE follows a logical progression from largest to smallest, with gloves always LAST: (1) HAND HYGIENE (always performed before and after PPE use), (2) GOWN (ties at neck and waist, covers the front and back of the torso), (3) MASK or RESPIRATOR (secure over nose and mouth, fit-check N95 if used), (4) EYE PROTECTION/FACE SHIELD (placed over eyes, with ear pieces over mask straps), (5) GLOVES (always LAST - pull glove cuffs OVER the gown cuffs to create a continuous barrier with no exposed skin between gown and gloves). The DOFFING (removal) order is designed to prevent self-contamination and follows a different sequence: (1) GLOVES (most contaminated item, removed first using glove-in-glove or beak technique), (2) HAND HYGIENE, (3) GOWN (break ties, roll contaminated surface inward), (4) HAND HYGIENE, (5) EYE PROTECTION (remove by touching earpieces/headband only), (6) MASK (remove by touching strings/elastic only), (7) HAND HYGIENE. The order matters because it minimizes the risk of contaminating clean PPE with contaminated items.",
    "PPE donning order: hand hygiene → gown → mask → eye protection → gloves (last); doffing: gloves (first) → gown → eye protection → mask", ["PPE","infection-control","donning-doffing","contact-precautions","safety"]);

  pn("Physiological Integrity","Asthma Medication","Pharmacological Therapies",2,
    "An LPN is teaching a patient about the difference between their albuterol (rescue) inhaler and their fluticasone (controller) inhaler. Which statement by the patient indicates understanding?",
    [O("A","'I should use my fluticasone inhaler when I'm having an acute asthma attack for quick relief.'"), O("B","'I use my albuterol inhaler for quick relief during an asthma attack (it works within minutes), and I use my fluticasone inhaler every day as prescribed to prevent attacks even when I feel fine (it reduces airway inflammation over time).'"), O("C","'Both inhalers are the same and can be used interchangeably.'"), O("D","'I only need to use my controller inhaler when I feel symptoms starting.'")],
    ["B"],
    "Understanding the difference between rescue and controller inhalers is critical for asthma self-management: RESCUE (quick-relief) inhalers: ALBUTEROL (Ventolin/ProAir) is a short-acting beta-2 agonist (SABA). It works in 5-15 MINUTES by directly relaxing bronchial smooth muscle (bronchodilation). Used for acute symptoms, exercise-induced bronchospasm, and emergencies. If using >2 times/week (excluding exercise pre-treatment), asthma is NOT well-controlled and the controller regimen needs adjustment. CONTROLLER (maintenance) inhalers: FLUTICASONE (Flovent) is an inhaled corticosteroid (ICS). It works by reducing airway INFLAMMATION over time (takes days to weeks for full effect; NOT for acute attacks). Must be used DAILY as prescribed regardless of symptoms. After using ICS, the patient must RINSE MOUTH with water and SPIT to prevent oral candidiasis (thrush) and dysphonia. Other controllers include: long-acting beta-agonists (salmeterol, formoterol - always combined with ICS, never used alone), leukotriene modifiers (montelukast), and long-acting muscarinic antagonists (tiotropium).",
    "Rescue (albuterol) = quick relief, bronchodilator, for acute symptoms; Controller (fluticasone) = daily prevention, anti-inflammatory, rinse mouth after", ["asthma","albuterol","fluticasone","rescue-vs-controller","patient-education"]);

  // ============ MORE NCLEX-RN ============

  rn("Critical Care","Mechanical Ventilation","Physiological Integrity",4,
    "An RN is caring for a mechanically ventilated patient and the high-pressure alarm sounds. Which condition is the MOST likely cause?",
    [O("A","Endotracheal tube cuff leak or patient circuit disconnection"), O("B","Increased airway resistance from mucus plugging, bronchospasm, biting on the endotracheal tube, or patient-ventilator dyssynchrony (fighting the ventilator)"), O("C","Resolution of the underlying respiratory condition"), O("D","The ventilator is functioning normally; high-pressure alarms are routine")],
    ["B"],
    "Mechanical ventilator HIGH-PRESSURE alarms indicate increased resistance or decreased compliance in the airway or lungs. Common causes: MUCUS PLUGGING (secretions obstructing the airway - suction the patient), BRONCHOSPASM (increased smooth muscle constriction - administer bronchodilators), BITING on the ET tube (place a bite block or oral airway), PATIENT-VENTILATOR DYSSYNCHRONY (patient 'fighting' the ventilator - assess for anxiety, pain, hypoxia; consider sedation), PNEUMOTHORAX (decreased compliance from air in pleural space), WATER in the ventilator circuit (drain condensation), KINKING of the ET tube, PATIENT COUGHING, or WORSENING LUNG COMPLIANCE (ARDS, pulmonary edema). Nursing response: (1) assess the patient FIRST (not the machine), (2) check the airway for obstruction, (3) auscultate lung sounds, (4) suction if indicated, (5) check the circuit for kinks or water. LOW-PRESSURE alarms indicate decreased resistance: ET tube cuff leak, circuit disconnection, or loss of airway. Remember: HIGH pressure = something is BLOCKING; LOW pressure = something is LEAKING.",
    "Vent alarms: HIGH pressure = obstruction/resistance (suction, bronchospasm, biting); LOW pressure = leak/disconnection; always assess PATIENT first, not machine", ["mechanical-ventilation","high-pressure-alarm","ventilator","critical-care","troubleshooting"]);

  rn("Cardiac","12-Lead ECG Interpretation","Physiological Integrity",4,
    "An RN is interpreting a 12-lead ECG showing ST elevation in leads II, III, and aVF. Which coronary artery territory does this represent?",
    [O("A","Left anterior descending (LAD) artery territory - anterior wall MI"), O("B","Right coronary artery (RCA) territory - inferior wall MI; the inferior leads (II, III, aVF) correspond to the inferior surface of the heart supplied by the RCA in most patients"), O("C","Left circumflex (LCx) artery territory - lateral wall MI"), O("D","Left main coronary artery territory - global ischemia")],
    ["B"],
    "12-lead ECG interpretation localizes myocardial infarction by correlating ST elevation in specific lead groups with coronary artery territories: INFERIOR MI: leads II, III, aVF - RIGHT CORONARY ARTERY (RCA) in ~85% of patients (the RCA supplies the inferior surface of the heart, SA node, and AV node). ANTERIOR MI: leads V1-V4 - LEFT ANTERIOR DESCENDING (LAD) artery (the 'widow maker' - supplies the anterior wall and interventricular septum; anterior MI has the highest mortality). LATERAL MI: leads I, aVL, V5-V6 - LEFT CIRCUMFLEX (LCx) artery. POSTERIOR MI: reciprocal ST depression in V1-V3 (tall R waves, upright T waves as mirror image of posterior ST elevation). IMPORTANT for inferior MI: always obtain RIGHT-SIDED leads (V3R-V6R) to assess for RIGHT VENTRICULAR INVOLVEMENT (occurs in ~30-50% of inferior MIs because the RCA also supplies the RV). RV infarction is a contraindication for nitroglycerin (can cause severe hypotension due to preload dependence).",
    "ECG MI localization: II/III/aVF = inferior (RCA); V1-V4 = anterior (LAD); I/aVL/V5-V6 = lateral (LCx); check right-sided leads for inferior MI", ["ECG","STEMI","inferior-MI","RCA","12-lead"]);

  rn("Neurology","Stroke Assessment","Physiological Integrity",3,
    "An RN is assessing a patient with suspected acute ischemic stroke. The patient has right-sided hemiparesis, aphasia, and right facial droop. Which cerebral artery territory is MOST likely affected?",
    [O("A","Right middle cerebral artery causing left-sided symptoms"), O("B","Left middle cerebral artery: the left hemisphere controls the right side of the body (contralateral motor function) and contains Broca's and Wernicke's areas for language in most people; left MCA strokes produce right-sided weakness AND aphasia"), O("C","Posterior cerebral artery causing visual deficits only"), O("D","Anterior cerebral artery causing bilateral leg weakness")],
    ["B"],
    "The middle cerebral artery (MCA) is the most commonly affected artery in ischemic stroke. LEFT MCA stroke produces: CONTRALATERAL (right-sided) hemiparesis/hemiplegia (face and arm > leg because the MCA territory includes the lateral motor cortex representing the face and upper extremity), APHASIA (the left hemisphere is dominant for language in >95% of right-handed and ~70% of left-handed individuals; Broca's area = expressive aphasia/motor, Wernicke's area = receptive aphasia/sensory), right homonymous hemianopia, and right-sided sensory loss. RIGHT MCA stroke produces: left-sided hemiparesis, left neglect syndrome (unilateral neglect - the patient ignores the left side of space and their own body), left homonymous hemianopia, but typically NO aphasia (language center is usually in the left hemisphere). The ANTERIOR cerebral artery supplies the medial frontal and parietal lobes (leg motor and sensory areas - causes contralateral leg weakness). The POSTERIOR cerebral artery supplies the occipital lobe (visual cortex - causes visual field deficits). Acute ischemic stroke treatment: IV alteplase (tPA) within 4.5 hours of symptom onset, or thrombectomy within 24 hours for large vessel occlusion.",
    "Left MCA stroke = right hemiparesis + aphasia; Right MCA = left hemiparesis + neglect (no aphasia); MCA = face/arm > leg", ["stroke","MCA","aphasia","hemiparesis","neurology"]);

  rn("Obstetrics","Fetal Monitoring","Physiological Integrity",4,
    "An RN is monitoring a patient in active labor. The electronic fetal monitoring (EFM) shows repetitive late decelerations with minimal variability. What is the PRIORITY nursing action?",
    [O("A","Continue monitoring without intervention since late decelerations are normal during active labor"), O("B","Reposition the patient to the left lateral position to improve uteroplacental perfusion, administer oxygen by non-rebreather mask, increase IV fluid rate, discontinue oxytocin if infusing, and notify the physician immediately as late decelerations indicate uteroplacental insufficiency"), O("C","Prepare for immediate vaginal delivery by having the patient push with each contraction"), O("D","Administer more oxytocin to speed up labor and reduce the number of contractions")],
    ["B"],
    "LATE DECELERATIONS are a non-reassuring (Category III when persistent with minimal/absent variability) fetal heart rate pattern that indicates UTEROPLACENTAL INSUFFICIENCY - the placenta is not providing adequate oxygen to the fetus during contractions. Late decelerations begin AFTER the peak of the contraction, reach their nadir AFTER the contraction peaks, and return to baseline AFTER the contraction ends. Combined with MINIMAL VARIABILITY (reduced beat-to-beat variation, suggesting decreased fetal CNS oxygenation), this pattern is ominous and requires IMMEDIATE intervention: (1) LEFT LATERAL POSITION (relieves aortocaval compression, optimizes venous return and uterine blood flow), (2) OXYGEN via non-rebreather at 10 L/min, (3) INCREASE IV fluids (improves intravascular volume and uteroplacental perfusion), (4) DISCONTINUE OXYTOCIN if infusing (reduce uterine activity/frequency of contractions), (5) NOTIFY the physician immediately (may need tocolytics for uterine relaxation, amnioinfusion, or emergent cesarean section). EARLY decelerations (mirror contractions, caused by fetal head compression) are benign. VARIABLE decelerations (abrupt onset, variable shape) indicate CORD COMPRESSION.",
    "Late decelerations + minimal variability = uteroplacental insufficiency; LEFT lateral, O2, fluids, stop oxytocin, notify MD; Early decels = benign (head compression); Variables = cord compression", ["fetal-monitoring","late-decelerations","uteroplacental-insufficiency","obstetrics","labor"]);

  rn("Nephrology","Hemodialysis Nursing","Physiological Integrity",3,
    "An RN is caring for a patient with an arteriovenous fistula (AVF) in the left forearm used for hemodialysis. Which nursing action is correct?",
    [O("A","Take blood pressure, draw blood, and start IVs in the left arm with the fistula"), O("B","Assess the fistula regularly for a bruit (audible whooshing/buzzing sound heard with stethoscope) and thrill (palpable vibration/buzzing felt with fingertips), which indicate fistula patency; NEVER use the fistula arm for blood pressure, venipuncture, or IV access"), O("C","Apply a tourniquet tightly above the fistula to strengthen it"), O("D","The AVF does not require any special nursing assessment or precautions")],
    ["B"],
    "The arteriovenous fistula (AVF) is the preferred long-term vascular access for hemodialysis because it has the lowest infection and thrombosis rates. Nursing care includes: ASSESS PATENCY by checking for BRUIT (audible whooshing/humming sound heard with the STETHOSCOPE over the fistula, caused by turbulent blood flow from the artery through the fistula into the vein) and THRILL (palpable vibration/buzzing felt with the FINGERTIPS over the fistula site; the most reliable indicator of patency). ABSENT bruit/thrill = CLOTTED fistula = emergency (notify physician immediately). PROTECT THE FISTULA ARM: NO blood pressure measurements, NO venipuncture, NO IV access, NO tourniquet application, NO restrictive clothing or jewelry on the fistula arm. These actions can compress the fistula, damage the access, or promote clotting. WATCH FOR COMPLICATIONS: infection (redness, warmth, drainage), thrombosis (absent bruit/thrill), steal syndrome (distal ischemia - cool, pale, painful hand from arterial blood being 'stolen' by the fistula), aneurysm formation, and bleeding. PATIENT EDUCATION: no sleeping on the fistula arm, no carrying heavy bags with the fistula arm, report signs of infection or changes in thrill/bruit.",
    "AVF care: check bruit (auscultate) and thrill (palpate) for patency; NEVER use fistula arm for BP, blood draws, IVs; absent bruit/thrill = clotted = emergency", ["hemodialysis","AVF","fistula","bruit","thrill","nephrology"]);

  rn("Neurology","Increased ICP","Physiological Integrity",4,
    "An RN is caring for a patient with a traumatic brain injury who develops increasing intracranial pressure (ICP). Which set of vital sign changes should the RN recognize as Cushing's triad (Cushing's response)?",
    [O("A","Tachycardia, hypotension, and tachypnea"), O("B","Hypertension (widening pulse pressure), bradycardia, and irregular respirations (Cheyne-Stokes or ataxic breathing); Cushing's triad is a LATE sign indicating brainstem compression and impending herniation - this is a neurosurgical emergency"), O("C","Normal vital signs with mild headache"), O("D","Hypothermia, tachycardia, and hypotension")],
    ["B"],
    "Cushing's triad (Cushing's response) is a set of three vital sign changes that indicate dangerously elevated ICP with brainstem compression: (1) HYPERTENSION with WIDENING PULSE PRESSURE (as ICP rises toward the mean arterial pressure, the body increases systemic blood pressure dramatically to maintain cerebral perfusion pressure; CPP = MAP - ICP; the systolic pressure rises more than the diastolic, widening the pulse pressure), (2) BRADYCARDIA (the baroreceptors in the aortic arch and carotid sinus sense the hypertension and trigger a vagal response, slowing the heart rate), (3) IRREGULAR RESPIRATIONS (brainstem compression affects the respiratory centers, producing abnormal patterns: Cheyne-Stokes, central neurogenic hyperventilation, apneustic, or ataxic/Biot's breathing). CRITICAL: Cushing's triad is a LATE and OMINOUS sign indicating that herniation is occurring or imminent. It requires IMMEDIATE neurosurgical intervention. Earlier signs of rising ICP include: decreasing level of consciousness (the EARLIEST and most sensitive indicator), headache, pupil changes (unilateral dilated fixed pupil = uncal herniation), projectile vomiting, and declining GCS score.",
    "Cushing's triad: hypertension (wide pulse pressure) + bradycardia + irregular respirations = brainstem compression = EMERGENCY; earliest ICP sign = decreased LOC", ["ICP","Cushing-triad","brainstem","herniation","neurology"]);

  rn("Pharmacology","Potassium Administration","Physiological Integrity",3,
    "An RN receives an order to administer potassium chloride (KCl) 40 mEq IV to a patient with severe hypokalemia (K+ 2.6 mEq/L). Which safety precaution is MOST critical?",
    [O("A","Administer the potassium as a rapid IV push to correct the deficit quickly"), O("B","NEVER give potassium IV push; dilute in compatible IV fluid and infuse no faster than 10-20 mEq/hour via an infusion pump; always administer on a cardiac monitor because rapid potassium infusion can cause fatal cardiac dysrhythmias (cardiac arrest)"), O("C","Potassium can be safely administered at any rate without cardiac monitoring"), O("D","Add the potassium to D5W and infuse it in 10 minutes")],
    ["B"],
    "Potassium chloride is a HIGH-ALERT medication that requires strict safety precautions. CRITICAL RULES: (1) NEVER give IV potassium as a PUSH or BOLUS (this can cause immediate cardiac arrest from hyperkalemia-induced ventricular fibrillation); (2) MAXIMUM infusion rate: 10-20 mEq/hour for peripheral IV, up to 40 mEq/hour via CENTRAL line in critical situations with continuous cardiac monitoring; (3) MAXIMUM concentration: 40 mEq/L for peripheral IV (higher concentrations cause phlebitis and pain), up to 80 mEq/100 mL via central line; (4) ALWAYS use an infusion pump for precise rate control; (5) CARDIAC MONITORING is mandatory (assess for peaked T waves, widened QRS, bradycardia); (6) ASSESS renal function before administration (potassium is excreted by the kidneys; avoid in oliguric/anuric patients); (7) MONITOR serum potassium levels during replacement; (8) assess the IV site frequently for infiltration (concentrated KCl causes tissue necrosis). Most facilities have removed concentrated KCl from nursing units and require pharmacy-prepared dilutions to prevent accidental overdose. The oral route is preferred when possible as it is safer and allows for physiological regulation.",
    "IV potassium: NEVER IV push (fatal); max 10-20 mEq/hr peripheral, use infusion pump, cardiac monitor, check renal function; HIGH-ALERT medication", ["potassium","IV-safety","high-alert","cardiac-monitoring","electrolyte"]);

  // ============ MORE REx-PN ============

  rpn("Community Health","Indigenous Health","Health Promotion",3,
    "An RPN is providing culturally safe care to an Indigenous patient. Which principle from the Truth and Reconciliation Commission (TRC) Calls to Action is MOST relevant to healthcare?",
    [O("A","Indigenous patients should receive the same cookie-cutter care as all other patients without any cultural considerations"), O("B","Recognize the impact of historical trauma (residential schools, colonization) on Indigenous health outcomes, provide culturally safe care that acknowledges diverse healing practices, address systemic racism in healthcare, and ensure the patient has access to traditional healers and cultural supports if desired"), O("C","All Indigenous patients prefer traditional medicine exclusively and refuse Western healthcare"), O("D","Cultural safety training is optional and not required for healthcare providers in Canada")],
    ["B"],
    "The Truth and Reconciliation Commission (TRC) of Canada issued 94 Calls to Action in 2015, with several directly addressing healthcare (Calls to Action 18-24). Key principles: ACKNOWLEDGE the intergenerational health effects of residential schools and colonization (higher rates of chronic disease, mental illness, addiction, and suicide in Indigenous communities); CULTURAL SAFETY goes beyond cultural sensitivity - it requires healthcare providers to examine their own biases, power imbalances, and the impact of colonialism on Indigenous health; RESPECT diverse healing practices (traditional medicine, ceremonies, Elders, Medicine Wheel teachings may be integral to the patient's healing journey); ADDRESS SYSTEMIC BARRIERS (racism, discrimination, geographic isolation, jurisdictional disputes between federal and provincial governments regarding Indigenous health funding); SELF-DETERMINATION means the patient chooses their care approach, which may include traditional healing, Western medicine, or both. The College of Nurses of Ontario (CNO) requires all nurses to provide culturally safe care and understand the social determinants of health affecting Indigenous peoples.",
    "TRC in healthcare: acknowledge historical trauma, provide culturally safe care, respect traditional healing, address systemic racism; culturally safe ≠ culturally competent", ["Indigenous-health","TRC","cultural-safety","reconciliation","social-determinants"]);

  rpn("Legal","PHIPA Privacy","Safe & Effective Care Environment",3,
    "An RPN in Ontario receives a phone call from a patient's employer asking about the patient's diagnosis and expected return-to-work date. What should the RPN do?",
    [O("A","Provide the employer with complete medical details since they are paying for the employee's benefits"), O("B","Decline to provide any health information to the employer without the patient's written consent; explain that personal health information is protected under PHIPA and can only be disclosed with the patient's informed consent or as required by law"), O("C","Share the information verbally but not in writing, as verbal disclosure is not covered by privacy laws"), O("D","Provide the diagnosis but withhold the return-to-work date")],
    ["B"],
    "The Personal Health Information Protection Act (PHIPA, 2004) in Ontario governs the collection, use, and disclosure of personal health information (PHI) by health information custodians. Key principles: CONSENT is required for disclosure of PHI to third parties, including employers, insurance companies, and family members (unless the patient has provided prior authorization). PHI includes: diagnosis, treatment, test results, prognosis, and any health-related information. EXCEPTIONS where consent is NOT required: mandatory reporting to public health (communicable diseases), reporting to Children's Aid Society (child abuse/neglect), reporting to regulatory bodies, court orders, and imminent risk of harm. The RPN should: confirm their identity as a healthcare provider, politely decline to share information, explain that privacy legislation prevents disclosure without consent, and advise the employer to request information directly from the patient or obtain a written consent form. All forms of disclosure (verbal, written, electronic) are covered by PHIPA.",
    "PHIPA: no health info disclosure without patient consent; applies to verbal AND written; exceptions: mandatory reporting, court orders, imminent harm", ["PHIPA","privacy","consent","disclosure","Ontario","legal"]);

  rpn("Leadership","Interprofessional Collaboration","Safe & Effective Care Environment",2,
    "An RPN is participating in an interprofessional team meeting to discuss a complex patient's discharge plan. The team includes an RN, physician, social worker, physiotherapist, and pharmacist. What is the RPN's role in this meeting?",
    [O("A","Remain silent since RPNs should not contribute to team discussions"), O("B","Actively contribute observations about the patient's daily functional status, response to treatments, psychosocial needs, and any concerns; RPNs provide valuable frontline bedside data that informs collaborative decision-making"), O("C","Make all final decisions about the patient's care since the RPN spends the most time at bedside"), O("D","Only attend the meeting if directly invited by the physician")],
    ["B"],
    "Interprofessional collaboration (IPC) is essential for optimal patient outcomes. Each team member brings unique expertise: the RPN provides critical frontline data from direct patient care (daily functional assessment, medication responses, patient/family concerns, psychosocial observations, changes in condition). In IPC: ALL team members are expected to actively participate and share their perspective; the patient's needs drive the discussion, not professional hierarchy; effective communication tools (SBAR: Situation-Background-Assessment-Recommendation) facilitate clear information exchange; shared decision-making integrates all disciplines' assessments for the best patient outcome. The RPN's role includes: reporting on the patient's daily status and progress, identifying barriers to discharge, advocating for the patient's wishes and needs, implementing the collaborative care plan within their scope, and documenting and communicating changes. This aligns with the CNO's interprofessional collaboration standard for practical nurses.",
    "IPC: RPNs actively contribute frontline bedside observations; use SBAR for communication; all team members share expertise; patient-centered decisions", ["interprofessional","collaboration","team-meeting","discharge-planning","communication"]);

  rpn("Pharmacology","Canadian Drug Names","Physiological Integrity",2,
    "An RPN in Canada is reviewing a patient's medication list and notes the patient takes salbutamol as a rescue inhaler for asthma. A student nurse from the US asks what the equivalent American brand name is. What should the RPN explain?",
    [O("A","Salbutamol is not available in the US and there is no equivalent"), O("B","Salbutamol is the international non-proprietary name (INN) used in Canada; in the US, the same medication is called albuterol (brand names include Ventolin and ProAir); they are the same short-acting beta-2 agonist bronchodilator with identical pharmacology"), O("C","Salbutamol and albuterol are completely different medications with different mechanisms"), O("D","Only the Canadian name is correct; the US name is wrong")],
    ["B"],
    "Drug naming varies between countries: SALBUTAMOL is the International Non-Proprietary Name (INN) used in Canada, the UK, Australia, and most of the world. ALBUTEROL is the United States Adopted Name (USAN) used exclusively in the US. They are the SAME medication: a selective short-acting beta-2 adrenergic agonist that causes bronchodilation. Other common Canada-US naming differences: acetaminophen (Canada/US) = paracetamol (UK/international); epinephrine (Canada/US) = adrenaline (UK/international); norepinephrine (Canada/US) = noradrenaline (UK/international); meperidine (Canada/US) = pethidine (UK/international). Brand name Ventolin is used in both countries. Canadian nurses should be aware of international naming differences as they may encounter patients from other countries or use international references. Canadian medication labels primarily use the INN naming convention, while dosing units follow the metric system (mmol/L for blood glucose, not mg/dL used in the US).",
    "Salbutamol (Canada/INN) = albuterol (US) = same drug (SABA bronchodilator); Canadian nurses should know international drug naming differences", ["salbutamol","albuterol","drug-naming","Canada","bronchodilator"]);

  return qs;
}

async function main() {
  console.log("=== Scale PN/RN Batch ===\n");
  const before = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("BEFORE:"); for (const r of before.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs = build();
  const bk: Record<string,number> = {};
  for (const q of allQs) bk[q.exam] = (bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`, bk);
  let ins=0, dup=0, err=0;
  for (const q of allQs) {
    const h = sh(q.stem);
    try {
      const ex = await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`, [h, q.tier, q.exam]);
      if (ex.rows.length > 0) { dup++; continue; }
      await pool.query(
        `INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at)
         VALUES (gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,
        [q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,
         "Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);
      ins++;
    } catch (e: any) { err++; console.error(`ERR: ${e.message.substring(0,100)}`); }
  }
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after = await pool.query(`SELECT tier, exam, COUNT(*)::int as c FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier, exam ORDER BY tier, exam`);
  console.log("\nAFTER:"); for (const r of after.rows) console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session = await pool.query(`SELECT exam, COUNT(*)::int as cnt FROM exam_questions WHERE tier IN ('rpn','rn') AND exam IN ('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at > NOW() - INTERVAL '8 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:"); for (const r of session.rows) console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}

main().catch(e => { console.error("Fatal:", e); process.exit(1); });
