import crypto from "crypto";
import pg from "pg";
const pool = new pg.Pool({ host: process.env.PGHOST||"helium", user: process.env.PGUSER||"postgres", password: process.env.PGPASSWORD||"password", database: process.env.PGDATABASE||"heliumdb", ssl:false });
function sh(t:string):string{return crypto.createHash("sha256").update(t.trim().toLowerCase().replace(/[^a-z0-9\s]/g,"").replace(/\s+/g," ")).digest("hex").substring(0,16);}
const O=(l:string,t:string)=>({label:l,text:t});
interface Q{tier:string;exam:string;stem:string;options:{label:string;text:string}[];ca:string[];rat:string;diff:number;tags:string[];topic:string;sub:string;rs:string;cp:string;bs:string;}

function build():Q[]{
  const qs:Q[]=[];
  const pn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"NCLEX-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"US",cp,bs});
  const rn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rn",exam:"NCLEX-RN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"BOTH",cp,bs});
  const rpn=(t:string,s:string,bs:string,d:number,st:string,opts:any[],ca:string[],rat:string,cp:string,tags:string[])=>qs.push({tier:"rpn",exam:"REx-PN",stem:st,options:opts,ca,rat,diff:d,tags,topic:t,sub:s,rs:"CA",cp,bs});

  // NCLEX-RN Batch 25
  rn("Pharmacology","Antibiotic Allergy Cross-Reactivity","Physiological Integrity",3,
    "An RN is caring for a patient with a documented penicillin allergy (hives) who requires antibiotic therapy. The physician orders cefazolin (a first-generation cephalosporin). What should the RN know about cross-reactivity?",
    [O("A","Cephalosporins are completely unrelated to penicillins and can always be given safely"),O("B","The cross-reactivity between penicillins and cephalosporins is approximately 1-2% (much lower than the previously cited 10%); patients with a MILD penicillin allergy (rash, hives) can generally receive cephalosporins SAFELY with monitoring; however, patients with a SEVERE penicillin allergy (anaphylaxis, angioedema, Stevens-Johnson syndrome) should AVOID cephalosporins, especially first-generation agents which share more structural similarity; alternatives include azithromycin, fluoroquinolones, or vancomycin"),O("C","All patients with penicillin allergy must never receive any cephalosporin under any circumstance"),O("D","Cross-reactivity is 100%, making cephalosporins absolutely contraindicated")],
    ["B"],"Penicillin-cephalosporin cross-reactivity: historically cited at 10%, but current evidence shows the TRUE cross-reactivity rate is approximately 1-2%. STRUCTURE: both penicillins and cephalosporins contain a beta-lactam ring, but the side chain structure is what determines allergic cross-reactivity, not the beta-lactam ring itself. FIRST-GENERATION cephalosporins (cefazolin, cephalexin) share more structural similarity with penicillins → slightly higher cross-reactivity risk. THIRD/FOURTH-GENERATION cephalosporins have very different side chains → very low cross-reactivity. CLINICAL APPROACH: MILD penicillin allergy (hives, rash, GI upset): cephalosporins can generally be given with monitoring (observe for 30-60 minutes after first dose). SEVERE penicillin allergy (ANAPHYLAXIS, angioedema, bronchospasm, Stevens-Johnson syndrome, toxic epidermal necrolysis): AVOID cephalosporins (especially 1st generation); use alternatives: azithromycin (macrolide), fluoroquinolones (levofloxacin, moxifloxacin), vancomycin (for MRSA/gram-positive), clindamycin, or carbapenems (meropenem, imipenem - very low cross-reactivity <1% with penicillin). PENICILLIN ALLERGY TESTING: skin testing can identify true IgE-mediated allergy; approximately 80-90% of patients reporting penicillin allergy are NOT truly allergic (allergy often develops in childhood and is lost over time → penicillin allergy de-labeling programs).",
    "Penicillin-cephalosporin cross-reactivity: ~1-2% (not 10%); mild allergy = can give cephalosporins with monitoring; severe (anaphylaxis) = avoid; 80-90% 'allergic' patients aren't truly allergic", ["cross-reactivity","penicillin-allergy","cephalosporin","beta-lactam","alternatives"]);

  rn("Obstetrics","Postpartum Hemorrhage","Physiological Integrity",4,
    "An RN is assessing a patient 2 hours after vaginal delivery. The fundus is boggy and the patient is soaking through perineal pads rapidly. Estimated blood loss exceeds 500 mL. What is the FIRST nursing action?",
    [O("A","Apply an ice pack to the perineum and continue monitoring"),O("B","Immediately perform FUNDAL MASSAGE: the #1 cause of early postpartum hemorrhage is UTERINE ATONY (the uterus fails to contract adequately after delivery → the open spiral arteries at the placental site bleed freely); fundal massage stimulates uterine contraction; also: administer OXYTOCIN (Pitocin) as ordered to promote uterine contraction; monitor vital signs for hypovolemic shock; establish IV access; monitor urine output; keep the patient warm; prepare for possible additional uterotonics (methylergonovine/Methergine - contraindicated in hypertension, carboprost/Hemabate - contraindicated in asthma, misoprostol/Cytotec)"),O("C","A boggy fundus is normal 2 hours postpartum"),O("D","Only notify the physician; no immediate nursing action is needed")],
    ["B"],"Postpartum hemorrhage (PPH) management: PPH is defined as blood loss ≥500 mL after vaginal delivery or ≥1000 mL after cesarean delivery. The 4 T's of PPH causes: TONE (uterine atony - #1 cause, 70-80%), TRAUMA (lacerations, hematoma), TISSUE (retained placental fragments), THROMBIN (coagulation disorders). UTERINE ATONY: the uterus should contract firmly after delivery to compress the spiral arteries at the placental site. If it fails to contract (BOGGY fundus) → uncontrolled hemorrhage from the open blood vessels. RISK FACTORS: overdistension (macrosomia, twins, polyhydramnios), prolonged labor, precipitous labor, magnesium sulfate use (smooth muscle relaxant), multiparity, chorioamnionitis. NURSING ACTIONS: (1) FUNDAL MASSAGE: the first and most critical intervention; place one hand above the symphysis pubis for support (lower uterine segment) and firmly massage the fundus with the other hand in a circular motion until it becomes FIRM (a contracted uterus feels like a grapefruit). (2) OXYTOCIN (Pitocin): first-line medication; IV infusion promotes uterine contraction. (3) METHYLERGONOVINE (Methergine): IM injection; promotes sustained uterine contraction; CONTRAINDICATED in HYPERTENSION (causes vasoconstriction → hypertensive crisis). (4) CARBOPROST (Hemabate/15-methyl PGF2α): IM injection; CONTRAINDICATED in ASTHMA (bronchoconstriction). (5) MISOPROSTOL (Cytotec): rectal, sublingual, or buccal; can be given when IV access is difficult. (6) Manage hypovolemia: IV fluids, type and crossmatch for possible transfusion, monitor vital signs q5-15 minutes, foley catheter (full bladder can prevent uterine contraction).",
    "PPH: fundal massage FIRST for boggy uterus; oxytocin first-line med; methylergonovine contraindicated in HTN; carboprost contraindicated in asthma; 4 T's of PPH", ["postpartum-hemorrhage","fundal-massage","uterine-atony","oxytocin","obstetric-emergency"]);

  rn("Pharmacology","Thyroid Medication Teaching","Physiological Integrity",2,
    "An RN is teaching a patient about levothyroxine (Synthroid) for hypothyroidism. Which instruction promotes optimal medication effectiveness?",
    [O("A","Take levothyroxine with a high-fat breakfast for better absorption"),O("B","Take levothyroxine on an EMPTY STOMACH, 30-60 minutes BEFORE breakfast with a full glass of WATER: food, especially fiber, calcium, and soy products, significantly DECREASES absorption; also avoid taking with calcium supplements, iron supplements, or antacids (space by at least 4 hours); take at the SAME TIME each day for consistent thyroid hormone levels; it takes 4-6 WEEKS to see the full effect of a dose change; do NOT switch brands without physician approval (bioavailability varies between brands)"),O("C","The medication can be taken at any time with any food"),O("D","Double the dose if a dose is missed to maintain consistent levels")],
    ["B"],"Levothyroxine (Synthroid) teaching: MECHANISM: synthetic T4 (thyroxine); the body converts T4 to the more active T3 (triiodothyronine) peripherally. Replaces thyroid hormone in hypothyroidism. TIMING: take on an EMPTY STOMACH, 30-60 minutes before breakfast (or before bed if preferred). Consistent timing is important. ABSORPTION INTERACTIONS (space by at least 4 HOURS): CALCIUM supplements (bind levothyroxine in the GI tract), IRON supplements (same), ANTACIDS (aluminum/magnesium hydroxide), PROTON PUMP INHIBITORS (altered gastric pH), cholestyramine/colestipol (bile acid resins), SOY products, coffee, and high-FIBER foods all decrease absorption. EFFECT: takes 4-6 WEEKS for the full effect of a dose adjustment (T4 has a long half-life of 6-7 days). TSH is the best indicator of thyroid replacement adequacy; check 6-8 weeks after dose changes. MONITORING: TSH levels (goal: normal range, usually 0.5-4.5 mIU/L); HYPERTHYROID symptoms (overdose): tachycardia, palpitations, anxiety, insomnia, weight loss, heat intolerance, diarrhea → dose may be too high. HYPOTHYROID symptoms (underdose): fatigue, weight gain, constipation, cold intolerance, dry skin, hair loss → dose may need to increase. BRAND CONSISTENCY: do NOT switch between brands without physician approval and TSH re-check (bioavailability varies between brands). SPECIAL POPULATIONS: start at a LOW dose in elderly and cardiac patients (thyroid hormone increases metabolic rate → increases myocardial oxygen demand → can precipitate angina, MI, or dysrhythmias in patients with underlying cardiac disease).",
    "Levothyroxine: empty stomach 30-60 min before food; avoid calcium, iron, antacids (4 hr gap); same time daily; 4-6 weeks for full effect; don't switch brands", ["levothyroxine","hypothyroidism","empty-stomach","absorption","thyroid"]);

  rn("Neurology","Meningitis Assessment","Physiological Integrity",3,
    "An RN is assessing a patient with suspected bacterial meningitis. Which assessment findings are characteristic of meningeal irritation?",
    [O("A","Meningitis presents only with headache and no other specific signs"),O("B","NUCHAL RIGIDITY (stiff neck - resistance and pain with neck flexion), KERNIG SIGN (patient supine with hip flexed to 90°; attempts to extend the knee cause pain and resistance in the hamstrings), and BRUDZINSKI SIGN (passive flexion of the neck causes involuntary flexion of the hips and knees); additional findings: severe headache, PHOTOPHOBIA (light sensitivity), fever, altered LOC, PETECHIAL RASH (especially with Neisseria meningitidis - meningococcemia); the classic triad of bacterial meningitis: fever, nuchal rigidity, and altered mental status"),O("C","Meningitis causes only GI symptoms like nausea and diarrhea"),O("D","Kernig and Brudzinski signs are cardiac assessment findings")],
    ["B"],"Meningitis assessment: MENINGITIS: inflammation of the meninges (protective membranes surrounding the brain and spinal cord). BACTERIAL meningitis is a medical EMERGENCY with high mortality if untreated. CLASSIC TRIAD: fever + nuchal rigidity + altered mental status (present in approximately 45% of cases; at least 2 of the 3 are present in 95%). MENINGEAL SIGNS (signs of meningeal irritation): NUCHAL RIGIDITY: stiffness and pain with neck flexion (the inflamed meninges are stretched when the neck is flexed forward → pain and involuntary muscle spasm). KERNIG SIGN: patient supine → flex the hip to 90° → attempt to EXTEND the knee → positive = pain and resistance in the hamstrings (extending the leg stretches the inflamed meninges along the spinal cord → pain). BRUDZINSKI SIGN: patient supine → passively FLEX the neck → positive = involuntary flexion of the hips and knees (reflex withdrawal response from meningeal stretching). Both signs have moderate sensitivity but are highly specific for meningeal irritation. OTHER FINDINGS: severe HEADACHE (often described as the worst of their life), PHOTOPHOBIA (light worsens headache), PHONOPHOBIA (sound sensitivity), nausea/vomiting, seizures, PETECHIAL RASH (non-blanching - especially with Neisseria meningitidis → meningococcemia; can rapidly progress to purpura fulminans and DIC). NURSING: DROPLET PRECAUTIONS (for N. meningitidis until 24 hours on antibiotics), dim lighting (photophobia), quiet environment, HOB elevated 30°, seizure precautions, close neurological monitoring, IV antibiotics ASAP (do NOT delay for lumbar puncture results). DIAGNOSIS: lumbar puncture (LP) with CSF analysis: bacterial = elevated WBCs (neutrophils), elevated protein, DECREASED glucose, cloudy/turbulent appearance.",
    "Meningitis: nuchal rigidity + Kernig sign + Brudzinski sign; classic triad: fever, stiff neck, altered LOC; petechial rash (N. meningitidis); droplet precautions; LP for diagnosis", ["meningitis","nuchal-rigidity","Kernig","Brudzinski","bacterial"]);

  rn("Pharmacology","Clozapine Monitoring","Psychosocial Integrity",4,
    "An RN is caring for a patient taking clozapine (Clozaril) for treatment-resistant schizophrenia. Which monitoring requirement is MOST critical and unique to clozapine?",
    [O("A","Clozapine requires no special monitoring beyond other antipsychotics"),O("B","Regular ANC (absolute neutrophil count) monitoring for AGRANULOCYTOSIS: clozapine can cause a dangerous decrease in white blood cells (particularly neutrophils) → the patient becomes severely immunocompromised; monitoring schedule: WEEKLY ANC for the first 6 months, then every 2 WEEKS for months 6-12, then MONTHLY thereafter; clozapine is dispensed through a national registry (Clozapine REMS/CPMS) that requires ANC verification before each dispensing; if ANC drops below 1500 (or 1000 in patients with benign ethnic neutropenia), clozapine must be HELD or DISCONTINUED; also monitor for metabolic syndrome and myocarditis"),O("C","Only liver function tests are needed for clozapine"),O("D","Clozapine monitoring is the same as for haloperidol")],
    ["B"],"Clozapine (Clozaril) unique monitoring: clozapine is an ATYPICAL antipsychotic reserved for TREATMENT-RESISTANT schizophrenia (failed ≥2 adequate trials of other antipsychotics) and for reducing suicidal behavior in schizophrenia/schizoaffective disorder. AGRANULOCYTOSIS: the most serious and unique risk of clozapine (1-2% incidence); loss of neutrophils → severe immunosuppression → life-threatening infections. MONITORING PROTOCOL: Weeks 1-26 (first 6 months): ANC WEEKLY. Weeks 26-52 (months 6-12): ANC every 2 WEEKS. After 12 months: ANC MONTHLY (if ANC has remained normal). CLOZAPINE REMS (Risk Evaluation and Mitigation Strategy) / CPMS (Clozapine Patient Management System): a MANDATORY national registry; the pharmacy CANNOT dispense clozapine without a verified ANC within the required time frame. If patient misses blood work, clozapine cannot be refilled. ANC THRESHOLDS: Normal: ≥2000. GREEN (continue): ≥1500 (or ≥1000 for patients with benign ethnic neutropenia - BEN). YELLOW (increase monitoring to 3×/week): 1000-1499 (500-999 for BEN). RED (DISCONTINUE): <1000 (<500 for BEN). Once discontinued for agranulocytosis, clozapine should NOT be rechallenged. OTHER SIDE EFFECTS: METABOLIC SYNDROME (weight gain - average 4-5 kg in first 10 weeks, hyperglycemia, dyslipidemia → metabolic monitoring at baseline, 3, 6, 12 months, then annually), excessive SEDATION, SIALORRHEA (drooling - paradoxical, opposite of other anticholinergics), orthostatic hypotension, seizures (dose-related), MYOCARDITIS (rare but potentially fatal - monitor for chest pain, tachycardia, fever, especially in first month).",
    "Clozapine: weekly ANC ×6mo, then biweekly, then monthly; agranulocytosis risk; REMS registry mandatory; hold if ANC <1500; also watch for metabolic syndrome, myocarditis", ["clozapine","agranulocytosis","ANC","REMS","treatment-resistant"]);

  // NCLEX-PN Batch 25
  pn("Safety","Latex Allergy LPN","Safe & Effective Care Environment",2,
    "An LPN is admitting a patient who reports a history of allergic reactions to bananas, avocados, and kiwi. Which additional allergy should the LPN screen for?",
    [O("A","These food allergies have no connection to any other allergies"),O("B","Screen for LATEX ALLERGY: there is a well-documented CROSS-REACTIVITY between latex proteins and certain fruits/vegetables (banana, avocado, kiwi, chestnuts, papaya, mango, passion fruit, figs, peaches, tomatoes); this is called LATEX-FRUIT SYNDROME; the LPN should document the food allergies, specifically ask about reactions to latex products (gloves, balloons, rubber bands, elastic waistbands), and ensure the patient is placed in a LATEX-FREE environment if latex allergy is confirmed or suspected (non-latex gloves, latex-free equipment)"),O("C","These foods are allergens but unrelated to any clinical products"),O("D","Only shellfish allergies are relevant in healthcare settings")],
    ["B"],"Latex allergy and latex-fruit syndrome: LATEX: a natural rubber product from the Hevea brasiliensis tree; used extensively in healthcare (gloves, catheters, tourniquets, IV tubing ports, medication vial stoppers, blood pressure cuff tubing, stethoscope tubing). LATEX-FRUIT SYNDROME: cross-reactivity between latex proteins and proteins found in certain fruits and vegetables. ASSOCIATED FOODS (highest cross-reactivity): BANANA, AVOCADO, KIWI, CHESTNUTS. Moderate cross-reactivity: papaya, mango, passion fruit, figs, peaches, tomatoes, potatoes, melon. A patient reporting allergies to multiple foods on this list should be screened for latex allergy. HIGH-RISK GROUPS: healthcare workers (frequent latex glove exposure), patients with spina bifida (frequent catheterizations and surgeries → repeated latex exposure → sensitization), rubber industry workers, patients with multiple allergies or atopy. REACTIONS: Type I (immediate hypersensitivity): urticaria, angioedema, rhinitis, bronchospasm, ANAPHYLAXIS (most serious; occurs within minutes of contact). Type IV (delayed contact dermatitis): redness, itching, cracking of the skin 24-48 hours after contact. NURSING: document the allergy prominently, apply allergy armband, use NON-LATEX alternatives (nitrile or vinyl gloves, silicone catheters, latex-free IV supplies), post a 'Latex Allergy' sign on the door, schedule the patient FIRST in the OR (latex particles from previous procedures can be airborne), ensure epinephrine is available.",
    "Latex-fruit syndrome: banana, avocado, kiwi, chestnuts cross-react with latex; screen for latex allergy; use non-latex products; schedule first in OR; epinephrine available", ["latex-allergy","cross-reactivity","banana-avocado-kiwi","latex-free","anaphylaxis"]);

  pn("Physiological Integrity","Chest Tube Assessment LPN","Physiological Integrity",2,
    "An LPN observes continuous VIGOROUS bubbling in the water seal chamber of a patient's chest drainage system. What does this finding indicate?",
    [O("A","Vigorous continuous bubbling is expected and indicates normal function"),O("B","Continuous vigorous bubbling in the water seal chamber indicates an AIR LEAK somewhere in the system: normal function shows INTERMITTENT (tidaling) bubbling that fluctuates with respiration; continuous vigorous bubbling means air is entering the system; the LPN should systematically check all CONNECTIONS for tightness, inspect the tubing for cracks or disconnections, check the insertion site dressing, and notify the physician; clamp the chest tube briefly at points along the system to isolate the leak location (if bubbling stops when clamped near the patient, the leak is at the insertion site)"),O("C","The drainage system needs to be shaken to stop the bubbling"),O("D","Continuous bubbling means the drainage system should be replaced immediately without assessment")],
    ["B"],"Chest tube drainage system assessment: THREE-CHAMBER SYSTEM: (1) COLLECTION CHAMBER: collects fluid/blood draining from the chest. Normal: monitor output; report >100 mL/hr (may indicate hemorrhage) or sudden cessation (may indicate tube obstruction). (2) WATER SEAL CHAMBER: filled with 2 cm of sterile water; acts as a one-way valve (allows air to exit the chest but prevents air from re-entering). NORMAL: TIDALING (the water level rises with inspiration and falls with expiration in spontaneously breathing patients; opposite in mechanically ventilated patients) - this confirms the tube is patent and the system is functioning. INTERMITTENT bubbling during expiration or coughing is expected with a pneumothorax (air is being evacuated). ABNORMAL: CONTINUOUS VIGOROUS BUBBLING = AIR LEAK. Causes: loose connections in the tubing, crack in the drainage unit, air leak at the insertion site (loose dressing, tube displaced), or continued large air leak from the lung. Troubleshoot: systematically check and tighten all connections, check tubing for cracks, check insertion site dressing, briefly clamp the tube at various points starting nearest the patient (if bubbling stops = leak is between the clamp and the patient; if bubbling continues = leak is between the clamp and the drainage system). ABSENCE of tidaling: may indicate tube obstruction (kinked, clotted) or full lung re-expansion (normal after pneumothorax resolves). (3) SUCTION CONTROL CHAMBER: regulates the amount of suction applied (typically -20 cmH2O); continuous gentle bubbling in this chamber IS normal (indicates the suction level is correct). GENERAL: keep the system BELOW chest level, maintain an upright position, secure all connections, do NOT clamp for extended periods (risk of tension pneumothorax), keep petroleum gauze at bedside (for accidental tube dislodgment - cover the site and tape on 3 sides to create a flutter valve).",
    "Chest tube: continuous vigorous bubbling in water seal = AIR LEAK (check connections); tidaling is normal; suction chamber gentle bubbling = normal; system below chest level", ["chest-tube","water-seal","air-leak","tidaling","drainage-system"]);

  pn("Physiological Integrity","Orthostatic Hypotension LPN","Physiological Integrity",1,
    "An LPN assists a patient to a standing position and the patient becomes dizzy and lightheaded. The LPN suspects orthostatic hypotension. How should the LPN respond?",
    [O("A","Ignore the dizziness as it will pass quickly on its own"),O("B","Assist the patient to SIT or LIE DOWN immediately to prevent a fall; check blood pressure in the lying, sitting, and standing positions (orthostatic hypotension is defined as a drop of ≥20 mmHg SYSTOLIC or ≥10 mmHg DIASTOLIC within 3 MINUTES of standing); teach the patient to change positions SLOWLY (sit on the edge of the bed first, DANGLE the legs for 1-2 minutes before standing, and rise slowly); review medications that may contribute (antihypertensives, diuretics, alpha-blockers, psychotropics, opioids); ensure adequate hydration"),O("C","Encourage the patient to walk quickly to overcome the dizziness"),O("D","Orthostatic hypotension is not a real clinical condition")],
    ["B"],"Orthostatic (postural) hypotension: DEFINITION: a drop in systolic BP ≥20 mmHg or diastolic BP ≥10 mmHg, or an increase in heart rate ≥20 bpm within 3 MINUTES of standing (compared to sitting or supine measurements). MECHANISM: normally, standing causes blood to pool in the lower extremities due to gravity → baroreceptors detect decreased venous return → sympathetic nervous system activates → vasoconstriction + increased HR → maintains BP. In orthostatic hypotension, this compensatory mechanism is impaired or overwhelmed. CAUSES: MEDICATIONS (most common modifiable cause): antihypertensives (especially alpha-blockers, beta-blockers, ACE inhibitors), diuretics (volume depletion), vasodilators (nitroglycerin, PDE5 inhibitors), psychotropic medications (antidepressants, antipsychotics - especially phenothiazines), opioids, and anti-Parkinson drugs. VOLUME DEPLETION: dehydration, hemorrhage, diarrhea, vomiting, excessive diuresis. AGING: decreased baroreceptor sensitivity, decreased vascular tone, decreased cardiac output. PROLONGED BED REST: deconditioning of cardiovascular reflexes. NURSING INTERVENTIONS: (1) SAFETY: assist patient to sit/lie down when symptomatic; fall precautions. (2) TEACH gradual position changes: sit on the edge of the bed → DANGLE legs for 1-2 minutes → stand slowly with support. (3) HYDRATION: ensure adequate fluid intake (unless fluid-restricted). (4) COMPRESSION STOCKINGS: promote venous return. (5) MEDICATION REVIEW: identify contributing medications; administer antihypertensives at bedtime if possible.",
    "Orthostatic hypotension: ≥20 SBP or ≥10 DBP drop within 3 min of standing; dangle legs 1-2 min before standing; review meds; hydrate; compression stockings", ["orthostatic-hypotension","dangle","position-changes","fall-risk","blood-pressure"]);

  // REx-PN Batch 25 - EXCEEDING REx-PN target!
  rpn("Clinical Skills","Specimen Collection Canada","Physiological Integrity",1,
    "An RPN is collecting a midstream urine specimen (clean catch) for culture and sensitivity. Which instruction ensures proper specimen collection?",
    [O("A","Collect the first part of the urine stream for the most concentrated sample"),O("B","Clean the urethral meatus with antiseptic wipes (front to back for females, circular motion from the meatus outward for males); begin voiding into the toilet (the FIRST stream flushes bacteria from the distal urethra), then collect the MIDSTREAM portion in the STERILE specimen container WITHOUT interrupting the urine stream; cap the container immediately; label with patient identifiers, date, and time; transport to the laboratory within 30 minutes or refrigerate (prevents bacterial multiplication that would falsely elevate colony counts)"),O("C","Any clean container can be used for urine culture specimens"),O("D","The entire void should be collected in the specimen container")],
    ["B"],"Midstream urine (clean catch) specimen collection: PURPOSE: obtain an uncontaminated urine sample for culture and sensitivity (C&S) testing to identify the causative organism and determine antibiotic susceptibility. CONTAMINATION PREVENTION: the distal urethra and periurethral area harbor normal flora bacteria; without proper technique, these bacteria contaminate the specimen → false-positive culture results → unnecessary antibiotic treatment. TECHNIQUE: (1) FEMALE: separate the labia with the non-dominant hand and KEEP THEM SEPARATED throughout the procedure. Cleanse the urethral meatus with antiseptic wipes (or sterile water per facility protocol): wipe FRONT TO BACK (3 swipes: left labial fold, right labial fold, center/meatus), using a new wipe for each stroke. (2) MALE: retract the foreskin if uncircumcised (keep retracted throughout). Cleanse the meatus with antiseptic wipes using a CIRCULAR motion from the meatus outward. (3) COLLECT: begin voiding into the TOILET (first 30 mL flushes distal urethral bacteria). Without stopping the stream, move the STERILE container into the stream and collect the MIDSTREAM portion (30-60 mL). Remove the container before the stream ends (terminal urine may contain prostatic fluid or sediment). (4) CAP the container immediately (prevent environmental contamination). (5) LABEL with patient identifiers (at least two), date, time, source (midstream clean catch). (6) TRANSPORT to the laboratory WITHIN 30 MINUTES (or refrigerate at 4°C for up to 24 hours); delay allows bacterial multiplication → falsely elevated colony counts → inaccurate results.",
    "Clean catch: cleanse meatus (front to back female), void initial stream to toilet, collect midstream in sterile container, transport within 30 min or refrigerate", ["clean-catch","urine-specimen","midstream","culture","technique"]);

  rpn("Safety","CCAC Home Care Canada","Safe & Effective Care Environment",2,
    "An RPN working in home care through the local Home and Community Care Support Services (formerly CCAC/LHIN) is visiting a patient who lives alone with mobility limitations. Which assessment is PRIORITY during the home visit?",
    [O("A","Only assess the patient's medication regimen"),O("B","Perform a comprehensive HOME SAFETY ASSESSMENT: evaluate the home environment for fall hazards (loose rugs, clutter, poor lighting, uneven surfaces, absence of grab bars in the bathroom), assess the adequacy of the patient's support network (family, community services, personal support workers), verify medication safety (proper storage, ability to self-administer, correct medications and doses), assess nutritional status and food accessibility, evaluate the patient's ability to manage activities of daily living independently, and determine if the level of care and services is adequate to maintain safety"),O("C","The home environment does not need to be assessed"),O("D","Only assess the patient's surgical wound if applicable")],
    ["B"],"Home care assessment in Ontario: Home and Community Care Support Services (HCCSS, formerly Community Care Access Centres/CCAC and Local Health Integration Networks/LHIN home care services) coordinate and deliver publicly funded home care services. RPN ROLE in home care: RPNs provide direct nursing care in the patient's home, functioning more autonomously than in institutional settings. HOME SAFETY ASSESSMENT (priority for patients living alone with mobility limitations): ENVIRONMENT: fall hazards (loose RUGS, CLUTTER on pathways, electrical CORDS, wet/slippery surfaces, uneven surfaces, thresholds, STAIRS without railings), LIGHTING (adequate in hallways, stairwells, bathrooms, nightlights), GRAB BARS in the bathroom (near toilet and in shower/tub), non-slip bath mats, raised toilet seat if needed, smoke/CO detectors working, adequate heating/cooling, accessibility of phone (for emergencies). MEDICATION SAFETY: proper STORAGE (locked if children visit, appropriate temperature), ability to self-administer (can the patient open bottles, read labels, draw up insulin?), medication organizer (dosette/blister packs may improve compliance), check for expired medications, reconcile with physician orders. NUTRITION: food availability, ability to prepare meals, programs like Meals on Wheels, nutritional adequacy. SUPPORT NETWORK: availability of family, friends, neighbors; PSW services (personal care, light housekeeping); Meals on Wheels, transportation services, community programs. FUNCTIONAL STATUS: ADL and IADL assessment; cognitive status; fall risk. EMERGENCY PLAN: personal emergency response system (Lifeline button), emergency contacts posted.",
    "Home care: priority = home safety assessment (falls, lighting, grab bars, meds, nutrition, support network); RPNs practice more autonomously in community settings", ["home-care","safety-assessment","HCCSS","fall-hazards","community-nursing"]);

  rpn("Pharmacology","Antihypertensive Canada","Physiological Integrity",2,
    "An RPN is monitoring a patient who was started on ramipril (Altace), an ACE inhibitor, for hypertension. Which side effect should the RPN assess for and report immediately?",
    [O("A","ACE inhibitors have no side effects requiring monitoring"),O("B","Assess for ANGIOEDEMA: swelling of the face, lips, tongue, and throat that can cause AIRWAY OBSTRUCTION; this is a rare but potentially FATAL adverse effect of ACE inhibitors caused by bradykinin accumulation; it can occur at any time during therapy (even after years of use); if angioedema is observed, STOP the ACE inhibitor permanently, maintain airway, administer epinephrine if severe, and the patient should NEVER receive an ACE inhibitor again; also monitor for persistent DRY COUGH (common, caused by bradykinin), hyperkalemia, and first-dose hypotension"),O("C","Only blood pressure needs to be monitored"),O("D","Angioedema only occurs within the first hour of the first dose")],
    ["B"],"ACE inhibitor angioedema: MECHANISM: ACE normally breaks down bradykinin; ACE inhibitors block this degradation → bradykinin accumulates → vasodilation and increased vascular permeability → edema of the subcutaneous and submucosal tissues, particularly in the face, lips, tongue, and THROAT (oropharyngeal/laryngeal edema). INCIDENCE: 0.1-0.7% of patients taking ACE inhibitors; higher incidence in Black patients (up to 3-4 times higher), smokers, and patients with previous angioedema. TIMING: can occur within hours of the first dose OR after YEARS of therapy (this unpredictability is why nurses must always assess for it). PRESENTATION: swelling of the face (periorbital), LIPS, TONGUE, and THROAT; can progress rapidly to AIRWAY OBSTRUCTION. Distinguished from urticaria (angioedema involves deeper tissues; urticaria is superficial). MANAGEMENT: (1) STOP the ACE inhibitor permanently. (2) Maintain AIRWAY: prepare for possible intubation; severe cases may require emergency cricothyrotomy/tracheotomy. (3) EPINEPHRINE for severe reactions with airway compromise. (4) Consider: icatibant (bradykinin B2 receptor antagonist) or C1 esterase inhibitor concentrate for ACE inhibitor-induced angioedema that does not respond to standard treatment (antihistamines and steroids are often INEFFECTIVE because the mechanism is bradykinin-mediated, not histamine-mediated). (5) The patient must NEVER receive ANY ACE inhibitor again; ARBs may be used cautiously as an alternative (small cross-reactivity risk). In Canada, pharmacist-prescribed and physician-prescribed ACE inhibitors are among the most common medication classes; awareness of angioedema is critical for all nurses.",
    "ACE inhibitor angioedema: can occur ANY time (even years later); face, lips, tongue, throat swelling → airway obstruction; STOP permanently; higher risk in Black patients; antihistamines often ineffective", ["angioedema","ACE-inhibitor","ramipril","airway-obstruction","bradykinin"]);

  return qs;
}

async function main(){
  console.log("=== Massive Batch 25 ===\n");
  const before=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("BEFORE:");for(const r of before.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const allQs=build();const bk:Record<string,number>={};for(const q of allQs)bk[q.exam]=(bk[q.exam]||0)+1;
  console.log(`\nGenerated ${allQs.length} total:`,bk);
  let ins=0,dup=0,err=0;
  for(const q of allQs){const h=sh(q.stem);try{const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 AND tier=$2 AND exam=$3 LIMIT 1`,[h,q.tier,q.exam]);if(ex.rows.length>0){dup++;continue;}await pool.query(`INSERT INTO exam_questions(id,tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,tags,body_system,topic,subtopic,region_scope,stem_hash,scenario,clinical_pearl,exam_strategy,clinical_trap,distractor_rationales,career_type,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,'MCQ','published',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'nursing',NOW(),NOW())`,[q.tier,q.exam,q.stem,JSON.stringify(q.options),JSON.stringify(q.ca),q.rat,q.diff,q.tags,q.bs,q.topic,q.sub,q.rs,h,q.stem.substring(0,120),q.cp,"Select the evidence-based answer","Avoid outdated or harmful practices",JSON.stringify({A:"Incorrect",C:"Inappropriate",D:"Harmful"})]);ins++;}catch(e:any){err++;console.error(`ERR: ${e.message.substring(0,100)}`);}}
  console.log(`\nInserted: ${ins}, Duplicates: ${dup}, Errors: ${err}`);
  const after=await pool.query(`SELECT tier,exam,COUNT(*)::int as c FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') GROUP BY tier,exam ORDER BY tier,exam`);
  console.log("\nAFTER:");for(const r of after.rows)console.log(`  ${r.tier}/${r.exam}: ${r.c}`);
  const session=await pool.query(`SELECT exam,COUNT(*)::int as cnt FROM exam_questions WHERE tier IN('rpn','rn') AND exam IN('REx-PN','NCLEX-PN','NCLEX-RN') AND created_at>NOW()-INTERVAL '24 hours' GROUP BY exam ORDER BY exam`);
  console.log("\nSession totals:");for(const r of session.rows)console.log(`  ${r.exam}: ${r.cnt}`);
  await pool.end();
  console.log("\n=== Done! ===");
}
main().catch(e=>{console.error("Fatal:",e);process.exit(1);});
