/**
 * NCLEX-PN blueprint gap closure — flashcard sets for 10 gap topics.
 * 20 cards per topic: recall, application, prioritization, pharmacology, clinical judgment.
 * Topics: Ethics, Client Education, DVT, Respiratory Failure, Oxygen Therapy,
 *         Diabetes, Hyperglycemia, Diuretics, Cardiac Medications, Medication Administration.
 */

export type PnGapFlashcard = {
  id: string;
  topic: string;
  lessonSlug: string;
  exam: "NCLEX-PN";
  cardType: "recall" | "application" | "prioritization" | "pharmacology" | "clinical-judgment";
  difficulty: 1 | 2 | 3;
  front: string;
  back: string;
  weakAreaTag: string;
  studyPlanMapping: string;
};

export const NCLEX_PN_GAP_FLASHCARDS: readonly PnGapFlashcard[] = [

// ═══════════════════════════════════════════════════════════════════════════
// ETHICS & PROFESSIONAL STANDARDS (20 cards)
// ═══════════════════════════════════════════════════════════════════════════
{ id:"pn-eth-fc-01", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the 6 core ethical principles in nursing?", back:"Autonomy (self-determination), Beneficence (do good), Nonmaleficence (do no harm), Justice (fairness), Fidelity (keep promises), Veracity (truth-telling).", weakAreaTag:"ethical-principles", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-02", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A competent adult patient refuses a blood transfusion due to religious beliefs. The PN's action is:", back:"Respect the decision. Document the refusal. Notify the provider. Do NOT persuade, override, or contact family without the patient's consent. Autonomy is paramount for cognitively intact adults.", weakAreaTag:"patient-autonomy", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-03", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Who is responsible for obtaining informed consent from a patient?", back:"The provider (physician, NP, PA) — NOT the nurse. The PN may witness the patient's signature but cannot ensure or substitute for the provider's explanation of risks, benefits, and alternatives.", weakAreaTag:"informed-consent", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-04", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"A patient expresses uncertainty about a procedure they already signed consent for. PN action?", back:"STOP the procedure. Notify the provider immediately. The patient's uncertainty suggests the consent may not have been fully informed. The provider must re-educate and re-consent before proceeding.", weakAreaTag:"informed-consent", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-05", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the exceptions to patient confidentiality (HIPAA)?", back:"1) Mandatory reporting: abuse/neglect, certain infectious diseases, gunshot wounds. 2) Imminent threat to self or others (duty to warn/protect). 3) Court orders. 4) Public health reporting. All other sharing requires patient authorization.", weakAreaTag:"hipaa-exceptions", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-06", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A colleague posts a story about a 'difficult patient' on social media with no name but includes the diagnosis and unusual case details. PN action?", back:"Report to charge nurse or facility compliance officer immediately. HIPAA is violated when identifiable health information is shared, even without a name. Social media posting of patient details violates HIPAA regardless of name omission.", weakAreaTag:"social-media-hipaa", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-07", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Who are mandated reporters, and what triggers mandatory reporting?", back:"All nurses are mandated reporters. Report: suspected (not confirmed) child abuse/neglect, elder/vulnerable adult abuse, and state-listed communicable diseases. The PN reports suspicion — investigation is done by appropriate authorities, not the nurse.", weakAreaTag:"mandatory-reporting", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-08", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:3, front:"A PN suspects a colleague is diverting controlled substances. Appropriate action?", back:"Report immediately to the charge nurse or supervisor — do NOT confront the colleague, investigate independently, or wait for more evidence. Drug diversion is a patient safety and criminal issue requiring immediate reporting. The PN does not self-investigate.", weakAreaTag:"drug-diversion-reporting", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-09", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"How is an error corrected in a handwritten medical record?", back:"Draw a single line through the error (keeping it legible), write 'error,' add your initials and the date, then write the correct information. NEVER use white-out, scribble out, or alter entries to make the original illegible.", weakAreaTag:"documentation-error-correction", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-10", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A provider orders a nurse to perform a task that is outside the PN's scope. Correct action?", back:"Refuse the task. Explain that it is outside current PN scope/competency. Notify the charge RN. Document the refusal. The PN cannot perform tasks beyond their scope even when ordered by a provider. Scope is determined by the Nurse Practice Act, not physician orders.", weakAreaTag:"scope-of-practice", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-11", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the difference between negligence and malpractice?", back:"Negligence: failing to act as a reasonable person would. Malpractice: professional negligence — failure of a licensed professional to meet the standard of care expected in their field. Both can result in civil liability; malpractice is specific to professional conduct.", weakAreaTag:"negligence-malpractice", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-12", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:2, front:"What is the hierarchy of surrogate decision-makers when a patient lacks capacity and has no advance directive?", back:"Spouse → adult children → parents → adult siblings. The closest legally recognized next of kin makes decisions in this order. A court-appointed guardian supersedes all family members.", weakAreaTag:"surrogate-decision-maker", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-13", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"prioritization", difficulty:2, front:"A patient's advance directive says 'Do Not Resuscitate.' The family insists on CPR. The PN's priority action?", back:"Follow the advance directive — it is a legal document representing the patient's autonomous wishes. Notify the charge RN and attending provider immediately. Do NOT override a valid DNR at family request. Escalate to the ethics committee if conflict persists.", weakAreaTag:"advance-directive-enforcement", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-14", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is an occurrence/incident report, and is it part of the medical record?", back:"An incident report documents safety events (falls, errors, near-misses, patient injuries) for quality improvement and risk management. It is NOT part of the medical record and should NOT be referenced in chart notes. It does not replace accurate charting of the event.", weakAreaTag:"incident-report", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-15", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:3, front:"Family members of a cognitively intact patient request that the diagnosis not be shared with the patient 'to protect them.' The PN's response?", back:"The cognitively intact patient has the right to receive information about their health. The PN does not confirm the diagnosis (provider's scope) but escalates: inform the RN and provider of the family request immediately, advocate for the patient's right to know, and document. The PN does NOT withhold information on behalf of the family.", weakAreaTag:"truthful-disclosure-autonomy", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-16", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is 'veracity' as an ethical principle, and when is it most relevant for the PN?", back:"Veracity = truthfulness. Relevant when: documenting accurately, correcting patient misconceptions, not falsifying records, not deceiving patients or families. A nurse who charts events that did not occur or omits errors violates veracity and commits fraud.", weakAreaTag:"veracity-truthfulness", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-17", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on a medical floor calls the PN to say they smell alcohol on a nurse who just cared for them. What should the PN do?", back:"Take the report seriously. Notify the charge nurse immediately. The charge nurse will assess the staff member according to facility policy (typically remove them from patient care pending evaluation). Impaired nursing practice is a patient safety emergency requiring immediate escalation.", weakAreaTag:"impaired-nurse-reporting", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-18", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is 'justice' as an ethical principle in nursing practice?", back:"Justice = treating all patients fairly, equitably, and without discrimination regardless of race, religion, socioeconomic status, sexual orientation, insurance status, or diagnosis. The PN advocates for equitable care and reports disparities in treatment to the charge RN.", weakAreaTag:"justice-equitable-care", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-19", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"A PN receives a telephone order from a physician: 'Give morphine 8 mg IV now.' The PN thinks this dose is too high. Correct action?", back:"Question the order BEFORE administering. Call the provider back: 'I want to clarify the morphine order — the usual dose in our protocol is 2–4 mg IV. Can you confirm 8 mg is intended?' Document the clarification and confirmed/corrected order. Administering a dose you believe is unsafe without questioning is a violation of professional duty.", weakAreaTag:"questioning-unsafe-orders", studyPlanMapping:"ethics-professional-standards" },
{ id:"pn-eth-fc-20", topic:"Ethics", lessonSlug:"us-pn-ethics-professional-standards", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are acceptable times to share patient information without explicit patient authorization?", back:"1) Other members of the care team directly involved in the patient's care. 2) Mandatory reporting (abuse, reportable diseases). 3) Court orders/subpoenas. 4) Imminent threat to self or others. Family members who are NOT the patient's designated surrogate require authorization even in emergencies.", weakAreaTag:"hipaa-sharing-rules", studyPlanMapping:"ethics-professional-standards" },

// ═══════════════════════════════════════════════════════════════════════════
// DVT (20 cards)
// ═══════════════════════════════════════════════════════════════════════════
{ id:"pn-dvt-fc-01", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the three components of Virchow's Triad?", back:"1) Venous stasis (immobility, HF, pregnancy), 2) Endothelial injury (surgery, IV catheter, trauma), 3) Hypercoagulability (cancer, OCP, inherited thrombophilias). All three increase DVT risk; cancer is the highest medical risk factor.", weakAreaTag:"virchows-triad", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-02", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the classic signs and symptoms of DVT?", back:"Unilateral leg swelling, warmth, erythema along the vein, and calf/thigh pain/tenderness. NOTE: Up to 50% of DVTs are asymptomatic. DVT is characteristically UNILATERAL — bilateral swelling suggests systemic causes (HF, hypoalbuminemia).", weakAreaTag:"dvt-signs-symptoms", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-03", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"A patient with DVT complains of sudden dyspnea, chest pain worsening with inspiration, and O₂ sat 89%. PN action?", back:"CALL RAPID RESPONSE immediately. This is pulmonary embolism (PE) until proven otherwise. Stay with patient. Apply O₂ (NRB). Position: high Fowler's. Notify provider. Prepare for CTPA and anticoagulation. PE is a life-threatening emergency.", weakAreaTag:"pulmonary-embolism-recognition", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-04", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"What is the therapeutic INR range for DVT treatment with warfarin?", back:"2.0–3.0. Below 2.0 = subtherapeutic (clot propagation risk → hold warfarin adjustment). Above 3.0 = supratherapeutic (bleeding risk). INR must be checked regularly. Warfarin requires 2–5 days to reach therapeutic effect — bridge with heparin/LMWH until INR is 2.0–3.0 for 2 consecutive days.", weakAreaTag:"warfarin-inr-target", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-05", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"prioritization", difficulty:1, front:"A patient with DVT is scheduled for ambulation. The PN should:", back:"Encourage and assist with ambulation as tolerated. Ambulation is NOT contraindicated with DVT on anticoagulation — in fact, prolonged bed rest worsens venous stasis and is the wrong approach. The PN removes the SCD for ambulation and replaces it when the patient returns to bed.", weakAreaTag:"dvt-ambulation", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-06", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the FIRST-LINE diagnostic test for suspected DVT?", back:"Compression ultrasound (duplex ultrasound) — non-invasive, >95% sensitivity for proximal DVT. A thrombosed vein does not compress. D-dimer is used to RULE OUT DVT (not rule in) when pre-test probability is low.", weakAreaTag:"dvt-diagnosis-ultrasound", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-07", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"What is Homan's sign, and is it reliable for DVT diagnosis?", back:"Homan's sign = calf pain on dorsiflexion of the foot. NOT reliable — low sensitivity AND low specificity. Many false positives (muscle cramps, Baker's cyst). Not used clinically for DVT diagnosis. On NCLEX: 'Homan's sign is unreliable' is the correct answer when asked about its value.", weakAreaTag:"homans-sign-unreliable", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-08", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:3, front:"What is heparin-induced thrombocytopenia (HIT), and why is it paradoxically dangerous?", back:"HIT: immune-mediated platelet drop >50% between days 5–14 of heparin. Paradoxical: despite LOW platelets, the risk is THROMBOSIS (not bleeding). Action: stop ALL heparin (including flushes), switch to non-heparin anticoagulant (argatroban/fondaparinux). NO platelet transfusions — worsens clotting.", weakAreaTag:"hit-heparin-thrombocytopenia", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-09", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"Enoxaparin (Lovenox) — key PN administration facts:", back:"Route: subcutaneous only (never IV push). Inject into abdominal fat — do NOT expel the air bubble from prefilled syringe (it prevents medication loss). Rotate sites. Dose-reduce with CrCl <30 mL/min. Partial reversal: protamine sulfate. Monitor anti-Xa level (not aPTT) when monitoring is required.", weakAreaTag:"enoxaparin-administration", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-10", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"Which action does the PN NEVER perform in a patient with DVT?", back:"NEVER massage the affected limb — can dislodge the thrombus causing pulmonary embolism. Also never apply SCD to a limb with known DVT (same risk). These are always the WRONG answer on NCLEX when DVT is present.", weakAreaTag:"dvt-contraindications", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-11", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is post-thrombotic syndrome?", back:"Chronic venous insufficiency from DVT valve damage → persistent leg swelling, pain, skin changes (hyperpigmentation, lipodermatosclerosis), and venous stasis ulcers. Prevention: graded compression stockings after DVT, adequate anticoagulation, early ambulation.", weakAreaTag:"post-thrombotic-syndrome", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-12", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"prioritization", difficulty:2, front:"A post-op hip replacement patient on day 2 has right calf swelling 3 cm greater than left, warmth, and tenderness. What does the PN do FIRST?", back:"Do NOT massage. Notify charge RN and provider immediately. Document exact circumference measurements. Monitor O₂ sat, HR, and breathing for signs of PE. Do NOT apply SCD to the affected leg. Anticipate order for compression ultrasound.", weakAreaTag:"dvt-assessment-escalation", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-13", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What do anticoagulants DO and DO NOT do for existing DVT?", back:"DO: Prevent clot propagation (extension). Prevent new clot formation. Prevent PE from existing clot. DO NOT: Dissolve the existing clot (that requires thrombolytics). The body's own fibrinolytic system (plasmin) dissolves the existing clot over time.", weakAreaTag:"anticoagulant-mechanism", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-14", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on warfarin for DVT says they've been taking ibuprofen for back pain. Why is this concerning?", back:"NSAIDs (ibuprofen) increase bleeding risk and can displace warfarin from plasma protein binding → INR rises → increased hemorrhage risk. NSAIDs also cause GI irritation and GI bleeding. The PN notifies the provider for assessment and possible INR recheck.", weakAreaTag:"warfarin-nsaid-interaction", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-15", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What DVT prophylaxis measures are standard for high-risk hospitalized patients?", back:"1) Sequential compression devices (SCDs) while in bed. 2) Early ambulation post-operatively. 3) Pharmacologic prophylaxis: low-dose LMWH (enoxaparin 40 mg SQ daily) or unfractionated heparin (5000 units SQ BID/TID). 4) Adequate hydration. 5) Avoid prolonged immobility.", weakAreaTag:"dvt-prophylaxis", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-16", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"What is the aPTT therapeutic range for IV unfractionated heparin (UFH)?", back:"60–100 seconds (1.5–2.5× the control value). Monitor q6h during infusion and after dose changes. Subtherapeutic: clot propagation risk. Supratherapeutic: bleeding risk. Reversal: protamine sulfate. HIT monitoring: check platelet count daily.", weakAreaTag:"heparin-aptt-monitoring", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-17", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"When is a D-dimer test most useful in DVT diagnosis?", back:"D-dimer is useful to RULE OUT DVT when pretest probability is LOW (Wells score <2). A NEGATIVE D-dimer + low clinical probability = DVT very unlikely → no ultrasound needed. A POSITIVE D-dimer does NOT confirm DVT (many conditions elevate it: surgery, infection, cancer, pregnancy).", weakAreaTag:"d-dimer-interpretation", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-18", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"When applying SCDs for DVT prophylaxis, what is the key assessment before application?", back:"Confirm the limb does NOT have a known DVT. Applying SCDs to a limb with DVT can compress the thrombus and cause PE. Also assess: skin integrity (do not apply over active wounds or skin breakdown), and ensure proper fit (too tight → impairs venous return; too loose → no effect).", weakAreaTag:"scds-application-safety", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-19", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"prioritization", difficulty:3, front:"A patient is on heparin for DVT. Platelet count drops from 310,000 to 94,000 on day 8. Priority action?", back:"Suspect HIT. STOP all heparin immediately (IV infusion, SQ doses, heparin flushes, heparin-coated devices). Notify provider STAT. Anticipate order for non-heparin anticoagulant (argatroban). Do NOT give platelet transfusions. Monitor for arterial and venous thrombosis (HIT is prothrombotic).", weakAreaTag:"hit-management", studyPlanMapping:"dvt-deep-vein-thrombosis" },
{ id:"pn-dvt-fc-20", topic:"DVT", lessonSlug:"us-pn-dvt-deep-vein-thrombosis", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Which patient characteristic represents the HIGHEST risk for DVT?", back:"Active malignancy (cancer) is the single highest medical risk factor. Cancer promotes hypercoagulability through tumor procoagulants, reduced activity, and treatment effects. Pancreatic, ovarian, and lung cancers carry especially high thrombosis risk.", weakAreaTag:"dvt-highest-risk-cancer", studyPlanMapping:"dvt-deep-vein-thrombosis" },

// ═══════════════════════════════════════════════════════════════════════════
// DIURETICS (20 cards)
// ═══════════════════════════════════════════════════════════════════════════
{ id:"pn-diur-fc-01", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the three classes of diuretics and their sites of action?", back:"1) Loop diuretics (furosemide): thick ascending loop of Henle — most potent, lose K⁺/Mg²⁺/Ca²⁺. 2) Thiazides (HCTZ): distal convoluted tubule — moderate, lose K⁺, retain Ca²⁺. 3) Potassium-sparing (spironolactone): collecting duct — weak diuresis, RETAIN K⁺.", weakAreaTag:"diuretic-classes-mechanism", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-02", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"A patient on furosemide and digoxin has K⁺ 3.1 mEq/L. Action?", back:"HOLD furosemide AND digoxin. Notify provider immediately. Hypokalemia sensitizes the myocardium to digoxin → toxicity risk even at therapeutic levels. Anticipate: KCl replacement order. Do not resume either medication until K⁺ is corrected and provider re-orders.", weakAreaTag:"furosemide-digoxin-hypokalemia", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-03", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:1, front:"Furosemide (Lasix) — IV onset and nursing priority check before administration:", back:"IV onset: 5 minutes. Before giving: Check BP (hold if SBP <90), check K⁺ (hold if <3.0 mEq/L), assess for signs of dehydration. Give IV push no faster than 20 mg/min (to prevent ototoxicity). Monitor urine output — expect ≥200 mL in first hour after IV dose for HF.", weakAreaTag:"furosemide-administration", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-04", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Why is furosemide given in the morning (not at bedtime)?", back:"Diuretics cause increased urinary output during their peak effect (furosemide oral: 1–2 hours, lasting 6–8 hours). Evening/bedtime dosing causes nocturia — frequent nighttime urination → sleep disruption and fall risk. Always schedule diuretics for morning or early afternoon.", weakAreaTag:"diuretic-timing", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-05", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on spironolactone (Aldactone) says they use salt substitutes instead of table salt. What is the concern?", back:"Salt substitutes contain potassium chloride (KCl) instead of sodium chloride. Spironolactone is a potassium-sparing diuretic → retains K⁺. Combining with KCl-containing salt substitutes risks severe hyperkalemia. Educate: avoid potassium-containing salt substitutes and K⁺ supplements unless ordered.", weakAreaTag:"spironolactone-hyperkalemia-food", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-06", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What electrolyte does thiazide therapy RETAIN (opposite of loop diuretics)?", back:"Calcium. Thiazide diuretics enhance calcium reabsorption in the distal tubule → decreased urine calcium. Clinical use: thiazides are prescribed to PREVENT kidney stones in patients with hypercalciuria. Loop diuretics INCREASE calcium excretion (hypocalcemia risk).", weakAreaTag:"thiazide-calcium-retention", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-07", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"prioritization", difficulty:2, front:"A patient on daily furosemide gains 4 pounds overnight. What does this indicate and what does the PN do?", back:"4 lbs overnight ≈ ~2L fluid retention → heart failure exacerbation. Assess: crackles, JVD, worsening dyspnea. Notify provider immediately with SBAR (weight, symptoms, vitals). Anticipate: increased furosemide dose or IV furosemide. Document all findings.", weakAreaTag:"weight-gain-hf-diuretic", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-08", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"Spironolactone — mechanism, primary uses, and key side effects:", back:"Mechanism: aldosterone antagonist → blocks Na retention and K excretion at collecting duct. Uses: HFrEF (proven mortality reduction), hyperaldosteronism, cirrhosis/ascites. Side effects: HYPERKALEMIA (monitor K⁺ weekly initially), gynecomastia in men (anti-androgenic), impotence. Contraindicated if K⁺ >5.5 mEq/L or CrCl <30.", weakAreaTag:"spironolactone-overview", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-09", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Signs of over-diuresis (dehydration from excessive diuretic effect):", back:"Orthostatic hypotension (dizziness on standing), rapid weight loss (>2–3 lbs/day), poor skin turgor, dry mucous membranes, concentrated urine, rising BUN and creatinine (prerenal azotemia), decreasing urine output. Notify provider if signs present; hold diuretic.", weakAreaTag:"over-diuresis-signs", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-10", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on HCTZ reports a painful swollen big toe. What diuretic complication does this represent?", back:"Gout attack from HCTZ-induced hyperuricemia. Thiazide diuretics block uric acid secretion → uric acid accumulates → urate crystal deposition in joints. Big toe (podagra) is the most common site. Notify provider: may need to switch diuretic class or add urate-lowering therapy.", weakAreaTag:"thiazide-gout-hyperuricemia", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-11", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:3, front:"IV potassium chloride (KCl) is ordered for a patient with hypokalemia from furosemide. Key PN safety rules:", back:"NEVER give IV KCl as bolus (causes cardiac arrest). Must always be diluted. Central line preferred for rates >10 mEq/hr. Peripheral IV: maximum 10 mEq/hr in dilute solution. Always monitor cardiac rhythm during infusion. Assess IV site frequently — KCl is a vesicant.", weakAreaTag:"iv-potassium-safety", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-12", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What electrolyte imbalances does furosemide cause? (List the four major ones)", back:"1) Hypokalemia (K⁺ <3.5 → arrhythmias), 2) Hypomagnesemia (Mg <1.5 → arrhythmias, worsens hypokalemia), 3) Hypocalcemia (Ca²⁺ decreased — loops lose calcium), 4) Hyponatremia (Na⁺ loss with large volume depletion). Monitor all four electrolytes in patients on loop diuretics.", weakAreaTag:"furosemide-electrolyte-losses", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-13", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"What is ototoxicity from loop diuretics, and how is it prevented?", back:"Hearing loss/tinnitus from high-dose IV loop diuretics (especially furosemide). Risk increases with: high IV doses, rapid infusion, concurrent aminoglycosides (gentamicin, tobramycin). Prevention: administer IV furosemide no faster than 20 mg/min; avoid concurrent ototoxic drugs; monitor for patient complaints of tinnitus.", weakAreaTag:"furosemide-ototoxicity", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-14", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient asks why they need to weigh themselves every morning on their diuretic. What is the PN's explanation?", back:"Daily weight is the most sensitive measure of fluid status. 1 kg (2.2 lbs) weight change = approximately 1L fluid change. Weighing at the same time (morning, after urinating, before eating, same scale) ensures accurate comparison. Weight gain >2 lbs/day or >5 lbs/week should be reported to the provider immediately.", weakAreaTag:"daily-weight-fluid-monitoring", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-15", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Which diuretic class is first-line for hypertension per JNC guidelines?", back:"Thiazide diuretics (hydrochlorothiazide, chlorthalidone). Chlorthalidone is preferred over HCTZ for hypertension due to longer duration (24h vs 12h) and proven cardiovascular outcome benefit. Thiazides are less effective in patients with GFR <30 mL/min — use loop diuretics instead.", weakAreaTag:"thiazide-first-line-htn", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-16", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"prioritization", difficulty:3, front:"A patient on furosemide for HF has urine output of 30 mL over the past 2 hours despite an IV dose 1.5 hours ago. Action?", back:"Notify provider immediately. Oliguria (<0.5 mL/kg/hr) despite IV diuretic indicates: inadequate cardiac output (worsening HF), severe volume depletion, or acute renal failure. The provider must reassess the clinical picture — may need higher dose, different agent, or fluid bolus if dehydrated.", weakAreaTag:"oliguria-furosemide-response", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-17", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What fall prevention measures are critical for patients on diuretics?", back:"1) Teach patient to change positions slowly (sit at edge of bed 1 minute before standing — orthostatic hypotension prevention). 2) Keep call light within reach. 3) Bed in lowest position. 4) Non-slip footwear. 5) Ensure access to urinal/commode during peak diuretic effect. 6) Schedule diuretics in morning to avoid nighttime trips.", weakAreaTag:"diuretic-fall-prevention", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-18", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"Why do loop diuretics remain effective in patients with renal failure, while thiazides do not?", back:"Loop diuretics act on the thick ascending limb of Henle — this tubular segment remains functional even with reduced GFR. Thiazides require adequate GFR (>30–40 mL/min) to reach their site of action in the distal tubule; below this threshold, they are ineffective. Exception: metolazone (thiazide-like) retains efficacy at lower GFR.", weakAreaTag:"renal-failure-diuretic-selection", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-19", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:1, front:"What foods are high in potassium? When should patients on loop diuretics eat more of these?", back:"High-potassium foods: bananas, oranges, potatoes, avocados, beans/lentils, spinach, cantaloupe, tomatoes, dairy, dried fruits. Patients on loop diuretics should eat potassium-rich foods regularly to compensate for urinary K⁺ loss. Supplement if K⁺ remains low despite dietary intake.", weakAreaTag:"potassium-rich-foods", studyPlanMapping:"diuretics" },
{ id:"pn-diur-fc-20", topic:"Diuretics", lessonSlug:"us-pn-diuretics-pharmacology", exam:"NCLEX-PN", cardType:"recall", difficulty:2, front:"Spironolactone's unique benefit in heart failure beyond diuresis:", back:"Spironolactone (and eplerenone) reduces mortality and hospitalizations in HFrEF independent of its diuretic effect. It acts on aldosterone receptors in the heart, reducing cardiac remodeling, fibrosis, and ventricular hypertrophy. This is why it is used in HF at doses lower than those needed for diuresis.", weakAreaTag:"spironolactone-hf-mortality", studyPlanMapping:"diuretics" },

// ═══════════════════════════════════════════════════════════════════════════
// CARDIAC MEDICATIONS (20 cards)
// ═══════════════════════════════════════════════════════════════════════════
{ id:"pn-cardiac-fc-01", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the therapeutic serum digoxin level range?", back:"0.5–2.0 ng/mL. For heart failure with reduced EF, the optimal range is 0.5–0.9 ng/mL (lower is safer). Levels >2.0 ng/mL = toxicity territory. Draw the level ≥8 hours after the last oral dose for accurate assessment.", weakAreaTag:"digoxin-therapeutic-level", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-02", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"Classic triad of digoxin toxicity:", back:"1) GI: anorexia, nausea, vomiting. 2) Visual: yellow-green (xanthopsia) or blurred vision, halos around lights. 3) Cardiac: bradycardia, AV block, ventricular arrhythmias (bigeminy, ventricular tachycardia). Any combination of these → hold digoxin + check level + notify provider.", weakAreaTag:"digoxin-toxicity-triad", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-03", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"What is the antidote for severe digoxin toxicity?", back:"Digoxin Immune Fab (Digibind/DigiFab). Indicated for: ventricular arrhythmias from digoxin toxicity, symptomatic bradycardia unresponsive to atropine, serum level >10–15 ng/mL, or suspected massive overdose. Not used for mild toxicity — manage with drug discontinuation and electrolyte correction.", weakAreaTag:"digoxin-antidote", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-04", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"prioritization", difficulty:1, front:"Before administering digoxin, the PN must check:", back:"1) Apical pulse for 60 full seconds. Hold if <60 bpm. 2) Serum potassium — hold if <3.5 mEq/L (hypokalemia causes toxicity). 3) Serum digoxin level (if recent). 4) Renal function (digoxin is renally cleared — reduces dose in renal failure). Document these assessments with every dose.", weakAreaTag:"digoxin-pre-administration", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-05", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"Beta-blocker antidote in overdose:", back:"IV Glucagon — physiological antidote for beta-blocker overdose. Mechanism: activates adenylyl cyclase independently of beta receptors → increases cAMP → increases HR and contractility. Also: calcium chloride/gluconate (for CCB overdose), atropine for bradycardia, transcutaneous pacing for refractory bradycardia.", weakAreaTag:"beta-blocker-antidote", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-06", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on metoprolol with Type 2 diabetes says 'I feel hypoglycemic but my heart isn't pounding like it usually does.' Why?", back:"Beta-blockers mask the sympathetic symptoms of hypoglycemia (tachycardia, tremor, palpitations). Sweating may still occur but the adrenergic warning signs are blunted. Diabetic patients on beta-blockers must rely on blood glucose monitoring rather than symptom recognition for hypoglycemia detection.", weakAreaTag:"beta-blocker-hypoglycemia-masking", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-07", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Why must beta-blockers NEVER be stopped abruptly?", back:"Abrupt discontinuation causes rebound adrenergic stimulation from receptor upregulation: severe rebound hypertension, tachycardia, angina, and potentially myocardial infarction. Beta-blockers must always be tapered gradually under medical supervision. This is one of the most tested drug discontinuation safety facts on NCLEX.", weakAreaTag:"beta-blocker-abrupt-discontinuation", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-08", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"What distinguishes the three proven beta-blockers for heart failure mortality reduction?", back:"Carvedilol, metoprolol succinate (Toprol-XL), and bisoprolol are the ONLY three beta-blockers with evidence-based mortality reduction in HFrEF. Starting dose must be low ('start low, go slow') — beta-blockers can initially worsen HF (negative inotropy) before providing long-term benefit through remodeling effects.", weakAreaTag:"hf-beta-blockers-evidence", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-09", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Calcium channel blocker classes — which one is most negatively inotropic and should be avoided in systolic HF?", back:"Verapamil — most potent negative inotrope among CCBs. Contraindicated in systolic HF (HFrEF) because it reduces myocardial contractility. Diltiazem also has negative inotropic effects. Amlodipine (dihydropyridine) has minimal cardiac effects and CAN be used in HFrEF for hypertension or angina.", weakAreaTag:"verapamil-systolic-hf", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-10", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on amlodipine 10 mg daily has bilateral ankle edema 2+. Blood pressure is 124/76. Action?", back:"Notify provider. Document the edema. Educate patient that this is an expected side effect of amlodipine (vasodilatory peripheral edema, NOT HF). BP is well-controlled. Amlodipine edema responds poorly to diuretics. Provider may accept it as tolerable or switch to another antihypertensive class.", weakAreaTag:"ccb-peripheral-edema", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-11", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"prioritization", difficulty:2, front:"A patient on diltiazem for AFib rate control has an apical pulse of 44 bpm and BP 90/58. PN action?", back:"Hold diltiazem immediately. Notify provider STAT — severe bradycardia with hypotension requires urgent assessment. Position supine (or Trendelenburg if tolerated). Monitor vital signs. Anticipate provider order for atropine, vasopressors, or transcutaneous pacing depending on response.", weakAreaTag:"diltiazem-bradycardia", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-12", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Why is verapamil combined with a beta-blocker considered dangerous?", back:"Both verapamil and beta-blockers slow heart rate and AV conduction through different mechanisms. Combined effect: additive severe bradycardia, AV block, and decreased myocardial contractility → cardiogenic shock possible. This combination is generally avoided or used only with extreme caution and cardiac monitoring.", weakAreaTag:"verapamil-beta-blocker-interaction", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-13", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"Patient teaching for carvedilol (Coreg) — what must be included about orthostatic hypotension?", back:"Carvedilol has alpha-1 blocking effects in addition to beta-blockade → significant vasodilation → orthostatic hypotension. Take with food to reduce this effect. Rise slowly from sitting or lying positions. Avoid sudden position changes, especially in the morning. Hold if SBP <90 or if symptomatic dizziness with falls.", weakAreaTag:"carvedilol-orthostatic", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-14", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:3, front:"What foods should patients taking certain calcium channel blockers avoid, and why?", back:"Grapefruit and grapefruit juice with dihydropyridine CCBs (amlodipine, nifedipine, felodipine): grapefruit inhibits CYP3A4 enzyme → reduced drug metabolism → elevated drug levels → hypotension, edema, reflex tachycardia. Patients should avoid grapefruit entirely while on these medications.", weakAreaTag:"ccb-grapefruit-interaction", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-15", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Digoxin mechanism of action (two effects):", back:"1) INOTROPIC: inhibits Na-K-ATPase pump → intracellular Ca²⁺ rises → increased cardiac contractility (positive inotropy → improves HF symptoms). 2) CHRONOTROPIC/DROMOTROPIC: slows AV node conduction → reduces ventricular rate in atrial fibrillation (negative chronotrope/dromotrope).", weakAreaTag:"digoxin-mechanism", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-16", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:3, front:"Patient on digoxin has K⁺ 2.8 mEq/L (from furosemide). What is the greatest danger, and what is the priority action?", back:"Greatest danger: digoxin toxicity → fatal ventricular arrhythmia. Hypokalemia sensitizes Na-K-ATPase to digoxin. Priority: hold digoxin AND furosemide. Notify provider immediately. Anticipate KCl replacement. Monitor cardiac rhythm (telemetry). Do NOT give either drug until K⁺ is corrected and provider re-orders.", weakAreaTag:"digoxin-hypokalemia-lethal", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-17", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the standard hold parameter for metoprolol (beta-blocker)?", back:"Apical pulse <60 bpm OR systolic BP <90 mmHg → hold and notify provider. Always measure apical pulse for a full 60 seconds before administration (not 30 seconds, not radial — apical is required for accuracy, especially with irregular rhythms like AFib).", weakAreaTag:"metoprolol-hold-parameter", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-18", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient just started on beta-blockers for HF says 'I feel more short of breath than before.' What does the PN explain?", back:"Initial worsening of HF symptoms (fluid retention, fatigue, dyspnea) is common when starting beta-blockers due to negative inotropy. This is expected and temporary — the long-term benefit is reduced mortality and remodeling. Reassure the patient; ensure they are being started on a low dose. Notify provider if symptoms are severe.", weakAreaTag:"beta-blocker-hf-initiation", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-19", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"What is the difference between metoprolol tartrate and metoprolol succinate?", back:"Metoprolol tartrate (Lopressor): short-acting, taken twice daily, used for acute rate control and post-MI. Metoprolol succinate (Toprol-XL): extended-release, taken once daily, proven mortality benefit in HFrEF. Do NOT crush or split Toprol-XL (extended-release). NCLEX may test which form is used for HF — it's succinate.", weakAreaTag:"metoprolol-formulations", studyPlanMapping:"cardiac-medications" },
{ id:"pn-cardiac-fc-20", topic:"Cardiac Medications", lessonSlug:"us-pn-cardiac-medications", exam:"NCLEX-PN", cardType:"prioritization", difficulty:3, front:"Prioritize assessment of a patient on digoxin, furosemide, and lisinopril. What is the most critical pre-medication check?", back:"Serum potassium BEFORE ANYTHING ELSE: furosemide loses K⁺; lisinopril (ACE inhibitor) retains K⁺ — these partially offset each other, but K⁺ can still be critically low. If K⁺ <3.5, hold digoxin AND furosemide and notify provider — digoxin toxicity risk is lethal. Then check apical pulse and BP.", weakAreaTag:"multi-drug-priority-check", studyPlanMapping:"cardiac-medications" },

// ═══════════════════════════════════════════════════════════════════════════
// MEDICATION ADMINISTRATION (20 cards)
// ═══════════════════════════════════════════════════════════════════════════
{ id:"pn-medadmin-fc-01", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the 6 Rights of Medication Administration?", back:"1) Right PATIENT (two identifiers), 2) Right MEDICATION (verify name), 3) Right DOSE (calculate/verify), 4) Right ROUTE (as prescribed), 5) Right TIME (within ±30 min of scheduled), 6) Right DOCUMENTATION (after administration, never before).", weakAreaTag:"six-rights", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-02", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are two acceptable patient identifiers for medication administration?", back:"Name + Date of Birth OR Name + Medical Record Number. NOT acceptable: room number, diagnosis, physician name, or appearance. Always use TWO identifiers. Scan the armband with barcode medication administration (BCMA) if available.", weakAreaTag:"patient-identifiers", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-03", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the 3-check system for medication safety?", back:"Check 1: When removing medication from storage (pyxis/drawer). Check 2: When preparing/drawing up medication. Check 3: At the bedside, just before administration to the patient. All three checks compare: drug name, dose, route, expiration. BCMA scan at bedside is the technology-assisted version of check 3.", weakAreaTag:"three-check-system", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-04", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"The PN prepares to give a medication and the barcode scanner gives an alert warning that the drug does not match the patient's record. Action?", back:"STOP. Do NOT override the alert and administer. Investigate the discrepancy before proceeding. Notify the charge nurse. Barcode medication administration (BCMA) alerts catch errors at the point of care — overriding without investigation is a leading cause of preventable harm.", weakAreaTag:"bcma-alert-response", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-05", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"Which medications should NEVER be crushed?", back:"Extended-release (ER, XR, SR, LA, XL, CD): causes dose dumping. Enteric-coated (EC, DR): removes GI protection → stomach irritation/ulcers. Sublingual tablets: changes the route (swallowed vs. sublingual). Liquid-filled capsules. Some narrow-therapeutic-index drugs with special formulation.", weakAreaTag:"no-crush-medications", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-06", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient refuses their scheduled medications. Correct PN sequence:", back:"1) Assess and document the reason for refusal. 2) Educate: explain the purpose and risks of refusing. 3) Respect the decision — do NOT coerce or force. 4) Document the refusal in the chart (specific drug, reason, education given). 5) Notify the charge RN and provider. 6) Schedule re-offer if appropriate.", weakAreaTag:"medication-refusal", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-07", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:1, front:"What ISMP dangerous abbreviations should the PN recognize and avoid in orders?", back:"'U' for units (misread as '0' or '4' → 10x overdose) → write 'units'. 'QD' for daily (misread as 'QID' → 4x dose) → write 'daily'. Leading decimal without zero (.5 mg → looks like 5 mg) → write '0.5 mg'. Trailing zero (5.0 mg → looks like 50 mg) → write '5 mg'. 'µg' for mcg → write 'mcg'.", weakAreaTag:"dangerous-abbreviations", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-08", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the ISMP high-alert medications requiring extra verification?", back:"Insulin, anticoagulants (heparin, warfarin, LMWH), opioids, concentrated electrolytes (IV KCl, hypertonic saline), chemotherapy, concentrated dextrose (>10%), neuromuscular blocking agents. Independent double-check by two nurses is required per facility policy.", weakAreaTag:"high-alert-medications", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-09", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:2, front:"PN discovers a medication error during the previous shift. The patient is currently stable. First action?", back:"1) ASSESS the patient first. 2) Notify the charge nurse and provider immediately. 3) Document accurately in the chart (what was given, time, patient's condition). 4) Complete an incident report. 5) Do NOT alter the MAR. Stable condition does NOT delay reporting. The error must be addressed whether or not harm occurred.", weakAreaTag:"medication-error-response", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-10", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the minimum onset requirement for documenting on the MAR?", back:"Document AFTER administration — never before. Pre-administration documentation is falsification of the medical record (documenting a medication was given when it hasn't been yet). If the medication ends up not being given after pre-documentation, patient harm and legal liability result.", weakAreaTag:"mar-documentation-timing", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-11", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"A patient on a pureed diet is prescribed an extended-release metoprolol capsule. What should the PN do?", back:"Do NOT crush. Notify the provider and request a different formulation: metoprolol tartrate (immediate-release) tablets can be crushed for tube feeding or pureed diet administration. Extended-release (Toprol-XL) cannot be crushed without causing dose dumping. This is a clinical judgment and scope question.", weakAreaTag:"er-tablet-alternative-form", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-12", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the required process for a verbal medication order?", back:"Read-back verification: 1) Write down the complete order as it is given. 2) Read the entire order back to the prescriber. 3) Receive verbal confirmation of accuracy. 4) Document the order with 'V.O. [prescriber name] / read back verified' + PN signature. Provider must co-sign within the time period required by facility policy.", weakAreaTag:"verbal-order-readback", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-13", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"application", difficulty:3, front:"A patient develops sudden onset hives, facial swelling, and wheezing after receiving IV penicillin. PN priority action sequence:", back:"1) Stop the infusion immediately. 2) Stay with patient. 3) Call for help (rapid response). 4) Administer epinephrine 0.3 mg IM (thigh) if severe anaphylaxis with hypotension or airway involvement — per standing order. 5) Apply O₂. 6) Position supine. 7) Monitor vital signs q5 min. 8) Notify provider. 9) Document: time, drug, symptoms, interventions.", weakAreaTag:"anaphylaxis-response", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-14", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the difference between a drug allergy and a drug intolerance/side effect?", back:"Allergy: immune-mediated reaction (urticaria, angioedema, anaphylaxis) — NEVER give the drug again. Intolerance/side effect: non-immune pharmacological reaction (nausea from codeine, headache from NSAIDs). Intolerance does not always prevent future use. The PN must document what actually happened, not just 'allergic to.'", weakAreaTag:"allergy-vs-intolerance", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-15", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"pharmacology", difficulty:2, front:"Methotrexate is prescribed for rheumatoid arthritis. The order reads '2.5 mg daily.' What should the PN recognize?", back:"RED FLAG: Methotrexate for RA is dosed WEEKLY (typically 7.5–25 mg/week), not daily. Daily dosing at RA doses causes fatal bone marrow suppression. This is a well-documented ISMP high-alert error. The PN must clarify the order with the provider before administering. Do NOT administer a daily dose without confirmation.", weakAreaTag:"methotrexate-weekly-dosing", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-16", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is medication reconciliation and when must it occur?", back:"Medication reconciliation: comparing the patient's complete medication list against new orders to identify and resolve discrepancies (omissions, duplications, interactions). Required at every transition of care: ADMISSION, TRANSFER (unit to unit), and DISCHARGE. The PN participates by accurately collecting and verifying home medication lists.", weakAreaTag:"medication-reconciliation", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-17", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"application", difficulty:2, front:"Why is sublingual nitroglycerin's burning sensation clinically significant?", back:"Burning/tingling under the tongue = nitroglycerin is POTENT. No burning = tablet may be degraded (exposed to heat, light, or moisture). SL nitroglycerin must be stored in original dark glass container, at room temperature, away from heat and light. Tablets expire once the bottle is opened (typically 3–6 months).", weakAreaTag:"sublingual-nitro-potency", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-18", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What is the PRN medication documentation requirement beyond time and dose?", back:"For PRN medications, document: 1) Drug, dose, route, time. 2) Indication (reason the PRN was given). 3) Assessment finding that triggered administration (e.g., 'pain 8/10'). 4) Patient response/effectiveness 30–60 minutes post-administration (e.g., 'pain reduced to 3/10'). All four components are required.", weakAreaTag:"prn-documentation", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-19", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"clinical-judgment", difficulty:3, front:"Two common look-alike/sound-alike medications that can cause fatal errors:", back:"1) Morphine vs. Hydromorphone: hydromorphone is ~5–7x more potent; a dose error can cause respiratory arrest. 2) Insulin (clear) vs. Heparin: both come in similar vials; drawing wrong drug causes clotting crisis or fatal hypoglycemia. Facilities use tall-man lettering: HYDROmorphone vs. morphinE to visually differentiate.", weakAreaTag:"lasa-medication-errors", studyPlanMapping:"medication-administration" },
{ id:"pn-medadmin-fc-20", topic:"Medication Administration", lessonSlug:"us-pn-medication-administration-six-rights", exam:"NCLEX-PN", cardType:"recall", difficulty:1, front:"What are the 5 'rights' of delegation as they relate to medication administration?", back:"Right TASK (medication administration is within scope for PN; only PN/RN administer medications — not UAP). Right CIRCUMSTANCE (patient stable enough for PN scope). Right PERSON (trained and competent PN). Right DIRECTION (clear order). Right SUPERVISION (charge RN oversight). NOTE: UAP/CNAs do NOT administer medications in most US states — this is always a PN/RN responsibility.", weakAreaTag:"delegation-medication-scope", studyPlanMapping:"medication-administration" },

];

export default NCLEX_PN_GAP_FLASHCARDS;
